### ISSUE TITLE
Style for represent keyboard shortcut

### ISSUE THREAD

**Issue by Xarkam** [BookStackApp/BookStack#1001]
**Describe the feature you'd like**
New format for represent keyboard shortcut

**Describe the benefits this feature would bring to BookStack users**
If you write book on programming or how to use software, is important to have a model to represent keyboard shortcuts

**Additional context**
Example of Github representation of keyboard shortcut
<kbd>shift</kbd> + <kbd>command</kbd> + <kbd>3</kbd>
<kbd>shift</kbd> + <kbd>ctrl</kbd> + <kbd>3</kbd>

**Comment by ssddanbrown** [comment]
Thank for the request @Xarkam. Unfortunately there's been no further request for this in the last ~3.5 years so I don't think it'll be worth implementing. You can use the "inline code" formatting to get a similar style where needed. Even GitHub now shows a keyboard shortcuts in the same/similar style to inline code.

Will therefore close this off.
