### ISSUE TITLE
Can't see revisions more than 50

### ISSUE THREAD

**Issue by seunghunee** [BookStackApp/BookStack#1004]
**Describe the bug**
Can't see revisions more than 50

**Steps To Reproduce**
1. Go to some page 
2. Click on 'More' and 'revisions'
3. See only 49 revisions.

**Expected behavior**
Can see all of the revisions of that page.

**Screenshots**
Revision 47~166 is disapeared.
This page always have only 49 revisions.
![image](https://user-images.githubusercontent.com/36041278/45404987-19466f80-b69c-11e8-8390-24cafd7e3453.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.19.0 
 - PHP Version: 7
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Thanks for reporting this @seunghunee.

Just to confirm, I'm pretty sure this is purposeful. Just as a prevention to over-filling the DB with revisions.
That said, Maybe we should add it as a `.env` option.

**Comment by ssddanbrown** [comment]
Closed in 3f58800ed1fca4cd274125b812aa2faadcbfd989.

As of the next release you'll simply need to add: `REVISION_LIMIT=150` to increase the current limit or set `REVISION_LIMIT=false` to disable the limit altogether.
