### ISSUE TITLE
Use common user database shared with another Laravel project

### ISSUE THREAD

**Issue by nekromoff** [BookStackApp/BookStack#1010]
**Describe the feature you'd like**
Would it be possible to use social login/user accounts shared with another Laravel project that uses default user schema? This would specially be useful for social logins.

Currently my use case is this:
I have two Laravel installs (projects) running on the same domain. If user logs in using social OAuth2 access in another project, Bookstack token is overwritten and Bookstack requires log in again. Same goes once a user log is Bookstack, then another project requires relogging in.

**Describe the benefits this feature would bring to BookStack users**
Smoother streamlined login (remembered) process.

**Additional context**
n/a

**Comment by nekromoff** [comment]
Cool, this would definitely resolve it and I understand your argument.

**Comment by ssddanbrown** [comment]
Okay, I that case I'll close this and we can await #1018 in the next release.
