### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by junlicn** [BookStackApp/BookStack#1011]
**Describe the bug**
When I submited a long article, it hint :413 Request Entity Too Large

**Comment by ssddanbrown** [comment]
Hi @junlicn,
Would be suprised to see this if just editing page content but you usually get this error when you exceed the max POST request size for your webserver. 

You can try following the instructions here to increase this limit:
https://www.bookstackapp.com/docs/admin/upload-limits/

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
