### ISSUE TITLE
Add ability to order roles listing in settings

### ISSUE THREAD

**Issue by matt-ttam** [BookStackApp/BookStack#1012]
Firstly, this is a great application. About as simple as a document/wiki system can get while still retaining all the key pieces.

Just a few small queries.
It looks like the Roles listed in Settings and when listed in custom permissions are ordered by creation date, any way to get those ordered by name? I could see it quickly getting difficult to maintain if the groups listed aren't in alphabetical order.

I have LDAP_REMOVE_FROM_GROUPS=true in the .env however, I'd like my administrator to take the "Admin" BookStack role, so I can remove the default admin. However if I don't have an "Admin" Security Group in Active Directory attached to the person, it will keep deleting that group off the BookStack user.
Could you either add an .env flag to change or change the behavior of LDAP_REMOVE_FROM_GROUPS to ignore the base groups - Admin, Editor, Viewer, Public 
These names are fine for inside BookStack, but no Active Directory structure is going to create those sort of names and attach to users, as they are too ambiguous. For example, I have an admin AD group but it's called BS-Admin and I have others like BS-User-xxx-Edit.

 - Exact BookStack Version (Found in settings): 0.23.2
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Hi @matt-ttam, Thanks for your request.
I agree a different ordering for roles would be ideal. Would be best to have multiple ordering options. 

In regards to the group sync query, with the role configuration there is a `External Authentication IDs` field. For the admin role you could set this to `BS-Admin` and that name will be used instead & the role name will be ignored. Does that solve your issue?

**Comment by matt-ttam** [comment]
Apologies for the late reply, the External Authentication IDs worked fine to solve the admin issue. Looking back it makes sense now in your docs, but ldap always seems to be a bit of trial and error to get working, but maybe that's just me.

You can close this down, unless you want to keep it open for the role order enhancement query.

**Comment by ssddanbrown** [comment]
Just came across this and realised we added [role ordering to the settings view in v22.11](https://www.bookstackapp.com/blog/bookstack-release-v22-11/#redesigned-interface-tabular-lists) and I think role ordering in the content permissions view has been a thing for a few years now, so I'll go ahead and close this off. 

Thanks again @matt-ttam for the suggestion.
