### ISSUE TITLE
Select "Application Homepage" always returns "No items available"?

### ISSUE THREAD

**Issue by tommyz4** [BookStackApp/BookStack#1014]
**Describe the bug**
I have just completed a fresh manual installation. Some new books have been added and now when I try to change the homepage to books in settings it always returns no results with the message "No items available". There are no errors in the php error log.

BookStack v0.23.2
PHP 7.0.31-1+ubuntu14.04.1+deb.sury.org+1 /nginx/1.4.6 / 5.5.61-0ubuntu0.14.04.1

root@mailsrv:~# php -m
[PHP Modules]
apc
apcu
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imap
intl
json
libxml
mbstring
mcrypt
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by ssddanbrown** [comment]
Hi @tommyz4, Sorry to hear your experiencing issues.
Can you confirm exactly where you are seeing `No items available` with a screenshot?

You may be in the view to select a page to show as a homepage. Try creating a page and see if anything appears in the same area. When setting books as the homepage you don't select a book, It is a listing of all books.

**Comment by fatihsari** [comment]
same issue also apply to me, you can show ss on attachment.

thanks for replies.

![screenshot_2018-10-13 bookstack](https://user-images.githubusercontent.com/2094683/46904781-34eaa300-cef2-11e8-94ab-dae75532f863.png)

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this.

If this issue remains please feel free to open a new issue, referencing this one.
