### ISSUE TITLE
Can't upload images due to permission error.

### ISSUE THREAD

**Issue by robindimyan** [BookStackApp/BookStack#1016]
Hello, I'm using the BookStack app on Ubuntu 16.04 server.
I'm trying to upload an image to add in a page but I get this error.
![resim](https://user-images.githubusercontent.com/11705003/45790508-da14b180-bc8d-11e8-95b4-89475e0bd9b4.png)

I went to Settings>Roles>Permissions and edited the role my user belonged to, checking appropriate permissions about image creation etc. When I save the settings the app doesn't give me any error, but when i go back to the permissions page I'm seeing that the permissions remain unchecked.

Therefore I went onto adding permissions manually from mysql, but i saw that it's not the case here and the role seems to already have appropriate permissions.
![resim](https://user-images.githubusercontent.com/11705003/45790629-5e673480-bc8e-11e8-8050-36858950f1d6.png)

Then I set the owner to www-data and granted write permissions to upload directories. The error persisted.

My next step was checking access logs of bookstack app. I saw that the uploading request to "/images/gallery/upload" returned a 403.
![resim](https://user-images.githubusercontent.com/11705003/45790928-fdd8f700-bc8f-11e8-9635-68afedf5b19e.png)

I went onto checking routes file and I saw that there wasn't an entry for that route, so I added one and set the appropriate (i think) method.
![resim](https://user-images.githubusercontent.com/11705003/45790768-214f7200-bc8f-11e8-8b59-96e417090820.png)

After this nothing changed and I'm getting the same error still. I don't know what to do at this point and I'm not sure if this is a permissions issue or sth else.

**Comment by ssddanbrown** [comment]
Hi @robindimyan,

The route does exist by default, It's just dynamic for gallery images:
![image](https://user-images.githubusercontent.com/8343178/45807483-70ab9780-bcbb-11e8-8d5a-9c4d2a145479.png)

This will be a BookStack role permission error rather than a filesystem permission error.

> When I save the settings the app doesn't give me any error, but when i go back to the permissions page I'm seeing that the permissions remain unchecked.

This is strange, Is it for all permissions or just the image create permission?

Also, What version of BookStack are you using (Found at top of settings)?
I have a faint memory of such an issue on a version a while ago.

**Comment by robindimyan** [comment]
its only permissions affiliated with image. Idk the version but i downloaded from github.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
