### ISSUE TITLE
GitLabExtendSocialite.php  failed to open stream No such file or directory

### ISSUE THREAD

**Issue by leiyu1139** [BookStackApp/BookStack#1024]
I am sorry, my english is not ok!
**Describe the bug**

**Steps To Reproduce**
When i access my website,it takes an error:
ErrorException (E_WARNING)
include(/var/www/html/BookStack/vendor/composer/../socialiteproviders/gitlab/GitLabExtendSocialite.php): failed to open stream: No such file or directory

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19724032/45927022-19c5ec80-bf5f-11e8-97d3-ef83d0079b4f.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
BookStack-0.22.0
 - PHP Version:
![image](https://user-images.githubusercontent.com/19724032/45927025-2e09e980-bf5f-11e8-8ae2-57a0be0b4231.png)

 - Hosting Method (Nginx/Apache/Docker): 
nginx

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @leiyu1139, Sorry to hear you are experiencing issues.
When did this issue occur? On upgrade or on initial install?

What happens when you run `composer install` or `php composer.phar install` from the command line in your BookStack install folder.

**Comment by leiyu1139** [comment]
when i run php composer.phar install in  BookStack install folder ,there is an error:
![image](https://user-images.githubusercontent.com/19724032/45927397-38c77d00-bf65-11e8-8395-900c4ab4c347.png)

**Comment by leiyu1139** [comment]
This site is still available a week ago, but it is not accessible today, during which I just reinstall gitlab-ce.

**Comment by leiyu1139** [comment]
thanks to help me！ @ssddanbrown

**Comment by ssddanbrown** [comment]
@leiyu1139 You may need to install composer again.

Download composer from this site:
https://getcomposer.org/download/
Follow the commands at the top of the page and you should end up with a `composer.phar` file in that directory.

Once done retry running the `php composer.phar install` command.

**Comment by leiyu1139** [comment]
OK! it works! thanks a lot! @ssddanbrown 
![image](https://user-images.githubusercontent.com/19724032/45928155-9c57a780-bf71-11e8-91cb-129847599600.png)

**Comment by ssddanbrown** [comment]
@leiyu1139 Awesome, Happy to hear things are now working!
