### ISSUE TITLE
php artisan migrate fails when migrating from V0.23

### ISSUE THREAD

**Issue by NathanVaughn** [BookStackApp/BookStack#1027]
**Describe the bug**
`php artisan migrate` fails when migrating from V0.23

**Steps To Reproduce**
1. Have Bookstack V0.23 instance setup
2. `git pull origin release && composer install && php artisan migrate`

**Expected behavior**
Migrate to complete successfully.

**Screenshots**
![capture](https://user-images.githubusercontent.com/8636459/45954310-4e26c080-bfd2-11e8-88a4-79340a73437a.JPG)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.23
 - PHP Version: 7.2.7
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Additional context**
I have had this happen on 2 different instances.

**Comment by Jekotia** [comment]
Same issue here, coming from 0.22.0.

**Comment by Jekotia** [comment]
On subsequent attempts:

![bookstack 0 24 0 migrate fail](https://user-images.githubusercontent.com/654774/45956341-3e15dd80-bfe0-11e8-9ccb-a8547af6444d.png)

And here's the copy-able text:
> [2018-09-24 13:32:27] production.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bookshelves' already exists (SQL: create table `bookshelves` (`id` int unsigned not null auto_increment primary key, `name` varchar(200) not null, `slug` varchar(200) not null, `description` text not null, `created_by` int null, `updated_by` int null, `restricted` tinyint(1) not null default '0', `image_id` int null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bookshelves' already exists (SQL: create table `bookshelves` (`id` int unsigned not null auto_increment primary key, `name` varchar(200) not null, `slug` varchar(200) not null, `description` text not null, `created_by` int null, `updated_by` int null, `restricted` tinyint(1) not null default '0', `image_id` int null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci) at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bookshelves' already exists at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bookshelves' already exists at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

> [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bookshelves' already exists (SQL: create table `bookshelves` (`id` int unsigned not null auto_increment primary key, `name` varchar(200) not null, `slug` varchar(200) not null, `description` text not null, `created_by` int null, `updated_by` int null, `restricted` tinyint(1) not null default '0', `image_id` int null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)

> [Doctrine\DBAL\Driver\PDOException]
> SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bookshelves' already exists

> [PDOException]
> SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bookshelves' already exists

**Comment by ssddanbrown** [comment]
Thanks for reporting @NathanVaughn  & @Jekotia.

Can either of you confirm MySQL versions?

**Comment by ssddanbrown** [comment]
And also, At any point, Have either of you been using MySQL 5.5 with BookStack?

Checking the engine used on the `books` table would be a big help, To see if it's InnoDB or MyISAM.

**Comment by Jekotia** [comment]
@ssddanbrown I manually applied the above commit and this is now the result when trying to migrate

> [2018-09-24 15:10:37] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null (SQL: insert into `permission_role` (`permission_id`, `role_id`) values (69, )) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null (SQL: insert into `permission_role` (`permission_id`, `role_id`) values (69, )) at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

> [Illuminate\Database\QueryException]
>SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null (SQL: insert into `permission_role` (`permission_id`, `role_id`) values (69, ))

> [Doctrine\DBAL\Driver\PDOException]
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null

> [PDOException]
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null

**Comment by ssddanbrown** [comment]
@Jekotia Yeah, Came across that also, Just debugging it now.

**Comment by ssddanbrown** [comment]
@Jekotia @NathanVaughn Okay, Just pushed out a new release. Please try again. Hopefully should be covered now. Please confirm here how the upgrade want. Apologies for this issue.

**Comment by NathanVaughn** [comment]
The new release worked perfectly for me. Thanks so much @ssddanbrown.

**Comment by ssddanbrown** [comment]
Awesome, Hopefully that covers everything. Will close this then.

**Comment by Jekotia** [comment]
Fixed here as well. Thank you for the prompt resolution!
