### ISSUE TITLE
vertical align in tables

### ISSUE THREAD

**Issue by gruessung** [BookStackApp/BookStack#1033]
Hello there,
Is it possible to vertically center the text in a table?
At the moment it looks rather strange.

![table](https://user-images.githubusercontent.com/433331/46212243-c88a7400-c335-11e8-9f59-837c9967f05b.PNG)

Greetings

**Comment by ssddanbrown** [comment]
@gruessung Sorry for the really late reply, Must have missed this one. This is currently possible, although a little long-winded:

1. Click in the cell you want to vertical align.
2. Click the dropdown on the table toolbar icon.
3. Select Cell > Cell properties. 
4. Click the V Align dropdown.
5. Select middle. 

![image](https://user-images.githubusercontent.com/8343178/57968196-389a4880-795f-11e9-93e7-973706ba90f5.png)

![image](https://user-images.githubusercontent.com/8343178/57968213-62536f80-795f-11e9-99da-3272ce9ac983.png)

**Comment by gruessung** [comment]
Thank you!
