### ISSUE TITLE
Bookshelf Titles in Breadcrumbs

### ISSUE THREAD

**Issue by Rubizzle** [BookStackApp/BookStack#1038]
**Describe the feature you'd like**
Bookshelf titles in breadcrumbs.

**Describe the benefits this feature would bring to BookStack users**
Easier navigation - moving between different books within the bookshelf instead of going through the "Shelves" link and going clicking on the books.

**Additional context**
I like having another level - I've incorporated it since the release of Bookshelves; but I find inconvenience of navigation when needing to find my book within the Shelves section again as I tend to move within the book quite frequently. I've gotten to the point where I have many books as a result of having bookshelves and would like the small feature incorporated if possible.

**Comment by aljawaid** [comment]
Possibly irrelevant, but reading this, as an idea, I just thought.... what if clicking on the bookshelf created a popup horizontal scrolling gallery so we could select a book to read.... but then that would just mess up the current way of how the bookshelves as a general are displayed.

I guess with breadcrumbs, it would have to be clear which breadcrumb is part of the bookshelf and which is part of the book.  Maybe expand the breadcrumb on hover...

Just sharing some ideas :)

**Comment by ssddanbrown** [comment]
Thanks for raising this @Rubizzle, 
I agree this would be a useful feature and thought about this myself when adding Bookshelves but it's a surprisingly complex feature to add therefore did not make it into the first bookshelves release.

**Comment by Nebucatnetzer** [comment]
I like this idea, you got my vote :).
For other people who initially might be a bit puzzled by the request:
https://en.wikipedia.org/wiki/Breadcrumb_(navigation)

**Comment by ssddanbrown** [comment]
As of the latest release this is now implemented:
https://www.bookstackapp.com/blog/beta-release-v0-26-0/#shelf-improvements

The logic can be a bit odd sometimes due to the complexity of shelf relations but it should work as expected in the majority of cases.
