### ISSUE TITLE
Editor is focusable on mobile although it's too small

### ISSUE THREAD

**Issue by moqmar** [BookStackApp/BookStack#1039]
**Describe the bug**
I cannot use the editor on my phone (or, any phone) because it's tiny due to the huge wrapping headers. As soon as I tap it to open the keyboard, it completely disappears behind it.

A workaround is to click the full screen button, but the existence of this button implies that the editor is also usable if not in full screen mode, so it's not too great from a usability perspective.

A possible solution to this problem would be automatically opening the editor in full screen mode if it's focused on a screen too small for the editor. That leaves the question if leaving the full screen mode is intuitive enough that people will find the save button - probably the "back" button on a phone (and closing the keyboard without clicking anywhere?) should also close the editor.

**Steps To Reproduce**
1. Click "Edit page" on a mobile phone (e.g. Android with Firefox)
2. Try to actually do something without going into full screen mode.

**Expected behavior**
The editor should not be focusable if it is too small.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5559994/46261890-2c5d9a00-c4fa-11e8-97ad-af4e241c425a.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.24.1
 - PHP Version: 7.1.17
 - Hosting Method (Nginx/Apache/Docker): Docker + Caddy (https://hub.docker.com/r/momar/bookstack/)

**Comment by qianmengnet** [comment]
I think you can add a "footer" that includes copyright, links, and help links, which will increase the height at the bottom of the page, and maybe help us get the editor up.

**Comment by moqmar** [comment]
Sure, that's possibly another workaround, but - in my opinion - not an acceptable solution to the problem.

**Comment by ssddanbrown** [comment]
A lot of work went into increasing mobile space efficiency and editor usability in the last release so this should now been much improved, therefore I will close this request.
