### ISSUE TITLE
Feature Request: Allow adding borders around images

### ISSUE THREAD

**Issue by stalks** [BookStackApp/BookStack#1042]
Images with a background similar to the page background would look better with a border.

Editing the HTML and adding "border='1'" has no effect currently either.

**Comment by ssddanbrown** [comment]
Hi @stalks,

If you want to add such styling to all images you can do so through the 'Custom HTML Head Content' setting.

This is what I use:

```html
<style>
    .page-content img {
        box-shadow: 0 0 36px 0 rgba(0, 0, 0, 0.1), 0px 2px 6px 0 rgba(0, 0, 0, 0.2);
        border-radius: 3px;
    }
</style>
```

You can just place that in that setting and save and all images will have a nice shadow to separate the content. Alternatively, For a border: 

```html
<style>
    .page-content img {
        border: 2px solid #DDD;
    }
</style>
```

Currently no simple UI option for singular images though.

**Comment by stalks** [comment]
@ssddanbrown This works great thanks!

**Comment by DonnaScriptTechs** [comment]
Great tip! Thanks. Still would be a nice feature similar to Confluence that has a setting for image shadow/border/style

**Comment by ssddanbrown** [comment]
@stalks Awesome, Will therefore close this request
