### ISSUE TITLE
How to make a site public?

### ISSUE THREAD

**Issue by Biepa** [BookStackApp/BookStack#1045]
Hey everyone,
maybe someone can help me with making a site public?

The Public group had all ticks on show and the guest user is in the public group.
I then ticked "show" on the specific site for the public role but if i take the link and want to open it without being logged in, i get to the login page.

What am I doing wrong?

**Comment by lithium-ap** [comment]
The public group is the default group for public registrations. I'm otherwise unsure if access is available without registration / logon. 

If it isnt, implementing OAuth with G. Suite is a fairly straightforward process.

**Comment by Biepa** [comment]
Oh ok, i thought public meant, that everybody can see it without login.
So this option isn't implented yet?

**Comment by lithium-ap** [comment]
I'm not sure, @ssddanbrown is this a function?

**Comment by TBK** [comment]
@Biepa @lithium-ap Yes it is possible, under settings enable this setting:
![image](https://user-images.githubusercontent.com/858296/46495639-40650c80-c816-11e8-94b7-246d0c4806c7.png)

**Comment by TBK** [comment]
I have not tested this but I would imagine you could set "Allow public viewing" to yes and then set the permissions level to a higher level on the content you want to "hide".

**Comment by Biepa** [comment]
@TBK Tested it, you're right. I set "Allow public viewing" to yes and the can "hide" if I dont tick "view" for the public group. 

Maybe there is a better way to implement this?
For example if we could set the "public viewing" option per book/chapter/page. This way you also don't have to overwrite all permissions for every book/chapter/page, you don't want to make viewable to the public.
Then you just have to tick it, where you want it, and not everywhere you don't want.
Or maybe there is an another, better idea.

**Comment by TBK** [comment]
One solution would be to add a new view to "Settings" where you could see and change the permissions of all content individually and in bulk.

**Comment by tpeacock19** [comment]
Another workaround was mentioned in an earlier feature request #407 the steps are as follows:

> To achieve a 'whitelist' approach for public users you can do the following:
> 1. Turn on the "Allow public viewing" setting.
> 2. Edit the 'Public' role and uncheck all permissions then save.
> 3. Go to the book you want to make visible publicly and edit the permissions via the dropdown to the right of the 'Edit' link.
> 4. Check 'Enable Custom Permissions' then set all the permissions you want, Ensuring you check the view permission for the public role.

Following the above has worked for me in that any shelf/book/chapter/page I want public.

**Comment by Biepa** [comment]
Thank you @tpeacock19 !
Still not the best way i think, but much better than the alternative.

**Comment by ssddanbrown** [comment]
Thanks everyone for providing support. Will now close this as it looks solved (Although I am aware the permissions UX needs a bit of work).

As an extra tip, You could keep all public books in a bookshelf, Then when you need to update the permissions of those, You can simply change the shelf permission and there's a button to apply the same permissions to all child books. Pages and chapters within books will then inherit those book permissions. Just a way to potentially make things more manageable by batch-setting permissions.

**Comment by srvprivate** [comment]
Here is the code necessary for hiding the Left Bar Recent Activity for unauthenticated users, the right bar "Revisions" section, but maintains Recent activity for logged in users. This took me awhile. 

```
<script>
document.addEventListener("DOMContentLoaded", function () {
    // Detect public user by checking for the "Log in" link in the header
    const isPublicUser = document.querySelector('a[href*="/login"]') !== null;

    if (isPublicUser) {
        // Hide left sidebar Recent Activity block
        const recentActivity = document.querySelector('#recent-activity');
        if (recentActivity) recentActivity.style.display = 'none';

        // Hide revision-like metadata in the right sidebar (Updated by, Created by)
        const entityMeta = document.querySelectorAll('.entity-meta-item');
        entityMeta.forEach(item => {
            const text = item.textContent.toLowerCase();
            if (text.includes('updated') || text.includes('created')) {
                item.style.display = 'none';
            }
        });

        // Hide "Revisions" links if any appear (future-proofing)
        const links = document.querySelectorAll('a[href*="/revisions"]');
        links.forEach(link => {
            link.style.display = 'none';
        });
    }
});
</script>
```
