### ISSUE TITLE
I want to contribute kr language

### ISSUE THREAD

**Issue by codev-kuk** [BookStackApp/BookStack#1046]
I would like to contribute to Korean translation. What can I do?

**Comment by TBK** [comment]
1. Fork BookStack
2. Clone the "resources/lang/en" folder
3. Rename from "en" to "kr"
4. Translate each of the files
5. Git commit & push
6. Submit PR via GitHub

**Comment by ssddanbrown** [comment]
Thanks @TBK for explaining the process.

Thanks @codev-kuk for offering to contribute translations. As an addition to the above, Ensure you do the translations in the `master` branch and create a pull request against the `master` branch.

More details are in the [project readme here](https://github.com/BookStackApp/BookStack#translations).
