### ISSUE TITLE
add an option to the /create-book page, select "Private" or "Public"

### ISSUE THREAD

**Issue by qianmengnet** [BookStackApp/BookStack#1052]
**Describe the feature you'd like**

When creating a book, add an option to the /create-book page, select "Private" or "Public". If you select "Private", the name of the book does not appear in the list and activity.
You can also add a "access by password"

**Describe the benefits this feature would bring to BookStack users**

1. Some content, before it is perfected, people don't want others to see it.

2, some content, people like to let a group of people they are familiar with, but do not want everyone to see

**Additional context**

![](https://raw.githubusercontent.com/qianmengnet/myfocus/gh-pages/QQ%E6%88%AA%E5%9B%BE20181008160313.jpg)

There is a similar Chinese website www.bookstack.cn that has these features and is easy to use.
Demo: http://demo.bookstack.cn
Username: bookstack
Password: bookstack.cn

**Comment by ssddanbrown** [comment]
Hi @qianmengnet,
Thanks for this request.

I'm hesitant to expand the upon the permissions systems already in place as they already somewhat complex. The site linked is for a fairly different use-case to BookStack.

This is essentially already open under #747 so I'll close this.

Note, Draft pages are kept private until their first full save. When creating a new page, if you only save via the save shortcut (Ctrl+S), You page won't be visible by others.
