### ISSUE TITLE
Not logged users get LDAP password information from the 404 page

### ISSUE THREAD

**Issue by Carlosongit** [BookStackApp/BookStack#1054]
**Describe the bug**
When a non allowed user tries to access an article he gets a 404 page where all the config info can be seen.

**Steps To Reproduce**
1. Share an article page to someone
2. This someone is not logged to the Bookstack and click on the link
3. He/she gets a 404 page with all the info from the server including the LDAP password

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43954188/46603125-73e3b780-caf2-11e8-9fe3-0271d5e6ca20.png)
![image](https://user-images.githubusercontent.com/43954188/46603192-a7bedd00-caf2-11e8-88b4-a8084e03a3fc.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.22.0 
 - PHP Version: PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
I would rather have a non logged user redirected to the login page.
And of course be sure that any important information is not shown.

Thank you in advance for this fabulous application and for any further help.

Carlos

**Comment by ssddanbrown** [comment]
Hi @Carlosongit,
This is only showing since debug mode is turned on.

I'd advise you disable debug mode in normal operation to avoid such scenarios.

**Comment by Carlosongit** [comment]
Dan, it sas absolutely the answer thank you.

Cheers,

Carlos Alonso Souza

**Comment by ssddanbrown** [comment]
Thanks @Carlosongit for confirming that solves this.
I've now added a warning to the debugging page in the BookStack docs to highlight this.
