### ISSUE TITLE
Images inserted in the markdown editor should be wrapped in an anchor tag leading to the original file

### ISSUE THREAD

**Issue by thomasjsn** [BookStackApp/BookStack#1062]
When inserting an image in the WYSIWYG editor a link to the original image file is added, it would be useful if the markdown editor did the same.

I'm just starting to migrate my content to BookStack, this feature would save me a lot of manual editing and copying and pasting URLs.

I've looked at the source; mind if I have a crack at implementing it? Anything special? Should a link be added even if no larger version of the image exists?

**Comment by ssddanbrown** [comment]
Now merged, To be in next minor release.
