### ISSUE TITLE
Use date/time on Exported files instead of "... ago"

### ISSUE THREAD

**Issue by Vicvinegar0** [BookStackApp/BookStack#1065]
When exporting pages, the bottom of the page shows "Created 1 day ago" and "Updated 2 hours" ago for example, and I think it makes more sense to use dates and times because the document is then static and using "ago" isn't meaningful.

**Comment by ssddanbrown** [comment]
Thanks for opening this @Vicvinegar0.

Totally agree, Suprise this hasn't been requested sooner. Marking for next release.

**Comment by JHenneberg** [comment]
hello,
talking about the bottom of the page. I would like to see an option to disable this Footer completly. Maybe I am not the only one :)

**Comment by aljawaid** [comment]
#493 [FEATURE] Header/Footer for PDF Export

**Comment by ssddanbrown** [comment]
Change applied, Will be in the next release.
Thanks again for reporting @Vicvinegar0.
