### ISSUE TITLE
increase page  content size

### ISSUE THREAD

**Issue by andreiM101** [BookStackApp/BookStack#1067]
**Describe the feature you'd like**
Set the size of the content of the page on the screen. 

**Describe the benefits this feature would bring to BookStack users**
Now on the left and right of the page content it is a very big (depend of the screen size) empty white area. On the left of the page,, until the navigation bar, is as large as the navigation bar and on the right is big enough. Having the possibility to reduce of this unused area could increase the usability for the users.
![bookstack screenshot](https://user-images.githubusercontent.com/38532244/47006031-b2562380-d13d-11e8-88ad-6ded5d02b757.jpg)
I marked with black the zones I'm refering to.

**Additional context**
If it is possible and I didn't find in the documentation please share with me.

Thanks.
Andrei

**Comment by qianmengnet** [comment]
`.page-content {
  width: 100%;
  max-width: 840px;
  margin: 0 auto;
  margin-top: 48px;
  overflow-wrap: break-word;
  }`

public/dist/style.css

840px  

moodify it

**Comment by andreiM101** [comment]
Worked like a charm.

Thanks
