### ISSUE TITLE
Table without border (Border customization)

### ISSUE THREAD

**Issue by Biepa** [BookStackApp/BookStack#1068]
**Describe the feature you'd like**
An option to make the border of a table invisible to the frontend or to customize the border in general.

**Describe the benefits this feature would bring to BookStack users**
To make sites look better and match the way you design your Bookstack pages.

**Additional context**
I would like to have content next to each other without having the borders around it.

If this is already on option then let me know.
I know about the HTML<head> section in the settings i can edit, but then the change would affect all tables, right?

**Comment by cw1998** [comment]
You can do this with cell properties. Select all cells, then choose cell properties:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1470412/48408980-8fb22d00-e732-11e8-84d2-0626fe90e625.png">

Select the advanced tab and change the style to Hidden:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1470412/48409089-dc960380-e732-11e8-8415-9d5497d0ba25.png">

**Comment by Biepa** [comment]
@cw1998 Thank you! Didn't saw that.
