### ISSUE TITLE
sometimes is not able to connect to the AD server

### ISSUE THREAD

**Issue by andreiM101** [BookStackApp/BookStack#1069]
**Describe the bug**
Sometimes I receive this error at login:
[2018-10-16 12:19:54] production.ERROR: ldap_bind(): Unable to bind to server: Can't contact LDAP server {"exception":"[object] (ErrorException(code: 0): ldap_bind(): Unable to bind to server: Can't contact LDAP server at /var/www/BookStack/app/Services/Ldap.php:93)
[stacktrace]

**Steps To Reproduce**
1. Go to login page and fulfill the login credentials
2. Click on login
3. See error: in the screenshot:
![login error](https://user-images.githubusercontent.com/38532244/47016111-7334cc00-d157-11e8-8dd2-68cd8c6c6c29.jpg)
4. If I hit F5 and resend the login details it is connecting to the AD server and log me in.

**Expected behavior**
Log me in for the first time.

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.24.1 
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Additional context**
It is not happening everytime.

**Comment by matt-ttam** [comment]
have you tried changing in .env LDAP_VERSION=false to LDAP_VERSION=3 or visa versa?
I found I the LDAP_DN value had to use the FQDN to work.
So for example if your domain is example.com and your AD connect user account is ad.connect then you put LDAP_DN=ad.connect@example.com

**Comment by andreiM101** [comment]
LDAP_VERSION is 3.
LDAP_DN was FQDN as in: CN=ad.connect,OU=Admins,OU=People,OU=EA,DC=example,DC=com
now I changed it in ad.connect@example.com as you suggest.
I'll keep an eye on it to see if the problem will be solved.

Thanks

**Comment by andreiM101** [comment]
It did the same this morning.

**Comment by matt-ttam** [comment]
I have my LDAP_VERSION set to false, maybe try that. Have you got any aggressive antivirus/intrusion detection software set on the Active Directory server? It might be seeing the repeated connections and blocking access for a time period.
Here's my settings that got it working for me on Windows Server 2016. 

LDAP_SERVER=192.168.1.10
LDAP_BASE_DN=ou=Staff,ou=SiteName,dc=example,dc=com
LDAP_DN=ldap_search@example.com
LDAP_PASS=password123
LDAP_USER_FILTER=(&(sAMAccountName=${user}))
LDAP_VERSION=false

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
