### ISSUE TITLE
Can't search IP address

### ISSUE THREAD

**Issue by adam-devapp** [BookStackApp/BookStack#1070]
**Describe the bug**
We store networking data in a wiki document, such as IPs. We can't search for IPs in documents, which is quite useful for us.

**Steps To Reproduce**
1. Go to search bar.
2. Type in IP address i.e. 192.168.1.1
3. Hit return and no results are shown

**Expected behavior**
The search should show pages which contain the IP address. Without the period character the search works.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version BookStack v0.24.1
 - PHP Version: 7.1
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**

**Comment by matt-ttam** [comment]
wrap the IP address in double quotes and it will find it eg. "192.168.1.2". I can't see the full stop character in the search filter documentation, but it might be reserved for custom searches

**Comment by ssddanbrown** [comment]
Thanks @matt-ttam for providing an answer to this.
