### ISSUE TITLE
how to put changes in a theme

### ISSUE THREAD

**Issue by andreiM101** [BookStackApp/BookStack#1074]
**Describe the feature you'd like**
I modified the page-content CSS as described in #1067. I assume that at the next update the change will be lost. 
Is it possible to save this as a theme in order to avoid being override at the next update?

**Describe the benefits this feature would bring to BookStack users**
Any change to the aspect can be saved in case of an update if it is saved as a theme.

If it is already implemented please tell how I can do it.
Thanks

**Comment by ssddanbrown** [comment]
@andreiM101 instead of modifying the styles directly you can simply add the css to the 'Custom HTML head content' setting within the admin settings area. You'll need to wrap it in style blocks like so:

```html
<style>
.page-content { max-width: 1000px; }
</style> 
```

**Comment by andreiM101** [comment]
It is working, thanks.
These 'Custom HTML' it will be carried over in an update?

**Comment by qianmengnet** [comment]
`<style>`
`.page-content { max-width: 1000px; }`
`.container.small { max-width: 1000px; }`
`</style>`

This will change the width of the chapter list to 1000px. This setting is written to the database.

**Comment by ssddanbrown** [comment]
@andreiM101 Yes, 'Custom HTML head content' will persist across updates.

Since that's solved it I'll close this issue.
