### ISSUE TITLE
Allow scrolling past end / add bottom padding to the WYSIWYG editor

### ISSUE THREAD

**Issue by lindsayschm** [BookStackApp/BookStack#1075]
**Describe the feature you'd like**
Not sure if this is a local thing but i don't think it is. When editing (and in multiple other places), the editor is stretching to the very bottom of the browser's page, which makes it harder to see the bottom of the page when in full screen. Is there any way to make it so that there's a small "footer" on the bottom of the webpages that all content ends before?

**Describe the benefits this feature would bring to BookStack users**
This feature would make it a little easier to see all the text within the scrollable section. Also, it would help from an accessibility standpoint.

**Comment by ssddanbrown** [comment]
Sorry for not responding sooner @lindsayschm, Can you confirm the editor you are using (Default WYSIWYG editor or Markdown)?

**Comment by lindsayschm** [comment]
Ah -- using WYSIWYG.

**Comment by ssddanbrown** [comment]
Thanks for raising this @lindsayschm. I've added a change in 2df82dd87024d0dc6673e9a47e56e33b257150b8 to add this padding. This will be part of the next feature release. Sorry it's taken 2 years and 4 months for the change to be made.
