### ISSUE TITLE
Indention of list, Toggle list and highlight

### ISSUE THREAD

**Issue by ckdanny** [BookStackApp/BookStack#1078]
1. Indention of list will be classified as clock block

![image](https://user-images.githubusercontent.com/11786201/47250665-281d0080-d458-11e8-8dbb-5a89ca374d6e.png)

2. Feature Request: toggle list and highlight

Some page content can be hide by toggle list and make the page much more clear. The following example is from this [library](https://facelessuser.github.io/pymdown-extensions/extensions/details/) and I think it may give us some inspiration to make bookstack much better! I really love bookstack and hope that it can get better~

Also, the callout is currently not support wrapping the code block. I checked the ticket before, the proposed workaround is not work.

```html
<c><p class="callout info"> Put the content here </p></c>
```

![image](https://user-images.githubusercontent.com/11786201/47250674-61557080-d458-11e8-81f8-e850f2f0624f.png)

**Comment by ssddanbrown** [comment]
Hi @ckdanny, Thanks for your feedback:

1. I'm pretty sure that indented blocks in markdown becoming code blocks is pretty standard. From what I can tell this does follow [commonmark](https://commonmark.org/). 

2. Collapsible content blocks are already open under issue #78. Thanks for the link as an example though.

3. I'm not sure I understand your last point. Where did you find this proposed workaround?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
