### ISSUE TITLE
Bug: Export Menu Misaligned

### ISSUE THREAD

**Issue by aljawaid** [BookStackApp/BookStack#1079]
**Describe the bug**
The export menu is misligned (`html` `pdf` `text`) as shown below:

![bookstack-export-menu-align](https://user-images.githubusercontent.com/10233708/47255035-438d0900-d462-11e8-9d1f-58bc24fed509.gif)

**Steps To Reproduce**
1. Click Export in any page

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 24.0.0
 - PHP Version: 7.0.32
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for reporting @aljawaid.

I can't see this issue on my own local development instance.
Are you using any custom CSS in your instance? Prehaps in the custom HTML head content setting?

**Comment by aljawaid** [comment]
```
<style>
body {color:#000;}
code {background-color: #292b2c; border-radius: .2rem; padding: .2rem .4rem; font-size: 90%; color: #fff;}
a[href^="tel:"]:before {
    content: "\260E";
    /*display: block;*/
    margin-right: 0.5em;
}
</style>
```
is in the **Custom HTML head content** that's it.

**Comment by aljawaid** [comment]
_Using Firefox if it helps_

**Comment by ssddanbrown** [comment]
@aljawaid Thanks, Do you see the same on the [BookStack demo site](https://demo.bookstackapp.com/login?email=admin@example.com&password=password)?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old, and since the design of BookStack has changed a fair bit since the last comment, I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
