### ISSUE TITLE
Version number in settings doesn't always show correctly

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#108]
Getting `BookStack v0.5.0-176-ge86901c` on a `v0.9.3` release :disappointed:

**Comment by ssddanbrown** [comment]
Was due to tags not being in the repo, Maybe look at creating a script to update which includes fetching tags?

**Comment by nwalke** [comment]
If you're going to package this and make it so people don't need composer, might as well keep a version file handy instead.
