### ISSUE TITLE
Feature Request: Add new DIV block type

### ISSUE THREAD

**Issue by aljawaid** [BookStackApp/BookStack#1081]
**Describe the feature you'd like**
In page edit view, add a `div` in the format menu bar or a line spacing option.  The `paragraph` block for general text is not always appropriate as the line spacing can be too much for certain text.

![image](https://user-images.githubusercontent.com/10233708/47255144-41c44500-d464-11e8-875c-001cde44caa5.png)

**Comment by ssddanbrown** [comment]
Thanks @aljawaid for your request.

Ideally I like to keep the formats functional. Adding a 'div' option may be a bit too specific, and I'm not sure how this would be described displayed in a user friendly way.

When you say "line spacing can be too much" is that in reference to the spacing of two lines within a single paragraph or the spacing between two paragraphs?

**Comment by aljawaid** [comment]
Hello @ssddanbrown  thanks for your reply.

> Adding a 'div' option may be a bit too specific, and I'm not sure how this would be described displayed in a user friendly way.
- `Unformatted Text` might be a possible way

> When you say "line spacing can be too much" is that in reference to the spacing of two lines within a single paragraph or the spacing between two paragraphs?
- In the WYSIWYG editor, when you click enter twice it translates into the source code as `<p></p><p></p>` which gives the line space too high all the time.  The code makes me belive if you press `enter` then two paragraphs are coded anyway.  At this point in html, I would have expected a `<br>` I guess.

Another way to resolve it would be to have a `line spacing` button so we can have smaller gaps between parapgraphs where the text is needed.

**Comment by aljawaid** [comment]
@ssddanbrown What do you think of a line spacing option?

**Comment by ssddanbrown** [comment]
@aljawaid To be honest, I'm not too fond of a line-spacing option. It's a bit too granular. 

Are you aware you can insert a newline, instead of a new paragraph, using `Ctrl+Enter`? Might achieve what you require.

**Comment by aljawaid** [comment]
`Ctrl+Enter` saves the page **BUT**
`Shift+Enter` inserts a new _normal_ line... thanks for that!

I think it should be mentioned somewhere though :)
