### ISSUE TITLE
10+ second response times on new install (confirmed not nginx or database)

### ISSUE THREAD

**Issue by anstosa** [BookStackApp/BookStack#1082]
**Describe the bug**
I'm getting 10 second response times on all requests on a brand new install.  I've instrumeted my firewall, the nginx in the bookstack container, and the mariadb instance and they cumulatively add 200ms to the response times. Almost all of the 10 seconds is upstream of nginx (only the bookstack app itself)

**Steps To Reproduce**
1. Go to any page

**Expected behavior**
Responds in less than a second

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.24.1
 - PHP Version: 7
 - Hosting Method (Nginx/Apache/Docker): I'm using the linxserver [bookstack](https://github.com/linuxserver/docker-bookstack) and [mariadb](https://github.com/linuxserver/docker-mariadb) containers inside a kubernetes cluster.

**Comment by ssddanbrown** [comment]
Hi @anstosa,
I've just tested a setup using those two docker containers. All seemed to work okay with sub 200ms response times (From app to browser) on my dev machine.

I think this is going to be very specific to your setup. I'm not familiar with k8s but my best guesses are that this may be down to:
1. Limited host machine resources. or:
2. Network delay between the mariadb and bookstack. If there is a significant network delay between these two ( > ~5ms) then this delay will be multiplied be a large amount as BookStack can make quite a few database calls.

**Comment by anstosa** [comment]
Bummer, I will keep digging. Thank you for trying to repro.

If I log into the bookstack container and traceroute the mariadb port it's 1 hop instantaneous.

```
root@bookstack-d7b87c4bd-bh6f9:/$ traceroute <host> -p 3306
traceroute to <host> (<ip>), 30 hops max, 46 byte packets
 1  <ip> (<ip>)  0.005 ms  0.009 ms  0.005 ms
 2  *  *  *
 3  *  *  *
```

I will turn all the debugging on in bookstack and see if I can get any hints about what the slowdown is.

**Comment by anstosa** [comment]
Any idea why I wouldn't be getting a `laravel.log` in my storage directory? The app is up and running, just slow. And I don't see how it could be a permissions issue because it has no problem writing any of the other files it's responsible for

**Comment by ssddanbrown** [comment]
@anstosa Looking at https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config it looks like the logs directory is not symlinked to the `/config` path like everything else. That's why you're not getting logs.

Yeah, those timings are strange. Would be interesting to run a direct mysql query from the bookstack container on cmd line.

**Comment by anstosa** [comment]
Okay, `nmap` is similarly delayed. There's definitely an issue on my network not related to bookstack or mariiadb. Just taking forever to establish connections for some reason.
