### ISSUE TITLE
Converting Chapters to Books and Books to Shelves

### ISSUE THREAD

**Issue by lithium-ap** [BookStackApp/BookStack#1087]
At the moment (unless I'm missing something, which is entirely possible) I can't seem to find a way to 'move up' our current structure into the new shelf organization. 

To clarify... what we are trying to do is to convert Books into Shelves so we can utilize the additional nesting structure. Is there a way to do this currently without it being a big time expense?

**Comment by Smoin1** [comment]
would be nice to have that possibility on all levels (+pages to books). This is also useful in the context of an "evolving" wiki. Something which starts small as a page, may later on become a huge book :)

**Comment by Altersoundwork** [comment]
+1 on this, this would be such a time saver!

**Comment by boonduck** [comment]
+1: This request has my vote too because this exponentially improves the usability of the core application itself.

**Comment by kdamianakis** [comment]
+1: This would be very useful as it also exists in other similar tools - allows an organisation to evolve organically with more ease (within the knowledge management domain)

**Comment by jbutlerffcb** [comment]
I just came across the need for this too.

**Comment by ssddanbrown** [comment]
Started in #3499

**Comment by ssddanbrown** [comment]
This has now been added as of #3499. 
Chapters can be converted to books, and books can be converted to shelves.
If a book is converted to a shelf, and chapters within the original book will become books themselves. 
If the book contained any direct pages, then a book of the same name will remain, with " Pages" appended to the name, to contain those pages. 

This will be part of the next feature release.
