### ISSUE TITLE
Any Page not Working

### ISSUE THREAD

**Issue by Clost** [BookStackApp/BookStack#1093]
Hello
I deployed the application it gives me error and can't load the pages.
![errorb](https://user-images.githubusercontent.com/35677277/47580891-14710e80-d91e-11e8-8e87-1fc88762a2bb.PNG)

**Comment by ssddanbrown** [comment]
Hi @Clost,
Sorry to hear you are experiencing issues.

Unfortunately I cannot know what the issue is from the information provided. There are [instructions here ](https://www.bookstackapp.com/docs/admin/debugging/) on how to turn on debugging and find issues. Can you go through those steps to get more information of the issue?

**Comment by Clost** [comment]
Hello @ssddanbrown,
Sorry for the late reply. See below the errors that I found in logs
[2018-11-07 19:54:35] production.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\Encrypter.php:43)
[stacktrace]
#0 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('SomeRandomStrin...', 'AES-256-CBC')
#1 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(749): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(631): Illuminate\\Container\\Container->build(Object(Closure))
#3 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(586): Illuminate\\Container\\Container->resolve('encrypter', Array)
#4 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(732): Illuminate\\Container\\Container->make('encrypter', Array)
#5 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(885): Illuminate\\Foundation\\Application->make('encrypter')
#6 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(813): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#7 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(780): Illuminate\\Container\\Container->resolveDependencies(Array)
#8 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(631): Illuminate\\Container\\Container->build('BookStack\\\\Http\\\\...')
#9 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(586): Illuminate\\Container\\Container->resolve('BookStack\\\\Http\\\\...', Array)
#10 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(732): Illuminate\\Container\\Container->make('BookStack\\\\Http\\\\...', Array)
#11 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(138): Illuminate\\Foundation\\Application->make('BookStack\\\\Http\\\\...')
#12 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#15 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#16 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#17 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#18 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#19 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#20 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\app\\Http\\Middleware\\TrustProxies.php(45): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): BookStack\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#39 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\public\\index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#40 C:\\wamp64\\www\\BookStack-master\\BookStack-master\\server.php(21): require_once('C:\\\\wamp64\\\\www\\\\B...')
#41 {main}
"}

**Comment by Abijeet** [comment]
Hey @Clost - 

Did you run the `php artisan key:generate` command as mentioned in the guide? https://www.bookstackapp.com/docs/admin/installation/

**Comment by gandarez** [comment]
Having the same issue here

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this. Thanks to everyone above that's provided support.

If this issue remains please feel free to open a new issue, referencing this one.

**Comment by vincentbernat** [comment]
For me, the issue is that APP_KEY should be 32-character long to be compatible with AES-256-CBC cipher.
