### ISSUE TITLE
Spontaneous exclusion of a point from navigation

### ISSUE THREAD

**Issue by Tzeenchist** [BookStackApp/BookStack#1100]
**Describe the bug**
System persistently excludes the second item from navigation. 

**Steps To Reproduce**
1. Create/edit page;
2. Add text, format: header tiny;
3. Save page;
4. The second item is not displayed.

**Expected behavior**
Changing the format does not change the result. 

**Screenshots**
![etc](https://user-images.githubusercontent.com/4430099/47814412-75aa3f00-dd6f-11e8-9007-6924a9c28350.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.24
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Additional context**
I use the RU-version, changing the language does not solve the problem. The problem is unpleasant, but not critical. Thanks for the Bookstack!

**Comment by ssddanbrown** [comment]
Thanks for reporting @Tzeenchist.

Would it be possible to share the content HTML so provide an example of where this occurs? I'm having trouble re-producing this.

To grab the HTML (If using the standard WYSIWYG editor) edit the page then click the second-to-last button in the editor toolbar to view source code.

**Comment by Tzeenchist** [comment]
Unfortunately, no, I brought down the server.

**Comment by ssddanbrown** [comment]
Okay, I'll close this issue then but I'll keep it in mind if I see anything similar. 
If anyone comes across this in future, Please open a new issue, referencing this one, and provide the page HTML that causes this to occur.
