### ISSUE TITLE
PDF Export Issue if '&' Used in Title

### ISSUE THREAD

**Issue by aljawaid** [BookStackApp/BookStack#1107]
### **Describe the bug**
I noticed I get an `An unknown error has occurred` issue without any mention in the logs.  It only causes an issues when I put the `&` in the title line.  e.g. "Categories & Packages"

**PDF Export working** if title is "Categories and Packages"
**PDF Export NOT working** if title is "Categories & Packages"

### **Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.24.0
 - PHP Version: 7.0.32
 - Hosting Method (Nginx/Apache/Docker): Apache

### **Additional context**
Not sure if it is related to #804  or even #1097

**Comment by aljawaid** [comment]
#804 #1097

**Comment by james-geiger** [comment]
@aljawaid @ssddanbrown 

I've tested this in v.28-dev with DOMPDF and WKHTMLPDF and both generate readable pdfs with ampersands in the page title.

PHP 7.3.x
Laravel Valet (nginx)

If there are no further details, I recommend closing the issue.

**Comment by ssddanbrown** [comment]
Thanks for confirming @james-geiger.

Since there's been no follow-up I'll close this off.
