### ISSUE TITLE
Prevent the user from changing their email when using OAuth

### ISSUE THREAD

**Issue by pacroy** [BookStackApp/BookStack#1115]
I'd suggest creating a new issue for your feature reqeust "Prevent the user from changing their email when using OAuth".

_Originally posted by @HitomiTenshi in https://github.com/BookStackApp/BookStack/issues/1090#issuecomment-437611881_

**Comment by ssddanbrown** [comment]
Looks like this was covered by the changes for #1542, in that only privileges users can change email addresses in the system. I'll therefore close this off.
