### ISSUE TITLE
Copy / Duplicate various things

### ISSUE THREAD

**Issue by D347HxD** [BookStackApp/BookStack#1123]
You can copy pages, which is great

But what about copying chapters? Entire books?
Roles? Mainly for permissions sake, so maybe even just a "copy custom permissions to x"

Thanks for the awesome app, love the hard work .

**Comment by tpoindessous** [comment]
Hi !

We use BootStack for sharing documentations with our clients.

We created one Bookshelve for each client. We made one template Bookshelve and it would be great to be able to duplicate this entire Bookshelve for a new client.

If you have a SQL script or a Shell script, it will still make my day 😄 

Thanks !

**Comment by p1xelshader** [comment]
Just started using BookStack and I think it's an absolutely fantastic!  I would also love to be able to create a new book by copying an existing book.  The reason being I have created book templates to ensure the structure of our books is consistent.  Keep up the great work! :)

**Comment by p1xelshader** [comment]
Dear @ssddanbrown will you consider adding this feature request to a milestone?  In the mean time, would you be so kind as to give me some pointers on which tables to insert records into?  All I really need is to copy a book which has chapters but no pages.  It will save my team a huge amount of time, as we're creating lots of books with exactly the same chapter structure.  Thanks dude!

**Comment by dgarlans** [comment]
My use case is essentially identical to tpoindessous - we are using bookstack to maintain internal documentation about our clients, and it would save us a lot of time to be able to duplicate a book and have the the entire chapter and page structure created. The chapters would be like "hardware" "software" "SLA details" "Network information" "Personnel details".

It's not too big a burden to create one book from time to time, but when we are expecting to onboard a number of clients in the near future, it would easily end up saving hours of manual labor.

**Comment by benoitclem** [comment]
Hi all,
In our organisation we also use bookstack a lot, and it's fantastic 👍. Today, as we grow, we would love to have this ability to copy entire books. Is there any plans for this feature request in a near future?
Thanks in advance.

**Comment by rassakali** [comment]
Hello,

Is there any news about this request?

**Comment by ssddanbrown** [comment]
@rassakali No

**Comment by rassakali** [comment]
Is it a planning or design issue that is blocking implementation?
How can we move this application forward? 
Is there a workarounds for copying a book?
We really need this functionality.

**Comment by ssddanbrown** [comment]
> Is it a planning or design issue that is blocking implementation?

Neither really, More a lack of desire and time. The original issue request has very wide scope which makes things more difficult also (Since it requests roles and permissions in addition to books & chapters).

>  How can we move this application forward?

The application is constantly moving forward, just not in respect to this feature.

>  Is there a workarounds for copying a book?

Not really, apart from maybe using the REST API to create a programmatic external solution.

**Comment by p1xelshader** [comment]
> Is it a planning or design issue that is blocking implementation? How can we move this application forward? Is there a workarounds for copying a book? We really need this functionality.

@rassakali If you want to help move it forward there are a few things you can do...

- Sponsor Dan (he's not getting paid to develop this!)
- Contribute to the project yourself

@ssddanbrown Thanks for your continued work, and I hope you have a nice Christmas!

**Comment by rassakali** [comment]
Thank you very much for your answers it is very friendly :)
I have just made a small donation to Dan. We are a small association with limited finances.
@ssddanbrown, Thanks for the tip on using APIs, I'll test...

Thanks to Dan and thank you all

**Comment by ssddanbrown** [comment]
Lol, Fair play for following through on that!

Just reminded myself of the page copy logic, and think it should be fairly straightforward to expand for chapters and books. 
I'll assign this to the next feature release with the following scope:

- Add copying of Books and Chapters
  - This will have an intermediate view for setting the name and parent book (for chapter copies).
  - This will copy tags.
  - This won't duplicate or re-assign attachments or images within pages.
    - Attachments will not be copied or assigned to the copied content.
    - Images will be visible in copied content but remain related to their original pages.
  - Page/Chapter/Book permissions will not be copied (At least in this initial implementation).
- Add copying of Roles
  - This will not have an intermediate screen but instead the "Copy" button on one role will take you to the existing create view but with the form pre-filled based upon the original role.
  - Permissions for that role, assigned to pages/shelves/chapters/books will not be copied (At least in this initial implementation).
 
I'd consider the above to complete this issue, with future new issues to cover any additional specific requirements.
Does that sound reasonable?

**Comment by rassakali** [comment]
Hello,
I think this is a very good and complete start, maybe add the possibility to also copy attachments and images according to a parameter. but this is not urgent.
Just to be sure, copying a book or chapter should also copy its children, whether they are chapters or pages.

**Comment by ssddanbrown** [comment]
Okay, have focused on this over the last couple of days. 
Changes in https://github.com/BookStackApp/BookStack/pull/3118/files now merged into master to be part of the next feature release (Aiming to release this month).

Since this covers everything in the original request, and in my proposal above, I'll close this off. Further copy/duplicate requests, if required, can be made in new, more specific, issues. 

@D347HxD 

>  Just to be sure, copying a book or chapter should also copy its children, whether they are chapters or pages.

Yeah, That's the case. Books and Chapter copies will copy with all child items subject to the limitations I listed in my proposal above.
