### ISSUE TITLE
save draw.io diagrams as svg and enable editing

### ISSUE THREAD

**Issue by andre-lx** [BookStackApp/BookStack#1127]
**Describe the feature you'd like**
One problem with the diagrams is that if we want to change the diagram, we cannot without recreating the diagram all over again. If you save the diagram in svg (instead of png), you can also add a button to edit the diagram (on top of the image for example). This way, if we want to edit the diagram, the diagram can be loaded automatically on the draw.io page, edited and saved again to the doc page. 

Instead of replacing the old diagram with the new one, you can put the new diagram under the old. This way it is easy to check the differences and it is up to the user to decide whether to remove the old diagram or not.

**Describe the benefits this feature would bring to BookStack users**
As explained above, this will make it possible for you to be able to edit diagrams without having to re-create a new one.

Thanks for the project :)

**Comment by ssddanbrown** [comment]
Hi @andre-lx,

Have you tried double-clicking the drawing? Or just select the drawing and press the drawing toolbar button? Should allow you to edit it.

The PNG's have the full drawing data embedded within so they can quickly be edited with ease.

**Comment by andre-lx** [comment]
I'm really sorry man. Great job.
