### ISSUE TITLE
Custom permissions do not affect book cover images

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1128]
**Describe the bug**
Book cover image viewable and even deletable by user without any custom permissions (view, edit or delete) for a book.

**Steps To Reproduce**
1. Create 2 books (Book A and Book B) and 2 users (Alice and Bob)
3. Change custom permission: Book A so only Alice can view, edit and delete Book A
4. Give Bob permission to edit Book B (through custom or default)
5. Upload book cover image with Alice to Book A and save
6. Login with Bob > Edit Book B > Go to Cover Image Selection
Result: Bob can view Alice's cover image for Book A but but not the book itself. With default permission 'delete' Bob can even delete Alice's Book cover completely.

**Expected behavior**
Book cover images uploaded to not viewable books shouldn't be viewable in the image assets selection for other book covers. The same behaviour as for images in hidden pages.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.24.2
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache2

**Comment by ssddanbrown** [comment]
Yeah, I think the image selection for books and shelves needs to be re-worked to not go through the manager, Instead directly select images.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Bolthier.

As from the implementation of #1410, Cover images are now directly selected instead of using the image manager, therefore inheriting the permissions of the books. This will be part of the next release.
