### ISSUE TITLE
Issues with formatting in WYSIWYG editor after 0.24.2 update.

### ISSUE THREAD

**Issue by brian-emery** [BookStackApp/BookStack#1139]
In many cases, formatting no longer seems to stick in the WYSIWYG editor. If I create a blank line within the editor (carriage return), it disappears after I save. If I align text to the center, it is right aligned after I save. A workaround seems to be to define a paragraph using CTRL+D before adding text (or before hitting Enter in the case of wanting a blank line).

**Comment by brian-emery** [comment]
I've been able to replicate the issue by copying text from the web and pasting it into a wiki page. Some of the formatting seems to get copied over and then it impacts the entire page. A solution seems to be copying the text to a plain-text editor first and then copying from there into the wiki. Even using the "Clear Formatting" button doesn't seem to get rid of all the formatting (specifically the issue with blank lines) when text is copied straight over from another website.

**Comment by ssddanbrown** [comment]
Thanks for proving more information @brian-emery but this latest message almost seems like a different issue to the original post.

Would you be able to provide clear steps that re-produce the issue and confirm the behaviour that you'd expect.

**Comment by ssddanbrown** [comment]
Closing due to time since last response, If the issue persists please open a new issue.
