### ISSUE TITLE
Wrap Text Issues in Table

### ISSUE THREAD

**Issue by Di2g10** [BookStackApp/BookStack#1140]
**Describe the bug**
Text doesn't wrap in table is single word with no spaces.

**Steps To Reproduce**
1. Go to `(CTM BookStack)/books/marketing/page/lead-source-tracking`

**Expected behavior**
Wrap text text to keep the table readable. based on charicter limit if no appropriate spaces are available.

**Screenshots**
![image](https://user-images.githubusercontent.com/16775406/48908536-714ede80-ee62-11e8-9f6c-32baf88e7ae1.png)

**Your Configuration:**
 - Exact BookStack Version (CTM)

**Comment by ssddanbrown** [comment]
@Di2g10 I'm guessing this in Firefox? Looks okay in chrome.

Text wrapping on the web is one of those things which is way more complicated and non-standard than it should be.

**Comment by Di2g10** [comment]
Firefox

**Comment by Abijeet** [comment]
I'll check this out.

**Comment by Abijeet** [comment]
Hey @ssddanbrown - No haven't started yet. Feel free to take a crack at it.

**Comment by ssddanbrown** [comment]
@Abijeet Cool, Thanks for confirming.

**Comment by ssddanbrown** [comment]
Interestingly this appears to be fine when I test this in Firefox 64 on ubuntu. 
The `overflow-wrap: break-word;` from the `.page-content` element takes action and breaks text as expected. Can't see any recent change in support for `overflow-wrap` either. 

Maybe need to double check on windows just in-case it's different there.
Either way, Will need a bit more investigation. Moving out a release for investigation time.

**Comment by ssddanbrown** [comment]
I believe this is now confirmed to be sorted therefore closing.
