### ISSUE TITLE
Allow scrolling down past the last line on the page

### ISSUE THREAD

**Issue by haysebeyse** [BookStackApp/BookStack#1142]
**Describe the feature you'd like**
Allow scrolling down past the last line when editing a page

**Describe the benefits this feature would bring to BookStack users**
User can move the line in which they are typing towards the middle of the screen for better focus and eye alignment as opposed to looking down to the bottom of screen while typing.

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Thanks for the suggestion.
I think this may already be open under #1075.

If this is different to that one please let me know otherwise this will soon be closed as a duplicate.

**Comment by bisherbas** [comment]
@ssddanbrown I guess that one is similiar to what I am requesting. In a nutshell, I'd like to the ability to add a line item in a long page where the new line can be moved/scrolled into the middle of screen.

**Comment by haysebeyse** [comment]
Duplicate confirmed.
