### ISSUE TITLE
Custom HTML head content does not apply on settings page

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1144]
Changes in  "Custom HTML head content" are not applied on the settings page itself, I don't know if this is intended, but then it should be mentioned. I was confused at first because my changes did not have any effect.

Using v0.24.2

**Comment by qianmengnet** [comment]
```
<style>
.page-content { max-width: 1000px; }
.container.small { max-width: 1000px; }
.title-input.page-title input[type="text"] {    max-width: 1000px;}
</style>
```

**Comment by ezzra** [comment]
Sorry, but I don't understand this comment, its not a CSS problem, its just that the content of the custom head field does not show up in the settings page sourcecode.

**Comment by ssddanbrown** [comment]
Hi @ezzra,
This is done on purpose so ensure you can revert any breaking changes. 

Would be better if we added some additional text to confirm this,  nearby the setting.

**Comment by ssddanbrown** [comment]
As of the next release, A notice will now be shown below the input to make the user aware that the setting is inactive on the settings page. Thanks for reporting @ezzra.
