### ISSUE TITLE
Unable to load bookstack when system is restarted

### ISSUE THREAD

**Issue by CMADHANKUMAR** [BookStackApp/BookStack#1150]
**Describe the bug**
 I turned of the system installed with book stack.Today i turned it on and tried to login.
Login page is loaded.After giving my login details and tried to login.But ,it shows an empty page.The page is loaded but ,no content is there.Even after restarting the apache server it shows the same empty page.

**Comment by ssddanbrown** [comment]
Hi @CMADHANKUMAR,
Can you provide any extra information?
What operating system are you on?
What method did you use to install bookstack?
Have you checked the server logs for any errors?

**Comment by CMADHANKUMAR** [comment]
I used ubuntu 18.01 os.
I used the installation script to install bootstak.
It was working fine.Yesterday i turned off the system and today turned it on.
Then it was loading a blank page.

**Comment by CMADHANKUMAR** [comment]
How to check the server logs ?

**Comment by ssddanbrown** [comment]
@CMADHANKUMAR The apache server log can usually be found at ` /var/log/apache2/error.log` on ubuntu. Try to access BookStack then check the last lines of this file to see if it shows any errors.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
