### ISSUE TITLE
Synonym or Thesaurus Search Capability

### ISSUE THREAD

**Issue by moretolearn01** [BookStackApp/BookStack#1155]
**Describe the feature you'd like**
It would be great for end users to search based on terms they are familiar with, e.g. the term store could be a synonym for outlet, customer or shop and vice-a-versa.

**Describe the benefits this feature would bring to BookStack users**
The reason for this is that the documentation would use a generic term, like outlet, but when a user searches they tend to use terms they are familiar with, e.g. store, so they would be able to find matching pages that contain outlet, even though they searched for store.
This will increase the probability of users locating the desired information.

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for the original request here, but I'm going to go ahead and close this off since there's be little additional desire for such a feature, and this is something that could be achieved via a dedicated page in the system.
