### ISSUE TITLE
Ldap import user avatar

### ISSUE THREAD

**Issue by lucassmacedo** [BookStackApp/BookStack#1161]
Import avatar users when login is from LDAP

**Comment by lucassmacedo** [comment]
any idea?

**Comment by ssddanbrown** [comment]
Hi @lucassmacedo,
Thanks for your request. 

> any idea?

This is not currently supported. I've only used LDAP in the scenario of testing BookStack if I'm honest.
What would really help such an issue is if you could provide details on how avatars are provided by your LDAP system. 

For Example:

* What LDAP system do you use?
* What attribute are avatars served on?
* What is the format of the URL provided? Absolute or relative?
* What file type are avatars provided in?
* What size(s) are avatars provided in?
* Are the answers above standard for your LDAP system?

**Comment by lucassmacedo** [comment]
What LDAP system do you use?  **Active Directory**
What attribute are avatars served on? **thumbnailphoto**
What is the format of the URL provided? Absolute or relative? **(base64_encoded)**
What file type are avatars provided in? **(base64_encoded)**
What size(s) are avatars provided in? **(200x200)**
Are the answers above standard for your LDAP system? **Yes**

**Comment by lucassmacedo** [comment]
https://github.com/Adldap2/Adldap2/blob/6853e2f277013883e900f943c5c80edb72c87a86/src/Models/User.php#L579

**Comment by ssddanbrown** [comment]
LDAP user avatar import has now been merged as per #2320. 
This will be part of the next feature release and, at the time of that release, the docs will be updated to detail usage of this option. 

Thanks again @lucassmacedo for your request.
