### ISSUE TITLE
Looking to drop Internet Explorer 11 Support, Anyone Care?

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#1164]
As part of #1153 I'm looking to drop IE11 support.

If I'm honest I never really tested on IE11 but I did consider support while developing and would have fixed any issues (If anyone raised them). 

By dropping IE11 we can just focus on browsers that actually attempt to stay up-to-date with standards. Allows good use of new CSS & JS, Should reduced JS size a bit, Perhaps even negate the need for JS transpiling. 

This is more of a warning tbh, But would be interested to know if there's anyone that values IE11 support.

**Comment by derek-shnosh** [comment]
No issues here. I only ever used IE for Cisco NMS web UIs that weren't with the times; i.e. Call Manager, Unity. But even those have evolved, so I personally have no reason to open IE.

**Comment by Subdarub** [comment]
IE11 Support doesnt really sound necessary. If your are going to drop, it would be awesome to implement a message for the user if he tries to access the site with IE. The message could read like "IE is no longer supported please change to one of the supported Browser or ask your administrator to install one of those for you."

**Comment by al-ign** [comment]
If it would still *work* on IE, I don't care (about eye-candy).

If it would break the basic functionalty - I'm against it. It means I would need to install some 3rd-party browser just to access the docs, and sometimes there is no comfortable workaround to copy-paste some code snippets from the said docs, like with vSphere VIClient or IP-KVM.

**Comment by Nebucatnetzer** [comment]
I would vote for dropping it. Nobody should be using it to surf the web anymore. Sure for internal usage it might have it's place but is BookStack then really the best tool to use? In addition doesn't IE even work out of the box on a server because of some security settings?

**Comment by therealscottcarlow** [comment]
+1 for killing support. Even Microsoft advises not to use IE for anything other than as a [compatibility tool](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732). It's not worth the technical debt of ensuring backwards-compatibility with IE IMO, drop support for it like a sack of potatoes and move on.

For those who say the alternative to IE is a 3rd party browser and that they shouldn't have to download said browser to access Bookstack, I offer two counter arguments.

- Edge is the Microsoft-supported browser moving forward, not IE. Though it technically gets updates for patching CVE's and the like, they are not bringing over modern web features to IE -- it has, from a practical point of view, reached EOL as a modern web browser, except for where it's needed for legacy enterprise applications. That's the stance Microsoft takes as well as every compliance auditor I have spoken with; don't use IE. As such, a web app like bookstack shouldn't be beholden to a legacy browser -- it just drags the application down and saddles it with technical debt.

- Microsoft themselves have _essentially_ given up on their own browser, as they are changing Edge to be based off of Chromium. So, realistically, Chromium can't really be considered 3rd party so much... Chromium with a Microsoft skin is still Chromium. I admit I am generalizing a lot here and as such it's not _technically_ the most accurate statement I could have made, but I think my overall point of "chromium/quantum/whatever are _the_ web browser technologies moving forward and that should be Bookstack's focus" is still well represented.

**Comment by ssddanbrown** [comment]
Thanks for the feedback everyone, has been very helpful. 

Seems like the overriding verdict is that nobody really cares. We can look to maybe somewhat support any critical view-only issues otherwise, as of v0.26, IE will no longer be considered.
