### ISSUE TITLE
Change default search filter

### ISSUE THREAD

**Issue by rnsvarsitybball** [BookStackApp/BookStack#1166]
Hi, how could I change the search function to search books only?

**Comment by ssddanbrown** [comment]
Hi @rnsvarsitybball,
When searching, There are options on the side to choose what type of items to search for, You can untick everything but books. Alternatively, You can include `{type:book}` as part of your search query.

There's no way to force this option on for everyone without modifying core files which is not supported.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If any questions remain please open a new issue, referencing this one.
