### ISSUE TITLE
development - npm webpack missing in package.json

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1174]
I am not very experienced with node/npm, but when setting up the development environment I had problems because webpack was missing, after installing it is now added to my package.json:

```
    "node-sass": "^4.10.0",
    "npm-install-webpack-plugin": "^4.0.5",
    "npm-run-all": "^4.1.5",
```

I assume, some developers have installed webpack globally and so don't need to install it with this project, but it should be checked/installed by composer.

**Comment by ssddanbrown** [comment]
Hi @ezzra,

I think you'd just need to run: `npm install` before running the development commands. Looks like I've made the assumption developers will know to do this so I'll update the readme with this line. Webpack will be installed locally as part of `npm install`.

**Comment by ezzra** [comment]
mh Iam not sure but its possible that I forgot it, anyways its good to have it within the guidelines
