### ISSUE TITLE
Image page display problem

### ISSUE THREAD

**Issue by neb007** [BookStackApp/BookStack#1177]
Hello,

I create many pages with images, the uplad work well but when i open my page after days  the images is not showing .
The image still in the upload folder and i can insert it again.
I have manys pages , so i don't want to do it again
Is someone have the same problem ? 

I run  BookStack v0.23.2 

![boockstack](https://user-images.githubusercontent.com/45498909/49866413-03b22480-fe08-11e8-84b7-a94f04cdc39a.PNG)

Thx

**Comment by Abijeet** [comment]
Hi @neb007 

Sorry to hear that you are having trouble.

Please share some information regarding your setup.

1. What OS? What server - Apache / PHP?
2. Have you deployed BookStack under a subdirectory? If so, please [see this page](https://www.bookstackapp.com/docs/admin/subdirectory-setup/).
3. Would it be possible for you to give the URL of the image that's appearing on the web page? What image URL actually works for you?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

Thanks @Abijeet for trying to help on this one!
