### ISSUE TITLE
Code Block, SQL: SQL commands aren't recognized

### ISSUE THREAD

**Issue by steffenmaechtel** [BookStackApp/BookStack#1181]
**Code Block, SQL: SQL commands aren't recognized by CodeMirror (javascript library) and hence, they aren't highlighted correctly.**

Example mark up:
`<span role="presentation" style="padding-right: 0.1px;">FROM fe_users u</span>`

Comparisons:

_1) CodeMirror: SQL demonstration_
https://codemirror.net/1/contrib/sql/

key word: "join"
`<span class="sql-keyword">join </span>`

_2) CodeMirror: SQL Mode for CodeMirror_
https://codemirror.net/mode/sql/

key word: FROM
`<span class="cm-keyword">FROM</span>`

**Comment by ssddanbrown** [comment]
Thanks for reporting @steffenmaechtel.

Just need to tweak the mode used. Fix will be included in the next release.
