### ISSUE TITLE
plaintext for mails is missing

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1182]
System Emails (like password reset) are sent without the plaintext part, so they are only readable in email clients with html mode. Looks like html view is also included in the plaintext part of the mail.

**Comment by ssddanbrown** [comment]
Thanks for reporting @ezzra.

Had a look into this, Appears to be a change in how mail is rendered from Laravel 5.4.
Could get this to work by switching to markdown based content, by re-publishing email & notification content and updating them to suit but it adds a lot of extra files. That said, I much preferred the old system for BookStack's use case. Might look for a way to re-implement the old system.
