### ISSUE TITLE
Login from Google redirects to private IP instead of public DNS address

### ISSUE THREAD

**Issue by justein230** [BookStackApp/BookStack#1185]
When I register a Google account, I get no error and I land on the Bookstack home page. But, when logging in with a Google account, it redirects to my internal IP address, which is inaccessible. Manually typing in my public DNS address fixes the issue (the user sees the homepage when logged in) but this is obviously not intended behavior.

Steps to reproduce:

Pre-requisites: Reverse proxy setup/app URL enabled.

1. Register a Google user
2. Log out of the account
3. Sign back in, issue should reproduce

Running PHP v7.2, Bookstack v0.24.3.

**Comment by ssddanbrown** [comment]
@justein230 Just to confirm, You have `APP_URL` set (and set only once) in the `.env` file to a URL that's not the IP? 

Did you add the private IP to your app setup in google when setting it up? Would have thought Google would not even try and redirect you back to be honest.

**Comment by justein230** [comment]
Sorry for the delay. Just checked my .env file, and `APP_URL` is only set once. In my experience, if APP_URL is not set properly, the graphics don't display right, and that is not happening at the moment. I also thought to check my Google setup, and couldn't find anything there either. All redirects are set properly.

**Comment by justein230** [comment]
Update: I was running that in a custom Docker container, and it seems that if I run it on a plain old VM it works fine... Trying to re-create solidnerd's since his is a bit difficult to work with for me. Will continue to investigate this on my own. You can close if you want, but I'm assuming there is some dependency that the app runs without but causes this strange side-effect.

**Comment by justein230** [comment]
Apologies for the increased activity on this, and thanks for all the help and suggestions. Found out it was an issue with my proxy... This fix might actually help me figure out some issues with other apps. Closing this out. Thanks!

FYI, for anyone using nginx to proxy Bookstack, add this to your `location /` directive:
`proxy_set_header Host $host;`
