### ISSUE TITLE
Select image Tooltip item exceeds the area

### ISSUE THREAD

**Issue by Xarkam** [BookStackApp/BookStack#1186]
**Describe the bug**
The title of issue describe the bug.
Edit: after more analysis, I see the tooltips cannot display the error message.
But just the token to replace by localized error message.

**Expected behavior**
See the tooltip completely

**Screenshots**
![image](https://user-images.githubusercontent.com/331816/50213467-0966b780-037e-11e9-904b-62a1df42827f.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.24.1
 - PHP Version: not applicable
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Comment by Abijeet** [comment]
Hi @Xarkam 

Thanks for reporting this. A fix for this will be in the next release.
