### ISSUE TITLE
sharing pages between books

### ISSUE THREAD

**Issue by cainotis** [BookStackApp/BookStack#1189]
make possible to the user share a page between different books, it will help because books are used to organize topics and some pages may be useful in more the one book and copping is a problem becase if someone change in one book the other will continue the way it was

**Comment by nvnvnvnvn** [comment]
You can get the page ID by highlighting text in a page and it will pop-up with the shortcut link. That link will have the page ID in it.  Then in the page you want to include that page put:

`{{@###}}` where ### is the page ID.

Caveat: If permissions don't match for user viewing it, content won't display.

**Comment by cainotis** [comment]
It can be a problem because if someone wants to edit the page, he or she will need to find the original source of it. What I was thinking was a way to have a kind of link, so if I open the same page in different books it would be the same for reading or editing

**Comment by cainotis** [comment]
It can be a problem because if someone wants to edit the page, he or she will need to find the original source of it. What I was thinking was a way to have a kind of link, so if I open the same page in different books it would be the same for reading or editing

**Comment by ssddanbrown** [comment]
Hi @cainotis ,
Thanks for opening this issue.

This has already been requested in #182 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #182 it will help show support for that request.
