### ISSUE TITLE
Google authentication - Shutdown of Google+ API on March 7, 2019

### ISSUE THREAD

**Issue by flbla** [BookStackApp/BookStack#1190]
Hello,
It's not yet a bug:
Bookstack needs Google+ API to work with Google oauth

But I got an email from Google yesterday:
>  we will be **shutting down our Google+ APIs on March 7, 2019**

![image](https://user-images.githubusercontent.com/11298399/50342173-48357280-0522-11e9-826b-b6e66a5f7659.png)

**Comment by njam3** [comment]
Looks like it needs to be migrated to the [Google Identity Platform](https://developers.google.com/identity/)

**Comment by ssddanbrown** [comment]
Looks like this is taken care of by Socialite, Might just need to use the dev version of the socialite branch or create a quick fork to keep stable. 

https://github.com/laravel/socialite/issues/317

**Comment by ssddanbrown** [comment]
Will be updated in next release.
Will need to update docs, Since it will no longer be relevant to find and add Google+ API.

**Comment by ssddanbrown** [comment]
Just to confirm, Admins should not need to do anything, From my testing I could continue to use the same API credentials with the new functionality without issue. Tested by removing the G+ API's from my API project.

**Comment by flbla** [comment]
thank you @ssddanbrown
