### ISSUE TITLE
Display Book Name in Search Results

### ISSUE THREAD

**Issue by tgrosinger** [BookStackApp/BookStack#1194]
**Describe the feature you'd like**

In search results, when a page or chapter is listed, also display the name of the containing book. This could be similar to how pages are listed in the ctrl+k link browser.

**Describe the benefits this feature would bring to BookStack users**

When multiple pages with the same name are contained in different books, it is unclear in the search results which result is desired.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion.
This is planned for the #1153 design update.

**Comment by tgrosinger** [comment]
Wonderful, thank you.

**Comment by ssddanbrown** [comment]
As of the latest release:
https://www.bookstackapp.com/blog/beta-release-v0-26-0/

This is now implemented, Both book and, if applicable, chapter will be shown for a page or chapter. 
Will therefore close this issue.
