### ISSUE TITLE
Update modal windows and dropdowns to close on esc key press

### ISSUE THREAD

**Issue by BeckerFelix** [BookStackApp/BookStack#1198]
**Describe the feature you'd like**
I'd like to be able to close and save the code block window by keystroke. E.g. _esc_ or _enter_. I love the shortcuts but as far as I see, there is no assignment for this action.

**Describe the benefits this feature would bring to BookStack users**
Simplification in workflow, no need to grab the mouse and aim for the _save code_ button.

**Comment by MilkWithCoffee** [comment]
Actually by default, windows or menus should close with _esc_. For example having dropped-down the _Formats_ selection in WYSIWYG editor, it seems natural to me to abort by _esc_ keystroke.

**Comment by ssddanbrown** [comment]
As of the next release, v0.27, you should be able to close all BookStack native dropdowns and modal windows using the escape key. Unfortunately, The WYSIWYG editor dropdowns are harder to modify so won't yet get this functionality.

**Comment by ssddanbrown** [comment]
With the update of the editor in v22.02 it looks like this has now been achieved, Will therefore close this off.
