### ISSUE TITLE
Access Copy Page function for a role that only has view only for 'All' but can create their own.

### ISSUE THREAD

**Issue by mark-james** [BookStackApp/BookStack#1199]
**Describe the bug**
If a user only has view access on a book page, the user should still be able to copy that page to a book that they do have create/update access for.

**Steps To Reproduce**
1. Create a role with Create/Update for own books/pages etc
2. Add View access to other books to the same role
3. Login as user with that role
4. Go to view only book. The 'More' menu on the right hand side is not available.

**Expected behavior**
For a view only page a user should be able to 'copy' that page to a book provided they have create/update access on at least one book.

**Screenshots**
Copy Functionality
![image](https://user-images.githubusercontent.com/26987752/50502116-e8564300-0ab0-11e9-8138-4737935c379f.png)

**Additional context**
Use Case: I have a bunch of pages that are templates. I don't want users to be able to edit them. But I do want them to be able to take a copy and then edit that copy.

**Comment by ssddanbrown** [comment]
Now implemented as of merge in #1202. To be in the next patch release.
