### ISSUE TITLE
 Generate Static HTML site from all books/chapters/pages

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#12]

**Comment by yoginth** [comment]
Close this Issue! if finished!

**Comment by ssddanbrown** [comment]
I'm going to close this off as I don't think it makes too much sense to include in the core project and there has not been a massive demand for this.
This kind of thing is better suited to external use of the API. If needed, a simplified example of this can be found here:
https://github.com/BookStackApp/api-scripts/tree/main/php-book-to-static-site
