### ISSUE TITLE
Visibility of Shelves menu item with custom permissions

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1201]
**Describe the bug**
The visibility of the Shelves menu item is dependent only on global permission of a user role. With custom permissions only set to View for the same user role the menu item doesn't show up.

**Steps To Reproduce**
1. Go to user role Public and deactivate all default permissions for Shelves.
2. Activate the View custom permission for a Shelve for user role Public.
![2](https://user-images.githubusercontent.com/42382626/50538815-16518b00-0b76-11e9-9538-63899d267903.PNG)
3. Log out and see no Shelves menu item.
![1](https://user-images.githubusercontent.com/42382626/50538820-4ac54700-0b76-11e9-9635-ad041e67bf72.PNG)

**Expected behavior**
A tab for the Shelves if you have custom permissions for View on specific shelves even without any default permissions.

Or an option in Settings or Users where you can activate or deactivate the button.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.24.2
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache2

**Additional context**
 See also: https://github.com/BookStackApp/BookStack/issues/1171#issuecomment-446378261

**Comment by ssddanbrown** [comment]
@Bolthier Good find, Thanks for reporting.

Has very similar functionality requirements as #1199.

**Comment by ssddanbrown** [comment]
Patch applied to master, Will be in the next patch release.
