### ISSUE TITLE
Show full section headings in table of contents

### ISSUE THREAD

**Issue by trwnh** [BookStackApp/BookStack#1206]
**Describe the feature you'd like**

There should be an option to use full section headings and not truncate them.

![image](https://user-images.githubusercontent.com/10606431/50748903-4d244280-1201-11e9-8b26-1257b1f18c1d.png)

**Describe the benefits this feature would bring to BookStack users**

In a proper table of contents (as can be found in real books), no entries are truncated. The purpose of the table of contents is to provide an outline of a book or document so that a reader can tell at a glance what that work contains. This cannot be done effectively when the contents are not displayed in full.

**Additional context**

I would have done this in CSS by adjusting the word wrapping and overflow options, but it seems that the truncated headings are inserted directly with scripts rather than being styled with CSS, so I can't override this with styling alone. 

![image](https://user-images.githubusercontent.com/10606431/50749027-f703cf00-1201-11e9-9c47-c7ec9937196f.png)

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @trwnh.
This is now in master, ready for the next release. Up to 100 characters will be put on the front end (Limit just in-case a parsing error occurs). 

To prevent the ellipsing, you'll be able to override the `limit-text` class.

**Comment by lifedanceman** [comment]
Hello! As I see the feature is disabled in new versions. In master branche code is absent at least. How can I manage the feature now? Are there another way to manage one?
