### ISSUE TITLE
"Toggle Details" should have a setting to be enabled/disabled/toggled

### ISSUE THREAD

**Issue by trwnh** [BookStackApp/BookStack#1207]
**Describe the feature you'd like**
I would like to not have to click "Toggle Details" in order to show snippets of text; I would prefer that these snippets are always shown. Others may prefer that snippets are always off, or that they be toggle-able. Therefore, I am proposing that a new setting be added so that the following can be done on a user and/or instance level:

- Always show snippets
- Always hide snippets
- Show a toggle button; default to open
- Show a toggle button; default to closed

**Describe the benefits this feature would bring to BookStack users**
Not having to click "Toggle Details" on every single page load. Providing more context by default and with less work. Better representing the preferences of users.

**Additional context**
![image](https://user-images.githubusercontent.com/10606431/50751219-75666e00-120e-11e9-8351-c051e18d8f76.png)

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @trwnh.

To be honest, i'd prefer not to add extra option/setting UI for something like this. Agree it would be better to have the option remember it's state.

Currently doing a UI update but this will be one to come back to afterwards.

**Comment by ssddanbrown** [comment]
As of v0.26 the "Toggle Details" button will remember it's state so will therefore close this.
