### ISSUE TITLE
Page Tags Improvements

### ISSUE THREAD

**Issue by Di2g10** [BookStackApp/BookStack#121]
Some comments on ways to improve tag implementation
- [x] Can the suggestion list populated with all previously used Tags before any text is entered so i don't have to remember what the tag values where. (apply to tag values as well)
- [x] Tag Value Suggestions are limited to values used previously only for the related tag.(Rather than any tag value used anywhere)
- [ ] The ability to apply tags at the book and chapter level. Potentially these would then auto tag pages underneath them.
- [ ] Ideally i would have liked more controls on available tags and tag values i.e. forcing tag use or linking some tags to only be available based on other tags. However this may affect easy of use.

**Comment by bridgeyuwa** [comment]
Very nice suggestion

**Comment by ssddanbrown** [comment]
Added to milestone for next release. 
Done a couple of the original points already.

For next release the focus will be just to finish off the implementation of the base tags implementation by adding to Books and Chapters. Once this is done I will close off this issue. For further changes or to re-request remaining features feel free to open new, specific issues. 

To be honest, I think the remaining features are a little too specific at this stage for the implementation/maintenance effort. Good ideas though.
