### ISSUE TITLE
Can't close the sidebar on small-width mobile view

### ISSUE THREAD

**Issue by trwnh** [BookStackApp/BookStack#1210]
**Describe the bug**
The sidebar becomes wider than the viewport when opened in certain mobile layouts.

**Steps To Reproduce**
1. Use a 320px browser width, as in iPhone 5S / SE
2. Go to any page
3. Open the sidebar
4. The sidebar is now uncloseable

**Expected behavior**
The sidebar should be closeable.

**Screenshots**
320px:
![image](https://user-images.githubusercontent.com/10606431/50810669-66e08b00-12d0-11e9-8b4e-17ad1dcca2ca.png)

360px:
![image](https://user-images.githubusercontent.com/10606431/50810677-719b2000-12d0-11e9-8a42-9f5a7cdc0f96.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.24.3
 - PHP Version: 7.3.0
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Thanks for reporting @trwnh. Currently doing a UI update which may negate this anyway but will leave this open to re-check after that's rolled out.

**Comment by ssddanbrown** [comment]
As of v0.26 the mobile view uses an entirely different view layout so this should no longer be an issue therefore I'll close this. If there remains to be an issue please open a new issue, referencing this one.
