### ISSUE TITLE
Printing in firefox is broken due to flexbox

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#1211]
**Describe the bug**
Printing in Firefox is truncated and only prints the first page of content.

The is likely due to flexbox and [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=939897).

A workaround would be to apply `display: block` to the main content elements in the print CSS.

**Steps To Reproduce**
1. Open Firefox
1. Go to any content page in Bookstack that is long enough to print on multiple pages
2. Print the page
3. Only the first page prints

**Expected behavior**
The entire document should print.

**Comment by ssddanbrown** [comment]
Thanks for reporting @abulgatz. Should be a fairly easy fix so assigned to the next patch release.

**Comment by ssddanbrown** [comment]
Fixed applied, Will be in the next release.
