### ISSUE TITLE
Feature request: Add "Print" to the "Export" list

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#1212]
**Describe the feature you'd like**
Add a **Print** link in the **Export** menu of pages that opens tab or popup with a content-only version of the current page and auto-opens the print dialogue box.

**Describe the benefits this feature would bring to BookStack users**
This is a common feature of many documentation platforms.

Some users expect a print link in web apps and don't know where to find their browser's print feature.

If the content-only print popup doesn't use flexbox for layout, it would also fix the bug I reported [here](https://github.com/BookStackApp/BookStack/issues/1211).

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @abulgatz.

I can understand the use-case of showing Print but I wonder if it makes sense being in the "export" menu. It's good that it doesn't add an extra toolbar item but if a user could not find their browser print functionality would they think to look in an "Export" menu?

**Comment by ssddanbrown** [comment]
I'm going to close this off since there's been little other desire for this feature, indicating it's likely not widely needed.
