### ISSUE TITLE
Unable to add a book to a shelf

### ISSUE THREAD

**Issue by piiq** [BookStackApp/BookStack#1213]
Hi! 

Unable to drag-n-drop a book onto a shelf.
The drop object is not rendering

I have tried doing it with the latest version of Chrome and Safari on MacOS 10.14.2

This is similar to issue #1094 
I have checked the content of public/dist and it is the same as in repository.

**Setup specification:**
Bookstack 0.24.3 running in a docker container
The app was installed from the https://github.com/BookStackApp/BookStack/archive/v0.24.3.tar.gz bundle
The app is served by Nginx

![image](https://user-images.githubusercontent.com/11668535/50958313-7549c500-14d1-11e9-8354-271ade416a13.png)

Looks like the scroll-box is only partially rendered
![image](https://user-images.githubusercontent.com/11668535/50958531-fd2fcf00-14d1-11e9-96b8-fa5641684fb1.png)

Here's the developer console network tab
![image](https://user-images.githubusercontent.com/11668535/50958650-45e78800-14d2-11e9-9813-ef424f865391.png)

**Comment by piiq** [comment]
@Abijeet @ssddanbrown You have had some ideas how to solve this issue. Please help?

**Comment by ssddanbrown** [comment]
@piiq The `public/dist/app.js` file in the compressed bundle you linked is a different size to that shown in your network tab screenshot. Please double check this file since this file controls the functionality in question.

**Comment by piiq** [comment]
@ssddanbrown thanks a lot!
Your hint really got us to understand the reasons for this.
It seems that the following happened:

We have a setup with:

- MySQL container
- BookStack container
- Nginx container

We had an older version of the app (0.15.3) running in the BookStack container previously.

We were upgrading the app version inside the container by supplying the version number as an environment variable and rebuilding the same container. This somehow caused docker to use a some sort of a cached version of the same container that had parts of the older code in it.

In order to fix it we did the following:

- stopped all containers that are required for the app to work
- delete the BookStack container
- deleted the docker images that BookStack container used
- rebuilt the BookStack container anew

After these actions the drag&drop works
🎈🎈🎈

So if someone running BookStack in a container will be reading this - take notice! When updating, don't forget to wipe out the container and images before rebuilding with a newer version.

Cheers!

**Comment by ssddanbrown** [comment]
@piiq Awesome, Happy to hear you got things working!
