### ISSUE TITLE
Missing Date Localization in Version Overview

### ISSUE THREAD

**Issue by Reflic** [BookStackApp/BookStack#1214]
**Describe the bug**
In the Overview of the versions / revisions of one article the date is shown in an locale format for US and not for the language which has been set.

**Steps To Reproduce**
1. Set language on something which is not English.
2. Create a page and some versions.
3. Go to Versions Overview.

**Expected behavior**
The date should be formatted in the locale which has been specified in the settings.

**Screenshots**
![bug](https://user-images.githubusercontent.com/1646074/51042423-90453380-15bc-11e9-9d0f-6b6688aa7e75.PNG)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.24.3
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by Reflic** [comment]
I thought of working on this bug, but after some look on the code the topic of Date and Time Localization is not considered much (Which i can fully understand...). 
The diffToHuman things are working quite good. 

But i think here is some more plan needed. (Will take another bug in order to make it my first contribution 😆 )

**Comment by ssddanbrown** [comment]
Thanks for raising @Reflic. Both date formats in your screenshot use the same library but for the format in question it looks like some extra configuration is required or some system changes are needed.

Marked to be looked into for next patch release.

**Comment by ssddanbrown** [comment]
Now implemented to be in the next release.
Will need a documentation update since the relevant locales will need to be installed on the host system.

#### For documentation update

Locales for the language will need to be installed.
For ubuntu, this can be done via the following:

```
# Select your locales
dpkg-reconfigure locales 

# Restart any php processes
sudo systemctl restart php7.2-fpm.service 
```
