### ISSUE TITLE
Bug: in markdown editor when the attachments page is open, it is impossible to select some text in the editor

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#1217]
**Describe the bug**
On macOS in latest Chrome and Firefox.

When in the split-pane markdown editor and you open the right-hand "Page Tags"/"Attachments" sidebar, it becomes impossible to select some text in the editor.

**Steps To Reproduce**
1. Configure Bookstack to use markdown editor
2. Edit a page
3. Click the page tags or attachments icon to open the right-hand sidebar
4. You are now unable to select or edit some text with the mouse or keyboard

**Expected behavior**
Opening the sidebar should not prevent editing text.

**Screenshots**
![bookstac-md-selection-bug](https://user-images.githubusercontent.com/1438193/51080331-38332d80-169f-11e9-92e8-c05b74857d65.gif)

**Your Configuration (please complete the following information):**
 - BookStack Version:  v0.24.3
 - PHP Version: 7.0.33
 - Hosting Method: Sitegrounds cPanel nginx shared hosting

**Comment by ssddanbrown** [comment]
Thanks for reporting. I believe this has since been addressed so I'll therefore close this off.
