### ISSUE TITLE
Re-open: Scrolling with longer side navigation causes rubber-banding

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1218]
Still experiencing this issue:
https://github.com/BookStackApp/BookStack/issues/905

Updated infos in comment:
https://github.com/BookStackApp/BookStack/issues/905#issuecomment-454129508

If need be, I can give a link to my Bookstack webapp environment where this issue can be experienced live.

**Comment by ssddanbrown** [comment]
@Bolthier Sorry to hear you're still experiencing this issue.

Just tried to follow your instructions on Firefox/Ubuntu but could not reproduce.
Could you confirm if you're able to reproduce this in the [demo BookStack instance](https://demo.bookstackapp.com/login?email=admin@example.com&password=password)?

**Comment by Bolthier** [comment]
@ssddanbrown Can't reproduce it in the demo with comments enabled. For testing purposes I enabled comments in my productive instance. No issues with comments enabled. With comments disabled the issue can be reproduced.

Maybe related to:
https://github.com/BookStackApp/BookStack/issues/1142
https://github.com/BookStackApp/BookStack/issues/1075

Does a general footer feature with customizable html exist or is there anything planned into this direction?

**Comment by ssddanbrown** [comment]
Prepared a fix, will be in the next release.
