### ISSUE TITLE
Unable to upload an attachment to a page

### ISSUE THREAD

**Issue by piiq** [BookStackApp/BookStack#1219]
When editing a page unable to upload an attachment using the right side panel.
The response in states that `File path uploads/files/2019-01-Jan/crqyvxf233a01.jpg could not be uploaded to. Ensure it is writable to the server.`
*I experience this only with attachments. When I upload images for book covers - everything seems to work fine.*

**Screenshots**
![image](https://user-images.githubusercontent.com/11668535/51169249-75c0d200-18bc-11e9-9fe5-1ce7460eaaaf.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: v0.24.3
 - PHP Version: 7
 - Hosting Method (Nginx/Apache/Docker): Docker, Nginx, MySQL

**Additional context**
The permissions for the uploads folder are recursively set to 0777.
The owner is:
`drwxrwxrwx 4 www-data www-data 4096 Jan  9 18:36 uploads`

**What should be the correct permissions for the attachment file to upload and save?**

**Comment by ssddanbrown** [comment]
Hi @piiq,
Sorry to hear you're experiencing issues.
By default, Attachments use a different folder to images. You may need to check that the attachments folder is writable. Folder details can be found in the[ documentation here](https://www.bookstackapp.com/docs/admin/upload-config/#local).

**Comment by piiq** [comment]
Thanks @ssddanbrown .

There was some confusion between the two folders that host uploaded data
Images stored in `<bookstack_install_dir>/public/uploads/images`
Attachment stored in: `<bookstack_install_dir>/storage/uploads/files`

After fixing folder permissions at first the page responded with a 419 status code, but after a page refresh everything is working.
