### ISSUE TITLE
Enhancement: Book Description in Book Overview

### ISSUE THREAD

**Issue by Reflic** [BookStackApp/BookStack#1222]
I find the Book Description in Books Overview Page a little misleading. 

I don't know if there are any improvements planned with the new design, but i think it would be great if we only show the description to the next "ENTER" / New Line in the Overview. This would allow to give a short sentence for the overview and don't have these points...

![image](https://user-images.githubusercontent.com/1646074/51317892-13e99f00-1a59-11e9-8330-cc8ac8779847.png)

In this case the text would end after the first sentence.

**Comment by ssddanbrown** [comment]
Thanks for raising @Reflic. 
This is a fairly old issue now regarding the old design, so it may not apply. Generally though, I'd prefer not to just cut the description at the first line but in 0ca8d7fc032ab49c75602a06829be5149d8a0e43 I've changed the approach so it will cut the text dynamically based on the container width to better fill the space. Those changes will be part of the next feature release.
