### ISSUE TITLE
LUA Language

### ISSUE THREAD

**Issue by DevKurka** [BookStackApp/BookStack#1223]
**Describe the feature you'd like**
I'd really appreciated if more code languages (such as Lua which is important for me) could be released.

**Describe the benefits this feature would bring to BookStack users**
I think that there are so much people using languages others than these already setupped.

**Additional context**
I think that it wont be hard adding more if framework already exists.

Thanks for help!

**Comment by Mant1kor** [comment]
Does markdown-editor not support lua?

**Comment by DevKurka** [comment]
Not for me at least. I've updated to the latest version anyways

**Comment by ssddanbrown** [comment]
[Codemirror supports lua](https://codemirror.net/mode/lua/index.html), So support could easily be added, but it might be best to evaluate the cost of including loads of different languages, and perhaps look at different ways of loading them if required.

**Comment by DevKurka** [comment]
I tried to add it on my own but it failed at the end so.

**Comment by DevKurka** [comment]
@ssddanbrown Any tips about loading them manually or information if this can be worked on?

**Comment by ssddanbrown** [comment]
This has now been added, Will be in the next patch release.

**Comment by DevKurka** [comment]
Hey any clue when it will be released?

**Comment by DevKurka** [comment]
@ssddanbrown Hey! Thanks. Any clue when the patch release will be on?

**Comment by ssddanbrown** [comment]
@DevKurka I have a rough target of next weekend as a target for the patch release. No guarantees though.

**Comment by DevKurka** [comment]
@ssdanbrown Is there any way to get one installed before the release?

**Comment by DevKurka** [comment]
@ssddannbrown Is there any way to get it installed before it's released?

**Comment by Nico207** [comment]
I made the same changes as the commit e471d0c 
Adding a block of Lua code does nothing more, the text remains blank.
![image](https://user-images.githubusercontent.com/1179972/53969223-b2f55380-40f8-11e9-973d-11fc7404f1c0.png)


Should I do something more.

_I tried on other languages, with the same result (white text)_

**Comment by DevKurka** [comment]
@Nico207 Can reproduce. Had the same issue and that's the only one reason why I am waiting for the update.

**Comment by DevKurka** [comment]
@ssddanbrown Any tip for that?

**Comment by ssddanbrown** [comment]
@Nico207 @DevKurka Changes the JS files have to be built via node (Details in the readme).

If you don't want to do that but really need this, Here's a zip of the built JS from the current master branch. Can can try extracting the contained file out to `public/dist/app.js`. Can't guarantee stability though since this is from a development branch.
[app.zip](https://github.com/BookStackApp/BookStack/files/2943555/app.zip)

Otherwise, Will just have to wait for the release. 

Changing the files in the commit, or following the above, is not really supported and can cause conflicts on updating BookStack.

**Comment by Nico207** [comment]
Thanks for the zip file.
In my case, I don't really need the Lua language. My goal was mainly to understand how to activate other languages (in my case, VB and Pascal), and see if it was simple.
