### ISSUE TITLE
Update shortcut used for markdown drawing manager to be cross-platform

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#1228]
Is there any way to delete a draw.io drawing?

Maybe they can appear in the list of images or attachments on a page?

I also recommend a draw.io page in the documentation that explains how to edit a drawing by double-clicking on it in the wysiwyg editor or the markdown preview.

**Comment by ssddanbrown** [comment]
Hi @abulgatz,

There is a drawing manager which can be accessed in the WYSIWYG editor by clicking here:

![image](https://user-images.githubusercontent.com/8343178/51424835-60ed8280-1bcb-11e9-9554-aba90ab2f62f.png)

In the markdown editor I think it can be accessed by Ctrl+Clicking the "Insert drawing" link.

**Comment by abulgatz** [comment]
Thanks, "<kbd>Ctrl</kbd> + Click" drawing manager works, but only on Windows.

On a Mac, "<kbd>Ctrl</kbd> + Click" is interpreted by the OS as a right click and so doesn't work.

Can a different modifier key be used, either for all OS's, or recognize a mac and change to "<kbd>Command</kbd> + Click" just on the Mac?

**Comment by abulgatz** [comment]
in `/resources/assets/js/components/markdown-editor.js` line 63, changing:

~~~
if (action === 'insertDrawing' && event.ctrlKey) {
~~~

to

~~~
if (action === 'insertDrawing' && (event.ctrlKey || event.metaKey)) {
~~~

Should allow "<kbd>Command</kbd> + Click" to function on a Mac.
