### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by jacksonp2008** [BookStackApp/BookStack#1233]
**Describe the feature you'd like**
I have a confluence system we would like to import into Boostack.

**Describe the benefits this feature would bring to BookStack users**
Help me eliminate confluence.

**Additional context**
thanks

**Comment by Abijeet** [comment]
Hey @jacksonp2008 

System Import/Export has already been requested under a range of issues therefore I'm going to close this issue. Please add your thoughts to #43 and mention that you'd like to have import from Confluence.
