### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by gerroon** [BookStackApp/BookStack#1234]
Hi

Can you please add a default dark theme to BS. I find the default white theme to be super overwhelming, so I actually avoid using BS myself. If there was a dark theme installed I would definetely go for it.

This brings me a question about Docker install. How can I add a dark theme to the docker install? Like this one https://github.com/domainzero/bookstack-dark-theme

**Comment by tomaskir** [comment]
Please make a dark theme happen! :)

**Comment by antimatteraccord** [comment]
Another vote for dark mode!!
Please make this a simple button click in the UI.  That would help so much!

**Comment by kaleben0** [comment]
Not sure if anyone mentioned this, but this guy made a Dark Theme CSS for Bookstack - https://github.com/domainzero/bookstack-dark-theme

**Comment by Chrismettal** [comment]
+1 for dark mode.

**Comment by ssddanbrown** [comment]
A user-selectable dark mode has been implemented under #2022. This will be accessible via the top-right header dropdown menu (Under logout). This will be part of the next feature release, v0.29. 

A massive thanks to @domainzero for providing & maintaining a dark mode option for users over the last three years :1st_place_medal:

**Comment by ThorsenRune** [comment]
It appears to me that this does not apply to guest visitors. How can that be enabled for the guest account?

**Comment by ssddanbrown** [comment]
@ThorsenRune Being able to set the default state has been addressed already in #2081 and will be part of the next feature release: https://github.com/BookStackApp/BookStack/issues/2081#issuecomment-774786429
