### ISSUE TITLE
No overview when startpage is not default

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1236]
The default startpage is an overview with recent changes, your own last visits etc. When the startpage is changed to a specific page for example, you cannot access this overview page. I would like to have the possibility to use this overview page, even when the startpage is changed.

**Comment by ssddanbrown** [comment]
Thanks for the request but I'm going to close this off since there's been little other desire for this.
We do generally attempt to still shown the default homepage dash items on custom homepage, they are just shown in the sidebar instead of being laid in multiple columns.
