### ISSUE TITLE
Add custom formats to editor

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1241]
I don't know if this is already possible, but I would like to use custom formats in the editor.

![screenshot_2019-01-28_13-02-20](https://user-images.githubusercontent.com/37742522/51835209-f93ae400-22fc-11e9-8fa6-fbeb00d22acc.png)

For example something `fancy blinking stuff` or whatever the admins want to set up for their users.

**Comment by SomoIT** [comment]
Im also interested in this feature. Did you succeded in adding a new format?

**Comment by Pyselcongor** [comment]
It would be great to be able to add custom format or to be able to at least modify the default ones (font color, underlined etc...)

**Comment by ssddanbrown** [comment]
I'm going to close this off as it's not something I'd be looking to support directly in the core project, especially with the somewhat minimal demand. 

My work in https://github.com/BookStackApp/BookStack/issues/2738#issuecomment-1022683101 has enforced the idea for me that we need to stick to a standard format to ensure maintainability and portability of content. That said I will still aim to expose points of extension where feasible to allow customizations to those that really desire/need it, they just won't be so adverse to being impacted by updates/changes.

For example, the Custom HTML head can be used to style some existing formats as shown above.
The WYSIWYG editor config can be tweaked via some events we emit as shown here:
https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events
(Note, These events will likely change soon as we change up the editor).
