### ISSUE TITLE
admin preferences log

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1243]
Changes of preferences in admin area should be logged, so all changes can be tracked when there are multiple admins. It could also be possible to add changeset comments.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @ezzra.

I have now developed the new audit log functionality to include the following additional admin-focused events:

```
settings_update
maintenance_action_run 

recycle_bin_empty  
recycle_bin_restore
recycle_bin_destroy

user_create
user_update
user_delete

api_token_create   
api_token_update   
api_token_delete   

role_create
role_update
role_delete

auth_password_reset_request
auth_password_reset_update 
auth_login 
auth_register  
```

High level detail of each is generally tracked (To trace where the changes have occurred at a high-level).
This will be part of v0.31.
I will therefore close this off.
