### ISSUE TITLE
Convert Dokuwiki Docker to BookStack

### ISSUE THREAD

**Issue by hammermannman** [BookStackApp/BookStack#1244]
Hi,

is it possible to convert a existing DokuWiki to BookStack ?

**Comment by ezzra** [comment]
I guess it is possible, but someone would need to write a converter script. There will be several problem with format styles, page permissions, folder structures etc. But its possible to do.

**Comment by thoni56** [comment]
Here are some links to information that could be a start. Haven't looked into them myself (you would need to use a translator to understand the blog post...):

- https://github.com/BookStackApp/BookStack/issues/974
- https://blog.phoenixlzx.com/2018/03/23/migrate-dokuwiki-to-bookstack/
- https://github.com/phoenixlzx/dokuwiki-exporter

**Comment by ssddanbrown** [comment]
I'm going to close this off since I see the support of other platform formats as out of scope of the core project but we now have a more established API which could be utilised to help these kind of operations.
