### ISSUE TITLE
Handling recent activity

### ISSUE THREAD

**Issue by quentinDupont** [BookStackApp/BookStack#1250]
Hello and thanks for this amazing free software !
It's my first days with this software so i'm sorry in advance if i don't understand how it all works :slightly_smiling_face: 

**My issue**
While trying to add a custom CSS on recent activity on sidebar - with id=recent-activity, it doesn't apply on every pages.
And it seems that the sidebar is not managed the same way in home page than in book page for example.

In my home-page, it uses **views/common/home-sidebar.blade.php**
 (thanks to sidebar-layout.blade.php if I understand well) and in the book page, it uses **views/book/show.blade.php**.

In views/common/home-sidebar.blade.php it's set with **\<div id="recently-updated-pages">** and in show.blade.php, the activity is set with **\<div class="activity card">**.

Should i just need to customized more my CSS ?

Thanks in advance for your explanation :slightly_smiling_face:

**Comment by ssddanbrown** [comment]
Hi @quentinDupont,

> Should i just need to customized more my CSS ?

Yeah, for now you'll need to customize your CSS. There is an upcoming design update in where I'm looking to standardise the code structure a little more but for now, some customization is required.

If you need help coming up with selectors, I've recently created [select.style](https://select.style/) to help identify CSS selectors :smile:

**Comment by ezzra** [comment]
> If you need help coming up with selectors, I've recently created select.style to help identify CSS selectors

what is select.style?

@quentinDupont sometime you might need to set `!important` within your  css statement to make it working

**Comment by quentinDupont** [comment]
Thanks for your answers and for the news about the upcoming design !

Niice tools, thanks again !

**Comment by ssddanbrown** [comment]
Since this was answered I'll close this issue.
