### ISSUE TITLE
Add ability to save/insert custom text snippets

### ISSUE THREAD

**Issue by Nebucatnetzer** [BookStackApp/BookStack#1252]
**Describe the feature you'd like**
An option where one could configure text snippets and then later add them from the toolbar in the WYSIWYG editor.
One such example would be page breaks.
Another way to go about this would be text expansion. For example one would write _pagebreak and it inserts the relevant snippet.

**Describe the benefits this feature would bring to BookStack users**
It would save time and make it easier to insert komplex and/or repetitive text blocks.

**Comment by ssddanbrown** [comment]
Thanks for this request.
I feel most use-cases for such as system are now covered by the page templating system, added latter in 2019.
I'm therefore going to close this off.
