### ISSUE TITLE
extend breadcrump bar to show always the full navigation path

### ISSUE THREAD

**Issue by JHenneberg** [BookStackApp/BookStack#1254]
**Describe the feature you'd like**
Under the logo in bookstack there is a small navigation (class breadcrumps) bar which is showing the "path" to your book or article. You click for example on a book and there will be shown the shelve where its laying in
```
myShelve
```
You click on an chapter in a book and the book is shown there but the shelve not anymore. It would be a nice feature if it would always show the full path and in addition that you can go back to the overview of shelves or book in general, like it is possible with the two buttons on the top right corner
```
Shelves -> myShelve -> myBook -> myChapter
```

**Describe the benefits this feature would bring to BookStack users**
The "path" always shows the full level of depth and is not "hiding" any information. To go even down to the top level similar to the buttons on the top right would make sure that the navigation is not split into to areas. This would eliminate the confustion if I want to go back from my chapter to my book I need to use the navigation on the breadcrump bar and if i need to go back to the overview of my book I need to use the button on the top right.

Thanks for the great work so far.

**Comment by ssddanbrown** [comment]
Related to #1038.

Thanks for the suggestion @JHenneberg.
Talk of showing shelves is in #1038.

Showing the top-level shelves or books view might be a little tricky as we'd need to track where the user came from. Not impossible though. The more tricky part here might just be the design issue of fitting everything in since you could have `Shelves > Shelf > Book > Chapter > Page > Revisions`.

**Comment by JHenneberg** [comment]
thanks for your reply.

The design issue could be approached similar to the mobile version, which shows only symbols to a certain level or when a certain length is reached.

In #1038 you mention that you were thinking about smth similar. You had the time yet to think about this? I see a lot of Issues. Is there anyway to find out on which feature, bug someone is working right now and if there is any priority? The milestones are unfortunately only used one subversion ahead. I wish I could participate in this project but not beeing a webdeveloper its quite hard. Keep up the good work.

**Comment by JHenneberg** [comment]
this issues is solved in my opinion with v 0.26.0
