### ISSUE TITLE
question: change timezone in config/app.php?

### ISSUE THREAD

**Issue by jeyca** [BookStackApp/BookStack#1256]
I am not sure, if I should change 'timezone' in `config/app.php` to my local timezone? How is it actually used?

**Comment by ssddanbrown** [comment]
Hi @jeyca,

Really, You should not edit any of the files in `config/`, Only make config changes via the `.env` file.
The timezone config item you have found is not actually shown often, Most dates shown to the user are in a relative format.

**Comment by TBK** [comment]
If you have access to the php.ini file you can set the timezone - http://php.net/manual/en/datetime.configuration.php#ini.date.timezone

**Comment by ssddanbrown** [comment]
Will now close this since question was answered and no further response was requested.
