### ISSUE TITLE
Rebuild front-end translation system

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#1258]
Just putting this as a reminder to myself really.

Need to cleanup front-end translation system (`/translations` endpoint).
It's a badly-done system, inefficient system.

Instead only the translations used should land in the browser. Insert those via standard tags then parse out with standard JS. Translations could be defined near where but have [blade stacks](https://laravel.com/docs/5.5/blade#stacks) gather these into a common location.

**Comment by ezzra** [comment]
> Instead only the translations used should land in the browser.

I dont understand that very well, isn't that the case already? The textes are translated in backend when the html file is generated, arent they?

**Comment by ssddanbrown** [comment]
@ezzra Yeah, This is more for translation used inside of JavaScript components which is handled on the front-end, differently to the majority of the translations which are inserted within the back-end blade files.

**Comment by ezzra** [comment]
Ah ok, I totally missed the _front-end_ and was confused :)
