### ISSUE TITLE
Add a "Create Book" button to the shelves.

### ISSUE THREAD

**Issue by Nebucatnetzer** [BookStackApp/BookStack#1260]
**Describe the feature you'd like**
A button which would allow to create a new book in the current bookshelf.

**Describe the benefits this feature would bring to BookStack users**
It would make it easier to create a book which would belong to a shelf right from the start.
At the moment I have to:
1. Create a book.
2. Go to the bookshelf.
3. Edit the bookshelf.
4. Move the book into the shelf.
5. Open the book.
6. Create content.

With the button I could:
1. Go to the shelf.
2. Create the book.
3. Create content.

**Additional context**
Books and chapters already work this way. Therefore it would be quite logical if the highest element in the structure would work the same way.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion.

This was mentioned in #1171 but is good to have this issue open as it is a separate requirement to that issue. Might possibly look at implementing this as part of #1153.

**Comment by ssddanbrown** [comment]
Thanks to @cw1998, This feature is now in master and will be in the next release. Therefore I'll close this request.

**Comment by Nebucatnetzer** [comment]
Nice, thank you @cw1998!
