### ISSUE TITLE
Unify "sign up with slack" and "log in with slack".

### ISSUE THREAD

**Issue by timeandtimeago** [BookStackApp/BookStack#1262]
**Describe the feature you'd like**
When a user tries to log in with slack and does not have an account - they should be prompted to make an account with slack - or at least given the option.

**Describe the benefits this feature would bring to BookStack users**
This will help reduce confusion

**Additional context**
My organization has the issue where people expect to simply be able to log in with slack and when it does not work they get confused. Most "log in with social" features do not require you to "register with it" first. 

It would be extremely helpful if the user would be prompted to sign up with slack if they try to log in with slack and that slack account has not been signed up yet.

**Comment by ssddanbrown** [comment]
Hi @timeandtimeago,

Thanks for the suggestion, I think what you're after might already be in BookStack but just requires a small configuration change. Third-party auth methods have ["Auto Register" options available](https://www.bookstackapp.com/docs/admin/third-party-auth/#automatic-registration-email-confirmation).

I think, by adding the below to your `.env` option you will achieve your ideal functionality:
```
SLACK_AUTO_REGISTER=true
```

**Comment by ssddanbrown** [comment]
Since it's been a few weeks since last response I'm going to close this but feel free to open a new issue if the above does not meet your needs in some way.
