### ISSUE TITLE
Tagging of users in comments

### ISSUE THREAD

**Issue by abbeyjackson** [BookStackApp/BookStack#1266]
This is a suggestion added to issues as per Dan’s instructions via Twitter.

Currently people can leave comments and you cam see them in the activity list but if you have a large team or someone is leaving a lot of comments things will be missed. In a large team that activity tab will be iseless as people will not be able to easily see comments relevant to themselves. For a personal wiki or to be used purely as documentation Bookstack is great! But without tagging it can not be a Confluence replacement because collaboration is difficult. You need to email people with your comments or with a link to the page that has comments on it.

**Comment by ezzra** [comment]
This should also be part of a notification system that is discussed in https://github.com/BookStackApp/BookStack/issues/147

**Comment by ssddanbrown** [comment]
Thanks for your suggestion here @abbeyjackson (And sorry for my very late response).

I'm going to close this in favour of the earlier, more general issue #560 since that would achieve this same as this one.
