### ISSUE TITLE
Shortcut for bullet points and numbered lists

### ISSUE THREAD

**Issue by lmeerwood** [BookStackApp/BookStack#1269]
**Describe the feature you'd like**
A shortcut key to add bullet points or numbered lists so they can be added without using the mouse to select it from the menu

**Describe the benefits this feature would bring to BookStack users**
This would increase the speed at which someone would be able to write notes when bullet lists or numbered lists are commonly used.

**Additional context**
I go between bullet points and paragraph writing a lot. Nearly every other formatting item can be done via a short cut key, but bullet lists and numbered lists both require using the mouse to activate them. Would it be possible to have shortcut keys added for them?

**Comment by micw** [comment]
An alternative to shortcut would be to register "star + whitespace + character" at beginning of a line and auto-convert it to a bullet. That's a common pattern available in many other editors. Once in "bullet mode", more/nested bullets can already be added using keyboard only.

**Comment by deanord** [comment]
99% of the time, this is the only reason I have to reach for my mouse when working on a page.  @micw suggestion would be spot on, and agree that this is how most editors work.

**Comment by deanord** [comment]
Thank you Dan, this works great!

**Comment by ssddanbrown** [comment]
List shortcuts now added in #3599, To be part of the next feature release.
