### ISSUE TITLE
Only allow a certain social auth instead of traditional email login

### ISSUE THREAD

**Issue by aditya-aggarwal-1** [BookStackApp/BookStack#1271]
If using in a business setting over the public internet, it would be beneficial to only allow a certain Social Login option, and not show the default Email/password login.

**Describe the benefits this feature would bring to BookStack users**
Use-case examples would include the following use case:
I work in a start-up where we use Bookstack for our documentation purposes to share data between business as well as engineering teams. Since we do not use an LDAP, and mostly rely on Google Auth, it would be one less effort for my ops-team to ensure that the user doesn't have an account left Active on Bookstack after he/she leaves the organization. As we deactive their Google Login, it would deactive their access altogether. This is somewhat difficult to control in the current system, since we do not know if a user registered using Google or basic sign up.

Simply being able to set auth method to "google" or "socialite" may help.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @aditya-aggarwal-1.

This seems very similar to #1090. If there are differences to your request please let me know otherwise I'll soon close this issue as a duplicate.

**Comment by the-cybersapien** [comment]
@ssddanbrown yes, it's the same as #1090. Weird that when I searched the issues to find something like this, I didn't get this issue in the list. Wrong keywords I guess.
Please feel free to close this as a duplicate.

**Comment by ssddanbrown** [comment]
Thanks for confirming!
