### ISSUE TITLE
Optionally Export pdf without revision and author information

### ISSUE THREAD

**Issue by mark-james** [BookStackApp/BookStack#1276]
**Describe the feature you'd like**
When exporting a page as a pdf have a modal that allows the user to exclude revision and author information from the pdf.

**Describe the benefits this feature would bring to BookStack users**
When pages are used as either templates or presentation collateral to be used by a customer we don't want the customer to see the author and revision information. Because it's a pdf it's difficult to edit afterwards.  

**Additional context**
This somewhat relates to #992 however I believe it's significantly less ambitious to implement.  By executing this as a modal after the export pdf is clicked further export options could be added later.

**Comment by sorvani** [comment]
This is super needed. I was going to export a bunch of user documentation from our wiki to use for client training. but i do not want these links in it. The user will have no access to the wiki. There is no public/guest visbile data.

**Comment by cw1998** [comment]
This is something I would also like to see, but would maybe require an extra screen with options before exporting (whereas currently the export button goes straight to a download). Adding extra "without footer" variants to the export menu would look cluttered in my opinion, but is another option. 

The way I work around this is exporting a page as HTML, removing the footer information in a text editor then using my browser's print to PDF feature, or an online converter to save the result as a PDF.

**Comment by lenusch** [comment]
I need this aswell. Don't want to have those Data in Footer. 
Maybe some Options in Settings to disable Footer? 
And or make it customizable via Overrides?

**Comment by andrej1919** [comment]
We would like to use BookStack for ISO documentation but this missing feature is one of of the serious obstacles. It's a pity since BookStack is really very close and almost ideal for this purpose. Just the page numbering and better footer handling are missing.

**Comment by ssddanbrown** [comment]
It's possible to do this via the [theme system](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#theme-system).

### Quick Guide

Add `APP_THEME=custom` to your BookStack `.env` file.

Within your BookStack installation, create the file at the path `themes/custom/partials/entity-export-meta.blade.php`. You should already have a `themes` directory but you'll need to create the `custom` and `partials` directories The file you create can be blank.

You should no longer have the footer content in exports.

Note, while the view system itself is stable, the files you override using it are not so you'd want to check your overrides are still working after any updates.

**Comment by petersem** [comment]
I achieve this by hiding the version and author with some basic CSS in the settings screen under custom header. This seems to suppress it nicely for PDF and for encapsulated HTML exports.

    <style>
    #page-show .text-muted {
      visibility: hidden;
    }
    .contents .text-muted 
    {
      visibility: display;
    }
    </style>

**Comment by sebekmartin** [comment]
Hello everybody,
as I have not found anything new about this feature, I tried to set this up according to Dan's comment from December 2020. It is working correctly, there is just a different file, you need to override.
If you want to remove the version revisions in the footer, just create a blank file at the path `themes/custom/exports/parts/meta.blade.php`. 
Also, any content in this file will be displayed in the page's footer instead of the revision information.

I hope, that this helps someone.

**Comment by ssddanbrown** [comment]
Since this can be achieved via the visual theme system, as explained above, I'm going to therefore go ahead and close this off.

**Comment by ConfusedHelpticon** [comment]
I fixed this for myself by adding a display: none style to the settings/customization/Custom HTML Head Content block of my bookstack web UI. Inside the "HTML Head Content" block, just add:

<style>
  .entity-meta {
      display: none;
    }
<style/>

if you already have a style reference in there, then just add:
  .entity-meta {
      display: none;
    }
 inside the <style> element

This works nicely for me, I hope it works the same for everyone else.

**Comment by oppassum** [comment]
I realize this is an older issue but since I just found it, some of you may also be interested in this:

I used @ConfusedHelpticon's recommendation for .entity-meta {display: none;} -- but I still wanted to show the revision on the page, just not on the PDF.

I adapted it to be surrounded by @media print { } so that it would only hide it when trying to export.

Full code:

<style>
  @media print
  {
  
     .entity-meta { display: none !important; } 
  }
<style/>

NOTE: this worked for the PDF export, but NOT the contained web file export.
