### ISSUE TITLE
Add "Listed" permission to a book

### ISSUE THREAD

**Issue by LoosGuccreen** [BookStackApp/BookStack#1279]
**Describe the feature you'd like**
The idea is to add a "listed" permission to a book (or article, or shelve), that would tell whether a book can be seen on a shelve or not without certain permission (but not to access it). 
If ticked, it would behave as it does now
If unticked, it would act pretty much like Youtube's unlisted videos: If you have the correct link, you can read them (and if the permission is set on the book level and you have access to it, you can see the list of articles in said book), but they cannot be reached only by clicking.

**Describe the benefits this feature would bring to BookStack users**
Example case: You organize an event and have to disclose informations to a lot of people (they are not "sensitive" but they should not be public). Having to ask them to register and then manually act on the account to change its role so that they can read is painful.
This solution would allow to just give them a link without fearing that any wiki user find them.

**Comment by ssddanbrown** [comment]
Thanks for creating this issue @LoosGuccreen.

This is an interesting idea, I actually thought of something similar, except I was thinking about chapters having this "Unlisted" functionality instead. [My thinking can be seen here](https://github.com/BookStackApp/BookStack/issues/129#issuecomment-460412403) in second-to-last paragraph.

**Comment by ssddanbrown** [comment]
Since there's been little demand since this issue was created I'm going to close it off.
I think that, once we have #288 implemented, this will be somewhat possible by removing all default view permissions after creating a custom access link.
