### ISSUE TITLE
Set table column width in px

### ISSUE THREAD

**Issue by ongmark** [BookStackApp/BookStack#1281]
**Describe the feature you'd like**
A way to set table column width in px the same way we can set row height.

**Describe the benefits this feature would bring to BookStack users**
Precise control of column widths. Right now, setting column width involves dragging borders until it looks just about right.

**Comment by ssddanbrown** [comment]
Hi @ongmark,

This is currently possible although a little hard to find, [Check out this video](https://i.imgur.com/BeqpAu7.mp4) to get an idea how to achieve this.  

Let me know if that does what you wanted.

**Comment by ongmark** [comment]
@ssddanbrown yes, this is exactly what i was looking for. Thanks!

**Comment by ssddanbrown** [comment]
@ongmark Awesome! Will therefore close this.
