### ISSUE TITLE
Possibility to add a redis password

### ISSUE THREAD

**Issue by msbt** [BookStackApp/BookStack#1283]
**Describe the bug**
When using redis as cache/session driver, one might need to add a password for the redis connection, there is no variable in the config or any mention in the [db file](https://github.com/BookStackApp/BookStack/blob/master/config/database.php)

**Steps To Reproduce**
1. Change drivers to redis
2. Look for the place to put the password

**Expected behavior**
Either have a REDIS_PASSWORD variable or use something like REDIS_SERVERS=:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.25.1
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): apache in a docker container behind nginx reverse proxy

**Additional context**
Hope I didn't miss something

**Comment by ssddanbrown** [comment]
> Hope I didn't miss something

No, Just don't used redis that often myself so did not know it could be commonly used with a password.

Thanks for reporting, Should be a fairly quick thing so have marked for the next minor release.

**Comment by msbt** [comment]
Great, thanks!

**Comment by ssddanbrown** [comment]
The new format will be `HOST:PORT:DATABASE:PASSWORD`, Where `:PASSWORD` is optional.
Just about to merge in the code updates for this, Will be in the next patch release. 

### Notes for release

Previously specifying multiple redis servers did not actually seem to do anything, Only the first was used. Code is now updated to auto-use a cluster if more than one server is provided.

The `REDIS_CLUSTER` has now been removed.
