### ISSUE TITLE
Align Right in Table Breaks Cell

### ISSUE THREAD

**Issue by cwmke** [BookStackApp/BookStack#1284]
**Describe the bug**
After typing text into a cell of a table, when I select 'Align right', the individual cell squeezes to the right which looks odd.

**Steps To Reproduce**
1. Create a table (tested with 4x4)
2. Enter some text in some cells
3. Click a cell(s)
4. Click the 'Align right' button

**Expected behavior**
The table shape and size remains unchanged while aligning the text in the selected cell to the right side.

**Screenshots**
![screenshot_20190218_091712](https://user-images.githubusercontent.com/1923967/52960265-08daa500-335e-11e9-9ddb-b4ba8ae18bce.png)

**Your Configuration:**
 - Exact BookStack Version (Found in settings): v0.25.1
 - PHP Version: 7.2.14
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
Freshly installed yesterday.

**Comment by ssddanbrown** [comment]
@cwmke Thanks for reporting, this definitely is not right, can see what's going wrong though so should be fairly quick to fix. Have assigned to the next bugfix release.

Surprised how long this must have gone unreported

**Comment by ssddanbrown** [comment]
Fix applied, Will be in the next patch release.

**Comment by jeromequintard** [comment]
4 month I want to add this issue... @ssddanbrown I dont see a patch to resolve this little bug. Is it really applied ?

**Comment by ssddanbrown** [comment]
@jeromequintard it should be. If you're experiencing issues please confirm your BookStack version and the exact issue you are coming across.
