### ISSUE TITLE
Demo PDF export image misaligned

### ISSUE THREAD

**Issue by avafowler** [BookStackApp/BookStack#1288]
**Describe the bug**
Image in exported PDF wrapping text incorrectly.

**Steps To Reproduce**
1. Go to [book demo](https://demo.bookstackapp.com/books/dummy-content-book).
2. Click on 'Export'.
3. Select 'PDF File'.
4. Go to page 6.
5. Image displays incorrectly behind text.

**Expected behavior**
Text should be wrapped around image.

**Screenshots**
Incorrect - Exporting PDF from book:
![image](https://user-images.githubusercontent.com/46720084/53048559-0dd54c80-3463-11e9-80cb-40b62b6bfe82.png)
Correct - Exporting PDF from page:
![image](https://user-images.githubusercontent.com/46720084/53048537-fe560380-3462-11e9-899c-74f27606a1f9.png)

**Your Configuration (please complete the following information):**
 - Using BookStack Demo page.

**Additional context**
This occurs when exporting a PDF at the book level, not at the page level.

**Comment by ssddanbrown** [comment]
@avafowler Thanks for reporting. Demo is using the less-accurate, default, DomPDF renderer but It'd still expect the page content to render the same in both export types. 

Will look into when I get the chance

**Comment by ssddanbrown** [comment]
Based upon testing via https://demo.bookstackapp.com/books/bookstack-demo-site/page/mixed-content-example-page, I think this may have since been fixed so I'll close this off.
