### ISSUE TITLE
Enable only social integrations

### ISSUE THREAD

**Issue by gandarez** [BookStackApp/BookStack#1290]
**Describe the feature you'd like**
A way to disable the standard login and keep enabled only social ones I define.

**Describe the benefits this feature would bring to BookStack users**
In the company I work they make us to login using only Google and do not accept other types of authentication.

**Comment by ssddanbrown** [comment]
Hi @gandarez,
Thanks for opening this issue.

This has already been requested in #1090 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #1090 it will help show support for that request.
