### ISSUE TITLE
Possibility to choose type of books

### ISSUE THREAD

**Issue by tdslot** [BookStackApp/BookStack#1292]
**Type of books**
Would be very useful if we have possibility to choose type of books. I mean when we create book could be:
* Simple book - (as now)
* Knowledge book - like knowledge base in Microsoft or VMware. would be structured template how to fill all information.
* Note book - with a lot of category and sub categories without limit like now.

**Benefits**
With different type of books you can expand BookStackApp work as knowledge base and have mo flexible organized content.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @tdslot.

To be honest, I like the simplistic system we have now. Having different types of books weakens what a book is and complicates the structure of content in addition to adding additionally implementation and maintenance work. 

> With different type of books you can expand BookStackApp work as knowledge base and have mo flexible organized content.

It would be good to expand on this to explain _how_ the book types would "expand BookStackApp work as knowledge base". I get that it would provide more options to the user but what do these options enable that is currently not possible for BookStack users?

**Comment by tdslot** [comment]
I can understand you that you want keep things simple. But we lag for example this thins I suggested. Would be nice If those books can be created.

**Comment by noseshimself** [comment]
> To be honest, I like the simplistic system we have now. Having different types of books weakens what a book is and complicates the structure of content in addition to adding additionally implementation and maintenance work.

Maybe not as separate types of books but offering page templates from a template library. And not having "simple" or "complex" books but permitting at least sub-chapters of a configurable (? -- or endless) depth.

I just tried out Bookstack to see if we could move our documentation over from the current collection of tools but only having chapters and pages will  not work for us.

**Comment by cw1998** [comment]
I've always liked the idea of having a colour assigned to a book. This wouldn't complicate the current structure, but would allow for at-a-glance viewing of all books of a particular colour, which you can map internally to a type if you like. Blue books for knowledge, green books for notes, yellow books for logs etc

However I would agree that adding book types or categories would add complexity to the structure.
It would be possible in this case to tag a book with however you wish to categorise it. Cover images could also be used in some way to categorise a book.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off as out of scope since I can't see implementing this any time soon. The core features actually desired are either likely covered by other existing issues or have been previously requested.
