### ISSUE TITLE
Attachment size limited to 256MB

### ISSUE THREAD

**Issue by kramester** [BookStackApp/BookStack#1293]
**Describe the bug**
I am unable to upload attachments larger than 256MB (according to the error).

**Steps To Reproduce**
1. Running Ubuntu 18.04 - used installation script
2. updated /etc/php/7.2/apache2/php.ini
```
memory_limit = 2048M
post_max_size = 2048M
upload_max_filesize = 2048M
```
3. Go to any page and try an upload file larger that 256MB
4: Get error "File is too big (filesize). Max filesize: 256MiB."

**Screenshots**
![2d-artist-p40](https://user-images.githubusercontent.com/6633780/53110035-c781fb00-34ff-11e9-97bd-b27bfc7b0388.png)

**Configuration:**
 - BookStack v0.25.1
 - PHP Version:  7.2.15
 - Apache 2

**Comment by ssddanbrown** [comment]
Sorry @kramester to see you're hitting issues here.

Looks like this is a limit set in the file-upload library.
We can look ot make this configurable as we have done for the timeout, Shouldn't be too tricky.
Have assigned to the next patch release.

**Comment by kramester** [comment]
Most excellent, thank you!

**Comment by Zeigren** [comment]
How is this fix enabled? I tried adding something like
`<script>
    window.uploadLimit = 512;
</script>`
to the Custom HTML head content but it didn't change anything.

**Comment by ssddanbrown** [comment]
@Zeigren Are you on the latest BookStack release?
Do you get the exact same error message? Please screenshot it if you can.

Might be an idea to open a new issue since this one is closed, otherwise comments may be missed.
