### ISSUE TITLE
Arbitrary renaming of Shelves and Books

### ISSUE THREAD

**Issue by gab-cass** [BookStackApp/BookStack#1301]
**Describe the feature you'd like**
Enhancement request: The possibility to rename Shelves and Books throughout the app to something else (ex: Spaces and Wikis)

**Describe the benefits this feature would bring to BookStack users**
Renaming would work for other user-case scenarios

**Additional context**
Thanks for the app, it's pretty good as it is!

**Comment by ssddanbrown** [comment]
Thanks @gab-cass for the request and the good feedback.

The fundamental feature requested here is already open under #406 therefore I'm going to close this to cut down on duplicates.

**Comment by gab-cass** [comment]
Thanks @ssddanbrown , I missed that one. Cheers!
