### ISSUE TITLE
Set static header and footer on dompdf when exports 

### ISSUE THREAD

**Issue by drbelmonte** [BookStackApp/BookStack#1305]
Hello, 
Can i set static header and footer on dompdf when exports   ? 
I try to look on internet pages, but no sucess .. :( 

Anyone can help  ?

**Comment by ssddanbrown** [comment]
Hi @drbelmonte ,
Thanks for opening this issue. Unfortunately this is not currently possible.

This feature has already been requested in #493 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #493 it will help show support for that request.
