### ISSUE TITLE
PowerShell codeblock support

### ISSUE THREAD

**Issue by eFiggy** [BookStackApp/BookStack#1309]
Hi there! I ran into BookStack some time ago and was interested in getting my teammates at work to try using it. However, there was one **teeny** problem -- a lot of commandline stuff we do uses PowerShell, and BookStack doesn't support PowerShell in its codeblock. Would this be something that could be added in the future? Thanks for considering it!

**Comment by ssddanbrown** [comment]
Hi @eFiggy,
Thanks for your request.

Powershell support was added recently into the main code (#1040, #1263) so will be in the next minor release that's due in the next couple of weeks. Keep an eye out for that!

I'll close this issue since this functionality is already lined up for release.
