### ISSUE TITLE
Accessing Bookstack from local IP is not possible after setting up APP_URL

### ISSUE THREAD

**Issue by recklessnl** [BookStackApp/BookStack#1310]
**Describe the bug**
I cannot access Bookstack through my local IP anymore once I set up APP_URL. I'm not sure this is intended, but the other day my internet was out for the day and it was highly annoying not being able to access a local database on my own network. All my other selfhosted docker apps are fine running behind both a web URL (reverse proxied) and local access. Only Bookstack has this issue and I don't know why. It's great that I can access Bookstack using my domainname and a reverse proxy, but giving up local access to do that seems silly and a weak feature - I can't think of any other Docker app that I'm running that has this issue, all of them can be accessed fine through a reverse proxy and also locally using their IP and port.

I'm using the latest version of Bookstack, on Docker, as of today.  Everything else works fine, but there has to be a way to access it locally in case the internet goes down (and really, why not access it locally when you are on the network and you can?)

How can I access it locally when APP_URL has been set up?

**Comment by ssddanbrown** [comment]
Hi @recklessnl,
`APP_URL` essentially forces all generated URLs in BookStack.
BookStack only really supports being used on a single host URL for a single BookStack instance.

You can try to go without setting `APP_URL` but it's possible you could face other issues, Especially in a reverse proxy setup.

**Comment by dfanara** [comment]
@recklessnl Can you briefly describe your docker / networking setup? If you are experiencing issues accessing a locally hosted system when the internet goes down it may just be as simple changing your DNS settings. 

It does seem that Bookstack works without `APP_URL` set, but you need to make sure that your proxy is connecting to your Bookstack container using HTTPS otherwise Bookstack will only serve HTTP links.

**Comment by ssddanbrown** [comment]
I'm going to close this in favour of grouping related issues into #1342.
