### ISSUE TITLE
Upgrade from 0.22 to 0.25.1 - "An unknown error occurred"

### ISSUE THREAD

**Issue by Nico207** [BookStackApp/BookStack#1313]
**Describe the bug**
After updating from 0.22 to 0.25.1, I've got this error when I go on the homepage, in books, in pages, on the connection screen :

> An unknown error occurred

**Steps To Reproduce**
1. Install the v0.22
2. Use the command to upgrade : `git pull origin release && composer install && php artisan migrate`
3. Go to the homepage

**Screenshots**
![image](https://user-images.githubusercontent.com/1179972/53812037-e7330d80-3f5a-11e9-9d8a-6885e08fedfe.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): V0.25.1
 - PHP Version: PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
 - Hosting Method (Nginx/Apache/Docker):  Apache/2.4.29 (Ubuntu)

**Additional context**
I found some of this lines into the logfile :
```
...
[2019-03-05 13:37:46] production.ERROR: Class 'BookStack\Services\Facades\Activity' not found {"exception":"[object] (ErrorException(code: 0): Class 'BookStack\\Services\\Facades\\Activity' not found at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:80)
...
[2019-03-05 13:38:13] production.ERROR: Class '\BookStack\User' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class '\\BookStack\\User' not found at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php:147)
...
[2019-03-05 13:38:44] production.ERROR: Class 'BookStack\Services\Facades\Views' not found {"exception":"[object] (ErrorException(code: 0): Class 'BookStack\\Services\\Facades\\Views' not found at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:80)
...
```

**Comment by ssddanbrown** [comment]
Hi @Nico207,
Sorry to see you're experiencing issues. 

Did you see any errors when running the upgrade commands? 
What do you see when running `git status` in your BookStack installation directory?

**Comment by Nico207** [comment]
I didn't see any errors during the upgrade ([UpadateResult.txt](https://github.com/BookStackApp/BookStack/files/2931409/UpadateResult.txt)).
Here is the result of `git status`

> root@bookstack:/var/www/bookstack# git status
> On branch release
> Your branch is up to date with 'origin/release'.
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
>         modified:   config/app.php
>         modified:   config/mail.php
> 

> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>         .env.bak
>         composer.phar
>         public/local_css/
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> root@bookstack:/var/www/bookstack#

**Comment by Nico207** [comment]
And before the update, `git status` would return this :

> root@bookstack:/var/www/bookstack# git status
> On branch release
> Your branch is up to date with 'origin/release'.
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
>         modified:   config/mail.php
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>         .env.bak
>         composer.phar
>         public/local_css/
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> root@bookstack:/var/www/bookstack#

_PS : if necessary, I have a snapshot of the server just before the update_

**Comment by Nico207** [comment]
I found the biggest problem : the original installation was done with the feet... 
After making a backup, I maked a clean installation with the script and restored the data.
Everything is working perfectly now.
Sorry about the false alarm.

**Comment by BirenGrooveHere** [comment]
We still getting this issue can anyone explain. we recently move bookstack on new server

**Comment by BirenGroove** [comment]
Hi there,
after many googles searched, found there was an issue with my Php so I followed below i

PHP 7.0:

Ubuntu: apt-get install php7.0-xml
CentOS / Fedora / Red Hat: yum install php70w-xml
PHP 7.1:

Ubuntu: apt-get install php7.1-xml
CentOS / Fedora / Red Hat: yum install php71w-xml
PHP 7.2:

Ubuntu: apt-get install php7.2-xml
CentOS / Fedora / Red Hat: yum install php72w-xml
PHP 7.3:

Ubuntu: apt-get install php7.3-xml
CentOS / Fedora / Red Hat: yum install php73w-xml
PHP 7.4:

Ubuntu: apt-get install php7.4-xml
CentOS / Fedora / Red Hat: yum install php74w-xml
PHP 8.0

Ubuntu: apt-get install php8.0-xml
CentOS 8 [with php:remi-8.0 enabled]: dnf install php-xml
