### ISSUE TITLE
how to change the editor beyond markdown  and wysiwgy freely? not just globaly configue by admin user

### ISSUE THREAD

**Issue by starfish100** [BookStackApp/BookStack#1315]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.

**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @starfish100,
Thanks for your request.

The feature you have asked for has already been requested within the issues: #458, #119 & #842.
To cut down on duplicate issues I will be closing this.
