### ISSUE TITLE
Allow specifying full group DN instead of just group name

### ISSUE THREAD

**Issue by craftbyte** [BookStackApp/BookStack#1318]
**Describe the feature you'd like**
Allows specifying the full DN of a role auto assign group instead of just the name.

**Describe the benefits this feature would bring to BookStack users**
In large federated AD environment (like the one we have at the University of Ljubljana) each part of the company has their own AD server with a specific domain (subdomain). We would be able to limit a role like wikiadmin to only one in our AD domain and not the whole federation, if someone else were to make a group with a same name.

**Additional context**
DNs are in same format as usernames:
`CN=WikiAdmins,OU=Groups,DC=member1,DC=example,DC=com`

**Comment by ssddanbrown** [comment]
Thank for the request here but I'm going to close this off since it's had relatively little demand since the original request and I don't want to expand the scope of the authentication systems without clear & wide benefit.
