### ISSUE TITLE
No Confirmation In Restore Function

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1321]
**Describe the bug**
When using the restore function no confirmation query is shown before restore. While not a problem of its own the link is written into the browser history and can be activated accidently without knowing that you're about to restore a page into an older state.

**Steps To Reproduce**
1. Create page with all permissions with this user.
2. Update the page once.
3. Use the restore function and restore the first revision.
4. Look in your browser history and click on the entry.
5. Page is restored without confirming it.

**Expected behavior**
A clear confirmation before restoring a revision.

**Screenshots**
![2019 03 10-18 59](https://user-images.githubusercontent.com/42382626/54089290-d7a33280-4367-11e9-977e-9c13333a1b43.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):  BookStack v0.25.1
 - PHP Version: 7.2.10
 - Hosting Method (Nginx/Apache/Docker): Apache 2

**Comment by ssddanbrown** [comment]
Thanks for reporting @Bolthier, I agree with this, This should be a POST/PUT/PATCH request instead of a GET request to prevent it even being in the history.

I have assigned to myself for the next release as it would be good to do this as part of the design update.
