### ISSUE TITLE
Add web-app meta tags for fullscreen on mobile devices

### ISSUE THREAD

**Issue by hmr-it-jr** [BookStackApp/BookStack#1322]
**Describe the feature you'd like**
If you click "Add to Homescreen" on your Android or iOS device there is no icon available. Besides this if you open the newly created shortcut on your homescreen it opens the browser - but not fullscreen.

If you provide some meta tags the app opens in fullscreen mode in is like a native app.

**Describe the benefits this feature would bring to BookStack users**
Fullscreen and native app feeling on mobile devices of any os.

**Additional context**
ready to use repo: [https://github.com/gokulkrishh/awesome-meta-and-manifest](https://github.com/gokulkrishh/awesome-meta-and-manifest)

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @hmr-it-jr.

There are two existing issues that seem to cover what you're requesting here:
* #1252 - Progressive Web Application (For add to homescreen support / App feel)
* #301 - iOS homescreen icon support

In the interest of keeping duplicates reduced I'm going to close this. Please comment if I've misunderstood at all though.

**Comment by chillinPanda** [comment]
Just a small addition to the above linked issue for PWA: It is #1253

**Comment by hmr-it-jr** [comment]
@ssddanbrown are you sure you don't want to add this as feature to BookStack?

There is a generator which I use for other projects: [https://tomitm.github.io/appmanifest/](https://tomitm.github.io/appmanifest/) - after using generator you just have to add the meta tags to /resources/views/public.blade.php and put the manifest.json in the public folder.

... that's it. Nothing more to do. I've done it to show you how it'd look like:

![ezgif-5-0e9e5a55a735](https://user-images.githubusercontent.com/36242595/54314432-f01b8300-45db-11e9-8b03-1dc24a73e355.gif)

If I send a pull request would you merge it?

**Comment by ssddanbrown** [comment]
@hmr-it-jr Just to be clear, I'm not rejecting this request, I've closed it as the requested feature set is already covered by other issues, 

> you just have to add the meta tags to /resources/views/public.blade.php and put the manifest.json in the public folder.

It's not quite that simple, We'll need to make the manifest accessible in the base template and make it dynamic to react to different configuration options. The icons may be tricky since the current app logo setting is likely not to be suitable for an app icon in many cases.

**Comment by hmr-it-jr** [comment]
@ssddanbrown why not add the "simple" variant with static logo, etc. now that the users can benefit from the app like feeling and add the dynamic and configurable variant later?

**Comment by ssddanbrown** [comment]
@hmr-it-jr We could do that but it will be another half-finished feature in the system.

> and add the dynamic and configurable variant later

It's always too easy to leave the hard pieces for later. I must admit though I'm somewhat haunted by the thoughts of the addition of a "simple" variant leading to a bunch of new issues requesting configurability and expansion on the feature.

**Comment by lignumaqua** [comment]
This may be already known, but I didn’t find it in the documentation. You can add the meta tags for full-screen use on an iOS device in the 'Custom HTML Head Content' section within BookStack. The following works on an iPad when BookStack is run from a Home Screen bookmark

`<meta name="apple-mobile-web-app-capable" content="yes">`

**Comment by igorrust** [comment]
Nice find! Thanks! 

When you open bookstack like this, it seems the way I think most imagine the site to act from the ios homescreen, but unfortunately when you select a book, it opens this book in a new "tab" (without addressbar though, but with back /share/done buttons). So it becomes only partial fullscreen.

Still hoping for a more permanent solution.


> This may be already known, but I didn’t find it in the documentation. You can add the meta tags for full-screen use on an iOS device in the 'Custom HTML Head Content' section within BookStack. The following works on an iPad when BookStack is run from a Home Screen bookmark
> 
> 
> 
> `<meta name="apple-mobile-web-app-capable" content="yes">`
