### ISSUE TITLE
On the user profile form, Roles with a dot in the name do not remember their input on validation failure

### ISSUE THREAD

**Issue by tpoindessous** [BookStackApp/BookStack#1325]
Hi

I got hit by a small bug but an unpleased one, as it takes me long time to figure it out.

**Describe the bug**
I made a new user : I checked one role for this user and I mistyped the password and the password-confirm didn't match. When I save my user, page is refreshed, error message is displayed but the role is unchecked. I did several tests and I can reproduce it : it seems that this bug occurred because :
  * I checked the last role of the list
  * OR because my role contains a dot "Client.NAME"

**Steps To Reproduce**
1. Go to '/settings/users/create'
2. Fill name and email
3. Check the last role, which contains a dot in his name
4. Mistype password and password-confirm so they don't match
5. Save user 

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.25.1

Thanks !

**Comment by ssddanbrown** [comment]
Thanks for reporting @tpoindessous.

I've confirmed this to occur when a dot is part of the role name. I'll update the issue name to be more specific based on the results that I've found.

**Comment by ssddanbrown** [comment]
Fixed by @cw1998 in #1392, Fix will be deployed in the next release.
