### ISSUE TITLE
error in sql database

### ISSUE THREAD

**Issue by aglyon** [BookStackApp/BookStack#1326]
**Describe the bug**
After installation, when I checked my database with phpMyAdmin, i have this error, i don't know if this have an effect on the behavior of Bookstack 

**Message on phpMyAdmin**

Warning in ./libraries/sql.lib.php#601
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2038: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1984: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'c0bookstack',
string 'books',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `books`',
NULL,
NULL,
)
./sql.php#216: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'c0bookstack',
string 'books',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `books`',
NULL,
NULL,
)

**Your Configuration**
BookStack v0.25.2
PHP Version: 7.2.16-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.5.5
Web Server Info: Apache/2.4.38 (Ubuntu)

**Comment by ssddanbrown** [comment]
Hi @aglyon,
None of the files in the logs above are any of BookStack's. I believe this is probably a PHPmyAdmin error:
https://stackoverflow.com/questions/48001569/phpmyadmin-count-parameter-must-be-an-array-or-an-object-that-implements-co

As an extra note, Your MySQL version is rather old. MySQL `5.5.5` was released in 2010! For BookStack we only really look to support MySQL 5.6+.

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this. 
If this issue remains please feel free to open a new issue, referencing this one.
