### ISSUE TITLE
Login on moved site is not working

### ISSUE THREAD

**Issue by adminarf** [BookStackApp/BookStack#1328]
**Describe the bug**
1. Logging in returns to the login page without messages
2. Password reset returns to the password reset page without messages

**Steps To Reproduce**
Steps to reproduce the first issue:
1. Go to login page
2. Do not click Remember me
3. Enter credentials and submit

Steps to reproduce the second issue:
1. Go to login page
2. Enter email address and submit

**Expected behavior**
1. Expected login and if not I expected an error message.
2. Expected password reset email

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.20.0
 - PHP Version: 7.1.26
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
The site was copied to a new server and had worked properly on the old server.

.env was updated for new DB and email server details.

I added a new admin account with `php artisan bookstack:create-admin`. The result was the same.

I changed app_debug to true. This is the result from login:

**Views**

> 7 templates were rendered
> auth.login (resources/views/auth/login.blade.php) 2 blade
> auth.forms.login.standard (resources/views/auth/forms/login/standard.blade.php) 8 blade
> form.text (resources/views/form/text.blade.php) 10 blade
> form.password (resources/views/form/password.blade.php) 10 blade
> public (resources/views/public.blade.php) 8 blade
> partials.custom-styles (resources/views/partials/custom-styles.blade.php) 8 blade
> partials.notifications (resources/views/partials/notifications.blade.php) 8 blade

**Queries**

> select * from `users` where `system_name` = 'public' limit 1 3.02ms /app/User.php:45
> select * from `settings` where `setting_key` = 'registration-confirmation' limit 1 420μs
> /app/Services/SettingService.php:229
> select * from `users` where `system_name` = 'public' limit 1 330μs /app/User.php:45
> select * from `settings` where `setting_key` = 'registration-enabled' limit 1 330μs /app/Services/SettingService.php:229

**Comment by ssddanbrown** [comment]
Hi @adminarf,
Sorry to hear you are facing issues.

Hard to know what's the issue here. This kind of thing can often occur if the browser does not save cookies for the site or if there's a change of domain during the login and post-login redirect. 

Do you have the `APP_URL` option set in your `.env` file? Might be worth setting to force a domain. Also worth trying a different browser just to rule-out any overzealous cookie defences.

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this.
If this issue remains please feel free to open a new issue, referencing this one.
