### ISSUE TITLE
Ability To have export option per group

### ISSUE THREAD

**Issue by causefx** [BookStackApp/BookStack#1332]
**Describe the feature you'd like**
Would love to have options to lock down each export option by user group.

**Describe the benefits this feature would bring to BookStack users**
For some people that open up all books to public, you don't want people abusing the export options.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion.

Please see my comments on this [very similar issue](https://github.com/BookStackApp/BookStack/issues/1251#issuecomment-459977336).

**Comment by causefx** [comment]
So sorry about that.   I searched the open issues but assume I didn't do it correctly.  Their request is more in depth whereas mine was strictly per group but I do see the issue.  In the meantime, I will use the custom css option.  Thank you!
