### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by ZerGBlunt** [BookStackApp/BookStack#1335]
I  have recently installed Bookstack to another server, after typing up some information and saving it, the actual view of the page shows a large block of white space but I can not replicate this in the editor mode. How to remove this?
![VJ9QJ9GqUOL](https://user-images.githubusercontent.com/43989945/54485816-b94ca380-484d-11e9-8124-d2854e485bd2.png)

**Comment by ssddanbrown** [comment]
Sorry to see you're having issues with BookStack @ZerGBlunt.

Just to help me diagnose this one, Are you able to reproduce this issue on the [BookStack demo site](https://demo.bookstackapp.com/login?email=admin@example.com&password=password)?

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this.
If this issue remains please feel free to open a new issue, referencing this one.
