### ISSUE TITLE
Default landing page per user role

### ISSUE THREAD

**Issue by adamgranted** [BookStackApp/BookStack#1341]
**Describe the feature you'd like**
It would be amazing if you could set a default page (whether shelf, book, or page) on a user role level. This way if you have a particular department that solely or primarily reads off of a specific shelf, that shelf will be the default location when the login.

**Describe the benefits this feature would bring to BookStack users**
I see it simplifying the user experience particularly for those employees that are not technically savvy. It will make the documentation that applies for their position available immediately on login.

**Additional context**
No other context to add.

**Comment by ezzra** [comment]
duplicate #1152

**Comment by ssddanbrown** [comment]
Thanks @adamgranted for submitting this clear feature request.

As stated by @ezzra, #1152 covers the core requested feature. Therefore, to keep duplicate issues down, I'll close this one.

Adding a thumbs-up reaction to the original post on #1152 would help show support for such a feature.
