### ISSUE TITLE
Split table feature

### ISSUE THREAD

**Issue by p0lp0** [BookStackApp/BookStack#1343]
**Describe the feature you'd like**
I don't see any clear way to, once a table has been created, split a table into two separate tables from a given row.

This capability is familiar to Microsoft Office users: https://support.office.com/en-us/article/split-a-table-d231a898-6983-4ef8-acb0-797c7f2b0c45

**Describe the benefits this feature would bring to BookStack users**
When you're working with a long table and want to break it into sections to make better use of the text formats / headings feature, it seems you need to modify the page source in order to do this., which is confusing.

**Comment by ssddanbrown** [comment]
Thanks for the request, but I'm going to lose this off since there's been little demand for such a feature since this original request.
