### ISSUE TITLE
Uploading Attachments Larger Than 256MB

### ISSUE THREAD

**Issue by Zeigren** [BookStackApp/BookStack#1346]
**Describe the bug**
Unable to upload attachments larger than 256MB

**Steps To Reproduce**
1. Upload a file larger than 256MB to a given page.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/1381145/54831621-e945dd80-4c77-11e9-9c7f-efc3da6cdd8e.png)

**Your Configuration (please complete the following information):**
 - BookStack v0.25.4
 - PHP Version: 7.3.3
 - Hosting Method (Nginx/Apache/Docker): Nginx/Docker
 - Ubuntu 18.04

**Additional context**
php.ini
`post_max_size = 0
upload_max_filesize = 0
memory_limit = 1028M
expose_php = off
cgi.fix_pathinfo = 0`

nginx.conf
`client_max_body_size 0;
client_body_timeout 6666s;`

Custom HTML head content
`<script>
    window.uploadTimeout = 6666 * 1000;
    window.uploadLimit = 600;
</script>`

Same issue as #1293 

Files smaller than 256MB are able to be uploaded just fine and I have the upload limits effectively turned off for nginx and php. Upload timeouts are extended although the file never starts to upload.

**Comment by ssddanbrown** [comment]
Hmm, This is odd. Using the exact same HTML head content line I can get the following:

![image](https://user-images.githubusercontent.com/8343178/54884037-e8719f00-4e63-11e9-9103-64954ee84dc7.png)

Are you using a specific docker image? If so I could run the same image and test within.

**Comment by Zeigren** [comment]
It's just something off with this specific installation it seems, so I should be able to fix it and I'll close the issue.

Here's my Docker stack https://github.com/Zeigren/docker-swarm-bookstack which on its own is working just fine.
