### ISSUE TITLE
Documentation: Default role names to map to LDAP groups

### ISSUE THREAD

**Issue by ookerberry** [BookStackApp/BookStack#1349]
I am trying to use openLDAP groups to set roles in bookstack.
I cannot find in the documentation what the default role names are so I can create the appropriate LDAP groups that map to them.

What are the default role names? Are they:
admin
editor
viewer
public

I was looking for something in the documentation that described the default role names and permissions, but I could not fine any such documentation.
Also the LDAP documentation describes the rules for mapping names, but does not describe the default role names.

If the default role names listed above are correct, then my understanding is that if I create LDAP groups by the same name and set the variables in environment listed below, then, for example,  a user in the LDAP group "admin" would be set to the role of "admin" in BookStack.  Is this correct?
    LDAP_USER_TO_GROUPS=true
    LDAP_GROUP_ATTRIBUTE="memberOf"
    LDAP_REMOVE_FROM_GROUPS=false

**Comment by ssddanbrown** [comment]
> Also the LDAP documentation describes the rules for mapping names, but does not describe the default role names.

Yeah, I thought listing out the default roles could cause more confusion as they are only a default and will depend on the instance setup and somewhat the BookStack version. The rules for the mapping of names remain the same though so you can just apply the rules to the default roles.

> What are the default role names? Are they:
> admin
> editor
> viewer
> public

Yes, That looks correct for a fresh install. 

> my understanding is that if I create LDAP groups by the same name and set the variables in environment listed below, then, for example, a user in the LDAP group "admin" would be set to the role of "admin" in BookStack. Is this correct?

Yes. Alternatively you can use existing LDAP groups and enter their names (Lower-cased and hyphenated) in the `External Authentication IDs` options when viewing a role in BookStack.

**Comment by ssddanbrown** [comment]
Will now close this
