### ISSUE TITLE
Error 500 out of nowhere

### ISSUE THREAD

**Issue by vincentmakes** [BookStackApp/BookStack#1351]
**Describe the bug**
My site was working fine and few hours later when I went back to check a page I got a 500 error. Rebooting the server fixed it but this is a strange behaviour.

This is the error I got in the log:
`Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack`

From what I understand it might work to modify the database.php file and replace localhost by 127.0.0.1 in the connection string but was wondering if anyone else has encountered this.

**Your Configuration (please complete the following information):**
The latest one, everything was installed yesterday from the script for Ubuntu 18.04

 - Exact BookStack Version (Found in settings):
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker):

**Comment by ssddanbrown** [comment]
Thanks for reporting @vincentmakes, Very strange. Have not heard of this issue myself and from the lack of comments here looks like not many other have either. Possibly a setup-specific issue.

I'm going to close this to keep issues focused but it'll still be searchable for others and I'll keep it in mind in the event something similar pops up in the future.
