### ISSUE TITLE
Social login / registration will fail in this specific scenario

### ISSUE THREAD

**Issue by nekromoff** [BookStackApp/BookStack#1352]
**Describe the bug**

**Steps To Reproduce**
1. Use Social login (e.g. Google) to log in without previous registration
2. The system will tell you that such user is not connected to any social accounts.
3. Next try to register via social service / e.g. Google and the system will tell you that user already exists.

**Expected behavior**
Social registration via first-time login should be either automatic or if so, do not block actual  registration from hapenning.

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):BookStack v0.25.2 
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @nekromoff,
Thanks for the concise issue info.

It sounds like you may want to use the [third-party auth auto-registration](https://www.bookstackapp.com/docs/admin/third-party-auth/#automatic-registration-email-confirmation) option?

For example, setting `GOOGLE_AUTO_REGISTER` will allow login attempts using google to automatically register a user if the social account has not already been registered and if the social account email address is not already in use.

**Comment by nekromoff** [comment]
Great! Thanks for these options, I must have missed them or they were not
available when I first installed BookStack. I am going to try it with some
new user in next few days to see if that works, but I think we can close
this issue.
