### ISSUE TITLE
Can't get email notification work / smtp problem

### ISSUE THREAD

**Issue by akurzawa** [BookStackApp/BookStack#1355]
=||=

**Comment by akurzawa** [comment]
Trying to configure email notification via local smtp server (kerio mail server) but it's not working

/var/www/bookstack/.env:

# Can be 'smtp', 'mail' or 'sendmail'
MAIL_DRIVER=smtp

# SMTP mail options
MAIL_HOST=10.0.0.2
MAIL_PORT=25
MAIL_USERNAME=public
MAIL_PASSWORD=public
MAIL_ENCRYPTION=null

but it does not work, what else to change to enable email notifications?

**Comment by ssddanbrown** [comment]
Hi @akurzawa,

Information on debugging errors can be found here:
https://www.bookstackapp.com/docs/admin/debugging/

Please follow those instructions to find more details about why you're receiving an error.

**Comment by akurzawa** [comment]
Will Try, thanks

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
