### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by gab-cass** [BookStackApp/BookStack#1356]
After trying / researching a multitude of similar solutions and wikis, I have settled for BookStack. It performs and it looks very good in production.

I have to say it's one of the best solutions as of now, considering ease of install + ease of customization + ease of administration/backup + end-user interaction as well.

The "near-desktop feel" editing experience plus the ability to attach files to pages - is all is needed for a good documentation website. I, personally can generate a static website in Hugo or Pelican, but BookStack makes it easier for average Jo end user, to actually use the software as well.

Thanks Dan and Abijeet + contributors, good stuff!

* You can close this, not an issue, obviously.

**Comment by hahmed09** [comment]
agreed great stuff guys

**Comment by ssddanbrown** [comment]
Thank you so much for your positive feedback, It's great to hear!

**Comment by ciphermenial** [comment]
I recently came back to using BookStack after rebuilding my server at least a year ago. I restored the database and it updated easily to the latest version. I signed in and was amazed by how much it has grown in that time.

**Comment by ssddanbrown** [comment]
Since it's been over 18 months I'll close this off. Thanks everyone :heart:
