### ISSUE TITLE
Attachment manager

### ISSUE THREAD

**Issue by hahmed09** [BookStackApp/BookStack#1358]
Will it be possible to create an attachment manager / portfolio, where all previously uploaded items sit and can easily be accessed via search for future uploads?

I believe that this will greatly simplify the end user experience if they are re-attaching elements across books or shelves.

**Comment by ssddanbrown** [comment]
Thanks for your request @hahmed09.

This has already been requested in #924. Since this issue is requesting the same feature I will close this one to cut-down on duplicates.
