### ISSUE TITLE
UI - vertical BAR

### ISSUE THREAD

**Issue by akurzawa** [BookStackApp/BookStack#1359]
Hi

can we get rid of vertical bar which is visible in mobile / small screen version of book stack? 

Istead of that there could be a small top button that toggles left menu

![image](https://user-images.githubusercontent.com/20043789/55320621-d0a7a580-5477-11e9-8a37-bc78f253b889.png)

**Comment by ssddanbrown** [comment]
Hi @akurzawa,
Could you could explain **why** you'd want to remove the vertical bar? That would help evaluate other potential solutions.

**Comment by ezzra** [comment]
I can see the benefit in this, it would actually give a little more space for the content and provide a cleaner view for mobile

**Comment by ssddanbrown** [comment]
As of v0.26 this vertical bar shown in the above image no longer exists. Will therefore close this.
