### ISSUE TITLE
Clone user with permissions

### ISSUE THREAD

**Issue by akurzawa** [BookStackApp/BookStack#1362]
Would that be possible? to clone user and just change email name and password for new user but preserve all permissions?

**Comment by ssddanbrown** [comment]
Thanks for the request @akurzawa.

I can see how this would be useful but I'm not sure how it can be intuitively be shown as an option in the interface. You can't exactly have a button that says "Clone user with permissions but not email, name or password". I think the use-case may be minimal for the extra UI and process it would require. 

I'll leave this open though to judge if this is a pain-point for others.

**Comment by ssddanbrown** [comment]
Thanks for the request but I'm going to proceed and close this off since there's been little demand for this feature since the original request.
