### ISSUE TITLE
@user mention in page

### ISSUE THREAD

**Issue by akurzawa** [BookStackApp/BookStack#1365]
would that be possible to include @user and after saving that page the metioned @user would recieve an email notification that he/she was mentioned in page?

![image](https://user-images.githubusercontent.com/20043789/55459424-d0cab100-55ef-11e9-82c3-3c366293df1c.png)

**Comment by ezzra** [comment]
that should be part of a general notification system that unfortunately is still missing, see https://github.com/BookStackApp/BookStack/issues/147

**Comment by ssddanbrown** [comment]
Thank you for the suggestion @akurzawa.

This fundamental request of this issue is already open under #560. Therefore, to cut down on duplicates I will close this.

**Comment by akurzawa** [comment]
ok thanks for info.

**Comment by akurzawa** [comment]
Hello 1,2 year later - any chance that bookstack will be able to send email to user with notification?

**Comment by matjazantloga** [comment]
wondering, this still not possible ?
