### ISSUE TITLE
Setup mail and ldap

### ISSUE THREAD

**Issue by TheDealman** [BookStackApp/BookStack#1369]
Hello

I just installed bookstack on ubuntu 16.04 and I used the installation script to do the install for me. I would like to setup the email and LDAP auth but all the documentation references some .env file that needs to be edited. Where is this .env file that I need to edit?

**Comment by cw1998** [comment]
Hi, there is an example .env file called `.env.example` in the root directory of the project. You can copy this to a file called `.env` and update the values as you need.

**Comment by ssddanbrown** [comment]
Thanks @cw1998 for providing some helpful info.

@TheDealman If you're having trouble finding your BookStack install, You'll probably find it at `/var/www/bookstack` since you installed using the script.

**Comment by TheDealman** [comment]
If i used the install script to do the installation where are some places i can look for this file? i'm not seeing it

**Comment by TheDealman** [comment]
> 
> 
> Thanks @cw1998 for providing some helpful info.
> 
> @TheDealman If you're having trouble finding your BookStack install, You'll probably find it at `/var/www/bookstack` since you installed using the script.

Thanks I found it

**Comment by TheDealman** [comment]
I will try to get this all working today

**Comment by TheDealman** [comment]
Okay i was able to get this working in the .env file that's located /var/www/bookstack

#General auth
AUTH_METHOD=ldap

# LDAP authentication configuration
LDAP_SERVER=ip of the AD server:389
LDAP_BASE_DN=OU=name,DC=ADNETBIOS,DC=SUFFIX
LDAP_DN=CN=ACCOUNT,OU=NAME OF OU,ADNETBIOS,DC=SUFFIX
LDAP_PASS=PASSWORD ACCOUNT LISTED ABOVE
LDAP_USER_FILTER=(|(mail=${user})(sAMAccountName=${user}))
LDAP_VERSION=3
LDAP_TLS_INSECURE=false
LDAP_EMAIL_ATTRIBUTE=mail
LDAP_DISPLAY_NAME_ATTRIBUTE=cn
LDAP_FOLLOW_REFERRALS=true

I was able to login using LDAP credentials but i didn't have any user roles so I changed the AUTH_METHOD to standard instead of ldap so i could login with the local admin account. I am able to see the accounts that have logged in via the ldap auth and assign roles but my question is when the ldap auth method is set how do you assign roles?

**Comment by TheDealman** [comment]
Anyone know the answer to the above question?

**Comment by ssddanbrown** [comment]
@TheDealman You can either set LDAP groups manually in the system and/or enable [LDAP group syncing](https://www.bookstackapp.com/docs/admin/ldap-auth/#ldap-group-sync) which will run when an LDAP user logs-in.

**Comment by TheDealman** [comment]
> 
> 
> @TheDealman You can either set LDAP groups manually in the system and/or enable [LDAP group syncing](https://www.bookstackapp.com/docs/admin/ldap-auth/#ldap-group-sync) which will run when an LDAP user logs-in.

Yes I setup a LDAP group but my question is  I am able to see the accounts that have logged in via the ldap auth but how do you assign roles?

**Comment by ssddanbrown** [comment]
@TheDealman You'd need to assign BookStack roles manually by viewing each user and selecting the roles to assign them. Otherwise you can align the names with LDAP groups to auto-set BookStack roles on login.

**Comment by TheDealman** [comment]
> 
> 
> @TheDealman You'd need to assign BookStack roles manually by viewing each user and selecting the roles to assign them. Otherwise you can align the names with LDAP groups to auto-set BookStack roles on login.

How do I align the names with LDAP groups to auto-set BookStack roles on login?

**Comment by ssddanbrown** [comment]
Sorry for my late response @TheDealman.

The process/logic is described in the [LDAP group syncing documentation page](https://www.bookstackapp.com/docs/admin/ldap-auth/#ldap-group-sync). Ultimately, you can either configure BookStack role names to align with LDAP group names otherwise use the `External Authentication IDs` BookStack role option to perform this matching.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
