### ISSUE TITLE
[Feature request] Make internal links robust to title changes

### ISSUE THREAD

**Issue by jl-costa** [BookStackApp/BookStack#1372]
Currently, if I create a hyperlink to an internal section (whether it is a book or page), the hyperlink is hard-coded to the current URL for that book/page.

If I later change the title of the book/page in question, all links pointing to it automatically become broken.

Given that we're not really linking to something external, but rather to an internal resource, I think it would be very nice if all internal links were not vulnerable to simple title changes.

**Comment by ezzra** [comment]
> If I later change the title of the book/page in question, all links pointing to it automatically become broken.

mh, I experienced that it still works, but not always. Its worse with chapter renaming. But true, its not really robust

**Comment by ssddanbrown** [comment]
Hi @jl-costa ,
Thanks for your request.

As @ezzra has mentioned, The page revision system is used to potentially catch renamed items in the hierarchy to prevent simple page title changes breaking the links.

The fundamental feature requested here has already been requested in #732 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #732 it will help show support for that request.

Let me know if I've misunderstood though.
