### ISSUE TITLE
Favorite books

### ISSUE THREAD

**Issue by TommiieeSV** [BookStackApp/BookStack#1376]
Hi,

We've been trying out BookStack with our team some time now and it's great!

On the Books page, on the left there's a bar that shows Recently Viewed books, Popular Books and New Books. We'd like an option to 'Favorite' specific books (user-dependent), so users are able to quickly find books they read often. The Books page would then get an extra section (preferably on the top) that would show Books you favorited as a user.

Arguably the books would appear in Recently Viewed, but that would depend on not reading (too much) other books.

**Comment by ssddanbrown** [comment]
Thanks for the feedback @TommiieeSV.

The possibility to have personal favorite items would be a good idea. 
This is related to #505.

**Comment by venkat0304** [comment]
Favorite would be a great feature. If you can make the 'love icon' visible on the books cover and user click that icon so that particular book will be bookmarked .. something like that :)

**Comment by Zerbz** [comment]
Heres a v0.29.0 fork with page favorites. This was quickly adapted from a very quickly built favorite system for v0.25.1 that was used internally, so please use with caution.  I can expand this to include chapters and books if desired. 

https://github.com/Zerbz/BookStack-v0.29.0-With-Favorites

**Comment by ssddanbrown** [comment]
I've just opened #2063 to gather feedback on the naming of such a feature similar to that which has been requested here.

**Comment by ssddanbrown** [comment]
An implementation of a favourites system, which would apply to books, chapters, shelves and pages, has now been added in #2748 ready for the next feature release.

Thanks again @TommiieeSV for the suggestion.
