### ISSUE TITLE
More Readable PDF Output at Shelves Level

### ISSUE THREAD

**Issue by blackshrub** [BookStackApp/BookStack#1379]
I would like to see the PDF output as readable as the HTML output. The title is not proportional and the line height is too large. It is also wonderful to be able to export consolidated books from one shelf.

**Comment by ssddanbrown** [comment]
The PDF output can often be a little shaky due to the technicalities in rendering to PDF.
In the docs we have some detail on changing the PDF rendering system to use the more accurate WKHTML library:
https://www.bookstackapp.com/docs/admin/pdf-rendering/

**Comment by blackshrub** [comment]
Okay thanks for pointing this out. I will close it as the request to export shelf has been posted in another issue.
