### ISSUE TITLE
Add generic Oauth2 login option?

### ISSUE THREAD

**Issue by poVoq** [BookStackApp/BookStack#1390]
**Describe the feature you'd like**
Is there any guidance on how to add a custom OIDC / Oauth2 provider though?
There are plenty already supported, see: https://www.bookstackapp.com/docs/admin/third-party-auth/

But I would like to add my own Nextcloud instance as the user backend since that is now possible, see for example:
https://www.claudiuscoenen.de/2018/10/oauth2-with-nextcloud-provider-and-gitlab-client/

**Describe the benefits this feature would bring to BookStack users**

Use to login of your own website if you set up a OIDC / Oauth2 service for which there are many options. 

**Additional context**
See also:
https://github.com/BookStackApp/BookStack/issues/1338

**Comment by acvigue** [comment]
+1, would like to use Keycloak as OIDC authentication backend.

**Comment by durnerj** [comment]
+1

**Comment by acvigue** [comment]
Any updates? @ssddanbrown

**Comment by ssddanbrown** [comment]
@acvigue No update right now. This is something I'd like to do, since I don't really want to expand the BookStack third-party login list much further, but I've been focusing my time on other bits recently as I found auth systems were using up a lot of my time. 

Shouldn't be too hard, just a case of understanding potential variability in services.

**Comment by thutex** [comment]
@ssddanbrown another +1 here for a way to match up authentication with nextcloud.
i would be happy with either oauth or imap/smtp authentication.

**Comment by Agnael** [comment]
+1 would love to integrate my personal bookstack with my personal IdentityServer (OAuth2+OIDC)

**Comment by tlvz** [comment]
another +1 : log in with nextcloud credentials would be very handy for many small companies I think :)

**Comment by dmigis** [comment]
+1 for Nextcloud
