### ISSUE TITLE
Page Navigation - section headings are truncated

### ISSUE THREAD

**Issue by tlmmm** [BookStackApp/BookStack#1396]
Hi,

Is there a way to show the full section headings in the Page Navigation box?  Some of our longer headings are being truncated so we can't see the full titles.  Is there a way to get around this and to show the full section headings?

Thanks.

**Comment by ssddanbrown** [comment]
Hi @tlmmm,
Thanks for the request, This is not possible right now I'm afraid. 

This has been previously requested in #1206 therefore I'm going to close this one to reduce duplicates but if you add a thumbs-up reaction to the main post on #1206 issue it will help to show support.

**Comment by tlmmm** [comment]
Thank you @ssddanbrown .  This would be a great feature to add.  :)
