### ISSUE TITLE
More E-Mail preferences

### ISSUE THREAD

**Issue by DanielKng** [BookStackApp/BookStack#1399]
Hello,

I think it would be a great addition to have the option to send out e-mails if a book was added/changed.
Might as well allow for customisation of those mails (Signature, general structure,...).

Currently I'm sending e-mails manually from my personal Mail-Account to notify the administrators that I've added a Book or changed something important. 
Therefore this would be a nice addition to bookstack.

**Comment by ssddanbrown** [comment]
Hi @DanielKng,

Did you just close then re-open your own issue (#42) to bump it up? Not sure how I feel about that, bit cheeky 😏 .

Something that does not help this to be completed is that this issue encompasses two requests:
* Email notification on Book events.
* Customization of emails.

I think the second point may already be possible albeit through the undocumented & unstable theming system. 
I can explain how you'd achieve this if you'd like.

**Comment by DanielKng** [comment]
Hi @ssddanbrown,
Nope, I did not. 
Also, you refer to "Add feature to delete images" wich really is not what I want at all ;)

But, I did create this issue on the BookStack/website-Repo first. But I found that this will fit here much better, that's why I closed that issue over there. :)

Sure, guide me trough it! :)

**Comment by ssddanbrown** [comment]
@DanielKng Ah, My bad, Yeah, I see what's happened. 
I'll respond back which how you could customize the email HTML when I next have a few minutes spare.

**Comment by ssddanbrown** [comment]
Just came across this again, Realised I had not responded.

The visual theme system [is now documented here](https://github.com/BookStackApp/BookStack/blob/master/dev/docs/visual-theme-system.md). It would be a case of [overriding this view](https://github.com/BookStackApp/BookStack/blob/master/resources/views/vendor/notifications/email.blade.php) to customize emails sent from BookStack.

Email notifications is already open under other issues (Primary being #241) so I'll therefore close this off.
If familiar with the framework, the [logical theme system](https://github.com/BookStackApp/BookStack/blob/master/dev/docs/logical-theme-system.md) could potentially be used to jerry-rig a notification system.
