### ISSUE TITLE
Add more Markdown syntax

### ISSUE THREAD

**Issue by ChrissyChien** [BookStackApp/BookStack#1401]
I would appreciate if it support more markdown syntax, e.g: > , to create a simple line in front of test.

It makes contents more beautiful.

**Comment by ssddanbrown** [comment]
Hi @ChrissyChien,
What currently happens when you try to use a markdown quote (`>`).
These should be already supported:

![image](https://user-images.githubusercontent.com/8343178/56455600-2de89580-6358-11e9-8f1c-5cd1920db680.png)

**Comment by ssddanbrown** [comment]
Since the original request is already implemented and since there's been no follow up I'll close this off.
