### ISSUE TITLE
css not properly loaded

### ISSUE THREAD

**Issue by stkac** [BookStackApp/BookStack#1403]
After build from this commit
https://github.com/BookStackApp/BookStack/commit/c24764018a9684fcf4418b359ddd793bb380063b
I get this css screen

![screenshot-wki wtmh dev-2019 04 19-21-07-51](https://user-images.githubusercontent.com/41887474/56439745-86cc1580-62e7-11e9-80f6-b895cb4f7128.png)

**Comment by ssddanbrown** [comment]
Hi @stkac,

CSS and JS is only built and committed on the release branch. 
Details of building the JS & CSS can be found here:
https://github.com/BookStackApp/BookStack#development--testing

Unless you're looking to specifically develop or test, you should remain on the release branch as all others are unstable and could cause you further issues.
