### ISSUE TITLE
Images in exported pdf does not look right

### ISSUE THREAD

**Issue by npelov** [BookStackApp/BookStack#1404]
**Describe the bug**
Left aligned image does appears under the text in pdf export

**Steps To Reproduce**
1. Go to https://demo.bookstackapp.com/books/bookstack-user-guide
2. export to pdf
3. Scroll down to page 3
4. Image does not appear correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/16647317/56469919-86975b80-6448-11e9-951e-82289214c4df.png)

**Your Configuration (please complete the following information):**
Tested on demo server

**Comment by ssddanbrown** [comment]
Thanks for reporting @npelov.

This has already been reported on issue #1288, So to reduce duplicates I will close this.
