### ISSUE TITLE
Add ability to customize shelf/book/chapter names

### ISSUE THREAD

**Issue by CorruptComputer** [BookStackApp/BookStack#1405]
My organization would love if we were able to change the name of shelves to "Departments", books to "Teams", etc. Would this be a feature which you would consider adding?

**Comment by Abijeet** [comment]
Hi @CorruptComputer 

Thank you for the feature request. The fundamental feature requested here is already open under #406 therefore I'm going to close this to cut down on duplicates. Please add a thumbs-up on the main issue #406 to show your support.
