### ISSUE TITLE
Date on Exported PDF is in UTC

### ISSUE THREAD

**Issue by sorvani** [BookStackApp/BookStack#1407]
When I export a PDF, the revision date and time are showing in UTC.

The system itself set to the correct timezone. 
![image](https://user-images.githubusercontent.com/3302372/56767788-44d12280-6772-11e9-9830-d6428ca3dd48.png)

I do not see any setting for controlling the timezone in the application itself.

Possibly related to the original request #83

**Comment by ssddanbrown** [comment]
Thanks for reporting @sorvani.

It looks like we added an option to set the app core timezone in v0.26 but I never tagged this issue for that release or came back and responded to this.

This option can be seen here: https://github.com/BookStackApp/BookStack/blob/00308ad4ab9302293afd0a65f815feeaca06b626/.env.example.complete#L35-L38

I'll therefore close this off, but if there's any trouble in using this option feel free to open a new issue.
