### ISSUE TITLE
css files are not found

### ISSUE THREAD

**Issue by lovesgg** [BookStackApp/BookStack#1409]
i have install it successful.
but when i login it show css files are not found.

Failed to load resource: the server responded with a status of 404 (Not Found)

/dist/styles.css?version=v0.25-dev
/dist/print-styles.css?version=v0.25-dev

the projects are not exists dist folder

**Comment by ssddanbrown** [comment]
Hi @lovesgg, it looks like you've cloned down the master branch, which is used for development. Try using the release branch which will include built CSS and JS assets.

**Comment by lovesgg** [comment]
ok.thanks.i have solved that.  the problem just like what you told me.i pull the wrong branch."--branch release --single-branch" is ok.




------------------ 原始邮件 ------------------
发件人: "Dan Brown"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午2:57
收件人: "BookStackApp/BookStack"<BookStack@noreply.github.com>;
抄送: "1287018390"<1287018390@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [BookStackApp/BookStack] css files are not found (#1409)




Hi @lovesgg, it looks like you've cloned down the master branch, which is used for development. Try using the release branch which will include built CSS and JS assets.

**Comment by ssddanbrown** [comment]
@lovesgg Great! will therefore close this.
