### ISSUE TITLE
Automatic Registration & Email Confirmation not working - still requiring confirmation

### ISSUE THREAD

**Issue by tylerlucas** [BookStackApp/BookStack#1412]
I saw issue #573, which may be related.  

BookStack v0.25.1

I have Google Auth enabled. I also have domain restriction enabled in BookStack.

I have added GOOGLE_AUTO_REGISTER=true to my .env file, but even after doing so, users are still being required to confirm email. Is this intended behavior?

**Comment by ssddanbrown** [comment]
Hi @tylerlucas,
To auto-confirm emails for google authentication users you can add the following `.env` option:

```shell
GOOGLE_AUTO_CONFIRM_EMAIL=true
```

Automatic registration is slightly different to automatic confirmation, details on this can be found here:
https://www.bookstackapp.com/docs/admin/third-party-auth/#automatic-registration-email-confirmation

**Comment by tylerlucas** [comment]
Gah, thanks Dan.

I misinterpreted the second code block as being the same as the first. I think this could be slightly more clear if you add another line to the wiki in bold before "If you trust a third-party login service you can enable automatic email confirmation”.

Thanks for the help.

**Comment by ssddanbrown** [comment]
@tylerlucas No problem! I've now updated the docs to be more clear, with the auto-reg and auto-confirm now under two separate headings so will therefore close this.
