### ISSUE TITLE
Allow svg-based images

### ISSUE THREAD

**Issue by nmehlei** [BookStackApp/BookStack#1413]
**Describe the feature you'd like**
In addition to the existing support of adding pixel-based images, it might be good to allow the user to include svg-files in a page. 

**Describe the benefits this feature would bring to BookStack users**
Especially for vector-based graphics and diagrams, exporting them to raster decreases quality and sharpness, especially when scaling is involved. This gets even more important since, as explained in #1108 , it does not seem possible to upload high-resolution images and scaling is used quite extensively and unavoidable in some cases. Allowing SVG-based images would help a lot here.

**Additional context**
Partially related to #1108

**Comment by ssddanbrown** [comment]
Thanks @nmehlei for your request.

Support for uploading SVG images is already open under #1103. Therefore I'm going to close this request to cut down on duplicates.
