### ISSUE TITLE
[Regression] Login Page Tabbing Order

### ISSUE THREAD

**Issue by FreeTheTech101** [BookStackApp/BookStack#1418]
**Describe the bug**
With the new interface introduced in BookStack v0.26.0, it seems that the tab order on the login page is no longer in order.

**Steps To Reproduce**
1. Click on "Log in"
2. Enter your username
3. Press the tab button
4. See the cursor jump to the search bar

**Expected behavior**
The cursor should jump to the password field.

**Screenshots**
![2019-05-06_15-34-02](https://user-images.githubusercontent.com/7614507/57250123-b6cc2600-7014-11e9-8193-583de197a3e1.gif)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: BookStack v0.26.0
 - PHP Version: 7.2.17
 - Hosting Method: Apache

**Additional context**
Loving the new user interface! I am glad to finally see it in full and cannot wait for the stable release.

**Comment by ssddanbrown** [comment]
Thanks for reporting the issue @FreeTheTech101, In addition to the nice feedback.

A patch has been applied to the master branch, Hoping to put out in a release tonight.
