### ISSUE TITLE
Support Grammarly

### ISSUE THREAD

**Issue by nmehlei** [BookStackApp/BookStack#1421]
**Describe the feature you'd like**
I'm using Grammarly constantly in my daily work. Grammarly is a really nice and useful browser plugin to help people like me who are not native to English to fix a lot of common mistakes while typing. As is usual with spell correction, errors are marked in red. Unfortunately, when using the editor of BookStack, those red markings are then somehow persistently saved in the saved content. Probably BookStack just stores the displayed HTML back again as it doesn't expect for external processes to change it. I disabled Grammarly for my BookStack wiki but as wikis are very text-intensive Grammarly would be even more important for a wiki than for most of the remaining internet. 

**Describe the benefits this feature would bring to BookStack users**
The benefit would be to allow great spell checking and correction for an application that is almost completely text-centric.

IF it is not the developers wish to support Grammarly then this problem can be partially avoided with adding a "data-gramm" attribute to disable Grammarly's spell checking, thus a user does not have to put it manually in an ignore list. But obviously support would be the better solution ;)

**Additional context**
While writing this entry I found https://github.com/quilljs/quill/issues/574 , which might contain a (partial) solution but I didn't have the time to understand it completely.

**Comment by ssddanbrown** [comment]
Since I do not intend to specifically support Grammarly and since this was not followed-up as an issue I'll close this off.

Thanks still @nmehlei for the detail in your original request.
