### ISSUE TITLE
[Question] webcrawler, search engine, sitemap

### ISSUE THREAD

**Issue by JHenneberg** [BookStackApp/BookStack#1422]
Hello,

I hava question concering search engine optimization. How good is a public Bookstack searchable for a search engine and is there anything I can do to optimize it? Create a sitemap or similar?

Great update (0.26.0) by the way  :)

Greetings Julian

**Comment by ssddanbrown** [comment]
Hi @JHenneberg,

> Great update (0.26.0) by the way :)

Thank you very much, glad you like it!

> How good is a public Bookstack searchable for a search engine and is there anything I can do to optimize it? Create a sitemap or similar?

To be honest I'm not really sure, The most likely uses for BookStack are within private or controlled environments, So I've not had much experience. I generally try to ensure headers are properly used and the editor kind of enforces clean code output which should help. BookStack is server-side generated with JS only used for dynamic areas so it should be well compatible with the search engine crawlers. 

BookStack does lack the use of many bits of metadata that sites often use to help SEO and parsing such as opengraph or schema.org tags.

A sitemap will help search engines at least find all your pages, probably worth doing, there's a few different online services that will quickly generate a sitemap for you.

To be totally honest, I'd imagine the hardest part will be the typically difficult SEO challenges of building your site reputation with reputable inbound links and providing fresh unique content for your focused target topics that will help you stand out.

**Comment by JHenneberg** [comment]
thanks for the answer so far. This is a good start to dig deeper.

**Comment by ssddanbrown** [comment]
@JHenneberg No problem, Since the original comment was answered I'll close this but feel free to open a new issue for future questions or feature requests.

**Comment by srinisubramanian** [comment]
Just in case this helps someone else who ends up here.  For our documentation site I needed to generate a sitemap.  Ended up creating a robots.txt file and excluded URLs like */export/, /search, /dist/ etc.  Then used ScreamingFrog to generate a sitemap and works great.  Quite simple for a sitemap.  The SEO bit with keywords etc will need some work from BookStackApp I guess.

**Comment by bridgeyuwa** [comment]
I decided today to try modifying my bookstack installation to automatically generate sitemap on create/delete/update. 

I hope it works, and if it does, I'll contribute it to the project.

**Comment by grugel-maintro** [comment]
Im also looking for an SEO solution any updates on this?

**Comment by rubensflinco** [comment]
Também busco isso, uso para meu site o BookStack que é um grande documentação de API, mas não tem o sitemap.xml seria ótimo se estivesse. segue meu site:
https://docapi.dev/

Alguma novidade?



EN-US:
I also look for this, I use BookStack for my website which is a great API document, but it doesn't have the sitemap.xml it would be great if it did. follow my website:
https://docapi.dev/

Any news?
