### ISSUE TITLE
Application Homepage applies Book view differently

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1423]
**Describe the bug**
The Book and Shelves views are applied differently on the homepage compared to the Books/Shelves pages. This leads to a lot of scrolling in the mobile view with the actual content of the books buried by the additional infos.

**Steps To Reproduce**
1. Go to Settings and change Application Homepage to Books
2. Switch to a mobile device/viewport and click on homepage
3. Click on menu > Books
4. Compare views

**Expected behavior**
The same design from the default Books site if choosen as the Homepage.

**Screenshots**
Homepage
https://i.imgur.com/47L63GR.jpg
Books
https://i.imgur.com/bQGrXqe.jpg

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):  BookStack v0.26.0 
 - PHP Version: 7.2.10
 - Hosting Method (Nginx/Apache/Docker): Apache 2

**Additional context**
The view in normal desktop version is slightly different, too.
On Books: Action menu on the right and the additional Info on the left way outside grayed out a bit until hovered over.
https://i.imgur.com/ulhjYS3.jpg

On Homepage: Action menu and additional info both on the left.
https://i.imgur.com/HLGsY0Q.jpg

I prefer in both mobile and desktop the default composition from the Books page.

**Comment by ssddanbrown** [comment]
Thanks @Bolthier for reporting.

Have now updated the custom home views to use the same layout system as the pages they imitate. Will be in the next release.

Some of the views can be a little awkward with the sidebars imbalanced but we can improve on that in future releases, Think it was important to primarily fix the bad mobile experience.
