### ISSUE TITLE
Fullscreen in editor showing save menu over editor in mobile view

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1424]
**Describe the bug**
When activating the fullscreen option of the editor in mobile view the menu with the save options is still shown.

**Steps To Reproduce**
1. Switch to mobile device/viewport
2. Edit a page
3. Activate fullscreen mode of the editor
4. See save menu still hovering over the editor

**Expected behavior**
Save menu to be hidden.

**Screenshots**
Before activating fullscreen
https://i.imgur.com/3IPLBAj.jpg
After activating fullscreen
https://i.imgur.com/aC8NZmT.jpg

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.26.0
 - PHP Version: 7.2.10
 - Hosting Method (Nginx/Apache/Docker): Apache 2

**Comment by ssddanbrown** [comment]
Thanks for reporting @Bolthier, I knew I shouldn't have been playing with z-index issues so close to release :sweat_smile: 

Was hoping to get in tonight's release but is actually a little tricky to ensure a fix doesn't break something else so am targeting the patch release thereafter.

**Comment by ssddanbrown** [comment]
Patch applied in master, to be in the next patch release.
Thank again @Bolthier.
