### ISSUE TITLE
Application Homepage shows Books without view permission through shelves

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1425]
**Describe the bug**
While using Shelves as the Application Homepage the title of Books without view permission can be viewed. The Shelve page does not show these titles.

**Steps To Reproduce**
1. Go to settings and set Shelves as Application Homepage
2. Create a book in a shelf
3. Set custom permissions so you shouldn't be able to view the book
4. Go to homepage and see the book title in list view

**Expected behavior**
The title shouldn't be visible like on the default Shelves page.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.26.0
 - PHP Version: 7.2.10
 - Hosting Method (Nginx/Apache/Docker): Apache 2

**Comment by ssddanbrown** [comment]
Thanks for reporting @Bolthier, I'll look to get a fix out for this tonight if possible, otherwise tomorrow night.

**Comment by ssddanbrown** [comment]
Fix now in master, with test to cover. Should being released tonight. Thanks again for reporting.
