### ISSUE TITLE
How to use certbot to redirect bookstack form 80 to 443?

### ISSUE THREAD

**Issue by donaldzou** [BookStackApp/BookStack#1430]
Hi, now I have http and https both enabled, but I want to force bookstack only 443. What should i do?

**Comment by ssddanbrown** [comment]
Hi @donaldzou, Your question is more of a webserver administration question that an question specific to BookStack. 

It will depend on what operating system, webserver software and how you've set-up HTTPS. If you provide those details then we may be able to provide more support.

If you used letsencrypt, via certbot, it usually gives you the choice to redirect HTTP traffic. 

You could set the `APP_URL` parameter in your `.env` file you start with `https://` but that won't force all requests to be https, only links generated by BookStack.

**Comment by Mant1kor** [comment]
@donaldzou It depends on the web server you use.

**Comment by lithium-c7ks7s** [comment]
> Hi, now I have http and https both enabled, but I want to force bookstack only 443. What should i do?

Hi, if you are using apache with certbot installed via apt or yum you it should prompt you during the final part of the cert generation. If not you will need to add a redirect to your virtualhost config or through .htaccess and rewrite module. This [article ](https://www.tecmint.com/redirect-http-to-https-on-apache/)is pretty straightforward. 

Like I mentioned tho... the final step in certbot asks you if you want certbot to create the redirect for you (both Apache and Nginx)

**Comment by lithium-ap** [comment]
> Hi, now I have http and https both enabled, but I want to force bookstack only 443. What should i do?

Hi, if you are using apache with certbot installed via apt or yum you it should prompt you during the final part of the cert generation. If not you will need to add a redirect to your virtualhost config or through .htaccess and rewrite module. This [article ](https://www.tecmint.com/redirect-http-to-https-on-apache/)is pretty straightforward. 

Like I mentioned tho... the final step in certbot asks you if you want certbot to create the redirect for you (both Apache and Nginx)

**Comment by ssddanbrown** [comment]
Thanks for the above responses.

Since the original issue creator has not responded, and since some useful information has been provided, I'll close this. If you continue to have problems feel free to open a new issue.
