### ISSUE TITLE
Toggle Details Button doesn't hide details once used with Guest user

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#1431]
**Describe the bug**
The Toggle Details Button doesn't work as intended for the Guest user. While the system is saving the preference in the cookies it doesn't save the undoing of it. Once details are enabled they stay visible for the Guest until the client browser clears its cookies or the user logs in and off.

**Steps To Reproduce**
1. Start a fresh browser session through a private tab.
2. Click on Toggle Details
3. Click on Toggle Details again so details should be hidden now again.
4. Reload the page.
5. Details on the sidebar are shown again.

**Expected behavior**
Toggle button should remember last setting with Guest user after using it a second time.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.26.0
 - PHP Version: 7.2.10
 - Hosting Method (Nginx/Apache/Docker): Apache 2

**Comment by ssddanbrown** [comment]
Thanks again for reporting @Bolthier, A fix has been applied in master to be in tonight's release.
