### ISSUE TITLE
Mail doesn't send.

### ISSUE THREAD

**Issue by ChristiaanDev** [BookStackApp/BookStack#1436]
**Describe the bug**
Copied my SMTP settings from Thunderbird (works properly there), set up the .env variables properly and I'm still getting: ``Email confirmation required but the system could not send the email. Contact the admin to ensure email is set up correctly.``

**Steps To Reproduce**
1. Go to 'Sign up' and enter all fields.
2. Click on 'Create Account'

**Expected behavior**
Bookstack to properly send e-mails.

**Actual behavior**
Bookstack warns that it couldn't send an e-mail.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.25.2
 - PHP Version: PHP 7.1.27
 - Hosting Method (Nginx/Apache/Docker): [Docker](https://hub.docker.com/r/solidnerd/bookstack)

**Additional context**
   ` - MAIL_DRIVER=smtp`
    `- MAIL_HOST=mail.*****************`
    `- MAIL_PORT=587`
   `- MAIL_FROM=wiki@*****************`
    `- MAIL_FROM_NAME=Wiki`
    `- MAIL_USERNAME=wiki@*****************`
    `- MAIL_PASSWORD=*****************`
    `- MAIL_ENCRYPTION=tls`

**Comment by Buddster124** [comment]
Did you fix this issue? I am having the same problem, is there a solution? Any help would be greatly appreciated.
