### ISSUE TITLE
Display on smartphones : unable to scroll down in editing mode

### ISSUE THREAD

**Issue by Zciwobukaj** [BookStackApp/BookStack#1439]
**Describe the bug**
When using Bookstack 0.26.1 with iPhone, it's impossible to edit and next scroll down the text. Particularly annoying with long content

**Expected behavior**
Text to edit should scroll down whether in computer or on mobile devices. This would make Bookstack a fully responsive tool.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): linuxserver / 0.26.1
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker): docker

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for reporting @Zciwobukaj.

I think this may be specific to iOS devices, I think safari has issues scrolling within an iframe. Will have to maybe re-think how the editor is laid-out for mobile. Will have to check the editor itself to ensure there's not going to be other fundamental issues anyway, even after fixing scrolling.

**Comment by Zciwobukaj** [comment]
Hi @ssddanbrown  , thanks for your reply.

I didn't precise it : I use Firefox for iOS when I perform my test on Bookstack.
Now, I check with Safari and the behavior is exactly the same.

**Comment by Zciwobukaj** [comment]
Hi again,

If you need inspiration, I found this article about how to make iframes scrollable on iOS : https://davidwalsh.name/demo/scroll-iframes-ios.php

**Comment by ssddanbrown** [comment]
Thanks for the additional information @Zciwobukaj.
I've found this is actually an already open issue here so I'm going to close this one just to reduce duplicates. 

Original issue: #1058
