### ISSUE TITLE
How to install on existing Laravel instance

### ISSUE THREAD

**Issue by NadimD** [BookStackApp/BookStack#1440]
Hello,

I would like to know how ot install BookStack on an existing Laravel instance and use its Laravel User's existing table.

I can't seem to find in the docs.

Thank you for your time. :)

Edit : Should I even do that ? The ReadMe states that there should not be interference., so I will have to install it in a folder ?

**Comment by ssddanbrown** [comment]
Hi @NadimD,

BookStack is not designed to be used as package, or as part of an existing app in any way. It is a standalone application. So unfortunately, the request you are asking for is not possible or supported.

**Comment by NadimD** [comment]
Hello @ssddanbrown ,
Thank you for answering. That's what I thought !
I'm closing this useless issue now ! :)
