### ISSUE TITLE
Unable to delete a page that was set as the Homepage after switching between homepage modes

### ISSUE THREAD

**Issue by nitrix** [BookStackApp/BookStack#1447]
**Describe the bug**
Unable to delete a page that was set as the Homepage after switching between homepage modes.

**Steps To Reproduce**
1. Go to Settings.
2. Choose the mode "Specific Page" for your homepage and select a page of your choice.
3. Save.
4. Change the mode back to either "Shelves" or "Books".
5. Save.
6. Now go see the page you previously had selected during step 2 and attempt to delete said page.
7. Error toast saying "Cannot delete a page while it is set as a homepage".

**Expected behavior**
Since the page is no longer used as Homepage, I would expect the page to be removable now.

**Your Configuration:**
BookStack v0.26.1

**Additional context**
I think this is a case of confusing UI. Notice that if the user selects again "Specific Page", they will see the pages that are marked as homepages listed and are then able to click "Reset". The problem is that switching between homepage _modes_ doesn't do this step for you.

Actually, I think it's two fold. Either that mark should get cleared when switching modes (not ideal), or the logic that shows the error should first ensure that the site is in "Specific Page" mode prior to denying you (much better idea).

**Comment by ssddanbrown** [comment]
Thanks for reporting @nitrix.

Fix now applied to master, ready for the next patch release. The page deletion will now not prevent deletion if the homepage type is not set to "Specific Page".
