### ISSUE TITLE
Search field missing in mobile view 

### ISSUE THREAD

**Issue by X52p** [BookStackApp/BookStack#1450]
**Describe the bug**
There is no Search field in the mobile version since the ui update.

**Steps To Reproduce**
1. Clicking on the menu with the three dots in the top right. 
2. In the menu click on search.
=> there is no text field

**Screenshot**
![Screenshot_2019-05-16-10-10-57-334_com yandex browser](https://user-images.githubusercontent.com/13068049/57837459-297e9380-77c3-11e9-970a-16b631f46fd0.png)

**Expected behavior**
There should be a text field to enter a search query. 

**Your Configuration (please complete the following information):**
 Using bookstack test instance from https://demo.bookstackapp.com

**Comment by ssddanbrown** [comment]
:man_facepalming: Yup, Totally thought there was another search bar on the search page itself when I made that change. My bad.

Have assigned to the next patch release.
