### ISSUE TITLE
Highlight search term in search results

### ISSUE THREAD

**Issue by jameswmcnab** [BookStackApp/BookStack#1451]
**Describe the feature you'd like**
Show and highlight the search term in each search result.

**Describe the benefits this feature would bring to BookStack users**
It is very helpful to have this additional context in order to select the search result most relevant to your query.

**Additional context**
Example of this in action for additional clarity (example used is Wikipedia):

![image](https://user-images.githubusercontent.com/718954/57931786-2a8dee80-78b1-11e9-91f8-893965964c56.png)

**Comment by ssddanbrown** [comment]
Hi @jameswmcnab,
Thanks for the detailed request, I think this is essentially already covered by #997. Therefore to cut down on duplicates I'll close this request.

**Comment by jameswmcnab** [comment]
Thanks @ssddanbrown!

I hadn't seen that issue when I searched before opening this but yes this is a duplicate.
