### ISSUE TITLE
Page Redirect Issue After Login

### ISSUE THREAD

**Issue by shayanderson** [BookStackApp/BookStack#1452]
If I'm logged into the Bookstack app I copy a URL like:
`https://mysite.com/books/my-book/page/my-page`

When that URL is used by a user that isn't logged in, they are asked to login. After login they are redirected to the URL:
`https://mysite.com/page/my-page`

However, that page is a 404 not found error. I assume because it is missing the "book" in the URL. Why are these URLs not redirecting properly? Should a page URL work without the "book" in the URL even if the page is in a book?

Am I missing something? Everything else in the application appears to be operating normally.

Thanks.

**Comment by ssddanbrown** [comment]
Thanks for reporting @shayanderson. I think I've seen this before, Will check the url logic for this redirect some point soon.

Possibly related to #1377.

**Comment by ssddanbrown** [comment]
A fix has been applied to master, ready for the next release. Thanks again for reporting.

**Comment by shayanderson** [comment]
Excellent. Thank you for the quick response and fix.
