### ISSUE TITLE
Shelf permission not propagating.

### ISSUE THREAD

**Issue by openmoto** [BookStackApp/BookStack#1455]
I created a shelf, then went to permissions and checked enable custom permissions.
Then added view check mark to public.
When I create a book within the shelf, I also have to either set permission on the book for it to be viewable by the public, or go back to the shelf permission and click on copy permission.

Is there a way to automatically propagate permissions on a shelf to books so that one can edit book permission if it needs to be different from the shelf, a d page permission of it needs to be different from the book..

Thanks

**Comment by ssddanbrown** [comment]
Hi @openmoto,
This has been previously question here:
https://github.com/BookStackApp/BookStack/issues/1091
Please see that thread which details the challenges of cascading shelf permissions and the current intended resolution.
