### ISSUE TITLE
IPhone : the "save" button disappears while editing a page

### ISSUE THREAD

**Issue by Zciwobukaj** [BookStackApp/BookStack#1456]
**Describe the bug**
On iPhone (i couldn't check on Android), the "save" button is not here while editing a new / existing page

**Steps To Reproduce**
1. Create a new page or edit an existing one
2. Scroll the top toolbar to the top. The button to add a comment to the latest modification is here but the button to save the page disappears

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.1
 - Hosting Method (Nginx/Apache/Docker): Docker
![A025FDDB-3C98-43A2-A1BE-620F4A43BA32](https://user-images.githubusercontent.com/35924688/57984685-7cc04280-7a5e-11e9-88ff-94170c74b2f3.jpeg)

**Comment by ssddanbrown** [comment]
Hi @Zciwobukaj,
On mobiles, The save button should move to the bottom of the screen as a floating action button, as shown in the bottom right of this screenshot:

![demo bookstackapp com_books_bookstack-user-guide_page_examples-of-different-content_edit(iPhone 5_SE)](https://user-images.githubusercontent.com/8343178/57984881-028cbf80-7a58-11e9-838f-8d3597ba81c3.png)

Does this button not show on your device?

**Comment by Zciwobukaj** [comment]
Hi @ssddanbrown ,

No this button is not here. Something related to this impossibility to scroll down maybe ?

**Comment by Zciwobukaj** [comment]
After checking with version 0.26.2 , the save button appears. Thanks ! 👍
