### ISSUE TITLE
SMTP extra options

### ISSUE THREAD

**Issue by sebastianlau** [BookStackApp/BookStack#146]
Currently swiftmailer tries to HELO as [::1] causing a rejection, it'd be good if server_name could be specified in .env which consequently runs $transport->setLocalDomain($server_name);

Additionally, settings for sender address and an email_base_url would be very useful to set in .env as emails are sent as BookStack mail@bookstackapp.com, and if a reverse proxy is in place the email url contains incorrect/internal links (e.g. http://localhost:8080/password/reset/......)

**Comment by armouredking** [comment]
Part of that is #88 and a function of Laravel. Laravel does not inherently trust proxies. You need to add in an extra layer that BSA doesn't currently include if you want BSA behind a proxy. Then your email links will be correct.

**Comment by ssddanbrown** [comment]
Hi @sebastianlau, In the `.env` file you can customize the sender address by adding a `MAIL_FROM` entry, For example:
```
MAIL_FROM=bookstack@mydomain.com
```
I'll look into your other issues at somepoint soon.

**Comment by ssddanbrown** [comment]
Now closing this due to the current master branch code having configurable proxy settings.
