### ISSUE TITLE
set default sorting order

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1461]
**Describe the feature you'd like**
Please add a option to define a default sort order per book.

**Describe the benefits this feature would bring to BookStack users**
At the moment every new page is at the bottom. Some users from us want that the book is automatically sorted by "Sort by Name" or "Sort by Updated Date"

**Additional context**
Thank you for this great tool 👍

**Comment by ssddanbrown** [comment]
Hi @JtheBAB,
Thanks for the request and for the feedback.

Since a very similar request is already open on issue #180 I'm going to close this one. Please give a "👍" to the original post of that issue to show support.
