### ISSUE TITLE
Attachment are always triggerd to download

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1464]
**Describe the bug**
When clicking to a attachment it always offers to download instead of using the default browser settings.

**Steps To Reproduce**
1. Go to a page with an attachment (pdf)
2. Click on the attachment link
3. Attachment is offered as a download instead of respecting the default behavior of the browser

**Expected behavior**
Bookstack should respect the default behavior of the browser. In my case open the PDF with the inbuild PDFReader from FireFox.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.1
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for the report @JtheBAB.

To be honest this is purposeful, to standardise how all attachments are handled. As soon as you stop forcing this behaviour it becomes unreliable as different file types will behave differently then this is multiplied by how browsers will handle  those different file types in a different manner.

**Comment by JtheBAB** [comment]
Hi  @ssddanbrown 

I see your point. But i think it would be better when the user settings are respected.

It came just now in my mind:

I don't know how complicated it is but why not add a setting on the "edit profile" page to control if it should be forced (default) or free?

**Comment by ssddanbrown** [comment]
> I see your point. But i think it would be better when the user settings are respected.

The trouble is, that it's often not up to the user. It's often up the browser and the overall users' system.

> I don't know how complicated it is but why not add a setting on the "edit profile" page to control if it should be forced (default) or free?

Would not be complicated to add but extra settings can be a burden on maintenance & support while opening the floodgates to more settings. Additionally, I'd imagine that admins in many multi-user environments would prefer consistency over user preference.

Perhaps we can look at achieving this in a different manner. The attachment link behaviour could stay as-is but have a little dropdown icon next to the attachment to select download type, Or a key modifier so a ctrl+click (Default open in new tab shortcut) opens it using browser behaviour.

**Comment by JtheBAB** [comment]
Sounds good :)

**Comment by mattkerrison** [comment]
Please implement this! PDFs just download instead of opening in a new tab, it’s so painful

**Comment by APlueckthun** [comment]
It would be extremely (!) appreciated by all of the users of BookStack in our place, if PDFs can be viewed inline, as opposed to being dowloaded. 
Why is this so important? We typically link scientific papers as PDFs, and without opening it, you cannot know whether this paper contains what you want. At the end, the download folder is full of PDFs. Conversely, if the PDF is opened inline, you can choose to download it, or let it disappear once the browser is closed.
We consider this the single biggest drawback of BookStack! And it would probably be easy to implement! And you would make a large numbers of users happy!

**Comment by APlueckthun** [comment]
Any way this is implemented is good. Whether this via the default browser setting or via an individual icon next to the link (download / inline view), both would be fine. 
But please implement this.

**Comment by rfrye** [comment]
I agree that the force download of PDF is a pain point for me. I dont have the solution for you, maybe a dropdown menu like you mentioned. Just wanted to be a voice that says its a pain point. 
Love Bookstack

**Comment by APlueckthun** [comment]
The resistance against implementing this change comes from the desire to treat all attachments the same. But this is the source of all misunderstanding. While most file types (.xlsx, .doc., or attached text files of any denomination) make no sense with anything else but download, PDFs are fundamentally different. PDFs are typically to be looked at, read, and not edited or worked upon. This is the very reason why many browsers have options to view them inline. 

The only thing we are asking for is to not overwrite this feature of the browser.

And to only do this for the file type PDF.

And if a browser does not support in line viewing, or the user has set other preferences, it gets downloaded anyway, so where is the damage?

If one is using BookStack for linking to lots of PDFs for the user to read up in depth on certain points, why prevent doing this in line? Why force the user to clutter his download folder with lots of PDFs, which then become unlinked to the original BookStack entry? 

I still hope this can be rectified. I just cannot discover any harm when treating PDFs separately from other file types, if the user has set his browser preferences accordingly.

Many thanks for reconsidering this! It would GREATLY enhance BookStacks (which is really great otherwise).

**Comment by ssddanbrown** [comment]
Within BookStack [v21.05.2](https://github.com/BookStackApp/BookStack/releases/tag/v21.05.2) it's now possible to open up attachments in an "inline" (Not forced download) via Ctrl+Click of the attachment (Or Cmd+click on Mac). Alternatively, an attachment link of this type can be manually formed by adding an `?open=true` query parameter to the link.

I'd still like to add some UI to the attachment items themselves so the access type can be chosen more intuitively (With better accessibility) but I could not come up with an approach I was happy with right now, Will need to have a deeper think about this from a design/accessibility perspective.

**Comment by npankaj365** [comment]
> 

For anyone wanting to loading PDF on side, I created the following snippet that implements what @ssddanbrown has shared. 
Sharing it here for reference if anyone's struggling. Placing this inside Custom HTML Head Content does the job. 
```
function previewPDF(item)
    {
        if( item.innerText.includes('.pdf'))
        {
            item.href += "/?open=true";
        }
    }
	window.onload = function(){
  		document.querySelectorAll('a').forEach(previewPDF);
    };
```

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off as the agreed upon implementation, [as per my comment above](https://github.com/BookStackApp/BookStack/issues/1464#issuecomment-496200398), [was essentially added as of v22.06](https://www.bookstackapp.com/blog/bookstack-release-v22-06/#attachment-link-dropdown).

**Comment by natkuhn** [comment]
Maybe I am missing more recent developments, but this is is asking readers who aren't super tech-savvy to jump through a lot of hoops. When you insert the link to a pdf attachment and then click on the link in the page, it does open a new tab ... but the tab wants to download the file. So go guide people to the pdf, I need to include a lot of text telling them to scroll in the sidebar, ctrl- or cmd-click, etc. I was hopeful that @npankaj365 's snippet above would work, but when I put it in the Custom HTML Head Content it did not seem to do anything on my version of Bookstack (v26.05.3), hosted on pikapods. If there's a way to fix that, I would be very grateful!

**Comment by julikaiba** [comment]
> Maybe I am missing more recent developments, but this is is asking readers who aren't super tech-savvy to jump through a lot of hoops. When you insert the link to a pdf attachment and then click on the link in the page, it does open a new tab ... but the tab wants to download the file. So go guide people to the pdf, I need to include a lot of text telling them to scroll in the sidebar, ctrl- or cmd-click, etc. I was hopeful that [@npankaj365](https://github.com/npankaj365) 's snippet above would work, but when I put it in the Custom HTML Head Content it did not seem to do anything on my version of Bookstack (v26.05.3), hosted on pikapods. If there's a way to fix that, I would be very grateful!

you just have to add "?open=true" to the end of the link, e.g. https://wiki.mysite.net/attachments/13?open=true when linking it on the page that way whenever its clicked the document gets opened in a new tab instead of being downloaded as long as thats possible
