### ISSUE TITLE
Title Wrap/Excerpt Doesn't Fit

### ISSUE THREAD

**Issue by blackshrub** [BookStackApp/BookStack#1469]
The title excerpt doesn't perfectly fit the end of the container

![Screen Shot 2019-05-27 at 20 00 39](https://user-images.githubusercontent.com/12421725/58421468-343a0200-80ba-11e9-808a-748a1373dbb1.jpg)

**Comment by ssddanbrown** [comment]
Thanks for the request @blackshrub.

Should probably bump up the character count from 35 to 40. 

Could alternatively potentially use [-webkit-line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) which surprisingly seems to have good browser support.

**Comment by ssddanbrown** [comment]
As of 4b4642c8ea58aa91cfe9b83095d2d420f608ad4d the limiting will now be done with css so that it's limited to two lines rather than being limited by a hardcoded, guessed limit.

Will be part of the next release. (v0.31)
