### ISSUE TITLE
Restoring

### ISSUE THREAD

**Issue by DirtyBeard** [BookStackApp/BookStack#1471]
Not a super technical person but maybe you can help. Followed the Backup and Restores procedures without issue. As suggested in your guide I attempt to run `sudo php artisan migrate` from `/var/www/bookstack`

Fresh install today on Ubuntu Server 18.04.2 using the 18.04 Ubuntu Script

Here is the output:
![Capture](https://user-images.githubusercontent.com/6845282/58466025-bf80bb00-80ed-11e9-8cf5-bdae2961e462.PNG)

At a loss here, basically after import I am greeted to a blank page when navigating to my bookstack url.

Thanks,
Drew.

**Comment by ssddanbrown** [comment]
Hi @Xtreme21, Sorry to hear you are experiencing issues.

From the error shown, BookStack cannot even get access to the database. Is the database running locally on the server and does the `bookstack` user exist in your database with a password matching that defined in your BookStack `.env` file?

**Comment by ssddanbrown** [comment]
Closing as there was no follow-up on this.
