### ISSUE TITLE
Print CSS not optimized for new UI

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#1472]
Since the v0.26 updated UI, printing a page from Firefox or Chrome results in a non-optimized result.

## Firefox Result

* Pave navigation is not hidden and gets an entire page to itself
* Page content is very narrow
* Box-shadow show around page content
* Only the first page of content prints, likely due to Firefox's [flexbox printing issues](https://bugzilla.mozilla.org/show_bug.cgi?id=939897)

<img width="167" alt="bookstack-firefox-print" src="https://user-images.githubusercontent.com/1438193/58560312-7b271500-81ea-11e9-9bcd-73dffa7ff42c.png">

## Chrome Result

* Page navigation is not hidden
* Page content is very narrow
* Box-shadow shown around page content

<img width="166" alt="bookstack-chrome-print" src="https://user-images.githubusercontent.com/1438193/58560355-94c85c80-81ea-11e9-8144-155da10484cf.png">

**Comment by ssddanbrown** [comment]
Thank you @abulgatz for reporting.
Updates now done in master, Will be part of the v0.27 release.
