### ISSUE TITLE
Firefox tablet view-width pushes page navigation far down

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#1473]
**Describe the bug**
In Firefox, between the full desktop view-width and the phone view-width, the "Page Navigation" gets pushes far down on the left column, with a huge amount of space between the Page Navigation and the Details/Actions area above.

This is not an issue in Chrome.

**Steps To Reproduce**

1. Open page in Firefox
2. Resize page to a "tablet" width.

**Expected behavior**

Should match chrome, where Page Navigation is directly below Details/Actions, with no large space.

**Screenshots**

<img width="187" alt="bookstack-firefox-page-navigation" src="https://user-images.githubusercontent.com/1438193/58561887-cd1d6a00-81ed-11e9-9ba3-5de08ced4d0a.png">

**Your Configuration (please complete the following information):**
 - v0.26.2
- MacOS 10.14.4
- Latest Chrome and Firefox

**Comment by JHenneberg** [comment]
duplicate of #1434

**Comment by ssddanbrown** [comment]
Thanks for reporting @abulgatz.

Since this is a duplicated, as reported above, I'll close this.
