### ISSUE TITLE
Mail not sending

### ISSUE THREAD

**Issue by simplesolution** [BookStackApp/BookStack#1474]
When configuring smtp, the registration-mail is never sended and I just get an error in the frontend. Nothing is showing up in the logs.

I've already read about this problem, but couldn't find any solutions.

**Comment by ssddanbrown** [comment]
Hi @simplesolution,
Have you configured any of the mail settings in the `.env` file or are they left as-is?

**Comment by simplesolution** [comment]
Hi @ssddanbrown!

I have configured following mail settings:

- MAIL_DRIVER=smtp
- MAIL_HOST
- MAIL_PORT
- MAIL_ENCRYPTION
- MAIL_FROM
- MAIL_FROM_NAME

I have not configured MAIL_USERNAME and MAIL_PASSWORD, since authentication is not required on our Microsoft Exchange Mail Account. But I already tried out configuring them and it did not change anything.

**Comment by timoschwarzer** [comment]
I have the same problem.

```
MAIL_DRIVER=smtp
MAIL_HOST=mail.myserver.com
MAIL_PORT=465
MAIL_USERNAME=mailgun@myserver.com
MAIL_PASSWORD=pass123
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=mailgun@myserver.com
MAIL_FROM_NAME="John Doe"
```

BokkStack shows that an E-Mail has been sent but it never reaches the SMTP server (according to its logs). There are no errors or whatsoever in BookStack's log files. It's really strange...

**Comment by timoschwarzer** [comment]
interesting note: Giving an invalid password results in a 500 (as expected). Seems like it tries to login but not actually sending the e-mail.

**Comment by nimmerdk** [comment]
We're having the same problem on our Exchange server. 
And can't find anything in any log that shows error. Maybe I'm looking the wrong places, plz help.

/nimmer

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
