### ISSUE TITLE
Mixed content on pages. 

### ISSUE THREAD

**Issue by escservices** [BookStackApp/BookStack#1477]
**Describe the bug**

Mixed content on pages with images that were created prior to us changing the APP_URL to https.  I had the issue with the logo as well as mentioned in "Mixed content #936 " and re-uploading it resolved the issue but I can't go through and update a ton of KB's that have images.  

**Steps To Reproduce**
1. Go to any "page" with images (Shelf -> Book -> Chapter -> Page)
View chrome dev tools, all images on the page were loaded with http not https.
(Only occurs on pages that were created when site was using http by default)

**Expected behavior**
All images be loaded over https, even if they were uploaded and added when the site was using http.

**Screenshots**
![image](https://user-images.githubusercontent.com/1287511/58734550-b598d980-83c5-11e9-8e02-0bc3990675d5.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.26.2
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @escservices,
An app URL change does currently have such effects as you're experiencing, where content using the old domain persists in the database. The easiest way to manage this at the moment would be to perform some replace queries on the content within database if you're handy with SQL. Details of this can be found [here](https://github.com/BookStackApp/BookStack/issues/1224#issuecomment-455320075), I detail extra database to update in the column below. Remember to back-up the database before making any changes.

We do have an open issue to make this easier in the future, via app command, here: #1225.

**Comment by escservices** [comment]
I see, thanks @ssddanbrown.  I found the SQL queries and was able to get everything updated.  Thanks for the help!

**Comment by ssddanbrown** [comment]
@escservices No worries, happy to hear you got things sorted!
