### ISSUE TITLE
Cant update, "Your requirements could not be resolved to an installable set of packages"

### ISSUE THREAD

**Issue by dewzor** [BookStackApp/BookStack#1481]
As im a huge linux noob i spent almost an hour just getting to the point of where i could run the update command from the bookstack install folder. When running the command and getting past earlier permission errors, i finally get this error: "Your requirements could not be resolved to an installable set of packages"

I googled it and its probably because of that some of the packages inside the set of programs to be installed have been updated so its dependent on something thats not included or something like that. I hope this can get fixed as i love Bookstack and would like to update it! Still on ver 20 :S

**Comment by ssddanbrown** [comment]
Hi @dewzor,
Do you get any extra output below the "Your requirements could not be resolved to an installable set of packages" message? I'd expect it to list the unresolvable packages. If possible, please post as much of the command line output as possible that you get when running the update command.

**Comment by ssddanbrown** [comment]
Closing since there has been no further followup on this.
