### ISSUE TITLE
WordPress to BookStack

### ISSUE THREAD

**Issue by HujinoKun** [BookStackApp/BookStack#1489]
Hello,

I just offered bookstack to my company. They agree to put the tool into a VM.

However, we have a wordpress wiki. As a result, I have two questions :

- How will I be able to migrate all articles from wordpress to bookstack?

- We already have an authentication system in a database, it's possible to use it for bookstack without much difficulty?

Best regards,

**Comment by ssddanbrown** [comment]
Hi @HujinoKun,

> How will I be able to migrate all articles from wordpress to bookstack?

As it stands there's not really any migration tools to get content into BookStack. The ease of this would depend on the format the content is stored in WordPress. It may be a case of coping across content manually. An API is on the roadmap for BookStack to help people script such scenarios in the future.

> We already have an authentication system in a database, it's possible to use it for bookstack without much difficulty?

BookStack does not support other database-authentication systems. It does support LDAP based authentication or any of the third-party solutions listed here:
https://www.bookstackapp.com/docs/admin/third-party-auth/

**Comment by thefury24** [comment]
Just wanted to leave a comment since this is a high Google result. This node js script will take a Wordpress XML file and convert it to Markdown which can be pasted into Bookstack. Still some manual work but better than nothing.

https://github.com/lonekorean/wordpress-export-to-markdown
