### ISSUE TITLE
v0.26.2 Chrome Layout Bug

### ISSUE THREAD

**Issue by pwilken** [BookStackApp/BookStack#1490]
**Describe the bug**
Since the v0.26.2 updated UI, the UI Layout looks destroyed in the Chrome Browser.

**Steps To Reproduce**
1. Open Chrome
2. Open bookstack url

**Screenshots**
![image](https://user-images.githubusercontent.com/34198662/59441725-54c3c500-8df9-11e9-9475-b6d4f746217f.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.2
 - PHP Version: PHP 7.1.30 (cli)
 - Hosting Method (Nginx/Apache/Docker): Docker
-  OS: macOS 10.14.5
-  Browser: Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by ssddanbrown** [comment]
Hi @pwilken,
From your screenshot I can tell the loaded styles are for an older version of BookStack and do not match those released as part of v0.26 or above. This mismatch may be causing the issue that you can see.

How are you performing updates for your docker container(s)?

**Comment by pwilken** [comment]
Hi @ssddanbrown,
thanks for your fast reply. The problem was the chrome cache, sorry for that.

I wish u a great weekend.
