### ISSUE TITLE
MSSQL Errors throughout entire process of creating a book

### ISSUE THREAD

**Issue by LukeARG** [BookStackApp/BookStack#1493]
**Describe the bug**
Getting this set up with MSSQL has been 3 headaches and a half.

**Steps To Reproduce**
1. Go to anything once the initial setup in IIS is done
2. Click on Create a book
3. ???

**Expected behavior**
I expect it to work. Every error is related to a SQL statement.

**Screenshots**
![image](https://user-images.githubusercontent.com/37671655/59537694-4b079380-8ec5-11e9-9816-de05deb1f91d.png)

**Your Configuration (please complete the following information):**
 - BookStack v0.26.2
 - 7.3
 - IIS 

**Additional context**
It seems like every issue is related to something not being nullable or there not being a default value. So far I've been making every default value "1" manually, but I don't know what this could effect long term.

If someone could help out by letting me know what default value should be set for everything, or what is okay to make nullable, would be super helpful.

Thanks,
Luke

**Comment by ssddanbrown** [comment]
Hi @LukeARG,
Sorry to hear you're having difficulties with the setup process.

The issue is that BookStack does not support MSSQL, only MySQL, hence why you are experiencing issues.

**Comment by LukeARG** [comment]
Is there any way to make it compatible? Or am I just SOL?

**Comment by ssddanbrown** [comment]
@LukeARG It could be made compatible, but it's not something I'm looking to do or, more importantly, support at this time, Sorry. My detailed thoughts on support for other DB systems [can be read here](https://github.com/BookStackApp/BookStack/issues/76#issuecomment-494956958).

**Comment by LukeARG** [comment]
No worries! I love what you're doing with the project, and after reading that I'm in full support of you, Dan. Closing this, maybe down the line I'll play with it and can create something that I'll make a fork/branch (still learning this platform). 

Thank you!
