### ISSUE TITLE
common user(except admin) can not add comments 

### ISSUE THREAD

**Issue by kentwei** [BookStackApp/BookStack#1495]
Common user(except admin) can not add comments 

![图片](https://user-images.githubusercontent.com/3234313/59577063-a8355c00-90f4-11e9-8f68-5d65a19cea54.png)

**Comment by ssddanbrown** [comment]
Hi @kentwei,

Sorry I missed this issue when you originally created it. I've just given this a test and it appears to now work on the current version of BookStack so has likely been fixed in the past year. If the issue remains feel free to open a new issue to address this.
