### ISSUE TITLE
Cannot create or edit any book

### ISSUE THREAD

**Issue by dusatvoj** [BookStackApp/BookStack#1496]
**Describe the bug**
After upgrade to 0.26.2 from 0.18.5 there's unable to change or create any page.
In edit window is only blank space.

**Steps To Reproduce**
1. Try to create or edit a page.

**Expected behavior**
Edit window is shown.

**Screenshots**
<img width="779" alt="Screenshot 2019-06-17 at 17 39 56" src="https://user-images.githubusercontent.com/11560794/59617866-6540ac00-9127-11e9-90b2-f28d85f332fb.png">

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.2
 - PHP Version: 7.0.33
 - Hosting Method (Nginx/Apache/Docker): Debian 9 with apache 2.4.25-3+deb9u7

**Comment by ssddanbrown** [comment]
Hi @dusatvoj, Sorry to hear your are having problems.
Are you able to edit the page when using admin account?

Otherwise, did you receive any errors when running the update commands?

**Comment by dusatvoj** [comment]
Hi, I've found the error. We have a production server with debian. There were apt composer v1.2.2 (released 2016). With latest composer is everything allright. Can you add minimum version of composer to install?
Thank you

**Comment by ssddanbrown** [comment]
Happy to hear you solved the issue!

Yeah, some Debian packages can be quite outdated. Don’t really want to keep on top of composer releases to maintain a minimum version. The ultimate goal is to remove composer as a production dependency.
