### ISSUE TITLE
Line does not break for very long inline code elements (information loss in html and pdf export)

### ISSUE THREAD

**Issue by Zaptro** [BookStackApp/BookStack#1507]
**Describe the bug**
I use inline codes for ssh commands that can become very long. Viewing them in the web view the code line sometimes extends out of the content area and adds a horizontal scrollbar which looks a bit odd, but no information is lost. But exporting to pdf or html simply cuts off the lines (tested with current version BookStack Beta v0.26.2).

**Steps To Reproduce**
1. Switch on Inline Code format and type in a very long line.
2. Export to html or pdf.

**Expected behavior**
I expected that the inline element would break the line at width of the web view content area and continue in the next line. The next line the grey background should maybe not have a vertical line at the beginning (left border of the box), indicating that this is still the same line of code. The same behaviour should happen in the html or pdf export file.

**Your Configuration (please complete the following information):**
 - BookStack Beta v0.26.2

**Comment by james-geiger** [comment]
@Zaptro See issue #1575 for a possible solution and provide feedback there as these seem at least tangentially related.

**Comment by ssddanbrown** [comment]
This has been fixed as part of #1587. That fix will be in the next feature release so I will therefore close this issue.
