### ISSUE TITLE
group of users access based to a specific book

### ISSUE THREAD

**Issue by iyadahmad** [BookStackApp/BookStack#1511]
There is no group or users access based , only per Role. right ,  why ? 

If what I'm talking about is really exist please tell me how to do that.

Thanks a lot

**Comment by ssddanbrown** [comment]
Hi @iyadahmad,
That's correct, You can only currently manager access permissions at role level. For individual permission you'd have to create a single-user role.

Not really sure what you mean by group, The grouping of users in BookStack is a "role".

**Comment by ssddanbrown** [comment]
Since the question was answered I'll close this off.
