### ISSUE TITLE
Error page should show a login notice

### ISSUE THREAD

**Issue by miterion** [BookStackApp/BookStack#1513]
**Describe the feature you'd like**
Currently, if a user is not logged in and visits a non public page a generic "Page not found" error is shown. Inexperienced users might not realize, that the page might be available to them if they would log in.
![before](https://user-images.githubusercontent.com/4395770/60336942-00e0e080-99a2-11e9-87e1-481e000b90be.png)

I suggest to amend this page with something like this:

>
> ### Page not found or not logged in
> #### Sorry, The page you were looking for could not be found or is only available after login.

**Describe the benefits this feature would bring to BookStack users**
Reduce confusion for new users when clicking on links from outside the bookstack environment (e.g. from Slack).

**Additional context**
A possible mockup for this:
![after](https://user-images.githubusercontent.com/4395770/60337037-3dacd780-99a2-11e9-821d-22d01c5223e8.png)

**Comment by ssddanbrown** [comment]
Thanks for your request @miterion.

As part of release v0.28.3, The wording on the 404 page was updated to indicate permissions may be hiding the content, And a login button was added to that section as a suggestion that the user may need to login. The changes can be seen in my comment here: https://github.com/BookStackApp/BookStack/issues/1706#issuecomment-599118692

Hopefully that covers this. If not, feel free to raise any concerns on a new issue, referencing this one.

**Comment by miterion** [comment]
That's a great solution, thank you very much :)
