### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by playNoA** [BookStackApp/BookStack#1514]
Hello
I installed a simple test in the virtual machine today, basically can meet my needs, thank you for your contribution;

In use, I found that there is no permission management system. For example, I don't want to publish bookshelves or books to everyone. The current roles and users seem to be created only for use, and there is no isolation policy; the entire site has no privacy. Can be set;

Also, I may not want any user to export the document at will, which is part of the rights management;

I noticed that this project is newly established, so do you plan to add rights management in the future?

**Comment by ssddanbrown** [comment]
Hi @playNoA,
There are quite a few permission options in BookStack. 
You can control global default access to items and settings on a role level via the role configuration.
On each shelve, book, chapter & page you can also assign custom per-role permissions.

A global option to enable/disable public access is available in the application settings. With this enabled you can control what's enabled for public users via controlling the public/guest role.

**Comment by javisomoza** [comment]
Hello
Default permissions for books, pages,... allow access to guest (public) access.
I think it would be better to allow public access only if you grant the permission explicitly instead of being granted by default.
I find no way of changing the default permissions of the created objects (books, etc...). Is there any?
Thanks!

**Comment by javisomoza** [comment]
No problem, by assigning a different default role to the "guest" user is possible and working!

**Comment by ssddanbrown** [comment]
Since the last comment, from the issue creator, relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
