### ISSUE TITLE
Option to use external profile picture source

### ISSUE THREAD

**Issue by coaqii** [BookStackApp/BookStack#1515]
**Describe the feature you'd like**
When using AzureAD authentication we would like the profile pictures to be the same as the user has configured in Office 365.

**Describe the benefits this feature would bring to BookStack users**
This would add a layer of personalisation between colleagues. Currently the profile picture is pretty useless.

**Comment by ssddanbrown** [comment]
Thanks for the request.
I'm going to close this as an effective merge with #2368 since they cover the same fundamental request here.
