### ISSUE TITLE
[HELP] Migrate AUTH_METHOD from Standard to LDAP

### ISSUE THREAD

**Issue by dusatvoj** [BookStackApp/BookStack#1521]
Hello, is there any way to migrate existing BookStack from _standard_ to _ldap_ AUTH_METHOD (in the best case with some link option to existing accounts)?
Thanks for help

BookStackApp v0.26.2 with MySQL

**Comment by ssddanbrown** [comment]
Hi @dusatvoj,

BookStack links BookStack users to LDAP users via the `uid` LDAP attribute. Upon LDAP login, BookStack checks the users table to see if that UID already exists and, if so, logs the submitter into BookStack as that user. 

When LDAP is enabled and you view an existing user, as an admin or `manage-users` account, you'll be able to see the "External Authentication ID" field in their profile. You can fill this in to set the `uid` for an existing non-LDAP user.

![image](https://user-images.githubusercontent.com/8343178/60619247-1efa7680-9dd0-11e9-80e6-cedda33dc41d.png)

If you have many users to match up you may find it quicker to directly edit in the database. You can set the `external_auth_id` column of the `users` table to achieve the same thing. 

Hope that helps!

**Comment by dusatvoj** [comment]
Thank you @ssddanbrown,
I will try it.

**Comment by ssddanbrown** [comment]
Okay, Now that the original question has been answered I will close this.

**Comment by dbergniche** [comment]
hello @ssddanbrown I am having this exact same issue, I was wondering what exactly you would put in the External Authentication ID field. As in uid=(users ID), or just the uid? a uid would be most likely be in the format of jsmith, correct?
