### ISSUE TITLE
Document Voting feature

### ISSUE THREAD

**Issue by openmoto** [BookStackApp/BookStack#1524]
**Describe the feature you'd like**
Voting feature: Ideally allow registered user to click on the "Worked for me" button to increase the count. Great if the option can be 'renamed' to upvote/downvote or any other to suite the use case.

Optionally allow feedback and give reader the chance to explain what went wrong privately [not another wordpress ;) ] 

**Describe the benefits this feature would bring to BookStack users**
This will allow document creators/editors to ask or collect information on where it failed and improve their documentation either by tagging to show what it applies to, or adding more details. 
One thing I've learnt since I've been writing IT documentation is that we often think we did a great job explaining "like I'm 5", till you realize someone can't use your notes because they have no clue what "desktop" is and tell you it doesn't work because they're on a laptop.

**Comment by ssddanbrown** [comment]
Thanks for the request here @openmoto but I'm going to close this one off as out of scope. This would be quite an opinionated feature, being useful for just a portion of the user-base. It would require an array of customization options and would likely lead to further requests or needs such as a dashboard for viewing the voting or reading/managing the feedback. Additionally, this has had little support over the last 18 months.
