### ISSUE TITLE
Clean up code suggestion for permission system and etc.

### ISSUE THREAD

**Issue by imanghafoori1** [BookStackApp/BookStack#1528]
Hi, I reviewed your code base and saw that you can clean up and make it more flexible and modular using my open-source laravel packages, (like : laravel-widgetize, laravel-heyman, laravel-decorator)

I can create PRs for you, but before that I wanted to ask if you allow for additional composer dependencies in pull requests or not ?

**Comment by ssddanbrown** [comment]
Thanks for the offer @imanghafoori1 but I'd prefer not to increase the dependencies without clear requirement or benefit to the project.

**Comment by imanghafoori1** [comment]
Of course it has clear benefits for code quality, but it still depends on the fact that how much you want your code to be cleaned up, or you are happy with it, that it just works.

**Comment by ssddanbrown** [comment]
Yeah, that's fair but familiarity, style and opinion also factor in I think. I'll close this for now but feel free to add a comment with a link to your re-write, once done, as I'm always interested to see real-life code organisation patterns.
