### ISSUE TITLE
Change user name display format in toolbar

### ISSUE THREAD

**Issue by alexmellott** [BookStackApp/BookStack#1529]
**Describe the feature you'd like**
Would like to have an option to change the user's name format in the upper toolbar. For example, John Doe would no longer appear as just "John". Instead, it would show up as "Doe, John".

**Describe the benefits this feature would bring to BookStack users**
Enterprise use functionality might require this naming format for internal reasons.

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @avm5689.

This is getting into the detail a bit so I'd probably not look to implement an option to control this but it might be something that would be easier to do via view customization in the future, once the theming system is a little more official.

Just a note, BookStack will attempt to show the full name (`John Doe`) if possible then will shorten down to the first word (`John`) if the full name is longer than the display limit.
