### ISSUE TITLE
Prevent Export

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1530]
**Describe the feature you'd like**
It would be great if we could define system wide or perhaps per book that it is not allowed to export the book.

**Describe the benefits this feature would bring to BookStack users**
Bookstack is a important wiki for us with a lot of knowledge, that users when they leave can easy export with a single click. Providing the option to hide the export button system or book wide can help to prevent leaking knowledge.

I know this will not prevent it completely, as of couse someone could print or copy page by page but it takes much more effort/time then just to click one button.

**Comment by ssddanbrown** [comment]
Hi @JtheBAB,
Thanks for proposing this feature.
This has already been requested under #1251 so I'll therefore close this as a duplicate.
My thoughts on this kind of feature can be found in my first comment there. I also have posted a code sample that allows you to hide the buttons in my second comment. I'll add a new sample to that issue that works with the recent redesign.
