### ISSUE TITLE
mail not sending

### ISSUE THREAD

**Issue by bugyak** [BookStackApp/BookStack#1532]
**Describe the bug**
I set mail config in .env file but mail do not send
i set debug=true in .env file when mail do not send but no logs
the mail config copied from other laravel projet 
version: latest release

**Comment by ssddanbrown** [comment]
Hi @bugyak, 
Sorry to hear you are having problems with email sending.
Are you hosting BookStack directly via Nginx/Apache are do you have a docker or reverse proxy setup?

Are you able to post any of your mail settings? You can omit any keys or usernames but other parameters would be helpful to see.

**Comment by Irrational-NX** [comment]
Hello @ssddanbrown , let me add more info on this matter (I also had problem for sending mails)

Bookstack (0.22) is working for me with Nginx.
I tried modifying everything in the .env file, but could not get a single mail out from the server using Office's SMTP. I did not found a single log either (from nginx or laravel logs)
But then... I modified this file : bookstack/config/mail.php 
and bam. The mails were working fine.

**Comment by ssddanbrown** [comment]
@Irrational-NX Thanks for the input. Could be a case of people with cached configuration in that case then. Running `php artisan config:clear` from the app directory may help.

Just as a warning, the `/config` files are not intended to be edited and could cause issues on update (They'll be moving on next release).

**Comment by bugyak** [comment]
@ssddanbrown php artisan config:clear works! but why it work?

**Comment by ssddanbrown** [comment]
@bugyak :tada: Glad to hear you got things working, Will therefore close this. Not sure why your config was cached. Will need to see if this happens automatically anywhere, Some artisan commands will cause config caching.
