### ISSUE TITLE
Edit drawings after creation

### ISSUE THREAD

**Issue by aarroonn789** [BookStackApp/BookStack#1537]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.

**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @aarroonn789,
Can you confirm what editor you are using?

Editing drawings is currently possible. You should be able to just double click them to open them back up in the editor.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
