### ISSUE TITLE
Kanban board integration

### ISSUE THREAD

**Issue by Zaptro** [BookStackApp/BookStack#1539]
**Describe the feature you'd like**
Would it be terrible complicated to integrate a kanban board like [Wekan ](https://github.com/wekan/wekan/wiki) into BookStack? You did integrate draw.io which is great. I dont know enough about programming to estimate the effort to do such a thing with Wekan for example or if there are other issues that prevent from doing such a thing.

**Describe the benefits this feature would bring to BookStack users**
In my opinion integrating a kanban board to bookstack would increase the attractivity of bookstack as a knowledge and productivity suite even more.

Let me know what you think about this idea.

Yours sincerely
Zaptro

**Comment by ssddanbrown** [comment]
Hi @Zaptro,
Sorry for my late reply and thanks for the idea. Unfortunately Kanban board integration will be out of scope for the core project, BookStack is not intended to handle any project or task management. It will take a fair bit of effort while not really fitting into the purpose of the project. 

Maybe it's something someone could build easier once we implement an API but for now I'm going to close this off as out-of-scope.
