### ISSUE TITLE
Javascript Copy Functionality

### ISSUE THREAD

**Issue by typkrft** [BookStackApp/BookStack#1547]
**Describe the feature you'd like**
I am trying to add a button would copy text to the clipboard. I think this would be a beneficial functionality for a number of users. 

**Describe the benefits this feature would bring to BookStack users**
I believe this is supported in all modern browsers. Use Case: IT Dept Using Bookstack as a Kbase. The Admin creates a page with canned responses. The user simply finds the response clicks a copy button and then can go on and paste that in an email or chat. 

**Additional context**
I've tried to implement it using variations of the HTML and JS here. https://www.w3schools.com/howto/howto_js_copy_clipboard.asp However IDs and Classes and Script seems to be scrubbed out occasionally or changed. I've also tried implementing https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js to no avail.

**Comment by ssddanbrown** [comment]
Hi @typkrft,

BookStack does already support click-to-copy functionality on code blocks:

![image](https://user-images.githubusercontent.com/8343178/62413731-2e0c5880-b60a-11e9-9bb7-b2209638c222.png)

In you use-case, you could simply format each of your canned responses as a code block which will show this copy button upon hover. 

Does this suit your need?

**Comment by typkrft** [comment]
I think this could work. Thanks for your response and to the Dev teams hard work.

**Comment by ssddanbrown** [comment]
@typkrft No worries! Will therefore close this off.
