### ISSUE TITLE
Ability to control meta description

### ISSUE THREAD

**Issue by RealityShift** [BookStackApp/BookStack#1549]
**Describe the feature you'd like**
The ability to control the meta description for pages/books.

**Describe the benefits this feature would bring to BookStack users**
We, personally, are using bookstack for internal AND public information (mostly API documentation). The public versions we would like to include meta descriptions on the pages so our SEO doesn't get hit for missing descriptions OR duplicate across several URLs

**Comment by ssddanbrown** [comment]
Thanks for opening this request @RealityShift.

To be totally open and honest, This is the kind of small scale option/control I'd prefer to avoid in BookStack for now, at least as some kind of "Meta/SEO description" field.

Maybe instead we'd implement something like that requested in #1126 and then update BookStack to use that as a meta description.

**Comment by RealityShift** [comment]
Completely understandable! I've forked your project and added this ability in for our use case. 

![image](https://user-images.githubusercontent.com/15909325/62427612-7c316280-b6c3-11e9-9588-2783c0a2f7a0.png)

I will be sure to watch for future updates on #1126 :) Thanks for the hard work on the project by the way, we love it!
