### ISSUE TITLE
No syntax highlighting exists for PHP

### ISSUE THREAD

**Issue by codemicro** [BookStackApp/BookStack#1557]
**Describe the bug**
You can select syntax highlighting for PHP in code blocks, but no highlighting is applied when no `<?php` is added to the top of the snippet.

**Steps To Reproduce**
1. Draft a new page
2. Click on Formats > Code Block
3. Select PHP from the list
4. Type some PHP without `<?php`
5. Tada! No syntax highlighting

**Expected behavior**
Syntax highlighting should be applied to the code block like it would if Javascript or Python were to be selected, even without `<?php`

**Screenshots**
With JS
![image](https://user-images.githubusercontent.com/25284325/62010303-1f80f580-b161-11e9-91b6-ea5c398fc25c.png)
With PHP
![image](https://user-images.githubusercontent.com/25284325/62010306-2a3b8a80-b161-11e9-962d-a0dc74f343d3.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: BookStack v0.26.3 
 - PHP Version: PHP Version 7.2.19
 - Apache2 on a DigitalOcean VPS

**Comment by ssddanbrown** [comment]
Thanks for raising @codemicro.

Is a little awkward due to the nature of PHP & how it can be mixed in with other content (HTML, text, etc..). Looks like such a mode is possible:
https://github.com/codemirror/CodeMirror/issues/137

We'll have to ensure it won't effect existing mixed blocks of code with PHP chosen. Might have to be another option in the code block editor language list.

**Comment by FinlayDaG33k** [comment]
I'm using the Markdown editor myself (because it's a lot faster for me) and PHP does highlight just fine in the markdown itself but then when I look at the right side (where the "output" is shown), it's not there.

This does imply that there is some highlighter for it in place already?

**Comment by ssddanbrown** [comment]
@FinlayDaG33k Code blocks are not highlighted in the Markdown preview window for performance reasons. Highlighting should be active when viewing the live page after saving.

**Comment by ssddanbrown** [comment]
Updated applied in master, For the next release (v0.28).

BookStack will now check for php opening tags (`<?php`) and change the exact mode depending on if they exist, meaning that standalone PHP code will now highlight as expected.

**Comment by codemicro** [comment]
Thank you very much! :)

**Comment by sabat24** [comment]
@ssddanbrown Is there a way to highlight the PHP code inside code block but without using opening tags? 

For example like here by marking code block as php one.

```php
class Event extends Relations\HasMany
{
  ...
}
```

**Comment by codemicro** [comment]
That is exactly the scenario I set out when I first opened this issue and,
as the comments clearly say, a fix has been implemented and will be
released in v0.28.

**Comment by sabat24** [comment]
Ok. I misunderstood the answer. I thought that that line "BookStack will now check for php opening tags (<?php)" was about the change which will be implemented and not the situation which is right now.
Now it's clear. Thanks.
