### ISSUE TITLE
Cannot delete an attachment from a page

### ISSUE THREAD

**Issue by TheBigCocio** [BookStackApp/BookStack#1558]
Hello,

After i upload a Attachment to a page i cannot delete it. 
I get a 405 (Method not allowed) when trying and i'm Admin.

What can i do to fix this?

**Comment by mrdth** [comment]
I'm seeing the same problem, trying to delete an attachment from a page results in a 405, even when trying as a user with a role which has permission to delete both Own / All attachements set

**Comment by navvienna** [comment]
I have the same problem running v.0.29.3 - is there a solution?

**Comment by tomsnunes** [comment]
I am still having this issue in v0.31.6. Any workaround available?

**Comment by ssddanbrown** [comment]
@tomsnunes The delete attachment request is one of the rare times in BookStack that a DELETE request is performed. It may be something related to that in combination with your setup that's causing issues, I've seen this before for IIS users.

Also, Check you have the APP_URL option set in the `.env` file. If you need further help I'll need more information about your hosting setup and ideally any error messages you're seeing in the browser development console.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one, but please provide details of your BookStack server environment to help debug the issue.
