### ISSUE TITLE
Can't login in Windows 10

### ISSUE THREAD

**Issue by distressmess** [BookStackApp/BookStack#1559]
After running through....several installations of Bookstack and WAMP (I am very new at all of this), I've finally got it working to the point of actually being able to reach a login screen. However, the login button doesn't work, and the only functional links on the page are the book in the top left (which takes you back to this same page), and the forgotten password link, which takes you to the page to submit your e-mail (but also has a broken button). 

I'm running the app on a fresh WAMP installation (3.1.9) and Windows 10. 

This is the screen that I'm running into:

![login](https://user-images.githubusercontent.com/53479820/62134505-98da2e80-b2ae-11e9-8378-2598885f6dab.jpg)

The BookStack version is v 0.26.0 I believe (the most recent one), PHP is 7.3.5, and it's hosted on Apache 2.4.39. The server is intended to be local. 

Thanks in advance! :)

**Comment by TBK** [comment]
Check the browser console, apache logs and php logs for errors.

It might be an issue with the browser, so try another browser.

**Comment by christophert** [comment]
BookStack no longer supports IE11 as of [v0.26.0](https://github.com/BookStackApp/BookStack/releases/tag/v0.26.0).

**Comment by distressmess** [comment]
Thanks for checking in guys! I'd tried it on multiple browsers to the same
effect. But I actually managed to get it working by switching to Docker for
Windows and ditching the WAMP setup altogether. :)

Thanks again!

**Comment by ssddanbrown** [comment]
@distressmess Glad to hear things started working, Will therefore close this.
