### ISSUE TITLE
Possible bug while parsing lists with dates

### ISSUE THREAD

**Issue by GeneralGeki** [BookStackApp/BookStack#1562]
Hey there,

I am experiencing weird behaviour while creating a list with german dates (DD.MM.YYYY)
It just ignores what I write and increases the list instead.
This behaviour stops, when I use an asterisk for the list.
Though doing so ends up increasing the space between the lines, which is annoying since it isn't consistent with the rest anymore.

Thanks for your help

![temp](https://user-images.githubusercontent.com/10200056/62243550-cc67a680-b3dd-11e9-8ac6-bcb5f712c724.png)

**Comment by ssddanbrown** [comment]
Hi @GeneralGeki,

Yeah, These dates are being rendered as numbered lists since they follow the general markdown format for those.

I've found you can escape the dot to render these as expected:

```markdown
* 14\. Jan 2069
* 21\. Feb 2077
```

**Comment by ssddanbrown** [comment]
Since the issue was explained with a workaround provide, and since there was no follow-up discussion, I'll close this off.
