### ISSUE TITLE
Add support for Captcha anti-spam fields

### ISSUE THREAD

**Issue by samtuke** [BookStackApp/BookStack#1564]
**Describe the feature you'd like**
Two days after making our manual public we have many spam users registered and making edits, many using variations of the same content and email address. To undermine the ability of bots to add scripted spam to bookstack, please add support for (re)captcha type anti-bot / spam fields.

**Describe the benefits this feature would bring to BookStack users**
Lower amount of robotic spam edits.

**Comment by ssddanbrown** [comment]
Thanks for the request @samtuke.

Since this has already been requested in #1114 I'll close this off as a duplicate. Please give the original post in #1114 a :+1: reaction to show support.

**Comment by samtuke** [comment]
Thanks @ssddanbrown
