### ISSUE TITLE
Make the recent activity feed link to a longer page with extended history

### ISSUE THREAD

**Issue by samtuke** [BookStackApp/BookStack#1566]
**Describe the feature you'd like**
To make it possible to see all activities, not merely the ones visible by the height of your browser viewport, link the activity feed sidebar to a page with a longer archive of activity, ideally making all past activities accessible in this way.

**Describe the benefits this feature would bring to BookStack users**
The ability to review all recent activity to identify problems and spam or other unwanted edits and behaviour, to protect the books.

**Comment by ssddanbrown** [comment]
Thanks for the request here @samtuke.

The core benefit requested can now be achieved via the system audit log that we introduced earlier this year. Due to that, and since there has been no other desire for this exact implementation to be added, I'm going to close this one off.
