### ISSUE TITLE
Pulling files or resources from a repository

### ISSUE THREAD

**Issue by hahmed09** [BookStackApp/BookStack#1569]
Hey guys, great stuff in building the app. One feature, I believe, will be super useful:

1. Having the ability to store files in a central repository
2. Being able to pull those files / resources onto any page. So instead of uploading it time and again, on this page itself they can select the files / resources from the repository:

<img width="1206" alt="Screen Shot 2019-08-01 at 17 14 32" src="https://user-images.githubusercontent.com/49093500/62296468-3042ab80-b480-11e9-80df-7e8f5ea6bab4.png">

What do you think?

**Comment by ssddanbrown** [comment]
Hi @hahmed09, Thanks for making your request.

This has already been requested in #924 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #924 it will help show support for that request.

**Comment by hahmed09** [comment]
Thanks, will do!
