### ISSUE TITLE
Test files can cause "Trojan" warnings on some systems

### ISSUE THREAD

**Issue by infario** [BookStackApp/BookStack#1571]
While I tried to install this on my server my cpanel antivirus reported trojan virus infection this source files

**Comment by Abijeet** [comment]
Hi @infario 

Can you add some more info or logs from the antivirus?

**Comment by infario** [comment]
![image](https://user-images.githubusercontent.com/9401329/62355797-5c683600-b52d-11e9-8534-92c12629f170.png)
The file you uploaded, BookStack-master.zip, contains a virus so the upload was canceled: Win.Trojan.Hide-2 FOUND

**Comment by Abijeet** [comment]
Can you share what hosting provider you use? Any ideas about what AV software they use?

On a side note, you can download the latest release of BookStack from the release section here - https://github.com/BookStackApp/BookStack/releases

The master branch is for development purpose.

**Comment by infario** [comment]
I tried the release BookStack Beta v0.26.3 and still get same error.  We use Panel secure hosting. I guess they are using  ClamAV Antivirus

**Comment by dawolf** [comment]
Automated malware scanners seem to pick up files in the `/tests/test-data` directory.

```
./tests/test-data/bad.php: Win.Trojan.Hide-2 FOUND
./tests/test-data/bad.phtml: Win.Trojan.Hide-2 FOUND
```

**Comment by infario** [comment]
Can i delete "tests" folder and upload?

**Comment by Abijeet** [comment]
@infario - Yes that should work fine.

**Comment by infario** [comment]
Yes now the virus error gone. Thanks @dawolf and @Abijeet

**Comment by Abijeet** [comment]
Re-opening this in order to bring to @ssddanbrown's attention, and maybe make a more long term fix.

**Comment by dawolf** [comment]
These files should be removed from the release if they get picked up by malware scanners.

**Comment by ssddanbrown** [comment]
Thanks @Abijeet for responding to this.

Yeah, Once we get to a point where we have packaged releases then the test files should not be included. GitHub just provides the current zip as a straight ZIP of the source. Have updated the title and will leave this open as a reminder for when we come to change the release process.

**Comment by LordSimal** [comment]
I just want to mention, that my hoster https://all-inkl.com/ reported those 2 PHP files as described above.
I now have deleted the tests folder but a "real solution" would be nice.

**Comment by stenootje** [comment]
April 2020 and this is still not removed... why? 
even more, why is this included? a php-file and phtml-file that are images!!

**Comment by ssddanbrown** [comment]
> April 2020 and this is still not removed... why?

@stenootje Because we have not developed a packaged release system yet.

> even more, why is this included? a php-file and phtml-file that are images!!

Because we have tests to ensure these types of files cannot be uploaded.

**Comment by stenootje** [comment]
so this directory can be removed from installation without causing other problems?

**Comment by ssddanbrown** [comment]
@stenootje The directory can be removed. If you installed using `git clone` to pull down the files, then it's possible you may get some warnings or error when pulling down the code for an update.

**Comment by LordSimal** [comment]
If these files are "just" to test the upload (while developing) why does it have to be in a production environment?
Could this be solved with a production and development branch?

**Comment by ssddanbrown** [comment]
> If these files are "just" to test the upload (while developing) why does it have to be in a production environment?

It's ideal to be able to run the tests against the exact branch of code that people are using, They'll never run in production but they're useful to be there.

> Could this be solved with a production and development branch?

Yeah, most likely. We pretty much already have that with `master` as our development branch and `release` as our production branch, is just working around the above (ensure we're testing production-intended code) and putting process in place. Just wasn't looking to spend time updating our dev/release process to account for just this since I ultimately want to change the release process anyway.

**Comment by liudass84** [comment]
FILE HIT LIST:
{CAV}Win.Trojan.Hide-2 : /.../tests/test-data/bad.php
{CAV}Win.Trojan.Hide-2 : /.../tests/test-data/bad.phtml

**Comment by ssddanbrown** [comment]
Within f25e585008178010c5fede256b4d9e7638da1070 I've re-worked these files for our testing usage to avoid them getting picked up by AV, Have tested with ClamAV. Will be part of the next feature release.
