### ISSUE TITLE
Lock editing page

### ISSUE THREAD

**Issue by Mracobes9** [BookStackApp/BookStack#1572]
Hi. How can i lock the editing document ? It is necessary because multiple users can't edit page at the same time. And application doesn't show notification for this case

**Comment by ssddanbrown** [comment]
Hi @Mracobes9, 

There is no current way to force a lock of a single page. 
BookStack will attempt to show a notification to a second editor if an edit is in progress by a previous user. Further functionality has already been requested in #395 so I'll therefore close this off as a duplicate.
