### ISSUE TITLE
Expand search scope to include tags by default

### ISSUE THREAD

**Issue by mainmachine** [BookStackApp/BookStack#1577]
**Easily Searchable Tags**
I'd like to see tags searched for automatically when you do a search query.

**Ease of Use/ Alignment with User Expectations**
It's kludgey to have to wrap tags in square brackets, and I don't believe it's documented. I just found it while derping through the UI.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion,
I agree that tags should probably be included in the scope of a default search term. 

[A full search syntax reference can be found here](https://www.bookstackapp.com/docs/user/searching/#advanced-search-syntax).

**Comment by mainmachine** [comment]
@ssddanbrown - Thank you for that link, that is very useful and I have added it to the bookstack based knowledge base I've been building for my company's internal use!

**Comment by medvedar** [comment]
+1

**Comment by Wookbert** [comment]
+1

No one is consequent enough to fully tag each and every page. However, sometimes it's necessary to add tags, cause it just doesn't fit into the page title, which could get incredibly long and cluttered.

Problem though is, that it is impossible to remember when and if the keyword one is searching for was added to the page title or instead as a tag. But: I never find myself using the search bar first, and the tag search second. (I actually just realized that the tag search field exists). Accordingly matching tags should/must be included in the search results by default.

**Comment by ssddanbrown** [comment]
This has now been added as part of #3043, specifically within 99587a0be63556a6915ac2728d8236da2f61c288. Both the tag names and values will be parsed as terms that get indexed to be matched and scored as part of normal search terms. Tags receive a score boost compared to a standard page text term (3x for tag names, 5x for tag values). This will be part of the next feature release so will hence close this off.

Thanks again @mainmachine for the suggestion.
