### ISSUE TITLE
TAB indentation

### ISSUE THREAD

**Issue by raisoftware** [BookStackApp/BookStack#158]
Desired Feature:
The Tab key should work as an editing key instead of a browser navigation key. Tab indentation should be preserved on the next line. This is very important for any kind of code editing.

Expected Behavior:
The editor should captured the Tab key and preserve indentation after Return, similar to any code editor like Atom. If text is selected and the Tab key is pressed, the whole selection should be indented instead of overwritten by tab.

Actual Behavior:
The Tab key navigates to the next browser control.

**Comment by patoroco** [comment]
This will be useful!

I need to go to Sublime Text, edit there, and after copy&paste to wiki

**Comment by domainzero** [comment]
This has been fixed now with the implementation of the Codemirror editor @ssddanbrown

**Comment by ssddanbrown** [comment]
@domainzero Thanks, Completely missed this one when searching past issues 😃 

For reference. Fixed as of about commit 968e7b8b72dba148166253c00e6b0d09b714888f

**Comment by ThorsenRune** [comment]
Just for reference: BookStack v0.31.6
TAB is not working

**Comment by dgomulka97** [comment]
Can confirm, I'm now googling how to use TAB instead of spaces in WYSIWYG editor

**Comment by dgomulka97** [comment]
Ok, I found new strange thing.
Tab doesn't work unless you are trying it on bullet list
I'm working with v0.31.8 using WYSIWYG
![tabissue](https://user-images.githubusercontent.com/78692869/113519089-5dffc200-958a-11eb-83a8-16b28dad819d.png)

**Comment by washichi** [comment]
> Ok, I found new strange thing. Tab doesn't work unless you are trying it on bullet list I'm working with v0.31.8 using WYSIWYG ![tabissue](https://user-images.githubusercontent.com/78692869/113519089-5dffc200-958a-11eb-83a8-16b28dad819d.png) @ssddanbrown

Exact same thing on [BookStack v23.02.1](https://github.com/BookStackApp/BookStack/releases)

**Comment by ssddanbrown** [comment]
Yeah, to confirm, we don't support tabs outside of code blocks.
