### ISSUE TITLE
Standard oAuth support

### ISSUE THREAD

**Issue by Ghost-chu** [BookStackApp/BookStack#1580]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.
Add Generic Oauth2 provider support.
**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.
We can build the a awesome system use one account to login everythings.
**Additional context**
GENERIC IS AWESOME

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Ghost-chu.

This had already somewhat been requested in #1157 although it was not fully clear to others outside of that issue. I've now updated that issue title so will close this to keep focus on one issue thread. Give the original post there a "Thumbs-Up" reaction to show support.
