### ISSUE TITLE
Image manager/Gallery Shows no pictures when pointerdown event is bound in header. Prevents adding images.

### ISSUE THREAD

**Issue by eceforge** [BookStackApp/BookStack#1588]
**Describe the bug**
I noticed that Images that were already on a page still display just fine, and images that get uploaded exist when I go dig in the docker storage volume -- it's just that the image manager doesn't show anything -- even immediately after a "successful" upload. Attachments work fine, its just images. 
Everything appears just fine on upload including the "image upload successfully" notification but images didn't appear in the image manager.

Turns out the image manager relies on the click event to start loading the images -- and I had foolishly bound the pointerdown event listener in the header in an attempt to get a reasonable update rate when using KaTeX (which would btw be a fantastic default feature). 

Not really a bug per say -- I started writing this bug before I had figured out what happened but I figured this might help someone else that is having a similar issue. 

**Steps To Reproduce**
1. Not know any better and add an event listener for the pointerdown event to render math while editing a page. 
1. Edit any page
2. Click on 'insert image'
3. Image Select dialog comes up, but no images are shown

**Expected behavior**
Images from the wiki including images that have just been uploaded with the image upload feature should be shown here for adding to the page. 

**Screenshots**
It's just a blank Image Select dialog. 

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.26.2
 - PHP Version: 7.1.30
 - Hosting Method (Nginx/Apache/Docker):  Docker (solidnerd)

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for noting for others, Will therefore close this off.
