### ISSUE TITLE
Any one can make a new user account 

### ISSUE THREAD

**Issue by lilayoung** [BookStackApp/BookStack#1589]
**Describe the feature you'd like**
Any one who visits the site, i.e., general public, can sign up for an account with full editing privilege. 

**Describe the benefits this feature would bring to BookStack users**
Make it more like Wikipedia and widen use-cases. 

**Additional context**
Hi, I am new to this, did not seem to find any documentation on new user set up, just wanted to suggest this or check that it already is included in the implementation :) 

Thank you!

**Comment by ssddanbrown** [comment]
Hi @lilayoung,

This should be currently possible. Simply create a role with the permissions you want for new sign-ups then, in settings, enable registration and set your role as the default.

**Comment by lilayoung** [comment]
Thank you! I will try and follow-up.

**Comment by ssddanbrown** [comment]
:+1:  I'll close this for now then. If you have any issues with the above feel free to open a new issue, referencing this one.
