### ISSUE TITLE
30 seconds

### ISSUE THREAD

**Issue by papypotage** [BookStackApp/BookStack#1590]
hello 
I have a limitation error of 30 seconds when exporting to pdf 

/var/www/html/vendor/dompdf/dompdf/lib/Cpdf.php

 Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Maximum execution time of 30 seconds exceeded

how can the time limit for export be changed?

**Comment by ssddanbrown** [comment]
Hi @papypotage,
Please see issues #389 & #1603 since these are pretty much the same thing.
You basically need to increase your server `max_execution_time` since it's just likely taking a while to generate the PDF.
