### ISSUE TITLE
Class 'BookStack\Http\Request' not found

### ISSUE THREAD

**Issue by figassis** [BookStackApp/BookStack#1594]
**Describe the bug**

**Steps To Reproduce**
1. Clone release branch (or download release archive 0.26.2+)
2. Serve on nginx+php-fpm
3. PHP logs show `PHP message: PHP Fatal error:  Uncaught Error: Class 'BookStack\Http\Request' not found in /var/www/html/public/index.php:54`
4. Error does not show when I use the master branch, but the master branch has no dist directory, so assets return 404.

**Expected behavior**
Show homepage

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.2
 - PHP Version: php 7.3 fpm
 - Hosting Method: docker+nginx+php-fpm

**Comment by ssddanbrown** [comment]
Hi @figassis,
Sorry to hear you are experiencing issues.

That error message would only show if `master` branch files are in use or have been cached/compiled, that message should never show on `release`.
Please can you use the latest release files and ensure a `composer install` is done while using the release files. Might also need to run `composer dump-autoload` if you have master files cached.

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this.
If this issue remains please feel free to open a new issue, referencing this one.
