### ISSUE TITLE
Self-managed Groups

### ISSUE THREAD

**Issue by mattstanyon-tall** [BookStackApp/BookStack#1597]
The ability for anyone to create a group, and manage its membership.

This would allow a self-service approach to the sharing of content.  This way, someone can login, as a member of the Public group, create a group and share their content instantly with this group.

**Comment by ssddanbrown** [comment]
Hi @mattstanyon-tall,
Thanks for the request.

I feel like the requested setup moves a bit too far from the core purpose of BookStack. BookStack is really intended for a single community rather than multiple separate communities in one. Therefore I'm going to close this request.
