### ISSUE TITLE
Display shelves a book belongs to

### ISSUE THREAD

**Issue by over-soul** [BookStackApp/BookStack#1598]
**Describe the feature you'd like**
Would like to be able to display which shelves a book belongs to on the books page. 

**Describe the benefits this feature would bring to BookStack users**
Currently, if you go to the books page, you have no way of knowing which shelves the book belongs to. Hence, a user is not able to access other similar books that might be categorized together under a certain book shelf. 

**Additional context**
Could display the name of the shelf (or shelves) that the book belongs to right below the description and above "created x days ago".

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @over-soul.
This has been implemented by @cw1998 and will be part of the v0.29 release.
