### ISSUE TITLE
Upgrade to Laravel 6

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#1600]
Laravel 6 is releasing soon. Would be good to align BookStack to a later release. Should be a fairly straightforward upgrade code-wise. The bigger concern will be the change in PHP version requirements (php7 to php7.2). Laravel 6 looks to be an LTS release which will be ideal since staying on Laravel 5.5 has kept things steady for the last two years.

### Considerations

* Install scripts will need to be updated to install php7.2 by default (Perhaps skip to latest stable version at time of changes).
* PHP upgrade guide would be ideal for those that have already installed with official install scripts. 
* We'll need to warn popular BookStack service/container maintainers of the change in order to ensure a quick and stable upgrade for their users.
* PHP dependencies will need to be reviewed to ensure compatibility with Laravel 6.

**Comment by JtheBAB** [comment]
The good thing is that even debian is with the latest version at php 7.3.

**Comment by ssddanbrown** [comment]
Ah, That's good news. Think the mains ones will be debian stretch, Ubuntu 16.04 & Centos 7. If we provide some instructions for those then we should be covered. Potentially debian Jessie also? But that is nearing EOL.

**Comment by JtheBAB** [comment]
Debian stable is Buster (php 7.3)
Debian old stable is Stretch (php 7.0)
Ubuntu is 18.04 prefered but 16.04 is still supported. But both have php 7.3

**Comment by timoschwarzer** [comment]
This is only missing a docs update for Debian stretch (how to get PHP 7.3 running) and updating system requirement lists eventually, right?

**Comment by ssddanbrown** [comment]
@timoschwarzer Yeah, Docs and install script updates for Debian Stretch, Ubuntu 16.04 & Centos 7. Leaving this issue open as a reminder for that. 

And also need to check the docker images and warn if they are on a lower PHP version. Might be alright there though.

**Comment by timoschwarzer** [comment]
Docs update is ready @ https://github.com/BookStackApp/website/pull/49
Now updating the install scripts.

**Comment by ssddanbrown** [comment]
Thank you so much for digging into this @timoschwarzer, Was very helpful. And also thanks @JtheBAB for providing details for systems. 

Since only further docs updates and deployment now need to occur I'll close this off.
