### ISSUE TITLE
sign in page is not opening correctely

### ISSUE THREAD

**Issue by mmteyrek** [BookStackApp/BookStack#1602]
**Describe the bug**
I isntalled bookstack on my local computer (wamp).
I'm facing this issue when opening the local virtual host (pointed on bookstack/public).
GET http://reghome/dist/app.js?version=v0.27-dev net::ERR_ABORTED 404 (Not Found)
login:13 GET http://reghome/dist/styles.css?version=v0.27-dev net::ERR_ABORTED 404 (Not Found)
login:14 GET http://reghome/dist/print-styles.css?version=v0.27-dev net::ERR_ABORTED 404 (Not Found)

**Steps To Reproduce**
1. install book stack on wamp

**Expected behavior**
signin page open

**Screenshots**
![image](https://user-images.githubusercontent.com/17122420/63831256-8ebf5480-c96e-11e9-84df-ac8278259508.png)

**Your Configuration (please complete the following information):**
 - last
 - PHP Version: 7.3.5
 - Hosting Method ( wamp Apache): 

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @mmteyrek,
It looks like your using the master development branch code. CSS an JS assets are not ready built in this branch.

Please use the release branch instead.

**Comment by mmteyrek** [comment]
thank you.
