### ISSUE TITLE
Uknown error during pdf export

### ISSUE THREAD

**Issue by denisdal** [BookStackApp/BookStack#1603]
**Describe the bug**
Hi all, during pdf export of a book with many pages (177 in my example) the process exit with an error

**Steps To Reproduce**
1. Go to the desired book 
2. Click on PDF Export
3. wait

**Expected behavior**
prompt pdf download/open

**Screenshots**
![immagine](https://user-images.githubusercontent.com/30142395/63838538-cda8d680-c97d-11e9-8c34-bf09e656046b.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.25.5
 - PHP Version: PHP 7.2.19-0ubuntu0.18.04.2
 - Hosting Method (Nginx/Apache/Docker): Apache2

**Additional context**
I tried:
- switch to wkhtmltopdf (https://www.bookstackapp.com/docs/admin/pdf-rendering/) with no results. Same error but I see that wkhtmltopdf  was called.
- Increase php memory_limit and max_execution_time

With a small book (< 10 pages) pdf export is fine.
Any suggestions ?

**Comment by over-soul** [comment]
What did you change memory limit and execution time to?

After you made the changes, did you run: 

`sudo systemctl restart php7.2.19-fpm.service`

**Comment by denisdal** [comment]
`memory_limit = 256M
max_execution_time = 300`

I restarted apache2 service directly as works in prefork not via FPM

**Comment by over-soul** [comment]
When you check phpinfo do you see the right limit and execution time?

**Comment by denisdal** [comment]
Yes
![immagine](https://user-images.githubusercontent.com/30142395/63866981-64908580-c9b4-11e9-88cf-1ddfe02f81d5.png)

**Comment by over-soul** [comment]
which version of wkhtmltopdf do you have?

**Comment by denisdal** [comment]
`root@usermanual:~# wkhtmltopdf -V`
`wkhtmltopdf 0.12.5 (with patched qt)`

**Comment by over-soul** [comment]
What happens if you un-restrict the execution time by entering it as -1? Does it work then?
Also, are your pages primarily made up of text?

**Comment by denisdal** [comment]
Tried with max_execution_time = 0 and -1 and there are same error:
`[Fri Aug 30 09:26:41.881842 2019] [php7:error] [pid 13038] [client 10.10.1.5:43413] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/html/bookstack/vendor/symfony/polyfill-mbstring/Mbstring.php on line 500`
`Fatal error: Maximum execution time of -1+2 seconds exceeded (terminated) in /var/www/html/bookstack/vendor/symfony/polyfill-mbstring/Mbstring.php on line 500`

Pages is primarily text but there are also images, not in all pages but they may have it.
Server with 1 GB RAM.

Thank you

**Comment by ssddanbrown** [comment]
@denisdal When you set `max_execution_time` to 300 was the browse loading for 5 minutes and did you see `300` in the resulting error log or were the experience/logged times different?

**Comment by denisdal** [comment]
Well, no.
Browser return unknown error way before then 300 seconds.

**Comment by denisdal** [comment]
Any help figuring out how to solve this ?
Thanks

**Comment by denisdal** [comment]
Any update ?

**Comment by ckdanny** [comment]
I have met the same issue while exporting a large file which will cause mentioned error, 
`production.ERROR: Maximum execution time of 30 seconds exceeded`

If the result file is smaller than around 5MB, it can export normally, otherwise, the error will be a trigger. 

@denisdal May I know if you have figure out any possible solution for it?

**Comment by denisdal** [comment]
No I'm still having this issue so far

**Comment by xavierlaviolette** [comment]
Hello, i have the same problem. I do this change : 
memory_limit = 256M
max_execution_time = 300
and restart the server but i have always this error.

Can you help me ?
Thanks

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
