### ISSUE TITLE
Allow Book to Shelf association during book creation/edit

### ISSUE THREAD

**Issue by mmteyrek** [BookStackApp/BookStack#1609]
**Describe the feature you'd like**
Currently it is possible to add books to as shelves in shelves.
It will be better to be able to associate a book to a shelf and (this way) when creating / editing the book.

**Describe the benefits this feature would bring to BookStack users**
The number of the shelves will be inferior to the number of books, so it will be easier to find the shelves.

in my case : the admin can only creates shelves, do the user can't modify the shelves.
currently, when the user create the book, he is not able to put it into as shelves. So with this feature, he will be able to do it

**Comment by ssddanbrown** [comment]
Very much related to #1483

**Comment by mmteyrek** [comment]
Same :)
