### ISSUE TITLE
Restrict book to some users

### ISSUE THREAD

**Issue by mmteyrek** [BookStackApp/BookStack#1610]
**Describe the feature you'd like**
 it will be great to have the possibility to restrict the access of a book to some users.

**Describe the benefits this feature would bring to BookStack users**
 when a user create a book, he can chose between 2 possibilities: public / private when public => all users can see the book when private => he has the possibility to choose the users who could see the book (by default he has access :p).

**Comment by ssddanbrown** [comment]
Hi @mmteyrek,
You can use the "Permissions" button when viewing a book to set controls about what roles can view/edit/delete the book. Permission on a book will cascade down to chapters and page.

You can create a role (Settings -> Roles) for the specific users you want to target.

**Comment by mmteyrek** [comment]
Hello,
Thank you but unfortunately this is not what I mean.
Actually I'm building a wiki style about a specific subject.

The current user is not an admin so he don't have Access to settings / roles.

Let's imagine this 2 scenario

**Comment by ssddanbrown** [comment]
Thanks for explaining @mmteyrek.

The request in #1747 should cover the cases described above so I'm going to close this issue off in favour of that one.
