### ISSUE TITLE
Export won't work (both .HTML & .PDF)

### ISSUE THREAD

**Issue by b0n3sh** [BookStackApp/BookStack#1615]
# **Describe the bug**
I run into error when trying to export a specific page I created, the other works fine, I'm not sure if may be because it have a lot of images, or maybe it's too big.
When exporting as html, a file will start to download, but it stays at 10% for ever and then will yield a network error.
When exporting as pdf, I get an "unknow error".

# **Steps To Reproduce**
## Steps to reproduce the behavior:
1. Export page as...
2. Error

**Expected behavior**
A working .html and .pdf file.

**Screenshots**
![](http://i.imgur.com/S31DsJh.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.27
 - PHP Version: PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
 - Hosting Method (Nginx/Apache/Docker): Apache2 (in a raspberry)

**Comment by ssddanbrown** [comment]
Hi @B0nesh,
When such errors occur they will often be logged. Can you check the log or check via debug mode. Details for this can be found here:
https://www.bookstackapp.com/docs/admin/debugging/

**Comment by B0nesh** [comment]
Hello, thanks for the fast response, this are the debug=true pictures.
![](http://i.imgur.com/Nml3o9U.png)

**Comment by ssddanbrown** [comment]
Similar to issues #389 & #1603.

You can try to increase your server `max_execution_time` since it's just likely taking a while to generate the output.

**Comment by B0nesh** [comment]
Hello, I raised the `max_execution_time` from 30 to 500 and restarted the server, but I'm getting the same error.
http://i.imgur.com/JAXdgcq.png

**Comment by denisdal** [comment]
same error here https://github.com/BookStackApp/BookStack/issues/1603
