### ISSUE TITLE
Double click popup colors are wrong

### ISSUE THREAD

**Issue by over-soul** [BookStackApp/BookStack#1616]
**Describe the bug**
When you double click text, you get the link and edit buttons. However, the background colors are missing and the URL icon is a different color from the pencil icon. 

**Steps To Reproduce**
1. Go to https://demo.bookstackapp.com/books/lorem-ipsum-dolor/page/my-lorem-ipsum-book
2. Double click on a piece fo text
4. See screenshot

**Expected behavior**
The background colors should match the Application Primary Color in settings

**Screenshots**
<img width="579" alt="Screen_Shot" src="https://user-images.githubusercontent.com/29743024/64074755-5b9aff00-cca7-11e9-915f-48e459b92bc7.png">

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27
 - PHP Version: 7.0
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Thanks for raising @over-soul.

I've just applied a commit so the edit icon will now show.
I have not changed the background colors as I felt the content of the popover should not be overly distracting in the event it shows accidentally. In addition, there's no primary action, which is where I've used theme-coloured buttons in the rest the UI.

**Comment by over-soul** [comment]
Thanks for fixing!
