### ISSUE TITLE
Not able to create new site

### ISSUE THREAD

**Issue by Phreeak** [BookStackApp/BookStack#1617]
**Describe the bug**
After Update to 0.27.1 i'm not able to create a new site

**Steps To Reproduce**
1. Go to 'Books'
2. Click on 'new Site'

**Expected behavior**
Creation of a new site 

**Screenshots**
![Screenshot_20190901_130628](https://user-images.githubusercontent.com/21967882/64075490-62327200-ccb9-11e9-9b19-22046f6d16c4.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.1
 - PHP Version: 
![Screenshot_20190901_130845](https://user-images.githubusercontent.com/21967882/64075517-ab82c180-ccb9-11e9-90ca-6d9e89213d45.png)
 - Hosting Method (Nginx/Apache/Docker): Apache (Ubuntu 18.04 Installation Script)

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @Phreeak,
When such errors occur they will often be logged. Can you check the log or check via debug mode. Details for this can be found here:
https://www.bookstackapp.com/docs/admin/debugging/

Feel free to post any log message here for further help although be sure to check they don't contain any sensitive information.

**Comment by Phreeak** [comment]
Hi, 
after changing the Log from false to true, i get this after clicking on 'create new site'

[2019-09-01 11:04:19] production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'template' in 'where clause' (SQL: select count(*) as aggregate from `pages` where (`draft` = 0 or (`draft` = 1 and `created_by` = 1)) and (exists (select * from `joint_permissions` where `pages`.`id` = `joint_permissions`.`entity_id` and `joint_permissions`.`entity_type` = BookStack\Page and `role_id` in (1) and `action` = view and (`has_perm$
[stacktrace]

you can do something with it!?
Btw: between my version is 0.27.2

**Comment by ssddanbrown** [comment]
@Phreeak Upon updating to v0.27.2, Did you run `php artisan migrate` within the BookStack install directory?

**Comment by Phreeak** [comment]
Of course. 
I did:
git pull origin release && composer install && php artisan migrate
and
php artisan cache:clear
php artisan view:clear

now after run 'php artisan migrate' again everyting works fine

**Comment by ssddanbrown** [comment]
:tada: Cool, Will therefore close this.
