### ISSUE TITLE
Page turn buttons below each page for a continuous reading experience 

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#1619]
**Describe the feature you'd like**
The name and UI concept clearly implies to organize your information in books with chapters and pages. Reading a book however comes with the experience and convenience of continuous reading through a simple page turn. This does not only apply for paper books, but also has been mimicked on any eBook reader.

On BookStack I'm missing this convenience however so far. Yes, we do have the Book Navigation in the left side panel next to the current page (hereunder; which BTW only follows your scrolling and thus is always in instant reach, if the browser window is wide enough, so that there’s enough space for a right side panel as well), but that’s just not as convenient as a simple page turn.

![image](https://user-images.githubusercontent.com/3104762/64079875-9d4e9880-cced-11e9-9eb4-b687fd7a9f5d.png)

I therefore suggest to additionally place four buttons between the end of the page and the comments section:

- Previous chapter (jumps to first page thereof)
- Previous page
- Next page
- Next chapter (jumps to first page thereof)

Here’s a quick mockup of how that could look:

![image](https://user-images.githubusercontent.com/3104762/64079956-c58ac700-ccee-11e9-9160-41dafc1b3022.png)

**Further behaviour** 
- Buttons are ghosted if there is no previous/next chapter/page.
- Buttons could be hidden entirely if there is just a single page (UX consistency?). (Hide chapter buttons if there aren’t any chapters??)

**Discussion: Floating navigation?**
Another concept might be to have this navigation with its 4 buttons visible not only when reaching the end of the page, but instead visible and thus accessible at all times, so one can e.g. jump to the next page, even if one’s only half-way through a long page. The preferable place for such a floating navigation would be the bottom of the window IMO.

The problem I see in this approach however is the waste of screen real estate. A solution to this problem could be to make the navigation only appear (instantly) when a) the mouse pointer gets moved to the lower something pixels at the window or b) one scrolls to the very end of the screen.

**Comment by over-soul** [comment]
I agree that having the next page and next chapter buttons would be massively useful.

**Comment by Wookbert** [comment]
So, why not give it a Thumb Up? 👍 🤪

**Comment by ssddanbrown** [comment]
Hi @Wookbert,
Thanks for the detailed request. This has already been requested under #1381 so I'm going to close this but I'll copy your detail and imagery across to continue the discussion.
