### ISSUE TITLE
After v0.27.3 update, unable to sort books

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [BookStackApp/BookStack#1639]
**Describe the bug**
When attempting to sort a book, the sorting links are dead.

**Steps To Reproduce**
1. Go to any Book
2. Click on Sort
3. Scroll to top of page
4. Attempt to click on one of sorting options
4. Nothing happens

**Expected behavior**
I would expect the sorting links to sort according to how they're labeled.

**Screenshots**
![image](https://user-images.githubusercontent.com/50454265/64349987-8776f700-cfbd-11e9-8e20-d8aff3a31956.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.3
 - PHP Version: 7.2.19
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
Sorting worked fine before updating to Bookstack v0.27.3

**Comment by ssddanbrown** [comment]
@FMCUSystemAdmins Thanks for reporting, Seems like the book outline decoration element overlays the buttons making them unclickable. Have allocated for the next patch release.
