### ISSUE TITLE
Google 2 Factor  Authentication

### ISSUE THREAD

**Issue by mhawkins01** [BookStackApp/BookStack#1642]
I would like to see if its possible to get Google 2 Factor Authentication working on login for Book Stack

As nearly all web apps now or are starting to allow at least Google 2 FA for better security 

Matthew

**Comment by ssddanbrown** [comment]
Hi @mhawkins01,
Thanks for the request. When you say "Google 2 Factor Authentication" can you detail exactly what this relates to? Is that the google authenticator app?

**Comment by mhawkins01** [comment]
I would like to see 2 Factor setup that is able to work with the Google authenticator app.

**Comment by cyclinggeorgian** [comment]
I would consider this a duplicate of #516

**Comment by ssddanbrown** [comment]
Closing in favour of discussions in #1118.
