### ISSUE TITLE
Unable to re-expand a collapsed page preview for a chapter

### ISSUE THREAD

**Issue by avnkx** [BookStackApp/BookStack#1643]
**Describe the bug**
When expanding a chapters pages in the book view and re-collapsing it, one is not able to expand it again.

**Steps To Reproduce**
1. Go to '/books/foo' that has at least one chapter with pages in it
2. Click on 'x pages' to expand the page preview for the chapter
3. Click on 'x pages' to collapse the page preview for the chapter
4. When clicking on 'x pages' again, nothing happens

**Expected behavior**
One should be able to expand the pages list of that chapter again.

**Screenshots**

--

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.27.4 (lastest release)
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Docker behind Nginx reverse proxy

**Additional context**

--

**Comment by ssddanbrown** [comment]
Can confirm, From my testing issue will often appear on Firefox, Not so much on chrome. 

Thanks for reporting @avnkx .
