### ISSUE TITLE
Unable to add templates.

### ISSUE THREAD

**Issue by mattstanyon-tall** [BookStackApp/BookStack#1644]
Although the side bar now has a Templates button, which expands a Templates section, there is no way to flag a page as a template.

**Expected behavior**
The ability to convert a page to a template.  Tested in both Chrome and Firefox.

![image](https://user-images.githubusercontent.com/33625647/64488412-0aab7d80-d248-11e9-8628-75d82590774f.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.4
 - PHP Version: 7.2.19
 - Hosting Method (Nginx/Apache/Docker): Apache2

**Comment by mattstanyon-tall** [comment]
Found this!  System Permissions needed to manage templates!

Thanks

**Comment by TimmKroe** [comment]
So it is fixed ?

**Comment by mattstanyon-tall** [comment]
Absolutely!
