### ISSUE TITLE
Multilanguage articles

### ISSUE THREAD

**Issue by b1f17773** [BookStackApp/BookStack#1659]
**Describe the feature you'd like**
It will be great to write some articles in more then one language.  

**Describe the benefits this feature would bring to BookStack users**
That will be usefull for example where you want to share content in more than language. Now you need to create to seperate articles.

**Comment by ssddanbrown** [comment]
Thank you for your request.

Since this has already been requested under issue #569 I'm going to close this off as a duplicate. Please add a thumbs-up reaction to the original request there to show support.
