### ISSUE TITLE
Cancel button on new book page doesn't go back to bookshelf

### ISSUE THREAD

**Issue by ethanmdavidson** [BookStackApp/BookStack#1662]
**Describe the bug**
If you are in a bookshelf and creating a new book, clicking the cancel button always brings you back to the "books" page, instead of back to the bookshelf you had open.

**Steps To Reproduce**
1. Go to a bookshelf (https://demo.bookstackapp.com/shelves/an-example-bookshelf)
2. Click "New Book" on the right hand side. This brings you to the create-book page within the bookshelf (https://demo.bookstackapp.com/shelves/an-example-bookshelf/create-book)
3. Click the "Cancel" button.

**Expected behavior**
Upon clicking the cancel button, I would expect to be brought back to the bookshelf I had open (https://demo.bookstackapp.com/shelves/an-example-bookshelf).

**Actual behavior**
You are redirected to the "Books" page (https://demo.bookstackapp.com/books).

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.4
 - PHP Version: 7.2.22
 - Hosting Method (Nginx/Apache/Docker): nginx/1.12.2 on CentOS 7

**Additional context**
The configuration info is for my install, but the steps to reproduce include URLs from the demo (which is running 0.27.3) for ease of use.
This is definitely not a huge deal, but it's a little annoying so I figured I would report it.

**Comment by cw1998** [comment]
Hey. I did some work a long time ago to add the new book button to shelves. This was an oversight on my part, so I felt the need to fix it with the above commit. PR on the way.

**Comment by ssddanbrown** [comment]
Fix applied in `master`, Will be part of the next feature release.
