### ISSUE TITLE
Redirecting error while running on prefix

### ISSUE THREAD

**Issue by dusatvoj** [BookStackApp/BookStack#1664]
**Describe the bug**
Missing slash in bookstack homepage address

**Steps To Reproduce**
1. Install bookstack on domain prefix (eg.: https://example.com/bookstack/)
2. Try to login
3. You will be redirected not to https://example.com/bookstack/ but to https://example.com/bookstack
(Same problem found when I want to go back from settings to homepage by clicking to top left button)

**Expected behavior**
Login OK, I'm redirected to homepage

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.27.4
 - PHP Version: 7.0.33
 - Hosting Method (Nginx/Apache/Docker):  Apache behind Apache reverse proxy

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
