### ISSUE TITLE
WYSIWYG Editor for books and shelves

### ISSUE THREAD

**Issue by cyruscuenca** [BookStackApp/BookStack#1666]
I would personally find it extremely helpful to add the WYSIWYG editor used for pages to the higher level pages.

BookStack encourages a hierarchical method of organization, but that does not mean that broader pages don't need bold text, lists, tables, and images. 

I know I would find this helpful, and I have a hunch that there are others who would like this feature.

I'm going to have a look at the codebase and try to do it for my installation. If this is something other people would like and I determine that the modification isn't too time consuming, I wouldn't mind sharing my solution.

**Comment by ssddanbrown** [comment]
Hi @cyruscuenca,
Thank you for your request.

This has been requested before, I'll copy my response from #1076:

> Currently markdown within description fields is not supported. Descriptions are purposefully designed to be as simple as possible. Allowing advanced formatting would add a good bit of complexity. It may also make it less clear where actual content should be placed whereas, at the moment, it's clear content is held in pages.

Due to the above, I'd prefer not to have further formatting in descriptions.
