### ISSUE TITLE
Link to external files

### ISSUE THREAD

**Issue by tklapettek** [BookStackApp/BookStack#1669]
I wanna create a link to a file like "file://///server/path/filename.ext". This file should be open in a new Tab or windows. In the moment I get only an empty page.
It's because we have a lot of documents where we want to link from a page 

Upload file is not an option because I have to download it before open and we have "living" documents which are always edited.

Thx 

Tom

**Comment by ssddanbrown** [comment]
Hi @tklapettek,

Are such links able to function when used anywhere else on the web? It's just that I think this could be a general web browser security feature that stops such links from working.

**Comment by FreeTheTech101** [comment]
Assuming that these documents are on some sort of SMB share, you could create a new virtual host that acts as a transparent proxy to the SMB share.

Example:
//server/path/filename.ext => https://documents.example.com/path/filename.ext

Just ensure to disable directory listing, or else people will be able to navigate the SMB share directly though their web browser, and possibly download files they should not have access to!

**Comment by derklompi** [comment]
FileLinks are disabled in browsers like Firefox and Chrome nowadays, only IE still supports it without altering the settings or using Addons.

**Comment by ssddanbrown** [comment]
I'm going to close this off as it does not seem possible, or secure, to support in the platform.
