### ISSUE TITLE
Code block editor doesn't show contents without clicking code content

### ISSUE THREAD

**Issue by jaylik** [BookStackApp/BookStack#1672]
**Describe the bug**
Code block editor doesn't show contents without clicking code content

**Steps To Reproduce**
1. Go to 'Edit' -mode
2. Add code block
3. Insert contents of 'https://github.com/BookStackApp/BookStack/blob/master/.gitignore'
4. Save Page
5. Open code block again in edit mode >> no code content visible without clicking code field

**Expected behavior**
Code block editor should show code content when its opened.

**Configuration**
 - Exact BookStack Version v0.27.4
 - PHP Version: 7.0.33-0+deb9u3
 - Hosting Method: nginx & fastcgi

**Comment by ssddanbrown** [comment]
Thank you for reporting @jaylik.

This has been addressed in 5a533fff8bc09e1520276c3fbb91740b432c8a3b and will be part of the next feature release.
