### ISSUE TITLE
Fixed element positioning makes it impossible to edit pages from mobile

### ISSUE THREAD

**Issue by trwnh** [BookStackApp/BookStack#1675]
![Screenshot_20190919-182250](https://user-images.githubusercontent.com/10606431/65288015-d6b73e80-db0a-11e9-97d9-0952fb28c5e6.png)

The page does not scroll. Only the very thin strip of the editor scrolls, and not enough to actually display anything more than a fraction of a line-height.

Perhaps the text-area needs a minimum height; otherwise, the fixed elements in the layout need to not be fixed-position.

**Comment by Epsola** [comment]
This is definitely an issue with the Markdown Editor.  Perhaps the preview pane would be better if it became a right sidebar button on mobile.

**Comment by ssddanbrown** [comment]
Thanks for reporting @trwnh.
Assigned to addressed as part of the next feature release.

**Comment by ssddanbrown** [comment]
I've just pushed 865e8d4ec550041c22e087e1aca5c422fa93e99b which will try to force the markdown area size a little more. As a backup, it also adds a fullscreen toggle to full the view with just the core editing panes. 

This will be released as part of v0.28, due at the end of the year. If you still have issues after that release feel free to open a new issue referencing this one.

Thanks again for reporting @trwnh.
