### ISSUE TITLE
Helm Chart - Configurable Admin User Name and Password

### ISSUE THREAD

**Issue by mjschmidt** [BookStackApp/BookStack#1676]
This project is awesome! But it took me a little while to figure out what the user name and password for the admin was, would you consider making this a configurable element in the helm charts value file?
https://github.com/helm/charts/tree/master/stable/bookstack

**Comment by ssddanbrown** [comment]
Hi @mjschmidt,
As per the other issue, that helm configuration is not something that's supported by this core project therefore I'm going to close this off. You might be able to get support via the repo you linked.
