### ISSUE TITLE
can LDAP Group CN support chinese

### ISSUE THREAD

**Issue by sosize** [BookStackApp/BookStack#1683]
**Describe the bug**
it can not use when LDAP External ID CN/OU is Chinese
ps: ldapsearch can support

**Expected behavior**
LDAP External ID support Chinese

**Screenshots**
![test](https://user-images.githubusercontent.com/7098141/65599058-84c15d80-dfcf-11e9-901d-75457e5de2d6.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):v0.27.4
 - PHP Version:7.3.8
 - Hosting Method (Nginx/Apache/Docker): Docker

**Comment by ssddanbrown** [comment]
Sorry for this extremely late response.

Non-ASCII support relies on matching the encoded format used by PHP/LDAP. I've built a little convert for this on JSfiddle here:
https://jsfiddle.net/ssddanbrown/4nkwuxj8/3/
