### ISSUE TITLE
LDAP_DISPLAY_NAME_ATTRIBUTE merge multiple values

### ISSUE THREAD

**Issue by dusatvoj** [BookStackApp/BookStack#1684]
**Describe the feature you'd like**
Ability to merge 2 values in `LDAP_DISPLAY_NAME_ATTRIBUTE` like:
`LDAP_DISPLAY_NAME_ATTRIBUTE={givenName sn}`

**Describe the benefits this feature would bring to BookStack users**
Merging first and last name from LDAP when fhere is no full name filled in LDAP

**Comment by ssddanbrown** [comment]
Thanks for the original request @dusatvoj.
Thanks to @MatthieuLeboeuf this has now been implemented via #5295 and is due to be part of the next feature release.

The syntax would follow the example: `LDAP_DISPLAY_NAME_ATTRIBUTE="firstname|lastname"`.
