### ISSUE TITLE
Validation failures are hidden if in a collapsable section of the form

### ISSUE THREAD

**Issue by cw1998** [BookStackApp/BookStack#1693]
**Description**
When creating or editing a book or a shelf, if there is a validation failure in the collapsable parts of the form (cover image, tags), the error is not immediately obvious as the section is automatically collapsed. This leads to a bit of confusion as to why you've been brought back to the form rather than the content.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to a book
2. Click on the edit button
3. Expand "Cover Image" section
4. Set cover image to something that will fail validation (such as file size too large, or unsupported format)
5. Click save
6. Observe that you remain on the form, but with the error message hidden
7. Expand "Cover Image" section to reveal the error.

**Expected behaviour**
My expectation would be one of the following:
- Show the error at the top of the page
- Highlight the Cover Image box in a suitable colour to indicate that there is a problem with that section
- Have the section(s) containing the error(s) already expanded when the page loads.

**Screenshots**
N/A

**Configuration:**
 - Exact BookStack Version: v0.27.4
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): Docker

**Additional context**

**Comment by ssddanbrown** [comment]
Good find @cw1998, Thanks for reporting.

**Comment by dellamina** [comment]
Hey @ssddanbrown I'd love to give some help in this one if you are not already working on it :)

**Comment by ssddanbrown** [comment]
Sorry @dellamina, Totally missed your message at the time.

I've now applied a patch for this in master, to be in the next release. I went for option 3 so that sections will now auto-expand on load if found to be containing an error message so that the error message is visible.
