### ISSUE TITLE
Send a Test Email Button in Settings

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#1696]
**Describe the feature you'd like**
An admin function to test if outgoing email is setup correctly.

**Describe the benefits this feature would bring to BookStack users**
As a Bookstack administrator I have no way of knowing if outgoing emial is working until one of my users complain.  Even then, I have no easy way to reproduce the problem or check if my actions have solved the problem.

**Comment by Cave-Johnson** [comment]
+1 to this

**Comment by ssddanbrown** [comment]
Thanks for creating this issue @tuaris, Have actually been meaning to add this functionality to the Maintenance section of the admin area. Will mark for the next feature release so I actually get this done.

**Comment by timoschwarzer** [comment]
@ssddanbrown have you already started development for this issue or can I grab it? :)

**Comment by ssddanbrown** [comment]
@timoschwarzer Nope, Not started on this, Got for it :+1:

**Comment by ssddanbrown** [comment]
Now implemented thanks to @timoschwarzer. Will be in the next feature release (v0.28).
