### ISSUE TITLE
LDAP Docker/Script Setup

### ISSUE THREAD

**Issue by ewhubby** [BookStackApp/BookStack#1701]
BookStack v0.27.4
PHP Version: 7.2
Docker
Ubuntu Server 18.04

Hello. I need some support. I have installed the script to install BookStack and love it. I am trying to setup LDAP (AD) but am not able to. I found issues stating to update the .env file in /var/www/bookstack. I do not have this file.

Does anyone have any setup notes or can provide the steps for setting up LDAP after using the install script under Ubuntu 18.04?

**Comment by ssddanbrown** [comment]
Hi @ewhubby,
If you used the Ubuntu 18.04 install script, Then `/var/www/bookstack` should be the correct location.
Often files started with a `.` such as `.env` will be hidden my default on linux systems. if you run `cd /var/www/bookstack && ls -alh` do you see the `.env` file in the output?

**Comment by ewhubby** [comment]
Thank you Dan for the information! I will give this a try.

**Comment by ssddanbrown** [comment]
Will therefore close this off.
