### ISSUE TITLE
New Page Creates Unknown Error

### ISSUE THREAD

**Issue by ewhubby** [BookStackApp/BookStack#1704]
BookStack v0.27.4
mySQL 14.14
Php 7.2.19
Ubuntu server 18.04

I am able to create a shelve and book without issues but when I try to create a page, I am receiving An Error Occurred message. I enabled debugging and message states that Column not found 1054 unknown column template were draft = 1 and created by = 4 ...

I ran the php artisan migrate and restarted the service but am still receiving the error.

**Comment by ssddanbrown** [comment]
Hi @ewhubby,
We've seen multiple people with similar issues recently. I can only imagine that an error occurs when migrating. That MySQL version does seem a little odd though.

When you run `php artisan migrate` do you get any errors or do you recall seeing any errors before?

Could you provide the output of running `php artisan migrate:status`? should output as a long table.

**Comment by ewhubby** [comment]
Hello Dan. I ended up reinstalling the server exactly as I did the first time via the same instructions. Upon this latest setup, I am not receiving any errors and is working successfully.

**Comment by ssddanbrown** [comment]
@ewhubby Ah, good news then, although odd! I'll close this since you no longer have the issue but I'll keep an eye out!
