### ISSUE TITLE
Underlining

### ISSUE THREAD

**Issue by jungren** [BookStackApp/BookStack#1705]
**Describe the feature you'd like**
Not sure if bug or feature-request: Usually you can do an underline in Markdown with \_text\_ but in BookStack I just get bold or italic text.

**Describe the benefits this feature would bring to BookStack users**
More clarity.

**Comment by ssddanbrown** [comment]
Hi @jungren
The BookStack markdown editor currently follows the parsedown spec which does not appear to have a syntax option for underlines upon using HTML `<u>` tags. [Interesting discussion about this here](https://talk.commonmark.org/t/feature-request-underline-text/343).

Just realised GitHub does not seem to have underlines available either.

**Comment by ssddanbrown** [comment]
Since this has had no further discussion and since a workaround is available I'll close this off.
