### ISSUE TITLE
New Page Button after Saving Page

### ISSUE THREAD

**Issue by ktm5j** [BookStackApp/BookStack#1707]
**Describe the feature you'd like**

It would be great to have a way to create a new page directly after saving the current page.  Currently, after saving a page, I have to go back out into the chapter or book before I can add another page.  This adds at least one unnecessary page load that could be avoided.

**Describe the benefits this feature would bring to BookStack users**

This would improve the workflow for adding pages to a chapter/book.  Would save at least one page load per page added to a chapter/book.  When quickly adding pages, this added page load adds a non-trivial amount of time waiting before I can continue to input content.

**Additional context**

As seen below, ideally there would be a new page button on the left toolbar (1)

Instead I have to click back out to the chapter (2) and then click "New Page"

![image](https://user-images.githubusercontent.com/3729107/66594076-58c4e100-eb66-11e9-8c4b-a480f9ff3607.png)

Thanks for your consideration!  Absolutely love bookstack, thanks for all the work you've done

**Comment by ssddanbrown** [comment]
Thank you for your clear request @ktm5j.

This has already been requested under #1267 so I'll close this to cut down on duplicates.
To be totally honest, The hardest part of this will be deciding what the button text would be. "Create sibling page" or "Create page in parent chapter" are both akward action names and kind of ruin the existing clear single-word actions in the sidebar.

**Comment by ktm5j** [comment]
Whoops sorry for the dupe.  Could I suggest using just the text "Next page" with the same plus sign icon that the "New page" button has?  I think that would get the message across.

Thanks again for everything!
