### ISSUE TITLE
Every Startup ask to migrate

### ISSUE THREAD

**Issue by docfactory37** [BookStackApp/BookStack#1710]
**Describe the bug**
On first start up always ask the below i can understand if this is the first time setting up the container but should not ask on ever start up

**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? (yes/no) [no]:

**Steps To Reproduce**
1. start contianer
2. input yes on first set up to migrate tables
3. stop contianer
4. start container on second start it will ask for this agian

**Expected behavior**
Ask on first time of setting up the container, then should not ask you agian.

**Screenshots**

* First time start 
![image](https://user-images.githubusercontent.com/20963053/66693043-3d85dd00-ecf0-11e9-96d0-5beed1de9994.png)

Secdion time start up 
![image](https://user-images.githubusercontent.com/20963053/66693055-5a221500-ecf0-11e9-983d-c7110c093019.png)

**Comment by ssddanbrown** [comment]
Hi @docfactory37,
What container config are you using? This seems like an issue specific to your container setup. BookStack does not officially ship with a production-level container config.

**Comment by docfactory37** [comment]
I'm using solidnerd/bookstack docker image.

**Comment by ssddanbrown** [comment]
@docfactory37 Ah okay. It sounds like this issue: https://github.com/solidnerd/docker-bookstack/issues/45. 

You may want to add a comment there to indicate that this is still an issue.
