### ISSUE TITLE
Shelf and Bookstack Symbols

### ISSUE THREAD

**Issue by Phreeak** [BookStackApp/BookStack#1711]
Hi,
is there an option to hide the symbols laying over the pictures?

![2019-10-12 12](https://user-images.githubusercontent.com/21967882/66700427-49719f00-ecf0-11e9-95eb-0e57e61d329b.png)

Thanks

**Comment by ssddanbrown** [comment]
Hi @Phreeak,
There's no official setting to manage just that icon but you can add the following to the "Custom HTML head" setting to hide these icons:

```html
<style>
	.entity-list-item-image svg {
		display: none;
	}
</style>
```

**Comment by Phreeak** [comment]
Perfect, Thanks!
