### ISSUE TITLE
Can't find a saved Draft

### ISSUE THREAD

**Issue by ShemamAmir** [BookStackApp/BookStack#1713]
Dears,
I created a page, and started editing it, and then saved it as draft.  When I tried to open it again I could not find it neither in the book that I created it in, nor in My Recent Drafts.  I am sure it was saved before I logout from my bookstack.  Any ideas that may help please?  thanks in advance

**Comment by ssddanbrown** [comment]
Hi @ShemamAmir,
Are you sure it didn't get saved as a page at somepoint? It's worth looking for a normal page, If you saved a draft on an existing non-draft page then your content should pre-populate when you go back into the page to edit. Probably a good idea to look for a page names "New Page" as that could be it.

Other than that, you could scan the database if you have access. Either the `pages` or `page_revisions` table.

**Comment by ShemamAmir** [comment]
Hi, 
Thank you so much for your quick reply,
I did not save it as page.  I saved it directly as draft

**Comment by ssddanbrown** [comment]
Okay, If at no point you hit "Save Page", then you'll need to look into the database as my comment above, if you can't see it via the UI. Look for something updated around the same time. 
If not there then it may just be lost.

**Comment by amo13** [comment]
> Are you sure it didn't get saved as a page at somepoint? It's worth looking for a normal page, If you saved a draft on an existing non-draft page then your content should pre-populate when you go back into the page to edit. Probably a good idea to look for a page names "New Page" as that could be it.

Thank you so much for this comment, it just saved me a *lot* of time =)

**Comment by ssddanbrown** [comment]
@amo13 No worries! 

Will close this off since there has not been a response from the original issue creator in a few months.
