### ISSUE TITLE
Deleting page from chapter returns to book, not chapter

### ISSUE THREAD

**Issue by cw1998** [BookStackApp/BookStack#1715]
**Describe the bug**
When you delete a page from a chapter, you are returned to the book view, not the chapter view.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to a book with a chapter
2. Click on the chapter
3. Click on a page in the chapter
4. Delete the page
5. Observe that you are brought back to the book.

**Expected behavior**
Expected behaviour for me would be to go one step up in the breadcrumbs instead of going back to the book.

If you go from book -> chapter -> page -> delete, then it would make sense to me that you are brought back to the chapter

If you go from book -> expanded page list for a chapter -> page -> delete, then it would make sense to go back to the book (and bonus points if you can be scrolled back down to where the chapter is in the list)

If you go from dashboard -> page -> delete, then you should be brought back to the dashboard.

etc...

**Screenshots**
N/A

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: 0.27.4 
 - PHP Version: 7.3
 - Hosting Method:  Docker

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @cw1998.
I agreed that this behaviour would make sense. I have now applied this behaviour to `master`, to be part of the next feature release (v0.28).
