### ISSUE TITLE
No selectable images after upload

### ISSUE THREAD

**Issue by irreleph4nt** [BookStackApp/BookStack#1716]
**Describe the bug**
When I am editing a page and upload a picture, the GUI tells me the upload succeeded and I can see my file under bookstack/public/uploads/images/gallery/2019-10/ but it does not show up in the GUI. The windows where you can select an image or search for one stays blank. 

I am on a fresh CentOS 8 install of 0.27.4.

**Steps To Reproduce**
1. Go to any page, a new one or edit existing one
2. Click on insert image
3. Upload any image file
4. Watch the "Select Image" dialog window

**Expected behavior**
An image that has been uploaded successfully should become available in the "Select Image" dialog so one can actually insert it into a page.

**Screenshots**
I am also seeing this in the Firefox console when the "Select Image" dialog opens and I subsequently upload a file.

![Bildschirmfoto vom 2019-10-14 21-02-55](https://user-images.githubusercontent.com/29428359/66776833-a4112380-eec7-11e9-9244-1fc68a9ea94f.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.4
 - PHP Version: 7.2.11
 - Hosting Method (Nginx/Apache/Docker): Nginx & Letsencrypt 

**Additional context**
My env file contains only the bare minimum of app_key, app_url and database information. Creation of text-based pages works fine.

**Comment by mvanwessem-hiveip** [comment]
I have noticed the same error:

![error #1](https://user-images.githubusercontent.com/54842854/66837256-9d7fbc00-ef5a-11e9-8922-c30954258ac4.png)

![error #2](https://user-images.githubusercontent.com/54842854/66837270-a1abd980-ef5a-11e9-8408-fe7dc6ae8ef9.png)



**Your Configuration (please complete the following information):**

- Exact BookStack Version (Found in settings): 0.27.4
- PHP Version: 7.3.10 (alson on 7.3.9)
- OS Version: CentOS Linux release 7.6.1810 (Core)
- Hosting Method (Nginx/Apache/Docker): Nginx & Trustico wildcard SSL

**Additional context:**
STORAGE_TYPE=local
STORAGE_IMAGE_TYPE=local
STORAGE_ATTACHMENT_TYPE=local_secure

No Secure image upload is set in settings.

**Comment by irreleph4nt** [comment]
@ssddanbrown
Any chance you can take a look at this? Meanwhile I'll roll back to v0.26 and test again.

**Comment by irreleph4nt** [comment]
@ssddanbrown I can confirm that this issue does not exist in v0.26.4. I installed that version on CentOS 8 and adding images to pages works fine.

**Comment by koesie10** [comment]
I encountered this issue as well. BookStack doesn't seem to recognize `content-type: application/json; charset=utf-8` header as JSON, it only recognizes `content-type: application/json`. In my case I had the `charset utf-8;` directive in my Nginx config file. When I removed it, images started working again.

**Comment by ssddanbrown** [comment]
Sorry @irreleph4nt for not coming to this until now. Are you still having issues?

If so, please could you confirm what the first error in the console log shows? Or if there are any failed requests in the network tab in the devtools when uploading an image?

I'm thinking the errors shown could be misleading but a failed request causes a side-effect to throw the errors.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
