### ISSUE TITLE
Export .MD file in addition to HTML and PDF

### ISSUE THREAD

**Issue by caseydierking** [BookStackApp/BookStack#1717]
**Describe the feature you'd like**
The ability to export single or bulk pages in .MD format instead of HTML or PDF

**Describe the benefits this feature would bring to BookStack users**
Let me preface this by saying I love bookstack. 
I want to be able to backup my files to a flat file structure and share them as I need to at the file level. I know we have HTML and PDF options for exporting, but I would love to be able to export the file directly to markdown. 

A lot of times, I write documentation for my company in bookstack and transfer that information over to our other static site generator for our docs. This would be a handy feature for me.

**Comment by ssddanbrown** [comment]
Hi @caseydierking,
Thanks for the request. At some point of the upcoming API build we'll look to handle conversion between HTML and Markdown on the back-end (Current conversion is done client-side only), At that point it should be a quick job to enable markdown as an export option. Could technically implement it sooner but I'd prefer to build the feature for all users rather than needing to add dynamic control to export options dependant on what page editor is in use.

Somewhat related to #1273.

**Comment by caseydierking** [comment]
Thanks for the response @ssddanbrown . Also thank you for your time and effort into this project. I'm impressed at how well thought out your responses are to issues and feature requests. 

Is there a current roadmap on development for the API? Anything others can do to help contribute?

Thanks,

**Comment by ssddanbrown** [comment]
@caseydierking Thanks!

No official roadmap specifically for the API. For the next release we'll probably have the auth mechanism and endpoints for one focused thing (Like just books) so it can be tested and feedback can be provided before we span it out to cover most BookStack actions. 

Just a case of me finding the time to get started on it.

**Comment by XVilka** [comment]
I think the second, related option should be also "Export MD with attachments", that will produce Markdown file, add the attached images/other files, then put everything in ZIP for downloading.

**Comment by alderson59** [comment]
Hey, new to this project, and already loving it! How are pages and books currently stored? I can't seem to find the directory in which they are stored. Is this all done in the MYSQL database?

Would it be possible to keep pages and books stored on a directory openly as .md files, as an option? I would love to store some important info using bookstack to manage, and would especially be useful if the files are not easily accessible in the event of a crash/whatever.

Not sure if this deserves its own FR, so pinging for some thoughts first :)

**Comment by OliverEvans96** [comment]
I agree with @alderson59 - I would feel much more comfortable putting important content into bookstack if I know I can easily export it / back it up in a plaintext format

**Comment by jacky35** [comment]
+1 
Yes I would also be reassured to have flat files.

**Comment by DOFfactory** [comment]
I would also welcome to see this as a milestone feature implemented soon. Please please please ☺

**Comment by ssddanbrown** [comment]
An implementation of markdown export has been merged as part of #2115 therefore I will close this off. This will be included in the next feature release.
