### ISSUE TITLE
Viewers are able to copy pages across books

### ISSUE THREAD

**Issue by grighi** [BookStackApp/BookStack#1722]
**Describe the bug**
Viewers are able to copy pages across books. I may be missing something, but this seems to be different than the intended role (i.e. able to view but not able to edit books). 

**Steps To Reproduce**
1. Login in as a user with role Viewer
2. Open the page of a book
3. Copy is in the Action pane for a page

**Expected behavior**
For viewers, the only button in the action pane should be export.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.27.4

**Comment by ssddanbrown** [comment]
Hi @grighi,
The "Copy" option should only show to someone if they have permission on any book or chapter to create pages within. You may see this for such "Viewer" roles, where they don't have creation abilities at the role level, if custom entity-level permissions have been granted.

You could test this by acting as a viewer, and click the option to copy a page, then open the "Destination" panel. If you see a few select chapters or books in there then it's likely custom set permissions at play.

**Comment by grighi** [comment]
Yep, tried to reproduce it and forgot I had changed a book permission, thanks.
