### ISSUE TITLE
Tags: Selecting a previous Tag from the dropdown list not working

### ISSUE THREAD

**Issue by burkusmax** [BookStackApp/BookStack#1725]
When you enter a Tag and save it, the next time you enter a tag a drop down list of previously entered tags will appear. It seems that after a few times selecting from this list it begins not to function. I still see the list, but am unable to click the value and it fill in. I have to arrow down and hit enter or I can start typing the letter that tag name starts with and it will allow me to click it once the list is filtered.

**Comment by ssddanbrown** [comment]
Sorry you were having issues with this @burkusmax.
As of the next release (v0.30) this system will be rebuilt.

If you still have issues after v0.30 please free free to open a new issue, with details of your browser and operating system.

Will therefore close this for now though.
