### ISSUE TITLE
Unable to setup HTTPS

### ISSUE THREAD

**Issue by ajjaic** [BookStackApp/BookStack#1740]
Hello there. I'm looking for some help setting up a bookstack server on digitalocean that I can access via HTTPS. For brevity, i'm going to keep it to the point.

* installed bookstack using docker-compose with [linuxserver.io](https://github.com/linuxserver/docker-bookstack).
* was able to configure it to use http and I am able to get that to work.
* I am completely clueless about setting up HTTPS to access my bookstack instance. And I was totally surprised when google gave me nothing when I searched for "bookstack https guide". 

Even if you are unable to provide me step by step, if you could point me in the right direction, it would be helpful. Been scratching my head over this for a few hours now.

**Comment by barry-smithjr** [comment]
This is not a BookStack issue but a general docker container & http issue. The easiest way is by putting the container behind a reverse proxy such as Apache, Caddy, or Nginx.

**Comment by ssddanbrown** [comment]
Linuxserver.io have a handy guide on setting up a reverse HTTPS proxy here:
https://blog.linuxserver.io/2017/11/28/how-to-setup-a-reverse-proxy-with-letsencrypt-ssl-for-all-your-docker-apps/

Also serves as a good intro into reverse proxies themselves.

**Comment by ssddanbrown** [comment]
Since this is a few months old and there has been little follow-on conversation I'll close this off.
