### ISSUE TITLE
Sort Books within Shelves

### ISSUE THREAD

**Issue by sazora** [BookStackApp/BookStack#1742]
When I enter through the shelves area and then click on a topic within the shelves, it would be helpful if we could have the sort helper option like there are in other sections.

It would make it uniform across the platform.

![Image 2019-10-24 at 5 21 30 PM](https://user-images.githubusercontent.com/54324712/67526475-df0f1600-f682-11e9-83a6-163e29444d3c.png)

**Comment by sunnythaper** [comment]
I would like to second this feature request!

**Comment by judokan9** [comment]
I would also like to have this feature

**Comment by pablfr** [comment]
+1 :)

**Comment by sorinsfirlogea** [comment]
+1

**Comment by ssddanbrown** [comment]
Thanks to @guillaumehanotel this functionality has now been merged and will be part of the next feature release so I'll therefore close off this request.
