### ISSUE TITLE
Switch between markdown and wysiwyg (page specific)

### ISSUE THREAD

**Issue by Luffyyy** [BookStackApp/BookStack#1748]
**Describe the feature you'd like**
Ability to toggle between markdown and wysiwyg for each page.

**Describe the benefits this feature would bring to BookStack users**
Some users prefer markdown and some prefer wysiwyg.

**Comment by ssddanbrown** [comment]
Hi @Luffyyy,
Thank you for your request.

I feel that this is already covered by the existing issues #119, #369 & #842.
Therefore I'm going to close this to reduce duplicates.
