### ISSUE TITLE
How to change favicon in docker?

### ISSUE THREAD

**Issue by madmads11** [BookStackApp/BookStack#1750]
Hi, I need some support with regards to how to change the favicon.

I'm running in Docker and instead of the default blue stack of books, I would like to use my own favicon instead. However I am unsure where to place it or change the relevant settings.

**Comment by ssddanbrown** [comment]
Hi @madmads11,
There's currently no app specific way of changing the favicon.
The best way to achieve this currently, without altering app files, would be to set-up a webserver rule for requests to `/favicon.ico` and serve your custom favicon on that rule.

**Comment by madmads11** [comment]
Hi Dan Brown, thanks for the quick answer.

I don't mind altering the app files, my problem is that I cannot seem to locate the favicon.ico file. I'm running in Docker and I've been searching but can't find it. What's the location of it?

**Comment by ssddanbrown** [comment]
Within the project it's within the `public` folder. It's served at the `/favicon.ico` endpoint. Where that is within the container or mounted volumes will depend on the specific container you're running. What docker setup are you running?

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this.

If this issue remains please feel free to open a new issue, referencing this one.
