### ISSUE TITLE
Issue uploading files

### ISSUE THREAD

**Issue by edwardbattye** [BookStackApp/BookStack#1753]
When trying to upload a file however over thumbnail and get error "405 not allowed error". Using nginx. Checked file permissions and they are correct, assuming this is a webserver issue. In the nginx log get following error
"2019/10/29 10:41:20 [error] 21713#21713: *12 open() "/var/www/bookstack/public/attachments/get/page/55" failed (2: No such file or directory), client: 10.65.20.97, server: www.wiki.xxx.co.uk, request: "GET /attachments/get/page/55 HTTP/1.1", host: "wiki.xxx.co.uk", referrer: "https://wiki.xxx.co.uk/books/ed/draft/55"
"

 - Exact BookStack Version (Found in settings): BookStack v0.26.2
 - PHP Version: PHP 7.0.33-0ubuntu0.16.04.7 
 - Hosting Method (Nginx/Apache/Docker):  Nginx

**Comment by edwardbattye** [comment]
Solved, was this in the nginx config file:
location ^~ /attachments {
mp4;
mp4_buffer_size       1m;
mp4_max_buffer_size   5m;
}

**Comment by ssddanbrown** [comment]
Thanks for confirming you found a solution!
