### ISSUE TITLE
Make pages bigger

### ISSUE THREAD

**Issue by madsmka** [BookStackApp/BookStack#1757]
Is there a way to make the pages bigger in the width? Maybe a feature request or is it possible with the Custom HTML if so how?

![image](https://user-images.githubusercontent.com/47882801/67856645-4f9bb400-fb15-11e9-8289-a37842bc6934.png)

**Comment by KeithIT-Dev** [comment]
I was wondering the same thing. I don't really like this new UI

**Comment by zlatin** [comment]
I think an option to hide sidebars will solve the problem.

**Comment by KeithIT-Dev** [comment]
The font is also an issue, the feature updates were great but the UI shouldn't have changed.

**Comment by madsmka** [comment]
I just think that there are so much wasted space from the page to the menus. Which we really could use in some of our big pages.

**Comment by KeithIT-Dev** [comment]
> I just think that there are so much wasted space from the page to the menus. Which we really could use in some of our big pages.

I agree. Hopefully it all gets addressed in a upcoming update. I'm glad my team and I was able to view the demo site before I upgraded my prod instance.

**Comment by ssddanbrown** [comment]
Using the following CSS in the "Custom HTML Head" option will help wider things a bit if that's what you're after:

```html
<style>
@media screen and (min-width: 1400px) {
    .tri-layout-middle-contents {
        max-width: 1700px;
    }
}
.page-content { max-width: 1200px; }
</style>
```

Could be some side-effects of this and may break thus require tweaking on update.

---

> The font is also an issue,

As in the fonts used? I don't think these have changed in a good while. A set of system fonts have been the default since 2017 at least. Or is this in regards to weighs and sizes? I specifically tried not to change the sizes of page content much to allow a smooth upgrade of user content.


> the UI shouldn't have changed

The UI will evolve as required over time. When doing this redesign I tried my best to explain the goals, keep development open and gain feedback from BookStack users as can be seen here: https://github.com/BookStackApp/BookStack/pull/1153

The change has generally been well received.

Just to clarify, the page-content wide remained pretty much the same to ensure that user-content would generally be unaffected upon update & space was generally better utilised in the new design thanks to a 3-column layout instead of 2.

> Hopefully it all gets addressed in a upcoming update.

It probably won't.

**Comment by madsmka** [comment]
> Using the following CSS in the "Custom HTML Head" option will help wider things a bit if that's what you're after:
> 
> ```
> <style>
> @media screen and (min-width: 1400px) {
>     .tri-layout-middle-contents {
>         max-width: 1700px;
>     }
> }
> .page-content { max-width: 1200px; }
> </style>
> ```
> 
> Could be some side-effects of this and may break thus require tweaking on update.

Yes, this is what I was looking for, thanks! :)

**Comment by Liandriz** [comment]
Thanks for the CSS tip, is it even possible too to disable the right sidebar, letting it on the left all the time no matter what is the page width?
Thanks!

**Comment by ssddanbrown** [comment]
@Liandriz You could copy out the mid-screen styles and extend the range, so something like:

```html
<style>
	@media screen and (min-width: 1000px) and (max-width: 4200px) {
		.tri-layout-container {
		    grid-template-areas:
		        "c b b"
		        "a b b"
		        ". b b";
		    grid-template-columns: 1fr 3fr;
		    grid-template-rows: min-content min-content 1fr;
		    padding-right: 24px;
		}
}
</style>
```

Again, Not officially supported and could cause side-effects but might get you what you want.

---

Since the original issue creator's problem has been addressed I'm going to go ahead and close this.

**Comment by Alexander-Wilms** [comment]
This works for me:

```css
<style>
@media screen and (min-width: 1400px) {
  .tri-layout-middle-contents {
    max-width: 1600px;
  }
}
.page-content { max-width: 9999px; }

.page-content.mce-content-body {
  max-width: 1600px;
}

@media screen and (min-width: 1400px) {
  .page-editor-wysiwyg .page-edit-toolbar, .page-editor-wysiwyg .page-editor-page-area {
    max-width: 1600px;
  }
}
</style>
```

**Comment by PhilippRieth** [comment]
I've thrown together some CSS and JavaScript that can be put into the "Custom HTML Head Content" -> [Extra Wide Pages and Editor for selected pages | Reddit
](https://www.reddit.com/r/BookStack/comments/1h0p79m/extra_wide_pages_and_editor_for_selected_pages/)

**Comment by aaronolsen** [comment]
I've written custom CSS+Javascript code that adds a button to the left sidebar to make it collapsible. Currently, it only collapses the left sidebar when the window has a two-column layout (window widths between 1001 and 1400 pixels). But you could modify the code to also collapse the sidebar when the window width is greater than 1400 pixels.

Here's what it looks like with the left sidebar expanded (button at top left).

![Image](https://github.com/user-attachments/assets/08ab5cad-7922-4c7f-8408-884f199df7c1)

And here's what it looks like when the left sidebar is collapsed:

![Image](https://github.com/user-attachments/assets/e90d2d4e-05ff-4d97-9994-43c542204471)

You can find the code, a full explanation of how it works, and a link to a working example page at https://3danatomystudios.com/coding/bookstack-hack-dynamic-collapsible-left-sidebar/.

**Comment by diepeterpan** [comment]
> I've written custom CSS+Javascript code that adds a button to the left sidebar to make it collapsible. Currently, it only collapses the left sidebar when the window has a two-column layout (window widths between 1001 and 1400 pixels). But you could modify the code to also collapse the sidebar when the window width is greater than 1400 pixels.
> 
> Here's what it looks like with the left sidebar expanded (button at top left).
> 
> 
> And here's what it looks like when the left sidebar is collapsed:
> 
> 
> You can find the code, a full explanation of how it works, and a link to a working example page at https://3danatomystudios.com/coding/bookstack-hack-dynamic-collapsible-left-sidebar/.

Can this or something similar **please** be added as standard so that we don't have to add it individually? Bookstack content viewing should be maximisable, as that is one of the major reasons, if not 'the' main reason, we capture content. To view and reference with ease.
