### ISSUE TITLE
LDAP with Active Directory

### ISSUE THREAD

**Issue by okwindart** [BookStackApp/BookStack#1761]
Bookstack can bind to AD but generates "Search operations error" Here is a screenshot from the logs:

![image](https://user-images.githubusercontent.com/46505131/67972088-ff3b5980-fbdb-11e9-80f3-7cf0f3b4cef6.png)

Also, here is my env file:
![image](https://user-images.githubusercontent.com/46505131/67972326-6fe27600-fbdc-11e9-9125-800b97d893aa.png)

Can someone please suggest what I may be doing wrong with the ENV file? Thanks in advance!

**Comment by philjak** [comment]
Are you sure you can bind your Active Directory anonymously? If you use Microsofts AD Explorer (https://docs.microsoft.com/en-us/sysinternals/downloads/adexplorer) - can you authenticate with the same set up credentials? (LDAP_SERVER and no user and no pass)

**Comment by Mant1kor** [comment]
AFAIK, AD server don't accept anonymous search request by default.

**Comment by okwindart** [comment]
@philjak Thank you! That was it! I can now authenticate BookStack against AD.
