### ISSUE TITLE
Books whose names have accents, generate slugs with errors

### ISSUE THREAD

**Issue by carlosmprzmx** [BookStackApp/BookStack#1765]
**Describe the bug**
Books whose names have accents, generate slugs with accents and a 404 error occurs when trying to access them

**Steps To Reproduce**
1. Go to a Shelve
2. Click on New Book
3. Name it with something like "Canción" and save it.
4. Try to access to the new book and you going to get an 404 error.

**Expected behavior**
Book correctly showed.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.27.5
 - PHP Version: 7.3 
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Hi @carlosmprzmx,
Sorry to hear you are having issues, Are you able to replicate this issue on the demo site:?
https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site

**Comment by carlosmprzmx** [comment]
on demo site not happens, maybe a problem with my Nginx

**Comment by ssddanbrown** [comment]
Can't think of anything on nginx, off the top of my head, that could cause this. Do you have `php-mbstring` installed?

**Comment by drzippie** [comment]
This is solved by using slugs that only contain characters that are the same encoded in a url (urlencode) as the original, that's why this change  (#2165)  solves that problem, as there are no characters that nginx or its rules take incorrectly

**Comment by ssddanbrown** [comment]
Closing this since, as said above, this should be resolved by #2165 which will be part of the next feature release.

If you still have issues after updating to v0.30 (Once it's released) feel free to open a new issue here.
