### ISSUE TITLE
Multi language Book

### ISSUE THREAD

**Issue by leechul** [BookStackApp/BookStack#1766]
When I Create a Book can i create a multi language version book?
for example the book default version is English and it also have other language .
so in a book I can write multi language book. and also can modify .
I have to create two some book one for english another one for different language.

by the way when i export a korean language book as PDF 

![image](https://user-images.githubusercontent.com/8435559/68080188-86393d80-fe39-11e9-8160-f6c094aa8dc4.png)

**Comment by zlatin** [comment]
Have you tried `wkhtmltopdf`? Here's how to set up https://www.bookstackapp.com/docs/admin/pdf-rendering/ . It works for me for Russian.

**Comment by leechul** [comment]
> Have you tried `wkhtmltopdf`? Here's how to set up https://www.bookstackapp.com/docs/admin/pdf-rendering/ . It works for me for Russian.
after i install WKHTMLTOPDF
APP_LANG=kr
WKHTMLTOPDF=/home/user/bins/wkhtmltopdf

i get below error

![image](https://user-images.githubusercontent.com/8435559/68522989-ceeb6d80-02f5-11ea-95f5-c8f93baab0cd.png)

**Comment by ssddanbrown** [comment]
Thanks for your request.

Mulitple language support is already open under #569 so therefore I'll close this off as a duplicate.
