### ISSUE TITLE
Tag Management UI

### ISSUE THREAD

**Issue by abossert** [BookStackApp/BookStack#1773]
**Describe the feature you'd like**
I would like a single user interface where I can manage tags and tag values with the ability to see a mapping of where tags are (listing of shelves, books, chapters, and pages).

**Describe the benefits this feature would bring to BookStack users**
Tags are very easy to add and the live suggestions as you type are great, however, as a project ages, it is quite likely that the tags will get out of control unless there is an easy way to manage them and clean them up periodically.  It would be great to be able to go to one place in the UI and be able to both see what tags are associated with what entities (shelves, books, etc.)

**Additional context**
The essential functionality requires no more than a new UI that simply reverses the normal mapping, which would be this:
[Shelf | Notebook | Chapter | Page] --> [tag1:tag-value1,tag2:tag-value2]
to this:
tag1:tag-value1 --> [Notebook1, Page21, Page23, Chapter3]

A nice to have feature down the road would be to include some data cleaning utilities such as what is included in tools like OpenRefine (similar strings, semantic similarity, misspellings, etc.)...But under no circumstances, should the latter feature be construed as necessary for an initial capability.

**Comment by Cave-Johnson** [comment]
After recently having found how useful tags are for searching, i would love this feature!

**Comment by ssddanbrown** [comment]
Related to #868 and #1354.

**Comment by saijojoe** [comment]
I would love a way to manage and edit tags. Right now, I have no way to modify a tag created in error due to a typo. I can remove it and create a new tag that's spelled correctly, but the old, incorrect tag remains.

**Comment by ssddanbrown** [comment]
@saijojoe The old tag should not remain, and you should be able to simply edit the name or the value of existing tags.

Maybe [play with the demo instance](https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site) to see if the behaviour is the same there, and if so, might be worth raising as an issue if you're able to provide clear steps in not being able to edit or remove tags.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since a tag overview dashboard, with a full breakdown of usage, was added as part of BookStack v21.11:

https://www.bookstackapp.com/blog/bookstack-release-v21-11/#new-tags-overview
