### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by prog20901** [BookStackApp/BookStack#1774]
How to install on a Windows machine ? I would like to install in a windows machine...to work in my desktop

**Comment by ssddanbrown** [comment]
Hi @prog20901,
Do you have any experience installing/managing web apps using something like apache?
Unfortunately this is a web hosted app so there's no easy installer, You'll need to manage separate web-server+php & database components to run BookStack.

**Comment by ahmadhadidi** [comment]
I was able to run Bookstack on my windows machine by installing [Docker](https://www.docker.com/products/docker-desktop) and running the script that's from [solidnerd](https://hub.docker.com/r/solidnerd/bookstack/).

Pre-requisite: Make sure that you have a version of Windows that supports VMs, e.g., Windows 10 Pro.

**Comment by prog20901** [comment]
Got it..Thanks a lot..
