### ISSUE TITLE
Use Laravel related translation from caouecs/Laravel-lang

### ISSUE THREAD

**Issue by zlatin** [BookStackApp/BookStack#1775]
**Describe the feature you'd like**
Use Laravel related translation files from https://github.com/caouecs/Laravel-lang

**Describe the benefits this feature would bring to BookStack users**
We don't need to translate common Laravel files like Validation

**Additional context**
Checked Russian and Ukrainian translations, and they look good at first glance.

**Comment by ssddanbrown** [comment]
Thanks @zlatin,
I can see how these would be useful and save a fair amount of effort. My main reservation would be how we can accurately handle attribution, especially with the recently implemented crowdin system which aligns all comments and file content fairly strictly.

**Comment by ssddanbrown** [comment]
I'm going to close this off as I don't really want to get into the license complications this introduces, especially with our translations automatically going into the crowdin translation memory.
