### ISSUE TITLE
Can Not get wkhtmltopdf rendering Chinese characters 

### ISSUE THREAD

**Issue by jzoy** [BookStackApp/BookStack#1778]
**Describe the bug**
Hey guys, I'm using bookstack with wkhtmltopdf plugin.
I did lots of reserch but still cannot get wkhtmltopdf to rendering chinese characters.

**Steps To Reproduce**
1. tried to use Dompdf not working 
2. tried to install wkhtmltopdf and upload `msyh.ttf` & `simsun.ttc` fonts to `/usr/share/fonts/` folder not working 
![](http://file.jzoy.com/2019/11/try-docker/wkhtmltopdf-github-issue-1.png)
3. tried to install chinese fonts still not working
 ```
 $ sudo apt-get install ttf-wqy-zenhei     
 $ sudo apt-get install ttf-wqy-microhei
```
4. tested use wkhtmltopdf command line " wkhtmltopdf www.baidu.com baidu.pdf", and download baidu.pdf file, it works well.
![](http://file.jzoy.com/2019/11/try-docker/wkhtmltopdf-github-issue-2.png)

**Expected behavior**
Could any tell me how to set the font, Thanks a lot!!

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):0.25.1(docker:linuxserver/bookstack)
 - PHP Version:7.2
 - Hosting Method (Docker): traefik 2.0

**Comment by or0or1** [comment]
兄弟，可以看看  https://github.com/or0or1/docker-bookstack/blob/master/readme-%E4%B8%AD%E6%96%87.md 。

**Comment by jzoy** [comment]
太感谢了，可以解释一下问题产生的原因吗，折腾了一个星期了，愣是没解决。。。

**Comment by ssddanbrown** [comment]
Judging by the posting in https://github.com/linuxserver/docker-bookstack/issues/50, this appeared to be a problem specific to within the container environment. Will therefore close this off.
