### ISSUE TITLE
Deleting comment is not working

### ISSUE THREAD

**Issue by MihaTomsic** [BookStackApp/BookStack#1782]
**Describe the bug**
Comment cannot be deleted by pressing trash icon and then trash icon again

**Steps To Reproduce**
1. Go to page
2. Add a comment and save it - comment is added
3. Click trash can in the comment - pop-up appears 
4. Clich trash can (Izbriši = Delete) in the popup
5. Nothing happens 
6. Comment is still there (also checked in database -> comment is still there)

**Expected behavior**
After deleting the comment should be gone.
Also in the database.

**Screenshots**
![bookstackcomment1](https://user-images.githubusercontent.com/5785564/68929736-38073100-078d-11ea-91e3-d6638e760ccb.png)

![bookstackcomment2](https://user-images.githubusercontent.com/5785564/68929770-45bcb680-078d-11ea-92f9-45e82b9afcfe.png)

![bookstackcomment3](https://user-images.githubusercontent.com/5785564/68929778-49e8d400-078d-11ea-9370-6423e33588a5.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.27.4
 - PHP Version: PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
 - Hosting Method (Nginx/Apache/Docker): Apache/2.4.29 (Ubuntu)

**Additional context**
Maybe it has something to do with slovenian version of the site.

**Comment by ssddanbrown** [comment]
Hi @MihaTomsic,
[BookStack v0.27.5](https://github.com/BookStackApp/BookStack/releases/tag/v0.27.5) specifically addressed an issue where comments could not be deleted. Please could you try updating to the latest BookStack version and see if the issue persists?

**Comment by MihaTomsic** [comment]
Updating to 0.27.5 worked great. 
Coments can be deleted and created. 
Is it safe to just do git pull on minor releases? Or would it be better to do the composer and artisan steps?
I am new to php/mysql web apps.

**Comment by james-geiger** [comment]
@MihaTomsic In regards to updating, the update command in the [BookStack documentation ](https://www.bookstackapp.com/docs/admin/updates/) is:
```
git pull origin release && composer install && php artisan migrate
php artisan cache:clear
php artisan view:clear
```
The composer and artisan steps are necessary to bring in any changes in packages or dependencies.

These steps essentially say, "Download new code, install any updated packages, update any changed database tables, remove cached files, update the page templates."

I've found that updating php apps is remarkably easy when they follow this method.  Always be sure to run the commands as whatever user 'owns' the directory that BookStack lives in on your instance to avoid permissions issues.

**Comment by MihaTomsic** [comment]
Thanks for the quick explanation. I am very happy with BookStack!
