### ISSUE TITLE
Instalation different subfolder

### ISSUE THREAD

**Issue by fontesanta** [BookStackApp/BookStack#1784]
Can someone help me please?
I'm trying to install Bookstack in a different directory.
When https: //192.168.32.6/wiki.
Unable to access this site
192.168.32.6 refused to connect.
Try it:
Check Connection
Check proxy and firewall
ERR_CONNECTION_REFUSED
I list my settings.
Thanks.

Instalation in /var/www/wiki/BookStack

My .env file

Application URL
Remove the hash below and set a URL if using BookStack behind
a proxy, if using a third-party authentication option.
This must be the root URL that you want to host BookStack on.
All URL's in BookStack will be generated using this value.
APP_URL=https://192.168.32.6/wiki

And my 000-default.conf

```
<VirtualHost *:80>
# The ServerName directive sets the request scheme, hostname and port that
# the server uses to identify itself. This is used when creating
# redirection URLs. In the context of virtual hosts, the ServerName
# specifies what hostname must appear in the request's Host: header to
# match this virtual host. For the default virtual host (this file) this
# value is not decisive as it is used as a last resort host regardless.
# However, you must set it for any further virtual host explicitly.
#ServerName www.example.com

    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
    # error, crit, alert, emerg.
    # It is also possible to configure the loglevel for particular
    # modules, e.g.
    #LogLevel info ssl:warn

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    # For most configuration files from conf-available/, which are
    # enabled or disabled at a global level, it is possible to
    # include a line for only one particular virtual host. For example the
    # following line enables the CGI configuration for this host only
    # after it has been globally disabled with "a2disconf".                                                                                                                                         #Include conf-available/serve-cgi-bin.conf                                                                                                                                              


    # BookStack Configuration
Alias "/wiki" "/var/www/wiki/Bookstack/public"

<Directory "/var/www/wiki/Bookstack/public">
  Options FollowSymlinks
  AllowOverride None
  Require all granted

  RewriteEngine On
  # Redirect Trailing Slashes If Not A Folder...
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*)/$ /$1 [L,R=301]

  # Handle Front Controller...
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^ index.php [L]
</Directory>


<Directory "/var/www/wiki">
  AllowOverride None
  Require all denied
</Directory>
# End BookStack Configuration
vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

**Comment by ssddanbrown** [comment]
Hi @fontesanta,
Can you check if any errors appear in your apache error log after a bad request?
Likely to be at `/var/log/apache2/error.log` if you on ubuntu.

**Comment by Mant1kor** [comment]
@fontesanta you've tried to open site with **https** protocol. It means you have to use certificate and your web-server configured to listen 443 port, but it's not.
So use `http` in browser and `.env` file, or configure apache to https.

**Comment by fontesanta** [comment]
Hello thank you very much for your help,
I changed in .env to http: // and the result is the same.
ubuntu error.log at: / var / log / apache2

[Mon Nov 18 06: 25: 06.447887 2019] [mpm_prefork: notice] [pid 1808] AH00163: Apache / 2.4.29 (Ubuntu) configured - resuming normal operations
[Mon Nov 18 06: 25: 06.447955 2019] [core: notice] [pid 1808] AH00094: Command line: '/ usr / sbin / apache2'
[Mon Nov 18 11: 05: 44.605609 2019] [mpm_prefork: notice] [pid 1808] AH00169: caught SIGTERM, shutting down
[Mon Nov 18 11: 05: 45.832869 2019] [mpm_prefork: notice] [pid 1053] AH00163: Apache / 2.4.29 (Ubuntu) configured - resuming normal operations
[Mon Nov 18 11: 05: 45.833059 2019] [core: notice] [pid 1053] AH00094: Command line: '/ usr / sbin / apache2'
[Mon Nov 18 11: 06: 12.256877 2019] [authz_core: error] [pid 1059] [client 192.168.32.188:62499] AH01630: client denied by server configuration: / var / www / wiki / Bookstack
[Mon Nov 18 11: 06: 25.197233 2019] [authz_core: error] [pid 1062] [client 192.168.32.188:62506] AH01630: client denied by server configuration: / var / www / wiki / Bookstack

**Comment by Mant1kor** [comment]
What address in browser did you try to open?

**Comment by lommes** [comment]
I'm not completly sure, but I think the Directoy directives are sequentially, so the <Directory "/var/www/wiki"> at the end overrides the <Directory "/var/www/wiki/Bookstack/public"> from earlier.

**Comment by fontesanta** [comment]
I´m trying 192.168.32.6/wiki

**Comment by fontesanta** [comment]
I tried different configurations without sucess.<Directory "/var/www/wiki"> at the end overrides the <Directory "/var/www/wiki/Bookstack/public"> from earlier.

**Comment by Mant1kor** [comment]
> <VirtualHost *:80>
Change to
`<VirtualHost _default_:80>`

**Comment by fontesanta** [comment]
Now i´m getting this:
403 Forbidden
You don't have permission to access this resource.
Apache/2.4.29 (Ubuntu) Server at 192.168.32.6 Port 80

[Mon Nov 18 15:34:41.884865 2019] [authz_core:error] [pid 2529] [client 192.168.32.188:50634] AH01630: client denied by server configuration

**Comment by fontesanta** [comment]
I tried to install again and came back to this:
http://192.168.32.6/wiki

Not Found
The requested URL was not found on this server.
Apache/2.4.29 (Ubuntu) Server at 192.168.32.6 Port 80
----
[Tue Nov 19 16:24:15.765111 2019] [core:notice] [pid 3939] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 19 16:27:42.042462 2019] [mpm_prefork:notice] [pid 3939] AH00169: caught SIGTERM, shutting down                                    [Tue Nov 19 16:27:42.341184 2019] [mpm_prefork:notice] [pid 4019] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Nov 19 16:27:42.341319 2019] [core:notice] [pid 4019] AH00094: Command line: '/usr/sbin/apache2'                                       [Tue Nov 19 16:28:32.103348 2019] [mpm_prefork:notice] [pid 4019] AH00169: caught SIGTERM, shutting down
[Tue Nov 19 16:28:32.393543 2019] [mpm_prefork:notice] [pid 4063] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Nov 19 16:28:32.393714 2019] [core:notice] [pid 4063] AH00094: Command line: '/usr/sbin/apache2'
----------
.env

# Application key
# Used for encryption where needed.
# Run `php artisan key:generate` to generate a valid key.
APP_KEY=base64:VGltbQQY7wdK4ClV/Bn/zjslV1UiOcOxfU+TowXjd7k=

# Application URL
# Remove the hash below and set a URL if using BookStack behind
# a proxy, if using a third-party authentication option.
# This must be the root URL that you want to host BookStack on.
# All URL's in BookStack will be generated using this value.
APP_URL=http://192.168.32.6/wiki

# Database details
DB_HOST=localhost
DB_DATABASE=wiki
DB_USERNAME=wiki
DB_PASSWORD=wikiPassw0rd!!

# Mail system to use
# Can be 'smtp', 'mail' or 'sendmail'
MAIL_DRIVER=smtp

# SMTP mail options
MAIL_HOST=localhost
MAIL_PORT=1025
---------------------------------

000-default.conf

<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".                                                                                                                                         #Include conf-available/serve-cgi-bin.conf                                                                                                                                              


        # BookStack Configuration
        Alias "/wiki" "/var/www/wiki/Bookstack/public"
 <Directory "/var/www/wiki/Bookstack/public">
        Options FollowSymlinks
        AllowOverride None
        Require all granted

        RewriteEngine On
        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)/$ /$1 [L,R=301]

        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]
        </Directory>

        <Directory "/var/www/wiki/Bookstack">
        AllowOverride None
        Require all denied
        </Directory>

        # End BookStack Configuration


</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

Thanks!

**Comment by lommes** [comment]
This might be (again) because you have a Directory directive for /var/www/wiki/Bookstack/public and override it with the one for /var/www/wiki/Bookstack.

It might work after placing 
```
 <Directory "/var/www/wiki/Bookstack">
    AllowOverride None
    Require all denied
    </Directory>
```
BEFORE
```
<Directory "/var/www/wiki/Bookstack/public">
Options FollowSymlinks
AllowOverride None
Require all granted

    RewriteEngine On
    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
    </Directory>
```

and restaring apache

**Comment by fontesanta** [comment]
I tested with what you said but the result is, unfortunately, the same ...

404Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at 192.168.32.6 Port 80

**Comment by lommes** [comment]
Is mod_alias enabled? `sudo a2enmod alias`

Since the error now is 404, which means the file/folder you are trying to access is not found, there should be something helpfull in the webserver (errror.)log.

It might be necessary to set AllowOverride All in the directory directive for the public folder.

**Comment by fontesanta** [comment]
sudo a2enmod alias : Module alias already enabled
-----
[Wed Nov 20 06:25:09.185746 2019] [mpm_prefork:notice] [pid 4063] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Nov 20 06:25:09.185835 2019] [core:notice] [pid 4063] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 20 09:26:49.632467 2019] [mpm_prefork:notice] [pid 4063] AH00169: caught SIGTERM, shutting down
[Wed Nov 20 09:29:23.051220 2019] [mpm_prefork:notice] [pid 17655] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Nov 20 09:29:23.125420 2019] [core:notice] [pid 17655] AH00094: Command line: '/usr/sbin/apache2'
----------------------
How can i do it ? :It might be necessary to set AllowOverride All in the directory directive for the public folder.

Thank you

**Comment by fontesanta** [comment]
afs@ubuntuserver: /var/www/wiki/BookStack
The bookstack files are located here. Am I doing something wrong here?
tkyou.

**Comment by lommes** [comment]
To set the AllowOverride to All just replace 
`AllowOverride None` with `AllowOverride All` in the <Directory "/var/www/wiki/Bookstack/public"> part.

To get 404 errors in your error.log you need to change the LogLevel to info. There is a line in your config, just remove the # infront of #LogLevel info ssl:warn and restart apache

**Comment by fontesanta** [comment]
After remove the # infront of #LogLevel info ssl:warn and restart apache

 Unit apache2.service has begun starting up.
Nov 20 14:32:37 ubuntuserver apachectl[21627]: AH00526: Syntax error on line 141 of /etc/apache2/apache2.conf:
Nov 20 14:32:37 ubuntuserver apachectl[21627]: Cannot find module ssl
Nov 20 14:32:37 ubuntuserver apachectl[21627]: Action 'start' failed.
Nov 20 14:32:37 ubuntuserver apachectl[21627]: The Apache error log may have more information.
Nov 20 14:32:37 ubuntuserver systemd[1]: apache2.service: Control process exited, code=exited status=1
Nov 20 14:32:37 ubuntuserver systemd[1]: apache2.service: Failed with result 'exit-code'.
Nov 20 14:32:37 ubuntuserver systemd[1]: Failed to start The Apache HTTP Server.

**Comment by fontesanta** [comment]
I am combining some sites, maybe it is not the best approach, can you indicate some tutorial that I can follow to install on ubuntu 18.04 apache mysql? thank you.

**Comment by ssddanbrown** [comment]
Since this support issue is over a year old I'm going to close this off.

If still needed, Our 18.04 install script can often act as a good guide since we keep it commented for clarity:
https://github.com/BookStackApp/devops/blob/master/scripts/installation-ubuntu-18.04.sh

Otherwise, you could search for "Laravel" install/deployment tutorials/guides since it'd be much the same.
