### ISSUE TITLE
A user with the email ... already exists but with different credentials

### ISSUE THREAD

**Issue by oden08** [BookStackApp/BookStack#1785]
**Describe the bug**
All users nowe get logging in all of a sudden I get the error "A user with the email ... already exists but with different credentials".

**Steps To Reproduce**
1. Click on "Log in"
2. Enter credentials
3. Error displayed: "A user with the email ... already exists but with different credentials"

**Expected behavior**
Expected behavior is normal login

**Screenshots**
![image](https://user-images.githubusercontent.com/30605459/68970899-59c8de00-07b6-11ea-9a41-fbf1aa3431fb.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.26.0
 - PHP Version: PHP 7.2.20
 - Hosting Method (Nginx/Apache/Docker): 

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @oden08,
Can you confirm what authentication systems are active and which one you used to show the error message above?

LDAP? Standard Email+Password? Google?

**Comment by oden08** [comment]
Sorry for the delay, we are using LDAP.

**Comment by oden08** [comment]
Is there a log I can look at?  Could my user database have gotten messed up?  I've checked that my LDAP user is active and the password hasn't changed.

**Comment by oden08** [comment]
Ok, weird thing, ran some sql statements against the database and now we are able to connect in.

**Comment by Mikuz** [comment]
Hello there, I have this same problem.

My config:
			LDAP_SERVER=172.16.100.2:389
			LDAP_BASE_DN=ou=Pracownicy,ou=Users,ou=Propoint,dc=propoint,dc=pl
			LDAP_DN=xxxx
			LDAP_PASS=xxxx
			LDAP_USER_FILTER=(|(sAMAccountName=${user})(userPrincipalName=${user}))
			LDAP_VERSION=false
			LDAP_ID_ATTRIBUTE=mail
			LDAP_EMAIL_ATTRIBUTE=mail
			LDAP_DISPLAY_NAME_ATTRIBUTE=cn

When I login first time (on clear bookstack) using Ldap there are zero problems, but when I try to login again, it tries to create again a new account and it fails - because email is already taken.

**Comment by ssddanbrown** [comment]
@Mikuz If you're still facing issues please open a new issue since this one is closed, and the details required to create an issue will be helpful and may differ in your case.
