### ISSUE TITLE
Instant search 

### ISSUE THREAD

**Issue by guischmo** [BookStackApp/BookStack#1789]
**Describe the feature you'd like**
When you search for something in the search bar, the results would be shown instantly as you type, not just when you validate the search.

**Describe the benefits this feature would bring to BookStack users**
Faster search, more convenient and elegant,

**Comment by ssddanbrown** [comment]
Strongly related to #1235

**Comment by ssddanbrown** [comment]
I'm going to close this off since I feel it's very much covered by #1235.
