### ISSUE TITLE
Callouts overflow onto tags

### ISSUE THREAD

**Issue by davidPilkington** [BookStackApp/BookStack#179]
PHP Version: 5.6.24
MySQL Version: 5.6.32

Expected Behavior:
Callouts added to a page are responsive tags and the container is adjusted to the page width.

Actual Behavior:
The callouts text is responsive to the tags container, but the background colour of the callout fill into the Tags container (see below)

![topic_1___cds_wiki](https://cloud.githubusercontent.com/assets/1942239/18334376/1a74b174-75b6-11e6-84dc-851802810e1b.png)

**Comment by ssddanbrown** [comment]
Thank you for finding this issue. It is now fixed as of release [v0.12.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.12.2).
