### ISSUE TITLE
Support browsing with custom permissions

### ISSUE THREAD

**Issue by cze-karel** [BookStackApp/BookStack#1801]
**Describe the feature you'd like**
Allow user to navigate through the hierarchy of books and chapters if a single chapter or page access is given via custom permissions. 

Currently, if I am not mistaken, the user will not be able to navigate to a book without having a direct link: 
- no access allowed on the book permission (to avoid inheritance of the chapters) 
- access is given (via custom permissions) only to one chapter (or even a page) 

The scenario:
- we have a book that covers one product / project with multiple topics (internal and external)
- we want to give access to a client - but only to a "client related" chapter where we would store relevant information
- the customer should be able to see the book in such case and once opened, only the chapters that are assigned specifically
- in case only a page (or multiple pages are assigned), these should be listed on the book page (either in the root or in the hierarchy of chapters identified just by title)

**Describe the benefits this feature would bring to BookStack users**
Easier sharing model and navigation for the users who do not possess the book level / chapter permissions.

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for the request.

This becomes tricky as you've explicitly revoked permission to view the book for the given role. We purposefully will keep the book details hidden where possible as the name or description of the book itself may contain information that should not be visible. I understand this hinders visibility but a solution of showing the parent item detail is not something I'd look to incorporate.
