### ISSUE TITLE
Share a page / chapter using a link

### ISSUE THREAD

**Issue by cze-karel** [BookStackApp/BookStack#1802]
**Describe the feature you'd like**
Allow page / chapter sharing (view only is fine I believe) with external users (without having a user account) by generating a unique link. Similar to Google Drive sharing capabilities. 

**Describe the benefits this feature would bring to BookStack users**
Ability to share just one page or chapter instead of creating a user account. 

**Additional context**
There should probably be specific permission for the user role to allow this.

**Comment by ssddanbrown** [comment]
Thanks for the request @cze-karel.

An outstanding issue (#288) effectively covers the functionality requested in this issue so I'm going to go ahead and close this request to cut down on duplicates.

**Comment by cze-karel** [comment]
Apologies @ssddanbrown - I must have missed that issue (288) while looking around. It's exactly what I was referring to.
