### ISSUE TITLE
Having some troubles with subdirectory, CSS not loading..

### ISSUE THREAD

**Issue by Seterak** [BookStackApp/BookStack#1806]
I installed bookstack on a clean Ubuntu 18.04.3 LTS using the installation script, since i'm planning on having wordpress on my site at the same time, i'm trying to move it to www.mydomain.com/wiki, but failing to do so. 
I followed this guide: https://www.bookstackapp.com/docs/admin/subdirectory-setup/ and made the changes to 000-default.conf and the .env file but when i load my domain, CSS and JS are broken. 

How do i fix this?

**Comment by ssddanbrown** [comment]
Hi @Seterak,
Did you follow the last step in that guide to set your `APP_URL` in the `.env` file?

If so, Please could you view the source of your BookStack home page (Right click > View Source) then search for the text `/dist/styles.css?version=` and let me know the numbers shown after the version in addition to the format of the URL shown (Does it include `/wiki` ?)

**Comment by XinLiu92** [comment]
I have the same issue here. @ssddanbrown 
the /dist/styles.css?version= is v0.28.2

**Comment by ssddanbrown** [comment]
Since the original creator of this issue has not responded in a while I'm going to close this off.

@XinLiu92 If you still have the issue please create a new GitHub issue here so you can detail out your own environment to help use assist you more effectively.
