### ISSUE TITLE
Can I reduce the size of the text in the pages list view?

### ISSUE THREAD

**Issue by guischmo** [BookStackApp/BookStack#1807]
Hi, this is more a question than a feature requests. Since i'm not very good at Tweaking things I ask here if this is easily possible.

My problem is that I will do a Medicine database so for each chapter I'll have a huge list of pages. 
In the current configuration  when you deploy a chapter to display the list of pages inside, the fonts is quite big and there is a ton of spacing between each page title, which looks nice but when you have about 150 page to display a more "compacted" list would be more useful for me.

If there is an easy way (1-2 lines of code somewhere to edit) I'll gladly take it. If it's too complicated, well I'll forget about it...

Thanks for the help

<img width="1350" alt="prev" src="https://user-images.githubusercontent.com/28254131/69885873-b4e2f080-12df-11ea-814e-f6841cd115b9.png">

**Comment by ssddanbrown** [comment]
Hi @guischmo, 
Sorry for the late response.

This is possible with a little bit of custom CSS. Add the following to the "Custom HTML Head Content" option in the settings area:

```
<style>
	.book-content .entity-list h4, .chapter-content .entity-list h4 {
		font-size: 1.2em;
	}
</style>
```

You can tweak the `1.2` above to suite your needs. The default in BookStack is `1.666`. Note that future BookStack updates could affect this tweak.

**Comment by ssddanbrown** [comment]
Closing this off as it appears to be answered and no follow-up seems to be required.

**Comment by alen-2026** [comment]
<img width="921" height="527" alt="Image" src="https://github.com/user-attachments/assets/650d0b94-801c-431f-a900-1fbc1c668ee0" />

**Comment by ssddanbrown** [comment]
@alen-2026 

```html
<style>
[option\:entity-search\:entity-type="book"] .card > h1 {
  font-size: 1rem;
}
</style>
```

**Comment by alen-2026** [comment]
**thank you very much!**
`</style>
[option\:entity-search\:entity-type="book"] .card > h1 {
  font-size: 2.55rem;
  font-weight: bold;
  color: #0080FF;
  text-align: center;
  
</style>`
