### ISSUE TITLE
Asciidoc Support

### ISSUE THREAD

**Issue by stobias123** [BookStackApp/BookStack#1809]
**Describe the feature you'd like**
Asciidoc support in the same manner as mmarkdown.

**Describe the benefits this feature would bring to BookStack users**
Initially, just support for another common markup language. 

Could be extended for additional styles, templates, and other asciidoc features.

**Comment by ssddanbrown** [comment]
Hi ,
Thanks for opening this issue.

This has already been requested in #1478 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #1478 it will help show support for that request.
