### ISSUE TITLE
Get e-Mail notification if comment is posted or if a page has been updated?

### ISSUE THREAD

**Issue by elbsurfer** [BookStackApp/BookStack#1812]
Hello,
is there a possibility to get e-Mail notifications if a page has been updated or a comment has been posted?

Is there also another possibility to view recent changes - like all changes named with a date when the change did occur?

Thanks!

**Comment by ssddanbrown** [comment]
Hi @elbsurfer,
The request for notifications on content change or comments has been already requested as part of issues #147, #241, #1266, #560. 

In regards to viewing changes, You can click through on "Revisions" when viewing a page to view the history of updates in addition to seeing changes or viewing that specific version.
