### ISSUE TITLE
Can't send e-mail

### ISSUE THREAD

**Issue by AlphaJack** [BookStackApp/BookStack#1813]
I want BookStack to send e-mail for login verification and password reset requests. The credentials I'm using work on other services on my server, but on BS I can't get rid of this red error:
```
Email confirmation required but the system could not send the email. Contact the admin to ensure email is set up correctly.
``` 

My relevant .env settings look like
```ini
MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_FROM=server@example.com
MAIL_FROM_NAME=Example-Server
MAIL_USERNAME=Username
MAIL_PASSWORD=Password
MAIL_ENCRYPTION=tls
#MAIL_ENCRYPTION=null
#MAIL_ENCRYPTION=ssl
#MAIL_ENCRYPTION=""
```
I've also added `APP_DEBUG=true` but I can't read anything on the log regarding stmp.
I've also tried `php artisan config:clear` and `php artisan config:cache` after every change, but without success.

Configuration:
 - Exact BookStack Version: BookStack v0.27.5 
 - PHP Version: 7.4
 - Hosting Method: Nginx

**Comment by John-OShea-Wordbank** [comment]
I can't help with this error directly but can confirm we're able to send emails via SendGrid using an API key. Here's the BookStack config we're using:
```
MAIL_DRIVER=smtp
MAIL_FROM=mail@bookstack.wordbank.com
MAIL_FROM_NAME=BookStack

MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=apikey
MAIL_PASSWORD=SENDGRID_API_KEY_PASSWORD_HERE
MAIL_ENCRYPTION=tls
```

**Comment by AlphaJack** [comment]
Thank you, I've tried to use the API but nothing changed. I ended up doing a clean install of BookStack and a full update of its dependencies. 
It is working now, the problem wasn't about the MAIL fields.
