### ISSUE TITLE
Request support for fast.co login

### ISSUE THREAD

**Issue by fur2** [BookStackApp/BookStack#1815]
**Describe the feature you'd like**
Request support for fast.co login .

**Describe the benefits this feature would bring to BookStack users**
A very simple and friendly way to authenticate your mailbox and solve login and password issues.
https://fast.co/

**Comment by ssddanbrown** [comment]
Thanks for the suggestion, but I would not want to directly implement a proprietary solution like this. Appears they are now focused on ecommerce nowadays anyway, and hide their documentation. Therefore will close this off.
