### ISSUE TITLE
"Not found" after installation on sub-directory, incorrect SSL config?

### ISSUE THREAD

**Issue by Virion21** [BookStackApp/BookStack#1821]
Hello, i have followed the bookstack subdirectory setup instructions as described here: https://www.bookstackapp.com/docs/admin/subdirectory-setup/

It seems like no matter what i do though i get a 404 not found error trying to access the site.

I have it on var/www/bookstack, my bookstack.conf config is as follows:

```
<VirtualHost *:80>
    ServerName mysite.com
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
    Alias "/bookstack" "/var/www/bookstack/public"
</VirtualHost>

<VirtualHost *:443>
        ServerName mysite.com
        ServerAdmin admin@localhost
        DocumentRoot /var/www/bookstack/public/
        Alias "/bookstack" "/var/www/bookstack/public"

    SSLEngine on
    SSLCertificateFile      /etc/letsencrypt/live/mysite.com/fullchain.pem
    SSLCertificateKeyFile   /etc/letsencrypt/live/mysite.com/privkey.pem

    <Directory /var/www/bookstack/public/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews -Indexes
            </IfModule>
            RewriteEngine On
            # Handle Authorization Header
            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
            # Redirect Trailing Slashes If Not A Folder...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_URI} (.+)/$
            RewriteRule ^ %1 [L,R=301]
            # Handle Front Controller...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.php [L]
        </IfModule>
    </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
My .env file's APP URL is set to "APP_URL=https://mysite.com/bookstack"

Any help would be appreciated...

**Comment by ssddanbrown** [comment]
Hi @Virion21,
Is the 404 page a BookStack page (Do you see a blue header bar?) or a plain looking error page?

Do you get a 404 when you visit direct on `https://mysite.com`?

**Comment by Virion21** [comment]
> e

Hey dan, thanks for the input. I've been able to solve it by adding /public at the end of the APP_URL

**Comment by Virion21** [comment]
> Hi @Virion21,
> Is the 404 page a BookStack page (Do you see a blue header bar?) or a plain looking error page?
> 
> Do you get a 404 when you visit direct on `https://mysite.com`?

Hey dan, thanks for the input. I've been able to solve it by adding /public at the end of the APP_URL

**Comment by ssddanbrown** [comment]
> Hey dan, thanks for the input. I've been able to solve it by adding /public at the end of the APP_URL

Ah, Good news! Will therefore close this.
