### ISSUE TITLE
Danish

### ISSUE THREAD

**Issue by Lett3rs** [BookStackApp/BookStack#1822]
We would like it i you could add Danish as a language - We are a few at our company that want to use this and we want our end-point users to have it on Danish - we are signed up at crowdin to help transalte from English to Danish .

//Lett3rs/Jacob

### Language To Add

_Specify here the language you want to add._

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Thanks for offering to provide translations @Lett3rs 

I have added Danish as a language on Crowdin: https://crowdin.com/project/bookstack/da#

This is the first time I've added a new language on crowdin so if you have any problems please let me know.

**Comment by ssddanbrown** [comment]
A massive thanks for working on these translations @Lett3rs.

Since this language was added to the language options in v0.28 I'll close this off. Any translation updates made more recently will be part of the next patch release.
