### ISSUE TITLE
Question: Change terminology? (ie. Books -> Pages)

### ISSUE THREAD

**Issue by aekramer** [BookStackApp/BookStack#1829]
Hello, first off I would like to say I only just installed BookStack and so far I am loving the design and easy of use. It is pretty much perfect for my use-case.

However, I was wondering how the language system works exactly (would manual translations need to be made for Books?)

And also, I would like to use a different terminology, for example I would like to rename:
Books -> Pages
Chapters -> Sections
Shelves -> Categories

Is there an easy way to go about doing this? I was thinking perhaps through the language system, but I have never heard of crownedin before (or used any other translation system before really) and I am having some trouble understanding how it works.

Thank you, and a happy new year :)

**Comment by ssddanbrown** [comment]
Hi @aekramer,
These terms are fixed to official BookStack terms (Books,Pages,Chapters) within the project code so we wouldn't accept any such changes to the included translations files or via Crowdin. 

To support this kind of use-case, The ability to locally & selectively override the translation files will be available in the next release; Details can be found here:
https://github.com/BookStackApp/BookStack/pull/1749

That said, This won't affect some areas such as the names used in URLs.

**Comment by aekramer** [comment]
> Hi @aekramer,
> These terms are fixed to official BookStack terms (Books,Pages,Chapters) within the project code so we wouldn't accept any such changes to the included translations files or via Crowdin.
> 
> To support this kind of use-case, The ability to locally & selectively override the translation files will be available in the next release; Details can be found here:
> #1749
> 
> That said, This won't affect some areas such as the names used in URLs.

Alright, thank you for the heads up I will be waiting for that version release.

The terminology seemed a bit weird to me, especially since the system is being described as a wiki system, for which shelves/books make little sense

**Comment by ssddanbrown** [comment]
Since the original question has been answered, and since the mentioned release is now available, I'll close this off.
