### ISSUE TITLE
Change UTC Time

### ISSUE THREAD

**Issue by 7uppi** [BookStackApp/BookStack#1832]
Greetings.

I have been playing around in bookstack for a little while now, and noticed that the time stamp on for example revisions is wrong. It looks like it uses UTC+00, where I live in UTC+01.
I have changed the date on the host itself, but it doesn't seem to change anything in bookstack.
Is it me who has overlooked something obvious?

Thank you.

**Comment by ssddanbrown** [comment]
Hi @7uppi,
Sorry for my late response.

Have you tried adding and setting the following `.env` option to your instance with your timezone?:

https://github.com/BookStackApp/BookStack/blob/4b79d5e4e8d5ffe2ae9856ee4f247cb76e5468ac/.env.example.complete#L35-L38

**Comment by 7uppi** [comment]
Well @ssddanbrown, apparently I skipped that section when reading through the .env.example. Sorry about that.

Thanks for the help nevertheless. It worked like a charm.
