### ISSUE TITLE
Upload Image error

### ISSUE THREAD

**Issue by TutoRapide** [BookStackApp/BookStack#1833]
Hello, 
Upload image on the page retourne server responded with 0 code.
https://ibb.co/9Hz893c

**Comment by Tacioandrade** [comment]
> Hello,
> Upload image on the page retourne server responded with 0 code.
> https://ibb.co/9Hz893c

I have the same error, managed to solve?

**Comment by MikeyMJCO** [comment]
There are a number of issues on this subject - all closed and pretty much all stemming from a server configuration error. Please review those (you can search the issues queue!) and if you're having a different issue open a new issues rather than commenting on a closed issue :-)

**Comment by Tacioandrade** [comment]
Problem solved!

Edit .env file and add:
APP_URL=https://site.com

Save and access the aplication again.

**Comment by Cassianosricardo** [comment]
Thanks @Tacioandrade! Solved for me!
