### ISSUE TITLE
Bad active pagination styling leaves number invisible

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#1839]
The active user page in the master branch uses a white background as the text style, this is illogical. I propose to set the default for the active page as black background.
![image](https://user-images.githubusercontent.com/4026090/72220800-4f3c8200-3576-11ea-9759-483c8f05ef5e.png)

**Comment by mflagler** [comment]
Or just have it set to the primary color configured in the settings. I alternatively added this to the Custom HTML Head Content:
`<style>li.page-item.active {background-color: #363636;}</style>`

**Comment by ssddanbrown** [comment]
Thanks for reporting. The colors used have been reviewed for both themes and visibility changes have been applied. Changes will be part of v0.30.
