### ISSUE TITLE
Saving a page without making any changes should not create a new revision.

### ISSUE THREAD

**Issue by Rumcajsev** [BookStackApp/BookStack#1846]
**Describe the feature you'd like**
Currently if I edit a page and save it without making any changes a new revision is created. 
I think that such action shouldn't create a new revision. 

**Describe the benefits this feature would bring to BookStack users**
This change would  make it easier to keep the page versions tidy. Currently I have to manually remove any 'empty' revisions which is time consuming and it's easy to make a mistake and delete the wrong one.
Thanks to this change in the revisions page users would only see actual changes made.

Another solution for this could be somehow marking the 'empty' revisions on the revision page.

**Comment by mflagler** [comment]
Why not just hit the back button instead of the save button? If you have made changes, it will prompt you before actually going back.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Rumcajsev.
There were some checks in place to prevent unrequired revisions but they were not working as intended. This has now been patched in 5323cb52245c4ec7f8735173e3057e321ff6327f, to be part of the next feature release.
