### ISSUE TITLE
Integration with spatie/laravel-backup

### ISSUE THREAD

**Issue by unnikked** [BookStackApp/BookStack#185]
I've been using Bookstack for a couple of months and I really look forward for this project. 

Since it is developed with Laravel it would be nice to integrate `spatie/laravel-backup` in order to automate the backup process so we can all feel secure about our data. 

**Why I think `spatie/laravel-backup` is a good choice ?**
- It's developed by an active webagency, so the package should not be abandoned. 
- It can perform and manage backups of both database and files. 
- You can schedule backups within your Laravel app. 
- You can monitor your backups. 
- You can get notifications on slack, email, pushover and custom channels. 

**How we should integrate this package ?**
I would like to hear the opinion of the author since this package can be integrated in the UI so a user can set his own logic for the backup. 

For reference there is also a [good documentation](https://docs.spatie.be/laravel-backup/v3/introduction) about this package.

**Comment by ssddanbrown** [comment]
Hi @unnikked,
Thanks for putting forward this idea.

I think building in backup to BookStack is a great idea and the linked package looks fantastic. Here are my thoughts on the idea and the `spatie/laravel-backup` package:

1. If backup is built in to BookStack then we'd have to ensure the implementation is solid as responsibility will be effectively be largely shifted from users to BookStack developers. This is not an issue, Just something to note.
2. The `spatie/laravel-backup` package looks like it does backups very well but, After a quick read of their documentation, I did not see anything about restore. I think we'd ideally implement both backup and restore.
3. I'm not sure how the spatie/laravel-backup [license requirements](https://github.com/spatie/laravel-backup#postcardware) will work for something like BookStack so I'd have to double check that. I don't want everyone who enables backup on their instance be required to send a postcard but I will respect that's their license.

**Comment by unnikked** [comment]
1. Agree on that. Also we could provide a simple backup solution that just works. Shifting the maintenance to the user. We can just provide the facility since Laravel provides it. 

2. Why don't make a feature request for the package in the future? 

3. No idea on that too. But I think the end user needs to send it if he is using this project on a production server (other than for a personal use). Maybe @freekmurze can reply in regards.

**Comment by freekmurze** [comment]
Hi,

1. I am dedicated to maintaining our package. You should not however that v4 will be released soon that ups the requirements to PHP 7 and Laravel 5.3. v3 should be pretty stable though

2. I decided not to include restore functionality because everybody does restores a bit differently. Each particular problem calls for it's own specific restore. Sometimes it's just a file that needs to be restored, sometimes a table, sometimes the whole db, sometimes the whole app. When I need to restore something I always do it manually. I'll probably never automate the restoration process and will probably not accept a PR that attempts to do this. Do this in your own project (or in this package).

3. We will send out our full battery of lawyers and dogs if you do not follow our license.
(no, users that install our package via yours are exempted)

**Comment by unnikked** [comment]
@freekmurze thank you for your prompt reply. About 2. by reading what you told I think you made the right decision. Keep up the good work! :D

@ssddanbrown according to freek's reply it's better to provide a custom solution for restoring.

**Comment by ssddanbrown** [comment]
@freekmurze Thanks for commenting on this.

So just to confirm, Only myself, as the project maintainer, would need to send a postcard? And all BookStack users, even with their own production instances, would not need to send a postcard?

**Comment by freekmurze** [comment]
Yup that's correct.

I can't guarantee eternal support for v3. No new features will be added to that version, but I'll probably fix breaking bugs. Unless it's very easy to support, probably I'll cease supporting v3 when Laravel 5.4 comes out.

**Comment by ssddanbrown** [comment]
I'm going to close this issue off since we have #723 and #2405 open, and this is focused on implementation rather than end-goal/results. 

I recently posted some thoughts in [my comment here](https://github.com/BookStackApp/BookStack/issues/723#issuecomment-1110220775).
