### ISSUE TITLE
Editor selection on edit page instead of system-wide 

### ISSUE THREAD

**Issue by nvhaver** [BookStackApp/BookStack#1855]
**Describe the feature you'd like**
Currently, choosing between the WYSIWYG and markdown editors is done system-wide as mentioned in #57. Would it be possible to let the user select the way they want to provide content instead of restricting this option for admins only, by adding an option to switch editor on the edit page?

**Describe the benefits this feature would bring to BookStack users**
Users would be able to select the editor they like instead of the system-wide editor.

**Additional context**
In my current situation, I have several users that do not like to use the markdown editor, while other users, including myself can't do without it, as I often migrate MD files from an older system. Having this feature would make it easier to cater to all the users of my BookStack instance.

The comment raised in #57 (https://github.com/BookStackApp/BookStack/issues/57#issuecomment-183544163) does mention this might be confusing to some users, but perhaps this ability to switch editors could then be disabled in the admin panel by the admin?

My thanks to all contributors. You guys are awesome.

**Comment by ssddanbrown** [comment]
Hi @nvhaver,

Thank you for your clear request. I'm going to close this as I feel this request is already covered by #842. 

There is an item on the roadmap ("Editor Alignment & Review") at which point we will strongly consider this kind of functionality.
