### ISSUE TITLE
Persian (Farsi) Translation

### ISSUE THREAD

**Issue by vatanparvar** [BookStackApp/BookStack#1858]
Hiya mate,

I really enjoy your project and would like to contribute by providing Persian (Farsi) translation.
I've already signed up to Crowdin and am ready to start.
Thanks for all the efforts you've put in to creating this amazing Wiki.

Cheers.
### Language To Add

_Specify here the language you want to add._

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Thank you so much for offering to translate into Persian. 
I've added Persian to the language list on CrowdIn. No pressure though, If you change your mind just let me know and I'll revert this.
