### ISSUE TITLE
Custom HTML Head Content doesn't work

### ISSUE THREAD

**Issue by essdeeay** [BookStackApp/BookStack#1863]
CSS in the the Custom HTML Head Content is just displayed above the top banner and thus has no effect.

BookStack 0.27.5 hosted on Docker

![image](https://user-images.githubusercontent.com/60404275/73295989-a42bf980-4200-11ea-85bd-759978a4583c.png)

**Comment by ssddanbrown** [comment]
Hi @essdeeay, can you copy and paste in a comment here the exact content you're using in this setting.

It looks like you just need to wrap you css in style tags, content in that setting gets inserted directly as html.

**Comment by essdeeay** [comment]
Ah, I need to close this... I've just found out that the styling needs to be <style> tags.

**Comment by essdeeay** [comment]
> Hi @essdeeay, can you copy and paste in a comment here the exact content you're using in this setting.
> 
> It looks like you just need to wrap you css in style tags, content in that setting gets inserted directly as html.

Aha, you replied, just as I found it - thank you - damn fast support!
S :)

**Comment by sunny5055** [comment]
Hi having same issue.. 
It does not apply 
How do i enable the custom html head ?

![image](https://user-images.githubusercontent.com/5800306/78801604-7d075a80-79ef-11ea-97d4-8be945216f05.png)

**Comment by ssddanbrown** [comment]
Hi @essdeeay,
This is is closed & I think your particular issue may be a bit different.

Could you open up a new issue specific to the particular issue you're experiencing? Ideally detailing what you're expecting to occur?
