### ISSUE TITLE
Fresh install no dist dir

### ISSUE THREAD

**Issue by ZalemCitizen** [BookStackApp/BookStack#1873]
Hello, 
Installed following Manual installation here : https://www.bookstackapp.com/docs/admin/installation/
Access to homepage returns 404 errors on styles.css app.js and print-styles.css since there is no dist directory.
Your .gitignore is excluding this dir.

Maybe I missed something but, how are we supposed to get these files ?

**Comment by ssddanbrown** [comment]
Hi @ZalemCitizen,
Can you please check what branch you're using by running `git status` in your BookStack install dir?

You should be on the `release` branch. I'm guessing you may be on the `master` branch.

**Comment by ZalemCitizen** [comment]
You're right !
Sorry for that
