### ISSUE TITLE
Send a Test Email results in 500 error if not configured correctly

### ISSUE THREAD

**Issue by rickr** [BookStackApp/BookStack#1874]
**Describe the bug**
When incorrectly configured the Send a Test Email returns a generic 500 error.

**Steps To Reproduce**
1. Ensure your email is not configured (eg set MAIL_HOST in .env to example.com)
1. Go to 'Settings'
1. Click on 'Maintenance'
1. Click on 'Send A Test Email'
1. See error

**Expected behavior**
A helpful toast or error page should be displayed. 

In my instance I had to look at the laraval log in order to find the following log entry:
```production.ERROR: Connection could not be established with host smtp.dreamhost.org```

Something similar should be displayed instead of a generic 500 error.

**Screenshots**
N/A

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
BookStack v0.28.0 
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker):
Linuxserver Docker 

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Well I guess the feature kind of works 😅

But yeah, we should probably catch any errors off the send, if we're not doing so, and report them back. Thanks for reporting.

**Comment by ssddanbrown** [comment]
Thanks again for reporting @rickr.

A fix has now been applied to be part of the next release.
