### ISSUE TITLE
V0.28 Upgrade results in "call to undefined function array" HTTP 500 errors

### ISSUE THREAD

**Issue by eferreira2** [BookStackApp/BookStack#1875]
Running Ubuntu 18.04 on PHP version 7.2.24. I successfully performed the bookstack upgrade from V0.27 to V0.28 however I keep getting HTTP 500 errors. 

**Laravel.log shows the following:**
 [object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function array_except() at /var/www/bookstack/storage/framework/views/b6907d7cb3d23d27cb94e567c7d5a2aafd964aab.php:19)
[stacktrace]
minate\\Foundation\\Http\\Kernel->handle(Object(BookStack\\Http\\Request))
![Debug Error](https://user-images.githubusercontent.com/60720273/73895627-34e08600-484e-11ea-9c18-cf4f0188ef24.png)

**Comment by finnwessel** [comment]
Could it be some kind of caching problem?
Maybe clearing the view Cache with laravels command `php artisan view:clear` could help

**Comment by eferreira2** [comment]
I followed the upgrade documentation where it suggests running the cache and view clears. I did both successfully, same issue.

php artisan cache:clear
php artisan view:clear

**Comment by finnwessel** [comment]
any problems with write permissions for the folder?
Does those files change after running the command?

**Comment by HavoK-at** [comment]
Heyho, had the same issue on a similar system (ubuntu 18.04, php 7.2.24) also after upgrading from 0.27.
According to this stackoverflow post (https://stackoverflow.com/a/58433430) laravel moved some functions to a helper package. Bookstack worked for me again after running `composer require laravel/helpers`. Hope that helps.

**Comment by ssddanbrown** [comment]
You should not need to run `composer require laravel/helpers` after updating, this would likely cause more issues when you come to update next time. BookStack has been updated to not need this package.

@eferreira2 After running `php artisan view:clear` do you have any `.php` files inside the `storage/framework/views/` folder? If so then your current user likely doesn't have permission to clear those files. You may have to run the command with elevated permissions (`sudo php artisan view:clear`)

**Comment by eferreira2** [comment]
The following 2 articles helped me resolve my issue:
https://stackoverflow.com/questions/32573924/composer-hanging-while-updating-dependencies
https://stackoverflow.com/questions/58432492/lumen-laravel-6-call-to-undefined-function-array-except/58433430#58433430

**Comment by mtariq786** [comment]
> Could it be some kind of caching problem?
> Maybe clearing the view Cache with laravels command `php artisan view:clear` could help

helpful!
