### ISSUE TITLE
Don't add an unintended new line in code block

### ISSUE THREAD

**Issue by hhk7734** [BookStackApp/BookStack#1877]
**Describe the bug**
New lines are added automatically when the code block is rendered.
Markdown is the editor.

**Steps To Reproduce**

**Expected behavior**
I hope that it does not add an unintended new line.

**Screenshots**
https://docs.loliot.net/link/133#bkmrk-installation

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.28.0
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**

**Comment by ssddanbrown** [comment]
@hhk7734 Thanks for reporting, Assigned to the next bugfix release.

I did remove some code that trimmed these blocks, as part of the last release, since that caused issues with intentional indenting but it looks like we should still trim the end.

**Comment by ssddanbrown** [comment]
Thanks again for reporting @hhk7734.

A patch has been applied and will be deployed as part of the next bugfix release.
