### ISSUE TITLE
Deprecated GitHub authorization method

### ISSUE THREAD

**Issue by ttyS0** [BookStackApp/BookStack#1879]
**Describe the bug**
The GitHub Auth feature is triggering a deprecation notice from GitHub.

**Steps To Reproduce**
1. Use GitHub Auth 

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.28.0
 - PHP Version: 7.4.2
 - Hosting Method (Nginx/Apache/Docker): Docker

**Additional context**
This is the message sent by GitHub: 

```
Hi @ttyS0,

On February 8th, 2020 at 14:43 (UTC) your application (redacted) used an access token (with the User-Agent GuzzleHttp/6.5.1 curl/7.64.0 PHP/7.4.2) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

Depending on your API usage, we'll be sending you this email reminder once every 3 days.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

**Comment by ssddanbrown** [comment]
@ttyS0 Thanks for reporting!

I've assigned this to the next feature release to ensure we deal with it before the deadline hits.
