### ISSUE TITLE
Vietnamese Language support

### ISSUE THREAD

**Issue by vuongtrunghieu** [BookStackApp/BookStack#1883]
Hi,

I'm fascinated with BookStack. I'd like to contribute to Vietnamese language translation to help some folks around me to use this amazing application. Got my new Crowdin account and ready to start at any moment!
Thank you.

Hieu

### Language To Add

Vietnamese

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Thank you very much for offering to translate the project into a new language @vuongtrunghieu. I've just seen your message on Crowdin also.

I've now set-up Vietnamese as an available language in Crowdin. Let me know if you have any issues. No pressure though, If you change your mind or find yourself busy just let me know and I'll remove the language option.

**Comment by vuongtrunghieu** [comment]
Hi Dan,

The translation is completed. I seldom use Vietnamese interface so there could be some awkward translations. These errors can be fixed in the future, when the translation is used in real life I think.
Thank you.

Hieu

**Comment by ssddanbrown** [comment]
Thank you again @vuongtrunghieu for these translations. I've now merged them into master so they're ready to be part of the next BookStack patch release (v0.28.3). Therefore I'm going to close this issue.
