### ISSUE TITLE
JSON error when uploading attachment

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#1890]
Hi

I couldn't find another issue posted about this.

I have the current release of BookStack installed on my server. All works fine EXCEPT if I try to upload an attachment to a page. I can select the file without problem, click the upload button and it seems to upload, but then I get 'X' through the file and hovering over it gives an error message saying 'Invalid JSON response from server'

I don't know if this is a configuration problem on my server (running CentOS 8.1, Apache 2.x, PHP 7.2, MariaDB 10.2) or an issue with BookStack itself. Totally new to this, so don't know where to start looking, what log files might give me a clue, etc....could someone enlighten me?

**Comment by techauthoruk** [comment]
Looked in the laravel.log file and there are no errors contained in there at all apart from one error a few days ago which was related to a permissions error for wkhtmltopdf, so I really don't know where to go next....

Help!

**Comment by techauthoruk** [comment]
OK, found the problem - it was a server permissions issue, so closing this.

**Comment by berttejeda** [comment]
Not sure if this is necessary, but I did so anyway: `mkdir public/uploads/images`
This, I'm sure is what fixed things: `sudo chown -R www-data public`
