### ISSUE TITLE
Artisan command for "refetching" user avatars for existing users.

### ISSUE THREAD

**Issue by ch0wm3in** [BookStackApp/BookStack#1893]
I've recently made my own web app, where i can serve pictures from Active Directory. It works, but only for new users because the function downloadAndAssignUserAvatar(); seems to be run on user creation.

For now the only way is to delete the user and then create the user again, which removes revisions from different books created by the user in question. This would be a much nicer way of doing it, when you already have a running instance of the application in production.

**Comment by ssddanbrown** [comment]
Thanks to @MarcHagen via PR #4560, this has now been added and will be part of the next feature release.
