### ISSUE TITLE
Custom HTML content IDs do not save

### ISSUE THREAD

**Issue by devSparkle** [BookStackApp/BookStack#1894]
**Describe the bug**
When [forcing a content ID](https://www.bookstackapp.com/docs/user/reusing-page-content/#forcing-content-ids) in the source code view of the WYSIWYG editor, the content ID will be automatically overridden by the pre-generated one.

**Steps To Reproduce**
1. Create a new page, and fill it with some content.
2. Assign an ID, _different than the automatically-assigned_, to any piece of content, such as a paragraph or a callout.
3. Save the page.
4. Open your browser inspect tool _or_ the source code view in the editor and see your custom ID reverted to an automatically-generated one.

**Expected behavior**
The custom ID should persist after being saved.

**My Configuration:**
 - BookStack Version: v0.28.0
 - PHP Version: 7.3.14
 - Hosting Method: Docker

**Comment by ssddanbrown** [comment]
Hi @devSparkle,

Thanks for reporting this issue.
I've had a dig into this and it looks like this was more of a fault in our documentation; ID's must be set with a prefix of `bkmrk` so something like `bkmrk-custom-id-value`.

I'll update the docs shortly to reflect this.

**Comment by ssddanbrown** [comment]
Docs now updated so I'll close this.

Apologies that this lack of documentation caused confusion and wasted your time.
