### ISSUE TITLE
Can't update to 0.28

### ISSUE THREAD

**Issue by nimmerdk** [BookStackApp/BookStack#1895]
Hi,
I'm trying to update to 0.28 FROM 0.27.5 with the following commands:

`git pull origin release && composer install && php artisan migrate`

but keeps getting the following error:

> error: Your local changes to the following files would be owerwritten by merge:

And then a long list of php-files, js-files and svg-files.

I haven't changed any of these files as far as I know. 

What to do?

**Comment by sunnybeats** [comment]
I had the same issue.

After i did the backup like discriped Backup routine, i did a 

`git reset --hard `

Before the update.

That worked fine for me and i didn‘t lose any of my configuration.

I don‘t know if its the best way but its simple and worked for me

**Comment by nimmerdk** [comment]
> I had the same issue.
> 
> After i did the backup like discriped Backup routine, i did a
> 
> `git reset --hard `
> 
> Before the update.
> 
> That worked fine for me and i didn‘t lose any of my configuration.
> 
> I don‘t know if its the best way but its simple and worked for me

I will try that and let you know if it works.

**Comment by nimmerdk** [comment]
Hmmm... it got a little bit longer, but now I get this:

```
[ErrorException]
file_put_contents(/var/www/html/BookStack/vendor/composer/installed.json):
failed to open stream: Permission denied

```

**Comment by sunnybeats** [comment]
Maybe this helps:

https://stackoverflow.com/questions/41212362/composer-file-put-contents-composer-json-failed-to-open-stream-permission

**Comment by ssddanbrown** [comment]
Did you manage to solve your issues @nimmerdk?

If not, looks like the user, that you're running composer as, does not have permission to the `vendor` directory. Happy to help further or I can close this if you have got things working or given up...

**Comment by nimmerdk** [comment]
Not entirely as I'm still getting some errors. although it seems that my Bookstack eventually got updated.
But I managed to f*ck up my ubuntu machine so hard, that I have to start over, so I will be installing a fresh copy later today.

/nimmer

**Comment by ssddanbrown** [comment]
Since it's been a few months I'll close this off.

**Comment by Sx3** [comment]
> I had the same issue.
> 
> After i did the backup like discriped Backup routine, i did a
> 
> `git reset --hard `
> 
> Before the update.
> 
> That worked fine for me and i didn‘t lose any of my configuration.
> 
> I don‘t know if its the best way but its simple and worked for me

Thanks it worked !
