### ISSUE TITLE
Can‘t edit user Profiles after Update to v.0.28.0

### ISSUE THREAD

**Issue by sunnybeats** [BookStackApp/BookStack#1896]
![F5421BFC-69AA-4F47-8DEC-3ABFF1E2382C](https://user-images.githubusercontent.com/57019865/74515874-b2bc2580-4f0f-11ea-9058-a8a762eb13f4.png)

If i try to edit a users Profile.
As Admin or es User himself..
I only get an error ( see the screenshot)

Url like (domain/settings/users/1)

Everything else seems to work without problems.

Setup:
 - Exact BookStack Version (v.0.28.0):
 - PHP Version:7.4
 - Hosting Method (Apache2):

**Comment by JHenneberg** [comment]
I had this issue editing pages and solved it doing the update routine again:
```BASH
php artisan migrate
php artisan cache:clear
php artisan view:clear
```

**Comment by sunnybeats** [comment]
Very big thanks,
That solved it.
So next time i will clear the stuff like recommanded

**Comment by coucho1972** [comment]
This also fixed my issue. My issue was that the User button wouldn't drop down at all, and when editing a page, or adding a new page, the Editor would show on 1/3 of the screen, the Image Explorer in another 1/3 and the Entity dialog on the last 1/3. This made the actual editor really hard to use. The commands by @JHenneberg resolved the issue. Just thought I would post this in case anyone else has the problem.
