### ISSUE TITLE
Side by Side editing?

### ISSUE THREAD

**Issue by branton5** [BookStackApp/BookStack#1898]
I find myself editing two pages at the same time (mainly moving text around, reorganizing etc) and I would find such a feature helpful.

So for example instead of having Editor / Preview you could have an option to open Page 1 / Page 2 and work on them at the same time.

Thank you!

**Comment by Zciwobukaj** [comment]
Good way to do that is to work on 2 screens with 1 opened window with Bookstack on each.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @branton5 and I understand how you could see this being helpful but realistically this would complicate the editor system significantly while achieving something that could be solved via features most operating systems offer (Window management).

Therefore I'm going to close this out.

**Comment by MikeyMJCO** [comment]
Small followup - for easy window snapping behaviour on MacOS checkout the app "Magnet" from the App Store!
