### ISSUE TITLE
Multiple Tag Values

### ISSUE THREAD

**Issue by davidPilkington** [BookStackApp/BookStack#190]
Desired Feature:
Allow multiple tag values to be added to a tag

Allow multiple tag values to be added to a tag, allow separation using a comma or semi-colon.

E.g. **Tag=>Value1;Value02;ValueThree**

[tag=>Value02] would return the same page as [tag=>ValueThree]

Each tag value would be independently searchable when combined with the tag key.

**Comment by ssddanbrown** [comment]
Thanks for the request @davidPilkington but I'm going to close this off for the following reasons:
- The same result can be achieved with multiple tags of the same name.
- It would complicate tag handling whenever the literal value (where including the chosen delimiter) is desired, and it's introduction would be a potentially breaking change we'd need to advise of.
- This has had very little demand in the past 6 years.
