### ISSUE TITLE
Search function only for english words?

### ISSUE THREAD

**Issue by hezhiyong517** [BookStackApp/BookStack#1902]
I found that the search function is only for english words.
when i search chinese words(the words do exist in my page),it doesn't work, and return no records

**Comment by ssddanbrown** [comment]
Hi @hezhiyong517,
I believe you're running into the issues described on #778. You might be able to wrap you search in quotes (`"search"`) to perform an exact search. 

Since I believe this to be a duplicate of #778 I'm going to close this off.
