### ISSUE TITLE
400 interaction_required

### ISSUE THREAD

**Issue by ch0wm3in** [BookStackApp/BookStack#1903]
**Describe the bug**
When using socialite provider for azure + Conditonal access with MFA, it will not allow MFA through bookstack.

**Steps To Reproduce**
1. Click Login With Microsoft
2. Have MFA enabled for organisation in Azure
3. See error - Which is unknown error in bookstack and 400 interaction_required in laravel log. 

**Expected behavior**
To be logged into the application

**Screenshots**

**Your Configuration (please complete the following information):**
 - 28.2
 - php7-7.3.14-r0
 - Docker

**Additional context**
Please see my pull request which fixes above, it is a fix recommended by socialite provider. 
https://github.com/BookStackApp/BookStack/pull/1889#issue-374326205

**Comment by ch0wm3in** [comment]
@ssddanbrown Any plans for merging?

**Comment by ssddanbrown** [comment]
@ch0wm3in Yes, I do plan to. Just haven't got round to it yet as I'd need to spend some time understanding how it fixes the issue and if it will possibly cause issues for existing setups.

**Comment by ssddanbrown** [comment]
As mentioned on #1889, Tested on my dev instance, which did not have this issue, and did not cause any side-effects there (Thinking of existing users), so now merged to be part of the next patch release.

Thanks for reporting and fixing @ch0wm3in.
