### ISSUE TITLE
SAML setup - array_replace_recursive(): Argument #4 is not an array

### ISSUE THREAD

**Issue by oden08** [BookStackApp/BookStack#1912]
Hello, I recently upgaded to v0.28.2 and noticed that SAML is now supported so set out to connect to my saml provider.  In my provider logs it is looking as though it is passing the proper information but in Bookstack I am getting the following error (with debugging on):

>>ErrorException
>>array_replace_recursive(): Argument #4 is not an array
>>https://domain/saml2/acs

There are no errors logged in my nginx errorlog and I am currently using these settings in my .env file - 

>>SAML2_NAME=SSO
>>SAML2_EMAIL_ATTRIBUTE=email
>>SAML2_EXTERNAL_ID_ATTRIBUTE=uid
>>SAML2_DISPLAY_NAME_ATTRIBUTES=username
>>SAML2_IDP_ENTITYID=https://_domain url_/sso/metadata.ashx
>>SAML2_AUTOLOAD_METADATA=true

Any ideas or thoughts on how I could go further to look into this?

**Comment by 1024jon** [comment]
Did you resolve this?  I'm having the same issue
