### ISSUE TITLE
SSL Issue behind Nginx Reverse Proxy (DOCKER)

### ISSUE THREAD

**Issue by danmed** [BookStackApp/BookStack#1915]
**Describe the bug**
Running Bookstack Docker behind an NGINX Reverse proxy with SSL.. However Bookstack obviously runs non ssl and i have display issues as the other open bugs say.. The problem is if i change it in the env then the next time the docker container updates, i have to do it again.. Any tips?

**Comment by ssddanbrown** [comment]
What docker setup are you using? You should be able to set the `APP_URL` as either an environment variable or you might be able to mount the container to share the `.env` file across to the host for safe keeping and manipulation.

**Comment by danmed** [comment]
HI, i'm running the solidnerd/bookstack:latest container

if i set the APP_URL to the https address you think that should work?

**Comment by ssddanbrown** [comment]
@danmed Awesome! Will therefore close this off.
