### ISSUE TITLE
View (reference to) code hosted on git

### ISSUE THREAD

**Issue by wessel145** [BookStackApp/BookStack#1917]
I would love to see some kind of git integration for the pages. This means that It's possible to select some code from a (selfhosted) git and add it to a specific page in bookstack.

**Why would we want this? and how does it benefit users?**

I personally love to write some text around my code or installation procedures. By having this integration, the code I push to some git gets updated in bookstack automatically, therefore i don't have to update the page by hand every time I refer to some code.

I would love to hear your feedback on this idea. I hope more users see the added value of this function :)

**Comment by ssddanbrown** [comment]
Thanks for offering this idea @wessel145.

I can understand why you may want such a feature but in all honesty it would be too grand to implement and maintain in relation to the portion of the BookStack user-base it would benefit. Therefore I'm going to close this off as out-of-scope.

Perhaps, once the API is a little more fleshed out, someone could implement some kind of external script that refreshes codeblocks based on a git repo.
