### ISSUE TITLE
upload error with images with points in the file name

### ISSUE THREAD

**Issue by Jonny124** [BookStackApp/BookStack#1918]
When you upload a picture file with a second point in the name an error message is shown stating just specific file types can be uploaded. 

example:
asdf2.0.jpg -> error
asdf20.jpg - > no error

Bookstack version 0.28.2 was used.

**Comment by ssddanbrown** [comment]
Yeah, There's prevention in place to prevent "double extensions" in uploaded files as it opens systems up to a range of potential double-extension or directory traversal attacks.
