### ISSUE TITLE
v0.28.2 // Site will not load after upgrade...

### ISSUE THREAD

**Issue by derek-shnosh** [BookStackApp/BookStack#1921]
**Describe the bug**
Try to load the site after upgrade from v0.27.x, presented with the following error when debug set to true in **.env** file.

```
"Declaration of BookStack\Http\Middleware\TrustProxies::handle(Illuminate\Http\Request $request, Closure $next) should be compatible with Fideloper\Proxy\TrustProxies::handle($request, Closure $next) ◀"
```

**Steps To Reproduce**
1. Open site URL.

**Expected behavior**
Either be presented with the login screen, or content if already logged in.

**Screenshots**
...with debug true.

![2020-02-26_10-51](https://user-images.githubusercontent.com/21090563/75377397-9b255b00-5886-11ea-8ad6-dbd634f2bd93.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.28.2
 - PHP Version: 7.4.3
 - Hosting Method (Nginx/Apache/Docker):  Apache2

**Additional context**
Initially had the issue wth php 7.2.x, upgraded to 7.4.x per the bookstack upgrade page just to be on latest and issue persists.

**Comment by ssddanbrown** [comment]
Hmm, Just checked and the classes appear to be compatible. In fact I remember there was even a pull request to update this to make it compatible. Can I confirm you've definitely ran `composer install` at this point and the `version` file in the root of your BookStack instance install directory shows v0.28.2?

**Comment by derek-shnosh** [comment]
```
/var/www/bookstack$ cat version 
v0.28.2
```
