### ISSUE TITLE
Cannot export to PDF - Illegal String

### ISSUE THREAD

**Issue by jvarnadore** [BookStackApp/BookStack#1923]
**Describe the bug**
My new Bookstack server cannot export to PDF, but it can export to HTML

The error message I get is: Illegal string offset 'hex'

**Steps To Reproduce**
1. Go to page selected.
2. Click on Export to PDF
3. See error

**Expected behavior**
A PDF is downloaded of your page.

**Screenshots**
![image](https://user-images.githubusercontent.com/61564883/75491349-d2c5fd00-5983-11ea-9ede-cab634dabad8.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.28.0
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Comment by ssddanbrown** [comment]
Hi @jvarnadore,
This was an issue that was addressed in [BookStack v0.28.1](https://github.com/BookStackApp/BookStack/releases/tag/v0.28.1). Please could you update to the latest BookStack version and see if the issue persists?
