### ISSUE TITLE
Install dev packages into production, is this correct?

### ISSUE THREAD

**Issue by joveice** [BookStackApp/BookStack#1928]
**Describe the feature you'd like**
Installation documentation mentions installing using `composer install`. Shouldn't this be `composer install --no-dev`?

**Describe the benefits this feature would bring to BookStack users**
Does not install development packages into "production"

**Comment by MikeyMJCO** [comment]
Just confirming that this works and results in a working production instance.

**Comment by ssddanbrown** [comment]
Yeah, probably worth doing. I ideally want to avoid composer being required at all for production setups so never looked to optimised it, but that's likely still a way off so have marked this to be updated before next release.

**Comment by Reflic** [comment]
Thumbs up for this one. I am doing this in two production environments and it did not have any negative impact so far.

**Comment by joveice** [comment]
Just fired up my own and it seems to work without issues when not installing dev packages.
Note there might be some packages in the non dev that could be moved to dev.

**Comment by ssddanbrown** [comment]
Thanks for confirming everyone.

I've now updated the docs and install scripts to use `--no-dev` mode. Will therefore close this.
