### ISSUE TITLE
Nothing shows after installing BookStack

### ISSUE THREAD

**Issue by jfha73** [BookStackApp/BookStack#1933]
Hey guys,

I just installed BookStack onto the root of a LAMP box using the instructions from your website, but after running composer install and editing .env with my settings when I browse using a web browser what it shows me is the page from Apache when /var/www/html is empty (the Apache Test Page), I also don't see an index.php file, what can I be missing?

Thanks.

**Comment by ssddanbrown** [comment]
Hi @jfha73,
Where are the files on your system? Did you install BookStack directly into /var/www/html or elsewhere?

**Comment by amo13** [comment]
unfortunately, same for me...
I am on archlinux with nginx, though. Installed to /srv/BookStack with php-tidy loaded and the following nginx config:
```
server {
    root /srv/BookStack/public;
    listen       8081;
    server_name  localhost;

    index index.php;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # default fastcgi_params
        include fastcgi_params;

        # fastcgi settings
        fastcgi_pass			unix:/run/php-fpm/php-fpm.sock;
        fastcgi_index			index.php;
    }
}
```
The database was created and migrated successfully. The folder containing BookStore is recursively owned by the http user.

Unfortunately, neither nginx nor php-fpm show anything in the logs...

I can tell that it should be running correctly because even though I get a blank page, the favicon shows up correctly in the browser. If I change favicon.ico to favicon.ico.bak and reload the page in the browser, the favicon disappears. 

Tested with php 7.3 and 7.4

I also feel like I am just missing something easy, but I am running out of ideas...

**Comment by MikeyMJCO** [comment]
Your PHP unix socket path looks wrong. This is usually `/var/run/php/phpVER-fpm.sock;` or `/run/php/phpVER-fpm.sock`

So I'd double check where your PHP sock file actually lives.

**Comment by amo13** [comment]
just double-checked and it definitely is correct. On archlinux /var/run is a symlink to /run and the command `ls -l /run/php-fpm/` confirms the result `srw-rw---- 1 http http 0 12. Mär 10:42 php-fpm.sock`. Besides, if the socket path was wrong, I a pretty sure nginx would throw an error in the logs.

**Comment by MikeyMJCO** [comment]
Have you got other PHP-FPM applications running on this server? Also what version of PHP-FPM do you have installed?

**Comment by amo13** [comment]
yes, other php applications run just fine. I have both 7.4 and 7.3 installed but neither works. I tested 7.3 by changing the path to the 7.3 sock (`/run/php73-fpm/php-fpm.sock`)

**Comment by amo13** [comment]
Dang it, I got it. Sorry for the irritation =/
Solution for me was to include the following additional lines to the nginx config:
```
server {
    root /srv/BookStack/public;
    listen       8081;
    server_name  localhost;

    index index.php;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # default fastcgi_params
        include fastcgi_params;

        # fastcgi settings
        fastcgi_pass			unix:/run/php-fpm/php-fpm.sock;
        fastcgi_index			index.php;
        
        fastcgi_buffers			8 16k;
        fastcgi_buffer_size		32k;

        # fastcgi params
        fastcgi_param DOCUMENT_ROOT	$realpath_root;
        fastcgi_param SCRIPT_FILENAME	$realpath_root$fastcgi_script_name;
    }
}
```
I don't know why these params are necessary, but I will create a quick pull request to include this into the installation guide...
Thank you for your help still!

**Comment by MikeyMJCO** [comment]
Those don't go in the installation guide - they should be in your fastcgi_params file in a php-fpm installation.

**Comment by amo13** [comment]
ok, that's where I'll put the params.
Then no pull request coming ;)
Thank you!

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this. 

If this issue remains please feel free to open a new issue, referencing this one.
