### ISSUE TITLE
Changing quality of pdf

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#1938]
Hi

I use BookStack with wkhtmltopdf. Is there a way to change the quality of exported pdf files? At the moment, they appear (although I may well be wrong) that they are produced in low quality format. Is it possible to change the render quality? Could it be added as an option on the settings page?

Many thanks

Mark

**Comment by ssddanbrown** [comment]
Hi @techauthoruk,

wkhtmltopdf does have some quality options that we could expose but the defaults are already at fairly high settings so it makes me think there may be other issues at play here if you're seeing low quality ouput...

Do you have an example of a generated low-quality PDF?

**Comment by techauthoruk** [comment]
Hi @ssddanbrown 

Thank you for taking the time to reply. This is all very embarrasing.....I have created a few pdfs and they all look fine. The only change I have made in the last few days is applying the 0.28.2 update, although I dont think that corrected any pdf issues with wkhtmltopdf.

Anyway, all looks fine so apologies for bothering you. I will close this issue.

Thanks again!

**Comment by techauthoruk** [comment]
Closed
