### ISSUE TITLE
Classifcation from Documents

### ISSUE THREAD

**Issue by boberbeck** [BookStackApp/BookStack#1940]
Hey,

it is possible to create a section for classification. My issue is, I will create a document in the wiki and this document must be classify to compliance. I hope you understand me. :)

Best regards

**Comment by Reflic** [comment]
Do you mean some kind of workflow or process for reviewing content? I quite don't get what you want...

**Comment by ssddanbrown** [comment]
Hi @boberbeck,
If this it just for the purposes of displaying a classification level, you could just use tags? (Found in the sidebar when editing a page)

If your levels are numerical then, by using tags, you'd even be able to use the tag search functionality to search greater-than or less-than a certain classification level.

**Comment by ssddanbrown** [comment]
Closing this off since clarification has not been provided. If the above tag solution does not fit, and you have further clarification, please feel free to open a new issue with that clarification, referencing this one.
