### ISSUE TITLE
Cant Paste text in to bookstack pages

### ISSUE THREAD

**Issue by GitJamz** [BookStackApp/BookStack#1944]
Hi,
Using firefox to access my bookstack instance. 
Im using the "normal" I guess not markdown mode when I create pages. What is very annoying is I can not paste text in to a page with ctrl+v. I have to right click and hit paste. 
This of course works everywhere else in my browser and other sites, its just in bookstack.

I can copy text with ctrl+c in bookstack just not paste with ctrl+v. Nothing happens when I try it.

Thanks

**Comment by ssddanbrown** [comment]
Hi @GitJamz, I just tested this on firefox and it works okay for me on my Ubuntu dev machine.

Can you confirm the following:

- What BookStack version are you on?
- What operating system are you using?
- Does this issue occur on the [BookStack demo site](https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site)?

**Comment by GitJamz** [comment]
Hi,
Nice and quick answer! Thanks..

Bookstack Version: BookStack v0.28.2 - its running from a linuxserver.io docker container on a synology NAS.

Operating system - KDE Neon . Ubuntu based.

Same issue on the bookstack demo site.

**Comment by GitJamz** [comment]
Actually trying another browser and it worked there on the demo site... Hmm..
My firefox is pretty "hardened" with a few config settings and bunch of addons.. But I have disabled most of the addons I belivie for the bookstack instance.. Probably have to dig a bit more to find out exactly what is causing this.. Ive used this browser and its settings for months with bunch of different services and stuff.. Not really had any problems that I can think if. At least not in the way that I cant paste things correctly.. ANy Idea what it might be ?

**Comment by ssddanbrown** [comment]
@GitJamz Hmm, not sure. The editor is a customised version of TinyMCE. Are you able to paste into the demo editor instances shown on this page?:
https://www.tiny.cloud/docs-4x/demo/basic-example/

**Comment by ssddanbrown** [comment]
Also, If you hit `F12` to show the firefox developer tools, the click on the `console` tab. Does anything show up in the console log when you press the paste shortcut?

**Comment by GitJamz** [comment]
> Also, If you hit `F12` to show the firefox developer tools, the click on the `console` tab. Does anything show up in the console log when you press the paste shortcut?

No Im not that familiar with the console but from what I can see nothing shows up there when i try it..
Than tiny.cloud link was a disaster. Couldnt get it working properly.. So many scripts and stuff that needed to run,,

**Comment by ssddanbrown** [comment]
@GitJamz Here's the direct demo hosted in codepen, might work better:
https://cdpn.io/tinymce/fullpage/YydQrY

**Comment by GitJamz** [comment]
Ok.. I think I found the problem setting.. Weird this has not turned up anywhere else.
dom.event.clipboardevents.enabled = false
In firefox about:config 
Can you try it and confirm this is the problem setting.. ?

**Comment by ssddanbrown** [comment]
@GitJamz Can confirm, that disables pasting. 

We do handle paste events, as we need to handle various formatting & handling paste-image-uploads.

**Comment by GitJamz** [comment]
> @GitJamz Can confirm, that disables pasting.
> 
> We do handle paste events, as we need to handle various formatting & handling paste-image-uploads.

Not sure how I should go around this.. I obviously dont want to allow this for every website out there just because its used in bookstack.
I also have a addon called canvasblocker. Maybe this will "fake" this canvas when websites try to get it from me (if I allow it in firefox settings), and then I can just disable it for the bookstack site alone (whitelist bookstack).
Im not sure if thats how it works though.. Guess I have some reading up to do.

Thanks for the help

**Comment by ssddanbrown** [comment]
@GitJamz No problem.

Yeah, I really wish the web standards people would get modern clipboard API access sorted, since it seems so fundamental, so we can have proper modern user-control and permissions. Still in draft though with sketchy browser support.

Since you now know the cause, and since it's a particular browse-setting override, I'll close off this issue.
