### ISSUE TITLE
WYSIWYG editor modal windows overflow the screen on mobile 

### ISSUE THREAD

**Issue by hjyoung1** [BookStackApp/BookStack#1945]
**Describe the bug**
1st i want to say thank you so much for making this. 
I tried so many such services but this is so much better, thank you.   
Now for bug it's just normal scaling issues on mobile screen. 
With source code and insert media modal in wysiwyg editor. 
**Steps To Reproduce**

Open any page in edit mode and tap on source code or insert media button. 

**Expected behavior**
I expect modal to adapt properly like it adapts completely on https://www.tiny.cloud  both button modal here is fully responsive. 

**Screenshots**
![Screenshot_20200308-015326](https://user-images.githubusercontent.com/45882061/76152117-d541f880-60e1-11ea-8984-6277f6c21673.jpg)
![Screenshot_20200308-015720](https://user-images.githubusercontent.com/45882061/76152118-d8d57f80-60e1-11ea-9639-a5599f8918bd.jpg)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.28.1
 - PHP Version: PHP 7.3.14
 - Hosting Method (Nginx/Apache/Docker): Docker (linuxserver image) 

**Additional context**
Not related to above issue. 
But i have two questions regarding editor as bookstack is using TinyMCE then why this looks different than https://www.tiny.cloud/features 
Also is it possible to add more TinyMCE plugins or themes/skins  like wordcount or spell checker?

**Comment by ssddanbrown** [comment]
> 1st i want to say thank you so much for making this. I tried so many such services but this is so much better, thank you.

Thanks!

> But i have two questions regarding editor as bookstack is using TinyMCE then why this looks different than https://www.tiny.cloud/features

That is the fully featured TinyMCE 5 instance, shown on their website. BookStack is using a customised TinyMCE 4 instance, Hence the differences. They added better mobile support overall in TinyMCE 5.

As part of the roadmap, we'll soon be reviewing the editors and potentially be replacing TinyMCE as the solution hence the lack of upgrade to 5 at this time.

> Also is it possible to add more TinyMCE plugins or themes/skins like wordcount or spell checker?

Yes, it is possible but you'd need to be familiar with JavaScript. We expose the editor config via events as described here:
https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events

It would be a case of using these events to alter the editor config as you wished. Note that we don't really provide support for these kind of customizations though and any custom additions you add to TinyMCE may be lost or not possible if we change to a new editor.

**Comment by Tzeenchist** [comment]
This problem concerns not only the tools, but also the inserted content. For example, videos from YouTube also go beyond the screen of a mobile phone.

**Comment by KarenArzumanyan** [comment]
> That is the fully featured TinyMCE 5 instance, shown on their website. BookStack is using a customised TinyMCE 4 instance, Hence the differences. They added better mobile support overall in TinyMCE 5.
> 
> As part of the roadmap, we'll soon be reviewing the editors and potentially be replacing TinyMCE as the solution hence the lack of upgrade to 5 at this time.

The current version of the editor in BookStack is very little functional and inconvenient.
What can be expected in the near future? Changing the editor to another or updating to a newer version of TinyMCE [6.0.1](https://github.com/tinymce/tinymce/releases/tag/6.0.1)?

**Comment by ssddanbrown** [comment]
I'll go ahead and close this off since the fundamental reports issues have been addressed in our update to TinyMCE 5 from release v22.02. Some of our own custom modals are still not responsive but there are other focused issues for those (Such as #2535).

> The current version of the editor in BookStack is very little functional and inconvenient.
> What can be expected in the near future? Changing the editor to another or updating to a newer version of TinyMCE 6.0.1?

@KarenArzumanyan Don't expect things to change too much. We'll probably update to TinyMCE 6 in the future but we'd probably attempt to keep things very much the same in terms of functionality.
