### ISSUE TITLE
header / footers for entire book, or chapter

### ISSUE THREAD

**Issue by ChangePlaces** [BookStackApp/BookStack#1947]
**Describe the feature you'd like**
The ability to add headers / footers to an entire book, or a chapter, such as page numbers, chapter name, plain text, etc. There should be a global header / footer, and chapter-specific ones are to override the book global header / footer.

**Describe the benefits this feature would bring to BookStack users**
Better experience / quality when printing.

**Comment by ssddanbrown** [comment]
Hi @ChangePlaces ,
Thanks for opening this issue.

This fundamental request has already been requested in #493 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #493 it will help show support for that request.

**Comment by ChangePlaces** [comment]
sure but I thought it was slightly different!
