### ISSUE TITLE
SAML2 Keycloak: Unknown login requester error

### ISSUE THREAD

**Issue by reavessm** [BookStackApp/BookStack#1950]
**Describe the bug**
I tried following the examples by [hugocortes](https://github.com/BookStackApp/BookStack/issues/1157#issuecomment-585804153), but I keep getting an 'Unkown login requester' error after it redirects to keycloak's login page.  Any thoughts?  I'm not too familiar with keycloak so I'm not too sure how to debug it

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.28.2
 - PHP Version: 7.3.15
 - Hosting Method (Nginx/Apache/Docker): Docker, behind nginx reverse proxy (linuxserver/bookstack)

**Comment by Dayflare** [comment]
double check your client id in keycloak, it has to be exactly the bookstack url from where you are coming. 
Your config of keycloak and bookstack would help.

**Comment by jimmytrivedi** [comment]
Where exactly I need to look at?

**Comment by jahangirahmad** [comment]
You need to check Client ID in keycloak and in the advanced section in SSO(SAML) settings in slack.
ex: both should be https://slack.com

**Comment by jahangirahmad** [comment]
You need to check Client ID in keycloak and in the advanced section in SSO(SAML) settings in slack.
ex: both should be https://slack.com

**Comment by AnEmortalKid** [comment]
Not related to this project, but I also had this error looking at the keycloak quickstarts. The `entityId` attribute should map to what the client id is.

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this. Thanks to everyone above that's provided support.

If this issue remains please feel free to open a new issue, referencing this one.
