### ISSUE TITLE
Database port env variable

### ISSUE THREAD

**Issue by dionysiusmarquis** [BookStackApp/BookStack#196]
### For Feature Requests

Desired Feature:
Change the database port via env variable.

Expected Behavior:
Be able to change the database port via DB_PORT variable

Actual Behavior:
This env variable is not implemented

**Comment by lommes** [comment]
It should work if you add tthe port to the host string in your .env-file:
```
DB_HOST=localhost:3399
```

**Comment by dionysiusmarquis** [comment]
In my special case I wanted to use it with https://hub.docker.com/r/solidnerd/bookstack/ and the whole docker start routine got messed up with the host:port approach. The [laravel port option](https://laracasts.com/discuss/channels/laravel/how-to-specify-a-different-database-port?page=1) was the only one working for me in this scenario.

**Comment by ssddanbrown** [comment]
Since solidnerd/docker-bookstack#9 has now been merged and made it into a release this is no longer required as the port can be defined via the host and is now compatible via the docker solution.
