### ISSUE TITLE
Default apache Bookstack.conf

### ISSUE THREAD

**Issue by Buliwif** [BookStackApp/BookStack#1963]
Hi,
Can someone give me the original apache bookstack.conf file content please ?
Thank you ;)

**Comment by ssddanbrown** [comment]
Hi @Buliwif,
That will depend on how you installed BookStack. Did you use the 18.04 install script? If so:

https://github.com/BookStackApp/devops/blob/59b5f6ebb2bd840a1c545ab52312b70aae3b7389/scripts/installation-ubuntu-18.04.sh#L75-L111

**Comment by ssddanbrown** [comment]
I assume the above was what you were after. Will therefore close this off. Please open a new issue if you needed something else.
