### ISSUE TITLE
Props: Automatic Draft Saving

### ISSUE THREAD

**Issue by james-geiger** [BookStackApp/BookStack#1970]
I wanted to give credit to this project for having the foresight to **save drafts as they're being written** to avoid the inevitable:

Today I was writing a draft in BookStack, wasn't paying attention, and hit the 'back' button in my browser.  Thanks to the auto-save feature, **only 23 seconds of typing** was lost.

Just another feature that other open-source DIY hosting applications might not have paid much attention to.

@ssddanbrown

**Comment by ssddanbrown** [comment]
Thanks for the feedback @james-geiger. Great to know the smaller features like this have genuinely helped people.

**Comment by ssddanbrown** [comment]
Since it's been almost a year, I'll close this off. Thanks again though @james-geiger!
