### ISSUE TITLE
PDF error 500 while using custom css fonts

### ISSUE THREAD

**Issue by vladaman** [BookStackApp/BookStack#1971]
- Exact BookStack Version (Found in settings): BookStack v0.28.3
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache

Bookstact throws 500 error while trying to export any page to PDF:

When loggin is enabled I get following error:

fopen(/var/www/BookStack-0.28.3/app/vendor/dompdf/dompdf/lib/fonts//nunito-italic_6e6e6d4f041dbe2cbb49180bbad139a4.ufm): failed to open stream: No such file or directory

This is related to custom css font in header. Once removed it fixed the issue.

**Comment by MikeyMJCO** [comment]
Why open a duplicate issue? You already commented on #1800 which is the same issue.

**Comment by ssddanbrown** [comment]
This should now be addressed in the current latest release, as discussed within https://github.com/BookStackApp/BookStack/issues/2746. Will therefore close this off.
