### ISSUE TITLE
"Changes" link on list of page revisions returns error

### ISSUE THREAD

**Issue by wlabarron** [BookStackApp/BookStack#1976]
**Describe the bug**
When looking at a page's revisions, clicking "Changes" on a page in the list shows a page which reads "An Error Occurred. An unknown error occurred." with a link to the homepage.

**Steps To Reproduce**
1. Go to a page with a few revisions.
2. Click "Changes" for one of the entries.
3. Error.

**Expected behavior**
I'm not sure, I've never seen it work properly.

**Screenshots**
<img width="789" alt="List of revisions" src="https://user-images.githubusercontent.com/16035785/77253474-77212380-6c52-11ea-8039-838f4bd37754.png">
<img width="829" alt="Error page, reading An Error Occurred. An unknown error occurred. A link home." src="https://user-images.githubusercontent.com/16035785/77253476-7a1c1400-6c52-11ea-8239-1d43579007e4.png">

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.28.3
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Hi @wlabarron,
Do you know if you have the `php-tidy` PHP extension installed? 
That would be my first guess if this occurs on any page in your instance.

**Comment by wlabarron** [comment]
`php-tidy` isn't listed when I run `phpinfo();` inside my `public` directory.

**Comment by ssddanbrown** [comment]
@wlabarron Ideally there should be some mention of `Tidy` in there. What operating system are you running BookStack on and what method did you use to install it?

**Comment by wlabarron** [comment]
I followed the [Manual Installation Instructions](https://www.bookstackapp.com/docs/admin/installation/#manual), and it turns out I do have `tidy` installed (I searched the page for `php-tidy` originally, hence no results). I'm on shared hosting, I know that it's not officially supported, but I was able to run all the install commands without issue so I ran with it. Looks like my server is running Red Hat, or at least that's what's listed in `/proc/version`.

**Comment by ssddanbrown** [comment]
@wlabarron Okay, Thanks for confirming.

This page details how you can enable debug mode in BookStack:
https://www.bookstackapp.com/docs/admin/debugging/

Could you follow that to gain more information and hopefully we'll get a handy error message when you click changes with debugging enabled.

**Comment by wlabarron** [comment]
@ssddanbrown Yep, got an exception (on a very lovely error page): `Required Tidy extension not found.` Odd, since it is listed in `phpinfo()`. Running `composer show`, however, doesn't list `tidy`.

**Comment by ssddanbrown** [comment]
@wlabarron  Hmm, Might be worth checking your `php.ini` file to see if the tidy extension is commented out in there.

**Comment by wlabarron** [comment]
@ssddanbrown There's no `.ini` inside my BookStack installation folder. There is one in my home directory which it's probably inheriting info from, but that has no mention of the Tidy extension. Should there be one in my installation folder?

**Comment by wlabarron** [comment]
This issue has resolved itself - seems like one of the last couple of updates has fixed whatever was set wrong.

**Comment by ssddanbrown** [comment]
@wlabarron Awesome, Thanks for confirming. Will therefore close.
