### ISSUE TITLE
Use Bookstack with Galera Cluster

### ISSUE THREAD

**Issue by onlinejul** [BookStackApp/BookStack#1980]
Hi everyone,

we are trying to install and configure our Bookstack instance to work with Galera but it seems that we are not able to.

Yesterday, we did the following : 

- created the empty DB on the Galera Cluster,
- created the user and the Grants on the Galera Cluster,
- dumped and restored the DB from the local MySQL to the Galera Cluster,
- changed the .env file with the new information
- tested the access
- uninstalled Mysql-server from the Bookstack instance
- retested the access

Just after the migration, Bookstack was working fine, and hours later, it finally broke with errors related to permission on the laravel.log file. We have reapplied the permission as they are specified in the install script : chown www-data:www-data -R bootstrap/cache public/uploads storage && chmod -R 755 bootstrap/cache public/uploads storage.

We now have another error which is : 

![image](https://user-images.githubusercontent.com/14540206/77423695-16b7f080-6dd0-11ea-96a5-c613ba0d7983.png)

Is there any "official" procedure for doing what we are trying to do or is this maybe not supported ? I have seen in the thread of tickets that someone has successfully made such system work, and had to change  the config/database.php file but we have not been able to do so ourselves (https://github.com/BookStackApp/BookStack/issues/722).

Thank you again, good day.

Julien

**Comment by ssddanbrown** [comment]
Hi @onlinejul.
Galera is not something we officially support. Looking at the responses in #722 BookStack should at least be able to connect and run fine by default.

The error indicates to me that either the `app/Config/database.php` files have been edited in an unsupported manner or that you maybe don't have the php-mysql module installed on your system. Can you check that non of the `app/Config/*.php` files have been changed and that your system has the php-mysql extension active and installed.

**Comment by onlinejul** [comment]
Hi Dan,

thank you again for your help, we have done the following and it seems that it is working fine now :

- reinstalled the Bookstack fronts without mysql-server
- plugged the fronts to the dbs behind galera

We suspect that when removed mysql-server, we also removed the php-mysql package.

Thanks again.

Julien
