### ISSUE TITLE
Overwriting Application name on two different instances

### ISSUE THREAD

**Issue by nobdev** [BookStackApp/BookStack#1981]
Yesterday I installed two instances of the Bookstack App.

1. Bookstack App is installed in folder: /opt/bookstack/app1/BookStack
1. Bookstack App is installed in folder: /opt/bookstack/app2/BookStack

Both instances have been configured to use different databases, different subdomains and have different URLs configured which were configured in .env respectively.

Now when I set the Application name from within the web settings, the app name is being changed on both instances. At least that is what is being shown within the browser.

when checking "settings" table in the databses i can see that the app name is different.

**Comment by ssddanbrown** [comment]
Hi @nobdev,
Have you configured any cache settings at all?

Settings, such as app-name, go through a layer of back-end caching so if the two instance use the same system for caching (Memcached or Redis) you may get some interference.

**Comment by nobdev** [comment]
Well.. that was smart. That solved my problem. Just switched one instace to redis and everything seems fine. I was too lazy to get into setting up two memcached instances.

**Comment by ssddanbrown** [comment]
Alternatively we do have support for different prefixes:

```env
# Cache key prefix
# Can be used to prevent conflicts multiple BookStack instances use the same store.
CACHE_PREFIX=bookstack
```

Could use the same store with different key prefixes per system.

**Comment by nobdev** [comment]
Problem was based on a misconfigured memcached setup.
