### ISSUE TITLE
Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by gabdel1** [BookStackApp/BookStack#1983]
So, I did the manual installation, all went ok, migrations ran seamlessely, but when I try to open the website on the browser, ignition throws this error at me:

> 
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: select * from `users` where `system_name` = public limit 1)

I tried everything from setting write permissions, to changing the host to 127.0.0.1 and anything else I could think of.

**Comment by ssddanbrown** [comment]
Hi @gabdel1,
What operating system are you running and what exact database system/version are you using?

I know on modern Ubuntu installations that you need to be the root system user to be able to use the `root` mysql user. Have you tried creating a new, non-root, mysql user for BookStack?

**Comment by gabdel1** [comment]
I am on Ubuntu 18.04 .. And you are right, it was root account that caused the problem. I created a new user granted them access to the DB and all is good now!

Thank you very much.
