### ISSUE TITLE
I've managed to break image upload

### ISSUE THREAD

**Issue by aaronnewsome** [BookStackApp/BookStack#1985]
I tried uploading a bunch of images to a page. The spinner was spinning for quite a while and eventual stopped with some errors. Now when I try to upload an image anywhere, it fails.

If I use the attachment sidebar on the right, I can upload an image, but it doesn't save.

If I drag an image to the markdown editor, it fails with an error too.

I've tried restarting the container, I've double checked all the permissions in /var/www/html and they seem fine.

Something with the failed upload of that bunch of images has broken uploads. I've tried looking at every log file that I'd know to look for and no luck there either. I can't find a single log file that shows the error when uploading the images.

I searched all the previous topics here and wasn't able to find anything relevant.

Thanks,...

**Comment by aaronnewsome** [comment]
Looks like there was some weird caching thing with Chrome. Honestly, I have no idea. I tried firefox and I was able to upload the same image that was failing with Chrome.

Now my new problem is that I can't seem to upload any images larger than 1MB. I've looked everywhere to try and figure out how to allow larger images.

My nginx reverse proxy allows large files. php.ini in the BookStack container allows larger files, the php-local.ini also allows it. I don't see anything in the .env file that has anything to do with file size uploads so I remain stumped on how to allow larger images.

**Comment by ssddanbrown** [comment]
@aaronnewsome Is your container running PHP directly? Or is there another webserver to check within the container itself?

**Comment by aaronnewsome** [comment]
> @aaronnewsome Is your container running PHP directly? Or is there another webserver to check within the container itself?

Hi Dan. Thanks for responding. As it turns out I was looking at the wrong server block in my nginx.conf file. I've added a parameter to the nginx.conf file to allow for larger file uploads and that seems to have fixed it.

I've been quite busy migrating a bunch of stuff into bookstack. I'm really impressed by the app. One of the best I've come across and an almost 100% fit for my needs.

**Comment by ssddanbrown** [comment]
@aaronnewsome Ah, Awesome! Glad to hear you found the issue, will therefore close this off. Thanks for the feedback, Happy to hear it works for your use!
