### ISSUE TITLE
LDAP Auth - Malformed UTF 8

### ISSUE THREAD

**Issue by rocnetBinarian** [BookStackApp/BookStack#1988]
Running bookstack v0.28.3, installed via the ubuntu script on a fresh LXC container.  PHP 7.2.24-0ubuntu0.18.04.3, hosted on apache (http) with an nginx proxy (https) in front of it.

After submitting any password (correct or incorrect) for a **valid user**, an InvalidArgumentException is thrown: `Malformed UTF-8 characters, possibly incorrectly encoded.`  Any password for an **invalid user** displays the normal "these credentials do not match our records"

Attempting to bind against Active Directory, not native LDAP.

My relevant config file, heavily edited but still similar:

```
AUTH_METHOD=ldap

LDAP_SERVER=192.168.50.5:389
LDAP_BASE_DN=ou=users,dc=example,dc=com
LDAP_DN=test@example.com
LDAP_PASS='test one test two'

LDAP_USER_FILTER=(&(sAMAccountName=${user}))
LDAP_VERSION=3

LDAP_ID_ATTRIBUTE=BIN;objectGUID
LDAP_EMAIL_ATTRIBUTE=mail
LDAP_DISPLAY_NAME_ATTRIBUTE=cn

LDAP_USER_TO_GROUPS=true
LDAP_GROUP_ATTRIBUTE="memberOf"
LDAP_REMOVE_FROM_GROUPS=false

LDAP_DUMP_USER_DETAILS=false
```

Per #1961 I have confirmed that LDAP_VERSION is 3, and that LDAP_ID_ATTRIBUTE is indeed BIN;objectGUID.  No luck.  One possible lead is that the AD server is rather old...perhaps too old for bookstack?  Please advise, and thanks for the help!

**Comment by ssddanbrown** [comment]
Thanks for opening this on a new issue @rocnetBinarian.

Could you post the full Exception while `LDAP_DUMP_USER_DETAILS=false` is set? Should list a bunch of files and line numbers. Would be good to know exactly when this occurs, and hopefully that full exception detail should indicate what property this is thrown at. 

Debugging details can be found here:
https://www.bookstackapp.com/docs/admin/debugging/

**Comment by rocnetBinarian** [comment]
Here ye be!

![image](https://user-images.githubusercontent.com/59892178/78265256-333fe100-74d2-11ea-987c-4574912c68c6.png)

Thanks

**Comment by ssddanbrown** [comment]
Thanks @rocnetBinarian, Is your `LDAP_DUMP_USER_DETAILS` definitely set to false or undefined when that error shows? 

That error contains `JsonDebugException` which I would not set to see if that option was false.

**Comment by rocnetBinarian** [comment]
It is definitely set to false.  I just tried commenting it out entirely as well, and same issue.

**Comment by ssddanbrown** [comment]
@rocnetBinarian On the broken instance, do you have any files within the `bootstrap/cache/`?

If you have a `bootstrap/cache/config.php` file then your config may have been cached at the framework level. Can just delete that file if so.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
