### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by ajmcateer** [BookStackApp/BookStack#199]
Hi I installed Bookstack on my Ubuntu server with the installation script but when I go to http://ipaddress I just get a default nginx page. What am I missing?

**Comment by ssddanbrown** [comment]
Hi @ajmcateer,
Were you on a fresh Ubuntu 16.04 instance and do you provide `ipaddress` when the script asked for a domain?

If yes to both above could you run `/etc/nginx/sites-enabled/bookstack` and check that the `server_name` in the output of that command matches your ip address.

**Comment by ssddanbrown** [comment]
Closing due to lack of response. Feel free to still answer the above and I'll re-open this.
