### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by doox911** [BookStackApp/BookStack#1992]
Run command: 
`git pull origin release && composer install --no-dev && php artisan migrate`

Result:
`fatal: unable to access 'https://github.com/BookStackApp/BookStack.git/': Failed to connect to github.com port 443: Время ожидания соединения истекло`

What happened? How do I upgrade?

**Comment by ssddanbrown** [comment]
Hi @doox911,
Looks like the system you're running this on can't connect to GitHub over HTTPS. Does the system have working outbound internet access?

**Comment by doox911** [comment]
> Привет @ doox911 ,
> похоже, что система, на которой вы работаете, не может подключиться к GitHub через HTTPS. Есть ли у системы работающий выход в интернет?

Now I have error:
`Could not delete /var/www/wiki/vendor/wnx/laravel-stats/composer.json:`

**Comment by ssddanbrown** [comment]
That'll be a permissions error. The user you're running `composer install --no-dev` as likely doesn't have permission to manage these files.

Depending on your system, you could try running these with elevated privileges:

```bash

git pull origin release && sudo composer install --no-dev && php artisan migrate
```

**Comment by doox911** [comment]
Thank you)
