### ISSUE TITLE
New Draw.io diagrams can't load images if username contains emoji character

### ISSUE THREAD

**Issue by dopyrory3** [BookStackApp/BookStack#1993]
**Describe the bug**
I don't even know if this is necessarily worth the time in fixing, but if a user has an emoji in their username and creates a draw.io diagram - the image is generated on the filesystem but BookStack gets HTTP 500 error trying to load it

**Steps To Reproduce**
1. Create a new user with an emoji character in their name
2. Create a draw.io diagram within a page
3. Save the diagram
4. See error in that image does not display & web console error 500

**Expected behavior**
I expect that upon saving the png generated of the diagram is displayed on my finished page

**Screenshots**
![image](https://user-images.githubusercontent.com/12117229/78241908-0f33ce00-74d9-11ea-85ce-52e95c2d24bd.png)

**Your Configuration (please complete the following information):**
 - Tested on demo site in screenshot above

**Additional context**
I haven't tested with many emojis, it's possible some of them work.

**Comment by ssddanbrown** [comment]
Thanks for reporting @dopyrory3. What a fun & strange issue.

After some testing, I think this only really occurs with Emoji ZWJ Sequences. Initially tried with a 🐫 and that worked fine. Could even have 🐫🐫🐫 in my name and it still work, Seems like the zero-width joiners triggers this. 

Have assigned to be addressed in the next feature release.
