### ISSUE TITLE
(Minor) Not possible to move book back to top level?

### ISSUE THREAD

**Issue by aekramer** [BookStackApp/BookStack#1997]
**Describe the bug**
One of the contributors moved a book into a category, while I would have preferred to keep this a top-level entry. But I am not able to reverse this.

**Steps To Reproduce**
1. When going to the page
2. Click on 'Move'
3. The list will only contain other books/sections (no way to return it to top level)

**Expected behavior**
Not sure if there is a way I don't know about to do this, but it would be nice to have an entry to remove it from a category instead of having to move it.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.28.2
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Additional context**
I am not sure if this is a bug or should be a feature request, as it might be expected behaviour on a fairly basic feature, I figured this might be more of a bug.

**Comment by ssddanbrown** [comment]
Hi there @aekramer,
I'm afraid I don't 100% understand your situation. Have them moved a book into a shelve (Represented in red by default in the UI)?

If so, you should be able to go to the shelf > Click Edit > Drag the Book out of the shelf or click on it:

![image](https://user-images.githubusercontent.com/8343178/78405617-c2dfaf80-75f8-11ea-9e42-33decb924c88.png)

**Comment by aekramer** [comment]
Sorry I think I have actually made a mistake here, apparantly had a shelve and a book named the same thing, made me assume when looking at the chapters I was looking at books (so trying to move a chapter out of a book really)

Again, sorry, I will close this now.

Due to the multiple (unneeded) layers of having Shelves -> Books -> Chapters -> Pages
We renamed a few things using the translation file and kind of skipped out one of them, which made it a bit confusing

**Comment by ssddanbrown** [comment]
@aekramer Cool, glad you found the issue.

If you do find you don't need shelves at all, The shelves option in the top header bar will hide if a user does not have permission to view any in the system, So you could strip shelf permissions from all your users and it'll be like the don't exist.
