### ISSUE TITLE
Installation problem - White page and "Permission denied"

### ISSUE THREAD

**Issue by FedericoGB25** [BookStackApp/BookStack#1999]
Hello everyone, I have installed BookStack correctly on my Debian VPS.
But, when I try to go to the main folder (public), it shows a blank page and nginx gives this error:

`2020/04/03 15:46:21 [error] 20279#20279: *23 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/BookStack/storage/framework/views/c36ffba2ab4ad4afa587fb2bd945bbf67e93de0a.php): failed to open stream: Permission denied in /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()
#2 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(129): Illuminate\Filesystem\Filesystem->put()
#3 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile()
#4 /var/www/html/BookStack/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\View\Engines\CompilerEngine->get()`

I correctly set up my nginx site config and my database settings. Dependencies are correctly installed. But I don't know how to proceed to fix this error...
I already tried to chmod the specified files/folders and find something online about this issue. but it didn't help.

Is there a way to solve it? Thanks a lot :)

**Comment by ssddanbrown** [comment]
Hi @FedericoGB25,

To run BookStack PHP will need permission to write to the `storage/`, `bootstrap/cache` & `public/uploads` folders within your BookStack installation.

You should be able to set the correct permissions by running the below within your BookStack install directory:

```bash
sudo chown www-data:www-data -R bootstrap/cache public/uploads storage && sudo chmod -R 755 bootstrap/cache public/uploads storage
```

If that doesn't work I'll probably need a little more information about your setup, in regards to how PHP is configured.

**Comment by FedericoGB25** [comment]
It worked. Thank you so much! :)

**Comment by ssddanbrown** [comment]
@FedericoGB25 Wonderful! I'll therefore close this off.
