### ISSUE TITLE
wysiwyg and nested style comment box

### ISSUE THREAD

**Issue by venkat0304** [BookStackApp/BookStack#2009]
It would be great if there is an option to enable wysiwyg style comment box with nested comments look  (something like this) ?

![](https://webhive.com.ua/store/img/p/74-429-thickbox.jpg)

**Comment by ssddanbrown** [comment]
Hi @venkat0304,
Thanks for the suggestion.

As per the feature request template, can you explain the benefits that the requested changes would bring to BookStack users?

Personally, I don't want to extend the comment features too far as it's not supposed to be a discussion system. At the moment, you can apply formatting in comments using markdown syntax.

**Comment by ssddanbrown** [comment]
Closing this off since there has been no followup conversation.
