### ISSUE TITLE
Sub directory installation, with multiple installations, session or cookie conflict

### ISSUE THREAD

**Issue by poppahorse** [BookStackApp/BookStack#201]
Firstly thanks for making this work in sub directories as per https://github.com/ssddanbrown/BookStack/issues/40.

I have got a few installations setup, but the session / login seems to conflict, so when I log into one, it logs me out of another.

Suspect the session or cookie name is getting tangled up? Any ideas?

**Comment by ssddanbrown** [comment]
Hi again @poppahorse,
Could you provide some more details on your setup?:

1. Are you sharing the same files or databases at all?
2. How are you doing sessions? If the `.env` config what are `CACHE_DRIVER` and `SESSION_DRIVER` variables set to?

**Comment by ssddanbrown** [comment]
Closing due to lack of response. Feel free to still answer the above and I'll happily re-open this.
