### ISSUE TITLE
links to attached files on page

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2013]
**Describe the feature you'd like**
I can upload files to a page. It should be possible to add a link in the text to the file (helpful for multple on one page)

**Describe the benefits this feature would bring to BookStack users**
It helps to show that a file is present. and it helps to differentiate between multiple uploaded files

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @Smoin1,
You could copy the attachment link and then simply paste that into the page, or paste when creating a link.

**Comment by Smoin1** [comment]
you probably mean to 
rightclick on the file - slect copy link address 
and use that?

then  I would propose to make it easier ;) maybe add the possibility to add the link via the add link menu :) this could look like: 
insert link - url - select files (instead of all pages) - select wanted file

**Comment by ssddanbrown** [comment]
Sure, I'm worried this could complicate the selector box a fair bit though.

Would the request in #1460 be a suitable alternative? So the option to drag in attachments items from the sidebar to create links, Or a button on them to insert a link?

**Comment by Smoin1** [comment]
I believe this would work, too :)
but the shown gif in that issue is not working on my end? As far as I understand it should though?

**Comment by vic-t** [comment]
Hi Dan, I would also much appreciate the possibility to mention an attachment (of any kind) within in the page text. Copying over the link does work, of course, but that creates a FQDN reference. It would be nicer if the link was really just referring to the file itself and the rest was created dynamically. So, +1 for #1460

**Comment by ssddanbrown** [comment]
Since #1460 should solve this I'll close this off as a duplicate.
