### ISSUE TITLE
Update WYSIWYG entity-link-insert to set link text to entity name, if input is empty

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2014]
**Describe the feature you'd like**
If I add a link to a different page the field "Text to display" is empty. If i click on ok, there will be no link. A text needs to be inputted. It would be nice to have the Title as fall back/standard shown text

**Describe the benefits this feature would bring to BookStack users**
Saves time, and helps new users with adding empty links (it happened to me the first time)

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Smoin1. The behaviour has now been updated to set the "Text to display" as the item name, if that input box is currently empty. 

This will be part of the next feature release, v0.29.
