### ISSUE TITLE
Issue with updating Bookstack on Windows Server with XAMPP

### ISSUE THREAD

**Issue by clpeterson84** [BookStackApp/BookStack#2018]
I took over for a previous leadership and the wiki we were using was put on a Server 2016 box with XAMPP.  I am wondering if anyone can give me some tips on how to update the app from within windows?  I don't have experience with it and neither does any of the remaining admins.

**Comment by ssddanbrown** [comment]
Hi @clpeterson84,
Have your tried following the update instructions?:
https://www.bookstackapp.com/docs/admin/updates/

If so, what part do you have trouble with?

You may need to check the PHP version in use on your xampp install if updating from more than a few versions ago.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
