### ISSUE TITLE
tab key not work 

### ISSUE THREAD

**Issue by LQchengdu** [BookStackApp/BookStack#2020]
**Describe the bug**

**Steps To Reproduce**
1. use editor WYSIWYG 
2. create new page

**Expected behavior**
table Key not working as #158 reported

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):BookStack v0.28.3
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker):Apache

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @LQchengdu,

Are you attempting to use a tab within the normal editor or the code editor? #158 was closed as that related to using the tab character for code, which is supported when you're editing a code block.

**Comment by LQchengdu** [comment]
Hi @ssddanbrown

 thanks for your reply

i am use tab within the normal editor.
