### ISSUE TITLE
Add a key icon in shelf/book with certain access

### ISSUE THREAD

**Issue by DevMimas** [BookStackApp/BookStack#2021]
**Describe the feature you'd like**
If a shelf or a book is made accessible only to certain persons, it would be useful to mark this with an icon - see the picture in the appendix. Or Additionally with a text, for example: "The shelf/book is allowed for certain users".

**Describe the benefits this feature would bring to BookStack users**
The user/administrator can see directly which shelves/books are subject to certain breaks.

**Screenshot**
![grafik](https://user-images.githubusercontent.com/44207756/79008498-d1c8e380-7b5d-11ea-8bb7-b97425f9feee.png)

**Comment by ssddanbrown** [comment]
Hi @DevMimas,
Thanks for the suggestion.

I'd prefer not to busy the titles of items with status icons as that can be a slippery slope to having various icons that distract from the content.

Just thinking about your intended benefits: 

> The user/administrator can see directly which shelves/books are subject to certain breaks.

There is functionality in the search system to help with this. You should see a "Permissions Set" option in the sidebar. Alternatively, you can search for `{is_restricted}` in the top search bar to trigger the same search. You can also use this search filter within a particular book.

**Comment by DevMimas** [comment]
Hi @ssddanbrown 
Thanks for your quick feedback.

Yes, that`s really good. But I think it would be more obvious to place a small icon there, which indicates that this area is protected or subject to permission.
I'm actually only concerned with the visual representation. If you have several shelves that are public or protected, it will be difficult to keep track.
