### ISSUE TITLE
Can't save pages

### ISSUE THREAD

**Issue by adoalon** [BookStackApp/BookStack#2024]
Hello, 
I have a clean installation of BookStack, everything works but I can't save pages, they stay as drafts.

Thanks

**Comment by ssddanbrown** [comment]
Hi @adoalon,
Could you list the steps you're following to save a page?

Additionally, are you able to save pages when using the demo instance here?:
https://demo.bookstackapp.com/login?email=admin@example.com&password=password

**Comment by adoalon** [comment]
Hi Dan, 
The problem was I didn not update alol of the PHP modules.
thanks
