### ISSUE TITLE
Automatic formatting of markdown

### ISSUE THREAD

**Issue by kayvanaarssen** [BookStackApp/BookStack#2025]
It would be nice to have thee option in the backend maybe per user.
To auto detect markdown.

For example a lot of our techs know how to write in Markdown that is way easier than with the codeblocks in Bookstack.

This way you don't have to style the code blocks by hand etc.

You can then just start typing away with markdown and Bookstack will format it.

Like: 
```
# Header
You need to edit `this` file to make the change **Strong**
```

Bookstack will turn it into;

Header
You need to edit `this` file to make the change **Strong**

**Comment by ssddanbrown** [comment]
Hi @kayvanaarssen,
Thank you for your suggestion.

Just to ensure I understand correctly, Is this in the default WYSIWYG editor that you want this functionality?

**Comment by kayvanaarssen** [comment]
Does not really matter.
Would be nice though. If it would auto detect Markdown.
Or better that you can use Markdown and normal "WYSIWYG" content in a mixed way.

Don't know if thats even possible, but it would be awesome and so fast than to write things.

**Comment by ssddanbrown** [comment]
Okay, Thanks for confirming. 

To be honest, I wouldn't want to support the transformation of WYSIWYG editor content on input as it would likely cause more frustration/confusion for many users while, if supporting as an option, will only be used by a small subset of the audience (Those that do not use the Markdown editor but want markdown transformation in the WYSIWYG editor). 

I'll therefore close this off. 

If this was requested for the main purposes of speed, I'd advise reviewing the available shortcuts: https://www.bookstackapp.com/docs/user/wysiwyg-editor/
They're faily intuitive once you get started with them and can speed up editing a fair amount. 

Ideally I'd be hoping to make it possible to switch between Markdown and WYSIWYG input in the future but that depends on possibilities when we come to re-review the editors.

**Comment by kayvanaarssen** [comment]
Its not only for Speed also Cross Compatibility for Git / Other Tools for example.
It would be a nice option to switch seamless between WYSIWYG and Markdown

**Comment by ssddanbrown** [comment]
> Its not only for Speed also Cross Compatibility for Git / Other Tools for example.

Sure but that is a very narrow audience in the greater scheme of where BookStack is intended for.

> It would be a nice option to switch seamless between WYSIWYG and Markdown

#842 and #458 and #369 are open to address such a request.

**Comment by andybaumgar** [comment]
I would also love this feature.  I admin a Bookstack instance and people love the editor, but we got a request for WYSIWYG markdown detection recently so I tried it out in Google Docs.  You type `## Example Title` for example and that is converted to an H2 heading.  I love that it's a "universal syntax", so there's the possibility of standardizing across editors.
