### ISSUE TITLE
Wikipedia "Grabber"

### ISSUE THREAD

**Issue by E-Fail** [BookStackApp/BookStack#2027]
**Describe the feature you'd like**
I want to link a page to wikipedia. The content from Wikipedia should appear in the page contents and refresh after a custom intervall. 

**Describe the benefits this feature would bring to BookStack users**
If an Article is updated, for example Fusion power, i have the latest infos in bookstack. For sure, I can search the wikipedia article in google but the idea is a private KB without long searches. All in one place.

**Additional context**
A option to select chapters would be nice, i don't need the sources at the end of every article. Everytime the page is new fetched from the source, archive the old - like on changes in a existing site.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @E-Fail.

To be honest, I don't think this is something I'd look to have as part of the BookStack core as this flow is very use-case specific and depends on an external wiki system. Therefore I'm going to close this off as out of scope. 

Once the API has been fleshed out a bit further, I'm sure this is something that someone could script without too much effort.
