### ISSUE TITLE
Dark Mode: Background and Fontcolor black

### ISSUE THREAD

**Issue by Stiles96** [BookStackApp/BookStack#2029]
**Describe the bug**
In the Editor on a page in the dark mode you cant read headings. The haedings in the dropdown menu "Formats" and on the page itself are not be able to see because of black font and black background.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51234422/79137333-d1755600-7db2-11ea-91ab-1ba10e07f90b.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.0
 - PHP Version: 7.4.4
 - Hosting Method (Nginx/Apache/Docker): Apache2 - Ubuntu Server 18

**Comment by ssddanbrown** [comment]
Hi @Stiles96,

Are you using any custom styles at all? Maybe in the "Custom HTML Head Content" option?

Do you see the same thing on our demo site?:
https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site

**Comment by Stiles96** [comment]
Hi @ssddanbrown,

I am not using a custom CCS. The option is blank at the settings.
The bug was the cache. I cleared it a second time at the browser, after that the headings was shown.

Thank you.
