### ISSUE TITLE
PDF Export of table broken

### ISSUE THREAD

**Issue by montharon** [BookStackApp/BookStack#203]
Source Code of the page: (Unfortunately I do not know how to post the source-code directly?)
It is always rendered as a html table....;)
 
<table id="bkmrk-bezeichnung-herstell" style="font-size: 0.75em;">
<tbody>
<tr>
<td>&nbsp;</td>
<td><strong>Bezeichnung</strong></td>
<td><strong>Hersteller</strong></td>
<td><strong>Alternative(n)</strong></td>
</tr>
<tr>
<td>&nbsp;</td>
<td>Ceramic White</td>
<td>Citadel</td>
<td>Smelly Primer [OC], White Primer (002) [VGC], Foundation White (919) [VMC], Morrow white [P3]</td>
</tr>
</tbody>
</table>
 

And the corresponding output of the PDF-File:
<img width="506" alt="pdfexport" src="https://cloud.githubusercontent.com/assets/21140797/18991920/bd8dc1cc-871b-11e6-82c1-6a6d9ecbca3c.PNG">

Many thanks again Dan for your great piece of software and your support!
Cheers,
montharon

**Comment by WinstonN** [comment]
I can confirm this bug

**Comment by ssddanbrown** [comment]
Thank you for finding this issue. It is now fixed as of release [v0.12.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.12.2).
