### ISSUE TITLE
Content Blown up after installing

### ISSUE THREAD

**Issue by WizardKid** [BookStackApp/BookStack#2033]
**Describe the bug**
Hi after installing, the contents of the page blown up (images filled the page). I am unable to view setting (not because i dont want to) but simple because the icons are much bigger than usual.

**Steps To Reproduce**
Not sure

**Expected behavior**

**Screenshots**
![Screenshot from 2020-04-14 15-34-47](https://user-images.githubusercontent.com/13104065/79236982-8c5e2c00-7e65-11ea-9bed-82ae075d7920.png)
![Screenshot from 2020-04-14 15-34-37](https://user-images.githubusercontent.com/13104065/79236988-8d8f5900-7e65-11ea-9cb5-c2c5302b6919.png)
![Screenshot from 2020-04-14 15-34-15](https://user-images.githubusercontent.com/13104065/79236989-8e27ef80-7e65-11ea-8ae1-cd6d2b3f9337.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): Cant find settings due to this bbehaviour
 - PHP Version: 7.3.16
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @WizardKid,
When installing, were you following the manual install instructions to use the `release` branch using the following clone command?:

```bash
git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch
```

You could run `git status` in your BookStack install directory to check what branch you are on. You should be on the `release` branch.

**Comment by WizardKid** [comment]
The status is master.. I forked the rep and simply installed it.. will install from the release

**Comment by WizardKid** [comment]
Working now. thank you
