### ISSUE TITLE
Feature request: ability to toggle image desaturation in dark mode

### ISSUE THREAD

**Issue by codemicro** [BookStackApp/BookStack#2035]
The new dark theme is great, I really like it a lot. However, I think that the image desaturation is not great as it tends to make pages look a bit off and sad. Would the ability to toggle this on and off either globally or per user be a good idea? Perhaps not even in the UI if it's global, just as a setting in `.env`.

If given the green light, I'd be happy to (at least attempt) to submit a PR implenting this.

**Comment by ssddanbrown** [comment]
Hi @codemicro,
Thanks for the feedback.

Just to confirm, is this in relation to the book and shelf cover images?

> Would the ability to toggle this on and off either globally or per user be a good idea?

To be honest I try to avoid any minor UI settings like this where possible. I'd rather change the default or people add some custom CSS in the "Custom HTML Head Content" setting for this kind of thing. Maybe we should just leave this issue open for a while to see if others feel the same, then use that to assess the best default option.

**Comment by codemicro** [comment]
> Just to confirm, is this in relation to the book and shelf cover images?

Yea - I think this shows it fairly well.

![image](https://user-images.githubusercontent.com/25284325/79281018-d49f3d80-7ea9-11ea-94a7-522a80faeca0.png)
