### ISSUE TITLE
Focus on Code Block Edit

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2037]
**Describe the feature you'd like**
It would be nice to have the focus in the text field when selecting Code Block as format.

**Describe the benefits this feature would bring to BookStack users**
No need to click into the box to start writing.

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @Smoin1,
I made some updates in v0.29.0 for code block focus. I updated it so focus would on the code upon code-block editing or creation.  When you opened this, were you on v0.29? Or do you not agree with the currently implemented logic?

**Comment by Smoin1** [comment]
seems like I was not on the right version. I am on 0.30.0 now and the focus is there :)
