### ISSUE TITLE
image name overwrites cover image

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2039]
**Describe the bug**
the image name of cover images have a problem with each other which leads to no shown cover image (see steps:)

**Steps To Reproduce**

- have a shelf with two books
- add a cover image (with the name "test.png") to the first book
- cover image is successfully shown
- add a cover image (also with the name "test.png") to the second book
- the second book gets no image, the first book looses its cover image

**Expected behavior**
obviously should not happen ;)
idea is to maybe rename the picture in the background

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker): 

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @Smoin1,

Thanks for reporting this occurrence but I'm having trouble reproducing this issue. When I follow the provided steps my outcome is different, Both books receive the provided image, with the latter being stored with a prefixed name to avoid conflicts.  Could you confirm the following:

1. Are you using a non-default storage option?
2. Are you able to re-produce this on the [demo site](https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site)?

**Comment by Smoin1** [comment]
hm, damn. something in the steps is different from what I did and I cannot reproduce it currently... you can close this and I will reopen once I found out

**Comment by ssddanbrown** [comment]
Okay, Thanks for confirming.
