### ISSUE TITLE
Ordered list number clipping

### ISSUE THREAD

**Issue by davidPilkington** [BookStackApp/BookStack#204]
PHP Version: 5.6
MySQL Version: 5.6
Expected Behaviour: Ordered list items are expected to show in full to user
Actual Behaviour: Numbers greater than 10 have some slight clipping to the left
![create_a_new_client_da______cds_wiki](https://cloud.githubusercontent.com/assets/1942239/19063149/9dcb5e10-8a47-11e6-91bb-a3ce8427d9a1.png)

**Comment by davidPilkington** [comment]
I'll admit, I got a little carried away with the squiggles :)

**Comment by ssddanbrown** [comment]
Thank you for finding this issue. It is now fixed as of release [v0.12.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.12.2).
