### ISSUE TITLE
Image contrast is off in Dark Mode

### ISSUE THREAD

**Issue by derklompi** [BookStackApp/BookStack#2045]
**Describe the bug**
If you turn on dark mode the contast in uploaded images is quite off and for some images parts are not visible anymore

**Steps To Reproduce**
1. Turn on Dark mode
2. Open a page with an image

**Expected behavior**
I expect the image to be shown the same in dark and "normal" mode.

**Screenshots**
![bookstackapp](https://user-images.githubusercontent.com/10167026/79453747-64e49c00-7fea-11ea-88d9-ab2058c589a2.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.29.0
 - PHP Version: 7.2.24
 - Hosting Method (Nginx/Apache/Docker): Apache 2.4.29

**Comment by aalbul** [comment]
+1. Have the same issue. I love dark mode, but this makes it almost unusable for me :(

**Comment by maderschramm** [comment]
Same issue here

**Comment by abulgatz** [comment]
Looks like it's the a tag dark-mode styling affecting images inside links.

```
html.dark-mode a {
    filter: brightness(1.3) saturate(0.7);
}
```

**Comment by jessica-mulein** [comment]
I ran into this as well. It trashes the color of book/shelf/app images.

**Comment by ssddanbrown** [comment]
Thanks for confirming everyone, For v0.30 I've updated the dark mode styles to not affect images. Until that's release you should be able to add the following to your "Custom HTML Head Content" setting to work-around for now:

```html
html.dark-mode body a {
    filter: none;
}
```

The styles causing this were down to attempting a brightening of links for dark mode use, which will now be left as the default app theme color. If found to be an issue (Links are commonly too dark), we'll have to look at other solutions for that instead.
