### ISSUE TITLE
v0.29 update ~ Issue with ".env.example.complete"

### ISSUE THREAD

**Issue by angelos-alexiou** [BookStackApp/BookStack#2049]
Hi!

I've got an error during the update from v0.28.3 to v0.29

**ERROR DESCRIPTION**
_error: Your local changes to the following files would be overwritten by merge:
	.env.example.complete
Please commit your changes or stash them before you merge.
Aborting_

**STEPS TO REPRODUCE IT**
According to the documentation [(https://www.bookstackapp.com/docs/admin/updates/)](url) i've done the followings:
`cd /var/www/bookstack`
`git pull origin release && composer install --no-dev && php artisan migrate`
...and then I get the above error.

**WORKAROUNDS**
Tried to clean the cache and then run the above git command with no luck.

**ADDITIONAL INFO**
Server Type = VPS
O/S = Ubuntu 18.04.4 LTS

Any ideas how to solve it??

**Comment by LouWii** [comment]
Try `git checkout .env.example.complete` before upgrading. That will reset the file and should fix the git issue. You'll loose any content you added/changed in that file, so make a backup if necessary.

**Comment by angelos-alexiou** [comment]
@LouWii: Thank you so much. **It works like a charm**!! :)

Please note that I'd get some weird errors when trying to run with `sudo`:
`sudo git pull origin release && composer install --no-dev && php artisan migrate`
so I decided to run it again using the root user:
`sudo -i`
`cd /var/www/bookstack`
`git checkout .env.example.complete`
`git pull origin release && composer install --no-dev && php artisan migrate`

Works perfectly!! Thank you so much!!

PS: The only change I've changed in the ".env.example.complete" file was:
`REVISION_LIMIT=3`
(_instead of 50_)

**Comment by ssddanbrown** [comment]
Just a note, you should not need to touch the `.env.example.complete` file, it's simply there as a reference of all options available. Make any changes you need within your `.env` file.

Since this appears to be solved, I'll close this off.
