### ISSUE TITLE
Shelf sort button

### ISSUE THREAD

**Issue by E-Fail** [BookStackApp/BookStack#2050]
**Describe the feature you'd like**
On some shelves I need a alphabetical order. I have to go to the PHPMyAdmin, Export a List of books in shelf X, Order them in Excel and drag them in Bookstacks. 

It would be nice to have a "sort alphabetical" button in the shelf edit. Not default for all, Sometimes it make sense, sometimes not. Only have the possibility to do so. 

**Describe the benefits this feature would bring to BookStack users**
Less grey hair. Sorting is essential.

**Comment by ademxoy** [comment]
+1

**Comment by fischmann-it** [comment]
Any Update since 2020?

**Comment by alatteri** [comment]
Agreed.... this would be really nice feature to have.

**Comment by ssddanbrown** [comment]
As part of the changes in #4049, there is now a little dropdown with some sort helpers when editing a shelf:

![image](https://user-images.githubusercontent.com/8343178/219708712-2c604f2c-3387-4a2b-a7b2-e38b9f93dd04.png)

This will be part of the next feature release, so I'll therefore close this off. 
Thanks @E-Fail for the original request.
