### ISSUE TITLE
Feature request: Table of contents in exported PDF

### ISSUE THREAD

**Issue by HanEmile** [BookStackApp/BookStack#2052]
**Describe the feature you'd like**
Exporting a book as a PDF containing a Table of contents (not on the first page, but embedded in the pdf file so that PDF viewers can use that information accordingly)

**Describe the benefits this feature would bring to BookStack users**
The benefit of this would be that books could be exported and used in a way that doesn't include having to tediously search for content in the PDF that is structured in the book.
The structure from inside bookstack could be contained in the PDF.

**Additional context**
Here a screenshot of how firefox displays embedded table of contents:
![DeepinScreenshot_select-area_20200418221224](https://user-images.githubusercontent.com/22756350/79670235-ce6ad300-81c1-11ea-9aee-ed85afd1a7cd.png)
(example from the [radare2 book](https://www.gitbook.com/download/pdf/book/radare/radare2book))

**Comment by ssddanbrown** [comment]
Hi @HanEmile,
Such as table of contents is not supported by the default PDF converted in BookStack (DomPDF).

BookStack can be configured to use WKHTMLtoPDF instead for PDF conversion as described here:
https://www.bookstackapp.com/docs/admin/pdf-rendering/

Unfortunately in the most recent (and popular) version, 0.12.5, table of contents functionality does not seem to work as per this issue:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3953

The workarounds from that issue, of using a [development build from here](https://builds.wkhtmltopdf.org/0.12.6-dev/) did seem to work for me, producing a PDF with the embedded TOC.

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by ssddanbrown** [comment]
Hi @ashkulz,
Sorry, I had missed your message before, Just coming across this now.

Just want to say, thank you so much for your work on wkhtmltopdf; the expertise and effort you spend on that project is greatly appreciated! 

I just ran a quick test on **0.12.6** and all seemed to work perfectly. Thanks!

**Comment by ssddanbrown** [comment]
Since a workaround for this issue now exists, by using the wkhtmltopdf option, I'll therefore close this off.
