### ISSUE TITLE
Language To Add Thai

### ISSUE THREAD

**Issue by katawutp** [BookStackApp/BookStack#2054]
### Language To Add

Please add Thai language. I'm willing to do the translation.
Thank you!

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Hi @katawutp,
Thank you very much for offering to translate the project into Thai. I've added Thai as a language to [Crowdin](https://crowdin.com/project/bookstack) so you should be able to go ahead and start translating. 

If you change your mind at all, feel free to comment here.
