### ISSUE TITLE
Dark Mode: Text highlight colour same as background colour in certain areas

### ISSUE THREAD

**Issue by conor-byrne** [BookStackApp/BookStack#2060]
**Describe the bug**
Highlighting/selecting text has no visual effect in certain areas while in dark mode. The text is still highlighted/selected as can be shown by a copy/paste.

Areas I've noticed it in:
* markdown editor
* code block in rendered page

Interestingly, it works in the markdown editor's preview pane but not the final rendered page.

**Steps To Reproduce**
1. Set editor to be markdown in settings.
2. Create a new page.
3. Include a markdown code block in the page.
4. Try to highlight any text in the markdown editor.
5. Observe no visual text highlighting.
6. Observe that copy and paste still work (Ctrl-C, Ctrl-P).
7. Save page and be returned to the rendered page view.
8. Try to highlight some text inside the code block.
9. Observe no visual text highlighting as before.
10. Observe that copy and paste still work (Ctrl-C, Ctrl-P).

**Expected behavior**
Text to be highlighted with white background, blue text colour.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.0
 - Hosting Method (Nginx/Apache/Docker): podman: docker.io/linuxserver/bookstack:latest

**Additional context**
Firefox Developer Edition 76.0b6

**Comment by ssddanbrown** [comment]
Hi @conor-byrne, Thanks for reporting this issue with clear reproduction steps.

Apologies about this, Turned out I had set a background style that then laid over the element that represented the text selection, making the selection hidden behind a foreground element.

I've now fixed this and the patch will be part of the next BookStack patch release.

**Comment by conor-byrne** [comment]
@ssddanbrown No problem at all, thanks so much for your work!
