### ISSUE TITLE
no callout possible on strikthrough

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2061]
**Describe the bug**
define a callout on text with strikethrough is not possible

**Steps To Reproduce**
write text
strikethrough
select any callout

**Expected behavior**

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker): 

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @Smoin1,
Unfortunately I have not been able to reproduce this issue on my instance, I can create a callout on strike-through text, and create strikethough text on a callout.

Do you have the same issue on the demo instance?:
https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site

If so, please could you confirm your BookStack version and your browser & operating system?

**Comment by Smoin1** [comment]
I retested: it is only prevented if I use the shortcut for callbacks. normally it cycles thourgh the 43 variants. this is not the case anymore. also confirmed on demo instance.

**Comment by ssddanbrown** [comment]
Thanks for confirming @Smoin1.

I have updated this shortcut in 468fec80de7e32d2881eab2d7f7c40a2df872956 to handle nested formatting, such content such as strike-throughs does not prevent the shortcut from cycling options.

This fix will be deployed in the next BookStack patch release.
