### ISSUE TITLE
Favourites vs Starred vs Bookmarks vs Pinned vs Something Else

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#2063]
Just looking to get some feedback on the naming for some kind of user-level "favourite" system of BookStack entities (Shelves, Pages, Books, Chapters).  This feature is a prerequisite for working towards a notification system in BookStack (For example, receiving notifications for starred items). 

What terminology do you think would suit best?

#### Intended Functionality of this system (Initially)

- "Favorited" items would be shown on a user's home screen for quick access.
- In the future, a user will be able to receive notifications for changes to "Favorited" items. 

#### Options

- Favourites
- Starred
- Bookmarks
- Pinned
- _Something Else - Feel free to suggest_

#### Thoughts so far

- Bookmarks initially sounds like it fits nicely with the "BookStack Theme" but it could cause confusion with browser book-marks. Also, the analogy does not translate fully as you wouldn't usually ally a "BookMark" to a shelf or whole book. 

---

Related to #505 & #1376

**Comment by hercules808** [comment]
Well, a word like "reservation" might fit with the book/library theme, although that has the same limitation around specificity (i.e. you might expect it to mostly apply to just a book), and it does feel like it might be stretching the metaphor a little too far! I wonder whether "Favourite" (English spelling preferred) might be the best choice even it it does tend to get over-used...

**Comment by MatthieuParis** [comment]
+1 for "_favourite_ shelves/books/chapters/pages".

The place where one could find all the favourites could be called ones's _desk_ or _nightstand_.

**Comment by angelos-alexiou** [comment]
Favourites = Could produce confusion! Eg. a "favourite" page full of warnings' descriptions, might not be as favourite as is sounds, but a shortcut to that page!
**Starred = THE BEST :+1:** 
Bookmarks = Agree to your thought
Pinned = Suitable for forums, not in bookstack (hey, my opinion)
Something Else = Shortcuts (??)

**Comment by dannyhanes** [comment]
I would go with favorite and maybe have the icon look a little like a bookmark. If you use "starred" then it would have to look like a star lol. 

In the future when we can get notifications, are you thinking if we "favorite" a book, then anytime a new page is created / updated in the book, we could send out notifications? Because that would be amazing.

**Comment by Venkinovec** [comment]
From your options I would go for **Starred**.
Something Else = what about simply **Watch** shelves/books/chapters/pages
then u can have a place called **Observatory** ?
Just my opinion.

**Comment by c0shea** [comment]
What about **Checked Out Items**? Although similar to the bookmark term, you don't check out a page.

**Comment by Honvid** [comment]
comment for the content's words.  it's looks like bellow:

![image](https://user-images.githubusercontent.com/8649968/86777837-3b3c8d80-c08c-11ea-8a28-c7f4aef55e6f.png)

this can be links to the page's comment, some other link address.

**Comment by b-zurg** [comment]
In terms of language and usability I think sticking to a commonly used term, like the ones originally put forth, is important instead of making something new. 

The clarity of its usage is more a matter of UX than a matter of wording imo. As for the wording I'm tending toward starred but I think that's because of my affinity for GitHub 😆

**Comment by alexmannuk** [comment]
I would suggest either Watch or Subscribe would be best. Bookmark would seem to be more like marking the last viewed page in a book, and may also be confused with Browser bookmarks, as may Favourites. Starred would commit you to using a star to mark, and intuitively seems like it would just be marking your most used pages/books. Watch and Subscribe both make it clear that you're looking for changes.

**Comment by patrickcage** [comment]
I think @alexmannuk has hit the nail on the head with Watch or Subscribe. It fits with Shelves, Books, Chapters & Pages as well as being very descriptive. I would lean towards Watch/Watched myself but I find either suitable.

**Comment by VonCountHLM** [comment]
I think it makes sense to name the section "Watchlist". "Starred" is a strong second in my opinion, as it's a common term used throughout software packages and the web at large. Either term seems straightforward to me.

**Comment by dannyhanes** [comment]
@VonCountHLM Starred if I am simply saving it for later. Watchlist if I am going to be emailed about changes to the page (or sub pages) +1 for watchlist if we can get that feature. 

I have a "Chapter" books and would LOVE to be able to send out emails to "watcher" whenever a new page (or chapter) is added to the book.

**Comment by bridgeyuwa** [comment]
Many Apps I have come across use starred, so I am more conversant with Star/Unstar

I vote in favor of **Starred**

**Comment by ssddanbrown** [comment]
Thanks everyone for your feedback.

In the end, when counting the comments and the various reactions on each, stars and favourites were kind of close, with 11 votes for "Favourites" to 12 votes for Stars. 

In the end I've chosen "Favourites" as the wording, since I think that's the most clear wording for the feature, especially for those that may be non-technical. I feel the "Stars" option may have had a slight bias advantage since this was asked on GitHub to technical folks. A star will be used as the icon that'll sit alongside the action.

I don't want any "Watch", "Subscribe" or similar wording for this since any kind of notification/alert would be a potential secondary idea of this feature, The core function is to have a personal refined list of content within the system.

A "Favourites" system implementation has now been merged into master (Details on PR #2748) ready for the next feature release.
