### ISSUE TITLE
Viewcount

### ISSUE THREAD

**Issue by canavar2212** [BookStackApp/BookStack#2066]
Books, bookcases, page and tabs view count can it be added?

**Comment by ssddanbrown** [comment]
Hi @canavar2212,
View-counts are stored in the database at a per-user level but are not exposed currently. If you are nifty with SQL you can review the `views` table in the database.

If you want these shown in the interface, it would help to describe in what manner they should be visible in addition to describing the benefits that the feature would bring to BookStack users.

**Comment by ssddanbrown** [comment]
Since there has been no response on this I'll close it off. If this remains something you still require please open a new issue, referencing this one, with the requested details provided.
