### ISSUE TITLE
Video in User Documentation couldn't be decoded

### ISSUE THREAD

**Issue by GiantCrocodile** [BookStackApp/BookStack#2068]
Hello,

the video at https://www.bookstackapp.com/docs/user/reusing-page-content/ is broken. It doesn't work in latest Firefox and latest Edge.

Video couldn't be decoded because of this error in the console:
![grafik](https://user-images.githubusercontent.com/6271057/80416011-b1c24f80-88d3-11ea-8703-d307a554cf9b.png)

Best Regards,

**Comment by ssddanbrown** [comment]
Thanks for reporting @GiantCrocodile.
I've now added a webm copy alongside the current video source to ensure better cross-device support.

**Comment by GiantCrocodile** [comment]
@ssddanbrown This seems to work for FireFox but didn't help for Edge. In Edge the video is just black. I don't know about other browsers.

**Comment by ssddanbrown** [comment]
@GiantCrocodile Ah, This is why people just use gifs :smile: 

Do you know if your're using the new chromium-based edge or the old one?

**Comment by GiantCrocodile** [comment]
@ssddanbrown I think it's not the chromium-based one:

```
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363
```

**Comment by ssddanbrown** [comment]
Thanks for confirming, In that case I'll probably ignore old-edge since; Since it's growingly-redundant.
