### ISSUE TITLE
LDAP Authentication Documentation incorrect 

### ISSUE THREAD

**Issue by robrotheram** [BookStackApp/BookStack#207]
PHP Version:7

MySQL Version:5.6

Expected Behavior: Working Ldap config

Actual Behavior: Ldap connection failer

This is beacuse the config listed at [https://www.bookstackapp.com/docs/admin/ldap-auth](https://www.bookstackapp.com/docs/admin/ldap-auth)
LDAP_SERVER pramater as a connection string ie ldap://example.com:389

Due to not type checking of the this paramater the explode function creates invalid connection parmaters
https://github.com/ssddanbrown/BookStack/blob/master/app/Services/LdapService.php#L116

Using the example url the explode function will create an array with 3 elements "ldap","//example.com",389

Since the connection paramater only looks at the first 2 elements in the array the connection parmaters are now increct snince the port needs to be a integer and now gets the string "//example.com"

My suggestion is to remove the ldap:// from the documentation to avoid further confusion or do type checking on the paramater somethink like `if starts with 'ldap://'`

**Comment by ssddanbrown** [comment]
@robrotheram Thanks for letting me know about this documentation issue, Sorry for the hassle it may have caused you.
