### ISSUE TITLE
Strict/more private guest mode

### ISSUE THREAD

**Issue by mahdi1234** [BookStackApp/BookStack#2072]
**Describe the feature you'd like**

My typical workflow for sharing notes with people over internet is that I use random stuff with random groups of people and am not interested that everyone sees everything. These are typically scripts for trainings or general info, not collaboration, so read-only for my guests.

It'd be great to have more strict guest access with following conditions:
- login page shows only "Login" button, no search, no history of changes
- guest can access direct link, which doesn't display any details pane nor books/pages with search removed and only option to login

**Describe the benefits this feature would bring to BookStack users**

One could share random stuff with random people without others knowing about other content.

**Additional context**

I'm trying to find alternative to hackmd which can share articles this way.

**Comment by ssddanbrown** [comment]
Hi @mahdi1234,
Thanks for your suggestion here.

I probably wouldn't look to include additional more "strict" guest permission options which alter the UI, as there's not a large amount of demand for them and that kind of addition has an impact on maintenance. You can already get fairly specific with the current permission options, by creating a role with no permissions then providing view access on particular items, although this is only available at a role-level, not a per-user level. 

Sharing via a direct, unique link is a feature that would add value and be much more possible. This is already open in issue #288.  

I'll therefore close this off.
