### ISSUE TITLE
Copy Permission to book not working

### ISSUE THREAD

**Issue by Biepa** [BookStackApp/BookStack#2075]
**Describe the bug**
I select a shelf and go to the permissions page, change the permissions, save and then click to copy the permissions to the book(s). There is 1 book in the shelf, but the notification shows, that the permissions are applied to 0 books. (GIF below)

**Steps To Reproduce**
It's not reproducible on the demo page. But also happens with more than 1 book on my instance. And happens independent of the permissions chosen.

**Expected behavior**
Permissions should be applied to books in the shelf.

**Screenshots**
![Peek 2020-04-28 19-57](https://user-images.githubusercontent.com/25102748/80527235-53a97100-8994-11ea-833f-25d6ddf24b0f.gif)

**Your Configuration (please complete the following information):**
Version 0.29 with linuxserver.io docker image

**Additional context**
I'm trying to solve the following problem:
I'm currently having a "user" group, where everybody could only access and modify there own content. Now i want to allow other users, to read-only my content (I'm also in the "user" group).
I added another "share" group and wanted to edited the custom permissions for my book, so "share" members could read it, but

a) when only choosing "view" for the "share" group, then i lock myself from editing the page (and if I'm not even in the "share" group i lock myself away from the whole book, so that I can't even see it anymore (needed the admin user to reconfigure the permissions). Is there a plausible reason to lock yourself out, or should something be implemented, that will you prevent from that? )

b) when also choosing "edit" for the "user" group (because I want to edit the book, and I'm in the "user" group, then all other "user" members could too.

What is the right setup for my I'm in the "user" group as everybody else, but want to share a book/shelve with other users, but still be (the only one) able to edit it (my content)?
Of course I could make every user his own role, but that doesn't seem to be the right way I think.

**Comment by xakaitetoia** [comment]
I have found some weird issues with the permissions as well. For example i thought when creating a normal user and giving him the editor role, it should not see and edit all other books from other users but seems you have to create a new specific role like "member" to be able create/edit/view/delete own books and chapters etc. 
Also a good idea is if you can share a page with someone or even transfer the ownership of the page

**Comment by Biepa** [comment]
Could you give me a hint at how to setup my permissions the best?

What is the right setup for my I'm in the "user" group as everybody else, but want to share a book/shelve with other users, but still be (the only one) able to edit it (my content)?
Of course I could make every user his own role, but that doesn't seem to be the right way I think.

**Comment by ssddanbrown** [comment]
Just spent some time to double check this issue.
From my testing, this could reasonably occur when the copy permission action is performed when you don't have permission to "Manage permissions" of any of the child books, which I think is reasonable, so I will close this off. 

My advice to the above would be to keep things at the book level, which you could then use the "own" role permissions and have permissions cascade.
