### ISSUE TITLE
Feature Request: Option to not add user/revision info to page PDF export

### ISSUE THREAD

**Issue by conor-byrne** [BookStackApp/BookStack#2076]
**Describe the feature you'd like**
User control over whether revision/user information is appended to the end of a page PDF export.

**Describe the benefits this feature would bring to BookStack users**
When used as part of an internal workflow, the hyperlinks will point to unreachable addresses for anyone outside of the network, which serves no purpose.

Currently, when I want to share a document with a client, I must first edit the generated PDF to remove the additional information at the end of the document.

**Comment by ssddanbrown** [comment]
Hi @conor-byrne,
If you want to sort this immediately you can achieve this via the theme system:

1. Create a blank `themes/custom/partials/entity-export-meta.blade.php` file, within your BookStack installation folder. You should find that the `themes` folder already exists, you'll need to create the `custom` and `partials` folders.
2. Add the below option to your `.env` file:

```bash
APP_THEME=custom
```

---

Edits via the theme system is not officially supported, and could break or cause issues upon update, but I'd be generally happy to support on such occurrence.

**Comment by conor-byrne** [comment]
@ssddanbrown Excellent, thanks! As an aside, are inline code sections intentionally orange in the exported PDF?

**Comment by ssddanbrown** [comment]
> As an aside, are inline code sections intentionally orange in the exported PDF?

Errr, Totally, Part of an early spooky halloween update :sweat_smile: 

Definitely [did not mistype a color-code](https://github.com/BookStackApp/BookStack/commit/2a2d0aa15b99f4181dd25b203b5932d56d221982).  _Has been patched for the next minor release_

**Comment by ssddanbrown** [comment]
Since the main benefit listed here, the removal of unreachable hyperlinks, is no longer relevant in the latest releases (No longer linked) and since a workaround has been provided for completely removing the meta content, I'll close this off.
