### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by EloFran** [BookStackApp/BookStack#2078]
Hello, I have an app, which has some webview. But when I try to do one with my Boockstack I get something that doesn't look like the mobile version I see when I'm browsing. Something very different appears to me and also does not work well. Could someone advise me on what to do? Thank you.

**Comment by ssddanbrown** [comment]
Hi @EloFran,
We'll need a deeper level of detail of what you're attempting here before we can help.
- Any screenshots of how things appear? 
- Any details of the webview in use? Or the devices this is on?
- Is you're BookStack instance working okay outside of the webview?

**Comment by EloFran** [comment]
thanks for the reply,
https://drive.google.com/file/d/1KZCfQd7MDILyndYSQJmwojvp1itT_p48/view?usp=sharing
https://drive.google.com/file/d/16rRFFV-n2Gh30q_zKcUvaff25URGJ2Gq/view?usp=sharing

One is the preview from android studio with a webview, and java activated. And the other is the browser view with see as mobile.
I have used the official website so that you do not think that I have anything modified in my code.
Thx

**Comment by ssddanbrown** [comment]
Hi @EloFran,

This is strange, The built-in Android webview has been chromium based and I thought it was kept up-to-date. Are you perhaps targeting a very old android API level? Or is the device being tested on relatively old? Are you testing on an emulated device or a real device over USB?

Additionally, Are you using the default built-in [Android webview](https://developer.android.com/reference/android/webkit/WebView)? Or some other class/library?

From your screenshot, I get the feeling that you're using flutter, And therefore not the official Android widget library.

**Comment by EloFran** [comment]
Hi,
you are absolutely right, with a real device if it looks good, it is only with the emulator that.
Thx very much.

**Comment by ssddanbrown** [comment]
Great, Sounds like this mystery is solved, Will therefore close this issue. Good luck with the app!
