### ISSUE TITLE
[Request] Is there a stable version of BookStack?

### ISSUE THREAD

**Issue by spikerola** [BookStackApp/BookStack#208]
### For Feature Requests

Desired Feature:

A stable version of BookStack

**Comment by pydubreucq** [comment]
Hi,
I'm using it in production and I don't any problem.
I'm just waiting the next release to have the last update like page summary.
Best Regards

**Comment by ssddanbrown** [comment]
Hi @spikerola,
There's only one version of BookStack, which is the one currently at Beta v0.12.1. I'm hesitant to bring it out of beta until I'm happy that all of the main bulky features are in the application (Which there's still a few of on the roadmap).

That said I do try to ensure BookStack is as stable as possible, even while in its beta form. I try my best to fix any usage-stopping bugs ASAP and release bugfix versions of BookStack. I've also kept an easy upgrade path so far although the next major release will require a little more attention (Required PHP version is increasing and some additional php extensions will be required). I have some plans for some major database changes in the near future as well but I will always try to keep an easy upgrade path for existing users.

**Comment by patoroco** [comment]
Nice!

PD: please close this kind of issues if there are solved! 💃

**Comment by Shackelford-Arden** [comment]
@spikerola I think it's safe to say we can close this?
