### ISSUE TITLE
BookStack is not reached from the web

### ISSUE THREAD

**Issue by wisdomlight** [BookStackApp/BookStack#2080]
On RPi4 with Ubuntu 20
BookStack is available via local home network

I have Nextcloud server with port forwarded to 80 and 443.

Accessing BookStack via my no-ip-domain-name.com I am served with a Nextclouod page.

I suppose the issue is with port forwarding?
What and where do i change the configuration?

Thank you.

**Comment by lithium-ap** [comment]
How is your webserver configured? Are you using nginx, apache, or something else? Can you share your configs? It sounds like you dont have vhosts configured.

**Comment by wisdomlight** [comment]
Hi @lithium-ap 
Thank you.
BookStack was installed with the help of the Ubuntu 20.04 script. So I guessed all the various components are automatically added?

Any how I solved it but not sure if it is a healthy solutio:
using my no-ip i directed my domain-name.com to a different port on the router and mapped it to internal port 80.
It seems to work now.
I am not sure why - but it seems to have done the trick.
Please let me know if you think there's a better way.
Thank you

**Comment by ssddanbrown** [comment]
@wisdomlight Commonly you'd use two different domain names and then have a proxy/web server to direct the traffic based on domain, But whatever works is fine I guess.

I'll therefore close this off.
