### ISSUE TITLE
Add env variable to set default light/dark mode option, For when no set preference exists

### ISSUE THREAD

**Issue by mahdi1234** [BookStackApp/BookStack#2081]
**Describe the feature you'd like**
Add .env setting for default to be dark mode.

**Describe the benefits this feature would bring to BookStack users**
Customization of bookstack appearance without using themes. Also since mode toggle is on home page anyone going to direct link can be forced to dark mode.

**Additional context**
Hope I haven't missed it, but I couldn't find it here https://github.com/BookStackApp/BookStack/blob/master/.env.example.complete

**Comment by ssddanbrown** [comment]
Hi @mahdi1234,
Could you describe what is meant by this?

> Customization of bookstack appearance without using themes. Also since mode toggle is on home page anyone going to direct link can be forced to dark mode.

The dark-mode in BookStack is a user-level preference. It should not affect other users in the system.

**Comment by mahdi1234** [comment]
Hi @ssddanbrown maybe I described that bit confusing, basically I would like to have a setting for default theme light/dark, so when I give someone direct link to page_xyz it's dark on first visit. Sure he can change later on to white, but it's about first visit, does it make sense?

**Comment by ssddanbrown** [comment]
@mahdi1234 Ah, Okay, that makes sense. Thanks for confirming, I'll update the title.

**Comment by mind-overflow** [comment]
Hey! Any updates on this?

**Comment by ssddanbrown** [comment]
> Hey! Any updates on this?

Nope, nothing yet

**Comment by FrostyWolf** [comment]
Is there still no way to change the default theme to dark?

**Comment by modem7** [comment]
+1 on this. My retinas would certainly appreciate it!

**Comment by ssddanbrown** [comment]
Code added in b0f4500c3419b10317c5e976f6bd357efdf8b049.

As of the next feature release (v0.32), You'll be able to set `APP_DEFAULT_DARK_MODE=true` to enable dark mode by default. This will be overidden for any users/sessions that have previously pressed one of the dark/light mode toggle buttons.
