### ISSUE TITLE
Just need some direction

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [BookStackApp/BookStack#2083]
If there's a better place for posts like this, please let me know.

We upgraded from v0.27.x (don't remember exactly) to the latest v0.29.1. During the upgrade, we received this message:

![image](https://user-images.githubusercontent.com/50454265/80774900-ce54c680-8b23-11ea-9e25-f3d80c99570f.png)

What do we need to do to heed the advice?

Also, with the upgrade from php 7.2 to 7.4, do we need to remove php 7.2? How would we go about that?

Thanks,
Craig

**Comment by ssddanbrown** [comment]
Hi @FMCUSystemAdmins,
You don't need to do anything about that warning. Is something that will be addressed with time.

> Also, with the upgrade from php 7.2 to 7.4, do we need to remove php 7.2?

Is that a system upgrade you've done? BookStack still works on php7.2, We would not have enforced such a change via a BookStack update.

Generally, it doesn't cause issues running multiple PHP versions side-by-side but you might as well remove the other if not in use, You'll have to be sure your web-server is using the correct one before you remove the other.

**Comment by FMCUSystemAdmins** [comment]
Thank you @ssddanbrown,

Sounds good on the warning.

As far as the PHP upgrade, we did that per [Updating to v0.28 or higher](https://www.bookstackapp.com/docs/admin/updates/). Only difference from our install and what is within that documentation is that we are using Apache for our web server instead of Nginx. After the install of the PHP 7.4 packages, we ran `a2enmod proxy_fcgi setenvif` and `a2enconf php7.4-fpm`. Was that sufficient to make Apache use 7.4? How would we verify this is the case to avoid breaking something with the removal of 7.2?

**Comment by ssddanbrown** [comment]
@FMCUSystemAdmins 

Ah, Okay, Those update instructions only really needed to be followed if you were on a lower PHP version than 7.2 but hey, might as well upgrade early and get the benefits of php7.4 👍

I'm not sure of an easy way to check what Apache is using. Easiest way I guess is to just remove php7.2 and see if it breaks. Hopefully, even if apache is still using php7.2, It'd switch over to the other version upon uninstall. 

If you want to be more careful, You could always create a `<bookstack_install_dir>/public/info.php` file with the contents:

```php
<?php phpinfo(); ?>
```

Then visit `https://<my_bookstack_url>/info.php` and find the version at the top. Remember to delete the `info.php` after checking though.

**Comment by FMCUSystemAdmins** [comment]
Thank you for that handy PHP version check. Apache was still using PHP 7.2. Ended up running `a2dismod php7.2` then `a2enmod php7.4`. Restarted the Apache service, refreshed the info URL, and it updated to 7.4. Uninstalled 7.2 and all still looks good on the PHP front. Also found that the `*fpm` packages are irrelevant for Apache. They are only needed if using Nginx.

Thanks for pointing me in the right direction!

**Comment by ssddanbrown** [comment]
@FMCUSystemAdmins No problem, Glad it's all working! Will therefore close this off.
