### ISSUE TITLE
Limited translation options in czech language on Crowdin

### ISSUE THREAD

**Issue by Venkinovec** [BookStackApp/BookStack#2084]
**Describe the bug**
I cannot translate variable named 'x_chapter' located in 'entities.php'.
Hint tells me to use two OR cases ':count Chapter|:count Chapters'.
We have 4 cases of using word 'chapter' in 3 different writtings and one writting is used in two cases.

**Steps To Reproduce**
Look for more in issues at [Crowdin](https://crowdin.com/translate/bookstack/46/en-cs).

**Expected behavior**
Should be able to translate it completely.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304952/80835366-e5161e80-8bf2-11ea-8c8d-c2a2ef306257.png)

**Your Configuration (please complete the following information):**
 BookStack v0.29.1

**Comment by mahdi1234** [comment]
How about reverse it

> kapitol :count

or

> počet kapitol :count

seems legit to me (if it's possible to do it like this).

**Comment by ssddanbrown** [comment]
Hi @Venkinovec,
BookStack uses Laravel's translation system, pluralisation cases can follow the formats defined here:
https://laravel.com/docs/6.x/localization#pluralization

Therefore the format in the following example can be used:
```php
'apples' => '{0} There are none|{1} There is one|[2,*] There are :count',
```

**Comment by Venkinovec** [comment]
Hmmm, I didn't think about this one.
> počet kapitol 

If I change other counter to "počet" then it will look naturally.
Thank youfor this advise.

**Comment by Venkinovec** [comment]
> Hi @Venkinovec,
> BookStack uses Laravel's translation system, pluralisation cases can follow the formats defined here:
> https://laravel.com/docs/6.x/localization#pluralization
> 
> Therefore the format in the following example can be used:
> 
> ```
> 'apples' => '{0} There are none|{1} There is one|[2,*] There are :count',
> ```

Wow, I will use the system then.
Thank you @ssddanbrown

**Comment by Venkinovec** [comment]
I'll study Laravel's localization a bit, since I plan to complete czech translation.

**Comment by Venkinovec** [comment]
I forgot (since I was focused on one problem).
Is there a way to modify recent activies to the point where I can change the structure of sentence completly (change position of username in text) ?I would like to have something like: 
>page :page created/edited/deleted by user :username

Otherwise I would have to recognize gender.
On Crowdin I seen in other languages modifications  only to the grey part of the text.
![image](https://user-images.githubusercontent.com/25304952/80849250-b01bc300-8c16-11ea-9929-9c67b9c4c684.png)

**Comment by ssddanbrown** [comment]
@Venkinovec Unfortunately not, at least not quickly & easily. Since the user and asset components are linked, and therefore within different HTML elements, it make it tricky to have in a single string, at least while ensuring content remains escaped and secure.
