### ISSUE TITLE
autorun script when user logs in first time after registration (first login via SAML)

### ISSUE THREAD

**Issue by Venkinovec** [BookStackApp/BookStack#2085]
**Describe the feature you'd like**
When user logs in for the first time I want to run some simple script to autocreate him a book(which he owns).

**Describe the benefits this feature would bring to BookStack users**
This could be a replacement for wikipedia [namespaces](https://en.wikipedia.org/wiki/Wikipedia:Namespace)

**Additional context**
The script could also do things like set him profile picture depending on his role given from SAML for example.
We use bookstack with SAML as closed wiki with documentation.
I want for everyone who logs in to have his own book and not be able to create any more books.

**Comment by ssddanbrown** [comment]
As of v21.04 this function can be done via the logical theme system: https://github.com/BookStackApp/BookStack/blob/master/dev/docs/logical-theme-system.md
