### ISSUE TITLE
include page in multiple books

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2087]
**Describe the feature you'd like**
I would like to be able to include a page (or even a chapter) in multiple books.

**Describe the benefits this feature would bring to BookStack users**
It would extend the benefits of the **digital** documentation. this is a thing which is very useful in many scenarios but not possible in real world. one example could be in a collaborative documentation where one person is responsible for the topic/technology and another for the use case (which uses several topics). we are often working that way :)

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @Smoin1,
This request is already open under #182. In fact, you are the latest commenter on that issue!
Will therefore close this off as a duplicate.

**Comment by Smoin1** [comment]
oh thank you.
I was also wondering but didn't find it in my notes. sry :D
