### ISSUE TITLE
Change search engine

### ISSUE THREAD

**Issue by EloFran** [BookStackApp/BookStack#2088]
**Describe the feature you'd like**
Hello again, I would like to know if there is a way that the predictive search engine that appears when you want to add a link when you are editing, was the one that comes as the main one. Or failing that the exact search engine.

**Describe the benefits this feature would bring to BookStack users**
In my case, the articles of my books are numbered and an approximate search is not useful.

**Additional context**
An example,
if I search for: "article 5", neither 15 nor 55 will be useful to me. I know that if I put it in quotation marks, the search is exact, but from the mobile it is quite uncomfortable to be adding quotation marks.
Thx !

**Comment by ssddanbrown** [comment]
Hi @EloFran,
Unfortunately there is no way to alter the search engine by default.

It might be possible to hack something via custom JS in the head, or via custom logic in the [logical theme system](https://github.com/BookStackApp/BookStack/blob/master/dev/docs/logical-theme-system.md) or inventive use of the [visual theme system](https://github.com/BookStackApp/BookStack/blob/master/dev/docs/visual-theme-system.md).

Within #3043 (To be part of the next feature release) I did make some changes to auto-convert potentially troublesome terms to exact terms, but I'm not sure that would help in your exact example scenario.
