### ISSUE TITLE
Export PDF - no display on Japanese characters

### ISSUE THREAD

**Issue by ahmadsyamim** [BookStackApp/BookStack#2092]
**Describe the bug**
Export PDF - no display on Japanese characters.
HTML Export seems to be no problem.

**Steps To Reproduce**
1. Create pages with Japanese character
2. Export to PDF
3. No Character showed

**Expected behavior**
To display Japanese character on export PDF

**Screenshots**
![image](https://user-images.githubusercontent.com/14102774/80948994-1cbcda80-8e2e-11ea-8a6b-423bcff43ca9.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.29.2
 - PHP Version: PHP 7.4.5
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
HTML Export seems to be no problem.

**Comment by boulledogue** [comment]
Hello,
I'm using [wkhtmltopdf](https://www.bookstackapp.com/docs/admin/pdf-rendering/) and i don't have any problem with japanese characters... Did you try too ?

**Comment by ahmadsyamim** [comment]
> Hello,
> I'm using [wkhtmltopdf](https://www.bookstackapp.com/docs/admin/pdf-rendering/) and i don't have any problem with japanese characters... Did you try too ?

Thank you @boulledogue ! 
I just tried and it really helps!
