### ISSUE TITLE
Highlighting in Code Blocks via Dark Mode Does Not Show the Highlight

### ISSUE THREAD

**Issue by ReaHe** [BookStackApp/BookStack#2093]
I could not find this bug already posted

**Describe the bug**
Whenever I highlight anything in a code block when in Dark Mode, via editing the code block or straight from the page the highlight does not appear.

**Steps To Reproduce**
1. Go to a existing page with a code block or make a page with one
2. Put content in code block
3. Turn on Dark Mode in the top right corner of the Bookstack
4. Attempt to highlight code block content and see that the highlight itself does not appear.

**Expected behavior**
I expect to see a highlight of the code in blue just as I do when I highlight any other content on the page normally

**Screenshots**
![highlight bug](https://user-images.githubusercontent.com/16505127/80997870-fd16b980-8e0f-11ea-8446-233862b82805.png)

**Your Configuration (please complete the following information):**
 - BookStack v0.29.0
 - PHP 7.3.16 (cli) (built: Mar 20 2020 11:26:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.16, Copyright (c) 1998-2018 Zend Technologies
 - nginx version: nginx/1.16.1

**Additional context**
- Did not try other browsers then Chrome
- Bug was found using the following Chrome Version: 
Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by ssddanbrown** [comment]
Hi @ReaHe,
Thanks for reporting this issue.
Can you please try updating your BookStack instance to the latest and see if this issue persists?

Im fairly sure I addressed this in v0.29.1 under issue #2060

**Comment by ReaHe** [comment]
I updated and its working now, apologies for submitting the ticket I will make sure to look at closed tickets next time. Thank you for getting back to me so fast!
