### ISSUE TITLE
Empty Attachment Links added

### ISSUE THREAD

**Issue by harshsyno** [BookStackApp/BookStack#2094]
**Describe the bug**
When User creates a page, while adding attachments from Attachment Manager Clicking on Attach Link without entering any details it adds a blank link, which neither can be deleted nor can be updated by User.

**Steps To Reproduce**
1. Create a Page.
2. Open Page with WYSIWYG Editor.
3. Click on Attachment Manager.
4. Go to Attach Link Tab.
5. Click on Attach
6. See in Attached Items List.

**Expected behavior**
It should not allow User to add a Blank attachment link.

**Screenshots**
![Screenshots](https://user-images.githubusercontent.com/40259154/81066582-f4e77880-8efa-11ea-801f-1a8ca0d8b9ea.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.28.3
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for reporting @harshsyno,
The way that the attachment interface is built was significantly changed in v0.30. From my testing it looks like this was fixed as part of those changes. Will therefore close.
