### ISSUE TITLE
show assigned shelfs in "book list view" and "book grid view"

### ISSUE THREAD

**Issue by Knaui** [BookStackApp/BookStack#2096]
currently there is no way to see which shelfs all books are assigned to.

would be very helpful if  "book grid view" would include not only the "create date" etc. but also would show the assigned shelfs below each book.

dunno the best way to do it in "book list view" - maybe in the same line as the book title?

btw. it is a very good feature that a book can be assigned to several shelfs at once and i strongly suggest to keep it that way!

**Comment by ssddanbrown** [comment]
Hi @Knaui,

Thanks for the suggestion.
I wouldn't really want to include shelves within a book item (grid or list item) as it does not work metaphorically (The shelves are not inside the book, it's the reverse) and it would not match the navigational structure used elsewhere in the application.

The shelves list view provides a good overview of the books within shelves:

![image](https://user-images.githubusercontent.com/8343178/86059395-9225df80-ba5a-11ea-97d7-6e18b33fcbdd.png)

Additionally the shelves for a single book can be viewed in the sidebar, when viewing a specific book.

**Comment by ssddanbrown** [comment]
Since there has been no further opinion or conversation on this I'll close it off.
