### ISSUE TITLE
pasting content from a webpage using dark theme results in white background 

### ISSUE THREAD

**Issue by Knaui** [BookStackApp/BookStack#2097]
copy content from a webpage (white background, black text color) to a page in bookstack
and save

the resulting page in bookstack shows white bars with the black text instead of changing the text color to grey or white and showing the page with a black background as intended

tested with BookStack version v0.29.0

**Comment by ssddanbrown** [comment]
Hi @Knaui,

Could you provide an example of a source website that causes this for you?
Would also be great to confirm what browser/operating system you're using.

**Comment by ssddanbrown** [comment]
Since no further information was provided I'll close this off.
