### ISSUE TITLE
UI Improvements to Reset Password page

### ISSUE THREAD

**Issue by AbijeetP** [BookStackApp/BookStack#210]
### For Feature Requests
Desired Feature: UI Improvements to Reset Password page 

### For Bug Reports
PHP Version: PHP 5.6.24-0+deb8u1

MySQL Version: MariaDB 10.0.x

Expected Behavior:

1. No confirmation of ending of process.
2. No link back to login page.

Actual Behavior:

1. Reset Password confirmation - Clicking on Send Reset Link causes the page to submit, but no confirmation is displayed to the user informing that a mail was sent or that the processing has ended.
2. Needs a link back to the login page.

**Comment by ssddanbrown** [comment]
Thank you for finding this issue. It is now fixed as of release [v0.12.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.12.2).

**Comment by Abijeet** [comment]
@ssddanbrown  - Testing this on demo leads me to an error on clicking on **Send Reset Link**.

**Comment by ssddanbrown** [comment]
@Abijeet On demo.bookstackapp.com? If so then yeah, I hadn't configured the emails sends properly. :scream:  Now set to just log upon mail so should not error.

**Comment by Abijeet** [comment]
@ssddanbrown  - Yup on demo.bookstackapp.com. Only logging, makes sense.
