### ISSUE TITLE
LaTeX mathematical symbols support

### ISSUE THREAD

**Issue by bo-ke** [BookStackApp/BookStack#2103]
I can't write LaTeX mathematical symbols in BookStack with WYSYWIG editor 
and Mathematic Fomulars in Markdown is not worked in BookStack too

this function is very important！

**Comment by whu-SpongeBob** [comment]
refer: https://github.com/BookStackApp/BookStack/issues/495

**Comment by ssddanbrown** [comment]
Thanks for the request, I'm going to close this off as a duplicate though since I feel this is already covered by #495 and #639
