### ISSUE TITLE
Code Blocks in Wysiwyg editor mode

### ISSUE THREAD

**Issue by nickbe** [BookStackApp/BookStack#2106]
How do I create a code block in the standard wysiwyg editor? There doesn't seem to be a button for this.

**Comment by mikeyz24** [comment]
The code block should be in the "Formats" menu.
![image](https://user-images.githubusercontent.com/43043830/81333528-c096c800-9072-11ea-8302-872d15e3bd4d.png)

**Comment by nickbe** [comment]
🤦‍♂️ I didn't even look there. Thanks. I thought this would be a standalone button.

**Comment by ssddanbrown** [comment]
:+1:  Will therefore close this now the option has been found. Thanks for responding on this one @mikeyz24.

Extra tip: We [have shortcuts](https://www.bookstackapp.com/docs/user/wysiwyg-editor/) for all the main formatting options so you can use `Ctrl+E` or `Ctrl+7` as quicker ways to insert code.

**Comment by NextBlaubeere** [comment]
Hi. With the recent updates it isn't there anymore, and I am not able to find it either. :-(

![Bildschirmfoto 2022-04-03 um 13 06 49](https://user-images.githubusercontent.com/10467690/161424856-6283892d-4254-44f2-97a8-f215b7e25a42.png)

**Comment by ssddanbrown** [comment]
@NextBlaubeere Please see #3310
