### ISSUE TITLE
Dark mode results in "Whoops, looks like something went wrong."

### ISSUE THREAD

**Issue by mattstanyon-tall** [BookStackApp/BookStack#2108]
**Describe the bug**
When clicking the Dark Mode button, the following message is displayed:
Whoops, looks like something went wrong.

**Steps To Reproduce**
1. Click Dark Mode

**Expected behavior**
Awesomeness in the form of Dark Mode to appear before my eyes.

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.2
 - PHP Version:PHP 7.2.24-0ubuntu0.18.04.4 (cli)
 - Hosting Method (Nginx/Apache/Docker): Apache2

**Additional context**
Can't see anything in the laravel.log....

**Comment by ssddanbrown** [comment]
Hi @mattstanyon-tall,
This sounds rather odd. Unfortunately the whoops message does not give any clues by itself. Could you follow this guide to enable debugging mode and let me know if you get any extra info:
https://www.bookstackapp.com/docs/admin/debugging/

Remember to turn debugging mode off straight after getting the message.

**Comment by mattstanyon-tall** [comment]
Nothing gets reported in storage/logs/laravel.log with debugging on, and then when I get the Dark Mode link....

At a loss with this one.

**Comment by ssddanbrown** [comment]
With debugging on does the error message seen have any more information? You should see a fair bit more than the default "Whoops, looks like something went wrong." message.

**Comment by mattstanyon-tall** [comment]
/var/www/bookstack/.env
# Enable application debugging
APP_DEBUG=true

/var/www/bookstack/app/Config/app.php
'debug' => env('APP_DEBUG', true),

Still I get the same Whoops, looks like something went wrong and nothing in the log.

The only thing I can find is in the Apache2 log:
172.16.0.20 - - [18/May/2020:08:31:27 -0400] "POST /settings/users/toggle-dark-mode HTTP/1.1" 405 879 "https://domain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"

Anything else I can try?

**Comment by ssddanbrown** [comment]
Hmmm. That error seems to imply the route cannot be found.
Additionally, you should be getting a debug view instead of the whoops message.

Could you confirm:
1. You've done a `composer install` after updating and there were no major errors during that process.
2. Whether you've ever cached routes or config. You can check this by seeing if there are any `.php` files in the `bootstrap/cache` directory.

**Comment by mattstanyon-tall** [comment]
Deleted the contents of /bootstrap/cache, and it's now working.
Thanks very much for your help with this.
