### ISSUE TITLE
`composer install` raise ErrorException tempman(): file created in the system's temporary directory

### ISSUE THREAD

**Issue by dschiller** [BookStackApp/BookStack#2109]
**Describe the bug**
Installation fails.

**Steps To Reproduce**
```
c:\>git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch
Cloning into 'BookStack'...
remote: Enumerating objects: 212, done.
remote: Counting objects: 100% (212/212), done.
remote: Compressing objects: 100% (177/177), done.
remote: Total 26583 (delta 50), reused 148 (delta 32), pack-reused 26371
Receiving objects: 100% (26583/26583), 15.02 MiB | 8.76 MiB/s, done.
Resolving deltas: 100% (18552/18552), done.

c:\>cd BookStack

c:\BookStack>composer install --no-dev


  [ErrorException]
  tempnam(): file created in the system's temporary directory



c:\BookStack>
```

**Expected behavior**
Should get installed properly

**Screenshots**
![image](https://user-images.githubusercontent.com/3144986/81455471-9b4bac00-918f-11ea-9276-a6dc202c667d.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): Can not find any Settings Folder or File; only a `version` file with `v0.29.2`
 - PHP Version: 7.4.2
 - Hosting Method (Nginx/Apache/Docker): IIS

**Additional context**
None

**Comment by dschiller** [comment]
*Solution:* execute the Commandline not as Administrator:

![image](https://user-images.githubusercontent.com/3144986/81455852-bcf96300-9190-11ea-886d-cea8f2ea9cc0.png)

**Comment by ChaarH** [comment]
A LOT OF THANKS FOR YOU! I lost three days to resolve this bullshit.

**Comment by dschiller** [comment]
Hey Carlos sorry to hear that. I didn't want to waste your time. Sorry!
