### ISSUE TITLE
Custom HTML head content does not apply on non logged in pages.

### ISSUE THREAD

**Issue by AbijeetP** [BookStackApp/BookStack#211]
### For Feature Requests
Desired Feature: Custom HTML head content does not apply on non logged in pages.

### For Bug Reports
PHP Version: PHP 5.6.24-0+deb8u1

MySQL Version: MariaDB 10.0.x

App Version: 0.12.1

Expected Behavior:

Custom HTML head content does not apply on non logged in pages.

Actual Behavior:

Custom HTML head content SHOULD apply on non logged in pages. There should at-least be a choice to do so.

Please close if this has been reported before.

PS. 

Maybe we should add application version in the issue template?

**Comment by ssddanbrown** [comment]
Thank you for finding this issue. It is now fixed as of release [v0.12.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.12.2).
