### ISSUE TITLE
Restricted books visible in list view

### ISSUE THREAD

**Issue by Usinouv** [BookStackApp/BookStack#2111]
**Describe the bug**
On the shelf view, in list view, it is possible to see all the books, including the ones you can't access.
However, the home screen displays only the good books.

**Steps To Reproduce**
1. Giving restricted rights to a book
2. Login with a user with restricted rights
3. Click on "Shelves" from any page or add /shelves to the site url.
4. Switch to list view

**Expected behavior**
Only authorized books should be visible whatever the view.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.2
 - Hosting Method (Nginx/Apache/Docker): Docker - LinuxServer

**Comment by ssddanbrown** [comment]
Thank you very much @Usinouv for reporting this security issue and apologies such a vulnerability existed. 

I have just released v0.29.3 to cover this:
https://github.com/BookStackApp/BookStack/releases/tag/v0.29.3

And have published a security advisory here:
https://github.com/BookStackApp/BookStack/security/advisories/GHSA-c32x-84w6-5mxq
