### ISSUE TITLE
Book-wide links and attachments that can be referenced on pages

### ISSUE THREAD

**Issue by vic-t** [BookStackApp/BookStack#2112]
When creating a new book, I always find myself adding a page with the name "Links". It's where I keep the most important bookmarks that are relevant to the information in the book. 

Unfortunately, there is not much I can do with this collection of links, for Bookstack it's really just another page. And if I then write a page that refers to one of these links, I have to create a new reference within the page. At this point, the information becomes redundant. If I refer to the same link on multiple pages, it may get even worse. 

Like in a real book, it would be great to be able to create a global table of references. I would love to have the opportunity to build one single list/table of links that I can then freely reference from any page within the book, for example using so called endnotes or footnotes. Vice versa, it would be nice to be able to go back and find all the places where a link or file is referenced. 

Bookstack currently allows to add links and file attachments to pages but they can't be referenced (except manually copy pasting the internal link). There have been other feature requests that addressed this already. Mine goes a bit further than that since I would prefer to (also) have the possibility to define a global list of links and attachments that I can reference on any page in the book. 

This may be rather difficult to implement, at least there is no quick fix for sure, so there is another suggestion I'd like to make as a temporary alternative. Once it becomes possible to create references to links in pages, it would be great if it was possible to have one book-wide, system created page that is basically an automatic report, collecting all links from all pages and linking back to their respective citations. This would basically be the read-only version of what I described above. Not the same but helpful none the less.

**Comment by ssddanbrown** [comment]
Thanks for the request, but I'm going to go ahead and close this off since it'd be substantial to specifically support a feature around this, while this has had no extra demand.

> ..., it would be great to be able to create a global table of references. I would love to have the opportunity to build one single list/table of links that I can then freely reference from any page ... it would be nice to be able to go back and find all the places where a link or file is referenced.

 You could have a specific page designated for this, with headers to define sections for attachments/links or whatever, then link to that from other pages. As of recent releases, out references system would then track/display links from pages to that designated page.
