### ISSUE TITLE
Text not rendering properly in the "Recently updated card"

### ISSUE THREAD

**Issue by rakeshdas1** [BookStackApp/BookStack#2114]
**Describe the bug**
I have a page in one of my books that has the following text: `Authy -> AndOTP`. For some reason, when I save the page and go back to my Bookstack home page, the page shows up in the "Recently Updated Pages" card, but the text in the recently updated section doesn't render properly, it shows the escaped character for the greater than sign: `Authy -&gt; AndOTP`. Looks like when the text is retrieved from the DB, the escape characters aren't accounted for properly.

**Steps To Reproduce**
1. Create a page with a less than or a greater than sign near the beginning of the page.
2. Go back to Bookstack homepage.
3. Look at the "Recently Updated Pages" card and see that the less than and/or greater than sign isn't rendered properly.

**Expected behavior**
The text in the "Recently Updated Pages" card should properly render the greater than sign and read out `Authy -> AndOTP`.

**Screenshots**
My page looks like this:
![image](https://user-images.githubusercontent.com/6901641/81582089-3a7dc880-9375-11ea-9260-0d1fefb79c91.png)

The "Recently Updated Pages" card looks like this:
![image](https://user-images.githubusercontent.com/6901641/81582167-508b8900-9375-11ea-91d0-1d3b8f6f96aa.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.29.0
 - PHP Version:  7.3.16
 - Hosting Method (Nginx/Apache/Docker): Docker

**Comment by ssddanbrown** [comment]
Thanks for reporting @rakeshdas1.
Can confirm this issue exists, Likely just where we're scraping the text from the HTML but not decoding the HTML entities. Should be an easy fix but will need testing.

**Comment by rakeshdas1** [comment]
Sounds good, thanks Dan! Please let know if you guys need help testing.

**Comment by TheAmigo** [comment]
FYI: the HTML entity names also show when viewing the list of pages in a book.  Hopefully the fix covers both cases.

![image](https://user-images.githubusercontent.com/4148739/93258488-ff950280-f763-11ea-91ba-bb37ce58f065.png)

**Comment by ssddanbrown** [comment]
Thanks to @mr-vinn this now has a fix ready to be part of the next release, Hence this issue is now closed.

Note, You will need to re-save a page with changes for the updates to take affect to a page excerpt.
