### ISSUE TITLE
Deny View Access to certain pages or chapters?

### ISSUE THREAD

**Issue by mikeyz24** [BookStackApp/BookStack#2117]
Is it possible to deny a user view access to certain chapters or pages while being able to view other chapters or pages within a book?  With my testing, it seems like I can only allow users to view all or view none.  
I'm trying to mimic the behavior of ABE (Access-based Enumeration) in NTFS when it comes to who can view what within a book.
Does anyone have some tips or workarounds on getting this type of behavior work?

**Comment by ssddanbrown** [comment]
Hi @mikeyz24,
BookStack has role-based-access that can be applied per shelf/book/chapter/page. Permissions set upon books & chapters will cascade to child items, unless they have their own permissions set.

To configure this you can just view any of those items and you should see "Permissions" under actions. You'll then get a view like this:

![image](https://user-images.githubusercontent.com/8343178/81980354-5c51a680-9626-11ea-8b1f-3c402b0452b5.png)

**Comment by mikeyz24** [comment]
How do I deny access to users to certain chapters or pages while allowing them to view other chapters/pages within a book/chapter?  There is no check box to mark as "deny".

**Comment by ssddanbrown** [comment]
@mikeyz24 Unchecked is essentially "deny". If you only checked the top "Enable Custom Permissions" checkbox and no others, then only users of the original built-in admin role would be able to view/create-within/update or delete that item.

**Comment by mikeyz24** [comment]
@ssddanbrown Thanks for the explanation, I understand how this works now.
