### ISSUE TITLE
Unable to edit page contents - Can edit page title

### ISSUE THREAD

**Issue by ShowMeIT** [BookStackApp/BookStack#2119]
**Describe the bug**
I can create a new page and edit the title of a page but not the page contents  (I am an admin user)

**Steps To Reproduce**
1. Go to any book
2. Click on new page
3. Try and edit page contents
![Edit Error1](https://user-images.githubusercontent.com/51915383/81915432-e9403400-9615-11ea-947a-f82b2dd7df74.png)
![Edit Error1](https://user-images.githubusercontent.com/51915383/81915456-f2310580-9615-11ea-82fe-bb1f40beed0e.png)

**Expected behavior**
I would expect to be able to edit page contents as well as Title

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.29.1
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): CPANEL (Apache)

**Additional context**
It will allow you to save the page but no edit tools or page contents are visible. Screenshot is of page after the edit button. 
I have tried from multiple users, different shelves and different books.

**Comment by ssddanbrown** [comment]
Hi @ShowMeIT,
Do you see this issue on the demo instance here?:
https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site

**Comment by ShowMeIT** [comment]
Hi,

Issue does not show on demo instance – when I click edit on demo I get the full edit screen with toolbar and can make changes (screenshot attached).

I’ve installed my instance following this guide:

https://www.warpconduit.net/2019/11/16/installing-bookstack-wiki-on-cpanel-shared-hosting/#more-915

I was able to edit successfully after installing.

And then I have updated to v0.29.1 following https://www.bookstackapp.com/docs/admin/updates/

As part of the install the /public folder of bookstack is copied to public_html/bookstack  - will this have implications for updating and possibly cause the issue I’m experiencing?

Thanks,
Andrew.

**Comment by ssddanbrown** [comment]
> As part of the install the /public folder of bookstack is copied to public_html/bookstack  - will this have implications for updating and possibly cause the issue I’m experiencing?

The guide followed makes multiple steps, including the copying of the public folder, which could cause issues when updating. The folder structure is no longer what is expected and `git` may not know how to apply changes upon the changes you have made. 

You might want to run `git status` to show the current state of the files. You might get away with updating your public folder content, that you copied, with the latest app content. 

You may have to discard some changes, then repeat some of the steps in that guide again.
Backup all files for your install before doing any of the following (At your own risk) but you should be able to reset the bookstack files by running `git reset --hard` within your install folder. Then you can re-run the update steps. You'll then need to re-apply the custom changes done in that guide and re-copy the public folder.

**Comment by ShowMeIT** [comment]
Hi @ssddanbrown,
Thanks for the response - I will give it try and let you know..

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
