### ISSUE TITLE
Searching with " - " at the end of the string causes application to barf

### ISSUE THREAD

**Issue by AbijeetP** [BookStackApp/BookStack#212]
### For Bug Reports
PHP Version: PHP 5.6.24-0+deb8u1
MySQL Version: MariaDB 10.0.x
App Version: 0.12.1

#### Expected Behavior:
In the top search bar, search with a term that ends with a ` - `. It should show entities that contain or end with ` - `. Search term example  - `actual -`. Note the space before "-".

#### Actual Behavior:
Application barfs and throws a "Whoops, looks like something went wrong.".

#### REQUEST URL
```
/search/all?term=asdasda+-+
```

**Comment by ssddanbrown** [comment]
Thank you for finding this issue. It is now fixed as of release [v0.12.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.12.2).
