### ISSUE TITLE
[Feature Request] Allow user logins with usernames

### ISSUE THREAD

**Issue by Skyler-Altol** [BookStackApp/BookStack#2122]
**Describe the feature you'd like**
Allow usernames to be used to login to BookStack, as well as emails.

**Describe the benefits this feature would bring to BookStack users**
Saves users time when logging in, typing out a full email address takes far longer than a regular username.

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Thanks for your request @Skyler-Altol.

Since this is effectively already requested in #1498 I'll be closing this off as a duplicate.
