### ISSUE TITLE
Bulgarian translate 

### ISSUE THREAD

**Issue by Oredna** [BookStackApp/BookStack#2124]
I want to translate the web app to Bulgarian, can you open new so I can start.

**Comment by ssddanbrown** [comment]
Thank you very much @Oredna for offering to translate this into Bulgarian,
I have added bulgarian to the supported language list on crowdin here:
https://crowdin.com/project/bookstack/bg#

If you change your mind just let me know and I'll remove it again. Otherwise I'll close this off.
