### ISSUE TITLE
Spoiler Blocks

### ISSUE THREAD

**Issue by mflagler** [BookStackApp/BookStack#2130]
**Describe the feature you'd like**
Add a formatting style for "spoilers" or anything that should be hidden by default but can be toggled between hidden and visible by clicking on it.

**Describe the benefits this feature would bring to BookStack users**
Would allow users to put mildly sensitive information in BookStack so that anyone looking over your shoulder doesn't see it. For instance it could be for common shared passwords for WiFi or any other password where encryption and security are not as important but just ease of letting those with permissions to the page to view the content. This would allow a page to have instructions on how to do a task and include the password but require them to click a toggle of some sort to view the password without it being openly visible by default.

**Additional context**
I think this could be done with simple CSS and/or JS but would like it to be a simple format from the dropdown menu so anyone could do it easily.

**Comment by ssddanbrown** [comment]
Thanks for the request @mflagler.

Although for a different use case, I think this would be covered by #78. Therefore, I'll likely close this off unless:

- This can be done via an alternate semantic HTML element.
- There's a strong case why collapsible content blocks would not be suitable for the requested purpose.

**Comment by ssddanbrown** [comment]
Will therefore close this off.
