### ISSUE TITLE
Broken image URL's when switching from https to https

### ISSUE THREAD

**Issue by JHenneberg** [BookStackApp/BookStack#2131]
**Describe the bug**
Broken image URL's when switching from `http` to `https`

**Steps To Reproduce**
1. insert image in bookstack
2. change the `APP_URL` from `http` to `https` or vica versa
3. image url is broken because switch from `http` to `https` is neglected

**Expected behavior**
adjusting the urls of images automatically depending on `APP_URL`

**Your Configuration (please complete the following information):**
 - Exact BookStack Version : 29.1
 - PHP Version: 7.4.5
 - Hosting Method (Nginx/Apache/Docker): Docker

**Comment by ssddanbrown** [comment]
Hi @JHenneberg,

There is a built-in command that can be used for this scenario:

```bash
# Update a URL in the database content of your BookStack instance.
# Searches for <oldUrl> and replaces it with <newUrl>
php artisan bookstack:update-url <oldUrl> <newUrl>
# Example:
php artisan bookstack:update-url http://docs.example.com https://demo.bookstackapp.com
```

**Comment by JHenneberg** [comment]
Hey, yeah it's written in the documentary as well. Thank you.
