### ISSUE TITLE
419 after successful login when using memcached

### ISSUE THREAD

**Issue by Totn** [BookStackApp/BookStack#2136]
**Describe the bug**
After Install the site，I change the session_driver to "memcached",
and using the defaut acount "admin@admin.com" to login，login success but the page show  "419|Page Expired", I have checked the memcached  and find that have no one value of the site。
When I change the session_dirver back, the login is OK,
 
So why my site can't drive memcached ? I have double check the memcached configure is correct.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):  branch release,  v0.29.3
 - PHP Version: 7.2.30
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Additional context**
libmemcached version => 1.0.18
memcached_host: 127.0.0.1:11211

**Comment by MoriarT3a** [comment]
I've this problem if I try to open bookstack with my mobile phone. On my desktop bookstack works very well...

**Comment by ssddanbrown** [comment]
@MoriarT3a Are you also using the memcached session driver?

**Comment by MoriarT3a** [comment]
Nope. I don't know what I've done. But it works now. Maybe a problem in my dockercontainer....
Sorry can't help you.

**Comment by EpicFail113** [comment]
I have this same issue after upgrading, I have been looking where to find the .env file to change the session_driver but I have had no luck.

**Comment by EpicFail113** [comment]
> I have this same issue after upgrading, I have been looking where to find the .env file to change the session_driver but I have had no luck.

From Discord I ran `php composer.phar install --no-dev` with no luck but then I ran the update command once more and then the clear cache command and I was able to log back in without issue.

**Comment by Totn** [comment]
I think  i got the cause;
When the Memcached service is unavailable, laravel's session writing will fail without reporting an error,
resulting in responding 419 where logging in;

**Comment by leopendas** [comment]
I have the same issue when trying to restore a backup; @Totn could you share more details for fixing this issue?
@EpicFail113 which is the update comand you run? apt update?
 thanks in advance!

**Comment by EpicFail113** [comment]
@leopendas I think what I did was elevated terminal with 'sudo su' and then ran the 'git pull origin release && composer install --no-dev && php artisan migrate' command.

**Comment by tacerus** [comment]
I encounter this as well when using `memcached`. Is there a solution or should I open a new issue?

**Comment by tacerus** [comment]
Turns out, the user my BookStack PHP FPM process was running under did not have read/write access to the memcache socket. I wonder why this is not being logged as an error by Laravel.
