### ISSUE TITLE
BUG: LDAP Auth fails  to AD --v0.29.3

### ISSUE THREAD

**Issue by mikebohlen** [BookStackApp/BookStack#2137]
Argument 1 passed to BookStack\Auth\Access\LdapService::validateUserCredentials() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in 
bookstack\app\Auth\Access\Guards\LdapSessionGuard.php on line 78

**Comment by ssddanbrown** [comment]
Hi @mikebohlen,

Do you still get this issue? When exactly does this issue occur? And detail on how to replicate would be much appreciated.

**Comment by mikebohlen** [comment]
Anytime anyone tries to sign on.  I have tried this with AD and a *STD x.500 LDAP both secured\unsecured  same issue, just fyi, I adjusted the search strings etc to match the LDAP server I was trying to auth. to, same issue each time with same error.

**Comment by tiredofit** [comment]
Hi @mikebohlen I'll try to handle LDAP queries for a bit here. Can you send some logs from your LDAP server, or share your .env LDAP configuration (sanitized?)

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
