### ISSUE TITLE
Bug: Importing a drawing from browser causes console error/blank popup

### ISSUE THREAD

**Issue by sburkett** [BookStackApp/BookStack#2140]
**Describe the bug**
Running v0.29.3 ... Trying to import from the browser in the drawing editor doesn't work. You get a blank popup and a console error.

**Steps To Reproduce**
1. Start editing a wiki page
2. Click on the drawing editor icon in the WYSIWYG editor
3. When the editor loads, select FILE, IMPORT FROM BROWSER

**Expected behavior**
Not sure, as it never gets that far :)

**Screenshots**

![image](https://user-images.githubusercontent.com/2219483/83284235-76ed5900-a1aa-11ea-8f44-2ce69371b4e8.png)

**Your Configuration (please complete the following information):**
 - v0.29.3
 - PHP Version: 7.3.18
 - Apache

**Additional context**
None

**Comment by ssddanbrown** [comment]
Have given this a test on Firefox and Chrome, Looks like it may have been an issue on the diagrams.net side which has since been resolved; The popup now displays (Albeit without any files). Will therefore close this off.
