### ISSUE TITLE
Support for Azure AD groups

### ISSUE THREAD

**Issue by coaqii** [BookStackApp/BookStack#2146]
**Describe the feature you'd like**
The ability to assign Azure AD groups permissions within Bookstack and on shelves, books and pages.

**Describe the benefits this feature would bring to BookStack users**
This way user management is from a single admin portal instead of groups within AD and groups within Bookstack.

I don't know exactly how to do this, possibly use the enterprise application to get certain selected groups with members and sync them that way as regular bookstack groups.

**Comment by ssddanbrown** [comment]
Hello @coaqii,

Are you using AzureAD as a social login option for BookStack, or are you using AzureAD via the LDAP or SAML2 option?

**Comment by coaqii** [comment]
Hi,

I'm using the social login option. We cannot utilize the LDAP option, would SAML2 be better for this?

**Comment by tiredofit** [comment]
SAML2 exporting your groups as an attribute would be your best bet to get the groups in a text-format.
Try setting `SAML2_DUMP_USER_DETAILS=true` in your .env file and share a sanitized version of a user authorization and I'll try to solve.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old, and since advanced group logic on social logins is not something I'd be immediately looking to support, I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
