### ISSUE TITLE
Multi-Instance

### ISSUE THREAD

**Issue by Shackelford-Arden** [BookStackApp/BookStack#215]
### For Feature Requests

Desired Feature:
If this is already here somewhere, I couldn't find it. Personally, I'd like to see some instructions of how to install multiple instances of Bookstacks on one webserver (Apache). Having multiple instances is something that I could find useful if I wanted to have my own personal wiki, one for work, one for everyone.

Or if anything, a portion of the installation instructions you already have to have a list of things to watch out for or to consider when trying to run multiple instances.

Still new to Docker, but I believe this would enable one to do this, however for those of us, like myself, who are not familiar with docker, a non docker method would be awesome!

**Comment by ssddanbrown** [comment]
Hi @Shackelford-Arden,

When it comes to multiple instances you can set this up fairly simply without the use of docker. You will just need to have multiple, separate BookStack setups on the single machine and use Apache virtual hosts to point to these instances.

As long as you keep them separate there's nothing really to look out for, Apart from having to maintain more than one instance.

Documenting this will be more about Apache/Nginx configuration but, if it will be useful, it'll still be handy to document I suppose. I'll mark it on the todo to document.

**Comment by Shackelford-Arden** [comment]
@ssddanbrown Thanks! I mean, from what it sounds like I did what you proposed a few weeks ago but it didn't work? I'll see if I can't test it tonight and see if I can get it up and running using the virtual hosts. I'll post back here when I've got something.

**Comment by Shackelford-Arden** [comment]
@ssddanbrown Following the same instructions as the first installation, I get the following error:

https://gyazo.com/eefbbb9d7ca6cf20cbd0e5c780bfdb22

"The requested URL /login was not found on this server."

I'd seen this a few times, but just wiped everything before and this seemed to go away after a couple attempts. Not sure if this is specific to already having an instance installed or something else.

**Comment by ssddanbrown** [comment]
Hi @Shackelford-Arden, Sorry it's so late but I've created some documentation on multiple instances here:
https://www.bookstackapp.com/docs/admin/multi-instance

If you are still trying to attempt multi-installation compare your setup with the instructions to see if there's any obvious differences otherwise post your apache config, if possible,  for both instances you've set up and I'll see if I can find the issue.

Regards,
Dan

**Comment by Shackelford-Arden** [comment]
@ssddanbrown I'll check this out and let you know if I run into any issues. Thanks for adding this to your docs! 👍

**Comment by Shackelford-Arden** [comment]
@ssddanbrown Sorry it took me a while to get back to you on this. I've got it working with multi-instance non docker! I'm quite the happy camper right now!

I'll go ahead and close this issue. Thanks for the documentation!

**Comment by ssddanbrown** [comment]
@Shackelford-Arden No worries! Glad to hear you got a multi-instance setup going!
