### ISSUE TITLE
Add option to set default shelves view 

### ISSUE THREAD

**Issue by sesipod** [BookStackApp/BookStack#2152]
Can we have an env value to set the default shelves view? There is already one for books and that is super nice.

This would provide extra customization to the platform.

**Comment by ssddanbrown** [comment]
Hi @sesipod,

You should be able to set the following `.env` option like so:
```bash
APP_VIEWS_BOOKSHELVES=grid
```

As can be found here: https://github.com/BookStackApp/BookStack/blob/master/.env.example.complete#L251
