### ISSUE TITLE
Dark mode decreases performance

### ISSUE THREAD

**Issue by maderschramm** [BookStackApp/BookStack#2154]
**Describe the bug**
Using Safari on macOS 10.15 I am experiencing massive slowdowns using Dark Mode - especially when trying to link pages, but also when scrolling normally.

The issue is mostly remediated with other browsers, but is still somewhat present.

**Steps To Reproduce**
1. Turn on Dark Mode
2. Attempt to link a page - scrolling is especially bad.

**Expected behavior**
Performance should be the same regardless of which theme is enabled - light or dark.

**Screenshots**
See the below .gifs:

Links in Dark Mode:
![darklinks](https://user-images.githubusercontent.com/2058120/84344781-a3757d80-ab79-11ea-8987-bee61847a49c.gif)

Links in Light Mode:
![lightlinks](https://user-images.githubusercontent.com/2058120/84344855-d0299500-ab79-11ea-82a8-1f9bcdc3943b.gif)

Scrolling in Dark Mode:
![scrollingdark](https://user-images.githubusercontent.com/2058120/84344888-eb94a000-ab79-11ea-98b6-53dc7500a04d.gif)

Scrolling in Light Mode:
![lightscroll](https://user-images.githubusercontent.com/2058120/84344934-06ffab00-ab7a-11ea-87e5-9d5329712998.gif)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.29.3
 - PHP Version: PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
macOS 10.15.5
Safari Version 13.1.1 (15609.2.9.1.2)

**Comment by ssddanbrown** [comment]
Thanks for reporting @maderschramm, I'll try and have a look for the next release. Is likely some css filters we're using in dark mode causing trouble.

**Comment by ssddanbrown** [comment]
Thanks again for reporting @maderschramm.

Found this same thing in my testing on my mac mini test machine. Unfortunately I could not find the exact cause, Did not seem to be the filters alone. I did find that when the editor was forced onto its own rendering layer performance would greatly improve. 

Changes will be part of v0.30. If you still have performance issues after that release please feel free to open a new issue, referencing this one and we'll debug further.
