### ISSUE TITLE
Change Search Syntax in Bookstack

### ISSUE THREAD

**Issue by gonetab23** [BookStackApp/BookStack#2158]
Hello,
is there a way to change the standard search Syntax in BookStack?
For example I want to change the syntax for Normal Search and Exact Search.

Thank You.

**Comment by ssddanbrown** [comment]
Hi @gonetab23,
The search syntax is currently not configurable and there are no current plans to make it configurable.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
