### ISSUE TITLE
Class 'Permissions' not found

### ISSUE THREAD

**Issue by jq-yeraz** [BookStackApp/BookStack#2159]
After a simple update from 26.2 to 29.3, I have the error :

```
laravel.ERROR: Class 'Permissions' not found {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Permissions' not found at /var/www/wiki.mgmt.yeraz.fr/app/Entities/Page.php:35)
```

**My Configuration**
BookStack : 29.3
PHP : 7.2.6
Hosting : NGINX

**Comment by MikeyMJCO** [comment]
Did you check file permissions?

**Comment by jq-yeraz** [comment]
Yes. All files are owned by the NGINX user, I have double check. It's not the only class, it can't find "Str".

**Comment by jq-yeraz** [comment]
I have deleted the vendor folder... and rerun composer same issue.

**Comment by ssddanbrown** [comment]
Hi @jq-yeraz, Did you get this fixed? I see that the instance is now live on 29.3. 

If not, Can you confirm if there's any errors when you run `composer install` or confirm the output of running `git status`.

**Comment by ssddanbrown** [comment]
Will close this off. If it remains to be an issue feel free to open a new issue, detailing what actions cause this error to appear in addition to responding to the questions in my previous comment.

**Comment by Nico207** [comment]
Hi,

I also have this error after an upgrade from V0.27.5 to V0.29.3 (Ubuntu 18.04.3 / PHP 7.2.24 / Laravel 6.18.3 / Apache)

![image](https://user-images.githubusercontent.com/1179972/88174857-42839f80-cc25-11ea-872b-b00d4adcb233.png)

Files permission is OK

`composer install` return no error (maybe a warning about abandoned package)

```
Package operations: 51 installs, 0 updates, 0 removals
  - Installing maximebf/debugbar (v1.16.1): Downloading (100%)
  - Installing barryvdh/laravel-debugbar (v3.2.9): Downloading (100%)
...
  - Installing wnx/laravel-stats (v2.0.2): Downloading (100%)
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
barryvdh/reflection-docblock suggests installing dflydev/markdown (~1.0)
barryvdh/reflection-docblock suggests installing erusev/parsedown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.7.2)
phpunit/phpunit suggests installing ext-soap (*)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0.0)
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating optimized autoload files
...
Package manifest generated successfully.
> @php artisan cache:clear
Application cache cleared!
> @php artisan view:clear
Compiled views cleared!
```

`git status` return the following

```
Sur la branche release
Votre branche est à jour avec 'origin/release'.

Fichiers non suivis:
  (utilisez "git add <fichier>..." pour inclure dans ce qui sera validé)
        .env.bak
        composer.phar

aucune modification ajoutée à la validation mais des fichiers non suivis sont présents (utilisez "git add" pour les suivre)
```

**Comment by BirenGrooveHere** [comment]
Hi all, I also get the same error  does anyone fixed it, 

[`Mon Feb 15 04:01:35.089378 2021] [:error] [pid 25130] [client 106.11.158.44:26498] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to undefined function BookStack\\Translation\\theme_path() in /var/www/bookstack/app/Translation/FileLoader.php:23\nStack trace:\n#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(324): BookStack\\Translation\\FileLoader->load('en', 'errors', '*')\n#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(240): Illuminate\\Translation\\Translator->load('*', 'errors', 'en')\n#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(125): Illuminate\\Translation\\Translator->getLine('*', 'errors', 'en', 'error_occurred', Array)\n#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(101): Illuminate\\Translation\\Translator->get('errors.error_oc...', Array, 'en')\n#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(884): Illuminate\\Translation\\Translator->trans('errors.error_oc...', Array, NULL in /var/www/bookstack/app/Translation/FileLoader.php on line 23`

**Comment by ssddanbrown** [comment]
@BirenGrooveHere Please see #2196 and follow the comment chain there to see if that helps
