### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by devin42r** [BookStackApp/BookStack#216]
Hey I'm a little new to development and linux.  I've followed the installation docs as best as I could follow (except for the email because I'm a little confused how that works) and I am just getting text when I load localhost.  _/ /_ |-------------------------------------------------------------------------- | Register The Auto Loader |-------------------------------------------------------------------------- | | Composer provi  etc.

I'm also getting error  [PDOException]  
  could not find driver
on artisan migrate

My phpinfo is working and I have a database and user created.  Where am I going wrong?

**Comment by ssddanbrown** [comment]
Hi @devin42r,
It looks like your webserver is not parsing PHP files and is simply serving them as text (Since what you provided is the content of the main php file).

What webserver are you using? Apache or Nginx or something else?

Also, What variant and version of linux are you using?

**Comment by devin42r** [comment]
Hey Dan thanks for the quick response.  I am using apache2 on kubuntu 16.  The info.php file I have created in the same directory that renders php is displaying desired php config info.

**Comment by devin42r** [comment]
hmm, except for info.php which is owned by root.  Is there some way that www-data would not be able to utilize php?

drwxrwxr-x  8 www-data root  4096 Oct 24 22:29 ./
drwxrwxr-x 13 www-data root  4096 Oct 24 18:42 ../
drwxrwxr-x  2 www-data root  4096 Oct 20 21:22 build/
drwxrwxr-x  2 www-data root  4096 Oct 20 21:22 css/
drwxrwxr-x  2 www-data root  4096 Oct 20 21:22 fonts/
drwxrwxr-x  2 www-data root  4096 Oct 20 21:22 js/
drwxrwxr-x  8 www-data root  4096 Oct 20 21:22 libs/
drwxrwxr-x  2 www-data root  4096 Oct 20 21:22 uploads/
-rw-rw-r--  1 www-data root 10933 Oct 20 21:22 favicon.ico
-rw-rw-r--  1 www-data root   412 Oct 20 21:22 .htaccess
-rw-rw-r--  1 www-data root  1819 Oct 24 22:29 index.php
-rw-r--r--  1 root     root    20 Oct 24 20:02 info.php
-rw-rw-r--  1 www-data root 11098 Oct 20 21:22 loading.gif
-rw-rw-r--  1 www-data root  4682 Oct 20 21:22 logo.png
-rw-rw-r--  1 www-data root    24 Oct 20 21:22 robots.txt
-rw-rw-r--  1 www-data root  7405 Oct 20 21:22 user_avatar.png
-rw-rw-r--  1 www-data root  6580 Oct 20 21:22 ZeroClipboard.swf

**Comment by ssddanbrown** [comment]
@devin42r Does anything load if you go to `http://localhost/index.php` ?

Just to ensure it's the apache config that's the issue you can go to the folder containing BookStack in the terminal and run `php artisan serve` which will run a simple php server accessible at `http://localhost:8000`. See if that works. I'd imagine you'd still have errors since the database did not migrate but hopefully you'll be further along.

**Comment by devin42r** [comment]
Hmm, a blank page.  Just empty <html>, <head> and <body> tags.  Now that is all I'm getting regardless of whether I use localhost or 127.0.0.1 (with or without index.php appended).  

When I kick up the phpserver it is giving me the same on 8000.

**Comment by lommes** [comment]
What's your PHP version? How do the permissions look in the BookStack base directory? Laravel sometimes fails when it cannot access/write logs. So if the base directory (or the storage subfolder) is only writeable for root, this might be the problem.

**Comment by devin42r** [comment]
php -v
PHP 7.0.12-1 (cli) ( NTS )

**Comment by devin42r** [comment]
drwxr-xr-x  4 root     root 4096 Oct 24 19:37 .
drwxr-xr-x 15 root     root 4096 Oct 24 19:03 ..
drwxrwxr-x 13 www-data root 4096 Oct 24 18:42 BookStack
drwxr-xr-x  2 root     root 4096 Oct 24 20:03 html

**Comment by devin42r** [comment]
My base directory is a little further up ^^

**Comment by ssddanbrown** [comment]
@devin42r Could you look for any clues in the Apache logs?

Should be an error log at /var/log/apache2/error.log or a similar location.

**Comment by devin42r** [comment]
PHP Parse error:  syntax error, unexpected 'echo' (T_ECHO) in /var/www/BookStack/public/index.php on line 3

Good call Dan, I don't know why I didn't check the logs.  I had inserted a line asdfasdf and on the next line echo "asdfasdf"; trying to test earlier and forgotten.  I removed both lines (echo works if I just leave it), but now I'm facing this screen 

Whoops, looks like something went wrong.  

Nothin in apache logs for this.  I doublechecked the write permissions on respective files, re-ran, php artisan key:generate, doublechecked database user settings (and logged in from terminal), mail settings are still default, and tried to run php artisan migrate (still same error of [PDOException] could not find driver).

**Comment by ssddanbrown** [comment]
> Whoops, looks like something went wrong.

This is a good line to see. The browser request is now reaching the application. You can turn on debugging or check the logs for more information. Details to do this can be found here:
https://www.bookstackapp.com/docs/admin/debugging

**Comment by ssddanbrown** [comment]
Also, Ensure you have the `php7.0-mysql` package installed (`sudo apt install php7.0-mysql`)

**Comment by devin42r** [comment]
Awesome, I was trying all sorts of installs on mysql and sqlite as recommended on stack but the one you just provided got me another step further.  Now I'm hitting the following: 

Base table or view not found: 1146 Table 'bookstack.settings' doesn't exist (SQL: select * from `settings` where `setting_key` = app-public limit 1)

I don't understand.  Am I supposed to configure some settings in mysql?  I created my db user, db and password but is there something else?

**Comment by devin42r** [comment]
No, I forgot I needed to actually finish the php artisan migrate...now it's taking me to /login and giving me 

The requested URL /login was not found on this server.

No apache logs hmmm

**Comment by ssddanbrown** [comment]
Okay, Now it looks like an issue in the apache configuration. What is the URL you are try to access BookStack at? is it something like `http://example.com/` or are you accessing via a sub-directory like `http://example.com/BookStack/`?

If you have set up an apache virtual host for BookStack can you paste the config here? If not have you made any changes to the apache configuration while installing BookStack?

**Comment by devin42r** [comment]
I have been accessing it at localhost or 127.0... 

Hmm, dang I did make some changes earlier but can't remember.  Maybe the allowoverride.  I'll search for what the default is and try to bring it back..
`
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Allow from all
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/BookStack>
        Options Indexes FollowSymLinks
        AllowOverride All
        Order deny,allow
        Allow from all
        Require all granted
</Directory>
`

**Comment by devin42r** [comment]
sites-available/000-default.conf does have 
DocumentRoot /var/www/BookStack/public

**Comment by devin42r** [comment]
Interestingly, http://127.0.0.1/index.php/login brings me to the correct page.  I can't navigate anywhere from there.  Similar thing is happening in nginx on my amazon server (except I can't even get index.php/login to load).

**Comment by ssddanbrown** [comment]
On your apache instance, Have you run `sudo a2enmod rewrite`?

**Comment by devin42r** [comment]
Awesome that did it!  Any idea how to do the same on nginx?  From what I understand it happens with that line you guys included in the installation try_files $uri...index.php...  Here is my relevant code from nginx.conf

`server {
        listen       81 default_server;
        listen       [::]:81 default_server;
        server_name  localhost;
        root         /usr/share/nginx/bookstack/BookStack/public;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location ~ / {try_files $uri $uri/ /index.php?$args;}`

**Comment by ssddanbrown** [comment]
> Awesome that did it!

:tada: 

> Any idea how to do the same on nginx?

No obvious issues from the config you pasted. Is PHP definately all working okay via nginx?

Here's the default config I put together for the default ubuntu 16.04 install script:
https://github.com/BookStackApp/devops/blob/master/config/nginx

You can compare your config with that one. It's made for ubuntu 16.04 so for other systems it may not be correct. You'll have to ensure you have the `php7.0-fpm` package installed on your system.

**Comment by ssddanbrown** [comment]
Closing due to lack of response. Feel free to still respond to the above and I'll re-open this.

**Comment by bydox** [comment]
Hi ! I encountered the same issue (blank login page after installation) on my Debian 8 installation. I eventually found the answer. It was a permission issue. What I did is the following, while in the app folder : 

`php artisan cache:clear
chmod -R 777 storage
chmod -R 777 bootstrap/cache
chmod -R 777 public/uploads
composer dump-autoload`
[Source](http://stackoverflow.com/questions/23540083/failed-to-open-stream-permission-denied-error-laravel)

I'll tweak the permissions to not let the folders completely opened, but I got to make BookStack to work.

**Comment by devin42r** [comment]
@bydox thanks for posting.  @ssddanbrown my apologies for not getting back.  I abandoned the nginx because I was simply doing that out of curiosity.  Recently I just spun up bookstack on an ec2 server, however, and might need to throw up an issue for that for future ec2 users.  I had to open permissions to 777 as well there.  Need to figure out who is in apache group and why ec2-user was having issues even as owner and group...

**Comment by dohlin** [comment]
Hey guys, I'm having a very similar issue and was hoping I might be able to get some assistance if anyone felt so kind :) I've got a fresh install of Ubuntu 16.04, and have gone through the scripted install commands up to the nginix part, just entering applicable commands manually (pretty much all the commands but the ones that involve setting variables.

I stopped at the Nginx section as I'd like to run Apache if possible.  I've gotten that all installed but the config file is what's really throwing me for a loop.  Per this thread I've tried the permissions adjustment as noted by @bydox, have enabled apache's mod rewrite function, and tried all the different variations on URL noted above with no luck.

My apache config currently looks like this:

    <VirtualHost *:80>
	
	ServerName wiki.david-ohlin.com

	DocumentRoot /var/www/bookstack/public
	ServerAdmin webmaster@localhost

	#Options +FollowSymLinks
	#RewriteEngine On

	#RewriteCond %{REQUEST_FILENAME} !-d
	#RewriteCond %{REQUEST_FILENAME} !-f
	#RewriteRule ^ index.php [L]

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	<Directory /var/www/bookstack/public>
		AllowOverride All
		Order allow,deny
		Allow from all
	</Directory>

    </VirtualHost>

    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet

When I hit the IP of my server (or http://localhost on the server itself), I get the following:

    <?php

    /**
     * Laravel - A PHP Framework For Web Artisans
     *
     * @package  Laravel
     * @author   Taylor Otwell <taylorotwell@gmail.com>
     */

    /*
    |--------------------------------------------------------------------------
    | Register The Auto Loader
    |--------------------------------------------------------------------------
    |
    | Composer provides a convenient, automatically generated class loader for
    | our application. We just need to utilize it! We'll simply require it
    | into the script here so that we don't have to worry about manual
    | loading any of our classes later on. It feels nice to relax.
    |
    */

    require __DIR__.'/../bootstrap/autoload.php';

    /*
    |--------------------------------------------------------------------------
    | Turn On The Lights
    |--------------------------------------------------------------------------
    |
    | We need to illuminate PHP development, so let us turn on the lights.
    | This bootstraps the framework and gets it ready for use, then it
    | will load up this application so that we can run it and send
    | the responses back to the browser and delight our users.
    |
    */

    $app = require_once __DIR__.'/../bootstrap/app.php';

    /*
    |--------------------------------------------------------------------------
    | Run The Application
    |--------------------------------------------------------------------------
    |
    | Once we have the application, we can handle the incoming request
    | through the kernel, and send the associated response back to
    | the client's browser allowing them to enjoy the creative
    | and wonderful application we have prepared for them.
    |
    */

    $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

    $response = $kernel->handle(
        $request = Illuminate\Http\Request::capture()
    );

    $response->send();

    $kernel->terminate($request, $response);

And if I uncomment the lines currently commented out in my config, then I get endless Error: 400 pages when visiting the same page.  I've looked in /var/log/apache2/error.log and don't see anything helpful.  Here it is just for reference purposes:

[Sun Apr 02 19:47:19.779814 2017] [mpm_event:notice] [pid 3692:tid 140545472726912] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:47:19.779934 2017] [core:notice] [pid 3692:tid 140545472726912] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 19:47:22.617287 2017] [mpm_event:notice] [pid 3692:tid 140545472726912] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 02 19:47:22.622669 2017] [mpm_event:notice] [pid 3692:tid 140545472726912] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:47:22.622702 2017] [core:notice] [pid 3692:tid 140545472726912] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 19:52:19.882141 2017] [mpm_event:notice] [pid 3692:tid 140545472726912] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 02 19:52:19.888133 2017] [mpm_event:notice] [pid 3692:tid 140545472726912] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:52:19.888169 2017] [core:notice] [pid 3692:tid 140545472726912] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 19:52:23.011607 2017] [mpm_event:notice] [pid 3692:tid 140545472726912] AH00491: caught SIGTERM, shutting down
[Sun Apr 02 19:52:24.168871 2017] [mpm_event:notice] [pid 4387:tid 140199877764992] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:52:24.168979 2017] [core:notice] [pid 4387:tid 140199877764992] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 19:57:01.013610 2017] [mpm_event:notice] [pid 4387:tid 140199877764992] AH00491: caught SIGTERM, shutting down
[Sun Apr 02 19:57:02.115402 2017] [mpm_event:notice] [pid 4697:tid 140215810697088] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:57:02.115521 2017] [core:notice] [pid 4697:tid 140215810697088] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 19:57:05.128422 2017] [mpm_event:notice] [pid 4697:tid 140215810697088] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 02 19:57:05.136610 2017] [mpm_event:notice] [pid 4697:tid 140215810697088] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:57:05.136624 2017] [core:notice] [pid 4697:tid 140215810697088] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 19:57:25.381106 2017] [mpm_event:notice] [pid 4697:tid 140215810697088] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 02 19:57:25.389079 2017] [mpm_event:notice] [pid 4697:tid 140215810697088] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:57:25.389091 2017] [core:notice] [pid 4697:tid 140215810697088] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 19:57:26.464980 2017] [mpm_event:notice] [pid 4697:tid 140215810697088] AH00491: caught SIGTERM, shutting down
[Sun Apr 02 19:57:27.555303 2017] [mpm_event:notice] [pid 4968:tid 139977789454208] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 19:57:27.555398 2017] [core:notice] [pid 4968:tid 139977789454208] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 20:03:44.503773 2017] [mpm_event:notice] [pid 4968:tid 139977789454208] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 02 20:03:44.509300 2017] [mpm_event:notice] [pid 4968:tid 139977789454208] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 20:03:44.509308 2017] [core:notice] [pid 4968:tid 139977789454208] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 20:03:46.944588 2017] [mpm_event:notice] [pid 4968:tid 139977789454208] AH00491: caught SIGTERM, shutting down
[Sun Apr 02 20:03:48.018174 2017] [mpm_event:notice] [pid 5382:tid 140627807795072] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 20:03:48.018254 2017] [core:notice] [pid 5382:tid 140627807795072] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 20:04:09.801201 2017] [mpm_event:notice] [pid 5382:tid 140627807795072] AH00491: caught SIGTERM, shutting down
[Sun Apr 02 20:04:10.893010 2017] [mpm_event:notice] [pid 5494:tid 140580858779520] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 20:04:10.893100 2017] [core:notice] [pid 5494:tid 140580858779520] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 02 20:04:36.058295 2017] [mpm_event:notice] [pid 5494:tid 140580858779520] AH00491: caught SIGTERM, shutting down
[Sun Apr 02 20:04:37.187084 2017] [mpm_event:notice] [pid 5607:tid 140320021604224] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 02 20:04:37.187190 2017] [core:notice] [pid 5607:tid 140320021604224] AH00094: Command line: '/usr/sbin/apache2'

**Comment by A9G-Data-Droid** [comment]
> `chmod -R 777 storage`
> `chmod -R 777 bootstrap/cache`
> `chmod -R 777 public/uploads`

It should be noted that you don't want to allow everyone write, which is what 777 does. If the user and group are correctly set to the httpd user `www-data` or `apache` then you permissions don't have to be set wide open.

EXAMPLE: 
```
sudo chown www-data:www-data -R bootstrap/cache public/uploads storage 
sudo chmod -R 755 bootstrap/cache public/uploads storage
```
