### ISSUE TITLE
corporate design

### ISSUE THREAD

**Issue by E-Fail** [BookStackApp/BookStack#2160]
We use Bookstack for documentation in the IT. If a User get access to a new service, like VPN, we export the How-to guide as PDF and send it via mail. But the PDF ist just a PDF. It would be nice to add a corporate design to it (Logos, Fonts, Layout etc.)

**Comment by ssddanbrown** [comment]
Thank you for your input @E-Fail.

The fundamental functionality requested is already covered by #493 and a few other PDF customization issues. Therefore I'm going to close this off as a duplicate.
