### ISSUE TITLE
Chooce type of editor per book. 

### ISSUE THREAD

**Issue by steelandt** [BookStackApp/BookStack#2163]
**Describe the feature you'd like**
Set the type of editor per book.

**Describe the benefits this feature would bring to BookStack users**
Technical users prefer the MKDOCS editor for fast writing documentation. Non technical people prefer the WYSIWYG. 

**Additional context**
I have both technical users writing technical data and end users writing user documentation. 
2 different kind of people that each prefer their editor. I'm splitting the books between technical and non techincal. In principle, you could have the choice for the editor set per chapter or even per page, which would make it even better. Having it on booklevel, would already be great for me.

**Comment by ssddanbrown** [comment]
Thanks for your request.

Since there are many existing issues, (#458, #119 & #842), which would essential solve the root problem I'm going to close this off as a duplicate.
