### ISSUE TITLE
Ability to remove pages instead of moving them to the book when removing a chapter

### ISSUE THREAD

**Issue by bendem** [BookStackApp/BookStack#2164]
**Describe the feature you'd like**
Currently, when you remove a chapter, all the pages inside are moved to the book. I would like a way to choose whether I want them moved up or actually removed (a checkbox with a clear description).

**Describe the benefits this feature would bring to BookStack users**
When you want to clean up some stuff, it's really annoying to have to delete all the pages of a chapter before removing the chapter.

**Additional context**
![image](https://user-images.githubusercontent.com/2681677/85730072-a5068000-b6f9-11ea-8fc1-39b098a68591.png)

**Comment by ssddanbrown** [comment]
Hi @bendem,
Thanks for the suggestion.

To be honest, I'd prefer not to have an option as these kind of options can quickly complicate things.

As of v0.31 and the inclusion of [the recycle bin](https://github.com/BookStackApp/BookStack/pull/2283), the default logic will be changing here. Deleting a chapter will now also delete the pages within (All get sent to the recycle bin). 

This means that within v0.31 (Once released):

- If you want to delete the chapter and all pages within, you just delete the chapter.
- If you want to keep the pages, you could go to the book sort screen first (Where you can multi-select for quick re-organising) then come back and delete the chapter. 

Does that sound like it'd suit your flow?

**Comment by bendem** [comment]
That's perfect. Better than the original idea.

**Comment by ssddanbrown** [comment]
@bendem Great, Thanks for confirming. In that case I'll close this off since the new functionality has been implemented and will be part of v0.31 which should be released before the end of the year.
