### ISSUE TITLE
[Error] Error after restore

### ISSUE THREAD

**Issue by mayrmartin** [BookStackApp/BookStack#217]
My server crashed and I had to use a backup to restore it.
After I restored my server, I restarted everything and I got a very strange error.
Could you explain me what kind of error it is and how it can be resolved?

![image](https://cloud.githubusercontent.com/assets/22145802/19783845/c48807de-9c93-11e6-8178-8fff3cc7d7da.png)

**Comment by ssddanbrown** [comment]
Hi @mayrmartin,
Not sure why this would happen but it looks like a dependant file is missing. To fix you could delete the `vendor` folder then re-run the command `composer install` to re-install all dependencies.

**Comment by mayrmartin** [comment]
I reinstalled everything and  imported my sqldump ( `mysql -u bookstack -p  < dump.sql ` )

and now I'm getting first a PDOException and then a  QueryException

> QueryException in Connection.php line 761:
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'system_name' in 'where clause' (SQL: select * from `users` where `system_name` = public limit 1)


> PDOException in Connection.php line 333:
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'system_name' in 'where clause'

**Comment by mayrmartin** [comment]
I solved the problem on my own, i just had to execute `php artisan migrate `
