### ISSUE TITLE
Your local changes to the following files would be overwritten by merge

### ISSUE THREAD

**Issue by 7uppi** [BookStackApp/BookStack#2172]
Hello.

I am trying to update bookstack (v0.28.3 > v0.29.3) using the following command from wiki:
`sudo git pull origin release && composer install --no-dev && sudo php artisan migrate`

I get an error telling me the following:
error: Your local changes to the following files would be overwritten by merge:
        .env.example.complete
        .github/translators.txt
        .github/workflows/phpunit.yml
        app/Actions/Activity.php
        app/Actions/ActivityService.php
        app/Actions/Comment.php
        app/Actions/CommentRepo.php
        app/Api/ApiDocsGenerator.php
        app/Api/ListingResponseBuilder.php
        app/Auth/Access/Guards/LdapSessionGuard.php
        app/Auth/Access/RegistrationService.php
        app/Auth/User.php
        app/Config/snappy.php
        app/Console/Commands/ClearViews.php
        app/Console/Commands/CopyShelfPermissions.php
        app/Console/Commands/DeleteUsers.php
        app/Console/Commands/RegeneratePermissions.php
        app/Console/Commands/RegenerateSearch.php
        app/Entities/Book.php
        app/Entities/Bookshelf.php
        app/Entities/Repos/BookshelfRepo.php
        app/Exceptions/NotifyException.php
        app/Http/Controllers/Auth/ForgotPasswordController.php
        app/Http/Controllers/Auth/LoginController.php
        app/Http/Controllers/Auth/ResetPasswordController.php
        app/Http/Controllers/BookController.php
        app/Http/Controllers/BookshelfController.php
        app/Http/Controllers/CommentController.php
        app/Http/Controllers/Controller.php
        app/Http/Controllers/HomeController.php
        app/Http/Controllers/Images/DrawioImageController.php
        app/Http/Controllers/UserController.php
        app/Http/Kernel.php
        app/Ownable.php
        app/Providers/AppServiceProvider.php
        app/Uploads/ImageRepo.php
        composer.json
        composer.lock
        dev/api/responses/books-read.json
        package-lock.json
        package.json
        public/.htaccess
        public/dist/app.js
        public/dist/export-styles.css
        public/dist/print-styles.css
        public/dist/styles.css
        public/libs/tinymce/plugins/help/plugin.min.js
        public/libs/tinymce/plugins/image/plugin.min.js
        public/libs/tinymce/plugins/imagetools/plugin.min.js
        public/libs/tinymce/plugins/lists/plugin.min.js
        public/libs/tinymce/plugins/paste/plugin.min.js
        public/libs/tinymce/plugins/print/plugin.min.js
        public/libs/tinymce/plugins/table/plugin.min.js
        public/libs/tinymce/plugins/textpattern/plugin.min.js
        public/libs/tinymce/plugins/visualchars/plugin.min.js
        public/libs/tinymce/plugins/wordcount/plugin.min.js
        public/libs/tinymce/skins/lightgray/content.inline.min.css
        public/libs/tinymce/skins/lightgray/content.min.css
        public/libs/tinymce/tinymce.min.js
        resources/js/components/book-sort.js
        resources/js/components/dropdown.js
        resources/js/components/markdown-editor.js
        resources/js/components/notification.js
        resources/js/components/page-comments.js
        resources/js/components/template-manager.js
        resources/js/components/wysiwyg-editor.js
        resources/js/services/code.js
        resources/js/services/drawio.js
        resources/js/vues/code-editor.js
        resources/js/vues/components/autosuggest.js
        resources/js/vues/page-editor.js
        resources/lang/ar/auth.php
        resources/lang/ar/common.php
        resources/lang/ar/passwords.php
        resources/lang/cs/auth.php
        resources/lang/cs/common.php
        resources/lang/cs/passwords.php
        resources/lang/cs/settings.php
        resources/lang/da/auth.php
        resources/lang/da/common.php
        resources/lang/da/passwords.php
        resources/lang/da/settings.php
        resources/lang/de/auth.php
        resources/lang/de/common.php
        resources/lang/de/errors.php
        resources/lang/de/passwords.php
        resources/lang/de/settings.php
        resources/lang/de_informal/auth.php
        resources/lang/de_informal/common.php
        resources/lang/de_informal/errors.php
        resources/lang/de_informal/passwords.php
        resources/lang/de_informal/settings.php
        resources/lang/en/auth.php
        resources/lang/en/common.php
        resources/lang/en/passwords.php
        resources/lang/es/auth.php
        resources/lang/es/common.php
        resources/lang/es/passwords.php
        resources/lang/es/settings.php
        resources/lang/es_AR/auth.php
        resources/lang/es_AR/common.php
        resources/lang/es_AR/passwords.php
        resources/lang/es_AR/settings.php
        resources/lang/fa/auth.php
        resources/lang/fa/common.php
        resources/lang/fa/passwords.php
        resources/lang/fa/settings.php
        resources/lang/fr/auth.php
        resources/lang/fr/common.php
        resources/lang/fr/errors.php
        resources/lang/fr/passwords.php
        resources/lang/fr/settings.php
        resources/lang/he/auth.php
        resources/lang/he/common.php
        resources/lan
Aborting

I tried searching for this issue online, and found something on [stackoverflow](https://stackoverflow.com/questions/25597104/git-pull-error-your-local-changes-to-the-following-files-would-be-overwritten-b). Knowing I had a working backup lying around, I tried running:
`git reset --hard`.
Turns out it cleared the user file (along with many other), so I reverted the server from backup.

It does look like I can use `git checkout (FILE)`, but that would first off take some time to go through, and secondly (not too good with the git command), wouldn't that delete some stuff I need?

Have I done something wrong?

**Comment by ssddanbrown** [comment]
Hi @7uppi ,

This can often be due to permissions. You could try telling git to ignore these files by running `git config core.fileMode false` in your BookStack install folder. That may fix this by itself. Otherwise, if not, running `git diff package.json may provide some clues as to what's changed. 

> Turns out it cleared the user file (along with many other), so I reverted the server from backup.

I would be surprised by git reset clearing out any files unless you've added files into this folder. You can always backup the directly, perform a hard reset, then copy back in any non-repo files/folders.

**Comment by 7uppi** [comment]
> You could try telling git to ignore these files by running git config core.fileMode false...
Thank you very much @ssddanbrown. It after running the first git command, it went through with the update.
Everything still seems to be there, so I am going to close this.
Have a great day.
