### ISSUE TITLE
Enable Auto Login for SAML2

### ISSUE THREAD

**Issue by tiredofit** [BookStackApp/BookStack#2175]
**Describe the feature you'd like**
I feel it would be useful to have full single sign on capabilities for SAML2 without having to click the login button.

**Describe the benefits this feature would bring to BookStack users**
This would avoid a click for users to login, and be automatically sent to the destination page.

**Comment by sswany** [comment]
This is relatively crude, but I was looking to do the same thing. I added the following to the Custom HTML head content and seems to work great. Basically just clicks on the SSO login button if its visible on the page after the DOM loads:
```
<script>
window.addEventListener("load", function () {
   document.getElementById("saml-login").click();
});
</script>
```

**Comment by ssddanbrown** [comment]
With the merge of #3406 this functionality is now available as a built-in option.
This will be part of the next feature release.
