### ISSUE TITLE
need bookshelf hidden

### ISSUE THREAD

**Issue by yoyomule** [BookStackApp/BookStack#2179]
Thanks for providing such a good tool. My needs are simpler. I want to use it as a help file system, so I don’t want a bookshelf to exist, or there is only one by default and it is hidden. I also hope that the tree navigation will be clearer. I don't know if it can be done through settings.

**Comment by ssddanbrown** [comment]
Hi @yoyomule & Thanks!

The BookShelves header menu option should hide automatically if a user does not have permission to create or view any bookshelves in the system. This can be tricky for admin accounts, where you'd have all permissions, but you could maybe create yourself a reduced permission account for daily use in that case.

Alternatively, A little custom CSS, in the "Custom HTML Head Content" could be used to hide the option.

**Comment by yoyomule** [comment]
Thank you, this can indeed solve the problem. But I have a suggestion, I found that its operation path is a bit long, I need to click multiple times to reach the page I need, can you optimize the tree directory better?

**Comment by ssddanbrown** [comment]
You could add the below to your "Custom HTML Head Option" to force-show all items in that menu:

```html
<style>
	.chapter-child-menu > button {
		display: none;
	}
	.chapter-child-menu > button + ul {
		display: block !important;
	}
</style>
```

Not an officially supported, stable tweak so could stop working on upgrade but should do the job now, Might just need a little adjustment if it does break in the future.

**Comment by ssddanbrown** [comment]
Since the questions have been answered I'll close this off.
