### ISSUE TITLE
Headers/Footers on PDF Export

### ISSUE THREAD

**Issue by tiredofit** [BookStackApp/BookStack#2181]
**Describe the feature you'd like**
Customizable Headers and Footers for PDF exports

**Describe the benefits this feature would bring to BookStack users**
The ability to put a legal disclaimer on as a footer in the export would be useful for those exporting. Also, a customizable header that would potentially allow a logo, the title of the book exported, and the option for allowing a date exported field would round out the PDF export function.

**Comment by ssddanbrown** [comment]
Hi ,
Thanks for opening this issue.

This has already been requested in #493 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #493 it will help show support for that request.
