### ISSUE TITLE
Recycle bin feature

### ISSUE THREAD

**Issue by Rumcajsev** [BookStackApp/BookStack#2183]
Adding this again since #1017 was closed.

Books/pages, when deleted, should go into the recycle bin, from which they could be either completly removed or brought back into the bookstack. 

I think this should be a priority feature, since without this function it's hard to recommend bookstack, especially for bigger teams.

**Comment by DavidLeutgeb** [comment]
Can't upvote this enough!  At the moment our workaround is to not allow anybody to delete anything expect some content admins. If they want something to be deleted they have to move it to a Deprecated folder where a content admin delete it after some time.

**Comment by b-zurg** [comment]
Should we set out a set of clear requirements?  Let me give it a shot.

* When a user deletes a page the confirmation page indicates that it will go to their recycle bin.
* A user can click on their account, and one of the options would be the recycle bin.
* If they click on the recycle bin it will take them to a page that shows a list of all of their deleted pages/chapters/books and their details.  If they click restore then everything would be reverted as is.
* Deleting a book will also delete all child chapters and children.  Deleting a chapter will delete all sub-pages.  Deleting a page would only delete the page.
* An admin can view the same recycle bin as the user, but would be able to manage all deleted entities for all users.

Any thoughts?

**Comment by Rumcajsev** [comment]
@b-zurg I would prefer another approach - which would be about page - book relation, rather than page - user as you proposed.

Users, depending on the permissions, can:

- Delete their pages/chapters
- Delete all pages/chapters (within the book)
- Cannot delete any pages/chapters

Once the page/chapter is deleted, it is moved to the recycle bin, which could be an option in the sidebar.

Admin and users with correct book permissions can browse through the recycle bin and remove the pages for good or revert them back into the book.

**Comment by ssddanbrown** [comment]
A recycle bin implementation has been added in #2283. This will be part of the next feature release, v0.31.
