### ISSUE TITLE
Bulk API support in BookStack

### ISSUE THREAD

**Issue by suvreal** [BookStackApp/BookStack#2188]
I would like to ask if there already is or would actually be availability of bulk API support to CRUD the data in BookStack. I don't know if it is matter of upcoming updates.

I am sorry for making possible duplicate of ticket.

--Suvreal

**Comment by watschi** [comment]
You opened the same issue 6 days ago in #2176  
Dan, the maintainer of this project, already answered that this will be available in future updates.

If you're not sure if there's already an open issue requesting a feature you would like to see, you can use the search function on the issue list.

**Comment by suvreal** [comment]
My apologies. I thought that the initial thought of adding bulk API handle was not said in previous ticket. In the previous ticket there was said bulk import/export accordig to the user UI, so I felt importance of asking API bulk in separate ticket. Again, sorry for possible mess.

**Comment by watschi** [comment]
No worries, but please remember that maintaining an open source project is a lot of (unpaid) work and more issues/requests equals less time available to actually develop the application.

I'm sure the maintainers are happy about constructive feedback and bug reports, but duplicate requests without much effort or research put into them might discourage people from continuing working on great projects ;)

**Comment by suvreal** [comment]
I just want to proved constructive feedback, I am sorry if it might be understood other way. I thought that this idea was not contained in previous ticket, because of which this ticket might be considered as duplicate. I will pay more attention to my communication to prevent to anything like this :).
I agree, we can close it.
