### ISSUE TITLE
Double click code to select it

### ISSUE THREAD

**Issue by ark-** [BookStackApp/BookStack#2189]
## Description

When double clicking inline code it would be great to select all of the contents of that inline code scope. Ready for copying.

Behavior not required for code blocks as they have their own copy button. 

## Benefits
A lot of bookstack users use it for documenting their own infrastructure or other software applications and as such a convenience feature such as this helps when copying and pasting inline code blocks. 

Hard to provide a measurable benefit. Anecdotally it would have been useful recently when I had to redeploy a service which had a bunch of manual copying settings into a Web GUI. 

I also write beginner guides that I share with my friends, there is often a lot of copying and pasting in those scenarios.

## Additional context
Below is a script I use in confluence to provide the same feature. It doesn't seem to work in the `Custom HTML Head Content` of  bookstack. Not sure why. 

``` javascript
var inline_code_elems = document.getElementsByTagName("code") 

for (var i = 0; i < inline_code_elems.length; i++) {
    inline_code_elems[i].addEventListener('dblclick', hiLite, false);
}

function hiLite(event) {
    var range = document.createRange();
    var selection = window.getSelection();
    range.selectNodeContents(event.target);
    selection.removeAllRanges();
    selection.addRange(range);
    e.stopPropagation();
}


```

**Comment by ssddanbrown** [comment]
Hi @ark-,
Thanks for the suggestion. 
This is already open under #1612 therefore I'm going to close this off as a duplicate.
