### ISSUE TITLE
Extended user page

### ISSUE THREAD

**Issue by tomasjay** [BookStackApp/BookStack#2190]
**Describe the feature you'd like**
It would be nice if the user could add content to his/her page, and to show up user pages e.g. in a book.

**Describe the benefits this feature would bring to BookStack users**
This would encourage users to be more active in editing and gardening on BookStack.

**Additional context**
Maybe there already exists a workaround?

Best, 
|||tomas jay

**Comment by ssddanbrown** [comment]
Hi @tomasjay,
Nothing really exists to do this right now. I want to be careful not to make the platform too much of a social platform, and keep it instead on the content/documentation.

Issue #1859 is already open for the idea of adding custom text/info to a profile page so I'm going to close this off just to cut down on any overlap in feature requests.

**Comment by tomasjay** [comment]
ok, I'll follow the other thread. thank you!
