### ISSUE TITLE
Keywords into files (.doc, .pdf, .bat...)

### ISSUE THREAD

**Issue by Vestarija** [BookStackApp/BookStack#2191]
Hi,

I am discovering Bookstack and I would like my company to integrate it into our services. 
It corresponds to our needs in particular for fast and efficient searches for content (keywords, exact term ...) That said, we have a lot of documents in PDF and I wanted to know if there was a possibility that the searches included the content (text for example) of a PDF or .doc document for example?

Thx

**Comment by Vestarija** [comment]
Nobody?

**Comment by JtheBAB** [comment]
The search function doesn’t index files.

**Comment by Vestarija** [comment]
> The search function doesn’t index files.

Okay, thank you.

**Comment by ssddanbrown** [comment]
Thanks @JtheBAB for answering, Will therefore close.
