### ISSUE TITLE
Select editor when creating a new note (MD / WYSIWYG)

### ISSUE THREAD

**Issue by solus-hq** [BookStackApp/BookStack#2194]
It would be really nice to have an option to choose note type when creating a new note. I have multiple notes which are mostly simple markdown templates for this and that and I simply don't want to pollute them with all these HTML tags if I sometimes switch to a new editor (WYSIWYG) and accidentally edit this note and save it.

So, for Markdown BookStack should choose MD editor, for WYSIWYG notes — WYSIWYG editor.

**Comment by ssddanbrown** [comment]
Hi @solus-hq , Thank you for your request.

I feel that this is already covered by the existing issues #119, #369 & #842.
Therefore I'm going to close this to reduce duplicates.

Note that an editor review and alignment phase [is planned on the roadmap](https://github.com/BookStackApp/BookStack#%EF%B8%8F-road-map).
