### ISSUE TITLE
Class 'Permissions' not found after upgrade from V0.27.5 to V0.29.3

### ISSUE THREAD

**Issue by Nico207** [BookStackApp/BookStack#2196]
Hi,

I have an error after upgrading Bookstack from V0.27.5 to V0.29.3 (Ubuntu 18.04.3 / PHP 7.2.24 / Laravel 6.18.3 / Apache)

![image](https://user-images.githubusercontent.com/1179972/88174857-42839f80-cc25-11ea-872b-b00d4adcb233.png)

I found issue #2159 that talks about the same thing (but with Nginx). As it's closed and there's a small difference, I took the liberty to open another one... Feel free to mark this one as a duplicate if necessary 😉

I checked the permissions files and everything seems OK

`composer install` return no error (maybe a warning about abandoned package)

```
Package operations: 51 installs, 0 updates, 0 removals
  - Installing maximebf/debugbar (v1.16.1): Downloading (100%)
  - Installing barryvdh/laravel-debugbar (v3.2.9): Downloading (100%)
...
  - Installing wnx/laravel-stats (v2.0.2): Downloading (100%)
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
barryvdh/reflection-docblock suggests installing dflydev/markdown (~1.0)
barryvdh/reflection-docblock suggests installing erusev/parsedown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.7.2)
phpunit/phpunit suggests installing ext-soap (*)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0.0)
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating optimized autoload files
...
Package manifest generated successfully.
> @php artisan cache:clear
Application cache cleared!
> @php artisan view:clear
Compiled views cleared!
```

`git status` return the following

```
Sur la branche release
Votre branche est à jour avec 'origin/release'.

Fichiers non suivis:
  (utilisez "git add <fichier>..." pour inclure dans ce qui sera validé)
        .env.bak
        composer.phar

aucune modification ajoutée à la validation mais des fichiers non suivis sont présents (utilisez "git add" pour les suivre)
```

**Comment by ssddanbrown** [comment]
Hi @Nico207 

Can you try fully deleting the `vendor` directory of your BookStack installation direction then re-run the `composer install` step. Afterwards, if still not working, might be worth trying to run `sudo php artisan cache:clear`.

**Comment by Nico207** [comment]
I have the same issue, even after deleting `vendor` directory and running the clear cache command.

**Comment by ssddanbrown** [comment]
Hmm, Might be worth trying `php artisan config:clear`. If that does not work try `sudo php artisan config:clear`.

**Comment by Nico207** [comment]
Great!
After `php artisan config:clear`, everything seems to work.
But, after that, do I need to reconfigure or verify anything?

**Comment by ssddanbrown** [comment]
@Nico207 Awesome, No need to do anything. Everything should have been done by the other update steps, just need to remove the older cached config. Will therefore close this off.

**Comment by Nico207** [comment]
> just need to remove the older cached config

Sorry but... how I do that ? 😳

**Comment by ssddanbrown** [comment]
Ah, Sorry, I mean `needed`. You did that by running the command.
