### ISSUE TITLE
The requested PHP extension ext-tidy * is missing from your system.

### ISSUE THREAD

**Issue by JoshuaJarman** [BookStackApp/BookStack#2199]
**Describe the bug**
composer install is throwing the following error:
```
The requested PHP extension ext-tidy * is missing from your system.
```

**Steps To Reproduce**
```
composer install --no-dev
```

**Expected behavior**
BookShelf to Install

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.3 (latest)
 - PHP Version: 7.3.20
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
php shows that the tidy module is indeed installed.
```
>php --version
PHP 7.3.20 (cli) (built: Jul 10 2020 16:17:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.0, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.20, Copyright (c) 1999-2018, by Zend Technologies
```
```
>php -m

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
i360
iconv
imagick
imap
intl
ionCube Loader
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
the ionCube PHP Loader + ionCube24
```

**Comment by JoshuaJarman** [comment]
if i bypass the composer issue with detecting tidy:
```
composer install --no-dev --ignore-platform-reqs
```

i still get a php error in dump.php
```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/vhosts/nelsondesigncollective.com/info.nelsondesigncollective.com/BookStack/vendor/symfony/var-dumper/Resources/functions/dump.php on line 18

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/vhosts/nelsondesigncollective.com/info.nelsondesigncollective.com/BookStack/vendor/symfony/var-dumper/Resources/functions/dump.php on line 18
```

**Comment by ssddanbrown** [comment]
Hi @JoshuaJarman,
I wonder if the composer install command is maybe using a different php instance on your system.

Could you download the composer.phar directly and run if via php like so?:

```bash
curl https://getcomposer.org/download/1.10.9/composer.phar > composer.phar
php composer.phar install
```

**Comment by Zenahr** [comment]
@JoshuaJarman I ran into a non-related but similar problem with `` today as well. Try the following steps to solve the problem:

1. Check which php.ini (configuration file) your PHP runtime is using
2. In the php.ini file make sure `tidy` is uncommented

```ini
...
;extension=...
extension=tidy
;extension=...
...
```

3. Run `composer update`

https://stackoverflow.com/questions/42557693/laravel-pdoexception-could-not-find-driver

**Comment by JoshuaJarman** [comment]
I was able to get it installed by using a local copy of composer.phar via @ssddanbrown suggestion.

Thanks to you both for the help!
