### ISSUE TITLE
Permissions Feature Requests

### ISSUE THREAD

**Issue by pinglanyue** [BookStackApp/BookStack#220]
In settings/roles page,can add 3 other permissions:

1.Lock : If locked,can't  edit and delete (until unlock it).
2. Delete Forever and Delete:If **DELETE** a book,viewer can't see it,but didn't delete it from database,admin can recovery/reopen it.But if  **Delete Forever** (only admin or settting roles ),the book will delete from database.(If a book was locked ,can't delete and "forever delete".)
**3.** Except the _own_ and _all_ permissions setting,can add a _group_ setting.(Also should add a 'setting/group' page to set/control group.Or 'settings/roles' can have admin,editor,group,viewer by default setting )

**Comment by pinglanyue** [comment]
Hi,@ssddanbrown .I use 0.13 and see new permission control.Consider current open issues about permissions:
[#112](https://github.com/BookStackApp/BookStack/issues/112)
[#299](https://github.com/BookStackApp/BookStack/issues/229)
[#299](https://github.com/BookStackApp/BookStack/issues/235)

I have a idea about the permissions setting:

**Now role setting**

| Name |  Email  | UserRoles             |
|---------------|------------|--------------|
| Admin |  **             | Admin        |
| Guest  | **             | Public       |


| Roles page:          |              |
|----------------------|--------------|
| RoleName             | Users(count) |
| Admin                |              |
| Editor               |              |
| Viewer               |              |
| Public               |              |


#  **Use Group**
**Users page:**

| UserName Email Roles |    |                                    |
|----------------------|----|------------------------------------|
| Admin1               | ** | Admin                              |
| Editor1              | ** | Editor                             |
| Editor2              | ** | Editor                             |
| Guest                | ** | Public                             |
| UserOwn              | ** | **Individual**|
|                      |    |                                    |
| User1                | ** | **GroupSuperAdmin**                    |
| User2                | ** | GroupSuperAdmin                    |
| User3                | ** | (no role)                          |
|                      |    |                                    |
| UserA                | ** | null                               |
| UserB                | ** | null                               |
| UserC                | ** | null                               |
| UserD                | ** | null                               |


Individual: Own setting just here,user sign up have no role ,Individual role user can create book,and make a book private or public.
Group:later ~


**Roles page:**
Admin 
Editor
GroupSuperAdmin
Group
Self	
Public
....(custom setting)

**Group's role permissions（only Admin and GroupSuperAdmin can setting）:**
GroupAdmin 
GroupEditor
GroupViewer(default)
no other role setting

**Groups page:**

| GroupsName | GroupSuperAdmin | GroupAdmin  | GroupEditor |    GroupUsers(count)                         |   
|------------|-----------------|-------------|-------------------------------|----------------------------|
| GroupA     | User1           | User1       | UserA                         | 3(User1,UserA,UserB)       |  
| GroupB     | User2           | User2       | UserA,UserB                   | 4(User2,UserA,UserB,UserC) | 
| GruopC     | User1           | User1,User3 | null                          | 3(User1,User3,UserC)       |  



User:Group=>N:N
(Admin/GroupSuperAdmin can create a group.One group only have one GroupSuperAdmin,but can have many GroupAdmin.GroupAdmin can't create book,but can manage all other thing.)
## Example:
User1 create GroupA and GroupC。
Add user and setting user's pressions:UserA is GroupA's editor,can User3 is Group's admin.
Create a book/project named Book1,so this book can setting this permissions:Public(everyone can view,default setting)or Group(only selected group's user can see)。chapter and page 's permisson setting is inherit book permisson's setting.but also do this special thing：Book1 have Chapter1 and Chapter2,in Chapter permission setting,you can select by role or by group.ex:only want to GroupA manage Chapter1's content and GroupB manage Chapter2。
another case : Book2 is GroupA 's private book ,user can join  GroupA to see it.Different group can make own project book.music group,movie group etc...if have a group setting,is onvenient on these scene.

**Comment by pinglanyue** [comment]
Another idea: every book can make a tag,Tag can control the permission.
tag like group.
example:
phpbook tag aas php and dev:

book tag bookpermission chapterpermission pagepermission
phpbok dev 1 1 1 
phpbook php 3 4 3
(all default permission is 1)



permissonid tagpermisson
0 private
1 only view
2 view+modify
3 +crete
4 +delete
........

tag user permissonid 
php user1  1
dev user1 3
...

**Comment by ssddanbrown** [comment]
I'll be honest, I've never responded to this since I've never really understood the request here. After re-reading I still don't really understand. I appreciate the effort you've gone to here though. 
This may even be solved with the good amount of permission system changes since this original request.

If you still require change in the permission system please open a new request with an example that's as simple as possible. Thanks.
