### ISSUE TITLE
Support HTML (Raw?) In Descriptions of Shelves and Books

### ISSUE THREAD

**Issue by tiredofit** [BookStackApp/BookStack#2203]
**Describe the feature you'd like**
The ability to parse HTML in descriptions of shelves and books

**Describe the benefits this feature would bring to BookStack users**
Richer content display as an introduction to a shelf or book.

**Additional context**
Use Case: Adding tables or formatting in the description would be useful for those using Bookstack for rich "introductions" to the Shelves/Books.

**Comment by ssddanbrown** [comment]
Related to #1076 and #1666.

**Comment by charleslcso** [comment]
I wish to add a hyperlink in descriptions. Use Case: I use Bookstack as a knowledge base application, while in description pointing users to a Support System.

**Comment by ssddanbrown** [comment]
Via PR #4729, there is base level of HTML support in descriptions of shelves/books/chapters, although no direct HTML input with instead a simple WYSWIYG interface provided. HTML can be directly set via the API although the format is limited to a simple subset of allowed HTML. 
Tables are not supported but links are.

These changes will be part of the next feature release, so I'll therefore close this off.
This was also related to #2354.
