### ISSUE TITLE
Google Adsense

### ISSUE THREAD

**Issue by austinsonger** [BookStackApp/BookStack#2205]
Is there a way to add "google adsense" to it?

**Comment by ssddanbrown** [comment]
Hi @austinsonger,

I don't really know what's involved for adding adsense to a page. There is a "Custom HTML Head" setting where you can insert some HTML that will be added into the HTML `<head>` of every BookStack page (Apart from the settings page itself). Alternatively it is technically possible to customize any view using the [theme system](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#theme-system) but it does take a little know-how.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
