### ISSUE TITLE
Rooms to arrange shelves into

### ISSUE THREAD

**Issue by christoroth** [BookStackApp/BookStack#2206]
**Describe the feature you'd like**
Extending the library analogy, what if shelves could be arranged into Rooms.  

**Describe the benefits this feature would bring to BookStack users**
We've currently got one entry point into bookstack which lists all of the book shelves.  Within the shelves are the books themselves.  

It'd be really neat to be able to have rooms called "public", "developers", "consultants" etc which each have their own sets of shelves because at the moment those rooms are shelves so everything in the shelf has to be a book.  Within Dev we'd like shelves for "best practices", "cookbooks", or different projects which would each have multiple books.

Thanks for reading!

**Comment by ssddanbrown** [comment]
Thank you for the suggestion @christoroth.

This is similar to #2139.
[My comment here](https://github.com/BookStackApp/BookStack/issues/2139#issuecomment-636062898), and the subsequent comment that leads to, reflects my own thoughts on adding another layer to the hierarchy.

**Comment by ssddanbrown** [comment]
Since there has been no further discussion to be had here I'll close this off.
