### ISSUE TITLE
Horizontal Line in Dark Mode Does Not Appear

### ISSUE THREAD

**Issue by ReaHe** [BookStackApp/BookStack#2209]
**Describe the bug**
When using Bookstack in dark mode and you use the "horizontal line" button when building your page it places a horizontal line in your page but you are unable to see it as long as you are in dark mode.

**Steps To Reproduce**
1. Turn on dark mode
2. Create a new page
3. Place horizontal line via the button right below the page name
4. As you can see its not viewable. Change to light mode or export a Contained Web File and it will appear

**Expected behavior**
For the horizontal line to be visible in dark mode

**Screenshots**
Dark Mode
![image](https://user-images.githubusercontent.com/16505127/89139792-d00c9c80-d50d-11ea-9f9b-996faefb86cb.png)
Light Mode
![image](https://user-images.githubusercontent.com/16505127/89139795-d569e700-d50d-11ea-9b0d-4560649473d1.png)

**Your Configuration (please complete the following information):**
 - BookStack v0.29.3
 - PHP 7.3.18 (cli) (built: May 15 2020 16:10:31) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.18, Copyright (c) 1998-2018 Zend Technologies
 - Docker

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Thanks for report @ReaHe. A fix has been applied to be part of v0.30.
