### ISSUE TITLE
Problem with big tables on page

### ISSUE THREAD

**Issue by Irbis-snowbars** [BookStackApp/BookStack#221]
BookStack Version:   0.12.2
PHP Version:    PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
MySQL Version:     5.7.16-0ubuntu0.16.04.1 (Ubuntu)

Expected Behavior:
The correct location of the block "Book tree" to the left of the page content, IMHO.
Actual Behavior:
At the moment a large table in the pages of the book overlap a block "book tree".
![scr-0](https://cloud.githubusercontent.com/assets/23168466/19854384/bb781bcc-9f7f-11e6-8a48-d403a9f09ec9.PNG)

**Comment by ubaltaci** [comment]
I second that tree navigation should be placed in left side.

**Comment by AngelGL** [comment]
Would be great if add the option to use horizontal scroll for big tables. It would solve the problem when visiting the page from mobile device.

**Comment by bharadwajag** [comment]
Yes, we are also facing the same problem for big tables.

**Comment by pranay-kd** [comment]
Also facing the same issue.

**Comment by s0n-** [comment]
Also facing the same problem and I would add that they arent necessarily "big" tables either. A lot of the tables we use get cut off until you scroll down. 

Moving navigation to the left would be a great and simple start.

**Comment by ssddanbrown** [comment]
@s0n- As part of the in-progress design update the navigation is moving to the left.

**Comment by s0n-** [comment]
@ssddanbrown Thank you very much, I want to thank you for all the work you've put into this product. Have you thought about using a funding platform for new features? I know personally I would put dollars or whatever you needed behind specific features for the product.

**Comment by ezzra** [comment]
I guess this could be closed

**Comment by ssddanbrown** [comment]
@ezzra Thanks for highlighting this.

Will close, Issues relating to responsiveness can be discussed within #1387
