### ISSUE TITLE
CSS is not working in master branch

### ISSUE THREAD

**Issue by kshitijsharma97** [BookStackApp/BookStack#2212]
When I serve the project from master branch and open it in chrome browser application was not looking as it suppose to be.
Is it because it is dev instance or it's an issue? I have just started to work on BookStack to solve some issues

**Steps To Reproduce**
1. Switch to master branch.
2. Serve the project and open it in browser.

**Video**
https://www.loom.com/share/99ef59e9c902429d8150a5980cd9b5d2

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: BookStack v0.30-dev
 - PHP Version: 7.3.13 (cli)
 - Hosting Method: Apache

**Comment by ssddanbrown** [comment]
Hi @kshitijsharma97,

The `master` branch does not contain the built CSS/JS, You'd need to build it yourself as per the readme here: https://github.com/BookStackApp/BookStack#%EF%B8%8F-development--testing

Alternatively, if you want to avoid that, you may be able to get away with copying the `public/dist` files from the release branch but you may run into a few issues, especially as the branches diverge.

**Comment by kshitijsharma97** [comment]
Hi @ssddanbrown ,

Thank you for responding. I was confuse when I read the readme. Now I have clear view. Thank you once again.
