### ISSUE TITLE
Autologin or skip logn?

### ISSUE THREAD

**Issue by lanslans** [BookStackApp/BookStack#2216]
**Describe the feature you'd like**
When you go to the bookstack front page, the user is automatically logged in to the guest account and does not see the login page. 

Bonus, but not necessary: The top-right user link is instead replaced with a "log in" link which logs out the guest account and brings you to a login page. If you don't log in and instead navigate away from this page, it returns you to the guest account.

**Describe the benefits this feature would bring to BookStack users**
Reduce user friction in environments where logging in isn't necessary. Eg: read-only public guest access, or an instance within a LAN for a group that doesn't care about tracking authorship.

**Additional context**
I'm willing to put in some work to help with this if someone can point me at the right place. That said, I have all of 0 programming experience in PHP.

**Comment by alexmannuk** [comment]
Log in as an admin user, go to Settings. The first setting at the top is "Allow Public Access" which works exactly as you wish.

**Comment by ssddanbrown** [comment]
Thanks @alexmannuk for providing the answer here.

Once public access is enabled you can then configure permissions against the default public role and guest user to control public visibility.
