### ISSUE TITLE
User Attrition

### ISSUE THREAD

**Issue by mmitchen** [BookStackApp/BookStack#2219]
I'd like the ability to manage/transfer a user's ownership of documents before removing the user from BookStack.

Based on the assumption that a user's documents will be removed once they are deleted from BookStack (I haven't been able to confirm this is true), this will allow me to clean up a user's documents and make sure they have a new owner before I remove the user. 

Apologies if this is the wrong approach for this type of question/feature request but I wasn't able to find what I was looking for online otherwise.

**Comment by ssddanbrown** [comment]
Hi @mmitchen,

Thanks for your request. Currently BookStack simply infers the "Creator" as the "Owner". 
I've opened #2246 to propose adding "Owners" officially to BookStack and have considered your request to assign a new owner within that proposal.

Just a note, A user's content will not be removed when they are deleted. They are left in the system to be used by those that have permission to view them.

**Comment by mmitchen** [comment]
Thanks for the follow up Dan and for submitting the enhancement suggestion for consideration. Thanks also for confirming user content remains if a user is deleted. That was biggest concern and part of the reason I wanted to have the ability to change the owner. I still think it would be good to be able to change owner but it's less of a priority for me with your confirmation. Thanks!
