### ISSUE TITLE
User Last Logged In

### ISSUE THREAD

**Issue by dannyhanes** [BookStackApp/BookStack#2220]
**Describe the feature you'd like**
I would love to see when a user last logged into Bookstack on the users page. Just a simple date / time would be very useful. 

**Describe the benefits this feature would bring to BookStack users**
I currently share my Bookstack with family and friends and would help me purge inactive users. 

**Additional context**
None.

**Comment by ssddanbrown** [comment]
Thanks for the request @dannyhanes,

This has already been requested in #848 so I'll therefore close this off.
