### ISSUE TITLE
Error resetting or changing book cover [ production.ERROR: SplFileInfo::getType() ]

### ISSUE THREAD

**Issue by hiimmazl** [BookStackApp/BookStack#2222]
Hi,

Your Configuration (please complete the following information):

Exact BookStack Version (Found in settings): v0.29.3
PHP Version: 7.4.9
Hosting Method (Nginx/Apache/Docker): IIS 

right now I have installed bookstack on IIS (newest version) and PHP Version 7.4.9.

Everything is working right except changing or resetting book covers. Once I have set a book cover I get an "An unknown error occurred" and nothing happens. As I restart the server I can upload and reset the book cover or change it once. Then it gets stuck again and I am not able to change or reset it again until a restart.

The laravel.log is stating the following:

> production.ERROR: SplFileInfo::getType(): Lstat failed for **_filename_** {"userId":1,"exception":"[object] (RuntimeException(code: 0): SplFileInfo::getType(): Lstat failed for **_filename_** at C:\\inetpub\\wwwroot\\BookStack\\vendor\\league\\flysystem\\src\\Adapter\\Local.php:508)

I am not able to track down the error on my own.

Thanks for some help! 👍

Edit :

I just installed XAMPP on another server for testing and I get the exact same error. Did everything like the installation guide again. 

Exact BookStack Version (Found in settings): v0.29.3
PHP Version: 7.4.8
Hosting Method (Nginx/Apache/Docker): XAMPP

**Comment by ssddanbrown** [comment]
Hi @hiimmazl,
Sorry to hear you're having issues.
I think this'll be a tricky one to replicate.

If I had to guess, this will be due to permissions and the php process having issues reading the directory contents. 
I'd maybe check the `storage/` and `public/uploads/` folders and apply some liberal permissions to them, at least temporarily, to see if that improves things at all.

**Comment by hiimmazl** [comment]
Hi @ssddanbrown,

thanks for the reply! 

I already applied permissions "full access" to "Everyone". Did not work out yet somehow. I dont know what I can do much different as I am seeing this issues with a xampp installation and also with an IIS installation.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
