### ISSUE TITLE
Controlling Pages via the API 

### ISSUE THREAD

**Issue by barleybobs** [BookStackApp/BookStack#2226]
**Describe the feature you'd like**
The ability to create, update and delete pages via the API.

**Describe the benefits this feature would bring to BookStack users**
More control over the system via the API.

**Additional context**
Use Case: Being able to create systems to update pages in real-time via API requests.

**Comment by sgvandijk** [comment]
A specific use case example: bulk updating of all pages. We have moved our storage but image URLs are still pointing to the old location, it would have been great to be able to use the API to bulk update those.

**Comment by ssddanbrown** [comment]
[As of v0.31](https://www.bookstackapp.com/blog/beta-release-v0-31-0/#api-update---pages) it's possible to perform CRUD actions on pages via the API so I'm going to close this issue. 

@sgvandijk There's a command built-in specifically for doing what you need. Please see the command at around line 40 of the code on this page: https://www.bookstackapp.com/docs/admin/commands/
