### ISSUE TITLE
Feature Request of .gif / .gifv support for animated snippets native on the page. 

### ISSUE THREAD

**Issue by MayankTahil** [BookStackApp/BookStack#223]
### For Feature Requests
Desired Feature: Support for embedded animations in .gif and/or .gifv in pages. Right now when gifs are embedded, only a single frame shows visually, and upon clicking the file embedded into the page, a new tab opens that then animates in the browser. I'd like to request gif animation support native on the same page in line with content. 

### For Bug Reports
PHP Version: N/A

MySQL Version: N/A

Expected Behavior: N/A

Actual Behavior: N/A

**Comment by dssoft32** [comment]
Any update on the feature request ?

**Comment by alariva** [comment]
I falled back to a Giphy embed that works neat, however this is far from ideal, and editing pages become a bit "noisy" with the browser statusbar loading the embeds on the preview panel.

**Comment by Abijeet** [comment]
@ssddanbrown - I looked into this a little bit and it seems that **Intervention/Image** does not support gifs yet which is causing this issue. Read more about it here - https://github.com/Intervention/image/issues/176

Is it OK if we check if an image file is a GIF and if so, return the path without any sort of scaling?

I'll have to change the code here - 

https://github.com/BookStackApp/BookStack/blob/c44c42103c9e1aa324ce706b4acb8e5076af9610/app/Services/ImageService.php#L185-L224

I'm not sure about the thumbnail though, maybe we leave it as is for now? So basically thumbnails still don't animate.

**Comment by ssddanbrown** [comment]
@Abijeet Yeah, That sounds like the best approach :+1:
