### ISSUE TITLE
Crispy Dark Mode Images

### ISSUE THREAD

**Issue by qjesse** [BookStackApp/BookStack#2242]
**Describe the bug**
It appears as though being in dark mode alters images in some way, and this can affect Page images very drastically, especially if they've been resized. I'm no expert in image alteration but you can see below in the screen shots.

**Steps To Reproduce**
1. Go to the WYS Editor, assure you're in dark mode.
2. Paste an image three times.
3. Resize the same image down each time.
(alternatively, open a document with a lot of images and look at the images in dark mode vs light mode)

**Expected behavior**
Same perfection of images that light mode has.

**Screenshots**
(dark mode)
![image](https://user-images.githubusercontent.com/24780907/92134525-3c114780-edcf-11ea-9f6c-99be794350b0.png)

vs
(light mode)
![image](https://user-images.githubusercontent.com/24780907/92134630-5f3bf700-edcf-11ea-987f-46f16e63c1aa.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.29.3
 - PHP Version: PHP 7.2.24
 - Hosting Method (Nginx/Apache/Docker):  Apache/2.4.29 

**Additional context**
Crispy Images = Sharp, aliasing images, and somehow seems brighter as well?

**Comment by ssddanbrown** [comment]
Hi @qjesse,
Thanks for reporting with clear examples.

This has been raised and fixed within issue #2045. It's just waiting on me to finish of that release. Therefore I'm going to close this off as a duplicate.
