### ISSUE TITLE
Full history via UI

### ISSUE THREAD

**Issue by wojosc** [BookStackApp/BookStack#2243]
**Describe the feature you'd like**
A place where I can see the full change history of a book. I would like to see beyond the past few changes:
![image](https://user-images.githubusercontent.com/22279621/92250149-66e0c600-eecb-11ea-8796-8c15b69fc07e.png)

**Describe the benefits this feature would bring to BookStack users**
This would give me the possibility to revise on certain days, weeks or months. For example if I would like to see all changes made on June 10th last year.

**Additional context**
At the end of the day it would be nice for me as a user to be able to see the full change history for a single book or page.

**Comment by DiscoveryOV** [comment]
Appears PR https://github.com/BookStackApp/BookStack/pull/1816 would add this?

**Comment by DiscoveryOV** [comment]
> At the end of the day it would be nice for me as a user to be able to see the full change history for a single book or page.

You can see full page revision history by going to a page and clicking the Revisions link in the right hand menu.

**Comment by wojosc** [comment]
> > At the end of the day it would be nice for me as a user to be able to see the full change history for a single book or page.
> 
> You can see full page revision history by going to a page and clicking the Revisions link in the right hand menu.

Thank you, yes, page history is fully accessible. Chapter or book missing though as far as I know.

@DiscoveryOV Thank you. That PR seems to at least cover chapter history. I have added my request there also.

have a nice day.

**Comment by ssddanbrown** [comment]
Thanks for the request @wojosc.

There's an existing issue #1566 which covers this case, of being able to view an extended activity feed history so I'm therefore going to close this off.

As another option, in v0.30 I added an audit log which could be used by admins to get a more detailed view of activities in the system (The audit log and the history feed use the same database table).

**Comment by wojosc** [comment]
Thanks for the Info!
