### ISSUE TITLE
iOS Webclip

### ISSUE THREAD

**Issue by kmplngj** [BookStackApp/BookStack#2247]
**Describe the feature you'd like**
I like to use BookStack as an iOS Webclip with StartUp Image, Icon and perhaps with hiding the Safari User Interface. Perhaps all this could also get configuration settings. 

**Describe the benefits this feature would bring to BookStack users**
Users could use BookStack more natively on iOS. 

**Additional context**
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by ssddanbrown** [comment]
Hi @kmplngj,
Thank you for your request.

This has already effectively been requested under issue #301. Therefore I'm going to close this off as a duplicate.
