### ISSUE TITLE
Backup and restore?

### ISSUE THREAD

**Issue by cptr13** [BookStackApp/BookStack#225]
I'm sorry, I'm not that technical.  How do you backup and restore BookStack?  This is a great app...but I can't use it if I can't backup and restore it.  Would someone mind pointing me in a direction so I can sort it out?

Thanks for any help.

### For Feature Requests
Desired Feature:

### For Bug Reports
PHP Version:

MySQL Version:

Expected Behavior:

Actual Behavior:

**Comment by ssddanbrown** [comment]
Hi @cptr13,
There's nothing built in at the moment but it can be done with a few commands. 

Since this information would be helpful to many users I have updated the docs with the relevant information:
https://www.bookstackapp.com/docs/admin/backup-restore

**Comment by cptr13** [comment]
This is fantastic, thank you so much, I really appreciate it!
