### ISSUE TITLE
All images and diagrams (Draw.io) crashing after change server ip address

### ISSUE THREAD

**Issue by 1vicente** [BookStackApp/BookStack#2254]
**Describe the bug**
In homolog enviroment when the server change ip address, all images and diagrams (Draw.io) are crashing.

Verifying I found some possible reason: - images link not change with actual server ip address.

But is necessary investigate a reason of diagrams (draw.io) are crashing too.

**Steps To Reproduce**
1. Create a page;
2. Put in an image;
3. Force to change server IP address;
4. Check all images.

**Expected behavior**
Images link should update automaticaly with the server IP address.

**Screenshots**
![image](https://user-images.githubusercontent.com/13755048/93090772-a352b580-f673-11ea-9650-4ba0f8c258f2.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.3
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by cdrfun** [comment]
You have to execute a command to change the urls. This is documented at https://www.bookstackapp.com/docs/admin/commands/

```
# Update a URL in the database content of your BookStack instance.
# Searches for <oldUrl> and replaces it with <newUrl>
php artisan bookstack:update-url <oldUrl> <newUrl>
# Example:
php artisan bookstack:update-url http://docs.example.com https://demo.bookstackapp.com
```

**Comment by 1vicente** [comment]
Hello.

It works!

Thank you for your help.
