### ISSUE TITLE
VBScript Syntax Highlighting

### ISSUE THREAD

**Issue by kayvanaarssen** [BookStackApp/BookStack#2255]
Please add VBScript Syntax Highlighting

Example code: 

```
Sub Task_Run()
    
    Dim NextStep
    
    NextStep = "Retrieve data new WF9009"

    Do
        Select Case NextStep
            Case "Retrieve data new WF9009"
                'Run Action 'Retrieve data new WF9009'
                Steps("Retrieve data new WF9009").Run
                If Steps("Retrieve data new WF9009").RowCount<>0 Then
                    'Set the RecordSource of 'Create Mail New WF9009' to RecordSet of 'Retrieve data new WF9009'
                    Set Steps("Create Mail New WF9009").RecordSource = Steps("Retrieve data new WF9009").RecordSet
                    'Run Action 'Create Mail New WF9009'
```

Highlighting in Visual Studio Code Example:

![image](https://user-images.githubusercontent.com/672841/93454707-a223c180-f8db-11ea-80c4-87af5cab1dcb.png)

**Comment by nutsflag** [comment]
Hello @kayvanaarssen,

Would that suit you? 

![image](https://user-images.githubusercontent.com/26460023/94902144-0461f200-0498-11eb-9b90-26ca64302ab9.png)

**Comment by kayvanaarssen** [comment]
Looks good for a start. Did you use some existing highlight template?
Better than nothing though 👍

**Comment by nutsflag** [comment]
No, I imported the Codemirror module corresponding to VBScript. 

You can change the theme. You have the information in the documentation ( Changing Code Block Themes - [link](https://www.bookstackapp.com/docs/admin/visual-customisation/))

**Comment by kayvanaarssen** [comment]
Great, could you import other common used languages as well?
Markdown is also a big one.
And;
Showing a list of languages of an other system we often use.

![image](https://user-images.githubusercontent.com/672841/94909072-e6e65580-04a2-11eb-858e-62ffc79869d9.png)

Thanks!

**Comment by nutsflag** [comment]
Markdown is already present

**Comment by kayvanaarssen** [comment]
Right, missed that sorry, but you get the point 👍

**Comment by ssddanbrown** [comment]
Thanks for the request @kayvanaarssen and thanks for the PR @nutsflag 
I'll look to merge before next release where possible.

@kayvanaarssen I don't want to throw all possible languages in right now since it has a toll on the script download/run size. I'll probably look to dynamically load them in to negate that toll at some point but, even then, the size of a list can have an impact on UX. Therefore I'd prefer to keep it to those which are fairly popular while being fairly happy to accept new languages upon request, such as this, for the time being.

**Comment by kayvanaarssen** [comment]
I understand!
I'll open new issues as needed for more lanuages. 
Can't check at the moment but PowerShell, Bash, Phython etc. Were already in there right.

**Comment by ssddanbrown** [comment]
@kayvanaarssen Yup, All existing options

**Comment by anutator** [comment]
Please add Dockerfile, jinja2 syntax.

**Comment by ssddanbrown** [comment]
Thanks to @nutsflag this will be part of BookStack v0.30.3 (Releasing soon)

**Comment by anutator** [comment]
please add TypeScript and GraphQL syntax highlight
