### ISSUE TITLE
Language to Add Bosnian

### ISSUE THREAD

**Issue by semirteskeredzic** [BookStackApp/BookStack#2256]
### Language To Add Bosnian

Please add Bosnian language to the app. I am ready to start translating as soon as it is added to Crowdin.
The app is so great.
Thank you

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by semirteskeredzic** [comment]
@ssddanbrown Is there a way for this issue to be resolved? Thanks

**Comment by ssddanbrown** [comment]
Thanks for offering to translate @semirteskeredzic and sorry for my really late reply.

I've added Bosnian to the [crowdin project](https://crowdin.com/project/bookstack). If you've changed your mind just let me know. If little translation progress is made after a couple of months I'll likely remove it from the project and it'll need to be re-requested.
