### ISSUE TITLE
If the MAIL_FROM_NAME contains spaces it breaks Bookstack

### ISSUE THREAD

**Issue by geekedtv** [BookStackApp/BookStack#2258]
**Describe the bug**
If the MAIL_FROM_NAME contains spaces it breaks Bookstack

**Steps To Reproduce**
1. Edit the .env file and change the MAIL_FROM_NAME
2. Refresh site
4. White page until changed back to name without spaces

**Comment by mr-vinn** [comment]
It sounds like you need to quote the `MAIL_FROM_NAME` value, like this:

```
MAIL_FROM_NAME='BookStack Notifications'
```

**Comment by ssddanbrown** [comment]
Thanks for providing the solution @mr-vinn.

Does that work for you @nashosted? Have tested on my side to confirm it does on my dev setup.

I've [updated the default .env file with some commentary](https://github.com/BookStackApp/BookStack/commit/9e11fc33fa6cf657b35af97a268210ec447c59a7) to explain this to hopefully help people avoid getting confused about this in the future.

**Comment by ssddanbrown** [comment]
Will therefore close off this issue.

If the issue remains even with the solutions above please make some noise on this issue or feel free to create a new one.
