### ISSUE TITLE
S3 Bucket storage requires files to be public

### ISSUE THREAD

**Issue by homebrandcola** [BookStackApp/BookStack#226]
I setup BookStack on an Ubuntu box on AWS using ngnix. Managed to configure S3 for storage using a user created in AWS IAM that has control of the bucket.

The files are successfully being upload to S3, however they aren't shown in the BookStack app correctly.

<img width="417" alt="screen shot 2016-11-05 at 10 28 00 pm" src="https://cloud.githubusercontent.com/assets/5846428/20029680/2a5cfffa-a3a7-11e6-9044-c4fba27ed973.png">

The URL used to show the image is the S3 object URL which of course returns an 'access denied'  error from S3.

Ideally it should proxy the connection to S3, using the credentials defined in the .env as part of the setup to retrieve the image and show it in the app.

Some googling later ... I am not a developer, but it looks like it should be possible to do it within the  server {} config in nginx - sample code that is designed for a full static site:

```
server {
    listen 80;
    server_name [MY_DNS];

location * {
    set $bucket           '[MY_BUCKET]';
    set $aws_access       '[MY_AWS_KEY]';
    set $aws_secret       '[MY_AWS_SECRET]';
    set $url_full         "$1";
    set_by_lua $now       "return ngx.cookie_time(ngx.time())";
    set $string_to_sign   "$request_method\n\n\n\nx-amz-date:${now}\n/$bucket/$url_full";
    set_hmac_sha1          $aws_signature $aws_secret $string_to_sign;
    set_encode_base64      $aws_signature $aws_signature;
    resolver               MYIP valid=300s;
    resolver_timeout       10s;
    proxy_http_version     1.1;
    proxy_set_header       Host $bucket.s3.amazonaws.com;
    proxy_set_header       x-amz-date $now;
    proxy_set_header       Authorization "AWS $aws_access:$aws_signature";
    proxy_buffering        off;
    proxy_intercept_errors on;
    rewrite .* /$url_full break;
    proxy_pass             http://s3.amazonaws.com;
}
```

Making the bucket public would also solve the issue, but that would make all content on their public.

**Comment by ssddanbrown** [comment]
Hi @homebrandcola,
Upon upload of files BookStack should automatically set the individual files to be publicly accessible in s3. I'm not very experienced in S3 but my assumption as to why your files are not being made public is maybe to do with the permissions for your IAM user?

Setting up NGINX to proxy S3 would still effectively make everything public so I don't think that achieves anything other than the ability to keep the same domain for images. At the moment all uploaded images are public. Originally I tried to put them behind the application authentication layer but  booting the whole application rapidly multiple times caused many issues. I'd still like to get around this at some point but It may take a more creative solution. In the settings is an option to add a random string to file names to make images harder to find via random access.

**Comment by patoroco** [comment]
Any news with that @homebrandcola? I'm testing BookStack in local, but I need to use it in AWS, and S3 will be great (instead of use EBS in the local machine)

**Comment by ssddanbrown** [comment]
Closing due to lack of response. Feel free to still respond to my points above and I'll re-open this.
