### ISSUE TITLE
Database Issue on Upgrade to v0.30

### ISSUE THREAD

**Issue by swizzle1** [BookStackApp/BookStack#2261]
The following error came up at the end of upgrading from v0.29.3 to v0.30:

Migrating: 2020_08_04_111754_drop_joint_permissions_id

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `joint_permissions` add primary key `joint_primary`(`role_id`, `entity_type`, `entity_id`, `action`))

  at /home/ino1jdl5c9we/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      /home/ino1jdl5c9we/BookStack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:131

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      /home/ino1jdl5c9we/BookStack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129

  Please use the argument -v to see more details.

**Comment by ssddanbrown** [comment]
Hi @swizzle1,
Can you provide any details regarding your database at all?

Ideally it would be great to know the MySQL or MariaDB version in use and the table engine. Table engine can be found by running `show table status like 'joint_permissions'` on the bookstack database. Would also be ideal to know the Row Format on that table (Also shown by that command)

**Comment by vlude** [comment]
Hi Dan,
I am experiencing the same issue:
Migrating: 2020_08_04_111754_drop_joint_permissions_id

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `joint_permissions` add primary key `joint_primary`(`role_id`, `entity_type`, `entity_id`, `action`))

  at /home/vlude/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      /home/vlude/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:131

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      /home/vlude/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129

By running the above mentioned command on the bookstack DB:
![image](https://user-images.githubusercontent.com/12392970/93852245-fb13a100-fcb1-11ea-8b24-02b6f02d5bff.png)

DB version: 10.4.13-MariaDB - MariaDB Server

**Comment by swizzle1** [comment]
> Hi @swizzle1,
> Can you provide any details regarding your database at all?
> 
> Ideally it would be great to know the MySQL or MariaDB version in use and the table engine. Table engine can be found by running `show table status like 'joint_permissions'` on the bookstack database. Would also be ideal to know the Row Format on that table (Also shown by that command)

I'm running MySQL v5.6.49-cll-lve.  The engine is MyISAM.  The row format is Dynamic.

**Comment by philjak** [comment]
InnoDB will fix this

**Comment by ssddanbrown** [comment]
I don't really know if it's worthwhile trying to change this database migration for this case at this stage. I think this will mainly show up where 'MyISAM' is used. 

With MyISAM slowly fading out of usage I'd suggest upgrading the relevant table to InnoDB instead as suggested by @philjak above. This can be done, for the table in question, like so:

```sql
ALTER TABLE joint_permissions ENGINE=InnoDB;
```

Let me know if there are any issues encountered in doing this or if there any strong reasons why we might need to find an in-app strategy to fix.

**Comment by swizzle1** [comment]
Ok, thank you.  I changed it to InnoDB and will see if there are any other issues in the future.

**Comment by vlude** [comment]
Currently I am experiencing a different error, during php artisan migrate. 
Version is .30.2
Migrating: 2020_08_04_111754_drop_joint_permissions_id

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP COLUMN `id`; check that it exists (SQL: alter table `joint_permissions` drop `id`)

  at /home/ludeio/domains/ludeveger.nl/public_html/kb.ludeveger.nl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP COLUMN `id`; check that it exists")
      /home/ludeio/domains/ludeveger.nl/public_html/kb.ludeveger.nl/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:131

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP COLUMN `id`; check that it exists")
      /home/ludeio/domains/ludeveger.nl/public_html/kb.ludeveger.nl/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129
