### ISSUE TITLE
In the near future, I am going to start a public company project on aragon.org, and I hope you who are interested to participate together!

### ISSUE THREAD

**Issue by atanggeblog** [BookStackApp/BookStack#2264]
I want to add some powerful functions and build a world-class library, so that more people at home can create online, and get the benefits they deserve. Say goodbye to the original traditional publishing industry! In the near future, I am going to start a public company project on aragon.org, and I hope you who are interested to participate together!

**Comment by atanggeblog** [comment]
BookStack v0.30 is very powerful and very suitable for expanding more powerful functions. I am going to let him link IPFS.IO, Ethereum.org. Of course, this requires a lot of developers. Everyone is welcome to participate. A BookStack world-class book with complete community autonomy Pavilion!

**Comment by atanggeblog** [comment]
helpbooks.aragonid.eth

**Comment by ssddanbrown** [comment]
Hi @atanggeblog,
This reads a little like an advertisement and I can't see a specific point to help with so I'm therefore going to close this off.

If there is a specific issue to report or feature to request please feel free to open a new issue.
