### ISSUE TITLE
line break too early

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#2265]
BookStack 0.30.0
![image](https://user-images.githubusercontent.com/4026090/93891393-cd0b7c80-fd04-11ea-9cee-5cf9c0521968.png)
you can slightly adjust the styles and make it more beautiful

extra padding here
![image](https://user-images.githubusercontent.com/4026090/93891553-f6c4a380-fd04-11ea-993e-5f706ab27b87.png)

there is a lot of extra space here
![image](https://user-images.githubusercontent.com/4026090/93891648-1065eb00-fd05-11ea-85f0-547737dd054e.png)

do at least this way
![image](https://user-images.githubusercontent.com/4026090/93891758-3095aa00-fd05-11ea-997d-adddf8e1acac.png)

**Comment by ssddanbrown** [comment]
Thanks for reporting @Statium.

I've made some changes in 328d2514c4873968888022fb8dbf8ca792bbad52 to make these boxes flex to the content instead of fit to a fixed `2/3 + 1/3` layout. These changes will be part of the next patch release.
