### ISSUE TITLE
Upgraded to v0.30.0 and get "Whoops, looks like something went wrong." when saving/editing

### ISSUE THREAD

**Issue by cwldev** [BookStackApp/BookStack#2266]
So, in Bookstack I see all my entries, can view anything jsut fine (it seemed ok after the latest update based on that).

But, once I **add a new entry or try to save an edited entry in a book**, I get the above "Whoops" error with nothing else to go on. Everything was working fine before this version. (I think it was v29)

I run this on Linux using the Docker container:
linuxserver/bookstack@sha256:9d5df6d504263a6f41a0ceae25f00e563f298bbf3fd411cc7755a8ea57633287

During the update, the bookstack container logs offered this info:
Running config - db_user set
/var/run/s6/etc/cont-init.d/50-config: line 77: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 77: warning: command substitution: ignored null byte in input
Migrating: 2020_08_04_111754_drop_joint_permissions_id
Migrated:  2020_08_04_111754_drop_joint_permissions_id (0.7 seconds)
Migrating: 2020_08_04_131052_remove_role_name_field
Migrated:  2020_08_04_131052_remove_role_name_field (0.05 seconds)
Migrating: 2020_09_19_094251_add_activity_indexes
Migrated:  2020_09_19_094251_add_activity_indexes (0.15 seconds)

looking closer at various logs, I notice this error in the /bookstatck/log/ngix/error.log (edited to remove specific details): 
2020/09/22 13:47:02 [error] 548#548: *85 FastCGI sent in stderr: "PHP message: PHP Warning:  Unknown: POST Content-Length of 275 bytes exceeds the limit of 100 bytes in Unknown on line 0" while reading response header from upstream, client: 192.168.0.0., server: _, request: "POST /books/bookname/draft/76 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "books.server.com:6876", referrer: "https://books.server.com:6876/books/bookname/draft/76"

Hoping someone might help me understand more about what's going on here. Is it possible to go back to a previous version with the same database (or has the db been changed now). 

Any help appreicated, Thanks

**Comment by cwldev** [comment]
Turns out simply restarting the container and I found it working. Still testing.
More on this here: https://github.com/linuxserver/docker-bookstack/issues/64

**Comment by ssddanbrown** [comment]
Hi @cwldev, Yeah, You likely encountered the linked linuxserver.io issue. The pull request on their side to fix this has been merged so the latest containers should be fine although you may have needed a restart or two for the faulty file to be updated then picked up by the container. Will therefore close this.
