### ISSUE TITLE
Possibility for a user to subscribe/follow a page (notified of changes)

### ISSUE THREAD

**Issue by palminha** [BookStackApp/BookStack#2273]
**Describe the feature you'd like**
A way for a user to subscribe/follow a page and then he would be notified (by email) of changes made in that page

**Describe the benefits this feature would bring to BookStack users**
Would like to be notified that someone made some changes to a page.

**Comment by ssddanbrown** [comment]
Thanks for the request @palminha,
This has already been requested within #935 so I'm going to therefore close this off as a duplicate.
