### ISSUE TITLE
Setting Links inside a page using the WYSIWYG Editor at design time is brokn

### ISSUE THREAD

**Issue by cdrfun** [BookStackApp/BookStack#2278]
**Describe the bug**
When you edit a page and want to set links to different heading of that page the "Insert/Edit Link"-functionality of the editor offers you the headings available on the page. These links don't work after saving.

**Steps To Reproduce**
1. Create a new page
2. Add content and heading
3. Mark a word and press on Insert/Edit Link
4. Click in the URL text field and choose a heading
![grafik](https://user-images.githubusercontent.com/146877/94239297-dfa6d100-ff11-11ea-8401-24dcd9f14df4.png)
![grafik](https://user-images.githubusercontent.com/146877/94239338-edf4ed00-ff11-11ea-9d15-17347e85289d.png)

5 . Klick ok and save the page
6. After clicking on the link on the page nothing happens. The anchor set for the text doesn't exist
![grafik](https://user-images.githubusercontent.com/146877/94239503-36140f80-ff12-11ea-82da-1b10df54e9e9.png)

**Expected behavior**
The link should link to the correct heading.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.30
 - Hosting Method (Nginx/Apache/Docker): docker (Linuxserver.io)

**Comment by ssddanbrown** [comment]
Hi @cdrfun,
Thanks for reporting.

This is one of the WYSWYG editor features that I didn't really know existed. 
You'll find that this will work for headers that were part of previous page saves, just not fresh ones due to the way we re-assign ids ourselves.

**Comment by ssddanbrown** [comment]
Changes made in 465d405926c7e22173fe650bf2d417d4633d7990 will now mean links are updated when the ids are changed which should solve this, Therefore I'm going to close this off.
These changes will be part of the v0.30.2 patch release.

**Comment by cdrfun** [comment]
Just wanted to confirm: The bug is resolved. Thank you!
