### ISSUE TITLE
Meta title does not show complete

### ISSUE THREAD

**Issue by AngelGL** [BookStackApp/BookStack#228]
On the demo, the meta title doesn't show complete to the real title of the page:
http://i.imgur.com/zsGauHf.png
view-source:https://demo.bookstackapp.com/books/dummy-content-book/page/another-example-of-various-content

**How it has to be:** 
http://i.imgur.com/KRwLfIn.png

**Comment by ssddanbrown** [comment]
This is done on purpose to ensure overly-long titles do not get put in the title tag. The current limit set is quite short (25 chars) so would just increasing it to 48 characters be okay? I guess the real question is what's the issue with the title being cut off?

**Comment by ssddanbrown** [comment]
Closing due to lack of response. Feel free to still answer the above and I'll re-open this.
