### ISSUE TITLE
The button on the top right cannot be clicked on mobile phone view in 0.30.1

### ISSUE THREAD

**Issue by MFYDev** [BookStackApp/BookStack#2284]
**Describe the bug**
When using 0.30.1 BookStack, the top right button on mobile view cannot be clicked because of a js error

**Steps To Reproduce**
1. Install 0.30.1 BookStack
2. View it with your smart phone by Chrome or Edge
3. Go to the homepage an click on the top right button which contains the log in button

**Expected behavior**
The button should be able to be clicked and unfold to display the log in button and other functions.

**Screenshots**
<img width="273" alt="2" src="https://user-images.githubusercontent.com/53750381/94387812-d6ba3780-017d-11eb-9b80-07216b99f87f.png">
![1](https://user-images.githubusercontent.com/53750381/94387821-d9b52800-017d-11eb-86f6-99fec7a77c67.gif)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.30.1
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Hi @MFYDev,
Can you provide any version information? This does not seem to occur in my own testing.
Tested on Chrome Version 85.0.4183.121 (Desktop) and Version 85.0.4183.127 (Android Device)

**Comment by MFYDev** [comment]
@ssddanbrown Hi mate, I just upgrade the chrome and edge to the latest version on google play. 

And I found that chrome does not have this problem, but edge, which version is 45.08.4.5072, the latest, still has this issue.

I really wonder why because both of theme are chromium core. You can test it with edge.

**Comment by ssddanbrown** [comment]
@MFYDev Thanks for confirming, Have tested on android edge and confirm the same issue.

From my research, it seems that for the Android Edge build, they lag behind a bit on the chromium version in use. Currently reports as version 77 which is about a year old. 
Also had reports about recent changes breaking Firefox ESR releases, Think I need to dial back how aggressively modern JS is used or built by our tools.

**Comment by ssddanbrown** [comment]
@MFYDev I've just published [version 0.30.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.30.2) with some changes in the build system to go a little further back. Seems to solve things from my testing on my phone but could you update and let me know if that solves this for you?

**Comment by MFYDev** [comment]
It seems that Edge and Firefox have deliberately kept their kernel versions old for maximum stability and compatibility. Thank you for your quick reply and powerful update！:D

**Comment by ssddanbrown** [comment]
Thanks for confirm this was fixed @MFYDev.

Will therefore close.
