### ISSUE TITLE
Drawings - draw.io breaking

### ISSUE THREAD

**Issue by Kabe0** [BookStackApp/BookStack#2285]
When you click the drawing button in the editor, it appears to present a broken image. The URL throws a 301 redirect

![image](https://user-images.githubusercontent.com/6827834/94445103-0d3f8480-0175-11eb-8c4b-2b2361efd694.png)

If you open the link in the browser draw.io say's the following 
![image](https://user-images.githubusercontent.com/6827834/94445194-2a745300-0175-11eb-87cf-36f935275aa1.png)

**Comment by nutsflag** [comment]
Hello,
What is your version? 
Thanks

**Comment by Kabe0** [comment]
BookStack v0.30.1, though it also happens on the demo on the main Bookstack website.

Seems to affect only Chromium based browsers right now.

**Comment by nutsflag** [comment]
Okay,

I just tested with Firefox, Google Chrome and Edge with the demo version. 

I didn't have any problem.

**Comment by Kabe0** [comment]
![image](https://user-images.githubusercontent.com/6827834/94456217-762cf980-0181-11eb-9ea6-2d4440fb1a97.png)
Chrome version: 85.0.4183.102

**Comment by nutsflag** [comment]
![image](https://user-images.githubusercontent.com/26460023/94456939-33d0e000-01b4-11eb-94d1-4e7c2eb9fae4.png)

I just tried with Chromium (Version 87.0.4277.0). I don't have any problem. 

For my Chrome version : Version 85.0.4183.121 (Official Build)
No errors either.

**Comment by Kabe0** [comment]
You sure your not cached? The issue is caused by this line specifically **x-frame-options: SAMEORIGIN** which stops cross frame iframe displaying. Do you see this line in the response headers?

**Comment by Kabe0** [comment]
works!

**Comment by nutsflag** [comment]
Does it work with modification?

**Comment by Kabe0** [comment]
Yep, it works as expected on existing and new ones.

**Comment by ssddanbrown** [comment]
As of [BookStack v0.30.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.30.2) the default URL has now been updated to be the diagrams.net embed URL.

Thanks for your time in helping here @nutsflag.
