### ISSUE TITLE
Link books to shelves in the API

### ISSUE THREAD

**Issue by Legoracers** [BookStackApp/BookStack#2287]
Currently it is possible to link chapters to books using the API, it is a mandatory option. It isn't yet possible to link books to shelves using the API.

**Comment by ssddanbrown** [comment]
Hi @Legoracers,
You should be able to use the Shelves update request (PUT) to link a shelf to books.
From the docs:

![image](https://user-images.githubusercontent.com/8343178/94744763-6f64d900-0371-11eb-93ec-cf601522506c.png)

Let me know if you experience any trouble using that. Note that it does mention that it will overwrite existing book assignments so, depending on what you're doing, you may need to read the shelf first to get its current assignments.

**Comment by Legoracers** [comment]
Thank you for the response! I will try it shortly and will let you know.

**Comment by Legoracers** [comment]
It worked, thanks!
