### ISSUE TITLE
Sharing or Permissions per book / page

### ISSUE THREAD

**Issue by AntonyPritchett** [BookStackApp/BookStack#229]
Desired Feature: The ability to assign certain pages, chapters, books to a role or even share to individual users

Are there any plans for features along these lines?

**Comment by ssddanbrown** [comment]
Hi @AntonyPritchett,
Currently you can restrict permissions on individual books, chapters & pages to specified user groups by going to the permissions screen found in the menu at the top-right of the page when viewing a book, chapter or page.

You cannot currently do this at a user level. Does this cover your use-case or do you need something different?

**Comment by ssddanbrown** [comment]
Closing due to lack of response. Feel free to still answer the above and I'll re-open this.

**Comment by Rdnaskel** [comment]
Hi. Sorry for posting here and there, it just happens that if I google something about BookStack that goes beyond docs I stumble upon a github issue. Is group/role-only sharing is still the case? No sharing for individual users?

**Comment by ssddanbrown** [comment]
> Is group/role-only sharing is still the case? No sharing for individual users?

That's correct, currently permissions are based on roles only.

**Comment by Rdnaskel** [comment]
@ssddanbrown any chance that user based sharing will be added? Or that's not a desirable scenario in case of BookStack?
