### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2290]
**Describe the bug**

Undo feature isn't working, can undo only once

**Steps To Reproduce**
1.Create/Edit Page
2.type somthing
3.undo with ctrl+z/button
4.wait til its saves draft
5.type something
6.undo

**Expected behavior**
the undo button/key combination isn't working if the document is saved as draft.
even though the undo button is still lit up.
and the page is saved at exact time of history save, that meaning you can only undo once.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.30.1
 - PHP Version: 7.2.24
 - Hosting Method (Nginx/Apache/Docker):  Nginx

**Additional context**
it seems after the page is saved it deletes the history

**Comment by ssddanbrown** [comment]
Hi @Zyzto,
Thanks for reporting this suspected issue.

I've done a quick test in my dev environment and I have not been able to reproduce. Is this issue consistent for you? If so, Please could you confirm the, operating system, browser and browser version you're able to replicate this on?

**Comment by Zyzto** [comment]
@ssddanbrown I have this issue on multiple hosting
I tested firefox 80.0.1, brave 1.14.84 and chrome from at least 2 week old version

On latest bookstack version.

**Comment by Zyzto** [comment]
it's working with new update (0.30.2v), I don't know what happened.
