### ISSUE TITLE
Code block Nesting when it shouldn't 

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2292]
**Describe the bug**
Code block is nesting and you can't edit previous settings

**Steps To Reproduce**
1.Create/edit page
2.input text
3.make it codeblock
4.make it again code block it will now switch to code lines
5.make it codeblock it will now become one line with nested borders after the 4th~5th time of repeating this

**Expected behavior**
Every time I click codeblock or press CTRL+E, it should display the highlighted code block and be able to change settings

**Your Configuration (please complete the following information):**
- Exact BookStack Version (Found in settings): BookStack v0.30.1
- PHP Version: 7.2.24
- Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Hi @Zyzto,
Thanks for reporting.

I've managed to replicate this issue but only when inside a list, Are you able to replicate this outside of lists?

**Comment by Zyzto** [comment]
@ssddanbrown I haven't noticed it,but yeah it only happened in lists only. Just tested it.

**Comment by ssddanbrown** [comment]
@Zyzto Thanks for confirming. I think case I'll close this off since it's really dependant on the request of code being supported within list blocks.
