### ISSUE TITLE
Code block not allowed with another text in ordered list 

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2293]
**Describe the bug**
when entering code block inside ordered list you can't have text in same step even if you create new line with Shift+Enter

**Steps To Reproduce**
1. Create/Edit Page
2. Make ordered list
3. Type text
4. Press shift+enter
5. try to enter codeblock

**Expected behavior**
the ability to have code block in same list number and even in same line

**Your Configuration (please complete the following information):**
- Exact BookStack Version (Found in settings): BookStack v0.30.1
- PHP Version: 7.2.24
- Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Hi @Zyzto,
Thanks for your request. The request to allow code blocks within lists is already open under #534 so I'll therefore close this off as a duplicate.
