### ISSUE TITLE
Add feature of collapse content.

### ISSUE THREAD

**Issue by 1vicente** [BookStackApp/BookStack#2295]
**Describe the feature you'd like**
Add feature of collapse content (images, diagrams, tables, code blocks, links and so on) on pages. 

**Describe the benefits this feature would bring to BookStack users**
Turn easier longer pages visualization and faster to find specific contents.

**Additional context**
Maybe it can be a new buttom in Formats menu drop, **like this**:
![image](https://user-images.githubusercontent.com/13755048/94713222-e3c35c00-0320-11eb-9d20-82539d09900c.png)

**Example Collapse content on page**:
![image](https://user-images.githubusercontent.com/13755048/94703661-752cd100-0315-11eb-9952-83bf9ebc8bb5.png)
Reference: [https://open.berkeley.edu/guides/site-builders-guide/edit-html-page/expandcollapse-conten](https://open.berkeley.edu/guides/site-builders-guide/edit-html-page/expandcollapse-content)

**Comment by ssddanbrown** [comment]
Thanks @1vicente for the request.

This is already open under #78 so I'm going to therefore close this off as a duplicate.
