### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by robertlandes** [BookStackApp/BookStack#230]
### Desired Feature:
Are there any plans to support other languages than English?
Although I probably can't help with developing the localisation support, I could support by translating into German language.

**Comment by robertlandes** [comment]
Okay, i checked the sources and found that there is actually multi language support already implemented. I am working on the German (formal) translation right now and will create a pull request, once I am finsihed.

**Comment by ssddanbrown** [comment]
HI @robertlandes,
Language support has already been opened under #115 so I will therefore close this issue.

Thanks for offering German translations. Currently, only a small portion of the text in BookStack is in the `resources/lang` folder, ready for translation. After the next release I will be pushing forward to moving much more or all text into these files to be translated. Therefore it may be better to wait until all text is ready to translate. If you have already done some work feel free to open pull requests though as any help now is still appreciated :+1:

**Comment by robertlandes** [comment]
Hi @ssddanbrown,

sorry for the duplicate issue. I actually already finished the translation and would add it, however I am not allowed to. Created a local branch "localization-de" and now that I try to do a pull request, I get a "permission denied" ;) (sorry, not a super experienced dev here, more an ops guy).

Any advise how to add my translations?

Thanks,

Rob

**Comment by ssddanbrown** [comment]
@robertlandes No worries on the duplicate issue.

To create a pull request fork the BookStack repo on github so you have your own copy. Push your new branch to that copy then create a pull request via the GitHub UI.

Digital Ocean has a good tutorial on the whole process if that helps:
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by hahmed09** [comment]
Hey guys, product is amazing! any plans to localise for arabic? that also requires RTL support: https://en.wikipedia.org/wiki/Right-to-left

**Comment by ssddanbrown** [comment]
Hi @hahmed09,
Experimental arabic support was released in v0.24, You just need to set `APP_LANG=ar` in your `.env` and/or select arabic as your language in your profile area when logged in.

**Comment by hahmed09** [comment]
Awesome, thanks @ssddanbrown will check it out :)
