### ISSUE TITLE
No scrolling in Shelves edit Mode on Touch device (iPAD)

### ISSUE THREAD

**Issue by sunnybeats** [BookStackApp/BookStack#2301]
**Describe the bug**
If Edit an existing shelve with content on an iPad (Safari) and have a look at the „Sort books“ or „add books“ section. Then you can not scroll in this fields, your are moving the books all the Time and can noct scroll down.

**Steps To Reproduce**
1. An Existing Shelve with some Books in it
2. Click on edit in the navigation
3. Try to scroll in the books list
4. you will have no scroll bars and no chance to scroll

**Screenshots**
![IMG_0092](https://user-images.githubusercontent.com/57019865/94924665-43a33980-04be-11eb-8b94-3f19086dd27f.jpeg)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.30.2
 - PHP Version: php7.4
 - Hosting Method (Nginx/Apache/Docker): Apache 

Hope there is an easy way to solve it ;-)

**Comment by sunnybeats** [comment]
Does anyone else can confirm this problem?

**Comment by ssddanbrown** [comment]
Thanks for reporting @sunnybeats,
Can confirm this. Think we'll need to limit drag/drop sorting to handle, at least on mobile, to allow a touch region for scrolling.
Have assigned to be looked at in a future feature release.

**Comment by ssddanbrown** [comment]
This has now been addressed in ccbc68b5600790546e073546a31b8123d5693411 and will be part of the next feature release.
