### ISSUE TITLE
Unable to upload images using a domain name

### ISSUE THREAD

**Issue by pvvqla** [BookStackApp/BookStack#2304]
Hi there!

That is my problem 

![imagen](https://user-images.githubusercontent.com/47861041/94993812-d1048d80-0593-11eb-927c-faa5bba713c2.png)

I received this server 0 code error when I try to upload any file. 

The error appears just when I use a domain name, when I enter using the IP it works perfectly.

I am using cloudfare  and traefik .

Please anyone can help?

Logs has no errors.

**Comment by nutsflag** [comment]
Hello @pvvqla ,

Can you do a test without using cloudflare ? (Disable Proxied and use DNS resolution only)

Thanks for your reply.

**Comment by ssddanbrown** [comment]
Thanks @nutsflag for providing assistance here. Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
