### ISSUE TITLE
Change the Domain

### ISSUE THREAD

**Issue by dugaa95** [BookStackApp/BookStack#2305]
Hi,

how I can change Domain on my BookStack Server?

My Bookstack Server is now example.xx.com and i want do change in example.yy.com

I try to change Domain in /etc/apache2/sites-enabled then nano bookstack.conf but is not going?

Thanks
Regreds!!!

**Comment by nutsflag** [comment]
Hello @dugaa95,

did you change the line in the .env ?

# Application URL
# Remove the hash below and set a URL if using BookStack behind
# a proxy or if using a third-party authentication option.
# This must be the root URL that you want to host BookStack on.
# All URL's in BookStack will be generated using this value.
APP_URL=https://your.domain.name

**Comment by ssddanbrown** [comment]
Also check that you've restarted apache after making config changes.

**Comment by dugaa95** [comment]
> Hello @dugaa95,
> 
> did you change the line in the .env ?
> 
> APP_URL=https://your.domain.name

Thank you so much!

**Comment by dugaa95** [comment]
.

**Comment by asdert92** [comment]
In current version in same .env file we found a example of how do it with an artisan command:
`php artisan bookstack:update-url https://old.example.com https://new.example.com`
