### ISSUE TITLE
Ensure "images with dots in file-name" error message shows localised message

### ISSUE THREAD

**Issue by DevMimas** [BookStackApp/BookStack#2306]
**Describe the bug**
A graphic drawn in diagrams.net and exported as png file cannot be inserted as an image. It is always said that it is a wrong file extension. Unfortunately I can't describe it better because it works strangely with other png images.

Would be important to fix it quickly.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to page
2. Click on insert image
3. Insert png picture 

**Screenshots**

![grafik](https://user-images.githubusercontent.com/44207756/95021533-cf10fc00-0671-11eb-80a2-9404d1476832.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version v0.30.2
 - PHP Version: PHP/7.3.22
 - Hosting Method (Nginx/Apache/Docker): docker and the image is `linuxserver/bookstack:v0.30.2-ls106`

**Comment by DevMimas** [comment]
Okay, false alarm. I had a dot in the file name, that was the problem. It works.

On the other hand, the translation for it is completely missing. DE selected EN displayed. Also the error message is a bit minimalistic, I think.

**Comment by ssddanbrown** [comment]
I've given this a test, User-facing message seems to be translated as expected when using both types German available. 

Error message could indeed be clearer, but there's an existing issue to handle this different so don't want to cause time spent on changing error messages if it'll be soon redundant.
