### ISSUE TITLE
Revision changes view is broken

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2309]
**Describe the bug**
Revision changes view is broken it shoes weird text and misinformation and out of bond highlighting

**Steps To Reproduce**
1.create page
2.save it
3.reopen it
4.edit it
5.view changes made

**Expected behavior**
for it to display in correct format and correct information.

**Screenshots**
![image](https://user-images.githubusercontent.com/13531154/95196411-b3783380-07e0-11eb-9da3-08683db20f80.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):0.30.2
 - PHP Version:7.2.24
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Thanks for reporting this @Zyzto.

This very much looks like what was found in #1553 so I'm going to close this off as a duplicate. Even if not, We're completely changing the HTML diffing library for the next release so the output will likely be different, if not now correct.
