### ISSUE TITLE
Search not in the Center

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2310]
**Describe the bug**
Search bar is not in the middle of screen and move to the left when hiding the title

**Steps To Reproduce**
1.settings
2.remove title

**Expected behavior**
for the search bar to be in the cetner

**Screenshots**
![image](https://user-images.githubusercontent.com/13531154/95203555-97c65a80-07eb-11eb-9559-da0f5d4862db.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):0.30.2
 - PHP Version:7.2.24
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Additional context**
I have custom banner image and custom title

**Comment by ssddanbrown** [comment]
Thanks for raising @Zyzto.

I've just committed 4f96cd91648a4f50aa691d7c26c1fd09f66838e6 which should keep the search bar centered until it's pressured to move out by right or left elements. This will be part of the next feature release.
