### ISSUE TITLE
Let user choose whether a Page is Markdown or WYSIWYG

### ISSUE THREAD

**Issue by mateja82** [BookStackApp/BookStack#2312]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.
We've been using Bookstack for a while, mostly for technical docs. Since we have a lot of Dev and Ops, as well as non technical people, there's been a demand to both use Markdown, and use 
WYSIWYG (or whichever editor Bookstack ends up using by default). 

**Describe the benefits this feature would bring to BookStack users**
Technical users who use Git or Spoenx would have an easy way to copy paste the docs, and non technical users wouldn't have to struggle with "#" and other MD particularities. 

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @mateja82  , Thank you for your request.

I feel that this is already covered by the existing issues #119, #369 & #842.
Therefore I'm going to close this to reduce duplicates.

Note that an editor review and alignment phase [is planned on the roadmap](https://github.com/BookStackApp/BookStack#%EF%B8%8F-road-map).
