### ISSUE TITLE
Draw.io integration broke after an update to 0.30.2

### ISSUE THREAD

**Issue by mateja82** [BookStackApp/BookStack#2313]
**Describe the bug**
Since we updated Bookstack last week, we cant use draw.io.

We're using Markdown. The issue exists ONLY if your editor is Markdown.

**Expected behavior**
It opens the platform, but won't let us save the diagram. 

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.30.2
 - PHP Version: PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
 - Hosting Method (Nginx/Apache/Docker): NGINX

**Comment by ssddanbrown** [comment]
Thanks for report @mateja82.
Can confirm this.
Will look to wrap this up in a patch release as soon as I can gain the time. 

Note to self: Looks due [this change in the id](https://github.com/BookStackApp/BookStack/commit/3bfd26bf86ebf2d325bbb90b2a2879aa5d33f95b#diff-1f2d050ca41f561a1248db9f99ff19be256691b4da77509a0fea91e7d97f4050L1-R1) which is not accounted for in the script.

**Comment by ssddanbrown** [comment]
This has been fixed in bb1f1a9ecd1687e867b40f7f4a3441bce825e979 and will be part of v0.30.3 which will be released shortly.
