### ISSUE TITLE
Special tags show/hide toggle and pagination

### ISSUE THREAD

**Issue by quildcrest** [BookStackApp/BookStack#2316]
1.
**Describe the feature you'd like**
A toggle button to hide/show some special tags.
Most of ancient Chinese articles need to put annotations after  some words in the main text. It looks like this:
**軒轅之時，神農氏世衰。**`<small>`【note1】皇甫謐曰：「易稱庖犧氏沒，神農氏作，是爲炎帝。」班固曰：「教民耕農，故號曰神農。」【note2】世衰，謂神農氏後代子孫道德衰薄，非指炎帝之身，即班固所謂「參盧」，皇甫謐所云「帝榆罔」是也。【note 3】《帝王世紀》云：「神農氏，姜姓也。母曰任姒，有蟜氏女，登爲少典妃，遊華陽，有神龍首，感生炎帝。人身牛首，長於姜水。有聖德，以火德王，故號炎帝。初都陳，又徙魯。又曰魁隗氏，又曰連山氏，又曰列山氏。」《括地志》云：「厲山在隨州隨縣北百里，山東有石穴。（曰）〈〔昔〕〉神農生於厲鄉，所謂列山氏也。春秋時爲厲國。」`</small>`**諸侯相侵伐，暴虐百姓，而神農氏弗能征。於是軒轅乃習用干戈，以征不享，**
Usually I put the notes in [quoteblock] or `<small></small>`. The toggle is used to show/hide the notes.

**Describe the benefits this feature would bring to BookStack users**
The readers don't need to see the notes all the time. If there is a toggle button somewhere, it will be a good choice for those who need this feature.

**Additional context**

2.
**Describe the feature you'd like**
The paging function allows users to control the content ("page" in BookStack) displayed in different pages.

**Describe the benefits this feature would bring to BookStack users**
It is very useful for some long articles in Chinese, maybe in Japanese also.

**Additional context**

**Comment by quildcrest** [comment]
Usually I put the notes in [quoteblock] or `<small></small>` tag.

**Comment by ssddanbrown** [comment]
Hi @quildcrest,

Thanks for your request. 

For 1. We already have a request in issue #78 for toggle-able/collapsible show/hide blocks. This sounds like it would achieve the same thing?

For 2. I don't really want to have pagination within a BookStack "page". I think that could easily cause confusion and works against the current design structure/metaphor. I'd rather recommend that you split larger pages into multiple smaller pages.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up or further discussion I'm going to close this.
