### ISSUE TITLE
HTML error 500: not sure where to even begin

### ISSUE THREAD

**Issue by ThSGM** [BookStackApp/BookStack#2318]
**Describe the bug**

I had Bookstack working for several weeks on my Ubuntu 14.04.6 LTS system (yes I realise this is quite old but I am loathed to update). However, today I suddenly received HTTP error 500 when trying to access the website. 

**Steps To Reproduce**

1. Go to the website.

**Expected behavior**

The Bookstack was working just fine until recently.

**Your Configuration (please complete the following information):**
 - Bookstack version: v0.29.3
 - PHP Version: 7.3.21
 - Hosting Method (Nginx/Apache/Docker): Apache (I think)

**Additional context**

I'm not sure if it's helpful but I'll copy a few lines from the laravel.log file

```
2020-08-26 00:45:05] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'database_username'@'localhost' (using password: YES) (SQL: select * from information_schema.tab$
[stacktrace]
#0 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('select $
#1 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run('select * from i...',$
#2 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * $
#3 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\M$
#4 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(590): Illuminate\\Database\\Migrations\\DatabaseMigratio$
#5 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(91): Illuminate\\Database\\Migrations\\Mig$
#6 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(63): Illuminate\\Database\\Console\\Migrat$
#7 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#8 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closu$
#10 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closu$
#11 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Objec$
#12 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(BookStack\$
#13 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#14 /var/www/mydomain.com/public_html/BookStack/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input$
#15 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symf$
#16 /var/www/mydomain.com/public_html/BookStack/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvI$
#17 /var/www/mydomain.com/public_html/BookStack/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\$
#18 /var/www/mydomain.com/public_html/BookStack/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\$
#19 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfon$
#20 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony$
#21 /var/www/mydomain.com/public_html/BookStack/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfo$
#22 {main}
```

**Comment by Vanillabacke** [comment]
Same issue on Ubuntu 18.04.5 LTS‬

**Comment by ThSGM** [comment]
I examined [the issue linked here](https://github.com/BookStackApp/BookStack/issues/672) and it was suggestred by @ssddanbrown to use `tail -f /var/log/apache2/error.log`. 

Upon doing so I get: 

`[Sun Oct 11 18:02:09.090995 2020] [php7:error] [pid 390] [client 176.223.11.5:54397] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/mydomain.com/public_html/BookStack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27\nStack trace:\n#0 /var/www/mydomain.com/public_html/BookStack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:host=loca...', 'bookstack', 'mypassword', Array)\n#1 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=loca...', 'bookstack', 'mypassword', Array)\n#2 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=loca...', 'bookstack', 'mypassword', Array)\n#3 /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illumin in /var/www/mydomain.com/public_html/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 669, referer: http://www.mydomain.com/`

**Comment by ThSGM** [comment]
@Vanillabacke 

I am not sure what was the issue but reading [this thread](https://askubuntu.com/questions/224298/mysql-not-starting), I tried the following:

`sudo service mysql status`

which informed me 

`mysql stop/waiting`

I then did this

`sudo /etc/init.d/mysql restart`

and it said

```
stop: Unknown instance:
mysql start/running, process 14768
```

and now things seem to be working again. Again I am not sure what caused the issue but it is perhaps not a Boosktack issue.

**Comment by ssddanbrown** [comment]
Thanks @ThSGM for confirming you found a solution. Will therefore close this.

@Vanillabacke On Ubunutu 18.04 you might need to instead run `sudo systemctl restart mysql`. You should be able to see the status of the database with `sudo systemctl status mysql`. Feel free to open a new issue if the above does not resolve your issue.
