### ISSUE TITLE
Combine Social Login with LDAP

### ISSUE THREAD

**Issue by ehv1** [BookStackApp/BookStack#2319]
We are using Bookstack with LDAP login, to also fetch the groups for a user.
When using social login (in our case Azure), the groups are not synced, because no group information is parsed with social login.
It would be nice if there's an option to do an LDAP query after SOCIAL LOGIN succeeds to fetch the group membership for the current user.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @ehv1.

To be totally honest, I really don't want to complicate authentication by mixing mechanisms in any way, These systems already take a lot of effort to maintain without considering features that span options. 

Therefore I'm going to close this off but I'm thinking the core issue could be possibly solved in a different manner, such as the one described in https://github.com/BookStackApp/BookStack/pull/2288.
