### ISSUE TITLE
nothing happens during draw save

### ISSUE THREAD

**Issue by badsmoke** [BookStackApp/BookStack#2321]
**Describe the bug**
nothing happens during draw save

since the last update i can't create a drawing anymore, if you want to insert a drawing the editor appears and after pressing the save button nothing happens.

So the drawing is neither saved nor inserted in the bookstack

<--
**Steps To Reproduce**
is already written above

**Expected behavior**

the drawing should fit into the page

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.30.2
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker):  docker

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @badsmoke,
Could I confirm the editor that you're using. Are you using the WYSIWYG page editor or the Markdown page editor? (If unsure then a screenshot of the page-edit screen would help.)

**Comment by badsmoke** [comment]
i use the markdown editor

![image](https://user-images.githubusercontent.com/24853712/95818355-f9bf1c80-0d23-11eb-894c-152b5be57a1b.png)

**Comment by ssddanbrown** [comment]
Thanks for confirming @badsmoke.
This has already been reported under #2313 so I'll therefore close this off as a duplicate.
As said on that issue, I'm aiming to get a fix out soon to cover this.
