### ISSUE TITLE
New home for helm chart?

### ISSUE THREAD

**Issue by JoshKCarroll** [BookStackApp/BookStack#2322]
**Describe the feature you'd like**
A new home for the BookStack helm chart which is currently hosted on helm's `stable` but being marked obsolete in a few weeks.

**Describe the benefits this feature would bring to BookStack users**
Community continues to be able to run BookStack in Kubernetes using a public helm chart.

**Additional context**
With helm `stable` and `incubator` being deprecated in a few weeks (see https://github.com/helm/charts/issues/21103), there won't be a canonical helm chart available any more for running eventrouter.

Anyone thinking about hosting one? I recognize that @ssddanbrown probably does not have the bandwidth, but this seems like a good place to discuss if other folks in the community are interested in it. @verwilst and @solidnerd I believe that y'all did most of the work the `stable` version of this chart, not sure if you might have any ideas.

**Comment by ssddanbrown** [comment]
Just to confirm my position, I would not want this within the official BookStack repos as I try to keep away from supporting infrastructure components outside of a few Linux LTS scripts. 

Happy to leave this open for a bit though for visibility. 

Is there any way to see usage at all to get an idea if it's worth someone spending their time?  Can see a couple of issues here mention helm charts but have not come across it outside of that.

**Comment by verwilst** [comment]
Hello,

I'm ok with maintaining it. How do we get started?

Kind regards,

Bart
________________________________

**Comment by JoshKCarroll** [comment]
Awesome!! Thank you Bart!! Based on the discussion [here](https://github.com/helm/chartmuseum/issues/356#issuecomment-708742123) I believe there are some instructions for the best way to do it, but I don't have the link. I made a comment asking about it and tagged you, I'm hoping one of the `helm/charts` maintainers will respond. I may be picking up another one myself so will be trying to find them one way or another...

Dan to your question about usage, I looked around but unfortunately it seems that they don't expose any public metrics about it from the chart registry.

**Comment by JoshKCarroll** [comment]
Ah, @verwilst I found the instructions:

https://github.com/prometheus-community/helm-charts/issues/3#issue-679666169

https://github.com/helm/charts-repo-actions-demo

**Comment by ssddanbrown** [comment]
Since any discussions or further volunteers here have dried up, I'll close this off.

**Comment by pchang388** [comment]
I know this thread is old and apologies for digging through it again. I was looking for a helm chart to also deploy my own personal instance of bookstack on k3s. I found that most of the existing charts are no longer maintained or missing the ability to customize. I know a lot of users may be wary of using bookstack on K8, but with pvc backups (via longhorn storageProvider) and file level backups, I have running, it is pretty stable for me and I already have built-in ways to do DR.

I've been working on a more up to date helm chart with github actions for tagged releases. This adheres to the new standards and requirements for tagged releases using github-pages:


Bookstack specific chart [here](https://github.com/homeylab/helm-charts/tree/main/charts/bookstack)
All charts [https://github.com/homeylab/helm-charts](https://github.com/homeylab/helm-charts)

Chart includes mariadb from bitnami as an optional dependency (enabled by default) and I try to keep the image up to date and test things properly before releasing with `chart-testing`. Hope it helps!
