### ISSUE TITLE
Abandoned Packages by jakub-onderka

### ISSUE THREAD

**Issue by bridgeyuwa** [BookStackApp/BookStack#2323]
**I got the following message when I was installing the current release via composer** 

`Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.`

**Comment by ArlorNaturalScientific** [comment]
Hello,
I just updated to 0.31.1 version.
I have the same message, and this one too:

`Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.`

**Comment by Luxame** [comment]
Hi
I in the light of "Ubuntu 20.04 Installation Script" to install v0.31.4 version
have get same message :
```
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
```

I install system version :

```
$ uname -a
Linux ip-172-31-0-12 5.4.0-1035-aws #37-Ubuntu SMP Wed Jan 6 21:01:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by ssddanbrown** [comment]
Just to confirm, there are kind of expected for the time being until potentially being able to upgrade the version of the framework used which may towards the end of the year at the earliest.

The packages reported are primarily for development or command line use, so are not a particular concern.

**Comment by ssddanbrown** [comment]
I don't believe these messages will show now on the latest releases so will close this off.
