### ISSUE TITLE
An Error Occurred - ('The stream or file "%s" could not be opened: '.$this->errorMessage, $this->url)?

### ISSUE THREAD

**Issue by labratrace** [BookStackApp/BookStack#2324]
**Expected behavior**

**Screenshots**
https://imgur.com/a/eZgsaTG

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): Uh... wish I knew :(
 - PHP Version: PHP 7.4.9
 - Hosting Method (Nginx/Apache/Docker):  nginx/1.18.0

**Additional context**
So I'm still a bit new to this.  But I recently had to move my Bookstack software to a new server.  And I received the error I see above.

Nginx is up, database is up, php looks like it's up and running.  So I'm not sure what it is I should be looking for to resolve this issue and get bookstack up and running.

Edit: I enabled debugging on the server and, to be honest, I'm not sure what I'm looking at.

**Comment by nutsflag** [comment]
Hello @labratrace,
checks the permissions on files and folders.  also try by putting 755 to test.

**Comment by labratrace** [comment]
I found a similar page discussing this issue.  I currently have permissions set to 777 on storage.  Checking everything, but that didn't seem to change much.

**Comment by ssddanbrown** [comment]
Hi @labratrace,
Sorry for my lack of reply, Do you still have this issue? If so, could you provide the output of running `ls -alh storage/logs` from your BookStack install folder (Assuming a unix/linux system is in use here).

That error is fairly specific to permissions of that log file shown.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
