### ISSUE TITLE
Page Navigation In Editor

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2325]
**Describe the feature you'd like**
Page Navigation In Editor, like view page

**Describe the benefits this feature would bring to BookStack users**
Faster and easier editing

**Comment by niklasgrewe** [comment]
i think this could be done with [Editor.js](https://editorjs.io/) It would be awesome, when i can choose between 

* WYSWYG (TinyMCE)
* Markdown
* Inline (Editor.js)

as an idea

**Comment by ssddanbrown** [comment]
Thanks for the request @Zyzto.

Since this is already open under #2210 I'm going to close this off as a duplicate.
