### ISSUE TITLE
Feature Requests & bug : slug name setting

### ISSUE THREAD

**Issue by pinglanyue** [BookStackApp/BookStack#233]
book/chapter/page name work fine in the url when use English or other language like 'mọi người'.
But Chinese ,Japanese.... are wrong:
if you change  book./chapter description and any content in page(haven't change title name),the url will auto change.like this:
![](https://images.mondedie.fr/WHHwwcFi/6s0eYMqs)

should add a slug name setting beside  title name setting to avoid this.
slug testeare can auto input slug name like now url's slug.but if use Chinese or other can auto input,user can comster input in .
I think it is a bug .Because if you create another book's page ,and insert a Chinse page's url link to get information,if the Chinese (title) page change ,the link will dead.

Test in : demo.bookstackapp.com

**Comment by ssddanbrown** [comment]
@pinglanyue Thanks for reporting this issue.

I have updated the slug system to open it up to allow almost all UTF8 characters (including Chinese and Japanese). I have removed the bug that forces slug changes on every chapter/book save.

This will be pushed out in the next release (Likely going live tomorrow).
