### ISSUE TITLE
Cannot upload profile pictures

### ISSUE THREAD

**Issue by NeaChimeraYoungspace** [BookStackApp/BookStack#2330]
**Describe the bug**
Everytime I try to change my user profile picture, and error occurs and the picture does not change.

**Steps To Reproduce**
Click on Profile picture in the top right.
Then click on profile and scroll down until you come to the user avatar section.
Now upload a image file (I tried it with a .png)
Finally click on Save

Now I see a page with:

An Error Occurred
An unknown error occurred

**Expected behavior**
After clicking on save the user should have his selected image as his profile picture.

**Screenshots**
![bookstack error](https://user-images.githubusercontent.com/64079948/96373080-7742bc80-116a-11eb-96d9-89e9c7dc2ae5.PNG)

**Your Configuration (please complete the following information):**
 - BookStack v0.30.3 
 - PHP Version: Did not find it, sry
 - Hosting Method: hosted via Docker (in Unraid)

**Comment by qwertyuu** [comment]
Just changed mine, works well

**Comment by ssddanbrown** [comment]
Hi @NeaChimeraYoungspace,
Sorry to hear you're experiencing issues. 
Please see details here on how to gain more information for debugging: https://www.bookstackapp.com/docs/admin/debugging/

Additionaly, It would be good to know if you have this problem for all image uploads (Page images, app logo in the settings etc..) or if it's just on profile images.

**Comment by dawolf** [comment]
I have fixed this problem by deleting `bootstrap/cache/config.php` as mentioned here: https://github.com/BookStackApp/BookStack/issues/2458#issuecomment-757353428

**Comment by ssddanbrown** [comment]
Thanks for offering a solution @dawolf.

Since there has been no further discussion from the issue creator I'll close this off.
