### ISSUE TITLE
Latvian Language Support

### ISSUE THREAD

**Issue by RMednis** [BookStackApp/BookStack#2331]
Hello, I just realised that language requests have to be done through GitHub. 
I've used bookstack a lot internally and would like to help translating it to Latvian, since that's what users are most comfortable with around here. I already have a Crowdin account, and can start as soon as the language is added.

Thanks in advance!
### Language To Add

Latvian

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by pilsetnieks** [comment]
Seconding the request, I would also like to contribute and give my users the possibility to use BookStack in their native language.

**Comment by ssddanbrown** [comment]
Thanks for offering to translate both and sorry for my really late reply.

I've added Latvian to the [crowdin project](https://crowdin.com/project/bookstack). If you've changed your mind just let me know. If little translation progress is made after a couple of months I'll likely remove it from the project and it'll need to be re-requested.
