### ISSUE TITLE
Image paths

### ISSUE THREAD

**Issue by sharma-akshay** [BookStackApp/BookStack#2332]
Hi,

I had setup Wiki on one server and now I copied the whole Wiki directory and database on another server. The Wiki server is working properly, but for the images it is still referring to old server path. 

Do I need to change some config file or update any table. Please let me know. Also is there any other better way to migrate Wiki data from one server to another.

Thanks,
Akshay Sharma

**Comment by cdrfun** [comment]
You can update the image urls with
`php artisan bookstack:update-url <oldUrl> <newUrl>`

The command is documented here: https://www.bookstackapp.com/docs/admin/commands/

**Comment by sharma-akshay** [comment]
> You can update the image urls with
> `php artisan bookstack:update-url <oldUrl> <newUrl>`
> 
> The command is documented here: https://www.bookstackapp.com/docs/admin/commands/

Thanks for the quick response.

**Comment by sharma-akshay** [comment]
> php artisan bookstack:update-url <oldUrl> <newUrl>

Is there any other clean way of migrating Wiki server from one server to another.

**Comment by cdrfun** [comment]
Idk what you are aiming for, but there is no "all in one" process if that's what you mean. You'll have to manually move the database, the config and upload files and apply the url command, if the url has changed. The process is dependent on how you host bookstack.

**Comment by ssddanbrown** [comment]
Thanks for providing the quick response here @cdrfun. Will therefore close this off since it's been answered.
