### ISSUE TITLE
Allow disabling of the default registration role option

### ISSUE THREAD

**Issue by mikeyz24** [BookStackApp/BookStack#2338]
I'm running Bookstack v0.30.3.  I have LDAP sync turned on and working along with AD Group sync.  Group Sync is working fine but I noticed that the "default user role after registration" gets applied to each user in addition to their AD group.  Is there a way to turn this off?  I just want to apply the AD Group to each user.

**Comment by awarre** [comment]
Just ran into the same issue. Unintuitive if you have Registration disabled and want to just use LDAP (which is nearly always going to be the case when using LDAP).

"Default user role after registration" applies to all new LDAP users, which by default makes every new user a BookStack administrator.

For now I'm working around by setting the default role to "Public".

**Comment by moqmar** [comment]
It seems like by default the role is empty, Admin is just the first one that's selected, so saving the settings sets it as a value - maybe adding an empty value to the select field is enough already to fix this issue?

**Comment by ssddanbrown** [comment]
Thanks @moqmar, This was indeed the case. 

This has now been addressed in 17215431caec61334cd653e030ba3b42c7ef2ca1.
You'll now be able to effectively disable the default registration role by choosing a `-- None --` option.
This will be part of the next patch release.
