### ISSUE TITLE
Getting 404 not found on resources.

### ISSUE THREAD

**Issue by Niquify** [BookStackApp/BookStack#2339]
**Describe the bug**
I've been trying to recover a BookStack installation from a backup for a client on a Plesk server. I don't have any configuration files that I could use and the domain hasn't changed. When entering the website it's missing all css and js files and you can see they're all giving a 404 error. I followed the manual installation right before the php artisan migrate step.

**Steps To Reproduce**
1. Go to the website.
2. All assets are missing.

**Expected behavior**
The website can properly find and load the files from dist/

**Screenshots**
![image](https://user-images.githubusercontent.com/8874280/96750868-c851eb00-13cc-11eb-8209-59981e9087d5.png)
![image](https://user-images.githubusercontent.com/8874280/96750900-d273e980-13cc-11eb-9698-67cf48657cd9.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.30.3
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Apache. Using Plesk.

**Additional context**
I added the following config to Apache:

```
ServerAdmin admin@example.com
DocumentRoot /var/www/vhosts/{domain}/{subdomain}.{domain}/public
ServerName {domain}

<Directory /var/www/vhosts/{domain}/{subdomain}.{domain}/public/>
	Options FollowSymlinks
	AllowOverride All
	Require all granted
</Directory>
```
If I don't have this config, I can go to domain.com/public/login and it works fine, though that's not the recommended configuration.

![image](https://user-images.githubusercontent.com/8874280/96751338-56c66c80-13cd-11eb-8151-803d5481fbb3.png)

The BookStack installation seems to work, but it won't load any files.

**Comment by ssddanbrown** [comment]
Hi @Niquify,
Sorry for my late response, Are you still experiencing issues?

If so, double check that the `.env` file and check the `APP_URL` value aligns with the URL you're now hosting BookStack on, including the starting http/https part. 

Failing that, we'll need to see what URL bookstack is trying to access the resources on, by looking at the page source.

If you are accessing the instance with `public` in the URL then it's likely that you could have an insecure configuration unless specific care has been made.

**Comment by Niquify** [comment]
Hey @ssddanbrown,
The APP_URL value matches the URL for bookstack.

The resources that are returning 404 are being accesed on APP_URL/dist/, ex: example.com/dist/file.js

![image](https://user-images.githubusercontent.com/8874280/102637934-09f5dc80-4157-11eb-9faf-178d4473ff7d.png)

**Comment by ssddanbrown** [comment]
@Niquify Okay, What do you see when you attempt to directly go to the URL `https://<domain>/dist/app.js`?

**Comment by Niquify** [comment]
@ssddanbrown I get a 404 Not Found 
![image](https://user-images.githubusercontent.com/8874280/102640033-2d6e5680-415a-11eb-81c9-988889560a95.png)

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Comment by mrdarrengriffin** [comment]
I'd like to re-open this if possible. I am using Plesk but when I navigate to the resource directly, I get the 404 page but with no CSS, ironically.
![image](https://user-images.githubusercontent.com/6920899/108866345-087be100-75ec-11eb-8cfa-87c3138b0fb2.png)

**Comment by mrdarrengriffin** [comment]
My bad, I was on the development branch and not release.
