### ISSUE TITLE
[Feature Request] Multi-language documents

### ISSUE THREAD

**Issue by fernandozap2** [BookStackApp/BookStack#2340]
**Describe the feature you'd like**
I'd like to make another version of my documents in another languages. So if you access a multi-language document you could see an option to change it for the languages that it were translated.

**Describe the benefits this feature would bring to BookStack users**
It would be better than make a new Book/Chapter with another language. Easier to update and translate the documents.

**Comment by ssddanbrown** [comment]
Thanks for this request @fernandozap2.

This has already been requested in #569 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #569 it will help show support for that request.
