### ISSUE TITLE
Issues getting OKTA to work. 

### ISSUE THREAD

**Issue by nat-webdev** [BookStackApp/BookStack#2344]
I seem to be getting issues when i follow https://www.bookstackapp.com/docs/admin/third-party-auth/#okta to get okta to work with instance of self hosted book stack. Can not find any documentation except this. When I click the okta link it takes me to my instance but does not login. I have removed all the sensative info. Have i missed a step to get my okta integrated?

<img width="735" alt="Screenshot 2020-10-23 at 16 54 21" src="https://user-images.githubusercontent.com/53788312/97025761-6a4e1080-1550-11eb-9d02-523657d8000a.png">

**Comment by ssddanbrown** [comment]
Hi @nat-webdev,
It looks like you're editing the `app/Config/services.php` file. These files should not be altered unless you're intending to make deeper, non-supported changes to your instance.

Instead, revert any changes in the `app/Config/services.php` file (Let me know if you need guidance on that) then, all changes should made in the `.env` file within your install. This file might be hidden by default depending on system.
You'd add the options, shown in the documentation, to this file and customize there.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
