### ISSUE TITLE
php-tidy el8

### ISSUE THREAD

**Issue by jordanenglish** [BookStackApp/BookStack#2347]
I'm trying to install BookStack on RHEL8 and get going down various holes of research trying to get php-tidy to work.

PHP installed version from Red Hat for RHEL8 is 7.2.24. 

Even going to a site looking for the package turns up no results:https://pkgs.org/download/php-tidy

I have seen a few guides mention using Remi repo, but I don't feel comfortable using that for production.
http://rpms.remirepo.net/enterprise/8/remi/x86_64/

Any ideas?

```
# /usr/local/bin/composer install
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
> @php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires PHP extension ext-tidy * but it is missing from your system. Install or enable PHP's tidy extension.
  Problem 2
    - gathercontent/htmldiff is locked to version 0.2.1 and an update of this package was not requested.
    - gathercontent/htmldiff 0.2.1 requires ext-tidy * -> it is missing from your system. Install or enable PHP's tidy extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
    - /etc/php.d/20-bz2.ini
    - /etc/php.d/20-calendar.ini
    - /etc/php.d/20-ctype.ini
    - /etc/php.d/20-curl.ini
    - /etc/php.d/20-dom.ini
    - /etc/php.d/20-exif.ini
    - /etc/php.d/20-fileinfo.ini
    - /etc/php.d/20-ftp.ini
    - /etc/php.d/20-gd.ini
    - /etc/php.d/20-gettext.ini
    - /etc/php.d/20-iconv.ini
    - /etc/php.d/20-json.ini
    - /etc/php.d/20-mbstring.ini
    - /etc/php.d/20-mysqlnd.ini
    - /etc/php.d/20-pdo.ini
    - /etc/php.d/20-phar.ini
    - /etc/php.d/20-simplexml.ini
    - /etc/php.d/20-sockets.ini
    - /etc/php.d/20-sqlite3.ini
    - /etc/php.d/20-tokenizer.ini
    - /etc/php.d/20-xml.ini
    - /etc/php.d/20-xmlwriter.ini
    - /etc/php.d/20-xsl.ini
    - /etc/php.d/30-mysqli.ini
    - /etc/php.d/30-pdo_mysql.ini
    - /etc/php.d/30-pdo_sqlite.ini
    - /etc/php.d/30-wddx.ini
    - /etc/php.d/30-xmlreader.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by fexxes** [comment]
I am sorry that i cant directly help, But this was two weeks ago a reason for me to switch from centos 8 to Debian 10, 

Maybe someone with more knowladge can show you a way on RHEL. I was totaly new to a RPM system and just give it a try. 

On Debian 10 it the intallation works like a charm.  Not sure this can help you.

**Comment by ssddanbrown** [comment]
I'm afraid that without compiling your own PHP source you might be out of luck without wanting to use the remi repo.

Generally the dependency on lib-tidy has proved to be a pain for some environments. 
It was only really used by a package for generating diffs between revisions.

This weekend I've ported a c# library to PHP for use in BookStack from the next release:
https://github.com/ssddanbrown/htmldiff/

**Comment by ssddanbrown** [comment]
Since the new non-tidy-reliant library has now been implemented I'll close this off. This change will be part of the next feature release v0.31.
