### ISSUE TITLE
Button enable / disable

### ISSUE THREAD

**Issue by tobiaspihale** [BookStackApp/BookStack#2350]
I would like to be able to disable / enable the Books and Shelfs Button on the Topbar of the page

In our case the users should navigate through the main screen / the shelfs not through the top navigation because it is easier for them

<img width="595" alt="Bildschirmfoto 2020-11-02 um 13 01 50" src="https://user-images.githubusercontent.com/26013858/97866207-c9a7df80-1d0b-11eb-88b9-5133874ccaf2.png">

**Comment by tiredofit** [comment]
@tobiaspihale You can handle that by making a custom theme as outlined here: https://www.bookstackapp.com/docs/admin/hacking-bookstack/

I believe you can get what you need by modifying `common/header.blade.php`

**Comment by ssddanbrown** [comment]
As another quicker alternative, You can add the following to the "Custom HTML Head Content" input found in the settings page:

```html
<style>
/* Hide shelves link */
header nav a[href$="/shelves"] {
	display: none;
}

/* Hide books link */
header nav a[href$="/books"] {
	display: none;
}
</style>
```

I wouldn't look to implement fine-grained UI options/controls for doing this but instead utilise flexible unofficial hackery as provided in the two options provided, therefore I'll close this off.
