### ISSUE TITLE
Maintenance > Cleanup Images: Wording is ambiguous

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#2352]
<img width="910" alt="Bildschirmfoto 2020-11-03 um 21 13 34" src="https://user-images.githubusercontent.com/3104762/98035905-791ea800-1e19-11eb-92a2-ada6864b777a.png">
The option „Ignore images in revisions“ has an ambiguous meaning in my opinion. It can both mean

- a)„ignore the images in earlier versions of the pages, so leave them untouched and do NOT delete them“ and

- b) „don't give a sh*t about these images and earlier versions of the pages, just delete them, regardless to what that means, when one wants/needs to revert to an earlier page version!“ (which is what this option actually does)

In order to make this option less ambiguous, I would retitle it to: **„Also delete images only found in previous page revisions“** (or in german: „Bilder, die nur in vorherigen Seiten-Versionen vorkommen, ebenfalls löschen“)

**Comment by ssddanbrown** [comment]
Thanks again for reporting @Wookbert.
I totally agree, My wording here it terrible. Marked to be changed for next release.

**Comment by Wookbert** [comment]
I wonder if this „Delete Images from previous page versions“ option should/could be a bit smarter, e.g. so that one can revert to at least a/the last version with images still in tact. Would require a bit of thinking...

**Comment by ssddanbrown** [comment]
Now updated in 4e82d93350c28bb8667f9cac262c4103b7345e62 ready for next release so will therefore close. Thanks again @Wookbert.

> I wonder if this „Delete Images from previous page versions“ option should/could be a bit smarter, e.g. so that one can revert to at least a/the last version with images still in tact. Would require a bit of thinking...

That could be a smart idea, probably best to do it based on time (Revisions in the last x days rather than last revision) but I think that'd be optimizing a corner of the system that has little traffic.
