### ISSUE TITLE
Support Multipage draw.io diagrams

### ISSUE THREAD

**Issue by donnib** [BookStackApp/BookStack#2357]
**Describe the feature you'd like**
draw.io supports multiple pages drawings. I would like to be able to see the other pages of the diagram than the first one. 

**Describe the benefits this feature would bring to BookStack users**
You can have more advanced diagrams.

**Additional context**
Read more about this how it's supported in Confluence which also uses draw.io here : https://drawio-app.com/draw-io-for-confluence-multi-page-diagrams/

Here is a screenshot of the feature in Confluence : 
![drawio-6-2-page-navigation-1-1-300x212](https://user-images.githubusercontent.com/252702/98342173-52769200-2010-11eb-87d7-858b70a8b003.png)
![drawio-6-2-Navigate-Pages-1-300x226](https://user-images.githubusercontent.com/252702/98342178-530f2880-2010-11eb-878d-0f0f26f8ec4e.png)

**Comment by ssddanbrown** [comment]
Hi @donnib,
Please see my thoughts regarding this functionality here:
https://github.com/BookStackApp/BookStack/issues/2294#issuecomment-701604448

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
