### ISSUE TITLE
Copy / Paste image from clipboard into Markdown page

### ISSUE THREAD

**Issue by dean-mrack** [BookStackApp/BookStack#2361]
Hi, please, can you to consider implementing the ability to insert an image from clipboard when generating a markdown page. That would be sooo convenient.

v0.30.4

**Comment by ssddanbrown** [comment]
Hi @dean-mrack,
This should already be possible if you have image data on the clipboard. I can’t remember if it’s possible to copy/paste image files from the OS, Might depend on system and browser, Remeber there being something awkward there.

Could you confirm whether you’re attempting to paste image data or an image file? Also confirming your operating system & browser will help here.

**Comment by dean-mrack** [comment]
Wow, its greatefulll, its work ! )
Windows 10, FireFox 82.

Sorry, but i was sure it didn't work. tried to insert a picture several times. I must have done something wrong. Thank you for your work, very aesthetic and functional application. I like it. )))

**Comment by ssddanbrown** [comment]
Thanks @dean-mrack for confirming, I'll therefore close this off.
