### ISSUE TITLE
Add icons to pages

### ISSUE THREAD

**Issue by LilTrublMakr** [BookStackApp/BookStack#2362]
**Describe the feature you'd like**
Ability to add icons to the content in a page.

**Describe the benefits this feature would bring to BookStack users**
 It would allow users to add icons to their pages. Very useful if you are documenting a mobile app that uses icons.

**Additional context**
I have searched the issues, the documentation, and on Google to see if there is a way that we can add icons to pages and have not found a solution.

I am exploring using Bookstack as a documentation application because my current one is hitting its limits. Sometimes, I use icons because some of my documentation includes mobile apps. Right now, the only way I can think of to do something similar would be to make it an image and then upload it. To me, that would be a waste of resources since there are definitely icons being loaded as a whole. It would also be a bonus if I can style the icons to be able to match the style of the application.

**Comment by ssddanbrown** [comment]
Thanks for the request @LilTrublMakr,

Personally I’ve become fairly strict when it comes to insertable content to ensure it remains as simple and non complex as possible to ensure people’s content remains portable. My issue with icons would be how to retain that thinking. 

As you’ve said, Images could be used here. I don’t really know what’s meant by this line:
> that would be a waste of resources since there are definitely icons being loaded as a whole

Images will add little overhead in reality and I can’t imagine that people’s desired icon set will align with BookStack’s use of icons, Not that I’d look to have page content rely on BookStack’s icon set anyway. 

Embeddable SVGs come to mind as a standard method of embed, you could probably already use these in the markdown editor, but icon placement and desired controls may complicate things, especially so if people desire icons to show inline with text.

**Comment by LilTrublMakr** [comment]
What I mean about the resources comment is that it would use resources in both space and CPU to insert an image than it would be to just use an icon that is already loaded in to the icon sets that you use (I believe I saw somewhere that you use the Google icon set). Unless you only load the icons that you use, the resources I am requesting is already there. Just need to have a way to be able to access them. It's just my way of thinking. 

I do see that there is a way to insert an icon set in to the header so I guess I will have to explore that route.

**Comment by ssddanbrown** [comment]
Okay. The icons we use are directly embedded svgs, so re-using the same icons won't really save any CPU and space for a few extra icons is rarely a concern. I would not really be interested in exposing this icon set for use within page content anyway since they're really just for the UI trim and not intended to be stable. As you have found. using the "Custom HTML Head" content will be the best bet.

I'm going to close this off, as I don't really see us supporting icons outside of some level of embedded SVGs, for which there's already an existing issue for SVG support.
