### ISSUE TITLE
无法使用自建的gitlab进行第三方登录

### ISSUE THREAD

**Issue by campnou-44** [BookStackApp/BookStack#2364]
你好，我在使用gitlab第三方登录的时候，跳转总是跳向gitlab.com，而不是我自己的gitlab地址，请问这是哪个地方出现了错误

**Comment by ssddanbrown** [comment]
Hi @campnou-44,
Can you confirm if you have set the `GITLAB_BASE_URI` option in your `.env` File?

**Comment by campnou-44** [comment]
是的，我十分确定，我在.env文件中设置了GITLAB_BASE_URL=http://mygitlab.com，但是总是跳转向gitlab.com这个地址

**Comment by campnou-44** [comment]
现在又出现了另外一个问题，跳转之后总是会显示Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.我的key和secret都是正确的，为什么会出现这种情况呢

**Comment by ssddanbrown** [comment]
I've just created a self-hosted gitlab setup to ensure this authentication still works for self hosted and all works as expected.

Some things to check:

1. If you have any php files within the `bootstrap/cache/` folder you can try deleting these.
2. Are you still being directed to `gitlab.com` or is that part now fixed? 
3. Are you creating an "Application" like in the screenshot below? 

![image](https://user-images.githubusercontent.com/8343178/101700041-44cf8480-3a74-11eb-98ba-d3d279eace56.png)

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
