### ISSUE TITLE
Pictures with relativ paths

### ISSUE THREAD

**Issue by Stiles96** [BookStackApp/BookStack#2366]
**Describe the feature you'd like**
By inserting a picture, the hole URL (absolute path) will be save to the page, e.g. https://bookstack.com/uploads/picture1.jpg. It makes problems by using a local domain and a public domain. Best is to save the relativ path e.g. /uploads/picture1.jpg.

**Describe the benefits this feature would bring to BookStack users**
You can see the picture by using every domain (internal and external)

**Comment by ssddanbrown** [comment]
Thanks for the request @Stiles96,
BookStack does currently only support being hosted on a single domain.
There are existing issues for relative paths  #1342 #1137.
There are also open requests for being able to use multiple domains  #2008.

Therefore I’m going to close this off as a duplicate.
