### ISSUE TITLE
“Sharing on <dd. mm. jjjj> by <first name Last Name>" and “Checked on <dd. mm. jjjj> by <first name Last Name>"

### ISSUE THREAD

**Issue by MorpheusSohn** [BookStackApp/BookStack#2369]
**Describe the feature you'd like**

In BookStack I would still like to have the possibility of approval and examination. Then you could use BookStack as a productive environment in the school context. 

**Describe the benefits this feature would bring to BookStack users**

A student creates an hourly log in BookStack. Then the student draws up the protocol – it could be checked and released by the specialist teacher after he was able to assess it professionally.

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for the request @MorpheusSohn, 

BookStack is not primarily intended for an education environment, so I wouldn't really look to implement any education specific features or have education-specific workflows being a primary driver for a new feature.

I could see how a general approval/review flow may benefit BookStack users in general though.
There are some existing features related to an approval/review flow: #2123 and #473.
Therefore I'm going to close this off as a duplicate.

**Comment by MorpheusSohn** [comment]
@ssddanbrown The use in educational institutions was just one example - with this option BookStack would have features of a quality management system (QMS), which I would if there were, for example, an export to and an import from .odt and .md files. Since I'm unfortunately not that good at programming, I don't know to what extent it would be feasible.
