### ISSUE TITLE
[Feature Request] Microsoft SQL Integration

### ISSUE THREAD

**Issue by athornfam2** [BookStackApp/BookStack#2371]
**Describe the feature you'd like**
I'm requesting that the developers look into bringing Microsoft SQL integrations as an option for Bookstack

**Describe the benefits this feature would bring to BookStack users**
For those that own and operate either a SQL Developer or Production environment will have a lot of benefits. Personally for me, I would rather not have multiple databases under multiple different open-sourced products. Open Source is great but for me and some others that use SQL at home and Work it would be nice to integrate this program into that as an additional database.

**Comment by ssddanbrown** [comment]
Thanks for the request @athornfam2.

Unfortunately I'm going to close this off as out of scope, at least at this time.
Over the past 5 years we have had some requests for SQLite and Postgres but MSSQL support has been little requests so I'm fairly confident it won't be worth the implementation and maintenance, especially for a database that is fairly (Although lesser so nowadays) platform dependant.

My thoughts on additional database support in general can be seen here:
https://github.com/BookStackApp/BookStack/issues/76#issuecomment-494956958
