### ISSUE TITLE
v0.30.4: PHP Parse error during update 

### ISSUE THREAD

**Issue by tomasjay** [BookStackApp/BookStack#2378]
Dear Dan,

I have tried to update to v0.30.4.
When running `composer install --no-dev` installing files works fine. But then there is a message saying:

      - Installing robrichards/xmlseclibs (3.1.1): Downloading (100%)         
      - Installing onelogin/php-saml (3.4.1): Downloading (100%)         
    Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
    Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
    Generating optimized autoload files
    > Illuminate\Foundation\ComposerScripts::postAutoloadDump
    PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
    
    Parse error: syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416

The next steps (`php artisan migrate` etc.) do not work. They end with the same error message. 

Do you have an idea what my problem is? Unfortunately, I cannot tell you which was my old version of BookStack, probably v0.28. Running `php version` is already saying "v0.30.4".

I have no idea on how to roll back, and BookStack (which is heavily used as our company's Wiki) is down. Your advice is appreciated.

Best, 
Thomas

**Comment by ssddanbrown** [comment]
Hi @tomasjay,
Could you confirm the operating system you're using (To host BookStack)?
Additionally it would be good to know what version of PHP you're using. `php version` is simply printing out the BookStack version file, You should be able to use `php -v` to get the full php version info.

**Comment by tomasjay** [comment]
Hi Dan,

operating system is Ubuntu 16.04 LTS 64bit.
PHP version is

    PHP 7.0.30-0 ubuntu0.16.04.1 (cli) ( NTS )

Ok, I see, PHP update to min version 7.2 required with BookStack v0.28 or higher.
Is it recommended to update the entire OS or is enough to update PHP?

Best regards,
Thomas

**Comment by ssddanbrown** [comment]
@tomasjay You can update just PHP to the latest stable version without needing to update the whole operating system.

The following commands, ran one at a time, should install php7.4:

```
sudo add-apt-repository -y ppa:ondrej/php
sudo apt update
sudo apt install -y php7.4 php7.4-fpm php7.4-curl php7.4-mbstring php7.4-ldap php7.4-tidy php7.4-xml php7.4-zip php7.4-gd php7.4-mysql
sudo systemctl restart apache2.service
```

Note, if you host other PHP applications on the same machine they may be effected by this upgrade.

**Comment by tomasjay** [comment]
@ssddanbrown thank you. update to php version 7.4 done. 
    PHP 7.4.12 (cli) (built: Oct 31 2020 17:03:53) ( NTS )

an owncloud application on the same server works fine.

then i repeated the installation steps starting with 
    git pull origin release && composer install --no-dev && php artisan migrate

i restarted apache. 

but it seems that the update is not complete. 
`git pull` quits with `Already up-to-date`.  
`composer install` says `Nothing to install or update` (see line 6 below).

    Do not run Composer as root/super user! See https://getcomposer.org/root for details
    > @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
    > @php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
    Loading composer repositories with package information
    Installing dependencies from lock file
    Nothing to install or update
    Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
    Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
    Generating optimized autoload files
    > Illuminate\Foundation\ComposerScripts::postAutoloadDump
    > @php artisan package:discover --ansi
    Discovered Package: barryvdh/laravel-dompdf
    Discovered Package: barryvdh/laravel-snappy
    Discovered Package: facade/ignition
    Discovered Package: fideloper/proxy
    Discovered Package: intervention/image
    Discovered Package: laravel/socialite
    Discovered Package: nesbot/carbon
    Discovered Package: nunomaduro/collision
    Discovered Package: socialiteproviders/manager
    Package manifest generated successfully.
    > @php artisan cache:clear
    Application cache cleared!
    > @php artisan view:clear
   Compiled views cleared!

However, I continued with php artisan migrate.

    Migrating: 2019_07_07_112515_add_template_support
    Migrated:  2019_07_07_112515_add_template_support (0.31 seconds)
    Migrating: 2019_08_17_140214_add_user_invites_table
    Migrated:  2019_08_17_140214_add_user_invites_table (0.2 seconds)
    Migrating: 2019_12_29_120917_add_api_auth
    Migrated:  2019_12_29_120917_add_api_auth (0.08 seconds)
    Migrating: 2020_08_04_111754_drop_joint_permissions_id
    Migrated:  2020_08_04_111754_drop_joint_permissions_id (0.55 seconds)
    Migrating: 2020_08_04_131052_remove_role_name_field
    Migrated:  2020_08_04_131052_remove_role_name_field (0.22 seconds)
    Migrating: 2020_09_19_094251_add_activity_indexes
    Migrated:  2020_09_19_094251_add_activity_indexes (0.07 seconds)
 
At the end I did `php artisan cache:clear` and `... view:clear` as well as an apache restart.

OwnCloud is still up, BookStack is not ... 
Web inspector shows that nothing was loaded except for an (additional) external stylesheet.

Any idea?

**Comment by ssddanbrown** [comment]
@tomasjay What do you see when you attempt to access BookStack? BookStack error page? A different error page?

**Comment by tomasjay** [comment]
@ssddanbrown no, i see nothing except a white page. no error message. 

i looked into the web inspector in safari, and nothing was loaded except for an (additional) external stylesheet. this is probably still there from the last load when bookstack was still up. 

i started BookStack on firefox as well. and it delivers an empty page indeed.

**Comment by ssddanbrown** [comment]
@tomasjay Blank white pages can often be from permission issues.

You could try to change the required location to be owned by the server by running the below:

Navigate to your BookStack installation folder before running this.

```bash
sudo chown -R www-data:www-data bootstrap/cache storage public/uploads
```

**Comment by tomasjay** [comment]
@ssddanbrown thank you for your help. i did this, but unfortunately nothing changed.

**Comment by ssddanbrown** [comment]
@tomasjay Okay, Let's check the logs now to see what might be going wrong. 
If you go to `/var/log/apache2/` and list the files there with `ls` do you see a file named `error.log` or something BookStack specific like `bookstack-error.log`?

**Comment by tomasjay** [comment]
@ssddanbrown seems i can cd to /var/log. but i cannot switch to apache2. 

`permission denied`.

**Comment by ssddanbrown** [comment]
@tomasjay  Okay, might have to be root. You can peek inside with `sudo ls /var/log/apache2/`.

**Comment by tomasjay** [comment]
@ssddanbrown ok, i see the content of the folder. but there are no BookStack specific files in it. 
only several access.log, error.log and other_vhosts_access.log files.

**Comment by ssddanbrown** [comment]
@tomasjay In that case, run:

```
sudo tail -f /var/log/apache2/error.log
```

You will go into a mode where you'd see the latest lines of this file, in addition to any updates made live.
with that running, Refresh the bookstack page and see if anything gets added/shows-up.
You can press `q` or `Ctrl+C` to stop following that file for changes and return to the command line.

**Comment by tomasjay** [comment]
@ssddanbrown ok, here the last lines of error.log:

    [Wed Nov 18 22:30:18.545564 2020] [:error] [pid 23507] [client 93.217.165.22:57253] PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
    [Wed Nov 18 22:40:56.554099 2020] [:error] [pid 23512] [client 93.217.165.22:57382] PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
    [Wed Nov 18 23:10:06.015301 2020] [:error] [pid 23513] [client 93.217.165.22:58388] PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
    [Wed Nov 18 23:10:27.833174 2020] [mpm_prefork:notice] [pid 23497] AH00169: caught SIGTERM, shutting down
    [Wed Nov 18 23:10:28.982899 2020] [mpm_prefork:notice] [pid 23950] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
    [Wed Nov 18 23:10:28.982973 2020] [core:notice] [pid 23950] AH00094: Command line: '/usr/sbin/apache2'
    [Wed Nov 18 23:10:34.206833 2020] [:error] [pid 23953] [client 93.217.165.22:58391] PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
    [Wed Nov 18 23:11:13.414683 2020] [:error] [pid 23955] [client 93.217.165.22:58402] PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
    [Wed Nov 18 23:15:55.026704 2020] [:error] [pid 23962] [client 93.217.165.22:58462] PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
    [Wed Nov 18 23:16:04.953514 2020] [:error] [pid 23954] [client 93.217.165.22:58465] PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416

seems to be the same error as during installation (see above):

    PHP Parse error:  syntax error, unexpected '=' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416

**Comment by ssddanbrown** [comment]
@tomasjay Okay, It's possible that apache is still using the old php version. Could you run the following command and provide the output?:

```
apachectl -V | grep MPM
```

**Comment by tomasjay** [comment]
@ssddanbrown 

    AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/000-default-le-ssl.conf:
SSLCertificateFile: file '/etc/letsencrypt/live/(server address)/fullchain.pem' does not exist or is empty

I'm looking into this atm.

it's a bit strange, because owncloud is running fine on https.

**Comment by ssddanbrown** [comment]
@tomasjay Odd, Might not be a major error.

For changing the PHP versions, You can try running these commands and see if BookStack loads afterwards:

```bash
sudo a2dismod php7.0
sudo a2enmod php7.4
sudo service apache2 restart
```

**Comment by tomasjay** [comment]
@ssddanbrown that did the trick!!! wow.

**Comment by ssddanbrown** [comment]
@tomasjay Awesome, I'm just glad you got it going. Again, Give owncloud a check over to make sure that's okay after changing php versions. 

Just a warning for the future, If you had previously changed the upload limits you might be to do that again ("Changing Upload Limits > PHP" section):
https://www.bookstackapp.com/docs/admin/upload-config/#changing-upload-limits

The php7.4 install likely has it's own separate `php.ini` file.

**Comment by tomasjay** [comment]
@ssddanbrown thanks for the hint regarding ownCloud.

< This version of ownCloud is not compatible with PHP 7.1.
You are currently running 7.4.12. Please use at least ownCloud 10.0.0.>

seems to turn into a night shift
:-D  

yes, i'll check the upload limits setting.

thank you once more!

**Comment by tomasjay** [comment]
@ssddanbrown look here: https://companeer.com
;-)

**Comment by ssddanbrown** [comment]
> @ssddanbrown look here: https://companeer.com
> ;-)

😆 Thanks
