### ISSUE TITLE
Support Google Adsense Sharing

### ISSUE THREAD

**Issue by bridgeyuwa** [BookStackApp/BookStack#2383]
I am suggesting that **Adsense sharing program** feature should be added to bookstack to encourage registered users to contribute more in the wiki.

If they get paid a percentage or all of the Adsense earnings from their work contributed, they will be more enthusiastic to continue.

https://developers.google.com/adsense/host/revenuesharing

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @bridgeyuwa, But I really don't want to get involve any monetary systems like ad-sense in the core project in any way. I get that a minor portion of current BookStack instances may benefit for such a change, but I think that portion will be so small that it won't be worth the integration, maintenance and support. Meanwhile it would open us up to other similar money-involved requests/features and it would likely make BookStack more attractive to those looking to quickly throw up a revenue-generating scheme, who would stretch out the limited support we can offer even further and would generally be an audience I would not want to attract.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion, and I don't see this going much further, I'll close this off.
