### ISSUE TITLE
第三方登录出现错误

### ISSUE THREAD

**Issue by campnou-44** [BookStackApp/BookStack#2390]
An error has occurred
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
当我使用gitlab进行第三方登录的时候，明明填写了正确的key，却发生了错误，是因为我在scope勾选框那个地方勾选了东西吗，可是不勾选又无法创建应用

**Comment by ssddanbrown** [comment]
Closing this since  #2364 is already open.
