### ISSUE TITLE
Change Page's permissions to only owner can edit

### ISSUE THREAD

**Issue by csongs** [BookStackApp/BookStack#2391]
Hi,
Thanks for developing Bookstack, it is a useful platform that almost meets my needs. 

I setting ldap authentication for my team and default user role after registration is **Editor** (asset permissions edit for all).

How do I set page if author only **owner** can edit ?

My current setting is that default user edit for own, and then the respective pages are set to edit the asset permissions for all.

![image](https://user-images.githubusercontent.com/14192944/100834977-d1dc7180-34a7-11eb-8754-7681c984ae5f.png)

**Comment by ssddanbrown** [comment]
> Thanks for developing Bookstack, it is a useful platform that almost meets my needs.

Awesome, Thanks!

> How do I set page if author only owner can edit ?

To be honest I'm not 100% sure from that sentence, what you're attempting to achieve. You can only set the "Own" permissions with a role, Any overrides you set at a page-level will apply for a whole role, So in your screenshot all editors will be able to edit that page.

There are some existing issues open regarding providing more control, For example:

- #2246 is open to allow the "Owner" of a page to be changed so make the "Own" permissions more useful.
- #1747 is open to allow user-specific permissions be assigned at a page/chapter/book/shelf level.

**Comment by 10935336** [comment]
> To be honest I'm not 100% sure from that sentence

It looks like csongs is trying to make the page/chapter/book/shelf editable only by the creator/author/owners of the page. And this feature is not available in the permission management of the page itself.

I think it would be good to add a permission to the permissions management of the page itself that only the owner itself can edit. You can imagine a knowledge base where everyone has editing permissions, but certain personal pages or important public pages don't want others to edit them. This can now be done, but with the creation of an additional role.
So basically it is #1747

**Comment by ssddanbrown** [comment]
Thanks for your interpretation @10935336.

Since I think this issue is covered, or at least dependant, on the above referenced issues I'm going to close this off for now.
