### ISSUE TITLE
Update WYSIWYG editor to TinyMCE 5

### ISSUE THREAD

**Issue by 10935336** [BookStackApp/BookStack#2395]
**Describe the feature you'd like**
Update to TinyMCE 5. 

**Describe the benefits this feature would bring to BookStack users**
I noticed that TinyMCE 4.x support will end in December 31, 2020, so maybe it's time to migrate to TinyMCE 5.
In addition, upgrading to TinyMCE 5 brings a bunch of new easy-to-use features that I think we should upgrade to if we don't have coding problems.

**Additional context**
https://www.tiny.cloud/blog/tinymce-4-support-window/
https://www.tiny.cloud/docs/migration-from-4x/

**Comment by kayvanaarssen** [comment]
With that update maybe also enable more options for advanced users. I think Bookstack has now many options disabled for a cleaner UI

@ssddanbrown Maybe check the upgrade path with your thoughs on other improvements of the editor and much requested auto Markdown support without needing to make codeblocks of them😊

**Comment by ssddanbrown** [comment]
Thanks for the request @10935336.

It's unlikely we will migrate to TinyMCE 5 though. 

An "Editor Alignment & Review" stage is on the roadmap to be looked at after the REST API. As part of that there will be a review of the editors themselves. Therefore I don't feel it's worth spending the time migrating at this stage.

As with #1649 and #1661 I'll keep this open for now as an editor suggestion but I'll likely merge it up into a wider editor-review issue/discussion in the future.

**Comment by ssddanbrown** [comment]
As mentioned above, Closing this in favour of #2738
