### ISSUE TITLE
Integration with Nextcloud

### ISSUE THREAD

**Issue by Baptistou** [BookStackApp/BookStack#2397]
**Describe the feature you'd like**
We could provide an integration with Nextcloud in 3 steps :
- [ ] Provide a SSO authentication with Nextcloud with Oauth2 support for example (#1390)
- [ ] Create a BookStack app on Nextcloud to provide an easy access to a wiki. For now, I use [External Sites](https://apps.nextcloud.com/apps/external) as a convenient way to link BookStack, but it would be awesome to have further integration with for example [Dashboard](https://apps.nextcloud.com/categories/dashboard) or inside the File interface.
- [ ] Add ability to browse from/save into Nextcloud when inserting images and file attachements to a wiki page

**Describe the benefits this feature would bring to BookStack users**
BookStack is an amazing open-source wiki software and Nextcloud is a powerful open-source file storage software.
They are both installed on my server and it would bring huge benefits if they could interact with each other.

**Comment by ssddanbrown** [comment]
Thanks for the request @Baptistou.

To be totally honest, I'd personally consider this out of scope, apart from the auth which I'd only consider if not NextCloud specific, for which an issue is already open as you have linked. 

The effort to do the second and third points well would likely not be worth the effort, support and maintenance required for the small portion of the user base that may happen to use both platforms to benefit from such additions. 

Don't wanna be too close minded on this though as I may be missing something so I'll leave this open for a while so feedback can be given but I'll likely close this off after a few months.

**Comment by Baptistou** [comment]
Yeah, I know this requires a huge effort while BookStack is still in beta version. Still, I am just amazed what a good project it is and a Nextcloud integration could greatly increase its visibility. Nextcloud lacks a wiki software, contrary to Office 365, and I think BookStack will greatly improve the open-source ecosystem.

See the discussion :  https://help.nextcloud.com/t/intranet-wiki-app/6416/11

> Ideally there would be an easy integration with Bookstack

> I would definitely love to see Bookstack as an app in nextcloud +1000

If you need help, I would be very interested in getting involved there. :smile:

**Comment by ssddanbrown** [comment]
Sure, I can totally see how this could be useful to existing users of Owncloud.

> Nextcloud integration could greatly increase its visibility. 

I'm sure it would but I'm wary not to have visibility/popularity become a driving force behind decisions for the platform as that's a very slippery slope. Benefit to existing users & maintainability are much higher prioritised for this project at the current time.

**Comment by tiredofit** [comment]
I really like the 3rd point of being able to integrate into an external file system. regardless if it was NextCloud,Owncloud,Seafile, or some thing supporting DAV.

As more and more people move to an online only environment these web base file management, document management, and knowledge information management tools are going to eventually all intersect, providing the foundation for a one stop solution for teams and organizations. One of the benefits of forcing assets to route through a third part file service would be the ability to limit uploads from a users computer, and only show media available to them from the remote file service based on their credentials.

At present I believe the Bookstack media library shows all content uploaded by all users which could be a privacy concern for users using this in a corporate fashion.

**Comment by ssddanbrown** [comment]
> At present I believe the Bookstack media library shows all content uploaded by all users which could be a privacy concern for users using this in a corporate fashion.

While the actual image files remain accessible to all for performance, The image/drawing galleries will look to filter their views based on access to the pages that they were originally uploaded to. 

Attachments are more restrictive, They (As long as web-serving is not misconfigured) are uploaded to a non-http-accessible space then, upon access, view permissions are checked against the page they were uploaded to.

BookStack does currently support S3-compatible file stores, as does OwnCloud. I'm not familiar with owncloud but tt may be possible to have BookStack files show in OwnCloud by using an S3-like service as an intermediary.

**Comment by ssddanbrown** [comment]
Now that we've added OIDC (Have not checked NextCloud supports this as an IDP myself but referencing point 1 of this original posting) I'm going to close this off since I retain my consideration of this being out of scope since we don't have the resources to maintain additional layers of platform-specific integration.

Just to re-iterate though, I'm not closed off to supporting further integration but it'd ideally be through platform-abstract/open means. If there's a specific BookStack API request to help support an external integration, or you have an idea for achieving other levels of integration through abstract means then feel free to open a new issue for discussion on that specific point.
