### ISSUE TITLE
Make attachments visible in sidebar

### ISSUE THREAD

**Issue by kayvanaarssen** [BookStackApp/BookStack#2401]
When you attach an attachment at this point.
You need to link it in the page etc.

Would it not be more clear to have a section in the sidebar where you can see the Attachments?
That way you can see all attachments to a page etc. at a glance.

**Comment by ssddanbrown** [comment]
Hi @kayvanaarssen,
Could you explain this further at all? In both the edit view and display view of a page, the attachments are located in a sidebar.

**Comment by kayvanaarssen** [comment]
Shit! I see now.
Attachments are displayed on the left sidebar. I was looking for them on the right sidebar and overlooked the left one.
They are on the top indeed.

Should have checked better...
