### ISSUE TITLE
Translation for persian language farsi

### ISSUE THREAD

**Issue by wikiccu** [BookStackApp/BookStack#2403]
### Language To Add

_Specify here the language you want to add._

----Persian / Farsi 

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Thanks for offering to translate @wikiccu and sorry for my really late reply.

I've added Persian to the [crowdin project](https://crowdin.com/project/bookstack). If you've changed your mind just let me know. If little translation progress is made after a couple of months I'll likely remove it from the project and it'll need to be re-requested.
