### ISSUE TITLE
Please show space characters

### ISSUE THREAD

**Issue by ShuiHuo** [BookStackApp/BookStack#2404]
**Describe the feature you'd like**
Don't delete spaces`　　`

**Describe the benefits this feature would bring to BookStack users**

https://translate.google.cn/?sl=zh-CN&tl=en&text=在汉语书写习惯中，每个段落的开头都会有两个与汉字相同大小的空格，这能让段落显示更为清晰。

**Additional context**

```
### 一、项目集是什么

　　项目集是一系列项目的集合，用于归类项目。

### 二、如何使用

#### 1. 进入项目集

　　具有项目集相关权限的产品和项目管理人员，点击左边的`项目集`链接即可进入项目集界面。

#### 2. 添加项目集

　　在项目集界面右上方找到`添加项目集`链接或在现有项目集的右侧找到`子项目集`链接，点击进入添加项目集界面。填写完相关信息之后点击保存，一个项目集添加好了。
```

| ✔ | ✘ |
|---|---|
| ![有空格](https://user-images.githubusercontent.com/7471938/101854407-73487f00-3b9c-11eb-93cc-4dbbabd1b3f1.png) | ![没有空格](https://user-images.githubusercontent.com/7471938/101854423-7c395080-3b9c-11eb-9841-f50d7b8ebdee.png) |

**Comment by ssddanbrown** [comment]
Hi @ShuiHuo,
The trimming of spaces is fairly common in markdown (Seems to happen here on GitHub also).

To keep our markdown standard, and to avoid incorporating a mix of opinions, we follow the [commonmark](https://commonmark.org/) specification which includes this trimming.

There are a few potential workarounds that may help:

1. You could use `&ensp;` to represent spaces at the start of your paragraph like so:

```
&ensp; &ensp;项目集是一系列项目的集合，用于归类项目。
```

2. You could add some CSS, to the "Custom HTML Head Content" setting like the below to add an indent to all paragraph sections within page content:

```html
<style>
    .page-content p {
        text-indent: 2em;
    }
</style>
```

**Comment by ShuiHuo** [comment]
>     1. You could use `&ensp;` to represent spaces at the start of your paragraph like so:
> 
> 
> ```
> &ensp; &ensp;项目集是一系列项目的集合，用于归类项目。
> ```

Thanks @ssddanbrown 

In my test: 
`&emsp;`  look like `　`.
`&ensp;`  look like ` `.

I think can add a buttom `　 ↔ &emsp；`, `&emsp` too long. 

[Sometimes, I may paste the markdown content from other places to BookStack, or copy the markdown text in BookStack to other software, maybe I can increase the conversion when copying and pasting (if I can import and export markdown, I hope so). Of course, users can set these functions according to their own habits.](https://translate.google.cn/?sl=zh-CN&tl=en&text=%E6%9C%89%E6%97%B6%E5%80%99%EF%BC%8C%E6%88%91%E5%8F%AF%E8%83%BD%E4%BC%9A%E4%BB%8E%E5%85%B6%E4%BB%96%E5%9C%B0%E6%96%B9%E7%B2%98%E8%B4%B4%20markdown%20%E5%86%85%E5%AE%B9%E5%88%B0%20BookStack%EF%BC%8C%E4%B9%9F%E5%8F%AF%E8%83%BD%E5%A4%8D%E5%88%B6%20BookStack%20%E4%B8%AD%E7%9A%84%20markdown%20%E6%96%87%E6%9C%AC%E5%88%B0%E5%85%B6%E4%BB%96%E8%BD%AF%E4%BB%B6%EF%BC%8C%E4%B9%9F%E8%AE%B8%E5%8F%AF%E4%BB%A5%E5%A2%9E%E5%8A%A0%E5%9C%A8%E5%A4%8D%E5%88%B6%E5%92%8C%E7%B2%98%E8%B4%B4%E7%9A%84%E6%97%B6%E5%80%99%E8%BD%AC%E6%8D%A2%EF%BC%88%E5%A6%82%E6%9E%9C%E8%83%BD%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%20markdown%EF%BC%8C%E5%B8%8C%E6%9C%9B%E4%B9%9F%E8%83%BD%E5%A6%82%E6%AD%A4%EF%BC%89%E3%80%82%E5%BD%93%E7%84%B6%EF%BC%8C%E7%94%A8%E6%88%B7%E5%8F%AF%E4%BB%A5%E6%A0%B9%E6%8D%AE%E8%87%AA%E5%B7%B1%E7%9A%84%E4%B9%A0%E6%83%AF%E5%8E%BB%E8%AE%BE%E7%BD%AE%E8%BF%99%E4%BA%9B%E5%8A%9F%E8%83%BD%E3%80%82)

**Comment by ssddanbrown** [comment]
Since some workaround to achieve the intended behaviour have been provided I'll close this off.
