### ISSUE TITLE
Using offline

### ISSUE THREAD

**Issue by maggie0002** [BookStackApp/BookStack#2409]
**Describe the feature you'd like**
Clarity over what requires online access. 

**Describe the benefits this feature would bring to BookStack users**
Using the app in offline environments as part of IoT devices. 

**Additional context**
I have noted Draw.io and avatars as requiring internet access, and the ability to disable it. Are there other internet reliant components or other issues I may encounter deploying BookStack in an offline environment? https://www.bookstackapp.com/docs/admin/other-config/#custom-drawio-url

**Comment by ssddanbrown** [comment]
@maggie0002 Should just be (by default) draw.io, avatars and any external authentication providers you choose to use. 

It is possible to self-host draw.io though so that could be used in an offline environment if needed.
