### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by ateliermedia** [BookStackApp/BookStack#241]
### For Feature Requests
Desired Feature: Would be nice to have the possibility to add subscribers from the existing users to a book/chapter/page (maybe only for pages) and to have notifications when something was modified (with checkbox for not sending them when minor edits).

### For Bug Reports
PHP Version:

MySQL Version:

Expected Behavior:

Actual Behavior:

**Comment by tmikaeld** [comment]
I'm also interested in this, would make it easier to follow important "books".

**Comment by LeDistordu** [comment]
+1 Notification with diff

**Comment by Kdecherf** [comment]
Related to #147

**Comment by a-mawlawi** [comment]
+1 for this

**Comment by fureweb-com** [comment]
+1

**Comment by Doctor-Macintosh** [comment]
+1 for this feature request. Very important feature to notify all useres (opt-out via a setting in the user account should be possible). Great idea to have the author check a box when he wants / does not want an update to be pushed out. To bring it to the max a user could subscribe to a daily digest (one eMail with all the changes of the last 24 hours if any) or immediate notification about a change of (or new) content.

**Comment by costib-ro** [comment]
+1
Also related to what @Doctor-Macintosh said above:
Something like send me an automated digest of my new notes/pages every week could help me retain more knowledge and solve this "no spaced repetition" issue - because I tend to never go back to my old notes once I wrote them...

**Comment by drexxi** [comment]
+1 we need this too

**Comment by ssddanbrown** [comment]
If any instances need desperately desire this kind of functionality, I've created a couple of examples of achieving this via our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md).
These are unsupported customizations and there are notes to consider on each:

- [Email page updates based upon favourite pages](https://gist.github.com/ssddanbrown/f14f7a5b0ab190899b6bd84ba9731f36)
- [Email page updates based on roles tagged on parent book](https://gist.github.com/ssddanbrown/800c762ef53b26700ace2416f3cf0697)

**Comment by byPavel** [comment]
Good afternoon, Are notifications planned out of the box?  This functionality is very lacking.

**Comment by ssddanbrown** [comment]
I have just opened #4371 for feedback, with a proposal for an initial implementation of email-based content notifications.

**Comment by ssddanbrown** [comment]
A base implementation, following the proposal in #4371, has been added within PR #4390.
This will be part of the next feature release. 
I'll therefore close this off. Additional/related functionality can be opened separately (ideally after gaining experience with the new implementation) if not already covered by an existing issue.
