### ISSUE TITLE
Let user customise BookStack page elements

### ISSUE THREAD

**Issue by andrej1919** [BookStackApp/BookStack#2411]
**Header and Footer**
It is difficult to expect that HTML would provide the same functionality as word processor. Having header and footer on _each page_ is probably too much to ask. However, having fully customisable header and footer at least at the beginning and at the end of document would greatly improve the usability of BookStack. Now you can have footer, but no header as the title of the page comes first by default.

**Describe the benefits this feature would bring to BookStack users**
BookStack would become a more suitable tool for some more formalised and rigidly defined document types such as ISO documentation.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion but I'm going to close this off as I can't envisage an in-built implementation that would be suitable without leading to further requests and options required.

If your intended header/footer is fairly static across your content then the visual theme system would be quite suitable to achieve this: https://github.com/BookStackApp/BookStack/blob/master/dev/docs/visual-theme-system.md

The view where page content is rendered is already quite specific so you don't need to override much:
https://github.com/BookStackApp/BookStack/blob/master/resources/views/pages/parts/page-display.blade.php
