### ISSUE TITLE
[Feature request] GDPR Compliance notice

### ISSUE THREAD

**Issue by NHendriks01** [BookStackApp/BookStack#2413]
Hi there,

I'm using Bookstack in the EU and even though I am the sole user of the installation it is required for a website that is accessible in the EU to comply with the GDPR and have a cookie-acceptance thingy. 

Is it possible to get like a small pop-up that asks to accept cookies and if not accepted redirect to another website or possibly even disable all cookies on Bookstack?

**Comment by ssddanbrown** [comment]
Hi @NHendriks01,

From my dealings with GDPR, the core BookStack functionality should not need a cookie notice. BookStack by default will only use a couple of first-party cookies for CSRF protection and session tracking. 

The only things I would potentially be cautious of is the third party integrations BookStack could use (Draw.io and Gravatar) which would only be active if logging in and making edits, so not something I think is a concern for your use case.

If you need to add something for some other cookies/systems you might be using (If you've added analytics tracking or something) you may be able to find a solution you can add to the "Custom HTML Head Content" part of BookStack.

**Comment by NHendriks01** [comment]
Ah cool! Thanks for your response! I think I'll leave it like this then as I'm not planning on making it for public use :)
