### ISSUE TITLE
Improve Presentation of search results

### ISSUE THREAD

**Issue by gronfuzius** [BookStackApp/BookStack#2418]
When I search in Bookstack, the result Pages/Chapters etc. are shown with a teaser text, which is always the beginning of complete text of the Page (or other type) regardless of what I searched for or where the search hits are.

It would be very great if the teaser would already show search hits highlighted. This would make navigation within the pages much easier.

I have for example ip addresses scattered in some pages. When I search "ip address" I would get page hits and the teaser would already show me some addresses with context. I would have a complete overview and maybe I wouldn`t even have to klick on the result page to get the information I want. Now in the current state I would have to click every single result to see which ip address is in the text.

It would be useful in any other search to have the search result with some context. That`s why every internet search engine does this (not neccesserily with higlights though).

**Comment by ssddanbrown** [comment]
Thanks for the request @gronfuzius.

This has already been requested on issue #997 so I'm going to close this off as a duplicate.
