### ISSUE TITLE
APP_URL is changed after update docker | APP_URL no longer persistant after reboot!

### ISSUE THREAD

**Issue by SupaYoshi** [BookStackApp/BookStack#2420]
**Describe the bug**
After restarting docker today I noticed I could no longer access my wiki, I checked the config for bookstack on two instances of the wiki I am running and in both the APP_URL had changed to my public IP. As I am using bookstack behind traefik, I prefer to keep it the way it was... but that did not let me do this as it was persistant to reset it to the public IP after the restart of the container again! My wiki is now not working since the latest update!

EDIT:
When I set the APP_URL manually correctly (as traefik serves it) it works again, yet after a docker-restart of the container, bookstack will now replace the APP_URL by my public IP and that will not work obviously, can BOOKSTACK, please leave my APP_URL alone?
**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker): 

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @SupaYoshi,
Am I right in thinking that you're using the linuxserver.io image? If so, you'll need to open an issue on their repo since we don't manage and production docker images in the core project. 

https://github.com/linuxserver/docker-bookstack

**Comment by Biepa** [comment]
@SupaYoshi Do you added the APP_URL environment variable in your docker run or docker-compose? Mine got reset, because it wasn't set there like shown here: https://hub.docker.com/r/linuxserver/bookstack

Unfortunalety my instance of bookstack is still not reachable.

**Comment by Biepa** [comment]
Cleared cache of Bookstack and it's working again.

**Comment by xSTUDDSx** [comment]
Having a similar issue. After the latest update, the app is no longer accessible. I noticed the change for the required APP_URL so I added that to my docker-compose, however it is still inaccessible. Have tried clearing cache as well as deleting and recreating the container to no avail.

**Comment by xSTUDDSx** [comment]
Nevermind! Looks like it just took awhile to notice the changes. It's working again.

**Comment by ssddanbrown** [comment]
Will therefore close this since the original issue creator has not responded and it looks like this was generally due to a change in a specific hosting setup.
