### ISSUE TITLE
BadMethodCallException after upgrading to 0.30.7

### ISSUE THREAD

**Issue by nitalr** [BookStackApp/BookStack#2422]
**Describe the bug**
after upgrading from 0.29.3 to 0.30.7 when user try to access books he gets internal error occurred
i enabled debug mod and the error i see is:

BadMethodCallException
Method Illuminate\Database\Eloquent\Collection::whereNull does not exist. 

Bad Method Call

Did you mean Illuminate\Database\Eloquent\Collection::where() ?

**Steps To Reproduce**
1. Go to 'shelf'
2. Click on 'book'

**Expected behavior**
the book supposed to be accessible....

**Screenshots**
![image](https://user-images.githubusercontent.com/62211591/102756741-05a90980-4379-11eb-8c74-48b8f228bff8.png)

![image](https://user-images.githubusercontent.com/62211591/102756631-dc887900-4378-11eb-852c-26342831f79f.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.30.7
 - PHP Version: 7.4.13
 - Hosting Method Apache: 

**Additional context**
from debug file:
`[2020-12-21 08:24:08] production.ERROR: Method Illuminate\Database\Eloquent\Collection::whereNull does not exist. {"userId":3,"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Database\\Eloquent\\Collection::whereNull does not exist. at /storage/bs/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103)
[stacktrace]
#0 /storage/bs/app/Entities/Managers/BookContents.php(62): Illuminate\\Support\\Collection->__call('whereNull', Array)
#1 /storage/bs/app/Http/Controllers/BookController.php(116): BookStack\\Entities\\Managers\\BookContents->getTree(true)
#2 [internal function]: BookStack\\Http\\Controllers\\BookController->show(Object(BookStack\\Http\\Request), 'test')
#3 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('show', Array)
#5 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Controllers\\BookController), 'show')
#6 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#8 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(BookStack\\Http\\Request))
#9 /storage/bs/app/Http/Middleware/Authenticate.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#10 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\Authenticate->handle(Object(BookStack\\Http\\Request), Object(Closure))
#11 /storage/bs/app/Http/Middleware/GlobalViewData.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#12 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\GlobalViewData->handle(Object(BookStack\\Http\\Request), Object(Closure))
#13 /storage/bs/app/Http/Middleware/Localization.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#14 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\Localization->handle(Object(BookStack\\Http\\Request), Object(Closure))
#15 /storage/bs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#16 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(BookStack\\Http\\Request), Object(Closure))
#17 /storage/bs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#18 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#19 /storage/bs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#20 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#21 /storage/bs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#22 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(BookStack\\Http\\Request), Object(Closure))
#23 /storage/bs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#24 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#25 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#26 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#27 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Request))
#28 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(BookStack\\Http\\Request), Object(Illuminate\\Routing\\Route))
#29 /storage/bs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(BookStack\\Http\\Request))
#30 /storage/bs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(BookStack\\Http\\Request))
#31 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(BookStack\\Http\\Request))
#32 /storage/bs/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#33 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(BookStack\\Http\\Request), Object(Closure))
#34 /storage/bs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#35 /storage/bs/app/Http/Middleware/TrustProxies.php(39): Fideloper\\Proxy\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#36 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#37 /storage/bs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#38 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(BookStack\\Http\\Request), Object(Closure))
#39 /storage/bs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#40 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(BookStack\\Http\\Request), Object(Closure))
#41 /storage/bs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#42 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(BookStack\\Http\\Request), Object(Closure))
#43 /storage/bs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#44 /storage/bs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /storage/bs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(BookStack\\Http\\Request))
#46 /storage/bs/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(BookStack\\Http\\Request))
#47 {main}
"}
`

**Comment by ssddanbrown** [comment]
Hi @nitalr,
Could you confirm if ran the `composer install` step as part of the upgrade? If so, does running that step produce any errors?

**Comment by nitalr** [comment]
Hi,
sorry for the delay (git didn't update me on you comment 
![image](https://user-images.githubusercontent.com/62211591/103812821-c6acd080-5067-11eb-8d00-cb86115770bb.png)
this is the error 

today i was trying to upgrade to 0.31.1
and the error is even worst i get 

Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined function BookStack\Http\Middleware\user() 

BookStack\Http\Middleware\Localization::handle :60
app/Http/Middleware/Localization.php:6

**Comment by ssddanbrown** [comment]
Hi @nitalr,
It looks like the `composer install` step is failing and therefore you have incompatible/outdated code.

Seems to be permission based.
Could you:

- Backup your bookstack files.
- Fully delete the `vendor/` folder within your BookStack install.
- Re-run the `composer install` step.

**Comment by nitalr** [comment]
Hi,
i started from a working state (v0.29.3) and sis the folowing steps:
1. sudo -u ApacheUser git pull origin release && composer install --no-dev && php artisan migrate
2. sudo -u ApacheUser  php artisan cache:clear
3. sudo -u ApacheUser  php artisan view:clear
4. not mandatory but i also used the command sudo -u ApacheUser   php artisan bookstack:regenerate-comment-content
5. website is down 
BookStack\Http\Middleware\Localization::handle :60
6. i deleted the vendor folder (sudo rm -r vendor)
7. sudo -u ApacheUser composer install --no-dev

i have revived this errors:
![image](https://user-images.githubusercontent.com/62211591/103898781-1fc74380-50fe-11eb-896f-299a275f8e5f.png)
i tried to run steps 2-4 again and received the error in the picture 

in the web browser in debug mod it was recommended to run migrate
after executing the command "sudo -u ApacheUser  php artisan migrate" everything is resolved and the site is back to operation

(i have written the full process hope it will help others with the same problem 
thank you!
