### ISSUE TITLE
Show Path to Public Pages

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2423]
**Describe the feature you'd like**
our Bookstack is mainly for knowledge sharing, we have public and private pages, now if you have public page in private book and chapter you can't see them in the home page, so you can't access the pages without having link to the page or looking on the left history tab. if the question rises why not have them in different shelf and books, well it's a lot easier for those who have full access to manage and navigate the site.

**Describe the benefits this feature would bring to BookStack users**
this would allow easier access to pages as now it's pretty hard to access

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Zyzto.

I'm going to close this off as I can't see a way of this working without having options that are only useful to specific use-cases in certain situations. This would be fighting back against the permission system, and would have to be an option upon the current functionality as people would typically expect the items without view permission would be hidden.

Maybe #182 would be a more likely option for the fundamental visibility issue at play here.
