### ISSUE TITLE
File upload documentation update for php memory limit

### ISSUE THREAD

**Issue by aarchijs** [BookStackApp/BookStack#2424]
I was trying to upload file larger than 400MB, but I got HTTP500 error. 
Configuration was made according to https://www.bookstackapp.com/docs/admin/upload-config/ documentation. 

After some digging I found that PHP script memory usage should be increased aswell to increase max file size for uploads. 

I think that additional configuration information about this should be included in documentation. 
within php.ini 

Default is 128M.
Maximum amount of memory a script may consume (128MB)
memory_limit = 128M

By increasing memory limit max file upload size also increases.

**Comment by ssddanbrown** [comment]
Thanks @aarchijs for raising this.

I have now updated the documentation to advise that the memory limit may also need to be changed for larger files.
