### ISSUE TITLE
Add language for translation - Latvian

### ISSUE THREAD

**Issue by aarchijs** [BookStackApp/BookStack#2425]
### Language To Add

Latvian

----

**Comment by aarchijs** [comment]
I saw that there is similar issue #2331 
I could translate Bookstack to Latvian via Crowdin or other method. As far as I understand Crowdin is preffered.  
@ssddanbrown

**Comment by ssddanbrown** [comment]
Thanks for offering to translate @aarchijs and thanks for the reminder and sorry for my really late reply.

I've added Latvian to the [crowdin project](https://crowdin.com/project/bookstack). If you've changed your mind just let me know. If little translation progress is made after a couple of months I'll likely remove it from the project and it'll need to be re-requested.
