### ISSUE TITLE
Changing language in user settings doesn't work

### ISSUE THREAD

**Issue by NHendriks01** [BookStackApp/BookStack#2430]
**Describe the bug**
Changing language as a user in the 'edit profile'-page does not work. You can select another language in the dropdown but when you press save nothing happens. 

**Steps To Reproduce**
1. Go to 'edit user'
2. Change language in the dropdown
3. Press save
4. See that it goes back to the old value

**Expected behavior**
For the language to change

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.30.5
 - PHP Version: 7.4 (phpinfo at https://nhes.be/info.php)
 - Hosting Method (Nginx/Apache/Docker): Apache2

**Comment by NHendriks01** [comment]
Updating to v0.30.7 fixed the issue but sadly it still persists in v0.30.5

**Comment by ssddanbrown** [comment]
Will therefore close this off since updating fixed it.

Just a note, no changes in this area were specifically made between v0.30.5 and v0.30.7. It's likely the same cause as your issues in #2429 which would likely be file/folder permission based.
