### ISSUE TITLE
The double quotation marks in quote blocks overlap the text on mobile devices

### ISSUE THREAD

**Issue by MFYDev** [BookStackApp/BookStack#2431]
**Describe the bug**
When using Bookstack 0.30.7, and setting default editor as mardown.

Then the quote block cannot display normally on mobile device, because the double quotation marks overlap the text.

**Steps To Reproduce**
1. create a new page in the book.
2. using `>` to create a quote block and fill it with some characters.
3. viewing it on your mobile device. (Mine is Android Chrome)

**Expected behavior**
the double quotation marks should not overlap the text.

**Screenshots**
![error](https://user-images.githubusercontent.com/53750381/103154457-4a4a0000-47d2-11eb-8e28-7932f1cfed2e.jpg)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):0.30.7
 - PHP Version:7.4
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Thanks for reporting @MFYDev.

I'm having trouble reproducing this, Can you confirm the following:

* What device is in use? Just so I can get details of the browser viewport size.
* Have you made any customizations to your BookStack instance? The quote mark looks different to what I see by default on chrome/firefox.

**Comment by MFYDev** [comment]
@ssddanbrown I am using Mi 10 Ultra and here is the parameters of my device.
![Screenshot_2021-01-02-10-08-01-079_com android settings](https://user-images.githubusercontent.com/53750381/103449384-9d481980-4ce2-11eb-88d4-1c2b6e8aaeb5.jpg)

I never do any customization on this thing. I just add mathjax to the header, but this has nothing to do with the quote marks. Maybe it is because of the Chinese characters?

**Comment by ssddanbrown** [comment]
Thanks for confirming @MFYDev, Yeah, May be due to the characters or maybe the default font active on the phone. I do have a xiomi device somewhere, might give it a test on that.

If possible, it would be ideal if you could let me know if you see the same thing on the BookStack demo site on your device. There's a quote block towards the bottom of this page:
https://demo.bookstackapp.com/books/bookstack-user-guide/page/examples-of-different-content

**Comment by MFYDev** [comment]
Thank you so much for the efficient support @ssddanbrown, and I can confirm this issue happens on your demo site too, here is the screenshot in the following:
 
![image](https://user-images.githubusercontent.com/53750381/103449912-e5b70580-4ce9-11eb-9017-1c4c2ee75668.png)

BTW, I found another problem at the same moment, the table appears incomplete on the mobile device and cannot be dragged,
here is the screenshot:

![image](https://user-images.githubusercontent.com/53750381/103449925-0da66900-4cea-11eb-8daf-40b5b87b5b44.png)

 I am using the lastest version Andorid Chrome which was downloaded from Google Play.

**Comment by MFYDev** [comment]
Honestly, I suggest to remove the quote marks. Because sometimes, we do not use quote blocks just to quote somebody's words. We also use this block to highlight something, then, displaying the quote mark will be a little bit weird.

I know you want this block more pretty, but this thing is not always the best in markdown editor.

Maybe one of the solutions is adding a switch to control the quote mark in the block displays or not?

I do not know, just wanna express my perspective.

**Comment by MFYDev** [comment]
@ssddanbrown Please do not forget this issue sir.

**Comment by tcsi-github** [comment]
I realize this is about a year old.... however I feel the same way. I would like to see the double quote go away. Rarely are we using it to denote an actual quote but more of sectioning something to be on it's own.

**Comment by ssddanbrown** [comment]
@tcsi-github I wouldn't really look to change the default style based on people using blockquotes against their intended purpose.
You can override the styles on your instance if desired using the "Custom HTML Head Content" setting:

```html
<style>
blockquote:before { content: none; }
</style>
```

**Comment by tcsi-github** [comment]
That is perfectly acceptable for me. Thank you for the workaround.
