### ISSUE TITLE
@name mention functionality

### ISSUE THREAD

**Issue by wojosc** [BookStackApp/BookStack#2432]
Merry Christmas :)

In many systems these day you are able to use a mention feature to highlight people who also have an account on the platform. I could see this being very helpful in the comment section.

![image](https://user-images.githubusercontent.com/22279621/103168829-0210f900-4837-11eb-9fd3-31f6a00b499a.png)

With posting the comment the account mentioned with the @ would receive an e-mail with the comment and a URL-Link to the specific page where the comment is coming from.

Kind Regards
Wolfram

**Comment by ssddanbrown** [comment]
Thanks for the request @wojosc and Merry Christmas to you too!

This has already been requested within #560 so I'm therefore going to close this off as a duplicate.
