### ISSUE TITLE
Unable to save or create books/shelves after update [v0.29.3] to [v0.30.7]

### ISSUE THREAD

**Issue by ikdekker** [BookStackApp/BookStack#2433]
I have updated my docker from 29.3 to 30.7, now I get the 'Whoops, looks like something went wrong.' error on saving a page. 

For example this error is logged to the nginx log:
```
2020/12/27 14:18:57 [error] 379#379: *13 FastCGI sent in stderr: "PHP message: PHP Warning:  Unknown: POST Content-Length of 1080 bytes exceeds the limit of 100 bytes in Unknown on line 0" while reading response header from upstream, client: 172.18.0.1, server: _, request: "POST /books/magento-guides/page/encountered-issues HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "bookstack.w4e.com", referrer: "http://bookstack.w4e.com/books/magento-guides/page/encountered-issues/edit"
``` 

It's always the content-length warning. I have never encountered this before. Is there a fix or way to downgrade so I can save again?

**Comment by ssddanbrown** [comment]
Hi @ikdekker,
Are you using the linuxserver.io docker image?

If so, It's worth restarting your containers and see if that fixes this as they did have a temporary issue where the PHP content limit was set too low, which appears to be the issue you have now. They added a fix but it would only take action after a restart of a fixed container image.

**Comment by ikdekker** [comment]
I am not sure what fixed it in the end, i believe using a new shared /config and restarting helped.
