### ISSUE TITLE
redirecting of url

### ISSUE THREAD

**Issue by JayRhithu** [BookStackApp/BookStack#2435]
Hi,

I am trying to install bookstack in windows 8, following this tutorial (https://www.youtube.com/watch?v=lSaY4lK_RjM)(WAMP Server). All done successfully. Also added virtual host in wamp server. But when I browse the url 'http://bookstack.local/login' or 'http://127.0.0.1:800' it's redirecting to a url 'https://example.com/login'. Checked in the C:\Windows\System32\Drivers\etc\hosts file also (it is  - 127.0.0.1  bookstack.local).

Please help.

**Comment by alvar0liveira** [comment]
Hi, 
Have you checked APP_URL parameter on .env file? You need to set APP_URL=bookstack.local.
Hope this helps!

**Comment by JayRhithu** [comment]
Thanks for the support... It's working now...
