### ISSUE TITLE
The actions button options in the recycle bin in the Chinese environment are not displayed completely

### ISSUE THREAD

**Issue by 10935336** [BookStackApp/BookStack#2442]
**Describe the bug**
The destroy option in the actions button is not displayed, and the recovery option only displays half a word. In the Chinese environment.

**Steps To Reproduce**
1. Delete a page
2. Go to recycle bin
3. Click on actions button

**Expected behavior**
The destroy option and recovery option should display correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/32383605/103517519-3fb3f880-4ead-11eb-8287-08e76c86aaf6.png)
![image](https://user-images.githubusercontent.com/32383605/103517495-3165dc80-4ead-11eb-8da4-8656e7ff710a.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: BookStack v0.31.0
 - PHP Version: 7.4.13 
 - Hosting Method:  Nginx/1.19.6

**Comment by escservices** [comment]
I'm having the same issue but with the English environment.

![image](https://user-images.githubusercontent.com/1287511/103565584-94944680-4e8e-11eb-97ce-10d880f53566.png)

-  Apache 2.4.29
- PHP 7.4.13
- Bookstack Version: v0.31.0

**Comment by ssddanbrown** [comment]
Thanks for raising @10935336 and thanks for confirming @escservices. Can confirm this was apparent on chrome-based browsers but not FireFox. 

This will be fixed in a patch release due shortly.

**Comment by 10935336** [comment]
Perhaps the browser type and version should be added to the question template.
