### ISSUE TITLE
Revision number incorrect 0.31.0v

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2444]
**Describe the bug**
revision number is not same as revision clicked on

**Steps To Reproduce**
1-have page already edited more than once
2-view changes
3-look a the number of revision above

**Expected behavior**
the number to be the same

**Screenshots**
two images
![image](https://user-images.githubusercontent.com/13531154/103539900-e39ba500-4ea9-11eb-9bdf-1e53ba8066b2.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.31.0
 - PHP Version: 7.2.4
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for raising @Zyzto.

This has already been reported in #2373 so I'm going to close this off as a duplicate.
