### ISSUE TITLE
Custom set owner can't manage permissions for owned items

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#2445]
**Describe the bug**
Issue with new feature: Entity Ownership System #2436
The option "Manage permissions on own book, chapter & pages" is still checking for the creator instead of the custom set owner.

**Steps To Reproduce**
1. Go to 'Setting' and give a user role the option to manage their own permissions
2. Create 2 users with the user role
3. Create a page with user 1
4. Change owner of page to user 2
5. See error: Still able to change permissions with user 1
6. Login with user 2 and see error: No option to change permissions with user 2

**Expected behavior**
After changing an owner the new owner should be able to manage the permissions for owned items instead of the creator.

**Screenshots**
Error for step 5
![image](https://user-images.githubusercontent.com/42382626/103557999-4b56ed80-4eb4-11eb-9573-b770cdbe68e6.png)

Error for step 6
![image](https://user-images.githubusercontent.com/42382626/103558202-95d86a00-4eb4-11eb-932e-56ee69ae82e5.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.31.0 
 - PHP Version: 7.2.24
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
Just recently updated from v0.26 to 0.31. Thanks for the new features!

**Comment by ssddanbrown** [comment]
Thanks for reporting @Bolthier, To be honest I totally forgot we had that owner-based permission control option.
Just updated the test and prepared a fix. Will be deployed in a patch release shortly. 

> Just recently updated from v0.26 to 0.31. Thanks for the new features!

No problem, Over a year's worth of updates there!
