### ISSUE TITLE
Feature Request: Redirecting a page/chapter

### ISSUE THREAD

**Issue by Ingenieur81** [BookStackApp/BookStack#2447]
**Describe the feature you'd like**
The ability to redirect clicking on a page/chapter to another page/chapter

**Describe the benefits this feature would bring to BookStack users**
Instead of the need to create a page which contains a word that links to another page/chapter the page/chapter itself already links to that page/chapter.

**Additional context**
None

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Ingenieur81.

I feel the goal of this is fundamentally already covered by #182 and #1360 so I'm going to close this off as a duplicate.
