### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError Class 'BookStack\Uploads\Log' not found

### ISSUE THREAD

**Issue by Midas1989** [BookStackApp/BookStack#2449]
Hello, i have a freh installation on ubuntu 18.04.

When i create a new User with Mailsend i become this error
with a local create user on cli
root@wiki:/var/www/bookstack# php artisan bookstack:create-admin

 Please specify an email address for the new admin user:
 > test@example.com             

 Please specify an name for the new admin user:
 > test

 Please specify a password for the new admin user:
 > 

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'BookStack\Uploads\Log' not found

  at /var/www/bookstack/app/Uploads/UserAvatars.php:32
    28|             $avatar = $this->saveAvatarImage($user);
    29|             $user->avatar()->associate($avatar);
    30|             $user->save();
    31|         } catch (Exception $e) {
  > 32|             Log::error('Failed to save user avatar image');
    33|         }
    34|     }
    35| 
    36|     /**

  Exception trace:

  1   BookStack\Uploads\UserAvatars::fetchAndAssignToUser(Object(BookStack\Auth\User))
      /var/www/bookstack/app/Auth/UserRepo.php:265

  2   BookStack\Auth\UserRepo::downloadAndAssignUserAvatar(Object(BookStack\Auth\User))
      /var/www/bookstack/app/Console/Commands/CreateAdmin.php:77

  Please use the argument -v to see more details.

The User is createt but with mail he dont send the mail. the testmail is still running

Thanks for help

**Comment by ssddanbrown** [comment]
Thanks for reporting @Midas1989.

This was due to a failed code reference that shows up when an avatar fetch fails, preventing the fetch from failing gracefully. I have patched this in e5a96b0cb0788f44b331afa83f1279314a7bafd1with updating testing to cover this case. This will be part of v0.31.2 which will be released sometime today.
