### ISSUE TITLE
Attachment Size Limitations

### ISSUE THREAD

**Issue by N3V3N** [BookStackApp/BookStack#245]
How can I increase the file size limitation on attachments? I've already increased the upload limits in php.ini but anything more than a couple megabytes is still being rejected. Is there a framework related config I need to edit? Thanks in advance.

**Comment by ssddanbrown** [comment]
Hi @N3V3N, There's nothing at app or framework level that should limit upload size. Have you updated both `post_max_size` and `upload_max_filesize` variables in the php.ini file?

If so it could possibly be something at web-server level. Are you using Nginx, Apache or something else?

**Comment by N3V3N** [comment]
![image](https://cloud.githubusercontent.com/assets/23702666/20714093/772ace90-b610-11e6-82a5-befa0bf3c0c8.png)

I'm using Nginx as installed by the installation script.

**Comment by N3V3N** [comment]
I figured it out, thank you for pointing me in the right direction Dan. I also appreciate all your hard work on developing this fantastic documentation solution.

For posterity, I edited /etc/nginx/nginx.conf and added the following line:
`client_max_body_size 100m`
After which I was able to successfully upload the files.

**Comment by ssddanbrown** [comment]
@N3V3N Awesome, I'm glad you found the fix.

I'll keep this issue open for now to remind me to add a page to the docs with details of changing attachment size limits.
