### ISSUE TITLE
Help: Messed up with the customized header

### ISSUE THREAD

**Issue by wx-Yao** [BookStackApp/BookStack#2450]
Sry ... I'm not very expert in php but, the thing is I was trying to add some CSS attributes in the settings -> customize content header. And it seems that i messed up the content block and some injected css was breaking the rendering. Now my whole website is blank empty but "view source" gives this:

![image](https://user-images.githubusercontent.com/20643897/103666050-14b1cd80-4faf-11eb-83fa-61f1c9ca7585.png)

It feels like i commented out the other logic accidentally?

After the blank out, I went to database trying to remove the injected content in "settings" table by

` update settings set value="" where setting_key="app-custom-head"`

and it doesn't work either. Any place i should look into to revert the customized header change?

Thanks very much.

**Comment by wx-Yao** [comment]
I was thinking about ... a direct API call to set the header content to be empty again or sth like that ...  i don't wanna get my hands dirty with db again without some "official" guidance lol. Yeah my bad. thanks for the help.

**Comment by ssddanbrown** [comment]
Hi @wx-Yao,
The `/settings` page specifically does not load in the customizations so that nothing breaks and you are able to revert changes where needed.

You should still be able to visit `<your_bookstack_url>/settings` so that you can undo the changes.

**Comment by ssddanbrown** [comment]
Just realised you mentioned running the sql query. Settings are also cached so you might have cleared the setting but it's still in the system cache.

You can try running `php artisan cache:clear` to clear the cache. Might have to run with `sudo` depending on permissions.

**Comment by wx-Yao** [comment]
> You should still be able to visit <your_bookstack_url>/settings so that you can undo the changes.

yeah man thanks very much. this fixes everything. Closing the issue because it's resolved.
