### ISSUE TITLE
Show difference between two page revision

### ISSUE THREAD

**Issue by johnroyer** [BookStackApp/BookStack#2454]
**Describe the feature you'd like**
It is good to add a function which can show the difference between two revision.

This is how Mediawiki do below:

![revision diff tool](https://user-images.githubusercontent.com/114491/103752788-1f1ea680-5045-11eb-8b38-f412ae392c89.png)

----

**Describe the benefits this feature would bring to BookStack users**
It take a lot of time using preview page to know what is changed in revisions. If there is an diff tool, review changes is a lot more easier.

**Comment by ssddanbrown** [comment]
Hi @johnroyer,

There's already a "Changes" option when looking at the revisions of a page. Is there something additional to that which you need?

**Comment by johnroyer** [comment]
oh .... maybe I have not grade yet. Give some timeto upgrade.

soerry.

**Comment by johnroyer** [comment]
I know why now.

The is a button called `change`. But it translate to `說明 (instruction)` in Chinese. That why I did not found the function.

----

I will send an PR to fix this problem.

**Comment by johnroyer** [comment]
Issue closed. Thanks a lot !

**Comment by ssddanbrown** [comment]
@johnroyer No problem, thanks for reporting and providing the updated translations!
