### ISSUE TITLE
Problem with Version 0.31.0

### ISSUE THREAD

**Issue by dugs951** [BookStackApp/BookStack#2455]
I run BookStack on Ubuntu Container, i want to update to new Version 0.31.0, but after upgrade Bookstack dont work anymore.

I go to /var/www/html/Bookstack and run
git pull origin release && composer install --no-dev && php artisan migrate

After update Bookstack dont work anymore?
Can somebody help me pleas?

**Comment by modem7** [comment]
When you say "container" do you mean a VM or in Docker?

**Comment by ssddanbrown** [comment]
In addition to the above, what do you mean by it doesn't work? What error or result are you seeing?

**Comment by dugs951** [comment]
> In addition to the above, what do you mean by it doesn't work? What error or result are you
ii cant open any more my book stack

**Comment by ssddanbrown** [comment]
@dugs951 Sure, But what do you visually see when attempting to access?  A blank white screen? An error message?

**Comment by dugs951** [comment]
I open /var/www/html/Bookstack then i make Update:
git pull origin release && composer install --no-dev && php artisan migrate

Then i can not more open my BookStack
When i go to bookstack.mydomain.com i can not open my bookstack
Know somebody whats the problem?

**Comment by dugs951** [comment]
Diese Seite funktioniert nicht
bookstack.mydomain.com kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500

> @dugs951 Sure, But what do you visually see when attempting to access? A blank white screen? An error message?

**Comment by ssddanbrown** [comment]
@dugs951 

- In regards to the " HTTP ERROR 500". Where are you seeing that? When accessing the homepage URL?
- What operating system are you using?
- How did you originally install BookStack?

**Comment by killadelphia** [comment]
I ended up with a HTTP ERROR 500 when trying to load the bookstack homepage when upgrading to 0.31.0 as well. Mine was an an error with migration tables, I dropped the tables from the SQL database and was able to continue the migration.

**Comment by joe-eklund** [comment]
> I ended up with a HTTP ERROR 500 when trying to load the bookstack homepage when upgrading to 0.31.0 as well. Mine was an an error with migration tables, I dropped the tables from the SQL database and was able to continue the migration.

Was the error you were getting the same one I detailed in #2473? And by fixing it you just dropped the bad tables?

**Comment by dugs951** [comment]
Somebody can help with this problem?

**Comment by ssddanbrown** [comment]
@dugs951 I can do but you'd need to provide some additional details, such as those requested in https://github.com/BookStackApp/BookStack/issues/2455#issuecomment-757473542.

**Comment by dugs951** [comment]
> @dugs951 I can do but you'd need to provide some additional details, such as those requested in [#2455 (comment)](https://github.com/BookStackApp/BookStack/issues/2455#issuecomment-757473542).

Which table i need to drop?
I go to mysql i show my tables but i dont know which table i need to drop?

**Comment by dugs951** [comment]
[Wed Jan 27 00:33:32.145816 2021] [php7:error] [pid 561] [client 192.168.188.201:43646] PHP Fatal error:  Declaration of Symfony\\Component\\Translation\\TranslatorInterface::setLocale($locale) must be compatible with Symfony\\Contracts\\Translation\\LocaleAwareInterface::setLocale(string $locale) in /var/www/html/BookStack/vendor/symfony/translation/TranslatorInterface.php on line 24
[Wed Jan 27 00:33:32.230338 2021] [php7:error] [pid 561] [client 192.168.188.201:43646] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to undefined method Illuminate\\Support\\Carbon::now() in /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php:37\nStack trace:\n#0 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(269): Illuminate\\Cache\\FileStore->availableAt(0)\n#1 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Cache\\FileStore->expiration(0)\n#2 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('setting-app-nam...', 'Book dD22', 0)\n#3 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever('setting-app-nam...', 'Book dD22')\n#4 /var/www/html/BookStack/app/Settings/SettingService.php(112): Illuminate\\Cache\\Repository->forever('setting-app-nam...', 'Book dD22')\n#5 /var/www/html/BookStack/app/Settings/SettingService in /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php on line 37

**Comment by dugs951** [comment]
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies

**Comment by ssddanbrown** [comment]
> Which table i need to drop?

@dugs951 Please don't drop any tables.

It looks to me like your php dependencies are not up-to-date. 
Can you retry re-running `composer install --no-dev`? 

Let me know if there are any errors in the output. Also, If there are files ending in `.php` within the `bootstrap/cache` folder, Please delete those.

**Comment by dugs951** [comment]
> > Welchen Tisch muss ich fallen lassen?
> 
> @ dugs951 Bitte keine Tabellen löschen .
> 
> Es sieht für mich so aus, als ob Ihre PHP-Abhängigkeiten nicht auf dem neuesten Stand sind.
> Können Sie es erneut versuchen `composer install --no-dev`?
> 
> Lassen Sie mich wissen, wenn die Ausgabe fehlerhaft ist. Wenn es auch, sind Dateien mit der Endung `.php`innerhalb des `bootstrap/cache`Ordners, Bitte löschen Sie diese.

 @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"oot@BookStack:/var/www/html/BookStack# sudo tail -100 /etc/httpd/logs/error_log

**Comment by dugs951** [comment]
@php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');

**Comment by dugs951** [comment]
I deleted files with php but problem is still same

**Comment by ssddanbrown** [comment]
Just to confirm, Did you see any errors when running `composer install --no-dev`?

**Comment by dugs951** [comment]
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /root
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
root@BookStack:~# cd /var/www/html/BookStack
root@BookStack:/var/www/html/BookStack# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
> @php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-snappy
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/socialite
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: socialiteproviders/manager
Package manifest generated successfully.
40 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan cache:clear
Application cache cleared!
> @php artisan view:clear
Compiled views cleared!

**Comment by ssddanbrown** [comment]
Okay, Looks like that ran, any change in error now compared to your log example in https://github.com/BookStackApp/BookStack/issues/2455#issuecomment-767925910?

**Comment by dugs951** [comment]
> Okay, Looks like that ran, any change in error now compared to your log example in [#2455 (comment)](https://github.com/BookStackApp/BookStack/issues/2455#issuecomment-767925910)?

This is the Error now

PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to undefined method Illuminate\\Support\\Carbon::now() in /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php:37\nStack trace:\n#0 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(269): Illuminate\\Cache\\FileStore->availableAt(0)\n#1 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Cache\\FileStore->expiration(0)\n#2 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('setting-app-nam...', 'Book dD22', 0)\n#3 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever('setting-app-nam...', 'Book dD22')\n#4 /var/www/html/BookStack/app/Settings/SettingService.php(112): Illuminate\\Cache\\Repository->forever('setting-app-nam...', 'Book dD22')\n#5 /var/www/html/BookStack/app/Settings/SettingService in /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php on line 37

**Comment by dugs951** [comment]
PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to undefined method Illuminate\\Support\\Carbon::now() in /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php:37\nStack trace:\n#0 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(269): Illuminate\\Cache\\FileStore->availableAt(0)\n#1 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Cache\\FileStore->expiration(0)\n#2 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('setting-app-nam...', 'Book dD22', 0)\n#3 /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever('setting-app-nam...', 'Book dD22')\n#4 /var/www/html/BookStack/app/Settings/SettingService.php(112): Illuminate\\Cache\\Repository->forever('setting-app-nam...', 'Book dD22')\n#5 /var/www/html/BookStack/app/Settings/SettingService in /var/www/html/BookStack/vendor/laravel/framework/src/Illuminate/Support/InteractsWithTime.php on line 37

**Comment by ssddanbrown** [comment]
@dugs951 Okay, I think there's something else going on here. You could try deleting the `vendor/` folder within the bookstack install and re-run `composer install --no-dev` just as a test.

Otherwise, This could be cause by your webserver running a different PHP version than that used on the command line.
What version of Ubuntu are you using and have you installed multiple versions of PHP at any time?

**Comment by dugs951** [comment]
> @dugs951 Okay, I think there's something else going on here. You could try deleting the `vendor/` folder within the bookstack install and re-run `composer install --no-dev` just as a test.
> 
> Otherwise, This could be cause by your webserver running a different PHP  version than that used on the command line.
> What version of Ubuntu are you using and have you installed multiple versions of PHP at any time?

I try it but dont work.

When i look under /etc/php i have Version 7.1 and 7.4
When i make php -v then i have this version

PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies


I dont know what is the Problem, i make always upgrade without Problem.

**Comment by dugs951** [comment]
And i have Ubuntu 20.04

**Comment by ssddanbrown** [comment]
> When i look under /etc/php i have Version 7.1 and 7.4

Then there's a chance that Apache/Nginx is using PHP 7.1. Running `php -v` will only tell you the command line version of PHP in active use. 

- What webserver do you use?
- Do you know why you might have 7.1 on your system? Did you upgrade from an older Ubuntu version or manually choose to install 7.1?

**Comment by dugs951** [comment]
I use Apache2 
And i think Apache2 use 7.1 
When i look /etc/php/7.1 i have apache and php.ini
And 7.4 i dont have apache Order

How i can change php Version for Apache2?

**Comment by ssddanbrown** [comment]
You could try:

```
sudo a2dismod php7.1
sudo a2enmod php7.4
```

Alternatively, You may want to look to completely remove php7.1 from the system if you're sure it's not needed by anything else and re-install php7.4 to get to a clean php setup.

**Comment by dugs951** [comment]
Yes, i removed completely php then i install 7.4 and now is going.
Thank you so much.

**Comment by ssddanbrown** [comment]
Great news! Glad to hear the cause was found.
