### ISSUE TITLE
Question - Timezone in .env

### ISSUE THREAD

**Issue by joaomezzari** [BookStackApp/BookStack#2457]
Hello,

I changed my timezone settings in the .env file, but I don't see it reflecting it in the application. I used the São Paulo timezone like that:
APP_TIMEZONE=America/Sao_Paulo

But, if I check the auditory log, for example, the time is not correct... I believe it's using UTC still. Any ideas?

**Comment by ssddanbrown** [comment]
Hi @joaomezzari,

From my testing, changing the `APP_TIMEZONE` won't alter existing date times but new saved data will saved for the configured timezone. Do you get the same result?

**Comment by joaomezzari** [comment]
Hey @ssddanbrown, my bad! The behaviour is exactly as you said.
