### ISSUE TITLE
Docker with php-fpm

### ISSUE THREAD

**Issue by tchiotludo** [BookStackApp/BookStack#246]
For information, I've made a new docker version for Bookstack : https://github.com/tchiotludo/docker-bookstack-fpm
It's only php-fpm dockerfile, and allow you to choose the webserver.
I also provide a docker-compose file with spawn an nginx, mysql and bookstack.
The old version is apache2, mod_php based and consume a lot of memory that can't work with 1G server.

And thanks for the soft, it's simply works :smile:

**Comment by patoroco** [comment]
Great to know @tchiotludo :D
