### ISSUE TITLE
Show tags for search results

### ISSUE THREAD

**Issue by burnoutberni** [BookStackApp/BookStack#2462]
**Describe the feature you'd like**
I'd like to be able to see all tags of a given search result. This could look something like this:

![Screenshot from 2021-01-07 16-24-15](https://user-images.githubusercontent.com/1640933/103910202-d75f5400-5104-11eb-8cdf-ea23b7c45391.png)

One might also consider adding either a global or a search setting for this in order to make it optional, but personally I consider this useful and unintrusive enough to have around all the time.

**Describe the benefits this feature would bring to BookStack users**

We use BookStack as a internal knowledge base for our organization and have important metadata stored in our tags (such as datestamps if pages are related to an event). Showing this information would make it easier to pinpoint which search results are relevant. Probably that's the case for other users too.

**Additional context**
This feature request should be really simple to implement, but I wanted to double-check whether it has any chance of being added before starting a PR. Also, I have no experience with Laravel/Blade, so my implementation would probably be very basic (read: no extra settings, just adding the tags). If that sounds good to you, please let me know and I'll go ahead.

On a similar note, it would be great to use this tag metadata in other contexts too such as for sorting the search results (I already mentioned that in https://github.com/BookStackApp/BookStack/issues/577).

**Comment by ssddanbrown** [comment]
Thanks @burnoutberni! Closing as per #2487.
