### ISSUE TITLE
Copying a page doesn't copy the contents to the new page.

### ISSUE THREAD

**Issue by nickolasdeluca** [BookStackApp/BookStack#2463]
**Describe the bug**
After I updated from v0.30.3 to v0.31.1 I noticed that when I copy a page, it's contents are not copied over.

**Steps To Reproduce**
1. Create a page, type anything into the contents of the page, give it a name and save.
2. On the new page you just created, click on copy on the left sidebar, give it a new name and save.
3. The new page has the name you just typed, but it is empty.

**Expected behavior**
It should copy the contents of the page over to the new one, just as it did on v0.30.3.

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.31.1
 - PHP Version: 7.4.9
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Additional context**
I had a problem when updating my bookstack instance last time, where my database was behind on a couple of migrations, even though my database had the fields and tables that the missing migrations should add, I then created the migration records manually and tried to update again, which fixed the issue and I managed to update with no issues.

**Comment by ssddanbrown** [comment]
Thanks for reporting @nickolasdeluca.

Can confirm this is occurring when no markdown content exists on a page. 
Have marked as a priority to be fixed as part of the next patch release.

**Comment by nickolasdeluca** [comment]
Oh thank god it wasn't something I've done while fixing the migrations issue. haha

Looking forward to the fix, meanwhile I'll copy things manually.

**Comment by ssddanbrown** [comment]
This has been patched in 526be33ab2a88609e0178187e013e22081263ee3 with updated testing to cover. This will be part of v0.31.2 which should be released sometime today. Therefore I'll close this off.
