### ISSUE TITLE
Healthcheck Endpoint

### ISSUE THREAD

**Issue by modem7** [BookStackApp/BookStack#2467]
#### API Endpoint or Feature

A healthcheck endpoint where it returns an OK/200 if all is good.

#### Use-Case

Docker and Traefik both allow healthchecks to be performed, this is useful if there is a failure and the container needs rebooting/alerting that something isn't right.

**Comment by ssddanbrown** [comment]
Thanks for the request @modem7.

I'm thinking that this being part of the official API system may cause a lot more complexity than required (As you'd need to pass the right auth headers).

I think we could just add this as a publicly accessible, still JSON, endpoint. As long as we're not exposing anything private.
On request, We should probably perform:

- Simple DB query to ensure connection.
- Cache random value put/get check.

Return 200 status code unless any failure, in which case 500.

**Comment by modem7** [comment]
The publicly accessible endpoint would definitely be useful, that way we could also have it on loadbalancers with reverse proxies as well as docker/grafana etc.

**Comment by ssddanbrown** [comment]
Now included within 6eda1c1fb28142d432bf0ca05d7eaba9bf16f0d0, To be part of the next feature release (v0.32).
