### ISSUE TITLE
line break too early

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#2468]
A similar problem here:
https://github.com/BookStackApp/BookStack/issues/2265

At the moment the problem occurs in the recycle bin, when deleting and restoring:

![image](https://user-images.githubusercontent.com/4026090/104122392-94042000-5366-11eb-8e59-0987a95006a7.png)

**Comment by ssddanbrown** [comment]
Thanks for reporting @Statium.

I've patched this in 18f86fbf9b29460192d5e19341e81a954b9c1ac9 to be part of the next patch release.
