### ISSUE TITLE
Strikethrough not rendering (Markdown editor)

### ISSUE THREAD

**Issue by marianrh** [BookStackApp/BookStack#2470]
**Describe the bug**
The same issue as described and fixed in #2452 still seems to occur with text that is marked as being striked through.

**Steps To Reproduce**
1. Configure BookStack to use the Markdown editor
2. Create a new page anywhere and text marked as being striked through, e.g. `~~test~~`
3. Save the page
4. The page view displays `~~test~~` literally

**Expected behavior**
`test` should be displayed as striked through.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.31.2
 - PHP Version: 7.4.3
 - Hosting Method (Nginx/Apache/Docker): Apache

---

BTW, thank you very much for your work, @ssddanbrown! BookStack is amazing! I've migrated from Confluence, and administration and updates of BookStack are so much easier and performance is so much better :)!

**Comment by ssddanbrown** [comment]
Thanks for raising @marianrh, That's another part thing I'm surprised is not part of the commonmark spec. Should be an easy thing to add back in though.

And thanks for the feedback, good to hear from another confluence migrator!

**Comment by ssddanbrown** [comment]
This has now been patched and released as part of [v0.31.3](https://github.com/BookStackApp/BookStack/releases/tag/v0.31.3) so I'll therefore close this off. 

Thanks again for reporting.

**Comment by badsmoke** [comment]
with version v0.31.3, the problem still exists for me

**Comment by ssddanbrown** [comment]
@badsmoke Even when following the exact steps/syntax above, saving a new page?

**Comment by badsmoke** [comment]
thanks, that has fixed it
