### ISSUE TITLE
Non-Authenticated API access

### ISSUE THREAD

**Issue by commagray** [BookStackApp/BookStack#2471]
Hi!

#### API Endpoint or Feature

We have the Guest account, and it can be enabled to create and use API. It'll be good to have an ability to use the API without authentication.

#### Use-Case

Some programs (like Hugo static site generator) don't have an ability to use authentication headers, so they can't use the API.

Thanks.

**Comment by ssddanbrown** [comment]
Hi @commagray,
I saw Hugo added header support for requests:

https://gohugo.io/news/0.84.0-relnotes/#http-headers-in-getjsongetcsv

Otherwise, Do you still have a use-case for the requested feature here?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up and no evidence of existing requirement/need for this I'll close this off.
