### ISSUE TITLE
Audit Log; filter by User

### ISSUE THREAD

**Issue by SiddoSnow** [BookStackApp/BookStack#2472]
**Describe the feature you'd like**
In the admin Audit log, add an option to filter actions by user, in addition to the existing event filter and date ranges.

**Describe the benefits this feature would bring to BookStack users**
Currently, there is not - to my knowledge - a convenient way of reviewing a specific user's activity in the audit log.
This makes it difficult to determine a user's contributions as well as the nature of their contributions. 

Having the ability to sort by a particular user's actions would make admin review of malicious users significantly easier. It would also make the general administration significantly easier by giving a convenient overview of an individual user's contributions (or lack thereof), aiding in quality control.
Using their profiles is sub-ideal as it is only recent activity and not a complete log.

Example of what I imagine:
https://puu.sh/H5G0z/2cfa5fa13e.png

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @SiddoSnow.

I totally agree, I didn't add this filter before as we didn't have any pre-built "User Select" control but I had to add one for the content-owner changes in v0.31 which we can re-use here. Have marked for the next feature release.

**Comment by ssddanbrown** [comment]
Thanks again @SiddoSnow.

This has now been implemented, to be part of the next feature release.
