### ISSUE TITLE
Old links are not in transliteration

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#2474]
Previously, links on a page in a language other than English displayed in the system language and were ugly.
(https://localhost/books/%D1%87%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B9-%D0%B7%D0%BD%D0%B0%D0%BA-c81/page/%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82-%D0%BC%D0%B0%D1%80%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B9-%D0%BE%D0%B1%D1%83%D0%B2%D0%B8-%D0%B2-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5-%D1%87%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B9-%D0%B7%D0%BD%D0%B0%D0%BA)

Now links to new pages are transliterated, but links to old pages remain in the system language.

**Comment by Statium** [comment]
Also, links to books are still not translated.

**Comment by ssddanbrown** [comment]
Hi @Statium,

I'd expect old links not to be altered. The changes made will only apply for new URL slugs generated, which will occur when you save new content or when the name of something changes.

I have double checked on the current release and books do use the new slug generation system.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'll go ahead and close this.
