### ISSUE TITLE
Meta tags to uniquely Identify Bookstack among other technologies using laravel

### ISSUE THREAD

**Issue by bridgeyuwa** [BookStackApp/BookStack#2483]
**Describe the feature you'd like**
I am suggesting that meta tags should be added so that bookstack app can be uniquely Identified as Bookstack App and not only Laravel especially on websites like Wappalyzer, BuiltWith and WhatCMS

I will also like to know if it will be possible to add a feature which will automatically generate and update sitemap to improve search engine optimization

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @bridgeyuwa, but to be honest I don't really see the value of this.

As per the issue template, What benefit would this bring to existing BookStack users? 

I generally purposefully keep very few references to the platform being BookStack, Apart from a few default option values, some setting descriptions and the version link in the settings area.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up on this I'll close this off.
