### ISSUE TITLE
Copy Page does not copy the content

### ISSUE THREAD

**Issue by FredFu0234** [BookStackApp/BookStack#2486]
**Describe the bug**
Execute "Copy" on a page, select a destination page. Only the title is copied - not the content of the page.

**Steps To Reproduce**
1. Go to any page
2. Click on Menu 'Copy'
3. Select a destination book - click "Copy Page"
4. Now you are on the new page  - the title is correct but no content was copied.

**Expected behavior**
On step 4. I would expect a copy of the orignal page

**Your Configuration (please complete the following information):**
 - Reproducible on https://demo.bookstackapp.com

**Comment by ssddanbrown** [comment]
Hi @FredFu0234,
This is fixed in [v0.31.2](https://github.com/BookStackApp/BookStack/releases/tag/v0.31.2), I just haven't got round to updating the demo instance yet.
