### ISSUE TITLE
+1 for this. It seems like an easy feature to add that would make the user experience substantially more intuitive.

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#2489]
+1 for this. It seems like an easy feature to add that would make the user experience substantially more intuitive.

_Originally posted by @zachoooo in https://github.com/BookStackApp/BookStack/issues/1381#issuecomment-754352200_

**Comment by ssddanbrown** [comment]
I'm assuming this was not meant to be a new issue, but an accidental reference, therefore closing.
