### ISSUE TITLE
Image editor button missing

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#2493]
**Describe the bug**
Since my upgrade the edit buttons for width and height of images is missing. Last version was v0.26.

**Steps To Reproduce**
1. Edit a page
2. Insert an image
3. Select image and see no edit button

**Expected behavior**
A button for editing width, height, swapping image etc. for an image. Beneath the image or in the toolbar as a dropdown (similar to the Drawing Manager)

**Screenshots**
![image](https://user-images.githubusercontent.com/42382626/104817657-e049d700-5822-11eb-8c2a-5f0dc6eea489.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.31.3 
 - PHP Version: 7.2.24
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for reporting @Bolthier, My bad, I removed a plugin I thought was unused. 
Will be back in as part of BookStack v0.31.4, To be released shortly.
