### ISSUE TITLE
Restoring Revisions Changes Code from Markdown to HTML

### ISSUE THREAD

**Issue by kracken2222** [BookStackApp/BookStack#2496]
I was trying to see if this was already talked about or some sort of setting that I needed to change but I was not able to find any other posts or conversations on the issue.

After upgrading to V0.31+ I noticed that if I restored a page revision the page text would switch from Markdown to HTML and there was no easy way to change it back. 

Initial Save 

![image](https://user-images.githubusercontent.com/77635738/104947997-29fd0380-5982-11eb-860d-9334292901d5.png)

When I go back to edit the edit panel still is in markdown.
The issue happens when I go to restore a page to a previous revision. (left side Revisions page, click restore on previous version) 

![image](https://user-images.githubusercontent.com/77635738/104948121-6a5c8180-5982-11eb-8828-6d912495a680.png)

As you can see it all switched over to HTML and makes it hard to go back to how it was. 

I did not see this happening in versions before 0.31. Has anyone else been seeing this issue and is there a known fix I missed for this?

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.31.4
 - PHP Version: PHP 7.2.24-0ubuntu0.18.04.7
 - Hosting Method: Apache on ProxMox

**Comment by ssddanbrown** [comment]
Thanks for reporting @kracken2222, This was indeed a bug introduced in v0.31.

A patch has been applied in a7e3c26fe3418110cf1859774b7d2722aa3748c5 with testing to cover in 37de4e2e0aa2f7525cafa05d31e21999c2fc8877. This will be part of patch release v0.31.6 which is due within the next day or so.
