### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by modem7** [BookStackApp/BookStack#2507]
**Describe the feature you'd like**
Some form of image compression tool that compresses image either during upload and/or on demand (execute task) ala TinyPNG.

**Describe the benefits this feature would bring to BookStack users**
This would reduce image sizes across the board, making pages load faster, and less of a storage concern.

**Additional context**
Have been using https://tinypng.com to reduce images by approx 60-70% without noticeable degradation.

**Comment by ssddanbrown** [comment]
Thanks for the request @modem7.

I feel this is already covered by #2342 so I'm going to close this off as a duplicate.

**Comment by tipuraneo** [comment]
I wrote a script, please have a look here:
https://github.com/BookStackApp/BookStack/issues/2342#issuecomment-1698639777
