### ISSUE TITLE
Need CSS / SASS support

### ISSUE THREAD

**Issue by johnroyer** [BookStackApp/BookStack#2508]
Description:

I can not find any usage or CSS/SASS framework reference.  This make me afraid to mis-used CSS classes.

----

Exceptect:

I expect there is a front-end framework document for development. Or maybe a simple instruction to describe the basic design of SASS / CSS.

Thanks

**Comment by ssddanbrown** [comment]
Hi @johnroyer,

What are you attempting to do? There is no common framework at play here, no document, and none of the classes used, outside of page-content styling, are deemed stable in any way. 

I don't really want to have to document the css unless there's a significant use, it would be another thing to maintain and slow development.

**Comment by johnroyer** [comment]
I try to add a footer to show contact information or creative common license. I do not know if it is possible to break the layout while using wrong CSS classes.

**Comment by ssddanbrown** [comment]
Any use of classes may break since they're not officially supported. 

If you're fine with making your own modifications to the code, you'd generally just need to follow the existing patterns/classes used.

**Comment by ssddanbrown** [comment]
Will therefore close this off.

**Comment by bridgeyuwa** [comment]
I tried building a theme today to customize my bookstack from a Laravel Admin & Dashboard Template  and I got frustrated because of this issue.

:sweat: :sweat: :sweat:
:cry: :cry: :cry:
