### ISSUE TITLE
audit log and time zone

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#2509]
my php.ini configured like this

date.timezone = Asia/Yekaterinburg

the server is restarted, the cache is cleared, while the time is displayed incorrectly in the audit log and possibly in other places - the difference is 5 hours.

**Comment by ssddanbrown** [comment]
Hi @Statium,
You may need to set the following `.env` option: https://github.com/BookStackApp/BookStack/blob/master/.env.example.complete#L38

As an extra note, the reflected time of existing activity items will not change, But new activity items should adhere to that option.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Comment by dm-canteen** [comment]
Permalink for the above line: https://github.com/BookStackApp/BookStack/blob/92922288dd55ce0f77acc83eea9068cad28dccd9/.env.example.complete#L38
