### ISSUE TITLE
Wrong file Format pic upload

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#2516]
**Describe the bug**
I can no longer upload a picture, see screenshot

**Steps To Reproduce**
1. Click on "insert an image" in the editor.
2. click on the image selection bar
3. select image from finder

**Expected behavior**
image is uploaded and I can paste it into a post

**Screenshots**
![CleanShot 2021-01-29 at 10 53 48](https://user-images.githubusercontent.com/12276250/106260129-5afdf380-6220-11eb-8b5c-0e9f29b1738d.jpg)
![CleanShot 2021-01-29 at 11 23 01](https://user-images.githubusercontent.com/12276250/106263234-66ebb480-6224-11eb-92cd-ef2281494acb.jpg)

**Your Configuration (please complete the following information):**
- Exact BookStack Version (Found in settings): BookStack v0.31.4
- PHP Version: 7.4.14
- Hosting Method (Nginx/Apache/Docker): nginx

**Comment by Tealk** [comment]
Ok the error is that there are dots in the filename.

**Comment by ssddanbrown** [comment]
Thanks for confirming, Will therefore close since there are existing issues to review this validation check.
