### ISSUE TITLE
Include video upload in 'insert/edit media' panel

### ISSUE THREAD

**Issue by maggie0002** [BookStackApp/BookStack#2517]
**Describe the feature you'd like**
When editing a page, there is an Insert/edit media option:

<img width="538" alt="Screenshot 2021-01-29 at 12 23 57" src="https://user-images.githubusercontent.com/64841595/106324009-3b20fc80-622d-11eb-89bf-320534ae0d7a.png">

It would make the UI clearer if there could be a third tab there that allowed for uploading videos. I see the functionality is already there using the 'Attachments' feature. This same upload logic would be good to see integrated into a third tab to keep all the video adding functions together. Once uploaded, the default response would then be for BookStack to insert the newly uploaded video into the opened page as it does when you insert a link from the attachments tab (note, this is not inserting an embedded video to the BookStack link, as that opens a whole can of worms on permissions and rendering, it would just include a link to the file the same way the attachment option does). 

**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.

From a user interaction perspective, and when writing docs on how to upload videos, this ergonomic improvement would be a great help.

**Comment by ssddanbrown** [comment]
Thanks for the request @maggie0002,

This is already open in #882 so I'm going to close this off as a duplicate. Video on the web is still a tricky thing in terms of support, as shown within that issue, which makes me hesitant as if we provided a flow I'd want it to be easy and reliable for users.
