### ISSUE TITLE
Exporting Books (PDF/HTML)

### ISSUE THREAD

**Issue by joaorosad0** [BookStackApp/BookStack#252]
Hello, 
Thank you to develop this very and useful app. At first approach it's really cool.

### For Feature Requests
Desired Feature:  Possibility to export an entire book with all chapters and pages as a PDF / HTML.

I'm working in IT and I'm thinking about using your app to create all our customers IT documentations.
The concept is to dedicate a book for each customer and then create chapters per infrastructure categories and then have procedures or processes into this chapters.
I thought it will be interesting to add the feature that I'm asking to have the possibly to export the all documentation in one shoot and to print it for our usage or to give it to customer if they ask for.

Thank you for your feedback about the idea.
Joao Do Carmo Rosado

**Comment by Shackelford-Arden** [comment]
Seems kind of similar to #177 ? @joaorosad0

**Comment by joaorosad0** [comment]
Hello,
Yes you're right it's similar, sorry for the duplicate feature request.
Do you think this will be possible to implement ?
Thanks
Joao

**Comment by Shackelford-Arden** [comment]
@ssddanbrown Not sure if we want to close this and merge with #177 ? 

@joaorosad0 That's more of a question for Dan

**Comment by ssddanbrown** [comment]
@Shackelford-Arden Thanks, Yes, I will close this issue as it's a duplicate.

@joaorosad0 Yeah, I want to get v0.14 finished up then, for the next release (v0.15), I want to work on improving all the import/export capabilities.
