### ISSUE TITLE
Search does not find words after slash ("/")

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#2523]
Somewhat identical to issue #2095 ...

If the page title is `Bluetooth Audio Transmitter/Receiver Comparison` and one searches for `Receiver`, one doesn't get this particular page in the search results. (Workaround is to add spaces before and after the /, but one most of the time forgets that).

Guess one needs to create a full list of characters which should be internally, when it comes to searching, treated as blanks.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Wookbert.

I've made #2095 more generic now to centralise these requests so will therefore close this off.
