### ISSUE TITLE
Search books owned by me

### ISSUE THREAD

**Issue by Baptistou** [BookStackApp/BookStack#2529]
**Describe the feature you'd like**
Thank you for the great feature #2436 !
Now that we have a owner field, it would be a very nice feature to better identify books that we own.
For now, I found only two options available in the search page which are "Created by me" and "Updated by me".
I was thinking about 3 possible ideas :
- Add an option "Owned by me" in the search page
- Display the owner field in the list/grid view next or under book title.
- Set an automatic book tag "own" that we could search, or even better that could be displayed #2528 

**Describe the benefits this feature would bring to BookStack users**
Better identify books that we own.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Baptistou.

I can see the need, but I don't want to add any potentially confusing automatic tagging or clutter the listing views at all so the first option would be my preference, and should be relatively simple to add that for all assets types (Shelves, Chapters & Pages also).

Would you be happy for me to update the issue title to focus on the first option as a solution?

**Comment by Baptistou** [comment]
I agree that the first point is the most simple. Will it be possible to search books from other owners such as ``` {owned_by:John Doe}``` ?
This is why I proposed also the second point. It does make sense to search or sort books based on its owner, like in a library where books are stored by author.
Concerning the clutter issue, we generally see an image, the title and the author on a book cover. However, in BookStack we see an image, the title and the first sentence of content. What about reconsidering this choice ? Or what about adding a ```Toggle Details``` button like in home page ?

But this is probably two different issues. I will change the title and create another one.

**Comment by ssddanbrown** [comment]
Thanks to @benediktvolke this has now been merged into master and will be part of the next feature release.
