### ISSUE TITLE
Error with new registred members

### ISSUE THREAD

**Issue by Screamy86** [BookStackApp/BookStack#2539]
Hi,

a error occure while register new members. When a new member register a new account an error message appear on the screen after hitting the register button. The user is still getting created and after try to login he gets a message to resend the registration email. For the notes in have restricted the wiki for our domain. The original email is not sended, but the registration can be finished successfull with resend the mail and then hit the confirm button in the mail.

1. Open the wiki login page.
2. Click on the register new account button
3. Fill in needed information
4. click on register button, then the error appears

I expect a message that show a text like. A mail was sended to your provided emailadress, you have to confirm your account. 

**Your Configuration (please complete the following information):**
- Version BookStack v0.30-dev
- Windows Server 2016 with WAMP

here the info from the logfiles:
[2021-02-02 12:18:10] production.ERROR: Class 'BookStack\Uploads\Log' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'BookStack\\Uploads\\Log' not found at C:\\Wiki-Installationsordner\\BookStack\\app\\Uploads\\UserAvatars.php:32)
[stacktrace]
#0 C:\\Wiki-Installationsordner\\BookStack\\app\\Auth\\UserRepo.php(245): BookStack\\Uploads\\UserAvatars->fetchAndAssignToUser(Object(BookStack\\Auth\\User))
#1 C:\\Wiki-Installationsordner\\BookStack\\app\\Auth\\UserRepo.php(89): BookStack\\Auth\\UserRepo->downloadAndAssignUserAvatar(Object(BookStack\\Auth\\User))
#2 C:\\Wiki-Installationsordner\\BookStack\\app\\Auth\\Access\\RegistrationService.php(66): BookStack\\Auth\\UserRepo->registerNew(Array, false)
#3 C:\\Wiki-Installationsordner\\BookStack\\app\\Http\\Controllers\\Auth\\RegisterController.php(94): BookStack\\Auth\\Access\\RegistrationService->registerUser(Array)
#4 [internal function]: BookStack\\Http\\Controllers\\Auth\\RegisterController->postRegister(Object(BookStack\\Http\\Request))
#5 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#6 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('postRegister', Array)
#7 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Controllers\\Auth\\RegisterController), 'postRegister')
#8 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#9 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Route->run()
#10 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(BookStack\\Http\\Request))
#11 C:\\Wiki-Installationsordner\\BookStack\\app\\Http\\Middleware\\CheckGuard.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#12 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): BookStack\\Http\\Middleware\\CheckGuard->handle(Object(BookStack\\Http\\Request), Object(Closure), 'standard')
#13 C:\\Wiki-Installationsordner\\BookStack\\app\\Http\\Middleware\\RedirectIfAuthenticated.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#14 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): BookStack\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(BookStack\\Http\\Request), Object(Closure))
#15 C:\\Wiki-Installationsordner\\BookStack\\app\\Http\\Middleware\\GlobalViewData.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#16 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): BookStack\\Http\\Middleware\\GlobalViewData->handle(Object(BookStack\\Http\\Request), Object(Closure))
#17 C:\\Wiki-Installationsordner\\BookStack\\app\\Http\\Middleware\\Localization.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#18 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): BookStack\\Http\\Middleware\\Localization->handle(Object(BookStack\\Http\\Request), Object(Closure))
#19 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#20 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(BookStack\\Http\\Request), Object(Closure))
#21 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#22 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#23 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#24 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#25 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#26 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(BookStack\\Http\\Request), Object(Closure))
#27 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#28 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#29 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#30 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Request))
#32 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(BookStack\\Http\\Request), Object(Illuminate\\Routing\\Route))
#33 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(BookStack\\Http\\Request))
#34 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(BookStack\\Http\\Request))
#35 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(BookStack\\Http\\Request))
#36 C:\\Wiki-Installationsordner\\BookStack\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#37 C:\\Wiki-Installationsordner\\BookStack\\app\\Http\\Middleware\\TrustProxies.php(39): Fideloper\\Proxy\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#38 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): BookStack\\Http\\Middleware\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#39 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#40 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(BookStack\\Http\\Request), Object(Closure))
#41 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#42 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(BookStack\\Http\\Request), Object(Closure))
#43 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#44 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(BookStack\\Http\\Request), Object(Closure))
#45 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#46 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 C:\\Wiki-Installationsordner\\BookStack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(BookStack\\Http\\Request))
#48 C:\\Wiki-Installationsordner\\BookStack\\public\\index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle(Object(BookStack\\Http\\Request))
#49 C:\\Wiki-Installationsordner\\BookStack\\server.php(21): require_once('C:\\\\Wiki-Install...')
#50 {main}

Thanks for any help!

**Comment by ssddanbrown** [comment]
Hi @Screamy86,

It looks like you're using slightly-old development code to run BookStack. This reflects an error that would have been fixed in January. Did you intend to use the development code?

**Comment by Screamy86** [comment]
Hi, thank you for your reply! I used this command "composer install --no-dev" for installation. It was not intentional to use a dev version. What is the best way to update the current version to a no dev version?

**Comment by ssddanbrown** [comment]
@Screamy86 This is not an issue in how composer is used, but with how the application files were originally fetched. 

The manual install instructions state to use `git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch`. If using git to download/manage the files, you may have missed off the `--branch release` part of the command. 

If you downloaded the files manually from GitHub, then you would likely have got the development files. The following link can be used to get the release files direct from GitHub: https://github.com/BookStackApp/BookStack/archive/release.zip
That said, upgrades may be tricky as we don't support or offer instructions on updating via a non-git approach.

**Comment by Screamy86** [comment]
Hi,
the problem is, in our company network many things didnt work. So i tried many aproaches to install bookstack. When i install bookstack now with the release version. What do i need to do to get the data that i have now setup already into the new installation? Like i see it i just provide the database connction and copy the puvlic/uploads and sotrage/uploads into the new installation. And then it should work? Hopefully its tht easy :). But i guess not. If you have some tips, would be great.

**Comment by ssddanbrown** [comment]
@Screamy86 It should just be the steps you've mentioned.
If you downloaded those files after 31st Jan, then you've also got a database change that'll be for the next release which should not cause you issues in this case, but could be troublesome if I make changes to that before the next release, although that's probably unlikely.

**Comment by Screamy86** [comment]
Hi,
unfortunately its a much older version, i downloaded the package at 15.12.2020. Cause of the struggle with installation in our network i mentioned its not the up-to-date package. Can you provide me a link to a version that i should use to reinstall the wiki in relsease version? I will install this version, than import the database and folder and do a update after.  It should work best like this, i guess?

**Comment by ssddanbrown** [comment]
@Screamy86 Ideally the app files should be managed by git as per the manual install instructions. This will make updates much easier and more reliable. 

Git can be installed on windows if required: https://git-scm.com/

Otherwise my link post above 6 days ago has the link to the latest release files.

**Comment by Screamy86** [comment]
Hi,

ok i got it to work now with new version. Was straight forward. Now error is gone, Thanks for helping!

**Comment by ssddanbrown** [comment]
Thanks for confirming, Will therefore close this off.
