### ISSUE TITLE
In-page navigation with special characters does not work

### ISSUE THREAD

**Issue by montharon** [BookStackApp/BookStack#254]
I've noticed, that the automatically generated in-page-navigation feature does not work, if
the headline contains any special characters like brackets or the like...

<img width="723" alt="inpage-navig" src="https://cloud.githubusercontent.com/assets/21140797/21293364/88a27ef4-c522-11e6-92dd-3125e561f25a.PNG">

If I click on, let's say, "Receipe 02 (Doctor Faust)" on the right menu panel, nothing happens...

Keep up the great work Dan!
Cheers,
Mike

**Comment by ssddanbrown** [comment]
Hi @montharon, Thanks for reporting this issue. 

Unfortunately I can't seem to replicate this bug. When I create headings of the same name it works without issue. To help me solve this issue could you:

1. Copy the page content into a new test page and see if the issue occurs there.
2. If it still does occur, Copy the url of a non-working nav link and paste it here and also provide the HTML ID of the corresponding header (Let me know if you're unsure on how to find this).

Thanks,
Dan

**Comment by montharon** [comment]
Hi @ssddanbrown,

so, here is the corresponding url of the nav link
....books/miniature-painting/page/gold#bkmrk-rezept-02-%28doctor-fa

and here is the HTML ID of the corresponding header of the paragraph
<h4 id="bkmrk-rezept-02-%28doctor-fa">Receipe 02 (Doctor Faust)</h4>

Once again, many thanks for your great support Dan!
Cheers
montharon

**Comment by ssddanbrown** [comment]
@montharon Thanks for the extra details. I found that chrome just handles special characters natively whereas on firefox the issue could be seen. Now updated to find the correct block with JavaScript and added smooth scrolling and better highlighting. Fix will be in the next release.
