### ISSUE TITLE
Inform with maillists about new shelfentrys/books/sites

### ISSUE THREAD

**Issue by Screamy86** [BookStackApp/BookStack#2541]
Hi,

i would like a feature where i can setup maillists for specific Shelfs/book/site. So for example a new book will be added to the shelf, all users from the mailinglist will get a notification via mail. So the users dont have a excuse that they did not know the information provided by someone via the wiki. If there is such a feature already please tell me where i can find it.

**Comment by ssddanbrown** [comment]
Thanks for idea @Screamy86,

I feel this very much overlaps with the idea put forward in #1246, #147, #935 and #241 so I'm going to close this off to avoid duplicates.
