### ISSUE TITLE
redirect to http://84.145.113.77:6875/login

### ISSUE THREAD

**Issue by ragman1976** [BookStackApp/BookStack#2545]
Hi,

I tried to install bookstack via docker stack Here the stack I used:

---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=998
      - PGID=100
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=yourdbpass
      - DB_DATABASE=bookstackapp
    volumes:
      - /var/docker/bookstack/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=998
      - PGID=100
      - MYSQL_ROOT_PASSWORD=yourdbpass
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=yourdbpass
    volumes:
      - /var/docker/bookstack/data:/config
    restart: unless-stopped

After the process was completed I typed the ip-adress of the device I´m running docker (Raspberry4) 192.168.10.33:6875 but I got redirected to http://84.145.113.77:6875/login ???

Whats wrong?

Thanks in advance.

**Comment by ssddanbrown** [comment]
Hi @ragman1976,
Please set an `APP_URL` environment variable on the bookstack container for the domain you want to use BookStack on (`APP_URL=http://192.168.10.33:6875` for example)

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
