### ISSUE TITLE
Books and Chapters as templates

### ISSUE THREAD

**Issue by Mynster9361** [BookStackApp/BookStack#2550]
**Describe the feature you'd like**
Just like you are able to set a page as a template to later use it would be nice to be able to do the same with books and chapters if you have a lot of books or chapters that should look a like.
It would be much easier to just "copy" a book from a template which includes chapters / pages and pages within chapters.
And also set a "Template" permissions on the said book template

**Describe the benefits this feature would bring to BookStack users**
It would reduce it time it takes to import a lot of content from other places when you can predefine how you would like the book template to look like.
It would standardizes a way of making/having documentation.
It would make it easier for the end users to create a whole new book.
If you are able to predefine the permissions of a book it will make it easier for the users to not even have to look at it

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Mynster9361.

I think the core goal requested here is already covered by  #1123 and #808 so I'm going to close this off as a duplicate.
