### ISSUE TITLE
Is it possible to install bookstack under windows? How?

### ISSUE THREAD

**Issue by ThorsenRune** [BookStackApp/BookStack#2551]

**Comment by ssddanbrown** [comment]
Generally you'd use something like [XAMPP](https://www.apachefriends.org/download.html) (7.4 version) or [Laragon](https://laragon.org/) or WSL 2 or docker. These are all more kind of "development" setups though, the latter would really more be emulating Linux environments. The most production-like way on Windows would really be via IIS but that's not an area I have too much knowledge around.

**Comment by ThorsenRune** [comment]
Managed to do it.
Installed composer:https://getcomposer.org/
Installed XAMPP https://www.apachefriends.org/index.html
In XAMPP I started phpMyAdmin. Created the database with the name set in .env file
Opened a cmd terminal. 
Ran the steps described in the installation. ....fixed problems that I cant remember now....
Finally it runs on my windows 10 pc. 
If i find time ill write up the process and post it
