### ISSUE TITLE
Add the ability to lock pages

### ISSUE THREAD

**Issue by nickolasdeluca** [BookStackApp/BookStack#2555]
**Describe the feature you'd like**
I'd like to lock a page to prevent people and myself from editing or moving it. These kind of pages act as a template for other pages, the only thing I need them for is to copy them to another page and then edit this page and add what I need and sometimes my idiot self forgets to copy them and starts editing and saving the template page.

**Describe the benefits this feature would bring to BookStack users**
Have the ability to create page templates for books and prevent users and the owner from editing them mistakenly. 

**Additional context**
This feature should act simply as a validation, if the page is locked, no one can edit it or move it. If you have to do either of these actions to the page, you can simply click the lock button and unlock it.

**Comment by ssddanbrown** [comment]
Hi @nickolasdeluca,

You should be able to do this via setting page permissions, by removing edit permissions on this page. Ensure you still leave view permissions. If you use the default admin account you may have to create a new "Custom Admin" role, and use that instead, since the default Admin role always retains permissions.

**Comment by nickolasdeluca** [comment]
> Hi @nickolasdeluca,
> 
> You should be able to do this via setting page permissions, by removing edit permissions on this page. Ensure you still leave view permissions. If you use the default admin account you may have to create a new "Custom Admin" role, and use that instead, since the default Admin role always retains permissions.

Exactly, I can do that today creating new roles and stuff... but I don't like that idea. haha
Anyways, if the lock page is not worth developing, that's ok, I'll deal with it, but I thought it was a cool idea to have implemented.

**Comment by ssddanbrown** [comment]
Okay, I'll therefore close this off since It's something that can be served by the permission system with a little initial setup.
