### ISSUE TITLE
Failed to save draft constantly pops up.

### ISSUE THREAD

**Issue by DillFrescott** [BookStackApp/BookStack#2557]
**Describe the bug**
The message:  "Failed to save draft. Ensure you have internet connection before saving this page" pops up all the time even though I have a good connection to the page.

**Steps To Reproduce**
1. Start editing a page.
2. A few seconds later it pops up and keeps popping up in regular intervals.

**Expected behavior**
I'd expect for this not to always pop up as the connection to the server is fine.

**Screenshots**
https://i.ibb.co/T15qC6d/Capture.png

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.31.6 
 - PHP Version: I used the install script for Ubuntu 20.04. I don't know the PHP version.
 - Hosting Method (Nginx/Apache/Docker): Install script on Ubuntu 20.04.

**Additional context**
n/a

**Comment by DillFrescott** [comment]
I'm going to try installing it manually on Windows and see if that fixes the issue.

**Comment by DillFrescott** [comment]
That fixed it :)

**Comment by kevinblackdesk** [comment]
Yeah I have the same problem now. Installed it on an Ubuntu webserver.

![image](https://user-images.githubusercontent.com/69786972/108470013-90c75280-7289-11eb-91e0-8e0c8fd23a9d.png)

**Comment by DillFrescott** [comment]
@kevinblackdesk sorry I have no idea. I'm using XAMPP on windows so it could be whatever the web server it's using on Ubuntu causing it maybe?

Wish I knew more about the issue.

**Comment by DillFrescott** [comment]
@kevinblackdesk on Ubuntu the formatting for editing a page was all screwed up as well. For example, it wouldn't center text and code blocks were huge.
