### ISSUE TITLE
Discord Auth broken "The specified interactions endpoint url could not be verified."

### ISSUE THREAD

**Issue by Overbryd** [BookStackApp/BookStack#2558]
**Describe the bug**
When configuring Discord authentication according to the documentation (https://www.bookstackapp.com/docs/admin/third-party-auth/), the process cannot be completed, Discord will reject the Interactions Endpoint URL.
![Screenshot 2021-02-13 at 1 36 52 PM](https://user-images.githubusercontent.com/21111/107850288-9e03bd80-6e01-11eb-8def-7b5b6038a6aa.png)

BookStack responds with a 405 on the Interactions Endpoint URL.

```
172.19.0.4 - - [13/Feb/2021:12:42:32 +0000] "POST /login/service/discord/callback HTTP/1.1" 405 642 "-" "Discord-Interactions/1.0 (+https://discord.com)"
172.19.0.4 - - [13/Feb/2021:12:42:33 +0000] "POST /login/service/discord/callback HTTP/1.1" 405 642 "-" "Discord-Interactions/1.0 (+https://discord.com)"
```

**Steps To Reproduce**

1. Setup BookStack
2. Register a new Discord Application
3. Configure BookStack with the following settings from the Discord Application

    * "Client ID" as `DISCORD_APP_ID`
    * "Client secret" as `DISCORD_APP_SECRET`

4. Restart BookStack to pick up the changes
5. Back the Discord Application, enter the "Interactions Endpoint URL" according to your public BookStack instance

    e.g. `https://mybookstack.foo.com/login/service/discord/callback`

6. When you attempt to save your changes on the Discord Application, it will yield an error. In the background, Discord will send a request to your Bookstack instance, that you can see in your logs. Bookstack answers that request with 405 which is insufficient for Discord to verify the Bookstack "Interactions Endpoint URL"

**Expected behavior**

The "Interactions Endpoint URL" responds correctly to the Discord probe, so that the integration works.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.31.6
 - PHP Version: 
```
PHP 7.3.27 (cli) (built: Feb  4 2021 21:04:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
```
 - Hosting Method (Nginx/Apache/Docker): Docker

**Comment by ssddanbrown** [comment]
Hi @Overbryd,

Our instructions do not mention to set any kind of "Interactions Endpoint URL". I have also just double checked to ensure it's not something that's required. Just don't fill this input in for your application.

**Comment by random-persone** [comment]
when i type in my Interactions Endpoint URL and save it it doesnt save

**Comment by jeanhadrien** [comment]
> when i type in my Interactions Endpoint URL and save it it doesnt save

https://discord.com/developers/docs/getting-started#adding-interaction-endpoint-url
if you're following this guide, don't forget to add "/interactions" after the link...

**Comment by tensymbols** [comment]
It doesnt verify any links with numbers in it i guess? Because when i try to paste glitch link, it saves, but when i do the same with the link from ngrok example in guide it doesnt

**Comment by Mirviriam** [comment]
Context:  You're probably correct that boostackapp doesn't have it in there, but in trying to get started - when there's issues - we go back to basics like the discord instructions & glitch's instructions to try & see if it's something we can finesse.

I spent like 30 minutes chasing it from 3 guides & then just decided it wasn't worth the time.

Bit of info for whoever follows after - basically skip the interaction end point if you can at all but - verifying it can be done.  My browser was blocking discord's error from coming up initially.

Original post....

Still fails with /interactions ... full URL below, no other fields messed with, cleared cookies, did ipconfig flushes, restarted pc, tried alternative browsers & their privacy modes.  I setup another bot successfully in the same app, then reset the keys & tried to do the linked app next with same setup when I started getting the Endpoint URL issues.

> https://abrupt-rainbow-cobweb.glitch.me/interactions

Guide is out of date too - some of the field names don't match anymore, they mention an app.js & glitch asks for fields in the .env discord instructions don't include.

Discord guide specifically mentions we should have:

> To install slash commands, the app is using [node-fetch](https://github.com/node-fetch/node-fetch). You can see the implementation for the installation in utils.js within the DiscordRequest() function.

... but at that point guide they haven't asked us to fire off any commands to bring the utils.js into the glitch.com instance & it's not already included in the remix previously.

I switched to trying glitch side too:

> https://delightful-lace-throat.glitch.me

**Comment by yapgamer** [comment]
> > when i type in my Interactions Endpoint URL and save it it doesnt save
> 
> https://discord.com/developers/docs/getting-started#adding-interaction-endpoint-url if you're following this guide, don't forget to add "/interactions" after the link...

even after adding the /interactions it still doesn't work, it keeps saying "The specified interactions endpoint url could not be verified."

**Comment by ssddanbrown** [comment]
@yapgamer Are you doing this for BookStack auth? BookStack does not use interactions, and therefore does not need the interactions field to be filled. Have you tried leaving it empty as per my 2021 comment above?

**Comment by yapgamer** [comment]
@ssddanbrown sorry for not being clear, but I am using Glitch and following this tutorial(https://discord.com/developers/docs/getting-started) and when I get to the endpoint thing it does the error, also I just realised this is bookstack app discussion, becuase in my desperate search for answers I didnt pay attention to where I was posting.

**Comment by ssddanbrown** [comment]
Okay, I think this thread is commonly being found outside the context of BookStack so I'm going to lock this issue off to further comments. 

If you using BookStack with discord, you do not need to provide an interactions URL.
If you have other issues with discord and BookStack, please open a new thread.
