### ISSUE TITLE
Hope you add more language

### ISSUE THREAD

**Issue by IrfanArsyad** [BookStackApp/BookStack#2560]
### Language To Add

_Specify here the language you want to add._
INDONESIAN LANGUAGE
----
https://crwd.in/indotest
_   
please add indonesian language

**Comment by ssddanbrown** [comment]
Thanks for requesting to translate BookStack!

I've now added Indonesian as an option on crowdin for the BookStack project. I'll leave this open for a while but may remove it after a while if translations have not been started at all.
