### ISSUE TITLE
Colorpicker in Editor

### ISSUE THREAD

**Issue by Screamy86** [BookStackApp/BookStack#2565]
Hi,

we would need a colorpicker, for coloring tablecells. In my company there are many colleges that dont know much about how to get something to work when you using browserbased editors. So it would great to have a simple colorpicker as a icon in the editor. So it would copy by choosing a color the hexvalue into the clipboard. So they can paste this into the cell background properties. 

i added a simple screen from google colorpicker where you can choose the color and the hexvalue will be shown. in addition we wold need a ok button or something to copy the chosen color to the clipboard.

![image](https://user-images.githubusercontent.com/25805178/108188016-5e91e580-710f-11eb-9c54-ef26b1f0b199.png)

**Comment by geins** [comment]
+1 for that important feature

**Comment by ssddanbrown** [comment]
As of v22.02 a colorpicker now exists on WYSIWYG editor color configuration options.
