### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by nelsondani** [BookStackApp/BookStack#2567]
#### API Endpoint or Feature

Clearly describe what you'd like to have added to the API. 

#### Use-Case

Explain the use-case that you're working-on that requires the above request.

#### Additional Context

If required, add any other context about the feature request here.

**Comment by nelsondani** [comment]
30000[_29990[_5550_]()_]()

**Comment by ssddanbrown** [comment]
I don't really understand the request here since no information has been provided, Nor do I understand why you're cross-linking powershell repo issues with this project, so I'll close this off. 

If you are able to fill out the issue template feel free to open a new issue.
