### ISSUE TITLE
500 Internal Error after Installation

### ISSUE THREAD

**Issue by bridgeyuwa** [BookStackApp/BookStack#2569]
**Describe the bug**
getting  500 Internal Server Error on installation of Bookstack **0.31.6**

**Steps To Reproduce**

 Run a normal install using the installation instruction.

**Expected behavior**
It give a 500 Internal Server Error

 ```
**Internal Server Error**
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at postmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/7.4.14 Server at localhost Port 80
```

**Screenshots**
<a href="https://ibb.co/k8F3gWH"><img src="https://i.ibb.co/swr5vMm/Screenshot-12.png" alt="Screenshot-12" border="0"></a>

<a href="https://ibb.co/27KLWsk"><img src="https://i.ibb.co/0jJWmFG/Screenshot-13.png" alt="Screenshot-13" border="0"></a>

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (0.31.6):
 - PHP Version: 7.4.14
 - Hosting Method: Apache

**Additional context**
This is the error log from Xampp:
`[Wed Feb 17 23:41:11.473316 2021] [core:error] [pid 8568:tid 1872] [client ::1:2814] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.`

**Comment by ssddanbrown** [comment]
Hi @bridgeyuwa,
What version did you upgrade from?

Might be worth checking the `APP_URL` is set in your `.env` and matches the base URL you're hosting on.

**Comment by bridgeyuwa** [comment]
I didn't Upgrade... Its a fresh install from the Release branch  on Github.

and this is how it is set in my `.env`  `APP_URL=http://localhost`

**Comment by ssddanbrown** [comment]
@bridgeyuwa Hmm, Makes me think it's something on the apache side then. Is the Apache virtualhost definitely pointing to the `public` folder?

**Comment by bridgeyuwa** [comment]
I edited the `Config` in the **Xampp** to point here `DocumentRoot "C:/xampp/htdocs/bookstack/public"`

**Comment by benediktvolke** [comment]
@bridgeyuwa Try to add `RewriteBase /` in `public/.htaccess` right under `RewriteEngine On`
