### ISSUE TITLE
Subchapters, Re-ordering & Sorting

### ISSUE THREAD

**Issue by haynes11** [BookStackApp/BookStack#257]
I love bookstack! Missing a couple of features that I can live without but really would help with organisation and making my life easier!

### For Feature Requests
Desired Feature:

Sub-Chapters
Re-Ordering Of Pages
Re-Ordering Of Chapters
Re-Ordering of Pages/Chapters by Drag N' Drop?
Sort Alphabetically for pages/Chapters via one-click if so desired
Sort by time added for pages/Chapters via one-click if so desired

Kind Regards,
Jerome Haynes

**Comment by haynes11** [comment]
Also,

If exporting as pdf/whatever - option to have logo at the top.

**Comment by haynes11** [comment]
Feel rather stupid now... realised sorting is already there that allows this. Still after Sub-Chapters desperately though?!

**Comment by nwalke** [comment]
Subchapters is already being discussed here: https://github.com/BookStackApp/BookStack/issues/95

**Comment by haynes11** [comment]
Apologies must have missed it on my search. Thanks!

**Comment by LazyLama** [comment]
Is there any way the default [no filters set] to sort alphabetically windows style like books A-Z then under that chapters, then pages?
