### ISSUE TITLE
Don't scale down the application logo

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#2571]
Currently the application logo gets scaled down to 43px in height.

This doesn't look very good on a High DPI screen (above 100% scaling on Windows, most modern Macs, smart phones, etc.).

I'm not sure the scaling is necessary at all, but if we want to keep the scaling, 2x (86px) is probably a better height to scale to.

**Comment by ssddanbrown** [comment]
Thanks for raising @abulgatz,
I'd want to keep the scaling but agree, we should double it up for HighDPI.

**Comment by Hecke29** [comment]
Current code already contains `86px` for height-scaling (and does so since 2 years): https://github.com/BookStackApp/BookStack/blob/5e01c30882892089b2475a15830abf583a9cc486/app/Http/Controllers/SettingController.php#L61

Should it be doubled to `172` or is this task stale?

**Comment by abulgatz** [comment]
Actually, when I just tried uploading a logo, it didn't scale at all with my current latest Bookstack install, so I'm not sure what's going on?

**Comment by ssddanbrown** [comment]
@Hecke29 Thanks for checking, I'd say double should be enough.

@abulgatz Just tested it against the latest version and the logo got scaled to 86px. Is your uploaded image at least 86px in height or have you made any modifications to the code of your instance?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
