### ISSUE TITLE
Failed to (auto) save draft

### ISSUE THREAD

**Issue by kevinblackdesk** [BookStackApp/BookStack#2572]
**Describe the bug**
Getting a popup saying "Failed to save draft. Ensure you have internet connection before saving this page" while editing a page. Manually saving does work.

**Steps To Reproduce**
1. Edit a new page
2. Type something
3. See popup in screen after a few seconds

**Expected behavior**
To save the draft successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/69786972/108470555-6f1a9b00-728a-11eb-8400-fce4a7e5d3a6.png)
![image](https://user-images.githubusercontent.com/69786972/108470569-76da3f80-728a-11eb-9478-5551f8ac52d7.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.31.6
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Manually on a DirectAdmin server (CentOS)

**Additional context**
None.

**Comment by ssddanbrown** [comment]
Hi @kevinblackdesk,
Can you confirm if you have the `APP_URL` option set in your `.env` file, reflecting the base path that you have BookStack installed on?

**Comment by kevinblackdesk** [comment]
Hey @ssddanbrown, my `APP_URL` is set to the domain the BookStack application is installed on (ex: `APP_URL=https://docs.domain.nl`)

**Comment by ssddanbrown** [comment]
@kevinblackdesk Thanks for confirming.
Can you report any errors shown on draft save within the browser console? In the network tab screenshot you've shared i see failed in there, Clicking on the request may also provide more info. Just also want to ensure that the request is going to your domain.

**Comment by kevinblackdesk** [comment]
@ssddanbrown I'm seeing this in the console tab

![image](https://user-images.githubusercontent.com/69786972/108813291-09dbe800-75b1-11eb-86da-ab87e45fd7e7.png)

Website is served over HTTP2 (h2):

![image](https://user-images.githubusercontent.com/69786972/108813663-c0d86380-75b1-11eb-9c41-fa252eb3d80f.png)

**Comment by ssddanbrown** [comment]
@kevinblackdesk This would generally point to a an issue on the webserver configuration side. 

Are you able to share any details on that? Any headers or gzip configuration set at a webserver level could affect this, especially if in a proxy setup.

**Comment by kevinblackdesk** [comment]
@ssddanbrown Yeah, I'm just running a standard DirectAdmin server running on CentOS. I have Apache for handling PHP and Nginx for handling static content (images, scripts, etc). Both Apache&Nginx are serving content over HTTP2 (H2) and SSL. Standard Apache / Nginx configuration files except for the fact I had to create a rewrite for the `public/` folder to make Bookstack work.

**Comment by ssddanbrown** [comment]
@kevinblackdesk Okay, I don't think I've seen a setup like that before. I've seen proxying to apache servers but not using both depending on dynamic/static. It might be simpler just to use nginx+php-fpm. 

I'd suspect there's some dual https/gzipping going on in that setup causing headers to become invalid.

**Comment by kevinblackdesk** [comment]
@ssddanbrown Using an 'Nginx reverse proxy' is quite a common thing to do 😄

**Comment by cdrfun** [comment]
@kevinblackdesk Dan was referring to splitting dynamic and static content. I've used a Nginx reverse proxy using Nginx proxy manager with bookstack successfully in the past. Your setup is kinda special, I'd recommend simplifying things (in your case don't split dynamic and static content) to check if that works.

**Comment by ssddanbrown** [comment]
Thanks @cdrfun, You're spot-on here. I've seen & hosted a lot of nginx proxied apps before, but don't think I've ever seen two webservers serve the content for a single app, at least on the same protocol.

**Comment by kevinblackdesk** [comment]
> but don't think I've ever seen two webservers serve the content for a single app

Hey @ssddanbrown, It's just a simple nginx proxied app. One webserver serving the content for a single app, on the same protocol.

**Comment by ssddanbrown** [comment]
Okay, Have you tried disabling the https and/or gzip on the server you're proxying to at all?

**Comment by rednaxLamington** [comment]
I have the exact same problem, but running on IIS. Also ```safe as a draft``` fails (as the message already implies)
Save page is working.

Configuration:
- IIS on Windows 10
- PHP 7.4.16
- Edge
![doc-error](https://user-images.githubusercontent.com/13933387/113666267-5554dc00-96af-11eb-9f2f-db240e84a169.png)

**Comment by rednaxLamington** [comment]
I'm not an expert, but could it be the problem that in the file routes.php the routing to save-draft is missing?

**Comment by rednaxLamington** [comment]
After a lot of googling and checking parameters, I found the solution...

In IIS, you have to assign a module mapping, so it knows what to do when you request for example a .php file.
The problem was that verbs for this module only was: GET,HEAD,POST. Changing this to All verbs resolved my issue.
![verbs](https://user-images.githubusercontent.com/13933387/113733716-06349880-96fb-11eb-8cda-020a100ddb59.png)
