### ISSUE TITLE
[Bug] Attachment Upload Issue

### ISSUE THREAD

**Issue by athornfam2** [BookStackApp/BookStack#2575]
**Describe the bug**
Unable to upload attachments to existing or new articles.

**Steps To Reproduce**
1. Open a recent page
2. Click Edit
3. Click on the paperclip
4. Drag and drop or file upload a document

**Expected behavior**
It should upload the attachment, process it, and add it to the article.

**Screenshots**
![2021-02-20 14_57_43-Editing Page Create SCCM Device Col  _ BookStack](https://user-images.githubusercontent.com/74559383/108607129-8772de80-738c-11eb-806b-8dd0a074c5e0.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.31.6
 - PHP Version: 7.2.24
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Additional context**
None

**Comment by ssddanbrown** [comment]
Hi @athornfam2,
2MB is the default limit in a lot of cases on Apache.
Have you tried following the guidance here to increase the limit?: https://www.bookstackapp.com/docs/admin/upload-config/#changing-upload-limits

**Comment by athornfam2** [comment]
> Hi @athornfam2,
> 2MB is the default limit in a lot of cases on Apache.
> Have you tried following the guidance here to increase the limit?: https://www.bookstackapp.com/docs/admin/upload-config/#changing-upload-limits

I saw that but I thought the default was 10MB for Apache?

**Comment by ssddanbrown** [comment]
Checking this again, Apache often doesn't have limits itself but 2MB is the limit for at least one of the PHP options; So you'll need to check/change the options for the PHP config that Apache is using.
