### ISSUE TITLE
Feature Request: User language selection upon creation

### ISSUE THREAD

**Issue by digitall-it** [BookStackApp/BookStack#2576]
**Describe the feature you'd like**
BookStack allows for a default and a per user language settings. However, you can send a password initialization email only on default language. If you save the new user, the password initialization email cannot be sent anymore.

**Describe the benefits this feature would bring to BookStack users**
Better multilanguage support, less reliance of the concept of a default language

**Additional context**
Path to ```/settings/users/create``` allows either to send a password initialization email, or save and change language. I propose to add the language dropdown to the new user form, in the unsaved initial state. I also propose to add a button to send or resend the password initialization email.

**Comment by Baptistou** [comment]
Related issue : #2408

**Comment by ssddanbrown** [comment]
Thanks for the request @digitall-it,
As noted in  #2408, a user language select box has now been added to the create view with a default selected option reflecting the configured system default language.
This will be part of the next patch release so I will therefore close this off.
