### ISSUE TITLE
Export to html full shelf

### ISSUE THREAD

**Issue by magicman32** [BookStackApp/BookStack#2578]
**Describe the feature you'd like**
Current version only allows export to html from page level
I was hoping to export to html from a full shelf

**Describe the benefits this feature would bring to BookStack users**
Would be great to have an interactive backup of shelves

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @magicman32,
Shelf export is already open under #1138 so I'll therefore close this off as a duplicate.
