### ISSUE TITLE
Feature Request: multilanguage books

### ISSUE THREAD

**Issue by digitall-it** [BookStackApp/BookStack#2579]
**Describe the feature you'd like**
I would like to have multilanguage libraries, chapters and books, instead of having to create separate versions, sort of like Wikipedia multilanguage pages.

**Describe the benefits this feature would bring to BookStack users**
A right step to full i18n.

**Additional context**
Support in MediaWiki is [explained here](https://www.mediawiki.org/wiki/Multilingual_MediaWiki).

**Comment by ssddanbrown** [comment]
Hi @digitall-it,
Multi-language content has already been requested under #569 so I'll therefore close this off as a duplicate.
