### ISSUE TITLE
Delete uploaded images

### ISSUE THREAD

**Issue by bharadwajag** [BookStackApp/BookStack#258]
### For Feature Requests
Desired Feature: A normal user who has access to delete images, should able to delete uploaded images.

### Issue
We're using **BookStack v0.13.1**, we are facing problems when we trying to delete images. 

**Note**
- Admin level user who has full access is able to delete images.
- A normal user is not able to delete an image, even though he has access to delete images.
- We tried by giving access to attachments also, even though we are getting same error.
### Roles 
**Admin level access**
![admin-role](https://cloud.githubusercontent.com/assets/7804894/21539864/967848fe-cdd0-11e6-8efe-179b4725cc40.png)

**User level access**
![users-role](https://cloud.githubusercontent.com/assets/7804894/21539874/aefdc70a-cdd0-11e6-988c-36509a0a9d86.png)

### Error what we are getting
![bs-image-error](https://cloud.githubusercontent.com/assets/7804894/21539674/03369c4a-cdcf-11e6-83f6-1c1909c95a53.png)

We've checked **laravel.log** and it shows as below.

`[2016-12-29 05:32:08] production.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::jointPermissions()' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2440
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('jointPermission...', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->jointPermissions()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1436): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('jointPermission...', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->jointPermissions()
#5 /var/www/html/bootstrap/cache/compiled.php(11602): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1007): Illuminate\Database\Eloquent\Model->__call('jointPermission...', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1007): BookStack\Image->jointPermissions()
#8 [internal function]: Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(184): call_user_func(Object(Closure))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1008): Illuminate\Database\Eloquent\Relations\Relation::noConstraints(Object(Closure))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(810): Illuminate\Database\Eloquent\Builder->getHasRelationQuery('jointPermission...')
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(881): Illuminate\Database\Eloquent\Builder->has('jointPermission...', '>=', 1, 'and', Object(Closure))
#13 /var/www/html/app/Services/PermissionService.php(458): Illuminate\Database\Eloquent\Builder->whereHas('jointPermission...', Object(Closure))
#14 [internal function]: BookStack\Services\PermissionService->BookStack\Services\{closure}(Object(Illuminate\Database\Eloquent\Builder))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(771): call_user_func(Object(Closure), Object(Illuminate\Database\Eloquent\Builder))
#16 /var/www/html/app/Services/PermissionService.php(459): Illuminate\Database\Eloquent\Builder->where(Object(Closure))
#17 /var/www/html/app/Services/PermissionService.php(415): BookStack\Services\PermissionService->entityRestrictionQuery(Object(Illuminate\Database\Eloquent\Builder))
#18 /var/www/html/app/helpers.php(56): BookStack\Services\PermissionService->checkOwnableUserAccess(Object(BookStack\Image), 'image-delete')
#19 /var/www/html/app/Http/Controllers/Controller.php(103): userCan('image-delete', Object(BookStack\Image))
#20 /var/www/html/app/Http/Controllers/ImageController.php(160): BookStack\Http\Controllers\Controller->checkOwnablePermission('image-delete', Object(BookStack\Image))
#21 [internal function]: BookStack\Http\Controllers\ImageController->destroy(Object(BookStack\Repos\PageRepo), Object(Illuminate\Http\Request), '643')
#22 /var/www/html/bootstrap/cache/compiled.php(9385): call_user_func_array(Array, Array)
#23 /var/www/html/bootstrap/cache/compiled.php(9412): Illuminate\Routing\Controller->callAction('destroy', Array)
#24 /var/www/html/bootstrap/cache/compiled.php(8470): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(BookStack\Http\Controllers\ImageController), 'destroy')
#25 /var/www/html/bootstrap/cache/compiled.php(8451): Illuminate\Routing\Route->runController()
#26 /var/www/html/bootstrap/cache/compiled.php(8147): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/app/Http/Controllers/Controller.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/bootstrap/cache/compiled.php(9862): BookStack\Http\Controllers\Controller->BookStack\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/app/Http/Middleware/Authenticate.php(47): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/html/bootstrap/cache/compiled.php(9870): BookStack\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/bootstrap/cache/compiled.php(9978): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/bootstrap/cache/compiled.php(9870): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/bootstrap/cache/compiled.php(3151): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/bootstrap/cache/compiled.php(9870): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/bootstrap/cache/compiled.php(13464): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/bootstrap/cache/compiled.php(9870): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/bootstrap/cache/compiled.php(11907): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/bootstrap/cache/compiled.php(9870): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/html/bootstrap/cache/compiled.php(13210): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/bootstrap/cache/compiled.php(9870): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/bootstrap/cache/compiled.php(13147): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/html/bootstrap/cache/compiled.php(9870): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/html/bootstrap/cache/compiled.php(9855): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/html/bootstrap/cache/compiled.php(8148): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /var/www/html/bootstrap/cache/compiled.php(8139): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /var/www/html/bootstrap/cache/compiled.php(8130): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#56 /var/www/html/bootstrap/cache/compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/html/bootstrap/cache/compiled.php(3213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/html/bootstrap/cache/compiled.php(9870): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/html/bootstrap/cache/compiled.php(9855): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/html/bootstrap/cache/compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 /var/www/html/bootstrap/cache/compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 {main}  `

### For Bug Reports
PHP Version: 5.6.27

MySQL Version: 5.6.32

Expected Behavior: User should able to delete uploaded images, if he has access to delete images. 

Actual Behavior: A normal user who has access to delete images, is not able to delete uploaded images.

**Comment by ssddanbrown** [comment]
@bharadwajag Thank you for reporting this bug and apologies for any problems this may have caused you.

This will be fixed in the next release.

If you need this fixed sooner you can simply change [Line 398 in app/Services/PermissionService.php](https://github.com/BookStackApp/BookStack/blob/v0.13.1/app/Services/PermissionService.php#L398) to the following:

```
$nonJointPermissions = ['restrictions', 'image', 'attachment'];
```

**Comment by bharadwajag** [comment]
@ssddanbrown  
Happy to see this, thank you very much.
