### ISSUE TITLE
subscripe pages to get information about updates 

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2580]
**Describe the feature you'd like**
A way to subscribe pages, so that users which subscribed this get an email if this page updated with changes.

**Describe the benefits this feature would bring to BookStack users**
Users get informed over changes --> A good example is, when u a there documentaten about a customer and someone change informations in the documentation. So subscribed users will informed that there were changes like Name or nither

**Comment by Mynster9361** [comment]
This has already been requested here:

https://github.com/BookStackApp/BookStack/issues/147

https://github.com/BookStackApp/BookStack/issues/935

**Comment by ssddanbrown** [comment]
Thanks @Mynster9361.
Since this feature has already been requested I'll close this one off as a duplicate.
