### ISSUE TITLE
Problem on login with LDAP 

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2582]
**Describe the bug**
I configrated ldap-connection like the documentation now i have the problem that i can't login and some other too, but one person can ... --> same groups in ad. Same Problem on ldaps and ldap

**Steps To Reproduce**
Configurate the LDAP Connection like in the screenshot and tried to login

**Screenshots**
![2021-02-23 18_13_13-kb-one-001 - Royal TS](https://user-images.githubusercontent.com/67209365/108882199-6ae0db80-7604-11eb-84ea-1ca87a8d13d3.png)
![2021-02-23 18_12_34-Window](https://user-images.githubusercontent.com/67209365/108882207-6d433580-7604-11eb-82fd-d166fd2e8c97.png)

**Comment by pboatone** [comment]
just found a problem in the screenshot changed ldaps:\\  to ldaps:// --> but same issue

**Comment by awarre** [comment]
1. Are all desired users within the LDAP_BASE_DN OU?
2. Do all users match the filter criteria?
3. Does changing the filter to `(&(sAMAccountName=${user}))` resolve?

**Comment by pboatone** [comment]
oh i am so sry i foregot to close this issue. For LDAP you need to habe `(sAMAccountName=${user})` in the searchfilter, if you don't it makes only first match ......
But thx for your reply
