### ISSUE TITLE
Field for deleted pages?

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#2584]
Hi

Hope someone can help. I currently have a query that I run weekly that returns all the new pages that have been added in the previous 7 days. The query works fine, BUT if I forget to empty the BookStack recycle bin, these documents are included in the query results.

Is there a field in the PAGES table that flags when a page is deleted? If there is I can just add that as a criteria in my query.

Many thanks for any assistance - it will be greatly appreciated!

Mark

**Comment by ssddanbrown** [comment]
Hi @techauthoruk,
There should be a `deleted_at` timestamp field on the table. This will be `null` if the page is not deleted.

**Comment by techauthoruk** [comment]
@ssddanbrown 

Thanks Dan, that was most helpful
