### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by Haboubi92** [BookStackApp/BookStack#2588]
### Language To Add

Arabic
I'm native Arabic speaker and I'm prepared to provide translations for it.

**Comment by taha-mahmoud-ly** [comment]
Same here 😊

**Comment by ssddanbrown** [comment]
Hi @Haboubi92 & @taha-mahmoud-ly,
Arabic should already be available as an option within the application and via crowdin: https://crowdin.com/project/bookstack

Let me know if I'm missing something though.

**Comment by ssddanbrown** [comment]
Closing as there has been no further clarification.
