### ISSUE TITLE
Make pages with custom permissions more discoverable

### ISSUE THREAD

**Issue by pavlkx** [BookStackApp/BookStack#2589]
**Describe the feature you'd like**
If you share a page directly (through page custom permissions, but without any permissions on the book/chapter the page is in) with another user, the only way for that user to discover the page is: 
 - through direct link to the page
 - through the "recently updated/viewed pages" dasbhoard
 - through clicking on the little arrow at the top of the page once you are in a shared page (which will let you see all pages for the book shared in this way)

I think it should be possible to discover pages with direct permissions through regular Books menu - the Books menu should show the entire path (Book->Chapter->Page) to the page, but only show books/chapters that have at least one page for which the user has at least View permissions. 

**Describe the benefits this feature would bring to BookStack users**
Pages that have direct permissions set in this way are not discoverable by any user-friendly means. Accessing direct links by the user is not practical for any sort of knowledge base and "recently updated pages" dashboard may not contain the page user is looking for (plus, no user would look there for specific page).

Clicking the little arrow is not usable - most users will not even think to look there (as all the other content is accessed through the Books menu) and it will only offer pages from the same book (but the user has no way of knowing which page belongs to which book).

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @pavlkx.

> the Books menu should show the entire path (Book->Chapter->Page) to the page, but only show books/chapters that have at least one page for which the user has at least View permissions.

To be honest I don't want to go down that route. For that to occur, there'd be specific permissions applied to those pages and chapters to prevent viewing.  I think a solution along the lines of #182 may be more suitable.

**Comment by pavlkx** [comment]
All right, I understand if you do not want to do it this way. #182 would solve this problem as well and will benefit other use cases too.

Let's close this suggestion then, thank you for taking the time to consider it.

**Comment by ssddanbrown** [comment]
Thanks for your understanding.

Closing as suggested.
