### ISSUE TITLE
Export to PDF with hyperlinks in numbered lists results in unexpected output.

### ISSUE THREAD

**Issue by razem-io** [BookStackApp/BookStack#259]
PHP Version: using docker-compose.yml from solidnerd
MySQL Version: using docker-compose.yml from solidnerd (5.7.12)
Bookstack Version: 13.1

Expected Behavior:
When a numbered lists contains hyperlinks the output behind the number should still be aligned with the number when exporting to pdf.

Actual Behavior:
The output behind the number is slightly below the number when exporting to pdf.

**Comment by ssddanbrown** [comment]
Hi @razem-io, Sorry for my late reply, This issue slipped by. Would you be able to post a screenshot of the issue as I'm finding it hard to reproduce this.

**Comment by ssddanbrown** [comment]
Closing due to lack of response. Feel free to comment still and the issue can be re-opened.
