### ISSUE TITLE
Saving changes to users (possibly other forms) not working on Microsoft Edge

### ISSUE THREAD

**Issue by aekramer** [BookStackApp/BookStack#2590]
**Describe the bug**
While adjusting roles for a user, I noticed it would not update. After going through error logs and doing an update incase it was a bug, it still would not work.
Then I realized I am using Edge these days and used to have google chrome, and low and behold it worked fine on there.

**Steps To Reproduce**
1. Go to any user, and adjust their settings (add/remove a role)
2. Click on 'Save'
3. Instead of being redirected back to the Users page (with the top right notification "Succesfully saved user..") the form will refresh
4. The user was not updated (and no error was shown)

**Expected behavior**
To properly save the user

**Screenshots**
NA

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): Had it on 0.30.4 but now still on 0.31.6
 - PHP Version: 7.2.24 
 - Hosting Method (Nginx/Apache/Docker):  Nginx (Ubuntu 18.04)

**Additional context**
This may not be the only form with this issue, but its the only one I tested.

**Comment by ssddanbrown** [comment]
Thanks for reporting @aekramer,
Would you be able to confirm your exact version of edge in use?  I'd generally expect edge to behave the same as chrome with the fairly recent move for edge to use the same base project as chrome. Could possibly be an extension only existing in edge?

**Comment by aekramer** [comment]
> Thanks for reporting @aekramer,
> Would you be able to confirm your exact version of edge in use? I'd generally expect edge to behave the same as chrome with the fairly recent move for edge to use the same base project as chrome. Could possibly be an extension only existing in edge?

I am using Edge version 88.0.705.74 (64-bits)

While I do have a very barebones chrome (only use it for things that are not supported in edge, or if a website is behaving weirdly I test if its also the case in chrome, and as my laptop is relatively new chrome has been opened less than 10 times in total), edge also does not really have any extensions, I only use an adblocker and password manager. I just tried disabling them and the issue still persist (have not tried uninstalling completely as its a bit more hassle for now), I might try it on a different computer tomorrow that does not have these extensions in edge.

**Comment by ssddanbrown** [comment]
Thanks for confirming @aekramer. Tested on `Version 90.0.803.0 (Official build) dev (64-bit)` (Thier Linux build) and seems to work fine.

Something similar could occur if the browser was auto-filling the password field(s) in any way. You should see an error message below the fields but it might not be obvious, especially on a smaller screen.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
