### ISSUE TITLE
Please add Portuguese (European)

### ISSUE THREAD

**Issue by starkyller** [BookStackApp/BookStack#2593]
### Language To Add

pt_PT

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Thanks for requesting to translate to Portuguese, I've re-uploaded the pt_BR into this as a base. 
I've added this to crowdin now, and I'll keep it open unless there's been no translation activity after a while.
