### ISSUE TITLE
Icons on headers for links not visible but @icon() visible

### ISSUE THREAD

**Issue by kamleshbhure** [BookStackApp/BookStack#2596]
Hi All,

After completing installation, I am see only @icon() visible on login page and also after login on all other pages as well.

Can someone please help to resolve below issue?

Please find below screenshot
![bookstack_issue](https://user-images.githubusercontent.com/5301678/109390023-31c2a700-7935-11eb-8b4e-42ed77f6c1ba.png)

Thanks in advance.

**Comment by ssddanbrown** [comment]
That's rather odd, can you provide any details regarding your installation method or hosting of BookStack?

**Comment by kamleshbhure** [comment]
Below is bookstack.conf

```
server {
   server_name bookstack;
   root           /var/www/html/BookStack/public;
   index          index.php;

   location / {
                try_files $uri $uri/  /index.php?$query_string;
   }

   # Remove trailing slash to please routing system.
   if (!-d $request_filename) {
            rewrite     ^/(.+)/$ /$1 permanent;
   }

   location ~ \.php$ {
       #try_files $uri /index.php =404;
       try_files $uri =404;
       fastcgi_split_path_info ^(.+\.php)(/.+)$;
       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
       fastcgi_index index.php;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       include fastcgi_params;
   }

   listen 443 ssl; # managed by Certbot
   ssl_certificate /etc/letsencrypt/live/bookstack/fullchain.pem; # managed by Certbot
   ssl_certificate_key /etc/letsencrypt/live/bookstack/privkey.pem; # managed by Certbot
   include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
   ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = bookstack.gitaforlife.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


   server_name bookstack;
    listen 80;
    return 404; # managed by Certbot
}
```

**Comment by ssddanbrown** [comment]
@kamleshbhure That all looks fine. This would be something on the PHP side. Possibly permissions.

Can you try running `php artisan view:clear` on your instance. Also, Let me know if there are any issues when re-running `composer install`.

**Comment by kamleshbhure** [comment]
@ssddanbrown I tried running `php artisan view:clear` but doesn't helped. 
After I tried re-running `composer install` problem got solved. 
Thank you so much.
