### ISSUE TITLE
Live Search / Ajax Search / Typeahead Support?

### ISSUE THREAD

**Issue by Vondelphia** [BookStackApp/BookStack#2597]
Might you know if the search box input field has a working setup for live search? Maybe you know of a plugin someone already coded and shared that even works with Algolia?

Great project so far, love everything about it (except the search box) 😂😅.

**Comment by ssddanbrown** [comment]
Thanks for the request @Vondelphia and thanks for the kind feedback.

No way available right now to do what's requested.
I'm going to close this off since we already have #1235 which I feel covers this request.
