### ISSUE TITLE
stackedit.js as markdown editor

### ISSUE THREAD

**Issue by Baptistou** [BookStackApp/BookStack#2600]
**Describe the feature you'd like**
https://benweet.github.io/stackedit.js/
StackEdit.js is an opensource WYSIWYG markdown editor and it could be easily integrated into BookStack.
This is a very good alternative to the current TinyMCE HTML editor.
I tried and love both StackEdit.js and TinyMCE, but I prefer to use markdown over HTML for dev documentation.

**Describe the benefits this feature would bring to BookStack users**
Enhance the current markdown editor.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Baptistou but I would not consider stackedit to be suitable or something I'd want to integrate into the core BookStack project.

The fact it shows the markdown content makes it something that I don't see as suitable to replace the WYSIWYG editor.
 
Additionally I don't want to have to rely on an external system existing for what is a core part of the platform, and in that manner stackedit does not provide the customizability/configurability of something like the codemirror/tinymce libraries we use now. 

The fundamental request here is "Enhance the current markdown editor.". Watch out for a discussion later this year as there'll be a point where I'll be formally gathering feedback as part of the editor review roadmap item.

**Comment by Baptistou** [comment]
Hi @ssddanbrown , I just would like to highlight that [stackedit.js](https://github.com/benweet/stackedit.js) is different than [StackEdit](https://github.com/benweet/stackedit). The first is a library that you can download and include in an HTML file to be rendered in a textarea like Codemirror/TinyMCE while the latter is the SaaS editor.

**Comment by ssddanbrown** [comment]
@Baptistou from what I can see stackedit.js essentially just loads the sass offering in an iframe on the page (similar how we integrate with draw.io).

In terms of api and options, it's very different to codemirror and tinymce.

With some effort, You could already hack stackedit.js in now via custom html head content but it would not be integrated at the same level.
