### ISSUE TITLE
License setting for books and uploads

### ISSUE THREAD

**Issue by paviro** [BookStackApp/BookStack#2601]
**Describe the feature you'd like**
We just started using BookStack on https://knowledge.fm4f.org. 
For our use case it would be nice to be able to specify what license a book has and also what license uploads have. 
Ideally there would be a default setting for the whole site but individual assets like images or attachments could also have different licenses if needed.

**Describe the benefits this feature would bring to BookStack users**
For BookStack instances that host public information this would greatly improve the management of files with different licenses.

**Comment by ssddanbrown** [comment]
Hi @paviro,
Tjanks for the request. To be honest though, I don't really know what you mean by license. There's no existing conceptt of a "license" within BookStack. Could you explain what is meant by this?

**Comment by paviro** [comment]
Hi @ssddanbrown,
Thank you for your reply! [Here](https://commons.wikimedia.org/wiki/File:Codex_Manesse_197v_Goesli_von_Ehenheim.jpg) is an example on Wikimedia Commons, the image is public domain which can be seen by clicking on it in the article and going into the detail view. 

What I mean is it would be great if one could assign a license to uploaded attachments and images like for example:
File A is CC BY-SA 4.0.
File B is `copyright Person x`.

On our website for example I might get permission to use an image on our particular site from a copyright holder and some other images might be using a Creative Commons licence. Right now this is hard to note down. I can add a note below the image but this note will only be on the page I added it. If someone adds the same picture to another page the copyright information won't be there as its not linked to the upload.

The same thing would also be useful for book though here it would probably be one licence for all books on the site.

Does that clarify things?

**Comment by ssddanbrown** [comment]
Thanks for the clarification!

To be honest, I don't want to bog the platform down at all with additional metadata.  For shelves, books, chapter and pages you could make use of tags for this. Have a `License` tag with different values for the different licenses you'll want to apply.

**Comment by ssddanbrown** [comment]
After revisiting this later on, My thoughts still align with my above comment, so I'm going to close this off as out of scope since this is a level of metadata/detail I don't want to get into at this time.
