### ISSUE TITLE
Typo in spanish translation at user invite email subject

### ISSUE THREAD

**Issue by arcoai** [BookStackApp/BookStack#2608]
**Describe the bug**
There is a missing letter in the spanish translation of the user invite email subject.

**Steps To Reproduce**
1. Configure spanish as default language
2. Add a new user and check the option "Send user invite email"
3. See received email subject

**Expected behavior**
Current translation is: As sido invitado a unirte a :appName!
Fixed translation is: Has sido invitado a unirte a :appName!

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.31.7
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Closed in #2609
