### ISSUE TITLE
APP_URL in evn file gets changed

### ISSUE THREAD

**Issue by PascalMinder** [BookStackApp/BookStack#2613]
**Describe the bug**
I am not entirely sure why it happens. I think everytime my bookstack instance gets updated, the `.env` file changes, but only the `APP_URL=` gets changed. It's changed from my domain to an IP.
Since I use the docker container from linuxserver.io it also might be a problem from there.

**Expected behavior**
No changes in the config file.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.31.5 
 - Hosting Method (Nginx/Apache/Docker): Docker from Linuxserver.io and Traefik as reverse proxy

**Comment by ssddanbrown** [comment]
Hi @PascalMinder,

We don't do anything that would alter any `.env` options.
This will likely be [this functionality](https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L61) within the linuxserver.io container.

I think passing the correct `APP_URL` directly to the container may prevent it from auto-changing on run.

**Comment by PascalMinder** [comment]
> 
> 
> Hi @PascalMinder,
> 
> We don't do anything that would alter any `.env` options.
> This will likely be [this functionality](https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L61) within the linuxserver.io container.
> 
> I think passing the correct `APP_URL` directly to the container may prevent it from auto-changing on run.

Hey, thank you very much. I'll change it and will see what happens.
