### ISSUE TITLE
Email confirmation assigns role

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#2614]
**Describe the feature you'd like**
Would it be possible to change the registration so that you get a role assigned only after you have confirmed your email?

**Describe the benefits this feature would bring to BookStack users**
This could prevent spam, currently there are few possibilities.
e.g.:
Without confirmed email you would then only have view rights and if you confirm them you get editor.

**Comment by ssddanbrown** [comment]
Hi @Tealk,
Sorry for the late response, just coming across this while reviewing some other issues.

I'm not sure I see the purpose of this? When email confirmation is enabled, an account can't really be used to browse a BookStack instance so a difference in roles pre/post confirmation should not matter. 
Recently I've made changes to the auth process so a user won't even appear logged in, in any manner, until they confirm their email.

**Comment by Tealk** [comment]
> Sorry for the late response

No problem, thanks for your answer.

>  Recently I've made changes to the auth process so a user won't even appear logged in, in any manner, until they confirm their email.

If this is the case, then my request is no longer necessary.
