### ISSUE TITLE
Missing template options

### ISSUE THREAD

**Issue by chrisnewmanuk** [BookStackApp/BookStack#2623]
**Describe the bug**
No template content in side bar

**Steps To Reproduce**
Steps to reproduce the behavior on latest release:
1. create new page and save it
2. go back in and no content in templates from side bar
![image](https://user-images.githubusercontent.com/7243321/110310389-6819b980-7ffa-11eb-82a7-8aad27e90fd8.png)

**Comment by ssddanbrown** [comment]
Hi @chrisnewmanuk,
I would assume that no templates have been configured in your system and you also do not have permission to create new templates.

**Comment by chrisnewmanuk** [comment]
Thanks - got it now!  Hiding in the "admin" permissions :)
