### ISSUE TITLE
Bookstack Image Resolution

### ISSUE THREAD

**Issue by TurieE90** [BookStackApp/BookStack#2627]
Hi,

I am new to Github thanks to this issue I'm having with Bookstack. I have been uploading documentation and manuals to Bookstack for my organization and am finding that images are scaled down when I upload them.
I upload screenshots and images using the "insert an image" function, but they still come out blurry on the site and also when I export to PDF.

I will be very grateful if someone could help me with resolving this issue.

Thanks so much for your help in advance

**Comment by ssddanbrown** [comment]
Hi @TurieE90,
Images uploaded to BookStack should be auto-scaled to 1680px wide, which is 2x the default image display view which should ideally not be blurry. Also, if using the default WYSIWYG editor to insert images, you should be able to click through on the image to view the original. 

If you have a genuine example of an image where it becomes blurry after upload it would help to provide that if possible.

**Comment by TurieE90** [comment]
![view mentoring group](https://user-images.githubusercontent.com/80173110/111163776-c94e0980-8573-11eb-9bcc-4f03ed321ba3.png)

Hi @ssddanbrown,

Thanks for responding! I have attached an image for example.

**Comment by ssddanbrown** [comment]
Hi @TurieE90,
Sorry for my late response.

When uploading the provided image to BookStack I can't really see any difference in the uploaded result to be honest.
If you see that become blurry after upload, Would you be able to download and share the copy after upload to BookStack? Just so I can see a direct comparison of the two images before and after upload.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one and addressing the latest request on this issue.
