### ISSUE TITLE
upload articles

### ISSUE THREAD

**Issue by hexi** [BookStackApp/BookStack#2629]
Can i upload articles from local

**Comment by ssddanbrown** [comment]
Hi @hexi,

I'm not 100% sure what's meant by articles.
You can attach files to a page if needed. If you have existing HTML content, you may be able to insert it into a page via the `Source Code` button when editing. Alternatively there is an API that could be used to create pages if desired. 

There is no functionality to upload arbitrary content as a page outside of the above options.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
