### ISSUE TITLE
Redirect to requested URL instead of APP_URL

### ISSUE THREAD

**Issue by momab** [BookStackApp/BookStack#2640]
I am running Bookstack via Docker and am trying to get Bookstack behind a load balancing reverse Proxy (Traefix).
For this I am setting up the url ```wiki.domain.com``` and ```bookstack.domain.com```, from which to reach Bookstack.

For the multiple bookstack instances I have set up the hostnames ```bookstack-prod-1``` and ```bookstack-prod-2```, so I can access those if I need to.

Docker Config:
```
APP_URL = wiki.domain.com
APP_URL = bookstack.domain.com
```

I there any way to access bookstack from ```wiki.domain.com```, as well as ```bookstack.domain.com```? It keeps redirecting me to ```wiki.domain.com```.

**Comment by ssddanbrown** [comment]
Hi @momab,
No, BookStack only currently supports a single `APP_URL` value.

**Comment by momab** [comment]
Hi @ssddanbrown,
thanks for the response.

Is there any way to at least stop redirecting to the ```APP_URL```?

**Comment by ssddanbrown** [comment]
> Is there any way to at least stop redirecting to the APP_URL?

Not really. BookStack uses that as the base for all internal URL generation.

You could try setting the value to `""` or `null` in which case the platform may infer the URL from the request but we don't support it, its less secure and might cause further issues.

What's the purpose of load balancing across two domains? Seems pointless unless you're using two different DNS services and are super critical about DNS going down.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
