### ISSUE TITLE
Official Docker image for production needed

### ISSUE THREAD

**Issue by krswin** [BookStackApp/BookStack#2641]
**Describe the feature you'd like**
Please provide official Docker image for production use. thanks.

**Comment by ssddanbrown** [comment]
Hi @krswin,
Can you describe why this is needed? 
Is there something lacking in the [linuxserver.io bookstack container](https://github.com/linuxserver/docker-bookstack/)?

**Comment by Dayflare** [comment]
using the linuxserver.io image in production for around 100 users, everything runs fine.
You can always modify the docker-compose.yaml for specific configurations.

**Comment by krswin** [comment]
> Hi @krswin,
> Can you describe why this is needed?
> Is there something lacking in the [linuxserver.io bookstack container](https://github.com/linuxserver/docker-bookstack/)?

Yes in linuxserver.io External MySql server with port other then 3306(default mysql port) not working. DB_PORT is not mapping to the app.

**Comment by krswin** [comment]
> using the linuxserver.io image in production for around 100 users, everything runs fine.
> You can always modify the docker-compose.yaml for specific configurations.

@Dayflare 

Thanks for reply. Can you please also mention how do you connect to MySql server? Is it running on some IP address with random port(other then 3306)? 
Actually problem is this that port other then 3306 with linuxserver.io image not working I was checking for a long time. 
If you have some solution please share. thanks

**Comment by Dayflare** [comment]
> > using the linuxserver.io image in production for around 100 users, everything runs fine.
> > You can always modify the docker-compose.yaml for specific configurations.
> 
> @Dayflare
> 
> Thanks for reply. Can you please also mention how do you connect to MySql server? Is it running on some IP address with random port(other then 3306)?
> Actually problem is this that port other then 3306 with linuxserver.io image not working I was checking for a long time.
> If you have some solution please share. thanks

i'm using a mariadb container with default 3306 port as database.
Both containers need to be in the same docker network to find each other.

**Comment by ssddanbrown** [comment]
I'll now close this off, since the linuxserver.io team have responded to the main cause for this request, and since propose reasoning does not justify the effort in maintaining an official docker image.
