### ISSUE TITLE
Homepage for groups

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#2642]
Hello,

my idea came from the fact that I would have liked to have different start pages for guests and registriete users, but I think it would be easier if you do this right for groups.

The start page is really interesting for registered or administrators, but unfortunately not for guests, who would be better off at the shelves.

**Comment by ssddanbrown** [comment]
Thanks for the request @Tealk.

I'd consider this already covered by #1152 so I'm going to close this off as a duplicate.
