### ISSUE TITLE
NGINX Reverse Proxy issue

### ISSUE THREAD

**Issue by killmasta93** [BookStackApp/BookStack#2650]
Hi

I was wondering if someone could shed some light currently trying to configure NGINX with bookstack as reverse proxy as its currently with Apache, I changed the apache ports to 8080 and this is my NGINX config

but im now getting distortion picture

https://imgur.com/W4GA0Pi.png

```
server {

# listen 80 default_server;

# listen [::]:80 default_server;

listen 443 ssl;

server_name wiki.domain.com;

ssl_certificate /etc/letsencrypt/live/wiki.domain.com/fullchain.pem;

ssl_certificate_key /etc/letsencrypt/live/wiki.domain.com/privkey.pem;

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

ssl_prefer_server_ciphers on;

ssl_dhparam /etc/ssl/certs/dhparam.pem;

ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';


location ~ /.well-known {

root /var/www/letsencrypt;

allow all;

}

`# Add index.php to the list if you are using PHP`

`index index.html index.htm index.nginx-debian.html;`



location / {

proxy_pass http://192.168.3.190:8080/;

proxy_set_header X-Real-IP $remote_addr;

proxy_set_header Host $host;

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

`}`
```

**Comment by ssddanbrown** [comment]
I replied on reddit: https://www.reddit.com/r/selfhosted/comments/matu7d/bookstack_reverse_proxy_nginx/grus6rm/?utm_source=reddit&utm_medium=web2x&context=3

Let me know if neither of those apply and we'll have to start digging into the browser devtools to understand where those requests are going.

**Comment by killmasta93** [comment]
thanks for the reply,i realized the APP_URL i forgot to add the https it was http :=0
that fixed it

**Comment by ssddanbrown** [comment]
Glad to hear you found the cause!
