### ISSUE TITLE
Automatically apply shelf permissions to books

### ISSUE THREAD

**Issue by djmattyg007** [BookStackApp/BookStack#2652]
**Describe the feature you'd like**
Right now, a book's permissions automatically apply to the pages inside it. It would be nice if a shelf's custom permissions could automatically apply to all books within the shelf, without having to manually copy permissions to all books inside the shelf.

**Describe the benefits this feature would bring to BookStack users**
Less overhead in maintaining permissions, and less chance of making a mistake that accidentally reveals private information to public users.

**Comment by ssddanbrown** [comment]
Thanks for the request @djmattyg007.

This has come up before, It's worth reading through #1091 which covered the same request originally.

**Comment by djmattyg007** [comment]
I didn't realise a book could be on multiple shelves. That honestly seems confusing and breaks the physical library metaphor that BookStack seems to use.

**Comment by ssddanbrown** [comment]
Maybe, Although you can have copies of a book on mulitple shelves. It's not something that can be easily back-tracked upon at this stage.

Shelves are optional, If someone has no permissions to interact-with/view any shelves then the menu options won't show.

**Comment by djmattyg007** [comment]
I just came across #1171. It would be nice to see this implemented as an option. I appreciate it would likely create complexities around the database design though.

**Comment by ssddanbrown** [comment]
Okay. Since the original request here has been answered, and since #1171 remains open,  I'll close this off.
