### ISSUE TITLE
Summary hyperlink problem when exported as PDF with WKHTMLTOPDF

### ISSUE THREAD

**Issue by KinGsNowGH** [BookStackApp/BookStack#2653]
**Describe the bug**
Hyperlink on summary dsnt work when exported as PDF file using WKHTMLTOPDF.

**Steps To Reproduce**
1. Go to book
2. Export > PDF

**Screenshots**
![image](https://user-images.githubusercontent.com/61286068/112353840-e76de500-8caa-11eb-9aec-adb9cc8172f7.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.31.8
 - PHP Version: PHP 7.3.27
 - Hosting Method (Nginx/Apache/Docker): Docker linuxserver.io

**Comment by ssddanbrown** [comment]
Thanks for raising @KinGsNowGH.

Since this is already open under issue #2459 I'm going to close this off as a duplicate.
