### ISSUE TITLE
Add icon to links that open in a new window

### ISSUE THREAD

**Issue by frank-embleton** [BookStackApp/BookStack#2655]
**Describe the feature you'd like**
Links that open in a new window should have an icon as hint to the user.
_Example:_
![image](https://user-images.githubusercontent.com/61879399/112459404-15603180-8d5e-11eb-853f-347e230b1f6c.png)

**Describe the benefits this feature would bring to BookStack users**
This is common behaviour elsewhere online. The most obvious example I can think of is Wikipedia, where all external links have an icon after them  
_Reference implementation:_
![image](https://user-images.githubusercontent.com/61879399/112459023-ad115000-8d5d-11eb-8b8e-2c71d6ff9a64.png)

**Additional context**
I have successfully implemented it by adding the following snippet in the Custom HTML Head Content on the Settings page. I feel that it would be a useful default.
```
a[target=_blank][href*="//"]:not([href*="mysite.com"]):after {
    content: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAQElEQVR42qXKwQkAIAxDUUdxtO6/RBQkQZvSi8I/pL4BoGw/XPkh4XigPmsUgh0626AjRsgxHTkUThsG2T/sIlzdTsp52kSS1wAAAABJRU5ErkJggg==);
margin: 0 3px 0 5px;
}

```

**Comment by ssddanbrown** [comment]
Thanks for the request @frank-embleton.

The fundamental request has already been requested as part of #1620 so I'll therefore close this off as a duplicate.
