### ISSUE TITLE
419 - Page Expired on Android

### ISSUE THREAD

**Issue by rdbtn-no** [BookStackApp/BookStack#2659]
**Describe the bug**

After upgrading to 0.31.8, I can no longer access my bookstack installation from my phone, a Pixel 4 running Android 11.  Login information is correct, but always results in " 419 | Page Expired" error message.

**Steps To Reproduce**

1. Navigate to FQDN of bookstack installation using any Android Browser
2. Enter Username and password
3. Click "Log In"
4. See the error message "419 | Page Expired"

**Expected behavior**
Ideally, login would be successful.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.31.8
 - PHP Version: 7.4.3
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
This was working correctly with my original installation, which I believe was 0.30.0.  I have tried many different browsers to rule that out, including Firefox Nightly, Opera, latest version of Chrome, Brave and regular Firefox.  None work.  

I upgraded using the instructions here: https://www.bookstackapp.com/docs/admin/updates/
No other changes were made to the server (or the phone) except for the bookstack update.
Thanks!

**Comment by bridgeyuwa** [comment]
Your CSRF is failing.... session is active but token doesn't match maybe.

Try clearing your browser cookies.

If it still persists, then run `php artisan session:clear`

**Comment by ssddanbrown** [comment]
You can also check the `APP_URL` defined in your `.env` file and ensure it aligns with the page that your instance is accessed on.

**Comment by rdbtn-no** [comment]
> 
> 
> You can also check the `APP_URL` defined in your `.env` file and ensure it aligns with the page that your instance is accessed on.

This worked, but it was previously commented out, and had the default values.  Weird!

Thank you!
