### ISSUE TITLE
Duplicated operations being fired from multiple clicks on Save/Delete

### ISSUE THREAD

**Issue by TyDev7121** [BookStackApp/BookStack#2661]
It happens mostly for users with slow internet. After clicking once on buttons that would fire create, update or delete operations, before the process gets finished, if user click again, duplicated create, update, or delete would be fired again. For create,  duplicated Shelves/Books/Chapters/Pages get created; for update and delete, not found errors would show up.

Other than users with slow internet, for some users, it's natural to double, triple, sometimes even multiple click on a button trying to do a single save/delete operation. They would likely see the issue a lot due to this habit.

It is nothing big. Duplicated created items can be removed and the not found error is not actually affecting the intended operation. Just that it would be really nice if this can be handled gracefully for better user experience.

Repro steps for the not found error:
- Navigate to any page.
- Click on Delete.
- For delete page confirmation, **rapidly** click on CONFIRM in a very short amount of time (like 5-9 clicks per second). (Because it is hard to have slow internet for testing purpose, we need to click rapidly in order to get the same results.)
- The page not found error would show up due to multiple clicking.

There are similar issues for saving page while editing.

Repro steps for duplicate/multiple creation:
- Navigate to any shelve.
- Click on New Book.
- For creating new book, **rapidly** click on SAVE BOOK in a very short amount of time (like 5-9 clicks per second). (Because it is hard to have slow internet for testing purpose, we need to click rapidly in order to get the same results.)
- Duplicate/Multiple books would be created.

Test Environment:
- OS: Win 10
- Browser: Google Chrome, Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by ssddanbrown** [comment]
Thanks for the request here, but I'm going to go ahead and close this off. While we could add some handling to prevent duplicate submissions, I don't believe it'd be worth the added complexity at this time since I've had no other report/indication of this being an active issue for users.
