### ISSUE TITLE
Problems on export a book as pdf

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2666]
**Describe the bug**
When exporting a book as pdf there are a lot of problems with tables they look very bad --> But if you export the page all is fine

**Steps To Reproduce**
1. Go to book 
2. Export as pdf

**Screenshots**
Export the whole book
![export_book](https://user-images.githubusercontent.com/67209365/114032918-170d1780-987d-11eb-9d64-e82b8e88af1f.png)

Same page just export under page
![export_page](https://user-images.githubusercontent.com/67209365/114032942-1f655280-987d-11eb-84bf-30ee5b53330a.png)

**Comment by rednaxLamington** [comment]
Same issue here. 

Also, the icon of a callout is missing

**Comment by ssddanbrown** [comment]
Thanks @pboatone for reporting with clear examples. I've added a patch (95798a2ebacc617c5883aa0473e474fdfe4f2f8c) which should standardise the export styles used across books, chapters and pages and therefore solve this. Seems to look okay from my development instance testing. This will be part of the next patch release.

Will therefore close this off but if you still have issues after upgrading to v21.04.4 (Once released) feel free to open a new issue, referencing this one, or add a comment again here.
