### ISSUE TITLE
LDAP - Zentyal 7 AD sync issues

### ISSUE THREAD

**Issue by boka89** [BookStackApp/BookStack#2667]
Dear all,

In my home lab, I was using bookstack ldap sync with MS AD (trial), it was working fine. After I have replaced MS AD with Zentyal AD, ldap does not want to authenticate, even if I have deleted old users and tried to register new ones. The APP_DEBUG=true shows an invalid credentials error message, so I am guessing Zentyal AD has a different shema vs MS AD.
Did anyone manage to use Zentyal AD and?

Thanks in advance.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
