### ISSUE TITLE
Hyperlinks are not being rendered as hyperlinks

### ISSUE THREAD

**Issue by rajkumar-osm** [BookStackApp/BookStack#267]
### For Feature Requests
Desired Feature:

### For Bug Reports
PHP Version:

MySQL Version:

Expected Behavior:
Hyperlinks that we put in the content should be rendered as links automatically.

Actual Behavior:
Hyperlinks are not being rendered as links automatically, we have to add it manually.

**Comment by AbijeetP** [comment]
@ssddanbrown  - This should be pretty easy to do with https://www.tinymce.com/docs/plugins/autolink/

**Comment by ssddanbrown** [comment]
@rajkumar-osm Feature added in, Will be in the next release.

@AbijeetP Thanks for pointing me to the plugin, Made it very simple to add 👍
