### ISSUE TITLE
419 Page Expired

### ISSUE THREAD

**Issue by MFYDev** [BookStackApp/BookStack#2671]
After upgrade to the latest release which version is 21.04

I cannot log in on the win10 Chrome and Edge browser.

Every time when I log in, it displays things like this:

![image](https://user-images.githubusercontent.com/53750381/114265361-f088e100-9a22-11eb-92d6-a2004a814bef.png)

**What's the most weird thing is, I can log in on my phone, which is Android 11 MIUI Edge browser.**

This issue has never happened before this upgrade. I can assure the `APP_URL` in the env file is correct.

Please investigate as it is really an emergent problem.

**Comment by ssddanbrown** [comment]
Hi @MFYDev,

- What version did you upgrade from?
- Does the `APP_URL` value exactly match the public base URL for Bookstack, that will be accessed in the browser including the starting https/http, with no trailing slash?
- Are you always connecting over https? Or both http and https? or just http?
- What files exist in the `bootstrap/cache` folder within your BookStack install folder?

**Comment by MFYDev** [comment]
Hi @ssddanbrown ,


> * What version did you upgrade from?

I upgraded from 0.31.8

> * Does the APP_URL value exactly match the public base URL for Bookstack, that will be accessed in the browser including the starting https/http, with no trailing slash?

Yes, definitely, it works well in all version before v21.04

> * Are you always connecting over https? Or both http and https? or just http?

I always use https, and I have turned on forcing https.

> * What files exist in the bootstrap/cache folder within your BookStack install folder?

There are 3 files: `.gitignore` , `packages.php` , `services.php`

**Comment by MFYDev** [comment]
Dear Dan,

After a long time investigation of `.env` file, I finally found out what parameter cause this problem.

It is `ALLOWED_IFRAME_HOSTS`

This value is the new parameter and firstly I just set it as `ALLOWED_IFRAME_HOSTS="https://mfy.world"` which is my wordpress blog.

From my perspective I thought it can make my blog iframe bookstack page in the passage. But I do not know why, remove this line makes all thing works well again

**Comment by ssddanbrown** [comment]
That value appears correct, Were you getting the 419 issue just on embedded/iframed versions of Bookstack or did you get this error all the time, even when using the proper domain?

Setting that value does change how cookies are handled. It may be the case that old cookies are interfering with new cookies that BookStack is attempting to set. It'll be worth completely clearing cookies, or trying to login & use BookStack within a fresh incognito/private window to see if the issue remains.

**Comment by MFYDev** [comment]
I get this error all the time even I use the proper domain.

So I did a quick test according to your advise.

Firstly, I add that parameter again and view bookstack in private window, this issue still happens.

Then, I tried to clean all the cookies and cache of my browser and view it again. Still, this problem exists.

It is really weird.

**Comment by Zetman13** [comment]
@MFYDev I had similar problem - 419 on Firefox, WIndows 10, but ok on Firefox, Android. Fixed with clearing cache in PC browser. Have you tried it?

**Comment by shmoulana** [comment]
Guys we are also getting the same thing ?

Any solution for this ?

**Comment by MFYDev** [comment]
> Guys we are also getting the same thing ?
> 
> Any solution for this ?

Honestly not any yet.

I suggest not using this parameter until @ssddanbrown found out where the problem exactly is.

**Comment by ssddanbrown** [comment]
@MFYDev I've setup a replicated test of using this option here: https://danb.me/embed.html

Can you attempt login to the demo site via the iframe in that test page and let me know if that works for you?

**Comment by MFYDev** [comment]
@ssddanbrown Sorry for the delay mate.

Using admin@example.com with password as password, I can successfully log in to this test site.

Would you please tell me if you set any other parameter that is not default which may affect this problem?

Thank you so much in advance.

**Comment by ssddanbrown** [comment]
@MFYDev This is the entire contents of the `.env` for the demo site:

```shell
APP_ENV=demo
APP_DEBUG=false
APP_KEY=REDACTED

DB_HOST=localhost
DB_DATABASE=REDACTED
DB_USERNAME=REDACTED
DB_PASSWORD=REDACTED

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=log
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

GITHUB_APP_ID=false
GITHUB_APP_SECRET=false
GOOGLE_APP_ID=false
GOOGLE_APP_SECRET=false

# URL for social login redirects, NO TRAILING SLASH
APP_URL=https://demo.bookstackapp.com

ALLOWED_IFRAME_HOSTS="https://danb.me"
```

If you're able to provide an example of a failing embed I can inspect the headers and make sure everything is aligned or see if there are other things causing interference. Don't need access/login to the BookStack instance, just an example of it embedded.

**Comment by MFYDev** [comment]
Dear Dan @ssddanbrown ,

Thanks for the information.

I set a personal test embed site for my personal BookStack website: [https://api.mfy.world/test/embed.html](https://api.mfy.world/test/embed.html)

And here is my `.env` file in the following, it is so long so I have to fold it, feel free to unfold it:

<details>

```bash
# This file, when named as ".env" in the root of your BookStack install
# folder, is used for the core configuration of the application.
# By default this file contains the most common required options but
# a full list of options can be found in the '.env.example.complete' file.

# NOTE: If any of your values contain a space or a hash you will need to
# wrap the entire value in quotes. (eg. MAIL_FROM_NAME="BookStack Mailer")

# Application environment
# Can be 'production', 'development', 'testing' or 'demo'
APP_ENV=production

# Enable debug mode
# Shows advanced debug information and errors.
# CAN EXPOSE OTHER VARIABLES, LEAVE DISABLED
APP_DEBUG=false

# Application key
# Used for encryption where needed.
# Run `php artisan key:generate` to generate a valid key.
APP_KEY=REDACTED

# Application URL
# This must be the root URL that you want to host BookStack on.
# All URLs in BookStack will be generated using this value
# to ensure URLs generated are consistent and secure.
# If you change this in the future you may need to run a command
# to update stored URLs in the database. Command example:
# php artisan bookstack:update-url https://old.example.com https://new.example.com
APP_URL=https://mfy.wiki

# Application default language
# The default language choice to show.
# May be overridden by user-preference or visitor browser settings.
APP_LANG=zh_CN

WKHTMLTOPDF=/usr/local/bin/wkhtmltopdf

# Auto-detect language for public visitors.
# Uses browser-sent headers to infer a language.
# APP_LANG will be used if such a header is not provided.
APP_AUTO_LANG_PUBLIC=true

# Application timezone
# Used where dates are displayed such as on exported content.
# Valid timezone values can be found here: https://www.php.net/manual/en/timezones.php
APP_TIMEZONE=Asia/Shanghai

# Database details
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=REDACTED
DB_USERNAME=REDACTED
DB_PASSWORD=REDACTED

# Mail system to use
# Can be 'smtp', 'mail' or 'sendmail'
MAIL_DRIVER=smtp

# Mail sending options
MAIL_FROM=REDACTED
MAIL_FROM_NAME=REDACTED

# SMTP mail options
MAIL_HOST=REDACTED
MAIL_PORT=REDACTED
MAIL_USERNAME=REDACTED
MAIL_PASSWORD=REDACTED
MAIL_ENCRYPTION=SSL

# Cache & Session driver to use
# Can be 'file', 'database', 'memcached' or 'redis'
CACHE_DRIVER=file
SESSION_DRIVER=file

# Session configuration
SESSION_LIFETIME=120
SESSION_COOKIE_NAME=bookstack_session
SESSION_SECURE_COOKIE=false

# Cache key prefix
# Can be used to prevent conflicts multiple BookStack instances use the same store.
CACHE_PREFIX=bookstack

# Queue driver to use
# Queue not really currently used but may be configurable in the future.
# Would advise not to change this for now.
QUEUE_CONNECTION=sync

# Storage system to use
# Can be 'local', 'local_secure' or 's3'
STORAGE_TYPE=local

# Image storage system to use
# Defaults to the value of STORAGE_TYPE if unset.
# Accepts the same values as STORAGE_TYPE.
STORAGE_IMAGE_TYPE=local

# Attachment storage system to use
# Defaults to the value of STORAGE_TYPE if unset.
# Accepts the same values as STORAGE_TYPE although 'local' will be forced to 'local_secure'.
STORAGE_ATTACHMENT_TYPE=local_secure

# Authentication method to use
# Can be 'standard', 'ldap' or 'saml2'
AUTH_METHOD=standard

# Social authentication configuration
# All disabled by default.
# Refer to https://www.bookstackapp.com/docs/admin/third-party-auth/
# REDACTED ALL

# Enable diagrams.net integration
# Can simply be true/false to enable/disable the integration.
# Alternatively, It can be URL to the diagrams.net instance you want to use.
# For URLs, The following URL parameters should be included: embed=1&proto=json&spin=1
DRAWIO=true

# Default item listing view
# Used for public visitors and user's without a preference.
# Can be 'list' or 'grid'.
APP_VIEWS_BOOKS=list
APP_VIEWS_BOOKSHELVES=grid
APP_VIEWS_BOOKSHELF=grid

# Use dark mode by default
# Will be overriden by any user/session preference.
APP_DEFAULT_DARK_MODE=false

# Page revision limit
# Number of page revisions to keep in the system before deleting old revisions.
# If set to 'false' a limit will not be enforced.
REVISION_LIMIT=50

# Recycle Bin Lifetime
# The number of days that content will remain in the recycle bin before
# being considered for auto-removal. It is not a guarantee that content will
# be removed after this time.
# Set to 0 for no recycle bin functionality.
# Set to -1 for unlimited recycle bin lifetime.
RECYCLE_BIN_LIFETIME=30

# Allow <script> tags in page content
# Note, if set to 'true' the page editor may still escape scripts.
ALLOW_CONTENT_SCRIPTS=false

# Indicate if robots/crawlers should crawl your instance.
# Can be 'true', 'false' or 'null'.
# The behaviour of the default 'null' option will depend on the 'app-public' admin setting.
# Contents of the robots.txt file can be overridden, making this option obsolete.
ALLOW_ROBOTS=null

# The default and maximum item-counts for listing API requests.
API_DEFAULT_ITEM_COUNT=100
API_MAX_ITEM_COUNT=500

# The number of API requests that can be made per minute by a single user.
API_REQUESTS_PER_MIN=180

# Enable the logging of failed email+password logins with the given message.
# The default log channel below uses the php 'error_log' function which commonly
# results in messages being output to the webserver error logs.
# The message can contain a %u parameter which will be replaced with the login
# user identifier (Username or email).
LOG_FAILED_LOGIN_MESSAGE=false
LOG_FAILED_LOGIN_CHANNEL=errorlog_plain_webserver

ALLOWED_IFRAME_HOSTS="https://api.mfy.world"
```
</details>

**Comment by ssddanbrown** [comment]
@MFYDev No problem, Happy to hear you git it working!

I'd imagine it was just the `SESSION_SECURE_COOKIE=false` line that was causing issues, This would conflict with the requirements for cookies to be used in an embedded context. BookStack will now dynamically set that option anyway based upon your `APP_URL` value.

**Comment by willre** [comment]
> Dear Dan @ssddanbrown ,
> 
> Thanks for the information.
> 
> I set a personal test embed site: https://api.mfy.world/test/embed.html
> 
> Finally I found out things make this issue happen:
> 
> ```shell
> # Session configuration
> SESSION_LIFETIME=120
> SESSION_COOKIE_NAME=bookstack_session
> SESSION_SECURE_COOKIE=false
> ```
> 
> After I deleted these session configuration parameters, all things work again.
> 
> I should have thought of deleting these lines earlier after searching `419 page expired` in google, because most of answers saying that error is related to session. 😥
> 
> It seems although I always wanna use the complete env file to take full control of my site. but some of the unfamiliar parameters will still cause small problems. I should know more about them before using them.
> 
> **Thank you so much for all the replies and patience. Lessons are learned for me after all these.**

I have encountered the same problem, which can be solved according to @MFYDev  method

**Comment by shhoppe** [comment]
When I went to implement the @MFYDev method, I found that those lines did not exist in my .env so I added them, which resolved the issue for me.
When it happens again, then I'll remove them.

**Comment by vdawg-git** [comment]
I am also facing this issue after adding an URL to `ALLOWED_IFRAME_HOSTS`.

@shhoppe Have you set `SESSION_SECURE_COOKIE` to false or true?

**Comment by shhoppe** [comment]
For me, I think it has something to do with the way my server handles sessions, so what I do for the moment is toggle.  When the issue occurs, then if it's true I set to false and vice versa.  Not ideal, but it suits me until I finally find some time to look at things more deeply.

**Comment by ash34** [comment]
I see this is marked as closed but I experience the 419 page expired issue with a new install (I'm new to Bookstack).

After logging in and using for maybe 2-3 minutes I will receive the 419 page. I experimented with changing SESSION_LIFETIME=120 to SESSION_LIFETIME=12000 as a temporary workaround but was there a fix for this?

**Comment by ssddanbrown** [comment]
@ash34 The default session time should already by two hours, so I wouldn't expect changing that to affect that particular issue, unless something else was off in regard to that setting.

Otherwise, it's hard to determine exactly what may lead to a 419 without knowing the exact reproduction steps and environment. Sometimes URL misconfiguration, or recently changed session/cookie settings, or browser controls/extensions, or embedding techniques, or failed requests to load things via BookStack, can trip up the session.

**Comment by krismarc** [comment]
@ssddanbrown,

same story here. I'm running bookstack as the add-on in Home Assistant. As long as I do not set ALLOWED_IFRAME_HOSTS all works fine. Once it set this value, I start getting 419 page expired. Happens only in Chrome. In firefox all fine, even with this var.
https://community.home-assistant.io/t/bookstack-embedded-into-dashboard/775013/3

doesn't matter if I access the app directly or from the iframe.

**Comment by eric-saintetienne** [comment]
Same here, with `ALLOWED_IFRAME_HOSTS` set, I get the page expired issue, irrespectively of any frame (inside or outside an iframe). I'm using Firefox.

**Comment by Soosbrecht** [comment]
Did you manage to fix this problem? I have the same issue when trying to embedd the iframe. I get the 419Error when trying to log in through the frame. When accesing bookstack directly i the login screen gets stuck in a loop (correct login data but not loggin in). If i rmeove the allowed_iframe_hosts it works fine.
