### ISSUE TITLE
Audit log inputs heights and paddings are inconsistent 

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#2678]
On the audit page, the heights of the blocks are different. Also, the user selection field has incorrect indentation.
![image](https://user-images.githubusercontent.com/4026090/114447944-655b4700-9bec-11eb-80d7-0bdf5f1fe49b.png)

**Comment by ssddanbrown** [comment]
I believe this has now been addressed as part of #3433.
Just checked across blink, webkit and gecko and they appear to be equal there.
