### ISSUE TITLE
Abbility to add sections/subsections

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2683]
**Describe the feature you'd like**
Actual you have Shelf->Book->Section->Page. It would be nice to add with an option in the config to add the abbilty to add more sections/subsections Shelf->Book->Section->SubSection1->Subsection2->Page

**Describe the benefits this feature would bring to BookStack users**
It is great for sorting in bookstack. We use this app as knowledgebase and we like it. But sometimes it would be nice to have one or two levels more for sorting pages in

**Comment by ssddanbrown** [comment]
Thanks for the request @pboatone but I feel my [comments from here](https://github.com/BookStackApp/BookStack/issues/95#issuecomment-206509825) are still relevant on this matter.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
