### ISSUE TITLE
Azure AD unable to sign in

### ISSUE THREAD

**Issue by stefantrav** [BookStackApp/BookStack#2685]
I followed these steps to use the Azure AD sign in.

https://www.bookstackapp.com/docs/admin/third-party-auth/#azuread-microsoft

after signing in, it returns to the Bookstack signin page with a red error message display

Misconfigured application. This could be due to one of the following: the client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, the admin has not consented in the tenant. Or, check the application identifier in the request to ensure it matches the configured client application identifier. Or, check the certificate in the request to ensure it's valid. Please contact your admin to fix the configuration or consent on behalf of the tenant. Client app ID: 2823da84-f789-4af1-b965-**********. Trace ID: 16c22f7c-223e-4e45-952c-************** Correlation ID: 9a7b8249-a080-4112-a694-*************** Timestamp: 2021-04-19 07:39:12Z

**Comment by Mynster9361** [comment]
You need to login to your azure tenant.
go under permissions and then grant admin consent for it like shown here:
![image](https://user-images.githubusercontent.com/66535357/115211018-741b8f80-a0ff-11eb-9a1d-193655b1b342.png)

**Comment by stefantrav** [comment]
that did the trick

thank you
