### ISSUE TITLE
Unknown Error - trying to change permissions to page after removing it's creator

### ISSUE THREAD

**Issue by dgomulka97** [BookStackApp/BookStack#2687]
**Describe the bug**
After removing a user and trying to change permissions for pages he created - you will end with "An Error Occurred" and you can't view this page anymore, same for books and probably shelves. It seems that changing permissions triggers this apocalypse. Migrating ownership didn't change anything

**Steps To Reproduce**
1. Create new account, e.g $[test]
2. Log in using account $[test]
3. Using $[test] account create new $[page]
4. Log in as admin and delete $[test] account
5. Change permissions for this $[page]
6. Tadam, now you can't access $[page] anymore and you see only:
"An Error Occurred
An unknown error occurred"

****Same with books. Reproduce steps above with $[book] instead of $[page] and:****
- you will be able to read pages in that book from e.g homepage
- you won't be able to open $[book]

**Expected behavior**
You should be able to migrate ownership after removing user

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.04
 - PHP Version: 7.3.27
 - Hosting Method (Nginx/Apache/Docker): Docker, using linuxserver image of bookstack and mariadb

**Comment by ssddanbrown** [comment]
Thanks for reporting @dgomulka97.

I think I managed to reproduce this.
I've just [released v21.04.2](https://github.com/BookStackApp/BookStack/releases/tag/v21.04.2) which includes [some changes](https://github.com/BookStackApp/BookStack/commit/20528a2442b7149ad8fd1f4cb470062d9ff73b31) that solve the scenario on my local instance.

Before I close this off it would be great if you could update to that new release and confirm if the page is now accessible again. Fresh Linuxserver.io container images usually follow new releases by about an hour or two.

**Comment by dgomulka97** [comment]
Working flawlessly, thank you :D
