### ISSUE TITLE
Draw.io diagram can't be edit after restoration

### ISSUE THREAD

**Issue by aomori69** [BookStackApp/BookStack#2688]
Hello , this is my first post hope it is in a good section.
I've backup and restore with the last version of Bookstack
Unfortunately, when i try to edit a draw.io diagram is executing but stop at loading and i can't edit the diagram anymore.
It opens the platform, but won't let us go the diagram.

However, when i create a new page draw.io diagram works normally and i can edit them.

![image](https://user-images.githubusercontent.com/82651042/115248473-00da4380-a128-11eb-95b6-fb4122800f1f.png)

Did i miss something ?

 BookStack Version 21.04
  PHP Version: PHP 7.2.24-0ubuntu0.18.04.6 
 Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Hi @aomori69,

In reference to the mentioned restore operation, was that a direct mysqldump import from the previous system or was it more involved? 

Additionally, I see that you've specified PHP7.2 in use whereas the latest version of BookStack requires PHP 7.3 or greater.

**Comment by aomori69** [comment]
Hi ! Thank you for your answer ! 

You were right my php version is 7.4.16 ,  7.2 was my old server ! 

about the restoration i use this tutorial : https://www.bookstackapp.com/docs/admin/backup-restore/
so mysqldump was involved but i made a copy of .env public/uploads  and storage/uploads

Thank you for any help you can give ! 

Aomori

**Comment by ssddanbrown** [comment]
Thanks for confirming @aomori69.
This can often occur if the original image/drawing file does exist where expected or if permissions are blocking access to the image.

Do you see anything added to your logs each time you attempt to edit the image? Details on viewing the logs can be found here:
https://www.bookstackapp.com/docs/admin/debugging/

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
