### ISSUE TITLE
no longer access to our bookstack instance

### ISSUE THREAD

**Issue by jhjacobs81** [BookStackApp/BookStack#2693]
it says: Return value of BookStack\Auth\User::getDefault() must be an instance of BookStack\Auth\User

even browsing to the root page throws this error. when i try to create a new user by commandline i receive the same error.

**Comment by ssddanbrown** [comment]
Hi @jhjacobs81,
I'm going to need some details to go on.

- Has there been a change that caused this to occur?
- Have you, at any point, attempting manually editing users via the database?
- What version of BookStack are you using?
- What version of PHP are you using?
- Do you get any further details when this error occurs, such as a list of files and numbers? If so, those will help.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
