### ISSUE TITLE
Error message when accessing deleted or not existing files

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#2696]
**Describe the feature you'd like**
When deleting a file the url sometimes still exists in other places e.g. pages or external websites/chats. When trying to access these deleted files the error message only tells me an error occurred. I'ld suggest putting in an error message like the one for pages:

"File not found
Sorry, The file you were looking for could not be found.

If you expected this file to exist, it might have been deleted."

Example Link: https://demo.bookstackapp.com/uploads/images/gallery/2021-04/image-1619003945781.jpg

Before
![image](https://user-images.githubusercontent.com/42382626/115546524-6e5fae80-a2a5-11eb-8a0c-f0589c32c4ea.png)
After
![image](https://user-images.githubusercontent.com/42382626/115548396-b7b0fd80-a2a7-11eb-87ec-31d286cd8de1.png)

**Describe the benefits this feature would bring to BookStack users**
Better explanation to the user for the kind of error that occured.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Bolthier, I would completely agree that the current state was not providing much guidance. Was actually hitting a strange error scenario. Have been tidying up the error handling and have implemented the suggested handling. Will be part of v21.04.4.
