### ISSUE TITLE
Be able to specify permissions on books / chapters / pages when using the API to import content

### ISSUE THREAD

**Issue by Mynster9361** [BookStackApp/BookStack#2702]
#### API Endpoint or Feature

Be able to specify permissions on books / chapters / pages when using the API to import content

#### Use-Case

When you are creating or importing content and already know which group should have access to that specific group it would be nice to set it already in the import faze instead of having to do it manually after content has been imported.

Example.
You have a book with custom permissions on.
Within that book you have pages and chapters also with custom permissions.
So lets say you would like to add a chapter into a book but the content within the chapter needs to be reviewed before it gets released to everyone

#### Additional Context

I do not believe i have any further context to this

**Comment by abouchereau2** [comment]
Hi!
That would be awesome, I'm really looking for this feature.
Today, I don't know how to assign default permissions (to a known group) when creating a shelf or a book using the API.

**Comment by ssddanbrown** [comment]
This has now been added within the work of #4099, and will be part of the next feature release so I'll therefore close this off. 

This is done over a couple of new endpoints, including a `PUT` endpoint to set role-override permissions, fall-back permissions (Inheritance control) and owner user. You'd now be able to follow up your book/chapter/page create request with a PUT to the new endpoint to set permissions for that item as desired.

Additionally, Role API endpoints were added to the last release which may help here.
