### ISSUE TITLE
Error when uploading Title Picture to Book

### ISSUE THREAD

**Issue by wojosc** [BookStackApp/BookStack#2705]
When uploading a title picture for a book you get an error for incopatible file-ending when there are dots in the file name:

![grafik](https://user-images.githubusercontent.com/22279621/115695106-c78d1800-a361-11eb-9985-43f6021f9a0d.png)

Workaround:
delete all dots from the file name

eg:
change "picture_20.04.2021.png" to "picture_20-04-2021.png"

**Comment by ssddanbrown** [comment]
Hi @wojosc,
Please can you confirm what version of BookStack you're experiencing this issue on?

**Comment by wojosc** [comment]
BookStack v0.30.5

**Comment by ssddanbrown** [comment]
Thanks for confirming @wojosc.

This validation requirement was removed within BookStack v21.04 so this should be sorted on the current latest release therefore I'll close this issue off. If you still have problems on the latest release feel free to create a new issue.

**Comment by wojosc** [comment]
Thanks!
