### ISSUE TITLE
Deleting a book does not delete corresponding table records

### ISSUE THREAD

**Issue by tstkenny** [BookStackApp/BookStack#2708]
I am developing a store procedure to save an existing book into a new book including chapters and pages and I found a related bug:

When you delete a book via UI, some of the relational table records are not deleted.   e.g. joint_permission.

If you use the UI button to copy all the permissions in a BookShelf to all Books, the deleted books will APPEAR AGAIN, which is a serious bug.

A quick but dirty fix:

delete from books where deleted_at is not null;
delete from chapters where deleted_at is not null;
delete from pages where deleted_at is not null;
delete from joint_permissions where entity_type='BookStack\\Page' AND entity_id not in (select id from pages);
delete from joint_permissions where entity_type='BookStack\\Chapter' AND entity_id not in (select id from chapters);
delete from joint_permissions where entity_type='BookStack\\Book' AND entity_id not in (select id from books);

Thank you.

**Comment by ssddanbrown** [comment]
Thanks for reporting @tstkenny,

Just to confirm, When you say "the deleted books will APPEAR AGAIN", do you mean within the user interface or do you mean within the database?

**Comment by tstkenny** [comment]
@ssddanbrown actually the record never got deleted so it stays in the database since beginning.  The book will re-appear in the UI.

**Comment by ssddanbrown** [comment]
Hi @tstkenny,
I just attempted to re-produce this by doing the following:

1. Delete a book that exists within a shelf via the UI.
2. Run the "Copy Permissions" action from the shelf's Permission page.

After doing this the book did not re-appear but remained deleted, in the recycle bin, as expected and therefore did not re-appear in the shelf within the UI. I tested the and without custom permissions set on the shelf.
Does you instance behave differently? If so please can you confirm the version?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
