### ISSUE TITLE
dark mode on iOS: html select elements not readable

### ISSUE THREAD

**Issue by geins** [BookStackApp/BookStack#2709]
**Describe the bug**
The text on select-fields on settings page are not readable (light text on light background) in dark mode on iOS-device.

**Steps To Reproduce**
1. Use latest iOS device (iPad), Browser Safari
2. Enable dark mode in bookstack, (dark-)mode setting in iOS doesn't matter 
2. Go to settings page
3. Scroll to homepage-setting (pulldown-list/select-field)
4. Text is light on light back, so not really readable

**Expected behavior**
light text on dark background or vice versa

**Screenshots**
![dark mode](https://i.imgur.com/X0Yu6Nv.jpg)

![light mode](https://i.imgur.com/tA0ZOFj.jpg)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.04.2
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
Dark mode enabled
Device: Apple iPad mini 5, iOS 14.4.2 (latest)
Browser: Safari

**Comment by ssddanbrown** [comment]
Thanks for reporting @geins.

I've [applied a patch here](https://github.com/BookStackApp/BookStack/commit/aa6a752e38b73eea201ea8e6a5b994a715e24aec) to cover this (Although I may have got upset at apple in my commit message). Tested on my iPad (Safari), In Firefox and Chrome (Linux Desktop) in both light and dark mode to ensure it all looks sensible. 

This has been released as part of v21.04.3: https://github.com/BookStackApp/BookStack/releases/tag/v21.04.3

Will therefore close this but shout if it remains an issue after updating.
