### ISSUE TITLE
Replace current search solution

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#271]
https://github.com/teamtnt/tntsearch
https://github.com/teamtnt/laravel-scout-tntsearch-driver

### Advantages

* Will remove MySQL5.6+ requirement (And thus possibly make it easier to support other DB's in the future).
* Seems to be simple and fast - *Need to investigate*
* Could help to avoid odd issues seen using MySQL fulltext searches (#269) and prevent having to resort to 'LIKE' queries - *Need to investigate*

### Issues

* Need to look how to integrate with permissions system.
* Will be an extra dependency and will introduce SQLite requirement.

**Comment by ssddanbrown** [comment]
Looks like integrating TNTsearch will be a lot of hassle when combined with the permissions system. Ideally we'd have something that lives in MySQL so we can easily join permissions as required.

Maybe a simple custom MySQL table? Upon update, break pages down into terms and score on frequency and importance (Dependant on field). Then we can use "LIKE 'abc%' matching at a term level which will still use indexes.

**Comment by muramasatheninja** [comment]
Could Sphinx be an option?
http://sphinxsearch.com/
