### ISSUE TITLE
Volumes between books and chapters ?

### ISSUE THREAD

**Issue by Grazouillis** [BookStackApp/BookStack#2712]
**Describe the feature you'd like**
It would be very nice if we could have volumes between book and chapters.

**Describe the benefits this feature would bring to BookStack users**
Indeed, if you have a shelf with a theme (ex : dev)
and a book, with a web project
It is difficult to manage the versionings of this project (project 1.0, 2.0, and so on) in a chapter

It would be nice if we could have chapters to divide different subjects or approaches about this project in the version X, and pages in the chapters which could be grouped by this subject/approach

e.g: dev (shelf) > web project XYZ (book) > versioning 1.0 (volume) > user guide (chapter 1)* / expert guide (chapter 2) >  * menu, functionality 1, functionality 2, admin dashboard, etc. (pages)

Thank you :)

**Comment by ssddanbrown** [comment]
Thanks for the request but this is something that has essentially recently been requested in  #2683 so please see that for any further dicussion for now, and my feelings on adding another level of organisation can be seen from the link I've provided in that issue. Therefore I'm going to close this off.
