### ISSUE TITLE
Third party authentication with GitLab - `GITLAB_BASE_URI` problem

### ISSUE THREAD

**Issue by george-ycc** [BookStackApp/BookStack#2717]
I follow the steps on [the official documentation](https://www.bookstackapp.com/docs/admin/third-party-auth/#gitlab), setup the environment, and got an ERR_INVALID_REDIRECT when trying to login with GitLab.
It turns out that a trailing `/` is required for `GITLAB_BASE_URI`, which the documentation did not specify & the sample in the documentation did not have a trailing `/`.

Note 1: My gitlab base uri is something like `https://my-domain.com:30000`, maybe that port caused the bug?
Note 2: BookStack `v0.31.6`

**Comment by ssddanbrown** [comment]
Thanks for raising @george-ycc. Can confirm, was not specific to a custom port.

I've now updated the documentation with an updated example, that includes the trailing slash, and some supporting text to specify the slash is required.
