### ISSUE TITLE
Move books to other shelves

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2718]
**Describe the feature you'd like**
the possibility to move whole books in other shelves not only pages or sections

**Describe the benefits this feature would bring to BookStack users**
to add a shelv archiv for old entries

**Comment by ssddanbrown** [comment]
Hi @pboatone,
You can already store books within multiple shelves and move them around. Maybe I don't understand your request. Could you provide any further detail here?

**Comment by GhostNA** [comment]
Hi @ssddanbrown 
How it's possible? How create book within multiple shelves?

**Comment by GhostNA** [comment]
Yeap, @ssddanbrown thx, I found it just now)

@pboatone you can hit "Edit" on shelve page, and moving books through shelves

**Comment by pboatone** [comment]
Thank you @GhostNA @ssddanbrown found it
