### ISSUE TITLE
Button for "Next Page"

### ISSUE THREAD

**Issue by tillhoff** [BookStackApp/BookStack#2720]
### Describe the feature you'd like
A clear description of the feature you'd like implemented in BookStack.
As of now, when a page was read, it is necessary to scroll back to the top and click on the next page on the left-hand navigation. To make this more intuitive and more booklike, IMO there should be a button to get to the next page automatically - without the need to ask yourself where you are again.
The same actually applies for a "previous page" button, but "next page" is more important ;)
A button with a simple arrow would suffice I guess.

### Describe the benefits this feature would bring to BookStack users
Bookstack wants to be a simple virtual library - or so I have understood. When reading a book, I don't go back to the list of contents after each page/chapter to see where I should go next, but just flip the page. This feature should be somewhat simple to implement (at least from my newbie perspective) and would bring a more or less basic feature for an awesome software with the word "book" in its name :)

**Comment by ssddanbrown** [comment]
Thanks for the request @tillhoff but this is already open under #1381 so I'll close this off as a duplicate.

**Comment by tillhoff** [comment]
Thank you for the fast feedback! Somehow I missed that on my search... 👍🏻
