### ISSUE TITLE
Feature: Approval of edits

### ISSUE THREAD

**Issue by MaximilianKindshofer** [BookStackApp/BookStack#2725]
**Describe the feature you'd like**
I would like a feature for the approval of edits by the owner of a page

**Describe the benefits this feature would bring to BookStack users**
A viewer could purpose changes to a page or chapter e.g. spelling or even adding a new section an collaborate on a book with the author / owner

**Comment by ssddanbrown** [comment]
Thanks for the request @MaximilianKindshofer. I'm going to close this off since I see a lot of logical overlap with #473.
