### ISSUE TITLE
Commit f24336f: dark mode not fully respected on iOS

### ISSUE THREAD

**Issue by geins** [BookStackApp/BookStack#2728]
**Describe the bug**
Even after the commit the buttons are off color in dark mode on mobile iOS

**Steps To Reproduce**
open Bookstack on iOS mobile, activate dark mode.

**Expected behavior**
no white borders

**Screenshots**
before:
![iOS before](https://i.imgur.com/fna2s97.png)
after (see: **Additional context**) 
![iOS after](https://i.imgur.com/i08EfgF.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.04.3
 - PHP Version: 8.0
 - Hosting Method (Nginx/Apache/Docker): Apache
 - iOS iPad mini 5 and iPhone 11 Pro, iOS 14.4.2, Safari mobile, cleared cache

**Additional context**
my solution in header:
```
<style>
html.dark-mode .tri-layout-mobile-tabs {
  background-color: #222;
  border-bottom: 1px solid #222;
}
</style>
```

**Comment by ssddanbrown** [comment]
Thanks @geins for reporting, Fixed in https://github.com/BookStackApp/BookStack/commit/a3d36237e22338282053e3c9350eb1d1a72028c5 to be part of the next patch release.
