### ISSUE TITLE
display of entries in Chrome/Edge(based on Chromium) are not right 

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2732]
Hi,

today I opend bookstack on a other computer with the browser Chrome and Edge on it. There I opened an entry and it looks bad:
![2021-05-05 11_23_55-](https://user-images.githubusercontent.com/67209365/117121710-45efae00-ad95-11eb-9166-a4f35b619c80.png)

After I saw this, I opened the same entry on opera and all was okay:
![2021-05-05 11_31_24-Veeam Backup Plan _ Knowledgebase - Vivaldi](https://user-images.githubusercontent.com/67209365/117121932-92d38480-ad95-11eb-8c54-ea7e53d7ce1f.png)

**Comment by dopyrory3** [comment]
Can it be reproduced on the demo site? 
Can you try clicking the source code button while in editor mode and look at the table width property is? Table cols shouldn't overflow at the default 100%.

![image](https://user-images.githubusercontent.com/12117229/117128218-045f0300-ad95-11eb-9174-b5894d812786.png)

**Comment by pboatone** [comment]
i don't have a surce code button I am using Markdown

**Comment by ssddanbrown** [comment]
The behaviour should now be aligned thanks to @dopyrory3. Will be part of v21.04.5.
