### ISSUE TITLE
Exporting pdf causes a "Trying to get property 'name' of non-object"

### ISSUE THREAD

**Issue by martijndegouw** [BookStackApp/BookStack#2733]
**Describe the bug**
Exporting a PDF fails with the following error (when debug is enabled):
Trying to get property 'name' of non-object (View: /srv/www/bookstack/v21.04/resources/views/partials/entity-export-meta.blade.php) 

**Steps To Reproduce**
I've got the feeling this is caused by the original creator of the page being removed from bookstack, since the revision page of the page shows a lot of 'Deleted User', including the Initial publish.

**Expected behavior**
I expect that the pdf export still works

**Screenshots**
![image](https://user-images.githubusercontent.com/3339604/117161485-3aff4280-adc2-11eb-8d54-f948c9a1dabd.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v21.04
 - PHP Version: PHP 7.3.27-1~deb10u1
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
I removed line 8 from entity-export-meta.blade.php and the export works as expected.

**Comment by ssddanbrown** [comment]
Thanks for reporting @martijndegouw with the clear provided details. I've patched this up in a083ceaf44b87cf6a4062d6ed8f01eb75b6a5f43 with some testing to cover, This will be included in the next patch release.

**Comment by martijndegouw** [comment]
I tried your patch on our instance and can confirm the export to pdf works as expected now :+1:
