### ISSUE TITLE
Applying other filters for search remove existing created_by, updated_by condition

### ISSUE THREAD

**Issue by iTymz** [BookStackApp/BookStack#2736]
Hi!

I'm trying to find an option to get the full list of activities for a user but there is no option for this right now (without accessing to audit log). There is an option to find user-created or updated stuff so I tried to use it with other filters possible to apply in the search section.
The final result is removing the `{created_by:XY}` or `{updated_by:XY}` from the URL and show the results based only on "visible" filters available in the left section. This should apply the filters with existing ones.

Example:
https://demo.bookstackapp.com/search?term=%7Bcreated_by%3A1%7D+%7Btype%3Apage%7D

Then apply the date filtering:

https://demo.bookstackapp.com/search?search=&types%5B%5D=page&exact%5B%5D=&tags%5B%5D=&filters%5Bupdated_after%5D=&filters%5Bupdated_before%5D=&filters%5Bcreated_after%5D=2021-05-07&filters%5Bcreated_before%5D=

Results:
URL without `created_by` condition.

**Comment by ssddanbrown** [comment]
Thanks for reporting @iTymz.

Has been fixed within 2e49b1617743ee844b5eb63d0e8fd6bca6343d12 to be part of the next feature release.
