### ISSUE TITLE
Saving markdown page without editing content throws error

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2741]
Hi, 

at the moment if you have a new site in bookstack (markdown) and it is empty like that:
![2021-05-11 14_35_52-Window](https://user-images.githubusercontent.com/67209365/117816445-cc5d3180-b266-11eb-9f96-d27821d66c29.png)
And users try to safe it there comes an error message:
![2021-05-11 14_44_51-Window](https://user-images.githubusercontent.com/67209365/117817518-f7945080-b267-11eb-803d-487b56d23eff.png)

I think it would be nice to have an error message like that:
![2021-05-11 14_42_26-Window](https://user-images.githubusercontent.com/67209365/117817651-185ca600-b268-11eb-8e13-90a0b5b3a2c3.png)

The reason is, that this is easier to support. I had often the problem that users say "OMG I got this error, broke I bookstack ?"

**Comment by ssddanbrown** [comment]
Thanks for raising @pboatone. This is a bug, we should just allow the page to be saved in an empty state as per the WYSIWYG editor. Assigned to the next patch release.
