### ISSUE TITLE
Intervention error: Unable to init from given binary data. 

### ISSUE THREAD

**Issue by TheMightyOnyx** [BookStackApp/BookStack#2743]
https://flareapp.io/share/67O6nykP

**Describe the bug**
Error while changing book cover image.

**Steps To Reproduce**
Change book cover image.

**Configuration:**
 - Exact BookStack Version: v21.04.4
 - PHP Version: PHP 7.4.19 (php:7.4.19-fpm-alpine3.13)
 - Hosting Method: Docker

**Additional context**
Uploading images to pages doesn't work either, the image itself is uploaded and copied to the storage directory correctly, but no thumbs or scaled directories are created. I checked the permissions and everything and it seems fine, I even chmoded the dir to 777 and it still doesn't work. Considering the image is copied but no thumbs are created I imagine the error happens at some point during the thumbnail creation. I imagine there's some php module missing or something misconfigured, but I followed the list of requirements on docs/installation page and it seems all fine. I checked if all modules are enabled and it seems to be the case.

I enabled debugging and linked the stack trace above.

**Comment by ssddanbrown** [comment]
Hi @TheMightyOnyx,
Are you using a common docker image at all? Or are you able to share the scripts/Dockerfile to build your docker image at all? This kind of error can some down to the exact version/build of the GD php extension.

**Comment by TheMightyOnyx** [comment]
This is the php part that installs the modules and composer etc. It's based on `FROM php:7.4.19-fpm-alpine3.13`. If this is not enough and you need to test it yourself I can grant you access to the repository, it's on Gitlab though, so I would need your Gitlab username.
```
....
ARG PROJECT_VERSION=21.04.4
ARG PROJECT=https://github.com/bookstackapp/bookstack/archive/v${PROJECT_VERSION}.tar.gz
....
RUN \
# install dependencies
apk add --no-cache gettext libpng-dev oniguruma-dev libxml2-dev wget && \
# create project directory and download the project files, su into user otherwise umask is ignored
mkdir -p /usr/share/project && \
chown ariamis:ariamis /usr/share/project && \
wget -qO- "${PROJECT}" | su ariamis -s /bin/sh -c "tar -xzf - -C /usr/share/project --strip-components=1" && \
# install php extensions
docker-php-ext-install pdo_mysql mbstring tokenizer gd simplexml dom && \
# remove uneccesary data
apk del libpng-dev oniguruma-dev libxml2-dev wget && \
apk add --no-cache libpng oniguruma libxml2 && \
# copy php configuration
mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini && \
# install composer
cd /tmp && \
curl -sS https://getcomposer.org/installer | php && \
mv /tmp/composer.phar /usr/local/bin/composer && \
# install composer dependencies
s6-setuidgid ariamis composer install -d /usr/share/project/ --no-dev && \
# remove uneccesary data
rm -rf /root/.composer /tmp/*
```

Thanks for looking into this.

**Comment by ssddanbrown** [comment]
Hi @TheMightyOnyx,
I suspect you either need to configure gd with jpeg support and/or you need to not remove the libraries required by gd (So try not deleting the various `*-dev` packages required used by PHP extensions).

I tested things with the below basic Dockerfile and exporting a page containing a PNG and JPG image seemed to work.

```dockerfile
FROM php:7.4.19-fpm-alpine3.13

RUN apk add libpng-dev libjpeg-turbo-dev zlib-dev oniguruma-dev libxml2-dev
RUN docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install -j$(nproc) pdo_mysql gd
```

**Comment by TheMightyOnyx** [comment]
Thanks a lot, looks like installing gd with jpeg support fixed it. I'm installing dev versions of those packages, removing them and then installing non dev versions to save some space. Probably not worth the hassle, but it doesn't appear to be causing any issues.

I went ahead and made a pull request https://github.com/BookStackApp/website/pull/96 that adds "(with jpeg)" to gd, just in case anyone else runs into this.

Thank you for your help.

**Comment by ssddanbrown** [comment]
@TheMightyOnyx Happy to hear you got things working. Will therefore close this off.

**Comment by Scemist** [comment]
I'm also with this issue, I'm surprise there is no more issues related opened, I tried in many environments, although always in Docker with Ubuntu.

## The error throws every time I try to upload a JPG/JPEG file, PNG works fine.

```
Intervention\Image\Exception\NotReadableException

Unable to init from given binary data.
```

As example to reproduce it, you can just use the dev Dockerfile and try to upload a jpg file;

https://github.com/BookStackApp/BookStack/blob/development/dev/docker/Dockerfile

Is there some dependence missing in this Dockerfile?

**Comment by ssddanbrown** [comment]
> Is there some dependence missing in this Dockerfile?

There could possibly be, I have not tested the dev docker environment in a while.
Either way, the dev docker setup in this repo is not for production at all, please don't use this for an actual BookStack instance unless you are intending to only develop.

**Comment by Scemist** [comment]
Sure, actually we are developing a custom Docker setup over this official repo, just like the other community versions. We used this file to find out any missing dependencies.

I already fix it, really just missing dependencies, I sent a Pull Request #4422 , cause is just a few lines of code, but not easy to find out the solution.
