### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by Haboubi92** [BookStackApp/BookStack#2745]
to make Bookstack usable for scientific writing, a footnote is an important feature.
I tried out copying text with footnotes from Microsoft word and pasted it in bookstack. to my surprise the footnotes were put in very good and usable manner in bookstack.

but making footnotes directly in Bookstack is still hard to make
you would have to insert a link as "#_ftn1" then duplicate it
![footnote](https://user-images.githubusercontent.com/48198054/118324224-6bee1e80-b50a-11eb-84e9-bc5ebe13efa4.JPG)

It would be great if there is a dedicated button in wysiwyg editor to automate this process

**Comment by ssddanbrown** [comment]
Thanks for the request @Haboubi92, Closing this in favour of #2745 which requests a similar result.
