### ISSUE TITLE
fopen() Exception when exporting to pdf document

### ISSUE THREAD

**Issue by rednaxLamington** [BookStackApp/BookStack#2746]
**Describe the bug**
After upgrading V21.04.4 I can't export to PDF:

**Steps To Reproduce**
1. Go to a page or chapter
2. Click on export, than on PDF file

![image](https://user-images.githubusercontent.com/13933387/118351717-c4024080-b55d-11eb-94fd-c80058812ba5.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): V21.04.4
 - PHP Version: 7.4.16
 - Hosting Method (Nginx/Apache/Docker): Windows 10 / IIS

**Additional context**
The referenced directory does not exists. I believe `c:\BookStack\app\vendor\....` should be `c:\BookStack\vendor\....` (without \app). 
Just for testing, after manually creating the directory, the export does work.

**Comment by ssddanbrown** [comment]
Thanks for reporting @rednaxLamington. I've just released v21.04.5 with an included patch to use an existing path instead of the incorrectly shown one in your bug report. I was not able to replicate your original error but hopefully you'll no longer get this occurrence.

**Comment by rednaxLamington** [comment]
Thanks Dan,

I can confirm that the problem is solved.

**Comment by ssddanbrown** [comment]
@rednaxLamington Awesome, Thanks for confirming!
