### ISSUE TITLE
Activity Log - Add IP Address

### ISSUE THREAD

**Issue by Cave-Johnson** [BookStackApp/BookStack#2747]
**Describe the feature you'd like**
Would we be able to get the IP address used associated with user activity in the activity dashboard, potentially as an extra column next to date?

**Describe the benefits this feature would bring to BookStack users**
This would make it easier to track down malicious activity on a bookstack instance and make post breach incident response an easier process. 

**Additional context**
It would also allow admins an easier way to recognise any unknown logins. Useful as 2FA is not an option and password reuse, and attackers using password spraying is quite a common theme these days!

**Comment by johnroyer** [comment]
@ssddanbrown : I notice the data type of `detail` in `activities` is `text`.  
Do you think saving user IP in `detail` is reliable ?

**Comment by ssddanbrown** [comment]
@johnroyer I'd prefer a new column to keep the data organised.

If you're thinking about taking this one on, A couple of notes:

- We'll need to ensure that this keeps working behind a proxy where where standard proxy headers are used. (Laravel might already do this when fetching the request IP).
- We'll need to not store IP addresses when in demo mode.

**Comment by johnroyer** [comment]
There is a  discussion about getting real IP : [How to access client ip address in Laravel 5](https://www.edureka.co/community/92985). We may need to check headers in `$_SERVER` to fingure out the real IP. 

I create a [test page](https://zeroplex.tw) with [the code](https://gist.github.com/johnroyer/a6a93e82ab42e3e55d0e4bc2f4728f5a). This demo is using Nginx as reverse proxy, php-fpm as runtime environment. Hope it works.


No idea about adding IP into a new column for now. I think I need some more time to read the source code.

**Comment by Cave-Johnson** [comment]
As a thought, for the use of reverse proxies it would be worth checking for the presence of the X-Forwarded-For header as this should include the real external IP address rather than IP address of the proxy.  This may be present in Larvel but its not something I am familiar with

**Comment by johnroyer** [comment]
@ssddanbrown May I take this issue, even I do not familiar with Laravel ?

**Comment by ssddanbrown** [comment]
Thanks to @johnroyer this will be part of the next patch release. PR details in  #2936.

Thanks @Cave-Johnson for the original suggestion. Will therefore close this off.
