### ISSUE TITLE
'Manage Users' permission allows users to assign themselves to 'Admin' group

### ISSUE THREAD

**Issue by jackhadrill** [BookStackApp/BookStack#2751]
**Describe the bug**
The 'Manage Users' permission allows users to assign themselves to the 'Admin' group. 

**Steps To Reproduce**
1. Assign a user to a group with the 'Manage User' permission.
2. Login as that user.
3. Click on the 'edit profile' button.
4. Modify the group to whatever you want (including admin).

**Expected behavior**
I would expect 'Manage Users' to be able to only assign the roles that the user themselves is in.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.04.4 
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Hi @jackhadrill, 
We explicitly show a notice in the role configuration view to advise of this scenario.

![Screenshot from 2021-05-17 20-43-11](https://user-images.githubusercontent.com/8343178/118546977-9fba8580-b750-11eb-85ca-6302e31af369.png)

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
