### ISSUE TITLE
Change callouts and icons to match ANSI Z535.6

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#2752]
**Describe the feature you'd like**
The facility to change the callouts and icons to match those used in ANSI Z535.6

**Describe the benefits this feature would bring to BookStack users**
Compliance with the requirements of the standard, and enhancement of the callout appearance.

**Additional context**
Current callouts:

![callouts](https://user-images.githubusercontent.com/57015243/118486526-a37ae780-b711-11eb-9aec-84c13eef27fe.png)

ANSI:

![ansi](https://user-images.githubusercontent.com/57015243/118486564-aa095f00-b711-11eb-9732-9e1270c351e5.png)

**Comment by ssddanbrown** [comment]
Thanks for the request @techauthoruk.

To be honest I'm fairly wary about changing page content styles as for me that's changing people's documentation. I don't think the described benefits are worth any change here, since I'm not sure what compliance with the standards achieves or how callout appearance is enhanced. 

The standard desired here is really intended for safety materials, which I think in reality will be a more minor use of how BookStack is used, and callouts will often be used more generally in which case a more integrated, subtle design would be preferred. 

If you wanted to achieve these kind of styles on your own instance, you could get closer by pasting the below in your "Custom HTML Head Content" setting.

```html
<style>
	.callout.info {
		background-color: #226dac;
		border-color: #226dac;
		font-style: italic;
	}
	.callout.success {
		background-color: #17a24c;
		border-color: #17a24c;
	}
	.callout.success, .callout.info {
		color: #FFF;
		font-weight: bold;
		padding-left: 12px;
	}
	.callout.success:before,
	.callout.info:before {
		content: none;
	}
	.callout.warning {
		background-color: #f7aa28;
		border-color: #f7aa28;
		color: #000;
		font-weight: bold;
	}
	.callout.danger {
		background-color: #dd292f;
		border-color: #dd292f;
		color: #FFF;
		font-weight: bold;
	}
	.callout.warning:before,
	.callout.danger:before {
		background-size: contain;
		background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABuCAMAAADbNSdmAAAAk1BMVEUAAAD/1CoAAAB7ZhTzyyj4zinpwibkviXuxifSriKReBdpVxE1LAgRDgP60CkfGQUYFATFpCB0YBO/nx+ihxqAaxUJBwHfuSTbtiTYsyPJpyGagBk+NArNqiG2lx6ylB2ukRxvXBKrjhynixuGbxZcTA5VRg5PQg1FOQssJAclHwYNCwKLdBdKPQy6mx5kUxBhURBbbDe7AAAAAXRSTlMAQObYZgAABARJREFUaN682NlS6kAURmF/zITBJAxiQARRcEI95/2fzqIoWbWNeGEP65Yqvmqqeyf02d/r7TuLGGxMGjeujBtZxo0vA9frQUQYd5spfYsnA/clFS+xZNxz7buLDl/m2pe8x5FZ8I0ODaPAuINCh6oyhgy81Ff9CDDuY6pjV+Fl4FtRfhkD5ijRTeglc5SuDVwEn5wcJdsqKIz7UsiWPoWUgVei8FME9ylVpzKcDDxXt1kwGHckok0gGXjXiihvwsAs+EI/N2HJQdzXTBR+igDf6VRL4ADueyIKP0WAhzrdHNi7u9ZvrZE9w9OZfms2BQ54lPLVaDEoJ62I13u/bp0JdrPrHRpB500Y+B53XPeONcsgUwT3OcGd9oi9roQp4hEey34/LRL/UwS3rMyrtOn6OEUekX3Bs87Tl3LvUwR3I8q/wxmfjfzJnaOkYmfdJuGzliniZcEPEqW1hV8VYIqwb0Xfd7VEWe0THsv038KlJHpgyc7uv0qmc9DuX6lkgex+z2K7sPCbTB/AHo8SvyZNZEq3yE5wk4u466F72W6dYRZkG1p4KTJTxOdRYkk0FzFFnOEPdWot3BeZ3efkblN1yizciswU8XmUGNaUiRynCO6V1K0yw3oK7GWKcGXZbXHi4URjYPd7FipPPJyoYoo4XFkSt3n0/Fms2e0kDARh1IG2IqUF4aImhGBrwq8JvP/TGRPCwazOdDvJeq4Nn9Wdb+sZBYKR8ypLraxbgfAm8Y8SUNacv5DmTLBDWQZKDab6j8WjLPWy/pDfKU4EO5Ql8GZtWIKOR/aNEjTEUuYB2YFk1yhBoVxOYYu4lSVMKuVygvpKcoz9VziNoBHrLLiVJRyCy8nbIihLlZbc80T+pqkig8+NgF7W81wUWFh4lCWsCT6KAmvPCPuv0RG8EwXWni5lCSvljoCItSf2X6dY3INX/b5Hr7LELN245qJTX0gerCyhnt4X9jCsRVCWb9KHzfg4v24zAWP23KMEtdiw9oyz/36YelNZ+rFbxLb/fmgRxyhB/jotd+P3535fTIvoytJmc/uoap2LCWvPgfYftojjMhMF+58nEDg92JBLWQ9sEZSlTb5XVYS69rSVpbVigtbRIth/k1CwVRMB61pRlKXNMhDlJqw9FWVpUo40+2L8pWd5Fvu6gbgjaStLfWULe4GoFkFZgv3iA53E/YosZWmf0KhZYH2jKEuLfEnunJaNahGUZQzZ5/15ybVh7YlnqSWOl/H3h+y6TCCmRRilaLLnppA4aBGUZRJYe6IsU8DakzfaNHCz3R64kGTks4fgUhKyJBjvkILLQ/Asl2QU1UPwaJpJIopy9ONYn5bjJLQL5vhfoDLT8pQ6mNy00eSmjib2CwSCTC9nllI4AAAAAElFTkSuQmCC');
	}
</style>
```

**Comment by techauthoruk** [comment]
Thank you @ssddanbrown 

That works for me! Thank you for taking the time to put this together - it will be a great help in my work.

Regards

Mark
