### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2756]
Hi,

it would be nice to have the possibility to set an archive-flag for books/chapters/pages and make the archive only visible for a special group.

So you can sort out old books/chapters/pages and people without an archiv-group cant see them and with the group can see them in a other color.

Positiv: You can see only the current right books (MyTime2021), but if you want you can see older books like (MyTime2018) too

**Comment by ssddanbrown** [comment]
Hi @pboatone,

Thanks for the request. In my view this would have a lot of overlapping functionality with existing systems while being something that can be achieved using existing options (Permission System, Recycle Bin, "Archive" book or chapter), I'm not sure it'd be worth maintaining the additional UI, permissions and logic that would be required. 

This kind of thing will introduce ambiguity while potentially enticing weaker system cleanliness.

**Comment by ssddanbrown** [comment]
Will therefore close this off.
