### ISSUE TITLE
Adding SAML support

### ISSUE THREAD

**Issue by Xen3r0** [BookStackApp/BookStack#276]
### For Feature Requests

Desired Feature:
Adding SAML support for authentication method with `LightSAML` or another component.

Link:
https://www.lightsaml.com/

**Comment by ssddanbrown** [comment]
Hi @Xen3r0, I'd like to add SAML support but I'm not very familiar with the standard and maintaining another Auth method can be a lot of work.

I'd need to learn SAML and explore how it works. I'll leave this open and we'll see if it get's requested further otherwise I'll have to wait until I've got a large block of time to learn SAML and SSO standards.

**Comment by Ethanb00** [comment]
I'm curious what types of SAML provider folks are using. My org is using Okta. The implementation of an Okta integration is quite well documented and doesn't seem too intense:

http://developer.okta.com/standards/SAML/

**Comment by s0n-** [comment]
I would be very interested in Okta integration as well since Bookstack is shaping up to be our corporate Wiki.

**Comment by jacksonp2008** [comment]
Based on your other auth methods here @ssddanbrown , I don't think OKTA integration would be very difficult for you.  

We are very interested in seeing OKTA support, happy to test or help any way we can.

**Comment by poVoq** [comment]
https://github.com/onelogin/php-saml
This seems to be the new go-to lib for open php source projects wishing to implement saml author.

**Comment by therealscottcarlow** [comment]
Bump. My org is very big on SAML SSO and adding this feature to Bookstack would be a phenomenal addition. I would offer to help put it together, but I'm not a PHP developer. I do, however, know quite a bit about SAML if you get around to putting this together and want to bounce questions off of someone.

**Comment by cb3inco** [comment]
+1 for this. Or a way to use headers to inject the users auth details as we are using a service to do this and that way the server can live behind a authentication mechanism.

**Comment by t-aus-m** [comment]
+1, I would also appreciate SSO and SAML a lot, we're using Keycloak currently.

**Comment by ataraxus** [comment]
Also looking for a way to use Keycloak with BookStack saml or openid connect would be very appreciated

**Comment by koenhendriks** [comment]
Same here, Our organisation is using Okta and this application as internal Knowledge base. We would love to have SAML authentication for this.

**Comment by boblmartens** [comment]
We would love CAS support as well.

**Comment by vsegdacocacola** [comment]
+1 for SAML

**Comment by reavessm** [comment]
+1 for Keycloak

**Comment by KroonIT** [comment]
+1 for SAML functionality

**Comment by erosinger** [comment]
+1 for SAML

**Comment by Xiphoseer** [comment]
I wrote a PR adding SAML support in #1576. It works mostly like a new SAML socialite plugin and uses laravel-saml2, but also mirrors the LDAP support for groups.

**Comment by amelie-excent** [comment]
+1 for SAML

**Comment by ssddanbrown** [comment]
As per #1576 and #1787, Initial SAML2 support has been merged into master and will be in the next feature release, v0.28, which is targeted for about mid/late December. Therefore I will now close this request.

**Comment by bendem** [comment]
I see support was added, but the documentation mentioned here doesn't seem to be available. Is there any other place I can find it?
https://github.com/BookStackApp/BookStack/blob/c055310507ba27154eaf71d70c7bc3082fb5fd1d/.env.example.complete#L222

**Comment by ssddanbrown** [comment]
Hi @bendem,
This has not yet made a release. The current release is taking a little while longer than expected. That documentation URL will exist after the next release is deployed.
