### ISSUE TITLE
Reverse Proxy NGINX -> Apache Webserver Bookstack

### ISSUE THREAD

**Issue by m4ntic0r** [BookStackApp/BookStack#277]
My situation:
I host several sites at home e.g. tinyrss, nextcloud, wordpress, lychee, chevereto. Each service is a VM (Debian, Apache2, PHP5) + central MSQL 5.7x Server for all webservices.

My Frontend Proxy to reach all my webservers over my single my-domain.com is a NGINX VM.

Now i am trying to reach my bookstack installation from remote over my proxy, but that is not possible :(

Bookstack is running perfect over https://192.168.2.14
Root is /var/www/html/bockstack/public, Apache2 Server with mod_rewrite and .htaccess file.

Part of my Nginx Config:

 location /tinyrss/ {
    proxy_pass https://192.168.2.61/tinyrss/;
    include /etc/nginx/snippets/proxy.conf;
  }

  location /nextcloud/ {
    proxy_pass https://192.168.2.9/nextcloud/;
    include /etc/nginx/snippets/proxy.conf;
  }

  location /lychee/ {
    proxy_pass https://192.168.2.8/;
    include /etc/nginx/snippets/proxy.conf;
  }

  location /blog/ {
    proxy_pass https://192.168.2.12/blog/;
    include /etc/nginx/snippets/proxy.conf;
  }

  location /chevereto/ {
    proxy_pass https://192.168.2.16/chevereto/;
    include /etc/nginx/snippets/proxy.conf;
  }

  location /bookstack/ {
    proxy_pass https://192.168.2.14/;
    include /etc/nginx/snippets/proxy.conf;
  }

All sites are running, but bookstack does not :(
If i go to https://my-domain.com/bookstack i am redirected to https://my-domain/login, what does not exist. I tried a lot, but for me it is not possible to reach my bookstack via my nginx proxy :(
I think i have to add some rewrite´s in nginx config, but i dont know much about this..

Can anybody help me?

**Comment by ssddanbrown** [comment]
Hi @m4ntic0r, Sorry to hear you are having issues.
Have you set the `APP_URL` parameter in the `.env` file? This should be the root url you want bookstack on (`https://example.com/docs/` for example) and it should have no `#` in front of it.

**Comment by m4ntic0r** [comment]
wow yes this was it! really fast help.
this variable was not set, i changed it to https://my-domain.com/bookstack and now my reverse proxy works how it should :)

thank you!

**Comment by ssddanbrown** [comment]
@m4ntic0r 🎆 Glad to hear that sorted it! I'll close this issue now that's sorted.

**Comment by CodyWarmbo** [comment]
How do I change the .env? I used the Ubuntu install script.

**Comment by ssddanbrown** [comment]
@CodyWarmbo The `.env` file can be found at `/var/www/bookstack/.env` after using the install script.

**Comment by CodyWarmbo** [comment]
Thank you. Changing the APP_URL solved my issue of no css loading after using the install script behind a Caddy reverse proxy.
