### ISSUE TITLE
Custom translations with Theme System not work

### ISSUE THREAD

**Issue by daoxiaoyue2012** [BookStackApp/BookStack#2770]
Following the relevant instructions in the document [(Hacking BookStack),](https://www.bookstackapp.com/docs/admin/hacking-bookstack/) I changed some text content, for example: 'search' changed to 'find', but it did not take effect. The 'search' word is still displayed on the page. The'APP_THEME' option has also been added to the environment file. Can anyone help me see what the problem is? thank you very much.

**Comment by ssddanbrown** [comment]
Hi @daoxiaoyue2012,
Can you provide details of how you've used the theme system? The files you've created and the content within them, and the `APP_THEME` value you've set?

**Comment by daoxiaoyue2012** [comment]
Thank so much for your reply.  The following is the corresponding section in the .env file.

![image](https://user-images.githubusercontent.com/12840932/119684141-d4c48780-be76-11eb-91ab-8ecdea69b30b.png)


I  created the corresponding folders in the themes folder, and the details are as follows.

![image](https://user-images.githubusercontent.com/12840932/119681733-e9078500-be74-11eb-805d-ad7da658ccfc.png)

In the common.php file, I changed 'Search' to 'Find', and the following is the content of the file.

![image](https://user-images.githubusercontent.com/12840932/119682078-2c61f380-be75-11eb-8981-708be2bbe1d8.png)

After completing the above process and reloading the page, The 'search' word is still displayed in the search box.

![image](https://user-images.githubusercontent.com/12840932/119683884-a181f880-be76-11eb-9485-f0be0a608e19.png)

**Comment by ssddanbrown** [comment]
@daoxiaoyue2012 Odd, Seems to work for me using the same setup.
Do you happen to have a `bootstrap/cache/config.php` file within your BookStack directory?

**Comment by daoxiaoyue2012** [comment]
There is no config.php file in the directory, and only two files: packages.php and services.php.

**Comment by ssddanbrown** [comment]
@daoxiaoyue2012 Thanks for confirming. Can you provide any details regarding how you're running BookStack? Are you using something like docker?

**Comment by daoxiaoyue2012** [comment]
Docker is not used here. CentOS(v7.9) is running on my server, and nginx(v1.14) with php-fpm is used. During the installation, I referred to related guide([Installation](https://www.bookstackapp.com/docs/admin/installation/)). 

 My site's address is [pets.friendmorning.com](http://pets.friendmorning.com).

**Comment by ssddanbrown** [comment]
Okay, That's odd, All looks fine. 

Can I confirm the location of the`themes` folder? Is it within your BookStack folder? If you run `ls -a` within the folder do you see a `.gitignore` file?

**Comment by daoxiaoyue2012** [comment]
I am so sorry for the delay in my reply, and my English is not good.

![image](https://user-images.githubusercontent.com/12840932/119697474-cb411c80-be82-11eb-8f90-b7f1e1201ce8.png)

**Comment by ssddanbrown** [comment]
@daoxiaoyue2012 From that same directory, could you run `ls -al themes/` and provide the output?

**Comment by daoxiaoyue2012** [comment]
![image](https://user-images.githubusercontent.com/12840932/119698040-6c2fd780-be83-11eb-944c-1f8d94e2a3d9.png)

**Comment by ssddanbrown** [comment]
That looks okay, Now, To be sure of the file itself, the same again but `ls -al themes/custom/lang/en`

**Comment by daoxiaoyue2012** [comment]
![image](https://user-images.githubusercontent.com/12840932/119699891-35f35780-be85-11eb-9b66-dad6d1511416.png)

**Comment by ssddanbrown** [comment]
Permissions and paths all look okay. I'm not really sure what further to suggest to be honest. Have you made any other customizations or alterations to core app files? Or have you set any other options or changes relating to languages?

**Comment by daoxiaoyue2012** [comment]
@ssddanbrown  I have not modified the core file. Initially I tried to modify the common.php file under resource/lang/en folder to complete it, but it didn't work. Later, I found that this was mentioned in the document, and it can be done by hacking. So I tried this method.

**Comment by daoxiaoyue2012** [comment]
@ssddanbrown  Sorry, I found the problem. It was my mistake. There are two directories, which correspond to different domain names: friendmorning.com and pets.friendmorning.com. I did not operate in the corresponding directories.

**Comment by daoxiaoyue2012** [comment]
@ssddanbrown  I'm so sorry for taking you so much time.  Thank you so much for spending so much time helping me find the problem.

**Comment by ssddanbrown** [comment]
@daoxiaoyue2012 Ah, That'll do it. No worries, Happy to hear you found the solution!
