### ISSUE TITLE
24-hour / 12-hour clock time (am/pm) in export to PDF/HTML

### ISSUE THREAD

**Issue by R0GGER** [BookStackApp/BookStack#2771]
**Describe the bug**
In article revisions the 24-hour clock format is used, in exports to PDF/HTML 12-hour (am/pm). 
How do I fix this issue?

**Steps To Reproduce**
1. Go to an article
2. Click on Export to PDF
3. Scroll down to bottom of the document.
4. You'll see 12-hour clock time (am/pm) instead of 24-hour.

Screenshot bottom PDF:

![chrome_9iTJyy5qyA](https://user-images.githubusercontent.com/8298741/119818370-666fdb80-beef-11eb-8790-023e322d1acb.png)

Now go back to the article and click "Revisions", you'll see it's using 24-hour clock time.

Screenshot Revisions: 
![chrome_Fz6es6Z9La](https://user-images.githubusercontent.com/8298741/119818469-899a8b00-beef-11eb-94f8-582656cab3a2.png)

**Expected behavior**
Consistency, everywhere 24-hour clock time.

**Version:** BookStack v0.31.8

**Edit** 
Updated to BookStack v21.04.6, issue still exists.

**Comment by ssddanbrown** [comment]
Thanks for raising @R0GGER. The formats used in the export have now been updated to align with the revision format.
This will be part of the next feature release.
