### ISSUE TITLE
Multiple requests

### ISSUE THREAD

**Issue by athornfam2** [BookStackApp/BookStack#2775]
**Describe the feature you'd like**

* Share function (preferably e-mail)
* Ability to submit for article corrections
* Did this article help you section
* Add GIF's

**Describe the benefits this feature would bring to BookStack users**
- The share function would help those in the K-12 IT like myself giving internal users the ability to share articles amongst themselves to benefit each other
- Article corrections are handy for those that find updated ways to deploy software and want to submit these changes with description for review and then approve those changes adding it to the article
- Feedback from the community of "your users" helps to get stats of whether the article was helpful or not anonymously
- Gif's would give us the ability to add tasks in motion and giving end users a visual way of viewing the process they need to follow in the article

**Comment by ssddanbrown** [comment]
Thanks for the input @athornfam2 but I'm going to close this off since multi-request issues are hard to track & manage and since some of these are already open in some form.

GIFs should be supported, if there's an issue uploading/using a GIF feel free to file a bug report issue.
