### ISSUE TITLE
Password Protection for individual Page

### ISSUE THREAD

**Issue by travelg** [BookStackApp/BookStack#2780]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.

it is good feature to password protect individual page like Apple Note have this feature. 

**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.
To secure some sensitive information can be password protected so it can be open only by entering extra password or 2 factor authentication so its not open by mistake in front of a child. 

**Additional context**

Thanks.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @travelg, I'd consider this to overlap with #820 to be considered a duplicate so I'm therefore going to close this off.
