### ISSUE TITLE
Sort roles alphabetically in custom permissions and roles overview

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#2782]
**Describe the feature you'd like**
Sort roles alphabetically in custom permissions and roles overview

**Describe the benefits this feature would bring to BookStack users**
Roles will be easier to find.

**Additional context**
Suggestion from closed issue https://github.com/BookStackApp/BookStack/issues/2698.

**Comment by ssddanbrown** [comment]
Thanks @Bolthier, Have assigned to the next patch release.
