### ISSUE TITLE
Adjust Favourite sidebar style in non-default homepage

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#2783]
**Describe the bug**
When using a custom homepage like Books, Shelves or Specific Page the Favourite sidebar uses the default style with slithly brighter background. The UI should use the same style as the other sidebars like My Recently Viewed or Recently Updated Pages.

**Steps To Reproduce**
1. Go to 'Settings'
2. Change homepage to 'Shelves'
3. Favourite a book/chapter/page
4. See sidebar with slightly off style

**Expected behavior**
The same style as the other sidebars.

**Screenshots**
![image](https://user-images.githubusercontent.com/42382626/120477167-c06b1800-c3ab-11eb-9b26-a921bf923957.png)
![image](https://user-images.githubusercontent.com/42382626/120477311-e98ba880-c3ab-11eb-8bcc-fe647117a768.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.05
 - PHP Version: 7.3.28
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for raising @Bolthier. Looks like I copied it direct from the standard homepage without looking at the format used for the other sidebar items. Thought I tested it but obviously not since that's quite obvious. Have assigned to the next patch release.
