### ISSUE TITLE
Active diretory questions

### ISSUE THREAD

**Issue by dakarbr** [BookStackApp/BookStack#2789]
I was able to log bookstack into an LDAP active directory on a windows 2019 but I'm not getting it on a windows 2012 r2

the only difference in 2019 runs version 21.4 and in win2012 version 21.5

**Comment by dakarbr** [comment]
are different instances and servers

but in both I'm running ubuntu 20.4

all updated

in one running bookstack version 21.4
server win2019 100% functional

on another bookstack 21.5
windows 2012 r2
when I switch to ldap it doesn't even load the page

**Comment by dakarbr** [comment]
my file on win2019 works perfect

# General auth
AUTH_METHOD=ldap

# The LDAP host, Adding a port is optional
LDAP_SERVER=192.168.1.240:389
# If using LDAP over SSL you should also define the protocol:
# LDAP_SERVER=ldaps://example.com:636

# The base DN from where users will be searched within

LDAP_BASE_DN=dc=domain,dc=com

# The full DN and password of the user used to search the server
# Can both be left as false to bind anonymously
LDAP_DN=administrator@domain.com
LDAP_PASS=password

# A filter to use when searching for users
# The user-provided user-name used to replace any occurrences of '${user}'
# If you're setting this option via other means, such as within a docker-compose.yml,
# you may need escape the $, often using $$ or \$ instead.
LDAP_USER_FILTER=(&(sAMAccountName=${user}))

# Set the LDAP version to use when connecting to the server
# Should be set to 3 in most cases.
LDAP_VERSION=3

# Set the property to use as a unique identifier for this user.
# Stored and used to match LDAP users with existing BookStack users.
# Prefixing the value with 'BIN;' will assume the LDAP service provides the attribute value as
# binary data and BookStack will convert the value to a hexidecimal representation.
# Defaults to 'uid'.
LDAP_ID_ATTRIBUTE=BIN;objectGUID

# Set the default 'email' attribute. Defaults to 'mail'
LDAP_EMAIL_ATTRIBUTE=mail

# Set the property to use for a user's display name. Defaults to 'cn'
LDAP_DISPLAY_NAME_ATTRIBUTE=cn

# Force TLS to be used for LDAP communication.
# Use this if you can but your LDAP support will need to support it and
# you may need to import your certificate to the BookStack host machine.
# Defaults to 'false'.
LDAP_START_TLS=false

# If you need to allow untrusted LDAPS certificates, add the below and uncomment (remove the #)
# Only set this option if debugging or you're absolutely sure it's required for your setup.
# If using php-fpm, you may want to restart it after changing this option to avoid instability.
#LDAP_TLS_INSECURE=true

# If you need to debug the details coming from your LDAP server, add the below and uncomment (remove the #)
# Only set this option if debugging since it will block logins and potentially show private details.
#LDAP_DUMP_USER_DETAILS=true

LDAP_THUMBNAIL_ATTRIBUTE=thumbnailPhoto

**Comment by ssddanbrown** [comment]
@dakarbr Try removing the last line of that posted config:

```
LDAP_THUMBNAIL_ATTRIBUTE=thumbnailPhoto
```

That option is fairly new, there's a chance it's causing issues.

When you say:

>  when I switch to ldap it doesn't even load the page

Is that when attempting to just view the login page? Or are you able to see the login page but it stops loading when attempting to login?

**Comment by dakarbr** [comment]
I think I found the problem.

the ad password has - and spaces

how can i decide where there is space?

in the config file

**Comment by ssddanbrown** [comment]
@dakarbr To support spaces wrap the whole value in quotes, For example:

```bash
MY_OPTION="Value with spaces within"
```

**Comment by dakarbr** [comment]
Tks

**Comment by ssddanbrown** [comment]
Will therefore close this off.
