### ISSUE TITLE
Undefined variable: currentUser (View: /var/www/bookstack/resources/views/partials/sort.blade.php)

### ISSUE THREAD

**Issue by col-panic** [BookStackApp/BookStack#2794]
**Describe the bug**
After updating to Bookstack 21.05.1 with a SAML login, the login does not work anymore, showing
```
Undefined variable: currentUser (View: /var/www/bookstack/resources/views/partials/sort.blade.php)
```

**Steps To Reproduce**
1. Update to Bookstackt 21.05.1
2. Login via SAML provider (Keycloak 12)

**Expected behavior**
Login should work

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1679857/121131231-c475ba80-c82f-11eb-96f0-9a79959aa0b1.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.05.1
 - PHP Version: 7.4.20
 - Hosting Method (Nginx/Apache/Docker): Docker

**Additional context**
Keycloak SAML Login

**Comment by ssddanbrown** [comment]
Hi @col-panic,
I think the code you're using may be outdated, That line has not used that variable since v21.04. 
Here's the code as per the v21.05.1 release as an example:
https://github.com/BookStackApp/BookStack/blob/v21.05.1/resources/views/partials/sort.blade.php#L7

**Comment by col-panic** [comment]
I see, that was an error on our site! Thank you for checking!
