### ISSUE TITLE
Be able to set changelog under Page Revision

### ISSUE THREAD

**Issue by nousrfound** [BookStackApp/BookStack#2795]
**Describe the feature you'd like**
I would like to be able to set the changelog for  the current version without having to make a new revision.

**Describe the benefits this feature would bring to BookStack users**
Sometimes miss to add a changelog where it is useful for others to see.
Makes it easier to spot changes in large dokuments without having to open the changes and scroll.

**Comment by ssddanbrown** [comment]
Hi @nousrfound,
Thanks for opening this issue.

This has already been requested in #202 therefore I'm going to close this to reduce duplicates. If you add a :+1: reaction to the original post on #202 it will help show support for that request.
