### ISSUE TITLE
Months aren't translated

### ISSUE THREAD

**Issue by R0GGER** [BookStackApp/BookStack#2797]
### Language To Add
Months aren't translated in all language-files other than English.

**Example:**
![raw](https://user-images.githubusercontent.com/8298741/121314545-bc894980-c907-11eb-80ec-567c5f0c9331.png)
 

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Hi @R0GGER,
I just tested this on my dev install and these should translate. 
For generating dates BookStack does defer to system locale data.

Can you confirm if you have the `nl_NL` locale installed on your BookStack host system?
If you're not sure please let me know your method of hosting and, if possible, the operating system and I can attempt to provide guidance.

**Comment by R0GGER** [comment]
Ah..! Now I understand. Do not have `nl_NL` installed on my server.

**Comment by ssddanbrown** [comment]
> It would be nice if Bookstack doesn't rely on linux locale, but on the language files in /resources/lang/. Because when somebody chooses another language in Bookstack - Profile you have this problem again and again.

I guess but it would but it would put extra burden on the translators and make it less flexible for us to change/add date formats when desired or needed. If dates were more commonly shown I'd consider it but at this time I'd deem it not really worthwhile due to the their limited usage within BookStack.
