### ISSUE TITLE
Add permissions for project per user

### ISSUE THREAD

**Issue by Rumcajsev** [BookStackApp/BookStack#2799]
**Describe the feature you'd like**
In my organization not all books are shared with everyone - people should have access to books relevant to their projects only.  
Current workaround for this is:

- Creating a user group
- Adding individual users to given group
- Assigning custom permissions to a book for given group

I think this process can be a bit complex, as each person has to be manually added to the relevant group, which takes some time to go around the same menus few times. 
Additionally, it creates a lot of groups, which clutter the UI when eg. adding custom permissions or editing users access to groups.

Ideally, I would be able to give users access to certain books directly, rather than via groups they are members.
This could be set up in custom permisssions, similar to groups. Users could have the same permission settings (read, create, update etc.) as groups currently do. 
In order not to clutter the screen, users could be added via a autocomplete dropdown. When user is added to the permissions, then admin user can set up their permission settings for given book, or remove them from access.

**Describe the benefits this feature would bring to BookStack users**
This would make it much easier to work with a permissions system for organizations where it's more relevant to add access per person rather than per group. It would also cut down on number of groups created for this purpose, which currently unnecessarily clutter the groups list.

**Comment by ssddanbrown** [comment]
Thanks for the request @Rumcajsev. The core request has already been requested under #1747 so I'm going to therefore close this off as a duplicate.
