### ISSUE TITLE
Feature ask :: Recover deleted page/chapter/book

### ISSUE THREAD

**Issue by patoroco** [BookStackApp/BookStack#280]
Hi,

should be possible to save a history / revisions of deleted pages/chapters/books? It's dangerous to allow to full-delete by error and don't allow to recover the pages.

Maybe this feature exists, but I haven't find it :)

**Comment by thestepafter** [comment]
Yes, please add this feature to help with avoiding the loss of data if you delete something you shouldn't have.

**Comment by monitaure** [comment]
I would just add that history (or revisions) is a really great feature, even more if you are using an app for collaborative work.

**Comment by patoroco** [comment]
My suggest is to save revision, and delete page from database.

Maybe should be possible to have a "trash", where you can un-delete pages in last 30 days? In other case, remove totally (with all attachments).

What do you think?

**Comment by pdfrod** [comment]
A book has just disappeared and I have no idea who deleted, when or why. So yeah, something should be done in this department. At least an audit trail.

**Comment by ssddanbrown** [comment]
@pdfrod Just an FYI, If you'd like to find out what happened, Delete actions are commonly recorded but just not reflected in the UI. You can find them in the database on the `activities` table:

```sql
SELECT * FROM activities
     WHERE `key` LIKE '%_delete'
     ORDER BY created_at DESC
```

The `extra` column contains the name of the item deleted, The `user_id` is the `users` table id of the user that triggered that action.

**Comment by pdfrod** [comment]
That's helpful, thanks a lot @ssddanbrown!

**Comment by patoroco** [comment]
Thanks @ssddanbrown !

**Comment by ssddanbrown** [comment]
I've added a recycle bin implementation in #2283, which will be part of the next release (v0.31). Additionally, as of v0.30 it's possible to see delete events in the audit log (https://www.bookstackapp.com/blog/beta-release-v0-30-0/). 

Since the code for this has been merged, ready for a release, I'm going to close this off.

**Comment by patoroco** [comment]
Thanks for taking this one @ssddanbrown !
