### ISSUE TITLE
Trying to get property 'childNodes' of non-object

### ISSUE THREAD

**Issue by marinkaberg** [BookStackApp/BookStack#2804]
**Describe the bug**
Every time I attempt to export page as PDF or HTML, I have the following:
`ErrorException
Trying to get property 'childNodes' of non-object (View: /var/www/html/resources/views/partials/export-custom-head.blade.php)`

**Steps To Reproduce**
1. Settings -- Customization -- Custom HTML Head Content, add single line `<!-- Just a comment -->`, and save.
2. Open any page, Export -- html OR pdf (txt works fine)

**Expected behavior**
It is absolutely necessary that BookStack cannot be broken by user-defined content.

**Screenshots**

**Your Configuration (please complete the following information):**
Latest linuxserver docker image. Please let me know if you cannot reproduce this behavior: I'll show it remotely.

**Comment by ssddanbrown** [comment]
Thanks for raising @marinkaberg.

This has been addressed in b5caaa73b7b526f8fe8692ded0b31b1cbbc6c4d4 and assigned to be part of the next patch release.
