### ISSUE TITLE
Header Markdown not rendering

### ISSUE THREAD

**Issue by DDCMI** [BookStackApp/BookStack#281]
### For Bug Reports

* BookStack Version: 0.13.1
* PHP Version: 7.0.13
* MySQL Version: 5.7.16

##### Expected Behavior
markdown code to render in preview and after save
##### Actual Behavior
shows raw markdown

**Comment by ssddanbrown** [comment]
Hi @DDCMI, Sorry to hear you're having problems with the markdown editor. Could you confirm your browser application (and version) along with your operating system.

If possible, Could you also post a screenshot of any errors in the browser developers tools (Usually press F12 then click 'Console').

**Comment by DDCMI** [comment]
Browser chromium 55.0.2883.87

Arch linux 

kernel 4.8.13-1

so I guess its not that nothing renders (my bad I didnt get past the header not working ) however as you can see the header does not render. the error that where thrown where when I added the checkbox and the inline image link

![image](https://cloud.githubusercontent.com/assets/5843899/22084208/25034a34-dd9d-11e6-84a5-1407f519351d.png)

**Comment by Azphreal** [comment]
You need a space between the pound sign and the text of the header.

```
# Header
```
rather than 
```
#Header
```

**Comment by ssddanbrown** [comment]
Thanks @Azphreal, Beat me to it 😃

@DDCMI Nice arch system by the way, Is that top bar using arc theme?

**Comment by ssddanbrown** [comment]
@DDCMI Awesome! Yeah, Markdown seems to be a quite flexible standard in the fact there's quite a few 'Flavours' of markdown syntax and rendering about. A space after the hash is quite a common rule though.

I'll go ahead and close this issue now this is solved 🙌
