### ISSUE TITLE
Sorting a book changes the update time on pages.

### ISSUE THREAD

**Issue by nousrfound** [BookStackApp/BookStack#2811]
**Describe the bug**
When I sort a book the update time on pages changes if they are sorted, But looking at revisions it shows the last time the page was edited and saved.

**Steps To Reproduce**
1. Make a bunch of pages
2. Wait
3. Sort
4. New update time

**Expected behavior**
Show the same time on page updated as the revision

**Screenshots**
![image](https://user-images.githubusercontent.com/58333053/121998414-1ed0c700-cdac-11eb-844a-77d025e9ae27.png)
![image](https://user-images.githubusercontent.com/58333053/121998429-24c6a800-cdac-11eb-9599-d70382026ed2.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: v21.04.5
 - PHP Version: 8.0
 - Apache

**Comment by ssddanbrown** [comment]
Thanks for reporting @nousrfound. 

The core issue here has already been noted as part of #1777 so I'll therefore close this off as a duplicate.
