### ISSUE TITLE
Feature request - Honor transparency in profile picture

### ISSUE THREAD

**Issue by paulkoene** [BookStackApp/BookStack#2812]
It would be nice if the transparency in a profile png was used.

The benefit would be that instead of a circle with the profile picture in it, the picture would "pop-out" on the background.

**Comment by ssddanbrown** [comment]
Thanks for the request @paulkoene,
As per the feature request issue template, would you be able to fill-out the following part of it?:

```
**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.
```

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
