### ISSUE TITLE
I have exactly the same problem as Bug # 2485 "Bookstack | docker linuxserver/bookstack + nginx-proxy-manager"

### ISSUE THREAD

**Issue by nady2804** [BookStackApp/BookStack#2814]
Bookstack working well during local network without ssl. 
Then i will forward this with my nginx-proxy-manager and Letsencrypt keys.

I see only the big Letters was describted in the Bug #2485 
Unfortunatly the Bug was closed without any hints to find the bug......

I hope i'm not alone with this problem.
Both bookstack and nginx-proxy-manager ist hostetd on same ubuntu docker system hosted from proxmox  

**Expected behavior**
Can any help with some hints were can it be?

Br
Manfred

**Comment by ssddanbrown** [comment]
Hi @nady2804,
After updating to a HTTPS setup, did you update the APP_URL value to match the new base URL?

Please check any `APP_URL` values you're passing to the container and any within the `/config/www/.env` (You'd typically have that config folder mounted to your host system if using the linuxserver image).

**Comment by nady2804** [comment]
I checked this now with my new https domain and it worked now. I reconfigure the docker-compose file and rebuild container.
Great thx for helping

**Comment by nady2804** [comment]
Fixed now

**Comment by 4cki** [comment]
can you share your docker-compose file, so we could learn?

**Comment by nady2804** [comment]
---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://FQDN NAME
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstackPASSWORD
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/docker/bookstack/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstackPASSWORD
      - TZ=Europe/Vienna
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstackPASSWORD
    volumes:
      - /mnt/docker/bookstack/data:/config
    restart: unless-stopped

**Comment by nady2804** [comment]
I hope that helps!
