### ISSUE TITLE
Code Block editing do not work on iphone/iPad browsers

### ISSUE THREAD

**Issue by travelg** [BookStackApp/BookStack#2815]
**Describe the bug**
editing Code Block in iPhone browsers do not work. 

**Steps To Reproduce**
1. Go to edit page
2. Click on Formats
3. Add New Code Block and add some text
4. Save page
5. Open again this page to edit
6. Try to touch code block edit it on iPhone
7. Error Can not edit code block

**Expected behavior**
able to edit code block on touch screen devices iphone/iPad

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.05.2

**Comment by ssddanbrown** [comment]
Thanks for reporting @travelg  and sorry for the late response. 
Can confirm this, and have added functionality in 0269f5122e114203586d6fbb1e795e2421fb679b to show a tooltip, with edit button, when a code block is selected in the editor.
This will be part of the next feature release.
