### ISSUE TITLE
Password protect PDF exports

### ISSUE THREAD

**Issue by candrews67** [BookStackApp/BookStack#2816]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.

Would it be possible or is it already and i just missed it, to put a password on PDF exports?

**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.

I have been using BookStack for documentation.
 Awesome concept of books and shelves so this is perfect. Some of the documentation contains sensitive information and protecting it would be a benefit.

**Additional context**

I can not think of anything else to better explain.

Thanks for your time.

**Comment by Haboubi92** [comment]
passwords protection for pdf can be easily removed with many free online tools

**Comment by ssddanbrown** [comment]
Thanks for the request here but, since there's been no further request and since I don't want to complicate export formats unless for great benefit, I'm going to go ahead and close this off.
