### ISSUE TITLE
oAuth (GitHub) email verification 

### ISSUE THREAD

**Issue by ArieLevs** [BookStackApp/BookStack#2818]
**Describe the bug**
I'm not sure if its a bug or expected behavior,
but when setting up oauth vis GitHub and allowing registration the application tries to send a verification email.
I'm not sure why? 

**Steps To Reproduce**
1. Setup [authentication via GitHub](https://www.bookstackapp.com/docs/admin/third-party-auth/#github)
2. Enable registration so new users can register (for application settings)
3. Click the `Don't have an account?` on login screen
4. Choose `Sign up with GitHub`

**Expected behavior**
If using oAuth email verification should not be enforced.

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: v0.31.6
 - Hosting Method (Nginx/Apache/Docker): Docker

**Comment by ssddanbrown** [comment]
Hi @ArieLevs,
Within the settings of your BookStack instance, Are you using the "Domain Restriction" or "Email Confirmation" options at all?

**Comment by ArieLevs** [comment]
Hi @ssddanbrown, yes we use domain restriction,
I assume this should of been a feature request instead of a but issue, 
to add "allowed github organizations" or "restrict by GitHub user email".

The behavior is not 100% clear,
if for example I add `test.com` as restriction, and then try to register with GitHub user that has an email of `gmail.com` then I get message "The email domain does not have access to this application", 
this means that the restriction works as expected, 
but because it's a oauth user i'd assume verification would not be needed.

Thanks for the quick response, I'll close this one.

**Comment by ssddanbrown** [comment]
Thanks for confirming @ArieLevs,

It's worth reading the "Automatic Email Confirmation" section of this page: https://www.bookstackapp.com/docs/admin/third-party-auth/

Setting `GITHUB_AUTO_CONFIRM_EMAIL=true` should mean that GitHub provided email addresses are treated as verified.
