### ISSUE TITLE
Custom HTML Head not applied to /settings page

### ISSUE THREAD

**Issue by wxrl** [BookStackApp/BookStack#2819]
The custom HTML head is valid (e.g. customized font) for most pages but not the /settings page, while /settings/maintenance, /settings/audit, /settings/users, /settings/roles pages are using the customized font.

**Comment by ssddanbrown** [comment]
Hi @wxrl,

This is very much purposeful, and explained under the setting input:

![Screenshot from 2021-06-24 21-20-37](https://user-images.githubusercontent.com/8343178/123327252-202f8b80-d532-11eb-9b77-f74ec4f80c1a.png)

This is to ensure that any troublesome custom code can always be reverted if needed.
