### ISSUE TITLE
Adding a new Admin/User breaks at 3 max

### ISSUE THREAD

**Issue by aroldjacx** [BookStackApp/BookStack#2824]
**The bug**
As an admin when I create three (3) additional  users. After that, the system throughs an error if you want to create more users.

**Steps To Reproduce**
1. Go to 'Settings'
2. Click on 'Users'
3. Add A New User 'Click Add New User button', and now add more than  three (3) ADMINS until it Barks at you!.
```
**Illuminate\Database\QueryException**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'users.users_slug_unique' (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (xtimx, xtimx@gmail.com, $2y$10$3VZvuaT9oG/.O9n7Cs4R../oFLxf7W9cgio0w3IsqyrJ8DGHj2rH6, 2021-06-28 13:45:27, 2021-06-28 13:45:27))
http://bookstack.localhost/settings/users/create
```

**Expected behavior**
I expect to have the ability to create as much user/admin as needed without errors.

**Screenshots**
![admin](https://user-images.githubusercontent.com/8050442/123655052-a7178900-d7fc-11eb-8ab6-3e5867324d62.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.31.8
 - PHP Version:
 - Hosting Method: Nginx

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @aroldjacx,
I'm pretty sure your BookStack codebase and database state versions have got muddled here. Have you pehaps done some level of restore or attempted an upgrade to a more recent version? The column reported in the issue thrown was added in a later BookStack release than that shown in your reported version number.

**Comment by aroldjacx** [comment]
Upgrade yes! I did attempt an upgrade last month. are you saying the upgrade procedure was not complete? How would i go about cleaning this up?

**Comment by ssddanbrown** [comment]
@aroldjacx I don't think it's complete, That version of BookStack is a few months old. It depends on the errors that occured upon upgrade. Do you get any errors when running the upgrade command?

**Comment by aroldjacx** [comment]
Yes! what I have don is install the latest and now it working. You practically helped solve the issue from your first response. now i am just porting my setting over via the database

**Comment by aroldjacx** [comment]
THANKS much for your help solider!

**Comment by ssddanbrown** [comment]
@aroldjacx Glad to hear you got things working. Will therefore close this off.
