### ISSUE TITLE
Confirmed Signature[feature request]

### ISSUE THREAD

**Issue by kimet83** [BookStackApp/BookStack#2835]
I'm trying to use bookstack to create tutorials for groups to use.
I need the feature to be able to sign when a group member has read and verified a document.

ex)

I checked this document  [confirm] ↔ [unconfirm]
↓
user1 confirmed this article on 10/24.
user2 confirmed this article on 10/25.

**Comment by userbradley** [comment]
This would be better to do as a business procedure like using docusign or just have them leave a comment

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @kimet83  but I agree with @userbradley that using existing functionality such as comments or tags would be applicable for this kind of thing. In addition, this is a very specific requirement and it's not clear how this would benefit the majority of BookStack users (As requested in the feature request template).

I'll therefore close this off.
