### ISSUE TITLE
Markdown Checklist/Todo-List not hierarchical in Preview

### ISSUE THREAD

**Issue by randombugs** [BookStackApp/BookStack#2837]
**Describe the bug**
Markdown Checklist/Todo-List not hierarchical in Preview. Works after saving the page.

**Steps To Reproduce**
1. Create Page and paste: 
````
- [ ] whatever
  - [x] sub-whatever
````
2. see preview without indentation
3. save and see correct indentation
**Expected behavior**
Preview same as saved Page.

**Screenshots**
1. Editor + Preview: 
![bookstack-1](https://user-images.githubusercontent.com/84946465/124627701-10903b00-de80-11eb-96d5-7b0fcbac1fa4.jpg)
2. Saved Page: 
![bookstack-2](https://user-images.githubusercontent.com/84946465/124627721-1423c200-de80-11eb-87bd-38e210a4ce07.jpg)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.05.1 
 - PHP Version: PHP 7.4.20
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for reporting this issue @randombugs , with clear details and screen-shots.

This has now been patched and will be part of the next feature release. More details can be found in https://github.com/BookStackApp/BookStack/issues/2854#issuecomment-904148432.
