### ISSUE TITLE
top menu not rendering

### ISSUE THREAD

**Issue by anutator** [BookStackApp/BookStack#2839]
**Describe the bug**
After upgrading to the last version 21.05.3 can't see the full top menu, need to scroll (Firefox, Chrome). I can see full menu only if I  press `Ctrl `+ `-` twice. But all letters in other sections become smaller.
I have long site name bug everything was ok in last versions.

**Steps To Reproduce**
Open any wiki page.

**Expected behavior**
I can see full top menu and login without scroll.

**Screenshots**
Screenshots attached. 1- top menu (top right corner), 2 - top menu after scroll
<img width="431" alt="top_menu" src="https://user-images.githubusercontent.com/25155468/124750286-f44ad780-df2d-11eb-916a-b93af32ef58e.png">
<img width="555" alt="top_menu_after_scroll" src="https://user-images.githubusercontent.com/25155468/124750289-f57c0480-df2d-11eb-8da0-6643271ed604.png">

Top menu in Microsoft Edge - I can see full top menu and small main text (as after `Ctrl `+ `-` twice in Firefox and Chrome).
<img width="406" alt="top_menu_edge" src="https://user-images.githubusercontent.com/25155468/124751589-78ea2580-df2f-11eb-8d0d-f844d7566be5.png">

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.05.3
 - PHP Version: 7.4.20
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Hi @anutator,
Is this something you're able to re-produce on [the demo instance](https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site)? Or does this only occur on your own instance?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please respond to the previous message in a request for this to be re-opened.
