### ISSUE TITLE
HTML subscript not rendering

### ISSUE THREAD

**Issue by Azphreal** [BookStackApp/BookStack#284]
### For Bug Reports

* BookStack Version: 0.13.1
* PHP Version: 7.0.14
* MySQL Version: 10.1.20-MariaDB

##### Expected Behavior
Subscript to appear as text below the line

##### Actual Behavior
Subscript does not format with html tag `<sub>`. Superscript does.  
Issue is consistent in WYSIWYG editor.

![capture](https://cloud.githubusercontent.com/assets/21125058/22273477/153a5b08-e2f5-11e6-8579-165537d491b7.PNG)

**Comment by ssddanbrown** [comment]
@Azphreal Thanks for reporting this. Looks like subscript wasn't used that much as the styling was missing for quite a while 😨 
I've just deployed a new release, v0.14.2, to cover this and a few other bugs.
