### ISSUE TITLE
Updating the book stack website

### ISSUE THREAD

**Issue by hsharma89** [BookStackApp/BookStack#2841]
Hi  ,

I have updated my bookstack website to version to 21.05.03.

After updating my pages stopped working. Main page is working but when i open inner pages its not working.

![image](https://user-images.githubusercontent.com/22783551/124903965-2168ba00-e002-11eb-832b-1f8c7e2a72b6.png)

Is anybody knows this, please let me know.

Thanks

**Comment by pommetjehorlepiep** [comment]
@hsharma89 , I just updated to 21.05.03 as well and got the same issue!

When I opened dev tools in my browser it showed this
`
Failed to load resource: the server responded with a status of 500 ()
DevTools failed to load source map: Could not load content for https://bookstack.local/dist/print-styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load source map: Could not load content for https://bookstack.local/dist/app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load source map: Could not load content for https://bookstack.local/dist/styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
`
I checked for the mentioned files and found that they exist, but without the **.map** extension...

**Comment by ssddanbrown** [comment]
@pommetjehorlepiep Those console warnings (And missing map fields) should not be an issue, apart from maybe the first but I'm not sure what that first message refers to within the full context from your console.

---

@pommetjehorlepiep @hsharma89 If you are getting that 500 error shown after updating please ensure you have read any relevant version specific [update instructions on this page](https://www.bookstackapp.com/docs/admin/updates/) to ensure that you have met any requirement changes.

If you are still having issues, [this page of the documentation](https://www.bookstackapp.com/docs/admin/debugging/) explains how to get more information on any errors by finding your log file where any errors will be logged. If you get to that stage and are still unsure about what to do, feel free to open a new issue here, following the "Bug Report" issue template to help provide any details that might help us diagnose this issue.

**Comment by hsharma89** [comment]
Hi All,

I am able to resolve the issue. There are few tables missing in database which may be added in new version.  I run the migration command and it started working.

I ran the command before while updating version, but did not work at that time, but when i ran only this command it worked.

Thanks to all.
