### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by pulunza** [BookStackApp/BookStack#2844]
There are typoes in the "Multiple BookStack instances" page! (Of the "capitalization where it shouldn't be" variety).

> Before proceeding, Ensure you have your domains set up for all instances you want to create.

> Follow the standard installation instructions for each instance, Starting by cloning BookStack into each folder you created above.

> Once created, You will need to enable each site with the command

I know it's a tiny thing, but I noticed it and wanted to bring it to someone's attention.

**Comment by ssddanbrown** [comment]
Thanks @pulunza, I tend to be quite bad for putting capitals after commas. 

Have applied https://github.com/BookStackApp/website/commit/8c0cf215c95950aecc7713620f71e1bfe5ca8a04 to patch these cases and some others.
