### ISSUE TITLE
Support nested levels/use of content include tags

### ISSUE THREAD

**Issue by sid3windr** [BookStackApp/BookStack#2845]
**Describe the bug**
Multiple layers of page inclusion are not being evaluated correctly.

**Steps To Reproduce**
1. Create page A with some content.
2. Create page B with some content, and include page A in it. This will display correctly.
3. Create page C with some content, and include page B in it.
4. Page C will have the page C content from step 3, and the page B content from step 2, followed by the {{@123}} inclusion tag for page A, instead of page A's content.

**Expected behavior**
All pages to be included should be displayed correctly.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.04
 - PHP Version: 7.3.29
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Comment by ssddanbrown** [comment]
Related to #1601

**Comment by robertfshort** [comment]
+1 for this feature

**Comment by JoeIzzard** [comment]
+1 for this

**Comment by jasonF1000** [comment]
+1 for this feature

**Comment by deleyva** [comment]
+1 for this feature

**Comment by jasonF1000** [comment]
Hi,

i think a depth of 3 layers for the page inclusion should be enoght for the most cases.
Is there any implementation Plan in the near Future for this Feature?

Regards,
jason

**Comment by ssddanbrown** [comment]
Up to three levels of nested has now been added within the work of PR #4192, thanks to @jasonF1000.
Will be part of the next feature release.
