### ISSUE TITLE
FastCGI sent in stderr: "PHP message: PHP Fatal error:

### ISSUE THREAD

**Issue by BirenGroove** [BookStackApp/BookStack#2846]
I am getting issue with composer 

2021/07/14 17:16:24 [error] 3456#3456: *48 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.0.33. in /var/www/BookStack/vendor/composer/platform_check.php on line 24" while reading response header from upstream, client: 172.30.7.71, server: km.bmonmove.icicibank.com, request: "GET / 
HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host:

I try to update the PHP version to 7.3 but getting the below error 

Error: Package: gd-last-2.3.2-1.el7.remi.x86_64 (remi-safe)
           Requires: libraqm.so.0()(64bit)
 You could try using --skip-broken to work around the problem

**Comment by ssddanbrown** [comment]
Hi @BirenGroove,
Any PHP version greater than PHP7.3 should do it, You could install PHP8 now so you don't have to upgrade it again for a while (Unless you're running other applications on the same server that require a lower PHP version).

What operating system are you using? The Remirepo site has quite a straightforward wizard to provide you the commands for installing a specific PHP version, which can be found here: https://rpms.remirepo.net/wizard/

**Comment by BirenGroove** [comment]
I have Redhat 7, but there is check on Bookstack for PHP 7.3 it's checking that always !! can't we overnight the check ??

**Comment by ssddanbrown** [comment]
There is technically a way to ignore the php version during install, but bookstack does require PHP >= 7.3 so the logical thing is to ensure the right PHP version exists and is in use.

**Comment by BirenGroove** [comment]
If there PHP higher version, as you mention above install PHP 8 does it will work

**Comment by ssddanbrown** [comment]
@BirenGroove PHP8 should be fine. Remember to uninstall any other versions first to prevent confusion.

**Comment by BirenGroove** [comment]
Is this file required run bookstock on PHP8 
**79 connect to unix /var/run/php-fpm/php-fpm.sock**

**Comment by ssddanbrown** [comment]
@BirenGroove Maybe, but it very much depends on your webserver and how it's using PHP.

**Comment by BirenGroove** [comment]
I have RHEL 7.9 there was some issue with PHP version and FPM as well I did fresh installation for php7.3 and install composer it's working fine now

**Comment by ssddanbrown** [comment]
@BirenGroove Glad to hear you got it working. Just a warning, Keep an eye out for BookStack PHP version requirement changes since we'll likely require PHP7.4 as a minimum later this year or early next year.
