### ISSUE TITLE
.env parameter change not recognized by front end

### ISSUE THREAD

**Issue by whentotrade** [BookStackApp/BookStack#2847]
Changing .env parameter, but not recognized on front end when visiting site via a browser

I changed from oauth 2 provider via setting in the env file:
New entry
AUTH_METHOD=standard

Old entry (removed)
AUTH_METHOD=saml2

However, the login page still links to my IDP provider.

I observe similar behaviour if changing env parameters which are not picked up when visiting the front end via the browser.

Question:
What is required in order to bookstack app recognize .env parameter changes?

**Comment by whentotrade** [comment]
I found the solution:

I needed to run the following command to in order for the app to pick up latest .env settings and changes:

`artisan config:cache`

**Comment by whentotrade** [comment]
I found the solution:

I needed to run the following command to in order for the app to pick up latest .env settings and changes:

`artisan config:cache`

**Comment by ssddanbrown** [comment]
Hi @whentotrade,
Note that since you've cached your config you'd need to run that on any config change or app version update.
You can also run `artisan config:clear` to simply clear this cached config.
