### ISSUE TITLE
Draw.io - Error

### ISSUE THREAD

**Issue by grootsys24** [BookStackApp/BookStack#2849]
Hello,

when I try to use the Draw.io function of BookStack I get the following error message. What do I have to adjust so that it works and where?

BookStack v21.05.3 

![grafik](https://user-images.githubusercontent.com/66802022/126270020-5559ff21-352c-4fd9-835e-663d509ad74c.png)

**Comment by ssddanbrown** [comment]
Hi @grootsys24,
Are you sure you're using BookStack v21.05.3? We've been using `https://embed.diagrams.net` since BookStack v0.30.2 was released. 

This could also occur if you've defined a custom `DRAWIO` value in your `.env` file.

**Comment by grootsys24** [comment]
Yes, the version number will be displayed to me in the Admin Gui and I have done all the updates according to your information from the blogs. Where would the link to the Draw.io app be normal? Maybe something just wasn't updated

How check it ?

**Comment by grootsys24** [comment]
I found the Problem. Its was the cache. Sorry no error from BookStack

**Comment by ssddanbrown** [comment]
Thanks for confirming @grootsys24, Will therefore close this off.
