### ISSUE TITLE
One click installation with Softaculous in shared hosting environment

### ISSUE THREAD

**Issue by Haboubi92** [BookStackApp/BookStack#2850]
Me and numerous other users had [suggested](https://www.softaculous.com/board/index.php?tid=13625) adding Bookstack to Softaculous list of one click installation apps which is available in so many hosting services including very cheap shared hosting plans.

today I received the following response from Softaculous
"Hi,

Sorry for the delay. We are facing issue in Bookstack which we have reported here : [https://github.com/BookStackApp/BookStack/issues/2624](https://github.com/BookStackApp/BookStack/issues/2624)

They do not support installation in shared hosting environment. We are unable to provide it because it requires to make change in server's vhost file and Softaculous does not have rights to make change in vhost file.

See if you can raise same issue with them and ask for some workaround. Then we can try again."

Softaculous is very important tool for non-tech people to be able to enjoy hassle-free installation and updates.
and I believe it would push Bookstack adoption many folds forward

**Comment by ssddanbrown** [comment]
As per other shared hosting requests, I don't want to risk nor compromise the security to achieve the limitations imposed by shared hosting providers. If a provider does not offer a way to set the web root, or allow setting web-server rules outside of `.htaccess` then they'll likely be compromising in other areas such as lagging PHP version support. 

In addition, supporting shared hosting would open up the app to a wide section of the potential audience that may not be fully understanding in to keeping their instance up-to-date & maintained, and be more likely to rely on the core project to offer support which could have a significant impact.

**Comment by Haboubi92** [comment]
thanks for explaining 🌷
I'll close the issue now
actually I waited few days to see whether someone else have another point to make
