### ISSUE TITLE
Embedded Video wont play / Video upload as attachment fails

### ISSUE THREAD

**Issue by mettadron** [BookStackApp/BookStack#2851]
Hello,

i have problems to embedd Videos on bookstack.
When i embedd a video using a url it wont play after i saved the changes (same behavior as shown [here](https://github.com/BookStackApp/BookStack/issues/882#issuecomment-599155325)). I tried different Browsers (Firefox, Chrome, Edge Chromium. The video play in IE11 but the whole site looks really messed up with this one...

i also tried the attachment method, but the video wont upload at all. i get a message saying that the file could not be uploaded and that maybe the size is limited but i dont think it should not be the problem with somewhat about 3MB...

An upload of other Files (TXT, PPTX, XLSX) or Images works fine.

The workaround metioned on [issue # 882](https://github.com/BookStackApp/BookStack/issues/882) require me to be able to upload videos... 

appreciate any help...

thx

**Comment by ssddanbrown** [comment]
Hi @mettadron,
In regards to this:

> When i embedd a video using a url it wont play after i saved the changes (same behavior as shown here). I tried different Browsers (Firefox, Chrome, Edge Chromium. The video play in IE11 but the whole site looks really messed up with this one...

How exactly are you uploading this video? BookStack does not currently support embeds of videos uploaded as attachments. Even if using an externally hosted video file, Getting cross-browser support on video can sometimes be a tricky thing.

**Comment by mettadron** [comment]
Hi @ssddanbrown,
i use the "insert/edit media" control on a site an paste a location on a networkshare. Something like this:
file://k:/_media/myMediaFile.mp4

the result in Chrome, Firefox and Edge look like this:
![image](https://user-images.githubusercontent.com/85354058/126650135-1bc4fb22-c6f9-419f-ad9e-35a9c5cb4edb.png)

the same page in IE11 looks like this:
![image](https://user-images.githubusercontent.com/85354058/126650284-337259ae-068b-4f55-a092-548b4218d40d.png)

an https link from youtube works fine. just tested this...

**Comment by watschi** [comment]
Hi,

`file://`-links are not supported by any of the main browsers for some time now for security reasons, IE is the only one left to my knowledge.

Embedding videos with links to the filesystem will not be possible in any web application.

**Comment by mettadron** [comment]
@watschi 
oh. ok thank you didnt know that...

what ist the recommended way to to embedd a video on bookstack for now

**Comment by ssddanbrown** [comment]
Thanks for confirming that @watschi,

@mettadron BookStack does not really support hosting video content at the moment, That's effectively what #882 is requesting so I'll therefore close this off.

The best methods would be to use an external source (Vimeo/Youtube) then embed within, or host the video in some other available space to embed although cross-browser video format support can sometimes be tricky.
