### ISSUE TITLE
Updating to 21.05.3 yields blank webpage

### ISSUE THREAD

**Issue by max-d-stephens** [BookStackApp/BookStack#2852]
After installing php8.0.8 web interface still loaded fine. after updating via the tutorial (https://www.bookstackapp.com/docs/admin/updates/) web link yields a blank default login page. The following error is given on update.

<img width="1249" alt="BSupdate" src="https://user-images.githubusercontent.com/87876868/126831602-fe20a4b0-589f-416a-a640-e9c15611cbd8.png">

SYSTEM INFORMATION
Debian 10 bionic man running on VMWare
Bookstack current ver 0.30.5
PHP current ver 7.2.24

**Comment by Abijeet** [comment]
@max-d-stephens - This appears to be a permission issue. Are you using the same user to update as you did to install?

Also note that the minimum PHP version is 7.3

**Comment by max-d-stephens** [comment]
PHP was updated to 8 prior to updating Bookstack.

**Comment by max-d-stephens** [comment]
I will try with same user as install.

**Comment by ssddanbrown** [comment]
@max-d-stephens It's possible that maybe you have two PHP versions installed at the same time. It may also be worth checking:

- Permissions on the `<bookstack_install>/vendor` directory and the contents within. If the user that you're running `composer install` as does not have permission to edit the contents of that folder you may get that error message.
- Composer version (`composer --version`, Should be above version 2 ideally).

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
