### ISSUE TITLE
While setup portal getting "SQLSTATE[HY000] [2002] (SQL: select * from `settings` where `setting_key` = app-public limit 1)"

### ISSUE THREAD

**Issue by BirenGroove** [BookStackApp/BookStack#2853]
Hi Have Bookstack setup everything got installed properly but now getting below error while accessing portal 

![image](https://user-images.githubusercontent.com/77006816/126951355-f3177a50-9c1c-4e27-a17a-eeb66468f1ab.png)

**Comment by ssddanbrown** [comment]
Hi @BirenGroove,
From the error provided it seems like the BookStack instance can't connect to the database at all.
It might depend on how you've installed BookStack, but are you able to run the `php artisan migrate` command from the BookStack installation folder; If so, does it run without error?

**Comment by BirenGroove** [comment]
Hi Dan,

Thanks for your reply, yes I was SQL connectivity issue, I am using Azure Paas SQL which required SSL connection to connect SQL, I fixed this it start working, then I ran **php artisan migrate** inside of bookstack folder and all tables got created after that it's working fine

**Comment by ssddanbrown** [comment]
Thanks for confirming @BirenGroove, Will therefore close this off.
