### ISSUE TITLE
API Pages PUT removes HTML

### ISSUE THREAD

**Issue by mattstanyon-tall** [BookStackApp/BookStack#2856]
Sending a PUT to the pages endpoint results in existing HTML data being removed.

PUT https://bookstack.com/api/pages/123
BODY
{
		"tags": [
		{"name": "My Tag", "value": "Draft"}
	]
}

**Expected behavior**
It's expected only the tags get updated.

**Your Configuration (please complete the following information):**
 - 21.05.3
 - PHP Version: 8
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for reporting @mattstanyon-tall,
Have assigned to be confirmed and patched for the next feature release.
