### ISSUE TITLE
"View All" in a user profile searches by a user id rather than slug

### ISSUE THREAD

**Issue by irefuse** [BookStackApp/BookStack#2857]
**Describe the bug**
When you are in a user's profile page and click "View All" next to and of the "Recently created" sections, it takes you to a search page that is searching by user id rather than the user slug. This inherently causes the search to return all results.

**Steps To Reproduce**
1. Go to any user's profile page
2. Click on "View All" next to one of the "Recently Created" sections
3. View the search bar to see that the created by section is by user id number. "{created_by:3}" rather than "{created_by:test-user}"

**Expected behavior**
The "View All" button should search by user slug to produce the appropriate results.

**Screenshots**
![image](https://user-images.githubusercontent.com/2688319/127186735-f109a3e3-b85a-4c0f-aade-51ec2153638a.png)
![image](https://user-images.githubusercontent.com/2688319/127186796-4b3db52c-66e2-4977-99e4-58f8a2efd29d.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v21.05.3
 - PHP Version: 7.3.22
 - Hosting Method (Nginx/Apache/Docker): IIS

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Thanks for reporting @irefuse, Have assigned to the next feature release or may bring forward to a patch release depending on schedule.

**Comment by ssddanbrown** [comment]
7d19057e68c00891e8e823e794731857a6e1b25b

**Comment by ssddanbrown** [comment]
Thanks again for reporting @irefuse, This has now been addressed as part of [v21.05.4](https://github.com/BookStackApp/BookStack/releases/tag/v21.05.4).
