### ISSUE TITLE
Markdown blockquotes not rendering correctly in preview

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#2858]
**Describe the bug**
When using the Markdown editor and adding a blockquote, the blockquote does not render correctly in the preview pane

**Steps To Reproduce**
1. Go to any book and add a new page
2. Add a blockquote using `> Whatever text you like`
3. See error

**Expected behavior**
The blockquote should render correctly in the preview pane

**Screenshots**
Source:

![image](https://user-images.githubusercontent.com/57015243/127281455-4f422395-0803-446e-87d8-24dac0a07533.png)

Preview:

![image](https://user-images.githubusercontent.com/57015243/127281500-ea0e6c3c-60d7-42d5-9035-76dacf2789e8.png)

Page:

![image](https://user-images.githubusercontent.com/57015243/127281602-f6eac38b-fbd7-4768-9696-c7c6ea2795bd.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.05.3 
 - PHP Version: 8.0.8
 - Hosting Method (Nginx/Apache/Docker):  Apache
 - Linux: Ubuntu 20.04 LTS

**Additional context**
This behaviour shows on existing as well as new pages

**Comment by techauthoruk** [comment]
Mmmm, still puzzling me, this one. I know it doesn't actually impact on what you are trying to create (as the page displays correctly) but it would be nice to see the content correctly in the preview pane before you commit the changes. On a similar vein, I noticed that code blocls are actually highlighted/have colour in the editor pane, not in the preview pane, but display correctly on the published page!

@ssddanbrown Dan - is this an issue with CodeMirror or is there something else at play here? I know it is a really niggly thing that doesn't impact on the page itself, but it would be nice to see the prieview as it should be before its published. Maybe this is caused by the same issue that affects blockquotes #2858 - @ssddanbrown any thoughts Dan?

**Comment by ssddanbrown** [comment]
@techauthoruk The blockquote issue probably is an issue (I can kind guess it's a specific styling issue) but just have not yet spent the time to investigate.

The codeblocks are a known thing, We don't render them out via CodeMirror in the markdown preview for performance (The preview pane is re-rendered on each markdown input change). We could implement a more advanced way to update that preview so we wouldn't have to re-render CodeMirror blocks each change, but I'll be looking into changing the editors significantly later this year so there's not much point spending time on the existing editors unless it's fundamental bugs being addressed.

**Comment by ssddanbrown** [comment]
Thanks once again for reporting @techauthoruk.

This has now been addressed and will be part of the next feature release.
