### ISSUE TITLE
Better Integration with Greenshot 

### ISSUE THREAD

**Issue by Ethanb00** [BookStackApp/BookStack#286]
When I take a screenshot using Greenshot, the copy to clipboard and paste feature does not work with BookStack.  I have to save the file and then upload.  It would fix a *very* minor inconvenience to fix that. Pasting from other sources works just fine.

**Comment by ssddanbrown** [comment]
Hi @Ethanb00, I've just tested this and could not replicate the issue. I directly copied to clipboard and also opened up a screenshot in the greenshot image editor and copied from there and both pasted fine.

I'm on windows10 & using chrome. Can you confirm your OS and browser?

**Comment by Ethanb00** [comment]
Thanks for getting back to me @ssddanbrown,

I should have clarified. I was using the 'Copy to Clipboard' option, and then trying to paste into the editor. 

I haven't had other problems with copying and pasting images directly into the editor from other sources (like visio).

**Comment by ssddanbrown** [comment]
Hi @Ethanb00, Thanks for confirming those details. Yeah, I was also using the 'Copy to Clipboard' option. Possibly only an issue on Windows 7 then? I might have to download a win7 VM to test this.

**Comment by Ethanb00** [comment]
Before you go through the trouble, let me try some test on my end. I'll let you know tomorrow what I find.

Thanks!

**Comment by Ethanb00** [comment]
I'm not having issues with this anymore. I think a greenshot update fixed the problem. thanks for looking into it.

**Comment by ssddanbrown** [comment]
@Ethanb00 Awesome, Thanks for confirming.
