### ISSUE TITLE
Upgrade from 0.31.6 to 21.05.3

### ISSUE THREAD

**Issue by chrisnewmanuk** [BookStackApp/BookStack#2861]
Failing to migrate:

 php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 81

   Symfony\Component\Debug\Exception\FatalErrorException  : Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

  at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:81
    77|      * {@inheritdoc}
    78|      *
    79|      * @return \PDOStatement
    80|      */
  > 81|     public function query()
    82|     {
    83|         $args = func_get_args();
    84|
    85|         try {

   Whoops\Exception\ErrorException  : Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

  at /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:81
    77|      * {@inheritdoc}
    78|      *
    79|      * @return \PDOStatement
    80|      */
  > 81|     public function query()
    82|     {
    83|         $args = func_get_args();
    84|
    85|         try {

  Exception trace:

  1   Whoops\Run::handleError()
      /var/www/bookstack/vendor/filp/whoops/src/Whoops/Run.php:454

  2   Whoops\Run::handleShutdown()
      [internal]:0

**Additional context**
PHP 7.4
Ubunut 18LTS

**Comment by ssddanbrown** [comment]
Hi @chrisnewmanuk,
Did you receive any errors when running the `composer install` step or does that all work without error? 

Otherwise, Could you provide the complete output of both `php -v` and `composer -V`?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
