### ISSUE TITLE
Call to a member function bind() on null

### ISSUE THREAD

**Issue by mtrayn01** [BookStackApp/BookStack#2862]
**Describe the bug**
Apache access logs record error code 500 several times per day which gets picked up in my website monitoring tools.

Website crawlers are looking for image files that no longer exist, and that results in the page "An error occurred" instead of displaying a 404 error. When I enable APP_DEBUG, it shows:

Symfony\Component\Debug\Exception\FatalThrowableError
Call to a member function bind() on null

Illuminate\Support\HigherOrderTapProxy::__call
vendor/laravel/framework/src/Illuminate/Support/HigherOrderTapProxy.php:34

**Steps To Reproduce**
1. input a URL for an image file that does not exist such as 
http://localhost/uploads/images/gallery/2020-07-Jul/scaled-840-0/Hv00Bx6vSa7h2bUx-Membership---Pay-by-invoice.png

**Expected behavior**
404 error should be displayed

**Screenshots**
<img width="877" alt="Screen Shot 2021-07-29 at 1 46 30 PM" src="https://user-images.githubusercontent.com/86567740/127563595-16f1e040-226d-4c67-af35-a5a7c742f85f.png">
<img width="1224" alt="Screen Shot 2021-07-29 at 1 46 42 PM" src="https://user-images.githubusercontent.com/86567740/127563597-8c0c6f4b-b0af-4268-95d0-5016cdeb81d6.png">

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.31.6 - 
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Hi @mtrayn01,
This should have been already addressed since it was raised in issue #2696, the fix of which was included in [v21.04.4](https://github.com/BookStackApp/BookStack/releases/tag/v21.04.4). I'll therefore close this off but if you continue to receive errors after upgrading to the latest BookStack version let me know and I'll close this off.

**Comment by mtrayn01** [comment]
@ssddanbrown - Thanks - this fixed the issue. I was confused with version numbers as it looks like they changed format.
