### ISSUE TITLE
Problems displaying users in audit log

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#2863]
**Describe the bug**
In the audit log, although I can search for a user, I cannot select them to view their audit trail - I can only see the audit trail for users who are visible in the dropdown list (20 users). When I click on the user name I have searched for, the user name reverts to 'No user selected', or the last user selected that was in the dropdown list

**Steps To Reproduce**
1. Go to Settings', 'Audit Log'
2. Set an event filter
3. Click on 'User'
4. Type user name in search box
5. Click on desired user name
6. See error

**Expected behavior**
That when I search for a user it should allow me to select them (even if they aren't in the default dropdown list) and see their audit trail.

**Screenshots**
User selected from dropdown (ok):
![image](https://user-images.githubusercontent.com/57015243/127627904-5d8cb8a2-6825-4777-8306-b347546a48b5.png)

Search for user:
![image](https://user-images.githubusercontent.com/57015243/127628059-d645a80d-91b1-45e9-95a5-a49401316b07.png)

Click user name (returns to no user or last selected user):
![image](https://user-images.githubusercontent.com/57015243/127628314-cff97b4e-cfd7-473b-8e7c-c69091193e40.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.05.3 
 - PHP Version: 8.0.8
 - Hosting Method (Nginx/Apache/Docker):  Apache
 - Linux: Ubuntu 20.04.2 LTS

**Additional context**
The 20 users in the dropdown list are the LAST 20 users in the application (in this case names beginning Z to N).

**Comment by techauthoruk** [comment]
The more I look at this issue, the more I think the issue is that the audit log search is limited to the 20 users displayed in the dropdown - @ssddanbrown any thoughts on this? Is this something that can be resolved by end user or does it need back end code changes?

This is probably the most useful tool I have as an admin - particularly when users say 'I can't find the information.....' and then you discover they haven't logged in for 6 months!

**Comment by ssddanbrown** [comment]
Hi @techauthoruk,
There was some sketchy behaviour here, where the user search would interfere with the user selection.

I've just applied a patch as part of v21.05.4 to address this. After upgrading, can you let me know if that solves the issue for you also?

**Comment by techauthoruk** [comment]
Hello @ssddanbrown 

That seems to have fixed the problem. Althoght the dropdown still only dispays 20 users (z - a), entering a user name now does return the audit log for that user.

Good job - problem solved! I guess you can close this down now.

Thank you!

**Comment by ssddanbrown** [comment]
@techauthoruk Awesome, Thanks for confirming! The initial 20 is just to limit the initial load amount, Might have to think about some ux improvements around that if it's found to be an issue again in the future.
