### ISSUE TITLE
Backlinks / "pages that link to here"

### ISSUE THREAD

**Issue by leonth** [BookStackApp/BookStack#2864]
**Describe the feature you'd like**
Backlinks: a page can show the list of pages that link to (or redirect to) the current page. This is a common feature in wiki software.

**Describe the benefits this feature would bring to BookStack users**
For knowledge base use-cases, this feature will help recall and discovery, because pages that link to a target page are usually somewhat relevant to the target page. 

[There's an explanation on how a similar feature in Notion helps someone.](https://www.samuelthomasdavies.com/notion-backlinks/) 

**Additional context**

References:
* https://www.notion.so/guides/creating-links-and-backlinks
* https://en.wikipedia.org/wiki/Help:What_links_here

**Comment by leonth** [comment]
I put a little bit of thought about this today. Disclaimer: I'm a very recent user of BookStack.

I attempted to abuse the tagging system to create this functionality. For example, I could create the tag `linksTo=99` in all pages that link to the page ID 99. Then, a user can use the search functionality, searching with `/search?term=[linksTo%3D99]` to find all backlinks to page ID 99.

Theoretically, this could be run as cron script which scans recent pages and updates the pages with the tags as the links are discovered. However I couldn't implement this because I couldn't find a way to get the page ID from links - or at least the available API does not have that functionality at the moment. If this API is available, or can be easily be made available via the Logical Theme system then this can work.

**Comment by leonth** [comment]
Related to #1969

**Comment by robertfshort** [comment]
+1 for this feature

**Comment by ssddanbrown** [comment]
@robertfshort Please use the :+1: reaction on top-level issue posts instead of comments.

**Comment by ssddanbrown** [comment]
With the work done in #3656, this feature will be part of the next feature release. A link will be available under "details" with a count of references to the current item (Available on pages/chapters/books/shelves). Clicking that will provide a view of pages that reference the item:

![Screenshot 2022-09-05 at 12-44-15 BookStack](https://user-images.githubusercontent.com/8343178/188441687-d1bf9dda-dda8-4029-b3a0-cbeaa966dfe2.png)

Note: You'll need to run a maintenance action or command to update this reference index for old pages, this will be detailed in release notes for the next version.
