### ISSUE TITLE
Editor callouts not working in some pages

### ISSUE THREAD

**Issue by diegopau** [BookStackApp/BookStack#2865]
**Describe the bug**
We are having an issue that only affects some pages in which when applying one of the 4 callout formatting either nothing happens, or it changes the formatting but not in the desired way. When trying in one of those pages I see that some areas do allow the callouts to be applied but others not.

**Steps To Reproduce**
Open an "affected" page, edit it, highlight some text, try to apply a call out.
Page that works: https://wiki.oceanbuilders.com/books/open-source-projects/page/marine-navigation
Page that has issues: https://wiki.oceanbuilders.com/books/open-source-projects/page/ocean-monitoring-station

**Expected behavior**
The callouts should always be applied to the selected paragraph.

**Screenshots**
The issue can be seen clearly in this video http://files.oceanbuilders.com/f/0d7fb53d72134b61b55d/

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.05.3
 - PHP Version: 8.0.8
 - Hosting Method (Nginx/Apache/Docker): Apache

Please let me know what other information might help!
Important: I also tried deleting all the custom HMTL Head Content from Settings, the problem was still there.

**Comment by ssddanbrown** [comment]
Hi @diegopau,
Thanks for providing examples and a video for this, makes it much easier it look into & understand.

Have just been testing this. From what I can see, this comes down to specific blocks of content.
Looking at the content of the page that has issues, the content structure behind the scenes is much more complex. I get the feeling this has been copied in from another source. Usually the editor will attempt to clean-up the content on entry but I think it's had trouble here. 

This then leads to trouble when a callout is attempted to be added. Note, This doesn't break callouts on the whole page, just within that area; If you create a new section (After a couple of fresh newlines) at the bottom or the top you'll likely be able to add a callout in these areas. You can kind of fix broken areas by copying the content and pasting in as plain text (For me on FireFox/Linux that's via Ctrl+Shift+V).

**Comment by diegopau** [comment]
Thanks, that was indeed the issue. I tried in that affected page to copy the text, deleting it and pasting it as plain text and now callouts work in that page.

Thanks @ssddanbrown . I am closing the issue since this doesn't seem to need any action on BookStack development.
