### ISSUE TITLE
Href linking

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [BookStackApp/BookStack#2867]
**Describe the feature you'd like**
To link to specific parts of the page using headers. Like how Wikipedia allows linking to a specific part:
https://en.wikipedia.org/wiki/Bubonic_plague#Diagnosis

**Describe the benefits this feature would bring to BookStack users**
Could link to specific sections of internal wikis. Also a prerequisite for tables of contents inside a large page.

**Comment by ssddanbrown** [comment]
Hi @Adrian-at-CrimsonAuzre,
Each section is given a unique ID on save based on content, and when viewing a page highlighting text within a section should show a helper to provide a link to that section. See the gif on this page: https://www.bookstackapp.com/docs/user/content-permalinks/

**Comment by Adrian-at-CrimsonAuzre** [comment]
No idea how I didn't notice that. While I'm at it is there any way to embed an automatic table of contents?

**Comment by ssddanbrown** [comment]
@Adrian-at-CrimsonAuzre Not really I'm afraid, since it would run double-duty with the auto-generated one in the top-right when viewing a page.

**Comment by Adrian-at-CrimsonAuzre** [comment]
I meant more like the one you see on Wikipedia or can set in word. Where the level of header defines parent/child relationships within the page. If there isn't anything built in I was going to just use the text links to the headers within the page and have a info callout or something and manually link to them.

**Comment by ssddanbrown** [comment]
@Adrian-at-CrimsonAuzre Nothing built-in other than the mentioned auto-generated one. That one does indent depending on header level though, relative to largest header used within the document.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Ah, is there any way I can print the outline?
