### ISSUE TITLE
Add VB.net codemirror option

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#2869]
**Describe the feature you'd like**
Could you add support for VB.NET into the next release?

**Describe the benefits this feature would bring to BookStack users**
For those of us who have to document VB and VB.NET code, this would be of great benefit.

Thanks!

**Comment by ssddanbrown** [comment]
Hi @techauthoruk,
I've just snuck this into v21.05.4 which I've just published. After upgrading you should be able to select the VB.NET option to get the desired highlighting.

**Comment by techauthoruk** [comment]
@ssddanbrown All works fine Dan - thank you for this (makes my life much easier!)
