### ISSUE TITLE
Update error, cannot access any books

### ISSUE THREAD

**Issue by m4ntic0r** [BookStackApp/BookStack#287]
Tried update from 0.13.1 to 0.14.1, and i get this error when i click on a site link or book link:

"Whoops, looks like something went wrong."

Install Log:
http://pastebin.com/URCu2Cb7

Tried it twice.. had to restore my backups an now 0.13.1 is running again.

**Comment by lommes** [comment]
Can you supply some more info from laravels log file which can be found in storage/logs/laravel.log

**Comment by m4ntic0r** [comment]
After update i can login, go to settings etc. without a problem.
But if i try to click on a book or site link i get the error.

storage/logs/laravel.log shows this for every click on a link
http://pastebin.com/S4gMaz3m

**Comment by ssddanbrown** [comment]
Hi @m4ntic0r, I could not replicate this issue but I have deployed a new release, v0.14.2, with a hopeful fix. If that does not fix the issue just let me know and I'll re-open this.

**Comment by m4ntic0r** [comment]
Hi @ssddanbrown, i can confirm that 0.14.2 works. I updated and everything seems to work. Thanks for fixing this issue.
