### ISSUE TITLE
Table width overlaps info panel (right panel)

### ISSUE THREAD

**Issue by florian-obradovic** [BookStackApp/BookStack#2870]
Hello.

Thx a lot for the great work. I migrated all my personal documentation from Confluence to Bookstack!

**Issue:**
If a table has too many columns, the rendered table overlaps the info panel:
![CleanShot 2021-08-04 at 14 40 29](https://user-images.githubusercontent.com/57985125/128183176-42d3d368-bd49-46ea-b9af-afcff91f6e2e.png)

Version: BookStack v21.05.3

Browsers: current Google Chrome and Safari

Best regards, Flo.

**Comment by ssddanbrown** [comment]
Thanks for reporting @florian-obradovic,
This has already been raised as part of #2126 so I'll therefore close this off as a duplicate.

**Comment by florian-obradovic** [comment]
Thx @ssddanbrown - searched for existing issues but didn't find #2126 ;)
Thanks a lot for the good work!
