### ISSUE TITLE
Error with embedded video player in Safari

### ISSUE THREAD

**Issue by Telianedward** [BookStackApp/BookStack#2878]
The built-in safari video player does not understand the links of attached files, such as "attachments/123", and does not play the video, safari cant get first bytes of video

in Google Chrome all work fine

**Comment by ssddanbrown** [comment]
Hi @Telianedward,
Attachments links are not currently designed to provide video support. There are many complications with video support, including file format & codec support, and serving files in a stream-capable way. Attachments are served via BookStack for permission checking but this will complicate in-browser streaming.

I'd advise using a proper video hosting service for well-supported streaming.
