### ISSUE TITLE
[Feature Request] Add a "My Drafts" section to the user profile page

### ISSUE THREAD

**Issue by patrickcage** [BookStackApp/BookStack#2881]
**Describe the feature you'd like**
I would like to request a section be added to the 'View Profile' page for displaying any Drafts created by that user.
This section could perhaps be hidden if no drafts exist but display if there are 1 or more drafts.

**Describe the benefits this feature would bring to BookStack users**
I am aware there is an existing "My Recent Drafts" section on the "Default" home page but for some users I would like to default to the "Books" page which would effectively hide any draft pages (they could search but some users can be very obtuse).
Having a section under their profile page would make it very easy to pick up and continue any draft pages regardless of what page the land on when logging in.

**Comment by ssddanbrown** [comment]
Hi @patrickcage,

> I would like to default to the "Books" page which would effectively hide any draft pages

No matter the configured homepage option, a user's drafts should still show when on the home view. If the "Books" homepage option is chosen the drafts would typically be located in the sidebar.

**Comment by patrickcage** [comment]
@ssddanbrown ,
I do apologise, I have checked and that absolutely is the case.
Please feel free to close this.

**Comment by ssddanbrown** [comment]
@patrickcage No worries! will therefore close this.
