### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [BookStackApp/BookStack#2882]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ssddanbrown** [comment]
Hi @zidingz,
Security details can be found in the project readme: https://github.com/BookStackApp/BookStack#-security

**Comment by ssddanbrown** [comment]
Will now close this since the issue was addressed. Thanks for helping make BookStack more secure @zidingz
