### ISSUE TITLE
Error uploading cover image to book

### ISSUE THREAD

**Issue by ShowMeIT** [BookStackApp/BookStack#2883]
Hi,
I am getting the attached error when I try to add a cover image to my bookstack instance.
I'm running v21.05.3 on ubuntu 21.04.

I get the same error when I try a different image and when I try a different Book or Shelf.

Are you able to point me in the right direction as to what might be the issue please?

Thanks,
Andrew
![2021-08-14 14_46_55-Clipboard](https://user-images.githubusercontent.com/51915383/129434418-f245ca27-5881-40e0-9299-50e8efa9d01b.png)

**Comment by ssddanbrown** [comment]
Hi @ShowMeIT,
Have you check file/folder permissions for the target location, as indicated in the error message?

Let me know if you'd need further assistance to check that or to know how to address. I'll just need to know what webserver you're using.

**Comment by ShowMeIT** [comment]
Thank you for your response, 

Some help to check would be great please, using apache - book stack installed in /var/www/bookstack

Thank you,
Andrew

P.S - Awesome software!!

**Comment by ssddanbrown** [comment]
@ShowMeIT  The below commands should update permissions so that Apache has the right permissions:

```bash
sudo chown -R www-data:www-data /var/www/bookstack/storage /var/www/bookstack/public/uploads /var/www/bookstack/bootstrap/cache
```

**Comment by ShowMeIT** [comment]
Thanks @ssddanbrown, works perfectly now!

Thank you for your help.
