### ISSUE TITLE
Attachments in Sidebar

### ISSUE THREAD

**Issue by DarkSky77** [BookStackApp/BookStack#2885]
**Describe the feature you'd like**
When you are in "user-mode"/readonly there is no way possible to view the attachet files/links

**Describe the benefits this feature would bring to BookStack users**
the attachet file/links are accessable for readonly user.
for example there's a manual for a form, thats attached

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @DarkSky77,
I'm not sure I understand this request.

Attachments should already be visible towards the top of the left-hand sidebar for any users that have access to view the page they're attached to.

Are you not able to see this? If not, could you provide a full-screen screenshot of viewing a BookStack page after adding an attachment?

**Comment by DarkSky77** [comment]
sorry. i looked on the right side, not the left. ; expectet it where the sidepanel was.

sorry :)

**Comment by ssddanbrown** [comment]
No worries, Will therefore close this off.
