### ISSUE TITLE
Error uploading files more then 150mb

### ISSUE THREAD

**Issue by dividerbeam** [BookStackApp/BookStack#2886]
![image](https://user-images.githubusercontent.com/52495131/129556184-1837354e-fcd7-4556-b08b-5bd5c5c9286f.png)

files uploading run with connection to Minio s3

all server settings added:
php:
post_max_size
upload_max_filesize
memory_limit
nginx:
client_max_body_size
client_body_timeout
js:
window.uploadTimeout
window.uploadLimit

**Comment by dividerbeam** [comment]
![image](https://user-images.githubusercontent.com/52495131/129560543-9357305a-cdee-4d57-a068-ddee3163089b.png)

**Comment by ssddanbrown** [comment]
Hi @dividerbeam,
Would you be able to find the log file described within this page: https://www.bookstackapp.com/docs/admin/debugging/?

Once found, could you find the latest error logged upon causing that error? That should provide more detail as to what is failing here.

**Comment by dividerbeam** [comment]
![image](https://user-images.githubusercontent.com/52495131/129604825-36f5276e-29b8-4392-8e8d-8d82f0d31668.png)

but i cant change memory_limit, my .ini file in volumes being overwritten on container start

`version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    volumes:
      - /docs:/config
      - /home/artel/mydocs:/var/www/html
      - ./php-local.ini:/etc/php7/conf.d/php-local.ini
    environment:
        ....`

php-local.ini not applied after "docker-compose up", moreover, the file from the container replaces the local file

**Comment by ssddanbrown** [comment]
@dividerbeam Based upon the following lines:
https://github.com/linuxserver/docker-bookstack/blob/3aec0b9e4974eed807f2f363c250b8e62abadf01/root/etc/cont-init.d/50-config#L84-L85

I would assume that the linuxserver/bookstack image is already providing a `php.ini` at `config/php/php-local.ini` to provide customizations, hence you might be fighting that. Based on your volumes, do you have a `/docs/php/php-local.ini` file? and if so have you tried adding your customizations there?

**Comment by dividerbeam** [comment]
> @dividerbeam На основе следующих строк:
> https://github.com/linuxserver/docker-bookstack/blob/3aec0b9e4974eed807f2f363c250b8e62abadf01/root/etc/cont-init.d/50-config#L84-L85
> 
> Я бы предположил, что образ linuxserver / bookstack уже предоставляет `php.ini`at `config/php/php-local.ini`для предоставления настроек, поэтому вы можете бороться с этим. Судя по вашим объемам, у вас есть `/docs/php/php-local.ini`файл? и если да, то пробовали ли вы добавить туда свои настройки?

so that's where it comes from! I didn't know that the php settings are there, thank you

**Comment by dividerbeam** [comment]
Trying to upload 3.3gb zip archive with memory_limit = 16G :

![image](https://user-images.githubusercontent.com/52495131/129676760-19146e02-25c1-49bc-b3a7-bb01e398b704.png)

how much memory is needed?

**Comment by ssddanbrown** [comment]
@dividerbeam Not sure, a multiple of the uploaded size is somewhat expected, There has not been a massive amount of optimization for massive files, since that's not generally a large intent for BookStack.

**Comment by ssddanbrown** [comment]
A significant collection of improvements to memory handling have been made for uploaded/downloaded files within PR #3365. This will be part of the next feature release so I'll therefore close this off.
Further similar scenarios can be re-opened under new issues if not addressed by the next feature release.
