### ISSUE TITLE
HTML look fixing

### ISSUE THREAD

**Issue by wrkilu** [BookStackApp/BookStack#2889]
Hi,
Bookstack looks very promising however it has let say two important negatives in look.
Concrete question: how to expand center main field for content ? and how to delete first lines of page in pages list ?
![obraz](https://user-images.githubusercontent.com/36470632/129791053-517b7d30-8247-44cd-b59e-578a7a4fc2bb.png)

Regards.
wrkilu

**Comment by ssddanbrown** [comment]
Hi @wrkilu,
If you're handy with CSS you can add some overrides via the "Custom HTML Head Content setting". Note, this isn't officially supported though. Some suggestions for the width part are suggested in #1757 if you needed some hints.

**Comment by wrkilu** [comment]
All right not bad tip :)
So it remains second question: how to remove first lines of page in pages list ?

**Comment by ssddanbrown** [comment]
Sorry for the late reply. The following in the "Custom HTML Head Content" would remove the lines cross out in your screenshot:

```html
<style>
	.book-content .entity-item-snippet {
		display: none;
	}
</style>
```

Since both requested points have been addressed I'll close this off.
