### ISSUE TITLE
Password Reset Option Throws Error

### ISSUE THREAD

**Issue by eferreira2** [BookStackApp/BookStack#2895]
My user's get error messages when attempting to reset their passwords. I'm on Ubuntu 20.04 LTS and Bookstack v0.31.7

Swift_TransportException
Expected response code 250 but got code "554", with message "554 5.2.252 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:0A00B782, 1.36674:01000000, 1.61250:00000000, 1.45378:02000000, 1.44866:00000000, 1.36674:7A000000, 1.61250:00000000, 1.45378:05000000, 1.44866:00140000, 1.36674:0A000000, 1.61250:00000000, 1.45378:16000000, 1.44866:A1430000, 1.36674:0E000000, 1.61250:00000000, 1.45378:BA430000, 1.44866:26010000, 16.55847:061A0000, 17.43559:0000000030020000000000000000000000000000, 20.52176:140F54911800F01F03000136, 20.50032:140F54918817F01F07000000, 0.35180:1F000130, 255.23226:D51F0000, 255.27962:7A000000, 255.27962:0A000000, 255.27962:0E000000, 255.31418:21000000, 0.35250:1F001336, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:4E000000, 1.36674:32000000, 1.61250:00000000, 1.45378:53000000, 1.44866:01000000, 16.55847:BA000000, 17.43559:0000000088030000000000000100000000000000, 20.52176:140F54911800101068000000, 20.50032:140F54918817000050200000, 0.35180:6D000000, 255.23226:0A001380, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:B2200000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:E3200000, 0.38698:46000000, 1.41134:46000000, 0.37692:86000000, 0.37948:86000000, 5.33852:00000000534D545000000000, 7.36354:010000000000010986000000, 4.56248:DC040000, 7.40748:010000000000010B86000000, 7.57132:000000000000000032322D32, 1.63016:32000000, 4.39640:DC040000, 8.45434:5EC1E3D3BBBCC045A15B1D7B8AA38177612D6236, 1.46798:04000000, 5.10786:0000000031352E32302E343433362E3032343A504830505231314D42353132383A31666364646266612D623637372D346365342D393333342D3564653238666232323964343A323737343030003333342D356465, 7.51330:6E8A21AB0E67D90837343030, 0.39570:00000000, 1.55954:0A000000, 0.49266:02000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:7A000000, 1.56562:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 255.1750:BD000000, 255.31418:03003866, 0.22753:E6220000, 255.21817:DC040000, 0.64418:03000336, 4.39842:DC040000, 0.41586:C7000000, 4.60547:DC040000, 0.21966:F0220000, 4.30158:DC040000 [Hostname=PH0PR11MB5128.namprd11.prod.outlook.com] "

Swift_Transport_AbstractSmtpTransport::assertResponseCode
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459

    protected function assertResponseCode($response, $wanted)

    {

        if (!$response) {

            $this->throwException(new Swift_TransportException('Expected response code '.implode('/', $wanted).' but got an empty response'));

        }

 

        list($code) = sscanf($response, '%3d');

        $valid = (empty($wanted) || \in_array($code, $wanted));

 

        if ($evt = $this->eventDispatcher->createResponseEvent($this, $response,

            $valid)) {

            $this->eventDispatcher->dispatchEvent($evt, 'responseReceived');

        }

 

        if (!$valid) {

            $this->throwException(new Swift_TransportException('Expected response code '.implode('/', $wanted).' but got code "'.$code.'", with message "'.$response.'"', $code));

        }

    }

 

    /** Get an entire multi-line response using its sequence number */

    protected function getFullResponse($seq)

    {

        $response = '';

        try {

            do {

                $line = $this->buffer->readLine($seq);

                $response .= $line;

            } while (null !== $line && false !== $line && ' ' != $line[3]);

        } catch (Swift_TransportException $e) {

            $this->throwException($e);

        } catch (Swift_IoException $e) {

**Comment by eferreira2** [comment]
This appears to be something specific to O365 SMTP email send. I'm investigating further.

**Comment by eferreira2** [comment]
Problem resolved. I needed to add the MAIL_FROM field and set it to the same email address that was being used for account access.

**Comment by ssddanbrown** [comment]
@eferreira2 Thanks for confirming, Will therefore close this off.
