### ISSUE TITLE
Code indentation

### ISSUE THREAD

**Issue by unknowndomain** [BookStackApp/BookStack#290]
### For Bug Reports

* BookStack Version: v0.13.1
* PHP Version: 5.6.28
* MySQL Version: Unknown

There is a indentation problem in the first line of all code blocks:

![screen shot 2017-01-30 at 14 47 05](https://cloud.githubusercontent.com/assets/147143/22427528/7a780484-e6fb-11e6-8660-d0b1393f11b3.png)

You can see the first line #define is indented slightly.

**Comment by ssddanbrown** [comment]
Hi @unknowndomain, Thanks for highlighting this issue. This issue looks to be the same as #264. Please could you update BookStack to the latest version and check if the issue persists?

**Comment by unknowndomain** [comment]
This appears to be resolved.

**Comment by ssddanbrown** [comment]
@unknowndomain Glad to hear it. I will close this issue.
