### ISSUE TITLE
Ability to rename organization elements "shelves", "books" and "pages"

### ISSUE THREAD

**Issue by towerplease** [BookStackApp/BookStack#2901]
As i already saw in multiple instances. It would be nice if there is a way to easily change the default organization naming from shelves/books to something custom.

In my case i would like to change it to "departments", "products" and "articles".

I guess this would be a very nice feature to have, so you can have your BookStackApp more customized to individual needs.

Thank you in advance!

**Comment by ssddanbrown** [comment]
Hi @towerplease,
It may be worth reading through #406 which was a previous request for such a feature.

**Comment by ssddanbrown** [comment]
Since I feel this has been explain enough within #406, with potential workarounds via the visual theme system, I'm going to go ahead and close this off.
