### ISSUE TITLE
New page order not saving after updating to v21.08

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#2905]
**Describe the bug**
Sorting pages within a book - new order isn't saved

**Steps To Reproduce**
1. Open any book or chapter
2. Select 'Sort'
3. Reorder the pages
4. Click 'Save new order'
5. Dialog says page order is saved
6. See error

**Expected behavior**
New page order should be saved

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 21.08
 - PHP Version: 8.0.3
 - Hosting Method (Nginx/Apache/Docker): Apache on Ubuntu 20.04 LTS

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for reporting once again @techauthoruk and sorry for this being an issue. Has now been patched with a test to cover, To be part of the next patch release.

**Comment by T3-RnD** [comment]
hello @ssddanbrown

I am having the same issue with  v22.06.1, is there any solution for it

BTW I have the same version on my local machine its working fine, but when it comes to the production it's not capturing the changes, or the page priority field is not updated in the database even though I am getting a success message

**Comment by ssddanbrown** [comment]
@T3-RnD Are you able to reproduce this on our demo instance?

https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site

**Comment by T3-RnD** [comment]
I tried now on your demo, and it's working fine 

similar to my local machine the order of the page is being updated with no issues

the issue is only on my app (server-side: its PHP 7.4 and its Apache server), is there any suggestion to solve it, the strange thing is that I didn't touch this page

**Comment by ssddanbrown** [comment]
@T3-RnD Please could you open a new support issue here on GitHub, so that you can detail out your environment (Including operating system and install method) since it's likely a different fundamental issue cause than that of this issue report.
