### ISSUE TITLE
Edit Profile not available after update to 21.08-  An Error Occurred (An unknown error occurred)

### ISSUE THREAD

**Issue by eddeta** [BookStackApp/BookStack#2907]
After installing the newest update according to your guide 
https://www.bookstackapp.com/docs/admin/updates/
some pages are not available anymore 
Edit profile - An Error Occurred
After login - An Error Occurred (only browsers that have already logged in can access the page)
everything else seems to be working

**Comment by ssddanbrown** [comment]
Hi @eddeta,
Did you get any errors or warnings when running the update commands at all?

**Comment by eddeta** [comment]
Hi,
thanks for your answer. I had two errors after installing composer and running the command:
sudo git pull origin release && composer install --no-dev && php artisan migrate
here are the last few lines of the output:
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 5 installs, 21 updates, 0 removals
  - **Updating aws/aws-sdk-php (3.187.2 => 3.191.8):     Update failed (Could not delete /var/www/bookstack/vendor/aws/aws-sdk-php/src/IoTThingsGraph/Exception/IoTThingsGraphException.php: )**
    Would you like to try reinstalling the package instead [yes]? yes
  - Removing aws/aws-sdk-php (3.187.2)

In Filesystem.php line 217:
                                                                                                                        
  **Could not delete /var/www/bookstack/vendor/aws/aws-sdk-php/src/IoTThingsGraph/Exception/IoTThingsGraphException.php:**  

Any idea how to proceed?
I found that php7-session might be a dependency that I tried installing but didn't manage to find how

**Comment by ssddanbrown** [comment]
@eddeta This is likely a permissions issue, You may need to add `sudo` before the `composer install` part. In your example above:

> sudo git pull origin release && composer install --no-dev && php artisan migrate

**Comment by ashe400** [comment]
@eddeta if sudo doesn't work make sure your account has proper permissions to the /vendor/ directory and subdirectories. In my case there were a handful of files spread across various directories (symfony, composer to name a few) under /vendor/ that the installer couldn't remove. I had to tweak this a bit in order to get it to do the upgrade properly.

**Comment by eddeta** [comment]
@ashe400 - thanks for the tip. I had to run:
I had to chown -R user:sudo /var/www/bookstack/vendor and just ran the installation command again with sudo and it ran!
thanks a lot for the help!

**Comment by ssddanbrown** [comment]
Hi @eddeta ,
Just to confirm, is your original issue now all resolved?

**Comment by eddeta** [comment]
yes :)
thanks a lot for your help!
