### ISSUE TITLE
Show the setup parameters when setting up a TOTP device (not only in QR code)

### ISSUE THREAD

**Issue by timholl** [BookStackApp/BookStack#2908]
First of all, I am very happy about the MFA-features added in the v21.08 release, thank you very much!

**Describe the feature you'd like**
Possibility to optionally show the contents embedded into the QR-Code when setting up a TOTP device.

**Describe the benefits this feature would bring to BookStack users**
Generating TOTP codes is not limited to mobile devices (I personally use KeePassXC to generate them on my computer).
I had to make a screenshot of the QR code and run ` zbarimg -q screenshot.png` on it, to extract the information I needed.

Optionally showing the setup parameters (secret, hash algorithm, digit count, time period) on the web page would very help people which do not use a mobile phone for generating TOTP codes.

**Additional context**
(none)

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @timholl. I've updated the view with a box containing the full URL that the QR code contains, which would include all the required parameters. 

![Screenshot from 2021-09-01 20-59-17](https://user-images.githubusercontent.com/8343178/131736005-a78faea2-f116-4a8b-bd28-7053ae8287fc.png)

This will be part of the next patch release.

**Comment by timholl** [comment]
Thank you, @ssddanbrown , very much appreciated!
