### ISSUE TITLE
Unable to send a mail when MAIL_PASSWORD includes '#'

### ISSUE THREAD

**Issue by mzch** [BookStackApp/BookStack#2910]
**Describe the bug**
When `MAIL_PASSWORD` includes `#`, Bookstack will fail to send a mail.

**Steps To Reproduce**
1. Set password including `#` to `MAIL_PASSWORD` in `.env`
2. Go to `Settings` -> `Maintenance`
3. Click `SEND TEST EMAIL`

**Expected behavior**
Send a mail successfully

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v21.0.8
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
When quoting password using single quotation mark `'`, Bookstack sends a mail successfully.

**Comment by ssddanbrown** [comment]
Hi @mzch,

This is known and applies to any of the `.env` values. We have a notice at the top of the file for this:
https://github.com/BookStackApp/BookStack/blob/master/.env.example#L6-L7

**Comment by mzch** [comment]
Oh, I missed it. Thans @ssddanbrown !
