### ISSUE TITLE
responsive videos

### ISSUE THREAD

**Issue by Haboubi92** [BookStackApp/BookStack#2911]
inserting videos (like YouTube) within bookstack pages doesn't have responsiveness
I currently assigning 300 pixels width to ensure sufficient viewing on mobiles

is there any custom HTML head content trick to enforce responsiveness?
for [H5P](https://h5p.org/) content I use this code 
`<script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8">`

**Comment by ssddanbrown** [comment]
Hi @Haboubi92,
There's a very new CSS property which could help here: `aspect-ratio`. It's very new so I've been waiting for it to be more standard and supported before including in any default styles, but should work in current FireFox or Chrome browsers. The custom HTML head content for youtube would look something like this:

```html
<style>
	iframe[src*="youtube.com"] {
		aspect-ratio: 16 / 9;
		width: 100%;
		height: auto;
	}
</style>
```

Sets all youtube embeds to be 16:9 (widescreen) aspect ratio.
Or if you want to target all embeds within page content to be the same:

```html
<style>
	.page-content iframe {
		aspect-ratio: 16 / 9;
		width: 100%;
		height: auto;
	}
</style>
```

**Comment by Haboubi92** [comment]
thanks @ssddanbrown ♥ ♥ ♥
