### ISSUE TITLE
Command "migrat" is ambiguous when updating to 21.08.1

### ISSUE THREAD

**Issue by binarydad** [BookStackApp/BookStack#2912]
When attempting to update my Ubuntu 18.04 version of v21.05.4 to v21.08.1 using the command `git pull origin release && composer install --no-dev && php artisan migrate` (sudo'ing each command), I get the following error:

![image](https://user-images.githubusercontent.com/1760607/131934430-b2093e33-43a9-4ed8-90da-242a6ba9dc73.png)

**Comment by watschi** [comment]
Looks like you executed `git pull origin release && composer install --no-dev && php artisan migrat` (missing the last "e" in migrate).
Are you sure you pasted the whole line?

**Comment by binarydad** [comment]
> 
> 
> Looks like you executed `git pull origin release && composer install --no-dev && php artisan migrat` (missing the last "e" in migrate).
> Are you sure you pasted the whole line?

Damnit...
