### ISSUE TITLE
Add option in .env to disable select content pop-up

### ISSUE THREAD

**Issue by jhrdt** [BookStackApp/BookStack#2918]
**Describe the feature you'd like**
Add a .env flag for disabling the select content pop-up.

**Describe the benefits this feature would bring to BookStack users**
This is a opinionated request, but the pop-up disturbs the UX for non IT users.

**Additional context**
If there is a CSS trick do it with a custom header, this would be also good option.

**Comment by ssddanbrown** [comment]
Hi @jhrdt,
Since I believe this is the first request for this feature I don't really want to introduce another option to control this minor feature.
You can add the following to the "Custom HTML Head Content" setting to disable it within the current release:

```html
<style>
	.pointer-container {
		display: none !important;
	}
</style>
```

**Comment by jhrdt** [comment]
Hi @ssddanbrown ,

thank you. Yes this works as intended. 

You are right, a feature flag for such a minor feature is not needed. The CSS snippet works fine.
