### ISSUE TITLE
FatalErrorException' with message 'Call to a member function getThumb() on null' in app/User.php:154

### ISSUE THREAD

**Issue by garethfoote** [BookStackApp/BookStack#292]
Hi there,

I'm experiencing a server error on a few pages on my Bookstack install. 

### Install details
* BookStack Version: v0.14.1 (release branch)
* PHP Version: 5.6.28
* MySQL Version: 5.0.11-dev 

### Problematic pages
http://p-i-c.net
http://p-i-c.net/settings/users
http://p-i-c.net/books/physical-computing

### Error
[2017-02-01 11:52:59] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getThumb() on null' in app/User.php:154

The pages that are not displaying error are those that *do not* attempt to display a thumbnail of a user. The error occurred first after a user tried to upload their avatar. 

Thanks in advance. Appreciate the efforts being put into Bookstack.

**Comment by ssddanbrown** [comment]
Hi @garethfoote, Sorry to hear your were having this issue. I could not replicate this issue but I have deployed a new release, v0.14.2, with a hopeful fix. If that does not fix the issue just let me know and I'll re-open this.

**Comment by garethfoote** [comment]
Hi @ssddanbrown - That did the job! Appreciate the swift response.
