### ISSUE TITLE
Forced htmlentities() encoding in custom css 'content: ">";'?

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#2923]
We injected some custom CSS code (in Settings > Custom HTML head content) to display an "north east arrow icon" ↗️ behind external links on BookStack pages, using the `content` property, code point `&#8599;`.

Since release 21.08.x BookStack is parsing the value behind `content`, and automatically re-encodes HTML entities, not only „high“ Unicode data points, but simply everything which supports HTML re-encoding, in particular also `§` towards `&sect;`.

The change in 21.08.x unfortunately breaks our icon hack.

Here our said CSS injection:

```
<style type="text/css">
  /* adds arrow icon to external links */
  a[href*="//"]:not([href*="our.bookstack.com"])::after { 
    content: "↗️";
    text-decoration: none;
    padding-left: 0.15em;
    color: #999;
  }
  a[href*="//"]:not([href*="our.bookstack.com"]):hover::after {
    text-decoration: underline;
    text-decoration-color: red;
  }
</style>
<script>
  /* sets the target attribute to '_blank' if link doesn't begin with '#' or 'https://our.bookstack.com' */
  window.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.page-content a[href]').forEach(function(el, x, y) {
      if (el.getAttribute('href') && 
          (!el.getAttribute('href').startsWith('#')) &&
          (!el.getAttribute('href').startsWith('https://our.bookstack.com'))) {
        el.setAttribute('target', '_blank'); 
      }
    });
  });
</script>
```

**Comment by ssddanbrown** [comment]
Hi @Wookbert, Thanks for reporting and sorry for this.
Just so I can be sure, could you confirm the exact version you're on which has this issue?

I made some more significant changes to Custom HTML Head content within v21.08.2 which could have caused this but if you happen to be on v21.08 or v21.08.1 it'll be something unexpected.

**Comment by Wookbert** [comment]
I'm seeing this issue now on v21.08.2. Would have to ask my partner if it appeared in earlier versions.

**Comment by ssddanbrown** [comment]
@Wookbert Thanks, That's all I need. Pretty sure it'd be a v21.08.2 change that's caused this but wanted to confirm just in case I was jumping to assumptions.

**Comment by Wookbert** [comment]
Just learned that we went from 21.05.4 straight to 21.08.2, and skipped the in-betweens.

**Comment by ssddanbrown** [comment]
Just applied ef459ca4c45bd2450ecd5d67a4d73c07f836ab25, 
Will be part of the next patch release that should be released shortly. 

Thanks again for raising @Wookbert.

**Comment by Wookbert** [comment]
Now that was quick. The icons are back. Thanks, mate!

![image](https://user-images.githubusercontent.com/3104762/132993938-aa9a1b7e-e888-4a7c-a96b-e8045061bc69.jpeg)
