### ISSUE TITLE
Please support STARTTLS email encryption

### ISSUE THREAD

**Issue by mike12806** [BookStackApp/BookStack#2924]
Hi - as most email providers (with a secure setup, 2FA, etc.) require STARTTLS, I am unable to configure a bookstack email provider without getting an error that BookStack is not using STARTTLS (https://sendgrid.com/blog/what-is-starttls/)

Can you please add support for STARTTLS email encryption pattern?

**Comment by mike12806** [comment]
![image](https://user-images.githubusercontent.com/80599490/133013196-ac94dba2-6caa-4fa6-b0c2-4a993a7f5f39.png)

**Comment by ssddanbrown** [comment]
Hi @mike12806,
Are you using the following `.env` options at all?

```bash
MAIL_PORT=587
MAIL_ENCRYPTION=tls
```

If not, could you describe the ESP and configuration you're attempting to use here?

**Comment by mike12806** [comment]
The above was with an Outlook.com email, but I'm also getting the same result with GMAIL (which i'd prefer to use anyways)

Here's my env variables in the docker stack (removed username, from name, password for security). I have 2FA on in my GMAIL account so i'm using an app-specific password for GMAIL 

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_ENCRYPTION=tls
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM=
MAIL_FROM_NAME=BookStack

**Comment by ssddanbrown** [comment]
@mike12806 Would you be able to post a screenshot of the error you get from gmail, as you've done above for the outlook setup?

**Comment by mike12806** [comment]
Ah - so just re-added GMAIL details and re-deployed with a new app specific password, and all seems to be working right now. Apologize for taking up your time!
