### ISSUE TITLE
QR code not detected on Dark Mode

### ISSUE THREAD

**Issue by moucho** [BookStackApp/BookStack#2925]
**Describe the bug**
I am not able to configure 2fa scanning the QR code on Dark Mode, it is not picked up by my apps (Authy/Bitwarden).
It works ok on Light Mode, or manually copying the link.

**Steps To Reproduce**
1. Go to 'Edit Profile' when on Dark Mode
2. Click on 'Multi-Factor Authentication -> Configure Methods -> Reconfigure (TOTP)'
3. It shows the QR but it is not detected when scanning

**Expected behavior**
I should be scanned correctly

**Screenshots**
No screenshots

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v21.08.3 
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Nginx (reverse proxy)+ Apache

**Additional context**
I'm guessing that it needs more contrast with the page background, if I do that it works.

**Comment by ssddanbrown** [comment]
Thanks @moucho for reporting. Now patched, to be part of the next patch release.
