### ISSUE TITLE
504 Gateway Time-out while log in

### ISSUE THREAD

**Issue by dividerbeam** [BookStackApp/BookStack#2927]
I am running Bookstack in proxmox VM with a connection via nginx, nginx configs was testing with nginx support, there are no errors there

https://user-images.githubusercontent.com/52495131/133124372-562b0484-fad2-4a4f-b9e3-98dd7af18cc6.mp4

**Comment by ssddanbrown** [comment]
Hi @dividerbeam,
I'm not sure how much I'd be able to help as this looks specific to your configuration and network.

From the video, it looks like the login may be working but the redirect after login is failing.
Something strange I noticed, is that the login redirect is served by a different nginx version than that which times out. I get the impression there are mulitple nginx instances involved. It'll be worth looking at the logs for both of these instances.

**Comment by dividerbeam** [comment]
> Hi @dividerbeam,
> I'm not sure how much I'd be able to help as this looks specific to your configuration and network.
> 
> From the video, it looks like the login may be working but the redirect after login is failing.
> Something strange I noticed, is that the login redirect is served by a different nginx version than that which times out. I get the impression there are mulitple nginx instances involved. It'll be worth looking at the logs for both of these instances.

where did you see different versions of nginx? now I seem to have only 1 nginx

did bookstack have own nginx?

**Comment by ssddanbrown** [comment]
> where did you see different versions of nginx? now I seem to have only 1 nginx

At about 49 seconds in the video it showss nginx 1.18.0 in the response headers then at about 1:20 the error mesasge shows nginx 1.20.1. 

> did bookstack have own nginx?

No, not by default, unless you've used a container or similar that has its own nginx.

**Comment by dividerbeam** [comment]
i saw, tnx

**Comment by dividerbeam** [comment]
i use that bookstack https://hub.docker.com/r/linuxserver/bookstack, that's where this nginx 1.20.1 was found

**Comment by ssddanbrown** [comment]
Okay, So you have nginx as a reverse proxy to the linuxserver.io image. I'd imagine it's something between those two components at play here. Are you able to share the nginx reverse proxy config you're using?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
