### ISSUE TITLE
Debug mode won't turn off

### ISSUE THREAD

**Issue by mackcoding** [BookStackApp/BookStack#293]
* BookStack Version: BookStack v0.14.1 Save Settings
* PHP Version: 7.0.15-1~dotdeb+8.1
* MySQL Version: mysql  Ver 15.1 Distrib 10.1.21-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

##### Expected Behavior
Setting APP_DEBUG to false should turn off debug mode.

##### Actual Behavior
Setting APP_DEBUG to false does not turn off debug mode, it still shows at the bottom of the page. 

.env: 
# Environment
APP_ENV=production
APP_DEBUG=false

![image](https://cloud.githubusercontent.com/assets/10917563/22513830/5fe02ff4-e86b-11e6-93ec-a7a3f1e26ce1.png)

Am I missing something? Is there another option to get rid of the debug bar at the bottom of the page?

**Comment by ssddanbrown** [comment]
Hi @mackcoding,
I can only imagine that at some point the config has become cached, Thus caching your .env variables. Try running the following commands from the BookStack root dir:

```
php artisan config:clear
php artisan cache:clear
```

**Comment by mackcoding** [comment]
I did those commands multiple times, and of course, I tried it again and the debug bar is gone. Caching locally on browser maybe? Thank you for fast response!
