### ISSUE TITLE
Issue in audit log with Azure login

### ISSUE THREAD

**Issue by stefantrav** [BookStackApp/BookStack#2930]
I noticed that a some json output of azure login to be found in the audit log, that wasn't there before.... bug?
![image](https://user-images.githubusercontent.com/35542705/133228955-da7d6b04-c879-4a85-b174-5f136b1d5dbe.png)

**Comment by ssddanbrown** [comment]
Thanks for raising @stefantrav.

---

For dev reference, Likely due to incorrect second param here: https://github.com/BookStackApp/BookStack/blob/64785ed9da0d3bac61e4b3976da2e47a804335ec/app/Auth/Access/SocialAuthService.php#L144
Should add/update test to cover.

**Comment by ssddanbrown** [comment]
Thanks again @stefantrav, Now patched to be part of the next patch release.
