### ISSUE TITLE
Page Not Found for Okta login

### ISSUE THREAD

**Issue by tylerpixelguild** [BookStackApp/BookStack#2931]
**Describe the bug**

I get a "Page Not Found" response when clicking on the "Login with Okta" button from the login screen.

**Steps To Reproduce**

I followed the steps here to generate my app id and secret in okra, sensitive values replaced below:

https://www.bookstackapp.com/docs/admin/third-party-auth/#okta

I set these values in my .env file:
OKTA_APP_ID=0oXXXXXXXXXXXXX
OKTA_APP_SECRET=MP-XXXXXXXXXXXXXXXXXXXXXXXXX
OKTA_BASE_URL=myoktasubdomain
APP_URL=https://docs.mybookstackdomain.com

Then from the login screen click on the "Login with Okta" button and get a "Page Not Found" error when trying to resolve this URL format:

https://docs.mybookstackdomain.com/login/service/myoktasubdomain/oauth2/v1/authorize?client_id=0oXXXXXXXXXXXXX&redirect_uri=https%3A%2F%2Fdocs.mybookstackdomain.com%2Flogin%2Fservice%2Fokta%2Fcallback&scope=openid+profile+email&response_type=code&state=b1SAJxmhbY2QfQUWuZRY1LfeFzTKU4wxhURNFYBd

I also tried after running the following commands with no luck:
composer dump-autoload
php artisan config:clear
php artisan route:clear
php artisan view:clear
php artisan cache:clear
php artisan optimize:clear

**Expected behavior**
Authenticate me through Okta

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v21.05.3
 - PHP Version: PHP 7.4.21
 - Hosting Method (Nginx/Apache/Docker): Apache/2.4.29 (Ubuntu)

**Comment by ssddanbrown** [comment]
Hi @tylerpixelguild,
The `OKTA_BASE_URL` needs to be a valid base URL, not just the subdomain, So everything up to the okta.com part (If existing.)

**Comment by tylerpixelguild** [comment]
Doh! misread the docs. Thanks

**Comment by ssddanbrown** [comment]
No worries! Will therefore close.
