### ISSUE TITLE
Save error: did i reach the page size limit? 

### ISSUE THREAD

**Issue by pamMtz** [BookStackApp/BookStack#2933]
**Describe the bug**
I have created a page and filled it with all my documentation, saved the draft and when I save the page i got  the error:

![image](https://user-images.githubusercontent.com/90936672/133855390-0906f1c8-ed98-4aa6-afe2-008f778c4503.png)

Also while trying to export the page to pdf, got the same error. 

To have an idea of how much information is, this is how my scroll bar looks like:

![image](https://user-images.githubusercontent.com/90936672/133855957-6935650a-dd37-497b-8fcc-450970132604.png)

**Steps To Reproduce**
1. Create a page
2. Enter to edit the page
3. Fill it with lots of text and images 
3. Save the draft
4. Save the page
5. See error

**Expected behavior**
Save the page.
Export the page
 I don't know if there are any considerations about the size of the page. 

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 
BookStack v21.04.4
 - Hosting Method (Nginx/Apache/Docker):  Docker

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @pamMtz,

It could possibly be a size limit of some kind, potentially imposed by your web-server. That said, If the draft saves without issue I'd suspect it may be something else.

You can find details regarding debugging here:
https://www.bookstackapp.com/docs/admin/debugging/

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
