### ISSUE TITLE
Can't access from local network

### ISSUE THREAD

**Issue by Deicid** [BookStackApp/BookStack#2937]
Hi all!

I'm having trouble accessing Bookstack from a local network.

What has already been done:
1. I installed Bookstack in the Ubuntu 20.04 container from the script.
2. I configured NGINX to publish Bookstack to the internet. The code is attached: 
`server {`
           ` client_max_body_size 2500M;`
       `     listen                    443 ssl;`
         `   server_name               book.EXAMPLE.ru;`
       `     keepalive_timeout         70;`
       `     ssl_certificate           /etc/letsencrypt/live/book.EXAMPLE.ru/fullchain.pem;`
       `     ssl_certificate_key       /etc/letsencrypt/live/book.EXAMPLE.ru/privkey.pem;`
          `  ssl_protocols             TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE`
        `    ssl_ciphers               HIGH:!aNULL:!MD5;`
       `     ssl_prefer_server_ciphers on;`

            location / {
                proxy_pass http://192.168.20.152/;

`

What is the problem?
I configured the APP_URL=https://book.example.ru:3777 parameter in the .env file to make NGINX publishing work.
Bookstack is at 192.168.20.152, but I can't get to that address after publishing the site to NGINX.  When I go to 192.168.20.152, it redirects me to book.example.com:3777, and the site itself doesn't open (because I open it from 192.168.20.199).

I don't understand what the problem may be, and how to configure the site to be available on the Internet at https://book.example.ru:3777, and was also available on the local network at http://192.168.20.152/.

Currently the site is working via NGINX, but is not accessible via 192.168.20.152.

Thank you for your product, it is a very good product!

**Comment by ssddanbrown** [comment]
Hi @Deicid,
BookStack does not support being hosted on mulitple hosts/domains/IPs simultaneously. You'll need to choose a single address to use.

**Comment by Deicid** [comment]
It's very sad. But thank you for your product! It's the best I've seen on the software market.

**Comment by Deicid** [comment]
Can I create two versions of Bookstack and connect them to the same database? So that one version works on the local network and the other one on the public

**Comment by ssddanbrown** [comment]
@Deicid You kind of technically could but you'd still face issues with URL use within content. I'd suggest configuring the local network to allow use via the external domain.

**Comment by Deicid** [comment]
Dear @ssddanbrown 
Hello, I tried using Bookstack on one database for two instances. In general, everything works, but there is a problem with the pictures, they are displayed differently in different instances. 
Thanks for the tip on using external resources by routing to the local network, I think this can be implemented. But I would not want to do "such".

Nevertheless, thanks for your product. It is very easy to deploy and of very high quality!
