### ISSUE TITLE
Add attachments by API

### ISSUE THREAD

**Issue by geysonsantana** [BookStackApp/BookStack#2942]
It's possible attach a pdf document by API? I dont find any reference about this and it can be very useful for create a custom page with a external softwares.

**Comment by ssddanbrown** [comment]
@geysonsantana It's not possible at this time but we are open to requests for the API assuming there's a BookStack-focused use case.

It would be good to know the following:
- Are you already using BookStack or are you currently scoping it out for potential use?
- Can you provide details about your intended use of such an API endpoint?

**Comment by kayvanaarssen** [comment]
I think once the API is more developed this will be a great addition to integrate Bookstack into processes and automated workflows that we also have.
For example push config changes or things like that into Bookstack via an automated way.

**Comment by geysonsantana** [comment]
We are using the BookStack integrated with other system. Our idea is as follows, centralize and automate the criation of shelves, chapters, books and pages for a knowledge base. Some pages have an attachment and our workaround was create uns href in the page for other apache repository. For a while, its working good, but will be more interesting work at the bookstack by api.

**Comment by horshack** [comment]
It's a great idea to expand the API for uploading attachments. Maybe also pictures. When we are getting to URL of an uploaded picture we could automatically upload new articles with pictures.

Similar situation as @geysonsantana
