### ISSUE TITLE
Make Tags more prominent

### ISSUE THREAD

**Issue by newhinton** [BookStackApp/BookStack#2943]
**Describe the feature you'd like**
Show Tags more prominently. There are multiple different places, either below the details in the right bar, or below the search in the left bar (as a collapsible perhaps)
A tagpill could just be a link to the exisiting search with the tag selected.

**Describe the benefits this feature would bring to BookStack users**
This would allow for a more useful usage of tags, since there is no overview as proposed in #1354 

**Additional context**
#2829 would also greatly enhance the tagging feature.

**Comment by ssddanbrown** [comment]
Hi @newhinton,
Tags are already displayed in the top-left of a book/chapter/page/shelf view, and clicking on them does start a search as per your request. I wouldn't really want to repeat their display within the same view. Or have I misunderstood this request?

**Comment by newhinton** [comment]
You are right! At first i misunderstood how tags work. I assumed tags would always show up, regardless of 'type'.

Maybe it makes sense to show tags recursively, so that all tags that are present in a book show up on the left when a book is selected, not only 'book'-tags. (And the same for chapters and shelfes)

This way a user could quickly get a selection of a certain topic, without having to find an actual page with the tag.

**Comment by ssddanbrown** [comment]
Okay. I'm not sure on the value of showing all tags applied to child content. Would need to be a click away anyway since it'd otherwise get messy, and think it'll more likely cause confusion than provide assistance, especially since this is the first request I've seen for such tag behaviour.

**Comment by newhinton** [comment]
the "issue" i have is that i dont know what tags are in use, so that i cant really use it to filter for them. It's basically a context dependend version of the page requested here: #1354

![e](https://user-images.githubusercontent.com/25279821/134911377-097e2b25-0ca8-47c5-b30b-2f2b3e41e929.png)


this could use the book/page/chapter color instead of the primary-color, and/or use a separation-header to clear it up.

I may be wrong, but besides knowing tags or searching for them, there is no way to actually know which tags are in use, which makes them hard to use.

Also i dont think that it would have to be "a click away" is a bad thing, since its purpose is to give the user an overview, not necessary to get the user to the intended target. It's basically an even more slimed down version of the linked closed pr

**Comment by ssddanbrown** [comment]
Okay. The whole use-case and benefits described here revolve around understanding existing use of tags hence I'd consider this to overlap with the existing issue #738. I'll update that to reference your potential implementation above and therefore close this off.
