### ISSUE TITLE
Show revisions for viewers

### ISSUE THREAD

**Issue by ADMDW** [BookStackApp/BookStack#2946]
Hello,
is there a way in which the "Revisions" button can also be displayed under "Actions" for viewers? Currently the viewer can only see "Favourite" and "Export" but not "Revisions".
If the viewer adds "/revisions" to the URL, it works fine...

The benefit: Viewers can immediately recognize the changes in long texts.

Thanks very much!

**Comment by mlipok** [comment]
I was asking similar feature here:  https://github.com/BookStackApp/BookStack/issues/3192

The "/revisions" sufix added to the URL works fine also for "Public" and I think this should be added as I described it in my PR mentioned above.

btw. @ssddanbrown  could you mark this PR as "Feature Request" ?

**Comment by ssddanbrown** [comment]
Thanks both for raising.

This has been addressed in 2fe261e20729e005385f4fe31c375ee699d938b6 and will be part of the next feature release.

### Documentation Notes

- Update advisory to note revision link visibility change (Actual revision access remains unchanged, but permissions here would not have been obvious before).
