### ISSUE TITLE
Attach file (e.g. pdf) to a page

### ISSUE THREAD

**Issue by WaschlJoe** [BookStackApp/BookStack#2947]
I would like to attach one or more files to a created page. These files should be for example pdf or word documents.

**Describe the benefits this feature would bring to BookStack users**
This would make bookstack even more versatile. It would be for example possible to add official manuals of products to a page

**Comment by kayvanaarssen** [comment]
That's already possible.

You can add them via the side menu:

1. Edit the Page
2. 
![image](https://user-images.githubusercontent.com/672841/135041391-74ba1501-ac5c-4ca8-9ece-dbf212d825a2.png)
3. Drag and Drop your files

They will show up when you view the page in the left top corner **As Attachments**

**Comment by WaschlJoe** [comment]
Cool. Thanks a lot. I was searching this feature and did not find it.
