### ISSUE TITLE
Drag & Drop Book Sorting does not work. Not even on the Demo Bookstack Page.

### ISSUE THREAD

**Issue by AemonXVI** [BookStackApp/BookStack#2948]
https://www.bookstackapp.com/docs/user/organising-content/#sorting-books
"Here you can simply drag and drop chapters and pages around and also between different books. Once you have organised your content press ‘Save’ and all included books will be re-organised."

Does not work. Not even on the bookstack demo page. Nothing happens if I drag the chapters or pages.
I tried it with different, clean browsers.

Am I the only one with that problem?

**Comment by watschi** [comment]
Does work for me on the latest Firefox.
Just to make sure, did you click 'Sort' on the book view?

**Comment by AemonXVI** [comment]
On the newest version of Firefox it looks like this:
![I hate my life...](https://media.giphy.com/media/ugh0ZJsgQ7nq88B63Z/giphy.gif)

**Comment by AemonXVI** [comment]
It runs on:
Portainer 2.9.0
Docker 20.10.8
Nginx 1.20.1
PHP 7.4.23

**Comment by AemonXVI** [comment]
Okay... it works for everyone except for me.
Even with a new browser and no extensions.
