### ISSUE TITLE
BookStack not working at all

### ISSUE THREAD

**Issue by SimonOSR** [BookStackApp/BookStack#2950]
**BookStack is not working at all. Cannot do anything.**

**Steps To Reproduce**
1. Installed VirtualBox
2. Installed Ubuntu 20.04.3 LTS in VirtualBox
3. Ran the install script
4. Tried accessing 10.0.2.15 (or bookstackserver.com, the address I picked). Instead, it goes to 10.0.2.15/login and gives me a 404 error.

**Expected behavior**
Should be able to access BookStack

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): whatever is the default using the install script
 - PHP Version: whatever is the default using the install script
 - Hosting Method (Nginx/Apache/Docker): whatever is the default using the install script

**Additional context**
- I can ping 10.0.2.15, so I think everything installed and is running correctly.
- Typing in 10.0.2.15 forwards to bookstackserver.com

**Comment by ssddanbrown** [comment]
Hi @SimonOSR,
1. What exact ubuntu image are you using for VirtualBox?
2. What providing a domain/host when running the script, what exactly is the value you're providing?
3. You mentioned use of `bookstackserver.com`. Is this a domain that you've got pointing somewhere or have configured locally on the host machine?

**Comment by SimonOSR** [comment]
Hi, thanks for your quick reply!

1. Ubuntu 20.04.3 LTS, downloaded from https://ubuntu.com/download/desktop
2. I used "bookstackserver.com", see below:
![image](https://user-images.githubusercontent.com/91768607/135894730-9e82657d-291c-4af6-ba1f-866ceb9af175.png)
3. No, this is the domain I used during the setup script. What's interesting is that attempting to access 10.0.2.15 in my browser immediately forwards to bookstackserver.com/login, like this:
![image](https://user-images.githubusercontent.com/91768607/135895118-27c33f75-69ed-4469-ad6a-049e1448a458.png)
<Enter>
![image](https://user-images.githubusercontent.com/91768607/135895164-62b64abe-0a3a-4747-a27a-1d53303da471.png)

But I can ping 10.0.2.15, whereas pinging bookstackserver.com fails.

**Comment by ssddanbrown** [comment]
Thanks for confirming @SimonOSR,
So yeah, If you're providing bookstackserver.com, and you have not done anything to configure `bookstackserver.com`, then it's not going to work. You could use your local machine IP instead (`10.0.2.15` in the example above, Might be different when booting a different VM)

**Comment by SimonOSR** [comment]
Hmm, interesting. I hope you don't mind me suggesting to change the prompts in the setup script then. I thought the whole point of the setup script was to configure all that stuff for me.

So what you're saying is, I should enter 10.0.2.15 in the setup script?

**Comment by ssddanbrown** [comment]
@SimonOSR Setting up a web domain is outside the scope of what we're able to realistically do within the script. You'd typically run the script after already pointing/owning a domain to a machine.  I probably won't change the wording in the script as it has not been an issue before.

> So what you're saying is, I should enter 10.0.2.15 in the setup script?

Yes, assuming that using `10.0.2.15` in the browser would lead to the request reaching the machine you're installing BookStack onto.

**Comment by SimonOSR** [comment]
Hmm. I only got the 10.0.2.15 from the prompts at the end of the script. It says "you can now reach BookStack via 10.0.2.15 or bookstackserver.com". I'll give it a try in a minute.

Definitely thanks for your help already!

Regarding the prompt... maybe add a comment "note: this will not actually configure the domain for you" or something like that? It specifically gives URLs as example. What **does** it do with the URL if it's not setting up BookStack under that URL? Anyway, at the end of the day it's obviously your call :)

**Comment by ssddanbrown** [comment]
> It specifically gives URLs as example. What does it do with the URL if it's not setting up BookStack under that URL?

It configures the domain for BookStack and the Apache web server. It's still a web app so you'd need to have that domain purchased and pointing at the machine (Or domain forced locally to point at a machine). 

> Hmm. I only got the 10.0.2.15 from the prompts at the end of the script.

This IP is auto-detected as the machine network address. Depending on how these virtual machines are created a new virtual machine may be given a different IP address.

**Comment by SimonOSR** [comment]
Alright, had to start over with a new VM from scratch, but then it worked. Thanks a lot for your help!

![image](https://user-images.githubusercontent.com/91768607/135930174-ec569c76-27d9-4c08-a7e7-16f18ac29db6.png)
