### ISSUE TITLE
Grouping audit log by user's IP address

### ISSUE THREAD

**Issue by johnroyer** [BookStackApp/BookStack#2951]
**Describe the feature you'd like**
BookStack is now logging user's IP address in audit log. There should be functionality to access audit log by IP address.

**Describe the benefits this feature would bring to BookStack users**
It is easier to know the relationship between user and IP address.

**Additional context**
This is an enhancement from issue #2747. Please assign this issue to @johnroyer. Thanks.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @johnroyer.

Rather than a specific visual grouping view I'd suggest that we just provide the ability to search via IP address. 

> Please assign this issue to @johnroyer

Just to confirm, does that mean you're looking to work on an implementation for this yourself?

**Comment by johnroyer** [comment]
I think searching via IP address us not implement yet. And this is more important then grouping.

I am  not starting, just keep it in mind.

**Comment by johnroyer** [comment]
I have some times now, I think I will do the "Search by IP" functionality.

 It some thing I missed ?

**Comment by ssddanbrown** [comment]
@johnroyer Don't think you've missed anything. Feel free to work on and create a PR for IP search.

**Comment by johnroyer** [comment]
Audit log did not have a field for searching IP address. There are some UI mocks as candidates .

----

Put a field in the right of form :

![ip-address-field](https://user-images.githubusercontent.com/114491/140860976-8fb1e3b7-4ff6-4505-a40f-f2849833e8cf.png)

----

Maybe IP address is not a part of date range form. Put it under Event Filder:

![event-filter](https://user-images.githubusercontent.com/114491/140861630-c0e3c255-7757-4641-8beb-97f517c99eb8.png)

----

Or IP address is should be isolated from the others. I do not know which is better. Any suggestions?

**Comment by ssddanbrown** [comment]
@johnroyer On the right of the form is fine if there's room on a desktop view :+1:

**Comment by ssddanbrown** [comment]
Since searching by IP has been added in #3081 I'll close this off.
