### ISSUE TITLE
[Feature Request] Inherited permissions

### ISSUE THREAD

**Issue by athornfam2** [BookStackApp/BookStack#2955]
**Describe the feature you'd like**
Currently when creating a page and/or a chapter under a shelf you have to manually copy the permissions each time a new one is created. 

**Describe the benefits this feature would bring to BookStack users**
The benefit helps all users having to perform one less repetitive task and stop human error (as we all forget from time to time)

**Comment by ssddanbrown** [comment]
Hi @athornfam2,
Please see #1091 and  #2652 for context around this request. Unless you have a solution to address the concerns or technical challenges I'll soon close this off.

**Comment by athornfam2** [comment]
Hello @ssddanbrown 

After reading through both cases. Am I correct in understanding that Shelves do not have inherited permissions but books do?

**Comment by ssddanbrown** [comment]
@athornfam2 Yeah, Books and chapters will cascade their permissions down unless overridden. 
Shelves do not do this due to the fact that a book can be in many shelves.

**Comment by athornfam2** [comment]
@ssddanbrown Understood. I'd say this request can be closed then.
