### ISSUE TITLE
Roles Issue

### ISSUE THREAD

**Issue by athornfam2** [BookStackApp/BookStack#2956]
**Describe the bug**
When a domain user logs in they are being assigned the group that is set under **Registration** in the settings part of Bookstack. With our Bookstack environment pulling users and groups from a domain we do not want users to get any unwanted roles assigned to them. 

As you can see in the screenshots below... One of our users that has the Editor role was assigned the Public role too which was from the registration field in settings. Originally that Public roles was Staff&Students (because I was trying to test out where it was assigning this role) but changed it to another role to test.

My issue is somewhat similar to this issue https://github.com/BookStackApp/BookStack/issues/2116 but we don't want more than one role.

**Steps To Reproduce**
* Have Bookstack LDAP enabled
* Have have roles assigned by security groups
* Uncheck the enable registration and set role to Public

**Expected behavior**
I would expect when a domain user signs in they are assigned a specific role. We do not want them to have any other role than that.

**Screenshots**
![image](https://user-images.githubusercontent.com/74559383/136076945-d12de9b0-6d92-4925-912c-bccfe3dd6ff5.png)
![image](https://user-images.githubusercontent.com/74559383/136077357-5ac6376a-10e5-43c6-bf6d-d1ed0dac3fb1.png)
![image](https://user-images.githubusercontent.com/74559383/136077870-e4ba5678-9456-4ef6-8d00-8bd0893d5a88.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v21.08.04
 - PHP Version: 7.4.3
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Thanks for the request @athornfam2.
The fundamental request here, of disabling the default registration role, overlaps with #2338 so I've updated the title there for clarification and I'll therefore close this off as a duplicate.
