### ISSUE TITLE
'Save Settings' doesn't work or settings are immediately reverting back

### ISSUE THREAD

**Issue by MorhionGendehar** [BookStackApp/BookStack#2962]
It's as it sounds, when using the 'settings' page nothing persists, you can make changes all day long but after hitting 'save settings' which says 'settings saved' nothing has changed. At one point I was able to make changes but now nothing seems to work.

**Comment by ssddanbrown** [comment]
Hi @MorhionGendehar,
Within the settings view, are you pressing the save button for the section you're editing or are you pressing the save button for an adjacent section?

**Comment by aesy** [comment]
I just want to say that I made the exact same mistake, even thinking it was a bug. Maybe @MorhionGendehar and I are especially stupid, or maybe it just feels natural to scroll to the bottom to save everything. Either way, thanks for pointing me in the right direction :smile:

**Comment by ssddanbrown** [comment]
@aesy Yeah, has happened a few times (Done it myself tbh).  #3221 has seen been opened with a decision to change things to be a bit more intuitive.
