### ISSUE TITLE
Support for reverse proxies in audit log

### ISSUE THREAD

**Issue by Cave-Johnson** [BookStackApp/BookStack#2964]
Is there a way to to use X-Forwarded-for headers in the audit log for IP addresses? 

My bookstack instance is behind an nginx reverse proxy that handles SSL/TLS, in the audit log it shows up as the proxy IP address rather than the actual clients IP address

**Comment by ssddanbrown** [comment]
@Cave-Johnson I have not tried this but could you map the cloudflare header across to the expected header on the nginx proxy side? Via a rule such as:

```nginx
proxy_set_header X-Forwarded-For $http_true_client_ip;
```

**Comment by Cave-Johnson** [comment]
Had to use `proxy_set_header        X-Forwarded-For         $http_CF_Connecting_IP;` as `$http_true_client_ip` is for enterprise accounts only. 

All working now, thanks for the help!

**Comment by Sazzels** [comment]
### Info
*docker-compose.yml*
```
image: "linuxserver/bookstack:24.02.2"

networks:
  - proxy
```
*proxy network*
```
# NPM proxy network IP
"<ID>": {
    "Name": "proxy",
    "EndpointID": "<ID>",
    "MacAddress": "<MAC>",
    "IPv4Address": "172.25.0.4/16",
    "IPv6Address": ""
},
```

i know this is a old topic but i could not get this running with Nginx Proxy Manager. 

Bookstack and NPM share a network `proxy` and in NPM i forward to `http://bookstack:80`. 

```
Logs
172.25.0.4 - - [08/Apr/2024:19:07:49 +0000] "GET / HTTP/1.1" 200 10216 "<reverseProxyFQDN>"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
```
tried:
```
APP_PROXIES=*
```
```
APP_PROXIES=172.25.0.4
```
```
APP_PROXIES=<PROXY_IP>
```

@Cave-Johnson @ssddanbrown should i open a new issue?

**Comment by ssddanbrown** [comment]
@Sazzels Yes, and in that issue please detail where you're setting those environment variables and any actions performed after setting them before re-testing.

**Comment by oopen** [comment]
I use docker compose, with Traefik as reverse proxy.
To display real IP, I use this nginx config inpired from https://djangocas.dev/blog/nginx/nginx-access-log-with-real-x-forwarded-for-ip-instead-of-proxy-ip/#solution-1-get-client-user-real-ip-in-nginx-access_log

File `/config/nginx/nginx.conf`

```
[...]
#    access_log /config/log/nginx/access.log;

    log_format combined_realip '$http_x_forwarded_for - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';

    access_log /config/log/nginx/access.log combined_realip;
[...]
```
