### ISSUE TITLE
Ubuntu 20.04 install script - problem about SQL

### ISSUE THREAD

**Issue by horstepipe** [BookStackApp/BookStack#2974]
**Describe the bug**
Hello
I'm having problems with the install script provided for Ubuntu 20.04. 
I also tried it manually via this guidance, unfortunately seeing the same error there:
https://www.howtoforge.de/anleitung/bookstack-ubuntu-1804-lts/

Ater entering 
`sudo php artisan migrate`
I'm getting that error
`   Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = bookstack and table_name = migrations and table_type = 'BASE TABLE')

  at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDO\Exception::("could not find driver")
      /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18

  2   Doctrine\DBAL\Driver\PDO\Exception::new()
      /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:44

  Please use the argument -v to see more details.
`

MariaDB has this version:
Your MariaDB connection id is 22
Server version: 10.3.31-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

I can login with the bookstack credentials fine on MariaDB.

Has anyone some idea?

Best regards

**Comment by horstepipe** [comment]
okay sorry,
I removed all other php packages and now installer script works fine.
thanks for your time and sorry!

**Comment by ssddanbrown** [comment]
No worries, Glad you got it going! Will therefore close this off.

**Comment by navjotjsingh** [comment]
I am facing the same issue on Ubuntu 20.04 and MariaDB 10.6. There is only PHP 7.4 installed on my system and yet the migrate command keeps failing.
