### ISSUE TITLE
Possible for only some users to use SAML, and others to login direct?

### ISSUE THREAD

**Issue by abulgatz** [BookStackApp/BookStack#2984]
I'd like to use SAML authentication for my internal org users, and have essentially "guest" users that exist only in Bookstack and don't use SAML.

Is this possible?

**Comment by ssddanbrown** [comment]
Hi @abulgatz,
No, Support for multiple core authentication types is currently not supported. It would require some reworking of the auth systems and some re-thinking about how user experience is managed and a think through of any possible security considerations that it could introduce.

**Comment by ssddanbrown** [comment]
I'm closing this to collapse this into #2715, which I've made into the auth-method abstract issue for combining auth options.
