### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by a030225033** [BookStackApp/BookStack#3001]
### Describe the Bug

uploads/images since you don’t need account secret, you can browse 

patch
/uploads/images/gallery/

### Steps to Reproduce

know url 

### Expected Behaviour

input account 

### Exact BookStack Version

v21.08.6 

### PHP Version

php 7.4

### Hosting Environment

ubuntu 20.04
nginx

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please message me from this issue or open a new issue, referencing this one.
