### ISSUE TITLE
[Feature Request]: Sub-Chapter

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#3016]
### Describe the feature you'd like

A Sub-Chapter for the main Chapter

### Describe the benefits this feature would bring to BookStack users

A sub-chapter should be created for the main chapter main chapter

**Comment by ssddanbrown** [comment]
Since there has not been to much additional demand, relative to effort for this, and since there has been no expansion on benefits as requested above, I'm going to go ahead and close this off.
