### ISSUE TITLE
[Feature Request]: Minimalist Editor in the Comments

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#3018]
### Describe the feature you'd like

a minimalist editor for the comments area

Text Formating:
- Bold, Italic ....
- Bullet List
- Emoticons

### Describe the benefits this feature would bring to BookStack users

Better Formated Text´s in comments Area

**Comment by ssddanbrown** [comment]
With the merge of #4815 I've now brought the simple WYSWIYG description inputs (added last release) to comment boxes. This will be part of the next feature release.
Thanks again for the request @reddexx.
