### ISSUE TITLE
[Support Request]: Creating Okta Users

### ISSUE THREAD

**Issue by DarthBeav** [BookStackApp/BookStack#3020]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have configured our installation to auth with Okta following the instructions here: https://www.bookstackapp.com/docs/admin/third-party-auth/#okta

The Auth works I'm just trying to figure out the best option for provisioning users. I don't want users to be able to self register but right now I need that ability for an okta user to create a profile. The only way I have found to create an account that works with okta is to have the user click the I don't have an account link on the register page then choose the Sign up with Okta button.

So my two questions
Is there a way to pre-create the users for okta? Currently if I manually create and account that matches a user when they try to login with okta we get the message "This Okta account is not linked to any users. Please attach it in your profiles settings...." I don't see any option to attach or specify an existing account is Okta compatible. 
![image](https://user-images.githubusercontent.com/93331849/139272687-8da36c6e-c994-4c8b-84bd-1d3541bc1edd.png)

If that is not possible is it possible to only allow the Sign up with okta option and not allow a user to create a basic account on the register page? We will have this information allowed to anonymous access and do not want them creating accounts.

Thanks

### Exact BookStack Version

v21.08.6

### Hosting Environment

Linux Vm. I don't have access to the server to verify

**Comment by DarthBeav** [comment]
Thanks I missed that setting when I was going through the article. Exactly what I needed.

**Comment by ssddanbrown** [comment]
Awesome! Will therefore close this off.
