### ISSUE TITLE
Angular: HTTP failure during parsing[Support Request]: 

### ISSUE THREAD

**Issue by numpsi2002** [BookStackApp/BookStack#3024]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,
i try to get the API working on Angular 7. 
In general, all works fine, but if i get a request for the export in html, the Angular httpClient get a error "Http failure during parsing for http://localhost:6875/api/pages/1/export/html". But with the error comes the html-output and can be used correctly. 
Can someone help me, what correct Header-settings i have to use to get rid of that error?

### Exact BookStack Version

21.10.2-ls168

### Hosting Environment

linuxserver/docker-bookstack 21.10.2-ls168

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
