### ISSUE TITLE
[Feature Request]: Label colors

### ISSUE THREAD

**Issue by MaartenUreel** [BookStackApp/BookStack#3025]
### Describe the feature you'd like

Be able to define a color for specific label values.

For instance, a label "confidentiality" with three levels (green, amber & red) could be represented with that color.

### Describe the benefits this feature would bring to BookStack users

Help to achieve certain ISO compliancy guidelines.

**Comment by ssddanbrown** [comment]
@MaartenUreel The latest release now has additional attributes set on the tag elements:

```html
<div class="tag-item primary-background-light" data-name="Category" data-value="Demo">
```
If a quick live example is desired:
https://demo.bookstackapp.com/books/bookstack-demo-site/page/mixed-content-example-page

**Comment by ssddanbrown** [comment]
Since the original fundamental request can be now be achieved, using a little custom applied CSS, I'll close this off. 
Feel free to shout if you need an example of such CSS.
