### ISSUE TITLE
Callout formatting

### ISSUE THREAD

**Issue by unknowndomain** [BookStackApp/BookStack#303]
Desired Feature:

Improved formatting for callouts, including:

* Link colouring to match the style:

<img width="411" alt="screen shot 2017-02-07 at 01 52 18" src="https://cloud.githubusercontent.com/assets/147143/22674514/3a24fcc4-ecd8-11e6-8e10-dbbc73b1ad90.png">

* Paragraphs, and other mark down to be suppported.

**Comment by ssddanbrown** [comment]
@unknowndomain Thanks for the suggestion. The link colouring definitely needs to be improved. 

What kind of other formatting do your require? Callouts are designed to be simple really and should really only contain a line or two.

**Comment by unknowndomain** [comment]
http://p-i-c.net/books/physical-computing/chapter/physical-computing-for-prototyping

If you look at these week 1/2 pages you can see how we're using them a bit better, this is one of the main formatting problems we have.

**Comment by aljawaid** [comment]
@ssddanbrown On pdf export these callout (i) icons are just question marks randomly on the page :(

**Comment by ssddanbrown** [comment]
@aljawaid As of next update they should no longer be question marks but will be blank instead. Will hopefully find a way to include them in the exports.

**Comment by ssddanbrown** [comment]
Thanks to @alexmannuk the link coloring will now be fixed as of v0.30.1, to match the correct callout color.

In regards to deeper formatting, I'd prefer to keep callouts fairly simple and focused in use. Allowing different block styles within makes things more complex to support while opening up callouts for potential misuse in content. Additionally, there has not been much request for more advanced formatting over the last 3.5 years

**Comment by Felix-Kettnaker** [comment]
@ssddanbrown  
I would really appreciate this feature.  
I was actually using more complex callouts a lot in other note/wiki apps. I see it often times as a kind of tangent marker, something that deviates a bit from the main focus of the page. So it can be a bit longer sometimes.  
And from the technical view, blockquotes already allow all the styling. Where is the difference here? Why can't we get that functionality for the callouts also? Why should blockquotes be supposed to be less concise than callouts?

And what qualifies as a "misuse" of callouts - or bookstack in general? I am actually of the opinion that there is no misuse at all in private use and I'm interested in your view on this.
