### ISSUE TITLE
Update from 21.08.5 to 21.10.x went wrong

### ISSUE THREAD

**Issue by lorydone** [BookStackApp/BookStack#3034]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After runnung the update command from Version 21.08.5 to 21.10.3 and after the following step in the cli is reached:

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
```

I got following error message:

`The stream or file "/var/www/BookStack/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied`

This is for the commands (all in StreamHandler.php line 146)
```
php artisan cache:clear
php artisan view:clear
php artisan config:clear
```

This is strange, because permission are set as advised by running:
```
sudo chown -R www-data:www-data bootstrap/cache storage public/uploads
sudo chmod -R 755 bootstrap/cache storage public/uploads
```
(webserver user is www-data)

When cd'ing into the directory .../storage/logs/, attributes are shwon like this:
`-rwxr-xr-x 1 www-data www-data 212875 Nov  1 17:25 laravel.log*`  

All previous updates run without issues

When I command `sudo php artisan cache:clear` I get this error (in Application.php line 679):

`Class 'Facade\Ignition\IgnitionServiceProvider' not found`

Result is, that Login Page is Blank, there is no content on it.

Any ideas what is wrong and where to dig in?

### Exact BookStack Version

21.08.5 to 21.10.3

### Log Content

[previous exception] [object] (ReflectionException(code: -1): Class translator does not exist at /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php:803)
[stacktrace]
#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct()
#1 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): Illuminate\\Foundation\\Application->make()
#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(873): app()
#7 /var/www/BookStack/storage/framework/views/4b8e70439d73c1f6b6ab796f9756cda764dd98e9.php(7): trans()
#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/BookSt...')
#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(143): Illuminate\\View\\Engines\\CompilerEngine->get()
#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#14 /var/www/BookStack/vendor/symfony/http-foundation/Response.php(205): Illuminate\\Http\\Response->setContent()
#15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\\Component\\HttpFoundation\\Response->__construct()
#16 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()
#17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(410): Illuminate\\Routing\\ResponseFactory->view()
#18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(315): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(212): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#20 /var/www/BookStack/app/Exceptions/Handler.php(62): Illuminate\\Foundation\\Exceptions\\Handler->render()
#21 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(420): BookStack\\Exceptions\\Handler->render()
#22 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->renderException()
#23 /var/www/BookStack/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()
#24 {main}

### PHP Version

7.4

### Hosting Environment

Ubuntu Server 20.04 on Raspi4
nginx Server 1.18.0
mariadb 10.3.31

I had no problems running and updating Bookstackapp since updating from V21.08.5
Server runs behind a Nginx Proxy hostet on a Linux Container

**Comment by ssddanbrown** [comment]
Hi @lorydone, Does the `composer install --no-dev` update step run without error? Also, can you confirm the output of running `git status` within your bookstack install directory.

**Comment by lorydone** [comment]
Hi @ssddanbrown 
`composer install --no-dev` shows this:
+++++++++++++++++++
> ubuntu@ubuntu:/var/www/BookStack$ composer install --no-dev
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
> Installing dependencies from lock file
> Verifying lock file contents can be installed on current platform.
> Nothing to install, update or remove
> Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

>In StreamHandler.php line 146:

 > The stream or file "/var/www/BookStack/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied


> 53 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> @php artisan cache:clear

> In StreamHandler.php line 146:

 > The stream or file "/var/www/BookStack/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

> @php artisan view:clear

> In StreamHandler.php line 146:

 >  The stream or file "/var/www/BookStack/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied
++++++++++++++++++

`git status` shows this:

++++++++++++++++++
> ubuntu@ubuntu:/var/www/BookStack$ git status
> On branch release
> Your branch is up to date with 'origin/release'.

> Untracked files:
  > (use "git add <file>..." to include in what will be committed)
       >  public/info.php

> nothing added to commit but untracked files present (use "git add" to track)
++++++++++++++++++

**Comment by ssddanbrown** [comment]
@lorydone I think this does come down to permissions, with conflicting permissions between the user you're running the commands as and the permissions set on files for webserver use.

Can you try running:

```
sudo rm /var/www/BookStack/bootstrap/cache/*.php
```

and let me know if that changes anything?

**Comment by lorydone** [comment]
@ssddanbrown 
doesnt change anything. Still the permission error when running f.e. php artisan chache:clear

**Comment by lorydone** [comment]
sorry, typo: I run `php artisan cache:clear` of course, not chache...

**Comment by lorydone** [comment]
@ssddanbrown ok, I still get this error when running the artisan commands under the restricted user. With sudo they run finde now. 
Frontend is reachable again.
The cache remove command most probably did the job in this case.
Thx, @ssddanbrown
