### ISSUE TITLE
[Feature Request]: Make the editor choice a user preference

### ISSUE THREAD

**Issue by taophp** [BookStackApp/BookStack#3036]
### Describe the feature you'd like

The choice between WYSIWYG and Markdown editor should be set as user preference, not as application configuration, except, eventually for the _default_ editor.

### Describe the benefits this feature would bring to BookStack users

Each user could contribute using his preferred editor, not the admin's choice.

**Comment by ssddanbrown** [comment]
Hi @taophp,
This is already open within issues #119, #369, #458 and #842 so I'll therefore close this off as a duplicate.
