### ISSUE TITLE
[Feature Request]: Possibility as an admin to see which users are currently logged in

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#3037]
### Describe the feature you'd like

It should be possible to see in the admin area which users are currently active and who are editing posts

### Describe the benefits this feature would bring to BookStack users

This makes it easier for admins to plan when updates can be carried out or to notify users to log off. Very useful to avoid partial data loss caused by restarting the server

**Comment by ssddanbrown** [comment]
Thanks for your request @pboatone,

I think the core request here is already covered by issue #2828 (With #2985 being somewhat related) so I'll therefore close this off as a duplicate.
