### ISSUE TITLE
[Feature Request]: https://MYURL/pages/recently-updated - pagination

### ISSUE THREAD

**Issue by mlipok** [BookStackApp/BookStack#3044]
### Describe the feature you'd like

In
https://MYURL/pages/recently-updated

class="pagination" should be also on top not only on bottom

### Describe the benefits this feature would bring to BookStack users

this will be more flexilbe

**Comment by ssddanbrown** [comment]
Hi @mlipok,

We generally follow a bottom-only pagination style within BookStack to prevent additional visual clutter at the top of views (Where it can often be quite busy). This seems to come down to a personal preference overall. Bottom-only pagination is not unheard of, I just checked a few sites (duckduckgo, google, bing, github) and they all had a bottom-only pagination. 

Unless there's a significant reason to reconsider I'll soon close this off.

**Comment by mlipok** [comment]
I do not mean bottom only pagination, but both, down an also bottom.

**Comment by ssddanbrown** [comment]
> I do not mean bottom only pagination, but both, down an also bottom.

Sure, That's how I understood the request. Again, I think this just personal preference. Pagination at the top does not offer a great amount of benefit while adding visual complexity/clutter to the view. It's always a balance between features/convenience & ensuring the design is tidy, clean and non-intimidating.

**Comment by ssddanbrown** [comment]
Will therefore close this off.
