### ISSUE TITLE
Show updated date & last editor user on recently updated listing

### ISSUE THREAD

**Issue by mlipok** [BookStackApp/BookStack#3045]
### Describe the feature you'd like

in https://MYURL/pages/recently-updated 
I would like to see and information who update and when update was performed for each displayed updated content.

### Describe the benefits this feature would bring to BookStack users

When I go on vacation, or I am away from work for a few days because I am on a business trip, after returning to the office I would like to know what things to look at, usually I know that I did the last inspection on the previous Monday, and I know that I only have to go back to changes from the time period related to, for example, last Monday, but when I'm on vacation, I know that I have to go back to the time from two or even three weeks ago.

How do I know if something is new or already known to me?

It is also often the case that my co-worker tells me after come back to the office:
`There have been significant changes which I described a few days ago.`

For this reason, I would like to see the date of the change and the person who made the change.

To focus on updates made by this particular co-worker in a specific date range.

**Comment by ssddanbrown** [comment]
Thanks for the request @mlipok,
I agree that showing these details would provide benefit that would enhance that specific view.

**Comment by mlipok** [comment]
Also the comment provided by editor

**Comment by Julesdevops** [comment]
I can contribute this enhancement if no one is currently working on it

**Comment by ssddanbrown** [comment]
@Julesdevops I have not started, Feel free to take it on! Thanks!

**Comment by mlipok** [comment]
@Julesdevops do you have any progress ?

**Comment by Julesdevops** [comment]
@mlipok Sure, will open a PR during the week. (sorry for delay I'm currently backlogged)

**Comment by Julesdevops** [comment]
@mlipok I opened a draft PR. Feel free to let me know wdyt about this

**Comment by mlipok** [comment]
Screenshot added in PR:
https://github.com/BookStackApp/BookStack/pull/3177#issuecomment-1017293862

**Comment by ssddanbrown** [comment]
Will be in the next patch release since #3177 has been merged. Will therefore close this off.
