### ISSUE TITLE
[Feature Request]: recently updated listing - link

### ISSUE THREAD

**Issue by mlipok** [BookStackApp/BookStack#3046]
### Describe the feature you'd like

Please add an easy to click link to recently updated listing 
I mean to:    https://MYURL/pages/recently-updated

for example here
![image](https://user-images.githubusercontent.com/11089482/140811851-b25ef545-d17d-4554-b195-00b3e9fab63b.png)

or here:
![image](https://user-images.githubusercontent.com/11089482/140811772-106f5859-ba10-4d36-9eca-24da6b96a1f0.png)

### Describe the benefits this feature would bring to BookStack users

Nowadays, getting to this place is not easy at all.
I will say more, it took me a few days to find this functionality.

In my humble opinion, this should be one of the main functions you use every day, right after the search box.

**Comment by ssddanbrown** [comment]
Thanks for the request @mlipok,
I would not look to add this to the header as I don't think there's really the justification to make this a primary header link amoung others.

I agree that it's a little hidden right now. Maybe instead of linking the title of the card we add a link to the bottom of the "Recently Updated Pages" card to make this more obvious.

Just as an additional note, If desired, you could use the custom footer links option to add this as a footer link.

**Comment by mlipok** [comment]
> Maybe instead of linking the title of the card we add a link to the bottom of the "Recently Updated Pages" card to make this more obvious.

in the `dropdown-container` specyfically in `dropdown-menu` there is `My Favourites`
![image](https://user-images.githubusercontent.com/11089482/141070359-5151a3f4-52ad-4fc4-99d3-4343c2b52d7b.png)

Maybe the best solution would be to add a new "Recently updated" item here?

**Comment by ssddanbrown** [comment]
@mlipok All of the options in that menu relate to options or views that affect the current user. The "Recently Updated Pages" view does not fit into this at all.

**Comment by ssddanbrown** [comment]
Within 197caddf96b3d9ce6073109cfc2289133dd456f9 I've replaced the card header links with obvious links that sit at the bottom of the homescreen cards (Or list menus if using the non-default homepage option). This will be part of the next patch release.

This covers the core issue raised regarding accessibility of this link so I'll therefore close this off.
