### ISSUE TITLE
  [PDOException]   SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by s0n-** [BookStackApp/BookStack#305]
I am attempting to install Bookstack from the ububtu install script on 16.04

Everything looks good except I get the following error before the end and when i visit the IP i get the error from bookstack "something may have went wrong"

**Comment by lommes** [comment]
First thing that came to my mind was, that you are trying to use sqlite. If so please check if a file named `database.sqlite` is existing in the storage/ directory.

If you try to use any other database please provide further information from `storage/logs/laravel.log`

**Comment by s0n-** [comment]
Apparantly the first option was to put in a domain, the first time I put in http://IP and got this error. The next time I ran this i tried http://FQDN and this time it worked perfectly.
