### ISSUE TITLE
[Bug Report]: 'skip to main content' blocking content when printing

### ISSUE THREAD

**Issue by jeff0485** [BookStackApp/BookStack#3051]
### Describe the Bug

There is a "Skip to Main Content" link on the bottom left corner of every sheet when printing a page that exceeds 1 sheet in length.

### Steps to Reproduce

Open a BookStacks page that is longer than 1 sheet of paper
Print via the browser
"Skip to main content" link appears on top of content on bottom left of each sheet.

### Expected Behaviour

A clean printout without extra elements blocking content

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/94074288/141172648-88aca022-c789-493e-a499-2b490958864b.png)

### Exact BookStack Version

v21.10.3

### PHP Version

unknown

### Hosting Environment

Ubuntu 20.04 LTS, also shows on [official BookStack demo](https://demo.bookstackapp.com/books/bookstack-demo-site/page/mixed-content-example-page)

**Comment by shubham-004** [comment]
@jeff0485  Skip to main content doesn't contain any functionality currently, It just contains a link to the start of the page.
Maybe you can put a feature request for it.
Reference Screenshot:
![Screenshot from 2021-11-11 01-12-19](https://user-images.githubusercontent.com/92021999/141182767-d0cf76a7-6a2f-4291-b750-e592dba9a0a8.png)

**Comment by ssddanbrown** [comment]
Thanks for reporting @jeff0485.

Interestingly this does not occur on FireFox, Nor does it occur in chrome when emulating print styles using the development tools. May be a bug, or at least a strange scenario, in chrome for the styles of this particular element.

Either way, still something we should hide in print styles to be sure. Have assigned to the next feature release.
