### ISSUE TITLE
[Bug Report]: Markdown drafts being converted to HTML

### ISSUE THREAD

**Issue by serenewaffles** [BookStackApp/BookStack#3054]
### Describe the Bug

Markdown drafts are replaced with HTML when going back to editing.

### Steps to Reproduce

1. Create a new page with markdown editor enabled
2. Save that page as a draft
3. Click "Back" in upper left
4. Click new draft page to go back into editor
5. Page is now full of HTML

### Expected Behaviour

The draft should still be in Markdown.

### Screenshots or Additional Context

Saving the page normally (instead of as a draft) does not cause the markdown to be replaced with HTML. Saving a draft of an existing page works as expected.

### Exact BookStack Version

21.10.3

### Hosting Environment

Linuxserver.io docker container

**Comment by ssddanbrown** [comment]
Thanks for reporting @serenewaffles, was able to reproduce on my instance. Have now applied a patch and added a test to help prevent regression. Will be part of the next feature release.
