### ISSUE TITLE
[Feature Request]: Subdomain for shelves

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#3055]
### Describe the feature you'd like

Make a shelf accessible via a subdomain, so that it looks like there is only this theme.

### Describe the benefits this feature would bring to BookStack users

It would be possible to divide areas better and to access them directly. The clarity and handling would improve for the user.

**Comment by ssddanbrown** [comment]
Hi @Tealk,

I don't really understand this request. 

- Is this in relation subdomains as in the URL bar (Like https://subdomain.example.com)?
  - If so, Are you asking for subdomain-specific shelves?
  - Otherwise, What is meant by "Make a shelf accessible via a subdomain"?
- By "theme" are you talking about a category or are you reference design/styling?

**Comment by Tealk** [comment]
> If so, Are you asking for subdomain-specific shelves?

yes, your example would then navigate to the shelf subdomain



> By "theme" are you talking about a category or are you reference design/styling?

yes i mean categories, subdivision of topics

**Comment by ssddanbrown** [comment]
@Tealk Okay, Thanks for confirming. 

BookStack doesn't support being served via multiple host-names/sub-domains at all. 
It's not really something I'd look to support at this time due the impact and further requirements it would likely generate.

For this kind of situation I'd advise the use of multiple BookStack instances.

**Comment by Tealk** [comment]
yes that would be possible but it increases the support effort; you need a central login service and have to take care of each instance individually

**Comment by ssddanbrown** [comment]
> yes that would be possible but it increases the support effort; you need a central login service and have to take care of each instance individually

Sure, but the alternative puts an implementation and maintenance burden upon this project (and myself) at a level I can't foresee being viable at this time.

**Comment by ssddanbrown** [comment]
Will therefore close this off as out of scope.
