### ISSUE TITLE
Pulling LDAP Attribute for Email for new LDAP users

### ISSUE THREAD

**Issue by s0n-** [BookStackApp/BookStack#306]
Configuring a new instance of BookStack and integrated with AD for LDAP authentication. Are there any settings in the LDAP profile to specify where we can pull the email attribute from so emails do not need to be verified during login.

**Comment by ssddanbrown** [comment]
Hi @s0n- , There's not currently any option to do this, BookStack will simply look for a `mail` attribute on the fetched record. I'll mark this as a feature request.

**Comment by s0n-** [comment]
This would be great as we run a test lab and the domain isnt the same domain we use email on so we actually store it elsewhere. I know its a one off but being able to specify where the email would be helpful.

Thank you!

**Comment by ssddanbrown** [comment]
@s0n- The ability to configure the name of the 'email' LDAP attribute via a `LDAP_EMAIL_ATTRIBUTE` setting in the `.env` file will be in the next release (v0.15) of BookStack which I'm hoping to send out in the next day or two. Let me know if you have any issues with this after that release.

**Comment by s0n-** [comment]
This is great! Thank you very much!  Great development on this app, top notch.
