### ISSUE TITLE
[Bug Report]: Can not images are not displaying properly

### ISSUE THREAD

**Issue by milanLFC** [BookStackApp/BookStack#3061]
### Describe the Bug

Images are not displaying properly. After I associate an image to a shelf or book, neither are then displayed. I can see them in the uploads directory, but they don't get displayed.
As well as this the avatar image in the top right corner is not displayed.
Also if I try to paste an image into my page, I get an unexpected error

### Steps to Reproduce

1. Fresh docker install
2. login
3. add a shelf or a book
4. add an image to the shelf of book
5. save
6. look at shelves or books ..... images are missing

### Expected Behaviour

images to be displayed correctly

### Exact BookStack Version

BookStack v0.31.6

### PHP Version

7.4.15

### Hosting Environment

docker instance on Mac laptop

**Comment by ssddanbrown** [comment]
Hi @milanLFC,
Do you have anything you can share regarding your docker setup? 
Ideally, if you are using a `docker-compose.yml` file it would be ideal if you could share that. Just trying to understand what container is in use and how it's configured on the host.

Additionally, Is this an existing instance that has only recently errored? I see the BookStack version provided is quite old at this stage.

**Comment by milanLFC** [comment]
Firstly thanks for responding and I just realised the version is very old

This has never worked. This is a new instance I'm trying to get working via the details on docker hub 

docker-compose.yml is as below

version: "2"
services:
  bookstack:
    image: solidnerd/bookstack
    container_name: BookStack
    environment:
      - APP_URL= https://bookstack.xxxx.xxx
      - DB_HOST=xx.xx.xx.xxx:3306
      - DB_USERNAME=xxxxxxxxxx
      - DB_PASSWORD=xxxxxxxxxxxxxxxx
      - DB_DATABASE=BookStack
      - ENABLE_METRICS= 'true'
    volumes:
      - /home/user1/mydata/BookStack/uploads:/var/www/bookstack/public/uploads
      - /home/user1/mydata/BookStack/uploads_storage:/var/www/bookstack/storage/uploads
    ports:
      - 6875:8080
    restart: unless-stopped
    networks:
      - mynet
networks:
  mynet:

**Comment by milanLFC** [comment]
I think you can close this one. 
I've moved to an install on a docker apache+php server.
using the manual installation instructions
now on version v21.11
happy to say all seems to be working well
