### ISSUE TITLE
Posting LDAP credentials from another app

### ISSUE THREAD

**Issue by s0n-** [BookStackApp/BookStack#307]
We currently have a home grown application that would post credentials and would like to send them to bookstack. We currently do this with Moodle using the format 

login?username=${username}&password=${password}

Is there a way to pass login and password directly to Bookstack app at the /login page?

**Comment by lommes** [comment]
One way would be, to disable CSRF verification for the login route in [VerifyCsrfToken](https://github.com/BookStackApp/BookStack/blob/master/app/Http/Middleware/VerifyCsrfToken.php#L15) which, of course, is **not recommended**. With that change the above would work if username is the email of the user.

**Comment by s0n-** [comment]
Would it be possible to use this JUST for the site sending credentials?

protected $except = [ https://FQDN
//
];

**Comment by lommes** [comment]
Absolutely not sure, but something like
```
class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        //
    ];

    function __construct() {
    	if($_SERVER['HTTP_REFERER'] == 'WhateverYourSystemSendsAsReferrer') {
    		$this->except = [
    			'/login'
    		];
    	}        
    }
}
```
might work. Since referer is a value sent by the client, this can easily be faked.
