### ISSUE TITLE
[Feature Request]: Support correct umlaut conversion for URL slugs

### ISSUE THREAD

**Issue by cod3monk** [BookStackApp/BookStack#3071]
### Describe the feature you'd like

When using umlauts in page titles umlauts are removed in URL slugs, e.g., `öäü` becomes `/oau`, while it should convert to (according to German conventions) `/oeaeue`. Also, `ß` should convert into `ss`.

### Describe the benefits this feature would bring to BookStack users

Better readability of URL slugs.

### Additional context

https://en.wikipedia.org/wiki/Diaeresis_(diacritic)#HTML
https://en.wikipedia.org/wiki/%C3%9F

**Comment by ssddanbrown** [comment]
Hi @cod3monk,
On the latest version of BookStack a page name of `öäüß` results in a slug of `oauss`. 
So looks like the `ß` is converting fine.

In regards to the `öäü`, the linked Wikipedia page shows `oau` as a valid replacement for these characters. 

Generally I'd prefer to generally stick to the framework's handling of these characters to save us the effort, unless the current behaviour could be considered harmful in any manner.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion here I'll close this off.

**Comment by cod3monk** [comment]
@ssddanbrown 
I would not consider it technically harmful, but a matter of quality and compliance with german spelling rules. The current choice leads to misspelled slugs from currently spelled page titles.
