### ISSUE TITLE
[Bug Report]: On export to PDF multimedia is skipped (Youtube) 

### ISSUE THREAD

**Issue by PovilasID** [BookStackApp/BookStack#3077]
### Describe the Bug

Hello,

I added some Youtube embeds to my documents and then I exported them in a PDF the youtube embeds were missing.
Can you add a link to where the rich media was linking in the export?

### Steps to Reproduce

1. Create a page
2. Select "Insert/Edit media" from the editor meniu
3. Paste a youtube link in it.
4. Save
5. Export to PDF

### Expected Behaviour

Export to PDF would have a link to rich media that was provided to the editor

### Exact BookStack Version

v21.11.1

### Hosting Environment

VPS docker

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @PovilasID.
I've just pushed 2c21850da728dce55cec2e84ec73ed474ba0bd0a which replaced iframe elements with links for PDF exports.
This will be part of the next patch release.
