### ISSUE TITLE
[Feature Request]: Switch between MD / HTML editors dynamically

### ISSUE THREAD

**Issue by jlgarnier** [BookStackApp/BookStack#3078]
### Describe the feature you'd like

I'd like to have the choice of the editor on a per page basis when creating new content, as WYSYWYG (HTML) or Markdown could be only be selected at the instance level now.

### Describe the benefits this feature would bring to BookStack users

Although BookStack is a fantastic application, sometimes, working on Markdown notes is easier than HTML, depending on the exact content. For example, when copying .md notes from a third-party tool, I'd like to update their content in native Markdown. I know that there are plenty of MD -> HTML converters but this obviously add a step to a migration process.

**Comment by ssddanbrown** [comment]
Thanks for the request, but I'm going to close this off as a duplicate of #842.
