### ISSUE TITLE
[Feature Request]: PlantUML support

### ISSUE THREAD

**Issue by jlgarnier** [BookStackApp/BookStack#3079]
### Describe the feature you'd like

Support native PlantUML support to allow for diagram integration. The application should then support switching between text and "rendered" editor modes.

### Describe the benefits this feature would bring to BookStack users

User could directly create (a.k.a. text-draw) diagram into a page and have proper rendering.

**Comment by ssddanbrown** [comment]
Thanks for the request, but I'm going to close this off as a duplicate of #495.
My last thoughts on this can be found [in this comment](https://github.com/BookStackApp/BookStack/issues/495#issuecomment-628919106).

Note, that included diagrams.net/draw.io support does support PlantUML in some form.
