### ISSUE TITLE
[Support Request]: Failed to use Export PDF

### ISSUE THREAD

**Issue by Buliwif** [BookStackApp/BookStack#3087]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

I encounter a problem when I use export-books.php :
`PHP Warning:  file_get_contents(http://localhost/api/books?count=100&offset=0): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /home/userbookstack/export-books.php on line 72
PHP Fatal error:  Uncaught TypeError: Return value of apiGetJson() must be of the type array, null returned in /home/userbookstack/export-books.php:81
Stack trace:
#0 /home/userbookstack/export-books.php(48): apiGetJson('api/books?count...')
#1 /home/userbookstack/export-books.php(20): getAllBooks()
#2 {main}
  thrown in /home/userbookstack/export-books.php on line 81`

First I have to explain my configuration, my bookstack is configured with SSL : **https://bookstack.intra.local**
This is the apache conf : 
`<VirtualHost *:443>`
`       'ServerName bookstack.intra.local`
`        ServerAdmin webmaster@localhost`
`        DocumentRoot /var/www/bookstack/public/`
`        SSLEngine on`
`                SSLCertificateFile      /etc/ssl/certs/bookstack.intra.local cer`
`                SSLCertificateKeyFile /etc/ssl/private/bookstack.intra.local.key`

My API Jeton is ok and this is the export-books.php file : 
`$apiUrl = getenv('BS_URL') ?: 'http://localhost'; // http://bookstack.local/`
`$clientId = getenv('BS_TOKEN_ID') ?: 'ThisIsMySecret';'`
`$clientSecret = getenv('BS_TOKEN_SECRET') ?: 'ThisIsMySecret';`

### Exact BookStack Version

21.08.5

### Hosting Environment

Ubuntu 18.4

**Comment by ssddanbrown** [comment]
Hi @Buliwif,

From the first part of the error message:

```
PHP Warning: file_get_contents(http://localhost/api/books?count=100&offset=0):
```

The script you're running is attempting to fetch from `http://localhost` whereas you're saying you have BookStack at ` https://bookstack.intra.local`.

You either need to configure the `export-books.php` file to set the `$apiUrl` as your instance base URL, Or you need to set a `BS_URL` environment variable when running the script to point at your instance.

**Comment by Buliwif** [comment]
As always, thank you for your quick response.

I forgot to say that I tried to set https://bookstack.intra.local in the export-books.php file. The result is : 
`
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /home/userbookstack/export-books.php on line 72
PHP Warning:  file_get_contents(): Failed to enable crypto in /home/userbookstack/export-books.php on line 72
PHP Warning:  file_get_contents(https://bookstack.intra.local/api/books?count=100&offset=0): failed to open stream: operation failed in /home/userbookstack/export-books.php on line 72
PHP Fatal error:  Uncaught TypeError: Return value of apiGetJson() must be of the type array, null returned in /home/userbookstack/export-books.php:81
Stack trace:
#0 /home/userbookstack/export-books.php(48): apiGetJson('api/books?count...')
#1 /home/userbookstack/export-books.php(20): getAllBooks()
#2 {main}
  thrown in /home/userbookstack/export-books.php on line 81
`

**Comment by ssddanbrown** [comment]
@Buliwif Yeah, you'll get this with a self-signed certificate since it's not trusted by the instance you're running it on.
You'd either need to:

- Add the HTTPS CA cert to the CA bundle used by PHP on the command-line machine.
- or
- Update the `file_get_contents` references to disable SSL verification, As per this stackoverflow post: https://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-failed-to-enable-crypto

**Comment by Buliwif** [comment]
Thank You Dan,

I'll try it tomorrow and will tell you the result.

**Comment by Buliwif** [comment]
Hi,
Sorry for the delay but I was focused on other kind of problem on my job :)

The HTTPS CA is already present in /etc/ssl/certs
And for the `file_get_contents` solution, I try to modify the export-books.php

Initial : 
`function apiGet(string $endpoint): string {`
`    global $apiUrl, $clientId, $clientSecret;`
`    $url = rtrim($apiUrl, '/') . '/' . ltrim($endpoint, '/');`
`    $opts = ['http' => ['header' => "Authorization: Token {$clientId}:{$clientSecret}"]];`
`    $context = stream_context_create($opts);`
`    return file_get_contents($url, false, $context);`

But I'm not sure of what I need to modify, (sorry but php is not my cup of tea... lol)

**Comment by Buliwif** [comment]
Hi,

So I finally tried this : 

**1st try**
Modify the `/usr/share/php/Composer/CaBundle/CaBundle.php`
And add under `$caBundlePaths = array(` : 
`'/etc/ssl/certs/IntraLocalCA.cer'`

`systemctl restart php7.2-fpm.service apache2.service`

> Same problem

**2nd try**
Modify the `/etc/php/7.2/apache2/php.ini`
And add : 
`curl.cainfo` = '/etc/ssl/certs/IntraLocalCA.cer'
`openssl.cafile` = '/etc/ssl/certs/IntraLocalCA.cer'
`openssl.capath` = '/etc/ssl/certs/IntraLocalCA.cer'

`systemctl restart php7.2-fpm.service apache2.service`

 > Same problem

**Comment by Buliwif** [comment]
Hi Dan,

I finally found the php.ini few minutes before you wrote you message, and it works.

Thank you for taking time with me :)
Have a nice day.

**Comment by Buliwif** [comment]
Just an additional question please (or do you prefer I open a new issue ?)

Lot of pdf have a size of 0Kb ans are unreadable.
And I think it's linked, I have this error message when using export-books.php : 

`PHP warning: file_get_contents(https://bookstack.intra.local/api/books/19/export/pdf): failed to open stream: HTTP request failed! HTTP/1.0 500 Internal Server Error in /export-books.php on line 90`

Do you have an idea ?

**Comment by ssddanbrown** [comment]
You'll need to check the error log of your BookStack instance as per https://www.bookstackapp.com/docs/admin/debugging/.

My guess is potentially you're getting a timeout on exporting some books.

**Comment by Buliwif** [comment]
I think so it's a timeout cause it affect specially the biggest books, but can I easily  increase this timeout ?

**Comment by ssddanbrown** [comment]
It's likely a task of increasing the `max_execution_time` value in your `php.ini` as per https://stackoverflow.com/questions/3829403/how-to-increase-the-execution-timeout-in-php.

**Comment by Buliwif** [comment]
Thank You, I'll try this way.

**Comment by Buliwif** [comment]
Hi,

So, now I'm sure this is a timeout cause it happens only on the 2 biggest books.

So I modify php.ini : 

`max_execution_time=90`
`upload_max_files=20M`

I check apache and the execution time is set by default at 300 seconds.

But it still don't work, 
Is there something I miss ?

**Comment by ssddanbrown** [comment]
@Buliwif How long does it take before it times out? 

You should be able to test this quickly via the standard BookStack user interface. Just export the book to PDF in the UI. Does the same actions in the background.

**Comment by Buliwif** [comment]
It takes about 20 seconds, from interface and from cli. Far from the 90s I set in the php.ini.

**Comment by ssddanbrown** [comment]
@Buliwif Ah, this timeout is probably for a different php.ini than the one you edited for the certificate stuff. This'll be relevant to the php.ini used by Apache. Likely the `/etc/php/<7.3 OR 7.4 OR 8.0>/apache2/php.ini` file

**Comment by Buliwif** [comment]
So strange...

I try to increase the both values on all my php.ini files :
`max_execution_time=300`
`upload_max_files=20M`
Moreover, I try to set no limit in all my php.ini files : 
`max_execution_time=90`
`upload_max_files=20M`
Another test, I add this in the export-books.php : 
set_time_limit (3000);

Same result...
