### ISSUE TITLE
Error when loading changes and preview pages

### ISSUE THREAD

**Issue by ateliermedia** [BookStackApp/BookStack#309]
### For Feature Requests

Desired Feature:

### For Bug Reports

* BookStack Version: 0.14.3
* PHP Version: 5.6.26
* MySQL Version: 5.6.33

##### Expected Behavior

Load the _changes_ and _preview_ pages when clicking on the appropriate links under the _Page revisions_ screen.

##### Actual Behavior

Getting the message _Whoops, looks like something went wrong._ Full error message attached.
[error.txt](https://github.com/BookStackApp/BookStack/files/768779/error.txt)

**Comment by ateliermedia** [comment]
I don't know if it is the right place, maybe it is due to something else (server issues?) but I didn't know where else to ask.

**Comment by ssddanbrown** [comment]
@ateliermedia Sorry for my late response, Haven't been able to work on the project for a while.

Can reproduce this so does look like a bug. Will try to get a fix out soon to fix.

**Comment by ateliermedia** [comment]
@ssddanbrown Thanks, no problem for the late response. Is there a way to donate to the project?

**Comment by pataar** [comment]
Thanks, I'm having the same problem at the moment.
