### ISSUE TITLE
[Support Request]picture upload problems after let's encrypt certificate enabled

### ISSUE THREAD

**Issue by theonlyone54** [BookStackApp/BookStack#3092]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have a problem witch I cant find a solution for it. maybe someone can put me in the right direction. I have installed Bookstack on Ubuntu server LXC 20.04 on Proxmox. For reverse proxy I'm using NginxProxyManager. So Evrything is working fine when im usuing local on an local Ip, when I go thru NginxProxyManager the Http is working fine, but after I request an  Let's Encrypt certificate after login in I can't upload picuters. Im using the latest version BookStack v21.11.1 
It asking for a login and password ,and after I put it again it just crashes. I can find a solution for it.

### Exact BookStack Version

BookStack v21.11.1 

### Log Content

![Screenshot from 2021-11-30 15-40-57](https://user-images.githubusercontent.com/95184741/144079032-d4845671-0b43-4010-9831-7a0b12d691a6.png)

### PHP Version

7.4

### Hosting Environment

Ubuntu LXC 20.04

**Comment by ssddanbrown** [comment]
Hi @theonlyone54,
Have you updated the `APP_URL` variable in the `.env` file to match your new `https://` address?

**Comment by theonlyone54** [comment]
> Hi @theonlyone54, Have you updated the `APP_URL` variable in the `.env` file to match your new `https://` address?

thank you, after changing this to https everything works now.

**Comment by ssddanbrown** [comment]
Great! will therefore close this off.
