### ISSUE TITLE
[API Request]: Matched content preview/excerpt in api/search result

### ISSUE THREAD

**Issue by amelszg** [BookStackApp/BookStack#3096]
### API Endpoint or Feature

Hello, are there any plans to add search content preview/excerpt to search API result, similar to current search results in Bookstack UI?

![image](https://user-images.githubusercontent.com/50396711/144609046-71a7f6f3-9f71-49a7-9142-3516dffa2b73.png)

Thanks for the app :)

### Use-Case

Display additional context for each hit/match in result list when using search API.

**Comment by ssddanbrown** [comment]
Thanks for the request @amelszg.

We could add this but it would be under the following conditions:
- The contexual previews are a rough representation only. They don't actually relate to how an item was matched/scored within the context of the search results.
- It would be provided in HTML (Simple text with `strong` tags). I don't want to expand maintenance surface area to support other formats. 

Does that sound acceptable?

**Comment by amelszg** [comment]
Hi @ssddanbrown, yes, both conditions are fine, thanks a lot!

**Comment by ssddanbrown** [comment]
Thanks for confirming @amelszg.

This has now been added in b22dd3cb88335b362fdc5989e818829798d6658b to be part of the next patch release.
