### ISSUE TITLE
Broke install after editing Custom HTML head content

### ISSUE THREAD

**Issue by domainzero** [BookStackApp/BookStack#310]
I edited my Custom HTML head content and submitted before I was able to finish closing a tag now the page doesn't load completely.

Is there a location the custom html head is stored that I can edit to fix this?

**Comment by domainzero** [comment]
Found it in my database. Nevermind!

**Comment by ssddanbrown** [comment]
Glad you found a fix but I'm going to re-open this as you shouldn't have to edit the database if you accidentally miss a tag. Thanks for reporting.

**Comment by domainzero** [comment]
Thanks for the reopen and fix!
