### ISSUE TITLE
[Support Request]: Are there any paid subscriptions ?

### ISSUE THREAD

**Issue by Sx3** [BookStackApp/BookStack#3107]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

WE are interested in paid subscriptions for bookstack.

### Exact BookStack Version

v21.11 

### Hosting Environment

CentOP 7

**Comment by ssddanbrown** [comment]
Hi @Sx3,
The only subscriptions I currently offer are those on my GitHub sponsors page: https://github.com/sponsors/ssddanbrown
These don't really offer anything back though apart from some advertisement points in the latter tiers. 

Did you have something specific in mind in regards to what you'd want from a subscription?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
