### ISSUE TITLE
[Feature Request]: UID for Shelves, Books, Pages so links won't break

### ISSUE THREAD

**Issue by luminous706** [BookStackApp/BookStack#3114]
### Describe the feature you'd like

Every shelves, books, and pages to have a unique ID, so that renaming them won't break links.

### Describe the benefits this feature would bring to BookStack users

Sharing links and people bookmarking links won't break if a shelf, book, or shelf gets renamed.

**Comment by ssddanbrown** [comment]
Thanks for the request @luminous706.

I'm going to close this off as a duplicate since I feel the fundamental request is already covered or being discussed within #732, #1969 & #1781.
