### ISSUE TITLE
[Feature Request]: Export & Import Entire Site, Books, Shelves from the web interface

### ISSUE THREAD

**Issue by partoneoftwo** [BookStackApp/BookStack#3115]
### Describe the feature you'd like

This very good Wiki software solution needs a stable way to get data in and get data out.
It should be possible to perform these actions from the web interface. This is so because the roles of the data steward and the system administrators are not always held by the same person. 

### Describe the benefits this feature would bring to BookStack users

Easier to trust the data one have entrusted onto this wiki. Easier for users to self mange their instances.
Easier to sleep at night.

A more stable data format for end users over the long run.

A sharable and importable "bookstack pack" can become a thing.

### Additional context

I would be happy to chip in, pay money to see this developed.

**Comment by ssddanbrown** [comment]
Hi @partoneoftwo,
I'm going to close this off as a duplicate since you already have this covered in your previous request in #2405.
