### ISSUE TITLE
An error occurred when saving pages\books, etc after upgrading to 21.12

### ISSUE THREAD

**Issue by southeasterntech** [BookStackApp/BookStack#3124]
I believe I'm getting a similar error after upgrading to 21.12, with no webhooks enabled.  

"So for example, create a new page, hit save and I get an internal error. The upside is that the new page does get created, same as any other operation (delete, move, comment) but all happen after the internal error."

This is what I'm getting on our own self-hosted server on our LAN running Ubuntu 20.04

![image](https://user-images.githubusercontent.com/45638572/147501794-715d6580-9432-495f-a4ff-cacba3470082.png)

_Originally posted by @southeasterntech in https://github.com/BookStackApp/BookStack/issues/3122#issuecomment-1001713579_

**Comment by southeasterntech** [comment]
Here's the debug:
Error

Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.webhooks' doesn't exist (SQL: select * from `webhooks` where exists (select * from `webhook_tracked_events` where `webhooks`.`id` = `webhook_tracked_events`.`webhook_id` and (`event` = book_update or `event` = all)) and `active` = 1)

![image](https://user-images.githubusercontent.com/45638572/147502725-20c2ed62-ab07-4e2e-b606-b943b6b8c5c5.png)

**Comment by ssddanbrown** [comment]
Hi @southeasterntech,
Based upon that error it looks like the database migrations have not ran for the webhooks table.

Can you confirm the output of the `php artisan migrate` step of the BookStack update process?

**Comment by southeasterntech** [comment]
I did run the command originally from the documentation:
"git pull origin release && composer install --no-dev && php artisan migrate"

But, don't recall if it was successful or not.  I did create a snapshot of this server, so I can roll back if necessary.   I went ahead and ran the following again:

"php artisan migrate" and got the following result.
![image](https://user-images.githubusercontent.com/45638572/147503348-0fc06337-0691-42d9-afdb-82c6efcb16a9.png)

After attempting to recreate the issue now, the error message has now gone away and saving of the book was successful without error.

What about the above jobs table error though?

Thanks Dan for your help
Shane

**Comment by southeasterntech** [comment]
Thanks for the very awesome bookstack and the rapid support.  Sending $$ your way via sponsor.  Keep up the good work

**Comment by ssddanbrown** [comment]
Thanks @southeasterntech, Happy to hear things are now working and thanks for the sponsor! Will therefore close this off.

> What about the above jobs table error though?

There are no errors in your screenshot in the last message. The `create_failed_jobs_table` parts are in reference to a new table called `failed_jobs` which are just part of the system to support the new webhook abilities.
