### ISSUE TITLE
[Feature Request]: set focus on Search field on Insert Link Entity Select dialog

### ISSUE THREAD

**Issue by dudeskeeroo** [BookStackApp/BookStack#3127]
### Describe the feature you'd like

When inserting a link (`ctrl-k`) and clicking the search icon, it would be nice to have the Search field gain focus automatically.

![image](https://user-images.githubusercontent.com/16234856/147619096-2071c606-00fc-4682-9b8d-b95a3a76006f.png)

### Describe the benefits this feature would bring to BookStack users

This will reduce keyboard->mouse->keyboard transitions, thus enhancing user workflow.

It would allow the immediate typing of a search term, or allow a user to TAB to the list of pre-populated pages for keyboard navigation.

Currently, TABbing on the Entity Select dialog cycles the cursor between fields on the shadowed Insert Link dialog underneath. There is no way to use the Entity Select dialog without a mouse.

### Additional context

Sorry if this has come up before ... I did search, honest!

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @dudeskeeroo.
This has now been implemented, to be part of the next patch release (v21.12.1).
