### ISSUE TITLE
[Bug Report]: Erratic pasted code content behavoiour upon page save

### ISSUE THREAD

**Issue by noxtras** [BookStackApp/BookStack#3133]
### Describe the Bug

When pasting text from a html pre element (like code samples), the editor goes berserk. It shows everything correctly, but when saving the page, it asks if I'm sure I want to navigate away. If I click yes, the page is saved, but all the other code blocks on the page get doubled somehow: each line in the other code samples becomes a separate code block inside it's main code block...

### Steps to Reproduce

1. Copy a code sample from https://kinsta.com/blog/xmlrpc-php/, but any text inside a pre is the same, from what I've tested.
2. create a document in bookstack and add a code block with a few lines, save
3. Paste inside the created page (that already has a code block). (The new code block you add after the existing block(s), on an empty white space.)
2. Click save.

### Expected Behaviour

either copy as text (clean all formatting) or insert as code block

### Exact BookStack Version

21.10.3

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.4 LTS, Apache + Nginx

**Comment by ssddanbrown** [comment]
Thanks for reporting @noxtras.
This has been patched to be part of v21.12.1. 

This wasn't caused by any pre blocks, but code blocks on other sites, with certain formatting, could confuse and break our parsing logic which would then break the editor. The patch adds more extensive and safer language parsing.

**Comment by noxtras** [comment]
super
