### ISSUE TITLE
[Feature Request]: make a sidebar like gitbook.

### ISSUE THREAD

**Issue by hansism** [BookStackApp/BookStack#3147]
### Describe the feature you'd like

It would be nice to be able to make the table of contents of the book in the form of a menu like the sidebar of a gitbook.

### Describe the benefits this feature would bring to BookStack users

The interface with the table of contents for the book on the right is a very familiar way to use it very widely. I earnestly hope that you will develop such an interface.

**Comment by ssddanbrown** [comment]
Thanks for your request @hansism.

Interface alignment with other platforms is not something I'd desire, nor is a reason to make changes to the interface. BookStack is it's own product, we're not defined as a direct alternative to other offerings.

Changing the interface and/or structure would require significant reasoning in regards to how it benefits existing BookStack users, not how it would suit users looking for something similar to another product. The request doesn't really explain what we'd need to change (In comparison to the current book sidebar offerings) and the stated benefit is provided without evidence to the claim of familiarity. Most existing BookStack users are going to be familiar with the current approach.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to therefore close this off.
