### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Kosstrov** [BookStackApp/BookStack#3155]
### Describe the Bug

PDF exported from our site has problems with images (check images). 

p.s Since our wiki is for internal usage I can't share the link, sorry. 

### Steps to Reproduce

1. Go to https://demo.bookstackapp.com/login?email=admin@example.com&password=password
2. Click Export 
3. Select PDF
4. Check downloaded PDF or picture below

### Expected Behaviour

![image](https://user-images.githubusercontent.com/53850009/148873427-28908a8b-0450-4d8c-922d-c85f7239a790.png)

### Screenshots or Additional Context

PDF: 

![Screenshot 2022-01-11 114026](https://user-images.githubusercontent.com/53850009/148873461-8fa0cb1a-d8b5-4f38-892d-0b4025b446f0.png)

### Exact BookStack Version

v21.12.2

### Hosting Environment

CentOS 8

**Comment by ssddanbrown** [comment]
Hi @Kosstrov,

- Does this occur for images that are uploaded fresh via BookStack's image manager? 
- If you look at the source code for the page content being exported (Code button to the right of the editor toolbar in page editor) are these images (`<img src="<link>"/>` parts)  linked to your BookStack instance URL or an external URL?

**Comment by Kosstrov** [comment]
Thank you @ssddanbrown ! 
Everything working fine ... however pics are not aligned in PDF:

![image](https://user-images.githubusercontent.com/53850009/149053597-7abf4500-77d9-4047-a2ee-ffde89b19ebc.png)

**Comment by Kosstrov** [comment]
Just readd all pics and it helped, thank you.
