### ISSUE TITLE
[Feature Request]: content translations

### ISSUE THREAD

**Issue by vrozkovec** [BookStackApp/BookStack#3159]
### Describe the feature you'd like

Ability do define a set of languages that each page header and page content would be translatable to.
Ability to select a default fallback language.

If user selects a translation, then whole site switches to that language and shows shelves, books, chapters, pages etc. in that language, if such translation exists, otherwise falling back to default language.

### Describe the benefits this feature would bring to BookStack users

Clearer UI/UX when dealing with multinational teams that require content in their own language. 
Currently the only way is to have several pages siting next to each other or copying shelf / book / chapter hierarchy to different language.

### Additional context

For inspiration:

Screenshot from Wikipedia - clicking the link gives you the page in different language
![image](https://user-images.githubusercontent.com/135681/149190982-44155945-d5b8-41ca-ae76-befcdd467d40.png)

Wordpress editor with WMPL plugin
![image](https://user-images.githubusercontent.com/135681/149201830-cee13440-cd6f-4b78-a880-fc0f54d3dc1c.png)

My context:
A company that teaches languages. Native speakers from various parts of the world record sentences, some speakers don't speak another than their mother language so we need to have instructions available to them as well.

**Comment by ssddanbrown** [comment]
Thanks for the request @vrozkovec but this has already been requested in  #569 so I'm going to therefore close this off as a duplicate.
