### ISSUE TITLE
On user creation, Provide option to email the user a link to set their own password

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#316]
### For Feature Requests

Desired Feature:  Generate a random password and email the user when and administrator creates a new account.

##### Expected Behavior

When an admin creates a new user account, the option should exist to generate a random password and have the new account information sent to the user via email.  This way the administrator does not have the ability to see the password.  Additionally, the user should be promoted to create a new password on first sign-in.

##### Actual Behavior

The administrator must manually specify a password and give it to the user.  The administrator must also instruct the user to change their password, which does not always happen.

**Comment by ssddanbrown** [comment]
@tuaris Thanks for the suggestion. I agree, This would be a great feature to improve security and to make the lives to admins easier.

**Comment by ssddanbrown** [comment]
Promoting this to the next release since it provides a good level of extra security and eases administration. Title updated for clarity. 

I think the email => Set password flow should be the default action, with the admin having the choice to not notify and set a password manually if needed.

**Comment by ssddanbrown** [comment]
This is now in master, Ready for when v0.27 is release. This will be the default action:

![image](https://user-images.githubusercontent.com/8343178/63224769-a6554b00-c1c0-11e9-8b35-7340b9f4e273.png)
