### ISSUE TITLE
[Bug Report]: when uploading more than one image, once upload finishes, UI shows multiple instances of one image

### ISSUE THREAD

**Issue by vrozkovec** [BookStackApp/BookStack#3160]
### Describe the Bug

When uploading more than one image, once upload finishes, UI shows multiple instances of one image.

### Steps to Reproduce

Fresh install, trying to upload several images at once, clicking grey button at the top right corner
![image](https://user-images.githubusercontent.com/135681/149205016-8da5528a-49a0-4078-a499-ef01ac652328.png)

Selecting two images, hitting upload
![image](https://user-images.githubusercontent.com/135681/149205596-95bd87e9-1721-4142-80a3-e463d4315a4c.png)

State after upload finishes:
![image](https://user-images.githubusercontent.com/135681/149205674-666a2e30-8658-4d12-adb3-d5176453c34e.png)

### Expected Behaviour

Each uploaded image shows only once after uploading.

### Exact BookStack Version

BookStack v21.12.2

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04 VM
Nginx

**Comment by ssddanbrown** [comment]
Thanks for reporting @vrozkovec. Can confirm this issue and have patched within 4aed3f8558c429d95bdc8a987d72a6a9f6df7267 which will be part of the next patch release.
