### ISSUE TITLE
[Bug Report]: Tiny images on PDF export

### ISSUE THREAD

**Issue by joransrb** [BookStackApp/BookStack#3163]
### Describe the Bug

Exporting to PDF renders the images tiny.
Viewing and HTML works just fine

### Steps to Reproduce

1. Create page, add image trough upload dialog.
2. Save page and view, all is fine
3. Export page to HTML, all is fine
4. Export to PDF, images are tiny

### Expected Behaviour

Images to be the same as HTML view / export

### Screenshots or Additional Context

Here is a screen snippet of a correct view / html export:
![normal-image](https://user-images.githubusercontent.com/239341/149396365-f7087d45-83ec-49db-aa60-6e56a61ca8ea.png)

And here is a snippet of a PDF export woth the same image, its tiny:
![tiny pdf image](https://user-images.githubusercontent.com/239341/149396429-14a81d0c-9bb1-4fc9-877b-794ab2a41aef.png)

### Exact BookStack Version

v21.12

### Hosting Environment

I am using the https://docs.linuxserver.io/images/docker-bookstack docker container.

**Comment by watschi** [comment]
This should be fixed in [v21.12.1](https://github.com/BookStackApp/BookStack/releases/tag/v21.12.1) (duplicate of #3120)

**Comment by joransrb** [comment]
thanks for the info, i tried searching for a similar issue but didnt see that one.
