### ISSUE TITLE
[Feature Request]: Allow disable SMTP certificate verification

### ISSUE THREAD

**Issue by azhinu** [BookStackApp/BookStack#3166]
### Describe the feature you'd like

I didn't find any way to use SMTP server with self signed certificate.

It would be great to have an option like 'MAIL_TLS_VERIFICATION=true/false'

To allow insecure certs we need only add folowing to [app/Config/mail.php](https://github.com/BookStackApp/BookStack/blob/master/app/Config/mail.php)
```
'stream' => [
   'ssl' => [
       'allow_self_signed' => true,
       'verify_peer' => false,
       'verify_peer_name' => false,
   ],
],
```

### Describe the benefits this feature would bring to BookStack users

Sometimes users need to use self signed certificates and usually services allow to disable TLS verification, but not bookstack.

**Comment by lue30499** [comment]
I would like this as well. I have a local server just for email notifs that I just have a self-assigned cert on.

**Comment by ssddanbrown** [comment]
An alternative solution is to add your certificate CA to the host's trusted certificate store, that way I don't think you'd need to then disable additional security options.

**Comment by azhinu** [comment]
@ssddanbrown it's too complicated for quick local testing purposes.

**Comment by MDKAOD** [comment]
+1 on this request. I can confirm that the merged code works. I modified mail.php and I was able to use smtp. Sendmail was not working and threw an empty request received 220 error. Any chance this will be pushed?

**Comment by rockenren** [comment]
Upvote for adding this feature as option.

If I remember correctly, smtp without certificate validation worked some versions ago (I have test email from March, 2022 in my mailbox from our bookstack instance, mail server always have self-signed certificate).

**Comment by a-carvallo** [comment]
Had this issue after updating bookstack, though the option for ssl didn't work for me since its location seems to have moved with Laravel 9 (https://github.com/laravel/framework/discussions/41385).

I also get @ssddanbrown's concerns in https://github.com/BookStackApp/BookStack/pull/3439 but in my case it's a local SMTP server with no security at all basically.

**Comment by talesrodarte** [comment]
That functionality would be great. It is always necessary to correct in other ways and that takes time. It is very common for email servers to have self-signed certificates.

**Comment by ssddanbrown** [comment]
This has now been added as per of #4126. Will be part of the next feature release.
The setting to add to your `.env` fill be as follows:

```bash
MAIL_VERIFY_SSL=false
```
