### ISSUE TITLE
[Feature Request]: Protected 'blocks' of content

### ISSUE THREAD

**Issue by JoeIzzard** [BookStackApp/BookStack#3167]
### Describe the feature you'd like

The ability to set certain parts of a page to a different permission level. For example a page where most of the content can be viewed publicly but a certain section is restricted to only a certain role.

### Describe the benefits this feature would bring to BookStack users

Currently if certain information should only be viewed by a specific role, that would require a separate page with page level permissions, which works in a lot of cases. However, with this method all the content that should be on a page can be kept together with just a certain section restricted.

### Additional context

Not the best example, but take a page describing how to reset your password on a certain service. Most of the page can be public, how the end user can reset their own password, change it if they know it etc, but the section that talks about how to reset the password of an account as an admin of the service should be restricted to only the admins to see. This allows you to keep the entire 'Reset Password' documentation in one page, and not forgo any security or permissions settings.

One caveat would be in editing. The edit ability for the page would still likely have to lie with the Page Permissions, but you could work around that by displaying a warning that sensitive information can be revealed when editing and such.

**Comment by ssddanbrown** [comment]
Thanks for the request @JoeIzzard.
This has been previously requested within #978 which mentions a method to achieve this with current functionality.
Unless there's further context to add upon that I'll likely look to close this off as out of scope with the same reasoning as given on #978.

**Comment by JoeIzzard** [comment]
Thanks for the pointer! I had searched but nothing came up similar, nice to see a workaround that will do.

**Comment by ssddanbrown** [comment]
No worries, will therefore close this off.
