### ISSUE TITLE
[Feature Request]: able to set custom slug when creating bookshelve, book and etc...

### ISSUE THREAD

**Issue by Antares95** [BookStackApp/BookStack#3169]
### Describe the feature you'd like

Request to add a optional field on create page to allow user set a custom slug.

### Describe the benefits this feature would bring to BookStack users

This may very useful for CJK (Chinese Japanese Korean) users.

**Comment by ssddanbrown** [comment]
Hi @Antares95,
Thanks for your request.

> This may very useful for CJK (Chinese Japanese Korean) users.

I would need to know the benefits it would bring here. What does it allow or achieve for this group of users?

Generally I wouldn't want to add in an meta-level optional input field. In the future I'd be looking to change the URL scheme to be non-slug-based (For content at least) which would make this redundant. Will be a while though before we move to that scheme.

**Comment by Antares95** [comment]
Hi @ssddanbrown ,
Thanks for your reply.
Currently BookStack’s slug can`t recognize CJK character and just ignore them. If some books name is full of CJK character, it just generate a random hexdecimal string for the slug name. This may look strange in the URL address.
But I agree your point of view, a non-slug-based URL scheme will be a batter solution.
