### ISSUE TITLE
[Feature Request]: Library, book, page, chapter aliases

### ISSUE THREAD

**Issue by xplosionmind** [BookStackApp/BookStack#3175]
### Describe the feature you'd like

Suppose I create a book (or a library, or a page, or a chapter) named “TMI”. That title is useful if I know what I am looking for and what it stands for, but it is crucial to be able to set an alias, in this case “Too Much Information” that makes finding it easier and clarifies the meaning.

### Describe the benefits this feature would bring to BookStack users

Empowering even more the search feature, by allowing users to look for synonyms that might be used as aliases of pages’ titles.

### Additional context

The vast majority of Wikis support this kind of redirection/multiple naming. See for example Wikipedia and/or Obsidian.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @xplosionmind but I'm trying to keep away from adding meta fields which would likely have little use, especially where it influences discovery with little actual visibility.

You could achieve this using the existing tag system or description fields (On shelves/book/chapters).

**Comment by xplosionmind** [comment]
> I'm trying to keep away from adding meta fields which would likely have little use, especially where it influences discovery with little actual visibility.

If you believe that implementing this would make more of a mess rather than improvement, I do not really agree, but I trust your judgement, since it is much better informed, of course.

<br>

> You could achieve this using the existing tag system or description fields (On shelves/book/chapters).

This is not optimal, but a still effective workaround. Thank you for the suggestion!

**Comment by ssddanbrown** [comment]
Will therefore close this off
