### ISSUE TITLE
Feature Request: Built in image editor, screen capture, drawing tools

### ISSUE THREAD

**Issue by caroberto6** [BookStackApp/BookStack#318]
### For Feature Requests

Desired Feature: It would be nice to have built in screen capture and attach directly in the page function, image editor, and drawing tools for creating user guides.

Something like this: http://stepshot.net/

Thank you!
Robert

**Comment by ssddanbrown** [comment]
Hi @caroberto6, This would be a nice feature to have but creating & maintaining something like this would require a lot of work. Therefore I think i'd only implement if there was a good open-source project which I could plug-in.

As a side note, If you're on windows [Greenshot](http://getgreenshot.org/) is a great tool for screen capture and annotation. You can copy from screenshot and paste directly into BookStack pages.

**Comment by ssddanbrown** [comment]
I'm going to close this as the initial request is a little too broad and too large in scope for this project.
We now have some embedded drawing tools. Image editing and screen capture are things I think are best left to other, more system level applications.
