### ISSUE TITLE
[Feature Request]: recently-updated - in profile settings as a start page

### ISSUE THREAD

**Issue by mlipok** [BookStackApp/BookStack#3180]
### Describe the feature you'd like

Add option in the profile settings for start page to open https://MYURL/pages/recently-updated
![image](https://user-images.githubusercontent.com/11089482/150315597-750764dd-0848-4395-acd5-a250e3f80017.png)

### Describe the benefits this feature would bring to BookStack users

I think that the person who is a manager should like to start with checking what's new.

**Comment by ssddanbrown** [comment]
Thanks for the request @mlipok but I think this would be too specific since it's little desired and the custom start pages require extra support due to the homepage sidebar content we show. 

I'd instead look to  #1519 as a generic solution to achieving what you desire.
