### ISSUE TITLE
[Feature Request]: sort pages on article update

### ISSUE THREAD

**Issue by SimpelMe** [BookStackApp/BookStack#3181]
### Describe the feature you'd like

I would like to have pages sorted by article update date automatically. Means, if I update an article page sorting will be adapted. Currently I have to "hit a button" manually for this and it looks like a longer process to me. (Is that sorting written into database?)

### Describe the benefits this feature would bring to BookStack users

I mostly use articles I wrote recently more then all others. So I like to see them on top.

Beside: If one sorts by article name/title and one writes a new article this will be sorted alphabetically instantly.

**Comment by SimpelMe** [comment]
Funny #3180 could solve my personal wish too. 
But my feature request is more general I think. At the end it mustn't sorted this way but shown this way. Maybe an easier approach?

**Comment by ssddanbrown** [comment]
Thanks for the request @SimpelMe but I'm going to close this due to the fundamental request already being covered by issues #180 and #2065.
