### ISSUE TITLE
[Bug Report]: Owner of books/shelves can't see their own, if custom permissions selected

### ISSUE THREAD

**Issue by ddaniel15** [BookStackApp/BookStack#3185]
### Describe the Bug

I've created books and shelves and tryed to hide them befor publishing. 
In the permissions i select "enable custom permissions" and nothing other. 
For now i can't see my own books/shelves.

### Steps to Reproduce

1. Create book
2. Go to permissions
3. Select  "enable custom permissions"
4. Save

### Expected Behaviour

access to the book - as the owner of the book.

### Exact BookStack Version

21.12.1

### PHP Version

8.*

### Hosting Environment

ubuntu 20.04

**Comment by ssddanbrown** [comment]
Hi @ddaniel15,
This isn't really a bug, but an expected affect of the permission system, of setting permissions more restrictive than your own visibility.

The ability for owners to always see their content has already been requested in #2697 so I'll therefore close this off.

Note, Users assigned the original "Admin" role should retain visibility of anything so should be able to undo your permission control changes.

**Comment by ddaniel15** [comment]
Hello @ssddanbrown,
thanks for reply and for BookStack!
regards
