### ISSUE TITLE
[Feature Request]: Ability to add tables side-by-side

### ISSUE THREAD

**Issue by patsyk1** [BookStackApp/BookStack#3187]
### Describe the feature you'd like

Apologies if this is a feature and I've just not figured it out, but please could we get the ability to add tables side by side in a page? Similar to how we can have pictures side by side. 

### Describe the benefits this feature would bring to BookStack users

It would save a lot of page space/scrolling for pages that contain numerous tables of information. Especially if said tables are only 2/3 columns at best.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @patsyk1, but I'm going to close this off for the following reasons:

- There has been little additional demand for this feature.
- Tables are already limited in flexibility, which allowing use within more complex layouts would only exacerbate.
- I'd prefer not to complicate the core content layout capabilities where possible, to keep content as portable where possible.
