### ISSUE TITLE
[Support Request]: css not loading

### ISSUE THREAD

**Issue by monarrk** [BookStackApp/BookStack#3188]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

The same as the couple of issues before this one, the CSS for bookstack isn't loading on my site (https://wiki.5066.team). I'm using lighttpd on FreeBSD. It seems to function normally, just with no CSS.

this is my lighttpd vhost configuration:
```
$HTTP["host"] == "wiki.5066.team" {
        var.server_name = "wiki.5066.team"

        server.name = server_name
        ## example how to include another config:
        ## use trigger before download
        ## 
        # include "conf.d/trigger_b4_dl.conf"

        server.document-root = "/usr/local/www/bookstack/public"
        ##
        ## use a seperate access log file
        ## At the moment you cant have different error log files.
        ##
        accesslog.filename          = log_root + "/" + server_name + "/access.log"
        server.errorlog = log_root + "/" + server_name + "/error.log"

        # fix bookstack routing
        url.rewrite-once = ( "/*$" => "/index.php?${qsa}" )
}
```

### Exact BookStack Version

v21.12.2

### Log Content

2022-01-21 08:08:35: (gw_backend.c.285) establishing connection failed: socket: tcp:127.0.0.1:9999: Connection refused

### PHP Version

PHP 8.0.14 (cgi-fcgi) (built: Jan  2 2022 01:17:28)

### Hosting Environment

FreeBSD 13.0 with lighttpd/1.4.63

**Comment by monarrk** [comment]
Ah that was it! I had to change the rewrite rule to `url.rewrite-if-not-file`. Thank you!

**Comment by ssddanbrown** [comment]
Glad to hear it's solved! Will therefore close this off.
