### ISSUE TITLE
[Support Request]: Blank page after inserting 3rd party auth. - Azure

### ISSUE THREAD

**Issue by davecowley** [BookStackApp/BookStack#3189]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After adding the below to my .env file the site gives a blank page.  remove the code and its back to fully functioning.

```
{SERVICE}_AUTO_REGISTER=true
AZURE_AUTO_REGISTER=true
{SERVICE}_AUTO_CONFIRM_EMAIL=true
AZURE_AUTO_CONFIRM_EMAIL=true
````

I guessed that it was azre, the example was google and twitch.

Azure config is all ok as I can pair Azure with my account in users and it works fine.  

permissions are all ok and have performed sudo chown -R www-data:www-data bootstrap/cache storage public/uploads

### Exact BookStack Version

21.12

### PHP Version

7.4.27

### Hosting Environment

Server 2019 Hyper-V, Ubuntu 18.04.6 LTS

**Comment by ssddanbrown** [comment]
Hi @davecowley,
Can you remove the likes starting with `{SERVICE}`? So only keep the lines starting with `AZURE`. The {SERVICE} lines in the documentations are examples to show syntax, they are not needed themselves and are likely causing your config to break.

**Comment by davecowley** [comment]
Hi, yes your right.  totally obvious looking back

thanks for your help.
