### ISSUE TITLE
Feature Request: Checkboxes for to-do lists and more

### ISSUE THREAD

**Issue by Agent01** [BookStackApp/BookStack#319]
### For Feature Requests

Desired Feature: 
- [ ] Checkboxes like this!
markdown checkboxes  using \- [ x ] like the ones here: https://github.com/blog/1825-task-lists-in-all-markdown-documents

##### Expected Behavior
- [x] checkboxes! 
##### Actual Behavior
- Bulletpoints :(

**Comment by LeonLiuY** [comment]
Can we do this in WYSIWYG editor?
