### ISSUE TITLE
[Feature Request]: Recently upadted publicly available, and checking for changes to the version

### ISSUE THREAD

**Issue by mlipok** [BookStackApp/BookStack#3192]
### Describe the feature you'd like

in publicly available
https://......./pages/recently-updated

Please add possibity to add access to revisions for publicly available content.

### Describe the benefits this feature would bring to BookStack users

in publicly available
https://......./pages/recently-updated

I was wondering how people that publicly accessing some of my books, can check what exactly was changed.
I see the topic lists but how to give public viewers the chance to see what exactly is new ?

I would like to give them possiblity to acces to this:

https://......./books/........./page/....../**revisions**

I mean this "Wersje" feature marked by BLUE SQUARE.
![image](https://user-images.githubusercontent.com/11089482/150637171-fe953233-a856-4eba-8bfc-f7103b357841.png)

btw.
"Eksportuj" feature marked by GREEN SQUARE is already available on public https://......./pages/recently-updated

### Additional context

This Feature Request is related to:
https://github.com/BookStackApp/BookStack/issues/3045
https://github.com/BookStackApp/BookStack/issues/3183

**Comment by ssddanbrown** [comment]
Hi @mlipok,
The visibility of these is not linked at all to the `/recently-updated` view. It's simply part of the page display view.
The request to show the revision button to viewers is already open under #2946 so I'll therefore close this off as a duplicate.
