### ISSUE TITLE
[Bug Report]: Base table bookstack.webhooks doesn't exist

### ISSUE THREAD

**Issue by unpokitodxfavor** [BookStackApp/BookStack#3198]
### Describe the Bug

When i try to go to webhook settings i get an error

An unknown error occurred

### Steps to Reproduce

1. Go to settings
2. Webhooks
3. error

### Expected Behaviour

Illuminate\Database\QueryException SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.webhooks' doesn't exist (SQL: select * from `webhooks` order by `name` desc)

### Exact BookStack Version

v21.12.2

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 20.04 VPS

**Comment by ssddanbrown** [comment]
Hi @unpokitodxfavor,
When you run the `php artisan migrate` step of the update commands do you get any errors? Did you see any errors on last update?

**Comment by unpokitodxfavor** [comment]
I have upgraded to BookStack v21.12.3 and now I can add webhooks.
Fixed

  - Upgrading laravel/ui (v3.3.2 => v3.4.1): Extracting archive
  - Upgrading aws/aws-sdk-php (3.202.2 => 3.209.11): Extracting archive
  - Upgrading league/oauth2-client (2.6.0 => 2.6.1): Extracting archive
  - Upgrading paragonie/constant_time_encoding (v2.4.0 => v2.5.0): Extracting archive
  - Upgrading phpseclib/phpseclib (3.0.11 => 3.0.12): Extracting archive
  - Upgrading predis/predis (v1.1.9 => v1.1.10): Extracting archive
  - Upgrading socialiteproviders/manager (4.0.1 => v4.1.0): Extracting archive
  - Upgrading ssddanbrown/htmldiff (v1.0.1 => v1.0.2): Extracting archive
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
In StreamHandler.php line 146:
                                                                                                                  
  The stream or file "/var/www/bookstack/storage/logs/laravel.log" could not be opened in append mode: failed to  
   open stream: Permission denied                                                                                 
                                                                                                                  
57 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan cache:clear
Failed to clear cache. Make sure you have the appropriate permissions.
> @php artisan view:clear
Compiled views cleared!
**************************************
*     Application In Production!     *
**************************************
 Do you really wish to run this command? (yes/no) [no]:
 > yes
Migrating: 2021_11_26_070438_add_index_for_user_ip
Migrated:  2021_11_26_070438_add_index_for_user_ip (59.86ms)
Migrating: 2021_12_07_111343_create_webhooks_table
Migrated:  2021_12_07_111343_create_webhooks_table (152.55ms)
Migrating: 2021_12_13_152024_create_jobs_table
Migrated:  2021_12_13_152024_create_jobs_table (59.76ms)
Migrating: 2021_12_13_152120_create_failed_jobs_table
Migrated:  2021_12_13_152120_create_failed_jobs_table (47.00ms)
Migrating: 2022_01_03_154041_add_webhooks_timeout_error_columns
Migrated:  2022_01_03_154041_add_webhooks_timeout_error_columns (23.19ms)
