### ISSUE TITLE
[Bug Report]: selecting multiple lines to make them code block

### ISSUE THREAD

**Issue by noxtras** [BookStackApp/BookStack#3200]
### Describe the Bug

When I have multiple lines and I select them and click on 'code block', all the paragraphs on the page get smushed to one line. 
Strangely, if I select the same paragraphs and select block quote, it works perfectly.
Unrelated, but requires same bug fix: If I shift+enter some lines and then select code block, the entire paragraph gets smushed to a single line inside the code block. Again, block quote works as expected.

### Steps to Reproduce

New document
add a few lines of text, some with SHIFT+ENTER
select 2 lines from either the enter delimited and shift+enter delimited text and click code block.

### Expected Behaviour

It has to be like the block quote, retain line endings, so if you have 2 lines with an ENTER between them (2 paragraphs), the code block needs to be "line1, empty line, line2" , and if you have a paragraph with multiple lines, it needs to be "line1,line2".

### Exact BookStack Version

v21.12.2

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.4 LTS

**Comment by Julesdevops** [comment]
I will look into this and try to provide a fix

**Comment by noxtras** [comment]
Thank you. I'm reporting these bugs, for a more complete list of them. Bookstack is amazing as it is. I've moved from Confluence, that constantly crashed (some ini file). 
I hope you don't, but please don't feel like you have to fix these reported issues with priority, or at all.

**Comment by ssddanbrown** [comment]
This should now be addressed thanks to @Julesdevops in #3246 and some follow up changes in b2f863e1f18ab9997dc43178ef53bc04b849e10c. This will be part of the next patch release.

Thanks for reporting @noxtras! Suprised this was not raised earlier to be honest, especially since it attempted to make the whole page into a code block :scream_cat:
