### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by KapustaIKwas** [BookStackApp/BookStack#3201]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Describe the bug
HTTP ERROR 500 when going to site. 

Steps To Reproduce
Going to site, I get HTTP ERROR 500

Expected behavior
I would intend for the site to load.

### Exact BookStack Version

BookStack v21.12.3

### Log Content

PHP Fatal error:  Uncaught Error: Call to undefined method ComposerAutoloaderInit4e5fbf84e4a2bdf796f705349341e084::getLoader() in bookstack/vendor/autoload.php

### PHP Version

PHP 7.4.26 (cli) (built: Nov 19 2021 06:24:55) ( NTS )

### Hosting Environment

Debian 12, Apache

**Comment by ssddanbrown** [comment]
Hi @KapustaIKwas,

- Can you confirm the version of composer in use? (Output of running `composer -V`)
- Do you get any errors during the `composer install --no-dev` step of the update commands?

**Comment by KapustaIKwas** [comment]
Hey @ssddanbrown 

Composer version is:  2.2.4 2022-01-08 12:30:42

When running the install command im getting two PHP Warnings:

1. PHP Warning:  PHP Startup: Unable to load dynamic library 'apc.so' 
2. PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so'

**Comment by ssddanbrown** [comment]
@KapustaIKwas Thanks, I'm assuming there were not other errors running the command and that if you re-run it you see the following line within the output?:

```
Nothing to install, update or remove
```

You could trying deleting the `vendor/` directory within your BookStack install folder, then re-run the `composer install --no-dev` step to see if the issue remains afterwards.

**Comment by KapustaIKwas** [comment]
@ssddanbrown yeah the issue still remains after deleting and reinstalling the composer dependencies.
Could it have something to do with the fact that I'm using debian 12?

Just installed bookstack on a ubuntu 18 system and it works fine.

**Comment by ssddanbrown** [comment]
> Could it have something to do with the fact that I'm using debian 12

Potentially, always an added risk of using pre-release operating systems. Could be something funky in a caching element of the PHP setup.

> Just installed bookstack on a ubuntu 18 system and it works fine.

Okay, is that instead of the debian instance? Alright for me to therefore close this off?

**Comment by KapustaIKwas** [comment]
Yeah sure, thanks for the quick help!
