### ISSUE TITLE
[Feature Request]: Extend user card

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3202]
### Describe the feature you'd like

Add a link to the group in which this user is located in the field circled in the screenshot to understand who is who.
![image](https://user-images.githubusercontent.com/4026090/151114024-58b2caf5-6f78-47f2-ac7a-9a9be66f9cb0.png)

You can also add mail and last activity for clarity.

### Describe the benefits this feature would bring to BookStack users

Convenience

**Comment by ssddanbrown** [comment]
Thanks for the request @Statium.

I'm not sure this is information that should be exposed on user profile pages.
Group membership, email and last activity could all be considered details that may expose confidential information.
Most requirement to know these would be by admins, who can find these details within the admin-side users list anyway.
This profile page shows the latest content activity for the user, for content visible to the viewer, so some idea of latest activity can already be seen.

**Comment by ssddanbrown** [comment]
Due to the above concerns I'm going to go ahead and close this off.
