### ISSUE TITLE
[Bug Report]: "Be back soon" page rendering fails due to usage of `$cspNonce` which is undefined

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#3205]
Probably best to massively simplify this view to not be relying on so much app logic. 

Discovered by @Julesdevops on Discord.

**Comment by Julesdevops** [comment]
@ssddanbrown I started on this, will submit a PR this week end

**Comment by ssddanbrown** [comment]
Fixed in #3210.
