### ISSUE TITLE
[Feature Request]: LDAP Failover

### ISSUE THREAD

**Issue by Cidwill** [BookStackApp/BookStack#3207]
### Describe the feature you'd like

Apologies if this is already something that can be configured but I haven't seen a guide on how if so.

It would be great if the Bookstack .env gave the option to configure an alternative LDAP address that could be used if a lookup fails.  We recently lost access to a DC (thanks Microsoft for January patching fun) and our other DCs could have kept the service alive if Bookstack knew where to look after the first failed lookup.

### Describe the benefits this feature would bring to BookStack users

LDAP logins would continue to function if a single DC was offline or malfunctioning.  Greatly increasing availability of the Bookstack service.

**Comment by ssddanbrown** [comment]
Thank for the request @Cidwill.
Correct me if I am wrong, but I think this may come under the same request of #543?

**Comment by Cidwill** [comment]
Well this would be for multiple DCs within a domain rather than multiple domains but I imagine the actual functionality would be the same so yeah, happy to close off and add to that one.

Thank you for the quick response Dan.  Love your work.

**Comment by Cidwill** [comment]
[#543](https://github.com/BookStackApp/BookStack/issues/543)
