### ISSUE TITLE
[Feature Request]: Interactive question blocks

### ISSUE THREAD

**Issue by Rinma** [BookStackApp/BookStack#3208]
### Describe the feature you'd like

The ability to add an interactive question inside a page. When editing the page, it should be possible to add a question, a variable amount of answers, and an explanation block that can be opened after answering the question. The explanation block should be closed by default to save space. The first answer, when editing, is always the correct one, but when displayed to the reader, the questions should be randomly ordered.

### Describe the benefits this feature would bring to BookStack users

You could do little tests to check if the reader understood the topic, and if not, try to explain it differently afterwards inside the explanation block or show a walkthrough how to get to the correct answer.

### Additional context

![Screenshot 2022-01-28 at 16-44-40 Seite E01 Mathematische Gru bearbeiten BookStack](https://user-images.githubusercontent.com/1405824/151579813-7b2f6d94-eb59-4eac-bf1d-e78ffd7821d9.png)
![Screenshot 2022-01-28 at 16-41-02 Seite E01 Mathematische Gru bearbeiten BookStack](https://user-images.githubusercontent.com/1405824/151579819-700cf38e-5fe7-4520-88c4-2478729b34e3.png)

**Comment by ssddanbrown** [comment]
Thanks for the request @Rinma,

This is quite a specific feature request that'll complicate the content format and therefore make other areas of the application more difficult (Markdown editor, export formats etc..).
My main concern is that introducing quizzing elements widens the scope of the expected content and purposes of the platform. We're not really intending to be a quiz platform. While the scope of your request is reasonable and well-defined, I think that would differ for other users and we'd quickly see demands for extension in this area (Such as saving answers per user, providing results views etc..) and that's not really an are I want to expand into if we are to keep maintenance reasonable.

I feel the fundamental flow could be achieved by more basic block types that are more feasible to support. If we introduced collapsible blocks, as per #78, you could do something like below:

---

#### Example

What is the answer to everything?

- A) 21
- B) 42
- C) 56

<details>
<summary>Answer</summary>

The answer is B) 42.

> This is because the number 42........

</details>

---

**Comment by Rinma** [comment]
Thanks for the answer @ssddanbrown 

I get your concerns. The solution you provide, with a collapsible block, would work for me.

**Comment by ssddanbrown** [comment]
Thank for your understanding and confirmation @Rinma.
I'll therefore close this off since the functionality is requested in #78.

Although #78 has been open for a while, It is something that's possible currently in the markdown editor and something I'm looking to build into the default WYSIWYG editor within the currently progressing work in  #2738.
