### ISSUE TITLE
ID for revision

### ISSUE THREAD

**Issue by ateliermedia** [BookStackApp/BookStack#321]
### For Feature Requests

Desired Feature: Implement revision ID

### For Bug Reports

* BookStack Version:
* PHP Version:
* MySQL Version:

##### Expected Behavior

We have tested the system for a while, we would like to use it in production and we would need to have an id for every revision so it will be easier to refer to (also required by our "ISO stuff"). 
Perfect would be for us to have this information at the bottom of the page, too along with the creation date and last updated info. 

Great app, by the way, easy enough so the "not so tech users" will understand but powerful in the same time.

**Comment by ssddanbrown** [comment]
Hi @ateliermedia,
Happy to hear you like BookStack & thank you for your suggestion. I can see this feature being valuable for users in regards to providing proper record-keeping.

#### Development todo/notes

- [ ] Add revision_count to pages table (Total revisions for that page)
- [ ] Add revision_count to revisions table (Revision 'id' in the context of its related page)
- [ ] Display this information in revisions table and page meta footer
