### ISSUE TITLE
[Feature Request]: Failed Logins in audit log

### ISSUE THREAD

**Issue by cal940** [BookStackApp/BookStack#3211]
### Describe the feature you'd like

Additional event filter in audit log for failed logins

### Describe the benefits this feature would bring to BookStack users

- helpful for admins fixing Login problems of other users
- helpful for preventing unauthorized access to bookstack (e.g. searching for failed logins in bookstack and blocking specific ip addresses / network ranges in server firewall)

**Comment by ssddanbrown** [comment]
Hi @cal940, Thanks for the request.

I generally attempt to keep our internal activity/audit-log tracking to activities that modify system state in some way. Adding logging for this kind of thing can open up other areas of potential abuse and concern (For example, someone abusing the login form with many failed logins to fill the audit log and cause a mass of writes to the database).

We do already have separate specific functionality for logging failed logins:
https://www.bookstackapp.com/docs/admin/security/#failed-access-logging

This is done in a way which can then actually be used by other system tools such as Fail2Ban or manually inspected if desired.

**Comment by cal940** [comment]
Thanks for the workaround. I will check this out on my server.
