### ISSUE TITLE
[Support Request]: Is there a way to make users over API during testing? i.e. Postman, etc.?

### ISSUE THREAD

**Issue by DylanAlloy** [BookStackApp/BookStack#3212]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I see CSRF and bookstack_session and I don't want to run into a situation where I'm basically scraping those cookies to make a POST request. 

Is there a way alternatively to just put users into the DB with SQL if needed without much hassle? I looked in /database/seeders but couldn't find out how any User seeding was occurring.

What's the best way to make something like a curl request and end up with a new user for testing?

### Exact BookStack Version

v21.11-dev

### Hosting Environment

Dockerfile & repo clone

**Comment by ssddanbrown** [comment]
Hi @DylanAlloy,
There's no users API right now but one was started in #2734.
You could interact directly with the database, following the existing format (`users` table primarily) but you may have a challenge or cause issues trying to get the extact right format, aligned to what the interface would do, especially in terms of connecting up relations.

The only official way in this area of things is the command to create an admin user:
https://www.bookstackapp.com/docs/admin/commands/#create-an-admin-user

Note, there is a logical theme system where you could add endpoints/logic/commands without editing core files:
https://github.com/BookStackApp/BookStack/blob/master/dev/docs/logical-theme-system.md

**Comment by mxchinegod** [comment]
Thank you. This was the direction I needed to make a throwaway API endpoint to co-register a user from a request originating on a subdomain under the same Apache server.

**Comment by ssddanbrown** [comment]
@DylanAlloy Happy to help, will therefore close this off.
