### ISSUE TITLE
[Feature Request]: Change Admin Settings Save Buttons

### ISSUE THREAD

**Issue by Cave-Johnson** [BookStackApp/BookStack#3221]
### Describe the feature you'd like

Recently set up a new instance of bookstack and found the settings "save" buttons to be a tad confusing. Ie i was expecting changing settings in different sections and then pressing one of the save buttons to save all the changes but instead it only saved that section. Took me a few attempts to figure out what was going on.

Would it make more sense to have one save button for all sections at the bottom (or top) of the settings page rather than per section?

### Describe the benefits this feature would bring to BookStack users

Simpler interface following the method most other applications use

**Comment by ssddanbrown** [comment]
Hi @Cave-Johnson,
I agree, this has caused confusion for a few people.

> Would it make more sense to have one save button for all sections at the bottom (or top) of the settings page rather than per section?

I think I had this originally, but the button would be distant from the context of what you're editing and it did not work well visually when we grouped up the settings into distinct sections. I'd like to keep the button somewhat close to the settings being changed, especially as we return people close to that location.

I'm thinking it may be best to instead split these into three different views, with an overview/navigation between them in place of the existing `/settings` view.

**Comment by Cave-Johnson** [comment]
That would make sense as well!

**Comment by ssddanbrown** [comment]
I've now made & merged in changes within #3349 which split the settings view to different category sections to prevent the fundamental issue here from occurring. A preview of this can be seen here:

https://github.com/BookStackApp/BookStack/pull/3349#issuecomment-1080467379

This will be part of the next feature release. I will therefore close this off.
