### ISSUE TITLE
[Bug Report]: EUR char (€) not rendered in PDF Export

### ISSUE THREAD

**Issue by amelszg** [BookStackApp/BookStack#3224]
### Describe the Bug

EUR character (€) and possibly some other special chars are not rendered correctly in PDF.

### Steps to Reproduce

Can be reproduced on [BookStack Demo](https://demo.bookstackapp.com/) instance as well.

1. Edit any page and insert € into content.
2. Export the page as PDF

### Expected Behaviour

€ char is expected to be rendered correctly in PDF, same as when exported to html or previewed in editor. 

### Screenshots or Additional Context

Page content with € char:
![image](https://user-images.githubusercontent.com/50396711/151968777-7511bbf3-3d0a-46ca-8b94-72c2a3786227.png)

PDF Export screen:
![image](https://user-images.githubusercontent.com/50396711/151968860-4df71696-ba22-4c30-810b-ab5a5ba5cee0.png)

PDF Export as file:
[page-a.pdf](https://github.com/BookStackApp/BookStack/files/7978428/page-a.pdf)

### Exact BookStack Version

v21.12.3

### Hosting Environment

Ubuntu

**Comment by ssddanbrown** [comment]
Thanks for reporting @amelszg,
I feel the fundamental issue here is already covered by #719 and/or #148 so I'm going to close this off to keep duplication reduced.

**Comment by amelszg** [comment]
Just a note, this particular issue got fixed after installing current BookStack Version (v22.02.3, upgraded from v21.12.3).

I guess it got solved by dompdf 1.2 bump.

Thanks!
