### ISSUE TITLE
[Feature Request]: LDAP and local authentication in parallel

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3228]
### Describe the feature you'd like

As soon as the item AUTH_METHOD is set to "LDAP", only LDAP authentication is possible.

### Describe the benefits this feature would bring to BookStack users

The use of both backends facilitates the handling with e.g. customers and own employees, if customers are not created in the AD.

**Comment by ssddanbrown** [comment]
Thanks for the request @christianhz01,
This has already been requested in #2715 so I'll therefore close this off as a duplicate.
