### ISSUE TITLE
[Bug Report]: MFA error after artisan key:generate

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3229]
### Describe the Bug

If you have activated TOPT MFA and then renew the application key with "artisan key:generate", the MFA login fails. In this case, MFA must be reset for the user.

### Steps to Reproduce

1. Enable MFA for an User
2. change something in the .env File
3. execute artisan key:generate
4. Now you get an error if you try to login with the mfa user

### Expected Behaviour

no Error?

### Exact BookStack Version

21.12.3

### PHP Version

7.3

### Hosting Environment

Ubuntu20, Apache2, php7.3

**Comment by ssddanbrown** [comment]
Hi @christianhz01,
This is known. You should not be re-running the `artisan key:generate`. This should only ever be ran during initial install.
This command generates the key used for encryption, and encryption is used to secure MFA details. Changing the key will cause any encrypted details, encrypted with the previous/different key, to be inaccessible.

**Comment by christianhz01** [comment]
Hi @ssddanbrown 
Thanks for the answer. I understood that the command is needed to apply settings from the .env. Is that wrong then? How do I transfer the settings?

**Comment by ssddanbrown** [comment]
> I understood that the command is needed to apply settings from the .env. Is that wrong then

Yeah, that's wrong.

> How do I transfer the settings?

Settings from the `.env` file are ready automatically and dynamically. No commands are needed unless you've ran `php artisan config:cache` at some point (Not something we document though) in which case you may need to run `php artisan config:clear` once.

**Comment by christianhz01** [comment]
Thanks :)
