### ISSUE TITLE
[Feature Request]: Lock page when editing

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3233]
### Describe the feature you'd like

If user1 is editing a page while user2 is also editing it, the user who saves last overwrites the other change of the other user. An edit lock or other signaling might help.

### Describe the benefits this feature would bring to BookStack users

No mutual overwriting of the contents

**Comment by christianhz01** [comment]
Edit: A small marker (e.g. on the edit button) that the page is in progress and a popup when saving if another user has already published, with the option "save as draft" and "publish anyway" would be good. Maybe with reference to the versions?

**Comment by ssddanbrown** [comment]
Thanks for the request @christianhz01 but I'm going to close this off since a discussion referencing locking is already open in #395. As mentioned in that chain, there are some mechanisms already in place to warn in some scenarios when there are multiple active editors of a page.
