### ISSUE TITLE
[Feature Request]: Theme Select

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#3234]
### Describe the feature you'd like

Hi there,

Since the darkmode is not going so well, I have another idea of ​​choosing a topic

So you could adjust the complete CSS without the dark mode variable

I have an example as CSS code

The excerpt comes from the Darkreader (tool)

### Describe the benefits this feature would bring to BookStack users

Not only the simplification of the styles but also the provision of a number of topics would be guaranteed

### Additional context

[Dark.zip](https://github.com/BookStackApp/BookStack/files/7993088/Dark.zip)

![2022-02-03 09_44_33-](https://user-images.githubusercontent.com/6242840/152311636-0a8c80b0-4502-4f47-a417-09f2d16413a3.png)

**Comment by ssddanbrown** [comment]
Hi @reddexx,

To be honest, I don't understand the majority of this request. I'm not sure what feature you're asking for or what problem you're attempting to solve. I don't understand what you're referring to as "topics".

Is there another way to describe what you want here, or what you'd expect us to action based upon this request?

**Comment by reddexx** [comment]
Visual-Style from Bookstack over CSS

this ist not the Dark-Mode. This is my Edit over CSS Declaration

**Comment by ssddanbrown** [comment]
Okay, Are you expecting us to action anything based upon this request or are you just sharing your CSS edits for the community?

**Comment by reddexx** [comment]
My idea would be that you can choose a css-style like you can see on the picture (on the right). BookStack checks if there are CSS files in the directory and takes the filename as the style name, which can be selected in the menu. The selected CSS should then be used

**Comment by reddexx** [comment]
A style selection menu is better than the current darkmode

**Comment by ssddanbrown** [comment]
Ah, I see now. I'm not looking to change direction in how dark mode has been approached. We build it in to make usage easier while having the dark mode theme supported and aligned to the default light mode. This follows the "batteries included" approach I try to keep to but that does mean we have to keep our scope focused to keep things maintainable.  A lot of the reasoning above is quite opinionated and does not justify the benefits for the wider bookstack audience.

While I could maybe see a desire in some use cases for per-user selection of custom styles, that would be an edge case scenario and a more complex parallel to the light/dark system we already support.

**Comment by ssddanbrown** [comment]
Will therefore close this off.
