### ISSUE TITLE
[Feature Request]: email protected option

### ISSUE THREAD

**Issue by R0GGER** [BookStackApp/BookStack#3235]
### Describe the feature you'd like

E-mail adresses in text are shown as [email protected].
It would be nice if the administrator can decide whether to enable or disable this setting by editting .env or in Bookstracks settings.

### Describe the benefits this feature would bring to BookStack users

We are using Bookstack mainly for documentation. For example manuals about mailboxes or distribution lists are now much harder to read, because e-mail addresses hidden now...

**Comment by ssddanbrown** [comment]
Hi @R0GGER,
We have no in-built email protection within BookStack. 

Are you running BookStack behind CloudFlare? I'm pretty sure they provide an email protection option which can be disabled.

**Comment by R0GGER** [comment]
Yup... it was Cloudflare.
I turned "email address obfuscation" off.
![zqtVD2](https://user-images.githubusercontent.com/8298741/152442718-ef5f981a-1c86-4ad2-9201-a11e22752bac.png)
