### ISSUE TITLE
[Feature Request]: Stay logged in button

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3236]
### Describe the feature you'd like

A checkbock in the login screen "stay logged in" so that you don't have to enter your password all the time.

### Describe the benefits this feature would bring to BookStack users

No constant password entry

**Comment by ssddanbrown** [comment]
Hi @christianhz01,
We already have a "remember me" option for standard email/password authentication.
Are you using LDAP as your primary authentication mechanism? If so, the discussion in #1910 would be relevant.

**Comment by christianhz01** [comment]
Hi Dan,

thanks for the answer, the resolution for me is the "SESSION_LIFETIME=" in the .env. 

Tanks!
