### ISSUE TITLE
[Feature Request]: More Shortcuts

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3237]
### Describe the feature you'd like

I think that these shortcuts would be useful as well:
- New page: n
- Edit: E
- Tags/Labels: L
- Favorites: F
- Comment: C

### Describe the benefits this feature would bring to BookStack users

I know these shortcuts partly from Confluence and they improve/quicken and facilitate the way of working with such a docu tool

**Comment by ssddanbrown** [comment]
Thanks for the request @christianhz01,
Interface shortcuts have already been requested in  #1216 so I'm going to close this off as a duplicate.
