### ISSUE TITLE
[Bug Report]: Profile avatar cannot update

### ISSUE THREAD

**Issue by phucnguyenvn** [BookStackApp/BookStack#3240]
### Describe the Bug

![image](https://user-images.githubusercontent.com/19264169/152463746-794d9fe0-4a54-4bd3-8c53-20aa7e262610.png)
When I edit the profile, the button select image is just not working, no error showing in the console tab
This is happening on the newest release, the demo site also got the same issue

### Steps to Reproduce

1. Login
2. Click on user name -> edit profile
3. Scroll down to Avatar setting, click on select image

### Expected Behaviour

Should prompt the select file window to select a new avatar

### Exact BookStack Version

next version

### Hosting Environment

Ubuntu 18

**Comment by ssddanbrown** [comment]
Hi @phucnguyenvn,

The button is showing the file picker for me, I'm on Firefox 96 on fedora 35, tested on the demo site.

- What operating system and browser version are you using?
- Does it still occur in a private/incognito window (Or other browser).
- Does clicking the "Click Me" box on [this page](https://jsfiddle.net/y42hex65/) show the filepicker?

**Comment by phucnguyenvn** [comment]
hi @ssddanbrown the click me not showing on my side. I'm using Google Chrome Version 97.0.4692.99 (Official Build) (x86_64)

**Comment by ssddanbrown** [comment]
@phucnguyenvn Just tested on Chrome (`Version 97.0.4692.99 (Official Build) (64-bit)`) on fedora 35 and seems to work for me.

The method used to show the filepicker, in both bookstack and the example above, are quite simplistic usages of html functionality, there's no custom script going on. I'd question if there's something wrong with your instance of chrome.

- As above, what operating system are you using (to run chrome)?
- Does it still occur in a private/incognito window (Or other browser).

**Comment by phucnguyenvn** [comment]
@ssddanbrown I'm using MacOS Monterey, following your test I just make a restart for the whole system, now it's working without any issue. Let me close this bug. Really appreciate your help!!

**Comment by ssddanbrown** [comment]
Cool, thanks for confirming, glad we found the answer!
