### ISSUE TITLE
[Bug Report]: Cannot copy callouts

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3250]
### Describe the Bug

Unfortunately, it is not possible to copy callouts, which would definitely speed up the processing. It looks like a callout is handled like a font formatting, maybe that is also a good approach?

### Steps to Reproduce

1. Make an callout
2. copy with STRG+C
3. try tp paste with STRG+V

### Expected Behaviour

That the callout is copied

### Exact BookStack Version

21.12.05

### PHP Version

7.3

### Hosting Environment

Ubuntu20, PHP7.3, Apache2, MYSQL

**Comment by ssddanbrown** [comment]
Hi @christianhz01,
It should be possible to copy callouts. By default the format won't copy across if you're just copying and pasting the text but selecting vertically across the callout allows copy and paste.

Here's me copy and pasting mulitple callouts on our demo site (Firefox on Fedora 35):

https://user-images.githubusercontent.com/8343178/152702039-2a46dc6f-c34f-40e3-af03-a91d8088acf3.mp4

**Comment by christianhz01** [comment]
Thanks 😃

**Comment by christianhz01** [comment]
Hi @ssddanbrown 

thanks for the answer but you can not do this if you use a callout in a table...

Christian

**Comment by ssddanbrown** [comment]
@christianhz01 I was able to do the same within a table on our demo site. Same rules applied, need to select vertically across the callout.

**Comment by christianhz01** [comment]
@ssddanbrown Can you make a video of that as well? I can only do it by marking two cells.

**Comment by ssddanbrown** [comment]
> @ssddanbrown Can you make a video of that as well? I can only do it by marking two cells.

If it's the only thing in a cell you might need to make a little space to ensure you can select it. 

https://user-images.githubusercontent.com/8343178/153720645-6b41e37e-040c-4216-b282-224e4ba405c3.mp4

If it's any easier, Note you can use `Ctrl+9` to format the current block as a callout. Pressing it multiple times cycles through the types. That what I'm doing at the end of the video.

**Comment by ssddanbrown** [comment]
Will therefore close this off.
