### ISSUE TITLE
[Feature Request]: Multi language/translations support in user created pages 

### ISSUE THREAD

**Issue by mchaptel** [BookStackApp/BookStack#3253]
### Describe the feature you'd like

It would be great if several "language versions" of a page could be supported, without having to duplicate the page structure of a book for a different language.

For example, each page could have several language versions (user created) and depending on the user preferences, a specific language would be served to the reader (with the possibility of manually switching of course)

### Describe the benefits this feature would bring to BookStack users

A multilanguage functionality would be a great addition to bookstack and not having to duplicate books and pages to support several languages would be a better workflow (also, would make spotting the needed translations easier)

**Comment by ssddanbrown** [comment]
Thanks for the request @mchaptel, This has already been requested in #569 so I'm going to close this off as a duplicate.
