### ISSUE TITLE
[Feature Request]: Copy entire book

### ISSUE THREAD

**Issue by mchaptel** [BookStackApp/BookStack#3254]
### Describe the feature you'd like

I would like to have the possibility to copy an entire book and chapter, and not only have the possibility to copy single pages.

This would make book duplication easier, and allow for book level templating, which can be helpful to structure large ammount of documentation declinations.

### Describe the benefits this feature would bring to BookStack users

This feels like a pretty essential quality of life feature, I'm sure a lot of users would be happy to have it.
It is different from displaying the same single book on several shelves, and more for book templating.

**Comment by ssddanbrown** [comment]
Hi @mchaptel,

What version of BookStack are you running?
We added this feature in BookStack v21.12: 

https://www.bookstackapp.com/blog/bookstack-release-v21-12/#copy-entire-chapters--books

**Comment by ssddanbrown** [comment]
Will therefore close this off.
