### ISSUE TITLE
[Feature Request]: support full WYSIWYG/markdown compatibility back and forth

### ISSUE THREAD

**Issue by mchaptel** [BookStackApp/BookStack#3255]
### Describe the feature you'd like

Right now, pages using WYSIWIG are encoded using html. This means they cannot be later modified using markdown.

It would be better if WYSIWIG generated markdown under the hood, and that markdown was used to render the pages. This would ensure a complete back and forth compatibility between the two edit modes and not restrict edit mode to the way the page was created.

### Describe the benefits this feature would bring to BookStack users

Different users have different preferences for editing modes, and the fact that this selection blocks half the users whichever way is chosen is detrimental to the cooperation of the teams.

This change in implementation could be transparent for WYSIWYG users and benefit all.

**Comment by ssddanbrown** [comment]
Hi @mchaptel,
This has already been requested in #842, with #119 and #458 being closely related. Therefore I'm going to close this off as a duplicate.
