### ISSUE TITLE
[Feature Request]: Search for books when editing a shelf

### ISSUE THREAD

**Issue by ssoulaimana** [BookStackApp/BookStack#3266]
### Describe the feature you'd like

We want to be able to reuse the same book for several projects in our shelves.
When editing a shelf to add an existing book in it, it's tricky to find the right book because our list is so long.
It would be great to have a search bar when editing the shelf to allow for a Book search

![Search books](https://user-images.githubusercontent.com/94841745/153914054-b9759a70-21d7-4b93-9f7b-6d0d0abf0362.png)

### Describe the benefits this feature would bring to BookStack users

This will make finding books to add to a shelf a lot easier

**Comment by ssddanbrown** [comment]
Thanks for the request @ssoulaimana.

A simple local book-search has been added as part of #3591 and will be part of the next feature release.
