### ISSUE TITLE
[Feature Request]: Hotkeys/Keyboard Shortcuts!

### ISSUE THREAD

**Issue by travischambers** [BookStackApp/BookStack#3271]
### Describe the feature you'd like

https://support.atlassian.com/confluence-cloud/docs/keyboard-shortcuts-markdown-and-autocomplete/

From Confluence, the hotkeys I use the most are:
- e - edit
- s - share
- c - create

### Describe the benefits this feature would bring to BookStack users

For someone who creates or edits many pages frequently, this would significantly reduce the amount of time it takes.

**Comment by ssddanbrown** [comment]
Thanks for the request @tjchambers32,
The fundamental request and net benefits of this are already covered by  #1216 so I'm going to therefore close this off as a duplicate.

**Comment by travischambers** [comment]
You're totally right! Sorry, I thought I'd searched around better before submitting!
