### ISSUE TITLE
[Feature Request]: plug-in interface that makes external content appear to be a book with pages

### ISSUE THREAD

**Issue by craibuc** [BookStackApp/BookStack#3275]
### Describe the feature you'd like

I have an external, SQL-based, data-dictionary that I'd like to integrate with Bookstack.  I'd want to map some aspects of the dictionary as pages, while other content would be the pages' contents.

### Describe the benefits this feature would bring to BookStack users

This would allow others to extend the functionality of Bookstack.

**Comment by ssddanbrown** [comment]
Thanks for the request @craibuc.
This is somewhat related to  #2604.

I can see a feature such as this being a fairly major burden in terms of support and maintenance while providing little to no benefit for the majority of BookStack use-cases and adding usability complexity where it is used. Hence I may look to close this off as out of scope. The current benefit listed is very general and chasing extension for the sake of extension and usage flexibility is not something I believe to be sustainable.

**Comment by ssddanbrown** [comment]
As per above, will go ahead and close this off as out of scope.
