### ISSUE TITLE
[Feature Request]: In WYSIWYG Editor, Provide an easy way to remove links

### ISSUE THREAD

**Issue by robertfshort** [BookStackApp/BookStack#3276]
### Describe the feature you'd like

Remove link button in the Wysiwyg editor.

### Describe the benefits this feature would bring to BookStack users

It does not appear to be an easy way to remove a link once one has been created

**Comment by ssddanbrown** [comment]
Just a note to this, links can be removed by updating the link URL, or using the insert link button, while providing an empty URL. Agree it's not very obvious though.

**Comment by ssddanbrown** [comment]
Required change applied in #3298, awaiting scheduling into a release.

**Comment by ssddanbrown** [comment]
This has now been merged and will be part of the next feature release.
