### ISSUE TITLE
[Feature Request]: Permalink button

### ISSUE THREAD

**Issue by robertfshort** [BookStackApp/BookStack#3277]
### Describe the feature you'd like

When viewing a page (or even better a button when viewing a book or chapter) having a permalink button that will automatically copy the permalink to the clipboard. Ideally this should be under the action menu for the individual page. For editors add a button to the side in the book or chapter view with the same functionality. This could even be optionally turned on or off with a setting in the user's profile.

### Describe the benefits this feature would bring to BookStack users

MUCH faster way of creating permalinks, easier to explain to non-technical users.

**Comment by ssddanbrown** [comment]
Thanks the the request, but this has already been discussed in  #2917 so I will therefore close this off under the same reasoning.
