### ISSUE TITLE
[Feature Request]: New Page button under actions.

### ISSUE THREAD

**Issue by robertfshort** [BookStackApp/BookStack#3278]
### Describe the feature you'd like

Under actions, while viewing a page, have a button to insert a new page before or after the current page

### Describe the benefits this feature would bring to BookStack users

Ease of navigation

**Comment by ssddanbrown** [comment]
Thanks for the request @robertfshort,
This is something that's already been requested in #1267 so I'm going to close this off as a duplicate.
