### ISSUE TITLE
[Feature Request]: Discord Role Intergration

### ISSUE THREAD

**Issue by jxckUK** [BookStackApp/BookStack#3280]
### Describe the feature you'd like

Allow the adding of Discord roles to users who authenticate via Discord.

### Describe the benefits this feature would bring to BookStack users

This would allow communities to use BookStack and leverage Discord permissions which a lot of communities utilise. It would allow simpler management of user permissions and allocations.

**Comment by ssddanbrown** [comment]
Hi @jxckUK, Thanks for the suggestion.
I'm not currently looking to expand the functionality of the social auth systems at this time, especially where additional configuration or logic may need to be involved, in an effort to keep the scope of support auth systems feasible and maintainable.

If you have some dev skills, we do have [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) where it's possible to hook into login events, to be able to run custom logic upon login.
