### ISSUE TITLE
[Feature Request]: Allow some sort of fullscreen/distraction free reading mode

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#3286]
### Describe the feature you'd like

As of now, when using code blocks with large amount of code, it can be hard to view the whole thing and always scrolling left and right is not optimal. Plus the small reading width could be better. I was thinking of some sort of fullscreen or distraction free reading mode where it would get rid of the left and right sections/menus and take the full screen space to display the doc. 

### Describe the benefits this would bring to existing BookStack users

The would bring easier readability for:
* Long docs
* Docs with big images
* All the code blocks

### Can the goal of this request already be achieved via other means?

Probably just by exporting the doc in PDF but that defeat the purpose of using Bookstack

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @camaer,
Did you come across #465 in your search of existing issues? I think my thoughts on this remain aligned to those provided 5 years ago on that issue.

**Comment by ghost** [comment]
Hey Dan,

I did not. When searching for previous issues I made my original search on "fullscreen" and added the distraction free at the time of the creation of this issue. That being said your reasoning make sense so I will close this issue. Thanks for your work
