### ISSUE TITLE
Login page not working

### ISSUE THREAD

**Issue by Nakatomi2010** [BookStackApp/BookStack#329]
### For Bug Reports

* BookStack Version: .15
* PHP Version: 5.6
* MySQL Version: 5.7
* Server 2016 Core - IIS 10

##### Expected Behavior

Attempting to launch for first time, expecting to need to login

##### Actual Behavior

when going to the site bsa.<domain>.net I get forwarded to bsa.<domain>.net/login which then displays a page 404.

**Comment by Nakatomi2010** [comment]
Chipped away at it and found the following site that assist in converting .htaccess files in to web.configs:

https://blogs.msdn.microsoft.com/azureossds/2015/04/23/converting-apache-htaccess-rules-to-iis-web-config-using-iis-manager-for-azure-websites/

Requires having URL Rewrite 2.0 on IIS server.  Once imported though you get the following web.config file for the rewrites:

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rewriteMaps>
                <rewriteMap name="{REQUEST_FILENAME}" />
            </rewriteMaps>
            <rules>
                <clear />
                <rule name="Imported Rule 1" stopProcessing="true">
                    <match url="^(.*)/$" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Redirect" url="/{R:1}" redirectType="Permanent" />
                </rule>
                <rule name="Imported Rule 2" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>


The site now loads and lets me log in, though it does not look pretty.  Currently working on that issue.

**Comment by btone-comm** [comment]
@Nakatomi2010 If you have not resolved this issue, please verify your folder permissions.

IIS usually uses a local user, called: IIS_IUSRS
You'll want to verify that this user has the following allowed:
- Read & Execute
- List folder contents
- Read
- Write

These permissions should be applied to the following folders:
- storage
- bootstrap/cache
- public/uploads


Please, also verify that you are pulling the Release Branch, and not the Master Branch.

**Comment by ssddanbrown** [comment]
Closing due to duration since last update. Feel free to comment still if you need further support and this can always be re-opened.
