### ISSUE TITLE
Live Search

### ISSUE THREAD

**Issue by dannyhanes** [BookStackApp/BookStack#3290]
### Describe the feature you'd like

I would love to have Live Search implemented for the search box at the top of Bookstack.

### Describe the benefits this would bring to existing BookStack users

This would save users a little time when searching for documents.

### Can the goal of this request already be achieved via other means?

Right now, you would have to enter your search term, press return, wait for the page to load then click on a result. 
With live search you could start typing a keyword and results would immediately show up saving a few seconds per search.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @dannyhanes.
I think this may already be covered in #1235, although the original request there is a bit abstract. This would at least conflict with that request.

**Comment by dannyhanes** [comment]
@ssddanbrown Ahh predictive search... I looked through the issues for "Live Search" but didn't see it... apparently Predictive Search is the correct term. haha. 

Just throwing the request out there as its one of the very few things that bug me more than once a day lol 

Thanks!

**Comment by ssddanbrown** [comment]
Okay, thanks for confirming, will therefore close this off.
