### ISSUE TITLE
WYSIWYG editor not opening

### ISSUE THREAD

**Issue by wforumw** [BookStackApp/BookStack#3293]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After update from v21.12.5 to  v22.02 it seems that the WYSIWYG editor does not work anymore.
Everything works except if I create a new page or edit an existing page the page stays empty an no editor is seen.
If I change in the setting to 'markdown' I can edit a page or create a new one.

### Exact BookStack Version

v22.02

### Log Content

Nothing found in the error log
Also no error produced

### PHP Version

7.4.28

### Hosting Environment

Debian Bullseye

**Comment by SmokingCrop** [comment]
I have the same issue, opening up the browser Console gives an error (on editing a page where the WYSIWYG editor does not open):
_Uncaught TypeError: Cannot read properties of undefined (reading 'registry')
    at eN.setup (app.js:47:1295)
    at eN.execCallback (tinymce.min.js:2:343879)
    at new eN (tinymce.min.js:2:343292)
    at n (tinymce.min.js:2:353313)
    at Array.<anonymous> (tinymce.min.js:2:354874)
    at jt (tinymce.min.js:2:29356)
    at Object.e (tinymce.min.js:2:354723)
    at C (tinymce.min.js:2:10800)
    at d (tinymce.min.js:2:10946)
    at a (tinymce.min.js:2:10124)_

(PHP version 7.4.3 | Ubuntu 20.04.4 LTS without GUI)

(Reverted back to previous checkpoint)

**Comment by ssddanbrown** [comment]
Does this issue remain after a hard refresh? (Shift+R) or (Ctrl+Shift+R)

**Comment by SmokingCrop** [comment]
> Does this issue remain after a hard refresh? (Shift+R) or (Ctrl+Shift+R)

Ah, this fixed it for me 👍

**Comment by wforumw** [comment]
Thanks!! This fixed it for me

**Comment by ssddanbrown** [comment]
Thanks both for confirming. I usually update references for the editor script to force caches to be broken but forgot to do that for this release. Have tweaked this for our next patch release so users don't have to manually perform a hard refresh.
