### ISSUE TITLE
Plugin initialization error after upgrade to latest version (v22.02.1) 

### ISSUE THREAD

**Issue by towerplease** [BookStackApp/BookStack#3295]
### Describe the Bug

After updating Boockstacks to the latest version (V22.02.1) the editor shows multiple errors for plugins:
![image](https://user-images.githubusercontent.com/21177236/155941694-ec43569f-dd06-454c-8896-3b856999a8eb.png)
Except the messages, everything works fine. Do i have to repairs something?

Regards!

### Steps to Reproduce

Update to latest version
Add or edit a already existing page

### Expected Behaviour

No error popups

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/21177236/155942068-2eef151c-bafd-41a0-ae74-68bb0dd6f683.png)

### Browser Details

Opera

### Exact BookStack Version

v22.02.1

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 20.04 VPS, 4 Core, 4 GB RAM, HDD

**Comment by lucaguindani** [comment]
Same here ! Emptying my browser cache did the trick.

**Comment by towerplease** [comment]
Wow... you are right, i just didnt thought of that. Issue solved.

**Comment by baruchneo** [comment]
hello, yes it worked, thank a lot of
