### ISSUE TITLE
Code blocks no longer work properly

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3300]
### Describe the Bug

Unfortunately, since the new version, code blocks no longer work properly. It is no longer possible to edit a code block once it is created. You can't insert a new line directly above or below the block, which makes editing the page impossible.

### Steps to Reproduce

1. create new page
2. insert code block (three dots in the editor bar -> code block or via shotcut)
3. insert arbitrary code or text
4. save code block
5. now the codeblock can't be edited anymore and is stuck on the page.

### Expected Behaviour

-

### Browser Details

Microsoft Edge

### Exact BookStack Version

v22.02.1

### PHP Version

7.4

### Hosting Environment

Ubuntu20, Apache2, PHP7.4, MYSQL

**Comment by ssddanbrown** [comment]
Hi @christianhz01,

Are you able to replicate this same issue when using our demo site?:
https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site

In addition, can you confirm edge version and what operating system you're using?

**Comment by christianhz01** [comment]
Hi @ssddanbrown 

the problem had already been solved. When I looked for my Edge version, I saw that there is an update. Sorry, I should have checked better before I write something here. 😐 Have a nice week!
