### ISSUE TITLE
blank lines disappear

### ISSUE THREAD

**Issue by 10935336** [BookStackApp/BookStack#3302]
### Describe the Bug

Empty lines disappear after saving page.

### Steps to Reproduce

1. In the WYSIWYG editor, write two paragraphs with blank lines in between, like this (use "Enter" key)
![image](https://user-images.githubusercontent.com/32383605/156162599-60bb3420-1973-498c-8eb2-70082d2d170f.png)

2.Click save, then the page will display normally.

3.Edit the page again without changing anything, then save.

4.blank lines disappeared.
![image](https://user-images.githubusercontent.com/32383605/156163350-c143d174-c31b-4b9f-b1b4-3c05f77de4e4.png)

### Expected Behaviour

Blank lines are normally retained.

### Screenshots or Additional Context

This can be reproduced in the demo site.
https://demo.bookstackapp.com/books/dummy-content-book/page/new-page

### Browser Details

Chrome 8.0.4758.102 64bit Win10

### Exact BookStack Version

BookStack v22.02.1

### PHP Version

demo site

### Hosting Environment

demo site

**Comment by ssddanbrown** [comment]
Thanks for reporting, can confirm. Have assigned to the next patch release.

**Comment by ssddanbrown** [comment]
Patched in 5947f59a04fa8165141ac23ca89fbdcdb16848ad, to be part of the next patch release.
