### ISSUE TITLE
Error load Wising editor in a new page

### ISSUE THREAD

**Issue by baruchneo** [BookStackApp/BookStack#3304]
### Describe the Bug

When load a new page with wising editor generates plugins errors attach image support

![image](https://user-images.githubusercontent.com/5040560/156304096-c390b2b4-c90a-4801-884b-779599cb4184.png)

### Steps to Reproduce

1. create a new book
2. create a new section
3. create a new page
4.

### Expected Behaviour

load all plugins componentes  for example, plugin of table, plugin os link, etc

### Exact BookStack Version

22.02.1

### Hosting Environment

Centos 8,  with Docker image

**Comment by ssddanbrown** [comment]
Hi @baruchneo,
This is a known caching issue we had in the patch release and has been reported here: #3295

Clearing the browser cache or performing a hard-refresh should fix it instantly for a single user.
Last night I deployed `22.02.2` which adds additional measures to auto-clear the caches for all users.
