### ISSUE TITLE
LDAP server env variable should accept multiple servers

### ISSUE THREAD

**Issue by samip5** [BookStackApp/BookStack#3308]
### Describe the feature you'd like

I would like the `LDAP_SERVER` variable in .env file to accept multiple servers, as in environments with HA LDAP servers it should be supported in app too.

### Describe the benefits this would bring to existing BookStack users

This would bring HA support, so if one of the LDAP servers are unreacheable, it could use the 2nd one and not fail.

### Can the goal of this request already be achieved via other means?

Not to my knowledge.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

`LDAP_SERVER=ipa1.redacted.fi,ipa2.redacted.fi`

This happens with two LDAP servers set in .env file:

![Screenshot 2022-03-02 at 12 59 40](https://user-images.githubusercontent.com/1703002/156349224-90288a35-4f96-4268-b986-cc249be97977.png)

**Comment by ssddanbrown** [comment]
Thanks for raising @samip5,
I think this may already be covered by #543? Although that's specific to AD, it's still LDAP so would be the same fundamental feature request I think.

**Comment by samip5** [comment]
Ah, yeah seems to be. Let me close this and go put my screenshot of the current state there. :)

**Comment by joaomezzari** [comment]
+1 for this one

**Comment by igordps** [comment]
+1 for this one
