### ISSUE TITLE
What do you mean by  "The API is currently in a limited preview stage to ensure the foundations are correct, It will be expanded upon in future releases."

### ISSUE THREAD

**Issue by papagei89** [BookStackApp/BookStack#3311]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Can we use the API in production ?
Does it only have limited features ?
Can we build upon it ?
Do you have API documentation outside of the software ?
Can we contribute to expanding the APIs ?
Thanks for the answers.

### Exact BookStack Version

N/A

### PHP Version

7.4

### Hosting Environment

N/A

**Comment by ssddanbrown** [comment]
Hi @papagei89,

> Can we use the API in production ?

The `limited preview` message in our documentation was a bit outdated, from when the API was initially added. It's now considered supported as per the rest of BookStack. I have updated our documentation.

> Can we build upon it ?

Sure, may people already are.

> Does it only have limited features ?

Most of the core actions are now covered. I generally look to add some new endpoints on every release depending on what's been requested.

> Do you have API documentation outside of the software ?

Not really. I you don't have access to your own instance to check it's API documentation you can view the API of our demo instance here: https://demo.bookstackapp.com/api/docs

I also have a repo containing examples of using the API for a range of use-cases in a variety of programming languages: https://github.com/BookStackApp/api-scripts

> Can we contribute to expanding the APIs ?

Sure. If intending to develop the code for additional API endpoints, ideally you'd have some experience of PHP, Laravel and PHP testing. Please open an issue for discussion first to ensure it's something we'd merge to avoid potential disappointment if we were to reject your code.

There's a `New API Endpoint or API Ability` option when creating an issue that can be used specifically for API requests.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If any questions remain feel free to still comment here.
