### ISSUE TITLE
Book disappeared after a crash caused by running out of memory

### ISSUE THREAD

**Issue by JosephCTC** [BookStackApp/BookStack#3317]
### Describe the Bug

Attempted to upload a few images to a page in a book when the instance crashed due to running out of memory.
After restarting the book I was working in was completely gone. (IMG1)
Tried lookin in the recalling bin but was unable to find any of the pages or the book itself. (IMG2)
Looked at the audit log to see if I had done something accidentally and actually found a link to the page I was working on at the time but it goes to a page not found error. (IMG3)
After I saw that I though maybe I had hadn't saved but I had a couple times before this happened. (IMG4)

![chrome_aOglhBSGp2](https://user-images.githubusercontent.com/101208530/157297151-761d88df-f0ee-4a35-ae8b-ecf28d10ddd5.png)
![chrome_dAsXAxpJ6l](https://user-images.githubusercontent.com/101208530/157297155-cba73865-0aba-4cb8-ad5f-3413ec882a82.png)
![chrome_SDU0kNRBbe](https://user-images.githubusercontent.com/101208530/157297156-429f25f3-a495-44e7-83c7-9072c35387af.png)
![chrome_cn1sDPBZCB](https://user-images.githubusercontent.com/101208530/157297154-7dae05dc-ac38-4267-bf1e-46badcb29f8b.png)

### Steps to Reproduce

Was unable to reproduce as this is running in our production and was not able to test.

### Expected Behaviour

If the page itself had disappeared I would have been fine with it but then entire book is gone now witch I think would cause a lot of issues if some one wasn't keeping backups.

### Browser Details

Chrome on Windows 10

### Exact BookStack Version

BookStack v21.08.3

### PHP Version

PHP 7.4.3

### Hosting Environment

Azure B1s Virtual Machine Ubuntu 20.04.3 LTS x86_64 Installed using the official Installation Script

**Comment by JosephCTC** [comment]
New Development
I am able to view the pages in the disappeared book and see other pages we have made in the book but am not able to navigate to the book itself.
The page I was working on also does not appear to be listed.

Editing a page and saving it appears to have re listed this book on the shelf.

**Comment by ssddanbrown** [comment]
Hi @JosephCTC,
This could be a range of things depending on what was exactly occurring when memory ran out.
My best guess would be that the permissions failed to generate hence the contents are being hidden, but the content should still remain.

As mentioned on [this page](https://www.bookstackapp.com/docs/admin/commands/#regenerate-access-permissions) there's a command to "Regenerate Access Permissions". This should re-create any potentially lost permissions.
Probably worth running that and see if the book, and its contents, re-appear. I'd advise taking a database backup first before running the command just-in-case.

**Comment by JosephCTC** [comment]
> Hi @JosephCTC, This could be a range of things depending on what was exactly occurring when memory ran out. My best guess would be that the permissions failed to generate hence the contents are being hidden, but the content should still remain.
> 
> As mentioned on [this page](https://www.bookstackapp.com/docs/admin/commands/#regenerate-access-permissions) there's a command to "Regenerate Access Permissions". This should re-create any potentially lost permissions. Probably worth running that and see if the book, and its contents, re-appear. I'd advise taking a database backup first before running the command just-in-case.

Thank you this resolved my issue.
