### ISSUE TITLE
Searching strings with less than 6 characters

### ISSUE THREAD

**Issue by jernejpraprotnik** [BookStackApp/BookStack#332]
### For Bug Reports

Searching for strings that are less than 6 characters long does not return any results.

* BookStack Version: 0.14.2
* PHP Version: PHP 5.6.30-0+deb8u1
* MySQL Version: 10.1.21-MariaDB-1~jessie

##### Expected Behavior
 In my example I would like to search for content based on error codes, which are 4 character strings (example "F.15"). Search on those codes should return links to pages with descriptions for those codes. 
##### Actual Behavior
Search for strings with less than 6 characters returns empty result set.

**Comment by ssddanbrown** [comment]
Hi @jernejpraprotnik. Yeah, There are some issues in the search thus why #271 has been created. For now your can put your search term in quotes (`"F.15"`) which should use an exact match and work for shorter search terms.

**Comment by jernejpraprotnik** [comment]
Hi @ssddanbrown. Thank you for your reply. Putting sting in quotes works :)
