### ISSUE TITLE
Restrict access to shelves to only selected users

### ISSUE THREAD

**Issue by mpiko** [BookStackApp/BookStack#3324]
### Describe the feature you'd like

I'd like to be able to choose which of my users can see what books or maybe have a shelf locked down to only certain users. 

### Describe the benefits this would bring to existing BookStack users

Just like a physical library has restricted areas, being able to limit access to only specific users to certain shelves would be very useful. I would like to share my books with other but not everything to everyone.

### Can the goal of this request already be achieved via other means?

Not that I can see.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

If BookStack had this feature, I think it would be perfect.

**Comment by mpiko** [comment]
Thinking about it a bit more, I believe inheritance based on shelf would be better. I did see the comment regarding a book being in multiple places however, if I had multiple book shelves at home, I could not physically have the same book on two different shelves at once.
Therefore, I believe that permissions should be set per bookshelf and the books inherit from the shelf.
So, for example, one user could have full edit permissions to add, remove, delete books as they wish yet on another shelf, they would have maybe view only permissions. I think that would make more sense.

**Comment by ssddanbrown** [comment]
Hi @mpiko, Thank you for your request.

> Can the goal of this request already be achieved via other means?
> Not that I can see.

BookStack supports shelf/book level permissions based upon roles. You could technically achieve this by having user-specific roles then apply item-level permissions using these roles. Is a bit clunky and having many roles can affect performance in some areas, but it is a way to achieve the requested outcome.

> Thinking about it a bit more, I believe inheritance based on shelf would be better. I did see the comment regarding a book being in multiple places however, if I had multiple book shelves at home, I could not physically have the same book on two different shelves at once

This is really a perspective upon the metaphor used. You could have the same book on mulitple shelves of a library. Won't be the exact same physical thing but could be the same book with the same contents. Either way, this functionality is already in place and is not something we can just quickly remove to achieve other means.

---

User-level permission assignment is already open in issue #1747, which covers the fundamental request here, so I'm going to therefore close this off as a duplicate.

**Comment by mpiko** [comment]
Ok, fair enough. I would prefer to see it with inheritance just as we do with a file system on a computer. It works quite well.
