### ISSUE TITLE
Adding and updating styles in tinymce

### ISSUE THREAD

**Issue by looknear** [BookStackApp/BookStack#3325]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

changing and adding styles to config.js - has no effect on the styles of the tinymce.
adding new "formats" and "style_formats" has no effect.
is there some different setup than the original tinymce dev instructions?

### Exact BookStack Version

v22

### PHP Version

7.4

### Hosting Environment

apache

**Comment by looknear** [comment]
you can remove the issue.
but will be great to document some development flow and architecture better.
using NPM, how to start developing env etc.
Thanks.

**Comment by ssddanbrown** [comment]
Cool, Will therefore close.
I feel we've fairly well covered this in the readme: https://github.com/BookStackApp/BookStack#%EF%B8%8F-development--testing so I won't make any immediate changes.

Note: Tweaks to the editor config can be made without altering core app files by utilizing the custom editor events we emit:
https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events
