### ISSUE TITLE
Auto register for custom social login provider

### ISSUE THREAD

**Issue by androbey** [BookStackApp/BookStack#3329]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I did setup a custom SocialLogin Provider using the Logical Theme System. This works as expected with existing users. 

Now, I want to enable "auto register" for this provider (just like e.g. `TWITCH_AUTO_REGISTER=true` in .env file).
Is there any way to add some configuration to enable auto register for custom providers, without editing source files?

### Exact BookStack Version

v22.02.3

### PHP Version

8.0

### Hosting Environment

Ubuntu 20.04 VPS

**Comment by ssddanbrown** [comment]
Hi @androbey,
Sorry for the late response.

Looking at the codebase, you should be able to just add those options to the config array when using the theme system like so:

```php
Theme::addSocialDriver('reddit', [
    'client_id' => 'abc123',
    'client_secret' => 'def456789',
    'name' => 'Reddit',
    'auto_register' => true,
    'auto_confirm' => true,
], '\SocialiteProviders\Reddit\RedditExtendSocialite@handle');
```

Let me know how that goes and, if that doesn't work, I'll dig a bit deeper and do some testing.

**Comment by androbey** [comment]
Hi @ssddanbrown, 

sorry, you're right. I missed that the entire config array is passed (and obviously didn't read the comment clearly enough) (https://github.com/BookStackApp/BookStack/blob/ee6a2339b654d1a4537319fb1548fd311549dfc7/app/Auth/Access/SocialAuthService.php#L307). 

So, in fact, does work fine this way. Thank you very much and sorry to bother!

**Comment by ssddanbrown** [comment]
No bother at all! Happy to hear it works!
