### ISSUE TITLE
Issue with first run when installing via the script for ubuntu

### ISSUE THREAD

**Issue by nereme** [BookStackApp/BookStack#333]
* BookStack Version: Latest branch
* PHP Version: 7.0
* MySQL Version: 5.7

##### Expected Behavior

Opening bookstack for the first time, expecting to get to a login page

##### Actual Behavior

When running the install script for ubuntu and going to the ip of the server error message: whoops looks like something went wrong is all I get.

I originally wasnt getting anything due to a missing server name in the nginx config, but since correcting that i am not getting anything except the error message and have no idea what to look for to try and diagnose the issue as I am very new with this. Have tried the script a couple of times each time on fresh Ubuntu 16.04 VM's and have the same end result of Whoops looks like something went wrong

**Comment by mbw290** [comment]
I'm having the same issue.

**Comment by lommes** [comment]
Just run `php artisan key:generate` 

Since the script requires to be run as root there might be some other permission issues but that one command fixed it for me. The command is included in the script but fails because it is not run with the --force flag.

**Comment by ssddanbrown** [comment]
Script updated with above fix, Thanks @lommes for solving this one and for opening the issue on the devops repo.
