### ISSUE TITLE
Error Message on maintenance mode

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#3331]
### Describe the Bug

If I start the maintenance mode
"php artisan down"
I got following page
![2022-03-18 13_08_08-Error_ Undefined variable $cspNonce (View_ _var_www_html_bookstack_resources_vie](https://user-images.githubusercontent.com/67209365/159000729-6bd544f4-9b72-4ec5-98a0-e6dbfbb0be90.png)

### Steps to Reproduce

1 Start maintenance mode on console
2 Look at the main page

### Expected Behaviour

A site wich shows that the system is on maintenance mode

### Browser Details

all Browsers, Linux/MacOS/Windows 10/11

### Exact BookStack Version

v21.12.2

### PHP Version

8.0.16

### Hosting Environment

Ubunutu 20.04 VM on VMWare 
no proxy*s or either between

**Comment by ssddanbrown** [comment]
Hi @pboatone,

This should be fixed as of BookStack v21.12.4, as per issue  #3205 and PR #3210.

**Comment by pboatone** [comment]
Hi @ssddanbrown,
thanks i did not see these issue. I  updated today I will try it next week.

**Comment by ssddanbrown** [comment]
Okay, I'll therefore close this off but feel free to comment for re-open if issues remain after upgrade.
