### ISSUE TITLE
After add text to a book o a page when save, I receive: An unknown error occurred

### ISSUE THREAD

**Issue by AgusDiazMX** [BookStackApp/BookStack#3334]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello!

I have install this system some days ago, it really looks like to address our needs. Thanks so much!

I have created a book shelve, two books and some pages. When I create my first book, put a description like this: "Encontrará una descripción detallada del proceso de reparación controlado por AutoShop Easy, las actividades de los diversos roles de usuarios que participan en el proceso, así como las opciones de control disponibles en los diversos procesos de reparación y las herramientas y reportes del sistema." When I save it, I have received "An unknown error occurred", there was not a way to do any thing with it.

So, I have created another book, but this time with a short description and it was saved OK!  Fine, then I have created a Page on this new book with a shot title and a "Hello World!" as content and it was also saved OK! 

Fine! I was excited! So added more text, two paragraphs, but when save it, I have received "An unknown error occurred"....

As I did not find a way to edit again the book and the page that showed the error, I went to database and noticed than if I delete the data on the field "text" on the table "pages" on the row of the page with error, I was able to edit it again.  Then replace all my stuff and let only 10 words and it was saved OK!

Please, any help will be great!

![Edit a page - 2022-03-19 13-03-32](https://user-images.githubusercontent.com/101948276/159138720-ef38d639-93ff-487d-9b1e-8ef655eb737f.png)
![Error Occurred - 2022-03-19 13-05-04](https://user-images.githubusercontent.com/101948276/159138728-b99159f0-b60c-45b5-8688-df50e3c2d866.png)

### Exact BookStack Version

v22.02.3

### PHP Version

7.4.28

### Hosting Environment

Debian Linux 10
Kernel and CPU | Linux 4.19.0-13-amd64 on x86_64
Virtualmin 6.17-3
MariaDB version 10.3.31
SSL LetsEncrypt
[AS3asE45.sql.zip](https://github.com/BookStackApp/BookStack/files/8310145/AS3asE45.sql.zip)

```xml
<VirtualHost *:80>
    SuexecUserGroup "#1019" "#1005"
    ServerName 
    ServerAlias 
    DocumentRoot /home/ ..../public_html/public
    ErrorLog /var/log/virtualmin/..._error_log
    CustomLog /var/log/virtualmin/..._access_log combined
    ScriptAlias /cgi-bin/ /home/..../cgi-bin/
    DirectoryIndex index.html index.htm index.php index.php4 index.php5
    <Directory /home/ ..../public_html/public>
        Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
        allow from all
        AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
        Require all granted
        AddType application/x-httpd-php7.3 .php7.3
        AddType application/x-httpd-php7.4 .php7.4
        AddType application/x-httpd-php8.0 .php8.0
        AddType application/x-httpd-php7.4 .php
        Action application/x-httpd-php7.3 /cgi-bin/php7.3.cgi
        Action application/x-httpd-php7.4 /cgi-bin/php7.4.cgi
        Action application/x-httpd-php8.0 /cgi-bin/php8.0.cgi
    </Directory>
    <Directory /home/ ..../cgi-bin>
        allow from all
        AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
        Require all granted
    </Directory>
    RewriteEngine on
    RemoveHandler .php
    RemoveHandler .php7.3
    RemoveHandler .php7.4
    RemoveHandler .php8.0
</VirtualHost>
<VirtualHost ....:443>
    SuexecUserGroup "#1019" "#1005"
    ServerName 
    ServerAlias 
    DocumentRoot /home/ .../public_html/public
    ErrorLog /var/log/virtualmin/..._error_log
    CustomLog /var/log/virtualmin/..._access_log combined
    ScriptAlias /cgi-bin/ /home/ ..../cgi-bin/
    DirectoryIndex index.html index.htm index.php index.php4 index.php5
    <Directory /home/ ..../public_html/public>
        Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
        allow from all
        AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
        Require all granted
        AddType application/x-httpd-php7.3 .php7.3
        AddType application/x-httpd-php7.4 .php7.4
        AddType application/x-httpd-php8.0 .php8.0
        AddType application/x-httpd-php7.4 .php
        Action application/x-httpd-php7.3 /cgi-bin/php7.3.cgi
        Action application/x-httpd-php7.4 /cgi-bin/php7.4.cgi
        Action application/x-httpd-php8.0 /cgi-bin/php8.0.cgi
    </Directory>
    <Directory /home/vaicop/domains/ase.vaicop.com/cgi-bin>
        allow from all
        AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
        Require all granted
    </Directory>
    RewriteEngine on
    RemoveHandler .php
    RemoveHandler .php7.3
    RemoveHandler .php7.4
    RemoveHandler .php8.0
    SSLEngine on
    SSLCertificateFile /home/ ..../ssl.cert
    SSLCertificateKeyFile /home/ ..../ssl.key
    SSLCACertificateFile /home/ ..../ssl.ca
    SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
</VirtualHost>
```

**Comment by ssddanbrown** [comment]
Hi @AgusDiazMX,

What errors do you get in your BookStack error log file when this "unknown error" screen appears?
https://www.bookstackapp.com/docs/admin/debugging/#error-log-file

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
