### ISSUE TITLE
PHP Fileinfo extension must be installed/enabled to use Intervention Image.

### ISSUE THREAD

**Issue by Ikun886-cxk** [BookStackApp/BookStack#3337]
### Describe the Bug

I have a problem running php artisan key:generate.

### Steps to Reproduce

php artisan migrate

In ImageManager.php line 137:
                                                                               
  PHP Fileinfo extension must be installed/enabled to use Intervention Image.  
                                                                               
But I have installed the phpinfo extension.

### Expected Behaviour

php artisan migrate

In ImageManager.php line 137:
                                                                               
  PHP Fileinfo extension must be installed/enabled to use Intervention Image.  
                                                                               
But I have installed the phpinfo extension.

### Browser Details

Google Chrome (99.0.4844.74) 64-bit on Windows11

### Exact BookStack Version

v22.0.2.3

### PHP Version

8.0

### Hosting Environment

Debian GNU/Linux 11 x86_64 installed using Manual Installation

**Comment by ssddanbrown** [comment]
Hi @SurpriseLon,

I see you're using PHP 8 which would have been installed outside of available system packages (In addition to the default available version of PHP on debian 11).

Are you sure you have the `fileinfo` extension installed for the version of PHP used on the command line?

You can check the version of the command line php in use with `php -v`.
You can check the extensions installed with `php -m` then look for fileinfo in the output.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
