### ISSUE TITLE
Fatal error PHP version

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3340]
### Describe the Bug

Last update fatal error

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.12. in C:\xampp\htdocs\vendor\composer\platform_check.php on line 24

![image](https://user-images.githubusercontent.com/4026090/159513211-15f188e3-1063-4838-816f-6c01f8162900.png)

![image](https://user-images.githubusercontent.com/4026090/159513421-9bb50e17-6ba7-4a9f-ae5b-3069879068da.png)

### Steps to Reproduce

Updating

### Expected Behaviour

-

### Exact BookStack Version

22.02.3

### PHP Version

7.4.28

### Hosting Environment

Windows Server 2019

**Comment by ssddanbrown** [comment]
Hi @Statium,
Are you sure you're not running PHP7.3 on the web-server? It's common that command-line and webserver PHP versions can differ. 
When exactly do you see that error?

**Comment by Statium** [comment]
Problem solved.
