### ISSUE TITLE
Some of the editor buttons have no translation

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3342]
### Describe the Bug

Some of the editor buttons have no translation
![image](https://user-images.githubusercontent.com/4026090/159621576-8ef0e8c5-4afa-4202-a907-405454732a2f.png)

### Steps to Reproduce

Pointing to a button

### Expected Behaviour

-

### Exact BookStack Version

22.02.3

### PHP Version

7.4

### Hosting Environment

Windows Server 2019

**Comment by ssddanbrown** [comment]
Thanks @Statium, Can confirm this one is missing. Have assigned to the next feature release to add.

**Comment by Statium** [comment]
![image](https://user-images.githubusercontent.com/4026090/159719330-94ce9d4d-42b0-4394-b16a-68145047b96d.png)
![image](https://user-images.githubusercontent.com/4026090/159719401-05c0b00e-d700-4072-8fef-abf0318bcbd8.png)

**Comment by Statium** [comment]
![image](https://user-images.githubusercontent.com/4026090/159719609-883228b4-50a3-4701-9d09-125d408b80be.png)

**Comment by Statium** [comment]
![image](https://user-images.githubusercontent.com/4026090/159719761-057a8c04-c5bd-4a1a-bf59-6696cd3a99a4.png)

**Comment by Statium** [comment]
I found some more points, indicated in the photo above.

**Comment by ssddanbrown** [comment]
Thanks @Statium, further additions made in d23b24b8db2e4268dd5e32b9cfda1dd6a5a3caf3.
