### ISSUE TITLE
Bookstack Version via API

### ISSUE THREAD

**Issue by chrisnails** [BookStackApp/BookStack#3343]
### API Endpoint or Feature

It would be helpful if i could get the current Version of the Bookstack Instance via the API

### Use-Case

I'd like to add a Check in my Monitoring System to get notified if my Bookstack Instance is not on the latest Version.

### Additional context

i can check the latest bookstack release like this 
`curl -sL https://api.github.com/repos/BookStackApp/BookStack/releases/latest | jq -r ".tag_name"`
i just need somethign similar for Bookstack itself, compare Versions and Notify

**Comment by ssddanbrown** [comment]
Hi @chrisnails,
The version is used as a cache breaker on asset urls so it is possible to do the following:

```bash
curl -sL https://demo.bookstackapp.com/ | grep -oPm 1 "(?<=version=)v[0-9.]+"
```

If you need more than that, we do have a [status endpoint](https://demo.bookstackapp.com/status) we could maybe add the version to. I do wonder though if our usage of the version in such a status endpoint (and the existing cache breaker usage) would be a security concern for some (for those that want more obscurity). 

Maybe we could add a new api-side `/system` endpoint which shows additional detail such as app name and app logo and the version. Just trying to avoid single-use-endpoints if other similar details also get requested.

**Comment by chrisnails** [comment]
hi @ssddanbrown,
thanks for the quick answer!
For my current use-case, the cache breaker angle works fine.
But i agree that this Info might better be kept behind authentication.

**Comment by ssddanbrown** [comment]
Cool, since the cache breaker angle works for you I'll close this off but I'll keep it in mind for the future similar requests.
If we ever break you cache breaker scraping (Probably unlikely unless we start hiding versions) then just let us know on here and we can quickly move to implement such an endpoint if nothing already exists by that point.

**Comment by Bartiff** [comment]
I'm voting for a new api endpoint like /system!

**Comment by ssddanbrown** [comment]
@chrisnails @Bartiff In case it's still desired by either of you, an endpoint has been added via #5607 (Via Issue #5603) to be part of the next release.
