### ISSUE TITLE
Add an admin button to find orphaned books (not on any shelf)

### ISSUE THREAD

**Issue by Montg0mery** [BookStackApp/BookStack#3347]
### Describe the feature you'd like

To enforce a good structure, we make sure (manually) that every book is created on a shelf.

However there are some older books that were not created on a shelf, or sometimes someone forgets, and creates an "orphaned" book, that is not on any shelf. This makes it harder to see the overall hierarchy of shelves and books.

Orphaned books can be manually moved to a shelf, but as far as I can tell, there is no easy way to find orphaned books, without going through every shelf, making a note of every book, and then cross-referencing to find which ones are not on any shelf.

Having an admin button which says "list all books not on any shelf" or similar would be useful for us. Doing it manually with so many books is not easy.

Thank you.

### Describe the benefits this would bring to existing BookStack users

Be able to more easily find books not on any shelf, in order to move them to a shelf (or create a new shelf if an appropriate one doesn't exist).

### Can the goal of this request already be achieved via other means?

Yes, but it is a tedious manual task when there are a significant number of books and shelves.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

This is similar to #1171, but hopefully simpler to design and implement first. After using this feature to fix up all orphaned books, being able to subsequently enforce the "all books must be on a shelf" constraint would also be useful (#1171).

**Comment by ssddanbrown** [comment]
Thanks for the request @Montg0mery.
I'm going to close this as I feel the core request here is already covered by issue #1077.
