### ISSUE TITLE
Unable to embed iframe with source external to site

### ISSUE THREAD

**Issue by kaylahynes** [BookStackApp/BookStack#3351]
### Describe the Bug

Embedded Iframes from external sources are shown as blocked due to some sort of environment variable. 

### Steps to Reproduce

Create new page

Embed iframe from an external source(eg. google forms)

### Expected Behaviour

Successful embed

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/5714193/160499096-9632128f-be36-45e0-a33c-09c3a1019650.png)

### Browser Details

Google Chrome 

### Exact BookStack Version

Latest

### Hosting Environment

Ubuntu 20.04 LTS Server

**Comment by ssddanbrown** [comment]
Hi @meepmeep22,
This is not a bug but a security measure to control content within your BookStack instance via browser CSP controls.
Please see the "IFrame Source Control" section of our security documentation for more detail:
https://www.bookstackapp.com/docs/admin/security/#iframe-src-control

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up or discussion I'll close this off.
