### ISSUE TITLE
OIDC Discovery Error: cURL error 28: Resolving timed out after 3000 milliseconds 

### ISSUE THREAD

**Issue by itxworks** [BookStackApp/BookStack#3360]
### Describe the Bug

Getting this Error only with Bookstack Container (https://hub.docker.com/r/linuxserver/bookstack)

OIDC Discovery Error: HTTP request failed during discovery with error: cURL error 28: Resolving timed out after 3000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://auth.xxxx.com/realms/xxxx/.well-known/openid-configuration

### Steps to Reproduce

Works fine with other Apps linke "keycloak traefik forward auth" ...

### Expected Behaviour

Is there a way to increase the curl timeout ...  

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/73403258/161236859-0bcfe368-4f30-4816-88e7-f3b4e03de902.png)

### Browser Details

Chrome

### Exact BookStack Version

[BookStack v22.03]

### PHP Version

 image:  lscr.io/linuxserver/bookstack

### Hosting Environment

Debian 11 VPS

**Comment by ssddanbrown** [comment]
Hi @itxworks,

> Is there a way to increase the curl timeout ...

No, not without editing app files at least. I'm not sure editing the timeout is the answer here, three seconds is quite a long time for a request resolve to occur. It indicates there's an issue elsewhere.

- Is that `https://auth.xxxx.com/realms/xxxx/.well-known/openid-configuration` URL accessible from the BookStack host when manually sending a curl request? 
  - If so, how long does it take to resolve? 
  - Does this still work when accessing the container?

```
curl https://auth.xxxx.com/realms/xxxx/.well-known/openid-configuration
```

**Comment by itxworks** [comment]
OK ... thx
