### ISSUE TITLE
Make Bookstack more Awesome

### ISSUE THREAD

**Issue by Shahin-rmz** [BookStackApp/BookStack#3363]
### Describe the feature you'd like

Hello
First of all, thanks for developing, and maintaining such a nice artifact.
I have used bookstack and use it and now I'm able to organize my knowledge.
2 suggestions:
- It will be awesome, if we could have Vim keybindings in Markdown mode of page editors.
- it will be near perfect, if we could have pen support (drawing support) for Bookstack. something like tiddlywiki images that we can also touch and draw on them.

Thanks

### Describe the benefits this would bring to existing BookStack users

- Vim keybindings are getting more popular these days, and it is wide spread between many editors.
- drawing is direct way to express our ideas so we can have a fast draft and work with it later.

### Can the goal of this request already be achieved via other means?

Yes, many editors have vim keybindings, such as Google colab, to Pycharm, Jupyter, ...
and tiddlywiki also has the ability to add pictures and draw on it.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

I love the idea behind bookstack and like to see it improving.
As medium level Python developer, ready to help.

**Comment by ssddanbrown** [comment]
Hi @Shahin-rmz, Thanks for the feedback!

Multi-issue comments like this are hard for us to manage, so I'm going to close this off but, if needed, you can re-open them as their own requests.

> It will be awesome, if we could have Vim keybindings in Markdown mode of page editors.
> Vim keybindings are getting more popular these days, and it is wide spread between many editors.

Vim bindings is probably not something I'd look to include in the core project. This hasn't really had any demand before and the inclusion would then result in a wider scope, of providing key binding control in the editor.
Our editor, Codemirror, has [vim bindings available](https://codemirror.net/demo/vim.html) although they are not actively maintained. We do expose our Codemirror config for the markdown editor [via our custom editor events](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events). It may be possible to combine these to add vim bindings yourself, by loading the vim bindings code externally then adding to config via our provided events.
 If there are issues in script loading I'd be happy to look to see what we can do.

> it will be near perfect, if we could have pen support (drawing support) for Bookstack. something like tiddlywiki images that we can also touch and draw on them.

This would be very tricky for us to achieve within the direct scope of our own platform and the existing page content. 
It does look possible though to perform freehand drawings via the [diagrams.net](https://www.diagrams.net/doc/faq/insert-freehand-shapes) integration. It looks like they support pen input in a bunch of different ways.

**Comment by Shahin-rmz** [comment]
Thanks for the reply.
Yes, diagrams.net solution for handwriting is what I meant.
For the Vim Keybinding part, Maybe I should take a look at the API and think of a client for sending and seeing the Books/Shelves etc which supports Vim Keybinding.
