### ISSUE TITLE
Recycle bin endpoints

### ISSUE THREAD

**Issue by bourdaisj** [BookStackApp/BookStack#3372]
### API Endpoint or Feature

Ability to read from the recycle bin, as well as restoring items.

### Use-Case

Context: currently working on a side project for fun using the rest API.
After item deletion,  I want to allow the end-user to cancel the deletion afterward.

**Comment by bourdaisj** [comment]
Can get started on this today

**Comment by ssddanbrown** [comment]
@Julesdevops Awesome, Would be happy to accept a PR for such a feature.
Just follow convention for the other API endpoints. 
Will need to ensure the endpoints are covered by tests.
Will also need to ensure any request/response body examples are added to `dev/api`: https://github.com/BookStackApp/BookStack/tree/development/dev/api

Just shout if you need any guidance!

**Comment by ssddanbrown** [comment]
Code now merged as detailed in #3377, Will be part of the next feature release. Thanks again @Julesdevops!
