### ISSUE TITLE
Hide Books/Chapters/Pages

### ISSUE THREAD

**Issue by mridula-techwriter** [BookStackApp/BookStack#3375]
### Describe the feature you'd like

I would love a feature that will enable me to hide my books, chapters or pages. As of now I do not see a way to do that. I have created a Book exclusively for templates and its contents are open to the viewers with view only access.

### Describe the benefits this would bring to existing BookStack users

This feature will automatically bring in the draft feature. Not only that page with Metadata about the content structure can remain hidden from the viewers.

### Can the goal of this request already be achieved via other means?

I sm not sure about this.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

I am creating a troubleshooting document for engineers and they need not see the books not meant for them.

**Comment by ssddanbrown** [comment]
Hi @mridula-techwriter, It sounds like your main aim is to hide your "templates" book from any viewers.

Have you attempted to use the "Permissions" option on the book to limit permissions so that only certain roles can view the contents?

**Comment by tasosgkantaev** [comment]
Hello @mridula-techwriter, i've used as @ssddanbrown permissions to limit that and it works like a charm. 
I personally used it to store some documentations for myself.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up from the original issue creator I'm going to close this. If you have further discussion to the above feedback feel free to still comment and this can be re-opened if required.

**Comment by mridula-techwriter** [comment]
Hey Dan, sorry to go absconding, I set the permission for the book and now it is no longer visible to a viewer. What I didn't realize is that by default all will get to see all publications. 

Do you this a FAQ on this topic will help others?

**Comment by ssddanbrown** [comment]
@mridula-techwriter Sure, I've just pushed a "Role and Permissions" page to our own docs:
https://www.bookstackapp.com/docs/user/roles-and-permissions/
