### ISSUE TITLE
Edit Shelves

### ISSUE THREAD

**Issue by Loqzo** [BookStackApp/BookStack#3376]
### Describe the feature you'd like

'Shelves' can be edit to new word , like change to 'Kategory' or something like that...

### Describe the benefits this would bring to existing BookStack users

users can understand the content better

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @Loqzo,
This is already covered by open issue #2901, with a more extensive historical discussion in #406 which includes some potential workarounds.

I will therefore close this issue.
