### ISSUE TITLE
Links to Page Bookmark change PageID for Page Slug (untie data from server)

### ISSUE THREAD

**Issue by thecek** [BookStackApp/BookStack#338]
### For Feature Requests

Desired Feature:

I wouls like to suggest a changing for improvement on the feature 'link', the one it appears when you double click an area of the document.
Actually it builds the url link based on the server name, page ID and bookmark of the page.
Example: http://bookstackserver/link/2#bkmrk-some-part

My proposal is to untie the link from the Page ID, changeing to the page slug perhaps
Example: http://bookstackserver/link/cool-page#bkmrk-some-part

That would help in the future if we are going to 'export' and import the book to another server or place.
I would also suggest to export the whole book as an html, so I could share the book html in another place, and the links could still works if i have the correct alias to http://bookstackserver/link/

I hope it becomes clear.

I´ll soon get some time to contribute with bookstack development as I appreciate very much the simplicitty.

### For Bug Reports

* BookStack Version:
* PHP Version:
* MySQL Version:

**Comment by thecek** [comment]
Of course for that, pages slugs (bkmrk'ers) should be unique across whole book

http://static.bookstorage.com/book-of-dev#bkmrk-some-part

book-of-dev would be a whole book in a html (extensionless) file.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @thecek 

Since this has had little support in the last 3 years, and since it's still possible to get a non-id based URL via just copying out the URL bar, I'm going to close this off.
