### ISSUE TITLE
Request to add Uzbek language

### ISSUE THREAD

**Issue by vodiylik** [BookStackApp/BookStack#3383]
### Language to Add

Uzbek

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via CrowdIn.

**Comment by ssddanbrown** [comment]
Thanks @vodiylik for offering to translate into a new language.
I've added the requested language to our Crowdin project here: https://crowdin.com/project/bookstack/uz

I'll therefore close off this issue now the language is available to translate to. If there's little progress after a month or so I may remove this language.

**Comment by vodiylik** [comment]
Thank you @ssddanbrown
