### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by Simon8912** [BookStackApp/BookStack#3390]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I'm running two LXC container on proxmox with Bookstack and in one of them I encounter this issue couple versions before. When i run the update commands in terminal it shows this output. Bookstack is getting updated but I don't understand the problem. Have someone came across with this ?? 

![Screenshot at 2022-04-20 21-54-25](https://user-images.githubusercontent.com/38328674/164323055-e8a9d8fb-1a73-4265-bd0f-57479994cd4d.png)

I have been running the Composer diagnose and also clearing Composer's cache but this didn't help.

### Exact BookStack Version

22.03.1

### PHP Version

7.4.3

### Hosting Environment

ubintu 20.04 lts

**Comment by ssddanbrown** [comment]
Hi @Simon8912,

As of [BookStack v21.12.3](https://github.com/BookStackApp/BookStack/releases/tag/v21.12.3) composer >= v2 is required. Please update your composer version to the latest stable version and try again. Details for checking your composer version and upgrading can be found in the details of the v21.12.3 release:
https://github.com/BookStackApp/BookStack/releases/tag/v21.12.3

**Comment by Simon8912** [comment]
thanks @ssddanbrown I have resolved the problem with the help of this link. I had to uninstall the old composer and then install a new one.

**Comment by ssddanbrown** [comment]
@Simon8912 Good to hear! I'll therefore close this off.
