### ISSUE TITLE
Metadata for SAML authentication

### ISSUE THREAD

**Issue by max1c** [BookStackApp/BookStack#3398]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

My identity provider says that the vendor must provide the metadata and the list of required attributes. Here is what they said:
>So, from the vendor, you need:
>1) the metadata for the SP (or at the very least, the entityID)
>2) the list of attributes that need to be provided by the IdP

Where can I get these things? 

### Exact BookStack Version

22.03.1

### Hosting Environment

Debian 11.3 using docker container using LinuxServer.io recipe.

**Comment by ssddanbrown** [comment]
### 1. the metadata for the SP (or at the very least, the entityID)

While SAML2 is active and configured your metadata will be found at `<your_bookstack_base_url>/saml2/metadata`.
This URL is also the entityID.

### 2. the list of attributes that need to be provided by the IdP

The exact attributes can be configured in BookStack to map to your IDP.
BookStack makes use of the following details:
- Email Address
- External (IDP) ID
- Display Name (BookStack can combine multiple attributes for this if required)
- Groups (If using group syncing).

Detail regarding the exact options can be found in our docs:
https://www.bookstackapp.com/docs/admin/saml2-auth/

**Comment by max1c** [comment]
Thank you Dan for the information and all your hard work.
