### ISSUE TITLE
I found My First Bug a Style Bug XD

### ISSUE THREAD

**Issue by M1k30FF** [BookStackApp/BookStack#3403]
### Describe the Bug

On line 6 in` /resources/views/books/export.blade.php`

`<h1 style="font-size: 4.8em">{{$book->name}}</h1>`

your solution is not working: https://github.com/BookStackApp/BookStack/issues/462#issuecomment-786803638

Please excuse my bad English, I hope you can still understand

### Steps to Reproduce

i add a screen shot

### Expected Behaviour

I expected this headline to be smaller as well

### Screenshots or Additional Context

![Screenshot_2022-04-29_22_19_59 (conflicted copy 2022-04-29 224149)](https://user-images.githubusercontent.com/66423455/166066438-9ab533c2-4bd8-4ac3-8c6c-9ab44856e7f4.png)

### Browser Details

Firefox 99.0.1 Win/Linux 

### Exact BookStack Version

 v22.03.1 

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04 LXC Use Your install script

**Comment by ssddanbrown** [comment]
Thanks for reporting @smarthome-fan, But style customizations, such as that provided in https://github.com/BookStackApp/BookStack/issues/462#issuecomment-786803638, are not considered official supported functionality so I wouldn't really look to change anything in the core project in response to this issue creation.

If you wanted your custom header size to take priority in exports you could force their use like so:

```html
<style>
.page-content h1 { font-size: 2rem !important; }
.page-content h2 { font-size: 1.8rem !important; }
.page-content h3 { font-size: 1.6rem !important; }
.page-content h4 { font-size: 1.4rem !important; }
.page-content h5 { font-size: 1.3rem !important; }
.page-content h6 { font-size: 1.15rem !important; }
</style>
```

**Comment by ssddanbrown** [comment]
I'll therefore close this off.
