### ISSUE TITLE
Auto redirect to SAML / ADFS login page when accessing BookStack URL

### ISSUE THREAD

**Issue by isurinda** [BookStackApp/BookStack#3411]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have configured BookStack with ADFS / SAML authentication. When I access the application URL it displays **"Login with SSO"** button. I'm looking for a way to configure auto redirect to ADFS login page instead of click and redirect to login page.

### Exact BookStack Version

22.02.3

### PHP Version

7.4

### Hosting Environment

Ubuntu Server version 20.04 LTS

**Comment by ssddanbrown** [comment]
Hi @isurinda,
This is not currently functionality we have built in but has been requested within  #2175.
There's a potential workaround within that issue that could help for now.
A PR to potentially add this functionality has also recently been opened in #3406.

**Comment by isurinda** [comment]
Thank Dan, I've applied the workaround and its working as expected.
