### ISSUE TITLE
PDF Export ignores table width settings

### ISSUE THREAD

**Issue by tvogt** [BookStackApp/BookStack#3413]
### Describe the Bug

When exporting a book/page as PDF, all columns have identical width, no matter what changes to width had been made in the WYSIWYG editor, resulting in a PDF that is visibly different from the on-screen page.

### Steps to Reproduce

1. create a table
2. drag some column around to make them thinner or wider
3. "export to PDF"
4. look

### Expected Behaviour

PDF export should honour table settings

### Browser Details

Firefox 99.0.1 (64-Bit) on MacOS 10.14.6

### Exact BookStack Version

v22.04

### Hosting Environment

solidnerd docker container, installed via "docker compose up"

**Comment by ssddanbrown** [comment]
Thanks for raising @tvogt, but I'm going to close this off as a duplicate of existing issue #1280.

**Comment by tvogt** [comment]
You are correct. I searched but missed that existing issue.
