### ISSUE TITLE
noindex tag

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3414]
### Describe the feature you'd like

Add an option in the settings to prohibit indexing even of a public site for search engines.

### Describe the benefits this would bring to existing BookStack users

Prevent indexing of inappropriate content.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @Statium,
We already offer controls for this via the following option:
https://github.com/BookStackApp/BookStack/blob/44013721f0d9bd21c8ebe7cf2ae7d39067fe74bb/.env.example.complete#L321
By default Robot access intent will be controlled by your app's public access status but this can be overridden using the option posted above.

We use the `robots.txt` approach for this functionality, I wouldn't really look to complicate our implementation further with other robot access request techniques without significant reason to do so. The only flaw I can currently see in our existing approach is that it might not take action if using BookStack on a sub-path, but the hoster could just update the robots.txt file on their root-level site instead.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion I'm going to close this.
