### ISSUE TITLE
Predictive Search

### ISSUE THREAD

**Issue by alexphillips-dev** [BookStackApp/BookStack#3419]
### Describe the feature you'd like

Anticipating the search needs of a user, by making suggestions related to their queries as they type in a search bar. 

### Describe the benefits this would bring to existing BookStack users

Save time for the user by letting them click on the suggestions instead of forcing them to complete their queries.

### Can the goal of this request already be achieved via other means?

No/I'm not sure what you're referring to by "other means"

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @XCrownedClownsX,
This is already open within #1235 so I'm therefore going to close this off as a duplicate.
