### ISSUE TITLE
Stepping back in history and saving after creating page causes exception

### ISSUE THREAD

**Issue by JoelESvensson** [BookStackApp/BookStack#342]
* BookStack Version: BookStack v0.15-dev
* PHP Version: 7.1
* MySQL Version: MariaDb 10.1

##### Expected Behavior

I just created a page. Then I stepped back in history to edit the page again. I should be able to save without any problems.

##### Actual Behavior

The exception handler appeared.

**Comment by AbijeetP** [comment]
Hi @JoelESvensson,

Can you please post the logs from `logs/laravel.log`?

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this.
