### ISSUE TITLE
[GitHub] Authentication issue

### ISSUE THREAD

**Issue by abensimon86** [BookStackApp/BookStack#3422]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi

I have a situation with the Github authentication method. I follow all the steps from [https://www.bookstackapp.com/docs/admin/third-party-auth/#github](url)

The BookStack login page not show nothing about GitHub login auth

My .env file looks like that 
Full path /home/ubuntu/bookstack/www/.env

`APP_KEY=base64:zii+lyOj********
APP_URL=http://3.14*****:6875
GITHUB_AUTO_REGISTER=true

DB_HOST=bookstack_db
DB_DATABASE=bookstackapp
DB_USERNAME=bookstack
DB_PASSWORD=<yourdbpass>

GITHUB_APP_ID=9efec***********
GITHUB_APP_SECRET=0269*************`

### Exact BookStack Version

latest

### Hosting Environment

Docker-compose

**Comment by ssddanbrown** [comment]
Hi @abensimon86,

- What exact container image are you using?
- What do your container volume mounts look like?
- Have you attempted setting the `GITHUB_*` variables elsewhere or just in the stated file?

**Comment by abensimon86** [comment]
Hi @ssddanbrown 
Thanks for your response 

im use docker-compose

---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=<yourdbpass>
      - DB_DATABASE=bookstackapp
    volumes:
      - /home/ubuntu/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - /home/ubuntu/bookstack:/config
    restart: unless-stopped

My steps:

1) docker-compose up
2)register new GitHub app ([https://www.bookstackapp.com/docs/admin/third-party-auth/#github])
3)nano /home/ubuntu/bookstack/www/.env ---> and add two this variables 
GITHUB_APP_ID=9efec***********
GITHUB_APP_SECRET=0269*************

**Comment by ssddanbrown** [comment]
@abensimon86 Can you remove the `APP_URL` environment options from your docker-compose file, then restart the compose setup (Down then up). I think that blank `APP_URL` is overwriting the value set in the `.env` file hence it looks unset to BookStack.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
