### ISSUE TITLE
Edit the page view

### ISSUE THREAD

**Issue by amigthea** [BookStackApp/BookStack#3425]
### Describe the feature you'd like

I would like to modify the page view line height and have more control over the page display options. In the wysiwyg editor I can have a format that's changed when I open the page in view mode

### Describe the benefits this would bring to existing BookStack users

More possible customization to meet each user taste, more readability

### Can the goal of this request already be achieved via other means?

I don't know

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @Azertooth,

> More possible customization to meet each user taste, more readability

We can't really look to support every possible desired customization within the editor. To make additional style modifications we provide the "Custom HTML Head Content" setting in the "Settings > Customization" area of BookStack. Here you can add custom CSS and/or JavaScript to customize as required. Are you familiar with CSS?

**Comment by amigthea** [comment]
Thank you for joining the discussion @ssddanbrown 
I'm somewhat familiar but can you provide me some working example for the "Custom HTML Head" Content section? So I can reverse engineer that and tinkering around

**Comment by ssddanbrown** [comment]
@Azertooth Sure, here's an example of increasing the line-height of paragraphs within page content:

```html
<style>
	.page-content p {
		line-height: 2;
	}
</style>
```

**Comment by amigthea** [comment]
thank you for the help!
