### ISSUE TITLE
API Pages : not list all the pages

### ISSUE THREAD

**Issue by svgta1** [BookStackApp/BookStack#3427]
### Describe the Bug

The API pages don't list all the pages of the databases. In my case, a lot of pages included in chapters are not listed.
But the page is accessible when using its id.

### Steps to Reproduce

It's difficult to give steps to reproduce. My application has :
- 6 shelves
- 14 books
- 8 chapters
- more than 500 pages

### Expected Behaviour

List all pages with the API (in one shot or with pagination)

### Browser Details

Brave 64 bits on win 11

### Exact BookStack Version

v22.03.1

### PHP Version

PHP 8.1

### Hosting Environment

Debian 10, apache 2.4

**Comment by ssddanbrown** [comment]
Hi @svgta1,
Are you using the listing options as shown in the "Listing Endpoints" section of the API documentation? 

![Screenshot from 2022-05-09 16-01-07](https://user-images.githubusercontent.com/8343178/167438715-092a9cd7-d130-4023-8cb0-03f4f458243e.png)

**Comment by svgta1** [comment]
Hi,
Ok, you can close the issue... I have not seen the options in the API doc page. 
Sorry for that.

**Comment by ssddanbrown** [comment]
No worries, will therefore close off. If you ever need some examples of API usage I keep a collection here:
https://github.com/BookStackApp/api-scripts
