### ISSUE TITLE
[Feature request] slack integration

### ISSUE THREAD

**Issue by JoelESvensson** [BookStackApp/BookStack#343]
Desired Feature: Slack integration. So my team can be notified about changes.

**Comment by Shackelford-Arden** [comment]
@JoelESvensson I would think your request would be best merged with #147

**Comment by dsaundersWizmo** [comment]
Our team wanted this so I made a service that polls the MySQL database and hits a webhook when the change occurs.  It's in .C# but I might write something that works on the Ubuntu server running Bookstack at which point I'll share it.

**Comment by aljawaid** [comment]
What about the new upcoming Nextcloud Talk (slack alternative) integration as it is also open source self-hosted?

**Comment by ssddanbrown** [comment]
Since #147 was implemented I'm going to close this off since that allows posting of events to external services such as slack. 
If needed, this video shows the process (Using discord): https://www.youtube.com/watch?v=_zIp1ruGpoI
