### ISSUE TITLE
Draw.io link doesnt work

### ISSUE THREAD

**Issue by lakritzstange** [BookStackApp/BookStack#3431]
### Describe the Bug

I set a links in draw.io. to a bookstack Page.  when i save the Page the Link is not available in bookstack

### Steps to Reproduce

Add a draw.io 
Add a Link to it 
Save the Page
Try to click the Link 

### Expected Behaviour

Added links in draw.io should work

### Exact BookStack Version

22.04

### Hosting Environment

Ubuntu

**Comment by ssddanbrown** [comment]
Thanks for reporting but I'm going to close this off since the fundamental request is already covered by existing issue #1170.
