### ISSUE TITLE
How to hide heading sections?

### ISSUE THREAD

**Issue by peteSmith1229** [BookStackApp/BookStack#3444]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I would like to hide the "Shelves" and "Books" headers on the top-right of the webpage and only have these enabled when the user logs in.

I thought of using CSS in the Custom HTML Head Content section in Settings so as a test, I tried to hide the entire heading field to see if it works by using `.header {display:none;}` but the header section is still displayed.

Is this the right method to hide the "Shelves" and "Books" headers or is there a more efficient method?

### Exact BookStack Version

v22.02.3

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 20.04, Bookstack installed using this script: https://github.com/BookStackApp/devops/blob/main/scripts/installation-ubuntu-20.04.sh

**Comment by ssddanbrown** [comment]
The following will hide both of those menu items using JavaScript:

```html
<script>
    window.addEventListener('DOMContentLoaded', function() {
        const isLoggedIn = document.querySelector('header form[action$="/logout"]') !== null;
        if (!isLoggedIn) {
            const linksToHide = document.querySelectorAll('header a[href$="/books"], header a[href$="/shelves"]');
            for (const link of linksToHide) {
                link.style.display = 'none';
            }
        }
    });
</script>
```

Unfortunately, there will still be a flash of these items before the JavaScript runs, and they will show if JavaScript is disabled. It's not yet possible (In a widely supported way) to achieve this with CSS alone in the current configuration of BookStack.

For better customization, you could override [the header bar template](https://github.com/BookStackApp/BookStack/blob/development/resources/views/common/header.blade.php) using [the visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md).

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.

**Comment by peteSmith1229** [comment]
Sorry for the late reply. Thanks for your comment, I think the best method for me is just to edit the `var/www/bookStack/resources/views/common/header.blade.php` file directly and comment out the lines which displays the "Shelves" and "Books" headings.

**Comment by ssddanbrown** [comment]
No worries @peteSmith1229,

Editing core app files can mess with update updates though, Using the visual theme system I linked above would allow you to make your modifications without editing original app files.

**Comment by peteSmith1229** [comment]
That's good to know, thanks again!
