### ISSUE TITLE
Specify username and avatar in webhook

### ISSUE THREAD

**Issue by adocampo** [BookStackApp/BookStack#3447]
### Describe the feature you'd like

I love webhook feature, glad to see it implemented here!

I use webhooks to notify a channel called #notifications on my RC instance. That channel was created at first to notify our Taiga system to all our IT department.

I have several services pointing to that channel: taiga, monit,  rundeck, custom webhooks, and now Bookstack! But I saw a little issue, the user who appear to had sent the notification is the default user for that channel, instead of an alias for Bookstack, as I have in other services.

Ideally, shoud appear as Taiga does, showing its own avatar and name, so a human can easily visually track the message among all the notifications
![imagen](https://user-images.githubusercontent.com/2266612/169350271-d3fec1c2-afaa-4333-bb37-d82bdd321985.png)
Monit send the default avatar, but at least can specify the alias
![imagen](https://user-images.githubusercontent.com/2266612/169350423-a3d17617-578b-46bf-88a4-e028bfcbf1c8.png)
But Bookstack send no avatar nor alias for username, so it appears as the default user
![imagen](https://user-images.githubusercontent.com/2266612/169350696-a6dcbc8e-6a2d-441c-b032-c556eb3c311f.png)

### Describe the benefits this would bring to existing BookStack users

Showing its own avatar and username alias, can help humans to visually detect which notifications are important for them the most without reading all of them, specially when there are many of them

### Can the goal of this request already be achieved via other means?

We could create a separate chat room just for Bookstack notifications, and perhaps there are people that prefer to have one room per service, but there are others who will prefer to have all notifications in one room, for instance all system-related notifications from all services being received in one room, all new entries from kanban, bookstack, gitlab issues, etc on another room, etc.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @adocampo,

With webhooks I'm not really looking to officially support functionality or integrations of any specific chat applications, outside of providing the `text` property as a convenience helper since it's used by many messaging services, since it massively widens our scope of support.

I'd think this is generally something that can be achieved from the side of the chat application.
Are you not able to add an additional "Incoming Webhook" integration, specifically for BookStack, with a custom name and avatar configured, then point that into the same channel?

**Comment by adocampo** [comment]
Thank you for your answer @ssddanbrown 

Yes, it can do the trick, indeed. I didn't get to set the avatar yet, but at least it shows the alias "Bookstack", so it will do just fine for me.

Thank you very much!
