### ISSUE TITLE
Figma embeds not working

### ISSUE THREAD

**Issue by lpadula** [BookStackApp/BookStack#3450]
### Describe the Bug

Figma embeds are not allow via CSP directive.

### Steps to Reproduce

1. Create/Edit a page.
2. Insert figma embeds code.

### Expected Behaviour

Display figma embeds

### Browser Details

Edge and Chrome on Windows 11

### Exact BookStack Version

v22.04.2

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04 LTS (official installation script)

**Comment by ssddanbrown** [comment]
Hi @lpadula,
You'll need to enable figma's embed host to be allowed, please see the "Iframe Source Control" section of our security docs:
https://www.bookstackapp.com/docs/admin/security/#iframe-src-control

I'll therefore close this but feel free to comment if you face issues with doing that.
