### ISSUE TITLE
Export function not working 

### ISSUE THREAD

**Issue by theankitsinha** [BookStackApp/BookStack#3456]
### Describe the Bug

I have recently installed bookstack in ubuntu 20.04 , we have created some books and selves and it has some pages and chapters too, but when try to export in any format its opening new tab but nothing is happening it doesn't download any file, the newly opened tab gets closed automatically .

### Steps to Reproduce

Go to any selves or page in bookstack
click on export button 
select format
click to download 

But after this it doesn't download any file 

### Expected Behaviour

To download file after clicking on the file format

### Exact BookStack Version

v22.04.2

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04 , installed using script provided in docs, 
Installed SSL for apache 2,

**Comment by ssddanbrown** [comment]
Hi @theankitsinha,

Are you able to re-produce this by clicking the "Image Attachment" attachment on this page of our demo site?:
https://demo.bookstackapp.com/books/bookstack-demo-site/page/mixed-content-example-page

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
