### ISSUE TITLE
Add Latex codemirror option

### ISSUE THREAD

**Issue by p-ang** [BookStackApp/BookStack#3458]
### Describe the feature you'd like

Add code display option for LaTeX, which could allow code highlighting as illustrated here:

https://codemirror.net/mode/stex/index.html

I believe that the required mode files that need to be referenced in the bookstack source are available here:

https://github.com/codemirror/CodeMirror/tree/master/mode/stex

### Describe the benefits this would bring to existing BookStack users

It would allow users to beautifuly present LaTeX source code

### Can the goal of this request already be achieved via other means?

Not that I know of. I looked at earlier issues, and I can see that in the past users had to request for specific languages to be added.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @p-ang,
Latex code block highlighting has been added in 7c597a05f69c3c4637d213405e55e922844b46a8 and will be part of the next feature release.
