### ISSUE TITLE
No Tab Indenting in editor

### ISSUE THREAD

**Issue by nh-mike** [BookStackApp/BookStack#346]
Hi,

Currently, when inserting code into the TinyMCE Editor, the only compatible indenting is by using spaces. I am unsure whether the TinyMCE Editor supports this, but it would be nice if we could indent using the tab bar.

Thanks.

**Comment by nh-mike** [comment]
Hi,

I have commenced working on doing this myself and will create a merge request once I am happy with this, as I believe that this may be useful for many people.

I have started adding my code to resources\assets\js\directives.js but I have no experience with Angular, so progress is slow. At this point, I have it adding the indent and it saves nicely but it moves the caret to the beginning of the editor content and does not yet work with pasted text.

Also, I only intend for this to work inside code boxes.

I am happy to continue to see this through until I am happy with it.

Cheers.

**Comment by ssddanbrown** [comment]
@nh-mike Thanks for confirming this issue and offering to attempt to fix this. This is now fixed as of 968e7b8b72dba148166253c00e6b0d09b714888f as part of the new code editing features. It will be released as part of the upcoming v0.17 release. Therefore I will go ahead and close this issue.
