### ISSUE TITLE
执行出错：Failed to parse dotenv file due to an invalid name. Failed at

### ISSUE THREAD

**Issue by cclives789** [BookStackApp/BookStack#3463]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

docker中删除了.env 重新配置也是这个问题

密码中也仅有一个@符号，无其他特殊符号

php 7.4

### Exact BookStack Version

v2.4

### Log Content

执行出错：Failed to parse dotenv file due to an invalid name. Failed at [﻿#####################################################################]. [{"file":"\/app\/vendor\/vlucas\/phpdotenv\/src\/Parser.php","line":30,"function":"parseName","class":"Dotenv\\Parser","type":"::","args":["﻿#####################################################################"]},{"file":"\/app\/vendor\/vlucas\/phpdotenv\/src\/Loader.php","line":169,"function":"parse","class":"Dotenv\\Parser","type":"::","args":["﻿#####################################################################"]},{"file":"\/app\/vendor\/vlucas\/phpdotenv\/src\/Loader.php","line":107,"function":"processEntries","class":"Dotenv\\Loader","type":"->","args":[["﻿#####################################################################"

### PHP Version

7.4

### Hosting Environment

ubuntu 18

**Comment by ssddanbrown** [comment]
Hi @cclives789,

I'm confused by your setup.
Are you hosting BookStack using docker or are you running directly on Ubuntu? If using docker, what docker container image are you using?

Additionally, when i translate your message it mentions deleting a file. Is this correct and what exact file are you deleting?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
