### ISSUE TITLE
Logo being served over http instead of https.

### ISSUE THREAD

**Issue by tmikaeld** [BookStackApp/BookStack#347]
### For Feature Requests

Desired Feature: The logo should also be served over https so users get the green lock

### For Bug Reports

* BookStack Version: v0.15.2
* PHP Version: N/A
* MySQL Version: N/A

##### Expected Behavior

All content over https

##### Actual Behavior

Logo served over http

Tried adding the APP_URL=https://my.domain.com

But that didn't help

**Comment by tmikaeld** [comment]
Aah, noticed that if i switch to https then go to the setting and hit save - the URL for the logo is updated.

**Comment by ssddanbrown** [comment]
Missed the update on this, yeah, you need to be https when saving. Will therefore close this since a solution was found.

**Comment by luper769** [comment]
This is a rather handy piece of info. Is it possible to include this somewhere in the Bookstack docs?
