### ISSUE TITLE
Missing field `image_id` in API Call /api/books

### ISSUE THREAD

**Issue by bytepoets-ssi** [BookStackApp/BookStack#3474]
### Describe the Bug

The documentation mentions a field `image_id` but the API does not deliver it in API Call /api/books

### Steps to Reproduce

1. Log in to Bookstack
2. Create a book
3. Add a title image to the book
4. Open /api/books
5. Field `image_id` is missing for every book

### Expected Behaviour

The field `image_id` is returned for every book

### Screenshots or Additional Context

The field is mentioned in the source code, but isn't returned anyway
https://github.com/BookStackApp/BookStack/blob/7c597a05f69c3c4637d213405e55e922844b46a8/app/Http/Controllers/Api/BookApiController.php#L40

### Exact BookStack Version

v22.04.2

### Hosting Environment

https://demo.bookstackapp.com

**Comment by ssddanbrown** [comment]
Thanks for reporting @bytepoets-ssi. Looks like this property has been hidden for a couple of years, since about v0.30.0.
I'd suggest we simply remove it from the listing call and the API docs since I can't see it providing much value as-is.

**Comment by ssddanbrown** [comment]
As per my last comment, this property has now been removed for documentation.
Change will be included in the next feature release.
