### ISSUE TITLE
sort data in a table

### ISSUE THREAD

**Issue by libroc** [BookStackApp/BookStack#3475]
### Describe the feature you'd like

- I, primarily as an editor of a table, want to sort data in a table (column): From "A to Z" or "largest number to smallest".

### Describe the benefits this would bring to existing BookStack users

- Very useful for a first page with a variable index / table of content leading to pages / anchors.

### Can the goal of this request already be achieved via other means?

- Not really (e.g. copy/pasta in Excel, sort it, and back).

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

- As discussed [here](https://github.com/BookStackApp/BookStack/issues/1518), but not implemented yet.

**Comment by ssddanbrown** [comment]
Hi @libroc,
Does your issue fundamentally differ to issue  #1518, which you linked above?

**Comment by libroc** [comment]
Not really.

**Comment by libroc** [comment]
Not really, but built-in feature's still missing.

**Comment by ssddanbrown** [comment]
Thanks for confirming @libroc, I'll therefore close this off as a duplicate.
