### ISSUE TITLE
After installation it say's "Page not found"

### ISSUE THREAD

**Issue by tapashdutta009** [BookStackApp/BookStack#3476]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

![image](https://user-images.githubusercontent.com/79140277/172387878-5a21a6e1-93c6-43e7-b195-b13432a9ad39.png)

I followed the instruction and done the installation and also setup of the project is the 
http://43.**.**.16/knowledgebase_books
the URL looks like this, I stored it inside "knowledgebase_books" sub folder, using Apache server, DB migration also happened successfully. Any suggestion will be appreciated, thanks. 

### Exact BookStack Version

v22.04.2

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04, VPS

**Comment by ssddanbrown** [comment]
Hi @tapashdutta009,
How did you setup the `knowledgebase_books` sub-path? What does the webserver config look like? 

BookStack does not support being part of another website's sub-folder, so you can't just move the site to sub-folder of another, specific webserver config is required to handle this properly.

**Comment by tapashdutta009** [comment]
Ok, thanks for the information, I will try to setup the project in root folder.

**Comment by ssddanbrown** [comment]
Okay, Just keep in mind that the BookStack folder itself should not be in public web-space.
Only the public folder within your BookStack installation should be exposed to the web, as the document/web-root

**Comment by tapashdutta009** [comment]
> Okay, Just keep in mind that the BookStack folder itself should not be in public web-space. Only the public folder within your BookStack installation should be exposed to the web, as the document/web-root

Sure, thanks

**Comment by ssddanbrown** [comment]
I'll therefore close this off but if you need further assistance feel free to still comment.
