### ISSUE TITLE
Unlisted Pages

### ISSUE THREAD

**Issue by morcousw** [BookStackApp/BookStack#3479]
### Describe the feature you'd like

This is similar to YouTube's "unlisted" videos - they are accessible via link, but don't show up in Search Results or Recommendations.

A page that is "unlisted" would not show up in Search Results, would not show up in "Recently Updated" blocks, the "Recently Updated Pages" page, or the "Popular Pages" block. It would still be accessible via link and still accessible via the Book page or Chapter page (assuming user has access to the Book/Chapter, and has access to view the Page).

### Describe the benefits this would bring to existing BookStack users

For the last year or so I've been using BookStack as my own personal Wiki for note-taking and keeping records. Many times, I want to share a link to a specific page for others to reference or use. However, I'd like to do that without exposing other pages.

I may have made page A public to share with group A, and page B public to share with group B... but I don't necessarily want group A to see page B or vice versa.

I've run into this several times in the last year, and I got "close enough" by making chapters and books and shelves not public (i.e. hiding the internal hierarchy from being navigated).

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

Because of my need for this feature, I I have implemented it on my Local Instance via an additional column `unlisted` on the `pages` table and a checkbox on the Permissions page with various updates to Search, Recently Updated and Popular blocks. I would not mind refining it and opening a PR if the feature is desired, or even extending it to Books, Shelves, Chapters if that's desired.

**Comment by ssddanbrown** [comment]
Hi @morcousw,
Thanks for the clear request.

Although a different implementation idea, would the feature requested in #288 essentially cover your fundamental need here?

**Comment by morcousw** [comment]
Yes that would absolutely cover the need!
