### ISSUE TITLE
markdown table support?

### ISSUE THREAD

**Issue by zhangchengshan** [BookStackApp/BookStack#348]
### For Feature Requests

bookstack can support table with '|--|--|' style?

### For Bug Reports

* BookStack Version:0.15.2
* PHP Version:7.0.12
* MySQL Version:5.6

**Comment by juniorrocha** [comment]
Yes, bookstack already support table, example:

key | value
|:--:|:----:|
|a|1|

The coluns able to align text.
In the example above, the text will be centralized. 
If you want to align to left, use: |:-| and right: |-:|

Simple like that!
