### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by alexohneander** [BookStackApp/BookStack#3482]
### Describe the Bug

I get a timeout when I'm trying to export a certain page as PDF.
I have already increased the max_execution_time in my PHP.ini. 
Unfortunately, this did not help.

### Steps to Reproduce

1. Open Entry
2. Export as PDF

### Expected Behaviour

If I export the entry as a PDF, that I can download it.

### Exact BookStack Version

v21.05.2

### PHP Version

7

### Hosting Environment

The whole thing runs in my Kubernetes cluster as a deployment (Docker).
The PHP.ini file I edited is: `/etc/php7/php.ini`

Docker Image: `linuxserver/bookstack:version-v21.05.2`

**Comment by ssddanbrown** [comment]
Hi @alexohneander,

It's not clear to me where the `php.ini`, which you are editing, exists? Is this inside the container?

The linuxserver container image exposes a `php/php-local.ini` file within the advised-mounted `/config` directory, for making local php config edits. Do you have such a file?

**Comment by alexohneander** [comment]
> Hi @alexohneander,
> 
> It's not clear to me where the `php.ini`, which you are editing, exists? Is this inside the container?
> 
> The linuxserver container image exposes a `php/php-local.ini` file within the advised-mounted `/config` directory, for making local php config edits. Do you have such a file?

Yes, that's exactly what I edited. @ssddanbrown 
`/config/php/php-local.ini`

Content:
```ini
; Edit this file to override php.ini directives and restart the container

date.timezone = 
upload_max_filesize = 500M
post_max_size = 500M
max_execution_timeout = 3000
```

**Comment by ssddanbrown** [comment]
Hi @alexohneander,
A few things:

- The property is [`max_execution_time`](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time), not `max_execution_timeout`.
- Are you restarting your container(s) after changing this?
- Are you editing from within the container or via a file on the host that is being passed through as a volume?

**Comment by alexohneander** [comment]
Hi @ssddanbrown,
`max_execution_time` fixed it for me. 

Thank you very much.
