### ISSUE TITLE
Gitlab OAuth SSO provider

### ISSUE THREAD

**Issue by MitchMaris** [BookStackApp/BookStack#349]
Gitlab OAuth SSO provider (self hosted, not gitlab.com)

Hi,

It would be great if you could show me how to integrate my self hosted gitlab server's SSO OAuth provider into BookStack.

I'm not afraid of coding, and Will pull a copy down onto my dev box but I figured if you could point/show me where I need to modify or have this feature added I'd be very grateful.

**Comment by ssddanbrown** [comment]
Hi @MitchMaris, Sorry for my delayed response.

Adding new providers is fairly simply to do if you have some prior knowledge of the Laravel framework.
Laravel has a social login provider framework called 'Socialite' which makes adding new social provides quite quick. In fact, someone has already created a provider for GitLab.

The following page would be a good place to start:
http://socialiteproviders.github.io/providers/gitlab/

It has steps for installing into an application. There's going to be a few BookStack specific things as well but I'm happy to help if you take a crack at coding this.

**Comment by MitchMaris** [comment]
sounds good. I'll setup a dev vm and pull the code. If it ends up working, maybe I'll make a push request. Thanks for the info!

**Comment by ssddanbrown** [comment]
Added in #691, Will be in the next release (v0.20).
