### ISSUE TITLE
Possibility to hide only part of pages to guest/public ?

### ISSUE THREAD

**Issue by eskiiom** [BookStackApp/BookStack#3491]
### Describe the feature you'd like

Hello everyone,
The tool you made is absolutely awesome for homelab and sharing amongst friends :)
I had a quick look on the Internet and didn't find the answer.

Is there a possibility to hide only part of pages to guest/public ?
Something like a "confidential" tag in order to protect some personal, important or confidential content (phone, IP address, serveur name, screenshots ...) we could put in some pages.

Thank you very much 
and sorry if the answer is obvious, but in this case I genuinely missed it.

### Describe the benefits this would bring to existing BookStack users

It may already exist or it may not be feasible but it would be a nice to have

### Can the goal of this request already be achieved via other means?

hiding full pages or books

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request and kind feedback @eskiiom!

This has been previously requested within #978 which mentions a (albeit complex) method to achieve this with current functionality.
Unless there's further context to add upon that I'll likely look to close this off as out of scope with the same reasoning as given on #978.

**Comment by eskiiom** [comment]
Hey @ssddanbrown thanks for the quick reply. 

In fact my feature request seems more simple than in issue 978 because it's just about setting part of the content as confidential. 
But I can understand it's not an easy one to implement :)
No problem if you wish to close it

Have a nice weekend

**Comment by ssddanbrown** [comment]
Thanks for confirming, I will therefore close this off.
