### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by rmfooty** [BookStackApp/BookStack#3500]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi.

I am trying to books over manually to a new instance. When I migrate the Books table, it will not show any of the import data. It will only show new books that have been created using the UI.

Has anyone else had the same issue. 

### Exact BookStack Version

v22.04.2

### PHP Version

8

### Hosting Environment

AWS Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @rmfooty,
We don't really support partial migration of specific tables from one instance to another.
There's a lot of related data in connected tables which will impact things.
For example, you're likely not seeing content since the related permisison data does not exist in the system.

If possible, you'd generally want to migrate the entire database as a whole otherwise you will likely face issues.

**Comment by rmfooty** [comment]
Hi @ssddanbrown. 

We are trying to migrate the application from an old instance to the current version. Unfortunately we cant do a direct migration as the table fields have changed on a few tables. We have added the new fields and then found that the data was not showing. Even if we modify a simple book record with no other dependencies, it wont show in the UI.

**Comment by ssddanbrown** [comment]
> We are trying to migrate the application from an old instance to the current version. Unfortunately we cant do a direct migration as the table fields have changed on a few tables.

You should not need to do any manual database changes. BookStack will auto-migrate old app database versions to newer versions as needed. You should just export & backup your old clean database, then restore into an empty database on the new system then run the BookStack update commands. 

> Even if we modify a simple book record with no other dependencies, it wont show in the UI.

Again, you'll be fighting the permission system. We have commands to regenerate permission system intermediate tables but you should ideally update/migrate your data as above as there are many issues you may run into with partial data migrations.

**Comment by rmfooty** [comment]
Worked like a dream. Thanks for your help :)
