### ISSUE TITLE
Iframe works on desktop but not on mobile

### ISSUE THREAD

**Issue by thomasmoors** [BookStackApp/BookStack#3501]
### Describe the Bug

With the risk this is some browser specific bug.

I embedded a google calendar through an iframe. I had to add the google calendar domain to `ALLOWED_IFRAME_SOURCES`. Now it works on desktop (Chrome, windows) but not on mobile (Chrome, android). Any idea what this might be? If not I will tak some time in the future to debug the mobile browser through debugging tools, but it's a big hassle to set up.

Desktop
![image](https://user-images.githubusercontent.com/486765/173525359-3eab0f94-090b-46e4-aba1-9327c6197194.png)

Mobile
![image](https://user-images.githubusercontent.com/486765/173525447-3a1b56cc-bb7c-4aa3-a491-3408b7fdd64c.png)

### Steps to Reproduce

1. add to `ALLOWED_IFRAME_SOURCES` https://calendar.google.com
2. add a iframe to a page with google calendar
3. visit on mobile

### Expected Behaviour

To show the content of the iframe on the page on mobile

### Browser Details

chrome mobile

### Exact BookStack Version

BookStack v22.04.2

### Hosting Environment

shared

**Comment by ssddanbrown** [comment]
Hi @thomasmoors,
Does this also occur in a private/incognito window on desktop?

I have a feeling this may occur if the iframe attempts to go through the authentication process, and hence go across a different domain or go to the google accounts domain which may not allow embedding.

You could update your `ALLOWED_IFRAME_SOURCES` to instead contain `https://*.google.com` to allow all google subdomains but it may not help if it's the subdomain site itself which is preventing use within an iframe.

**Comment by thomasmoors** [comment]
Adding the wildcard fixed it. Good thinking, for me it's weird the iframe behaves differently.
