### ISSUE TITLE
Add same chapter/page to multiple books (in the meaning of a link, not a copy)

### ISSUE THREAD

**Issue by Der-K-2000** [BookStackApp/BookStack#3506]
### Describe the feature you'd like

So far you only can `link` **one** book to **several** shelves. In the same _though_ it would be a helpful feature to available that also **for chapters and pages**, which are linked to more than one book. Currently you have to copy everything, while it's difficult to edit those pages later, if only one page is edited.

### Describe the benefits this would bring to existing BookStack users

In huge productions with many authors, many projects and much content it's (in my case) often necessary to have (redundant) content in multiple Books and/or Chapters. And also to have the same Chapters (with the exact same page-content) in multiple Books.

So actually it's only a "link" from a page to one or several Books/Chapters. At least for the pages it would be a big help to add one of them to multiple books.

### Can the goal of this request already be achieved via other means?

No, not yet, I guess.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @SebastianBerlin but I'm going to close this off as a duplicate since I feel the fundamental request is already covered by existing issues #182 and #1360

**Comment by Der-K-2000** [comment]
Oh sorry, I checked many entries for this suggestion, but I've overseen it obviously.
