### ISSUE TITLE
Code snippet appearing as single line in edit mode

### ISSUE THREAD

**Issue by monabomble** [BookStackApp/BookStack#3507]
### Describe the Bug

With the latest release (22.04.2), it appears a bug has been introduced within the edit UI.
When I enter a code snippet (CTRL-SHIFT-E) and hit 'Save Code' the snippet is displayed as one single line. If I either save the page at that point OR open the code snippet editor and hit 'Save Code' a second time, the snippet is displayed correctly (multiple lines).

### Steps to Reproduce

1. Start editing any page
2. Open a new code snippet editor with CTRL-E
3. enter a multi-line snippet
4. Click 'Save Code'
5. The code snippet with be displayed as a single line

### Expected Behaviour

Even whilst editing a page a multi-line code snippet would appear as multiple lines and not one single line.

### Screenshots or Additional Context

![edit_code](https://user-images.githubusercontent.com/64267954/174308277-5e77ee3a-1b77-428c-8852-edc46b3beade.png)
![view](https://user-images.githubusercontent.com/64267954/174308323-5e80d138-a641-4460-9a0e-957d7e569fb7.png)

### Browser Details

Firefox 100.0.2 (64-bit) on Pop!_OS 22.04 LTS

### Exact BookStack Version

v22.0.4.2

### Hosting Environment

We are using the LinuxServer Docker image. Specifically:

linuxserver/bookstack             latest    ed4f031b5e08

**Comment by ssddanbrown** [comment]
Thanks for reporting @monabomble. Can confirm this behaviour. Have assigned to be fixed for the next feature release.

**Comment by monabomble** [comment]
Thank you Dan!
