### ISSUE TITLE
Add ocaml as a supported language in codesample

### ISSUE THREAD

**Issue by ericgaspar** [BookStackApp/BookStack#3511]
### Describe the feature you'd like

Add ocaml as a supported language in codesample

### Describe the benefits this would bring to existing BookStack users

ocaml is the default language learned in French 'classes préparatoires' alongside C and Python

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Looks [already built-in](https://github.com/BookStackApp/BookStack/blob/19d7e26dda84e75344c4915df28c04b597c8713a/resources/js/code.mjs#L74), just needs to be added to code manager list.

Modemap might also need updating to use the mime-style modes defined here for full highlighting:
https://codemirror.net/5/mode/mllike/index.html

**Comment by ssddanbrown** [comment]
Now added as of the changes within #3512.
Will be part of the next feature release.
