### ISSUE TITLE
Add "book" and "books" as variables

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#3513]
### Describe the feature you'd like

First of all thanks for the great work.

My thought is that if the words "book" and "books" are present as variables in the language files, and they can be edited individually by users.

### Describe the benefits this would bring to existing BookStack users

In this way, BookStack could be used for almost all collectible objects.

### Can the goal of this request already be achieved via other means?

Manually editing of language files only.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

I edited the language files manually and use them for my vinyl collection.

![20220620-1000](https://user-images.githubusercontent.com/58190287/174647495-f2ab11d5-ac64-4be2-9a5b-7068460f6cf5.jpg)

**Comment by ssddanbrown** [comment]
Hi @memo-567, Thanks for the request and kind feedback!

I believe the fundamental request here is already covered by open issue #2901 so I'll therefore close this off as a duplicate. You can also refer to #406 to see history of this request. Let me know if I've misunderstood though and I could re-open this if required. 

Note: It's possible to override built-in text without editing the original app files using the visual theme system:
- [Guide](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) - See "Customizing Text Content" section.
- [Video Guide](https://www.youtube.com/watch?v=gLy_2GBse48) - I override some text as an example in this demo.

**Comment by ghost** [comment]
I guess I missed that after searching.

Sorry, and thanks for the notice 👍
