### ISSUE TITLE
Port set in env file

### ISSUE THREAD

**Issue by Stoiker** [BookStackApp/BookStack#3514]
### Describe the feature you'd like

The port the application listens to can be set in the env-file.

### Describe the benefits this would bring to existing BookStack users

To use Bockstack behind a reverse proxy (like nginx) it would be great if the application could be configured in such a way that the port it listens to is set in the env-file. 

My current problem is that with podman port 80 is restricted as mapped port in a pod and I want nginx to use that port.

Would that be feasible?

### Can the goal of this request already be achieved via other means?

Not afaik

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @Stoiker,
None of the release content within this core project/repo listens to a port.
The port is usually handled by the webserver in use.

If you're using one of the community containers, usually they expose 80 by default but you can usually map a different host port to port 80 of the container, when running/starting the container.

**Comment by Stoiker** [comment]
Hi @ssddanbrown 
that makes sense. Doing multiple container recently, lead to a mix-up in my mind ...
Sorry for the inconvenience.
