### ISSUE TITLE
Notifications...

### ISSUE THREAD

**Issue by jacksonp2008** [BookStackApp/BookStack#352]
### For Feature Requests

Any chance you will be adding notifications in the near term for new books or pages?  Email would be fine, webhook, or RSS feed would also work.

If no, can you provide a suggestions on where you might implement this and we will take a look?

Thanks
-Steve

**Comment by ssddanbrown** [comment]
HI @jacksonp2008, I have added to the discussion in #147. Since this issue covers the same general request I will close this issue.
