### ISSUE TITLE
Customization Tab Layout in Settings breaks

### ISSUE THREAD

**Issue by DiscordDigital** [BookStackApp/BookStack#3523]
### Describe the Bug

When you go to the settings and insert a long string into the "Custom HTML Head Content", the layout of the page will break.

### Steps to Reproduce

1. Go to settings
2. Click on Customization
3. Enter a long text into the "Custom HTML Head Content" input field, until the page layout starts expanding.

### Expected Behaviour

The text should start overflowing with a scrollbar in the input field for "Custom HTML Head Content"

### Screenshots or Additional Context

Screenshot:
https://cdn.discord.digital/bookstack-bug.png

### Browser Details

Chrome 102.0.5005.115

### Exact BookStack Version

v22.06

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04 VM

**Comment by ssddanbrown** [comment]
Whoops! Can confirm this, Thanks for reporting @DiscordDigital, have assigned to the next patch release.

**Comment by ssddanbrown** [comment]
This has now been patched in 0801955a26393cbf286596826b9cccde83dc7850 and will be part of the next patch release.
