### ISSUE TITLE
Emeded Video's - This content is blocked.

### ISSUE THREAD

**Issue by davecowley** [BookStackApp/BookStack#3525]
### Describe the Bug

I have upgraded to the latest version and embeded videos are saying that the content is blocked and to contact the site owner to fix the issue.
![chrome_SbKsIIJMkv](https://user-images.githubusercontent.com/89160018/175567531-db86cbe0-50fa-4043-bc9d-c6bcc344939f.png)

### Steps to Reproduce

Go to article, and embed a known shared video on the article and post.

### Expected Behaviour

Video preview to be there. 

### Screenshots or Additional Context

I have upgraded to the latest version this week but only noticed today.

### Browser Details

Chrome, Edge, firefox

### Exact BookStack Version

22.04.2

### PHP Version

PHP 7.4.28

### Hosting Environment

 Ubuntu 18.04.6 LTS on Hyper-V

**Comment by ssddanbrown** [comment]
Hi @davecowley,
This is very much likely related to update notice for v22.02.3:
https://www.bookstackapp.com/docs/admin/updates/#updating-to-v22023-or-higher

**Comment by davecowley** [comment]
Hi @ssddanbrown 

thanks for your help, I added the line in as mentioned and it worked.

for anyone else reading this.

add this line to your .env file /var/www/bookstack/.env

ALLOWED_IFRAME_SOURCES="https://*.draw.io https://*.youtube.com https://*.youtube-nocookie.com https://*.vimeo.com https://*.microsoftstream.com"
