### ISSUE TITLE
Can't add book tags anymore

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#3527]
### Describe the Bug

Can't add book tags after update to BookStack v22.06 anymore.

### Steps to Reproduce

Try to add book tags as usual.

### Expected Behaviour

Book tag has to be added to book / item

### Browser Details

Chrome / Firefox ...

### Exact BookStack Version

v22.06 

### Hosting Environment

Debian 11 Bullseye

**Comment by ghost** [comment]
Maybe also good to know: BoockStack as been installed thought YunoHost script.

**Comment by ssddanbrown** [comment]
Hi @memo-567, Thanks for reporting. I can confirm this issue. Apologies for this. Have assigned to the next patch release.

**Comment by ghost** [comment]
No problem at all. I'm looking forward to the next patch.

**Comment by ssddanbrown** [comment]
This has now been fixed in 3ed1ffdbeb043431788c87f761cabda52fd379db and will be part of the next patch release.
