### ISSUE TITLE
Clear link to content search field after closing the box

### ISSUE THREAD

**Issue by Tagirijus** [BookStackApp/BookStack#3528]
### Describe the feature you'd like

When using _Ctrl+Shift+K_ or the respecting button to link to another content, you can search for e.g. book titles or pages and select things you have found then. The box closes and the content will be linked. If you **now** want to link to another content, the box opens again, but still has the old search text in the search bar. I would like the bar to be cleared after the box closes or so.

### Describe the benefits this would bring to existing BookStack users

In my eyes it a) would improve the workflow, since you probably do not want to link to the exact content twice that often and b) it almost feels like a not-intuitive behaviour; maybe almost like some kind of bug.

### Can the goal of this request already be achieved via other means?

Instead of clearing the field it might be an option to automatically select the search bars content after opening the linking box. That way a user could start typing straight ahead to search for another content without the need of it to be deleted. This can, already, be achieved manually via _Ctrl-A_, for example.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @Tagirijus.

This has now been amended in c9d0e22132ad72752ef1b545cac1f0b12b30479b, to reset the selector interface upon selection, and these changes will be part of the next patch release.

**Comment by Tagirijus** [comment]
Well, this was fast. Thank you!! (=
