### ISSUE TITLE
Error translate

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3529]
### Describe the Bug

Translations in the settings navigation do not work in the new version 22.06
![image](https://user-images.githubusercontent.com/4026090/175775049-30c6d6d1-b1ab-4ada-b154-1a4c6df7a31b.png)

### Steps to Reproduce

Go to settings

### Expected Behaviour

-

### Exact BookStack Version

22.06

### PHP Version

8.1

### Hosting Environment

Windows Server 2019

**Comment by ssddanbrown** [comment]
Thanks for reporting @Statium, This has been patched in 12c282597d6e5d5d257f3e8b33db66b5ce8b0fca to be part of the next patch release.
