### ISSUE TITLE
Sorting for pages?

### ISSUE THREAD

**Issue by mcblum** [BookStackApp/BookStack#353]
### For Feature Requests

Desired Feature:
It would be amazing to be able to sort pages the way you can sort chapters! I often mess up the order and then need to correct it later. 

Thank you for this awesome software!
Matt

**Comment by mcblum** [comment]
Closing because idiot.

**Comment by stev0thegreat** [comment]
I landed here looking for the same thing. Guessing I need to look harder or level-up my google-fu eh?
😆

**Comment by bdillahu** [comment]
I will chime in that I'm another one that came here looking for the same thing. Seems like maybe the "sort" button could be active all the way down?

**Comment by chans08** [comment]
> I will chime in that I'm another one that came here looking for the same thing. Seems like maybe the "sort" button could be active all the way down?

I found page sort can be in book sort level.

**Comment by hawken93** [comment]
I would like to reorder some pages because I wanted to create an overview/introduction page. Any way to do this?

**Comment by bdillahu** [comment]
When you go to the Book there should be a “sort” command in the menu (under Edit)...

**Comment by hawken93** [comment]
> When you go to the Book there should be a “sort” command in the menu (under Edit)...

At first I thought you were misunderstanding me, but it worked! Thanks :)

**Comment by awnz** [comment]
Lol so many of us doing the exact same thing to land here :upside_down_face: 
Thank you @mcblum for the original question so the rest of us could google our way here!
