### ISSUE TITLE
Error translate

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3530]
### Describe the Bug

I also suggest adding translations of the color names in the code editor.
![image](https://user-images.githubusercontent.com/4026090/175775819-c7049bc0-4103-4715-9074-8c2f5857d884.png)

Also, when creating a new page, the wrong translation clearly appeared here.
![image](https://user-images.githubusercontent.com/4026090/175776016-72e0bde5-54af-4bf7-8b3c-737bb1d490ae.png)

### Steps to Reproduce

-

### Expected Behaviour

-

### Exact BookStack Version

22.06

### Hosting Environment

-

**Comment by ssddanbrown** [comment]
Thanks @Statium,
I've now simply removed text labels from the color grids. 
The page create activity text was correct in English so is likely a translation side issue, although I noticed this was updated shortly after this issue was opened.
