### ISSUE TITLE
"An unknown error occurred" after upgrading to 22.06.01

### ISSUE THREAD

**Issue by GustavJer** [BookStackApp/BookStack#3536]
### Describe the Bug

After upgrading from v22.02.3 to v22.06.01 almost everything in our Bookstack instance returns "An unknown error occurred". All shelves/books/chapters/pages are also missing.

I can still se my groups on my user profile but that is pretty much it.

I have rolled back our instance to a snapshot now but if needed I can upgrade again for further troubleshooting.

### Steps to Reproduce

1. Upgrade to v22.06.01 using git version control
2. Login to Bookstack - the landing page displays "An unknown error occurred".

### Expected Behaviour

Bookstack should function normally and return shelves/books/chapters/pages with no errors.

### Screenshots or Additional Context

![unnamed](https://user-images.githubusercontent.com/92147045/175891943-183195ed-15b8-41f4-85ee-d7cf769bf346.png)

### Exact BookStack Version

22.06.01

### Hosting Environment

Ubuntu 20.04 LTS, installed using official installation script.

**Comment by ssddanbrown** [comment]
Hi @GustavJer,
You will need to check your error log to find the cause of this error:
https://www.bookstackapp.com/docs/admin/debugging/#error-log-file

Based on your description, it's likely that some required database changes have not been applied.
Were there any issues when running the `php artisan migrate` step of the update instructions?

**Comment by GustavJer** [comment]
Hi @ssddanbrown 

I reran the update again and this time it went fine :)

Tho I noticed the same problem with the LDAP group mapping breaking which was already mentioned in #3535.
