### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by SwiftRedline** [BookStackApp/BookStack#3537]
### Describe the feature you'd like

Hello! 

i would prefer that a plugin system exists.
So u can develope your own plugin and implement it in to the system. 

That would be great! 

### Describe the benefits this would bring to existing BookStack users

More flexibility with plugins and program your own extensions. 

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

Please, if this feature get's real. Give me an update.

Regards,
Mav

**Comment by ssddanbrown** [comment]
Hi @SwiftRedline,
I'm going to close this off as a duplicate of existing open issue #127.
Please note my latest comment within https://github.com/BookStackApp/BookStack/issues/127#issuecomment-862656359, which details the available methods of extension.
