### ISSUE TITLE
Missing book authors when create new books

### ISSUE THREAD

**Issue by yangyt8024** [BookStackApp/BookStack#3539]
### Describe the feature you'd like

add authors when create new books

### Describe the benefits this would bring to existing BookStack users

easy for users to check & search books

### Can the goal of this request already be achieved via other means?

NO

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

<details>

![微信截图_20220627184153](https://user-images.githubusercontent.com/6180598/175926619-bdc6a8a0-3863-4df5-a323-32f34d6732ae.png)

</details>

**Comment by ssddanbrown** [comment]
Hi @yangyt8024, Thanks for the request.

To me it's not fully clear how this would fit into the platform or how it would achieve the described benefits.

I would not want to add an additional subsystem, that would have to be manually maintained to keep current, just to provide a little extra metadata to readers.
If you want to list your own idea of "Authors" for searching upon, you could already do this using tags. 

Would this request achieve anything significant upon simply using tags to define the authors?

**Comment by yangyt8024** [comment]
I thought about it carefully, mainly because the tag is not displayed to public users. If I plan to put more than 100 books, it will be difficult to manage for users and admin.

**Comment by ssddanbrown** [comment]
> the tag is not displayed to public users

Tags are displayed to everyone that can see the content they're assigned to. There is no additional permission/visibility control of tags upon the content itself.

**Comment by yangyt8024** [comment]
is it possible to show target in book list? it will easy for reader
![微信图片_20220704095013](https://user-images.githubusercontent.com/6180598/177069082-3120e64a-ad1c-4113-865f-628303cf741f.png)
not only book itself
![微信图片_20220704095026](https://user-images.githubusercontent.com/6180598/177069166-a2cdd7f5-1b0d-498f-a26a-c9f8c5c50353.png)

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since, as per the above, I don't think think adding functionality, upon that provided by tags, would be worthwhile.
I would not look to add tags to list items either, at least within the scope of this context, but if you've got some code skills you could look to customize the used views using our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md).
