### ISSUE TITLE
Connection to Local Host

### ISSUE THREAD

**Issue by sharonvillines** [BookStackApp/BookStack#3541]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have Bookstacks installed. Used MAMP to set up local server. Server opens bookstack but only as HTML pages. Which I think means it isn't connected to the database. I don't know how to correct this.

Bookstack is installed in  Applications > MAMP > htdocs

Not in User_name > Applications

### Exact BookStack Version

22.6.2

### Log Content

``

### PHP Version

Most recent — just dowloaded it.

### Hosting Environment

MacBook Pro, OS 12.4, MAMP, Adobe2, PHP

**Comment by ssddanbrown** [comment]
Hi @sharonvillines,

> Server opens bookstack but only as HTML pages.

It's not clear what this fully means.
- Have you configured your apache web root to be the `public` folder of the BookStack installation?
- Are you following our [manual installation steps](https://www.bookstackapp.com/docs/admin/installation/#manual)?

To confirm, you can't just place the BookStack install files in the `htdocs` folder and have it start working, like you can some other PHP application.

**Comment by sharonvillines** [comment]
I’ve been working on this for a week and am pretty brain fried but I’m very eager to try this app.

I’ve deleted and reinstalled using MAMP, Homebrew, and Docker several times, reading instructions and watching videos.

Your manual installation steps don’t get the connection done — I do not know the language used in terminal. And I’ve followed them several times.

Mamp says to install Bookstack in the htpdocs folder so I did. Mamp and I now see the index page when go to localhost:8888.

Sharon

**Comment by ssddanbrown** [comment]
Alright, Just to confirm though, this is built to be a web application, rather than a easy-to-run local app. If you're having a lot of trouble at this stage, you may also find keeping your instance maintained & up-to-date troublesome.

It's hard to understand the state of your environment, but the following may help:
- There should be some kind of "Document Root" or "Web Root" option in MAMP. This should point to the `public` folder of your BookStack install.
- You will need to use the command line to get BookStack working, specifically to download the required dependancies using composer and to run bookstack commands such as `php artisan migrate`.
- You will need to be able to access and manage the database, to create a user and database schema to use with BookStack. The user must have full privileges for that database. 
- If you've downloaded the files manually (As a ZIP) instead of using git as per the instructions you'll likely have trouble updating in the future and, depending on what exactly you've downloaded, you may not have all the files needed.

**Comment by sharonvillines** [comment]
Thank you — I’ll work on that information in the morning.

I’m working on this as the information storage module of a community management software so it would be hosted on the web. We use Bluehost and Siteground. Siteground won’t host this because the program requires server access. I suspect Bluehost will say the same thing. 

Who would host it? I understand you don’t provide support for that but we have  to put it out there somewhere. And find someone who speaks Terminal.

Sharon

**Comment by ssddanbrown** [comment]
> Who would host it? 

It can be hosted on most VPS offerings, although they require a little knowledge of managing a system. An example of doing this can be [seen in my video here](https://www.youtube.com/watch?v=ShqUjt33uOs).

Alternatively, some hosts do offer BookStack support. 
- [Cloudabove](https://cloudabove.com/hosting/starter) is a UK host that is supporting us, and has mentioned they can support users with running BookStack
- [Stellarhosted](https://www.stellarhosted.com/bookstack/) is another sponsor of ours that offers BookStack specific hosting.
- Upon this you can find a [few extra options on our install page](https://www.bookstackapp.com/docs/admin/installation/#other).

**Comment by sharonvillines** [comment]
I contacted Cloudabove and told them I was looking  for a host for Bookstack that would also host my other sites. I talked to Ryan Devonshire and Ashley Cawley (via email) and had a Bookstack site set up within 24 hours. They said they are planning a program for hosting Bookstack sites free but haven’t started it yet. But they set one up for me. If it goes well, I’ll move my Siteground stuff there.

Questions:  

I’ve started designing shelves, books, etc., and everything works very well. The size of the text and the headings seems too extreme. Viewed actual size the text is the right size for me (others would want larger) but the headings take up a lot of space. If I reduce the size of the headings, the text is too small. Is there any ability for an admin user to modify the CSS?

One of the uses I’m hoping to use Bookstack for is a photo album. I don’t understand the note about how photos would be stored. These pages would only be available to registered members. But there would be well over 1,000 so they have to load normally.

Thank you,
Sharon.

**Comment by ssddanbrown** [comment]
>  If I reduce the size of the headings, the text is too small. Is there any ability for an admin user to modify the CSS?

Yeah, Within the settings you'll find a "Custom HTML Head Content" setting where you could add css. An example of changing the large heading size might look like:

```html
<style>
.page-content h2 { font-size: 20px; }
</style>
```

> One of the uses I’m hoping to use Bookstack for is a photo album.

Okay. To be up-front, BookStack is not designed as a photo album system so we don't have many features built specifically for this. 

> I don’t understand the note about how photos would be stored.

You might have to point me directly to what note you're referencing here for me to provide an accurate answer.

**Comment by sharonvillines** [comment]
On Jun 30, 2022, at 8:36 PM, Dan Brown ***@***.***> wrote:

> One of the uses I’m hoping to use Bookstack for is a photo album.
> 
> Okay. To be up-front, BookStack is not designed as a photo album system so we don't have many features built specifically for this.
> 
> I don’t understand the note about how photos would be stored.

This is the note on the Features and Security page:

> Higher Security Image Uploads
> For performance reasons, all images are public. This option adds a random, hard-to-guess string in front of image urls. Ensure directory indexes are not enabled to prevent easy access.

I use a Wordpress wiki now for a photo album of 1000+ photos. I don’t like the gallery programs, actually, because using a wiki allows people to search for a year, name, event, subject and see all the photos in that category. Albums require that I assemble each one of them and keep them up to date.

The whole site would be private and everyone has to sign in. I don’t know what this means in terms of speed, server stress, etc.

Another question about importing files — how can posts from current Wordpress installations be imported? 

Sharon

(Loving the program. Lovely graphics. Excellent writing in the Admin Documentation.)

**Comment by ssddanbrown** [comment]
### Image Uploads

By default any images are uploaded into publicly accessible space. If someone external to the application guessed (or found) the URL of an image they could see it. The "Higher Security Image Uploads" setting adds a hard-to-guess random part of the name for make it harder to guess such image URLs. Alternatively, there is an alternative image storage system that would require login to see any of the uploaded images. This can impact performance but it's usually not a massive amount. You'd need to consider if any kind of access to your images would be a problem.

### Wordpress

There's no built-in import for wordpress content. Such integration would likely be possible, using the BookStack REST API, if you have some development skills, but there logic required to handing converting content may end up complex.

**Comment by sharonvillines** [comment]
I’m in the process of setting up a Bookstack model for Cohousing communities to track their Buildings & Grounds, Social History, Current events, Governance and Decision-making. I’m trying to sort out a suggested set of bookshelves, books, chapters, pages for a new community and one 30 years old. 

What I’m missing is being able to see the whole “table of contents” in one place. I’m getting dizzy clicking back and forth to see what I’ve just entered or not entered yet. And being able to see everything on one screen.

How can I create this? Attached screenshot of wordpress wiki installation.

Sharon

**Comment by ssddanbrown** [comment]
@sharonvillines I don't think screenshots work on the GitHub reply-by-email feature.

I'm assuming it's a big hierarchical list of everything in the system? If so, there's no such singular list built in at this time.

**Comment by ssddanbrown** [comment]
Since this support chain has run its course I'll close this thread off.
