### ISSUE TITLE
Customize layout of content pages

### ISSUE THREAD

**Issue by calliostro** [BookStackApp/BookStack#3548]
### Describe the feature you'd like

It would be nice if you could easily customize the layout of the content pages:

- Be it that you can store a CSS file in the configuration file   _-- or --_
- To set certain styles via the settings dialog like font size, spacing, headers etc.

### Describe the benefits this would bring to existing BookStack users

You can make the most important part of BookStack the way you want - that is, the content pages.

I like the GitHhub style very much and have a few hacks built into my installation that [this file](https://github.com/sindresorhus/github-markdown-css
) overwrites just the page styles provided by BookStack. Not the overall BookStack layout.

### Can the goal of this request already be achieved via other means?

Yes, by editing the internal CSS files

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

There was already a discussion: https://github.com/BookStackApp/BookStack/issues/1581

My suggestion is to outsource the default design for pages to a separate CSS file, which can then be customized by server admins - or e.g. replaced by another (external) file through a configuration setting.

**Comment by ssddanbrown** [comment]
Hi @calliostro,
There are a couple of ways to make customization as required without editing core files. Specifically the "Custom HTML Head Content" setting or the visual theme system. Both of these are mentioned on this page:
https://www.bookstackapp.com/docs/admin/hacking-bookstack/

If you're already aware of these methods, just let me know what you're expecting in addition to these options or why these are not suitable.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be addressed respond to my previous comment and this can then be re-opened.
