### ISSUE TITLE
Inconsistent Shelf Naming

### ISSUE THREAD

**Issue by tyfai** [BookStackApp/BookStack#3553]
### Describe the Bug

This isn't a bug as such, but I've noticed some inconsistent naming around shelves.

When creating shelves the copy reads "Create New Shelf". The item in the navigation bar reads "Shelves".

However when editing shelves the copy reads "Edit Bookshelf". The same is true for deleting as the copy reads "Delete Bookshelf".

I think it would be good to standardise on one name for shelves on the frontend. As a new user it was slightly jarring to be presented with two terms for the same thing. Either "Bookshelf" or "Shelf" is fine, but I think being consistent is important.

### Steps to Reproduce

See above.

### Expected Behaviour

See above.

### Exact BookStack Version

N/A

### Hosting Environment

N/A

**Comment by MagnusHJensen** [comment]
So what is the proposed wording, "Bookshelf" or just "Shelf"

**Comment by tyfai** [comment]
I assume that question is for @ssddanbrown, but I'm happy to share my opinion if it helps:

I would propose using the word "Shelf". I think it's clear that in the context of BookStack a shelf would only contain books.

It's also a shorter word! :)

**Comment by ssddanbrown** [comment]
Thanks for raising @tyfai.
Have aligned the term to be "Shelf" in commit 9da3130a12301c9b2cc52a3bb6ada2d65a66c106.
Might take a while for non-English languages to catch-up with this change. 
Will be part of the next release.

**Comment by tyfai** [comment]
Excellent, thank you for sorting this.
