### ISSUE TITLE
Comment count incorrect on Chinese language options

### ISSUE THREAD

**Issue by GongMingCai** [BookStackApp/BookStack#3554]
### Describe the Bug

when i set application default language to 'zh_CN' or 'zh_TW', then add or delete comment for a page, as a result, the comment count no update and show as below image.

![image](https://user-images.githubusercontent.com/88075411/177520743-f2a6f3cd-cf46-45da-89dc-a13570f89698.png)

![image](https://user-images.githubusercontent.com/88075411/177521315-16136409-7b12-460d-8b00-9a4734dd3b65.png)

### Steps to Reproduce

1. set .env file APP_LANG=zh_CN or APP_LANG=zh_TW
2. open a page and add some comments
3. the comment count no updae

### Expected Behaviour

the comment count should update normally

### Browser Details

Version 103.0.5060.114 (Official Build) (64-bit)

### Exact BookStack Version

v22.06.2

### PHP Version

8.0.20

### Hosting Environment

Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Comment by ssddanbrown** [comment]
Thanks for reporting @GongMingCai.
Done some testing across these languages, based upon that, this should be addressed by commit 9d54cb2254599ae2e506d519f779120d8942eca0 which will be part of the next feature release.
