### ISSUE TITLE
Truncate IP addresses for GDPR reasons

### ISSUE THREAD

**Issue by Android1338** [BookStackApp/BookStack#3560]
### Describe the feature you'd like

For GDPR reasons it would be very nice if BookStack would give you the option to truncate IP addresses for any actions in the database with different configurations like the following examples:
- Full IP: 123.234.111.222
- Truncated IP long: 123.234.111.0
- Truncated IP short: 123.234.0.0
- Truncated IP very short (I think it's a little useless):123.0.0.0

If applicable also for IPv6.

### Describe the benefits this would bring to existing BookStack users

Storing less personal data in database

### Can the goal of this request already be achieved via other means?

No, I don't think so.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
This has now been added in 4e8995c3d0e4c738219fdfa4080b22cb40607bd2 and will be part of the next feature release.
The new option will be as follows:

```bash
# Alter the precision of IP addresses stored by BookStack.
# Should be a number between 0 and 4, where 4 retains the full IP address
# and 0 completely hides the IP address. As an example, a value of 2 for the
# IP address '146.191.42.4' would result in '146.191.x.x' being logged.
# For the IPv6 address '2001:db8:85a3:8d3:1319:8a2e:370:7348' this would result as:
# '2001:db8:85a3:8d3:x:x:x:x'
IP_ADDRESS_PRECISION=4
```
