### ISSUE TITLE
OIDC Keycloak

### ISSUE THREAD

**Issue by mv-yurchenko** [BookStackApp/BookStack#3562]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Added Keycloak as OIDC provider. Got the following error.
![image](https://user-images.githubusercontent.com/33545848/178139524-7c15b20e-8295-4fb4-8f44-845c1e2fbb38.png)

My KK config 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/33545848/178139534-bc5707a5-4b2e-4fbf-a098-2dc3ccce933a.png">

### Exact BookStack Version

latest

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Hi @mv-yurchenko,

This error usually means the configured `OIDC_ISSUER` does not exactly match that found in the response at your OIDC autodiscovery endpoint (`<issuer>/.well-known/openid-configuration`). Check the value there and ensure both exactly match, for the full text value.

**Comment by mv-yurchenko** [comment]
Solved with adding new tls to issuer.

**Comment by mv-yurchenko** [comment]
@ssddanbrown thanks for help.
I've got 1 more question. 
I need to pass admin privileges to bookstack from keycloak, is any docs about this?

**Comment by ssddanbrown** [comment]
@mv-yurchenko Ah, mentioned it in the other thread you commented on, but there is no current group/role sync for OIDC usage.
I'm taking feedback in https://github.com/BookStackApp/BookStack/issues/3004 to get an idea of data format for future support.

**Comment by ssddanbrown** [comment]
Since the original matter is solved I'll close this off.
