### ISSUE TITLE
Getting 419 after KK OIDC

### ISSUE THREAD

**Issue by mv-yurchenko** [BookStackApp/BookStack#3566]
### Describe the Bug

After deploying to k8s getting 419 error from url `https://wiki/oidc/login` when returns from OIDC. 

### Steps to Reproduce

1. Connect KK to BS with OIDC
2. Deploy to k8s with deployment
3. Try to login

### Expected Behaviour

Successful logic

### Exact BookStack Version

22.06.2

### Hosting Environment

Kubernetes (docker)

**Comment by ssddanbrown** [comment]
Such an error will usually indicate loss of cookies leading to a loss of session management.
Are you doing anything at any of the networking layers (Especially reverse proxy if involved) to alter HTTP headers or add security controls?

**Comment by mv-yurchenko** [comment]
I am not editing headers just using application load balancer (just route traffic on L3)

**Comment by ssddanbrown** [comment]
Okay, thinking further, I can only assume some misconfiguration is at play somewhere, likely on the keycloak side?
A 419 response would only generally occur on a POST request, not a GET request like what would be expected on the redirect back to BookStack. Is the BookStack client definitely set to use OIDC in keycloak? I'd expect a POST request if SAML2 was in use.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
