### ISSUE TITLE
GOOGLE_AUTO_REGISTER not working

### ISSUE THREAD

**Issue by BeyonityEurope** [BookStackApp/BookStack#3571]
### Describe the Bug

Users are not getting autoregistered when they press "login with google" with registration turned off.
The error is in german but it says: "This Google account is not assigned to a user yet"
[Laravel.log](https://github.com/BookStackApp/BookStack/files/9101749/bookstackGoogleAutoRegister.txt)

### Steps to Reproduce

0. setup google auth
1. Enable GOOGLE_AUTO_CONFIRM_EMAIL=true and GOOGLE_AUTO_REGISTER=true in .env
2. Try to login with a not registered google account

### Expected Behaviour

When user is not registered and successfully logs in with google it should create an account for the user ([as per documentation](https://www.bookstackapp.com/docs/admin/third-party-auth/#google)

### Exact BookStack Version

22.06.2

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @begehungen,

Please could you share the exact output of running the following command?:

```bash
ls -alh /var/www/bookstack/bootstrap/cache
```

And also the exact output of running this exact command:

```bash
cat /var/www/bookstack/.env | grep -n GOOGLE_AUTO
```

**Comment by BeyonityEurope** [comment]
@ssddanbrown 
![grafik](https://user-images.githubusercontent.com/60754810/178752102-63781604-8c3b-4758-84c1-7c7431cccdd8.png)

**Comment by ssddanbrown** [comment]
Thanks @begehungen,

It looks like an optimize/cache command has been run at some stage (29th June). This prevents config changes being active until the cache is cleared. 
Please run the following command to clear this cache:

```bash
rm /var/www/bookstack/bootstrap/cache/config.php
```

**Comment by BeyonityEurope** [comment]
thanks a lot! I will try that. I thought I cleared the cache with `sudo php artisan cache:clear`

**Comment by ssddanbrown** [comment]
> I thought I cleared the cache with `sudo php artisan cache:clear`

That does a different cache. There is the `php artisan config:clear` command which effectively does the same `rm` command as above.
