### ISSUE TITLE
[Feature request] A better guide for running bookstack locally

### ISSUE THREAD

**Issue by nikkwong** [BookStackApp/BookStack#3575]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I think many people may be interested in Bookstack but don't know much about mamp or PHP. I've spent the afternoon trying to run everything locally but am basically stuck at the MAMP part. I tried to go through the MAMP tutorial and otherwise set it up with reasonable defaults but it's way over my head as a new user; I think the quickstart expects a lot of knowledge that many might not have.

Thank you! 

### Exact BookStack Version

v21

### PHP Version

7.4

### Hosting Environment

Local on osx.

**Comment by ssddanbrown** [comment]
Thanks for the request @nikkwong, but I'm not looking to expand our documentation to detail additional environment-specific hosting options, outside of the generic guidance and Ubuntu-LTS scripts we already provide. 

If it helps, I recently produced a windows+xampp video guide, [found here](https://www.youtube.com/watch?v=_v-4BhVz7OI), which may share many similar steps to what you'd need.

**Comment by nikkwong** [comment]
This was exactly what I needed and got me set up in less than an hour, thank you! Maybe link to this somewhere in the docs.
