### ISSUE TITLE
Own book get lost

### ISSUE THREAD

**Issue by ChriFo** [BookStackApp/BookStack#3577]
### Describe the Bug

When changing the permission of a specific book to have no role permissions the book is invisble to the owner itself. 

### Steps to Reproduce

1. Create book
2. Open permission
3. Enable custom permissions and deselect everything
4. Save permissions

### Expected Behaviour

Only the owner (and the admin) is able to see the book.

### Exact BookStack Version

v22.06.1 

### Hosting Environment

https://demo.bookstackapp.com/

**Comment by ssddanbrown** [comment]
Thanks for the report @ChriFo. 
This is not something I'd consider a bug, more of a side-affect of the permission system taking place. There's no specific logic to give the owner more rights when custom permissions are into play.
Note: Users assigned to the original admin account should always have view access, if you need to undo the custom permissions.

A request to allow owner-visibility in such scenarios is already open in #2697 so I will therefore close this off.
