### ISSUE TITLE
Mysql fails to start

### ISSUE THREAD

**Issue by Robert4908** [BookStackApp/BookStack#3578]
### Describe the Bug

Followed the video for a install at DO on Ubuntu 22.04
No errors in install log
When trying to login, browser displays 
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache2.log shows
[Sat Jul 16 08:12:23.309633 2022] [php:error] [pid 15206] [client 179.43.155.171:37410] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70\nStack trace:\n#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()\n#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()\n#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()\n#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()\n#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1064): call_user_func()\n#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1100): Illuminate\\Database\\Connection->getPdo()\n#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\\Database\\Connection->getReadPdo()\n#8 /var/www/bookstack/vendor/laravel/framework/src/I/var/log/apache2/error.log

mysql shows

oot@bookstack:/# sudo systemctl status mysql
× mysql.service - MySQL Community Server
     Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
     Active: failed (Result: oom-kill) since Sat 2022-07-16 08:35:10 UTC; 33min ago
    Process: 1055 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
    Process: 1063 ExecStart=/usr/sbin/mysqld (code=killed, signal=KILL)
   Main PID: 1063 (code=killed, signal=KILL)
     Status: "Server startup in progress"
        CPU: 509ms

Jul 16 08:35:10 bookstack systemd[1]: Failed to start MySQL Community Server.
Jul 16 08:35:10 bookstack systemd[1]: mysql.service: Scheduled restart job, restart counter is at 8.
Jul 16 08:35:10 bookstack systemd[1]: Stopped MySQL Community Server.
Jul 16 08:35:10 bookstack systemd[1]: mysql.service: Start request repeated too quickly.
Jul 16 08:35:10 bookstack systemd[1]: mysql.service: Failed with result 'oom-kill'.
Jul 16 08:35:10 bookstack systemd[1]: Failed to start MySQL Community Server.

Any advice appreciated

### Steps to Reproduce

Reinstalled on private server, same problem

### Expected Behaviour

works

### Browser Details

Firefox Edge

### Exact BookStack Version

22.06.2

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04 
DO
512 MB RAM

**Comment by ssddanbrown** [comment]
Just ran a quick test install,
Does now look like, within increased Ubuntu and MySQL default memory usage, that is struggles with just 512MB of RAM with default options active, hence the system kills MySQL due to memory usage on startup.

A little swap space helps to handle memory spikes though and can help get things running.
Would advise adding swap space before running the install script.
There's a good digital ocean guide to this here:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-22-04#introduction

**Comment by Robert4908** [comment]
I added swap and on reboot same problem.  I then increased droplet memory to 1G but following error still shows in Apache log:

[Sat Jul 16 08:01:53.949388 2022] [mpm_prefork:notice] [pid 13482] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Sat Jul 16 08:01:53.949461 2022] [core:notice] [pid 13482] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jul 16 08:02:25.364261 2022] [mpm_prefork:notice] [pid 13482] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Jul 16 08:02:25.520613 2022] [mpm_prefork:notice] [pid 14514] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Sat Jul 16 08:02:25.520697 2022] [core:notice] [pid 14514] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jul 16 08:11:38.471450 2022] [mpm_prefork:notice] [pid 14514] AH00171: Graceful restart requested, doing restart
[Sat Jul 16 08:11:38.787795 2022] [mpm_prefork:notice] [pid 14514] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Sat Jul 16 08:11:38.787822 2022] [core:notice] [pid 14514] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jul 16 08:11:43.004356 2022] [mpm_prefork:notice] [pid 14514] AH00171: Graceful restart requested, doing restart
[Sat Jul 16 08:11:43.120544 2022] [mpm_prefork:notice] [pid 14514] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Sat Jul 16 08:11:43.120565 2022] [core:notice] [pid 14514] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jul 16 08:11:46.162663 2022] [mpm_prefork:notice] [pid 14514] AH00171: Graceful restart requested, doing restart
[Sat Jul 16 08:11:46.351413 2022] [mpm_prefork:notice] [pid 14514] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Sat Jul 16 08:11:46.354304 2022] [core:notice] [pid 14514] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jul 16 08:11:46.455273 2022] [mpm_prefork:notice] [pid 14514] AH00171: Graceful restart requested, doing restart
[Sat Jul 16 08:11:46.629051 2022] [mpm_prefork:notice] [pid 14514] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Sat Jul 16 08:11:46.629071 2022] [core:notice] [pid 14514] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jul 16 08:12:23.309633 2022] [php:error] [pid 15206] [client 179.43.155.171:37410] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70\nStack trace:\n#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()\n#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()\n#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()\n#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()\n#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1064): call_user_func()\n#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1100): Illuminate\\Database\\Connection->getPdo()\n#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\\Database\\Connection->getReadPdo()\n#8 /var/www/bookstack/vendor/laravel/framework/src/I/var/log/apache2/error.log

So memory now 1G, and:
root@bookstack:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           971Mi       523Mi        88Mi        17Mi       359Mi       284Mi
Swap:          511Mi       0.0Ki       511Mi

Any suggestions?  Thanks

**Comment by ssddanbrown** [comment]
Hi @Robert4908,
I'd suggest starting from a fresh machine, adding swap then running the install script.
The machine probably got to a messy state, with the required database setup never taking place originally, and the install script is not designed to be ran more than once.

**Comment by Robert4908** [comment]
All fixed
root@bookstack:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           467Mi       297Mi        20Mi        17Mi       149Mi       131Mi
Swap:          1.0Gi       265Mi       758Mi

Really appreciate your help

**Comment by ssddanbrown** [comment]
Awesome! Happy to help, Will therefore close this off.
