### ISSUE TITLE
Chapter links are not preseved

### ISSUE THREAD

**Issue by cod3monk** [BookStackApp/BookStack#3582]
### Describe the Bug

When a chapter is moved to another book, old links are not redirected but lead to a 404 page. This behavior is unlike page links, where previous slugs will redirect to the new location.  

### Steps to Reproduce

1. Create a chapter, save "old link"
2. Move chapter to different book
3. Try old link

### Expected Behaviour

Redirection to new chapter location.

### Exact BookStack Version

v22.04.2

### Hosting Environment

docker

**Comment by ssddanbrown** [comment]
Thanks for raising, but I'd consider the fundamental issue to already be covered & discussed across issues #732, #1969, #3520
