### ISSUE TITLE
No way to add images from iOS

### ISSUE THREAD

**Issue by 2600box** [BookStackApp/BookStack#3584]
### Describe the Bug

There is no way to add images from iOS.

The screen to add images is inaccessible. 

Additionally, images in native HEIC format are not accepted by Bookstack, so would need to be converted to JPG or PNG.

### Steps to Reproduce

On a test add, tap image icon. Face half an interface that is not optimised for mobile.

### Expected Behaviour

Should be able to upload and convert images to an acceptable format.

### Exact BookStack Version

BookStack v22.06.2

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Thanks for reporting, although I' going to close this off since an issue to address the image manager on mobile is already open in issue  #2535. Upon that HEIC support is tracked in #2505.
