### ISSUE TITLE
Changelog as mandatory information

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#3587]
### Describe the feature you'd like

Make the changelog mandatory so that you can only save changes if you have filled it out.

### Describe the benefits this would bring to existing BookStack users

It could be better and faster overview in the version history what has been changed.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @Tealk but I'm going to close this off as I feel the fundamental request is already covered by  #1051 (and somewhat #941)
