### ISSUE TITLE
Question callout

### ISSUE THREAD

**Issue by duckhaven** [BookStackApp/BookStack#3588]
### Describe the feature you'd like

A new callout type that indicates a question:

![image](https://user-images.githubusercontent.com/109732193/180195868-4edbe618-a0f2-4c81-8966-1171f797f4f8.png)

### Describe the benefits this would bring to existing BookStack users

Callouts are used as a strong visual indicator to help readers spot relevant information quickly. BookStack already has callouts that convey warnings of varying severity, and other important information. However, it is missing a callout type for key questions that the reader should keep in mind as they read further.

For example, this may take the form of a rhetorical question, to guide the reader to a particular conclusion. Or it may be an open question, to contextualize a topic being discussed in the text. In a document that is being written in stages, it can also act as a guide to the writer, to remind them to address the question as they continue to write the text.

Additionally, BookStack users who are migrating from OneNote, or have previous experience in using OneNote for documentation, may already have experience using its equivalent feature:

![image](https://user-images.githubusercontent.com/109732193/180199250-3f03ffc5-9ada-484e-9b25-69a92005e9a5.png)

### Can the goal of this request already be achieved via other means?

Existing callout types can be used for this, but this does not provide such immediate visual feedback that the callout text is a question.

Text can also be **marked as bold** to draw the reader's attention, but this is a generic method of emphasis, and not as strong a visual indicator as a callout.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by duckhaven** [comment]
If this feature is accepted, I would be happy to submit a pull request that implements it.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion but this is not something I'm sure of myself. As of now the callouts are all effectively alert/attention states. Questions are really a different category, and I don't think the callout styles really work for the use of questions. I would think that, if the question requires specific alerting to the user, then it would also fit into the category of an existing callout option.

**Comment by ssddanbrown** [comment]
As per my comment above, I don't really see this type of format fitting in so will go ahead and close this off.
