### ISSUE TITLE
How to delete page revisions & move multiple pages

### ISSUE THREAD

**Issue by cevinov** [BookStackApp/BookStack#3592]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,

I already search regarding my case, and i found this solution :
https://www.bookstackapp.com/docs/admin/commands/

But when i run command "php artisan" on bookstack container, it says couldn't open file artisan.
![image](https://user-images.githubusercontent.com/94840989/180653933-13b7b788-d2ba-4643-8a9c-af7f36af2ba5.png)

Could you give any clue, what path location to run that command. And is there a feature to move multiple pages or tag them?.

Thanks.

### Exact BookStack Version

Linuxserver.io version:- v22.02.3

### Hosting Environment

Oracle Cloud

**Comment by ssddanbrown** [comment]
Hi @cevinov,
With the linuxserver.io image, I think the BookStack install is located in `/var/www/html` so you should be able to run such commands if you `cd` into that directory.

> And is there a feature to move multiple pages or tag them?

There's no way to tag multiple pages at once. You can move multiple pages at once via the "Sort" option when viewing the parent book.

**Comment by cevinov** [comment]
Thanks, it solved now
