### ISSUE TITLE
Details page on the right side - removable

### ISSUE THREAD

**Issue by SwiftRedline** [BookStackApp/BookStack#3594]
### Describe the feature you'd like

Hello!

Is it possible to make the details page when u are on a page removable? 

### Describe the benefits this would bring to existing BookStack users

Better reading with more space

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @SwiftRedline,
This is not something I'd support as an interface option but the following should hide the "Details" section of a page, when added to the "Custom HTML Head Content" customization setting:

```html
<style>
#page-details {
    display: none;
}
</style>
```

This is not an officially supported customization, so could break upon future updates.
