### ISSUE TITLE
Discord Webhook Response - 400

### ISSUE THREAD

**Issue by mpadvisory** [BookStackApp/BookStack#3595]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Would like some help determining why my Discord webhook for Bookstack is 400'ing from the endpoint. As far as I know my Docker-Compose.yml of the Bookstack container is not experiencing any connection issues.

### Exact BookStack Version

BookStack v22.06.2

### Hosting Environment

Ubuntu 22.04 Jammy Jellyfish, installed with Docker version 20.10.17, build 100c701 and docker-compose version 1.29.2, build unknown.

**Comment by ssddanbrown** [comment]
Hi @mpadvisory, Are you posting to the slack compatible webhook endpoint?

**Comment by mpadvisory** [comment]
> Hi @mpadvisory, Are you posting to the slack compatible webhook endpoint?

I have copied the Discord API webhook endpoint, hopefully it is the correct one. For example, the last webhook attempted was: https://discord.com/api/webhooks/1001121069937201202/lfnXAd1JlIscyerDlV_NpiBgRZJm_fK-ItmApJRbogATDrBhqY_oqYhNIdJD3v82K4fY

**Comment by ssddanbrown** [comment]
@mpadvisory Try adding `/slack` to the end of that.

**Comment by mpadvisory** [comment]
> @mpadvisory Try adding `/slack` to the end of that.

That worked! Thank you ssddanbrown!
