### ISSUE TITLE
Possibility to hide an image from the gallery

### ISSUE THREAD

**Issue by Atn-D** [BookStackApp/BookStack#3596]
### Describe the feature you'd like

Add a boolean to the gallery, which if checked, will not display the image in the gallery.

### Describe the benefits this would bring to existing BookStack users

Bookstack allows you to make the visibility of certain spaces reserved for certain groups of people, but the images/media you upload are visible in the gallery as long as you can write in a place of the wiki.

### Can the goal of this request already be achieved via other means?

Yes by uploading to an external service, but it degrades the user experience

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @Atn-D,

I would not look to add such as option since it only suits a very specific scenario and it'll be prone to user-experience confusion (How do you then see the image to make it visible again etc...). 

I believe the visibility of images are somewhat bound by access to the page they were originally uploaded to.

**Comment by Atn-D** [comment]
@ssddanbrown I really like the idea of giving the same rights of visibility in the gallery as the rights of the page via which you upload.

But isn't it much more complicated to set up?

**Comment by ssddanbrown** [comment]
> But isn't it much more complicated to set up?

How do you mean? From an in-platform admin perspective or are you referring to technical code implementation?

**Comment by Atn-D** [comment]
@ssddanbrown i referring to technical code implementation.
But I may be wrong.

As long as there is a way to not make uploaded media visible to everyone for a private area, I'd be happy.

**Comment by ssddanbrown** [comment]
@Atn-D Okay, my comment from above:

> I believe the visibility of images are somewhat bound by access to the page they were originally uploaded to.

This is current functionality. I double checked this yesterday, seems to be the current behaviour. Access to the image files themselves is not strictly controlled by permissions, but the image gallery, in the current release, should only show images that have been uploaded to content you have access so.

**Comment by Atn-D** [comment]
@ssddanbrown Oh sorry, I'll do some more tests on my side.

**Comment by ssddanbrown** [comment]
Since the core requirement should be possible via existing functionality, as per the above, I'll go ahead and close this off.
If I am mistaken feel free to comment and this can be re-opened if needed.
