### ISSUE TITLE
Diagrams.net Insert diagram button still shows after button click

### ISSUE THREAD

**Issue by c0shea** [BookStackApp/BookStack#3597]
### Describe the Bug

Part of the editor toolbar shows on top of the diagrams.net window and you can't hide it after you go to insert or edit a diagram.

### Steps to Reproduce

1. Create a new page with the HTML editor
2. Click the ... button and click the Insert/edit drawing button
![image](https://user-images.githubusercontent.com/17714002/180846560-e7b8e336-a1a0-43f6-99f6-f4e531c913f4.png)
3. Once the editor launches, the menu that opened when you clicked the ... button remains shown on top of the editor and you can't hide it
![image](https://user-images.githubusercontent.com/17714002/180846722-d8760410-8ec3-40ff-b11a-9a4b93eba200.png)

### Expected Behaviour

The submenu should be hidden after the button is clicked and the diagram editor is launched

### Browser Details

Edge 103.0.1264.62 (64-bit) Windows 10

### Exact BookStack Version

v22.06.2

### PHP Version

8.1.7

### Hosting Environment

Windows Server 2012 R2 with PHP running under IIS

**Comment by ssddanbrown** [comment]
Thanks for raising @c0shea, Kept noticing this myself but would forget to raise as an issue or address when developing.
Have now addressed within fee3022ad8d073c8b169cb8f38b85baf8a3ebdfc. This will be part of the next feature release.
