### ISSUE TITLE
Document classification

### ISSUE THREAD

**Issue by tweak19** [BookStackApp/BookStack#3602]
### Describe the feature you'd like

I think it would be a really nice feature if you can implement a simply document classification in the sites of bookstack.
Or maybe in a whole book?

The Idea would be if you create a new Book or a New Sheet you select through a drop-down or something the classification and fillout the needet parts.

And if you export an book or site you had the classification in the footer oder header of the document.

### Describe the benefits this would bring to existing BookStack users

Benefit? More Use-Cases for Bookstack, specually if it would be used in scopes where classicfication is required

### Can the goal of this request already be achieved via other means?

No idea, but the request with the idea to use tags didn't handle that, because if you export documents that won't be visible.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request @tweak19, although I think this is fundamentally the same as issue  #3026.

As mentioned in #1940, I don't see the benefit of creating and maintaining another focused subsystem just for what is essentially a tag/label, especially as different environments would have different expectations upon some kind of classification system.

If you have some dev skills, you could use our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) to customize the export templates to add some indicator for your tag.

> Benefit? More Use-Cases for Bookstack, specually if it would be used in scopes where classicfication is required

With regards to benefits in feature requests, I generally don't see "more use-cases" as a viable justification as that could be applied to almost any feature addition, focus is instead on our existing audience.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up or progression here, I'll close this off.
