### ISSUE TITLE
OIDC Authorization after successful Authentication?

### ISSUE THREAD

**Issue by mschaefers** [BookStackApp/BookStack#3604]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I configured Bookstack to Authenticate via OIDC

Now I need to **Authorize** an authenticated user to limit access to users that match certain critera (role, group)
Is there any way to do that in Bookstack?

### Exact BookStack Version

v21.12

### Hosting Environment

HELM Chart installation on RedHat OKD4 (https://k8s-at-home.com/charts/ v.4.4.2)

**Comment by ssddanbrown** [comment]
Hi @mschaefers,
Within the registrations settings is a "Default Registration Role" option that can be used to apply a single role to new users accessing via OIDC.

There is no group/role sync for OIDC at this time, but I am seeking varied feedback in #3004 for future implementation. 
Upon that, our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) does provide methods of hooking into the registration/auth events to run custom logic where needed.

**Comment by ssddanbrown** [comment]
I will therefore close this off, with #3004 being targeted on a solution to achieve the requested functionality.
