### ISSUE TITLE
OIDC Authentication: Disable editing of users' key attribtues

### ISSUE THREAD

**Issue by mschaefers** [BookStackApp/BookStack#3606]
### Describe the feature you'd like

A user that authenticated via OIDC is still able to edit name and email address, although these values were initally provided by the authenticating server.

Editing these files should be disabled for OIDC provisioned users. Either automatically or configurable by the instance administrator

### Describe the benefits this would bring to existing BookStack users

a user email is considered a key attribute or a constant when this data is provided by an external provider.

User should not have the ability to tamper this data in bookstack.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Hi @mschaefers,

The email address is only editable by those with the `Manage Users` permission. 
In regards to the user's name, There has not been much previous demand for controlling this field so I'm not sure it'd be worth adding such a feature.
