### ISSUE TITLE
Files in dist-dir are missing

### ISSUE THREAD

**Issue by nielsk** [BookStackApp/BookStack#3607]
### Describe the Bug

I installed a couple of days ago and noticed today that there is no dist-dir and I see several 404s in the browser console for this. I just updated to 22.07 and it is still missing. I am on the release branch

### Steps to Reproduce

follow install instructions

### Expected Behaviour

dist-dir not missing

### Exact BookStack Version

22.07

### Hosting Environment

Debian 11, manual installation

**Comment by nielsk** [comment]
I am wrong - the public/dist-dir exists. I have to check why there are 404s

**Comment by nielsk** [comment]
The following files are missing:
- /dist/print-styles.css.map
- /dist/styles.css.map
- /dist/app.js.map
- /dist/code.js.map

**Comment by ssddanbrown** [comment]
Hi @nielsk,
This is known and fine, these files should only be requested when you have the dev tools open.

**Comment by ssddanbrown** [comment]
Will go ahead and close this off as I don't believe there's an issue here.

**Comment by nielsk** [comment]
Oh yes. Sorry and thanks for your reply.
