### ISSUE TITLE
Read Confirmation for Pages/Books

### ISSUE THREAD

**Issue by smartmaracl** [BookStackApp/BookStack#3609]
### Describe the feature you'd like

If this feature was already requested by someone else please close this request. But I couldn't find anything like this.

The ability for a person to tick a box or press a button at the bottom of page confirming they have read the page to the author or anyone with the ability of viewing the page. example in image below.

### Describe the benefits this would bring to existing BookStack users

Multiple companys using bookstack in germany could benefit of this feature. It is a necessary documentation for multiple ISO-certificates and for some national certifications.

### Can the goal of this request already be achieved via other means?

No. As far as I can tell there is no way to display that you have read a page other than adding yourself in a list in the article itself, which requires the permissions to edit.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

### Additional context

![grafik](https://user-images.githubusercontent.com/14792735/181732199-72295074-6e6d-4e2c-a079-7aa3ad8db7b0.png)

**Comment by ssddanbrown** [comment]
Thank you for the request. Issue #2835 has a similar request, My thoughts really remain the same, in that this is quite a specific requirement that is really meant to serve business process rather and being useful in the context of BookStack itself.

This is something that could be achieved to some degree using page comments, or by tracking via many other options (Internal form/spreadsheet/etc...).

**Comment by smartmaracl** [comment]
Thank you for your very fast response! In general I can understand that this is a business case and not on your current Roadmap.
However in relation to issue 2834 I find that comments are not a really good alternative for such a feature. As far as I could analyze the behaviour with the BookStack Demo you can delete comments and there is no Log or anything (like the Pagerevision) where you can see who commented and what , or did I miss something there ?

**Comment by ssddanbrown** [comment]
> As far as I could analyze the behaviour with the BookStack Demo you can delete comments and there is no Log or anything (like the Pagerevision) where you can see who commented and what , or did I miss something there ?

No, there is no specific log for comments, although their action of commenting on something will be written to the audit log and that would remain after the comment is deleted. 

If it's really important, and you have a little PHP hacking skill, you could use our [logical theme system](https://github.com/BookStackApp/BookStack/blob/master/dev/docs/logical-theme-system.md) to hook into comment events and log them to a file. 
Alternatively, you could use webhooks on comment events to integrate that data into an external system.

**Comment by BloodyIron** [comment]
@ssddanbrown would it be possible to have webhooks serve this function? In that, it says "this user" read "this page" (after they read the whole thing or something?), as in... not on comment events, but read page events?

This may be already achievable... ish...

**Comment by Mailstorm-ctrl** [comment]
> @ssddanbrown would it be possible to have webhooks serve this function? In that, it says "this user" read "this page" (after they read the whole thing or something?), as in... not on comment events, but read page events?
> 
> This may be already achievable... ish...

Yes...but not in bookstack. Bookstack is not meant to be a compliance tool (what this request is requesting). If you wanted to track if someone read a page you could do the following:

1. Create a webhook for when a user registers (auth_register)
2. Have a separate program read webhook data and send it to your actual compliance software. This can be done via middleware.

**Comment by ssddanbrown** [comment]
> would it be possible to have webhooks serve this function? In that, it says "this user" read "this page" (after they read the whole thing or something?), as in... not on comment events, but read page events?

The scope of where I want to track audit/webhook events is fixed to change actions, I don't want to introduce passive actions (read events) to these systems.

Since this is a feature really intended to serve business process, rather than the benefit of BookStack itself, I'm going to close this off as out of scope.
