### ISSUE TITLE
Rename email field when viewing users.

### ISSUE THREAD

**Issue by DaneEveritt** [BookStackApp/BookStack#361]
### For Feature Requests

Desired Feature: Theres an annoying auto-fill "bug" in Safari (and likely other browsers), where the email address for users gets set to whatever email you use normally in the browser, and if you don't notice, it tries to set the user's email to your auto-filled one.

Would be nice if the field could be renamed to something like `current_email`, or somehow disable auto-fill on that field.

**Comment by Shackelford-Arden** [comment]
Sounds more like an extension is doing this? In  Firefox, Google Chrome and Microsoft Edge I don't see this? I know for me LastPass will sometimes do things like this. @DaneEveritt

**Comment by alexmannuk** [comment]
Doesn't appear to happen in Chrome, Firefox, or IE in v0.29.3. Can likely be closed, given the age of the issue.

**Comment by ssddanbrown** [comment]
Thanks for testing  confirming @alexmannuk and @Shackelford-Arden.

Since this has not been reported since this issue was created 3 years ago I'll close this off. If it remains problematic and re-producible feel free to open a new issue, referencing this one.
