### ISSUE TITLE
can't display image on the page

### ISSUE THREAD

**Issue by Zhengyueewee2e** [BookStackApp/BookStack#3612]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I   upload image successful,But the image can't diskplay on the web page
![image](https://user-images.githubusercontent.com/40627010/182062347-5eaa6c97-6e10-467d-9c6a-ddb8cdbabfcb.png)

### Exact BookStack Version

v22.07

### PHP Version

7.4.30

### Hosting Environment

CentOS Linux release 7.9.2009 (Core)

**Comment by ssddanbrown** [comment]
Hi @Zhengyueewee2e,
To help I'd need a bit more information regarding your setup & environment.

- Were you following a guide? If so, are you able to share a link to it?
- What webserver set-up did you perform? Can you share the configuration (Feel free to redact private details)?

**Comment by Zhengyueewee2e** [comment]
> Hi @Zhengyueewee2e, To help I'd need a bit more information regarding your setup & environment.
> 
> * Were you following a guide? If so, are you able to share a link to it?
> * What webserver set-up did you perform? Can you share the configuration (Feel free to redact private details)?

Hi @ssddanbrown 
I follow https://blog.csdn.net/weixin_44799797/article/details/122563323 to install bookstack
I use nginx/1.20.1 as my webserver 
I have solved half problem 
![image](https://user-images.githubusercontent.com/40627010/182745065-19b89aac-f7b8-4828-8f41-46d731fe1d61.png)
The problem is caused by 404 can't found my image ,my profile .env wirte "APP_URL=http://" before，then image‘s url is http://IP/http://upload/image...",so my image cam't be found .
I change the "APP_URL=http://"to "APP_URL=" then the admin.image can be found.

But the logo.image is still 
![image](https://user-images.githubusercontent.com/40627010/182745742-edec036c-a3d5-449d-8502-bf88d6d82c62.png)
I  can't found what profile could I change

**Comment by Zhengyueewee2e** [comment]
Hi @ssddanbrown 
I solved all the problem
![image](https://user-images.githubusercontent.com/40627010/182746358-30881949-9426-475c-9d39-30379613160e.png)
I change this setting then the image display
![image](https://user-images.githubusercontent.com/40627010/182746386-3f4599c2-8597-4e04-b717-bd72cc4c3b22.png)

**Comment by ssddanbrown** [comment]
Alright, will therefore close this off.
