### ISSUE TITLE
Cannot select activity type input in Audit Log

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3623]
### Describe the Bug

![image](https://user-images.githubusercontent.com/4026090/183350115-1e4f28e1-d197-47cb-ad4a-95424aef30c3.png)
in the audit log, it is not possible to filter by events, because when clicked, it resets to "No filter"

### Steps to Reproduce

Go to audit log
change event filter

### Expected Behaviour

-

### Browser Details

Chrome (latest)

### Exact BookStack Version

v22.07

### PHP Version

8.3

### Hosting Environment

Windows Server 2019

**Comment by ssddanbrown** [comment]
Thanks for reporting @Statium, This has been addressed in a90446796a113c0e9da916f0e2ea4fb61e7b6a46 and will be part of the next patch release.
