### ISSUE TITLE
Footer and Header on PDF

### ISSUE THREAD

**Issue by FalcoDomenico** [BookStackApp/BookStack#3629]
### Describe the feature you'd like

Is possibile to insert, in the export Pdf function, a footer and an header? I need to insert some images like company logo or other type of item.

Thank you

### Describe the benefits this would bring to existing BookStack users

In this way, manuals are more captivating.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @FalcoDomenico, but this is already open in #493 so I'm going to therefore close this off as a duplicate.
