### ISSUE TITLE
advanced editor Tinymce 

### ISSUE THREAD

**Issue by dnazerox** [BookStackApp/BookStack#3634]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

hi, how can the advanced menus be enabled in the Tinymce editor?
es. file - edit - view  - insert  - format  - tools  - tables

tnks

### Exact BookStack Version

v22

### PHP Version

7.2

### Hosting Environment

debian

**Comment by ssddanbrown** [comment]
Hi @dnazerox,

We [expose some events](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events) that can be used to edit the TinyMCE config. My [comment here](https://github.com/BookStackApp/BookStack/issues/1203#issuecomment-621342313) shows an example of using this to alter the toolbar of TinyMCE.

Note: Altering of tinymce is not supported and customizations may break upon future updates.

**Comment by dnazerox** [comment]
thank you very much, I'll give it a look


Il giorno mer 10 ago 2022 alle ore 14:12 Dan Brown ***@***.***>
ha scritto:

**Comment by ssddanbrown** [comment]
Happy to help, will therefore close this off.
