### ISSUE TITLE
Failed to modify guest Preferred  Language

### ISSUE THREAD

**Issue by maojunxyz** [BookStackApp/BookStack#3645]
### Describe the Bug

I modified the English to Chinese.It doesn't work。
 
I logged out of my account and it still shows English. When I logged in again, the guest language settings page was automatically reset to English. 

### Steps to Reproduce

1. Login Admin
2. Go to Users Setting
3. modify Guest Preferred Language to Chinese
4. Log out Admin
5. guest access, the display is in English
6. Login Admin Again
7. Go to Users Setting
8.  Guest Preferred Language displayed in English

### Expected Behaviour

modify guest Preferred  Language Should work

### Browser Details

Chrome 103.0.5060.134

### Exact BookStack Version

v22.07.3

### Hosting Environment

ubuntu 20.04

**Comment by ssddanbrown** [comment]
Hi @maojunxyz,
Technically, the anonymous user is not logged in as this account, it's just used for permission control, so their language option won't be applied for external/public use.

Please see this page in our docs for setting the default language:
https://www.bookstackapp.com/docs/admin/language-config/#setting-the-default-language
