### ISSUE TITLE
Add romanian translation

### ISSUE THREAD

**Issue by om226** [BookStackApp/BookStack#3646]
### Language to Add

Romanian (RO)

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Hi @om226,
Thanks for offering to translate BookStack into Romanian. I have now enabled this language option in Crowdin:
https://crowdin.com/project/bookstack/ro

Note, I may remove this option again if progress is minimal after some time.
