### ISSUE TITLE
Add font size plugin

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3647]
### Describe the feature you'd like

Add font size plugin to change default font on pages.
https://www.tiny.cloud/blog/custom-font-sizes-in-tinymce/

### Describe the benefits this would bring to existing BookStack users

Convenience

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by Statium** [comment]
or please tell me in which file the editor is initialized to add the plugin

**Comment by ssddanbrown** [comment]
Hi @Statium,
Font size control has already been requested in #1148 so I'll therefore close this off as a duplicate.
We expose editor events which can provide the TinyMCE config for tweaking:
https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events

You can see an example of this in my comment here:
https://github.com/BookStackApp/BookStack/issues/1203#issuecomment-621342313

Note: Edits to the TinyMCE config are not supported and may break on future updates.
