### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3648]
### Describe the feature you'd like

Pretty simple...support for HTTPs would be nice. If you force the page to load over https (after adding virtualhost 443) the pages are broken because the links in the page reference http...causing them not to load.

![image](https://user-images.githubusercontent.com/53045430/184521556-a52fe757-f435-49f3-a73d-05ffc2c421b2.png)

### Describe the benefits this would bring to existing BookStack users

It's HTTPs...it's pretty standard and businesses would benefit greatly.

### Can the goal of this request already be achieved via other means?

Not that I know of :(

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @Mailstorm-ctrl,

You just likely need to update the `APP_URL` option in your `.env` file (Commonly at `/var/www/bookstack/.env` if installed using the Ubuntu install script). 
I've have a video guide on adding HTTP if it helps:
https://youtu.be/wq78komr9rs?t=649

**Comment by Mailstorm-ctrl** [comment]
> Hi @Mailstorm-ctrl,
> 
> You just likely need to update the `APP_URL` option in your `.env` file (Commonly at `/var/www/bookstack/.env` if installed using the Ubuntu install script). I've have a video guide on adding HTTP if it helps: https://youtu.be/wq78komr9rs?t=649

Ah...didn't realize that. Thanks!

**Comment by ssddanbrown** [comment]
Will therefore close this off.
