### ISSUE TITLE
Month missing when exporting instructions

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3650]
### Describe the Bug

When exporting a statement, the month was not specified in the creation date
![image](https://user-images.githubusercontent.com/4026090/184575072-83d968db-e42e-4167-8485-2b74383df797.png)

### Steps to Reproduce

1. Export PDF

### Expected Behaviour

-

### Exact BookStack Version

v22.07.02

### PHP Version

8.3

### Hosting Environment

WinServer

**Comment by Statium** [comment]
The problem is in the encoding (at least when choosing the Russian language by default). When exporting html, the month is replaced by question marks.

**Comment by ssddanbrown** [comment]
Very much related to #3590, Possibly due to missing locale data. I'm not sure how locales work in Windows environments.

@Statium Can you provide any additional detail regarding your environment, and actual PHP version? Since PHP8.3 is not a thing that exists right now.

**Comment by Statium** [comment]
PHP 8.1.5
Windows Server 2019

**Comment by Statium** [comment]
@ssddanbrown In Russian, the problem is not solved.
I am attaching a screenshot.
![image](https://user-images.githubusercontent.com/4026090/189293895-b3c1860c-77ef-410c-9d10-ff1472cf10a9.png)

**Comment by Statium** [comment]
![image](https://user-images.githubusercontent.com/4026090/190900355-1e693864-88b4-42af-b262-0760ae0783e8.png)
I corrected line 52 in the LanguageManager.php file and it solved the problem (added UTF-8)
![image](https://user-images.githubusercontent.com/4026090/190900458-1010ea1b-fa20-4c74-b1c4-ee4a5570b85e.png)

**Comment by ssddanbrown** [comment]
Thanks for confirming what works @Statium.
I've made changes in 050d69ea276da40ec23c32d8f0da6f7d958b1427 to include the specific format you displayed in your last message. These will be part of v22.09.1.

**Comment by Statium** [comment]
@ssddanbrown The problem recurred in 22.10.1
