### ISSUE TITLE
404 on settings page

### ISSUE THREAD

**Issue by Stephan9283** [BookStackApp/BookStack#3655]
### Describe the Bug

Hello,
actually I have version v22.02.3 installed and want to upgrade to the new version. Everything is fine but the settings page comes with the 404 error message. In the url I see that it want to open /settings/features and in the old version it will only open /settings
thanks and regards
Stephan

### Steps to Reproduce

1. Logged in as admin
2. click on settings

### Expected Behaviour

I wanted to see the settings page. 

### Screenshots or Additional Context

![Bookstack nach Update](https://user-images.githubusercontent.com/111346010/184835926-bbc0a588-41d7-4293-8d79-a922401d1094.PNG)

### Browser Details

Firefox 102.1.0esr (64-Bit)

### Exact BookStack Version

v22.02.3

### PHP Version

7.4.28

### Hosting Environment

Debian GNU/Linux 11 (bullseye)

**Comment by ssddanbrown** [comment]
Hi @Stephan9283,
I'm confused about your scenario, are you attempting to upgrade here?
The `/settings/features` URL is only part of BookStack v22.03 or greater, you should not have that URL, or expect that to work, on an earlier version.

**Comment by Stephan9283** [comment]
> 

Hello @ssddanbrown ,
thanks for your help. I'm currently on version 22.02.3 and want to update the latest 22.07.3 following the update instructions on github. But after the update the settings/features is not available and I get the 404 error.

**Comment by ssddanbrown** [comment]
@Stephan9283 Okay, do you get any errors when running any of the three main update commands?

**Comment by Stephan9283** [comment]
> 

No errors. The other setting pages like maintenance, audit or users work fine.

**Comment by ssddanbrown** [comment]
@Stephan9283 Within your bookstack directory can you provide the output of running the following command?:

```
git status
```

**Comment by Stephan9283** [comment]
> @Stephan9283 Within your bookstack directory can you provide the output of running the following command?:
> 
> ```
> git status
> ```

Auf Branch release
Ihr Branch ist auf demselben Stand wie 'origin/release'.

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add/rm <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git restore <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)
        gelöscht:       .env.example
        geändert:       resources/views/settings/audit.blade.php
        geändert:       resources/views/settings/customization.blade.php
        geändert:       resources/views/settings/features.blade.php
        geändert:       resources/views/settings/layout.blade.php
        geändert:       resources/views/settings/maintenance.blade.php
        geändert:       resources/views/settings/registration.blade.php
        geändert:       storage/clockwork/.gitignore

Unversionierte Dateien:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
        composer.phar

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")

**Comment by ssddanbrown** [comment]
@Stephan9283 Okay, there appear to be some changed files there which could conflict on update.

- Have you intentionally made any changes to core BookStack files?
- Can you provide the full output shown when running the `git pull origin release` update step?

**Comment by Stephan9283** [comment]
[git_pull_origin_release.txt](https://github.com/BookStackApp/BookStack/files/9350430/git_pull_origin_release.txt)

No I didn't change any core files.

**Comment by ssddanbrown** [comment]
@Stephan9283 Thanks for confirming.

The output provided makes it seem like that `git pull origin release` had not yet been ran, did you definitely run this command when attempting update before?

What occurs now if you proceed with the next two update steps?

```bash
composer install --no-dev
php artisan migrate
```

**Comment by Stephan9283** [comment]
that was before with the old version. Now the result ist the following:
Von https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
Bereits aktuell.

**Comment by ssddanbrown** [comment]
@Stephan9283 Okay, can you now run the above two update steps and provide output of those?

**Comment by Stephan9283** [comment]
> @Stephan9283 Okay, can you now run the above two update steps and provide output of those?

**composer install --no-dev**
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]?
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-snappy
Discovered Package: intervention/image
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: socialiteproviders/manager
Package manifest generated successfully.
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan cache:clear
Application cache cleared!
> @php artisan view:clear
Compiled views cleared!

**php artisan migrate**
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.

**Comment by ssddanbrown** [comment]
@Stephan9283 After those commands, does it still fail to load the settings page?

**Comment by Stephan9283** [comment]
Unfortunately yes

**Comment by ssddanbrown** [comment]
@Stephan9283 Alright, can you re-confirm the output of running: `git status` in the current state of the application.

**Comment by Stephan9283** [comment]
still the same output:
Auf Branch release
Ihr Branch ist auf demselben Stand wie 'origin/release'.

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add/rm <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git restore <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)
        gelöscht:       .env.example
        geändert:       resources/views/settings/audit.blade.php
        geändert:       resources/views/settings/customization.blade.php
        geändert:       resources/views/settings/features.blade.php
        geändert:       resources/views/settings/layout.blade.php
        geändert:       resources/views/settings/maintenance.blade.php
        geändert:       resources/views/settings/registration.blade.php
        geändert:       storage/clockwork/.gitignore

Unversionierte Dateien:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
        composer.phar

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")


But the files are in the correct folder (resources/views/settings/
), I think:
-rwxr-xr-x 1 www-data www-data 5380 16. Aug 12:30 audit.blade.php
-rwxr-xr-x 1 www-data www-data 7789 16. Aug 12:30 customization.blade.php
-rwxr-xr-x 1 www-data www-data 2732 16. Aug 12:30 features.blade.php
-rwxr-xr-x 1 www-data www-data 1532 16. Aug 12:30 layout.blade.php
-rwxr-xr-x 1 www-data www-data 3544 16. Aug 12:30 maintenance.blade.php
drwxr-xr-x 2 www-data www-data 4096 16. Aug 12:30 parts
drwxr-xr-x 3 www-data www-data 4096 16. Aug 12:30 recycle-bin
-rwxr-xr-x 1 www-data www-data 3634 16. Aug 12:30 registration.blade.php
drwxr-xr-x 3 www-data www-data 4096 16. Aug 12:30 roles
drwxr-xr-x 3 www-data www-data 4096 16. Aug 12:30 webhooks

**Comment by ssddanbrown** [comment]
@Stephan9283 Please can you provide the output of running the following:

```bash
git diff resources/views/settings/features.blade.php
```

**Comment by Stephan9283** [comment]
diff --git a/resources/views/settings/features.blade.php b/resources/views/settings/features.blade.php
old mode 100644
new mode 100755

**Comment by ssddanbrown** [comment]
@Stephan9283 Alright, Please run the following to ignore permission changes:

```
git config core.fileMode false
```

It's a bit suspicious that only this directory have had permission changes, and that this is the view that fails to load.
Could you confirm the full output of running:

```
ls -alh resources/views/settings
```

**Comment by Stephan9283** [comment]
I run the git command and had no output.

Here ist ls output:
insgesamt 56K
drwxr-xr-x  6 www-data www-data 4,0K 16. Aug 12:30 .
drwxr-xr-x 25 www-data www-data 4,0K 16. Aug 12:30 ..
-rwxr-xr-x  1 www-data www-data 5,3K 16. Aug 12:30 audit.blade.php
-rwxr-xr-x  1 www-data www-data 7,7K 16. Aug 12:30 customization.blade.php
-rwxr-xr-x  1 www-data www-data 2,7K 16. Aug 12:30 features.blade.php
-rwxr-xr-x  1 www-data www-data 1,5K 16. Aug 12:30 layout.blade.php
-rwxr-xr-x  1 www-data www-data 3,5K 16. Aug 12:30 maintenance.blade.php
drwxr-xr-x  2 www-data www-data 4,0K 16. Aug 12:30 parts
drwxr-xr-x  3 www-data www-data 4,0K 16. Aug 12:30 recycle-bin
-rwxr-xr-x  1 www-data www-data 3,6K 16. Aug 12:30 registration.blade.php
drwxr-xr-x  3 www-data www-data 4,0K 16. Aug 12:30 roles
drwxr-xr-x  3 www-data www-data 4,0K 16. Aug 12:30 webhooks

**Comment by ssddanbrown** [comment]
Nothing unexpected there.
If you navigate directly to the `/settings/audit` endpoint, does that load okay?

**Comment by Stephan9283** [comment]
yes. I see the audit protocol

**Comment by ssddanbrown** [comment]
Okay, what about the `/settings/registration` endpoint? Does that load okay?

**Comment by Stephan9283** [comment]
that also fails with a 404

**Comment by ssddanbrown** [comment]
@Stephan9283 Okay,

- Can you provide the output of running `ls -alh bootstrap/cache`
- Have you ran any other commands starting with `php artisan`, other than the migrate command?

**Comment by Stephan9283** [comment]
yes I ran the clear caches commands as well
php artisan cache:clear
php artisan config:clear
php artisan view:clear


ouput of ls -alh bootstrap/cache
insgesamt 348K
drwxr-xr-x 2 www-data www-data 4,0K 17. Aug 08:59 .
drwxr-xr-x 3 www-data www-data 4,0K 31. Jan 2022  ..
-rwxr-xr-x 1 www-data www-data   14 31. Jan 2022  .gitignore
-rwxr-xr-x 1 root     root     1,6K 17. Aug 08:59 packages.php
-rw-r--r-- 1 root     root     311K 31. Jan 2022  routes-v7.php
-rwxr-xr-x 1 root     root      17K 17. Aug 08:59 services.php

**Comment by ssddanbrown** [comment]
@Stephan9283 Alright, looks like some optimizations/cache commands had been ran earlier this year to cache the routes which could cause this issue.

Please ensure any files within the `bootstrap/cache` path, that have a `.php` extension, are deleted.

**Comment by Stephan9283** [comment]
> @Stephan9283 Alright, looks like some optimizations/cache commands had been ran earlier this year to cache the routes which could cause this issue.
> 
> Please ensure any files within the `bootstrap/cache` path, that have a `.php` extension, are deleted.

Great! That solved my problem. Many thanks
