### ISSUE TITLE
Deaktivate Bright/Dark Mode Switch

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#3658]
### Describe the feature you'd like

Is it possible to disable the switch for the bright/dark mode?

![image](https://user-images.githubusercontent.com/6242840/185372704-69743a8f-a667-4d34-b001-5d2368e1a055.png)

### Describe the benefits this would bring to existing BookStack users

We not use the DarkMode from BookStack

Because it wasn't optimally designed

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Hi @reddexx,
This would not be an option I'd look to build in, but you could hide the toggle buttons using our [methods of customization](https://www.bookstackapp.com/docs/admin/hacking-bookstack/).
Below is a quick "Custom HTML Head Content" hack that would do this, quickly tested on the latest release.

```html
<style type="text/css">
	form[action$="toggle-dark-mode"] {
		display: none;
	}
	header .dropdown-menu li:nth-child(5),
	header .dropdown-menu li:nth-child(6) {
		display: none;
	}
</style>
```

May not be applicable for future updates.
