### ISSUE TITLE
Reusing Page Content - inlcude the content within the element

### ISSUE THREAD

**Issue by hctrr** [BookStackApp/BookStack#3661]
### Describe the Bug

Including all the content from a page with {{@5}} works.

The current bug is when attempting to include the content within the element of the ID.
when entering the syntax: {{@202#bkmrk-copy-this-section}}
the end result will be text that simply reads "copy this section"

### Steps to Reproduce

Generate the Tag:
![image](https://user-images.githubusercontent.com/15852711/185484662-4f427f08-cc01-4bd4-a212-b8e9c633bd02.png)

Update page with the tag syntax:
![image](https://user-images.githubusercontent.com/15852711/185484773-eb68664c-0738-4fc5-9d9f-78592845acae.png)

Results:
![image](https://user-images.githubusercontent.com/15852711/185484820-8ede6a69-1de0-49a9-aeba-1a376f052e6b.png)

### Expected Behaviour

The full section (header and body) of the within {{@202#bkmrk-copy-this-section}} to be mirrored on the new page.

as mentioned - Including all the content from a page with {{@202}} works. its just when attempt to use sections.

### Browser Details

Firefox 103.0.2

### Exact BookStack Version

v22.07.3; v22.06.2

### Hosting Environment

https://github.com/linuxserver/docker-bookstack

**Comment by ssddanbrown** [comment]
Hi @hctrr,

What you've described in the reproduction steps is what I'd expect.
The header and body text are two seperate sections, the content includes system only works on a single-section or whole-page basis, it does not support ranges. A request for ranges is already open in  #3267.

**Comment by hctrr** [comment]
understood. I'll leverage the syntax for the block of text.
thank you for your response.
