### ISSUE TITLE
How to create a new function in page-edit toolbar ?

### ISSUE THREAD

**Issue by E60502** [BookStackApp/BookStack#3665]
### Describe the feature you'd like

I want to add an editor like SVG-edit to the toolbar in page-edit.

### Describe the benefits this would bring to existing BookStack users

You can use the editor you used before using bookstack, such as Gantt chart, self-made editor, it will be more convenient.

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

![toolbar](https://user-images.githubusercontent.com/111739746/185890000-1e96322c-4026-4c64-9f92-269d54d73431.png)

**Comment by ssddanbrown** [comment]
Hi @E60502,

The underlying editor, and its toolbar, can be modified using some [custom events](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events) we emit.

See [my comment here](https://github.com/BookStackApp/BookStack/issues/705#issuecomment-1203691993) for an example which modifies the toolbar with an extra button.

Note, these options of extension are not fully stable and may break upon updates.
In  addition, SVG usage (and more advance content formats in general) may affect other parts of the system and cause issues (PDF exporting for example).

**Comment by E60502** [comment]
@ssddanbrown let me try, thanks.

**Comment by ssddanbrown** [comment]
Will therefore close this off.

**Comment by E60502** [comment]
Are BookStack Editor Events custom in Custom HTML Head Content? I just start to learn this.

**Comment by ssddanbrown** [comment]
@E60502 They can be used with any method to add custom JavaScript, but yes, the "Custom HTML Head Content" setting is the main way to add code for these events.

**Comment by E60502** [comment]
@ssddanbrown Thank you for your reply.
Then if I want to import the application I want to use in the button I added, where should I put the code folder of the application I want to import?
And this code `window.addEventListener('*', event => console.log('*', event.detail));`
What do I import in ' * ' ?

**Comment by ssddanbrown** [comment]
> where should I put the code folder of the application I want to import?

There's no ideal place within BookStack right now to add additional assets. You'd have to use a CDN link for your library, or host in yourself in some public web space, or embed the code directly into BookStacks extension options.

> What do I import in ' * ' 

If editing the tinymce config you'd typically want to use `window.addEventListener('editor-tinymce::pre-init', eventHandler);`.
If you wanted a much simpler example of editing TinyMCE config, you [could see my comment here](https://github.com/BookStackApp/BookStack/issues/1203#issuecomment-621342313).

**Comment by E60502** [comment]
I have already put the bookstack and the application's code folder on the same server, so can I extend it directly in the themes folder?

**Comment by E60502** [comment]
Thank you for answering me patiently, I will reorganize the functions I want to add, I have a project system that needs to be logged in, this system's code and Bookstack's code are placed on the same server, I want to create a button in the editing toolbar and when I clicking it, the system does not need to log in again.

My current idea is to remove the login page of the project system and click the button to enter the window for selecting a project.

Q1. I think this will involve the connection of the database. They are all in MSSQL. I would like to ask if Bookstack can connect to another database? I have seen the connection to the database in .env.

Q2. I have read the article about adding a PDF button, and I can already add a button. I want to change the window for inputting PDF to input project name. After inputting, I can connect to the database to capture the project I want to open. If Q1 can be achieved, this should also be edited in Custom HTML head content?

Sorry to keep bothering you.

**Comment by ssddanbrown** [comment]
> I think this will involve the connection of the database. They are all in MSSQL. I would like to ask if Bookstack can connect to another database? I have seen the connection to the database in .env.

It is possible via custom hacking of the BookStack PHP code (Perhaps via the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md)) , and the base framework in use (Laravel) does have some support for MSSQL, but this kind of thing is not supported in any way.

> After inputting, I can connect to the database to capture the project I want to open. If Q1 can be achieved, this should also be edited in Custom HTML head content?

Q1 could not be done in custom HTML head content alone. You'd need to write some custom logic to handling a lookup to a custom endpoint to run your query of the other database. Getting a bit advanced at this stage so you'd need to be fairly confident with this. Ideally you'd want some level of full-stack web experience since this would involve writing and combining custom front-end and back-end code.

**Comment by E60502** [comment]
Can I embed the link of the project system in the Custom HTML head content?

**Comment by ssddanbrown** [comment]
@E60502 Maybe, but I'm not really sure what you mean by that to be honest.

**Comment by E60502** [comment]
Like attaching a link to the project system in a custom button.

**Comment by ssddanbrown** [comment]
Do you mean inserting a link into the content of the page?
Or do you mean attaching a link-based attachment? (Which would show in the sidebar of the BookStack page when viewed.)

**Comment by E60502** [comment]
On the button.

**Comment by E60502** [comment]
For jQueryGantt, can it be implemented with TinyMCE?

**Comment by ssddanbrown** [comment]
> For jQueryGantt, can it be implemented with TinyMCE?

Probably possible in some way, but It would take a fair amount of work, and expertise of the JavaScript code at play, to integrate to be honest.

**Comment by E60502** [comment]
In order to complete this what skill is must require ? And is this possible for a beginner?

**Comment by ssddanbrown** [comment]
> In order to complete this what skill is must require ?

Primarily a fair amount of JavaScript skill and experience. Some PHP/Laravel experience may help to understand usage with back-end functions, since the addition may cause further problems that need to be addressed.
Ideally some experience with TinyMCE, although this could be learnt by someone with enough JavaScript skill.

> And is this possible for a beginner?

Not really beginner level stuff to be honest.

**Comment by E60502** [comment]
Thank you for your reply, if there is any problem, I will contact you again.
