### ISSUE TITLE
Recycle Bin Life

### ISSUE THREAD

**Issue by deadlypantsd** [BookStackApp/BookStack#3667]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Is there a way to configure the life of items in the Recycle Bin?

"On each item you can choose to restore or permanently delete it as required. By default, Items deleted over 30 days ago may be automatically permanently deleted from the recycle bin."

### Exact BookStack Version

22.07.3

### Hosting Environment

Ubuntu Server 20.04 stripped
NGINX
PHP 7.4 w/ required supporting addins

**Comment by 10935336** [comment]
Can be set in `.env`

https://github.com/BookStackApp/BookStack/blob/837fd74bf691129467361ce8066ba31f64408647/.env.example.complete#L300-L306

**Comment by nasmi3** [comment]
I added a section describing the options on the page Admin Documentation > Other Configuration > .env Options and submitted a PR

**Comment by ssddanbrown** [comment]
Thanks @nasmi3!

This has now been added to the docs, as per PR https://github.com/BookStackApp/BookStack/issues/3667, so I will close this off.
These additions can be seen here:
https://www.bookstackapp.com/docs/admin/other-config/#recycle-bin-lifetime
