### ISSUE TITLE
Add code language 1C

### ISSUE THREAD

**Issue by byPavel** [BookStackApp/BookStack#3668]
### Describe the feature you'd like

Добрый день. Хотелось бы добавить еще один язык программирования в редактор кода.

### Describe the benefits this would bring to existing BookStack users

Expand opportunities. A more beautiful interface

### Can the goal of this request already be achieved via other means?

I was looking for how to manually add a new language and style, but to no avail.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

![1с](https://user-images.githubusercontent.com/69891182/185993223-f0737bcb-e251-4f8c-99ed-4b052d15db20.png)

**Comment by ssddanbrown** [comment]
Hi @byPavel,

I only really add languages that have official support from CodeMirror themselves, the underlying library we use.
There's already an open issue (#2057) to provide support for custom additions to the language set.
Otherwise, I will close this off for the above reasons.
