### ISSUE TITLE
File not found. Docker with Portainer

### ISSUE THREAD

**Issue by michaelortnersanube** [BookStackApp/BookStack#3670]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

If i want to visit the wiki page, there is coming a error named "File not found" i don't know why he says this, and don't found any erros. Maybe someone can help

### Exact BookStack Version

v22.07.3

### Hosting Environment

Ubuntu 20.04 - VPS, Docker Container from linuxserver

**Comment by ssddanbrown** [comment]
Where are you seeing this error? Can you provide a full view (or screenshot) of this error you see?

**Comment by michaelortnersanube** [comment]
If i visit directly the site, as a example wiki.example.com

There is the screenshot: 
![image](https://user-images.githubusercontent.com/96595501/186126853-452e7a3b-62e3-4420-9aaf-8a84ccb92fe7.png)

**Comment by michaelortnersanube** [comment]
Here is a error from following location: bookstack/log/nginx/error.log

2022/08/23 09:43:49 [error] 214#214: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.2, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wiki.example.at"

**Comment by michaelortnersanube** [comment]
I found on storage/logs/laravel.log something new:

![image](https://user-images.githubusercontent.com/96595501/186128099-ac9fa9ec-3dce-4632-8695-b4f32d480191.png)

**Comment by ssddanbrown** [comment]
Hi @michaelortnersanube,
That message is quite old.

Is this a previously working BookStack instance that has failed upon upgrade?

**Comment by michaelortnersanube** [comment]
Hello,

yes. I have upgraded the docker container from 22.07.02 to 22.07.03 and now it doesn't work. I have take another image, but same error.

**Comment by ssddanbrown** [comment]
The linuxserver container did receive [some updates](https://github.com/linuxserver/docker-bookstack/commit/32df06d2ab1a84430f5577c5cd4adb81f4554195) recently which could be causing issues with your existing files/config.
I did upgrade a couple of older version setups (albeit from this year) on my machine without issue.

Did you make any changes to the `nginx/site-confs/default.conf` file at all? If not, can you share the contents to make sure it's correct? It may be the case [this migration](https://github.com/linuxserver/docker-bookstack/commit/32df06d2ab1a84430f5577c5cd4adb81f4554195) did not run as expected.

**Comment by michaelortnersanube** [comment]
Maybe i am stupid, but in the container the folder site-confs doesn't exist

![image](https://user-images.githubusercontent.com/96595501/186134078-47ca765a-e14a-4094-8469-bd59cb5264c3.png)

**Comment by michaelortnersanube** [comment]
ah i found it now, it is under config/nginx/site-confs/, my wrong. Here is the content

![image](https://user-images.githubusercontent.com/96595501/186136065-1126c2f4-20df-4b9a-92ad-965565f62821.png)
![image](https://user-images.githubusercontent.com/96595501/186136094-1052efb5-fd9f-460e-a66d-ea1662aa5f19.png)

**Comment by ssddanbrown** [comment]
That matches what I have.
- Any other files in the `site-confs` folder?
- What architecture are you running on? x86_64 or ARM64?
- What is the output of running `ps -aux | grep php` within the container?

**Comment by michaelortnersanube** [comment]
Thank you for the information. For your questions i have posted you some screenshots, i hope this help you to find out where my problem is :)

![image](https://user-images.githubusercontent.com/96595501/186137991-bb60346d-47c2-487f-a23a-8789fc5170d5.png)
![image](https://user-images.githubusercontent.com/96595501/186138180-1648e859-a1cd-40fc-8969-9c4b1099db40.png)
![image](https://user-images.githubusercontent.com/96595501/186138221-ed575973-be21-40e5-bbdc-075d2f9b57c1.png)
![image](https://user-images.githubusercontent.com/96595501/186138055-6f307a75-2414-4e2c-972b-79f2fb3bb2da.png)

**Comment by michaelortnersanube** [comment]
btw i am back to the version 22.07.2, where it has worked, but same problem

**Comment by ssddanbrown** [comment]
@michaelortnersanube Ah, I was going to say much of the values in those screenshots don't look right for the latest version.
I think jumping back to older versions will confuse things. The new container versions makes changes upon update to paths, which then won't match for older versions.

**Comment by michaelortnersanube** [comment]
Ah that was not good. So have you any idea how i can fix this problem maybe?

**Comment by ssddanbrown** [comment]
Not really, since we still don't know the exact cause of the problem.
It's likely some paths did not align after update, or some extra config is causing interference. Likely on the apache or php side of things. I'd focus on getting the new setup working.

As a last resort, **_after a backup of all files_**, you could always remove your existing bookstack volume files, start the container, then stop it, the restore your existing BookStack files (everything in `www` folder) into the matching directory then restart again. Essentially restoring your files into a fresh state.

**Comment by michaelortnersanube** [comment]
Hello you mean i should make a backup of this files: 
![image](https://user-images.githubusercontent.com/96595501/186141328-813a03df-5712-49cb-92a1-02d977516180.png)

then delete all these files and the volumes of bookstack. database container too? The i should recreate the bookstack and upload all the content from the folder www back to the folder www, right?

**Comment by ssddanbrown** [comment]
Yes but **_do not delete the database data or container_**, the database should be fine here. If that `DB` folder is your database files, leave that (I'd generally avoid sharing mounted volume folders like that).

**Comment by michaelortnersanube** [comment]
So step by step,

i copy the folder bookstack to bookstack-backup, then i remove the content from bookstack without the DB folder. Then i stop the container of bookstack, remove the volumes and then start it. Then i stop it again, cp the content of www to the new bookstack www

Thanks for help, but i want to make sure that i am 100% sure and make all right :)

**Comment by ssddanbrown** [comment]
Yeah, I'd personally backup the original files to another system first, to be sure they're safe.

**Comment by michaelortnersanube** [comment]
Hello,

i have made all of this, now it works, but the images are not loading, have i to upload them all my self or have i maybe something forgot to cp back to the new?

![image](https://user-images.githubusercontent.com/96595501/186145837-55d6b7d1-5cef-4d73-a793-5e8f3836641e.png)

**Comment by michaelortnersanube** [comment]
And maybe some other feedback:

I have set the linuxserver/bookstack image to latest, if i go to /var/www/html the folder is empty without the public folder. So i have reacreate all things back and set the image to 22.07.2, then all content was back in the folder

**Comment by michaelortnersanube** [comment]
i think maybe problem with the rights or the owner?
![image](https://user-images.githubusercontent.com/96595501/186148219-8849278a-078d-425b-b24c-5585013bbf36.png)

**Comment by michaelortnersanube** [comment]
My wrong, now working Sorry.
