### ISSUE TITLE
[Feature Request] Included blocks of content fall back

### ISSUE THREAD

**Issue by JoeIzzard** [BookStackApp/BookStack#3671]
### Describe the feature you'd like

I am using the method outlined in #978, protecting pages and including them to give protect blocks of content still within the flow of an existing page, for example for admin info. 

It would be great for somethings to be able to specify a fallback for a block of content so that if the included protect content can't be displayed because of permissions, we can leave a `Please contact X for assistance` message. This would ideally be specified at the inclusion tag level. This could take the form:

```
{{{@101*@1#blocked}}
```

In this example we are trying to include page 101, but if that is protected and you are not allowed to see it, display the blocked section from page 1. Exact syntax could be something cleaner but this would allow much more control over these sorts of things.

### Describe the benefits this would bring to existing BookStack users

This would give much more exact control over what is displayed when content is protected and would allow us to give fallback information. Currently you can just include both pages but then people with access would see both pages content.

### Can the goal of this request already be achieved via other means?

No, not that I am aware of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @JoeIzzard.

I'm hesitant to add features & grow the complexity of the include system since it's really a lesser know element meant for primarily for some power-user scenarios. 

As an alternative, I'm thinking we could maybe offer a [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) event within the include system, that could allow for a variety of extension/customization such as this where really desired.

**Comment by JoeIzzard** [comment]
For us the inclusion system has little value beyond restricting content, we do use it for pure inclusions too but primarily access restriction.

The ability to do more of that through the logical theme system would definitely be a really good step although to me feels more like a plugin system, is that what the logical theme system is? It seems from what you linked to to do a lot of 'plugin' style things.

**Comment by ssddanbrown** [comment]
>  although to me feels more like a plugin system, is that what the logical theme system is?

Yeah, kind of. It's providing an interface for out-of-platform customization/extension, to allow things that may not be, are have not yet been, added within BookStack on your own instance, without altering core app files.
Not a full plugin system yet but may form the foundation for a more comprehensive plugin system in the future.

**Comment by ssddanbrown** [comment]
As mentioned above, I've now added a "page_include_parse" theme event for customization of page include logic, as the work done in #3698.
This will be part of the next feature release.

You will be able to achieve the core request here, after upgrade, with a logical theme system `functions.php` along the lines of this:

```php
<?php

use BookStack\Entities\Models\Page;
use BookStack\Facades\Theme;
use BookStack\Theming\ThemeEvents;

// Provide fallback for not-found or empty include HTML content
Theme::listen(ThemeEvents::PAGE_INCLUDE_PARSE, function(string $tagReference, string $replacementHTML, Page $currentPage, ?Page $referencedPage) {
    if (empty($replacementHTML)) {
        return 'Included content could not be found, Please content x for assistance';
    }
});
```

I'm going to therefore close this off but if you need any help with adding the above, after the next feature release is available, feel free to comment here and mention me and I can provide some further guidance.
