### ISSUE TITLE
Lists next to floated images lose nesting indentation

### ISSUE THREAD

**Issue by Android1338** [BookStackApp/BookStack#3672]
### Describe the Bug

If I have text with a list beside of an image, the list entries will not change their positions at "Test #1", but in an exported PDF or Markdown file it works.

Please see attachment.
1. List with problems beside of an image.
2. List without problems with no image.
![problem](https://user-images.githubusercontent.com/29342292/186241447-428b057c-1d1d-4b59-b42a-d3f059324cfb.png)

### Steps to Reproduce

1. Add an image to a article
2. Change the image to "Align left"
3. Add some text beside of the image
4. Add a list with multiple tabbed items

### Expected Behaviour

A list beside of an image should looks normal, like a list without an image besides of it.

### Exact BookStack Version

v22.07.3

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04.1 LTS, installed using official installation script.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Android1338!

Looking into this, I've learnt some new CSS: `display: flow-root`. Should fix this issue since it creates a new block formatting context. Relatively new yet well supported. Will apply to lists for the next feature release.
