### ISSUE TITLE
System-Wide/Granular enable/disable for "Reusing Page Content" feature (plus audit?/tracking?)

### ISSUE THREAD

**Issue by BloodyIron** [BookStackApp/BookStack#3678]
### Describe the feature you'd like

This is regarding : https://www.bookstackapp.com/docs/user/reusing-page-content/

While this feature is mad lad cool, and I could see being mad useful in a lot of scenarios, it also presents IT Security problems. In that, I am not seeing a way to see when content is referred in this way, and where. Plus also not seeing a way to limit/disable this feature, at various scopes (including system-wide?)

IMO I think it would be beneficial to extend this feature such that:

1. You can audit all "Reusing Page Content" instances across the whole system, both in which content is sourced and where it is referenced. So that it is easier to see where it may be used poorly/abused.
2. Enable the ability to disable this feature at all scopes, site-wide/per-shelf/per-book/per-chapter/per-page/etc

I suspect there will be many users that legitimately would like this feature where I am implementing it, but I want to have my cake and eat it too. In that, I think there's sections of our content where this usage is not only reasonable, is valuable. And in other areas it represents a real IT Security threat, as we plan to also have extremely sensitive content in sections, that we cannot have referenced in ways that circumvent security configurations (RBAC, etc). And in its current form it sure does look like access controls can be circumvented with this feature, plus even tracking active links of this nature looks logistically infeasible currently (NIGHTMARE).

### Describe the benefits this would bring to existing BookStack users

Increase IT Security features so that access controls can be adhered to, but also make it so it can be used in areas where it is reasonable as a function.

### Can the goal of this request already be achieved via other means?

Not that I am aware of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Hi @BloodyIron,

Just to confirm the functionality of content includes, these are handled dynamically as page-view time and reference content should only become included if the viewer has the ability to view the page where the referenced/included content is sourced from.

The content include system is really something I don't want to expand the scope of, being a lesser known power-user feature, especially so when it comes to permissions. I really would not look to add granular permissions specific to this system, especially so at the variations requested, as I just don't see the complexity to be worthwhile.

Within [3671](https://github.com/BookStackApp/BookStack/issues/3671#issuecomment-1224297004) I mentioned the idea of adding a logical theme event for page includes. Maybe such an event could be used for control logic such as this, while different any desired logical complexity to the host admin instead of the BookStack project itself.

**Comment by BloodyIron** [comment]
> Just to confirm the functionality of content includes, these are handled dynamically as page-view time and reference content should only become included if the viewer has the ability to view the page where the referenced/included content is sourced from.

Is this how it works currently? Am I reading this correctly?

**Comment by Mailstorm-ctrl** [comment]
> > Just to confirm the functionality of content includes, these are handled dynamically as page-view time and reference content should only become included if the viewer has the ability to view the page where the referenced/included content is sourced from.
> 
> Is this how it works currently? Am I reading this correctly?

I just confirmed this. ~~If you want to reuse page content, the user making the page needs at the very least read/view permission on the specific page/pageid. If they don't have view/read then nothing shows up in the page.~~

~~I haven't confirmed if different users looking at a page that has a reuse tag can/cannot see content depending on their permissions. I only confirmed that if a user doesn't have access to the linked content, they won't see it.~~

If the viewer of the page doesn't have access to the original page, nothing will show up on the page. If the viewer does have access to the linked page, they will see whatever is on the text. So basically...as long as your permissions are solid there is no way of exposing covered pages through reusing content.

**Comment by ssddanbrown** [comment]
> If the viewer does have access to the linked page, they will see whatever is on the text. So basically...as long as your permissions are solid there is no way of exposing covered pages through reusing content.

Yeah, That aligns with my expectation. Of course a user could export/print/copy-paste restricted content and send it to a user without permissions, but you generally have that problem with any permission-controlled content, this just introduced a slightly more dynamic layer.

**Comment by ssddanbrown** [comment]
With the work in #3698, I've now added a custom event to the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) to allow customization of BookStack page content include handling. This will be part of the next feature release.

As an example, you will be able to achieve disabling of content includes, after upgrade, with a logical theme system `functions.php` along the lines of this:

```php
<?php

use BookStack\Entities\Models\Page;
use BookStack\Facades\Theme;
use BookStack\Theming\ThemeEvents;

// Disable page includes by returning empty HTML content
Theme::listen(ThemeEvents::PAGE_INCLUDE_PARSE, function(string $tagReference, string $replacementHTML, Page $currentPage, ?Page $referencedPage) {
    return '';
});
```

A lot of various variables are passed to this event so advanced logic can be built if really desired.
I'm going to therefore close this off but if you need any help with adding the above, after the next feature release is available, feel free to comment here and mention me and I can provide some further guidance.
