### ISSUE TITLE
[FR] Images text wrapping

### ISSUE THREAD

**Issue by sprnza** [BookStackApp/BookStack#368]
It would be great to have an ability to set text wrapping around images. I believe three options: Left, Right and None would be enough.

Thanks for the project, guys!

**Comment by kwa11ace** [comment]
Hi, I would also like to see if text wrapping is possible.  I've been looking for a online documentation system and this is a great project for it.

**Comment by ssddanbrown** [comment]
Hi @sprnza,
The main, WYSIWYG editor has this option:

![image](https://cloud.githubusercontent.com/assets/8343178/25504978/d8534754-2b97-11e7-9fc2-29fd86fc26d6.png)

Does this suit your need?

**Comment by sprnza** [comment]
Hi @ssddanbrown ! It's exactly what I need, but how did you do that? :)

**Comment by kwa11ace** [comment]
sprnza, hi 
1. Select the picture you want to float
2. Select the alignment you ans and, viola!

![image-float](https://cloud.githubusercontent.com/assets/28090400/25552110/fee1b234-2cc3-11e7-87ee-e30f5ad51b25.jpg)

**Comment by sprnza** [comment]
Doesn't work for me for some reason.
<a href="http://i.imgur.com/1KrIVYn.png">
  <img src="http://imgur.com/1KrIVYnl.png" />
</a>

**Comment by ssddanbrown** [comment]
@sprnza What browser/OS are you using?

**Comment by sprnza** [comment]
@ssddanbrown 
Firefox 53.0
Archlinux

**Comment by sprnza** [comment]
@ssddanbrown It's definitely FF's issue. It works with Luakit (the only extra browser I have)
<a href="http://i.imgur.com/TMyw6gN.png">
  <img src="http://imgur.com/TMyw6gNl.png" />
</a>

**Comment by ssddanbrown** [comment]
Since a lot has changed since this issue was created, including changes to aligned image placement, I'm going to close this. If the core issue remains please open a new issue referencing this one.
