### ISSUE TITLE
Markdown file export and import

### ISSUE THREAD

**Issue by geniusshiun** [BookStackApp/BookStack#3686]
### Describe the feature you'd like

It's a great service. 
I can export book by markdown format.
Can I import book by markdown format file?

### Describe the benefits this would bring to existing BookStack users

Create book faster.

### Can the goal of this request already be achieved via other means?

No?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
> Can I import book by markdown format file?

No direct UI-based import for books, but you can directly insert markdown into a page using the markdown page editor.
Books don't really have content themselves, but are built of many pages within BookStack. I don't want to expand to support custom formats to import custom collections of markdown files.

Alternatively, you can create/update pages using the REST API with markdown content, if you have some coding skills.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up to the suggestions above I'm going to close this off.
