### ISSUE TITLE
Search in Chinese/non-english need to be start of the sentence

### ISSUE THREAD

**Issue by stevo-king** [BookStackApp/BookStack#3687]
### Describe the Bug

I have created some books and page in my bookstackapp, when I search in english, it is working perfectly, the search result return a lot of thing, which is very good for knowledge base apps.

But when I search in chinese charater, it got some problem.  E.g., I have a book page with title of "如何製作form 1a/form 1c?". The below is the search result:
Search term: 製作 result: No search result
Search term: 何製作 result: No search result
Search term: 如何製 result: successful return of the search result
Search term: 1a result: successful return of the search result
Search term: form 1a result: successful return of the search result

So I think for non-English character, the search term must be the start of the sentence, so that I can get the result. 

### Steps to Reproduce

1. Use the search bar
2. Search different Chinese term in the books, it need to be start of the sentence to be searchable.

### Expected Behaviour

Search term: 製作 result: successful return of the search result
Search term: 何製作 result: successful return of the search result
Search term: 如何製 result: successful return of the search result

I think for non-english character, the search term is not necessarily required to be the beginning of the sentence.

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/9255890/187342235-a18aaeb4-75e4-4614-b57a-fea428962b98.png)
![image](https://user-images.githubusercontent.com/9255890/187342248-85de0d91-e793-4465-a7c8-35588e174b8a.png)
![image](https://user-images.githubusercontent.com/9255890/187342265-8896ac15-59a0-42f6-99f6-87c7fd90a75f.png)
![image](https://user-images.githubusercontent.com/9255890/187342282-11e70349-0dc6-454c-8f31-48fad214499f.png)

### Exact BookStack Version

v22.06.2

### PHP Version

7.4

### Hosting Environment

Apache/2.4.41 (Ubuntu)

**Comment by ssddanbrown** [comment]
Thanks for reporting @stevo-king,
But this is already open as issue #778 so I'm going to therefore close this off as a duplicate.
