### ISSUE TITLE
Meilisearch Integration

### ISSUE THREAD

**Issue by yarshad** [BookStackApp/BookStack#3690]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I installed Bookstack on Apache/Windows, and I noticed that the search does not work the way it works on Bookstack home page.

I saw a note that bookstack uses Meilisearch, so I was wondering if our installation comes with the Meilisearch or is there an easy way to integrate Meilisearch in my installation?

### Exact BookStack Version

v22.07.3

### Hosting Environment

Windows 10

**Comment by ssddanbrown** [comment]
Hi @yarshad,
BookStack does not integrate with, or use, Meilisearch at all.
The BookStack website is built with a static-site-generator ([source code here](https://github.com/BookStackApp/website)), not BookStack and hence we use Meilisearch on the website. If you're interested in why I don't use BookStack for the main site, [this thread](https://github.com/BookStackApp/BookStack/issues/3386) might be helpful.
