### ISSUE TITLE
Replce Shelves and Books with some other words

### ISSUE THREAD

**Issue by Swelidingo** [BookStackApp/BookStack#3691]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I would like to replace "Shelves" and "Books" with other words. i couldnt find any file that can be edited to replace those words.
i would appreciate some guidence if it is possible.

### Exact BookStack Version

v21.08.5

### Hosting Environment

Ubuntu 20.04

**Comment by ssddanbrown** [comment]
Hi @Swelidingo, We don't have a direct in-built way to achieve this.
A request for renaming is already open in #2901 so I'll therefore close this off.
A previous issue, #406, also had a lot of discussion about this.

A workaround is possible though, although it wouldn't change the names used in URLs.
See the latter part of my [comment here](https://github.com/BookStackApp/BookStack/issues/406#issuecomment-771249444) for more info. The system used is [detailed here](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md#customizing-text-content), and I show this system in use in [my video here](https://www.youtube.com/watch?v=gLy_2GBse48).
