### ISSUE TITLE
Revision Permissions

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3692]
### Describe the feature you'd like

It would be nice if we could control the permissions for revisions. For example, I'd want users to be able to go back and look at revisions, but I don't want them to be able to delete revisions (especially if it isn't logged).

Permissions that'd be nice with revisions:

View Revisions (Changes & Preview)
Rollback to Revision (Restore)
Delete Revision (Delete)

### Describe the benefits this would bring to existing BookStack users

Better permission control for revision

### Can the goal of this request already be achieved via other means?

Not that I know of

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by InoryS** [comment]
I need this too, the wiki system should be able to control viewing revisions.
I'd like to be able to allow guest to view revisions but not rollbacks and delete, Just like MediaWiki.

**Comment by ssddanbrown** [comment]
Thanks for this request, and the described behaviour is actually the intention, but the permissions for the revision list viewing links have always been off.

This is already open under #2946 so I'm going to close this off as a duplicate but I'm going to assign #2946 for the next feature release so I don't forget about it.
