### ISSUE TITLE
Webp image upload support

### ISSUE THREAD

**Issue by InoryS** [BookStackApp/BookStack#3694]
### Describe the feature you'd like

I noticed that my Webp images became PNG images after uploading. 
Please support Webp format image upload.

### Describe the benefits this would bring to existing BookStack users

Can save a lot of bandwidth and hard disk, help people save costs.
Users are also able to save bandwidth and see pages faster.

### Can the goal of this request already be achieved via other means?

- Use an external image service.
- Upload images directly to the website directory.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @InoryS,
Webp images should generally be supported. Just tested various cases on my instance to confirm this, Thumbnail/scaling retained webp format as expected.

If this is not working for you please could you confirm the following:
- If possible, please provide a webp image file that's being converted as described.
- Confirm the version of PHP being used with BookStack.
- Confirm the operating system in use.
- Confirm the hosting/install method.
- Confirm the exact version of BookStack in use (Found in settings or the `version` file in the BookStack folder).

**Comment by InoryS** [comment]
This is very strange, I just reproduced this before the demo reset, but now I can't reproduce the issue on my instance nor the demo.
Maybe it's an OS ghost issue, sorry for the trouble.

**Comment by rockonedege** [comment]
when pasting an image into the edit box, it is currently saved as PNG, is it possible to use webp as a default?

**Comment by ssddanbrown** [comment]
@rockonedege It should just match the source content (which could potentially be altered by the browser).
I wouldn't really look to complicate matters by adding an extra layer of configurable conversion like that.
