### ISSUE TITLE
Recently made and edited books and pages are not found after upgrading from v22.07.1 to v22.07.3

### ISSUE THREAD

**Issue by SmokingCrop** [BookStackApp/BookStack#3695]
### Describe the Bug

When upgrading BookStack v22.07.1 to v22.07.3, recently made and edited books/pages are not found.
They still appear in the Audit log. However when clicking on the link to go to the book, it just says "Book not found : Sorry, The page you were looking for could not be found. If you expected this page to exist, you might not have permission to view it.".

However, I can click on several pages within the book and view those just fine. Those were not edited recently.

Another book just seems to be gone all the way, I cannot view any pages within the book. And the book itself is gone as well. All those pages were edited or created recently.

When I check the audit log, it seems all books/pages that were either created or updated while on the v22.07.01 update are "not found" after updating to 22.07.03.

My user is the administrator that has permission to view everything.

Something gone wrong with the permissions?
I have put back a checkpoint, but I can easily upgrade again when our users are not going to be using it.

### Steps to Reproduce

1. Be on v22.07.01
2. Create some books/pages and edit some existing pages
3. Upgrade to 22.07.03
4. Try to find those books/pages again, they will be in the audit log, but you can't view them when clicking on the links in audit log.

### Expected Behaviour

The books and pages should remain viewable.

### Exact BookStack Version

v22.07.03

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 22.04, virtual machine on our Hyper-V server, installed with the official script.

**Comment by ssddanbrown** [comment]
Hi @SmokingCrop,

Nothing between those releases should really cause a visibility change such as this.

- Is the app version definitely the only variable here? Could have changes been made by users since your v22.07.1 restore point, or the point where you last tested there?
- Are these items in the recycle bin at all?
- Do these items have custom permissions applied to them or their parent items?

You could try re-building the permissions index after upgrading (via a `php artisan bookstack:regenerate-permissions` command) but, again, not really sure why this would be needed upgrading between the specified versions.

**Comment by SmokingCrop** [comment]
> Hi @SmokingCrop,
> 
> Nothing between those releases should really cause a visibility change such as this.
> 
> * Is the app version definitely the only variable here? Could have changes been made by users since your v22.07.1 restore point, or the point where you last tested there?
> * Are these items in the recycle bin at all?
> * Do these items have custom permissions applied to them or their parent items?
> 
> You could try re-building the permissions index after upgrading (via a `php artisan bookstack:regenerate-permissions` command) but, again, not really sure why this would be needed upgrading between the specified versions.


The `php artisan bookstack:regenerate-permissions` command fixed the issue!
- The restore point was from a minute before upgrading, no changes were made to anything really
- no items were in the recycle bin
- there were items without custom permissions and items with custom ones (that both seemingly disappeared after upgrading)


No idea why it happened, but the regenerate-permissions command fixed it 👍

**Comment by ssddanbrown** [comment]
For possible dev future reference, details and further info tracked in https://github.com/BookStackApp/BookStack/issues/3660#issuecomment-1260613841

**Comment by athornfam2** [comment]
> php artisan bookstack:regenerate-permissions

Just wanted to add that this fixed my issue with a minor upgrade (2.x to 2.x) This happened to me back in June but didn't have the time to dig into it. @ssddanbrown Can this be added to the debugging/troubleshooting? I'm not sure how to edit on github.
