### ISSUE TITLE
Image delete button visible without permission

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3697]
### Describe the Bug

This might be in other places but this bug is specifically for images.

If a user is allowed to VIEW pictures but NOT DELETE them the user will still have access to the delete button in the image select menu.
![image](https://user-images.githubusercontent.com/53045430/188467681-74970cce-c148-4016-8c2d-20d501c5ebc9.png)

If I click on the confirm button, I will get a bugged view of the image select screen that is only temporary.
![image](https://user-images.githubusercontent.com/53045430/188467782-1e526085-a4fa-4a9b-a94a-976c7c29d4a5.png)

The image doesn't delete (good) but the button still shouldn't be visible. Just a minor QoL thing.

### Steps to Reproduce

1. Create a role that can view images but not delete them.
2. Have a book where that role can view/create/edit but not delete.
3. Upload an image to a page is said book.
4. Save page.
5. Open page and try to delete the image from the image select menu.
6. Observe.

### Expected Behaviour

Delete button to be not visible or at least not-clickable.

### Exact BookStack Version

v22.07.3

### Hosting Environment

Ubuntu 20.04 LTS in a LXC container.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Mailstorm-ctrl.
Can confirm that permission-based visibility of this button was not active.
Have added within commit fbef0d06f2d61030183d5b85a49620f4d23717b1, to be part of the next feature release.
