### ISSUE TITLE
Copying a book should put it in the shelf/shelves it's currently in.

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3699]
### Describe the feature you'd like

Currently, when you copy a book that is in a shelf, the copy will not be a part of any shelf. These seems counter intuitive when you think about it. I understand somethings cannot/shouldn't be copied but the location of a book is something that seems like it should be.

If you want to copy a book and add it to a shelf, you will need to copy the book, open the shelf you want it to be in, then add it manually. This can be annoying if you have hundreds of books.

This can tie in nicely with [#1171](https://github.com/BookStackApp/BookStack/issues/1171)

### Describe the benefits this would bring to existing BookStack users

Copy function that operates as expected/intuitive. Also allows users to create "template" books within shelves.

### Can the goal of this request already be achieved via other means?

Not that I know of. Maybe through the use of webhooks and API but there doesn't appear to be a way to get the shelves a book may be apart of through the API or CLI.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @Mailstorm-ctrl.
I agree that this would be potentially expected and useful behaviour.
Will assign to the feature release after next.

**Comment by ssddanbrown** [comment]
Functionality now added in 60171b3522220e874436f52cc8936f6879e7e60f.
Note, this will only take place for relation to shelves, where the current user has permission to edit the shelf (Since they'd effectively be altering the shelf contents by cloning a book).

Will be part of the next feature release.
