### ISSUE TITLE
Footnotes not working

### ISSUE THREAD

**Issue by grugel-maintro** [BookStackApp/BookStack#3700]
Simple footnotes and also long footnotes are not working. 

Those are standard markdown syntax and should be implemented. 
```md
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: meaningful!

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

_Originally posted by @grugel-maintro in https://github.com/BookStackApp/BookStack/issues/2664#issuecomment-1237595086_

**Comment by ssddanbrown** [comment]
Hi @grugel-maintro,
Footnotes are not something that's supported, but are already requested in issue #2637 so I'll therefore close this off as a duplicate. 

> Those are standard markdown syntax and should be implemented.

Since there's really no such thing as "standard markdown" we tend to stick to commonmark, albeit with a few extensions.
