### ISSUE TITLE
/app/www/artisan bookstack:update-url PDOException

### ISSUE THREAD

**Issue by grugel-maintro** [BookStackApp/BookStack#3703]
### Describe the Bug

Try to replace the domain in the database in a newly setup docker environment with:
`docker exec -it bookstack-local php /app/www/artisan bookstack:update-url http://xxx.xxx http://localhost:xxxx`
get the following error:
```bash
   PDOException 

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again

  at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
     66▕         if (class_exists(PDOConnection::class) && ! $this->isPersistentConnection($options)) {
     67▕             return new PDOConnection($dsn, $username, $password, $options);
     68▕         }
     69▕ 
  ➜  70▕         return new PDO($dsn, $username, $password, $options);
     71▕     }
     72▕ 
     73▕     /**
     74▕      * Determine if the connection is persistent.

      +7 vendor frames 
  8   /app/www/app/Console/Commands/UpdateUrl.php:102
      Illuminate\Database\Connection::getPdo()

  9   /app/www/app/Console/Commands/UpdateUrl.php:70
      BookStack\Console\Commands\UpdateUrl::replaceValueInTable()
```

### Steps to Reproduce

1. Setup service over docker
2. Change URL in database with `docker exec -it bookstack-local php /app/www/artisan bookstack:update-url http://xxx.xxx http://localhost:xxxx`
3. Get error

### Expected Behaviour

Replace URL in database

### Exact BookStack Version

BookStack v22.07.3 

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Hi @grugel-maintro,
Based on that error I'd say that your BookStack instance does not have visibility of the database host system.
I'd expect you'd also be getting errors on container start-up as database migrations are attempted.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
