### ISSUE TITLE
Sections or categories in Shelves

### ISSUE THREAD

**Issue by CoSciBlog** [BookStackApp/BookStack#3708]
### Describe the feature you'd like

Would be nice to have another level of hirarchy in the shelves like categories or sections(or even categories with nested categories).

### Describe the benefits this would bring to existing BookStack users

This one would be usefull for technical knowledgebases or communities like with more than two levels of hirarchy.
for example
village a
-- church/category a
----- book 1
-- guilds/category b
----- book 2
----- book 3
-- companies/category c
----- book 4
----- book 5
----- book 6
village b
-- church/category a
----- book 1
-- guilds/category b
----- book 2
----- book 3
-- companies/category c
----- book 4
----- book 5
----- book 6

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request @CoSciBlog, but I'm going to close this off as the essential request is extra levels of heirachy which could already be covered by #3016.

For historical insight into this, #95 is worth a review.
