### ISSUE TITLE
DIA-Links in Bookstack doesn´t work

### ISSUE THREAD

**Issue by micha141076** [BookStackApp/BookStack#3709]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,
when I create a graphic in DIA and put a hyperlink on it, this link does not work in the saved page of Bookstack.
Is this a bug or I´m doing something wrong?

I hope 

Greetings & thanks for the help

### Exact BookStack Version

v22.07.3

### Hosting Environment

Ubuntu Server 22.04

**Comment by ssddanbrown** [comment]
Just to confirm, are you referencing Dia, the [gnome-based diagramming tool](https://wiki.gnome.org/Apps/Dia) or are you referencing the built-in diagrams.net integration?

**Comment by micha141076** [comment]
Hi. the built-in-Version.

**Comment by ssddanbrown** [comment]
Okay, Yeah, links are not supported at this time in drawings due to the format we use.
A request to support this feature is already open in #1170. Will therefore close this off.
