### ISSUE TITLE
The website icon is not shown

### ISSUE THREAD

**Issue by GongMingCai** [BookStackApp/BookStack#3711]
### Describe the Bug

The favicon.ico don't show, but the file is stored in a public directory.

### Steps to Reproduce

open bookstack website

### Expected Behaviour

The website display favicon.ico 

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/88075411/189265042-1067c166-495f-4257-8ae2-3c2d9410d493.png)

### Exact BookStack Version

BookStack v22.04.1

### PHP Version

8.0.20

### Hosting Environment

Red Hat Enterprise Linux 7

**Comment by GongMingCai** [comment]
I added the following code to resource/views/layouts/base.blade.php and it worked.
```
<link rel="icon" href="{{ versioned_asset('favicon.ico') }}">
```

**Comment by Statium** [comment]
I confirm, the problem is similar. Only the standard favicon is displayed

**Comment by ssddanbrown** [comment]
Hi @GongMingCai and @Statium,
Are you hosting your instance on sub-paths? For example: `https://example.com/wiki`

**Comment by GongMingCai** [comment]
yes

**Comment by GongMingCai** [comment]
yes
