### ISSUE TITLE
Support for Redis sockets

### ISSUE THREAD

**Issue by r7l** [BookStackApp/BookStack#3713]
### Describe the feature you'd like

The current configuration doesn't support connecting to Redis using Unix sockets. I've also seen the older issue there was about this. It was closed by the user back then but it would still be a nice feature. Laravel does support this out of the box and using sockets is also supported by Bookstack for MySQL (mostly because of Laravel).

### Describe the benefits this would bring to existing BookStack users

Being able to use Redis over Unix sockets as it is already supported by Laravel and even MySQL with Bookstack. It's most likely not of much use for users using Docker but there are still people out there that install software with a bare metal stack. Using sockets has the advantage to not to be bothered with additional network security issues as there is no network connection beside the HTTP endoint (Apache / Nginx). 

Beside security there also is better performance and therefor also a lower impact on environment, even if minimal. People should actually be encouraged using sockets instead of TCP when possible.

### Can the goal of this request already be achieved via other means?

Only by opening Redis up via TCP.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Previous mentioned issue for context: #2669

Thanks for raising @r7l, but I'm still not really sure on the use-case/purpose for this.
I don't like to add support for new options unless there's significant purpose or desire for it, for which I don't see here.
My feelings are that redis sockets are mainly used when the redis server is local, whereas we mainly have redis as an option for the purposes of remote or high-availability cache/session support, Otherwise the default filesystem driver is usually good enough.

**Comment by r7l** [comment]
@ssddanbrown I can surely understand the idea of not adding features and options when there is little demand. It's also understandable to have a focus on certain types of hosting. But then, this project was repeatedly mentioned on so called "[Selfhosting](https://www.reddit.com/r/selfhosted/comments/i14dnq/5_years_of_bookstack/)" communities for quite some time now. People hosting on all sorts of hardware at home is a constantly growing thing, thanks to stuff like RaspberryPI and NAS hardware.

I wonder if this feature would actually cause so much work to add and maintain, as it's already implemented in Laravel. I would assume that all you have to do is forwarding the options from `.env` to it. But i am not a Laravel developer. Instead i run [other OSS projects](https://github.com/Kovah/LinkAce/blob/main/config/database.php) that use Laravel and support Redis sockets.

**Comment by ssddanbrown** [comment]
> I wonder if this feature would actually cause so much work to add and maintain, as it's already implemented in Laravel. I would assume that all you have to do is forwarding the options from .env to it. 

That would be likely be all that's required, but the initial technical effort is rarely the costly part.
It's the test, validation upon framework update, documentation, user support and the extra variables when debugging and supporting with users.
If it was just this case, there wouldn't be an issue, but there are many many cases like this with little edge-case requests, which can add up in terms of impact, so I set a scope of what we support based upon value.

**Comment by ssddanbrown** [comment]
As per the above, I'm not clear on the value of this so I'm going to go head and close this off.
