### ISSUE TITLE
Emoji in Bookstack

### ISSUE THREAD

**Issue by micha141076** [BookStackApp/BookStack#3716]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,
How can I add emojis to Bookstack? Is there documentation on this?
I havn´t found nothing.

Greeting
Micha

### Exact BookStack Version

22.09

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @micha141076,
We don't specifically support any emoji interface controls (Nor do we for other symbols/characters) but they can be inserted using whatever means your operating system provides:

- [Windows](https://support.microsoft.com/en-us/windows/windows-keyboard-tips-and-tricks-588e0b72-0fff-6d3f-aeee-6e5116097942)
- [Mac](https://www.howtogeek.com/684025/how-to-type-emoji-on-your-mac-with-a-keyboard-shortcut/)
- On mobile devices there's often an emoji button when using the keyboard.

**Comment by micha141076** [comment]
OK. Thank for the feedback
