### ISSUE TITLE
Second and third AD catalogues.

### ISSUE THREAD

**Issue by igoresz** [BookStackApp/BookStack#3718]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello.
It looks like BookStack can't work with two mo more AD catalogues.
Is it correctable?

Many thanks in advance,
Igor St.

### Exact BookStack Version

BookStack v22.09

### Hosting Environment

Hello.
It looks like BookStack can't work with two mo more AD catalogues.
Is it correctable?

Many thanks in advance,
Igor St.

**Comment by ssddanbrown** [comment]
Hi @igoresz, By catalogues, I'm assuming multiple active directory instances?
If so, that is not something we currently support. It has been requested for LDAP in #543.
