### ISSUE TITLE
[Feature Request] Custom homepage with news

### ISSUE THREAD

**Issue by maximelebastard** [BookStackApp/BookStack#372]
Desired Feature:

It would be nice if we can have a light "blogging" module on the homepage. This can be useful to use BookStack for an intranet.
These news can include major updates on the articles to make the BookStack instance more alive.

**Comment by yoginth** [comment]
Visit https://friendstub.com

**Comment by ssddanbrown** [comment]
Proposed implementation discussed under #126.

**Comment by ssddanbrown** [comment]
Now complete as of 0a402e3
