### ISSUE TITLE
Broken Layout and Huge Icons

### ISSUE THREAD

**Issue by carlossierra311** [BookStackApp/BookStack#3721]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi BookStack team. I followed the steps described [here](https://www.bookstackapp.com/docs/admin/installation/) to install the application on my Windows PC, and the application seems to work, but the design is broken and the icons are huge: 
![image](https://user-images.githubusercontent.com/23511373/189961631-af57172f-537e-4184-8273-f1fc579a123c.png)

My APP_URL variable, in the .env file, looks like this:
`APP_URL=http://localhost`

I already read [this other support case](https://github.com/BookStackApp/BookStack/issues/879), but my installation was done from the **release** branch:
`git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch`

And I have content of the folders mentioned there: 
![image](https://user-images.githubusercontent.com/23511373/189961688-47752a86-e25a-4080-b20e-0abafe9b4168.png)

I also followed the debugging guide, and after turning debugging in the .env file and reloading the app, I tried looking for the storage/logs/laravel.log file, but the file wasn't there. And Nginx's error log only shows this:
`2022/09/12 22:44:29 [notice] 32896#30848: signal process started`

Here is the software stack I used for the installation: 
Bookstack 22.09 (taken from the version file on the installation folder)
mysql 8.0.30
nginx 1.23.1
php 8.1.10
Windows 10 Pro 21H2

I would appreciate if you could point me in the right direction to solve this issue. Thanks! 

### Exact BookStack Version

22.09

### PHP Version

8.1.10

### Hosting Environment

Windows 10 Pro 21H2

**Comment by ssddanbrown** [comment]
Hi @carlossierra311,
Can you right-click the page in the browser > View source > then within the source search for `<!-- Styles and Fonts -->` near the top then provide the first two lines under that?

**Comment by carlossierra311** [comment]
Hi @ssddanbrown. Sure thing:

```
<link rel="stylesheet" href="http://localhost/dist/styles.css?version=v22.09">
<link rel="stylesheet" media="print" href="http://localhost/dist/print-styles.css?version=v22.09">
```

Thanks

**Comment by ssddanbrown** [comment]
@carlossierra311 Thanks, What do you see when you go direct 
to the URL `http://localhost/dist/styles.css?version=v22.09` ?

**Comment by carlossierra311** [comment]
Hi @ssddanbrown. This is what I see:
![image](https://user-images.githubusercontent.com/23511373/190021306-dba61630-d036-44d6-be77-e43e0b329e97.png)

Thanks.

**Comment by ssddanbrown** [comment]
@carlossierra311 Okay, thanks. Right file is being served but likely with the wrong content-type. Likely due to some webserver misconfiguration. Look for any nginx config that's forcing a content-type. If you're not sure, please share as much of your nginx config as possible.

**Comment by carlossierra311** [comment]
Hi @ssddanbrown. Thanks again!

Here is the full nginx.conf file content:

```
worker_processes  1;
error_log  logs/error.log;
events {
	worker_connections  1024;
}

http {
	sendfile			on;
	keepalive_timeout	65;

	server {
		listen 80;
		server_name localhost;

		root   "D:/Bookstack/bookstack/public";
		index  index.php index.html;

		location / {
			autoindex on;
			try_files $uri $uri/ /index.php?$query_string;
		}

		location ~ \.php$ {
			fastcgi_pass   127.0.0.1:9000;
			fastcgi_index  index.php;
			fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			include        fastcgi_params;
		}
	}
}

```

**Comment by ssddanbrown** [comment]
@carlossierra311 In a typical nginx setup a `mimes.types` file would be included within the `http` block as shown here:

https://www.nginx.com/resources/wiki/start/topics/examples/full/

Never used nginx on Windows, but did it come with such a file you can include?

**Comment by carlossierra311** [comment]
Hi @ssddanbrown. It came with such a file. I just included it within the http block, restarted Nginx, force-refreshed the page in Chrome, but the result was the same. 

![image](https://user-images.githubusercontent.com/23511373/190026396-82014fba-7845-45ee-ad29-679ab27b164d.jpeg)

Any other ideas?

Thanks!

**Comment by ssddanbrown** [comment]
Hi @carlossierra311,

Are you sure those lines are valid for your windows setup? Those added lines have unix style paths.
Also, you should not need the proxy or fastcgi lines for this, they may be confusing things.

I downloaded the windows files for nginx and the default provided `http` block contained the following line:

```nginx
    include       mime.types;
```

Might be worth removing the lines you added and add the above to your `http` block.

**Comment by carlossierra311** [comment]
Yes, that was it @ssddanbrown. Thank you so much for your time and help. 

In case anyone else comes here to try and solve this or get a working nginx.conf sample for Windows 10, here is the final file content: 
```
worker_processes  1;
error_log  logs/error.log;
events {
	worker_connections  1024;
}

http {
	include			mime.types;
	default_type		application/octet-stream;
	sendfile		on;
	keepalive_timeout	65;

	server {
		listen 80;
		server_name localhost;

		root   "D:/Bookstack/bookstack/public";
		index  index.php index.html;

		location / {
			autoindex on;
			try_files $uri $uri/ /index.php?$query_string;
		}

		location ~ \.php$ {
			fastcgi_pass		127.0.0.1:9000;
			fastcgi_index		index.php;
			fastcgi_param		SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			include			fastcgi_params;
		}
	}
}
```

**Comment by carlossierra311** [comment]
Yes, that was it @ssddanbrown. Thank you so much for your time and help. 

In case anyone else comes here to try and solve this or get a working nginx.conf sample for Windows 10, here is the final file content: 
```
worker_processes  1;
error_log  logs/error.log;
events {
	worker_connections  1024;
}

http {
	include    		mime.types;
	default_type 		application/octet-stream;
	sendfile			on;
	keepalive_timeout	65;

	server {
		listen 80;
		server_name localhost;

		root   "D:/Bookstack/bookstack/public";
		index  index.php index.html;

		location / {
			autoindex on;
			try_files $uri $uri/ /index.php?$query_string;
		}

		location ~ \.php$ {
			fastcgi_pass   127.0.0.1:9000;
			fastcgi_index  index.php;
			fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			include        fastcgi_params;
		}
	}
}
```

**Comment by ssddanbrown** [comment]
@carlossierra311 Good to hear that got things working. Will therefore close this off.

**Comment by KatMan-59** [comment]
For those using Linux boxes: Claude discovered this as the primary reason for the large icons and lack of HTML:

Root cause: the bookstack nginx server block has:
types {
    application/javascript js mjs;
}
In nginx, a types {} block declared inside a server context completely replaces the MIME table for that server — it doesn't merge with the
http-level include mime.types;. So within this server block, only .js/.mjs get a real content-type; every other extension (.css, .png,
.ico, .woff, etc.) falls back to default_type application/octet-stream. That's why CSS won't apply (browsers refuse to use stylesheets not
served as text/css) and icon fonts/images render as broken/oversized fallback icons.

This was likely already broken pre-upgrade too, but may have gone unnoticed if browser cache had the old correctly-typed CSS cached — the upgrade forced a fresh fetch that exposed it.

Fix: remove that redundant/destructive types {} block — mime.types already maps both js and mjs to application/javascript, so it's not
needed at all. The .mjs location block further down already sets default_type application/javascript; explicitly for pdfjs modules, which
is the correct, non-destructive way to do this.
