### ISSUE TITLE
Server Migration

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [BookStackApp/BookStack#3725]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

If we need to migrate our BookStack server, is it as simple as installing the web server, php, and database packages. Then cloning the project and importing the database and everything beneath `/var/www/bookstack` to the new server?

### Exact BookStack Version

22.09

### Hosting Environment

Current: Ubuntu 18.04.6
Proposed: CentOS 7

**Comment by ssddanbrown** [comment]
> If we need to migrate our BookStack server, is it as simple as installing the web server, php, and database packages. Then cloning the project and importing the database and everything beneath /var/www/bookstack to the new server?

Yeah, pretty much. Might have some permission fixing to do (and selinux playing to do if active), and webserver config tweaks to make. Some details on our [backup/restore page](https://www.bookstackapp.com/docs/admin/backup-restore/) may help. Of course, backup everything first for safety and ideally don't delete anything on the old system before ensuring the new system is working.

**Comment by FMCUSystemAdmins** [comment]
> Yeah, pretty much. Might have some permission fixing to do (and selinux playing to do if active), and webserver config tweaks to make. Some details on our [backup/restore page](https://www.bookstackapp.com/docs/admin/backup-restore/) may help. Of course, backup everything first for safety and ideally don't delete anything on the old system before ensuring the new system is working.

Ok, will give it a go. Thanks!

**Comment by FMCUSystemAdmins** [comment]
Things went relatively fine. Had to create SELinux policies and apply them and web server user permissions _after_ importing the application files. Then had a little snag on LDAPS authentication, ended up finding out two things that can make or break that functionality:

- `setsebool -P httpd_can_network_connect 1`
- `/etc/openldap/ldap.conf` (along with certificate placement)

All seems stable (knock on wood) and the backup/restore article was gold during this, thank you.
