### ISSUE TITLE
Open new language (el-gr)

### ISSUE THREAD

**Issue by Gr-DigiLady** [BookStackApp/BookStack#3732]
### Language to Add

Greek

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Thanks for offering to translate into greek.
I'll add the language right after the next patch release is published, which should be in the next few days.
Feel free to remind me if there's been no further update after 5 days from now.

**Comment by Gr-DigiLady** [comment]
> Thanks for offering to translate into greek. I'll add the language right after the next patch release is published, which should be in the next few days. Feel free to remind me if there's been no further update after 5 days from now.

If you want, I already edited the php files to 70% and can upload them somewhere

**Comment by ssddanbrown** [comment]
@Gr-DigiLady Thanks, You should be able to directly upload them into Crowdin once the language is added.
I don't want to add the language right now, since the addition will trigger a lot of extra changes to project files, but as above it'll be some point soon.

**Comment by ssddanbrown** [comment]
Hi @Gr-DigiLady,
I've now added Greek to Crowdin: https://crowdin.com/project/bookstack/el
As mentioned above, you should be able to directly upload the PHP files.

I'll therefore close this off but if you have any issues feel free to still comment here and I should still be notified.

**Comment by Gr-DigiLady** [comment]
Hi, the Greek translation has been completed.

**Comment by ssddanbrown** [comment]
@Gr-DigiLady Thank you for your efforts. I've assigned this to the next release as a reminder to add it into the language selector list, so should become available as of the next feature release.
