### ISSUE TITLE
Add "Read button" to attest that the user has read this page

### ISSUE THREAD

**Issue by maxime-robin-mis** [BookStackApp/BookStack#3736]
### Describe the feature you'd like

On all pages, add a button that all readers can click to attest to the reading

### Describe the benefits this would bring to existing BookStack users

We us BookStack like an internal Wiki for my company.

When an user read one page, we doesn't know if he has really reading

### Can the goal of this request already be achieved via other means?

With the comment but it is not practical

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @maxime-robin-mis, but this really comes across as a business specific process so I'm not really sure on the value of such as feature within BookStack itself, other than being a convenient location for your business process.
Even if we added this, you would still not know if the user has read the page, only that they say they have.

**Comment by ssddanbrown** [comment]
Due to the above, and since there's been no further discussion, I'm going to go ahead and close this off.
