### ISSUE TITLE
Prepared statement contains too many placeholders when updating book permissions

### ISSUE THREAD

**Issue by AbijeetP** [BookStackApp/BookStack#374]
### For Bug Reports

* BookStack Version: BookStack v0.15.2
* PHP Version: 5.6.27
* MySQL Version: MariaDB 10.0.15

While updating the Book level permissions for a book. We're getting this issue. Book has 15 Chapters and about 170 pages, and about 25 users assigned to a role with permission for this book.

##### Expected Behavior
Should not have errors while updating the book.

##### Actual Behavior
Getting Prepared statement contains too many placeholders when updating the error and the request is timing out.

Please find the attached log file. 
[error-log-join-permissions.txt](https://github.com/BookStackApp/BookStack/files/957442/error-log-join-permissions.txt)

You'll also notice that the request is timing out.

**Comment by ssddanbrown** [comment]
Hi @AbijeetP,
Apologies about this issue.
I think I know what needs updating to fix this but I'm a little limited on time right now. I'll ensure a bugfix release goes out this weekend to cover this bug.
