### ISSUE TITLE
Add Technical Info button

### ISSUE THREAD

**Issue by ferdieb** [BookStackApp/BookStack#3740]
### Describe the feature you'd like

Add another Action button for a page called "Technical Information".
When clicking the button, a pop-up(?) can provide the technical info of the complete bread crumb summary for the current displayed item (a page in this example): 

### Item  > Display name  > Slug   [Technical ID]
**Shelve**  > MyShelve  > /shelves/cpy-myshelve
**Book**  >  Book One  >  /books/book-one
**Chapter**  >Chapter 1  >  /books/book-one/chapter-1
**Page**  > My  Page  > /books/book-one/pages/my-page [209]

### Describe the benefits this would bring to existing BookStack users

This is for technical reference only when an editor etc wants to upload an attachment to a specific page, or make updates to an item via a script or even API where the technical ID of such item is required as part of the API or Node string parameters.

It cuts the requirement from the user side to first run a API/ cURL command to find the required ids for the items to be referenced, being a page, chapter, book etc.an

### Can the goal of this request already be achieved via other means?

Yes, if one has the knowledge to issue the commands. It also assumes the specific user does have the access to issue the commands correctly

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

In my case, I've wanted to upload a number of attachments to various pages using the node script to do so, but need page ids, correct slugs and would find it much quicker and easier to get to those pieces of data. I understand not everyone will need this, but thought it might provide some ease-of-use in a more direct user-friendly manner.

**Comment by ssddanbrown** [comment]
Hi @ferdieb,

Thanks for the suggestion.
From this sounds of this, this primarily would provide the ID for the page since the other listed details can be already be found fairly directly. 

The ID can already be found fairly quickly via the link/include tag popup as shown in the "Easily Grabbing the Syntax" section fo the following page: https://www.bookstackapp.com/docs/user/reusing-page-content/#easily-grabbing-the-syntax

The URL or include tag shown in this popup includes the page ID.

**Comment by ssddanbrown** [comment]
Due to the above, and since there's been no further discussion, I'm going to go ahead and close this off.
