### ISSUE TITLE
Add MATLAB code syntax highlighting

### ISSUE THREAD

**Issue by Babalion** [BookStackApp/BookStack#3744]
### Describe the feature you'd like

It would be nice if you could add MATLAB syntax highlighting to the supported languages for code blocks

### Describe the benefits this would bring to existing BookStack users

In scientific and industrial areas MATLAB is a popular software for calculations and simulations.
Therefore, lots of people would use and like this feature!

### Can the goal of this request already be achieved via other means?

No. The only option is to use i.e. LaTeX syntax highlighting but it does not match well.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Relevant codemirror mode: https://codemirror.net/5/mode/octave/index.html

**Comment by ssddanbrown** [comment]
Now added in 391fb2cc62f19e36d4cb27a204135e0a95189bdb, will be part of the next feature release.
