### ISSUE TITLE
Turn off comments for Guest user

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#3746]
### Describe the feature you'd like

At the moment, it seems the comments feature is set globally, regardless of their access permissions. I think it would be beneficial to be able to turn off the comments feature for guest users who are using public access as they are only supposed to have read-only access to content

### Describe the benefits this would bring to existing BookStack users

Maybe this is my use-case specific, but I think it would be advantageous to do this to avoid the addition of inappropriate comments from unregistered users

### Can the goal of this request already be achieved via other means?

Not that I am aware

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @techauthoruk 

> but I think it would be advantageous to do this to avoid the addition of inappropriate comments from unregistered users

The ability to add/edit/delete comments should already be configurable via the roles assigned to a user, so in this case the roles assigned to the guest user. By default on a fresh system, the guest user should not be able to add/edit/delete comments.
An example of this setup can be seen on our [demo setup](https://demo.bookstackapp.com), where you'd see you can't add comments as a guest.

**Comment by techauthoruk** [comment]
Oops! My bad...missed that totally. Closing this off to avoid further embarrassment!
