### ISSUE TITLE
Missing content after upgrade to v22.09.1

### ISSUE THREAD

**Issue by frank-embleton** [BookStackApp/BookStack#3747]
### Describe the Bug

Following an upgrade to 22.09.1 many of my shelves, books and pages are missing from the frontend.

Inspecting the database I can see that the content is still there.

### Steps to Reproduce

1. Upgrade to 22.09.1
2. Look for pages/books/shelves...

### Expected Behaviour

My pages to be visible?

### Exact BookStack Version

22.09.1

### PHP Version

7.4

### Hosting Environment

Ubuntu 20.04 installed using script

**Comment by frank-embleton** [comment]
Running these commands seems to fix it:
```
php artisan bookstack:regenerate-references
php artisan bookstack:regenerate-permissions
php artisan bookstack:regenerate-search
```

**Comment by ssddanbrown** [comment]
Hi @frank-embleton,
Good to hear you found a fix. I'd think it's specifically the `regenerate-permissions` command that fixed this.

Do you happen to know the version of BookStack you upgraded from?

**Comment by frank-embleton** [comment]
@ssddanbrown I'm not sure but I'm fairly sure I skipped the 22.07 releases so likely 22.06.?

**Comment by ssddanbrown** [comment]
For possible dev future reference, details and further info tracked in https://github.com/BookStackApp/BookStack/issues/3660#issuecomment-1260613841
