### ISSUE TITLE
2 Bookstack Instance on a Database

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#3748]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,
I plan to publish my internal Bookstack but would like to have separate accounts
so that the external Bookstack (internet) can log in the manual registered users but not the Ldap users, runs around the internal network
 
I have the following question:

is it possible to host 2 Bookstack instances on one database?

there is the possibility to use separate login options.
(example:
Container1(Internal Network) with ldap

Container2: (External) Non - Ldap and Manual Register

Or is there a bridge that can syncronize the existing shelves/books/pages to another bookstack

### Exact BookStack Version

22.09.1

### PHP Version

8

### Hosting Environment

Docker Container 
Docker Host Debian

**Comment by ssddanbrown** [comment]
Hi @reddexx,

> is it possible to host 2 Bookstack instances on one database?

It is technically possible, that you could point two BookStack instance to the same database, but this is not advised nor supported in any way. The logic and systems built into BookStack assume a single instance to a single database instance. It's highly likely you're encounter side affects and bugs in doing this.

> Or is there a bridge that can syncronize the existing shelves/books/pages to another bookstack

None that I know of, but you could always build something via the API, although something fairly feature complete may be quite complex to build depending on the depth you're attempting to achieve here.

**Comment by reddexx** [comment]
Would it be possible to syncronize Bookstack instances in the future?

I just think it's safer not to log in with the ldap from the internet.

**Comment by ssddanbrown** [comment]
> Would it be possible to syncronize Bookstack instances in the future?

That wouldn't really be a feature I'd look to support directly within-platform. Maybe we'd introduce some additional export options to ease portability to move closer to that, but full sync is a large request that I don't think would be worthwhile to maintain.

> I just think it's safer not to log in with the ldap from the internet.

Maybe you could use an intermediate auth platform? Something that can look-up to your LDAP system (maybe via an approved/whitelisted IP/connect) but could facilitate the additional audience you desire, then integrate that intermediate platform for auth with BookStack?

**Comment by ssddanbrown** [comment]
Since the above has been answered, and since there has been no further discussion, I'll go ahead and close this off.
