### ISSUE TITLE
File does not exist: /var/www/bookstack/public/login

### ISSUE THREAD

**Issue by wforumw** [BookStackApp/BookStack#3749]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have a fresh install, following https://www.bookstackapp.com/docs/admin/installation/, on a Debian Bullseye.
The first time I access my page via https://my-server, I got the 
`The requested URL was not found on this server`

In our apache logs we see
`File does not exist: /var/www/bookstack/public/login`

As a test I put a phpinfo.php file under /var/www/bookstack/public and I call it via https://my-server/phpinfo.php
I get the outputs information about PHP's configuration

Any idee what could be wrong?

Many thanks

### Exact BookStack Version

v22.09.1

### PHP Version

7.4

### Hosting Environment

Debian Bullseye

**Comment by ssddanbrown** [comment]
Is `mod_rewrite` enabled for the apache?

Commonly:

```bash
sudo a2enmod rewrite
sudo systemctl restart apache2.service
```

---

Also, just as a prior warning, we'll likely be dropping PHP7.4 support later this year, for a php8.0 minimum.

**Comment by wforumw** [comment]
Is enabled yes

**Comment by ssddanbrown** [comment]
@wforumw Okay. Could you share any apache configuration that's been setup for this install?

**Comment by wforumw** [comment]
We have only port 443 open.

[apache.txt](https://github.com/BookStackApp/BookStack/files/9638198/apache.txt)

**Comment by ssddanbrown** [comment]
@wforumw I noticed the first apache configuration you shared did not have the rewrite rules included.
Is that something you've now added afterwards? If so, does that change the scenario or errors received upon access?

**Comment by wforumw** [comment]
@ssddanbrown The first apache config was an old one. The latest one works now. I don't know why the same config did not work before. Many thanks for your help. Will close it.

**Comment by wforumw** [comment]
With the latest apache config attached it works now.
