### ISSUE TITLE
Login page is not being localized

### ISSUE THREAD

**Issue by sprnza** [BookStackApp/BookStack#375]
### For Bug Reports

* BookStack Version: 0.15.3
* PHP Version: 7.1.4
* MySQL Version: MariaDB 10.1.22

My user agent string:
```
Your Browser User Agent String is Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
Operating System:     Linux
Platform:    UNIX
Internet Browser:    Firefox 53.0
Beta Version:    No
Connection Speed:    1.19 Mbps
Restrictive Firewall:    No
Local Date/Time:    4/26/2017, 11:14:36 AM
Language:    Russian
System Language:    Not detectable with this browser
User Language:    ru
```

##### Expected Behavior
The Login page is localized accordingly to my User Agent String
##### Actual Behavior
The login page is not localized I have all strings translated in resources/lang/ru/auth.php though.

**Comment by ssddanbrown** [comment]
Hi @sprnza, I must admit, I did not think about translations on the login page.
After a quick look around it looks like it may be best to use the `Accept-Language` http header rather than the user agent string?

Either way, I'll mark this as a bug to be fixed.
