### ISSUE TITLE
Justifx for list not stored

### ISSUE THREAD

**Issue by Tagirijus** [BookStackApp/BookStack#3750]
### Describe the Bug

When I want to have justified text in a list point, it is possible to have in the WYSIWYG editor, but after saving the page, it is not stored.

### Steps to Reproduce

1. Create a new page.
2. Start a list.
3. Write long text, which gets line breaks. Maybe even create subpoints, which have line breaks.
4. Set the texts to be _justified_.
5. Save the page: no justify on the text.
6. Re-edit the page: no justify on the text neither.

### Expected Behaviour

I expect the text to have justify, when it seems to be possible in the WYSIWYG editor after all.

### Screenshots or Additional Context

Here is a GIF, which shows my steps and how it looks here:

![bug justify text in list](https://i.imgur.com/GGusqPi.gif)

### Browser Details

Chrome v105.0.5195.127 on Windows 10

### Exact BookStack Version

v22.09

### PHP Version

8.0.20

### Hosting Environment

Not quite sure; since it's a webspace. PHP info tells me something like this: _"Linux localhost 5.10.61 # 1 SMP Tue Aug 31 01:12:12 CEST 2021 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux"_ - does this help or do you need even more from the PHP info? Let me know, maybe I can send it to you in private _(since I am not sure how unsafe it would be here)_.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Tagirijus, this has been addressed within d933fe5dcec5189a235058ff7852d3af83bf893f and will be part of the next feature release.

**Comment by Tagirijus** [comment]
Thanks, Dan!
