### ISSUE TITLE
New install of BookStack is not creating database tables

### ISSUE THREAD

**Issue by Tom-RMS** [BookStackApp/BookStack#3752]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [x] I have searched GitHub for the issue.

### Describe the Scenario

I have seen a [GitHub issue](https://github.com/BookStackApp/BookStack/issues/3714) from a couple of weeks ago regarding issues with updating BookStack & databases, not sure if it's related

I've just installed BookStack using the manual instructions. I of course created a blank database with a user and added the details into the .env file. I can confirm the details are correct, as I can login with MySQL and create a table in the bookstack database without issue

However, when I go to connect to BookStack in the browser for the first time, it errors (500) and I get a big load of errors in the Laravel log about tables not being found. I've looked around to see if I need to manually create the tables or something, but no information on such, nor on this particular error

### Exact BookStack Version

v22.09.1

### Log Content

Truncated log as it's 4000 lines, The first few lines are the most important parts I'd assume

```
[2022-09-27 16:07:16] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.settings' doesn't exist (SQL: select * from `settings` where `setting_key` = app-public limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.settings' doesn't exist (SQL: select * from `settings` where `setting_key` = app-public limit 1) at /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
[stacktrace]
#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()
...[TRUNCATED]
#9 /var/www/BookStack/app/Settings/SettingService.php(245): Illuminate\\Database\\Eloquent\\Builder->first()
#10 /var/www/BookStack/app/Settings/SettingService.php(100): BookStack\\Settings\\SettingService->getSettingObjectByKey()
```

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04, Apache2, MariaDB on same server

**Comment by ssddanbrown** [comment]
Hi @RockFoundries,
Did you run step 9 of the manual install steps, to run `php artisan migrate`? If so, does running that emit an error?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
