### ISSUE TITLE
Port Forwarding URL Issue

### ISSUE THREAD

**Issue by ahmedwael216** [BookStackApp/BookStack#3754]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I installed book stack on a fresh Ubuntu server with the script.
on my local network it works flawlessly at 192.168.1.250.
But after setting up port forwarding on port 50000 and trying to go to http://{my router public IP}:50000 I find a connection timed out error message in the browser.

After a lot of digging with termshark and comparing capture files from connecting from inside the network and outside.
I found that when connecting from inside the local network the URI the base URI in the HTTP packets is "/login" and when connecting from outside the local network it's "/".
so I tried connecting to http://{my router public IP}:50000/login I reached bookstack but with the logos and images broken.
searching in the debugging webpage i found [this](https://www.bookstackapp.com/docs/admin/debugging/#no-styles-and-large-icons-on-access) but it just says I have a problem in my URL.

So..Any ideas??

### Exact BookStack Version

22.09

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04.1 installed using official script

**Comment by ssddanbrown** [comment]
Hi @ahmedwael216,
BookStack only supports being hosted on a single base URL at a time. This is what you set as the `APP_URL` in the `/var/www/bookstack/.env` file. I'm assuming your external accessing is redirecting you to your internal network address which is then not available.

**Comment by ahmedwael216** [comment]
ok this makes sense.
so is there a way to connect from outside my local network?
maybe a proxy server or something like that?

and thanks for your quick response.

**Comment by ssddanbrown** [comment]
@ahmedwael216 I'd probably just standardise on using the external address, and use that for when both in and out of your internal network. You'd need to update the `APP_URL` in the `/var/www/bookstack/.env file` for this.

If you had a hostname/domain set-up for use in the URL, you could maybe configure your local device/network DNS (depending on devices, usage and network setup) to point to the internal IP address instead to keep network traffic within-internal-network.

**Comment by ahmedwael216** [comment]
Ok thanks.
 I'll try it.

**Comment by ssddanbrown** [comment]
Since the original queries here have been answered, and since there's been no further discussion, I'll go ahead and close this off.
