### ISSUE TITLE
Including tags in search results within a book/chapter

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3755]
### Describe the feature you'd like

Currently, when you use the global search you will see what tags are attached to the particular search result.
![image](https://user-images.githubusercontent.com/53045430/192916260-1b5343cd-d144-434e-97f7-61b511dae9ab.png)

However, the same is not true when using the search within a book/chapter.
![image](https://user-images.githubusercontent.com/53045430/192916405-4ba1b7fc-750b-4646-a35d-c3c24210f317.png)

It would be a nice QoL if book/chapter searchs included the attached tags as the global search does.

### Describe the benefits this would bring to existing BookStack users

Consistent search experience. Quality of Life

### Can the goal of this request already be achieved via other means?

Nope

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @Mailstorm-ctrl, but I feel that #3407 already covers the fundamental request here so I'm going to close this off as a duplicate.
