### ISSUE TITLE
migrate from "standard" auth to saml2

### ISSUE THREAD

**Issue by badsmoke** [BookStackApp/BookStack#3756]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

hi,

is there a way to migrate from "standard" login to saml2?

i am building a SSO via authentik, now i would like to migrate all my users (almost 100) without deleting the old users and losing permissions

### Exact BookStack Version

v22.09.1

### PHP Version

8.8

### Hosting Environment

docker

**Comment by ssddanbrown** [comment]
Hi @badsmoke,
Yeah, It's possible to migrate. BookStack will need to know the unique IDs of the users, for the external authentication system, to be able to match them up.

It's probably best to watch through the "External Authentication ID Field" [part of my video here](https://youtu.be/szweYsAow88?t=889) to understand the field where this would be done, and its use.
As I touch on in that video, you could update this field via the database, or the REST API, in bulk if preferred.

**Comment by badsmoke** [comment]
thanks for the quick reply and the video, the first test worked.
