### ISSUE TITLE
collapsible block makes an extra line in each block when changing a page

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#3758]
### Describe the Bug

When changing a page with the content "collapsible block", 1 line per block is added each time the change is made. at some point you have 50 empty lines.

### Steps to Reproduce

1. Edit Page
2. Save Page
3. Edit Page

### Expected Behaviour

No blank lines

### Screenshots or Additional Context

First Edit:
![image](https://user-images.githubusercontent.com/6242840/193219971-749ccc55-e3c4-4e81-af12-977afd43379f.png)

On the View Mode:
![image](https://user-images.githubusercontent.com/6242840/193220219-fd86370a-c244-4d94-8009-aef88a67e9a2.png)

Second Edit:
![image](https://user-images.githubusercontent.com/6242840/193220438-92be14dd-41dd-4cfe-a868-59429e76719a.png)

After Save:
![image](https://user-images.githubusercontent.com/6242840/193220625-0056cd88-50d9-450f-9f5c-836b5caaf285.png)

### Exact BookStack Version

22.09.1

### PHP Version

8

### Hosting Environment

Docker-Container

**Comment by ssddanbrown** [comment]
Hi @reddexx,
Based upon your screenshots and my testing, I think this may only occur when using the "LanguageTool" browser extension. 
It seems to add in sections for the highlighting ability, which messes with the content format.
Not sure if it should be the responsibility of BookStack to handle the manipulation of external tools.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and assume this was an issue with LanguageTool and hence close this off. 
If there's an issue specifically within BookStack, I'd be happy to hear what that is otherwise I'm not looking to workaround manipulations performed via external tools.
