### ISSUE TITLE
Updating to v22.09.1 has meant various Books are missing - but some pages are still searchable and readable

### ISSUE THREAD

**Issue by pat-keeley-aurum** [BookStackApp/BookStack#3759]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Since updating to [v22.09.1] I have a weird issue: many of my books/chapters are not in the Shelf/Book view/missing entirely. However, some can be searched for within Bookstack, and then you are able to click through and read the page. Some are just missing completely (for example some recent pages created and seen with Audit Log).

I simply get a Page not found message when trying to get to the old pages via a link.

### Exact BookStack Version

22.09.1

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 20.4

**Comment by pat-keeley-aurum** [comment]
This can be closed - resolved via restoring SQL dbs and files. Many thanks.

**Comment by AndrewBucklin** [comment]
Same issue here. I tried restoring just the server (the files) and then just the database without success. Then I restored both to the same point (before the v22.09.1 update) and everything is back. I will hold off on doing the update until someone determines the root cause.

**Comment by ssddanbrown** [comment]
@AndrewBucklin Issue #3660 has a deeper dive of this issue, with methods of addressing and suggestion of possible cause.
