### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by sprnza** [BookStackApp/BookStack#376]
In a User's profile overview there is a "Created" column, where it's adding "s" to make "book", "chapter" and "page" plural which is not translation-friendly. I don't know how it works in other languages but in Russian there are two forms of a word to make it plural: if 2, 3, 4, 12, 13, 14, etc it's "книг" in other cases it's "книги". I believe it's quite difficult to program to have it displayed correctly considering that not all languages have this weird spelling. 
I suggest to make it unified like this:
```
Created:
Books: 
Chapters:
Pages:
```
Always plural for all languages. It will make it displayed incorrectly if it's 1 for English and 2, 3, 4, etc for Russian, but it will be better than now in all non English languages.

**Comment by ssddanbrown** [comment]
Hi @sprnza, Apologies for my very late reply. I've now implemented a different solution for this which allows pluralization to be set manually for each language.

Please see #417 and #485 for further details on the implementation. 

I will therefore close this issue but feel free to comment further or open a new issue if you have further questions or require assistance.
