### ISSUE TITLE
unable to remove some option from search if applied

### ISSUE THREAD

**Issue by someplace53** [BookStackApp/BookStack#3762]
### Describe the Bug

Just something minor:

If I add one or both of the search options "Created by me" or "Updated by me" to the search, I am not able to remove said option from the search via the checkboxes.

I thought there where more options which had similar problems, but I am unable to reproduce that (maybe have a look at it, if your on it)

### Steps to Reproduce

1. login
2. search for something
3. click on search options "Created by me" to check the box and click "Update Search"
4. again click on the search options "Created by me" to uncheck the box and click "Update Search"
5. and see that the checkbox is marked again (and the search result contains only entries which I created)

### Expected Behaviour

I would expect, that if I uncheck the box, the checkbox should not be checked again

### Browser Details

Firefox 105.0 (64 bit) Linux

### Exact BookStack Version

v22.09.1

### PHP Version

7.4.19

### Hosting Environment

RHEL 8 installed via git and than composer

**Comment by ssddanbrown** [comment]
Thanks for reporting @someplace53.
Can confirm this from testing on our demo instance.
Have assigned to the next feature release.
