### ISSUE TITLE
LDAPS, add client TLS cert/key ability for authentication (required for Google Workspace LDAP)

### ISSUE THREAD

**Issue by BloodyIron** [BookStackApp/BookStack#3763]
### Describe the feature you'd like

So far as I can tell, LDAP within Bookstack does not have the ability to use TLS certificate + key pair for authentication (as client, not server certificates) when connecting to an LDAPS server. This is a problem as the Google Workspace service "Secure LDAP" (which is their only LDAP service) _requires_ the client always authenticate (at a minimum) with a client TLS Certificate + Key pair.

There is the added _option_ of _also_ authenticating with a username + password to Google Workspace Secure LDAP, however every method (even the stunnel alternative method) always requires the use of TLS Certificate + Key for client authentication.

As such, I would like Bookstack to have this capability added (and naturally documentation updated to cover this too).

### Describe the benefits this would bring to existing BookStack users

Currently Bookstack is completely incapable (so far as I can tell) from interfacing with Google Workspace authentication domains via LDAP, as the only LDAP service Google Workspace offers requires this capability.

I care about LDAP over SAML because I want delicious user avatar/image sync into Bookstack, which is only currently possible with LDAP, and not SAML (I think this is a Google Workspace limitation?).

### Can the goal of this request already be achieved via other means?

Not that I can tell.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

This generally is already an LDAP feature, and I suspect Bookstack just needs a slight extension to add this. But this effort-estimation is just speculation.

**Comment by BloodyIron** [comment]
So this situation occurred to me when I've been doing manual ldapsearch CLI testing, and getting results was very easy just using the certificates for authentication.

In my attempts to use Bookstack with Google Workspace Secure LDAP, the debug output for Bookstack is "ldap_search(): Search: Insufficient access". Initially I thought the Secure LDAP "server"/user (or whatever) didn't have access to search the domain, however looking closer that my Bookstack LDAP connection configuration doesn't talk about client cert/key at all (even though I've actually created a credential within kubernetes, as I'm using docker, containing the client cert/key, and mounted it in the running container/pod), it occurred to me the "Insufficient access" is being presented because the LDAP connection is effectively being refused as the cert/key isn't being presented for client authentication at all!

Really hoping this can get baked into mainline, as LDAP just straight up won't work for us at all otherwise. :(

**Comment by ssddanbrown** [comment]
Hi @BloodyIron,
Yeah, BookStack does not use or support custom client certifications to be defined for LDAP TLS.
It looks like it may be possible to support after some additional `LDAP_OPT_X_TLS_CERTFILE` and `LDAP_OPT_X_TLS_KEYFILE` options were added to PHP7.1, but it's going to be an annoying thing to test and I prefer not to expand the scope of our auth systems where possible, without significant benefit or need.

I saw Google provides a proxy tunnel for systems that don't support client certificates:
https://support.google.com/a/answer/9089736#stunnel
("Optional: Use stunnel as a proxy" section).
That looks fairly reasonable as an alternate way to gain support, have you attempted usage of this at all?

**Comment by BloodyIron** [comment]
@ssddanbrown well we're using the docker implementation of Bookstack so doing the stunnel aspect of it would be really not straightforward, since I don't believe it is included in the docker image.

**Comment by ssddanbrown** [comment]
https://github.com/dweomer/dockerfiles-stunnel looks fairly maintained and simple.
Not a massive amount of documentation, but the [script it uses](https://github.com/dweomer/dockerfiles-stunnel/blob/master/stunnel.sh) seems to make clear the expected volume mount paths for passing certs

**Comment by ssddanbrown** [comment]
Since there's been no further discussion, and since this is a low-demand auth feature with possible workaround, I'm going to close this off.
