### ISSUE TITLE
Incorrect tables

### ISSUE THREAD

**Issue by Kol8bok** [BookStackApp/BookStack#3768]
### Describe the feature you'd like

Hi!
When adding a wide table to a page, for example, with Microsoft EXCEL, it does not display it correctly.
Is it possible to make it so that it would be displayed more correctly and more beautifully?

So that the white background of the page would stretch to the right and the "Actions" menu would collapse, so that all this would not be superimposed visually on the table itself.

[https://transfiles.ru/qwc4i](url) - sample photo

### Describe the benefits this would bring to existing BookStack users

correct performance of the resource

### Can the goal of this request already be achieved via other means?

yes 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for requesting @Kol8bok but I'm going to close this off as a duplicate due to overlap with existing issues #1652, #2126 and #2381
