### ISSUE TITLE
Pointer link in table cell been cover by other cell

### ISSUE THREAD

**Issue by leofcshen** [BookStackApp/BookStack#3774]
### Describe the Bug

I try to set a p tag with id in a table cell like below for reuse this cell content.
I can reuse this table cell successful In other content with {{@page_id#content_id}} .
But when I select the cell, the pop-up pointer link is covered by up cell.

### Steps to Reproduce

 ```html
<tr style="height: 30.1094px;">
<td style="height: 30.1094px;">test</td>
<td style="height: 30.1094px;">
<p id="bkmrk-1"><code>F11</code></p>
</td>
<td style="height: 30.1094px;">comment</td>
</tr>
```
1.Select cell without setting p tag and id, pop-up pointer link normally (the default reference all table)
![擷取](https://user-images.githubusercontent.com/74611374/194809466-9b0fa699-a01f-4b75-ab2d-9935ec7c39d5.PNG)

2.Select cell with setting p tag and id, pop-up pointer link was covered by up cell.
![擷取](https://user-images.githubusercontent.com/74611374/194809781-81c5434a-4f08-4a56-84f4-7f498258b999.PNG)
![螢幕擷取畫面 2022-10-10 143911 PNG](https://user-images.githubusercontent.com/74611374/194810068-6b46f72a-c0a8-4ac5-834a-4b63b070c52d.jpg)

### Expected Behaviour

pop-up pointer link normally in table cell

### Browser Details

Chrome 105.0.5195.127(64-bit) on Windows 10

### Exact BookStack Version

v22.07.3

### Hosting Environment

docker container

**Comment by ssddanbrown** [comment]
Thanks for reporting @leofcshen, and thanks for providing clear replication guidance. 
Seemed to be something that was not an issue on Firefox but could replicate as described on chrome. 
This has been addressed in d084f225a0e1dd52e11e3fd96bdce59703a71eff and will be part of the next feature release.
