### ISSUE TITLE
Restrict logins by IP or allow local IP login only

### ISSUE THREAD

**Issue by nekonoire** [BookStackApp/BookStack#3777]
### Describe the feature you'd like

Hello! I want to start off by saying that BookStack has been absolutely fantastic for my documentation use so far, both for my personal use and for my company's internal team. 

One feature I would like to request is the ability to restrict logins by IP, or only allow local IP logins. The use case here is that I have a public BookStack Instance that have Public Access enabled, for quickly sharing documentations with other people. From public url, the BookStack login page is accessible. If BookStack can restrict the login by IP, it would add additional security by only allowing local logins. 

### Describe the benefits this would bring to existing BookStack users

If BookStack can restrict the login by IP, it would add additional security by only allowing local logins. This way, any attempts to login from the public url can be automatically denied. 

### Can the goal of this request already be achieved via other means?

Not sure. Perhaps a workaround can be denying the /login page all together within Apache/NGINX for the public url? 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @nekonoire,

I don't really want to complicate our auth systems much further without significant need, so I would not really look to build such functionality into the core system. As you've suggested, you could add these kind of protections via the webserver as one option. 
Another is to use our [Logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) to extend BookStack and set this functionality.

The below enables protection of the login and password-reset endpoints based on the IPs in the `$allowedIps` array. 
Note: This is essentially an unsupported functionality addition. There may be logical holes in usage and this could break upon future updates.

### Setup

You should already have a `themes/` folder within your BookStack directory.
Within this create a `custom` directory, then within that create a `functions.php` file with the code from the below `themes/custom/functions.php` section.

Within your BookStack `.env` file, add the below line to set your theme folder:

```bash
APP_THEME=custom
```

Within your `themes/custom/functions.php` file, You can edit the IP-address allowed at around line 11. This functions.php file is fully commented to describe what each section does.

Be sure to test this to ensure it has the functionality you need/expect. 

### `themes/custom/functions.php` file

```php
<?php

use BookStack\Facades\Theme;
use BookStack\Theming\ThemeEvents;
use Illuminate\Http\Request;

// Register a new web-middleware-before hook
Theme::listen(ThemeEvents::WEB_MIDDLEWARE_BEFORE, function (Request $request) {

    // A list of IP addresses that are allowed to use the login endpoints.
    $allowedIps = [
        '127.0.0.1',
    ];

    // The endpoint prefixes to protect.
    $protectedEndpointPrefixes = [
        'login',
        'password',
    ];

    // Gather the path and IP of the current request
    $path = $request->path();
    $ip = $request->ip();

    // Redirect to home if we're requesting a protected endpoint and the user
    // IP is not within our allowed list.
    foreach ($protectedEndpointPrefixes as $endpointPrefix) {
        if (strpos($path, $endpointPrefix) === 0 && !in_array($ip, $allowedIps)) {
            return redirect('/');
        }
    }

    // Otherwise return null to tell BookStack to continue its normal behaviour.
    return null;
});
```

**Comment by nekonoire** [comment]
Thank you! I tested the above code on my Bookstack instance, and it worked. 

Any attempts to navigate to the /login page from a non-allowed IP is automatically redirected to the home page instead. 

One thing I notice is that the allowedIPs portion of the code only accepts single IP address. Would it be possible to have the allowedIP code section to accept a subnet range instead, such as 192.168.1.0/24?

**Comment by ssddanbrown** [comment]
@nekonoire I don't really want to dive into working out IP subnet range math, but here's a tweaked version that will prefix-match against the user IP:

```php
<?php

use BookStack\Facades\Theme;
use BookStack\Theming\ThemeEvents;
use Illuminate\Http\Request;

// Register a new web-middleware-before hook
Theme::listen(ThemeEvents::WEB_MIDDLEWARE_BEFORE, function (Request $request) {

    // A list of IP addresses that are allowed to use the login endpoints.
    // Can be IP prefixes since match just checks the user IP starts with
    // one of the below values.
    $allowedIps = [
        '127.0.0.',
    ];

    // The endpoint prefixes to protect.
    $protectedEndpointPrefixes = [
        'login',
        'password',
    ];

    // Gather the path and IP of the current request.
    $path = $request->path();
    $ip = $request->ip();
    $protectedPath = false;
    $approvedUserIp = false;

    // Check if the current path starts with one of the defined protected endpoints.
    foreach ($protectedEndpointPrefixes as $endpointPrefix) {
        if (strpos($path, $endpointPrefix) === 0) {
            $protectedPath = true;
        }
    }

    // Check if the current user IP is approved.
    foreach ($allowedIps as $allowedIp) {
        if (strpos($ip, $allowedIp) === 0) {
            $approvedUserIp = true;
        }
    }

    // Redirect to home if we're at a protected path and the user is not approved.
    if ($protectedPath && !$approvedUserIp) {
        return redirect('/');
    }

    // Otherwise return null to tell BookStack to continue its normal behaviour.
    return null;
});
```

**Comment by nekonoire** [comment]
Ah got it! Thank you so much! 

Sort of on topic, for the login and password reset page, what's the direct path to those page on a localhost? I'm testing around to see if I can utilize NGINX to do allow IPs. Something like the following: 

`  location /login {
    allow 192.168.1.0/24;
    deny all;
  }`

**Comment by ssddanbrown** [comment]
All current routes are listed [in this file](https://github.com/BookStackApp/BookStack/blob/release/routes/web.php), Auth routes are towards the bottom. I think you can also run `php artisan route:list` within the bookstack directory to get a list for your instance.

In the logic I used above, I felt that prefix-matching on `/password` and `/login` covers most use cases with standard auth.

Thanks for the sponsorship by the way, Means a lot!

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up, and since the workaround has been provided for the original request, I'll go ahead and close this off.
