### ISSUE TITLE
Add failover non-LDAP administrative account

### ISSUE THREAD

**Issue by jsarnowski96** [BookStackApp/BookStack#3778]
### Describe the feature you'd like

Allow for creation of non-LDAP accounts when currently used authentication system is LDAP.

### Describe the benefits this would bring to existing BookStack users

Since BookStack by default allows for only a single authentication system to be active at a given time, in case of AD controller's failure and/or other emergent issue potentially coming from future BS patching, you're basically cut-off from the service. Changing configuration in .env file won't help because there's no basic auth account you could use to regain access to BookStack resources.

### Can the goal of this request already be achieved via other means?

Not to my knowledge, apart from completely abandoning non-basic auth systems and/or manually modyfing database records.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @jsarnowski96,

> Changing configuration in .env file won't help because there's no basic auth account you could use to regain access to BookStack resources.

You can use any account you setup before previously changing the `AUTH_METHOD` to ldap, or you can use our ["Create an Admin User" command](https://www.bookstackapp.com/docs/admin/commands/#create-an-admin-user) to create a new admin user login.

**Comment by jsarnowski96** [comment]
> Hi @jsarnowski96,
> 
> > Changing configuration in .env file won't help because there's no basic auth account you could use to regain access to BookStack resources.
> 
> You can use any account you setup before previously changing the `AUTH_METHOD` to ldap, or you can use our ["Create an Admin User" command](https://www.bookstackapp.com/docs/admin/commands/#create-an-admin-user) to create a new admin user login.

thanks, fair enough

**Comment by ssddanbrown** [comment]
Will therefore close this off
