### ISSUE TITLE
New markdown editor breaks anchor tags

### ISSUE THREAD

**Issue by lxtv** [BookStackApp/BookStack#378]
### For Bug Reports

* BookStack Version: v0.16
* PHP Version: PHP 7.0.15-0ubuntu0.16.04.4 
* MySQL Version: mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

##### Expected Behavior

On previous versions of Bookstack, using the Markdown editor, I was able to use sparing amounts of HTML when needed. Thus far, it had only been anchor tags, such as ```<a name="blah" />```. Using these on long documents, I was able to link to the tags to allow the reader to jump among topics.

##### Actual Behavior

According to the release notes, v0.16 switched markdown editors to Markdown-IT. Unfortunately this does not appear to support any HTML tags. Any time I edit a page with anchor tags, or create a new page, the HTML code is displayed as-is.

![screenshot 2017-04-27 17 45 20](https://cloud.githubusercontent.com/assets/8223837/25505777/5d345d7c-2b71-11e7-9152-955bad036ef4.jpg)

If there's a workaround, or if you can be persuaded to switch back or offer the option of choosing our markdown flavor, I'd greatly appreciate it.

**Comment by ssddanbrown** [comment]
Hi @lxtv,
My apologies, I did not realise that `markdown-it` had that behavior by default.

Looking at the documentation for `markdown-it`, HTML can easily be enabled. I've marked this as a priority bug to be part of a bug-fix release this coming weekend.

**Comment by lxtv** [comment]
Oh great, thanks for the quick response. In the meantime, I did find a workaround: copying the tags from the sidebar navigation. This works because all my tags are associated with headers. But it'll be good to have the flexibility of HTML back.

**Comment by yoginth** [comment]
but still **html** is **_not working_** after enabling it :cry:
