### ISSUE TITLE
BookStack version via API?

### ISSUE THREAD

**Issue by Bartiff** [BookStackApp/BookStack#3781]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I'd like to retrieve the version of my BookStack instance through the API.
Is it possible?

### Exact BookStack Version

v22.09.1

### Hosting Environment

Ubuntu

**Comment by ssddanbrown** [comment]
Hi @Bartiff, Please see https://github.com/BookStackApp/BookStack/issues/3343 for a previous discussion regarding this.

**Comment by Bartiff** [comment]
Ok sorry for that...
