### ISSUE TITLE
Add a way to set an obsolete status to an page

### ISSUE THREAD

**Issue by JeanDavidDaviet** [BookStackApp/BookStack#3782]
### Describe the feature you'd like

Where I work we've had a Bookstack for 4 years.
Some of the pages created are now obsolete but we still have new people being recruited.
I think it would be nice to have a way to easily toggle a state on a page to decide if this page is obsolete or not.
The infos may still be nice to have which is why the page is not deleted but the user may need to know the infos may not be up to date.

### Describe the benefits this would bring to existing BookStack users

For old technical documentations, it would be easier to know if the content is still good to use.

### Can the goal of this request already be achieved via other means?

I think if can be created via customisation of the theme, but I don't know enough about BookStack to know if it's possible.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @JeanDavidDaviet,
I avoid adding specific controls/options that don't add much value in themselves, instead only serving as additional metadata.

Are you not able to use tags for this? Or even just the addition of a callout/warning message to such pages to advise they are obsolete.
