### ISSUE TITLE
User management scales weirdly depending on security groups

### ISSUE THREAD

**Issue by Sys-Monitor** [BookStackApp/BookStack#3787]
### Describe the Bug

If you have lots of security groups, if someone have "too many" of them, the interface for user management scales horribly and gets down to 5 characters per column.
14 groups (~3-15 characters in length):
![image](https://user-images.githubusercontent.com/106233546/196624053-e83d902d-4536-4ecc-9aca-841f2c44a15a.png)

More groups:
![image](https://user-images.githubusercontent.com/106233546/196624119-79b04aed-7d35-4af2-8421-f777bbf452df.png)

### Steps to Reproduce

1. Make several security groups.
2. Have a user having several of them
3. Go into Users

### Expected Behaviour

Increase the height of the user entry (specifically **##td:nth-of-type(3)** ) instead of width so it doesn't have to squish the other columns to be unreadable.
That or have the **##.content-wrap.card** to scale at least to the size of the Audit Log which is way wider so it doesn't have to squish the columns so much. There's quite the wasted amount of space on specifically the Users tab:
![image](https://user-images.githubusercontent.com/106233546/196626891-9dc6abdc-415d-47fe-897c-1b4993784b42.png)

### Browser Details

Firefox (latest), Chrome (latest) - Windows 11

### Exact BookStack Version

v22.09.1

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04.1 LTS, installation script

**Comment by ssddanbrown** [comment]
Thanks for reporting @AH-SWG, Plan to change the structure of such lists in the future, but for now have [applied a quick patch](f9c0edbd0ce10440ed4f86ea6448c358dd017e70) to fix column sizes. Will be part of the next feature release.
