### ISSUE TITLE
How Bookstack introduced drawio ?

### ISSUE THREAD

**Issue by Rick1516** [BookStackApp/BookStack#3788]
### Describe the feature you'd like

I want to add some drawio-like functionality, so I want to know how drawio is added to bookstack, maybe I can find some way from it.

### Describe the benefits this would bring to existing BookStack users

Reference for those who want to add features.

### Can the goal of this request already be achieved via other means?

No, but I have seen similar questions, unfortunately not what I want.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

![image](https://user-images.githubusercontent.com/116056436/196640006-f8556e82-e11e-4395-835e-5dc93432e985.png)

**Comment by ssddanbrown** [comment]
Hi @Rick1516,
Some key points of the logic can be found here:

- [JavaScript handling](https://github.com/BookStackApp/BookStack/blob/d76bbb29546692732aea33ca5507df886ef6cb1b/resources/js/services/drawio.js)
- [WYSWIYG Editor integration](https://github.com/BookStackApp/BookStack/blob/b698bb0e07689feeb7b80e958bfffa5cf4602423/resources/js/wysiwyg/plugin-drawio.js)
- [Back-end handling](https://github.com/BookStackApp/BookStack/blob/06b500984250f75b98f38a8f25ac953cb45aeee4/app/Http/Controllers/Images/DrawioImageController.php)

**Comment by Rick1516** [comment]
@ssddanbrown,
So can I bring in other kits in the same way?

**Comment by ssddanbrown** [comment]
@Rick1516 You could I guess but you'd need knowledge of PHP and JavaScript, and it really depends on how the other systems integrate, they may not have similar APIs. You'd also be editing core BookStack files, so may end up incompatible with future BookStack versions.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion here I'm going to close this off.
