### ISSUE TITLE
Redirect to logotm-hhd.png image after logon

### ISSUE THREAD

**Issue by RikyTres** [BookStackApp/BookStack#3795]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [x] I have searched GitHub for the issue.

### Describe the Scenario

After complete the login I'm redirect to a specific url `/uploads/images/system/2022-07/logotm-hhd.png`.
This happen for every user, even new user.

Not sure if this can be related, but before this issue I changed the `SOTRAGE_TYPE` from `local` to `local_secure`.
Nothing on my .env file is releted to this url
No error logged in the error files.

This is my bookstack.conf

```
<VirtualHost *:80>
  ServerName bookstackapp.tresoldi.loc

  ServerAdmin webmaster@localhost
  DocumentRoot /var/www/bookstack/public/

  <Directory /var/www/bookstack/public/>
      Options -Indexes +FollowSymLinks
      AllowOverride None
      Require all granted
      <IfModule mod_rewrite.c>
          <IfModule mod_negotiation.c>
              Options -MultiViews -Indexes
          </IfModule>

          RewriteEngine On

          # Handle Authorization Header
          RewriteCond %{HTTP:Authorization} .
          RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

          # Redirect Trailing Slashes If Not A Folder...
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteCond %{REQUEST_URI} (.+)/$
          RewriteRule ^ %1 [L,R=301]

          # Handle Front Controller...
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteRule ^ index.php [L]
      </IfModule>
  </Directory>

  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

### Exact BookStack Version

v22.09.1

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04 LTS

**Comment by ssddanbrown** [comment]
Hi @RikyTres,
Please re-upload/re-configure the application logo setting within BookStack, then test the same flow within a fresh/private/incognito browser window to see if this issue remains.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.

**Comment by RikyTres** [comment]
I'm so sorry, I forgot to give a feedback.
It worked.
I removed the logo, saved and re-uploaded it... and then the issue disappeared...
