### ISSUE TITLE
Database error after update to v22.10.1

### ISSUE THREAD

**Issue by InoryS** [BookStackApp/BookStack#3799]
### Describe the Bug

Update from v22.09 to v22.10.1
implement
```
git pull origin release
composer install --no-dev
php artisan migrate
php artisan cache:clear
php artisan config:clear
php artisan view:clear
```

Then got the 500 error.

### Steps to Reproduce

1.cd website directory
2.git pull origin release
3.composer install --no-dev
4.php artisan migrate
5.php artisan cache:clear
6.php artisan config:clear
7.php artisan view:clear
8.get 500 error

### Expected Behaviour

normal access to the website

### Screenshots or Additional Context

error log: 
<details><summary>CLICK ME</summary>

```
2022/10/22 17:55:16 [error] 1241273#0: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'view' in 'where clause' in "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 "web_dir"/vendor/laravel/framework/src/Illuminate/Databa...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'view' in 'where clause' in "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 "web_dir"/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 "web_dir"/vendor/laravel/framework/src/Illuminate/Databa" while reading resp
```

</details>

### Exact BookStack Version

v22.09 to v22.10.1

### PHP Version

PHP 8.1.7

### Hosting Environment

RHEL 8 
6.0.0-1.el8.elrepo.x86_64
nginx version: nginx/1.23.1

**Comment by ssddanbrown** [comment]
Hi @InoryS,
I couldn't see any running of the `php artisan migrate` step in the command output. Are you sure this step was ran?
If so, please confirm the current output of running that update step.

**Comment by InoryS** [comment]
> Hi @InoryS, I couldn't see any running of the `php artisan migrate` step in the command output. Are you sure this step was ran? If so, please confirm the current output of running that update step.

Thanks for the quick reply, I'm sorry for any inconvenience.
I'm still editing the github code block, so you did not see update log.
I copied three pieces of updated code directly from the BookStack blog and pasted directly into ssh, and it seems that somehow `php artisan migrate is missing`.
I re-executed `php artisan migrate` which successfully solved the problem.
