### ISSUE TITLE
ACME certificates

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#3802]
### Describe the feature you'd like

Hi, I think it would be great if you could implement the generation and renewal of Let's Encrypt certificates from within the UI, allowing easy implementation of SSL. I know that book stack is generally accessed from inside a LAN, but for me, this would be nice to have. 

https://letsencrypt.org/docs/client-options/

### Describe the benefits this would bring to existing BookStack users

Allow easy configuration of HTTPS access to bookstack. 

### Can the goal of this request already be achieved via other means?

Yes, you can do this manually, but it would be nice to have access in the UI.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

I have been using the ACME integration in proxmox and pfsence and it works great!

**Comment by ssddanbrown** [comment]
Hi @ScottyP86,
Thanks for the request but I don't really see SSL handling being within the responsibility of the core BookStack project here, It's really something that's typically handled at the webserver layer. 
I don't think supporting and maintaining SSL handling within BookStack, especially with the variety of configurations & environments it can be used in, would be worth it for what is commonly built into layers above BookStack, or for what is commonly a one-time-run of a few commands nowadays.

**Comment by ghost** [comment]
Thanks for your response, totally understand.
