### ISSUE TITLE
Merged cells in tables using WYSIWYG edtior

### ISSUE THREAD

**Issue by MapManagement** [BookStackApp/BookStack#3805]
### Describe the feature you'd like

As far as I know there is no possiblity to merge cells of tables within the WYSIWYG editor. The following picture shows a small example I created using HTML. You can achieve the exact same result in Bookstack but only by using the Markdown editor. I would like to merge cells using the WYSIWYG editor, if possible.

![image](https://user-images.githubusercontent.com/49588429/197545147-b661cdc5-a340-4d62-be02-e253e3d7ffc4.png)

### Describe the benefits this would bring to existing BookStack users

Users wouldn't need to change the editor when creating more complex tables that use merged cells.

### Can the goal of this request already be achieved via other means?

Yes, you can create such tables using the Markdown editor.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @MapManagement,
You can merge cells by doing the following:

1. Select the cells you want to merge via click and drag.
2. Click on the table icon in the toolbar.
3. Under "Cell" options within the dropdown, click "Merge Cells"

**Comment by MapManagement** [comment]
Oh, my bad then, However, I couldn't find anything about it. Thank you very much.
Issue closed :)
