### ISSUE TITLE
Better Revision View

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [BookStackApp/BookStack#3807]
### Describe the feature you'd like

With the new permission view for shelves & books I think the revision views can get a little make over too. Currently, when you click on "Changes" you can only see what the difference is from the version before the version you clicked changes on.

I think it would be nice if this was more obvious to the user (header information that says Comparing version 2 against 1) and if you could also select which versions are compared. IE: You can compare the difference between version 5 and 2.

I understand that some in scenarios not all changes will be picked up (for example, a sentence existed in versions 3 and 4 but was deleted in 5) but I still think being able to view the changes between 2 versions that aren't adjacent to each other would be beneficial to some degree.

### Describe the benefits this would bring to existing BookStack users

Better revision experience.

### Can the goal of this request already be achieved via other means?

Not that I know of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @Mailstorm-ctrl, but I feel the fundamental request here is already covered by #1400?

**Comment by Mailstorm-ctrl** [comment]
> 

If only I searched for "versions" instead of revisions...I would of found that. My bad
