### ISSUE TITLE
Add Dart/Flutter support to the code editor

### ISSUE THREAD

**Issue by badd1976** [BookStackApp/BookStack#3808]
### Describe the feature you'd like

Thanks for creating this excellent wiki system. Our team has tried several wiki systems and now the searching finally comes to an end. The only thing lacking to reach 100% perfectness is the support of dart/fuller language in the code editor. That's what we use for app development and hope you can consider including this in the near future. Thanks.

### Describe the benefits this would bring to existing BookStack users

All the dart/flutter developers can enjoy using BookStack more.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks @badd1976.

Looks like there's a [built-in dart](https://codemirror.net/5/mode/dart/index.html) syntax, so should be an easy add. Have assigned for next feature release.

**Comment by ssddanbrown** [comment]
Now added in 5fd1c07c9d8da8b60373463a7b558f8ef4d20490, Will be part of the next feature release.
