### ISSUE TITLE
number of pages on a books view

### ISSUE THREAD

**Issue by ufukayyildiz** [BookStackApp/BookStack#3810]
### Attempted Debugging

- [x] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

Is there a way to set maximum page  on book views.

Example 20 page on a view, if total page quantity is >20 in a book should go to next book page ( book view ).

thanks

### Exact BookStack Version

22.10.1

### Hosting Environment

none

**Comment by ssddanbrown** [comment]
Hi @ufukayyildiz,

> Is there a way to set maximum page on book views.

No, there is no such option. Books always list their entire contents.

**Comment by ssddanbrown** [comment]
This this question was answered I'll go ahead and close this off.
