### ISSUE TITLE
Logon Message (for those of us with pesky lawyers!)

### ISSUE THREAD

**Issue by AutoJunkie79** [BookStackApp/BookStack#3811]
### Describe the feature you'd like

Add an option to add a logon message on the login page. If the option is enabled and message present then display, otherwise keep the clean look of the original! Bonus if the message can display an HTML link safely, otherwise text-only will still make the lawyers happy! 😬

![Sample Logon Page Message](https://user-images.githubusercontent.com/25411186/198039823-8b237807-1b34-40b3-a04e-d8eb0d424ff9.png)

### Describe the benefits this would bring to existing BookStack users

Some of us work for organizations that have big targets painted on our backs. Thus, we have to comply with certain security policies that are supposed to help us dodge bullets. Staying in compliance keeps our lawyer friends and CISO's happy so we get to spread the word on how BookStack is not only a work of art but also a great knowledge management tool.

This feature could also be used for announcements from the admin, such as "Bookstack upgrade tonight at 9pm EST, make a xerox copy of your pages if you need them!" However, this may make more sense as an entirely separate feature as well, perhaps only displayed once a user has logged in.

### Can the goal of this request already be achieved via other means?

I suppose I could try and edit the logon page directly, but I prefer to stay within the confines of editable areas the original author has surfaced so that the feature can be maintained long term (e.g. after my staff runs me over with a bus). 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Related to #608.

Hi @AutoJunkie79,
If handy with code, you can customize any view in the system using our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md). That page has a video guide on using this system to customize views. The login view can be found at `views/auth/login.blade.php` [as seen here](https://github.com/BookStackApp/BookStack/blob/release/resources/views/auth/login.blade.php), so a `auth/login.blade.php` file in your theme folder would override that.

**Comment by AutoJunkie79** [comment]
Nice - I will give this a shot. Not super handy with code, but it's not all Greek to me either. If I can figure this out then I can help solve another issue plaguing my users - they equate the "Save Page" button to saving a draft. I've pointed them to the draft options menu in the middle, but I guess they are just drawn to it for some reason. I think changing the text to "Publish Page" might help them think before they click! Thanks again @ssddanbrown!

**Comment by AutoJunkie79** [comment]
Visual Theme System = Genius! Mission accomplished. Thanks for the tip on where to find the login page.

![VTS save page](https://user-images.githubusercontent.com/25411186/198354525-b571bb2c-2639-49dc-8ed6-45db9d8dfdce.png)

![VTS Logon Page](https://user-images.githubusercontent.com/25411186/198354489-23ba23a6-fbe4-4087-936b-ec7d1a749740.png)

**Comment by ssddanbrown** [comment]
Awesome to see good use being made of the visual theme system!
