### ISSUE TITLE
Copy and Past in code block fails

### ISSUE THREAD

**Issue by fabianwilflingseder** [BookStackApp/BookStack#382]
### For Bug Reports

* BookStack Version: v0.16.1
* PHP Version: 5.6.30-0+deb8u1
* MySQL Version: 5.6.29-1~dotdeb+7.1

##### Expected Behavior

If I copy some code of a code block and paste it to another position in a code block, the code/text should appear IN the code block.

##### Actual Behavior

If you copy some code of a code block and paste it to another line in the (same) code block, the old code block gets splitted and a new code block with the pasted code appears! So you have three code blocks at the end.

### Images:
![2017-05-01_12h44_30](https://cloud.githubusercontent.com/assets/27973610/25578151/232bfe48-2e6c-11e7-8f8b-e1580d95fbd1.png)

Copy and Paste the line with "some code to copy"

![2017-05-01_12h44_13](https://cloud.githubusercontent.com/assets/27973610/25578155/3149a246-2e6c-11e7-8a26-8b39b985d143.png)

**Comment by ssddanbrown** [comment]
Thanks both for confirming this issue. This is now fixed as of 968e7b8 as part of the revamped code editing experience. It will be released as part of the upcoming v0.17 release. Therefore I will go ahead and close this issue.
