### ISSUE TITLE
No translation for horizontal line element

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3822]
### Describe the Bug

No translation for horizontal line element

### Steps to Reproduce

1. Go to editor
2. Hover over horizontal line

### Expected Behaviour

Text translation

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/4026090/198946707-ee388f05-26eb-4c21-935c-796b138a630b.png)

### Browser Details

Chrome

### Exact BookStack Version

22.10.1

### PHP Version

8

### Hosting Environment

WinServer

**Comment by Statium** [comment]
![image](https://user-images.githubusercontent.com/4026090/198947162-cdfb3c31-bded-48fe-aff7-fc4e9fa59c75.png)
Likewise, some other elements

**Comment by ssddanbrown** [comment]
Also need to add translation for "Inherit Defaults":
https://github.com/BookStackApp/BookStack/blob/986346a0e9de839ac876cf74c2b9e7d15da43d9b/resources/views/form/entity-permissions-row.blade.php#L28

**Comment by ssddanbrown** [comment]
Thanks for reporting, Now addressed for next feature release.
