### ISSUE TITLE
Georgian Language

### ISSUE THREAD

**Issue by stackge** [BookStackApp/BookStack#3823]
### Language to Add

Georgia

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Thanks @Alexskryper for offering to translate. I've now added Georgian to [our crowndin project](https://crowdin.com/project/bookstack).  It will be added to a BookStack release after the language gets to relatively high coverage. The language may be removed if it does not get to this point after a while.
