### ISSUE TITLE
local_secure_restricted + SAML = logo at login (re-upload does not fix)

### ISSUE THREAD

**Issue by BloodyIron** [BookStackApp/BookStack#3827]
### Describe the Bug

As in many other issue threads on this repo, we have experienced the "logo" presented after login, such that it is just linked to the image, and we don't actually get the full bookstack page. This happens when a user logs in (unsure if it's during provisioning, or every time).

I have read through multiple threads, and the recommended fix is to reset, save, then re-upload and save the logo. This does not fix the issue.

The issue happens when using specifically "local_secure_restricted" AND SAML. When we switch to "local_secure" (while also keeping SAML), then do the reset, save, re-upload, it is fixed.

I have gone through multiple attempts to reset, save, re-upload, with "local_secure_restricted", even wiping the underlying storage folders (docker container), and the logo issue happens 100% of the time when using "local_secure_restricted" (plus, in our case, SAML, unsure if SAML is required for this to "fail")

### Steps to Reproduce

I've already roughly explained this I do believe

### Expected Behaviour

Once the login channel completes, the user should be sent to the landing page for Bookstack.

### Browser Details

Tested with Chrome, Firefox, Safari, and Vivaldi.

### Exact BookStack Version

v22.10.2 "latest" tag for : https://hub.docker.com/r/linuxserver/bookstack/tags

### Hosting Environment

K8s, docker image "latest" : https://hub.docker.com/r/linuxserver/bookstack/tags

Storage is backed by EFS, mounted to /config (as part of the behaviour of this image).

**Comment by BloodyIron** [comment]
I tried to find anyone talking about this bug while also talking about "local_secure_restricted" and could not, only talking about "local_secure". So I think this bug is unique and previously un-reported.

Currently our running system is using "local_secure", so I may not be able to help troubleshoot this issue. I am filing the bug in the hopes this gets fixed so we can switch back to "local_secure_restricted" as that is the preferred configuration.

**Comment by ssddanbrown** [comment]
Thanks for reporting @BloodyIron, This has been addressed within d2260b234cd940652fd7bfc79e079422fe7e2dc5 and will be part of the next feature release. Note, you'll need to re-set/save the app logo setting after updating to a version with fixed behaviour to ensure the logo gets saved to the correct place.

**Comment by BloodyIron** [comment]
@ssddanbrown roger that! Thanks! :)
