### ISSUE TITLE
Google OIDC Groups sync

### ISSUE THREAD

**Issue by Leny1337** [BookStackApp/BookStack#3831]
### Describe the feature you'd like

Currently, when setting up OIDC sync with Google, there is no option to sync groups, because Google is not sending groups claim in response. 
From what I see, we can achieve that by implementing Google Admin SDK API to fetch user groups. 

### Describe the benefits this would bring to existing BookStack users

We will be able to have all groups config inside Google Workspace, without manually assigning groups on Bookstack.

### Can the goal of this request already be achieved via other means?

https://developers.google.com/admin-sdk/directory/reference/rest/v1/groups
https://developers.google.com/identity/openid-connect/openid-connect#offlineaccess

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @Leny1996,

To be honest, I wouldn't want to add vendor specific complexity to our auth system, especially in this case where other auth vendors are fairly aligned in providing this detail as a simple token claim.

As an alternative, I'd be open to adding a generic event to our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) which would allow a developer to extend BookStack's functionality to add such additional calls in.

**Comment by ssddanbrown** [comment]
As an additional alternative, if you'd be able to convince Google to sponsor the project for a significant ongoing monthly fee I could then look to build to their specific quirks.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed, and you'd be happy to work with me to develop a logical theme event option for custom extension, please respond to my previous comment and this can then be re-opened.
