### ISSUE TITLE
SQL fails to start when using lowest tier plan on DigitalOcean

### ISSUE THREAD

**Issue by resticker** [BookStackApp/BookStack#3832]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After following the video here, I was unable to get BookStack to connect from the browser. I always received a 500 Error with "This page isn't working" in my browser.

https://youtu.be/wq78komr9rs?t=99

After upgrading to the next tier up with 1 GB of RAM (lowest tier is 512MB), BookStack installed perfectly fine. (I was led to trying the higher tier based on this other issue https://github.com/BookStackApp/BookStack/issues/3578#issuecomment-1186447671)

Things seem to be working fine now, but I can't lower the DigitalOcean droplet settings afaik, which is a shame, since $4 was a sweet deal.

Maybe worth putting a note in the video that it's not okay to install it with the 512MB RAM DigitalOcean plan.

### Exact BookStack Version

v22.10.2

### Hosting Environment

 Ubuntu 22.10 (GNU/Linux 5.19.0-23-generic x86_64) following the installation instructions at https://www.bookstackapp.com/docs/admin/installation/#other

**Comment by ssddanbrown** [comment]
Thanks, I've now added a pinned comment to the video.
It is possible to install on such 512MB machines by [adding swap space](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-22-04) before going through the install.

**Comment by resticker** [comment]
> Thanks, I've now added a pinned comment to the video. It is possible to install on such 512MB machines by [adding swap space](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-22-04) before going through the install.

Thanks for the tip! That's very helpful

In case anyone else sees this, I got BookStack up and running on a free tier AWS EC2 instance in like 5 minutes flat using the video instructions. Possibly a nice alternative to DO for people wanting to try BookStack and are wiling to use a slightly less user-friendly UX.

Great work with BookStack btw! So far it's been incredible. Thank you! And the mobile view of BS is especially great
