### ISSUE TITLE
nginx no ssl_certificate after migrate data to a new server

### ISSUE THREAD

**Issue by michaelortnersanube** [BookStackApp/BookStack#3836]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello all,

I have recently started migrating Bookstack to a new server, as I wasn't quite in the Docker game before I didn't do a very good job of setting it up with the data accordingly, now I have a completely new system set up and wanted to migrate the data. So far all is well, the new data is now over there. However, as soon as I start the server I get the following error message: (Attention Docker environment) bookstack docker:

2022/11/08 06:06:12 [emerg] 1614#1614: no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:3

Anyone of you a idea? I use the linuxserv docker image

### Exact BookStack Version

inuxserver.io version:- v22.10.2-ls48 Build-date:- 2022-11-03T17:18:25+01:00

### Log Content

2022/11/08 06:06:12 [emerg] 1614#1614: no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:3f

### PHP Version

8.0.25

### Hosting Environment

Ubuntu 22.04.1 - Docker-Compose - Nginx Proxy Manager - Portainer

the old server:

Ubuntu 20.04 - Docker-Compose - Traefik - Portainer

**Comment by ssddanbrown** [comment]
Hi @michaelortnersanube,
I'm not overly familiar with the linuxserver container nginx setup, but I'd guess that maybe the old nginx config overrides are not compatible with the new setup.

Before anything, backup your old data first.

Within the mounted volume for the bookstack container, that maps to `/config`, you should have an `nginx` directory. You could try stopping the containers, delete that `nginx` directory to clear any old config, then restart your container setup. The nginx dir should be recreated upon restart with fresh files. I just gave this a test on my system to ensure that's that happens. 

Let me know how that goes.

**Comment by michaelortnersanube** [comment]
Hello @ssddanbrown ,

thanks! Now it works :)

**Comment by ssddanbrown** [comment]
Awesome! Good to hear!
