### ISSUE TITLE
Support Swift language (for insert code block)

### ISSUE THREAD

**Issue by mohamnexus** [BookStackApp/BookStack#3847]
### Describe the feature you'd like

Hi, please add Swift language support to insert code block.

### Describe the benefits this would bring to existing BookStack users

Users of BookStack can show Swift language (iOS language) in BookStack.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Appears to be a [built-in language](https://codemirror.net/5/mode/swift/index.html) so should be an easy add, have assigned for the next feature release.
