### ISSUE TITLE
Trying to Deploy Bookstack on IIS facing issues

### ISSUE THREAD

**Issue by Udaybhanud** [BookStackApp/BookStack#385]
### For Feature Requests

Desired Feature:

### For Bug Reports

* BookStack Version:0.16.1
* PHP Version:7.10.0
* MySQL Version:MariDB 10.7

##### Expected Behavior
Attempting to launch for first time, expecting to need to login

##### Actual Behavior
@ssddanbrown Unable to find login screen. getting 

> HTTP Error 404.0 - Not Found
I guess it is something with the file redirection can you please help me

**Comment by yoginth** [comment]
Change in configuration file! in Apache the conf file look like this

>` <IfModule mod_rewrite.c>`
>   ` RewriteEngine On `
>    `RewriteRule ^(.*)$ public/$1 [L]`
> `</IfModule>`

**Comment by Shackelford-Arden** [comment]
@Udaybhanud Did @yoginth 's comment above help with your problem?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
