### ISSUE TITLE
Local Admin account does not work with LDAP (commit 519283e)

### ISSUE THREAD

**Issue by Sys-Monitor** [BookStackApp/BookStack#3851]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

According to the following commit, an admin account should be validated across all login types:
https://github.com/BookStackApp/BookStack/commit/519283e643f9697952d49c7009dd9e9745cb4319

This does not seem to be the case as the local admin account "Admin" that was setup at the start does not work when enabling LDAP. It **only** works when disabling LDAP.

![image](https://user-images.githubusercontent.com/106233546/201640830-35b77b21-5df5-42f7-94c3-8e8baad87baa.png)
(I've also tried the associated e-mail and that does not work either)

### Exact BookStack Version

22.10.2

### Log Content

Nothing is logged into laravel.log or apache2/error.log. APP_DEBUG=true doesn't show anything different. Still only throws the same error on screen.

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04.1 LTS, installed using installation script

**Comment by ssddanbrown** [comment]
That referenced commit is regarding how the back-end auth session is managed. The user-visible login forms, and their subsequent login actions, are still different between the auth options. 

If attempting to login again with the original admin account, via non-LDAP, you'll need to switch the `AUTH_METHOD` back to `standard` (Or comment it out with a `#`) before refreshing the login page to show the normal auth form.

**Comment by Sys-Monitor** [comment]
I see. I thought we'd be able to manage the instance in case the AD connection goes down without having to edit the server config. I'll close the issue then.
