### ISSUE TITLE
Using Deeplinks with SAML Authentication

### ISSUE THREAD

**Issue by RobinFlikkema** [BookStackApp/BookStack#3856]
### Describe the Bug

Currently using a direct link / deeplink to a page, while not logged in results in begin redirected to the login page.
This is as expected.

However, after logging in using SAML you will be redirected to the homepage of your bookstack installation.

This is an issue as you will have to reopen the link again, or find the correct page yourself.

### Steps to Reproduce

1. Have a bookstack installation with SAML enabled
2. Save a link to a specific page of your bookstack installation
3. Logout of bookstack and try to open the link
4. You're now asked to login, and after login you're redirected to the homepage. Not to the page you tried to open.

### Expected Behaviour

I expect that after logging in, bookstack remembered the URL I tried to open, and redirects me to the page I tried to open.

### Screenshots or Additional Context

This might be related to SAML login. But i do not know for certain.
Public Access is disabled.

### Browser Details

Chrome (latest) on Win10

### Exact BookStack Version

v22.10.2

### Hosting Environment

Official script on Ubuntu

**Comment by RobinFlikkema** [comment]
This is fixed.

**Comment by ssddanbrown** [comment]
Thanks for confirming @RobinFlikkema, I was intending to test this when I had time, since it was something I expected to work. Good to hear its now working for you.
