### ISSUE TITLE
Dark mode in public access

### ISSUE THREAD

**Issue by brandonortiz** [BookStackApp/BookStack#3859]
### Describe the Bug

Clicking the Dark Mode option from Public Access homepage leads to the page expired screen. 

### Steps to Reproduce

1. Enable public access
2. Log out
3. Go to base url
4. Click dark mode

### Expected Behaviour

Dark mode enables or is not available as an option

### Exact BookStack Version

V22.10.2

### Hosting Environment

Ubuntu 20.04

**Comment by ssddanbrown** [comment]
Hi @brandonortiz,
This generally indicates an issue in session management for your instance. This would often be down to one of the following:

- The server does not have proper write access to the required folders as expected (in this case, the `storage/` folder and everything within).
- Something is affecting cookies on your instance, possibly added webserver security rules or layers?
- The `APP_URL` in your `.env` file does not full align with the URL being used to access your instance in the browser.

If you need further help, confirm you've checked the above points and also confirm exactly how you installed BookStack originally.

**Comment by brandonortiz** [comment]
Thanks Dan.

The issue was the browser not being redirected to https at the first page visited. I updated the apache config and it's working now.
