### ISSUE TITLE
Notification by User Rules

### ISSUE THREAD

**Issue by PSilva25** [BookStackApp/BookStack#3865]
### Describe the feature you'd like

The resource I request would be the notification of creation and update of pages directed to specific groups created in the rules. For example: a specific page was created for a group and I want only that group to be notified.

### Describe the benefits this would bring to existing BookStack users

In companies with multiple sectors it is sometimes necessary to notify only a group of people about the creation or update of pages. In my case, I develop processes for the sectors of the company I work for and I would like to notify only the sectors involved in the developed process.

### Can the goal of this request already be achieved via other means?

Currently notifications are used through Webhooks by a Telegram bot. It would be interesting if this were possible directly on Bookstack.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @PSilva25 but I somewhat see this as a complex extension of #241, with that covering the base idea of introducing activity user notifications handling of which would meet your described benefits. Hence I'm going to close this off as I don't like to have overlapping requests if I can avoid it. 

My [latest message in 241](https://github.com/BookStackApp/BookStack/issues/241#issuecomment-1333121138) may be of interest to you if you're really are desperate for such a feature. You might even be able to hack my customizations to directly integrate with telegram.
