### ISSUE TITLE
An Error Occurred, An unknown error occurred

### ISSUE THREAD

**Issue by davecowley** [BookStackApp/BookStack#3867]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi

when a user tries to login with an existing azure or local account they get the An error occurred message.  Also get the same message when trying to export to a pdf.

I did an update the other week and this started to happen after.  there was then another release to the latest which I thought had fixed but hadnt.

I saw others which the same issue but it hasnt fixed the issue.

I have tried:

git pull origin release

----

sudo git status
On branch release
Your branch is up to date with 'origin/release'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../../.env.bak
        ../../bookstack-files-backup.tar.gz
        ../../bookstack.backup.sql
        ../../composer.phar

nothing added to commit but untracked files present (use "git add" to track)
admin@<servername>:/var/www/bookstack/storage/logs$ sudo git status

----

sudo git log -n 1
commit edb0c6a9e89ceff723e30de60fe21d7e3a88d789 (HEAD -> release, origin/release)
Author: Dan Brown <ssddanbrown@googlemail.com>
Date:   Wed Nov 2 15:22:13 2022 +0000

    Updated version and assets for release v22.10.2
admin@asm-wh-knb1:/var/www/bookstack/storage/logs$

-------

sudo git reset --hard
HEAD is now at edb0c6a9 Updated version and assets for release v22.10.2
admin@<servername>:/var/www/bookstack$

Im not too sure what to try next.  I was going to kick up a new vm and restore the data but i'd prefer to fix this.

thanks for your help

### Exact BookStack Version

22.10.2

### Log Content

[2022-11-21 14:31:25] production.ERROR: Method Illuminate\Support\Str::transliterate does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Support\\Str::transliterate does $
[stacktrace]

[2022-11-21 14:33:02] production.ERROR: Class 'Barryvdh\DomPDF\Facade\Pdf' not found {"userId":3,"exception":"[object] (Error(code: 0): Class 'Barryvdh\\DomPDF\\Facade\\Pdf' not found at /var/www/bookstack/app/$
[stacktrace]

### PHP Version

7.4.33

### Hosting Environment

Ubuntu 18.04.6 LTS VM on Hyper-v

**Comment by ssddanbrown** [comment]
Hi @davecowley,
Can you re-run through the update commands for your instance again, running each one-at-a-time, but copy and share the output of each as you go through it?

**Comment by davecowley** [comment]
sure, please find attached
[bookstack_issue_3867.txt](https://github.com/BookStackApp/BookStack/files/10066896/bookstack_issue_3867.txt)

**Comment by ssddanbrown** [comment]
Thanks. Yeah, composer install step is not running properly.

Can you work through the "Updating to v21.12.3 or higher" part of [our updates page](https://www.bookstackapp.com/docs/admin/updates/#updating-to-v21123-or-higher) to validate you're using a recent & compatible composer version.

**Comment by davecowley** [comment]
Ive managed to upgrade composer as it was indeed out of date.

running in to some other permission issues now.

had to create a folder in Vendors folder for masterminds and just had to create /home/admin/.cache/composer/vcs/ but its not having it.  Do you have an advice on the below please?

  Failed to execute git clone --mirror -- 'https://ghp...mHN:x-oauth-basic@github.com/Masterminds/html5-php.git' '/home/admin/.cache/composer/vcs/https---github.com-Masterminds-html5-php.git/'

  Cloning into bare repository '/home/admin/.cache/composer/vcs/https---github.com-Masterminds-html5-php.git'...
  /home/admin/.cache/composer/vcs/https---github.com-Masterminds-html5-php.git: Permission denied

**Comment by ssddanbrown** [comment]
You should not need to manually create any folders, just need to fix permissions or run with require privileges. 
Not sure how your user `.cache/composer` directory has ended up with different permissions.
Assuming you're running via the `admin` user here, and you want to use that user for future updates, you'll just need to ensure they have permission to the folders composer uses.

Can reset these folders to have the `admin` owner by running:

```shell
chown -R admin /home/admin/.cache/composer
chown -R admin /var/www/bookstack
```

**Comment by davecowley** [comment]
thanks for your help on that.  Ive done the changes and it all went through smooth but the site has now died completely!  nothing in the logs, i'll dig around and let you know.

**Comment by davecowley** [comment]
You are a legend mate.  After all the above was complete I had the white page error but it was black not white.  

all fixed with this https://www.bookstackapp.com/docs/admin/debugging/#blank-white-screen-on-access

Thank you for your help Dan.  saved me a bollocking!

**Comment by ssddanbrown** [comment]
Happy I could help and good to hear things are working again!
