### ISSUE TITLE
Very long to answer and display a new page

### ISSUE THREAD

**Issue by MInus63** [BookStackApp/BookStack#3868]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Good morning

As bookstack takes 2 seconds or sometimes 3 to display a new page, I tried to optimize this with memcached
I installed memcached with this tutorial
https://debianpolska.pl/fr/instalacja-memcached-w-systemie-debian-11/

modified the file `/var/www/BookStack/.env` by adding in the end:

```
# Cache & Session driver to use
# Can be 'file', 'database', 'memcached' or 'redis'
CACHE_DRIVER=memcached
SESSION_DRIVER=memcached

# Example of using a single local memcached server
MEMCACHED_SERVERS=127.0.0.1:11211:100
```
restart apache2 but unfortunately this had no effect.

I forgot something in your instructions?

The config of my VM system under Esxi:
4 CPU (Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz)
4Go RAM
200Go HDD

Best regards

### Exact BookStack Version

BookStack v22.10.2 

### PHP Version

8.1

### Hosting Environment

Esxi 7.0 / Debian 11 up to date

**Comment by MInus63** [comment]
Strange behavior on 1 PC the server is super slow, on another PC, connected to the same switch the server has a normal behavior.

**Comment by ssddanbrown** [comment]
Yeah, I'd be surprised if memcached made a difference. 
To be honest, from your last message, it sounds like it's likely a network level issue. 
Would be worth analysing were the slowness is coming from.

If you're comfortable with browser dev tools, could perform a page request (On the slow system) then view the request in the network tab then look at the timings tab of that request, to get a breakdown.
Alternatively, could check timings using curl [like explained here](https://stackoverflow.com/questions/18215389/how-do-i-measure-request-and-response-times-at-once-using-curl).

**Comment by MInus63** [comment]
After my analysis, it is not a network problem but a problem with firefox v107 which is installed on my main PC.
Indeed if, on this same PC, I open bookstack with edge or chrome, it is extremely reactive.
On the other hand, if on another PC I open Bookmark with firefox v107, I also have no problem.
I have to find the origin of the problem, and it is the kind of painful debugging

**Comment by MInus63** [comment]
I ran a Firefox repair and that fixed the problem.

**Comment by ssddanbrown** [comment]
Alrighty, good to hear this is fixed, will therefore close this off.
