### ISSUE TITLE
Export books only registered users

### ISSUE THREAD

**Issue by lrossism** [BookStackApp/BookStack#3870]
### Describe the feature you'd like

Enable block export of books if the user is a visitor/guest

### Describe the benefits this would bring to existing BookStack users

We are working on documentation and want to avoid using outdated versions.

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @lrossism,

Have you tried adding/removing the following role permission from the "Public" role?:

![image](https://user-images.githubusercontent.com/8343178/203577640-abffd894-efd2-4127-a48a-f7efbd382857.png)

**Comment by lrossism** [comment]
Sorry, yes, it worked and I will close the request
