### ISSUE TITLE
Unable to send emails 

### ISSUE THREAD

**Issue by LordNex** [BookStackApp/BookStack#3877]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

There does seem to be an old ticket out for this but it was closed due to inactivity. 

Currently when you install the HA add on of Bookshelf, it come preconfigured with some default settings. After I logged in with the default user ID and Password I then wanted to get it configured for the people who will be using it. I don’t see any settings area to configure an SMTP host and when I click on “Send Test Email” I get the following error. 

```
Error thrown when sending a test email: Expected response code 354 but got code "503", with message "503 RCPT command expected "
```

After looking over my firewall logs it appears to be attempting to use smtp.mailgun.org but I can’t find any setting for this to be able to change it as most email providers do not have open SMTP relays for obvious reasons. The Bookstack documentation states to change a config file but that is embedded with the image that’s connected to Home Assistant and not easily accessible. 

### Exact BookStack Version

22.10.2

### Log Content

```
Error thrown when sending a test email: Expected response code 354 but got code "503", with message "503 RCPT command expected "
```

### Hosting Environment

Dell PowerEdge R620 with VMWare ESXi 7

## System Information

version | core-2022.11.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.4
Stage | running
Available Repositories | 1228
Downloaded Repositories | 91

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 2, 2023 at 6:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 491.4 GB
disk_used | 75.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.7.5), AirCast (3.5.0), AirSonos (3.5.0), Double Take (1.13.1), Duck DNS (1.15.0), ESPHome (2022.11.3), File editor (5.4.2), Frigate NVR Proxy (1.3), MariaDB (2.5.1), Matrix (0.10.0), Z-Wave JS (0.1.74), Studio Code Server (5.4.1), SSH & Web Terminal (12.1.3), Traccar (0.17.0), Tor (4.0.2), MQTT IO (0.1.3), chrony (2.4.0), Z-Wave JS UI (1.3.0), TasmoAdmin (0.21.0), Spotify Connect (0.12.2), Node-RED (13.5.3), Samba share (10.0.0), Genie (3.0.0), Mosquitto broker (6.1.3), Samba Backup (5.2.0), NGINX Home Assistant SSL proxy (3.1.5), Matter Server (0.4.0), Exadel CompreFace (1.1.0), go2rtc (0.1-rc.4), Dnsmasq (1.5.1), Hey Ada! (1.2.0), AppDaemon (0.10.1), Bookstack (1.3.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 53
views | 13
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 31, 2022 at 8:37 PM
-- | --
current_recorder_run | November 27, 2022 at 11:27 AM
estimated_db_size | 19052.23 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since it appears to be a hassio specific query and it's already open in https://github.com/hassio-addons/addon-bookstack/issues/198 where I have responded.
