### ISSUE TITLE
Problem with Permissions and roles (Asset Permissions)

### ISSUE THREAD

**Issue by AnaBS** [BookStackApp/BookStack#388]
Hi!
I'm new at this.
I have created a new role (Simorra) as I show you below:

![image](https://cloud.githubusercontent.com/assets/28437100/25795088/05701dcc-33d4-11e7-8a26-7487f1b00ddd.png)

I have created a book with permissions for this role (Simorra) and a page with links to pages from another book. These linked pages have view permissions for the Simorra role, but Simorra role does not have view permission for the book containing them.

The problem is as follows: Simorra Role can not see the links pages of the book to which she does not have permission.

Are the book, chapter and page permissions independent?
Is it possible to access a page if you do not have permission to the book containing it?

**Comment by nak1090** [comment]
I have the same problem with this feature. Permission on Books not working!

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old, and since there have been a few changes to the permission system since this was created, I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
