### ISSUE TITLE
Anchors in WYSIWG-editor

### ISSUE THREAD

**Issue by CptGroot** [BookStackApp/BookStack#3882]
### Describe the feature you'd like

I would like to refer to another point in a post and when you click on this point it should jump to the position of the point

As an example:

Installation is described in point 4.3 main installation

I would like to set an anchor to 4.3 main installation so that you can jump there

Sort of like in Word with a table of contents

### Describe the benefits this would bring to existing BookStack users

The advantages are that you can create your own table of contents or references in larger articles and have the references with you when exporting with html or pdf

### Can the goal of this request already be achieved via other means?

If you work in the Markdown editor, this is relatively easy, but unfortunately the Markdown editor is not suitable for the main use by many users

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
There is a somewhat built-in way to link to headers:

1. Insert link via toolbar or `Ctrl/Cmd+K`.
2. In the URL box, press a down/up arrow key or start typing the text of the header.
3. Should show the header as a dropdown option.
4. Click desired header.

For other sections, it's a bit fiddly but when viewing the page you can select a block and you'll see a popup with a link to that specific block. You can copy that link and use it in the editor.

**Comment by CptGroot** [comment]
ok,
Thank you thats what I needed :D

**Comment by ssddanbrown** [comment]
Cool, Will therefore close this off.
