### ISSUE TITLE
Unable to save newly created page in the book.

### ISSUE THREAD

**Issue by JotnarScrelsci** [BookStackApp/BookStack#3883]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Unable to save a copy pasted text in a newly created book.
After i click "save page" the web page just keep on loading and by the end of it i get an ERR_EMPTY_RESPONSE.
I tried changing the max_execution_time to 800 but still could't save the file.
The text that im trying to save was copied from a word file with a size of 495 kb
It is the only book that i have a problem with others are saving fine.

List of all the paramets in php.ini that i tried to change:
memory_limit = -1
max_execution_time = 800
post_max_size = 10M
upload_max_filesize = 10M

Is there any particular restriction or limitation that block me from saving the page?

Thanks in advance!

### Exact BookStack Version

22.10.1

### Log Content

/var/www/bookstack/storage/logs/laravel.log:
#0 {main}
"}
[2022-11-30 08:56:40] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":6,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/app/Entities/Tools/PageContent.php:231)
[stacktrace]
#0 {main}
"}
[2022-11-30 08:57:50] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":6,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/app/Entities/Tools/PageContent.php:231)
[stacktrace]
#0 {main}
"}

/var/log/apache2/error.log: 
Fatal error: Maximum execution time of 800+2 seconds exceeded (terminated) in /var/www/bookstack/app/Entities/Tools/PageContent.php on line 231
[Wed Nov 30 15:35:23.897155 2022] [mpm_prefork:notice] [pid 1505] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Nov 30 15:35:24.030696 2022] [mpm_prefork:notice] [pid 1681] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Wed Nov 30 15:35:24.030747 2022] [core:notice] [pid 1681] AH00094: Command line: '/usr/sbin/apache2'
[Wed Nov 30 15:43:35.026403 2022] [mpm_prefork:notice] [pid 1681] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Nov 30 15:43:35.141712 2022] [mpm_prefork:notice] [pid 1915] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Wed Nov 30 15:43:35.141838 2022] [core:notice] [pid 1915] AH00094: Command line: '/usr/sbin/apache2'

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04 VPS, installed via official installation script.

**Comment by ssddanbrown** [comment]
@JotnarScrelsci Hard to know what's going on without having the content you're coping.
Based on the lines in the error messages, might just be something funky within the content causing BookStack to timeout. Could be the sheer amount of content to process depending on the content.

Could try splitting it down, so only copy in half the content to see which half breaks things (If any), then half that down then repeat until you find a particular section that's breaking things, or find if it's just due to size of content being copied.

**Comment by JotnarScrelsci** [comment]
Wow thanks for the quick response! 
Indeed splitting the text in 2 blocks allowed me to save the page.
I guess this will do for now.
