### ISSUE TITLE
Installation behind Proxy fails

### ISSUE THREAD

**Issue by Ibso** [BookStackApp/BookStack#3884]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When using the installation script for Ubuntu 22.04 behind the corporate proxy, it fails to finish.
The Script stops at 
[5/9] Installing PHP dependencies using composer...

I've created a fresh VM, installed Ubuntu Server 22.04, set the global Proxy using:
`export http_proxy=http://proxy_host:proxy_port` and `export https_proxy=http://proxy_host:proxy_port` 
and set the git proxy using `git config --global http.proxy http://proxy.server.com:8080`

wget, curl and git commands work without a problem outside the script

### Exact BookStack Version

22.11

### Log Content

`[3/9] Downloading BookStack to /var/www/bookstack...`
`Cloning into 'bookstack'...`
`fatal: unable to access 'https://github.com/BookStackApp/BookStack.git/': Could not resolve host: github.com`
`[4/9] Installing Composer (PHP dependency manager)...`
`PHP Warning:  copy(): php_network_getaddresses: getaddrinfo for composer.github.io failed: Name or service not known in Command line code on line 1`
`PHP Warning:  copy(https://composer.github.io/installer.sig): Failed to open stream: php_network_getaddresses: getaddrinfo for composer.github.io failed: Name or service not known in Command line code on line 1`
`PHP Warning:  copy(): php_network_getaddresses: getaddrinfo for getcomposer.org failed: Name or service not known in Command line code on line 1`
`PHP Warning:  copy(https://getcomposer.org/installer): Failed to open stream: php_network_getaddresses: getaddrinfo for getcomposer.org failed: Name or service not known in Command line code on line 1`
`PHP Warning:  hash_file(composer-setup.php): Failed to open stream: No such file or directory in Command line code on line 1
Could not open input file: composer-setup.php`
`rm: cannot remove 'composer-setup.php': No such file or directory`
`mv: cannot stat 'composer.phar': No such file or directory`
`[5/9] Installing PHP dependencies using composer...`
`./installation-ubuntu-22.04.sh: line 122: cd: /var/www/bookstack: No such file or directory`

### Hosting Environment

Ubuntu 22.04 on a Hyper-V VM using the official script

**Comment by ssddanbrown** [comment]
Yeah, the script hasn't really been designed to work with proxies. You'd need to not use a proxy, or work around parts that don't support proxies by either altering the script or manually running the script commands instead, using workarounds for failing elements.

**Comment by Ibso** [comment]
Thanks for the fast response, Dan.  I'll try to work with the individual commands from the script and hope to get this thing to work.
would you consider modifying the scripts for future releases? since i am pretty sure others with similar setups will have the exact same issue.

**Comment by ssddanbrown** [comment]
> would you consider modifying the scripts for future releases?

Depends on how far we'd need to stray from official/documented methods for actions. Even then would probably not assure proxy support either since it's an extra pain to test when creating/updating these scripts.

**Comment by Ibso** [comment]
Understandable. Thanks dude!
