### ISSUE TITLE
use {Host} header or something else instead of {APP_URL} Enviroment

### ISSUE THREAD

**Issue by toshiya14** [BookStackApp/BookStack#3887]
### Describe the feature you'd like

I deployed the app into one internal server and use a public server to reserve proxy to it.
Now, if I specified {APP_URL} with the public host address.
It would redirect to the public host address even I enter the internal IP or hostname in browser.

Could I visit the app via internal IP or hostname but not the public host?

### Describe the benefits this would bring to existing BookStack users

Sometimes it is no need to visit via reverse proxy. But the redirect would always navigate users to the reserse proxy endpoint.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
You can use an IP or any hostname you'd like, but the fundamental thing here is that BookStack only officially supports being hosted at on IP/hostname at a time.

**Comment by toshiya14** [comment]
> You can use an IP or any hostname you'd like, but the fundamental thing here is that BookStack only officially supports being hosted at on IP/hostname at a time.

So the problem for me is: I'd like to use hostname: `http://notebook/` for private network visiting.
And `https://notes.something.com` for public network and reverse proxy to the deployment.

`APP_URL` is required. I could not leave it empty. And if I set to `https://notes.something.com`, when I visit `http://notebook` it navigate me to `https://notes.something.com`.

And I do not want to get this redirection.
Actually, I visit `http://notebook/` I could get the homepage displayed correctly.
But if I click any of the link in the page, it would redirect to `https://notes.something.com/xxx`.

**Comment by ssddanbrown** [comment]
Okay, to be honest I've never really understood the desire/need to bypass an external domain/host when used in-network. 
Just seems to complicate matters.

Either way, support for multiple base URLs is already open in  #1342 and therefore I'll close this off as a duplicate since it essentially has the same request at the core of it.
