### ISSUE TITLE
adding annotations to pictures

### ISSUE THREAD

**Issue by mb1811** [BookStackApp/BookStack#3888]
### Describe the feature you'd like

It would be very handy to right click to a photo and add simple annotation like arrows, blurr-boxes or a stamp which increases numbers with every click.

Resizing images is possible by now, but a simple cropping feature is missing

### Describe the benefits this would bring to existing BookStack users

Doing annotations inside bookstack will provide a much faster workflow instead of doing those with 3rd party apps.

I use it alot in our ticket system https://osticket.com/

![Screenshot 2022-12-01 at 10-32-33 Ticket #002842](https://user-images.githubusercontent.com/119583110/205017372-b4a8201e-9875-43c6-96fb-634cc89305f3.png)

The "stamping" feature can be seen on the "flameshot" screenshot app: https://flameshot.org/

The benefit to editable annotations inside Bookstack is that you can update those instead of doing a new screenshot, add annotation there an copy a final screenshot to Bookstack.

### Can the goal of this request already be achieved via other means?

it can be only achieved by 3rd party apps

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @mb1811, but issue #3350 already exists to request fundamental support for image annotations so I'll therefore close this off as a duplicate.
