### ISSUE TITLE
template system: metadata on every page

### ISSUE THREAD

**Issue by mb1811** [BookStackApp/BookStack#3889]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Exporting a single page as PDF adds some metadata to the end, with timestamp, editors name and version.

When you export a chapter or a book, none of these information is added to the individual page.

Is there a way to realize that within the template system? Just saw your video on adding header and footers - is there a way to get the metadata exported?

This code is found when exporting a singe page.

/resources/views/exports/page.blade.php

```
@include('pages.parts.page-display')

    <hr>

    <div class="text-muted text-small">
        @include('exports.parts.meta', ['entity' => $page])
    </div>
```

### Exact BookStack Version

22.10.2 

### Hosting Environment

Debian 11

**Comment by ssddanbrown** [comment]
Hi @mb1811,

The page item template is used for pages within chapter/books exports: https://github.com/BookStackApp/BookStack/blob/development/resources/views/exports/parts/page-item.blade.php

You could override this with the visual theme system, then append the:

```html
    <div class="text-muted text-small">
        @include('exports.parts.meta', ['entity' => $page])
    </div>
```

part to the template override to add the meta content for each page within chapter/book exports.

**Comment by mb1811** [comment]
Thank you very much!

```
<div class="page-break"></div>

@if (isset($chapter))
    <div class="chapter-hint">{{$chapter->name}}</div>
@endif

<h1 id="page-{{$page->id}}">{{ $page->name }}</h1>

<div class="text-muted text-small">
    @include('exports.parts.meta', ['entity' => $page])
</div>

{!! $page->html !!}
```

That looks much better. As we need to have a actual printout of our emergency handbook, this comes very handy!
Just need to figure out why the override in my template folder does not work.

Am I right to just copy 

/resources/views/exports/parts/page-item.blade.php

to

/themes/mytheme/layouts/parts/ 

?

**Comment by mb1811** [comment]
With that edit the version number is not printed when exporting the book.
When exporting the chapter the version number is visible.

**Comment by ssddanbrown** [comment]
Yeah, that data field does not exist in that context, since book contents are loaded in a different optimized way.

You may be able to update the `@include` line to be:

```html
 @include('exports.parts.meta', ['entity' => \BookStack\Entities\Models\Page::query()->find($page->id)])
```

Not tested, and may slow things down.

**Comment by mb1811** [comment]
Thanks - works for me!

**Comment by ssddanbrown** [comment]
Good to hear, Will therefore close this off.
