### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by montharon** [BookStackApp/BookStack#389]
* BookStack Version: 0.16
* PHP Version: 5.6.29-0+deb8u1
* MySQL Version: mysql  Ver 14.14 Distrib 5.5.53

![bookstack](https://cloud.githubusercontent.com/assets/21140797/25819399/311f619e-342e-11e7-809a-2f67509c1366.PNG)

I get a timeout when I'm trying to export a certain page as PDF.
I already checked the settings in my php.ini where it says....
....
max_execution_time = 300
...

Many thanks in advance,
montharon

**Comment by Shackelford-Arden** [comment]
@montharon I'm curios... is the page you're trying to export rather large?

**Comment by montharon** [comment]
@Shackelford-Arden
Yes, the page I'm trying to export is very large indeed!
It is a huge collection of knowledge with a great number of tables and so on....

Regards,
montharon

**Comment by Shackelford-Arden** [comment]
My guess then is that it's taking longer than 30 seconds to actually create the PDF but that's just a guess... @ssddanbrown

**Comment by ssddanbrown** [comment]
@Shackelford-Arden Yeah, Exporting to PDF is very intensive.

 It's hard to tell the exact part that's taking time here. You could try [changing PDF render](https://www.bookstackapp.com/docs/admin/pdf-rendering/) to see if that speeds things up (WKHTMLtoPDF is likely to be faster than the default DOMPDF).

**Comment by lommes** [comment]
If the timeout limit is reached laravel should tell you the current values, so it looks like the value in your php.ini is not used. 

Are you running this with a standalone webserver like apache/nginx or are you using the built-in php webserver (or artisan serve) for testing? If using the built-in server try running php --ini to see all possible ini files which might cause this problem. You can place a new file in the public/ directory with the following content
`<?php
phpinfo();`

Call this file in your browser (e.g localhost:8000/phpinfo.php if you called the file phpinfo.php) and check if the correct values are listed.

**Comment by montharon** [comment]
Hi to all of you!
I know it's been a while since I posted my issue here but the second half of the year 17 was crazy... woohh ;)

Soooo, I finally have changed from DOMPDF to WKHTMLTOPDF -> nothing changed....
And here is the output of a <?php phpinfo(); command...

[phpinfo.txt](https://github.com/BookStackApp/BookStack/files/1627269/phpinfo.txt)

Unfortunately I have no clue for what I should looking for?

Thanks in advance!
montharon

**Comment by lommes** [comment]
the loaded ini file is /etc/php5/fpm/php.ini, so there should be a value of max_execution_time with the value 30, raise that to 300 or something

**Comment by montharon** [comment]
That is exactly where I already raised the execution timeout ;(

![phpini](https://user-images.githubusercontent.com/21140797/34906509-5d97546a-f86f-11e7-96c9-15b461155596.PNG)

Thanks in advance!
montharon

**Comment by lommes** [comment]
Dir you restart at least the webserver afterwards?

**Comment by montharon** [comment]
I just restarted nginx with
`service nginx restart`
and retried to export a PDF file.
Unfortunately, after 30 seconds I got a timeout....????

**Comment by montharon** [comment]
Enabled debug ....

![blockphp](https://user-images.githubusercontent.com/21140797/34906589-c36f5764-f870-11e7-8bfd-62d7021e3462.PNG)

**Comment by montharon** [comment]
Just tried wkhtmltopdf once more with debugging turned on....

![wkhtmltopdf](https://user-images.githubusercontent.com/21140797/34906790-714866a2-f874-11e7-9d31-c8e1fcdc0a31.PNG)

...and my .env file...

![envfile](https://user-images.githubusercontent.com/21140797/34906791-790cc75c-f874-11e7-9464-831b2446c086.PNG)

montharon

**Comment by lommes** [comment]
wkhtmltopdf seems to need x server running, which is not given on every server. According to https://stackoverflow.com/a/9685072 this can be solved. 

After changing max_execution_time you need to restart the webserver or in your case fpm (service php-fpm restart).

**Comment by montharon** [comment]
We are getting closer!!! ;)
Now I get a 504 Gateway timeout...

I've followed these tips...

`
Für Nginx + FastCGI (php-fpm):
    in fpm/php.ini den Wert für max_execution_time (Sekunden) hinaufsetzen
    in fpm/pool.d/www.conf den Wert für request_terminate_timeout auf den selben Werten einstellen
    in nginx.conf zum Block location ~ \.php$ hinzufügen: 
`
... but sith no success ;(

Any ideas?

Many thanks in advance,
montharon

**Comment by over-soul** [comment]
@montharon 

After you change the execution time, you need to run

`sudo systemctl restart php5.6.29-fpm.service`

Also, are you using any non-default fonts?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Comment by alexohneander** [comment]
I have the same problem as the creator.
I have already adjusted the php_ini. Unfortunately, that didn't help.

[FlareApp Debug](https://flareapp.io/share/dmkx9OlP#F1)

**Comment by ssddanbrown** [comment]
@alexohneander It's likely one of the following:

- You're editing a different `php.ini` to that used by your BookStack setup.
- You have not restarted the PHP/webserver process to pickup PHP config changes.

If you need further help, please open a new support request issue to detail your setup.
