### ISSUE TITLE
update to 22.11: dark mode toggle, shortcuts, search not working

### ISSUE THREAD

**Issue by mb1811** [BookStackApp/BookStack#3890]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

updating from 22.10 to 22.11 - following your instructions - ran fine. No errors.
Settings menu shows v22.11.

After logging in I get a 405 page when choosing from the menu.

Clicking the shortcut item from menu, I get a bookstack message: Page not found.

The central search works the same as in v22.10. New search is not available

### Exact BookStack Version

22.11

### Log Content

nothing found.

### PHP Version

7.4.33

### Hosting Environment

Debian 11

**Comment by ssddanbrown** [comment]
Hi @mb1811,

Please can you provide the output of running `git status` within the top folder of your bookstack install?

**Comment by mb1811** [comment]
```
git status
Aktualisiere Index: 100% (1582/1582), fertig.
Auf Branch release
Ihr Branch ist auf demselben Stand wie 'origin/release'.

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git restore <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)
	geändert:       app/Config/snappy.php
	geändert:       public/dist/export-styles.css
	geändert:       resources/views/exports/book.blade.php
	geändert:       resources/views/exports/chapter.blade.php
	geändert:       resources/views/exports/parts/chapter-item.blade.php
	geändert:       resources/views/exports/parts/custom-head.blade.php
	geändert:       resources/views/exports/parts/meta.blade.php
	geändert:       resources/views/exports/parts/page-item.blade.php
	geändert:       resources/views/layouts/parts/export-body-end.blade.php
	geändert:       storage/clockwork/.gitignore

Unversionierte Dateien:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
	.env.bak
	.env~
	DEADJOE
	app/Config/snappy.php~
	public/dist/export-styles.css.backup
	public/dist/export-styles.css~
	resources/views/exports/book.blade.php~
	resources/views/exports/chapter.blade.php.backup
	resources/views/exports/chapter.blade.php~
	resources/views/exports/page.blade.php~
	resources/views/exports/parts/chapter-contents-menu.blade.php~
	resources/views/exports/parts/chapter-item.blade.php.backup
	resources/views/exports/parts/chapter-item.blade.php~
	resources/views/exports/parts/custom-head.blade.php~
	resources/views/exports/parts/meta.blade.php_backup
	resources/views/exports/parts/meta.blade.php~
	resources/views/exports/parts/page-item.blade.php#
	resources/views/exports/parts/page-item.blade.php.backup
	resources/views/exports/parts/page-item.blade.php~
	resources/views/layouts/export.blade.php~
	resources/views/layouts/parts/export-body-end.blade.php~

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")
```

**Comment by ssddanbrown** [comment]
@mb1811 I don't think you're getting the latest files downloaded, since the first update command to pull the latest changes would probably conflict with your local environment, since there are a bunch of files with detected changes.

Have you made changes to the listed (At the top) files? and if so do you need to retain those?

**Comment by mb1811** [comment]
Thanks for that hint. I'll check those files later - for now we need a running system to do our documentation.

**Comment by mb1811** [comment]
I tried to backup all those files I did minor changes on (mostly the export files), then deleted them. 
I did the update again - same errors-.

I then backed up the database and moved the install folder to a backup-location. 
Finally I did a reinstall with the old database - that worked.

As we need some changes especially in the export (left margin on an printed file, some css changes like fontsize, etc..) - is there a way to avoid those errors and to keep our files?

**Comment by rokkondic** [comment]
Hello,
I seem to be having the same issue. I updated version 22.10 to version 22.11.1. The update went fine, except for these issues:

- The search preview is not working
- When I try an toggle to light/dark mode I get this error:


![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/43110771/208425844-0a2011f7-6e84-4c30-a2dd-937aa7be8b7a.png)

Some additional information:

- PHP version: 7.4.32
- Server: Ubuntu 18.04.6 LTS
- Git status:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/43110771/208426076-cf80e60d-453f-48af-8de6-27319b0d8717.png)

**Comment by rokkondic** [comment]
After a clean reinstall all the mentioned problems are gone.

**Comment by ssddanbrown** [comment]
I will therefore close this off.

In regards to keeping customizations, please see our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) which allows custom overriding/customization of application views without editing core app files. 
For simpler tweaks, you can target exports via certain classes for CSS via the "Custom HTML Head Content" customizations setting. For example, a css rule of `.export-format-pdf p { color: red;}` would cause red paragraph text just within pdf exports.
