### ISSUE TITLE
How to increase maximum shelves on a page

### ISSUE THREAD

**Issue by xKugeki** [BookStackApp/BookStack#3891]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [x] I have searched GitHub for the issue.

### Describe the Scenario

Hello GitHub Community,

I created my website with bookstack and created some shelves and got now about 20 shelves.
After 18 shelves the rest will be placed on page 2.

Is there any way to increase the amount of shelves per page?
I tried to look inside the javascript files but I wasnt able to find the right settings for this.

Can you please help me out to find that settings?

I wish you a great day :)

### Exact BookStack Version

v22.10

### PHP Version

8.2

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
:wave: 

> Is there any way to increase the amount of shelves per page?
> I tried to look inside the javascript files but I wasnt able to find the right settings for this.

Yeah, this is drive by PHP-side logic, won't be in the JS.
You can find the listed number on this line:

https://github.com/BookStackApp/BookStack/blob/69d702c7830936e5ec8c5484446c04fddcc5f0fd/app/Http/Controllers/BookshelfController.php#L43

**Comment by xKugeki** [comment]
@ssddanbrown thank you very much :D 
That fixed my problem :)

Have a nice day :)
