### ISSUE TITLE
Removing pdf revision info

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#3892]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

As was (I think) originally mentioned in #2076, I need to remove the revision info from pdf documents. I followed all the instructions in that issue (adding `app_theme=custom`, creating a blank php file, etc), but the revision info persists:

![image](https://user-images.githubusercontent.com/57015243/205240185-5fdda071-1000-45e5-8f1a-631a51db0604.png)

I must be missing something, but I can't see what - or has the way to do this changed? Could someone enlighten me?

### Exact BookStack Version

22.11

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04 LTS with Apache2

**Comment by ssddanbrown** [comment]
Hi @techauthoruk,
The template file has since changed during some reorganisation. 
The blank file would now need to be at `themes/custom/exports/parts/meta.blade.php`

**Comment by techauthoruk** [comment]
@ssddanbrown 

Thanks for the info Dan - sorted now so closing this off
