### ISSUE TITLE
Discord authentication is requiring re-authorization each time a user logs into the site

### ISSUE THREAD

**Issue by dimforest** [BookStackApp/BookStack#3896]
### Describe the feature you'd like

We're using Discord as an identity provider and it works well... but for some reason it's prompting everybody (myself included) to re-authorize each time we log into the site fresh. Is there a way to have it only do this the first time or limit it to every 30, 60, etc days? It's not hindering people from getting into the site, it's just becoming increasingly annoying to have to re-authorize each time.

### Describe the benefits this would bring to existing BookStack users

This would allow our users to authorize using their Discord account to authenticate only the first time or at the very least, a lesser frequency than "every single time" 

### Can the goal of this request already be achieved via other means?

Not that I'm aware of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Looks like discord supports a `prompt` param. From [the docs](https://discord.com/developers/docs/topics/oauth2):

> prompt controls how the authorization flow handles existing authorizations. If a user has previously authorized your application with the requested scopes and prompt is set to consent, it will request them to reapprove their authorization. If set to none, it will skip the authorization screen and redirect them back to your redirect URI without requesting their authorization.

**Comment by ssddanbrown** [comment]
Digging into this, and by doing a test on my local instance, I can see the library we use recently updated to set `prompt=none` by default, so this behavior should no longer be an issue on the latest release of BookStack.
