### ISSUE TITLE
Removing domain restriction without being able to log in

### ISSUE THREAD

**Issue by moffitj** [BookStackApp/BookStack#3900]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I enabled domain restriction. After saving I got logged out and can't log back in because I have not verified my address. The server is unable to send emails and I'm unable to configure it to do so.

Is there a way to remove the domain restriction without being able to log in?

### Exact BookStack Version

22.09

### Hosting Environment

Debian 10

**Comment by ssddanbrown** [comment]
Hi @moffitj,
No built-in way to disable this, but the follow commands, ran from your bookstack folder, should reset this setting to turn off domain restriction:

```bash
php artisan tinker --execute="setting()->put('registration-restrict', '')"
php artisan config:clear
```
