### ISSUE TITLE
Display image attachments in browser rather than downloading

### ISSUE THREAD

**Issue by SteveDinn** [BookStackApp/BookStack#3905]
### Describe the feature you'd like

When I've attached an image to a page, and then link to it, my browser always wants to download the image rather than displaying it, which is what I really want to have happen 99% of the time. Specifically, it should open the image in a new tab.

### Describe the benefits this would bring to existing BookStack users

Images are meant to be viewed not necessarily downloaded. And even if the user wants to download an image, after it is shown, they can right-click and download it.

### Can the goal of this request already be achieved via other means?

Not that I know of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @SteveDinn,

If you copy/use the "Open in Tab" option link in the attachment dropdown it'll open inline as desired:

![Screenshot from 2022-12-06 23-21-58](https://user-images.githubusercontent.com/8343178/206046656-698531b8-8836-4b5a-88e4-85ff1358d5b0.png)

**Comment by tcatlas** [comment]
It is far more intuitive and normal for images displayed inline to open in a lightbox when clicked (most often, in my experience, to be zoomed and panned) and an option in that lightbox to download (or in the attachment list as is already present).

**Comment by SteveDinn** [comment]
I mean if I were to have the markdown as such:
```
[photo](https://bookstack.example.com/attachments/35)
```
Then it should still open as an image (however that might be), and not as a download.

**Comment by ssddanbrown** [comment]
Using the link as described above will achieve that. It will look the same but with `?open=true` appended to the URL. [Here's an example](https://demo.bookstackapp.com/attachments/1?open=true) on our demo instance.

Attachments are primarily intended as attachments for download so, although while possible as above, in-content imagery is not a focus for this feature since we already have specific image-focused features/usage via the image manager.

**Comment by SteveDinn** [comment]
I acknowledge that this is probably an edge case. 

I wanted to have pictures that were viewable by clicking a link but not actually displayed on the page because they're in a table. I was getting annoyed by having to remove the automatically generated markdown every time I added an image through the image manager. 

I'll close this because I can get around my issue by using `?open=true` as you suggested. Thanks for the help.
