### ISSUE TITLE
Pass Name and Email as parameters into custom HEAD section

### ISSUE THREAD

**Issue by tedivo** [BookStackApp/BookStack#3906]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have site usage / live chat integration using the custom HEAD section, but I would like to pass in the name and email of the user as a tag inside the Javascript.

Is it possible to pass this information as parameters into the custom HEAD javascript?

### Exact BookStack Version

22.11

### PHP Version

8.0

### Hosting Environment

Ubuntu 20.04 LTS

**Comment by ssddanbrown** [comment]
Hi @tedivo,
This is not complete information we expose to the front-end to be able to pick-up using JavaScript on the page.
To do this, you'd need to use something like the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) to customized a common base view used to expose those details for your use-case.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If you need additional information just let me know.
