### ISSUE TITLE
[Feature Request] Display breadcrumb trail in entity select dialog

### ISSUE THREAD

**Issue by mitchray** [BookStackApp/BookStack#391]
**Desired Feature: Display breadcrumb trail in entity select dialog**

There is currently no way of differentiating between pages of the same name; the content preview gives a nice hint as to the context of the page, but isn't enough when content is similar

![screen shot 2017-05-10 at 1 56 01 pm](https://cloud.githubusercontent.com/assets/5735900/25882678/a52e2cf4-3588-11e7-8ac2-2e491527aa05.png)

**Comment by ssddanbrown** [comment]
@mitchray Thanks for bringing this up and apologies, I kind of missed this one. Will be in the next bugfix release, v0.17.4, due in the next couple of days.
