### ISSUE TITLE
Darkmode - Seperate primary header/text colors for better dark header support

### ISSUE THREAD

**Issue by towerplease** [BookStackApp/BookStack#3910]
### Describe the feature you'd like

In Lightmode, the visuals will display fine:
![image](https://user-images.githubusercontent.com/21177236/206457937-692ef026-f723-4cf5-bb1e-dd1aa5b732c5.png)

When changing to darkmode, the navigation baar, or "actions" are almost unreadable due to the selected color (darkblue). 
![image](https://user-images.githubusercontent.com/21177236/206458226-81e514df-1604-4210-a380-d88c393729ee.png)

I think it would be better to make these light aswell, like on the left side.

### Describe the benefits this would bring to existing BookStack users

Usage of darkmode when a darker color from header is chosen.

### Can the goal of this request already be achieved via other means?

Not as i know.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Related to #2314

**Comment by ssddanbrown** [comment]
Thanks for the request @towerplease,
Within #4002 I've updated the colour settings so it's possible to set the link colour (Which includes the actions highlighted in your screenshot) independently of the app theme colour. 

This will be part of the next feature release.

**Comment by towerplease** [comment]
Nice!!! Thank you @ssddanbrown 

I'm excited for the next release.
