### ISSUE TITLE
Sub Page / Sub Chapter feature

### ISSUE THREAD

**Issue by arvindjkhr** [BookStackApp/BookStack#3916]
### Describe the feature you'd like

Since I was exploring this project, I found this very useful. Still, I would like to have some subpages and subchapters feature for better table of content generation so it would be easy to understand in a book/document.

### Describe the benefits this would bring to existing BookStack users

This will have better table of content generation as well as easy to maintain the documentation.

### Can the goal of this request already be achieved via other means?

I am not sure

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @arvindjkhr but I'm going to close this off as this has been discussed in multiple issues previously, with #95 being the main/original one.
