### ISSUE TITLE
Lost focus while using keyboard arrow keys in global search field

### ISSUE THREAD

**Issue by rockenren** [BookStackApp/BookStack#3920]
### Describe the Bug

When you place cursor in global search field and try to use keyboard arrow keys it will change input focus instead of moving cursor in search field.

Shortcut feature disabled.

### Steps to Reproduce

Can be reproduced on https://demo.bookstackapp.com/

1. Go to Global Search field
2. Type anything
3. Try to move cursor via keyboard arrow keys (left-right)
4. Search input will lose focus (will cycle thru live search results instead of moving cursor in the search field)

### Expected Behaviour

Cursor should be able to move with keyboard arrow keys in global search field.

### Browser Details

Firefox 108, Chrome 108

### Exact BookStack Version

v22.11

### PHP Version

7.4.30

### Hosting Environment

Ubuntu 18.04.6 LTS

**Comment by ssddanbrown** [comment]
Thanks for reporting @rockenren.
This has been addressed in 2c0a7346b1635b5fd1599a86e33e3c834d9a967c and will be part of the next patch release.
