### ISSUE TITLE
System wide personalized notification system 

### ISSUE THREAD

**Issue by mannydaniel** [BookStackApp/BookStack#3923]
### Describe the feature you'd like

A system wide personalized notification system for new books, pages and chapters and comments made on pages a user published. Notifications can be cleared and a formatting change shows a user has viewed them. An option can be made for individuals to subscribe for changes made to particular chapter, book or shelve. 

### Describe the benefits this would bring to existing BookStack users

In scenarios where quite a lot of things happen daily, it's hard to keep track of changes, that may be relevant to an individual. The 'Recently Updated Pages' tab does the job fine but a notification system that keeps track of items that are viewed will be helpful. Notification for comments made on pages a user published is currently not available. This will help users respond to comments easily and brings a sense of collaboration on pages. 

### Can the goal of this request already be achieved via other means?

Partially yes. The existing system shows limited number of changes on the platform but personalization will add a great value. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @mannydaniel, but I'm going to close this off as I feel the fundamental request is already covered across existing issues #935, #1246 and #241.
