### ISSUE TITLE
App url changed - all images are broken

### ISSUE THREAD

**Issue by pmvamsi-coder** [BookStackApp/BookStack#3924]
### Describe the Bug

I am running Bookstack app on docker. I changed the app URL then all the links are broken and unable to access.

### Steps to Reproduce

App URL was changed but all image links are broken.

### Expected Behaviour

It should align automatically if the app URL changes.

### Exact BookStack Version

v22.11.1

### Hosting Environment

Debian

**Comment by ssddanbrown** [comment]
Hi @pmvamsi-coder,
Please see the "Update System URL" section on this page:
https://www.bookstackapp.com/docs/admin/commands/#update-system-url

**Comment by pmvamsi-coder** [comment]
I am running app in docker .. ran command in bookstack container it is not working .. pls help

**Comment by pmvamsi-coder** [comment]
Even after running the update url command its showing the same broken images
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/61499149/208254005-b7782734-8c90-4fb9-84d6-0347fadd01ad.png">

getting as above

**Comment by pmvamsi-coder** [comment]
it updated the APP_URL and URLs in the database but still those images are still broken 😢

**Comment by ssddanbrown** [comment]
- Okay, How different is the current URL for images compared to what would be expected? If you open up a non-loading image in a new tab does the URL look incorrect?
- Since you mention using docker, did you have a mapped volume to retain container data? Can you see the image files within that mapped volume folder?

**Comment by pmvamsi-coder** [comment]
When I open the image url in the new tab it's showing the updated one only.

Images are there in the attached docker volume folder. Container configs are also same just changed the APP_URL

**Comment by ssddanbrown** [comment]
> When I open the image url in the new tab it's showing the updated one only.

What exactly is meant by that? I would expect the image URL to follow the format `<APP_URL>/uploads/images/*`. Does the URL differ to that? If so, how?

**Comment by pmvamsi-coder** [comment]
I mean the image url getting is the new one (with updated  APP_URL) but images are not getting displayed in the pages or book covers and profiles pic as well

**Comment by ssddanbrown** [comment]
Okay, does the new URL look valid, follow the format I shared above? With no other issues like double slashes or extra parts in the URL? Examples would be good if possible.

**Comment by pmvamsi-coder** [comment]
Below is the link I am getting after clicking on the image.
**https://pmv-bookstack.techsthal.online/uploads/images/gallery/2022-12/EcXimage.png**
But I am getting the error like this
![image](https://user-images.githubusercontent.com/61499149/208260457-f1170b8b-568a-4292-a946-fe13a5de814c.png)

**Comment by ssddanbrown** [comment]
Within your mounted volume folder can you find that `EcXimage.png` file then confirm it's directory (relative to root volume path).
Also, can you confirm if you have any `STORAGE_*`  options set in your docker environment or an `.env` file and, if so, confirm their values if possible.

**Comment by pmvamsi-coder** [comment]
I redeployed the whole setup from the backup and it works now.. Thanks for the quick response 😄
