### ISSUE TITLE
Header quick search result clicks not working in Safari 16.2

### ISSUE THREAD

**Issue by ChrisHardie** [BookStackApp/BookStack#3926]
### Describe the Bug

The header quick search feature is amazing! Unfortunately it only works for me in Chrome, and not Safari. I'm using version 16.2 (17614.3.7.1.7, 17614) on macOS Monterey 12.6. Typing a query works, display of results works, but when I click on a result the result box disappears. No apparent JS errors or other useful information in the console. 

### Steps to Reproduce

1. Use Safari version 16.2 on macOS 12.6
2. Log in to a Bookstack site
3. Conduct a header search
4. Try to click on the search results

### Expected Behaviour

The browser will visit the clicked link.

### Screenshots or Additional Context

![bookstack-results-2](https://user-images.githubusercontent.com/311772/208737615-253acaad-62d6-42d8-bea1-f0ab34df7f7c.gif)

### Browser Details

Safari Version 16.2 (17614.3.7.1.7, 17614)

### Exact BookStack Version

22.11.1

### PHP Version

8.0.21

### Hosting Environment

Ubuntu 20.04 droplet at Digital Ocean

**Comment by ssddanbrown** [comment]
Thanks for reporting @ChrisHardie,
This has been fixed in deda33174548c105e3470ecb361ea39e4f18f8f5 and will be part of the next feature release.
