### ISSUE TITLE
Constant 403 Error

### ISSUE THREAD

**Issue by jamslatt** [BookStackApp/BookStack#393]
Nginx, Ubuntu 16.04 , PHP P 7.0.15

I keep trying to install BookStack, however, get the following error every time.
`2017/05/11 23:50:08 [error] 31172#31172: *1 directory index of "/var/www/wiki.doma.in/html/" is forbidden, client: 24.19.108.145, server: wiki.doma.in, request: "GET / HTTP/1.1", host: "wiki.doma.in"`

I have set the owner of the root directory to `www-data:www-data` and have set the specific directories to `775`. Not sure what the error is. Any ideas?

**Comment by domainzero** [comment]
Hey @jamslatt,

Looks like you have directory listings turned off in nginx which is producing that error.
In this case, it looks like nginx isn't pulling up the index.php to load the page so it's trying to display the directory instead.

Can you show me your nginx server block and directory layout?

**Comment by jamslatt** [comment]
I figured it out. Had the wrong root path in my config. Thanks!

**Comment by domainzero** [comment]
👌

**Comment by Shackelford-Arden** [comment]
@jamslatt Mind closing this as it is no longer an issue? :)
