### ISSUE TITLE
Selecting the destination path when copying or moving a book

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#3933]
### Describe the feature you'd like

Currently, the user can copy or move pages and chapters to another location anywhere in Bookstack, including other books in other shelves. Sometimes, we also need to copy or move a book somewhere else. But when we intend to copy the book, it is only possible to create a copy only in the same shelf; which is almost useless.
It would be great if we could create copies of books in destinations other than the same shelf.

### Describe the benefits this would bring to existing BookStack users

Sometimes a collection of information existing in a book should be transferred into another location and the book is long and detailed enough to make it difficult to copy each chapter separately; therefore, the option of moving the entire book sounds necessary.

### Can the goal of this request already be achieved via other means?

No; that is because of the current design of the software. If the user can copy and move pages and chapters, it seems logical for the user to be able to do the same things to the books.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

The pages and chapters can be moved to other locations, as it can be seen here.

![pagedest](https://user-images.githubusercontent.com/100111649/209768521-890a1826-f952-48a1-b195-2b0e34deb287.PNG)

![chapterdest](https://user-images.githubusercontent.com/100111649/209768625-75ab2210-ecb1-4d0d-8f15-fdef5df9d417.PNG)

But books cannot be moved to another shelf.

![bookdest](https://user-images.githubusercontent.com/100111649/209768678-7c4b6da6-dd22-40c1-85ed-8f5bbb5bc3c9.PNG)

**Comment by ssddanbrown** [comment]
The relationship between books and shelves is different to that between books and pages/chapters.
Books do not belong to shelves in the same way that pages/chapters belong to a book, hence we don't show selection options for this.

When a book is copied, it's relation to existing shelves will also be copied if the user has permission to edit the shelves involved.

While we could show shelf selection controls in this view, this introduces significant extra complexity to this view and widens the scope of this specific copy action and view, which is not something I'm too keen on.

The fundamental result can currently be achieved via other means by altering shelves after copying.

**Comment by merrime-n** [comment]
Thanks for your guide @ssddanbrown 
I understand the complexity of the view.
I didn't fully comprehend your point by "altering shelves after copying", though.
Are there any alternative solutions to this issue? Can we move/copy books to another shelves rather than just copying them into the same shelf where it already exists?

**Comment by ssddanbrown** [comment]
> Can we move/copy books to another shelves rather than just copying them into the same shelf where it already exists?

Not within the same action, but you can go to the desired shelves > Edit > Then add/remove/sort books as desired.

**Comment by merrime-n** [comment]
But by altering the shelf and selecting the desired book, it will create a duplicate version of the book. Therefore, if we apply any changes to the duplicate version, the main version of the book from which the duplicate is created will also be changed.
We need to make copies, not duplicates.

**Comment by ssddanbrown** [comment]
Then just copy the book first, then edit the shelves to add/remove the copied book from shelves as desired.

**Comment by merrime-n** [comment]
Please follow these steps to reproduce the problem:

1. Create a copy a book in shelf A.
2. Edit shelf B and import the copied version of the book from shelf A.
3. Change/Delete the copied version in shelf A.
4. The copied version in shelf B will be also changed/deleted.

Even if I "just copy the book first, then edit the shelves to add/remove the copied book ", these two versions are the same.

Consequently, I think this feature cannot be achieved by the current available means.

**Comment by ssddanbrown** [comment]
@okaeiz Just to re-iterate, books are not owned by shelves. Following your instructions, the book is changed in Shelf A and Shelf B because they are the exact same book. Adding to a shelf does not create a copy in any way. If you edit shelf A and remove the copied book, then you have a complete copy of the original book on separate shelves.

**Comment by ssddanbrown** [comment]
Since there's been nothing further to discuss on this, I'll go ahead and close it off.
