### ISSUE TITLE
duplicating pages & chapters into different books in other shelves

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#3934]
### Describe the feature you'd like

It is currently possible to duplicate books from other shelves; so it can be modified by different people in different shelves and the changes are made into both versions. But this is intended, because sometimes people should not have access to the entire book.
It is also possible to "move" or "copy" the chapters and pages to different locations; but this is not duplication; since the copied version is independent of the main one.
**What we need is**, however, being able to duplicate specific parts of a book to another book in another shelf.

### Describe the benefits this would bring to existing BookStack users

When the page & chapter is **duplicated** - and NOT copied or moved - different users can modify them without having access to other parts of the book. Furthermore, the versions are not independent. This is as if we are using Google Docs, where different people work on a single document. 

### Can the goal of this request already be achieved via other means?

No, because copying or moving the page or chapter is not a good idea and there will be no collaboration since the pages are independant.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

When editing shelves, we can import duplicates of book existing in another shelves. 

![bookdupl](https://user-images.githubusercontent.com/100111649/209771704-c7c1c065-923b-440e-a065-fd54f43c1964.PNG)

What we need is, a similar option when editing a book. So we can import duplicates of chapters & pages from other locations.

![Capture](https://user-images.githubusercontent.com/100111649/209772029-70cc1e69-803f-44b9-9d0e-c70d3db86662.PNG)

**Comment by ssddanbrown** [comment]
The fundamental request here is already covered by #1360 and #182 so I'm going to close this off as a duplicate.
