### ISSUE TITLE
Libraries or subchapters as additional categories

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#3935]
### Describe the feature you'd like

When the amount of information increases, sometimes the book should possess more classes than only chapters and pages.
On the other hand, sometimes the entire collection should be categorized in a new class, e.g. Libraries.
Therefore, the classes will be as follows:

Library > Shelf > Book > Chapter > Subchapter > Page

### Describe the benefits this would bring to existing BookStack users

When the data becomes has so many different components, it seems necessary to consider additional classes.

### Can the goal of this request already be achieved via other means?

No. Currently there are only 4 classes available and they are not sufficient.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request @okaeiz  but I'm going to close this off as this has been discussed in multiple issues previously, with https://github.com/BookStackApp/BookStack/issues/95 being the main/original one.
