### ISSUE TITLE
search in the attachments

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#3941]
### Describe the feature you'd like

Hello,

We are using BookStack v22.11.1.
We would like to be able to search the content of attachments (pdf, docs, docx...).

### Describe the benefits this would bring to existing BookStack users

Some documents are indexed and may be available in the search bar

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request but please [see my comment here](https://github.com/BookStackApp/BookStack/issues/3719#issuecomment-1245267949) for my view & response to such a feature.
We also already have #3767 which covers what I'd imagine to be the most popular format for this request, and covers the fundamental request of widening scope of indexing to attachments.
