### ISSUE TITLE
Admin: 404 Issue on Some Books, Chapters

### ISSUE THREAD

**Issue by Suddenflame** [BookStackApp/BookStack#3945]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have recently updated the Bookstack from 2.09 to 2.11 resulting in some books, chapters, and pages no longer being visible even though I am the admin. If I navigate to one of the pages directly it could work but click on the chapter will direct me to 404. Same issue with some books where the book is visible but the chapters and pages will not.

Some of the content of the error logs are from me attempting to fix it but was not successful.

A full restore of the VM back to 2.09 will be done to resolve the issue in meantime. Any assistance for why the error occurred in the first place would be most helpful.

### Exact BookStack Version

2.11

### Log Content

[laravel.log](https://github.com/BookStackApp/BookStack/files/10346225/laravel.log)
[Uploading error.log…]()

### PHP Version

7.4

### Hosting Environment

VM running RHEL 8.7 with Nginx

**Comment by ssddanbrown** [comment]
This has [previously been found](https://github.com/BookStackApp/BookStack/issues/3660) in scenarios where the database was not being migrated upon certain updates.
Running the `php artisan bookstack:regenerate-permissions` command, from the bookstack install directory, has usually solved this.

**Comment by Suddenflame** [comment]
Thanks that worked!
