### ISSUE TITLE
Configure the Hyperlinks to New Window as default

### ISSUE THREAD

**Issue by adriangalbincea** [BookStackApp/BookStack#3949]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi, is there a way to change the default hyperlink window to New Window instead of Current Window?

### Exact BookStack Version

v22.10.2

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Hi @adriangalbincea,
There is no in-built option for this but it can be achieved via adding the following code in the "Custom HTML Head Content" customization setting:

```html
<script>
	document.addEventListener('DOMContentLoaded', function() {
		var links = document.querySelectorAll('.page-content a');
		for (var i = 0; i < links.length; i++) {
			links[i].target = '_blank';
		}
	});
</script>
```

This custom hack is not officially supported but it should be quite stable and rarely ever break.

**Comment by adriangalbincea** [comment]
Many thanks @ssddanbrown 
I shall give it a try.

**Comment by adriangalbincea** [comment]
It works. Thanks!!!
