### ISSUE TITLE
Req to add New Translation Language

### ISSUE THREAD

**Issue by conanslash** [BookStackApp/BookStack#3953]
### Language to Add

Malay

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Ah, sorry, had totally missed this until looking over all language requests now.
Let me know if you're still keen to translation for Malay, and I'll look to add if so.

**Comment by ssddanbrown** [comment]
I'll assume this is longer desired so I'll close this off but feel free to still comment or open a new issue if you do still want to translate for Malay.
