### ISSUE TITLE
The functionality on the page does not work.

### ISSUE THREAD

**Issue by rekvit** [BookStackApp/BookStack#3958]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

The functionality on the page does not work. Books, pages are created, but code editors do not open. Personal account is not open. In the google chrome console, it writes a message: "Uncaught SyntaxError: Unexpected token "." Error in app.js". Composer and php migrate are fine. Downloaded the latest version of Bookstack from git. The log file does not display an error. Debug mode too.
The installation was completely carried out in accordance with the video on YouTube.
![Снимок](https://user-images.githubusercontent.com/73035939/211516293-1af75c7f-26c1-446c-a5e9-eb68b64256be.PNG)

### Exact BookStack Version

22.11.1

### PHP Version

8.1.12

### Hosting Environment

XAMPP

**Comment by ssddanbrown** [comment]
> Downloaded the latest version of Bookstack from git. 

Can you run `git status` from the command line, within your BookStack install directory and confirm/share the output?
Or, when you mention downloading via git, do you mean some other method that wasn't via the command line?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
