### ISSUE TITLE
Strange behaviour of horizontal line element when adding it inside a collapsible text box

### ISSUE THREAD

**Issue by SmartPhoneLover** [BookStackApp/BookStack#3963]
### Describe the Bug

The bug is related to the **horizontal bar** and **collapsible text box** elements:
![9385309i306](https://user-images.githubusercontent.com/42898749/211942188-1d992982-b8e2-4c93-9ae1-e12d6fe9fa25.png)

I have recorded a little video below, but I will try to explain it as well here.
When you add a horizontal bar and write text just before and after it, then close and save the changes to the page, all is fine. Also, when you enter that page again in edit mode, nothing changes, apart from what you want to add/modify this time.

Things changes when you add the horizontal line inside a collapsible text box.
After adding it inside them, close and save, and then enter again in edit mode, there's an extra space just before and after this line. So, now you have delete these extra spaces manually, every time you want to make any changes to that page.

**Note:** It's happening since many versions before this one, but I just thought it was a little bug that may be fixed in an upcomming release. That's why I didn't report it until now.

### Steps to Reproduce

**1.** Enter in edit mode, and add a Collapsible Text Box element.
**2.** Add a Horizontal Line element (or more) inside it, and write some text before/after it.
**3.** Save the page.
**4.** Open the previous page in edit mode again.
**5.** You will see the bug.

### Expected Behaviour

No extra blank spaces are created before/after the Horizontal Line element, when it's added inside a Collapsible Text Box.

### Screenshots or Additional Context

Video about the problem:

https://user-images.githubusercontent.com/42898749/211941807-7ca5dd40-d137-46d7-94c3-aced47843b04.mp4

### Browser Details

Firefox v108.0.2

### Exact BookStack Version

v22.11.1

### PHP Version

v8.0.25

### Hosting Environment

Docker container (linuxserver)
[https://github.com/linuxserver/docker-bookstack/pkgs/container/bookstack](url)

Using: latest (tag)

**Comment by SmartPhoneLover** [comment]
Just to come it up if it can be fixed.
No one noticed this bug? I think it's a bit annoying.

**Comment by ssddanbrown** [comment]
Thanks @SmartPhoneLover for reporting (although the multiple posts via 3 separate community channels was maybe a little much).

This has now been fixed in b5cc0a8e38848043295e3d1960b5a347432532dd and will be part of the next patch release.
