### ISSUE TITLE
Generating links on marking posts

### ISSUE THREAD

**Issue by CptGroot** [BookStackApp/BookStack#3966]
### Describe the Bug

If you mark a text in a post, a popup comes up with a link, this works perfectly. However, if you are in a table and select text from the third, fourth, etc. line there, the popup appears at the top of the table and only refers to the table and not to the marked section

### Steps to Reproduce

1. Create post
2. Create a table with multiple rows and columns
3. Highlight text in a column (e.g. line 8).
4. Popup with link appears at the top of the table
5. Call up the link
6. Contribution jumps to the head of the table and not to line 8

### Expected Behaviour

It should work like outside of a table, so that you can mark a text and get a link for exactly this point and when you call up the link, the contribution also jumps to the spot

### Screenshots or Additional Context

Normal view with the right link:
![normal](https://user-images.githubusercontent.com/115283625/212309742-d8d548bc-c488-4902-892d-c6aa18e090ab.png)

In a table:
![in a table](https://user-images.githubusercontent.com/115283625/212309745-e0b8bad1-fb9e-4060-917d-9b4b01783802.png)

### Browser Details

Firefox, Chrome, Edge (all in the newest version)

### Exact BookStack Version

v22.11.1

### PHP Version

PHP 8.0.24

### Hosting Environment

Ubuntu 22.04.1 LTS

**Comment by ssddanbrown** [comment]
Thanks for reporting @CptGroot, but the current behaviour is intentional and not considered a bug in current behaviour.
BookStack applies it's IDs, to mark blocks, (Which this systems and others use) to top-level items (In addition to nested headers if existing) of the document to keep the scope and targeting of these consistent and reasonable.
