### ISSUE TITLE
Bookstack hosted on Windows - cannot use user invite email to create user

### ISSUE THREAD

**Issue by vineetparikh** [BookStackApp/BookStack#3970]
### Describe the Bug

When I try to add new users, I see the option of either sending an invite to the user email so they can make their own password, or setting the password for the user myself. The first one "fails with an unknown error", but the second one works for now.

This isn't super urgent or anything, because I can just set a temp password and have them log in and change it with the second approach, but is there any way to understand why the first approach doesn't work?

### Steps to Reproduce

1. Go to create a new user
2. Check the "send user an email" and put in a valid email
3. Click "create user"

### Expected Behaviour

User should be created and I should have received an email to that address

### Browser Details

Windows 10 + Chrome

### Exact BookStack Version

BookStack v22.11.1

### PHP Version

8.2.0

### Hosting Environment

I have a Bookstack instance hosted on Windows 10 Pro + XAMPP (MySQL + PHP) using DuckDNS for external availability.

**Comment by ssddanbrown** [comment]
Hi @vineetparikh,
I would guess that email sending is failing in your environment.
You'll find more details regarding the error in the error log, which can be found following our [debugging docs](https://www.bookstackapp.com/docs/admin/debugging/). 
You'll also find a email test send option in the "Settings > Maintenance" area which can be used to test email sending and display relevant errors.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
