### ISSUE TITLE
Modifying the CodeMirror style will cause the markdown editor to also be modified

### ISSUE THREAD

**Issue by liuhuanshuo** [BookStackApp/BookStack#3974]
### Describe the Bug

If I add a custom style like below in the background (according to the official documentation)
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/seti.css"/>
<script>window.codeTheme='seti';</script>
```
The code box style of the page will be modified, it works fine
![](https://pic.liuzaoqi.com/picgo/202301151137743.png)

But the style of the markdown editor will also be modified synchronously, which is bad
![](https://pic.liuzaoqi.com/picgo/202301151138256.png)

### Steps to Reproduce

It happens as long as you modify the relevant styles such as .cm-s-seti.CodeMirror, it seems that the code block and the editor use overlapping CSS

### Expected Behaviour

fix it

### Exact BookStack Version

V22.11.1

### Hosting Environment

docker compose

**Comment by ssddanbrown** [comment]
Hi @liuhuanshuo, This is actually intended and not a bug in existing functionality.
The markdown editor is considered a code editor and is also a codemirror instance.

If you really don't want this, you may be able to work around this by resetting the theme for the markdown editor by adding the below to the "Custom HTML Head Content" setting:

```html
<script>
window.addEventListener('editor-markdown-cm::pre-init', event => {
  const cmConfig = event.detail.config;
  cmConfig.theme = 'default';
});
</script>
```
