### ISSUE TITLE
Image Id is not set to zero after avatar is deleted.

### ISSUE THREAD

**Issue by ondrejpazourekdek** [BookStackApp/BookStack#3977]
### Describe the Bug

After resetting the avatar should be in the table image_id set to 0.
```
// BookStack\Http\Controllers\UserController
if ($request->has('profile_image_reset')) {
    $this->imageRepo->destroyImage($user->avatar);
    $user->image_id = 0; // added
    $user->save(); // added
}
```

### Steps to Reproduce

Delete the avatar and check the users table.

### Expected Behaviour

Zero in column image_id

### Exact BookStack Version

22.11.1

### Hosting Environment

does not matter

**Comment by ssddanbrown** [comment]
Thanks for reporting @ondrej-pazourek,
this has been addressed in 03ad288aaa55a0bd0aa143711aa07d0f1801d604, and will be part of the next feature release.
