### ISSUE TITLE
TinyMCE add headlines or paragraphs

### ISSUE THREAD

**Issue by nheimsath-gudat** [BookStackApp/BookStack#3979]
### Describe the feature you'd like

Adding a headline or a block/paragraph type to the TinyMCE editor. 

### Describe the benefits this would bring to existing BookStack users

Many markdown texts support H6 Headlines , and having the option to add  another type of paragraph, or maybe those colored boxes, would allow to filter out some parts of the document later in Weasyprint.  

### Can the goal of this request already be achieved via other means?

Almost completet in #3453,   but to be true i have no idea on how to add stuff via this event listener as i am not into Javascript. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

In general it would be helpfull to have some examples/tutorials on how to add remofe stuff in the TinyMCE.

**Comment by ssddanbrown** [comment]
Thanks for the request @nheimsath-gudat but the fundamental idea has previously been requested in  #1241 and my thoughts on this can be found [in my comment in that thread](https://github.com/BookStackApp/BookStack/issues/1241#issuecomment-1025142712). My feelings remain the same in that I don't want to officially support custom editor content types so I'm going to therefore close this off.
