### ISSUE TITLE
How to update properly?

### ISSUE THREAD

**Issue by TribuneX** [BookStackApp/BookStack#398]
What is the proper way to update BookStack to the latest release? 
I executed the steps listed in the [installation doc](https://www.bookstackapp.com/docs/admin/installation/), but got errors in the end. Therefore, I did a fresh install while reusing my database.

**Comment by yoginth** [comment]
Just copy and paste the new commits instead of updating in CLI.

**Comment by AbijeetP** [comment]
@TribuneX  - Would be good to know what errors you got after the update.

**Comment by TribuneX** [comment]
Will do next time. Unfortunately, I do not have the version with errors any more, since I installed from scratch. 

Looking at my Google history, errors like those showed up: 
https://github.com/laravel/framework/issues/17377

**Comment by Shackelford-Arden** [comment]
@TribuneX To update use [these instructions](https://www.bookstackapp.com/docs/admin/updates)

**Comment by ssddanbrown** [comment]
Thanks @Shackelford-Arden.

@TribuneX Feel free to continue this discussion if you have any issues running the official update instructions as linked above otherwise I'll close this issue for now.
