### ISSUE TITLE
Auto sort pages and chapters

### ISSUE THREAD

**Issue by mschoon85** [BookStackApp/BookStack#3980]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi @ssddanbrown ,

Is there a way to auto sort pages and chapters in alphabetical order? It's very annoying that the newly created pages and chapters are listed at the bottom and the users have to sort them manually every single time.

Kind regards,

Michel

### Exact BookStack Version

22.11.1

### Hosting Environment

Windows, Apache

**Comment by ssddanbrown** [comment]
@mschoon85 There is not such functionality built-in by default (Without restoring to hacking options via custom PHP).
This functionality is already open in #2065 so I'm going to close this off as a duplicate.
