### ISSUE TITLE
users mention and task manager

### ISSUE THREAD

**Issue by eoli3n** [BookStackApp/BookStack#3984]
### Describe the feature you'd like

I would like to be able to mention a user in the way of : "@user"
This is the minimal feature.

The complete feature would be to be able to detect if mentions are on a checkbox line, then create a menu in each user account, to list "checked" tasks as finish, and "unchecked" tasks as todo.

Even better, possibility to add a entire module which creates a table with task status tracking.
Like that one : https://www.dokuwiki.org/plugin:task

### Describe the benefits this would bring to existing BookStack users

Possibility to manage tasks in a wiki is a killer feature.
You could then follow project roadmap like

- [x] @user read that feature request : 21-01-2023
- [ ] @user code that feature request : 21-01-2023

or

| Who | When | What | State |
|---|---|---|---|
| @user | 21-01-2023 | read that feature request | done |
| @user | 21-01-2023 | code that feature request | todo |

### Can the goal of this request already be achieved via other means?

Not really.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request @eoli3n.
I'm going to close this off though for the following reasons:

- Issues already exist to cover the functionality of mentioning users (#953, #560).
- Two-part/request issues are hard to manage.
- The secondary task manager part is something I'd probably view as out of scope really as I don't want to spread our focus into what really is are todo or project management responsibilities.
