### ISSUE TITLE
Feature Request: Copy book or template function

### ISSUE THREAD

**Issue by mgjohansen** [BookStackApp/BookStack#399]
### Feature Requests

Desired Feature: The ability to create a template or a template book that you can copy/use so you don't have to create a book from scratch each time with the same format being used for standard documentation.

**Comment by Shackelford-Arden** [comment]
Hmm. Not sure if this is the same as #129 ? Even if they're not the same, I'd think of merging the two to simply cover "templates" in general. Template Books/Pages. Just a thought...

Aside from that, I agree! I know there are some who have standards that would benefit from having templates to start from.

**Comment by mgjohansen** [comment]
@Shackelford-Arden Sorry, did not see that! Searched and did not find any. 

Yes I agree, same functionality I'm asking for in this one.

**Comment by Shackelford-Arden** [comment]
no worries ^_^ @mgjohansen

**Comment by ssddanbrown** [comment]
Thanks @Shackelford-Arden for looking over this.
