### ISSUE TITLE
Bookstack roles customization for individual shelves

### ISSUE THREAD

**Issue by sachinvishwakarma26** [BookStackApp/BookStack#3991]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi Team,

We are trying to implementing custom authorization for bookstack members to access individual shelves via custom role. The current bookstack configuration doesn't provide an option to implement via custom shelves role access for the member s to login and access the shelves. Please provide a solution to achieve this use case for project requirement.

I would appreciate your faster response. 

Thanks,
Sachin

### Exact BookStack Version

v22.11.1

### PHP Version

7.4

### Hosting Environment

Amazon Linux 2

**Comment by ssddanbrown** [comment]
Hi @sachinvishwakarma26,
I'm not sure I understand exactly what you require.

We allow setting role-based permission on shelves, books, chapters and pages.
We do not allow multiple authentication methods to be used and/or combined on a per-role basis, and this is something we're likely never implement.

If you're doing this to strictly segment the system content into different role groups, and desire different options and authentication for those groups, I'd advise using multiple Bookstack instances instead.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up or discussion I'll close this off.
