### ISSUE TITLE
Can't change settings, open user panel or add image to book

### ISSUE THREAD

**Issue by WerWolv** [BookStackApp/BookStack#3996]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi
I tried installing Bookstack using docker-compose and the latest linuxserver/bookstack image. For the most part this worked fine and I managed to access my instance, change my credentials and create a new Shelf and Book. However I ran into a few issues from there. First I wanted to grant Public Access to the instance through the setting, however checking any of the checkmarks there and clicking on Save Settings simply resets the checkboxes back. I managed to manually force them on by modifying the relevant fields in the database which suggests that somehow the frontend can't communicate with the database correctly? Other things like creating books and modifying users worked however.
After that I noticed that clicking on the top right button with my username on it, doesn't do anything and also other buttons like the one that lets you upload a cover image for a book simply don't do anything.

I searched through all the log files mentioned in the documentations but none of them had any real errors or anything in them so I'm kinda lost.

### Exact BookStack Version

v22.11.1-ls60

### Log Content

The only error-like thing I could find was this here from the database logs:

```
Version: '10.6.10-MariaDB-log'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
2023-01-25 20:10:21 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: 'localhost' (This connection closed normally without authentication)
2023-01-25 20:10:23 6 [Warning] Aborted connection 6 to db: 'unconnected' user: 'unauthenticated' host: 'bookstack.documentations_default' (This connection closed normally without authentication)
2023-01-25 20:12:24 20 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
```

### PHP Version

8..1.14

### Hosting Environment

Arch Linux VPS - BookStack running inside of a Docker container setup using the docker-compose file from https://github.com/linuxserver/docker-bookstack

**Comment by ssddanbrown** [comment]
@WerWolv 👋 Any chance you're running your instance behind Cloudflare proxy DNS?

**Comment by WerWolv** [comment]
@ssddanbrown Hey! I am indeed, I didn't expect this to cause any issues. Is there anything I can do about that?

I tried changing the CNAME DNS record to DNS only now (disabling the Proxy) but it still didn't work

**Comment by ssddanbrown** [comment]
@WerWolv Okay, awesome, it's probably rocket loader. Can you [find and disable rocket loader](https://developers.cloudflare.com/fundamentals/speed/rocket-loader/enable/) in cloudflare, it causes issues with BookStack's script. 

> I tried changing the CNAME DNS record to DNS only now (disabling the Proxy) but it still didn't work

You sure you're now connecting directly? DNS is heavily cached at many layers. Try enabling again with disabled rocket loader.

**Comment by WerWolv** [comment]
Disabling Rocket Loader fixed it thank you so much! That would have been the absolute last place I would have looked
