### ISSUE TITLE
Document preview

### ISSUE THREAD

**Issue by mschoon85** [BookStackApp/BookStack#3997]
### Describe the feature you'd like

Hi @ssddanbrown 

I am requesting the implementation of a document preview feature for attachments such as PDF, DOC, DOCX, PPT, etc. on pages. For example:

![image](https://user-images.githubusercontent.com/96066244/214868673-ea425c1b-0e6f-47e0-a540-ee201d0a20d7.png)

Kind regards,

Michel Schoonderwaldt

### Describe the benefits this would bring to existing BookStack users

Users can avoid the need to download and open multiple documents by searching for the correct one before deciding which to open.

### Can the goal of this request already be achieved via other means?

Not that i'm aware

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request but this has been requested a few times already, with the main thread being the open issue #705. 
Although #705 doesn't directly cover office formats, I'd generally consider supporting the rending of office formats out of scope for the core codebase of this platform. Will therefore close this off.
