### ISSUE TITLE
Checkable checkboxes within pages

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#4]
Allow the Creation of checkboxes within pages which users can then use when going down a list. (No state saving)

**Comment by cgpro** [comment]
+1

Very handy feature for 2do lists!

**Comment by bridgeyuwa** [comment]
+1

**Comment by cgpro** [comment]
resources/assets/js/pages/page-form.js

**replace line 16:**
`toolbar: "undo redo | styleselect | bold italic underline strikethrough superscript subscript | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table image-insert link hr | removeformat code fullscreen | checker",`


**add after line 162:**
`// Add checkbox
editor.addButton('checker', {
            text: 'Checkbox',
            icon: false,
            onclick: function () {
                editor.insertContent('<label><input type="checkbox" name="checkbox" value="value">Text</label>');
            }
        });
`

Can't test it... :( the scripts have to be recompiled.

**Comment by tgrosinger** [comment]
I agree that this would be an awesome feature to have. It looks like a potential solution has been proposed. 

Can I bump this and hopefully get a maintainer to test out that solution?

**Comment by mainmachine** [comment]
Was this ever implemented...?

**Comment by ssddanbrown** [comment]
@mainmachine Nope, Not yet.

**Comment by mainmachine** [comment]
> @mainmachine Nope, Not yet.

Darn! Thanks for the quick response and all your work on Bookstack! :)

**Comment by lpadula** [comment]
Hi, any update of this?

**Comment by LaetzPlaey** [comment]
Hey,
this function is essential for us. Would be great :)

**Comment by MrXermon** [comment]
Hey,
would be great to have this implemented!

**Comment by yblis** [comment]
It would be great to have this feature!

**Comment by lpadula** [comment]
checkboxes are working on the markdown mode, but not in the HTML mode :(

**Comment by ssddanbrown** [comment]
This is heavily tied to editor functionality so will be realistically be blocked by #2738. Might or might not be part of that, but will be blocked beforehand either way.

**Comment by ssddanbrown** [comment]
With the merge of #3333 checkbox task-lists are now available/possible within the WYSIWYG editor. 
The implementation differs a little to what was originally thought out here, with the checkbox state being disabled on view but editable via page editor. This was to align and remain compatible with the existing markdown editor task-list implementation. If needed, you could sprinkle a little "Custom HTML Head Content" javascript to not have the disabled state for view.

These changes will be part of the next feature release.

**Comment by DhrRob** [comment]
> If needed, you could sprinkle a little "Custom HTML Head Content" javascript to not have the disabled state for view.

I made this script which you can add in the head content through the admin panel. Feel free to use.
It disables the `disabled` state of the checkbox inputs.

```<script>
function undisabled() {
	var inputs = document.querySelectorAll('input[type=checkbox]');
	for(var i = 0; i < inputs.length; i++) {
		inputs[i].disabled = false;
	}

	console.log('done');
}

document.addEventListener("DOMContentLoaded", function(event) { 
    undisabled();
});
</script>

**Comment by BloodyIron** [comment]
> > If needed, you could sprinkle a little "Custom HTML Head Content" javascript to not have the disabled state for view.
> 
> I made this script which you can add in the head content through the admin panel. Feel free to use. It disables the `disabled` state of the checkbox inputs.
> 
> ```
> function undisabled() {
> 	var inputs = document.querySelectorAll('input[type=checkbox]');
> 	for(var i = 0; i < inputs.length; i++) {
> 		inputs[i].disabled = false;
> 	}
> 
> 	console.log('done');
> }
> 
> document.addEventListener("DOMContentLoaded", function(event) { 
>     undisabled();
> });
> </script>
> ```

This works for me, except I needed to add "<script>" to the beginning as you forgot to put that XD

Also, take note this check-ing of the box is temporary to the page session. Refreshing and such undoes it. But still seems to help! Thanks! :D

**Comment by CDubs00** [comment]
> > > If needed, you could sprinkle a little "Custom HTML Head Content" javascript to not have the disabled state for view.
> > 
> > 
> > I made this script which you can add in the head content through the admin panel. Feel free to use. It disables the `disabled` state of the checkbox inputs.
> > ```
> > function undisabled() {
> > 	var inputs = document.querySelectorAll('input[type=checkbox]');
> > 	for(var i = 0; i < inputs.length; i++) {
> > 		inputs[i].disabled = false;
> > 	}
> > 
> > 	console.log('done');
> > }
> > 
> > document.addEventListener("DOMContentLoaded", function(event) { 
> >     undisabled();
> > });
> > </script>
> > ```
> 
> This works for me, except I needed to add "<script>" to the beginning as you forgot to put that XD
> 
> Also, take note this check-ing of the box is temporary to the page session. Refreshing and such undoes it. But still seems to help! Thanks! :D

Anyway to make the checking of the box permanent in this view?

**Comment by msizec** [comment]
checkboxex for todo lists not implemented yet right ?

**Comment by ssddanbrown** [comment]
@msizec Todo lists with checkboxes were added in 2022 as mentioned above:

![image](https://github.com/user-attachments/assets/396a5f72-4b3f-4eb6-b090-18b4c1ca0e20)

They're only checkable in editor mode (unless you apply additional customization).
