### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Nixellion** [BookStackApp/BookStack#400]
I'm trying to install BookStack using these Instructions (https://www.bookstackapp.com/docs/admin/installation/) on Ubuntu 16.04 LTS and I get an error while running `php artisan key:generate` and\or `php artisan migrate` commands.

```
PHP Warning:  require(/var/www/bookstack/BookStack/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/bookstack/BookStack/bootstrap/autoload.php on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/bookstack/BookStack/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/bookstack/BookStack/bootstrap/autoload.php on line 18
```

Do I need to perform some additional steps to set this up?

**Comment by Shackelford-Arden** [comment]
@Nixellion I feel like I've run into this myself before... but I can't remember exactly what I needed to do.

My go to reason for most errors though is permissions haha. I looked through the script and pulled out what Dan does to the respective folders in 4 of the instructions.

```
chown www-data:www-data -R bootstrap/cache public/uploads storage 

chmod -R 755 bootstrap/cache public/uploads storage
```

It does look like though that the error is occurring within PHP. Are all of the dependencies installed?

**Comment by ssddanbrown** [comment]
Yeah, My guess is that the dependencies have not been installed with composer since it's looking inside the `vendor` file in that 'No such file' error.  Running the following will install composer then install BookStack dependancies:

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
php composer.phar install
```

**Comment by Shackelford-Arden** [comment]
@Nixellion Did the commands that Dan posted above work to resolve your problem?

**Comment by Nixellion** [comment]
I actually went with dokuwiki for the time being, but I will try to install bookstack again alongside that, when I have some time for that, and try these commands out!

Thanks for the tips!

**Comment by ssddanbrown** [comment]
@Nixellion Okay, Cool. I'll close this for now then but if you have trouble when retrying feel free to comment again and I'll re-open this.

**Comment by BirenGroove** [comment]
Hi @ssddanbrown 
I getting same error but i have radhat system, there is no user **www-data:www-data** we have Nginx user I gave him all right like bookstack folder right and I installed composer with root user then gave ownership to Nginx user but still is same error I run **composer** I getting welcome page of composer I am not sure what I am doing wrong

**Comment by ssddanbrown** [comment]
@BirenGroove please open a new issue, following the issue template, with detail of your system and the exact error message you are getting.

**Comment by sinan-lab** [comment]
Hi @ssddanbrown, 
I got the same error too. I ran the above commands but my problem still persists. How can i solve it?

**Comment by ssddanbrown** [comment]
@sinan-lab Please see my previous message above yours.
The commands listed above are 4 years old and may not work as expected now.
