### ISSUE TITLE
Add user profile and link to contact user

### ISSUE THREAD

**Issue by gblondet117** [BookStackApp/BookStack#4000]
### Describe the feature you'd like

Hello,

i am working on a knowledge base with bookstack for my company, but i think something is missing (or i missed something).

I have seen [this issue](https://github.com/BookStackApp/BookStack/issues/1859) concerning user profile, but i would like to get more. In order to get a full knowledge base, I have to link pages, concepts, things,  with people. Users should be able to find people to get a solution : who i could contact to solve my problem, who is the expert, and so on.

I suggest, for instance, the development of : 
- a specific kind of page to describe the user ;
- a fast way to create link to a user's page, for instance @johnDoe, in pages ;
-  in the user's page, get a list of pages in which the user is cited , to know what he is doing.

Sorry if this issue was already adressed, but i have not seen comparable requests yet. 

### Describe the benefits this would bring to existing BookStack users

A part of knowledge cannot be written in a book, and new problem occur. The best solution is to find relevant people to get a solution. This kind of feature would improve communication in a company and shorten problem solving processes.

### Can the goal of this request already be achieved via other means?

I don't know.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @gblondet117, and congrats on being the 4000th GitHub issue on this project! :tada:

If feel that between issues #560 and #1859, the fundamental requirements you have are already covered and therefore I'm going to close this off as a duplicate.
There's no exiting issue for having a list of mentions, but that would be an addition to being able to notify so not really in scope to be it's own issue before mentions (#560), or something similar, has been implemented.
