### ISSUE TITLE
Feature Request: Search and Ranking needs improvement

### ISSUE THREAD

**Issue by jimmyc802** [BookStackApp/BookStack#401]
We are fully updated to the latest release at the time of submitting this feature request (16.2)

Desired Feature: 
Search ranking of results should add significant weight to matches on names of books, chapters, pages, and headings within pages. This should be the case without having to mess with advanced search or search filters.

Why this is a problem:
Right now the search result rankings don't make a ton of sense and is frustrating users. Some use cases:

A. User Joe wants to find our internal documentation for Tableau server. They first search **tableau server** (no quotes). The top the result is a page containing tons of instances of the word "server" but no instances of the word "tableau" or combination of "tableau server". Towards the bottom of the search results is an actual chapter titled "Tableau Server".

B. User Joe is now frustrated with not finding many results towards the top relevant to tableau server, so they add quotes and search for **"tableau server"**. The top result is now a page with one instance of "tableau server" in the content. The second result has 12 instances of "tableau server". The third result has "tableau server" in the title and 7 instances in the content. Halfway down the results page, is a chapter titled  "Tableau Server" with lots of pages also containing "tableau server" in their titles.

Why were these rankings chosen? It's certainly an improvement over version 15 but still has a long way to go. I know, I know, I should just contribute to the project, but I don't have time for that, hence the feature request.

**Comment by Shackelford-Arden** [comment]
@jimmyc802 Just curious (I'm still learning things haha) but are the pages tagged at all with "tableau" or "tableau server"? I'd think that the tags would help with the search to some extent. But... I do not fully understand how the tagging is implemented.

**Comment by ssddanbrown** [comment]
> Why were these rankings chosen?

Because they were an initial implementation of a revamped custom search solution. Names are given more weight over content but maybe that needs to be tweaked up a notch. Adding weight to headings is a good idea. 

Overall it's just about balancing performance vs search indexing 'depth'.

**Comment by nvnvnvnvn** [comment]
Curious as to status of this.  We have titles with spindle in it, but they show up at the bottom of the search:
https://support.machmotion.com/search?term=spindle

It seems like titles with the word should show up higher.  We are on V22 but I don't see this as being identified in V23 or 24.

**Comment by ssddanbrown** [comment]
I'm now going to close this off, Primarily due to the changes in #3043 which were part of v21.11 which included tweaking up the name weighting and adding weight to content headings.
