### ISSUE TITLE
Translation issue for Dutch language

### ISSUE THREAD

**Issue by mschoon85** [BookStackApp/BookStack#4015]
### Describe the Bug

Hi @ssddanbrown 

I found a translation issue for the Dutch language. When deleting a chapter the translation is that you are going to delete a book instead:

```
Dutch:
Dit verwijdert het hoofdstuk met de naam 'Test Chapter'. Alle pagina's die binnen dit hoofdstuk staan, worden ook verwijderd.

Weet je zeker dat je dit boek wilt verwijderen?
```

```
English (Google translate):
This will delete the chapter named 'Test Chapter'. All pages within this chapter will also be deleted.

Are you sure you want to delete this book?
```

The word **boek** needs to be: hoofdstuk

Kind regards,

Michel

### Steps to Reproduce

1. delete a chapter with the Dutch language enabled

### Expected Behaviour

boek needs to be chapter

### Exact BookStack Version

23.01

### Hosting Environment

Windows Server 2022 with Apache

**Comment by ssddanbrown** [comment]
Thanks for raising @mschoon85, but translation text is primarily managed via https://crowdin.com/project/bookstack.
You should be able to just sign-up there and then address the translation directly. It would then be automatically pulled into BookStack in a future release. 
Would you be willing to address this directly via Crowdin?

**Comment by mschoon85** [comment]
Yes of course @ssddanbrown. I will do that right away. Thanks (again)!

**Comment by mschoon85** [comment]
I have added the translation on Crowdin. Thanks!

**Comment by ssddanbrown** [comment]
Awesome, thanks @mschoon85 for contributing!
The changes may take a little while before they hit a release. Sometimes I merge soon into a patch release but often it'll be merged for the next major/feature release.
Will therefore close this off.
