### ISSUE TITLE
PHP Warning:  Module "intl" is already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by mschoon85** [BookStackApp/BookStack#4017]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi @ssddanbrown,

I installed the security update released today, but upon running the php artisan command for cleanup I got a few warnings. Can this do any harm?

```
D:\Apache24\htdocs\bookstack>php artisan cache:clear
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
Application cache cleared!

D:\Apache24\htdocs\bookstack>php artisan config:clear
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
Configuration cache cleared!

D:\Apache24\htdocs\bookstack>php artisan view:clear
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
Compiled views cleared!

```

Kind regards,

Michel

### Exact BookStack Version

23.01.1

### Hosting Environment

Windows Server 2022 with Apache

**Comment by mschoon85** [comment]
I update again via GIT and see these errors are not only when clearing the cache:

```
D:\Apache24\htdocs\bookstack>composer install --no-dev
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-snappy
Discovered Package: intervention/image
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: socialiteproviders/manager
Package manifest generated successfully.
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan cache:clear
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
Application cache cleared!
> @php artisan view:clear
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
Compiled views cleared!
```

**Comment by mschoon85** [comment]
We have made a snapshot of the system, so we can go back to the previous version easily. Let me know if we should do that, or we can solve this another way.

**Comment by ssddanbrown** [comment]
Those warnings don't appear to stop the commands being run at all, so might be fine, although they're not ideal.
Those will be specific you your configuration/environment, not really anything on BookStack's side as far as I could tell.

**Comment by mschoon85** [comment]
I panicked to soon. Sorry about that. I asked my new best friend ChatPGT about it and it came with the following answer:

/////////////////////
The error message "Module "intl" is already loaded in Unknown on line 0" means that the Internationalization extension (intl) has already been loaded in your PHP environment and cannot be loaded again. This extension provides localization functions for PHP.

In most cases, you do not need to resolve this error message as it is a warning message, not a critical error. However, if you are encountering this message while installing a PHP extension that requires the intl extension, you should make sure that the intl extension is installed and enabled in your PHP environment.

You can verify if the intl extension is installed by checking the output of the following command: php -m

This will list all installed PHP modules. If you see "intl" in the list, then the extension is installed.
/////////////////////

So nothing to worry about. It is just that intl is already loaded because this plugin is enabled in my php.ini file, and cannot be loaded twice.
