### ISSUE TITLE
Update to the latest bookstack with docker

### ISSUE THREAD

**Issue by Thom087** [BookStackApp/BookStack#4022]
### Describe the Bug

Updating to the latest mariadb and docker image provided from linuxserver gives me the following error message:

bookstack       |   SQLSTATE[HY000] [1045] Access denied for user 'bookstack_User_DB'@'bookstack.wiki_default' (using password: YES) (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')
bookstack       |
bookstack       |   at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
bookstack       |     708▕         // If an exception occurs when attempting to run a query, we'll format the error
bookstack       |     709▕         // message to include the bindings with SQL, which will make this exception a
bookstack       |     710▕         // lot more helpful to the developer instead of just the database's errors.
bookstack       |     711▕         catch (Exception $e) {
bookstack       |   ➜ 712▕             throw new QueryException(
bookstack       |     713▕                 $query, $this->prepareBindings($bindings), $e
bookstack       |     714▕             );
bookstack       |     715▕         }
bookstack       |     716▕     }
bookstack       |
bookstack       |       +33 vendor frames
bookstack       |   34  /app/www/artisan:37
bookstack       |       Illuminate\Foundation\Console\Kernel::handle()
bookstack       | [custom-init] No custom files found, skipping...
bookstack       | [ls.io-init] done.

Previous versions were bookstack: version-v22.1 and mariadb: 10.6.9

### Steps to Reproduce

Update docker-compose.yml file with the bookstack version v22.1.1 or v23.01.1
sudo docker-compose up -> gives then the error

### Expected Behaviour

Normally it should come up smoothly and everything works fine, as it did the last 2 years.

### Exact BookStack Version

23.01.1

### Hosting Environment

Docker on Ubuntu

**Comment by ssddanbrown** [comment]
This sounds like the same thing as issue #3940. You can view that thread for further detail and possible solutions.
It would also help, if possible, if you could comment in that thread and confirm what special characters (If any) were used in the database password.
