### ISSUE TITLE
Search entity slow

### ISSUE THREAD

**Issue by RossiNIT** [BookStackApp/BookStack#4024]
### Describe the Bug

The entity search is slow or blocked.
When I move, copy a page or link an entity to another, the window where I select the destination entity is stucked on the three dots and no entity is showed.
![image](https://user-images.githubusercontent.com/118269033/217199780-177ca531-c8cb-44ca-98f4-9bb4de9a7b1a.png)

### Steps to Reproduce

Go to a page
Click on move or copy

### Expected Behaviour

On the window to select the destination entity, I should see a list of avayable entity.

### Exact BookStack Version

BookStack v23.01.1

### Hosting Environment

Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-19-amd64

**Comment by ssddanbrown** [comment]
Hi @RossiNIT,

- Does the main header search bar work okay? 
  - Does the results change as you search different queries?
- Did you follow a particular guide to install BookStack?
- What webserver are you using?

**Comment by RossiNIT** [comment]
Hi @ssddanbrown,

Here I'll try to aswer to your question:

- The search bar in the header work well
- To install Bookstack I followed the guide on the [website](https://www.bookstackapp.com/docs/admin/installation/#manual)
- Bookstack is hosted on a Debian GNU/Linux 11

**Comment by ssddanbrown** [comment]
@RossiNIT Thanks for the information:

- Are you using Nginx or Apache or something else?
- When you view a book, there's a search-bar in the sidebar. Does this book-specific search-bar work without issue?

**Comment by RossiNIT** [comment]
- I'm using Apache2
- The serach bar on the side is perfectly working

It seem like the only serach that not work is the search entity when I need to link a page to another.

PS: Thanks for your attention

**Comment by ssddanbrown** [comment]
@RossiNIT Okay, thanks.

Are you familiar with browser development tools at all? It would help to see any if any errors show in the console when you run into the issue.
If not, please let me know what browser and operating system you're using to browse BookStack and I'll try and provide some guidance when possible.

**Comment by RossiNIT** [comment]
Yep, I'm working in IT sector.
Here is the screen of the errors in the console. These errors are generated on page load; when the window for choosing the entity is opened, however, no further messages are shown.
I'm working on chrome, but also in other browser the result is the same.

![image](https://user-images.githubusercontent.com/118269033/217738007-b155ac2b-0d9e-4d35-b429-2bad6a72afe6.png)

```
DevTools failed to load source map: Could not load content for http://intranit/dist/styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://intranit/dist/print-styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://intranit/dist/app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
app.js?version=v23.01.1:25          GET http://intranit/search/entity-selector?types=book%2Cchapter%2Cpage&permission=view 404 (Not Found)
Gs @ app.js?version=v23.01.1:25
zd @ app.js?version=v23.01.1:25
initialLoad @ app.js?version=v23.01.1:26
setup @ app.js?version=v23.01.1:26
Wd @ app.js?version=v23.01.1:25
So @ app.js?version=v23.01.1:25
(anonymous) @ app.js?version=v23.01.1:50
app.js?version=v23.01.1:25 Uncaught (in promise) Error: Not Found
    at Gs (app.js?version=v23.01.1:25:1404)
Gs @ app.js?version=v23.01.1:25
Promise.then (async)
initialLoad @ app.js?version=v23.01.1:26
setup @ app.js?version=v23.01.1:26
Wd @ app.js?version=v23.01.1:25
So @ app.js?version=v23.01.1:25
(anonymous) @ app.js?version=v23.01.1:50
DevTools failed to load source map: Could not load content for http://intranit/dist/print-styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://intranit/dist/styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://intranit/dist/code.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by ssddanbrown** [comment]
That's very strange, I can't see anything within the route itself that would provide a 404 for that endpoint.

- By any chance have you added additional apache config? Anything that could trigger on a keyword like `permission` or `selector` ?
- Would you be able to screenshot the exact view you see when visiting `http://intranit/search/entity-selector?types=book%2Cchapter%2Cpage&permission=view` directly in the browser?
- Same as above but for just `http://intranit/search/entity-selector`

**Comment by RossiNIT** [comment]
I not changed anything with apache. I have a clean VM on the server deticated only for bookstack, I installed bookstack via the instructions on your website and it work fine. After the last update the only things that doesn't work is the search entity when editing a page.
Here is the screen of the link `http://intranit/search/entity-selector?types=book%2Cchapter%2Cpage&permission=view`, the same is for `http://intranit/search/entity-selector`.

![Immagine 2023-02-10 141343](https://user-images.githubusercontent.com/118269033/218105325-dd12499b-ebe0-4ed9-b218-37004d4090c1.png)

**Comment by ssddanbrown** [comment]
What's the output of running `ls -alh bootstrap/cache` from your BookStack install directory?

**Comment by RossiNIT** [comment]
Here the output:

![Immagine 2023-02-13 151254](https://user-images.githubusercontent.com/118269033/218481659-67d72ccd-97ef-41a4-9cc4-1ef1f138a070.png)


In addition, always on 23.01.1 version, there are other error: on the dark or white theme button, list view and other, when click, the program call an exception and print it.

Hoping you find a solution for theese error, many thanks!

**Comment by ssddanbrown** [comment]
@RossiNIT Okay, looks like a route/optimization command was ran back in October which could lead to strange behaviour upon changes such as updates.
Please delete all `.php` files from the `bootstrap/cache` directory.

**Comment by RossiNIT** [comment]
Just deleted and all work fine now!

Thank you!
