### ISSUE TITLE
Uploaded images not shown when no pages have been saved yet

### ISSUE THREAD

**Issue by stebit** [BookStackApp/BookStack#4028]
### Describe the Bug

Bookstack does not show any uploaded pictures in the 'Image Select' popup before any page has been saved on the installation, even though the uploaded pictures appear on the filesystem. The uploaded pictures appear after saving and reopening the page.

I installed Bookstack with docker-compose and podman; with bind-mount, volumes and without any storage specified. It has always behaved the same.

When you know this behaviour it is not a big deal, mainly posting this for others who might encounter the same thing.

### Steps to Reproduce

1. Install bookstack (with docker-compose or podman).
2. Create a new book.
3. Create a new page, do NOT save.
4. Upload an image; it will be saved on disk, but not shown on 'Image Selector' popup.

### Expected Behaviour

Pictures are shown in image selection popup, even before saving for the first time.

### Screenshots or Additional Context

before saving the first page created on the installation
![before saving the first page created on the installation](https://user-images.githubusercontent.com/93426409/217478398-42d53979-41c6-4d04-894e-5d1c9d70b9f5.png)

after saving and reopening the page
![after saving and reopening the page](https://user-images.githubusercontent.com/93426409/217478502-25c7baeb-f04f-401c-8018-dd1c1c6886eb.png)

### Exact BookStack Version

v23.01.1

### PHP Version

8.2

### Hosting Environment

Debian 11 VPS, docker-compose & podman

**Comment by ssddanbrown** [comment]
Thanks for reporting this @stfeb, Can confirm.
Now a few other recent less-clear image upload issue reports make sense :sweat_smile: 

Have assigned to be addressed for next feature release.

**Comment by ssddanbrown** [comment]
Addressed within 08b39500b3b27181a7a1a0e4ee51dabce45673c2. Will be part of the next feature release. 
Thanks again @stfeb for reporting.
