### ISSUE TITLE
Site Style not being loaded

### ISSUE THREAD

**Issue by Conker224** [BookStackApp/BookStack#4033]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After multiple fresh installs using both the script for Ubuntu 20.04 and manually. Upon browsing to the site, All icons are large and there is no formatting to the rest of the site.

I have checked the .env file for the APP_URL it is correct.
I have checked for Web Socket issues, haven't found any.
Confirmed i am using the release branch.
Unable to check laravel.log as it doesn't exist, though the directory is writable.
When using Chrome's inspect view there are 404 warnings trying to load content for styles.css.map, print-styles.css.map and app.js.map. 

Any help would be appreciated.

### Exact BookStack Version

v23.01.1

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 20.04.5 LTS VM
4GB Memory
Virtual CPUs: 4, 1 socket with 4 cores per socket.

Currently installed via 20.04 Ubuntu Installation Script.

**Comment by ssddanbrown** [comment]
Hi @Conker224,

Any chance you can screenshot the browser console log? The console should be opened, then the browser window refreshed, then screenshotted.

**Comment by Conker224** [comment]
Hello,
Hopefully below is what you are after.

![image](https://user-images.githubusercontent.com/124874206/217813337-42a070cf-4d1d-4175-898a-f856979e1d5a.png)

**Comment by ssddanbrown** [comment]
@Conker224 Thanks, info in the screenshot looks fine.

By viewing your instance URL directly myself, I can see that your setup/hosting/webserver is attempting some kind of optimization/minification of the content served by BookStack, and it looks like this is messing up the CSS.
This may be done via a proxy/cache system if you have such a system sitting in front of BookStack.
Please turn that minification layer off, as it's often not that beneficial in reality as long as the webserver has gzip active.

**Comment by Conker224** [comment]
Hello,

Thank you, turns out that our firewall WAF rule had rewrite HTML turned on. Turning this off fixed our issue.

**Comment by ssddanbrown** [comment]
:+1:  will therefore close this off.
