### ISSUE TITLE
Add/edit/delete Roles via API

### ISSUE THREAD

**Issue by Rob787** [BookStackApp/BookStack#4034]
### API Endpoint or Feature

Add/edit/delete Roles via API call, currently this is missing. I can assign a user to a Role, but not list or add Roles via API.

### Use-Case

We use Bookstack for alot of internal use, but also have some shelfs or books for specific customers to give them some help guidelines. We manage these customers and their users in a central system. Once we create a new customer, I'd like to automatically create a new Role in Bookstack via the API for that customer and assign customers users to that Role.

With the Role, we can finely control what people can see in Bookstack and what not.

**Comment by ssddanbrown** [comment]
Thanks for the request @Rob787. 
This has been added as part of #4051, and will be part of the next feature release.
