### ISSUE TITLE
Click to View Image in Popup

### ISSUE THREAD

**Issue by Gum97** [BookStackApp/BookStack#4039]
### Describe the feature you'd like

![image](https://user-images.githubusercontent.com/21122797/218418168-c2fdeb38-4a41-4e04-aae4-c490ee4483fa.png)
Hello,
Can you make img popup on the page, clicking on the image will create a new page making the user experience not so good if you want to see the image more clearly

### Describe the benefits this would bring to existing BookStack users

The user experience will be better when you don't have to switch back and forth 1 tab when you want to see a clearer image

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @Gum97, this is already open in #464 (as you have commented on) so I'm going to close this off as a duplicate.
