### ISSUE TITLE
Add scrollbar in left side menu

### ISSUE THREAD

**Issue by wouterVE** [BookStackApp/BookStack#4041]
### Describe the feature you'd like

I'd like to suggest to implement a separate scrollbar in the left-side menu. See for instance the [new lay-out](https://en.wikipedia.org/wiki/Windows_7) of mediawiki which provides this function (for Bookstack, it would be better to have a small scrollbar with the same custom colour as the top bar I think)

### Describe the benefits this would bring to existing BookStack users

When using a lot of headings, attachments... it becomes difficult to navigate in this left-side menu. Providing a separate scrollbar would make it easier in that cases. E.g. in my workflow, I rely much on the page navigation section. At present, I have to scroll down the page a lot to view the headings at the bottom of the page navigation section. 
Adding a scrollbar would benefit the page navigation on large pages I think.

### Can the goal of this request already be achieved via other means?

Yes.
You could use the scroll function of the mouse/touchpad but this is less intuïtive (i.e. it only works when you are more towards the left side of this section. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

This is only a suggestion. If you feel that this doesn't fit into the layout of Bookstack, please feel free to close this topic.
I'm very happy with the functions of Bookstack. From time to time, I'd wish there is a separate scrollbar to make page navigation more easy.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @wouterVE.
Previous discussion and potential workaround in #3789.

**Comment by wouterVE** [comment]
Hello, 
Thanks for your reply. I've applied the changes suggested in [this post ](https://github.com/BookStackApp/BookStack/issues/3789#issuecomment-1303395447) and that's exactly what I was looking for!
So far I've tested it on  Opera, Chrome & Firefox (on Windows platform) and both show a scrollbar in the left menu (the latter uses a smaller scrollbar than Opera & Chrome).
See screenshots below:

Opera & Chrome
![image](https://user-images.githubusercontent.com/29882487/219350292-8dd66750-451f-431a-a1ce-c52298c9acb8.png)

Firefox
![image](https://user-images.githubusercontent.com/29882487/219350448-bfa00a28-573e-47ea-bbbc-3acc00bf6c82.png)

I understand that this fix may break with feature updates but I'm satisfied with the solution. I'll close this issue.
Thanks for your responsivenes & the great work you've put in Bookstack, It's providing me the perfect solution for my personal knowledge wiki.

**Comment by wouterVE** [comment]
Update:
I noticed that on Linux (in my case: Pop!_OS 22.04) this change has a different effect.
There is a horizontal scrollbar in the left side menu instead below the actions section & also at the very bottom:
![image](https://user-images.githubusercontent.com/29882487/219853764-232dfca7-b854-4b5f-a110-b618c5fd2298.png)

I don't expect any changes, it's just for your information.

Thanks.
