### ISSUE TITLE
Unable to configure LDAP authentication

### ISSUE THREAD

**Issue by YonatanGolick** [BookStackApp/BookStack#4045]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi guys,
I installed bookstack on an ubuntu 22.04 in my organization.
Now I am trying to configure ldap authentication (Windows active directory host).

```
AUTH_METHOD=ldap
LDAP_SERVER=<fqdn>:389
LDAP_BASE_DN="DN where all users are located"
LDAP_DN="DN of the service account created for bookstack"
LDAP_PASS="password"
LDAP_USER_FILTER=(&(sAMAccountName=${user}))
LDAP_VERSION=3
LDAP_ID_ATTRIBUTE=BIN;objectGUID
LDAP_EMAIL_ATTRIBUTE=mail
LDAP_DISPLAY_NAME_ATTRIBUTE=cn
LDAP_START_TLS=false
```

I know for a fact that the DN's are correct.
But when I try to log in I get the following error:
```
An Error Occurred
An unknown error occurred
```

Check what ldap version my DC is using got - 3 
What am I doing wrong ?

### Exact BookStack Version

v23.01.1

### Hosting Environment

Ubuntu 22.04 installed using the installation script.

**Comment by ssddanbrown** [comment]
Hi @YonatanGolick,
Please follow our [debugging documentation](https://www.bookstackapp.com/docs/admin/debugging/#error-log-file) to find the detail that would be logged when that error message appears.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'll close this off.
