### ISSUE TITLE
Error redirecting url creating new page

### ISSUE THREAD

**Issue by jmleandrocr** [BookStackApp/BookStack#4050]
### Describe the Bug

I´m using Bookstack last version with docker 

Everything is running ok, but when you create a new page , this happen 

GET http://100.30.4.00:6875/%20http://100.30.4.00:6875/books/notas-del-curso 404 (Not Found)

Does anyone know about this error?

### Steps to Reproduce

Just create a new page or charter

### Expected Behaviour

After click on create new page, the site has to go to the draft.

### Browser Details

Chrome

### Exact BookStack Version

BookStack v23.01.1

### Hosting Environment

Docker 
lscr.io/linuxserver/bookstack:latest

**Comment by ssddanbrown** [comment]
Have you set the `APP_URL` environment variable? The value should start with `http`. So, for example, `APP_URL=http://100.30.4.00:6875` (Assuming that "http://100.30.4.00:6875" is the base URL used in the browser to access your instance).

**Comment by jmleandrocr** [comment]
Yes , it’s already set in the docker-compose.yml file . 

The site works , you can login , search , manage , the only thing is this error when you create a new page .

Thanks

**Comment by ssddanbrown** [comment]
@mleandroj18 Okay, please can you share a screenshot all the environment options set in the `docker-compose.yml` file for the BookStack container? You can hide or remove any passwords/secrets first.

**Comment by jmleandrocr** [comment]
Here it is

![image](https://user-images.githubusercontent.com/23279507/219878630-b97224b9-371c-4f49-8209-aa602f574b55.png)

Version of the docker

![image](https://user-images.githubusercontent.com/23279507/219878659-eb9b7a5f-834b-4988-8391-daf3619cd328.png)

And the host of the docker engine

![image](https://user-images.githubusercontent.com/23279507/219878675-dcef9125-7432-4ec7-bd98-57aa5f527f09.png)

Thanks for your help.

**Comment by ssddanbrown** [comment]
@mleandroj18 The `APP_URL` has a leading space and a trailing slash. Please remove both of these then re-up your compose setup (Just restarting won't let the changes take effect).

**Comment by jmleandrocr** [comment]
Hi [ssddanbrown](https://github.com/ssddanbrown)

It worked.

Thanks.
