### ISSUE TITLE
Simulate user/role

### ISSUE THREAD

**Issue by nnsc-adowla** [BookStackApp/BookStack#4059]
### Describe the feature you'd like

I don't always have the best grasp of permissions. I could double-check that I've set things up properly immediately if the admin user/role had the ability to simulate other users or roles.

### Describe the benefits this would bring to existing BookStack users

- Reduce potential time between applying incorrect permissions and noticing any errors
- Eliminate the need to rely on end users to report issues, especially in cases where they might not know there is something to report if certain content is invisible to them

### Can the goal of this request already be achieved via other means?

- By creating a non-admin test account and using it simultaneously with the admin account to test permissions
- By being proactive and working with the user or role member to flag what they should see so that they can report errors

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

Usability feature that isn't available in every app/platform but has always been handy when available. Because of the workaround described above, this isn't a priority issue by any means, but thought it couldn't hurt to suggest for the long-term queue of possible new features.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion, but the fundamental request is already open in #3739 so I'll close this off as a duplicate.
