### ISSUE TITLE
SAML Error - Nested Groups

### ISSUE THREAD

**Issue by Sx3** [BookStackApp/BookStack#4063]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

We have setup Azure SAML login with bookstack and mapped the group IDs to Role IDsaccordingly with bookstack configuration.
Everything works and we needed to add another group in to our existing group so that the new group has same privilages as the existing one...
we are getting the following error.

```
Request Id: xxxxxxx-1234-1234-1234-e8d44da12900
Correlation Id: xxxxxxx-1234-47bf-1234-7ef734399133
Timestamp: 2023-02-23T06:24:32Z

Message: AADSTS50105: Your administrator has configured the application BookStack_SAML ('GROUP_ID') to block users unless they are specifically granted ('assigned') access to the application. The signed in user ['myemail](mailto:'myemail)' is blocked because they are not a direct member of a group with access, nor had access directly assigned by an administrator. Please contact your administrator to assign access to this application.
```

Is there any configuration on bookstack to allow nested groups to login ?
Thanks.

### Exact BookStack Version

v23.01

### PHP Version

PHP 7.4.30

### Hosting Environment

Apache/2.4.29 (Ubuntu)
PHP 7.4.30

**Comment by ssddanbrown** [comment]
Hi @Sx3,
To be honest, based upon that error message, this looks to be purely an AzureAD issue/limitation or something that's dependent to your Azure user group management. I'm don't think I can help you out with this from a BookStack perspective.

**Comment by ssddanbrown** [comment]
Since there's been no further conversation here I'll close this off.
