### ISSUE TITLE
Language Request: Albanian

### ISSUE THREAD

**Issue by Irdiism** [BookStackApp/BookStack#4065]
### Language to Add

Albanian

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Hi @irdiOL,
Sorry I had missed this originally and just coming back across it now.

Do you still desire Albanian in BookStack and are you willing (once added) to translate for this language via our translation service (Crowdin)?

**Comment by Irdiism** [comment]
Hey Dan, i am willing to contribute to translation but can not promise will be something i will do fast and regularty because i am involved in many projects. I will try to organise a translation sprint at our Hackerspace in the next months if you add the language and try to contribute as much as i can.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by ssddanbrown** [comment]
@irdiOL Thanks! I've now enabled Albanian on Crowdin so it's all ready to translate:
https://crowdin.com/project/bookstack

I will usually wait for a while, for significant coverage, before activating as a language in BookStack.
If many months go by without much progress I may remove the language.
