### ISSUE TITLE
What are the optimal requirements of a server to host Bookstack?

### ISSUE THREAD

**Issue by miriapa** [BookStackApp/BookStack#4071]
### Describe the feature you'd like

Hi! I've chose a hosting provider, but the ask me about the requirements to customize the hosting. I need advice of what server requirement would be the optimal for Bookstack. I need to know RAM capacity, SSD capacity and core.
I'd appreciate any help about this.

Thanks in advanced.

### Describe the benefits this would bring to existing BookStack users

Choose the optimal requirements of a server to host Bookstack.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by Swoy** [comment]
The short answer is: *it depends*.

To give us some chance to estimate this, we need to know what you will use BookStack for:
 - Should it support a small, medium or large community?
 - What type of content will it host? lots of images, documents, or just pure text?
 - What is the traffic forecast? Will it be used frequently, how much content will be generated on a daily basis?
 
In most cases, the requirements for the underlying operating system will usually be enough to run a basic configuration of BookStack with a small community (10-100) users. Space-requirements will vary greatly depending on the media types your community will want to upload. A separate database-installation could be considered if the installation will serve thousands of users with daily interactions.

At the end of the day, your best bet is to first map your needs and then potentially make some assumptions on what your community will want from the service. For perspective, the community I serve, we have 100+ users that upload about 10MB of data each, each week, on average. We run BookStack on a single box with 4 cores (2.1Ghz) and 8GB ram. We opted for a scalable storage solution with 10TB of space initially. This is plenty (and so far overkill) for our usecase.

**Comment by miriapa** [comment]
I don't know yet how many active users we'll have, but more or less, it would be around 150 users. We'll post all type of content, mostly text but also images and maybe embedded youtube videos. Mainly, it will be used for consulting support documentation.

We've already chose a hosting service. Thanks so mucho for the info and your time.

**Comment by ssddanbrown** [comment]
Likely concurrent users can be a big factor.

To be honest though, you never know until it's in use. Most hosting services provide the ability to scale resources up.
I'd consider the machine described by @Swoy to be quite beefy. 
As another data point, the demo instance, runs all on 1 cpu core and 512MB of RAM.

For your kind of described use-case, if you have the ability to scale things up when needed, I'd probably advise starting with 2 CPU cores, 1GB of RAM and about 50GB of storage space, then scale as needed.

**Comment by ssddanbrown** [comment]
Since the original question has been answered, I'll close this off.
