### ISSUE TITLE
After update to 23.02 the GUI is not working as expected

### ISSUE THREAD

**Issue by SGBICT** [BookStackApp/BookStack#4073]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi @ssddanbrown After updating the GUI looks strange, it would be better to just show it in the following screenshot:

![image](https://user-images.githubusercontent.com/124276098/221617049-1552bb4c-08cc-4057-afa8-552725ed6085.png)

Any idea what could be wrong? I don't think i saw any errors during the update.

After the update I also ran the following:
php artisan migrate
php artisan cache:clear
php artisan config:clear
php artisan view:clear

Kind regards,

Michel

### Exact BookStack Version

23.02

### PHP Version

8.1.11

### Hosting Environment

Windows with Apache

**Comment by ssddanbrown** [comment]
Hi @SGBICT,
What's the output of running `git status` from your BookStack installation directory?

**Comment by mschoon85** [comment]
Hi @ssddanbrown ,

The following result:

```
On branch release
Your branch is up to date with 'origin/release'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        resources/lang/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by mschoon85** [comment]
@ssddanbrown I did some more research and found this difference before and after the update. So all languages are missing and the dutch (nl) language does not contain the needed files. When I copy the files from the backup to the "nl" folder it works. But that would not be the solution, something goes wrong during the update. I reverted to the previous version with a snapshot, so we have time to find a solution that does not include manual action for the language on every upcoming update. Also the issue remains after updating to 23.02.1. 

![image](https://user-images.githubusercontent.com/96066244/221791933-9e764d50-ef1d-4072-87d7-034d6474bfdd.png)

![image](https://user-images.githubusercontent.com/96066244/221792747-80ea6705-be32-4439-9b57-636d87b5f7ea.png)


Just to be clear, I'm using the following commands to update Bookstack:
git pull origin release
composer install --no-dev
php artisan migrate
php artisan cache:clear
php artisan config:clear
php artisan view:clear


Thanks!

**Comment by ssddanbrown** [comment]
@mschoon85 The language files are not missing, they've just been moved up a level but it looks like you have custom edits/files in the language files that has kept the old location.
If you delete the `resources/lang` folder, things should start working for you.

**Comment by mschoon85** [comment]
@ssddanbrown That did the trick, thanks again!

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up by the original issue creator, I'll go ahead and close this off.
