### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by miriapa** [BookStackApp/BookStack#4078]
### Describe the Bug

Hi, I'm a new user of BookStack. Yesterday my team and I started customizing the platform and creating some shelves, books,... Some of the shelves, books, pages got created correctly but others don't work. Instead of appearing the usual, it appears this (image):
![Comunidad Hiopos _ BookStack - Google Chrome 01_03_2023 9_51_10](https://user-images.githubusercontent.com/126464875/222090581-afdc7d3b-1630-4d88-8bf9-989711ca4d79.png)

I have the lastest version of BookStack and the lastest php version my hosting server allows me to have, which is the 8.1.

I'd really appreciate some help.

Thanks in advanced.

### Steps to Reproduce

1. Click on some shelve/book/page
2. Get en error page with the message "An unkown error occurred"

### Expected Behaviour

I expected to see the shelve/book/page, I've created.

### Browser Details

Windows 10

### Exact BookStack Version

v23.02.1

### PHP Version

8.1

### Hosting Environment

The hosting server we're using is Cloudabove.
Hosting Package: S1
cPanel Version: 108.0 (build 13)
Apache Version: 2.4.55
MySQL Version: 8.0.32
Operating System: linux
Perl Version: 5.26.3

**Comment by ssddanbrown** [comment]
Hi @miriapa,
Please use our debugging documentation to gain more information on this error:
https://www.bookstackapp.com/docs/admin/debugging/#error-log-file

There should be more details in the error log file.

**Comment by miriapa** [comment]
Hi @ssddanbrown,

I've contacted with my hosting server and they solved it because it was an issue of them. A PHP extension that was needed to work, wasn't enable in my hosting plan.

Thanks for the documentation.

**Comment by ssddanbrown** [comment]
:+1: Will therefore close this off.
