### ISSUE TITLE
Fileupload through CloudFlare proxy stuck

### ISSUE THREAD

**Issue by towerplease** [BookStackApp/BookStack#4079]
### Describe the Bug

When i upload some bigger files like > 100MB to Bookstack the upload will not start and is stuck on 0 %.
![image](https://user-images.githubusercontent.com/21177236/222100573-8730c5eb-d411-4502-b15a-83eec4517004.png)
After a while it cancels with error 0.
![image](https://user-images.githubusercontent.com/21177236/222100673-1d636d09-d847-4e9f-bc0e-916654eaf538.png)

Any idea which CloudFlare configuration could interfere with the fileupload?

PS: Upload max Filesize is configured for like 4 GB Files. In the past (without CloudFlare proxy) i could upload without any problems.

### Steps to Reproduce

1. Access bookstack which is proxied by CloudFlare.
2. Try to upload files > 100 MB to page.

### Expected Behaviour

Upload should start normally.

### Browser Details

Opera, Chrome

### Exact BookStack Version

V23.02.1

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04.2 -> LAMP with CloudFlare proxy.

**Comment by ssddanbrown** [comment]
I'm pretty sure Cloudflare has a 100MB request upload limit.

**Comment by towerplease** [comment]
Damn... i researched and you are right...
![image](https://user-images.githubusercontent.com/21177236/222117147-5073c27d-1784-4b51-a1d1-be832e7941a8.png)

A bigger upload limit is only possible with Business/Enterprise plans.

Thank you!

**Comment by ssddanbrown** [comment]
If really needed in a few cases, as a cheeky workaround, you could upload a smaller attachment then swap out the file on the server.

**Comment by towerplease** [comment]
> If really needed in a few cases, as a cheeky workaround, you could upload a smaller attachment then swap out the file on the server. 

Thanks for that suggestion. 
My workaround is to access the server via the IP address directly from my LAN network in the case where I need to upload bigger files. 

Luckily these cases are very rare, I have just one page where I want to upload the latest version of a special editor which is about 450 MB.
