### ISSUE TITLE
[Feature Request] E-mail config in Settings page

### ISSUE THREAD

**Issue by bensulli** [BookStackApp/BookStack#408]
It would be great to have the e-mail config, including a 'test e-mail' button in the Settings config page for admins to alter. Right now having to log into the server (and in my case exec into the docker container), edit the mail.php file and then create a new account is a lot of steps to test the e-mail config.

**Comment by salimnanji** [comment]
+1

**Comment by dfirence** [comment]
+1

**Comment by alexmannuk** [comment]
Test Email button was added in v0.28.0. dotenv for credentials is usually considered more secure than storing them in the database, would suggest closing this as wontfix, mailserver settings are largely set once and forget.

**Comment by bensulli** [comment]
This is a great improvement, thanks!
