### ISSUE TITLE
Ability to see Bookshelf Name in search results for Books

### ISSUE THREAD

**Issue by nothing-fr** [BookStackApp/BookStack#4080]
### Describe the feature you'd like

Ability to see on what Bookshelf is a Book in the search Results

Actualy : 
![image](https://user-images.githubusercontent.com/92157590/222122410-1e8f84ef-6289-4b96-882e-415e07e906d0.png)

Target : 
![image](https://user-images.githubusercontent.com/92157590/222123555-37f9b6b5-fb8c-406d-b6b6-daba44d05f91.png)

### Describe the benefits this would bring to existing BookStack users

More lisibility in case of similar books name on multiples shelves

### Can the goal of this request already be achieved via other means?

I don't know, maybe customizing views if you're a Laravel developper.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by nothing-fr** [comment]
I've managed to do it with a view override and some code analysis / patience !

I've made a custom theme with `entities/list-item-basic.blade.php` containing :

```blade
<?php $type = $entity->getType(); ?>
<a href="{{ $entity->getUrl() }}" class="{{$type}} {{$type === 'page' && $entity->draft ? 'draft' : ''}} {{$classes ?? ''}} entity-list-item" data-entity-type="{{$type}}" data-entity-id="{{$entity->id}}">
    <span role="presentation pouet" class="icon text-{{$type}}">@icon($type)</span>
    <div class="content">
		@if($entity->shelves)
  	    <h6 class="entity-list-item-shelves break-test text-muted">
		@foreach($entity->shelves as $shelf)
		@icon('bookshelf') {{ $shelf->name }}
		@endforeach
	    </h6>
		@endif
            <h4 class="entity-list-item-name break-text">{{ $entity->preview_name ?? $entity->name }}</h4>
	    {{ $slot ?? '' }}
    </div>
</a>

```

Result : 
![image](https://user-images.githubusercontent.com/92157590/222226421-cc56bc85-a3a8-43f1-9971-2bec86bac0e9.png)

**Comment by ssddanbrown** [comment]
@nothing-fr Awesome, thanks for sharing, great to see the theme system being put to good use!
