### ISSUE TITLE
Jira Integration: Add links to Jira (onPrem) and display the issue key number + summary + status

### ISSUE THREAD

**Issue by florian-obradovic** [BookStackApp/BookStack#4083]
### Describe the feature you'd like

I'd love to see a basic Jira integration like you have it in Confluence.
In Confluence I can just paste a https://link-to-a-Jira-ticket and it recognises it automatically
It will be displayed inline and shows  issue key number + summary + status.

It looks like this:
ProjectPrefix-IssueKey - Issue Title - Status
Example:
BOOKSTCK-1719 - Implement basic Jira integration for Bookstack - Done:
![CleanShot 2023-03-02 at 22 12 13@2x](https://user-images.githubusercontent.com/57985125/222554889-23eb4570-5438-4c67-8745-c03cdfae76dd.png)

You can also use JQL (Jira Query Language) to query tables of issues:
![CleanShot 2023-03-02 at 22 05 09@2x](https://user-images.githubusercontent.com/57985125/222552738-b2495117-10f5-4fe8-a93c-994ae5f2748e.png)

This should be possible via the Jira REST API:
- add a remote Jira to Bookstack with URL and API token

### Describe the benefits this would bring to existing BookStack users

Confluence & Jira are tightly integrated.
Many want to move from Confluence to Bookstack but still use Jira.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @florian-obradovic but I'd generally consider integration with external platforms (especially non-open proprietary platforms) out of scope for the core project, so I'll therefore close this off. 

You may be able to use [our hacking options](https://www.bookstackapp.com/docs/admin/hacking-bookstack/) to hack such functionality into your own instance if desired.

**Comment by florian-obradovic** [comment]
Thanks @ssddanbrown - I had a look at the hacking options but as far as I can see there is nothing in it to display external data, right?

**Comment by ssddanbrown** [comment]
@florian-obradovic No, nothing direct for that, it'd be a case of hacking things in yourself.
So maybe some JavaScript to find specific syntax in page content, that then calls a custom endpoint defined via the visual theme system, that calls to the Jira API.
