### ISSUE TITLE
Add new Language-Highlighting-Support for ABAP

### ISSUE THREAD

**Issue by Eekrs** [BookStackApp/BookStack#4086]
### Describe the feature you'd like

Syntax-highlighting for the language ABAP in the code-block.

### Describe the benefits this would bring to existing BookStack users

ABAP is a very common programming language. It would be very helpful to have a syntax highlighting.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

https://github.com/larshp/codemirror-abap

**Comment by ssddanbrown** [comment]
Thanks for the request @Eekrs but I look to stick to the official Codemirror 5 mode list as our bounds of support in this regard, so would not therefore look to support ABAP by default, instead looking toward #2057 as a solution for this.
Therefore I'll close this off.
