### ISSUE TITLE
Impoting SSL cert into bookstack

### ISSUE THREAD

**Issue by BlowMeDown** [BookStackApp/BookStack#4087]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am trying to import a SSL cert into our bookstack following these directions https://docs.sam.gy/books/bookstack/page/enabling-https-for-the-bookstack-web-interface  

When I reboot Apache, I do not get the web page view instead I get the default apache2 Ubuntu Default Page when trying to view our site.  There is a older cert on this same server we are just trying to import a new one since the old cert will expire soon.  The old certs work fine  I am using the same configuration that is on the above link, and I am changing lines 2, and 8 to match our name

### Exact BookStack Version

0.29.3

### PHP Version

7.4.30

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
If you're already on HTTPS, and you're just updating the cert, you should only need to change the `SSLCertificateFile` and `SSLCertificateKeyFile` lines (To point at your updated cert), when looking at the configuration you mention you are using then restart the server.

**Comment by BlowMeDown** [comment]
Ok that is simple but as far as the private key is concerned, is the private key contained with the cert for this application?   I have downloaded the following, the Root Authority, and two intermediary authorities, and my signed certificate.   I wouldn't think the private key would be contained in any of these since the cert can be viewed publicly but  I could be wrong.

**Comment by ssddanbrown** [comment]
@BlowMeDown Just to confirm, this stuff isn't really specific to BookStack at all, this is all Apache server configuration. 
You should have some level of private certificate/file/key. Depending on how you've got a certificate, You may have created this yourself or generated it when creating a CSR during the process in getting your certs.

**Comment by BlowMeDown** [comment]
Ok I understand, I will figure out about the private key and then report back thanks.

**Comment by BlowMeDown** [comment]
Got it working, thanks for the help.
