### ISSUE TITLE
First page is failed to open properly - 404 was caught when bookstack in subfolder

### ISSUE THREAD

**Issue by to-blue-sky** [BookStackApp/BookStack#4088]
### Describe the Bug

ENV: 
xampp : php 8.2 + maria 10.4 + apache 2 
os : windows server 2019 
composer get module and artisan initial db both correct , no mistake.

Findings:
no need to define anything at apache vhost conf, as bookstack/public/.htaccess has already included everything in manual, means manual does not provide any help .
[https://www.bookstackapp.com/docs/admin/subdirectory-setup/](official link)

**#documentroot must be existed, can lead to first page, otherwise 403 or 500** 

```
vhost.conf
<VirtualHost *:80>

    #ServerName 192.168.0.88/bookstack

    DocumentRoot "/SERVER/WEB-XAMPP/htdocs/bookstack/public"

    <Directory "/SERVER/WEB-XAMPP/htdocs/bookstack/public">

    </Directory>

</VirtualHost> 
```

server name is not a must element, even ### this , no impact 

remark : nothing need to fill in directory block

http://192.168.0.88/bookstack - list folder 
http://192.168.0.88/bookstack/public - auto jump into login, cannot load css + res** 

for good side ,most 403 500 problems are solved in this way.
**but the problem left is app.js 404 , no css or any res can be captured .**

refer stackof + laravel official + tons of web pages..., most are pointing to uri problem, but no clear instruction to guide.
 
By guess , since laravel 404 is such usual problem to all users , lots app are facing in many many boards... to be fair - not only bookstack.

should any suggestion ...

### Steps to Reproduce

    <Directory "/SERVER/WEB-XAMPP/htdocs/bookstack/public">
#nothing need
    </Directory>

this step cannot skip, 

seems .htaccess  is almost the killer...

### Expected Behaviour

in docker , bookstack is placed on the root, everything is fine.
but sick in /www or /htdocs 

### Screenshots or Additional Context

no need

### Browser Details

firefox + edge +chrome all up to date

### Exact BookStack Version

"GET /bookstack/dist/app.js?version=v23.02.1 HTTP/1.1" 404 8013

### PHP Version

8.2

### Hosting Environment

winsrv 2019 + xampp
php 8.2 + maria +10.4 + apache 2 + ntfs 
apache httpd.conf / overwrite all + grant all / 
bookstakc folder / overwrite all + grant all /  everything in bookstack folder is listed in web page
443 is no need , ssl conf is nothing, all mods turn on, 
normal php apps are working properly like piwigo , phpmyadmin, crm tiki ....

**Comment by ssddanbrown** [comment]
Hi @jackyzhou888, This is quite hard to understand exactly what the issue is here but I'll try to respond.

> no need to define anything at apache vhost conf, as bookstack/public/.htaccess has already included everything in manual, means manual does not provide any help .

It sounds like you're purposefully going against our advice then coming across issues. I can only advise using the apache virtual host option as we have in our documentation. You cannot, and should not, just place a BookStack install within an existing website or public web-space, and rely on `.htaccess`, since this has security implications.

> http://192.168.0.88/bookstack/public - auto jump into login, cannot load css + res**

You should **never** have `public` as part of the URL as this indicates a potentially insecure install. The BookStack install files should not be in the public web-space of an existing website. 

>  normal php apps are working properly like piwigo , phpmyadmin, crm tiki ....

Many existing PHP apps try to make it easy so you can always just upload and serve the PHP application directly from a folder/subfolder. We don't do this, so you cannot expect BookStack to work the same. In the interest of security, we insist only the `public` folder is exposed, which makes subdirectory setup more complicated hence our documentation.

**Comment by to-blue-sky** [comment]
much thanks to your quick response.
my env is a testing platform , everything is placed in my NAS winsrv 2019 + my PC in house .
no secure issue is concerned at this point.

all I want is run the app in top prior, followed the official only lead the same result, so why I open every door to test.
vhost add full statement in 2 way
way 1 - from offcial manual 
        Options FollowSymlinks
        AllowOverride none
        Require all granted
		RewriteEngine On
        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)/$ /$1 [L,R=301]
        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]
way 2 - from help desk staff pointing subdomain in previous github post.
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews -Indexes
            </IfModule>
            RewriteEngine On
            # Handle Authorization Header
            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
            # Redirect Trailing Slashes If Not A Folder...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_URI} (.+)/$
            RewriteRule ^ %1 [L,R=301]
            # Handle Front Controller...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.php [L]
        </IfModule>

I tryed both 2 ways about 20 times, and catch output in log , both lead to 404 is the best result so far I can reach.

and also junp into my docker to compare every file i can find.

the only conclusion is my luck is not good enough....

follow your ins to shut the doors are right, but no better result come out.

**Comment by ssddanbrown** [comment]
@jackyzhou888 Make sure you are fully following the documentation. 

The `Alias` line in our documented apache configuration is a very important element, and I don't see that in anything you've posted. Additionally, the text above the config example provides a lot of detail about the environment and context since not all environments will be the same.

**Comment by to-blue-sky** [comment]
in version 2 
    Alias /bookstack "/SERVER/WEB-XAMPP/htdocs/bookstack/public"
  <Directory /var/www/bookstack/public/>
        Options Indexes FollowSymLinks...

i put alias before folder block follow by version 2, 
version 1 use servername and docuroot
2 parts I have not skipped any , can lead 192.168.0.88/bookstack to login page, and a big png pic only.
and nothing helpful via google, so why voice for help.

thanks again to your attention ...

**Comment by ssddanbrown** [comment]
@jackyzhou888 What's the current value of `APP_URL` in your `.env` file?

**Comment by lotze1234** [comment]
Hi,
 i use the Laravel Toolkit on plesk. i have exactly the same problem since the new verison. 
Everything works fine bevor. On the new installation css is not loading. 

Failed to load resource: the server responded with a status of 404 ()
app.js:1          Failed to load resource: the server responded with a status of 404 ()
dist/print-styles.css?version=v23.02-dev:1          Failed to load resource: the server responded with a status of 404 ()
login:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
print-styles.css:1          Failed to load resource: the server responded with a status of 404 ()
styles.css:1 

APP_URL = without puplic behind. 

like every time do an installation.

**Comment by ssddanbrown** [comment]
@lotze1234 Your issue is different. This thread related to a config issue when using within a subfolder.
From what you have shared, you are using the development code of BookStack, not a release version.
If need further help open a new support issue specific to your problem.

**Comment by lotze1234** [comment]
> @lotze1234 Your issue is different. This thread related to a config issue when using within a subfolder. From what you have shared, you are using the development code of BookStack, not a release version. If need further help open a new support issue specific to your problem.

thx

**Comment by to-blue-sky** [comment]
hi dan , below is almost everything i can get... much thanks...

--log
192.168.0.55 - - [09/Mar/2023:01:30:06 +0800] "GET /bookstack/ HTTP/1.1" 302 386 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
192.168.0.55 - - [09/Mar/2023:01:30:06 +0800] "GET /bookstack/login HTTP/1.1" 500 635 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"

[Thu Mar 09 01:30:06.502920 2023] [core:error] [pid 9028:tid 2008] [client 192.168.0.55:55030] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Thu Mar 09 01:31:07.266129 2023] [mpm_winnt:crit] [pid 9028:tid 568] AH02538: Child: Parent process exited abruptly. Child process is ending

--httpd-vhosts.conf
<VirtualHost *:80>
    Alias /bookstack "/SERVER/WEB-XAMPP/htdocs/bookstack/public"
  <Directory /SERVER/WEB-XAMPP/htdocs/bookstack/public>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews -Indexes
            </IfModule>
            RewriteEngine On
             #Handle Authorization Header
            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
             #Redirect Trailing Slashes If Not A Folder...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_URI} (.+)/$
            RewriteRule ^ %1 [L,R=301]
             #Handle Front Controller...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.php [L]
        </IfModule>
    </Directory>
    <Directory "/SERVER/WEB-XAMPP/htdocs/bookstack">
        AllowOverride None
        Require all denied
    </Directory>    
</VirtualHost>

--.env
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:codeblabla
APP_URL=http://192.168.0.88/bookstack
APP_LANG=zh-cn
APP_AUTO_LANG_PUBLIC=true
APP_TIMEZONE=UTC
APP_THEME=true
APP_PROXIES=null

DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=bookstack
DB_USERNAME=bookstack
DB_PASSWORD=bookstack

MAIL_DRIVER=smtp
MAIL_FROM=mail@bookstackapp.com
MAIL_FROM_NAME=BookStack
MAIL_HOST=localhost
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

CACHE_DRIVER=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
SESSION_COOKIE_NAME=bookstack_session
SESSION_SECURE_COOKIE=false
CACHE_PREFIX=bookstack
REDIS_SERVERS=127.0.0.1:6379:1
QUEUE_CONNECTION=redis

STORAGE_TYPE=local
STORAGE_IMAGE_TYPE=local
STORAGE_ATTACHMENT_TYPE=local_secure

DRAWIO=true
APP_VIEWS_BOOKS=list
APP_VIEWS_BOOKSHELVES=grid
APP_VIEWS_BOOKSHELF=grid
APP_DEFAULT_DARK_MODE=true

REVISION_LIMIT=100
RECYCLE_BIN_LIFETIME=30
FILE_UPLOAD_SIZE_LIMIT=50
EXPORT_PAGE_SIZE=a4

--remarks
attached content from 3 files, 
-log 
-vhost.conf
-.env

bookstack path
- xampp D:\SERVER\WEB-XAMPP\htdocs
- bookstakc D:\SERVER\WEB-XAMPP\htdocs\bookstack
- expect url htpp://192.168.0.88/bookstack

if above alias and <Directory ... is on , 500 and over routing limit are logged.
another test instance in docker is nginx, no .htaccees, simple config & working fine.

FYI, bookstack is quite nice compare to others, especially for KB mgt. 
functions of tiki is good in php times, but little out of date and users. 
docker/bookstack cannot be compareed with server deployment, why put lots time to test.
even issues and problems, you guys make a great work to all wiki users !!

stars......... flowers...

**Comment by ssddanbrown** [comment]
> xampp D:\SERVER\WEB-XAMPP\htdocs
> bookstakc D:\SERVER\WEB-XAMPP\htdocs\bookstack

It's likely to cause confusion having the BookStack as a subdirectory of other web space. 
The BookStack install folder should not be part of another site.

Try moving the `D:\SERVER\WEB-XAMPP\htdocs\bookstack` folder to `D:\SERVER\WEB-XAMPP\bookstack`.
Then update any `/SERVER/WEB-XAMPP/htdocs/bookstack/public` usages to `/SERVER/WEB-XAMPP/bookstack/public`

**Comment by to-blue-sky** [comment]
hi dan , you are right x 1000.

servername is the key, ip or server name with / is not able to handle.

move port to 81 and vhost use version 1 , the page come out , wahaha...........

hope to help you team and users.

ticket should be close .
