### ISSUE TITLE
Bookstack page not laading

### ISSUE THREAD

**Issue by thetayo** [BookStackApp/BookStack#4090]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hey guys, I moved my bookstack to a new server and followed the instructions on the website. I am able to load the page and enter a password. however after the password is entered, i get the error "this page is not working. HTTP Error 50" any ideas how i can fix this? i enabled debug in the .env file and checked my logs. i see a php fatal error but i am unsure how to fix this

### Exact BookStack Version

can't check

### Log Content

[Wed Mar 08 20:35:50.325652 2023] [php:error] [pid 4732] [client 192.168.14.3:56739] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action' in 'where clause' in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368\nStack trace:\n#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()\n#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()\n#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()\n#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\\Database\\Connection->run()\n#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\\Database\\Connection->select()\n#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\\Database\\Query\\Builder->runSelect()\n#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2936): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2403): Illuminate\\Database\\Query\\Builder->onceWithColumns()\n#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2863): Illuminate\\Database\\Query\\Builder->get()\n#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2791): Illuminate\\Database\\Query\\Builder->aggregate()\n#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1657): Illuminate\\Database\\Query\\Builder->count()\n#11 /var/www/bookstack/app/Auth/Permissions/PermissionService.php(529): Illuminate\\Database\\Eloquent\\Builder->__call()\n#12 /var/www/bookstack/app/helpers.php(81): BookStack\\Auth\\Permissions\\PermissionService->checkUserHasPermissionOnAnything()\n#13 /var/www/bookstack/storage/framework/views/6f7788501927ce60e7e3b5c36d74e91cc0f95558.php(36): userCanOnAny()\n#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')\n#15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()\n#19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()\n#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()\n#21 /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php(38): Illuminate\\View\\View->render()\n#22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')\n#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#26 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()\n#27 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()\n#28 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()\n#29 /var/www/bookstack/storage/framework/views/444e2e0a8c776f8bed9002e3000a037539df392e.php(16): Illuminate\\View\\View->render()\n#30 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')\n#31 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#32 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()\n#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()\n#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()\n#37 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#38 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct()\n#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()\n#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(585): Illuminate\\Routing\\ResponseFactory->view()\n#42 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#43 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#44 /var/www/bookstack/app/Exceptions/Handler.php(65): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#45 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): BookStack\\Exceptions\\Handler->render()\n#46 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(173): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#47 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#48 {main}\n\nNext Illuminate\\Database\\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action' in 'where clause' (SQL: select count(*) as aggregate from `joint_permissions` where `action` = view and `role_id` in (1) and (`joint_permissions`.`has_permission` = 1 or (`joint_permissions`.`has_permission_own` = 1 and `joint_permissions`.`owned_by` = 1)) and `entity_type` = BookStack\\Bookshelf) in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712\nStack trace:\n#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()\n#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\\Database\\Connection->run()\n#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\\Database\\Connection->select()\n#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\\Database\\Query\\Builder->runSelect()\n#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2936): Illuminate\\Database\\Query\\Bu

### PHP Version

PHP 8.1.2

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @thetayo, the error indicates the codebase is out of sync with your database.
Do you see any errors when running the `php artisan migrate` update step?

**Comment by thetayo** [comment]
No, i did see any error at the time.
i ran it again now and it says "nothing to migrate" which suggests it has been completed successfully previously.

**Comment by ssddanbrown** [comment]
Okay, can you share the output of running each of these commands from your BookStack install directory:

- `git status`
- `git log -n 1`
- `cat version`

Also, how exactly did you migrate the instance? Did you move a files as a whole? Did you create a new instance then restore specific files/data into that?

**Comment by thetayo** [comment]
i migrated it as per your documentation here https://www.bookstackapp.com/docs/admin/backup-restore/#restore i copied all the files and allowed permissions.

see the output of those commands below

```
sentinel@inuile:/var/www/bookstack$ git status
On branch release
Your branch is up to date with 'origin/release'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .env.bak
        .github/workflows/analyse-php.yml
        .github/workflows/lint-php.yml
        .github/workflows/test-php.yml
        app/Actions/IpFormatter.php
        app/Actions/Queries/
        app/Actions/TagClassGenerator.php
        app/Api/ApiEntityListFormatter.php
        app/Auth/Permissions/EntityPermissionEvaluator.php
        app/Auth/Permissions/JointPermissionBuilder.php
        app/Auth/Permissions/MassEntityPermissionEvaluator.php
        app/Auth/Permissions/PermissionApplicator.php
        app/Auth/Permissions/PermissionFormData.php
        app/Auth/Permissions/PermissionStatus.php
        app/Auth/Permissions/SimpleEntityData.php
        app/Auth/Queries/RolesAllPaginatedAndSorted.php
        app/Auth/Queries/UsersAllPaginatedAndSorted.php
        app/Console/Commands/RegenerateReferences.php
        app/Entities/Repos/DeletionRepo.php
        app/Entities/Repos/RevisionRepo.php
        app/Entities/Tools/HierarchyTransformer.php
        app/Entities/Tools/Markdown/CustomDivConverter.php
        app/Entities/Tools/Markdown/CustomImageConverter.php
        app/Entities/Tools/Markdown/MarkdownToHtml.php
        app/Entities/Tools/Markdown/SpacedTagFallbackConverter.php
        app/Entities/Tools/PageEditorData.php
        app/Exceptions/BookStackExceptionHandlerPage.php
        app/Http/Controllers/Api/RecycleBinApiController.php
        app/Http/Controllers/Api/RoleApiController.php
        app/Http/Controllers/Auth/ThrottlesLogins.php
        app/Http/Controllers/PermissionsController.php
        app/Http/Controllers/ReferenceController.php
        app/Http/Controllers/UserPreferencesController.php
        app/Http/Responses/
        app/Providers/ValidationRuleServiceProvider.php
        app/Providers/ViewTweaksServiceProvider.php
        app/References/
        app/Search/
        app/Settings/AppSettingsStore.php
        app/Settings/UserShortcutMap.php
        app/Translation/MessageSelector.php
        app/Uploads/FaviconHandler.php
        app/Util/LanguageManager.php
        app/Util/SimpleListOptions.php
        database/factories/Uploads/AttachmentFactory.php
        database/migrations/2022_04_17_101741_add_editor_change_field_and_permission.php
        database/migrations/2022_04_25_140741_update_polymorphic_types.php
        database/migrations/2022_07_16_170051_drop_joint_permission_type.php
        database/migrations/2022_08_17_092941_create_references_table.php
        database/migrations/2022_09_02_082910_fix_shelf_cover_image_types.php
        database/migrations/2022_10_07_091406_flatten_entity_permissions_table.php
        database/migrations/2022_10_08_104202_drop_entity_restricted_field.php
        database/migrations/2023_01_24_104625_refactor_joint_permissions_storage.php
        database/migrations/2023_01_28_141230_copy_color_settings_for_dark_mode.php
        database/migrations/2023_02_20_093655_increase_attachments_path_length.php
        database/migrations/2023_02_23_200227_add_updated_at_index_to_pages.php
        dev/api/requests/roles-create.json
        dev/api/requests/roles-update.json
        dev/api/responses/recycle-bin-destroy.json
        dev/api/responses/recycle-bin-list.json
        dev/api/responses/recycle-bin-restore.json
        dev/api/responses/roles-create.json
        dev/api/responses/roles-list.json
        dev/api/responses/roles-read.json
        dev/api/responses/roles-update.json
        dev/build/
        dev/docs/development.md
        dev/docs/javascript-code.md
        dev/docs/permission-scenario-testing.md
        dev/docs/release-process.md
        lang/
        phpcs.xml
        public/icon-128.png
        public/icon-180.png
        public/icon-32.png
        public/icon-64.png
        public/icon.ico
        public/icon.png
        public/libs/tinymce/models/
        public/libs/tinymce/skins/content/tinymce-5-dark/
        public/libs/tinymce/skins/content/tinymce-5/
        public/libs/tinymce/skins/ui/tinymce-5-dark/
        public/libs/tinymce/skins/ui/tinymce-5/
        resources/icons/add-small.svg
        resources/icons/download.svg
        resources/icons/groups.svg
        resources/icons/reference.svg
        resources/icons/remove.svg
        resources/icons/role.svg
        resources/icons/shortcuts.svg
        resources/icons/swap-horizontal.svg
        resources/js/components/auto-submit.js
        resources/js/components/chapter-contents.js
        resources/js/components/code-textarea.js
        resources/js/components/component.js
        resources/js/components/confirm-dialog.js
        resources/js/components/entity-permissions.js
        resources/js/components/global-search.js
        resources/js/components/pointer.js
        resources/js/components/setting-app-color-scheme.js
        resources/js/components/setting-homepage-control.js
        resources/js/components/shortcut-input.js
        resources/js/components/shortcuts.js
        resources/js/markdown/
        resources/js/services/components.js
        resources/js/services/keyboard-navigation.js
        resources/js/services/text.js
        resources/js/services/vdom.js
        resources/js/wysiwyg/icons.js
        resources/js/wysiwyg/util.js
        resources/sass/_opacity.scss
        resources/views/auth/login-initiate.blade.php
        resources/views/auth/parts/login-message.blade.php
        resources/views/auth/parts/register-message.blade.php
        resources/views/auth/register-confirm-accept.blade.php
        resources/views/books/parts/convert-to-shelf.blade.php
        resources/views/books/parts/sort-box-actions.blade.php
        resources/views/books/references.blade.php
        resources/views/chapters/parts/convert-to-book.blade.php
        resources/views/chapters/references.blade.php
        resources/views/common/confirm-dialog.blade.php
        resources/views/common/sort.blade.php
        resources/views/common/status-indicator.blade.php
        resources/views/entities/body-tag-classes.blade.php
        resources/views/entities/references.blade.php
        resources/views/exports/
        resources/views/form/entity-permissions-row.blade.php
        resources/views/layouts/parts/
        resources/views/pages/parts/editor-toolbar.blade.php
        resources/views/pages/parts/revisions-index-row.blade.php
        resources/views/pages/references.blade.php
        resources/views/search/parts/entity-selector-list.blade.php
        resources/views/search/parts/entity-suggestion-list.blade.php
        resources/views/settings/parts/setting-color-picker.blade.php
        resources/views/settings/parts/setting-color-scheme.blade.php
        resources/views/settings/recycle-bin/parts/recycle-bin-list-item.blade.php
        resources/views/settings/roles/parts/asset-permissions-row.blade.php
        resources/views/settings/roles/parts/related-asset-permissions-row.blade.php
        resources/views/settings/roles/parts/roles-list-item.blade.php
        resources/views/settings/webhooks/parts/webhooks-list-item.blade.php
        resources/views/shelves/parts/shelf-sort-book-item.blade.php
        resources/views/shelves/references.blade.php
        resources/views/tags/parts/tags-list-item.blade.php
        resources/views/users/parts/users-list-item.blade.php
        resources/views/users/preferences/
        tests/Api/RecycleBinApiTest.php
        tests/Api/RolesApiTest.php
        tests/Auth/GroupSyncServiceTest.php
        tests/Auth/LoginAutoInitiateTest.php
        tests/Auth/RegistrationTest.php
        tests/Auth/ResetPasswordTest.php
        tests/Commands/RegenerateReferencesCommandTest.php
        tests/Entity/ConvertTest.php
        tests/Entity/MarkdownToHtmlTest.php
        tests/Helpers/EntityProvider.php
        tests/Helpers/FileProvider.php
        tests/Helpers/PermissionsProvider.php
        tests/Helpers/TestServiceProvider.php
        tests/Helpers/UserRoleProvider.php
        tests/Permissions/Scenarios/
        tests/References/
        tests/Settings/RecycleBinTest.php
        tests/Settings/RegenerateReferencesTest.php
        tests/Settings/TestEmailTest.php
        tests/Unit/IpFormatterTest.php
        tests/UrlTest.php

nothing added to commit but untracked files present (use "git add" to track)
```



```
sentinel@inuile:/var/www/bookstack$ git log -n 1
commit 7233c1c7b2353167b937455912f26e7834c92c84 (HEAD -> release, tag: v22.03.1, origin/release)
Author: Dan Brown <ssddanbrown@googlemail.com>
Date:   Wed Mar 30 19:37:07 2022 +0100

    Updated version and assets for release v22.03.1
```



```
cat version
v22.03.1
```

**Comment by ssddanbrown** [comment]
Okay, your files are in a messy state, looks like a failed merge/pull of the updated code.
Most of your files are a year behind, but some of them are for the latest version.

THE BELOW COMMANDS ARE DANGEROUS AND WILL PERFORM DELETIONS, ensure everything is double backed-up.
Any custom edits or custom files within the codebase will be removed.

To clean things up we can use git clean:

```bash
git clean -df
```

Afterwards running `git status` should not list any files, If that's indeed the case, then proceed to run the three update commands, stopping and reporting back any errors if they show at any stage.

**Comment by thetayo** [comment]
thanks @ssddanbrown 
just to double check, what are the three update commands? Not sure what you mean there. Are those the commands listed here?: https://www.bookstackapp.com/docs/admin/updates/

**Comment by ssddanbrown** [comment]
@thetayo Yeah, those are the commands.

**Comment by thetayo** [comment]
It did not make any difference for me. still not working.

**Comment by ssddanbrown** [comment]
- Did `git status` after running the clean command show any files?
- Did those commands show any errors?
- Does `cat version` now show `v23.02.1`?

**Comment by thetayo** [comment]
git status did not show any file.
Output of `git status`:

```
sentinel@inuile:/var/www/bookstack$ git status
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean

```

there was no error but the `php artisan migrate` command did say nothing to migrate though.

`Cat version` now shows 

```
sentinel@inuile:/var/www/bookstack$ cat version
v23.02.1

```

**Comment by ssddanbrown** [comment]
Okay, can you re-check the error log and share the message that gets logged upon error?
It should at least be different now now the codebase is up-to-date.

**Comment by thetayo** [comment]
```

[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70)
[stacktrace]
#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1064): call_user_func()
#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1100): Illuminate\\Database\\Connection->getPdo()
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\\Database\\Connection->getReadPdo()
#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): Illuminate\\Database\\Connection->getPdoForSelect()
#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()
#11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\\Database\\Connection->run()
#12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\\Database\\Connection->select()
#13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\\Database\\Query\\Builder->runSelect()
#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2936): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2403): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(625): Illuminate\\Database\\Query\\Builder->get()
#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(609): Illuminate\\Database\\Eloquent\\Builder->getModels()
#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(294): Illuminate\\Database\\Eloquent\\Builder->get()
#19 /var/www/bookstack/app/Auth/User.php(99): Illuminate\\Database\\Eloquent\\Builder->first()
#20 /var/www/bookstack/app/helpers.php(38): BookStack\\Auth\\User::getDefault()
#21 /var/www/bookstack/app/Settings/SettingService.php(82): user()
#22 /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php(4): BookStack\\Settings\\SettingService->getForCurrentUser()
#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/bookst...')
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#26 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#27 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()
#28 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#30 /var/www/bookstack/storage/framework/views/444e2e0a8c776f8bed9002e3000a037539df392e.php(16): Illuminate\\View\\View->render()
#31 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/bookst...')
#32 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()
#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#37 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#38 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct()
#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()
#42 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(585): Illuminate\\Routing\\ResponseFactory->view()
#43 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#44 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#45 /var/www/bookstack/app/Exceptions/Handler.php(65): Illuminate\\Foundation\\Exceptions\\Handler->render()
#46 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(427): BookStack\\Exceptions\\Handler->render()
#47 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\\Foundation\\Http\\Kernel->renderException()
#48 /var/www/bookstack/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#49 {main}
"}
[2022-11-22 17:56:21] production.ERROR: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
Stack trace:
#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors\MySqlConnector->connect()
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1064): call_user_f {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
Stack trace:
#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()

#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1064): call_user_f at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
[stacktrace]
#0 {main}
"}

```

**Comment by ssddanbrown** [comment]
@thetayo Are those the latest errors? The datestamp reflects November 2022, and the error reflects one that would be unexpected based upon your confirmation of update commands.

If there's nothing more recent in that log file, you may need to look to the webserver error log files instead. 
We have some general guidance to find these log files [in our debugging docs](https://www.bookstackapp.com/docs/admin/debugging/#error-log-file).

**Comment by thetayo** [comment]
i Just tried my bookstack again and it was working as it should. I am guessing the `git clean` those update commands worked and maybe it just took some time to start working or something. Thank you for your help.

**Comment by ssddanbrown** [comment]
Cool! Will therefore close this off.
