### ISSUE TITLE
Possibility to add "Recommended Books"

### ISSUE THREAD

**Issue by nothing-fr** [BookStackApp/BookStack#4093]
### Describe the feature you'd like

Allows you to indicate books recommended by the author with the same subject or simply having a dependency on the current book.

Could be visible when clicking on a book at the bottom like : 

![image](https://user-images.githubusercontent.com/92157590/224492434-fed04f4b-e7da-4928-9ac1-5407041b3c3a.png)

And editing a book could look like : 

![image](https://user-images.githubusercontent.com/92157590/224492742-c5738b9f-42da-4998-8de1-9fa82e88bca1.png)

### Describe the benefits this would bring to existing BookStack users

Allows you to indicate to the reader which books is recommended to read before or after the one being read, or on a similar / related subject

### Can the goal of this request already be achieved via other means?

I don't know

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @nothing-fr, but this introduces a level of micromanagement of meta detail that I generally try to avoid in BookStack. Similar/related books could already by grouped via tags. 

If you're confident with PHP/code, it is likely possible that the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) could be used to find similar/related/recommended books, based upon tags, then show those in an extra block. 

If that would interest you I could probably come up with an example to add to our [hacks site](https://www.bookstackapp.com/hacks/).

**Comment by nothing-fr** [comment]
Tags are great, but not for this use case I think.

You have to see it more as a recommendation, the author of book A recommends book B, but maybe the author of book B doesn't recommend book 1. The relationship can be one-sided.

So I don't think that tags meet the need. It's more like a 1-n relationship.

I don't really want to do too many hacks on bookstack, because keeping it in working condition is more complicated during upgrades and there is no guarantee that it will work.

We are starting to use it for our production documentation. I don't really want it to be a pain to update.

**Comment by ssddanbrown** [comment]
>  the author of book A recommends book B, but maybe the author of book B doesn't recommend book 1. The relationship can be one-sided.
> So I don't think that tags meet the need. It's more like a 1-n relationship.

I don't see why tags would prevent that kind of relationship. You could just have multiple `Recommend => book-slug-b` style tags on the book to point single-direction recommendation relationships.

> I don't really want to do too many hacks on bookstack, because keeping it in working condition is more complicated during upgrades

Sure, but at the end of the day it's either maintenance dept on you, or maintenance dept on me, and I draw a relatively tight line these days to keep maintenance reasonable and sustainable.

**Comment by nothing-fr** [comment]
No worries if this is not done, it was an internal request. Users will be able to do without it.

It was just more comfort for them.

I'll try the Tags thing just to see if it's manageable...

**Comment by nothing-fr** [comment]
I managed to do what I wanted with the tags and visual hacks.

If anyone is interested:

Step 1 : assign tag 'recommends' with the slug of the recommended book

Step 2 : use this modification : 
in `themes/<yourtheme>/books/show.blade.php` : 
```blade
...
        @include('entities.search-results')
    </main>

@if($book->tags()->where('name', 'recommends')->count() > 0)
                 <h5 class="break-text">Other(s) book(s) recommended by the Author :</h5>
            <div class="recommends">
                 @foreach ($book->tags()->where('name', 'recommends')->get() as $slug)
                 @if ($slug->value != NULL && $book->where('slug', '=', $slug->value)->first())
                 <a href="/books/{{ $slug->value }}" class="text-book icon-list-item outline-hover">
                        <span><svg class="svg-icon" data-icon="book" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 0h24v24H0z" fill="none"></path>
            <path d="M18 2H6c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zM6 4h5v8l-2.5-1.5L6 12V4z"></path>
        </svg></span>
                        <span>
                                {{ $book->getBySlug($slug->value)->name }}
                                @foreach( $book->getBySlug($slug->value)->shelves as $shelf )
                                <br/><span class="entity-item-tags mt-xs">@icon('bookshelf') {{ $shelf->name }}</span>
                                @endforeach
                        </span>
                    </a>
                 @endif
                 @endforeach
            </div>
        @endif

@stop

@section('right')
...
```

in the HTML Header CSS thing property, add : 

```css
.recommends {
  padding: 16px 48px;
  margin-inline-start: auto;
  margin-inline-end: auto;
  margin-bottom: 24px;
  overflow: initial; 
  background-color: #fff;
  box-shadow: 0 1px 6px -1px rgba(0,0,0,.1);
  border-radius: 3px;
  border-left-width: 3px;
  border-left-style: solid;
  border-left-color: var(--color-book);
  display: grid;
  grid-template-columns: repeat(3, 1fr);
} 
```

Note that it's quick and dirty, the values are hardcoded, not made for translation, etc... and depends on the user's good will to fill the tag correctly with the book slug...

This should look like this at the end : 

![image](https://user-images.githubusercontent.com/92157590/228332481-4c776d4d-a0e9-48e1-8b29-427c33051661.png)
