### ISSUE TITLE
Border Style in Table Properties does not have any effect

### ISSUE THREAD

**Issue by Stephen-9445** [BookStackApp/BookStack#4096]
### Describe the Bug

Chenging the border style when editing the table properties does not seem to have any effect.

### Steps to Reproduce

Edit page
Insert Table 
Enter "Table Properties" 
Enter "Advanced"
Change border style to e.g. Dotted

### Expected Behaviour

The border style should change to "dotted"

### Browser Details

Firefox

### Exact BookStack Version

BookStack v23.02 

### Hosting Environment

Docker on Synology DSM7

**Comment by ssddanbrown** [comment]
Thanks for reporting @Stephen-9445, but I'd consider this covered by existing issue #3477 so will therefore close this off.

**Comment by govind2020** [comment]
can I add new properties in Cell properties of Table eg:- there is General and Advance and I want to add any New .
can we do this? like customization
