### ISSUE TITLE
SAML Login URL

### ISSUE THREAD

**Issue by cb3inco** [BookStackApp/BookStack#4101]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

We are using Azure AD SAML configuration (we were using another identity provider before with the same issue) and wondering if there was a 'Sign on URL' that would direct a user when they click the 'card' for the app in Office that it signs the user in directly instead of seeing the 'Sign in with SSO' screen. 

Right now, the URL is https://sub.domain.com in the SAML configuration in Azure, but I had tried https://sub.domain.com/saml2/login and didn't seem to work as it results in a **Page Not Found**

Is there a Sign on URL that can be used to by-pass the 'Sign in with SSO' option.

### Exact BookStack Version

v23.02.1

### Hosting Environment

Docker (Linuxserver.io) on Ubuntu 20.04

**Comment by ssddanbrown** [comment]
Hi @cb3inco,

There's no direct "GET" endpoint available. 
If SAML is the sole login option in your instance, you could set the `AUTH_AUTO_INITIATE=true` option to auto-start the login process to avoid the additional click and essentially get the user journey you desire.
Alternatively, if you cannot use the above option, it should be relatively easy to add a custom endpoint, [using the logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md), to allow the SAML process to be started from a GET request.

**Comment by cb3inco** [comment]
Oh! That's great news. AUTH_AUTO_INITIATE=true works great for our use case. Didn't realize this was an option. My little bit of testing seems to accomplish what I need it to.

Thanks for your help.

**Comment by ssddanbrown** [comment]
Good to hear! Will therefore close this off.
