### ISSUE TITLE
Unable to create and add diagrams to a book. 

### ISSUE THREAD

**Issue by ubundude** [BookStackApp/BookStack#4104]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

We are unable to add a diagram to a book. We are able to open the diagram editor just fine, however, when you click the Save or Exit buttons and it goes back into the Bookstack editor, an error is dislayed and the diagram is not added to the book.
![image](https://user-images.githubusercontent.com/1780035/225085399-e79d1e2d-ea47-498c-af3d-b6f63e62a8a3.png)

I have enabled debugging by setting APP_DEBUG=true in the .env file, however no errors are being logged when I go through the steps to generate the error in the screenshot. The error in the screenshot is the only error I've been able to find related to this. 

### Exact BookStack Version

v23.02.1

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04.02 running on a Linode VM.

**Comment by ssddanbrown** [comment]
Hi @ubundude,
When looking for errors, did you check any error logs files? If so, can you confirm which ones?

**Comment by ubundude** [comment]
Yes, I've looked at the Laravel log under /var/www/bookstack/storage/logs, as well as the error and access logs for Apache. I was unable to find anything else.

**Comment by ssddanbrown** [comment]
Okay. Can you open the browser development tools (Often via `F12` or via Menu > Development tools) then view the `Console` table, then reproduce the error. You should hopefully see a red error entry appear when the error occurs. Please share any errors that appear in this log.

**Comment by ubundude** [comment]
Sure, here's a screenshot from the console: 
[deleted screenshot]

**Comment by ssddanbrown** [comment]
Thanks @ubundude. BTW, that screenshot has your domain within it so feel free to delete that now if you don't want your site URL/domain to be visible. 

So you are specifically getting a 500 internal server error.
It would be very odd not to have this logged in their the BookStack or Apache error log.
When this occurs, do you see the request (To the `/images/drawio` endpoint) logged in the apache access log?
Also, do normal image uploads work okay, when inserting an image via the page editor?

**Comment by ubundude** [comment]
Hey Dan, so I've been doing some more digging this morning and here's what I've got. 
1. I realized that laravel.log hasn't updated since Oct 3rd of last year, so not sure what's up with that. 
2. I also see the requests to the /images/drawio endpoint in the apache access log. It's the same 500 error. 
3. It does look like we're having image upload problems. Looks like no one has uploaded anything since like May of last year, so IDK when that stopped working either. I can drop an image in, but there doesn't seem to be a button to finish uploading, or insert it or anything. I can insert an image that already exists.
Thanks so much!

**Comment by ssddanbrown** [comment]
> I also see the requests to the /images/drawio endpoint in the apache access log. It's the same 500 error.

Double check the apache error log(s). You have have multiple errors logs for apache so be sure you're finding the right one for your BookStack instance. It'd be strange not to be getting errors logs in apache if there's no error logged on the BookStack side of things.

As an extra thing to try, You could update a book or shelf with a new cover image, and see how the system reacts since that's a file upload on the save request rather than a background file upload. 

If I had to guess the error at this stage, without having see an error message with detail, I'd guess it might be due to permissions, with the webserver or PHP process not having permission to write to the required directories.
There's some [more detailed info on required permissions here](https://www.bookstackapp.com/docs/admin/filesystem-permissions/).

**Comment by ubundude** [comment]
It was definitely permissions, which I had a feeling might be the case. I went ahead and reset them all based on the link provided and both image uploads and the diagrams part are working now! Thanks so much for the help!
