### ISSUE TITLE
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: BookStack\Auth\User::getDefault(): Return value must be of type

### ISSUE THREAD

**Issue by ArtemDolor** [BookStackApp/BookStack#4105]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I deleted a guest user in the database and everything crashed, in the logs

### Exact BookStack Version

v23.02

### Log Content

 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: BookStack\Auth\User::getDefault(): Return value must be of type BookStack\Auth\User, null returned in /bookstack/app/Auth/User.php:106

### PHP Version

8.2

### Hosting Environment

Debian 11, Nginx and MariaDB

**Comment by ssddanbrown** [comment]
> I deleted a guest user in the database and everything crashed,

Yeah, the guest user account is expected to exist. You'll need to restore it to the database.

**Comment by ArtemDolor** [comment]
> > I deleted a guest user in the database and everything crashed, > > Yes, the guest user account should exist. You need to restore it in the database.

How can I do it better?

**Comment by ssddanbrown** [comment]
> How can I do it better?

I'm not sure I understand, better than what? What are you attempting to achieve at this point?

**Comment by ArtemDolor** [comment]
> 

How do I restore it? :)

**Comment by ssddanbrown** [comment]
You could do something like this in the database:

```sql
INSERT INTO users (name, email, password, remember_token, created_at, updated_at, email_confirmed, image_id, external_auth_id, system_name, slug)
VALUES ('Guest', 'guest@example.com', '', null, '2021-09-29 13:29:20', '2021-11-18 14:10:58', 1, 0, '', 'public',  'guest');
```

**Comment by ArtemDolor** [comment]
> You could do something like this in the database:
> 
> ```sql
> INSERT INTO users (name, email, password, remember_token, created_at, updated_at, email_confirmed, image_id, external_auth_id, system_name, slug)
> VALUES ('Guest', 'guest@example.com', '', null, '2021-09-29 13:29:20', '2021-11-18 14:10:58', 1, 0, '', 'public',  'guest');
> ```

Thanks!
