### ISSUE TITLE
empty code blocks that are hard to delete

### ISSUE THREAD

**Issue by rgkirch** [BookStackApp/BookStack#4108]
### Describe the Bug

Editing with code formatting is borked. It's difficult or impossible to delete the empty code blocks and they're created in normal edtiing.

### Steps to Reproduce

`<ctrl+shift+e>code<enter><backspace>`

### Expected Behaviour

don't create the extra empty code block

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/6143833/225989033-b642a1f1-0042-483c-9124-18ba11ecbfa4.png)

### Browser Details

chrome 111.0.5563.65 windows 10

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

8.2 from php:8.2-apache-buster from solidnerd/bookstack:23.2.1

### Hosting Environment

solidnerd/bookstack:23.2.1 docker

**Comment by rgkirch** [comment]
It kinda sounds like https://github.com/tinymce/tinymce/issues/2798 but that issue is really old.

**Comment by ssddanbrown** [comment]
Thanks for reporting. Can also reproduce on the plain Tinymce 6 demo: https://www.tiny.cloud/docs/tinymce/6/basic-example/, so does not look like something specific to our implementation.
Something similar occurs with other inline formatting options, they're just less visible. These don't seem to get saved as part of the page content though.
We could just hide empty `<code>` elements within the editor via CSS but would need some testing to see if that interferes with any other existing behaviour.

**Comment by rgkirch** [comment]
Thanks for the link, that's handy! I'm going to close the issue since it's not an issue with bookstack whether or not bookstack decides to hide it.
Thanks again!
