### ISSUE TITLE
I can't type after exiting the "Edit Code" window

### ISSUE THREAD

**Issue by rgkirch** [BookStackApp/BookStack#4109]
### Describe the Bug

I can't resume editing the document by typing after exiting the "Edit Code" window by pressing the Escape key or clicking on the X in the top right. This issue is not present when I click "Save Code" instead.
After closing the "Edit Code" window with the escape key or X then I have to click into the document in order to get a cursor and continue editing the document.

### Steps to Reproduce

<ctrl+e><escape>
then try to edit the document. you can't.

### Expected Behaviour

I should be able to edit the document same as if I had clicked "Save Code"

### Browser Details

chrome 111.0.5563.65 windows 10

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

8.2 from php:8.2-apache-buster from solidnerd/bookstack:23.2.1

### Hosting Environment

solidnerd/bookstack:23.2.1 docker

**Comment by ssddanbrown** [comment]
Can confirm this, thanks for reporting.

**Comment by esakkiraja100116** [comment]
@ssddanbrown  Does this issue still exist ?

- I can't able to find this one. Seems good [here](https://demo.bookstackapp.com/books/admins-only-book/page/this-is-a-draft-page) .

**Comment by ssddanbrown** [comment]
@esakkiraja100116 Yes, I could reproduce this on our demo site from a quick test.

**Comment by esakkiraja100116** [comment]
okay thanks @ssddanbrown.

**Comment by ssddanbrown** [comment]
Proper focus handling for cancel/close code editor window has now been added in 3bcbf6b9c55c9988b04835473053d514a1cb5df3 and will be part of the next patch release.

**Comment by rgkirch** [comment]
Cool. Thanks!
