### ISSUE TITLE
"Save Draft" doesn't work when editing tags

### ISSUE THREAD

**Issue by rgkirch** [BookStackApp/BookStack#4110]
### Describe the Bug

In order to add a tag to a page, I have to first click the "Edit" action so that I'm editing the document. Then there's a 🏷 "Page Tags" button in the right sidebar that expands a "Page Tags" window. After typing in a new tag, <ctrl+enter> doesn't do anything and <ctrl+s> triggers the browsers default "Save As" dialog to download the html page. I expect <ctrl+enter> (Save Page & Continue) and <ctrl+s> (Save Draft) to do the same thing they do when my focus is in the wysiwyg editor.

### Steps to Reproduce

edit a document
![image](https://user-images.githubusercontent.com/6143833/226073530-3674185d-6abd-410b-9cb7-cca9d3131b47.png)
add a tag
![image](https://user-images.githubusercontent.com/6143833/226073543-33a88c69-caef-4a27-ba53-636e1604a926.png)
finish typing name of tag
![image](https://user-images.githubusercontent.com/6143833/226073562-0cfc5d4e-cc65-4d04-9f1c-61141b2d950f.png)
press <ctrl+enter> or <ctrl+s>

### Expected Behaviour

ctrl+enter should do the same thing it does when you're editing the document
ctrl+s should save the tag but allow you to continue editing the document

### Browser Details

chrome 111.0.5563.65 windows 10

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

8.2 from php:8.2-apache-buster from solidnerd/bookstack:23.2.1

### Hosting Environment

solidnerd/bookstack:23.2.1 docker

**Comment by ssddanbrown** [comment]
It's not so much a bug, but the fact that the save-draft system only relates to page content itself, and the save draft shortcut is only within editor; nothing related to the page or things in the sidebar/toolbar uses the draft system.

There's possibly reason though to make this clearer to the user, but not sure on a clean non-distracting to do that. This is also the first time I can think of in the last 6 or so years that that has been raised, so not sure how significant of an issue it is.

**Comment by ssddanbrown** [comment]
Since this isn't a bug, as mentioned above, and since this hasn't really been reported to be a UX issue in the past I'm going to close this off.
