### ISSUE TITLE
Clojure code highlighting

### ISSUE THREAD

**Issue by rgkirch** [BookStackApp/BookStack#4112]
### Describe the feature you'd like

I'd like syntax highlighting for clojure code.
https://github.com/BookStackApp/BookStack/issues/3847#issuecomment-1312191477
> Appears to be a [built-in language](https://codemirror.net/5/mode/swift/index.html) so should be an easy add, have assigned for the next feature release.Clojure is in codemirror.
https://codemirror.net/5/mode/clojure/index.html

### Describe the benefits this would bring to existing BookStack users

You have lots of other languages but not clojure. I tried them all and the best are ruby and julia which change the color of keywords and strings. It's not very exciting though.

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
The clojure language is also part of the [legacy modes](https://github.com/codemirror/legacy-modes/blob/main/mode/clojure.js) package and therefore should not be an issue for CM6 adoption. 
Have assigned to the next feature release.

Related to #3617.

**Comment by ssddanbrown** [comment]
Added in fa6fcc1c1c9dd2888bacee084d31c2f482c53e10, to be part of the next release.
