### ISSUE TITLE
file attachment tooltip cut off

### ISSUE THREAD

**Issue by rgkirch** [BookStackApp/BookStack#4114]
### Describe the Bug

I uploaded an image 
![image](https://user-images.githubusercontent.com/6143833/226147947-19ead45c-2d47-4654-92e8-37e2bfd50471.png)
and when I hover the mouse over the image it displays some white text on a red background
![image](https://user-images.githubusercontent.com/6143833/226147963-0a2e53f0-292a-4d3b-b87f-9f82d834c603.png)
but the text gets cut off by the browser scroll bar and I can't see the rest of the text

### Steps to Reproduce

upload an image attachment
hover mouse over image

### Expected Behaviour

see the full text of the tooltip

### Browser Details

chrome 111.0.5563.65 windows 10

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

8.2.3

### Hosting Environment

solidnerd/bookstack:23.2.1

**Comment by rgkirch** [comment]
I just noticed the bottom scrollbar. I can scroll over to give it room but it's still cut off.
![image](https://user-images.githubusercontent.com/6143833/226148313-0edaac7c-4c25-4e63-a4cc-cfd57e33b949.png)

**Comment by rgkirch** [comment]
Oh.
```# docker compose exec bookstack bash
www-data@4ca961d7dfd8:~/bookstack$ id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```
Fixed.

**Comment by esakkiraja100116** [comment]
@rgkirch May I know where did you find this attachment option ?

**Comment by ssddanbrown** [comment]
@esakkiraja100116 It's in the sidebar when editing a page.
Note, I've completely rebuilt how upload handling is done in these areas, and the layout of the attachments area, within the current `development` branch state.
This may no longer be an issue, but I'd need to come back to this and speficially test with long paths/words in the error message to be sure.

**Comment by esakkiraja100116** [comment]
Oh okay @ssddanbrown . I found that one and also I check file upload, it's working fine only, but I found another small issue here

- When the upload limit exceeded, it needs to be cancelled manually. While clicking the remove link the tooltip will appear over there, So it's not a good UX.

[Screencast from 2023-04-28 17-23-16.webm](https://user-images.githubusercontent.com/57084732/235141257-5a422992-7c9e-4027-ada1-7faec53db8ae.webm)

**Comment by ssddanbrown** [comment]
_Edit: Sorry rgkirch, tagged you by mistake originally._

@esakkiraja100116 Thanks, but as said above, I've completely rebuilt how upload handling is done in these areas so any current upload UX issues here are somewhat irrelevant now, so not worth looking into or testing unless on the `development` branch.

**Comment by esakkiraja100116** [comment]
@ssddanbrown  I apologize for my above mentioned issue. It's working fine in our demo server and I really sorry for that. 

[Screencast from 2023-04-28 19-56-41.webm](https://user-images.githubusercontent.com/57084732/235175180-7b4ff604-a28f-4fc5-9123-d1000af2ed87.webm)

**Comment by ssddanbrown** [comment]
Since the format of these notifications has been [completely redone in v23.05](https://www.bookstackapp.com/blog/bookstack-release-v23-05/#new-upload-handling--attachment-manager-simplification), and therefore the problematic formats here no long exist, I'm going to close this off but feel free to open a new issue if you do experience the same when using the new styling.
