### ISSUE TITLE
Permission error after switching to OIDC

### ISSUE THREAD

**Issue by 10935336** [BookStackApp/BookStack#4117]
### Describe the Bug

I'm trying to login bookstack using OIDC using Keycloak as Idp.

In order to use group sync, I create groups "superadmin" and "op" in keycloak and same name role in bookstack.

- "superadmin" role had all 54 permissions.
- "op" has 52 permissions (unable to manage app settings and role permissions).
- The old admin role was called "oldadmin" and also had all 54 permissions.

Create a new user in keycloak and join the superadmin and op groups.

When I successfully integrated and configured group sync, I filled in the external authentication ID in the original local user, and then I logout and logged back in, it just like I logged in to the original local account. And it gets the "superadmin" and "op" roles correctly.

But I can't see my private books (only I have permission to view them).
Also the "superadmin" role permissions don't seem to be fully in effect, I can change system settings etc but can't see hidden books in the system.

If I grant myself the "oldadmin" role, I can view all books in the system.

I had another sysadmin try the same thing and he couldn't see his private books either.

### Steps to Reproduce

I'm honestly not sure how to reproduce this issue, it's a bit complicated.

1. Build keycloak and use OIDC to integrate with Bookstack
2. Create groups superadmin and op in keycloak
3. Create a user in keycloak and join the superadmin and op groups
4. Create roles superadmin and op in bookstack, superadmin has all 54 permissions, op has 52 permissions (unable to manage app settings and role permissions)
5. Set up group sync
6. Use OIDC to log in to BOOKSTACK, and fill in the external ID in the user information
7. Log out and log in again, the account looks the same as the previous local account, and the group is automatically synchronized as superadmin and op
8. Can't see my books
9. Can't see other hidden books
10. Grant yourself the old "oldadmin" role, then you can see hidden books in the system

### Expected Behaviour

The permissions system should work fine

- Can see your private books normally
- Can see other hidden books in the system normally

### Browser Details

Chrome 111.0.5563.65

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

PHP 8.1.7

### Hosting Environment

Bare metal server, RHEL 8, website behind CDN

**Comment by ssddanbrown** [comment]
Hi @10935336,

> Also the "superadmin" role permissions don't seem to be fully in effect, I can change system settings etc but can't see hidden books in the system.

Only the original BookStack "Admin" role has the ability to see everything in the system, regardless of permissions. Other roles, even if provided all role permissions, will be abiding to visibility permissions and therefore might not see everything, which is why you can't see hidden books via your `superadmin` role.

> But I can't see my private books (only I have permission to view them).

I'm not sure what you're referring to as private Books. BookStack does not specifically have any such feature. Permissions are managed at a role level. The closest to this is when all roles have just "view-own" permissions, with no item-level overrides, and then you're setting visibility by owner.  Is that your setup for such "private books"?

**Comment by 10935336** [comment]
>Only the original BookStack "Admin" role has the ability to see everything in the system, regardless of permissions. Other roles, even if provided all role permissions, will be abiding to visibility permissions and therefore might not see everything, which is why you can't see hidden books via your superadmin role.

Oh thanks, since we changed the default role name in the system, I don't quite remember it being a role provided by the system itself.

> I'm not sure what you're referring to as private Books. BookStack does not specifically have any such feature. Permissions are managed at a role level. The closest to this is when all roles have just "view-own" permissions, with no item-level overrides, and then you're setting visibility by owner. Is that your setup for such "private books"?

Sorry for my inaccurate description, what I mean is set the permission of everyone else to none.

![image](https://user-images.githubusercontent.com/32383605/227074297-6371c49f-de2c-44e2-84ea-85e2850302cb.png)

Then after migrating to OIDC, the owner of this book cannot see this book, and it is normal before migrating.

**Comment by ssddanbrown** [comment]
> Oh thanks, since we changed the default role name in the system, I don't quite remember it being a role provided by the system itself.

If helpful, this role can be identified by this extra bit of text shown when editing the role:

![image](https://user-images.githubusercontent.com/8343178/227559010-95973f32-535f-42aa-bb16-8dcafcbe3b75.png)

> ... what I mean is set the permission of everyone else to none.
> ... the owner of this book cannot see this book...

Based upon the screenshot of permissions, I would not expect that book to be visible to anyone apart from users in the original BookStack "Admin" group. There is no (and never has been) any functionality to specifically allow owners to retain visibility when custom permissions are fully in play (With no inheritance active). There is an open request for this behaviour in #2697.

**Comment by 10935336** [comment]
So it looks like we're confusing permissions, sorry.
But we still think that these are two unreasonable design.
1. There are undocumented hidden permissions, which are not documented as far as I know
2. The owner should automatically have all the permissions of the item. In this case, if the item owner cancels the viewing permission, the item will be lost unless the system-defined administrator handles it.
