### ISSUE TITLE
Don`t work  localIP/something

### ISSUE THREAD

**Issue by rsnorlax** [BookStackApp/BookStack#4127]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello. I installed Bookstack using the script for Ubuntu 22.04. If I try to specify an address like 172.16.30.2/bookstack during installation, then when I try to enter the address, I get page not found.

Please, tell me what am I doing wrong?

### Exact BookStack Version

23.02.1

### PHP Version

8.1.2-1ubuntu2.11

### Hosting Environment

Ubuntu Server 22.04.2 LTS

**Comment by ssddanbrown** [comment]
Hi @rsnorlax,
The installation script does not support setting up a on sub-path like `<IP>/bookstack`, Such a sub-path usually requires a more complex approach and will likely need to be approached specifically in the context of how BookStack is sharing that host/IP with other apps.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'm going to close this off.
