### ISSUE TITLE
"unknown error" when adding a new user

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#4132]
### Describe the Bug

I receive "unknown error" when adding a new user

### Steps to Reproduce

Following the usual process, when I click Save I get "An unknown error". Nothing show in the audit log.

### Expected Behaviour

Confirm new user added

### Screenshots or Additional Context

![2023 03 26-13_20_11-screenshot-info charlie cx](https://user-images.githubusercontent.com/1388797/227775237-d88083c6-f256-4b9a-9099-4c6020464a2c.png)

### Browser Details

Chrome 111

### Exact BookStack Version

BookStack v23.02.2

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04 with Docker

**Comment by ssddanbrown** [comment]
Hi @charliemoss,
Please can you [view the logs](https://www.bookstackapp.com/docs/admin/debugging/) and share the logged error message here.
You didn't state what docker image is in use, but assuming the linuxserver image, you can follow [my video from 7:28](https://youtu.be/6A8hLuQTkKQ?t=448) to find the `laravel.log` file.

**Comment by ghost** [comment]
It turned out to be a simple fix. The email is not setup, so I had to uncheck to send and create a password. Thanks for making an excellent app.

**Comment by ssddanbrown** [comment]
Good to hear you found the issue, and thanks! Will therefore close this off.
