### ISSUE TITLE
an unknown error occurred in bookstack

### ISSUE THREAD

**Issue by sachinvishwakarma26** [BookStackApp/BookStack#4134]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

We have configured Bookstack integration with Active Directory. while logging to portal its giving error like an unknown error occurred. Can you help me on this issue

![image](https://user-images.githubusercontent.com/43565381/227908683-34a6e08c-6462-47e8-9df6-b9e4f06265b0.png)

### Exact BookStack Version

v22.11.1

### PHP Version

7.4

### Hosting Environment

Amazon Linux 2

**Comment by ssddanbrown** [comment]
Hi @sachinvishwakarma26,

You checked the following in your support request:

> I have read the debugging page

When you did this, what detail did you find in [the error log file](https://www.bookstackapp.com/docs/admin/debugging/#error-log-file)?

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'm going to close this off.
