### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by MonVx** [BookStackApp/BookStack#4135]
### Describe the feature you'd like

thanks for your work, that‘s a really functional and beautiful page,
but I would appreciate it if any possibilities here to support the latex editor

### Describe the benefits this would bring to existing BookStack users

the current version has been covered by the vast majority of edit functions, but just only lacks latex support. because there are many occasions need to write a math formula in a book

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request but the requested fundamental feature is already covered by existing issues #639 and #495 so I'm going to close this off as a duplicate.
