### ISSUE TITLE
Register user via Logical Theme

### ISSUE THREAD

**Issue by HenrikPec** [BookStackApp/BookStack#4136]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi, 

according to the following instruction, I managed to login users via client certificate. 
In the past I've done this changing the LoginController. Reading the issue showed my a clearly nicer way. 

https://github.com/BookStackApp/BookStack/pull/2289#issuecomment-857164663

Could you give me a hint how I can add the UserRepo to the logical theme. I would like the user to automatically get registered if not exists. 
I'm not sure how to get the UserRepo object. 

Thanks

```
        if ($proxyEmail && !auth()->check()) {
            $user = User::query()->where($authUserAttribute, '=', $proxyEmail)->first();
            if ($user) {
                auth()->login($user);
            }
            else
            {
                print ("Register") ;
                $registerData = [];
                $registerData['name'] = $proxyUsername;
                $registerData['email'] = $proxyEmail ;
                $registerData['password'] = sha1(rand());
                $newUser = (new UserRepo())->create($registerData);
                $viewRole = Role::getRole('Viewer');
                $newUser->attachRole($viewRole);             

                auth()->login($newUser);
                return redirect()->intended('/');   
            }

        }
```

### Exact BookStack Version

BookStack v22.10.2

### PHP Version

8.1

### Hosting Environment

Windows with IIS

**Comment by ssddanbrown** [comment]
Hi @HenrikPechholz,

The `UserRepo` has its own dependencies that need to be provided when the class is created, although they may have their own. 
It is possible to use a Laravel framework method to auto-resolve this dependency chain to easily create a `UserRepo` object instance as shown below:

```php
<?php

use BookStack\Auth\UserRepo;

$userRepo = app()->make(UserRepo::class);
$userRepo->create(...)
```

As with all logical theme system code like this, the code used is unsupported and may change/break upon any future update.
