### ISSUE TITLE
Tag selection by click fails on Safari

### ISSUE THREAD

**Issue by matthias4217** [BookStackApp/BookStack#4139]
### Describe the Bug

When filing tags in a page, a  list of suggested tags appear. However, on Safari 16.3, it is not possible to select a suggestion by clicking on it. Using the arrow keys and keyboard however works fine. On the same computer, there is no issue if using Firefox.

### Steps to Reproduce

1. Start inputting a tag
2. When the suggested tags appear, try clicking on one.
3. The tag is not selected as expected.

### Expected Behaviour

Tag suggestion selection should work when using Safari.

### Browser Details

Safari 16.3 on macOS

### Exact BookStack Version

23.02.1

### PHP Version

8.1

### Hosting Environment

Openshift 4

**Comment by ssddanbrown** [comment]
Thanks for reporting @matthias4217.
This has been fixed as part of e722ee4268d64fd3c6699bec5291b0413c4e9099 and will be part of the next patch release.
