### ISSUE TITLE
LDAP Active Directory and BookStack in Docker

### ISSUE THREAD

**Issue by mry** [BookStackApp/BookStack#414]
Specific to running BookStack inside a Docker container and populating the environment variables.

### For Feature Requests

Update documentation to either include a clarifying note or include setting in example.

    #use double $$ since we are using docker
    - LDAP_USER_FILTER=(&(sAMAccountName=$${user}))

##### Expected Behavior
The PHP variable is expanded within BookStack and the LDAP query matches as expected.

##### Actual Behavior
With the single $ sign, the expression becomes a static string and the query will never return a result and no error message is thrown. Can be verified by replacing with a proper username.

**Comment by PipeItToDevNull** [comment]
Just a note. I had to map my .env file as a volume, and then manually edit this field to "LDAP_USER_FILTER=(&(sAMAccountName=${user}))". Even with this $$ trick that I found elsewhere it seems like the file was written with strange characters or just no $'s at all.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @mry.

A note has since been added for this option in the documentation.
