### ISSUE TITLE
Allow custom routes in Application Homepage

### ISSUE THREAD

**Issue by fjacobi** [BookStackApp/BookStack#4140]
### Describe the feature you'd like

I'm currently starting to extend bookstack for useful things in my company and the overall start is to do a portal entry page, likened to the typical dashboard application like Heimdall, etc. 

For that I'd want to set the application homepage to the custom route defined in my logical theme or have an API endpoint to manipulate the output specific to the homepage.

### Describe the benefits this would bring to existing BookStack users

Easier modification possibilities for developers.

### Can the goal of this request already be achieved via other means?

In theory I could probably replace it manually or use a custom tag via `page_include_parse` but I think the homepage is such a specific instance, that the feature request is valid.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @fjacobi. I feel this fundamental request is already covered by existing issue #1519 so I'm going to therefore close this off as a duplicate.
