### ISSUE TITLE
New installation guide for Debian 11 with PHP 8.2

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#4141]
### Describe the Bug

There is the [installation guide written by othlanalikhan](https://gist.github.com/OthmanAlikhan/322f83a77c15dfd1c91a2afe0b6a6fc2) which installs it with PHP 7.4.

I've wrote a new guide which is heavily based on this but helps install PHP8.2 and then BookStack.

The link is here : https://jardin.icamole.fr/books/bookstack/page/installation

I thought it may be useful for the community. 

Have a nice day !

### Steps to Reproduce

All the guide can be found in the following link : https://jardin.icamole.fr/books/bookstack/page/installation

### Expected Behaviour

Since PHP7.x has been deprecated, I thought maybe a Debian guide with PHP8.2 could be interesting.

### Exact BookStack Version

v23.02.1

### PHP Version

8.2

### Hosting Environment

Debian with a new installation guide :)

**Comment by code-kungfu** [comment]
Great work!
I used the original Debian guide as well to set up BookStack on Devuan Daedalus (Debian 12 Bookworm equivalent) with PHP 8.2 except leaving the systemd parts out, it worked really well.

**Comment by ssddanbrown** [comment]
Thanks @armando-femat! This prompted me to clean up this community guides area, moving most of the current guides to a "Old Guides" section to indicate they're no longer current, and have added your guide to the existing list.

Done within [fd535968b92128efc466258b8d4e6c3f35c41b44](https://github.com/BookStackApp/website/commit/fd535968b92128efc466258b8d4e6c3f35c41b44), will push changes live later today.
