### ISSUE TITLE
Custom Video Upload - fast forward/rewind issues

### ISSUE THREAD

**Issue by pat-keeley-aurum** [BookStackApp/BookStack#4142]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi guys,

Not sure if this is an expected one or not, as I can only find a few records in Open/Closed issues relating to custom videos, however, my custom uploaded videos to pages don't seem to allow me to rewind/fast forward using either keyboard or mouse. 

My embedded videos from alternative sources like YouTube/AWS are fine. 

Is this expected? I also tested using a custom video with the Bookstack demo site and had the same issue. 

### Exact BookStack Version

v23.02.1

### PHP Version

8.2

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Thanks @patsyk1, but yeah, this is known. We don't explicitly support any video-specific hosting features, which includes not supporting range-requests to properly allow video scrubbing. 

I feel this is already covered by existing issues #3274 and #882 so I'm going to close this off.
