### ISSUE TITLE
Separate tabs for books on global search results 

### ISSUE THREAD

**Issue by Neil-Woods** [BookStackApp/BookStack#4151]
### Describe the feature you'd like

Would love to see separate tabs for search results in books for the global search. A single tab will show all search results while users can go to other tabs to look for results in each book or shelf. If displaying books in a tab could result in the tabs being too many, admins may be given an option to display specific number of relevant tabs or set the tabs to display shelves. 

### Describe the benefits this would bring to existing BookStack users

This will streamline global search for the app. Users will be able to search in specific books or shelves without browsing to the location. I believe content discovery is key for the platform and this would be a valuable addition. I would add a 'please' for this feature, hope it would be in the interests of the core user base and your general direction for the platform. 

### Can the goal of this request already be achieved via other means?

Users can browse to specific books or shelves and type search items, though not as advanced as the global search page. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @Neil-Woods.
To be honest though, I'm not exactly sure on the value. It would complicate the global search interface significantly while the benefit seemingly being minimal.

> Users will be able to search in specific books or shelves without browsing to the location.

Sure, but there'd need to be some level of interface to first select the book they'd want to search within, meaning the amount of steps between this, and finding the book normally before searching, would be minimal.

**Comment by Neil-Woods** [comment]
Thanks for your reply @ssddanbrown . I felt that I didn't communicate my intentions well, so I attached the concept here. The scenario would be users typing a search term and the global search page would spun up results from all shelves and categorize them in tabs. Similar to a Google search, where it has tabs for images, videos and so on. This way, there will be less friction to look for results in a specific shelf. 

![Tabs in search](https://user-images.githubusercontent.com/129741425/229503012-9ecd051e-2502-40ae-9cef-45b1860be9cc.PNG)

**Comment by ssddanbrown** [comment]
Thanks for the further detail.
I'm not sure I'd ever look to make search so shelf-focused like that, since shelve are not required nor do they define boundaries between content, but I can see value in scoping search to a shelf.

We already have  #3546 open, which would achieve some of what's desired in this request, while it would otherwise be a dependency to something like this (Since we don't currently have scope-level search) so I'm going to close this off in the interest of de-duplicating issues.
