### ISSUE TITLE
Ability to always show "Owned by" even if "Created by" is same

### ISSUE THREAD

**Issue by haugli92** [BookStackApp/BookStack#4154]
### Describe the feature you'd like

I want the ability to always show the "Owned by <name>" on pages even if the "Created by <name>" is the same.
When this differs the "Owned by" is visible, but I would like always to show "Owned by". A checkbox to enable this feature or permanently show it to everyone would be nice.

### Describe the benefits this would bring to existing BookStack users

This makes it easier for everyone to see who owns a page, not just assume the creator is the owner. This might differ and might be the same.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
>  A checkbox to enable this feature or permanently show it to everyone would be nice.

Hi @haugli92,
I don't look to add options for detailed-level UI control where we can possibly avoid it.
Instead, this kind of thing can be achieved, and it intended to be achieved, via the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md). 

In this case, you'd extend this view, altering the highlighted lines:
https://github.com/BookStackApp/BookStack/blob/8e64324d62dcefbf1464bc26e4c66329930f0e95/resources/views/entities/meta.blade.php#L18-L27

**Comment by haugli92** [comment]
I understand @ssddanbrown. I will try this solution.

Thanks.
