### ISSUE TITLE
Sort books in shelf by tag or similar

### ISSUE THREAD

**Issue by jmmoreu** [BookStackApp/BookStack#4155]
### Describe the feature you'd like

In a real bookshelf, the user has the option to sort books by name, author, topic, or even book flap color. Currently, Bookcase allows the user to add books to multiple shelves, but the sorting options within the shelf are limited to the name, creation date, or last update.

The user should have the option to sort books by topics (perhaps through tags), by color (adding an extra attribute to each book), by author or even by rearranging the order of the books however they want (in a similar way to the chapter and subchapter sorting options within a book).

### Describe the benefits this would bring to existing BookStack users

Right now, if there is a book that is common to multiple shelves, the place where this book appears on each shelf depends on the attributes (name, last update, creation date) of the rest of the books on that shelf. By giving the option suggested in this feature request, the authors can keep a common structure of their different shelves and fix the location of that common book.

Also, when there are too many books on a shelf it is complicated to find the desired books. Having the option to sort books by topics or some other attributes would help the users when looking for the different books on the shelf.

### Can the goal of this request already be achieved via other means?

No. Currently, the sorting options within a shelf are by name, creation date, or last update.

Some may say that the shelves are already a way to sort books by topic, but that is not what the feature is looking for. The feature request is to sort books within a shelf. 

_Let's say that I use Bookstack to generate the documentation for each project I work on. In this case, I would create a shelf for each project and reutilize some of the books from previous projects (this is precisely why I use Bookstack!). However, I currently cannot sort the books on that shelf. This makes finding stuff hard, especially when there are too many books, and even harder when trying to find documentation from an old project. If I could sort my books as I want, the structure of each shelf would be more consistent making things easier. Of course, finding docs is easy using the Search bar, but that is only useful as long as you know what to look for. I would like each of my shelves (projects) to be self-explanatory so that if someone else gets access knows in what order should they read the books._

Others may say that I could go one level down, and arrange the chapters however I want, but then I would not be able to use the book concept where a book might be present on different shelves at the same time.

This feature request could be also applied to the shelves view, which only provides the same sorting options (name, creation date, and last update) as a shelf.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @jmmoreu,

The default sort option for the books on a shelf is a manual sort (Very much like chapters and pages within a book). 
Simply edit the shelf and you can drag/drop (or use the buttons) to move books around. 
This is then use by the "Default" sort option when viewing the shelf (and also used for the list view of the `/shelves` interface view).

**Comment by jmmoreu** [comment]
Hi @ssddanbrown, thanks a lot for your quick reply.

Oh that's great! I'm sorry I did not see that feature before. My bad.

What about sorting by other options (by topic or color)? Is that something you were planning to add to your roadmap? 

Also, I forgot to mention this, but it would be great if the shelf view, with the books sorted by tag for instance, had some kind of watermark or section where you could see the books belonging to each tag and not simply one after the other.

Thanks again!

**Comment by ssddanbrown** [comment]
> What about sorting by other options (by topic or color)? Is that something you were planning to add to your roadmap?

No, not really to be honest. That's a layer of meta-detail I'd usually avoid and I don't think would be realistically worth the added complexity. 

If you're handy with PHP/coding, there's a range of things you could potentially automate using our logical theme system. As an tangentially related example, here's a hack that auto-sorts books upon child chapter/page change:
https://www.bookstackapp.com/hacks/autosort-tagged-books/

**Comment by ssddanbrown** [comment]
Since much of the originally requested feature is possible via manual sorting, and since I see the other elements as fairly out of scope (With potential existing workarounds using hacking options), I'm going to close this off.
