### ISSUE TITLE
Feature: support Unix sockets for databases

### ISSUE THREAD

**Issue by AceBlade258** [BookStackApp/BookStack#416]
Please add support for unix sockets for databases such as MySQL and Postgres.

As far as I can tell, this is easily accomplished by adding the following to database.php:

    'unix_socket'   => env('DB_SOCKET', null),

**Comment by ssddanbrown** [comment]
Hi @AceBlade258,
Unix sockets can be set via the `DB_HOST` .env variable using the following format:
```
DB_HOST=localhost;unix_socket=/var/run/mysqld/mysqld.sock
```

Tested on my Ubuntu machine. Let me know if that doesn't work for you and I'll re-open this.
