### ISSUE TITLE
Add preview for draw io diagrams

### ISSUE THREAD

**Issue by mv-yurchenko** [BookStackApp/BookStack#4160]
### Describe the feature you'd like

In our work we use wide charts.
Now to see them - you have to press edit and see the details there
I would like to press a button and be able to view the diagram as a picture (with the ability to scroll)

### Describe the benefits this would bring to existing BookStack users

Allow everyone to view wide charts

### Can the goal of this request already be achieved via other means?

I supposed yes
Just with extra zoom for picture

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @mv-yurchenko. I feel the fundamental request here is already covered by #1548 so I'm going to close this off to de-duplicate requests.
