### ISSUE TITLE
AzureAD the request does not match the reply urls

### ISSUE THREAD

**Issue by SKRM9837** [BookStackApp/BookStack#4165]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,

i have a problem with authentication against AzureAD. I have read the request #967, but Azure dont support wildcard in reply URLs. In the documentation the reply url is "https://example.com/login/service/azure/callback". With this URL as reply url i get the error from azure: "AADSTS50011: The redirect URI 'https://example.com/login/service/azure/callback' specified in the request does not match the redirect URIs configured for the application". I have the correct domain exchanged for example.com.

Thanks

### Exact BookStack Version

V22.02.3

### Hosting Environment

Ubuntu 20.04.4 LTS

**Comment by ssddanbrown** [comment]
- Does the base of the redirect URL configured in Azure exactly match that used in your instance, as in the `APP_URL` value of your `.env` file, including starting `https://` or `http://`?
- Are you sure you're adding the URL to the correct place in Azure? If I remember there are a few places to add URLs. If so, can you provide a screenshot of the are where the URL has been added? (Of course obsecure the domain but ideally still show the path and domain).

**Comment by SKRM9837** [comment]
After waiting 6 hours it worked without any changes...
