### ISSUE TITLE
An Error Occurred while deleting a user 

### ISSUE THREAD

**Issue by jasonyunliang** [BookStackApp/BookStack#4166]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

when i tried to delete a user , no matter it created manually or sync it from LDAP. it all failed.  I've enabled the debug view. below is what i got. 

### Exact BookStack Version

v23.02.2

### Log Content

i tried to enable debug view while deleting a user. below is the error i've got. please help check. thanks. 

Error
TypeError
BookStack\Auth\UserRepo::destroy(): Argument #2 ($newOwnerId) must be of type ?int, string given, called in /app/www/app/Http/Controllers/UserController.php on line 202

### PHP Version

8.1.17

### Hosting Environment

self-hosted with docker image pulled from linuxsever/bookstack

**Comment by ssddanbrown** [comment]
This is something that was specifically addressed in v23.02.3, so please update and this should be fixed. I'm going to close this off but feel free to comment and this can be re-opened if it remains an issue in v23.02.3.

**Comment by jasonyunliang** [comment]
Ok.&nbsp; Got it.. Thanks a lot for quick support.



---Original---
From: "Dan ***@***.***&gt;
Date: Sun, Apr 9, 2023 21:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BookStackApp/BookStack] An Error Occurred while deleting a user (Issue #4166)




 
This is something that was specifically addressed in v23.02.3, so please update and this should be fixed. I'm going to close this off but feel free to comment and this can be re-opened if it remains an issue in v23.02.3.
