### ISSUE TITLE
Migrate to a new server and update Bookstack

### ISSUE THREAD

**Issue by tomasjay** [BookStackApp/BookStack#4167]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Dear Dan,

I have the following challenge: While our Bookstack installation contains a lot of valuable content, it has not been updated for a while. 

Our Bookstack installation is version 0.30.4. It is hosted on a virtual server at Strato. The OS is Ubuntu 16.04. PHP version is 7.4.12. 

It seems that I have to completely re-install the server via the Strato user interface to update to a higher Ubuntu and PHP version. All individual data will be deleted, unless it has been copied to a folder "/private-backup" for later use. 

I have read the documentation regarding Backup and Restore (https://www.bookstackapp.com/docs/admin/backup-restore/). So, I will copy all files from the Backup steps to the mentioned folder. 

Then, in Restore, I should do a fresh Bookstack installation as first step in Restore. My question: Does the fresh Bookstack version need to be the same as used before? Or can I pull the current one? Will the Backup & Restore procedure work as described, starting from my Bookstack version 0.30.4?

Best, Thomas

### Exact BookStack Version

v0.30.4

### PHP Version

7.4.12

### Hosting Environment

Ubuntu 16.04 on virtual server at Strato

**Comment by ssddanbrown** [comment]
> Does the fresh Bookstack version need to be the same as used before? Or can I pull the current one? Will the Backup & Restore procedure work as described, starting from my Bookstack version 0.30.4?

On the new instance, you should use the latest version of BookStack. Before restoring your old database ensure there are no existing tables in the database, that is really important. Then, after restoring the database content, running the `php artisan migrate` command will upgrade the old database content to be compatible with the latest version.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
