### ISSUE TITLE
SQLSTATE[HY000] [1044] Access denied

### ISSUE THREAD

**Issue by TomBachelot** [BookStackApp/BookStack#4169]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

My bookstack is in debug mode and i don't know why but when i refreshed my page this error just pop up : 

Illuminate\Database\QueryException
SQLSTATE[HY000] [1044] Access denied for user 'bookstack'@'localhost' to database 'bookstack' (SQL: select * from `users` where `id` = 1 limit 1)

### Exact BookStack Version

23.01.1

### Log Content

SQLSTATE[HY000] [1044] Access denied for user 'bookstack'@'localhost' to database 'bookstack' (SQL: select * from `users` where `id` = 1 limit 1)

### PHP Version

8.2.0

### Hosting Environment

windows on xampp server

**Comment by ssddanbrown** [comment]
This error usually indicates that the database user credentials (configured in the `.env` file) are not valid or do not have permission for the `bookstack` database. 

Make sure those credentials are correct and the user has been granted permissions for the database, and that the `php artisan migrate` install/update step runs without error.
