### ISSUE TITLE
Customize the "page not found" text

### ISSUE THREAD

**Issue by pierre-g-brainso** [BookStackApp/BookStack#4171]
### Describe the feature you'd like

I would like to modify the text that is displayed when a user views a page to which he does not have read rights or is not logged in.

More precisely, the 3 lines :
"Page not found
Sorry, The page you were looking for could not be found.

If you expected this page to exist, you might not have permission to view it."

I'd like to change them to something like, "🛑 Protected content!
Please login to access this page

If this page is expected to be public, please check the requested URL."

Is there a way to do it manually ? By changing a specific line in the code ?

![Capture](https://user-images.githubusercontent.com/99983903/231796565-abfeabe8-09d2-4629-9599-a6ed87717030.PNG)

### Describe the benefits this would bring to existing BookStack users

This could be clearer to non-technical users so that they can better understand why they don't have access to a link that has been shared with them. Currently, a user who doesn't know much about Bookstack might actually think that the page doesn't exist

### Can the goal of this request already be achieved via other means?

No, not as far as I know

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

Thanks for your help

**Comment by ssddanbrown** [comment]
Hi @pierre-g-brainso,
You could achieve this using our visual theme system:
https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md
My video here includes a similar use case:
https://www.youtube.com/watch?v=gLy_2GBse48

The not found text is specifically extracted into its own view for easy modification:
https://github.com/BookStackApp/BookStack/blob/development/resources/views/errors/parts/not-found-text.blade.php

**Comment by pierre-g-brainso** [comment]
Hi @ssddanbrown thank you, I was able to do what I wanted to do thanks to your answer.

Have a nice day
