### ISSUE TITLE
n8n integration (workflow automation)

### ISSUE THREAD

**Issue by Eekrs** [BookStackApp/BookStack#4177]
### Describe the feature you'd like

Modules for n8n (workflow automation tool).

### Describe the benefits this would bring to existing BookStack users

Easy no-code/ low code integration to bring different tools together and automate workflows.

### Can the goal of this request already be achieved via other means?

No. At the moment it is necessary to integrate other tools by writing scripts, like these: https://github.com/BookStackApp/api-scripts

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @Eekrs but I don't look to support new external systems as part of the core project to keep our scope reasonable and focused, instead I prefer to focus on providing APIs so such integrations could be built externally to any platform where desired. 

Therefore I'm going to close this off as out of scope.
I'd be intrigued to personally explore and potentially (unofficially) come up with examples for such a system but I don't have much eagerness to do that for n8n as I don't want to dedicate much effort to a non-open-source platform like N8N (It's only source available / fair-code).
