### ISSUE TITLE
dompdf export broken

### ISSUE THREAD

**Issue by eoli3n** [BookStackApp/BookStack#4178]
### Describe the Bug

When I try to export a pdf page, I get "An unknown error occurred".

In log, i get that line
```
[2023-04-17 10:37:15] production.ERROR: Call to a member function get_cellmap() on null {"userId":4,"exception":"[ob
ject] (Error(code: 0): Call to a member function get_cellmap() on null at /var/www/bookstack/vendor/dompdf/dompdf/sr
c/FrameReflower/TableCell.php:40)
```

### Steps to Reproduce

1. Go to a book/page
2. Export / pdf
3. Get the error

### Expected Behaviour

Pdf to be rendered

### Exact BookStack Version

v23.02.1 and v23.02.3

### PHP Version

8.2

### Hosting Environment

Debian 11
Nginx
Mariadb

**Comment by ssddanbrown** [comment]
This is very dependant on content, so please can you share a minimum sample of the page HTML/markdown content that's triggering this error?

You can get the HTML content of a page via one of the right-most buttons when in the WYSIWYG editor.

**Comment by eoli3n** [comment]
Ironically, the problem is about my comparative table about wiki solution choice 

This ->



  | dokuwiki | wiki.js | xwiki | bookstack
-- | -- | -- | -- | --
Libre et gratuit | oui | oui | oui | oui
Hébergé sur site | oui | oui | oui | oui
Éditeur WYSIWYG | plugin | ++ | + | ++
Authentification CAS-AD | AD | CAS-AD | ?-AD | ?-AD
Structure hiérarchique des pages | - | + | + | ++
ACL par agent/groupe | oui ? | oui | oui | oui
Éditeur de tableau avancé | plugin | ++ | + | ++
Mention des utilisateurs @jk | non | ? | ticket en cours | ticket en cours
Gestionnaire de tâches | plugin | ? | plugin | non
Historisation des modifications | oui | oui | oui | oui
Format de saisie du contenu | spécifique | md wysiwyg asciidoc html | ? | md wysiwyg
Format de stockage du contenu | txt | bdd | bdd | bdd
Export du contenu | pdf html odt | md html pdf(impression) | ? | md html pdf txt
Fichiers attachés aux pages | non | ? | ? | oui
Brouillons | ? | ? | ? | oui
Diagrammes | non | UML flowcharts sequence | ? | flowcharts
Commentaires | non | oui | ? | oui

**Comment by eoli3n** [comment]
for working exports, is there a possibility to manage zoom when exporting ? I want to export in a smaller font

**Comment by eoli3n** [comment]
The table was a copied/pasted from a dokuwiki, I recreated it, which solved my issue.
