### ISSUE TITLE
Back to top button is not working in Edit page

### ISSUE THREAD

**Issue by OHopiak** [BookStackApp/BookStack#419]
### Bug Report

* PHP Version: 7.0.18
* MySQL Version: 15.1

##### Expected Behavior
Scroll to top
##### Actual Behavior
Not doing anything

**Comment by ssddanbrown** [comment]
Hi @OHopiak, Thanks for reporting this. To be honest, The back to top button should not even display on the edit page as you shouldn't be able to scroll the main content far enough for it to show. Could you let me know what browser and OS you're using?

**Comment by darkmoon2** [comment]
I can confirm that the Back to Top Pop-Up does come up in the edit window, and does not function.  When you copy in paste in a large amount of text you get to the bottom very quickly.

Bookstack Version 0.16
Firefox 54.0.1 (64-Bit)

**Comment by ssddanbrown** [comment]
Can anyone provide a screenshot? Do you have to hover over the correct area to show or does it show after scrolling or does it show all the time?

**Comment by ssddanbrown** [comment]
As of next release, THe back-to-top button will be fully hidden on pages such as the edit page.

Change in 93147f434065e474a27b31a396caa332de8ee45d
