### ISSUE TITLE
A meaningless record "Restored from $versionId" in Changelog

### ISSUE THREAD

**Issue by LawssssCat** [BookStackApp/BookStack#4190]
### Describe the Bug

![image](https://user-images.githubusercontent.com/18041500/233836738-f323143c-7196-47df-8d1f-31763b28cf96.png)

### Steps to Reproduce

in any "Page Revisions" page

click "Restore" in Action column

### Expected Behaviour

Show the value in "#" column, Instead of `$revisionId` -- a global change version id.

or show  `$revisionId` in the left column "#" directly

https://github.com/BookStackApp/BookStack/blob/1cc7c649dc3a5e1adc0c1bbcee1e7adb61bbd968/app/Entities/Repos/PageRepo.php#L312

### Exact BookStack Version

BookStack v23.02.3

### Hosting Environment

null

**Comment by ssddanbrown** [comment]
Thanks for reporting @LawssssCat, but I'm going to close this as I feel its already covered by #2373 which generally covers the mix of ids used and shown to users.
