### ISSUE TITLE
Permalink Icon right on page

### ISSUE THREAD

**Issue by LHBL2003** [BookStackApp/BookStack#4195]
### Describe the feature you'd like

I found this post on the permalink.  in itself a very good thing.  However, for the end user, not really intuitive.

[https://www.bookstackapp.com/docs/user/content-permalinks/#:~:text=Simply%20select%20any%20block%20of,link%20with%20a%20single%20click.](https://www.bookstackapp.com/docs/user/content-permalinks/#:~:text=Simply%20select%20any%20block%20of,link%20with%20a%20single%20click.) 

Improvement idea 1: In the right area a link icon where you can create an external link.

Improvement idea 2: Switch the address in the browser URL to permalink via the configuration file.

### Describe the benefits this would bring to existing BookStack users

Improvement idea 1: The operator will quickly find that a normal link often leads to problems.  he will find the link icon and see the tooltip text for the benefits of that link.  He will also notice that the link looks different and gives him advantages for external access.

Improvement idea 2: In a company, you can immediately avoid the operator copying a link from the browser that quickly no longer works after restructuring.

### Can the goal of this request already be achieved via other means?

Via detours with the contribution to permalink described above.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request but this has already been discussed a few times, including within #2917 where you can find my thoughts on this.
