### ISSUE TITLE
Connection to Bookstack on AWS times out after fresh installation

### ISSUE THREAD

**Issue by Shisupun** [BookStackApp/BookStack#4198]
### Describe the Bug

I've created a fresh EC2 instance with Linux running Ubuntu 22.04.
The security inbound rules;
Port range 22, Protocol TCP, Source 0.0.0.0/0
Port range All, Protocol All, Source ::/0
Port range All, Protocol All, Source 0.0.0.0/0

### Steps to Reproduce

Create a fresh t2.micro EC2 instance on AWS.
Select Ubuntu 22.04
Instance size: 30GB
Port range 22, Protocol TCP, Source 0.0.0.0/0
Port range All, Protocol All, Source ::/0
Port range All, Protocol All, Source 0.0.0.0/0

Connect to the instance via AWS's ssh connection.
Follow the instructions here: https://www.bookstackapp.com/docs/admin/installation/#ubuntu-2004
The instructions suggest to do this from within the EC2 instance;
1. wget https://raw.githubusercontent.com/BookStackApp/devops/main/scripts/installation-ubuntu-22.04.sh
2. chmod a+x installation-ubuntu-22.04.sh
3. sudo ./installation-ubuntu-22.04.sh

When running line #3, it will ask for a domain name to point it to. I've already set the domain name of the public IP in Google DNS records.
Type A, TTL 1hour, Data [Public IP Address]

Once bookstack finishes installing it sends me to the Private IP address (Which I thought was odd) and the domain name. 

I follow the private IP address and Google Chrome says that the site can't be reached, [IP Address] took too long to respond. So of course, I switch my DNS records to point to the private IP address and try again, it again and Google Chrome says that the site can't be reached, [IP Address] took too long to respond. 

There's also no error log in /var/www/bookstack/storage/logs to point me in the right direction. 

### Expected Behaviour

Being able to view main bookstack login page. 

### Browser Details

Google chrome

### Exact BookStack Version

I dont know, I cant access Bookstack. 

### Hosting Environment

Ubuntu 20.04 using official installation script

**Comment by ssddanbrown** [comment]
If you're not getting through via your configured domain, this'll generally be an issue on your DNS or environment networking side.

- Did you wait for the DNS record to propagate after configuring?
- When you access the configured domain in the browser, is it connecting over `http://` and not `https://`? Some domains (like `.dev`) force HTTPS usage in browsers, but you won't have HTTPS active yet.
- If you run `php -S 0.0.0.0:8080` on the server, can you access `http://<domain>:8080` and see a "Not Found" page with a purple header bar?
  - If not, what about when you access `http://<public_ip>:8080`

**Comment by Shisupun** [comment]
- Its been a couple of hours, so I assume it should have propagated by now. 
- The bookstack application says to go to http;// and not https://. 
When I try to connect with http:// I get the same result, likewise with https://

- The domain is .net so I am not sure it applies here. 
- I run php -S 0.0.0.0:8080 and the output is
PHP 8.1.2-1ubuntu2.11 Development Server (http://0.0.0.0:8080) started
When I go to http://<mydomain.net>:8080 i receive the same error of the site can't be reached. There's no purple header bar,  

- When I access http://public_ip:8080 I do indeed get a "Not found" with a purple bar. 

What should I do next?

**Comment by ssddanbrown** [comment]
> When I go to http://<mydomain.net>:8080 i receive the same error of the site can't be reached.
> When I access http://public_ip:8080 I do indeed get a "Not found" with a purple bar.

Based upon that, it sounds like the domain is leading to the server, at least in your browser.
- Double check that the DNS record is pointing to the public IP. 
- Maybe try a different device browser on a different network (Phone on mobile network for example) to check with something that won't have previous caches filled.

**Comment by Shisupun** [comment]
It seems that by doing this, it worked! Thanks!

I'll try to reproduce this one more time to verify if there's something else that might need to be addressed.
