### ISSUE TITLE
No Filter Audit Log Wrong URL

### ISSUE THREAD

**Issue by c0shea** [BookStackApp/BookStack#4201]
### Describe the Bug

The URL that is redirected to when you select the No Filter option on the audit log page is wrong and doesn't keep the base path defined where BookStack is hosted.

### Steps to Reproduce

Once you're on the Audit Log page if you change the Event Filter to something other than No Filter, such as page_create, the page works as expected. However, once you have a filter selected and then change it to No Filter, it redirects you to the wrong URL. It goes to `/settings/audit` at the root of the host rather than using the base defined in the `APP_URL` in the `.env`.

![image](https://user-images.githubusercontent.com/17714002/234592134-24287e2d-6bd5-420c-961b-1fe2496ae938.png)

Selecting any other filter once you have a filter selected works and has the right URL.
![image](https://user-images.githubusercontent.com/17714002/234592152-71c4f376-5571-4ca8-8e6f-68b590c265a0.png)

### Expected Behaviour

The URL for No Filter should keep the base URL, which in my case is `/BookStack` before `/settings/audit`

### Exact BookStack Version

v23.02.3

### PHP Version

8.2.3

### Hosting Environment

IIS running on Windows Server 2012 R2

**Comment by ssddanbrown** [comment]
Can confirm, thanks @c0shea for reporting. Have assigned to the next feature release.
