### ISSUE TITLE
Please add support for Opentts API

### ISSUE THREAD

**Issue by dg9999cn** [BookStackApp/BookStack#4208]
### Describe the feature you'd like

tts  is very important for books, please add support for Opentts API. and give us some use sample. Thanks.

### Describe the benefits this would bring to existing BookStack users

with voice reading for book is very important.

### Can the goal of this request already be achieved via other means?

I don't know.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @dg9999cn,
I would not generally look to add support for any specific external APIs, at least not without heavy requirement/reasoning/demand which I don't think exists here, so in-build integration with the OpenTTS API is not something I'd look to add.

It may be possible to use the web browser speech API instead [docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API#speech_synthesis), [demo](https://mdn.github.io/dom-examples/web-speech-api/speak-easy-synthesis/), but support can be a little spotty for that. Could maybe be something that could be hacked in potentially.

> Describe the benefits this would bring to existing BookStack users
> with voice reading for book is very important.

You'd need to explain why it's very important.

**Comment by ssddanbrown** [comment]
I'll go ahead and close this off since there's been no further follow-up, and since I would not look to support the specific requested API as said above.
