### ISSUE TITLE
Api Search by book_id

### ISSUE THREAD

**Issue by matteostracchi81** [BookStackApp/BookStack#4214]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

hi at all,
I should search, via API, all the pages by book_id filter, but I can't.

I tryed a get request like this: http://localhost/api/pages?query={book_id:4}. 

Anyone can help me?

Thanks.

### Exact BookStack Version

23.2.3

### Hosting Environment

Docker image version 23.2.3

**Comment by ssddanbrown** [comment]
Hi @matteostracchi81,
You can do this with the following kind of format:

```
/api/pages?filter[book_id]=4
```

Refer to the ["Listing Endpoints"](https://demo.bookstackapp.com/api/docs#listing-endpoints) section of the API docs for full details on the options available at the `list` endpoints.

**Comment by matteostracchi81** [comment]
> /api/pages?filter[book_id]=4

thank you so much!
