### ISSUE TITLE
Exported Document - Poorly Formated Code Blocks

### ISSUE THREAD

**Issue by lue30499** [BookStackApp/BookStack#4215]
### Describe the Bug

The code blocks of an existing document when exported as PDF and HTML has the text behind the left number bar without numbers.

### Steps to Reproduce

1. Go to existing document
2. Click export
3. View export
4. Observe incorrect format

### Expected Behaviour

1. Go to existing document
2. Click export
3. View export
4. Observe correct format

### Screenshots or Additional Context

HTML Export:

![image](https://user-images.githubusercontent.com/63104612/235905708-4b89d8c8-6d9a-4921-8bab-b2e092596bb1.png)

PDF Export:

![image](https://user-images.githubusercontent.com/63104612/235905805-5c777454-18a7-4a56-8012-3dde562865fe.png)

### Browser Details

Chrome 112.0.5615.165

### Exact BookStack Version

v23.05

### PHP Version

8.1.2-1ubuntu2.11

### Hosting Environment

Proxmox LXC Ubuntu 22.04.2 LTS

**Comment by ssddanbrown** [comment]
Thanks for reporting @lue30499, Could definitely see this being due to changes I made for the latest release.
Have assigned to the next patch release.

**Comment by ssddanbrown** [comment]
This has now been addressed in 4489f6537111521fe7d6f8c96527ae23b68cde7c, and will be part of the next patch release.
