### ISSUE TITLE
Translatation is missing for specific notifications in webhooks

### ISSUE THREAD

**Issue by Android1338** [BookStackApp/BookStack#4216]
### Describe the Bug

I'm using a Discord server with a few channels for BookStack notifications only and if I restore a revision in BookStack, I just receive the following message:
`Julian activities.revision_restore`

The same happens if I change admin settings in BookStack:
`Julian activities.settings_update`

Also if a maintenance has been started:
`Julian activities.maintenance_action_run`

### Steps to Reproduce

1. Use "German" as language
2. Create a webhook, in my example for Discord
3. Make some changes in BookStack to receive alerts via Discord
4. Switch to Discord and you'll see non-translated messages

### Expected Behaviour

I expected translated messages like ...
- `Julian started a maintenance`
- `Julian restored a page`

### Screenshots or Additional Context

![bug](https://user-images.githubusercontent.com/29342292/235987900-c31af694-3be5-4b12-9419-bd3dd82d1dce.png)

### Browser Details

Firefox 112.0.2 (64-Bit) on Windows 10

### Exact BookStack Version

v23.05

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04.2 LTS VPS, installed using official installation script

**Comment by ssddanbrown** [comment]
Thanks for reporting.
I've now added activity text for each activity type within commit f39938c4e3b8750668442a6a17e1006953b5cef2.
This will be part of the next feature release.
Might take a little extra time for language variations to trickle down.
