### ISSUE TITLE
[CodeMirror] Mark only Line´s

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#4217]
### Describe the Bug

With the new Codemirror, can`t not Custom Mark.

See you Picture
![image](https://user-images.githubusercontent.com/6242840/236217982-7b721b3b-6e91-4e8e-b92d-073208ca0f5e.png)

Please Fix or Change

### Steps to Reproduce

Go to Code-Field and mark the Code

### Exact BookStack Version

23.05

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Hi @reddexx, can you explain exactly what you mean by "mark the Code"?
I don't really understand what the issue is here or what exactly this relates to.

**Comment by reddexx** [comment]
Go to Code-Box And mark a text, it doesn't work. You can't mark the code block either.  Only the lines were bad.

**Comment by ssddanbrown** [comment]
Hi @reddexx, Again I'm not sure what you mean by "mark a text" or "mark the code block". 
What exactly do these actions involve?

**Comment by reddexx** [comment]
Go to Code block (CodeMirror) and
Place the cursor in front of the first letter of the word, phrase, or paragraph you want to highlight. Hold down the mouse button while dragging the cursor to highlight the desired text.

This working not in Editor and view mode

**Comment by ssddanbrown** [comment]
@reddexx That works okay for me.

- Can you provide full details of the browser you're using, and the operating system it's installed on?
- Does the issue remain in other browsers, or when using a private window?
- Does the code block on [this demo page](https://demo.bookstackapp.com/books/bookstack-demo-site/page/mixed-content-example-page) have the same issue?

**Comment by reddexx** [comment]
![Animation2](https://user-images.githubusercontent.com/6242840/236283273-48f67811-2f37-46f1-bdc7-4bca5a7ac508.gif)
![Animation](https://user-images.githubusercontent.com/6242840/236283278-d0926518-363a-430f-aeea-a99ea7be01c4.gif)

in Demo Site working this

i use Chrome

**Comment by reddexx** [comment]
Hey Dan,

 i have the Docker Image Rebuild and the Container Recreated

it´s Working now 😂
