### ISSUE TITLE
Theme doesn't change "Recently Updated Pages"

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#4219]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I've read and applied https://github.com/BookStackApp/BookStack/pull/1749 and it's mostly working 👍 Only the items in `Recently Updated Pages` on the front page still got the old names.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/122267262/236391411-8f748c50-db06-4a20-99bf-162f5b904807.png">

![image](https://user-images.githubusercontent.com/122267262/236392759-20839e48-b858-43d1-8a28-d3be39de1ac4.png)

Did I miss something?

### Exact BookStack Version

v23.02.3

### Hosting Environment

Docker: `lscr.io/linuxserver/bookstack`

**Comment by ssddanbrown** [comment]
Hi @nstein-gpjoule,
Are you overriding the [activities](https://github.com/BookStackApp/BookStack/blob/development/lang/en/activities.php) translations?

**Comment by ghost** [comment]
No, that's what I was missing 👍
