### ISSUE TITLE
enables https for external access , don't know where to upload domain ssl

### ISSUE THREAD

**Issue by jasonyunliang** [BookStackApp/BookStack#4222]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I want to enable https for bookstack. going through the ssl.conf , 

the step i go is 
change the APP_URL  to be  https://x.x.x.x

and i see the path in ssl.conf as below
ssl_certificate /config/keys/cert.crt;
ssl_certificate_key /config/keys/cert.key;

i tried to replace the crt and the key of the above path. it seems not working.  can someone help ？ 

BTW, i'm using docker-compose to run the instance.  do i have to change the port map such as  6875: 443 ? 

many thanks. 

### Exact BookStack Version

v23.05

### PHP Version

the latest

### Hosting Environment

docker-compose

**Comment by ssddanbrown** [comment]
Yeah, the linux server container [listens on `443`](https://github.com/linuxserver/docker-bookstack/blob/d29c2f1f550cc3e050fecd6266f64d0022089eac/root/defaults/nginx/site-confs/default.conf.sample#L7-L8) for SSL connections, so you'd want to map to that port instead.

Note, in docker environments like this it's quite common to instead keep the application container on http, then use a reverse proxy in-front to handle routing/ssl. 
I do this in my video here: https://www.youtube.com/watch?v=dbDzPIv8Cf8
This kind of setup allows you to centralise SSL management and, if needed, serve multiple applications/containers on the same machine, using the same http/https ports, routing by domain/url as desired.

**Comment by jasonyunliang** [comment]
thanks.  i followed by the video you sent.  it's really helpful.  the ssl seems working. but i just can't open bookstackapp site.  

it showed  502 Bad Gateway.  

just don't know how to debug...    i checked the host,  selinux already disabled.  tried to disable firewall. but it ended up the same. 

do you know what else i can check ?

**Comment by ssddanbrown** [comment]
@jasonyunliang Just to confirm the current state of things, Are you now using some kind of proxy? Or something like cloudlfare?

If now using nginx-proxy-manager, it'll be useful to see a screenshot of the proxy config.

**Comment by jasonyunliang** [comment]
@ssddanbrown i'm using nginx proxy manager same as you mentioned in the video.  it somehow worked after a build a fresh new  rocky linux OS  and ubunt  OS, running docker-compose on the new OS and compared with old one , I saw the ports isn't showing up on the old containers

![1683513226289](https://user-images.githubusercontent.com/129718765/236721288-61cb4010-f0a4-431c-abef-1bb34a768e67.png)


and the newly built 

![1683513399917](https://user-images.githubusercontent.com/129718765/236721394-b4067db0-80d0-41e9-b5ab-4b6ab0fa9a92.png)

I think that may be caused by the mixing up with podman.  because i tried to run podman on that old rocky linux previously .  

anyway, it's all sorted out. and it's up running just fine.  

many thanks.

**Comment by ssddanbrown** [comment]
Good to hear things are now sorted. Will therefore close this off.
