### ISSUE TITLE
Updating through v23.02, PHP repo changed from remi to ondrej?

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [BookStackApp/BookStack#4224]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

We are hosting BookStack on CentOS 7. When we installed BookStack, we used Remi's PHP repository. The documentation for updating through v23.02 says that a PHP upgrade is needed. Do we need to switch our PHP repository to ondrej? Or can we continue using remi?

### Exact BookStack Version

22.11

### PHP Version

7.4.33

### Hosting Environment

CentOS 7

**Comment by ssddanbrown** [comment]
Hi @FMCUSystemAdmins,
You would continue to use remi, since that's suited for operating systems on the RHEL/rpm/fedora/centos side of things.
The Ondrej repo is for Debian based systems.

The commands provided in our updates notes are for those that used our scripts to install.

**Comment by FMCUSystemAdmins** [comment]
Ok, I thought that was the case, just wanted to be sure. Thank you.

Just ran through updates for PHP and BookStack, post-update pages aren't loading. Seeing these errors in httpd error_log:

`[Sat May 06 17:24:05.077383 2023] [php:warn] [pid 23856] [client [removed]:57325] PHP Warning:  require(/var/www/BookStack/vendor/composer/../symfony/deprecation-contracts/function.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/composer/autoload_real.php on line 41`
`[Sat May 06 17:24:05.077462 2023] [php:error] [pid 23856] [client [removed]:57325] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/BookStack/vendor/composer/../symfony/deprecation-contracts/function.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/BookStack/vendor/composer/autoload_real.php:41\nStack trace:\n#0 /var/www/BookStack/vendor/composer/autoload_real.php(45): {closure}()\n#1 /var/www/BookStack/vendor/autoload.php(25): ComposerAutoloaderInita27e8d44b338e7e2f5c376c299323d7e::getLoader()\n#2 /var/www/BookStack/public/index.php(34): require('...')\n#3 {main}\n  thrown in /var/www/BookStack/vendor/composer/autoload_real.php on line 41`
`[Sat May 06 17:24:05.133297 2023] [php:warn] [pid 23855] [client [removed]:57326] PHP Warning:  require(/var/www/BookStack/vendor/composer/../symfony/deprecation-contracts/function.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/composer/autoload_real.php on line 41, referer: [removed]`
`[Sat May 06 17:24:05.133356 2023] [php:error] [pid 23855] [client [removed]:57326] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/BookStack/vendor/composer/../symfony/deprecation-contracts/function.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/BookStack/vendor/composer/autoload_real.php:41\nStack trace:\n#0 /var/www/BookStack/vendor/composer/autoload_real.php(45): {closure}()\n#1 /var/www/BookStack/vendor/autoload.php(25): ComposerAutoloaderInita27e8d44b338e7e2f5c376c299323d7e::getLoader()\n#2 /var/www/BookStack/public/index.php(34): require('...')\n#3 {main}\n  thrown in /var/www/BookStack/vendor/composer/autoload_real.php on line 41, referer: [removed]`

Still looking myself, but any suggestions?

P.S. I replaced IP addresses and FQDNs with "[removed]".

**Comment by FMCUSystemAdmins** [comment]
@ssddanbrown, I think I got it. Looks like it was a permissions issue. Ran `chown -R apache:apache /var/www/BookStack`, refreshed the page, and it came up.

Thanks for your help and can't tell you how grateful we are for BookStack.

**Comment by ssddanbrown** [comment]
@FMCUSystemAdmins Assuming the update steps ran okay without error, this appears to be due to file permissions.
I have file permission guidance here: https://www.bookstackapp.com/docs/admin/filesystem-permissions/
That has an example approach I generally recommend. 
Note though that the `www-data` used in the commands on that page won't be applicable for your system. You might need to instead use `apache` but I'm not 100% sure on that.

**Comment by ssddanbrown** [comment]
@FMCUSystemAdmins Ah, good to hear you managed to resolve things!
