### ISSUE TITLE
Cant type the forwardslash `/` character in a code window

### ISSUE THREAD

**Issue by IceWreck** [BookStackApp/BookStack#4227]
### Describe the Bug

I think this key is also the search shortcut and the cursor jumps to the searchbar which is hidden under the code window.

### Steps to Reproduce

1. Create a code window
2. Type something
3. Press the `/` key

### Expected Behaviour

Should allow me to type the forwardslash char

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/18102790/236798863-08922eed-bd77-4fbc-bfc7-12fbd0f97a12.png)
(look - the cursor is now on the searchbar)

It could be that it was fixed in https://github.com/BookStackApp/BookStack/commit/3bcbf6b9c55c9988b04835473053d514a1cb5df3 which fixes a similar but different issue. If so, please close this.

### Browser Details

Firefox 112.0 on Fedora

### Exact BookStack Version

 v23.05

### PHP Version

the one with the latest linuxserver image so probably php 8.1

### Hosting Environment

Rootless Podman on Rocky Linux 8

**Comment by ssddanbrown** [comment]
Thanks for reporting @IceWreck, Can confirm. This occurs on all code windows (Including the markdown editor) and for all configured shortcuts.

Have assigned to the next patch release.

**Comment by IceWreck** [comment]
That was a super fast reply. You and Bookstack are awesome as always.

**Comment by ssddanbrown** [comment]
This has now been addressed in 8846f7d255d9d2f9d6b997d57aff9a511074796f and will be part of the next patch release.

**Comment by IceWreck** [comment]
Thank you
