### ISSUE TITLE
Use system fonts instead of Roboto

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#423]
Just an idea at the moment. Done it for a lot of recent projects and have seen some other large apps go the same way. I've been pretty happy with my own results.

### Advantages

* More consistent with user system UI.
* System fonts likely to render cleaner.
* Removes font download, Saves time and kb.

### Disadvantages

* Less consistency across users and devices.

**Comment by ls42** [comment]
**I'd prefer system fonts / consistency with user system UI.**

Although making the font-family CSS param configurable through the system settings would even better, if that's possible. Making it possible to switch between sans-serif and serif fonts.

**Comment by the4ndy** [comment]
Is there a current (easy ish) way to change the font for the whole app (ie via a config file or something)? If so, 1) i would love to know where this is, and 2) I think that should be adequate, maybe allow users to upload the font or choose the font from a list at the same place they put their branding image in.  
  
But that said, I agree, system fonts is likely the way to go.

**Comment by domainzero** [comment]
@the4ndy You can currently override the font by specifying a stylesheet or style in the Custom HTML Head section on the settings page. 

I am personally overwriting the `monospace` font with Hack for laughs, so it's doable.

**Comment by nh-mike** [comment]
I personally like the Roboto font. I'm a bit of an Android fanboy so there's no way I could prefer the system font. It would be nice if maybe this were in it's own stylesheet or something so that it is easy for the end user to modify, but I wouldn't lose sleep if the Roboto font were dropped from the project.
I guess if it were easily configurable to the end user, they could specify their own fonts (although that may lead to some ugly Bookstack instances, what does that matter here?) and would be a pretty cool addition.

**Comment by ssddanbrown** [comment]
Thanks everyone for your input. Looks like there's a general sway to system fonts. Will probably look to make that change in the next release then.

I agree about being able to customize. @domainzero makes a good point about using the custom HTML setting that's already there. I'd say maybe have a guide in the official docs about how to set a custom font with some examples otherwise system fonts are default. 

Might need to review the current SASS files minimize font definitions in css rules as much as possible to make overriding simple.

Will probably use approach B from [this guide](https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/) since it's served me well before.

**Comment by ssddanbrown** [comment]
Fonts have now been changed in master branch, Documentation updated in preparation. Both will be deployed with v0.18
