### ISSUE TITLE
the toolbar of edit page doesn't works in the correct positon in edge or Chromium browser.

### ISSUE THREAD

**Issue by lqdflying** [BookStackApp/BookStack#4230]
### Describe the Bug

by default the class in `resources/views/pages/parts/editor-toolbar.blade.php` is `primary-background-light toolbar page-edit-toolbar`
but in edge browser the toolbar postion shows at bottom
![image](https://user-images.githubusercontent.com/30266323/236867684-3a9c1000-389b-4e74-8818-ac37ac0d3763.png)
when i tried to delete the `toolbar` class,the page works well
![image](https://user-images.githubusercontent.com/30266323/236867954-5003a268-5229-4852-87b3-9f7d697f0a69.png)

### Steps to Reproduce

1. open `edge` browser ( in my laptop version is `113.0.1774.35 `)
2. create a page and click `edit`
3. toolbar postion shows wrongly.

### Expected Behaviour

toolbar shoud show correctly at the top of browser.

### Browser Details

edge  `113.0.1774.35 ` or Chromium `102.0.5005.167`

### Exact BookStack Version

BookStack v23.05.1

### PHP Version

PHP 8.1.2-1ubuntu2.11

### Hosting Environment

Ubuntu 22.04.2 LTS `clear env`

**Comment by ssddanbrown** [comment]
Just downloaded and tested this on Edge `Version 113.0.1774.35 (Official build) (64-bit)`, could not reproduce.

- Do you see this [on our demo instance](https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site)?
- Do you have any customizations applied at all for your instance?
- Have you got common extensions/plugins across these browsers which might be affecting things?

**Comment by lqdflying** [comment]
> 
Thank you for your proactive response. It turns out that a plugin caused this issue. I will now close this case.
