### ISSUE TITLE
Emojis are not displayed in PDF export of page

### ISSUE THREAD

**Issue by sense-design** [BookStackApp/BookStack#4232]
### Describe the Bug

On exporting a page as PDF emojis are not displayed correctly.

### Steps to Reproduce

1. Create a page
2. Add text and emoji to content
3. Export as PDF
4. Emoji is not displayed

### Expected Behaviour

Emoji is correctly displayed.

### Screenshots or Additional Context

Bookstack page

![image](https://github.com/BookStackApp/BookStack/assets/172284/8382bac0-9999-45be-b4ca-a26049ba0965)

PDF export
![image](https://github.com/BookStackApp/BookStack/assets/172284/2abccf3a-bd9a-49ff-a3da-0d4335c9ba18)

### Exact BookStack Version

v23.05

### PHP Version

8.0

### Hosting Environment

Ubuntu 22.04 VPS, nginx 1.23.4, PHP 8.0

**Comment by ssddanbrown** [comment]
Thanks for reporting, but I feel this is already covered by #719 and #148 so I'm going to close this off as a duplicate.

**Comment by Alexaandre** [comment]
hi, do you have any updates on this ? i saw there was a problem too with emoji

**Comment by grinchikav** [comment]
Hi @ssddanbrown Please tell me if you have found a solution to the problem with Unicode characters not being displayed when exporting PDF? in #719 and #148 i didn't see a solution of this problem.

**Comment by Tomblarom** [comment]
@grinchikav I was able to add [gotenberg ](https://github.com/gotenberg/gotenberg) to my docker stack and got fabulous results! It appears the ultimate solution for converting PDFs.

| dompdf (default)|weasyprint|gotenberg|
| -------- | -------- | -------- |
| <img width="300" src="https://github.com/user-attachments/assets/d8cee169-5baa-4fb5-86d5-9f09fd9c10e7" />|<img width="300" src="https://github.com/user-attachments/assets/928b71e9-327b-4c92-b7a4-3e5c4afe7f9d" />|<img width="300" src="https://github.com/user-attachments/assets/5b9ec6e4-d8ae-44b2-b9dd-d9ed2883af2f" />|
