### ISSUE TITLE
redirection after first connexion

### ISSUE THREAD

**Issue by TomBachelot** [BookStackApp/BookStack#4237]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

i would like to know if it is possible to set up a redirection to a  bookstack specific page  for a user when it's their first connexion ?

### Exact BookStack Version

BookStack v23.05.1

### PHP Version

PHP Version 8.2.4

### Hosting Environment

Xampp control panel v3.3.0 on windows 10

**Comment by ssddanbrown** [comment]
No way built-in to do this.

Could hack something in using the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) though. If you're willing to attempt using this, and are ideally familiar with PHP, then I can provide some high-level guidance on approach if needed.

**Comment by TomBachelot** [comment]
Yes please, I'm already using the logical theme system, so I am ready to hear your guidance !

**Comment by ssddanbrown** [comment]
Alright, so assuming "first connection" means first login, my thoughts would be like this:

1. Hook into the "web middleware after" event:

https://github.com/BookStackApp/BookStack/blob/ed96aa820e63a8f7a3c74efc2d6803ff2facec8b/app/Theming/ThemeEvents.php#L113-L123

2. Check if they're logged in and they don't have a specific flag via user settings.
 - Can access user settings via `setting()->getForCurrentUser('setting_key_here')`
 - Can check logged-in status via `auth()->check()`.
 
3. If (2) is true: set a specific user settings flag and redirect them as required.
 - Can set user settings via `setting()->putForCurrentUser('setting_key_here', 'value_here')`
 - Can redirect via returning a `redirect('path')` call from the middleware event handler.

Could possibly be some funky edge cases from this, but that's where I'd start.

**Comment by TomBachelot** [comment]
thanks i'll try to do my best with this !
