### ISSUE TITLE
Security audit flags expired certificate - installed by install script?

### ISSUE THREAD

**Issue by RZR7332** [BookStackApp/BookStack#4238]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

While scanning my system with Lynis, it flags a certificate as expired - specifically, /var/www/bookstack/vendor/league/oauth1-client/tests/test_rsa_publickey.pem. I am assuming this is installed as part of the installation script - what is it used for, and is it safe to remove? 

I realise this is not a major issue, but for compliance reasons expired certificates should be removed, or at least be replaced by valid certificates.

### Exact BookStack Version

23.05.1

### Log Content

2023-05-11 12:52:28 Result: certificate /var/www/bookstack/vendor/league/oauth1-client/tests/test_rsa_publickey.pem has been expired

### PHP Version

PHP 8.1.2-1ubuntu2.11

### Hosting Environment

Ubuntu Server 22.04 LTS, virtual machine, official install script.

**Comment by ssddanbrown** [comment]
@RZR7332 That file is within the testing data of a sub-dependency. It's not something that would actually be used during runtime.

**Comment by RZR7332** [comment]
Thanks Dan. Is it safe to remove or is it required for functionality?

**Comment by ssddanbrown** [comment]
@RZR7332 I'm sure it's safe to remove. Will likely re-appear every time you update though.

**Comment by RZR7332** [comment]
Thanks @ssddanbrown - good enough for me. Appreciate the quick response and support, much appreciated.
