### ISSUE TITLE
Unable to copy out of CodeMirror editor

### ISSUE THREAD

**Issue by domainzero** [BookStackApp/BookStack#424]
### For Bug Reports

* BookStack Version:  v0.17.0
* PHP Version: PHP 5.6.30 (fpm-fcgi) (built: Jan 19 2017 07:45:04)
* MySQL Version: mysql  Ver 15.1 Distrib 10.1.24-MariaDB, for Linux (x86_64) using  EditLine wrapper

##### Expected Behavior
Able to copy out of the Codemirror editor and paste elsewhere.

##### Actual Behavior
Issue exists only in Chrome from what I have seen. I'm running Chrome Version 59.0.3071.115 (Official Build) (64-bit). This problem **does not** exist in Firefox 54.0.1. It also doesn't exist in Chromium Version 58.0.3029.110 (64-bit).

Unable to copy from the Codemirror editor and paste elsewhere. Note that I can paste into the Codemirror editor. Using Ctrl+C or using right click + copy yields same results.

**Comment by ssddanbrown** [comment]
@domainzero Thanks for reporting. I'm seeing the same results. From my testing it only seems to be an issue for the markdown input? I can seem to copy fine within the WYSIWYG editor and from code blocks when viewing pages.

Very strange issue...

**Comment by ssddanbrown** [comment]
For any devs in the future experience issues with copying from codemirror and come across this issue, The issue was custom styling on textareas in codemirror. Remove any custom CSS rules for textareas inside codemirror and that should fix things.

The fix for this will be in the next bugfix release.

**Comment by ssddanbrown** [comment]
Update now out to cover this.
