### ISSUE TITLE
Problem selecting multiple files at the same time.

### ISSUE THREAD

**Issue by mnguiro** [BookStackApp/BookStack#4241]
### Describe the Bug

I'm having trouble getting all files selected when loading files.
I load several files at the same time. after updating to version 23.05, this feature is no longer available.

### Steps to Reproduce

uploading files.

### Expected Behaviour

to select the files in time.

### Screenshots or Additional Context

![Capture](https://github.com/BookStackApp/BookStack/assets/128167617/45648585-d0df-4a2d-b266-ba0c9ae9fa01)

### Exact BookStack Version

23.05

### PHP Version

8.2.6

### Hosting Environment

22.04.2 LTS

**Comment by ssddanbrown** [comment]
Thanks @mnguiro for reporting, this is probably something that I missed when changing this functionality up, since I didn't know this was a feature.
You should be able to drag+drop multiple files still, otherwise I'll tag this to be addressed in the next release, if not in a sooner patch release.

**Comment by mnguiro** [comment]
Thank you for this quick response.
We also thank you for designing this invaluable application.

We learn how to use drag and drop.

we will wait for the new version containing the correction.

THANK YOU !!!!

**Comment by ssddanbrown** [comment]
This has now been addressed in 6a7bc68b61d198a5d9f33690327f3d96cea3bc91, and will be part of the next patch release.
