### ISSUE TITLE
Custom Logon page

### ISSUE THREAD

**Issue by aegishajlmur** [BookStackApp/BookStack#4244]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

First of all, thank you for your amazing work !
I would like to know how I could customize (code, css and JS) the logon page. We would like to put our logo and change a little bit the part were you add you email and password. Is that possible ?

Many thnaks for your further help

### Exact BookStack Version

v23.05.1

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @aegishajlmur,
Our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md#visual-theme-system) allows overriding customization of any BookStack view/text/icon.

As an example, here's a hack using this system that adds custom message HTML to the login form:
https://www.bookstackapp.com/hacks/login-form-message/

**Comment by aegishajlmur** [comment]
Thank you for your help

**Comment by ssddanbrown** [comment]
Happy to have helped, will therefore close this off.
