### ISSUE TITLE
Autodiscover Languages

### ISSUE THREAD

**Issue by demlak** [BookStackApp/BookStack#4249]
### Describe the feature you'd like

As far as i understand the language-part of bookstack, currently a new language is not found in settings, until it is added to the list in `/app/www/lang/en/settings.php`. 
(Or any other choosen language?)

When adding own/custom languages, it would be nice to find them automaticaly in the settings.
Instead of using a static language-list, which has to be maintained in every Language-file, i would prefer auto discovery of every Language in the lang-folder.

Background:
We rename `books` and `shelfs` into `documents` and `categories`.. for that we add a modified version of our language files. On every update of bookstack (docker version) we have to add our own language manualy.

### Describe the benefits this would bring to existing BookStack users

a concept for automatic discovery could avoid maintaining a static list of languages in every language

### Can the goal of this request already be achieved via other means?

maybe by having a setting in system for renaming specific words

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
>We rename books and shelfs into documents and categories.. for that we add a modified version of our language files. On every update of bookstack (docker version) we have to add our own language manualy.

Hi @demlak, Based upon the above it sounds like you're actually using an existing language, but creating a modified version of it, is that correct?

If so, you'd be better off using our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md#visual-theme-system) to override select translations for your language. This would avoid you having to re-add your language on every update, allows you to override just the translations you need to alter, and voids the need for this request (And a change in process for us to handle it).

**Comment by demlak** [comment]
Thx a lot.. i'll give it a try

**Comment by demlak** [comment]
Seems to work as expected.. i think, this issue can be closed.

**Comment by ssddanbrown** [comment]
Good to hear, will therefore close.
