### ISSUE TITLE
Show Book permissions Directly on Book Cards

### ISSUE THREAD

**Issue by andriykrefer** [BookStackApp/BookStack#4250]
### Describe the feature you'd like

Currently I have to open a Book, and click "Permissions" to see this information.
I would like to see it directly on the book item on the books list, so I can see the permission for all listed books at once instead of opening one by one.

Some suggestions, in the case this implementation add too much clutter to the UI
- Make it optional
- Click on button to reveal this information
- Hover a button to reveal this information (for instance an "i" icon)

I made a draft mockup suggestion showing the group name, followed by icons representing "View, Create, Edit and Delete" permissions.

![image](https://github.com/BookStackApp/BookStack/assets/30701181/ce487802-c60d-43e9-8550-5997a7d1db87)

It would be nice to have this feature on both List and Grid modes.

### Describe the benefits this would bring to existing BookStack users

At my company, Groups and Permissions, are used to control the visibility of content according to the Groups assigned to the user.
For instance, there are book visible to "Engineering", but not to "Operations" or "Customer".
It is harder and prone to error to manage all books with this information "hidden". Sometime a book that should not be visible to some Group is left visible by mistake.

### Can the goal of this request already be achieved via other means?

No. I cannot see permission for multiple books at once, as far as I am concerned.

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @andriykrefer but this is not something I can see implementing with the core project, since I see this detail as too granular for being exposed at higher level views.

I would see #1736 and #3739 as being more appropriate solutions for reviewing permissions at a wider scale.

> Can the goal of this request already be achieved via other means?

While not direct, it could be possible to build reports via our API, since that now provides permission information.
That said, for your described use-case, you'd maybe actually want to know resolved permission status, rather than defined permission rules, which is not something we expose in a user-facing manner right now.

**Comment by andriykrefer** [comment]
Thanks for the response @ssddanbrown 

> I see this detail as too granular for being exposed at higher level views.

I agree it is too granular when you consider chapters and pages level permissions. But I would suggest only book level permissions on the card.

> I would see #1736 and #3739 as being more appropriate solutions for reviewing permissions at a wider scale.

#1736 would solve this issue for me as well! Any plans on implementing that?

> it could be possible to build reports via our API

Nice to know there is a way through the API, but a core implementation would be preferred to a hacked workaround

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off as per my reasoning above, and since #1736 would be a preferred alternative to the fundemental goal here.

> #1736 would solve this issue for me as well! Any plans on implementing that?

No plans at the moment, but I don't plan too far in advance.
