### ISSUE TITLE
Breadcrumbs not responsive on mobile

### ISSUE THREAD

**Issue by spaceraccoon** [BookStackApp/BookStack#426]
### For Bug Reports

* BookStack Version: Demo Website
* PHP Version: ^
* MySQL Version: ^

##### Expected Behavior
On mobile, the breadcrumbs should either be hidden or collapsed.  (I achieved this with a quick css fix).

![screen 2](https://user-images.githubusercontent.com/18413849/27857473-cafeba16-61ac-11e7-880d-4fddac604a1d.png)

##### Actual Behavior
Breadcrumbs are non-responsive and take up space when reading articles.

![screen 1](https://user-images.githubusercontent.com/18413849/27857474-cb076b98-61ac-11e7-8cb8-00804cb027f2.png)

**Comment by ssddanbrown** [comment]
@spaceraccoon Thanks for reporting. Will be in the next bugfix release. Made them collapse to just icons on mobile and prevented the 'toolbar' sections vertically collapsing.

**Comment by spaceraccoon** [comment]
Thanks Dan! That's much better than the quick and dirty CSS solition.
