### ISSUE TITLE
"New Page" pages keep getting added

### ISSUE THREAD

**Issue by david-burleigh** [BookStackApp/BookStack#4261]
### Describe the Bug

Phantom "New Page" pages appear in the page list of one of my books, with a purple bar at the left, and I can't find a way to delet them.

### Steps to Reproduce

I don't know what produces this.

### Expected Behaviour

I don't expect these phantom pages to appear at all...

### Screenshots or Additional Context

![Screenshot from 2023-05-24 05-26-10](https://github.com/BookStackApp/BookStack/assets/5530825/4bca83c8-cfd7-46ff-a7a7-67d7ee765d64)

### Browser Details

Firefox 113.0.1 (Linux)

### Exact BookStack Version

BookStack v22.09.1 

### Hosting Environment

Linux Mint 21.1 Cinnamon

**Comment by ssddanbrown** [comment]
> I don't know what produces this.

Whenever choose to create a new page, a draft "New Page" will be created.
The purple state indicates these are drafts, only visible to you, which have not yet been fully saved.
You can delete these via clicking into one then choosing to delete the draft via the draft status menu:

![image](https://github.com/BookStackApp/BookStack/assets/8343178/0d6c720c-6e53-40d1-b266-f72ac7577a2a)

**Comment by david-burleigh** [comment]
Thank you.
