### ISSUE TITLE
Number of Books on the page in "Books" view

### ISSUE THREAD

**Issue by jamescash120** [BookStackApp/BookStack#4266]
### Describe the feature you'd like

Would be great to have ability to change the number of Books on the page in "Books" view.

### Describe the benefits this would bring to existing BookStack users

Besides the obvious ones... In Telegram's InstantView it looks horrible and works incorrect, so for me personally, it is easier to change the number of books on the page rather than trying to figure out it in InstantView which twisted and presented "as is" and no support.

### Can the goal of this request already be achieved via other means?

Probably.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @jamescash120.

If we add a setting for this, there would become an expectation for something similar for other lists (Shelves, Shelves contents, maybe the sidebar/non-main lists). I'm not keen on going in the direction of exposing controls/options for every list. Maybe could at least group these up to shared settings. There's also the possibility of exposing via user-side controls but performance can come into question.

> Besides the obvious ones...

Can you describe the obvious ones? This kind of option has had little demand in the past so it'll be good to detail the actual benefits as I have not observed much user need for this.

> In Telegram's InstantView it looks horrible and works incorrect, so for me personally, it is easier to change the number of books on the page rather than trying to figure out it in InstantView which twisted and presented "as is" and no support.

I'm not familiar with Telegram in any way. Can you detail the issue and how such an option would help address that scenario? I don't really look to make changes to fit the concerns of other platforms but that are existing customizations/hacks that may be able to help with embedding scenarios.

**Comment by ssddanbrown** [comment]
Since there's been no follow up I'll go ahead and close this off.
