### ISSUE TITLE
Adding an btn to top menu, beside Shelves

### ISSUE THREAD

**Issue by ArmanBM** [BookStackApp/BookStack#4270]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,

I am trying to add a new menu item to the top menu of my Bookstack web application, but I am not sure how to do so. I have tried searching for documentation or tutorials on how to do this, but I have not found any clear instructions.

Can someone please provide me with step-by-step guidance on how to add a new menu item to the top menu of Bookstack? If possible, please provide me with the code snippet that I can use.

Thank you for your help.

### Exact BookStack Version

23.02.1

### Hosting Environment

Ubuntu 20

**Comment by ssddanbrown** [comment]
@ArmanBM That is not an officially supported option/feature at all. 
If handy with code/PHP, you could use our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) to override [the header template](https://github.com/BookStackApp/BookStack/blob/development/resources/views/common/header.blade.php).

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
If you need any assistance with the above customization option, feel free to still comment to request guidance/help.
