### ISSUE TITLE
Possibility to export Contained HTML file with image URLs

### ISSUE THREAD

**Issue by ondrej73** [BookStackApp/BookStack#4276]
### Describe the feature you'd like

Is there an option to export book to "not contained HTML file" with original images urls instead of having them encoded to base64? I would like to create online docs (where book exported to html is a perfect solution) with images uploaded on my server where Bookstack runs. 
Images encoded to base64 dramatically increase the filesize at the moment.
Possibility to have css file separated is the same feature for clear html output.
Did I miss any settings?

### Describe the benefits this would bring to existing BookStack users

Clean html code with minimum size for online docs, with images hosted on server and separated CSS file.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @ondrej73,

I'd have though the BookStack REST API would be suited to what you desire.
Through that you can access the plain HTML content of the page as required, without added CSS or embedded images.
I have a simple example of doing this within [this api example script](https://github.com/BookStackApp/api-scripts/tree/main/php-book-to-static-site).

Alternatively if using the default WYSIWYG editor within the BookStack UI, you can click the "Source code" button towards the end of the editor toolbar to access the page's HTML source.

**Comment by ondrej73** [comment]
Hi,
and thank you for the response. Allright, we gonna test this REST API solution.
However, I think a checkbox with "don't convert images to base64" option in the settings would be great.

**Comment by ssddanbrown** [comment]
Since the above provided solutions should suit I'll close this off.

>  However, I think a checkbox with "don't convert images to base64" option in the settings would be great.

To be honest, that's not something I'd really look to add as that opens up a whole new category of options, which I try to avoid where possible.

**Comment by ondrej73** [comment]
:(
