### ISSUE TITLE
Shortcuts are activate when try to add code block

### ISSUE THREAD

**Issue by porquero** [BookStackApp/BookStack#4278]
### Describe the Bug

If you try to insert a number when is used code block box, the system execute the shortcut.

### Steps to Reproduce

1. Edit any book.
2. Try to insert code block.
3. Insert any number.

### Expected Behaviour

Number inserted.

### Browser Details

Chrome

### Exact BookStack Version

23.05

### PHP Version

8.0

### Hosting Environment

Centos

**Comment by ssddanbrown** [comment]
Hi @porquero,
Could you try updating your BookStack instance to the latest version and see if the issue persists?
This is something I specifically addressed in [BookStack v23.05.1](https://github.com/BookStackApp/BookStack/releases/tag/v23.05.1)

**Comment by porquero** [comment]
Solved! thanks!
