### ISSUE TITLE
Allow to embed third party websites via iFrame or simular

### ISSUE THREAD

**Issue by saerdnaer** [BookStackApp/BookStack#4279]
As an editor I want to be able to embed html from external systems, e.g. a status table or simular. This could be implented by allowing the usage of an `<iframe>` HTML Tag

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @saerdnaer,
This should already be possible using the media button when using the WYISWYG editor:

<img width="498" alt="image" src="https://github.com/BookStackApp/BookStack/assets/8343178/cf2280ec-d08c-40c4-b1da-00334aff8e0e">

You may need to adjust [this security setting (Iframe Source Control)](https://www.bookstackapp.com/docs/admin/security/#iframe-src-control) to allow the remote host to be embedded within the BookStack UI (And the host must not prevent embedding).

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If you need further guidance just respond to my previous comment and this can then be re-opened.
