### ISSUE TITLE
Search Bar Element Layering

### ISSUE THREAD

**Issue by orchidObsessed** [BookStackApp/BookStack#4281]
### Describe the Bug

The current Bookstack version (and several versions prior) have an element layering issue with the searchbar. The drop-down results appear _behind_ the text field, blocking the first result.

### Steps to Reproduce

1. Have an instance of Bookstack 23.xx.xx, running on a CentOS7 box with PHP8.2
2. Populate with pages
3. Use the search bar at the top of the screen to search for an article
4. Search term & box appear over the drop-down results

### Expected Behaviour

The results start below the search bar, instead of behind it.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/74925432/1db25ff7-76c9-42ee-a68c-e65b38089aa3)

### Browser Details

All browsers (edge, Chrome/chromium-based, Firefox)

### Exact BookStack Version

2023.05.2

### PHP Version

8.2

### Hosting Environment

CentOS 7, no virtualization

**Comment by ssddanbrown** [comment]
Hi @orchidObsessed,
Thanks for reporting.

Are you able to reproduce this on our demo site?
https://demo.bookstackapp.com/

If so, can you confirm the URL in which you can replicate, and exactly where in the app this occurs (I don't recognise that style of search box for current versions of BookStack).

**Comment by orchidObsessed** [comment]
Hey @ssddanbrown!

Sorry for the false bug report - comparing the demo site to our instance, it looks like the issue is with our custom HTML head content, and not the Bookstack app.

I did catch the difference in search bar styles as well, so it looks like it's on our end. Thank you for pointing me to the demo site though, that's super useful! Wish I'd noticed it sooner... 😅 

Sorry, and thank you again!
