### ISSUE TITLE
Saving Draft bug/quirk

### ISSUE THREAD

**Issue by sadume** [BookStackApp/BookStack#429]
### For Bug Reports

* BookStack Version: 0.17.0
* PHP Version: 5.4.30
* MySQL Version: 14.14

##### Expected Behavior
When editing a page and saving a draft you click save draft and the popup goes away once the command to save the draft has processed etc

##### Actual Behavior
When editing a page and saving a draft you click save draft but the pop does not disappear once you press save, instead it only disappears once you move your mouse away. 

Can result in user(such as myself) thinking the draft didn't save and sit there spamming the save draft button when all they need to do is move their mouse and they will see the "Draft Saved" message

**Comment by ssddanbrown** [comment]
Thanks for reporting @sadume. Fix will be in the next bugfix release.
