### ISSUE TITLE
Add support for live-rendered pictures from external providers

### ISSUE THREAD

**Issue by f-steff** [BookStackApp/BookStack#4292]
### Describe the feature you'd like

This is a feature request to add support for live-rendered pictures from external providers.

Two examples of external providers are Mermaid and PlantUML, who both have public renderers available, as well as allow private renderers to be set up. Other alternatives could be the good old visit counters.

For Mermaid an example URL, which contains the image to be rendered, could be:

`https://mermaid.ink/img/pako:eNpVjstqw0AMRX9FaNVC_ANeFBq7zSbQQrPzZCFsOTMk80CWCcH2v3ccb1qtxD3nCk3Yxo6xxP4W760lUTjVJkCe96ay4gb1NJyhKN7mAyv4GPgxw_7lEGGwMSUXLq-bv18lqKbjqjGodeG6bKh69r8Cz1A3R0oa0_kvOd3jDB-N-7b5_H9ihXPrs-mp7KloSaAieSq4Q8_iyXX5_WlNDKplzwbLvHYkV4MmLNmjUePPI7RYqoy8wzF1pFw7ugj5LVx-AfLqVWg?type=png
`

Similar, for PlantUML an example URL, which contains the image to be rendered, could be:

`http://www.plantuml.com/plantuml/png/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vt98pKi1IW80`

Essentially this should end up inserting `<img src="Provided_URL" />` to the HTML of Bookstack, optionally with some WIDTH, HEIGHT, and ALT attributes.

### Describe the benefits this would bring to existing BookStack users

This would allow users to insert remotely generated graphic content.

For the examples, it would allow users to edit pictures directly in a live [PlantUML](http://www.plantuml.com/) or [Mermaid](https://mermaid.live/) editor, and save a link in Bookstack which contains everything to edit the picture.

### Can the goal of this request already be achieved via other means?

Not that I have found.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

The request differs from #566 [Diagram/graph feature on wiki via markdown syntax](https://github.com/BookStackApp/BookStack/issues/566) and #495 [Feature Request Math & UML](https://github.com/BookStackApp/BookStack/issues/495) in this is about adding a new image type where the rendered image is not cached in Bookstack.

**Comment by ssddanbrown** [comment]
Hi @f-steff,
You can set the image URL of any existing image, alongside its width and height, via the "Image" icon shown at the right side of the toolbar when an image is selected in the editor, as show below:

<img width="405" alt="Screenshot 2023-06-08 at 17 56 20" src="https://github.com/BookStackApp/BookStack/assets/8343178/8dd8b7b0-1479-4d64-8ef0-ddca8399373c">

Therefore you could insert another image like normal as a placeholder then swap out the URL for the image as required.

**Comment by ssddanbrown** [comment]
Since a potential workaround was provided above, with no further follow up, I'll go ahead and close this off.

**Comment by pjbosco** [comment]
Updating the "Image Select" dialog to accept either a link to an image or an uploaded image seems like a straight forward approach.
