### ISSUE TITLE
The format of the date and time returned by the Image Gallery API is different from other APIs

### ISSUE THREAD

**Issue by toras9000** [BookStackApp/BookStack#4294]
### Describe the Bug

In the response returned by the Image Gallery API, the format of the date/time field seems to be different from other APIs.
While other APIs return the date and time in UTC format, image-gallery create/read/update returns the date and time in local date and time format.
This is probably not the intended behavior.

Example:
- Other APIs
    - `"created_at":"2023-06-10T00:48:20.000000Z"`
- Image Gallery API
    - `"created_at":"2023-06-10 00:48:20"`

### Steps to Reproduce

Always occurs on requests to the create/read/update endpoints of image-gallery.

### Expected Behaviour

Expect the image-gallery API response to return the date and time in UTC format.

### Exact BookStack Version

v23.05.02

### Hosting Environment

Docker image, lscr.io/linuxserver/bookstack:version-v23.05.2

**Comment by ssddanbrown** [comment]
Thanks for raising this @toras9000.
I've just addressed this in 1e220c473fa71a412918a8e55b63949019b40744, which will be part of the next feature release.
