### ISSUE TITLE
Time is not displayed for the Romanian language

### ISSUE THREAD

**Issue by TheRazvy** [BookStackApp/BookStack#4297]
### Describe the Bug

Time is not displayed for the Romanian language for books and shelves.
![Screenshot_3](https://github.com/BookStackApp/BookStack/assets/48019314/f3b97748-9243-48e4-a41f-6443d82f032f)
![Screenshot_4](https://github.com/BookStackApp/BookStack/assets/48019314/1e34e587-7f52-44c6-ae53-9c42ab8471b1)

### Steps to Reproduce

Set the Romanian language in preferences

### Expected Behaviour

Display the correct time

### Exact BookStack Version

v23.05.2

### PHP Version

8.1

### Hosting Environment

Ubuntu 20.04 VPS installed using official installer script

**Comment by ssddanbrown** [comment]
Thanks for reporting @TheRazvy, Looks like the variable placeholders were accidentally translated. 
Have addressed via the [BookStack Crowdin project](https://crowdin.com/project/bookstack), Fixed translations should come through and get merged during as part of all translation updates for the next feature release.
