### ISSUE TITLE
API: Add ability to sort / order content within a book

### ISSUE THREAD

**Issue by riton** [BookStackApp/BookStack#4298]
### API Endpoint or Feature

I was unable to find an API call / endpoint that lets me adjust the **order** of content within a book.

I was only able to find an _HTML_ view that let me do that and seem to call [BookSortController](https://github.com/BookStackApp/BookStack/blob/af0b4fa851d8acda52d6176d6e9b2aef2448b499/app/Entities/Controllers/BookSortController.php#L52) for me.

### Use-Case

At [IN2P3-CC](https://cc.in2p3.fr/en/), we're planning to manage part of our documentation from Gitlab. CI/CD jobs would then update `Bookstack` according to the _Gitlab repository content_ which acts as our _source of truth_.

If new _pages_ or _chapters_ are inserted right in the middle of _other pages or chapters_ within the Gitlab repository, we require programmatic possibility to modify the _book chapters and pages_ order to match the one represented in our Gitlab repository.

### Additional context

Thanks in advance for your time and consideration

**Comment by ssddanbrown** [comment]
Thanks to @rouet in #4313 this functionality is now merged to be part of the next feature release.
A `priority` integer property can be provided on chapters and pages to control the ordering (smallest to largest priority).
