### ISSUE TITLE
Error and Attention boxes like Confluence

### ISSUE THREAD

**Issue by Hauptquartier** [BookStackApp/BookStack#430]
### For Feature Requests

Desired Feature:  Error and Attention boxes like Confluence

![attention](https://user-images.githubusercontent.com/23038635/27986390-00ec2bbe-63ff-11e7-90f1-db5e8b91703b.png)

![error](https://user-images.githubusercontent.com/23038635/27986391-03e0792e-63ff-11e7-912e-06fcd190c592.png)

![error_2](https://user-images.githubusercontent.com/23038635/27986393-087f1602-63ff-11e7-8584-143b95a7a6bb.png)

**Comment by domainzero** [comment]
Callouts do exist.

From the WYSIWYG editor you can select them from the "Formats" dropdown like so:
![callouts](http://i.imgur.com/bQinncc.png)

Using the Markdown editor you manually have to call the class to get the styling to work.
```html
<p class="callout success" id="bkmrk-sucess">Success</p>
<p class="callout info" id="bkmrk-info">Info</p>
<p class="callout warning" id="bkmrk-warning">Warning</p>
<p class="callout danger" id="bkmrk-danger">Danger</p>
```

**Comment by ssddanbrown** [comment]
@domainzero Thanks for providing the above advice. I'll consider this closed for now.

@Hauptquartier If you were after something different let me know and I'll re-open this.
