### ISSUE TITLE
Wrong size of headline at export to PDF, HTML or anythign else

### ISSUE THREAD

**Issue by Tome753** [BookStackApp/BookStack#4305]
### Describe the Bug

We think, that we found an error, when  you export sites as PDF, HTML or anything else. The size of the headline is the same like the chapter. We checked this with the markdown file and there we found that every part (headline, chapter and booktitle) has the same size. You can see this in a markdown viewer. Is this right? Normally the chapter, booktitle and headline should have a different size. 

### Steps to Reproduce

Create a book, next create a chapter, now create a site. Export this as HTML and as Markdown file. Use a markdownviewer to check the code. 

### Expected Behaviour

You will see that every title / chapter / headline has the same size. In the viewer you will see, that every part has a # in the front. Normally it should # for the book title, ### for the chapter and ###### for the headline of the page.

### Screenshots or Additional Context

![Example](https://github.com/BookStackApp/BookStack/assets/78590260/8abe2e03-21af-4a17-b698-a2b5ac2de4a8)

### Browser Details

Edge Version 114.0.1823.43 (Offizielles Build) (64-Bit)

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

8.2.6

### Hosting Environment

Linux (ubuntu 20.04)

**Comment by ssddanbrown** [comment]
Thanks for raising, but I'm not really sure what the suitable solution is, especially for markdown.
Users already have access to the full range of headers in the editor, so there's not really room to add some at the top level.
Could add complexing parsing and altering to squash at the higher-header levels as that's more likely to have unused space, but it will add fair complexity and still results in an non-ideal solution.

**Comment by Tome753** [comment]
Thanks for your answer. We thought, that this is an failure. If that is to complex to implement a different size this topic can be closed.
