### ISSUE TITLE
Update Bookstack from 22.04.2 to 23.05

### ISSUE THREAD

**Issue by Tutnich** [BookStackApp/BookStack#4311]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Update Bookstack from 22.04.2 to 23.05
Download:
cd /var/www
git clone https://github.com/BookStackApp/BookStack.git --origin release --single-branch bookstackv23.05 
cd bookstackv23.05
composer install --no-dev

Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in                                                                                                                                                              phar:///usr/local/bin/composer/vendor/symfony/console/Command/DumpCompletionCom                                                                                                                                                             mand.php:48
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in                                                                                                                                                              phar:///usr/local/bin/composer/vendor/symfony/console/Command/DumpCompletionCom                                                                                                                                                             mand.php:56
Do not run Composer as root/super user! See https://getcomposer.org/root for det                                                                                                                                                             ails
Continue as root/super user [yes]? yes
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in                                                                                                                                                              phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:881
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in                                                                                                                                                              phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:886
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/ca                                                                                                                                                             che/services.php');"
[...]
63 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan cache:clear

   INFO  Application cache cleared successfully.

> @php artisan view:clear

   INFO  Compiled views cleared successfully.

php artisan migrate

Do you really wish to run this command? (yes/no) [no]
❯ yes

In Connection.php line 760:

  SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE')

In Connector.php line 70:

  SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)

I just want to Update. I am new to Bookstack. I need help, pls.

### Exact BookStack Version

22.04.2

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @Tutnich,
A few things, first, please try updating composer.
Details for updating composer can be found at the [bottom of our updates page](https://www.bookstackapp.com/docs/admin/updates/#updating-composer).

Next, the steps you shared are incomplete steps for creating a new instance, and do not reflect the steps used to update an existing instance. Updating an instance should involve commands applied to an existing instance.
Refer to our [updates page](https://www.bookstackapp.com/docs/admin/updates) for more details.
Make sure you backup any existing files/content first.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll close this off.
