### ISSUE TITLE
Be able to edit footer of PDF or HTML files 

### ISSUE THREAD

**Issue by SamahMu7mmad** [BookStackApp/BookStack#4315]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I need to upload logo to the footer of the page instead of the author signature and dates related to the page creation & edits, or at least be able to remove it, please!

### Exact BookStack Version

v23.05.2

### Hosting Environment

Windows 10 Enterprise edition

**Comment by ssddanbrown** [comment]
Hi @SamahMu7mmad,
A request is already open to request PDF header/footer control in #493, so I'm going to close this off.

A potential workaround using our customization options can be found in this video:
https://www.youtube.com/watch?v=5bZ7zlNEphc
