### ISSUE TITLE
Custom html head content not seen by users

### ISSUE THREAD

**Issue by hlucian** [BookStackApp/BookStack#4319]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello
I have installed bookstack as a docker on a NAS and it is generally working great. 
However I noticed that changes to the "Custom HTML head content" are only seen
by myself as the admin. Users do not see these changes. E.g. I added the option two switch
between Markdown and WYSIWYG editor or to attach PDF-files. Can I enable this for all users?

### Exact BookStack Version

v23.05.2-ls85

### Hosting Environment

Docker container on QNAP NAS

**Comment by ssddanbrown** [comment]
Hi @hlucian,

> However I noticed that changes to the "Custom HTML head content" are only seen by myself as the admin.

If you believe that to be the case, can you share the custom code added so I can understand exactly what it's doing?

> E.g. I added the option two switch between Markdown and WYSIWYG editor or to attach PDF-files. Can I enable this for all users?

Those are both built-in features though? Both of those features may be permission controllers via user roles. Do the other users belong to roles that have permission to change page editor? Or upload attachments?

**Comment by hlucian** [comment]
Hi Dan

I figured it out, sorry. All my users have the role "Editor". I had to enable the features
in the role configuration in 

- System Permissions -> Change page editor
- Asset Permissions -> Attachements

Kindly
Lucian

**Comment by ssddanbrown** [comment]
Thanks for confirming, Will therefore close this off.
