### ISSUE TITLE
Setting Timezone breaks audit log

### ISSUE THREAD

**Issue by WebWalker3D** [BookStackApp/BookStack#4324]
### Describe the Bug

Everything is being recorded in UTC.  This is because the file app.php on line 74 sets it as such.  I also understand to fix this, I simply need to add the line `APP_TIMEZONE=America/New_York` in the .env and this should correct the timezone issue.  Unfortunately, what ends up happening instead is the audit log stops recording _any_ of the logs.  Unsetting this in .env fixes the audit log recording.

### Steps to Reproduce

1. Open .env
2. add line APP_TIMEZONE=America/New_York
3. save file

### Expected Behaviour

1. Open .env
2. add line APP_TIMEZONE=America/New_York
3. save file
4. audit log still records in America/New_York time

### Screenshots or Additional Context

php.ini date.timezone is set correctly  See also #2509 

### Exact BookStack Version

v23.02.2

### PHP Version

8.2.7

### Hosting Environment

Ubuntu 22.04.2 LTS VPS @ Digital Ocean, installed following the install instructions for production

**Comment by ssddanbrown** [comment]
Hi @WebWalker3D,
Just tested this, setting `APP_TIMEZONE=America/New_York` works for me.

> Unfortunately, what ends up happening instead is the audit log stops recording any of the logs. 

Are you sure this is the case?
And it's not the case that the logs are being recorded, but are just showing up below some of the older UTC logs (Which are recorded with a latter time)? This can happen when going back in time like you're doing here.

**Comment by WebWalker3D** [comment]
Yes, 100% positive. If I turn the .env variable on, nothing further is logged in audit log for anything, ever.  The second I remove this from .env everything works again as expected, just UTC

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ssddanbrown** [comment]
@WebWalker3D With the timezone changed as desired, If you create a completely new book, then create a new page within that book, then update that page, do these actions show in the sidebar when going back up and viewing that new book? Under the "Recent Activity" heading.

**Comment by WebWalker3D** [comment]
<details><summary>Large Screenshot</summary>
<p>

![Screenshot_20230616_173543_Chrome](https://github.com/BookStackApp/BookStack/assets/136760393/a3747e3c-466b-4147-b70e-d0709c03e79c)

</p>
</details>

**Comment by WebWalker3D** [comment]
These times are +4 ahead. It's UTC still

**Comment by WebWalker3D** [comment]
If I make the change in the .env file, nothing logs ever in the audit

**Comment by ssddanbrown** [comment]
@WebWalker3D Please can you respond based upon the specific steps in my last comment?

**Comment by WebWalker3D** [comment]
Yup did
![Uploading Screenshot_20230616_175652_Chrome.jpg…]()

**Comment by WebWalker3D** [comment]
![Screenshot_20230616_175652_Chrome](https://github.com/BookStackApp/BookStack/assets/136760393/1d83c0f3-405b-4854-b11b-3bab5f9404c9)
It's the same as you asked

**Comment by ssddanbrown** [comment]
@WebWalker3D That's not what I asked. I'll reformat the steps into bullet points, and specify what to screenshot:

- Create a completely new book
- Then create a new page within that book.
- Then update that page.
- View the book from the first step.
- Find the "Recent Activity" list in the sidebar.
  - On mobile, this will be under the "Info" top tab, instead of a sidebar.
- Screenshot the "Recent Activity" list along with any entries in this list.

**Comment by WebWalker3D** [comment]
Alright. I'll update on Sunday when I'm in front of a computer and not mobile. Appreciate your time my friend

**Comment by WebWalker3D** [comment]
Doing the points you asked, I get:  
![image](https://github.com/BookStackApp/BookStack/assets/136760393/df42d1a5-6699-4975-bf9f-c6fe8863195d)

The audit log shows 
![image](https://github.com/BookStackApp/BookStack/assets/136760393/1500d8a1-9177-40fc-a807-2cc779f1fe4b)

When I add the bottom line, the Audit Log stops recording
![image](https://github.com/BookStackApp/BookStack/assets/136760393/53a5b321-7910-46e3-9046-11f5b7418d84)

I'm seeing I still have the Recent Activity updating correctly when I do the steps a second time
![image](https://github.com/BookStackApp/BookStack/assets/136760393/8400d066-8381-4a5e-a69a-76a949fc7d9d)

Unfortunately, the Audit Log stops recording, for any events including login

**Comment by WebWalker3D** [comment]
I'm stupid, sorry.  lol

**Comment by ssddanbrown** [comment]
Was data being recorded as expected, but just below/behind existing audit log entries as per my first response?

**Comment by WebWalker3D** [comment]
It was.  I just didn't see it because the system was being used so there was a bunch of logs.  Today with it not being used, it was easy to see.
