### ISSUE TITLE
Creation date/time retrieved by Users-LIST API is incorrect.

### ISSUE THREAD

**Issue by toras9000** [BookStackApp/BookStack#4325]
### Describe the Bug

In the LIST endpoint of the Users API, the `created_at` field value of the responded list element appears to be incorrect.
From the looks of it, it appears to be the same as the value of `last_activity_at`.
However, i do not know if this is really the case.

### Steps to Reproduce

1. Create new user.
1. Obtain a list of users with the Users-LIST API.
    - The new user's `created_at` and `last_activity_at` are null.
1. Log in to the new user with a browser.
1. Obtain a list of users with the Users-LIST API.
    - The new user's `created_at` and `last_activity_at` are the same date and time.

### Expected Behaviour

Users-LIST API gets the correct `created_at`.

### Exact BookStack Version

v23.05.02

### Hosting Environment

Docker image, lscr.io/linuxserver/bookstack:version-v23.05.2

**Comment by ssddanbrown** [comment]
Thanks again @toras9000, Can confirm this. 
Have addressed within 00b5dd78528bff804a502dcaa5cd43b18652e0a9, and will be part of the next feature release.
