### ISSUE TITLE
'Create' Shelf Permissions not overriding group permissions

### ISSUE THREAD

**Issue by scwheele** [BookStackApp/BookStack#4326]
### Describe the Bug

When giving a user Create permissions on a shelf, the user is not able to create a new book. I'm trying to disallow users from creating books in shelves that do not belong to them. Unless I give them general "create book" permissions, they can't create any books at all.

The issue with giving the role create book permissions is that the user is able to create books in shelves that should be viewed, but only edited by the owning team.

### Steps to Reproduce

1. Create a role with no "create book" permissions
2. Create a shelf and assign an override for that role with "create" permissions
3. Create book button is missing from the shelf view

### Expected Behaviour

The New Book option should be available to users when they have the "create" override on a shelf.

### Exact BookStack Version

v23.05.2

### PHP Version

8.2

### Hosting Environment

Basic Azure App Service with a managed Azure MySQL database.

**Comment by ssddanbrown** [comment]
Thanks for raising @scwheele, but this is already covered in #2690 so I'm going to close this off as a duplicate.
