### ISSUE TITLE
Apache code highlighting

### ISSUE THREAD

**Issue by nioupola** [BookStackApp/BookStack#4327]
### Describe the feature you'd like

I'd like syntax highlighting for Apache/httpd code, same as nginx already included. It is already included in highlighting.js library.

### Describe the benefits this would bring to existing BookStack users

It's one of the most web server service and missing for the code block.

### Can the goal of this request already be achieved via other means?

No. I tried to edit manually the source code to set as `language-apache` but didn't work.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @tete2soja,
For code languages, I tend to stick with what's supported/provided officially by the codemirror project, for which there is no supported apache mode.

**Comment by nioupola** [comment]
Thanks for the feedback. I will take a look to codemirror then and to ask them to add Apache on their side to get downstream after.

**Comment by ssddanbrown** [comment]
I don't believe codemirror are taking on new languages, and there's been a [previous request for apache](https://github.com/codemirror/codemirror5/issues/6173). If you do interact with codemirror, please don't do so on BookStack's behalf. I do not wish to burden them at all for the purpose of BookStack.

**Comment by ssddanbrown** [comment]
Since there's not an official language to use, and I'm not looking to support additional languages myself, I'll close this off.
