### ISSUE TITLE
Allow Images to Appear as Modals (popup/dialog)

### ISSUE THREAD

**Issue by kenswampy** [BookStackApp/BookStack#4328]
### Describe the feature you'd like

I received a request from a client to have the ability to save images as modal images (Here's a reference: https://www.w3schools.com/howto/howto_css_modal_images.asp) so that they appear as dialog/popup/float images in the text. 

### Describe the benefits this would bring to existing BookStack users

This is purely aesthetic

### Can the goal of this request already be achieved via other means?

Possibly if I hack the backend code and add the necessary JavaScript, perhaps in a child theme would be safer, but ultimately not realistically

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

This is a low level change request to consider for future versions.

**Comment by ssddanbrown** [comment]
Thanks for the request @kenswampy, but I feel the fundamental request here is already covered by #464 so I'm therefore going to close this off as a duplicate.
