### ISSUE TITLE
Document formatting

### ISSUE THREAD

**Issue by vladime** [BookStackApp/BookStack#433]
### For Bug Reports

* BookStack Version: 0.17.0
* PHP Version: PHP7
* MySQL Version: 5.7.12

##### Expected Behaviour

1. There is a "document" in markdown formatting.
2. Switching Page editor to "WYSIWYG".
3. Editing "document" in "WYSIWYG" mode
4. Switching Page editor back to "Markdown".
5. "document" formatting is in HTML format full with HTML tags. Markdown formatting is gone forever.

##### Actual Behaviour

Formatting of a document (page) should correspond the Page editor after switch.

**Comment by lommes** [comment]
I'm not sure if this is really necessary since markdown is completly fine with including any valid HTML. There are some things you just can't do with markdown like adding classes to image tags. These customizations would be completly lost and, other than your example, has influence on the rendered output.

**Comment by ssddanbrown** [comment]
@vladime Hi there and thanks for submitting an issue.

@lommes is correct in the fact that this is technically fine and also necessary to prevent formatting loss.

An issue for pretty much the same thing is already open under #369 so I will close this issue. Feel free to contribute to the discussion there.

**Comment by vladime** [comment]
Thank you guys for the quick response.  
@lommes I get you point. It is just for some people WYSIWYG is easier to use and for some Markdown. And since there is no personal setting for default Page editor format switching feature would make sense.
@ssddanbrown thanks for the link. Will go there.
