### ISSUE TITLE
Page does not scroll to section when clicking on title in navigation

### ISSUE THREAD

**Issue by wouterVE** [BookStackApp/BookStack#4330]
### Describe the Bug

Since a few updates ago, I've noticed that my browser won't scroll to the section in question when clicking on an item in the page navigation bar. I don't see any errors in bookstack nor the browser console.
This behaviour is in any browser and on both Windows & Linux

### Steps to Reproduce

Click on an item in page navigation

### Expected Behaviour

Instead of scrolling down to the item section, the browser does scroll some random line down.

After I've scrolled down manually to the bottom of the page, the page navigation does seem to work again (untill opening a new page or refreshing the current page)

### Screenshots or Additional Context

![bookstack_avidemux_HB](https://github.com/BookStackApp/BookStack/assets/29882487/d6239e1c-ccf6-43ee-9b5d-8492bb8f137e)
See above recording of my screen: I need to click several times on an item in the page navigation untill the page has scrolled down to this section.

### Browser Details

Opera

### Exact BookStack Version

v23.05.2

### PHP Version

8.2.6

### Hosting Environment

Debian 11
Docker image = linuxserver.io

**Comment by ssddanbrown** [comment]
Hi @wouterVE,
Can you confirm if you experience the same [on our demo page here](https://demo.bookstackapp.com/books/bookstack-demo-site/page/header-level-examples#bkmrk-large-header)?

**Comment by wouterVE** [comment]
Hi @ssddanbrown 
On the demo page, everything works fine. I did use some custom CSS, as you proposed in[ this post](https://github.com/BookStackApp/BookStack/issues/4041#issuecomment-1431664836) (to add a scrollbar to the left side section), but even when I delete this custom CSS I still have the same problem.

Would it help you if I spin up a new empty instance to test if this problem still persists?

**Comment by majortomL** [comment]
Hi @ssddanbrown, I second this problem, among both Edge and Chrome. Weirdly, it works on Firefox. The demo page works fine, though. No custom CSS on our side.

**Comment by wouterVE** [comment]
@majortomL I have the same behaviour. Apparently, I didn't test it in Firefox before as scrolling does work in Firefox but not in Chromium based browsers like Opera, Edge...

**Comment by gaelanlloyd** [comment]
I was having the same issue with v23.05.2. Just updated my instance (to v23.08.2) and the problem went away.

**Comment by wouterVE** [comment]
I can confirm that the issue went away for 2 instances when upgrading to V23.08.2.
@ssddanbrown I'll close this issue
