### ISSUE TITLE
Page headings smaller

### ISSUE THREAD

**Issue by LHBL2003** [BookStackApp/BookStack#4338]
### Describe the feature you'd like

It would be good if the headings for the pages were not so huge. This often results in a line break.

### Describe the benefits this would bring to existing BookStack users

The headings are easier to read and do not take up so much space.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

If one does not want to depart from the standard, then it would be good if it can be personalised via the config file.

**Comment by ssddanbrown** [comment]
> Can the goal of this request already be achieved via other means?
> No

 Add the following to your the "Custom HTML Head Content" customization setting:

```html
<style>
  .page-content h1 { font-size: 1.5rem; }
</style>
```

Adjust the `1.5rem` up and down as desired.

**Comment by LHBL2003** [comment]
A dream, thanks for the tip.

**Comment by ssddanbrown** [comment]
:+1:  Will therefore close this off.
