### ISSUE TITLE
Sorting by name in the shelf is case sensitive

### ISSUE THREAD

**Issue by cdrfun** [BookStackApp/BookStack#4341]
### Describe the Bug

I have four books in a shelve: aa, ab, BB, BC

After sorting by name I get:

- BB
- BC
- aa
- ab

### Steps to Reproduce

Create books as described and sort them by name.

### Expected Behaviour

I'd expect to get a case insensitive sort:

- aa
- ab
- BB
- BC

### Screenshots or Additional Context

![grafik](https://github.com/BookStackApp/BookStack/assets/146877/8c99fa65-786d-452c-9b48-157fd7a65828)

### Exact BookStack Version

v23.05

### Hosting Environment

linuxserver.io Docker

**Comment by ssddanbrown** [comment]
Thanks for raising @cdrfun.
Could confirm this, was due to differences in how sorting was handled. 
I've addressed this in 9ae17efce9b3fce4d8636d14afdb005a4d795534, which will be part of the next feature release.
