### ISSUE TITLE
Options for hiding Footer Links before Log-in?

### ISSUE THREAD

**Issue by wxrl** [BookStackApp/BookStack#4343]
### Describe the feature you'd like

Would it be possible to have the setting options to hide/display **Footer Links** (set in Settings-->Customization) in Log-In page?

### Describe the benefits this would bring to existing BookStack users

It would be of great help to have the option to display only Log-in functionalities for closed/semi-closed site(s).

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @wxrl,
I generally try to avoid any settings that add visual variation like this. Combined with this being a relatively unique request, It's likely not something I'd look to add.

> Can the goal of this request already be achieved via other means?
> No.

The [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) can be used for this. You could override [the footer view](https://github.com/BookStackApp/BookStack/blob/7a6f21648a1d7286693fb7795b6e02d92f7b394c/resources/views/common/footer.blade.php#L1), and update the first line to be the following:

```blade
@if(count(setting('app-footer-links', [])) > 0 && signedInUser())
```

**Comment by ssddanbrown** [comment]
Since I wouldn't look to add this specific option, as per my comment above, and since there's been no further discussion, I'll close this off.
