### ISSUE TITLE
Error when renaming a book

### ISSUE THREAD

**Issue by david-prv** [BookStackApp/BookStack#4346]
### Describe the Bug

If I rename a book and click save, it says:

> An Error Occurred
> An unknown error occurred

When clicking "Return to Home", all made changes were saved properly. Just the redirect did not work.

### Steps to Reproduce

1. Rename an existing book
2. Click Save

### Expected Behaviour

Redirect with correct renamed book-name

### Exact BookStack Version

BookStack v23.02.1

### PHP Version

8.1.16

### Hosting Environment

Standard apache2 vHost running on a `wiki.` subdomain. We are using Let's Encrypt for free SSL Encryption.

The apache config file has the following rules:
```
<Directory /var/www/wiki.domain.tld/public>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        <IfModule mod_rewrite.c>
                <IfModule mod_negotiation.c>
                        Options -MultiViews -Indexes
                </IfModule>

                RewriteEngine On

                # Handle Authorization Header
                RewriteCond %{HTTP:Authorization} .
                RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

                # Redirect Trailing Slashes If Not A Folder...
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_URI} (.+)/$
                RewriteRule ^ %1 [L,R=301]

                # Handle Front Controller...
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^ index.php [L]
        </IfModule>
</Directory>

```

**Comment by ssddanbrown** [comment]
Hi @david-prv,

- Does this still occur if you update your instance to the latest release version of BookStack?
- If so, please can you follow [our debugging instructions](https://www.bookstackapp.com/docs/admin/debugging/) to gain details for this particular error, then share those details.

**Comment by david-prv** [comment]
An update to `v23.05.2` fixed it. Damn, that should have been my first step. Thank you and sorry for the inconvenience.
