### ISSUE TITLE
Cell/Border spacing not working

### ISSUE THREAD

**Issue by lue30499** [BookStackApp/BookStack#4348]
### Describe the Bug

The border spacing setting in the table properties isn't causing the cells to be spaced apart.

### Steps to Reproduce

1. Create table.
2. Set the table cells to have a background so its easier to see each cell.
3. Set the Cell Spacing to be something. Like 20px.
4. Observe no spacing.

### Expected Behaviour

For there to be spacing between each cell. Like below:

<img width="914" alt="Screenshot 2023-06-29 at 6 08 47 am" src="https://github.com/BookStackApp/BookStack/assets/63104612/d3d60511-2eba-48b8-abc6-e5d5a9ec57f1">

### Screenshots or Additional Context

<img width="489" alt="Screenshot 2023-06-29 at 5 59 49 am" src="https://github.com/BookStackApp/BookStack/assets/63104612/07e46ee7-5da0-47a0-baac-66754162da80">

<img width="888" alt="Screenshot 2023-06-29 at 6 00 04 am" src="https://github.com/BookStackApp/BookStack/assets/63104612/24c6a639-da8b-4349-a9c8-6d6db85f2953">

### Browser Details

Chrome 114.0.5735.198

### Exact BookStack Version

v23.05.2

### PHP Version

8.1.2-1ubuntu2.11

### Hosting Environment

Proxmox LXC
Ubuntu 22.04.2 LTS

**Comment by ssddanbrown** [comment]
Thanks for raising @lue30499, but this has already been reported within #2187 so I'll close this off as a duplicate.
