### ISSUE TITLE
IPv6 addresses in Audit log writes on top of date column

### ISSUE THREAD

**Issue by caseyrapnicki** [BookStackApp/BookStack#4349]
### Describe the Bug

When looking at the audit log, the IPv6 IP address are so long, they write on top of the next column with the date.

### Steps to Reproduce

1. Have someone connect to the site on an IPv6 address.
2. Login as an admin.
3. Browse to Settings -> Audit log. 

### Expected Behaviour

The text does not overlap.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/2466148/3c49d434-f8a2-42c5-936e-30ba597b289c)

### Exact BookStack Version

v23.05.2

### Hosting Environment

Platform.sh

**Comment by ssddanbrown** [comment]
Thanks for reporting @crapnicki.
This has been addressed in eb2c5d00cb8a3720f76f22730b3eb9c13989900f, and will be part of the next patch release.
