### ISSUE TITLE
Roles page fails to load on certain sort options

### ISSUE THREAD

**Issue by jgriffithsuk** [BookStackApp/BookStack#4350]
### Describe the Bug

When we try to go to the Role page we get a page saying

An Error Occured
An unknown error occured.

When disabling Ldap and logging in locally I still get the issue.

I basically want to create some LDAP groups so they sync the users,

Weirdly it did work once then we I press roles again I go tthe issue,

I have cleared cache and tried a different browser, (also another Pc)

is this a bug?

I am on verion v23.05.1

thanks

### Steps to Reproduce

Go to settings then roles

### Expected Behaviour

See the roles page

### Browser Details

Firefox, Chrome

### Exact BookStack Version

v23.05.1

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04 LTS

**Comment by ssddanbrown** [comment]
Hi @jgriffithsuk,
Please follow our debugging guidance to gain more detail for the error from your logs:
https://www.bookstackapp.com/docs/admin/debugging/

**Comment by jgriffithsuk** [comment]
Hi Dan

With Debug enabled I get this error

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.created_at' in 'order clause' (SQL: select *, (select count(*) from `users` inner join `role_user` on `users`.`id` = `role_user`.`user_id` where `roles`.`id` = `role_user`.`role_id`) as `users_count`, (select count(*) from `role_permissions` inner join `permission_role` on `role_permissions`.`id` = `permission_role`.`permission_id` where `roles`.`id` = `permission_role`.`role_id`) as `permissions_count` from `roles` order by `users`.`created_at` desc limit 20 offset 0)

Thanks

**Comment by ssddanbrown** [comment]
Thanks for the extra detail @jgriffithsuk,
Can confirm this occurs when sorting roles by created date.
I've assigned this to be addressed for the next patch release. 

I believe the sorting preference is saved per-user, so other admin user accounts may have working access to the roles list  if that helps.

**Comment by ssddanbrown** [comment]
This has now been patched within 18ee80a743cc54869a7b0f9c5e00527c62539ecd, and will be part of the next BookStack release.
Thanks again @jgriffithsuk for reporting.
