### ISSUE TITLE
Update time when gallery images are replaced

### ISSUE THREAD

**Issue by toras9000** [BookStackApp/BookStack#4354]
### Describe the Bug

I thought that was probably not the intended behavior, so I opened a ticket.
However, it is a trivial matter.

This is about replacing images in Image Gallery, which is supported in v23.06.
It appears that the updated date/time does not change when only replacing the image.

### Steps to Reproduce

1. Upload new images to the gallery.
1. Perform "Replace Image" on the above image.
    - The update date/time is not displayed in the information area of the image.
    - If the image name is changed, the update date and time will be displayed.

The same is true when images are replaced by the API.

### Expected Behaviour

Perhaps the renewal date and time should be changed.

### Screenshots or Additional Context

My guess is that this may be because there is no change in the database entity for the image information when the same user who uploaded the original image only replaces the image content.
(updateImageFile() in ImageRepo.php)

### Exact BookStack Version

v23.06

### Hosting Environment

Docker image, lscr.io/linuxserver/bookstack:version-v23.06

**Comment by ssddanbrown** [comment]
Thank you very much for raising @toras9000.
This has now been addressed in 96819b7bd985440f481ba0cd74aa21365aa15e6d, and will be part of the next patch release.
