### ISSUE TITLE
Reusing Page Content outside of BookStack

### ISSUE THREAD

**Issue by andreapx** [BookStackApp/BookStack#4359]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I put in Bookstack all the technical information about our products, so there are a lot of stuff more or less technical in depth.
i also use ToolJet to automatically create a webpage to share with some information that are basically the same that are in BookStack but in a nicely formatted way and automatically created with calculation, etc.
So, is there a way to use the content link (_{{@page_id#content_id}}_) outside of BookStack to have just the selected text/images without the BookStack frontend that I will get using the full link?

### Exact BookStack Version

v22.11.1 

### Hosting Environment

Ubuntu 22.04 with Docker container

**Comment by ssddanbrown** [comment]
> So, is there a way to use the content link ({{@page_id#content_id}}) outside of BookStack to have just the selected text/images without the BookStack frontend that I will get using the full link?

Not to the level of getting a specific block.
The closest available is using the REST API, which you'd use to get the HTML contents of a page (via its ID) then parse out a specific block yourself on the non-bookstack-end. I'm not familiar with Tooljet so not sure what you have available in that regard.

**Comment by andreapx** [comment]
> > So, is there a way to use the content link ({{@page_id#content_id}}) outside of BookStack to have just the selected text/images without the BookStack frontend that I will get using the full link?
> 
> Not to the level of getting a specific block. The closest available is using the REST API, which you'd use to get the HTML contents of a page (via its ID) then parse out a specific block yourself on the non-bookstack-end. I'm not familiar with Tooljet so not sure what you have available in that regard.

Thanks for the quick reply. 
I can try to do a workaround placing in the middle Node Red, but what do you think to add _content_id_ to the APIs?

**Comment by ssddanbrown** [comment]
> what do you think to add content_id to the APIs?

I'd be hesitant to add that based upon this request alone, because it wouldn't be exposing any more BookStack-side abilities or data, but instead suiting a specific external flow to simplify client usage.

I just had a play with ToolJet, It seems that the DOM is available in their "RunJS" scripts, so you could use that to parse HTML once fetched. Not sure how practical that is in regards to building into your use-case though.

**Comment by andreapx** [comment]
I get your point of view.
From mine, it would be so much easier to just select a portion of the page in BookStack and directly use it elsewhere without the need to work on it with JavaScript (that may not work in the future if I edit the page in BookStack).
Thanks for having a look!

**Comment by ssddanbrown** [comment]
Since the original support case has been answered I'm going to go ahead and close this off.
