### ISSUE TITLE
Cannot Login - explode(): Passing null to parameter #2 ($string) for saml2 in config file (but never used it!) 

### ISSUE THREAD

**Issue by sebzan** [BookStackApp/BookStack#4360]
### Describe the Bug

When accessing my Bookstack app on my Synology suddenly an error message shows up about "explode(): Passing null to parameter #2 ($string)" in Config file Bookstack.

I can see the login page but when I try to login I come to an error page.

Funny thing is that I´m not even using saml2 in any way, newer have!

I can see in Portainer that there have been an update  at "2023-07-03 09:03:24" (local time) for the image - and the application worked the day before yesterday....

I'm using the latest image, solidnerd image.

### Steps to Reproduce

1. Go to login page - see error message at the top of page
2. Try to login
3. Landing on a 404 page - error message at the top of page

### Expected Behaviour

1. Go to login page
2. Login
3. Get logged in

### Screenshots or Additional Context

This is the error message on top of the screen:
_Deprecated
: explode(): Passing null to parameter #2 ($string) of type string is deprecated in
/var/www/bookstack/app/Config/saml2.php
on line 17_

![2023-07-04_12h18_43](https://github.com/BookStackApp/BookStack/assets/22288383/fa8ea041-d72b-4080-887b-d064d5d243f7)
![2023-07-04_12h19_00](https://github.com/BookStackApp/BookStack/assets/22288383/ffc5d798-2da2-4281-a1e3-b8b1025d75f9)

### Browser Details

Latest chromeversion on Windows 10 (latest)

### Exact BookStack Version

23.6.0

### PHP Version

8.2.7

### Hosting Environment

Im running Bookstack via Docker on my Synology station.

Synology OS: DSM 7.2-64570 Update 1
Synology model: DS720+
RAM: 10 GB
Docker version: Latest, "Container Manager"

**Comment by ssddanbrown** [comment]
Hi @sebzan,
You have not stated which docker image you're using, but I'm assuming the solidnerd image?
If so, please try updating the image in use as they patched this issue yesterday.

**Comment by sebzan** [comment]
Hi,

Sorry, updated the bugreport now, using the latest image...

BR Zeb

**Comment by ssddanbrown** [comment]
@sebzan Can I confirm the method you're using to check you're using the latest image?

**Comment by sebzan** [comment]
In portainer it looks like this:
![image](https://github.com/BookStackApp/BookStack/assets/22288383/806f81dd-dbd3-4a13-ae21-988876415d3d)
![image](https://github.com/BookStackApp/BookStack/assets/22288383/f36cc1ca-7a08-4c30-a142-661bfc646b2e)

I´ve also recreated the container for bookstack just now via Portainer and pulled the latest image and that did not work either.

**Comment by ssddanbrown** [comment]
Okay, thanks @sebzan for confirming.
If you use `solidnerd/bookstack:23.6.0-1` instead of `solidnerd/bookstack:latest` that should get you to the patched version.
Looks like their patched container image isn't tagged to `latest`, which [I've raised with the solidnerd container](https://github.com/solidnerd/docker-bookstack/issues/410) team.

**Comment by sebzan** [comment]
Okay @ssddanbrown;

I´ll try to edit the image version in portainer and the pull that image down... Will get back.

**Comment by sebzan** [comment]
@ssddanbrown:
[First exuse me for my lacking skills on container as such. I´ve installed the bookstack app as a "stack" via Portainer following a post from "Marius hosting"].

I´m trying to change the image version as you mentioned above in portainer but I really seems to miss something because where i´m filling in the new image version in "Container> Bookstack> Container details and Create image" nothing happends after updating. And of course I´m a bit carefule since I have a lot of doumentation in the app. (db). :)

Where do I actually change from using the ":latest (not latest) image version to the one you mention without messing up the DB after puling down and creating a new image?

**Comment by ssddanbrown** [comment]
@sebzan Unfortunately I'm not familiar with portainer at all.
I was kind of hoping you'd just be able to change the `image` form field you had in your screenshot above.

Go careful though! Ideally make sure you have backups of docker volumes in use, and/or backups/snapshots of the entire host system if possible.

**Comment by sebzan** [comment]
@ssddanbrown: I´ll will do a more exact check later on today and then might have a go agian. :)

But, If the latest released version (solidnerd/bookstack:23.6.0-1) is fixed, since it´s actually is a problem, then I don´t need to do anything more than just "pull down" the image again in portainer and viola. :) - So let´s hope your friends will fix it quickly. :)

**Comment by sebzan** [comment]
@ssddanbrown: 
Workaround fixed for the error in "the latest build" - everything is working again. :)

This bug can be closed.
