### ISSUE TITLE
Font size for books title

### ISSUE THREAD

**Issue by MInus63** [BookStackApp/BookStack#4361]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello

I have applied your recommendations for changing font sizes as follows:

```
<style>
.page-content h1 { font-size: 1.8rem; }
.page-content h2 { font-size: 1.6rem; }
.page-content h3 { font-size: 1.4rem; }
.page-content h4 { font-size: 1.2rem; }
.page-content h5 { font-size: 1.1rem; }
.page-content h6 { font-size: 1.0rem; }
</style>
```

However, I realized that it doesn't change the font for the book, chapters and may be shelves titles.

It's OK when you display the list of available books, but, for exemple, if you click on a book to see the chapters and pages listed in that book, then the book title is in very large, unmodified type.

Is there an option I forgot to add in my modifications?

### Exact BookStack Version

v23.01.1 

### Hosting Environment

Debian 11

**Comment by ssddanbrown** [comment]
There are no specific classes/ids to target for the desired titles, but you could generically target them via:

```html
<style>
.content-wrap h1 {
 font-size: 1.8rem;
}
</style>
```

Note: this may affect other areas of the app also, not just those requested titles.

**Comment by MInus63** [comment]
Hi

Thanks Dan, that's exactly what I wanted 

```
<style>
.content-wrap h1 { font-size: 1.8rem; }
.page-content h1 { font-size: 1.8rem; }
.page-content h2 { font-size: 1.6rem; }
.page-content h3 { font-size: 1.4rem; }
.page-content h4 { font-size: 1.2rem; }
.page-content h5 { font-size: 1.1rem; }
.page-content h6 { font-size: 1.0rem; }
</style>
```

**Comment by ssddanbrown** [comment]
Awesome! will therefore close this off.
