### ISSUE TITLE
Page Details - Updated: giving missinformation date and author modification

### ISSUE THREAD

**Issue by Lelandi** [BookStackApp/BookStack#4369]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Greetings.
I've been experiencing some issues relative to "Page Details".
These problems started to appear last week and the docker container was up for more than 2 months without being updated.
Some users related some "ghost" updated info, showing time and user in the pages. Some pages are without any changes for almost a year but theres a Updated message saying the page was edited 6 days ago. 
![bookstack 1](https://github.com/BookStackApp/BookStack/assets/45545514/76491ac0-183f-48ad-9439-6adfc3db3a05)
![bookstack 2](https://github.com/BookStackApp/BookStack/assets/45545514/f19ca67e-8c90-4f73-b8e9-b8f1c7edd4e3)

I've updated the Bookstack version for the latest 23.06.1 from 23.02.2 and the issue remains.

### Exact BookStack Version

v23.06.1

### Log Content

bookstack    | [custom-init] No custom files found, skipping...

bookstack    | [06-Jul-2023 19:48:35] NOTICE: PHP message: PHP Warning:  PHP Startup: Invalid date.timezone value '', using 'UTC' instead in Unknown on line 0

bookstack    | [ls.io-init] done.

### PHP Version

PHP 8.2.7 (cli) (built: Jun  9 2023 00:27:17) (NTS)

### Hosting Environment

docker image: ghcr.io/linuxserver/bookstack:23.06.1

**Comment by ssddanbrown** [comment]
Thanks for reporting @Lelandi, but this is essentially already open under issue #1777, so I'll therefore close this off as a duplicate.
