### ISSUE TITLE
Expand edit view

### ISSUE THREAD

**Issue by 22Alena22** [BookStackApp/BookStack#4374]
### Describe the feature you'd like

Currently, the editing view is limited to a certain area. What leads to the fact that wide tables are displayed very squeezed. It would be nice if the editing interface would stretch over the entire area of the browser when editing pages. So that the entire white space under the menu can be used as a writing surface. 

### Describe the benefits this would bring to existing BookStack users

A big advantage would be the possibility to display more information on one page. But also wide graphics and tables could be displayed larger. Which makes them more readable and user friendly. 

### Can the goal of this request already be achieved via other means?

Currently I don't know that this function could be covered with another function. There are similar solutions only for tables, but not for the complete workspace. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

![image](https://github.com/BookStackApp/BookStack/assets/139131615/acdf6d58-d19b-4230-99c5-5b5acda8efc4)
I have marked the area in question in yellow in this image.

**Comment by ssddanbrown** [comment]
Hi @22Alena22,
The edit view is intended to mirror the display view of page content. I wouldn't look to change the content width just for the edit view.

The set content wide has been discussed, with some potential  workarounds, in #1757.
I have previously provided my thoughts in regards to the set width in #3408.

**Comment by ssddanbrown** [comment]
Since I wouldn't look to add the specific requested feature as per my message above, and since there's been no further discussion, I'll close this off.

**Comment by PhilippRieth** [comment]
I've thrown together some CSS and JavaScript that can be put into the "Custom HTML Head Content" -> [Extra Wide Pages and Editor for selected pages | Reddit
](https://www.reddit.com/r/BookStack/comments/1h0p79m/extra_wide_pages_and_editor_for_selected_pages/)
