### ISSUE TITLE
Right to create in the shelf

### ISSUE THREAD

**Issue by twrona** [BookStackApp/BookStack#4375]
### Describe the Bug

The right to create no longer appears in the shelf permissions, but on the books. Since it is not present on the shelves, it cannot be propagated on the books.

### Steps to Reproduce

Go to shelf permissions. Compare with book permissions

### Expected Behaviour

Have the right to create on the bookshelf to automatically propagate to the books on the shelf

### Screenshots or Additional Context

Sur étagères : 
![image](https://github.com/BookStackApp/BookStack/assets/96485903/420472b2-92d6-425c-988c-fcd47aa26c91)

Sur les livres sous cette étagère : 
![image](https://github.com/BookStackApp/BookStack/assets/96485903/70f66409-7355-40c8-996d-b719c673e9de)

### Exact BookStack Version

BookStack v23.06

### Hosting Environment

Ubuntu 22.04

**Comment by twrona** [comment]
on another bookstack in version BookStack v23.05.2 the parameter appears on the shelf permissions.

![image](https://github.com/BookStackApp/BookStack/assets/96485903/262e0ee3-f073-4dfe-8916-c8b4e81f287c)

**Comment by ssddanbrown** [comment]
Thanks for raising @twrona.
My apologies, this appears to be an oversight on my part.
The shelf create permission option was removed as it was thought to be useless, since they didn't have any direct functionality.

I completely missed the use-case of these permissions being used via the "Copy Permissions to Books" functionality.
I'll assign this to a new patch release and look to get something out within the next few days.

**Comment by twrona** [comment]
Thank you very much for your prompt reply. 
In fact, it was useful for me to automatically push bookshelf permissions every hour to avoid overloading books by users.  

Looking forward to the correction, thank you very much.

**Comment by ssddanbrown** [comment]
Okay, have now applied ae834050f58ab8dd963ac390c11e48a674b2bd8b to revert the permission removal, and have added a notice instead to indicate the limited use-case of this permission action.

Apologies again for this. Unfortunately existing shelf-create permissions would have been removed upon previous upgrade, so you'll have to re-check this create permission for any applicable shelves.

I'll be releasing v23.06.2 shortly with this patch included within.

**Comment by ssddanbrown** [comment]
@joaomezzari Tagging you for visibility of my last message since you were also affected by this.
