### ISSUE TITLE
Default permission on page independent of book/chapter permission

### ISSUE THREAD

**Issue by fbehmenb** [BookStackApp/BookStack#4378]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,
I recently started working with Bookstack and would like to use it to create internal and external documentation. This also works very well.
Unfortunately, I still have a small problem with the permissions. I have already experimented with permissions, but have not yet found the right solution for my problem.

I have shared books and chapters so that I can assign the following access rights.
![image](https://github.com/BookStackApp/BookStack/assets/112687778/11e5951c-0f16-4565-8366-34573d49e8b2)

I would like to create a new page now, that in the default only internal have access to the page. So that external get an access, the author or the employee should have to change the rights Manuel via the menu item "Authorization". That means, in the default, no rights of the book or the chapter may be inherited. Is there anywhere to set this? I have found nothing in the files.

The reason why I want this is that I want external users to be able to browse the BookStack by navigating through shelves, books and chapters. Also, the public user should be able to see a tree structure. I don't want the other authors to have to check if only internal users can see this page.

Can you help me?

I look forward to your help.

Greeting
Florian

### Exact BookStack Version

v23.06.1

### Hosting Environment

Ubuntu 22.04 on AWS

**Comment by ssddanbrown** [comment]
Hi @fbehmenb,

>  That means, in the default, no rights of the book or the chapter may be inherited. Is there anywhere to set this?

There is no option for setting alternative item-level default permissions.
On any chapter/page creation the item-level permissions will be blank by default, and therefore user permissions from roles and, if set, parent books/chapters.

**Comment by fbehmenb** [comment]
Hey Dan, is there no way to remove the "Inherit Default" hook in the default?
![image](https://github.com/BookStackApp/BookStack/assets/112687778/a66f2eb0-175a-43c2-a8b2-b7aaf54d6c5a)

Just removed this hook in my test on the authorization of the page and everything is as I want it :-)

**Comment by ssddanbrown** [comment]
No, nothing built in to do that.

If you're handy with PHP, it's possible to use the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) to listen to new item creation and alter permissions as desired.

**Comment by fbehmenb** [comment]
Thank you for your help. This will be a good solution.

**Comment by fbehmenb** [comment]
thank you for your help. This will be a good solution.

**Comment by demlak** [comment]
Hey... old Thread.. but @fbehmenb do you have a solution on this? Maybe you can share your code?
