### ISSUE TITLE
Copy shelf permissions not completely working

### ISSUE THREAD

**Issue by joaomezzari** [BookStackApp/BookStack#4379]
### Describe the Bug

Hello,
We have a few shelves within our BookStack instance. I use the command line to copy the permissions from the shelves to the books, chapter and pages, as described here: https://www.bookstackapp.com/docs/admin/commands/#copy-shelf-permission (pretty much use the php artisan bookstack:)copy-shelf-permissions --all)

For some reason, the permissions to CREATE pages and chapters are not cascading anymore, even if I use the buttom in the application.

<img width="786" alt="image" src="https://github.com/BookStackApp/BookStack/assets/53047818/4e08ab36-6d18-442a-9c86-e882e564123c">

It seems the "CREATE" in the permissions is missing. I have visualize, update and delete, as you can see in the 3 roles in the print above, so it doesn't replicate? I'm kinda lost. I can create books inside the shelf, but not pages or chapters inside those books.

If I check the specific book permissions, the CREATE permissions are unchecked:
<img width="596" alt="image" src="https://github.com/BookStackApp/BookStack/assets/53047818/f37a7aca-12ff-4a24-a55a-6d9ded3c1243">

If I check those and then run the copy-shelf thing, it unchecks it back (I believe that it's because it's missing in the shelf permissions in first place).

### Steps to Reproduce

1 - Open the shelf
2 - Try to add a new page to a existing book
3 - The option will be missing

### Expected Behaviour

The permissions are inherited from the shelf where the book is located.

### Browser Details

Google Chrome 114.0.5735.199

### Exact BookStack Version

v23.06

### PHP Version

PHP 8.2.3

### Hosting Environment

Ubuntu Server 18.04, installed using the official installation script

**Comment by joaomezzari** [comment]
Maybe related to:
https://github.com/BookStackApp/BookStack/issues/4375

Thanks in advance, love BookStack

**Comment by ssddanbrown** [comment]
Hi @joaomezzari,
This is indeed the same as #4375 so I'm going to close this off as a duplicate.
