### ISSUE TITLE
Add the header summary when in editiong mode and add some border and padding to the editor

### ISSUE THREAD

**Issue by navotera** [BookStackApp/BookStack#4381]
### Describe the feature you'd like

1. Add the heading tree in the Editor Mode. 
Currently, the book or page only focuses on the reader. It seems missing a feature that also makes the author **convenient** when doing a modification or creating a new book that has long content. Without the need to scroll on top or bottom, it will be better if there is a feature that allows the author to view the heading tree and can click to jump to the respected heading. 

This is nicely already implemented with Google Docs and WordPress editor. 

Let me share a screenshot : 
![image](https://github.com/BookStackApp/BookStack/assets/1424851/f7f31f49-98f5-41c6-8ad3-6e1f36d8c6fc)

2. Add some display hacks to allow some borders when editing in the HTML editor mode. 
In Editor Mode, it will be better to see some space and border between the area that allow the author to edit the content and the area that acts as the background. 

Although this can be implemented by using custom CSS, I think this will be better to add to the main CSS. 

![image](https://github.com/BookStackApp/BookStack/assets/1424851/c5a12e3d-b8b1-4cc1-bf12-220121fbe9e8)
to

### Describe the benefits this would bring to existing BookStack users

The editor or Author will be easier to browse and outline some of the ideas through summary of heading. 

### Can the goal of this request already be achieved via other means?

No, no such feature is available to achieve this for point 1. 
For point 2 it can be achieved by attaching custom CSS. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @navotera,
A request for table of contents (header summary) in the editor is already open in  #4218.

In regards to editor border/padding, I wouldn't look to make those changes in the core app, and prefer to leave it up to customizations where desired. I have had some desire for a more page-simulating edit area, but if I was to make such a change I'd probably want to further integrate the editor to be part of that page area, rather then be a page fully within the editor area.
