### ISSUE TITLE
Feature to sort shelves manually bring to good organize documentations

### ISSUE THREAD

**Issue by pemudakoding** [BookStackApp/BookStack#4382]
### Describe the feature you'd like

Currently, the BookStack App has a limitation in its sorting functionality. It can only sort shelves by name or created date by default. However, when using BookStack for multiple projects documentation, it becomes essential to have more flexible sorting options to better organize the documentation.

In a scenario where BookStack is being used as a documentation tool for multiple projects, there may be a need to categorize and group the documentation into different shelves based on projects, topics, or any other relevant criteria. By utilizing shelves, users can logically organize the documentation and easily navigate through the different projects and their corresponding documentation.

However, the default sorting options of sorting shelves by name or created date might not be sufficient in such a context. Users may require additional sorting options, such as sorting shelves by project priority, last updated date, or any custom criteria that aligns with their specific needs. Having these sorting options available would greatly enhance the organization and accessibility of the documentation within BookStack.

By expanding the sorting capabilities to include more criteria, users can have better control over the arrangement of shelves, making it easier to locate and manage documentation for different projects. This flexibility allows for a more efficient workflow, improved collaboration, and easier navigation within the documentation system.

In summary, while the current version of BookStack only offers basic sorting options for shelves, when BookStack is used as a documentation tool for multiple projects, it becomes crucial to enhance the sorting functionality. By incorporating more versatile sorting options, users can better organize their documentation and optimize their overall documentation management process.

like the example below: 
![image](https://github.com/BookStackApp/BookStack/assets/62993054/b6ed6ce6-a52f-4597-8772-a46df080ed85)

it will better if showing us like image below: 
![image](https://github.com/BookStackApp/BookStack/assets/62993054/817ef2f9-0444-4275-8958-e5d9b56446f8)

In order to facilitate a smooth onboarding experience for newcomers, it is important to prioritize their visibility to the shelves specifically designed for them. By ensuring that newcomers can easily find their respective shelves, they can quickly access the relevant documentation and resources they need to get started.

When multiple shelves exist within a documentation system, it can sometimes be overwhelming for newcomers to navigate and locate the shelves that are most relevant to them. To address this challenge, it is beneficial to implement a strategy that highlights or prioritizes the shelves meant for newcomers.

By making the newcomer shelves more prominently visible, such as placing them at the top of the shelf list or featuring them in a dedicated section, newcomers can easily identify and access the materials tailored to their needs. This approach streamlines their onboarding process, allowing them to efficiently explore the documentation that is specifically curated to support their learning and integration into the project or organization.

Prioritizing the visibility of newcomer shelves demonstrates a commitment to providing a positive user experience for new users. It helps to alleviate any potential confusion or frustration they may encounter when navigating through the documentation. By ensuring that the newcomer shelves are easily discoverable, organizations can foster a welcoming and supportive environment, enabling newcomers to quickly access the resources they require to ramp up their knowledge and become productive contributors.

In summary, emphasizing the visibility of newcomer shelves is essential for facilitating a seamless onboarding process. By making these shelves easily accessible and placing them in a prominent position within the documentation system, newcomers can swiftly locate and engage with the materials specifically designed to assist them in their initial stages of involvement. This approach ultimately contributes to a more efficient and effective integration of newcomers into the project or organization.

I would to like request feature to sort shelves manually like books, chapter or page did.
![image](https://github.com/BookStackApp/BookStack/assets/62993054/461fb1d4-b881-442a-b2cc-b16858e4b94f)

### Describe the benefits this would bring to existing BookStack users

Prioritizing the visibility of newcomer shelves in BookStack brings several benefits to existing users within the context described. Here are some advantages they can experience:

1. Improved Collaboration: By ensuring newcomers can quickly find their relevant shelves, existing users can more easily connect and collaborate with them. Clear visibility of newcomer shelves fosters a welcoming environment, encouraging existing users to engage and support newcomers as they navigate through the documentation. This enhances teamwork and knowledge sharing among all users.
2. Time Efficiency: Existing users can save time by directly accessing the shelves related to their ongoing projects or areas of expertise. With newcomer shelves prominently displayed, existing users can efficiently locate and retrieve the resources they need without spending unnecessary time searching through multiple shelves. This streamlined access allows them to focus more on their core tasks and responsibilities.
3. Knowledge Transfer: Existing users often possess valuable knowledge and expertise that can benefit newcomers. When newcomer shelves are clearly visible, existing users can identify areas where they can contribute their insights or assist newcomers in understanding the project-specific documentation. This facilitates knowledge transfer and helps build a stronger community of users.
4. Enhanced User Experience: Prioritizing newcomer shelves demonstrates a commitment to creating a positive user experience for all users, including existing ones. By organizing and highlighting newcomer resources, existing users can appreciate the effort put into improving the onboarding process. This can contribute to a more positive perception of the documentation system as a whole.
5. Support for Project Growth: As projects evolve and new users join, ensuring the visibility of newcomer shelves becomes crucial. By prioritizing these shelves, BookStack accommodates the scalability and growth of projects, making it easier for existing users to orient themselves and integrate newcomers seamlessly. This scalability ensures the long-term viability and usability of the documentation system.

In summary, prioritizing the visibility of newcomer shelves benefits existing BookStack users by facilitating collaboration, saving time, enabling knowledge transfer, enhancing user experience, and supporting the growth of projects. By creating an inclusive and efficient environment, BookStack becomes a more valuable tool for both newcomers and existing users, fostering a thriving community and driving project success.

### Can the goal of this request already be achieved via other means?

Yes we can achieve it with existing method by editing the date in order and order the shelves by created_at

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @pemudakoding,
I'm going to close this since we already have #180. I may update that to reference shelves, but it's essentially the same desire, of manually sorting top level items.

If you open new issues here in future, please don't just use an LLM to massively fill out the issue form like this.
I don't mind LLM being used to assist as a tool, but it's quite clear most of this is just LLM generated text.
Not only does the mass amount of repetitive text here waste time of maintainers, it really isn't helpful since it makes your core desire less clear. I ask these questions to make requesters think about what they fundamentally require, and the outcomes from that. This is important since I decide what's valuable to implement or work on based upon actual user need. LLM text like this, as reflected above, is just going to produce a lot of theoretical use-cases and reasons, which your own needs will get lost within and I'd end up disregarding anyway since it's not clear what's real.
