### ISSUE TITLE
WYSIWYG and markdown not working

### ISSUE THREAD

**Issue by anthonycaccese2** [BookStackApp/BookStack#4384]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

![image](https://github.com/BookStackApp/BookStack/assets/110774542/d2f4eff6-02a0-4856-9485-457e52504533)
I've installed the windows version of bookstack using this tutorial. Everything appears to be fine besides the markup/WYSIWYG editors. I notice that there is an error in the browser console saying the following. 
![image](https://github.com/BookStackApp/BookStack/assets/110774542/96c5f24f-9ae1-4b0c-956e-21a06cd94f3a)

### Exact BookStack Version

BookStack v23.06.2

### Hosting Environment

Windows 10 using the official git hub. Followed the following video: https://www.youtube.com/watch?v=_v-4BhVz7OI

**Comment by ssddanbrown** [comment]
Are there any specific issues outside of those warning messages being logged?

**Comment by anthonycaccese2** [comment]
> Are there any specific issues outside of those warning messages being logged?


This is also being logged in the browser. 
![image](https://github.com/BookStackApp/BookStack/assets/110774542/5792aee6-8cef-4762-9839-efad68dbf821)
I also found theses from the xammp server
[Sat Jul 15 11:52:28.453297 2023] [ssl:warn] [pid 32740:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 15 11:52:28.490293 2023] [ssl:warn] [pid 32740:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 15 11:52:28.907918 2023] [mpm_winnt:notice] [pid 32740:tid 400] AH00455: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4 configured -- resuming normal operations
[Sat Jul 15 11:52:28.907918 2023] [mpm_winnt:notice] [pid 32740:tid 400] AH00456: Apache Lounge VS16 Server built: Mar  7 2023 13:21:03
[Sat Jul 15 11:52:28.907918 2023] [core:notice] [pid 32740:tid 400] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Sat Jul 15 11:52:28.911885 2023] [mpm_winnt:notice] [pid 32740:tid 400] AH00418: Parent: Created child process 32104
[Sat Jul 15 11:52:29.278652 2023] [ssl:warn] [pid 32104:tid 404] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 15 11:52:29.320655 2023] [ssl:warn] [pid 32104:tid 404] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jul 15 11:52:29.361650 2023] [mpm_winnt:notice] [pid 32104:tid 404] AH00354: Child: Starting 150 worker threads.
[Sat Jul 15 11:56:39.339362 2023] [mpm_winnt:crit] [pid 32104:tid 404] AH02538: Child: Parent process exited abruptly. Child process is ending

Haven't been able to find any other errors anywhere else. No logs exist in the storage/logs/

**Comment by ssddanbrown** [comment]
So you're not experiencing any functional issues at all?
The markdown and WYSIWYG editors are loading and functioning okay?

Just asking since these logs aren't really relevant to functionality or a concern.

**Comment by anthonycaccese2** [comment]
> So you're not experiencing any functional issues at all? The markdown and WYSIWYG editors are loading and functioning okay?
> 
> Just asking since these logs aren't really relevant to functionality or a concern.

Bookstack is functionally working, account creation, books and bookshelf creation, etc. The markdown and WYSIWYG editors are not loading at all. So if try to bold a line using ctrl+b, that does nothing along with the markdown equivalent, **text**.

**Comment by ssddanbrown** [comment]
Okay. Could you confirm the exact browser URL path you're at when you're on a BookStack view where you're expecting the markdown, or WYSIWYG, editor to load?

**Comment by anthonycaccese2** [comment]
> Okay. Could you confirm the exact browser URL path you're at when you're on a BookStack view where you're expecting the markdown, or WYSIWYG, editor to load?

Yeah I made a bookshelf with a book called this is my book. When I edit the book there is no WYSIWYG editor
![image](https://github.com/BookStackApp/BookStack/assets/110774542/61092e1d-ec76-41b3-8472-fed408f84bad)

Same with editing a bookshelf: 
![image](https://github.com/BookStackApp/BookStack/assets/110774542/e5bca655-6db9-4358-b7a3-21df7078c90f)

**Comment by ssddanbrown** [comment]
Shelves, Books and Chapters do not have WYSIWYG editors, or support markdown, in BookStack. They just have plaintext descriptions. Only pages have content that is edited via WYSIWYG or Markdown.

**Comment by anthonycaccese2** [comment]
> Shelves, Books and Chapters do not have WYSIWYG editors, or support markdown, in BookStack. They just have plaintext descriptions. Only pages have content that is edited via WYSIWYG or Markdown.

Oh ok thats too bad, I thought there was. Thanks for the clarification!

**Comment by ssddanbrown** [comment]
No worries, I'll therefore close this off.
