### ISSUE TITLE
Sub-directory setup for Bookstack installation

### ISSUE THREAD

**Issue by basil-thgnet** [BookStackApp/BookStack#4385]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

I need to load bookstack with url as mentioned below:

http://domain.com/ok

All the books and uploads should load from the said path, because we are setting the bookstack to load via a sub-drectory "/ok" for knowledge-base as like:

https://domain.com/ok

I have tried updating the APP_URL, updating the URLs in database and still no use and the bookstack gets broken. I have tried the https://www.bookstackapp.com/docs/admin/subdirectory-setup/  but that is a different scenario. 

Could you let me know if bookstack can be called via >> http://domain.com/ok

### Exact BookStack Version

v23.06.2

### PHP Version

PHP 8.2.8

### Hosting Environment

Ubuntu 20.04.2

**Comment by ssddanbrown** [comment]
> I have tried the https://www.bookstackapp.com/docs/admin/subdirectory-setup/ but that is a different scenario.

Please can you explain why that is a different scenario that can't be followed here?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
