### ISSUE TITLE
Messy interface when opening pages on mobile

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#4387]
### Describe the Bug

On mobile phones, when we open pages in bookstack, the interface is not properly rendered for the mobile screen and is unusually small, and an unrelated error pops up as well. (screenshots included)

### Steps to Reproduce

1. On your mobile phone, go to bookstack.
2. Open a page.
3. The interface is messed up.

### Expected Behaviour

I expect the interface to be rendered properly and to fit the screen; and I also don't want to see any unrelated errors.

### Screenshots or Additional Context

![photo_3_2023-07-18_15-37-29](https://github.com/BookStackApp/BookStack/assets/100111649/f24751d7-417e-457c-82c5-94df63ec2360)
![photo_1_2023-07-18_15-37-29](https://github.com/BookStackApp/BookStack/assets/100111649/cffd011e-6595-460c-bcbc-e4bfac279989)

### Browser Details

Google Chrome Version 104.0.5112.102 (Official Build) (64-bit) On Windows 10

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 20.04 VPS, installed via docker.

**Comment by ssddanbrown** [comment]
Hi @okaeiz,

- Are you able to replicate this [on our demo instance](https://demo.bookstackapp.com/)?
- If not, do you have customizations applied to your instance?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
