### ISSUE TITLE
Page Expiration / Update Content Manager

### ISSUE THREAD

**Issue by Shackelford-Arden** [BookStackApp/BookStack#439]
# Desired Feature
So, once you've added a lot of content to your site, I believe it can be difficult to know what content was last updated and when (on a large scale).

I would find it helpful if:
- We could set a "field" on a page of when it's content needs to be updated or when it's marked as "outdated". 
- Have a view where we can see pages ranked by last modified date or their expiration date.

This view would help editors/admins know when pages need to be updated or potentially even removed.

Just a thought I had for myself and potentially groups who use Bookstack for content that changes on a frequent bases (like technical guides or documentation).

**Comment by dsaundersWizmo** [comment]
This would be a huge feature-- if a document could be flagged as _Outdated_ or _Needs Review_ by users.  Then, users (but not writers) of the documentation can easily communicate where there was an issue either with accuracy, clarity of wording, or order of the process.

The comments section would be a sufficient place to leave appropriate feedback I should think-- it would be interesting maybe if there was an _Issue_ comment type that could be marked as resolved and hidden from the main page (maybe just viewable in the revision history.  personally, I don't like seeing comments that are out of date as much as I don't like seeing pages that are out of date).

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since there's been little demand on this specific issue since it was opened. 
Note, there have been some options added since this request:

- You can filter search results based upon updated date.
- You could apply tags, such as "Last Reviewed At: 20220511" then run a tag query such as `[Last Reviewed At<=20220601]`
