### ISSUE TITLE
Main Menu Editor

### ISSUE THREAD

**Issue by redwoodcurtaindesign** [BookStackApp/BookStack#4391]
### Describe the feature you'd like

It would be helpful to edit the header menu in a similar manner to adding footer links

### Describe the benefits this would bring to existing BookStack users

There may be ways of using/navigating the system that the developer couldn't anticipate, and this would give that flexibility. For example, we use tags to mark content as "known wrong" or "incomplete", and then we can refer back to those tags when possible to polish documentation. Adding the /tags URL to the main menu would make finding that out of compliance content easier for us.

### Can the goal of this request already be achieved via other means?

Not that I've found. Links can be added to the footer, but that is more useful for rarely-used items (e.g., an impressum)

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @redwoodcurtaindesign,
This has been previously touched upon in #4270.
The visual theme system, as advised in that issue, is generally the way I go about providing customization options in BookStack, since I don't look to add additional options without additional specific reasoning or requirement.

**Comment by redwoodcurtaindesign** [comment]
@ssddanbrown well that will teach me to check support requests and not just feature requests 🤦‍♂️ 

I'll look into that and go from there. Thanks!
