### ISSUE TITLE
All in one simple gui backup solution

### ISSUE THREAD

**Issue by AuthorShin** [BookStackApp/BookStack#4398]
### Describe the feature you'd like

Thank you for creating and maintaining this incredible project.
It would be even more amazing if a straightforward backup and restore section could be added to support all environments and underlying systems. This would greatly simplify the migration process and ensure data preservation for large Bookstack instances. Additionally, it would be beneficial to have the option to schedule backups at custom intervals and save them locally or in cloud storage platforms like Nextcloud.

### Describe the benefits this would bring to existing BookStack users

This way docker users can easily make backups and migrate to different instance also scheduled backups make it possible to be a head of server failure by backing up the datas to a single unified file on a offsite storage.

### Can the goal of this request already be achieved via other means?

I don't know

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request but we already have #723 and #2405 which generally cover the fundamental request here, or at least act as a prerequisite.
