### ISSUE TITLE
Comment Management

### ISSUE THREAD

**Issue by Shackelford-Arden** [BookStackApp/BookStack#440]
# Desired Feature

I know this is pending a merge, but comments are coming to Bookstack. I've looked around a little bit but there doesn't seem to be a way for anyone to see (from a "birds eye" what pages are getting commented on. Would there be a way to see a list of pages that have comments sorted to show the most recently commented on page at the top of that list?

Just a thought...

@Abijeet Correct me if I just missed something in your code :) Nice work btw! Looking forward to seeing this!

**Comment by AbijeetP** [comment]
@Shackelford-Arden - Thanks! And yes, you are right, currently the comment system does not offer any notification. 

I feel that we need an overall notification system, that informs me of whats going on with things that I'm interested in. Comments can be a part of this.

We'll have to first design the system on how we want it.

**Comment by Shackelford-Arden** [comment]
@ssddanbrown I think for the purpose I had in mind, that'll work just fine :smile: .

In my mind, a more down the road look at it (in my mind) would be something of a dashboard of sorts. But, your idea works just fine for me :+1: 

Thanks!
