### ISSUE TITLE
access restriction

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#4404]
### Describe the feature you'd like

Is it possible to restrict access for a role only to a specific shelf or book?

### Describe the benefits this would bring to existing BookStack users

Allows you to adjust the visibility level more precisely

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Have you tired doing this via content level permissions?:

https://www.bookstackapp.com/docs/user/roles-and-permissions/#content-level-permissions

Give the role no permissions by default, then set permission on a specific item.

**Comment by jefry7** [comment]
Thank you very much! This is what need. It remains to understand whether it is possible to bind an LDAP group to a group in bookstack

**Comment by jefry7** [comment]
LDAP group syncing is declared. We will try to configure
