### ISSUE TITLE
How we can pass JWT Token on bookstack for authentication of user login ?

### ISSUE THREAD

**Issue by namannj46** [BookStackApp/BookStack#4405]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Actually i have integrated bookstack in our website through iframe.
so i want that when a user login to my website and click on bookstack module it automatically log in to the bookstack which is integrated in the website through iframe, we dont want to login again on bookstack when we actually logged on website already.

Is there any token or hash is passed on website url to authenticate the user.
kindly please suggest ways to deal

### Exact BookStack Version

v23.05.2

### Hosting Environment

ubuntu 22.04

**Comment by ssddanbrown** [comment]
> Is there any token or hash is passed on website url to authenticate the user.

No, there is not such functionality built in, and it's not something I'd look to support.

If you have PHP development skills available, you could use our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) to pick up any URL details and deal with them accordingly.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.
