### ISSUE TITLE
Huntr.dev - Webhooks

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#4410]
https://huntr.dev/bounties/9ce5cef6-e546-44e7-addf-a2726fa4e60c/

Reported by @scgajge12

**Comment by ssddanbrown** [comment]
Added in c324ad928dbdd54ce5b09eb0dabe60ef9de1ea38 and 903895814ace77cd30c22b57de16f9e22daf21e4

**Comment by scgajge12** [comment]
@ssddanbrown 
Thanks for the correction!
I would like to mark the fix as complete and request a CVE on "Huntr.dev".

**Comment by ssddanbrown** [comment]
@scgajge12 Sure, I've now done this since the release has been published.
Thanks again for reporting @scgajge12.
