### ISSUE TITLE
Aprove change/create role

### ISSUE THREAD

**Issue by magaiverpr** [BookStackApp/BookStack#4414]
### Describe the feature you'd like

We are wanting to use Bookstack to produce certains projects documentation. We are thinking that would be nice if we produce this documentation and give to the PO to approve (or not, asking for changes), creating an "official document" that everybody agree.

Some things that could be nice:

- Set book to be only visible after aproved.
- Set book to ask for a reason if not approved.
- Ask for aprove when any changes is made in the book, keeping the "oficial document".
-  Show who aproved the book.

### Describe the benefits this would bring to existing BookStack users

This could benefits other users that need to officialize documents or projects that is has been creating and demand an aproved scope.

### Can the goal of this request already be achieved via other means?

We can verbally agree to set visible the books after an email aproval, put it would be better to use this feature inside bookstack.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request, but I feel the fundamental desired ability here is already covered by  #473 so I'll therefore close this off as a duplicate.
