### ISSUE TITLE
Multiple Domain Controller Support

### ISSUE THREAD

**Issue by Gameink** [BookStackApp/BookStack#4415]
### Describe the feature you'd like

I have a Project where I try to create a KB for Multiple Windows Domains. Currently, I map one Domain via LDAPS. 

Would it be possible to add more than one LDAPS server in config and select them via the entered domain?

Like.
Smith@Domain1
sandra@domain2
...

Are there any Features Planned like this? 

I hope this is no repost and that I post this in the right section :)

### Describe the benefits this would bring to existing BookStack users

Some Companies use multiple Domains for their Locations. Having the ability to add all of them to one site would give us the opportunity to only create one site which authenticates all users and provides them with necessary information.

This keeps the Web server instance slim as only one instance has to be installed, maintained and secured.

### Can the goal of this request already be achieved via other means?

Maybe using multiple Auth Methods parallel.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for detailing your request @Gameink, but I feel this is already covered by #543 so I'll therefore close this off.
