### ISSUE TITLE
Azure AD Authentication: Role Assignment

### ISSUE THREAD

**Issue by mschoon85** [BookStackApp/BookStack#4417]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi @ssddanbrown,

We are in the process of implementing Azure Active Directory (AD) Authentication, and the progress has been satisfactory thus far. We have successfully created new profiles. Within Azure AD, we have established a group named "AzureTEST". Correspondingly, in Bookstack, we've created a role that shares the same name and external ID. However, we are encountering an issue: when a user associated with the "AzureTEST" group logs in, their user profile is created as expected, but the role isn't automatically assigned as intended.

Thus far, we have the following configuration in our ENV file:

AZURE_APP_ID= X
AZURE_APP_SECRET= X
AZURE_TENANT= X
AZURE_AUTO_REGISTER=true
AZURE_GROUP_SYNC=true

Kind regards,

Michel

### Exact BookStack Version

23.06.1

### Hosting Environment

Windows 2022 with Apache

**Comment by ssddanbrown** [comment]
Hi @mschoon85,

There is no built in group sync support for the AzureAD third party authentication option. 
I'm not sure where that `AZURE_GROUP_SYNC` option has come from.

If everyone would be logging in via AzureAD, then I'd probably recommend using [OIDC in BookStack](https://www.bookstackapp.com/docs/admin/oidc-auth/), connected to AzureAD.

I have a video on OIDC with AzureAD here:
https://foss.video/w/n67qNijhf8BdTRQys8SDYf

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If you need further help just respond to my previous comment.
