### ISSUE TITLE
Page previews failing for pages that begin with included content

### ISSUE THREAD

**Issue by XtremeBain** [BookStackApp/BookStack#442]
### For Bug Reports

* BookStack Version: v0.17.1
* PHP Version: 7.0.15
* MySQL Version: 5.7.17

##### Expected Behavior
The chapter page which lists pages with their previews should properly render the preview for pages that have included content in the beginning of them.

##### Actual Behavior
On the main page of a chapter that lists all of a chapter's pages, if a page's preview contains an include tag for another page or bookmark, there is a javascript TypeError exception logged to the console and the page list does not render.

**Comment by ssddanbrown** [comment]
@XtremeBain Thanks for reporting, Will be in the next bugfix release.

I've updated it so included content is parsed into the text view for list previews and searching. This is only on save though (For performance reasons) so it is possible that this text content may become outdated if the included content is changed.
