### ISSUE TITLE
 Multi-tenant across different servers

### ISSUE THREAD

**Issue by 22Alena22** [BookStackApp/BookStack#4425]
### Describe the feature you'd like

We have been working with Doku Wiki so far. Here it was possible to run one instance at the customer's site and one at ours. The status in our Wiki was then synchronized with the customer.  This way we could work with the customer in the same wiki but we didn't have to give him access to our wiki, as this would not be a good solution for data protection reasons.  Multi-Tentant in itself already exists, is an extension possible here? via a synchronization between intersecting servers? 

### Describe the benefits this would bring to existing BookStack users

The advantage here would be the simplified and safer collaboration with customers in a wiki. So both parties are up to date and do not run any security risk. 

### Can the goal of this request already be achieved via other means?

in principle, it can be partially covered with the multi-tenant solution but not fully, hence this new request. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @22Alena22,
Sorry for the delayed response.

> Multi-Tentant in itself already exists

I would not consider multi-tenant (As considered in the world of software) to be something supported within BookStack at all. We have a fairly extensive role-based permission system, which could be used to divide up access but we don't offer any features to manage multiple distinct environments within a single system, nor do I see that being something worthwhile to build in. My recommendation here has generally been to set up multiple instances in such scenarios.

> via a synchronization between intersecting servers?

There is not synchronization, or partial import/export, built into the system to support this. You could automate/program something along these lines using the REST API. That'd probably be the best option. There would likely be some complexities involved in that though (2-way sync can especially be a pain plus that are complexities like media/related-content management).

**Comment by 22Alena22** [comment]
Thank You for your Feedback. :) We solve the Problem with eh Pythen Skript, now we can Sync the information between diffrent Systems.

**Comment by Man-in-Black** [comment]
@22Alena22 do you mind sharing your code? I'm interested in it too, because I got two Bookstack instances which I want to sync partially.

**Comment by 22Alena22** [comment]
Hello Sascha, 

I have now turned the whole construct around a bit. We have a DokuWiki instance running at the customers. I now export the text file from this and read it in via phyton and convert it to Markdown. It has not become a direct BookStack sync.

**Comment by Man-in-Black** [comment]
Hi Alena,

thanks for the reply.
