### ISSUE TITLE
The width of the table columns is evenly distributed during the export

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4428]
### Describe the Bug

Hello,

when exporting a page as a PDF with built-in tables, the size of the columns is evenly distributed. As a result, content is unnecessarily squeezed.
It also didn't work when I put in fixed values, it automatically translates the fixed values to relative values.

### Steps to Reproduce

1. Create a table with multiple columns
2. Column width changed so that all columns have different widths
3. Export as PDF

### Expected Behaviour

When exporting, all columns should have the same relative width as seen in Bookstack.

### Screenshots or Additional Context

View in Bookstack:
<img width="434" alt="image" src="https://github.com/BookStackApp/BookStack/assets/9048534/11ecdcc4-382e-434b-9b74-61a17951edf5">

Result after Export as PDF:
<img width="397" alt="image" src="https://github.com/BookStackApp/BookStack/assets/9048534/aad87f81-9661-4828-9a4f-17f5ed2ffc3f">

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 22.04
installed using official installation script

**Comment by ssddanbrown** [comment]
Thanks for raising @Man-in-Black, but I'm going to close this off as a duplicate as I feel #1280 covers this.

**Comment by Man-in-Black** [comment]
Thanks, didn't found this issue.
