### ISSUE TITLE
Bookstack Tiny 6 - Font  / Size formatting

### ISSUE THREAD

**Issue by Nexow91** [BookStackApp/BookStack#4433]
### Describe the feature you'd like

Hello all, 

please forgive me if I post this wrong. 
First of all I love Bookstack and I maintain my entire wiki in Bookstack and wouldn't want to miss the app. 

What I would like to see are div. buttons to change text. I know via Header HTML that works but that affects mostly always the whole template and one would like but rather individual formats, sizes anlagen. I have seen that Bookstack works with the TinyMCE or with the WYSIWYG editor. 
Are we still on version 5, because on version 6 there are already buttons for font and size. 

I'm sorry if I'm not familiar with this, I'm just a user and I've already tried to create a custom button to change formatting in the editor. 

I am grateful for any advice and any tip and hope the app is getting better and better since this was recommended to me and I am so far quite happy with it :) 

PS: 

I use Booksack as Docker over Unraid on the version. 
BookStack v23.06.2

Greetings

### Describe the benefits this would bring to existing BookStack users

Simply executions and changes of formats

### Can the goal of this request already be achieved via other means?

Maybe Custom Codes

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @Nexow91,

BookStack currently ships with TinyMCE 6.5.1:

https://github.com/BookStackApp/BookStack/blob/1c922be4c7b0e32c57511e8875d479b99b763f75/public/libs/tinymce/tinymce.min.js#L2C4-L2C4

We purposefully don't allow changing the font size of font style of text within pages, to keep formatting limited and controlled, and to encourage proper use of headers. There is already an existing request & discussion for font-size control in #1148.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion, and since the requested functionality is likely already requested via another issue as above, I'll close this off.

**Comment by Nexow91** [comment]
sry I had forgotten to give feedback :( 
Yes unfortunately I would still prefer a full editor integration to create like Word, Notepad++ or other editors a custom formatting and also so the font sizes to be able to change but unfortunately this is only possible in a roundabout way anyway thanks for the info then I know at least that I need there no more energy purely put :)
