### ISSUE TITLE
Image compression for PDF export

### ISSUE THREAD

**Issue by Eekrs** [BookStackApp/BookStack#4437]
### Describe the feature you'd like

Compression of images in PDF files.

### Describe the benefits this would bring to existing BookStack users

PDF files are getting very large when using a lot of high quality images. Compressed images would reduce the file size.
Furthermore the PDF generation runs in timeouts, because of the file size. Benefit would be that PDF files with high quality images could be generated.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @Eekrs,

Do you have a simplified example to share, where it shows this is problematic?

From what I can tell, the PDF should be built from PNG/JPEG data which is already compressed via its file format.
On image upload/insert within BookStack, we generally limit to 2x page width which should limit dimensional scale of images in most cases.

I'd just need something a bit quantifiable to look into.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll go ahead and close this off.
