### ISSUE TITLE
Allow users to set WSYWIG or mardown in their own profile settings

### ISSUE THREAD

**Issue by lithium-arp** [BookStackApp/BookStack#4438]
### Describe the feature you'd like

Allow users to set whether they want to use markdown or WSYWIG

### Describe the benefits this would bring to existing BookStack users

Markdown is a very efficient way to create documents. Some of my associates prefer to WSYWIG while others, markdown. Having the ability for a user to set this preference within their own profile, or on the fly, would bring greater flexibility to the system. 

### Can the goal of this request already be achieved via other means?

This use case, no. It is set from a system-wide perspective. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Over 5 years

**Comment by ssddanbrown** [comment]
Hi @lithium-arp,
Since it's not mentioned in this request, just wanted to ensure you're aware it's possible to change editors from within the editor, on a per-page basis, as shown from about 1:39 in my video here: https://foss.video/w/b4aTq3YzsTVjdEFBQtuHgZ?start=1m39s

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll go ahead and close this off.

**Comment by lithium-arp** [comment]
Apologies... I thought this container was updating automatically. Thank you
