### ISSUE TITLE
Allow to add ref/variable of content.

### ISSUE THREAD

**Issue by racson** [BookStackApp/BookStack#4439]
### Describe the feature you'd like

Drawing inspiration from the current template feature, is it possible to develop a new function that functions as a variable feature? This would enable user to create specific pages as variables and insert them into other pages as needed. For instance, I could create a template for Terms & Conditions or document flow, ensuring that any changes made to these variables are automatically synchronized across all pages. Consequently, whenever I update the variable template, all pages utilizing the variable will be automatically updated with the latest version of its content.

### Describe the benefits this would bring to existing BookStack users

more convenient, time-saving

### Can the goal of this request already be achieved via other means?

Yes, copy and paste it into all different books and pages.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by cactus264** [comment]
@racson 
Good afternoon. Why was the topic closed? Did you find such functionality? or someone before you created such a request to add this functionality?
I really need this functionality. I read about it, but under a different name, macros in confluence are really what you need when a large knowledge base is planned.
