### ISSUE TITLE
Sorting of books is lost when copying

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4443]
### Describe the Bug

We have created a book as a template in our bookstack and now want to copy it. However, the manual sorting of the book is lost and is sorted automatically (by name?)

### Steps to Reproduce

1. Create a book with a fixed strcuture
2. hit the copy button
3. strucutre is lost

### Expected Behaviour

After clicking on copy the structure should be maintained.

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 20.04 VPS, installed using official installation script

**Comment by ssddanbrown** [comment]
Thanks for reporting this @Man-in-Black,
From testing on between versions, it looks like this was addressed for v23.08, while performing changes to support sorting for the API.
I'll therefore close this off but if you do continue to experience issues on the current version of BookStack feel free to still comment and this can be re-opened.

**Comment by Man-in-Black** [comment]
Hi, it seems to work fine now ;) thanks for the fast solution.
