### ISSUE TITLE
Updating a book/page does not affect "updated date" of shelf

### ISSUE THREAD

**Issue by etcy** [BookStackApp/BookStack#4450]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Current Behavior:
When a page is being updated/created, the book correctly shows the "updated date" but the "updated date" is not reflected at the shelf level. I suspect that this could be a design/feature rather than a bug but all my users think otherwise.

Even if it is by design, is there a way for me to modify the codes so that it behaves like what my users expect?

### Exact BookStack Version

v23.05.2

### Hosting Environment

Ubuntu 20.04, installed using official script

**Comment by ssddanbrown** [comment]
Hi @etcy,

> When a page is being updated/created, the book correctly shows the "updated date"

It doesn't as far as I know. It may do for some operations but most simple create/update of child content won't specifically touch the updated time of parent items.

> but the "updated date" is not reflected at the shelf level

Same as above for shelves, although the shelf->book relation is looser than other relations so less chance of there being a connection between these items.

> Even if it is by design, is there a way for me to modify the codes so that it behaves like what my users expect?

There's nothing built in or supported to do this.
If you have some PHP skills, you could use our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) to listen to update/create events of certain content then update the timestamp of related shelves.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll go ahead and close this off.
