### ISSUE TITLE
Role with global book create rights cant create Books under the shelves

### ISSUE THREAD

**Issue by mi-wulf** [BookStackApp/BookStack#4456]
### Describe the Bug

I have a custom user role with rights to create, edit and delete books, but if I login with a user with that role I cant create books under shelves.

### Steps to Reproduce

1. Create a custom user role with the right to create and edit books.
2. Give a user the custom role
3. Login as the user as the user and try to create a book under a shelf

### Expected Behaviour

That I can create a book under a shelve with my custom role.

### Screenshots or Additional Context

Role that has Books allow "everything":
![image](https://github.com/BookStackApp/BookStack/assets/129871417/cf10f2c6-cded-4343-9b9c-f2010739fa52)

Shelf view where I should be able to create the Book:
![image](https://github.com/BookStackApp/BookStack/assets/129871417/fca980ca-2f2d-47b3-89a7-3062f63d58c2)

### Browser Details

Google Chrome Version 116.0.5845.96

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 22.04.2 LTS

**Comment by ssddanbrown** [comment]
Hi @mi-wulf,
For bookshelves, we consider the relation to books part of the shelf itself. Therefore creating books directly within a shelf also requires the ability to edit the shelf in use.

**Comment by mi-wulf** [comment]
Hi @ssddanbrown,

thank you for the fast feedback and you explanation! The book creation works with the shelv edit right.
