### ISSUE TITLE
Feature Request: Word Count On Pages

### ISSUE THREAD

**Issue by My-Random-Thoughts** [BookStackApp/BookStack#4458]
### Describe the feature you'd like

Add a count for the number of words for a particular page.
Maybe include other stats like number of images, incoming links, etc.

### Describe the benefits this would bring to existing BookStack users

Allow users that use BookStack as a non-documentation tool, fiction book author for example, to see current work counts.

### Can the goal of this request already be achieved via other means?

No.  Only by copy/pasting into a word processor.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @My-Random-Thoughts.

From my view, this is probably not something I'd look to add for the following reasons:
- This has (as far as I can remember) not been requested before reflecting little demand.
- This request describes the benefits for "users that use BookStack as a non-documentation tool". I rather keep vision and development focused to our main use-case which is a documentation tool.
- I'm not sure what seeing word count actually provides in value/benefits other than an arbitrary metric to observe. I only really like adding metadata where a functional purpose is provided.

Depending on where you'd want this, and the skills at your disposal, this kind of thing may be relatively simple to hack into an instance via the [various available customization options](https://www.bookstackapp.com/docs/admin/hacking-bookstack/).

**Comment by My-Random-Thoughts** [comment]
That's fair.  I'll have a look see if I can hack something together.
Thanks
