### ISSUE TITLE
Allow hyperlinks and formatting in description of shelves, books and chapters

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4460]
### Describe the feature you'd like

It would be a nice feature if it were possible to insert for example functioning link into the description of book.
I have some chapters in which it would be a huge bonus. At the moment I had to make an extra side just to put a link into it.
In this case I'm building an internal documentation to bookstack itself and I want to reference to the homepage directly on the chapter.
Like in this picture but with a clickable link.
![image](https://github.com/BookStackApp/BookStack/assets/9048534/60b0d15b-2ee7-484f-8de5-f8c0f18fe99d)

### Describe the benefits this would bring to existing BookStack users

Links to source pages or referenced pages without having to create a separate page for it.

### Can the goal of this request already be achieved via other means?

I didn't find anything

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by matthias4217** [comment]
I agree this would be nice.  However, it has already been discussed in previous issues (#1666 and #1076) and it’d seem it won’t be implemented. However, an issue to support hyperlinks #2354 is still opened, as well as #2203 to support raw html in book descriptions.

**Comment by ssddanbrown** [comment]
Thanks for the suggest @Man-in-Black, but as pointed out by @matthias4217, #2354 already exists which I'd consider as already covering the fundamental request here. Therefore I'll close this off.

@matthias4217 As part of working on comments recently, it's in my mind to align various text inputs (comments input and content description fields) with a simpler WYSIWYG editor, and bring some added functionality as requested here. Won't promise a timeline for that but thinking within next few feature releases, so maybe by end of year.
