### ISSUE TITLE
Diagrams always are full width and pushed to the left; unable to be center or right aligned

### ISSUE THREAD

**Issue by jeremyherbert** [BookStackApp/BookStack#4463]
### Describe the Bug

No matter how I position my diagram on the canvas, it always has the diagram pushed to the left and the right spacing extended to the maximum:

![Edit_Page_Draft___BookStack_Demo](https://github.com/BookStackApp/BookStack/assets/52499/a43e88e2-4535-41b5-a86b-2818ee823dce)

I would like to center my diagram, but this seems impossible.

(note that the light blue rectangle was added by me highlighting the image in my browser to show the empty space)

### Steps to Reproduce

1. Go to demo instance and open a draft/new page
2. Add a diagram 
3. Add a small shape to the center of the canvas
4. Save and exit the diagram editor
5. The image in the editor does not have the shape at the center, and has significant blank space to the right

### Expected Behaviour

The PNG generated from the diagram should either be the same size as the canvas, or the minimum size needed to hold the diagram. It shouldn't arbitrarily add maximum whitespace to one side.

### Screenshots or Additional Context

(see earlier)

### Browser Details

Chrome 116.0.5845.110

### Exact BookStack Version

Whatever is on the demo server :)

### Hosting Environment

Whatever is on the demo server :)

**Comment by ssddanbrown** [comment]
Hi @jeremyherbert,
Thanks for raising, although this is not something I'd consider a bug, but maybe something behaviour different to expectations.

Within BookStack we consider drawings block level elements, which spans the width of the content area like other block level types. The drawing itself is often smaller though relative to that block width, so it gets left aligned by default within the container (Or right aligned if the page content is detected as primarily RTL language text). No arbitrary whitespace is specifically added.

If you'd like drawings to be center you could add this to the "Custom HTML Head Content" customization setting:

```html
<style>
  .page-content [drawio-diagram] {
    text-align: center;
  }
</style>
```

**Comment by jeremyherbert** [comment]
Thank you! That has sorted it for me. I'm happy for you to close this issue if you don't feel it is a bug.

**Comment by ssddanbrown** [comment]
Happy that works for you! Thanks, will therefore close this off.
