### ISSUE TITLE
Comparison table/matrix

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [BookStackApp/BookStack#4465]
### Describe the feature you'd like

Forgive me if there's already something like this, but I couldn't find it.

We have a use case in which we would like to document our organization's application suite and which departments get the respective applications. It would end up being tens of rows and columns (see additional context for example).

### Describe the benefits this would bring to existing BookStack users

We think having this capability would provide a quick way to answer a question with regard to "what applications does _x_ department use" or "does _x_ department use _x_ application" without digging through system configurations.

### Can the goal of this request already be achieved via other means?

We attempted to do this with the existing table function, however, the table becomes squished between the page margins (due to the number of columns required), making the content unreadable and adjusting the rows and columns has diminishing returns.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

https://wcs.smartdraw.com/software/img/feature-comparison-chart-example-2.png?bn=15100111875

**Comment by Man-in-Black** [comment]
A little tweak I discovered was to put in a personalized CSS in the <head> in the settings menu:
~~~
<style>
@media screen and (min-width: 1400px) {
  .tri-layout-middle-contents {
      max-width: 1700px;
  }
}
.page-content { max-width: 1200px; }
</style>
~~~
So I got a bit more space in the wideness of the page.

**Comment by FMCUSystemAdmins** [comment]
Thanks @Man-in-Black, but even with that, it doesn't give enough room for what we're looking for. I'm thinking it would have to be a scrollable table of some sort to "fit" with the page layout.

**Comment by ssddanbrown** [comment]
Thanks for the request @FMCUSystemAdmins.
Personally, I don't really want to be adding use-case specific block/formatting support, like I'd consider this to be. Especially where this would be very similar to an existing block options (tables) and we'd be facing the same issues/considerations that make tables an issue for this case.

**Comment by FMCUSystemAdmins** [comment]
@ssddanbrown, understood. Thank you
