### ISSUE TITLE
Editor scrolling doesn‘t work on mobile devices

### ISSUE THREAD

**Issue by BnAmN** [BookStackApp/BookStack#4466]
### Describe the Bug

On mobile devices (and mobile-sized desktop browsers) it‘s not possible to scroll the Markdown editor vertically (using touch or mouse wheel) if there are more lines than the viewport can display.

I‘m encountering this issue for a while now, but sadly I can‘t really tell the version I first encountered it. But it was definitely working fine in earlier versions.

I was able to workaround the issue by adding the following CSS:

```css
.markdown-editor-wrap {
  height: 100%;
}
```

### Steps to Reproduce

1. Use a mobile device (or a mobile-sized desktop browser)
2. Open a Book
3. Enter „Edit“ mode
4. In case there aren‘t enough lines: add some new lines until you leave the bottom of the screen
5. Try to scroll down to the bottom line

### Expected Behaviour

The editor is vertically scrollable.

### Browser Details

Any browser

### Exact BookStack Version

v23.06.2

### PHP Version

8.1

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Thanks @BnAmN, can confirm this issue. Getting a bit close, so could slip, but I've assigned to try to sneak into next upcoming feature release. 

### Dev notes

Needs flex balancing and maybe min-heights applied to get the flex to fit container.
Sections can have flex basis' left over from horizontal split control, which can interfere. Needs to work-with/override that.

**Comment by ssddanbrown** [comment]
Addressed in dc77233ec30ff4c58ba6f22ba6b39edee3443282, to be part of v23.08
