### ISSUE TITLE
List of who read the page.

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#4468]
### Describe the feature you'd like

Ability to get a list of users who have read the page

### Describe the benefits this would bring to existing BookStack users

Identify the popularity of pages. Make sure that the person has read the page

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @jefry7, but this has been touched upon in previous issues, including #518, #3736, #3609 and #2835.

**Comment by jefry7** [comment]
ok, we are waiting
