### ISSUE TITLE
Training plan

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#4469]
### Describe the feature you'd like

Determine the sequence of books, pages to read. Without confirmation of reading, the next page is unavailable. For each user individually

### Describe the benefits this would bring to existing BookStack users

Building training with the ability to track progress

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

When a new person comes to the team, he gets lost in the variety of books/ pages. In order for the study to be most effective, a plan with a sequence of books/ pages is needed

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @jefry7.

While I can understand the desire for something like this, from my perspective this is a rather use-case specific feature that's directly brining tangential business/use-case-specific process into the platform, which is something I'd generally want to avoid adding complexity for.

**Comment by jefry7** [comment]
I understood, it turns out it's only to make a separate page with a list of links in sequence and hope for the user's self-organization

**Comment by jefry7** [comment]
but to achieve the goal, it would be possible to use the list of views function. To track progress

**Comment by witi77** [comment]
It would be easier to have a book read event possibility within the webhook so you can record who reads which book and track progress like that. That would be less complex to add a new layer of functionality

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off for the reasoning of my previous comment.

I keep webhooks (and audit log) scoped to system change events, so I don't really want to expand out to view events for these subsystems.

We do record views though in a rolled-up manner, so a level of per-user-per-item view data is available via the database if needed. We could possibly add a [logical theme](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) event to hook into these if desired, and you have the resources and intent to build your own connected solution. That can be requested via a new request issue of desired.
