### ISSUE TITLE
Confirm email settings

### ISSUE THREAD

**Issue by salimnanji** [BookStackApp/BookStack#447]
### For Feature Requests
Desired Feature: Page to confirm system settings, i.e. if mail is configured correctly
When going to the "Forgot Password" for example, I see "Whoops, looks like something went wrong.". I imagine my mail config is incorrect.

**Comment by bensulli** [comment]
This is covered in a previous feature request:
https://github.com/BookStackApp/BookStack/issues/408

Might be worth commenting there to show support!
