### ISSUE TITLE
site structure

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#4470]
### Describe the feature you'd like

I would like to see a separate page where all shelves/ books/pages/paragraphs will be displayed in a tree view

### Describe the benefits this would bring to existing BookStack users

Quick content navigation

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by Man-in-Black** [comment]
I think this is the same feature request as this one: https://github.com/BookStackApp/BookStack/issues/616

**Comment by jefry7** [comment]
yes, the latest screenshots are what I would like to see

**Comment by ssddanbrown** [comment]
Since this is already covered by existing issues (#616, #2494) I'll close this off.
