### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#4471]
### Describe the feature you'd like

Sometimes you need to attach the original document/instructions in PDF format

### Describe the benefits this would bring to existing BookStack users

there is no need to look for another place to store files

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by Man-in-Black** [comment]
I think this is the same feature request as this one: https://github.com/BookStackApp/BookStack/issues/616

**Comment by jefry7** [comment]
if about #4470, then yes, this is what I would like to see

**Comment by jefry7** [comment]
I found about uploading files. https://www.bookstackapp.com/docs/admin/upload-config/

**Comment by Man-in-Black** [comment]
> if about #4470, then yes, this is what I would like to see

sorry you're right, was in the wrong issue.
