### ISSUE TITLE
Make it visible if the page was set as template

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4473]
### Describe the feature you'd like

It would be helpful if you could see directly when navigating whether a page was marked as a template, for example italicized or prefixed with a tag, somehow in the form.
Or maybe hide the templates in an collapsible section at the end of a book or chapter.

### Describe the benefits this would bring to existing BookStack users

Faster detection of whether a page has been marked as a template.

### Can the goal of this request already be achieved via other means?

Can't find anything like that.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by Man-in-Black** [comment]
I just found a way how I can achieve this with the visual theme system.
I made the following changes to the pages > parts > list-item.blade.php:
~~~
@component('entities.list-item-basic', ['entity' => $page])
    <div class="entity-item-snippet">
        <p class="text-muted break-text">
            <!-- added for template marking -->
            @if($page->template)
                @icon('template')
            @endif
            <!-- end template marking -->
            {{ $page->getExcerpt() }}</p>
    </div>
@endcomponent
~~~
not the neatest way, but I think this fixes my issue. But maybe there is a better way as mine.

@ssddanbrown if you don't have another solution for this and you think that this is enough then feel free to close this feature request. Maybe you can add this snippet into the core since it is not that much of a change in my oppinion.

**Comment by ssddanbrown** [comment]
@Man-in-Black Good to see you found a solution via the visual theme system.
I will therefore close this off, since I'm hesitant to bring metadata up to listing views without significant justification of general desire/requirement.
