### ISSUE TITLE
How to block public from accessing `/api/docs` route

### ISSUE THREAD

**Issue by shirogutama** [BookStackApp/BookStack#4475]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Currently, the API docs can be accessed by public users. And I want this only accessible to a specific role(s). How to do this?

### Exact BookStack Version

BookStack v23.06-dev

### PHP Version

8.2

### Hosting Environment

Ubuntu Local machine

**Comment by ssddanbrown** [comment]
Hi @shirogutama,
There is no built-in permission control available when it comes to viewing the API docs.

I see you're using a dev version of Bookstack, are you hacking on your own instance and desire advise on how to change the code to add such a permission check? (Would not be official, or update compatible).

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll close this off.
