### ISSUE TITLE
the ability to set separate permissions for the author

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#4477]
### Describe the feature you'd like

the ability to set separate permissions for the author

### Describe the benefits this would bring to existing BookStack users

the ability to prohibit editing of all pages except those who created themselves

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by Shun-Ibiki** [comment]
Isn't this feature already available under the settings-> roles->(your role)-> asset permissions? Then give user(s) this role.

**Comment by jefry7** [comment]
As far as I have figured out, you can specify the author (but it is not entirely clear what this applies to). You can specify the rights for the role. But I did not find how to give rights to an individual or an author.

**Comment by ssddanbrown** [comment]
@jefry7 To give user-specific permissions you'd need to create a user-specific role.

For user-specific permission assignment, I'd consider that already covered by #1747 so I'll therefore close this off as a duplicate since that generically covers the requested use-case.
