### ISSUE TITLE
Content Notifications are send in the wrong language

### ISSUE THREAD

**Issue by JK1198** [BookStackApp/BookStack#4480]
### Describe the Bug

I just tested the new notification system. For some testing before I have two accounts that are using different languages.
User A is set on English and User B is set on German (informal).
Now, if User A edits a page from User B, User B recieves the mail notification in English. It also works vice versa. Also if I switch the language from User A to e.g. Swedish, User B will recieve the mail partly in Swedish.

### Steps to Reproduce

1. User A sets preffered language to English
2. User B sets preffered language to any other language e.g. German and enables the notifications
3. User B creates a page
4. User A edits the page
5. User B receives the mail in English

### Expected Behaviour

It should use the preffered language of the account which receives the notification.

### Browser Details

Checked the MS Edge and Firefox

### Exact BookStack Version

v23.08

### PHP Version

PHP 8.1

### Hosting Environment

Debian 11, apache2 as webserver

**Comment by ssddanbrown** [comment]
Thanks for raising @JK1198, I have addressed this in #4497 and this has been merged to be part of the next patch release.
