### ISSUE TITLE
App only works if index.php is present in url

### ISSUE THREAD

**Issue by Macxion** [BookStackApp/BookStack#4482]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I just installed BookStack, followed [these](https://www.bookstackapp.com/docs/admin/subdirectory-setup/#apache-setup) instructions to configure apache, but using "/docs" alias. App is openning in browser but always redirects to "/docs/login" having the message "Page not found". Apache mod rewrite is enabled and the 000-default-conf in apache has exactly configuration in the link provided. When I put "index.php" right after /docs, ie: docs/index.php/login, the app works, but the problem is that app links don't use index.php, wich configuration do I have to make for this work correctly? All environment parameter are correct, the problems is just this index.php.

- My .env APP_URL is http://xxx.xxx./docs
- Followed configuration link to edit 000-default.conf
- a2enmod rewrite command says that module is already in use

### Exact BookStack Version

I don't know, could not login

### Log Content

No errors

### PHP Version

8.1

### Hosting Environment

Debian 11

**Comment by ssddanbrown** [comment]
Hi @Macxion,

- Are you restarting apache after configuration changes?
- Are there other apache config files (Likely in `/etc/apache2/sites-enabled` that are interfering and actually being used instead of the config being edited?)
- Does an apache config test pass? (`sudo apachectl -t`).
- Can you share as much of your actual config as possible.

**Comment by Macxion** [comment]
Hi @ssddanbrown, thank you for quicky response!

- Yes, apache restarted
- No, there is no other site-enabled, only 000-defaulf.conf
- Apache config test gives de message "Syntax OK"
- Of course, here it goes:

This is app_url in my .env
```
APP_URL=http://xxx.xxx.xxx.xxx/docs
```

This is my 000-default.conf
```
<VirtualHost *:80>
	
	ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

	ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html	

	[Some Env variables for PHP systems...]

	Alias "/docs" "/var/www/html/bookstack/public"

        <Directory "/var/www/html/bookstack/public">
                Options FollowSymlinks
                AllowOverride None
                Require all granted

                RewriteEngine On
                # Redirect Trailing Slashes If Not A Folder...
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule ^(.*)/$ /$1 [L,R=301]

                # Handle Front Controller...
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^ index.php [L]

        </Directory>


        <Directory "/var/www/html/bookstack">
                AllowOverride None
                Require all denied
        </Directory>

</VirtualHost>
``` 

Result for a2enmod rewrite command is "Module rewrite already enabled"

I have no other configuration, the inital instalation has run ok, when I access browser, always receive this "Page not found" message
![image](https://github.com/BookStackApp/BookStack/assets/63028407/4f3a9f2b-066a-4c16-ab6a-4d4c0ddbe511)

**Comment by ssddanbrown** [comment]
Thanks for the extra info @Macxion.
I see you have your BookStack install in `/var/www/html/bookstack`, which looks to be likely within another existing site/document root. This is not something I'd advise, and something I remember potentially being a problem in the past. It's also the main thing different to our guidance.

Could you try instead moving your BookStack install outside of this web root path? To somewhere like `/var/www/bookstack` then update your config to suit, then restart apache.
