### ISSUE TITLE
/Login Page Not Found

### ISSUE THREAD

**Issue by aszabonorbert** [BookStackApp/BookStack#4483]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When I make a request with https://my.domain.com/kb url, it redirects the browser to the https://my.domain.com/kb/login page with designed "Page Not Found" message, it's obvious that is from BookStack, so index.php gets the request.
I tried the v23.06.2 and the v23.08 with no success.
My url /kb is alias to the docroot, that is /var/www/my.domain.com/BookStack/public.

![Screenshot BookStack](https://github.com/BookStackApp/BookStack/assets/3910290/e9e4fa77-1322-4767-a1cc-488ddf6760a5)

### Exact BookStack Version

v23.08

### Log Content

- -  30/Aug/2023:19:49:10 +0000 "GET /kb/index.php" 302
- -  30/Aug/2023:19:49:10 +0000 "GET /BookStack/public/index.php" 404

### PHP Version

8.1

### Hosting Environment

Debian 11 with dockerized php-fpm

My apache config:
```
Alias /kb /var/www/my.domain.com/BookStack/public
<Directory /var/www/my.domain.com/BookStack/public>
    <FilesMatch "\.php$">
        SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"

        Options FollowSymlinks
        AllowOverride None
        Require all granted

        RewriteEngine On

        # Handle Authorization Header
        RewriteCond %{HTTP:Authorization} .
        RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_URI} (.+)/$
        RewriteRule ^ %1 [L,R=301]

        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]
    </FilesMatch>
</Directory>
```
My APP_URL=https://my.domain.com/kb
I set APP_DEBUG=true, but nothing is happening. The laravel log has only information about running artisan. There is no error in the apache log either.

**Comment by ssddanbrown** [comment]
Hi @aszabonorbert,
From a look at your config, my suspicion is that this is maybe due to nesting the existing config within the `<FilesMatch "\.php$">` block.

This isn't something I've tested, but maybe try moving that content out, to something like:

```apache
<Directory /var/www/my.domain.com/BookStack/public>
    <FilesMatch "\.php$">
        SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
    </FilesMatch>

    Options FollowSymlinks
    AllowOverride None
    Require all granted

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</Directory>
```

**Comment by aszabonorbert** [comment]
Hi @ssddanbrown,
Thanks your answer. Unfortunetaly it didn't help. Nothing has changed, same error.

**Comment by ssddanbrown** [comment]
Is `/var/www/my.domain.com` an existing site?
If so, I seem to remember the alias setup does not work well when pointing to an existing hosted directory.
You could try moving the BookStack install to a completely different location (like `/var/www/bookstack`) that's not in an existing site, then update the paths in the apache config, then restart apache.

**Comment by ssddanbrown** [comment]
Since there's been no further response I'll go ahead and close this off.
