### ISSUE TITLE
Update from 23.06.2 to 23.08 brings errors

### ISSUE THREAD

**Issue by TineUser** [BookStackApp/BookStack#4485]
### Describe the Bug

Updating BookStack from 23.06.2 to 23.08 brings the following errors:

```
Package socialiteproviders/slack is abandoned, you should avoid using it. Use laravel/socialite instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 891:

  Target class [BookStack\Actions\Activity] does not exist.


In Container.php line 889:

  Class "BookStack\Actions\Activity" does not exist


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

C:\xampp-dev\htdocs\bookstack>php artisan migrate

In Container.php line 891:

  Target class [BookStack\Actions\Activity] does not exist.


In Container.php line 889:

  Class "BookStack\Actions\Activity" does not exist
```
How can I fix this?

Kind Regards.

### Steps to Reproduce

composer install --no-dev

### Expected Behaviour

No errors

### Exact BookStack Version

23.08

### PHP Version

8.0.19

### Hosting Environment

Windows 10 22H2, Build 19045.3324

**Comment by TineUser** [comment]
Doing a clean installation and migrating the .env file, php artisan migrate helps to solve the issue.

**Comment by ssddanbrown** [comment]
Glad to hear you found a solution, I'll therefore close this off.
This was likely an instance-specific thing, maybe something stuck cached or not upgraded from a prior version since some of those reported paths would have only been relevant to pre-v23.06 versions of BookStack.
