### ISSUE TITLE
OIDC - Users table - Name contains the External_auth_id

### ISSUE THREAD

**Issue by BartNSTCL** [BookStackApp/BookStack#4486]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After setting up in the cloud with ODIC and fixing the existing users' external_auth_id, we started allowing new users to login. I noticed the name in the users table contained the value of the external_auth_id. Checking the .env, I didn't see an ODIC variable to set that field. When OIDC_DUMP_USER_DETAILS was set to Debug, the User's data is attached. I poked around in OidcService.php but I didn't see anything that stuck out. I probably have something set wrong or missing.

### Exact BookStack Version

v23.08

### PHP Version

8.1.2

### Hosting Environment

Ubuntu 22.04.3 LTS

**Comment by ssddanbrown** [comment]
Hi @BartNSTCL,
The `OIDC_DISPLAY_NAME_CLAIMS` env option controls what is used for the BookStack user display name.
By default just the `name` claim is used.
More details in the docs for the option here:
https://www.bookstackapp.com/docs/admin/oidc-auth/#bookstack-configuration

**Comment by BartNSTCL** [comment]
Sorry, I wasn't clear. I had a new user log so I could get a screen shot. While the email is correct, the Name is not.
![Screenshot 2023-08-31 073528](https://github.com/BookStackApp/BookStack/assets/142409660/4966fdaf-82c1-4978-a736-bbd1fdce17a9)

**Comment by BartNSTCL** [comment]
Sorry, I have  OIDC_DISPLAY_NAME_CLAIMS=given_name|family_name and maybe those variables are not present and I have to use name?

**Comment by ssddanbrown** [comment]
@BartNSTCL That could be the case, BookStack will fall back to the ID where the name details do not exist (or are empty).
You could use the `OIDC_DUMP_USER_DETAILS` option to test and be sure of exactly what claims are provided by the OIDC system.

**Comment by BartNSTCL** [comment]
Looks like "name", which for me is "Lynn, Bart (NSTCL)" is the only option, other than an email. Anyway or plans to all using Regular expressions again OIDC_DISPLAY_NAME_CLAIMS to be able to manipulate it? I was just looking for alternatives to editing the Name each time a new user logs in. I guess that would probably have to be a mysql job that runs and checks the name then updates it according to some criteria.

**Comment by ssddanbrown** [comment]
It's odd for the OIDC system to not provide more details.

No plans to do any regex stuff built-in.

If happy to get a little hacky in PHP, there is a built-in [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) event (`OIDC_ID_TOKEN_PRE_VALIDATE`) which allows you to hook in and customize the OIDC data after recieved by BookStack, but before BookStack validates/processes it.

There's an example on my blogpost here (OIDC ID Token Logical Theme Event section):
https://www.bookstackapp.com/blog/bookstack-release-v23-05/#oidc-id-token-logical-theme-event
I'm even doing some name manipulation stuff in that example.

**Comment by ssddanbrown** [comment]
Since the original support issue was solved, and there's been no further discussion, I'll go ahead and close this off.
Feel free to comment though if you need additional guidance.

**Comment by BartNSTCL** [comment]
I created a functions.php in/var/www/bookstack/themes/custom and added APP_THEME=custom to .env.
When I was updating the software, I found Bookstack gave me the forge@localhost error. After some research, I found once I did the php artisan config:clear , I needed to run php artisan config:cache. I read I needed to run that anytime .env was changed. Been 30 years since I used Linux but I wasn't sure. In any case, I think I got the custom theme to work as:
<?php
use BookStack\Facades\Theme;
use BookStack\Theming\ThemeEvents;

Theme::listen(ThemeEvents::OIDC_ID_TOKEN_PRE_VALIDATE, function (array $idTokenData, array $accessTokenData) {
    $currentName = $idTokenData['name'];
    if (str_ends_with($currentName, ' (NSTCL)')) {
		$nameStrArray=explode(',',str_replace(" (NSTCL)","",$currentName));
        return array_merge($idTokenData, [
           'name' => trim($nameStrArray[1]) ." " . trim($nameStrArray[0]),
        ]);
    }
});

**Comment by ssddanbrown** [comment]
>  I found once I did the php artisan config:clear , I needed to run php artisan config:cache. I read I needed to run that anytime .env was changed.

You only need to run `config:cache` or `config:clear` if you've attempting caching/optimization commands in the past. 
I don't advertise those commands in our guidance/documentation at all since they cause more problems then they solve for most of our users. If you only run `config:clear` then changes to the `.env` file would usually take place right away unless you run `config:cache` or `optimize` again.
