### ISSUE TITLE
Implement '@ Mention' Feature with User Dropdown and Notifications for Both Pages and Comments

### ISSUE THREAD

**Issue by davbauer** [BookStackApp/BookStack#4490]
### Describe the feature you'd like

I propose the addition of an '@ mention' feature in BookStack that functions in both page content and comments. The feature should operate as follows:

- Upon typing the '@' symbol in the text editor or comment box, a dropdown list featuring up to 5 users should appear.
- As the user starts typing a name or email, the list should dynamically filter to display matching users.
- The user should be able to navigate this dropdown using arrow keys.
- Pressing 'Enter' should insert the mention into the text.

For comments:
- The mentioned user should receive a notification as soon as the comment is posted.

For pages:
- The mentioned user should receive a notification only when they are mentioned in a new update, not with every page update.

### Describe the benefits this would bring to existing BookStack users

This feature would augment collaboration and user engagement by:
  
- Facilitating focused conversations by drawing the attention of specific users.
- Encouraging quicker response times due to notifications.
- Enriching user experience through easy-to-use, interactive elements.

### Can the goal of this request already be achieved via other means?

No. While notifications have recently been implemented, there is no '@ mention' feature to notify specific users.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

### Additional context

The '@ mention' feature is widely considered a standard in collaborative platforms, making its inclusion in BookStack a beneficial enhancement.

**Comment by ssddanbrown** [comment]
Thanks for the request @davbauer, But I'd consider this to already be covered by #560 so I'm going to therefore close this off as a duplicate.
