### ISSUE TITLE
Thumbnail src is error

### ISSUE THREAD

**Issue by youuncler** [BookStackApp/BookStack#4491]
### Describe the Bug

div class="featured-image-container" style="background-image: url(' http://192.168.2.246:6875/ http://192.168.2.246:6875/uploads/images/cover_bookshelf/2023-09/thumbs-440-250/snipaste-2023-09-01-09-41-44.jpg')">

img refs="image-picker@image" src=" http://192.168.10.68:6875/ http://192.168.10.68:6875/uploads/images/cover_bookshelf/2023-08/thumbs-440-250/snipaste-2023-08-28-19-04-24.jpg" class="cover " alt="图片预览"

has two values

### Steps to Reproduce

css backgroud-image
img src

### Expected Behaviour

thumbnail doesn't show

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 20.04

**Comment by ssddanbrown** [comment]
Hi @youuncler,
What is the exact value of the `APP_URL` option within your `.env` file?

**Comment by youuncler** [comment]
It is normal for me to use solidnerd/docker bookstack. The linuxserver/docker bookstack is incorrect.
