### ISSUE TITLE
Text editor menu broken & mis-sized edit space

### ISSUE THREAD

**Issue by Niceygy** [BookStackApp/BookStack#4495]
### Describe the Bug

(As above) edit box is very small when using markdown editor, default editor does not have an edit box
This is a brand new docker install (using LinuxServer.io Docker-Compose)

### Steps to Reproduce

1. Create a new install of bookstack
2. Create a new book, chapter and page
3. edit the page
4. Click on menu buttons. They dont work (nothing happens). Edit box is very small

### Expected Behaviour

A full size edit box, and working menus.

### Screenshots or Additional Context
(MarkDown below)
![image](https://github.com/BookStackApp/BookStack/assets/80964340/8c7a30a2-b7e7-4ac3-aa73-42542186c0bc)
(Default below)
![image](https://github.com/BookStackApp/BookStack/assets/80964340/a70c0096-7b43-42d8-8fa4-4b28d16290f1)

### Browser Details

MS Edge: 116.0.1938.62 (Official build) (64-bit). Windows 11 22H2 
Adblock Disabled

### Exact BookStack Version

V 23.08

### Hosting Environment

Ubuntu Host running Docker (LinuxServer.io Docker-compose used)

**Comment by ssddanbrown** [comment]
Hi @NiceygyLive,
Would you be able to open the browser development tools (Right click on webpage > Inspect), then go to the "Console" tab, then reload the page when in the BookStack editor. Then share messages you see in the log.

**Comment by Niceygy** [comment]
![image](https://github.com/BookStackApp/BookStack/assets/80964340/ed4c055e-2b0f-4c35-bc14-8f6ff9fd2941)


edit:1  Refused to load the script 'https://docs.niceygylive.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src http: https: 'nonce-AwiHnxjdtxVXyWwE68yeGmhn' 'strict-dynamic' 'nonce-347c7762-897f-488c-80d4-b200582f99ae'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:1  Error executing script: (function(w,d){w.zarazData.executed.push("Pageview");})(window,document)
 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src http: https: 'nonce-AwiHnxjdtxVXyWwE68yeGmhn' 'strict-dynamic' 'nonce-347c7762-897f-488c-80d4-b200582f99ae'".

    at new Function (<anonymous>)
    at s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:1:964
    at Array.forEach (<anonymous>)
    at s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:1:946
    at new Promise (<anonymous>)
    at window.zaraz._p (s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:1:910)
    at s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:5:2877
    at s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:5:2967
(anonymous) @ s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:1
(anonymous) @ s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:1
window.zaraz._p @ s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:1
(anonymous) @ s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:5
(anonymous) @ s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyRWRpdGluZyUyMFBhZ2UlMjBXZWJtaW4uc2VydmljZSUyMCU3QyUyMEJvb2tTdGFjayUyMiUyQyUyMnglMjIlM0EwLjAzNzU2NzQ0Njg5NDEzNjkzNSUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTYxJTJDJTIyZSUyMiUzQTEzMTAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkb2NzLm5pY2V5Z3lsaXZlLnh5eiUyRmJvb2tzJTJGdnBzLW9uZSUyRnBhZ2UlMkZ3ZWJtaW5zZXJ2aWNlJTJGZWRpdCUyMiUyQyUyMnIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmRvY3MubmljZXlneWxpdmUueHl6JTJGYm9va3MlMkZ2cHMtb25lJTJGcGFnZSUyRndlYm1pbnNlcnZpY2UlMjIlMkMlMjJrJTIyJTNBMjQlMkMlMjJuJTIyJTNBJTIyVVRGLTglMjIlMkMlMjJvJTIyJTNBLTYwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA==:5
DevTools failed to load source map: Could not load content for https://docs.niceygylive.xyz/dist/print-styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://docs.niceygylive.xyz/dist/styles.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Niceygy** [comment]
(Thanks for the prompt response!)

**Comment by ssddanbrown** [comment]
Thanks for the info @NiceygyLive,
Please can you go into Cloudflare and disable [rocket loader](https://developers.cloudflare.com/speed/optimization/content/rocket-loader/enable/) for your BookStack site?

Things should work after that.

**Comment by Niceygy** [comment]
That's done it! Thanks

**Comment by ssddanbrown** [comment]
Happy I could help, will therefore close this off.
