### ISSUE TITLE
Deleted books/chapters/pages can cause failure of notification preferences view

### ISSUE THREAD

**Issue by byPavel** [BookStackApp/BookStack#4499]
### Describe the Bug

Created a book of articles enabled subscription to notifications. Deleted the book.

### Steps to Reproduce

1.Created a book 
2.Create a page 
3. Enabled subscription to notifications. 
4. 4 Deleted the book 
6. I go to the settings and get an error

### Expected Behaviour

When deleting a book, automatic deletion of notifications

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/69891182/baca2958-89c6-4bcd-afcf-b4b2144e5aa4)

### Exact BookStack Version

BookStack v23.08

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Thanks for reporting this @byPavel! I have just pushed 817581aa0c8f7575f06d033fe7ec5e19744bee3c to cover this, which will be part of the next BookStack patch version, to be released soon.
