### ISSUE TITLE
Notification Preferences "MANAGE" button text wraps at page width > 1400px 

### ISSUE THREAD

**Issue by SirTwinkleberry** [BookStackApp/BookStack#4502]
### Describe the Bug

The "MANAGE" text of the middle button located at the _Preferences_ page in _BookStack 23.08_  wraps around when page_width > 1400px.

(starts at 1401px but I wasn't able to get the screenshot just right)

### Steps to Reproduce

1. Go to bookstackinstance.tld/preferences

### Expected Behaviour

"MANAGE" text stays on a single line just like the above and below buttons

### Screenshots or Additional Context

![screen](https://github.com/BookStackApp/BookStack/assets/30357667/201eba30-201d-4a06-9022-515b1379ab2c)
![screen2](https://github.com/BookStackApp/BookStack/assets/30357667/2c6ca6c4-54fd-4eae-8261-e4ea7266432f)

### Browser Details

Chrome 116.0.5845.110

### Exact BookStack Version

23.8

### PHP Version

8.0

### Hosting Environment

Linux Kernel: 4.18.0-425.13.1.lve.el8.x86_64
Freshly installed using latest git release
With and without custom HTML header

**Comment by ssddanbrown** [comment]
Thanks for raising @Timothy-Anders0n.
I've addressed this via e31b50dabdc4475ad0d45da1eefd2c3dedce7d8f, which will be part of the next patch release.
