### ISSUE TITLE
Messy interface when opening pages on mobile when the default language is set to RTL (e.g Hebrew)

### ISSUE THREAD

**Issue by topazb** [BookStackApp/BookStack#4505]
### Describe the Bug

On mobile phones, when we open pages in bookstack, the interface is not properly rendered for the mobile screen and is unusually small, and an unrelated error pops up as well. (screenshots included)

This is reproducible also in: https://demo.bookstackapp.com

Related issue:
https://github.com/BookStackApp/BookStack/issues/4387

### Steps to Reproduce

1. On your mobile phone, go to bookstack.
2. Set the default language to Hebrew.
3. Open a page.
4. The interface is messed up.

### Expected Behaviour

I expect the interface to be rendered properly and to fit the screen; and I also don't want to see any unrelated errors.

### Screenshots or Additional Context

![Screenshot_20230903_191943_Chrome](https://github.com/BookStackApp/BookStack/assets/25467194/1f44521e-5741-41da-af8a-079dee35f02e)

### Browser Details

Chrome on Android

### Exact BookStack Version

BookStack v23.06.1

### Hosting Environment

https://demo.bookstackapp.com

**Comment by ssddanbrown** [comment]
As per #4429, this was addressed in v23.08. I haven't yet updated the demo instance to the latest version.
I'll therefore close this off but if you can replicate this on v23.08 or higher, feel free to comment and I can re-open this.
