### ISSUE TITLE
Watched and deleted book gives an error in notification preferences

### ISSUE THREAD

**Issue by helmut72** [BookStackApp/BookStack#4507]
### Describe the Bug

Watched and deleted book gives an error in notification preferences:

> An Error Occurred
> An unknown error occurred

### Steps to Reproduce

1. create a book
2. set "watch"
3. delete this book
4. go to: preferences -> notifications -> manage

### Expected Behaviour

Notificaton settings continue to work

### Exact BookStack Version

23.08

### PHP Version

PHP 8.1

### Hosting Environment

Selfhosted with selfmade Docker images

**Comment by ssddanbrown** [comment]
Thanks for raising @helmut72, but this was something raised in #4499 and specifically addressed in v23.08.1. Therefore I'll close this off as a duplicate but if you have issues beyond v23.08.1 please comment and I'll re-open this.
