### ISSUE TITLE
drawio doesn't exit when clicking on save

### ISSUE THREAD

**Issue by oxismailxo** [BookStackApp/BookStack#4509]
### Describe the Bug

when i click save on drawio page, the app doesn't return to the page and gets stuck in drawio.

### Steps to Reproduce

1. Go to page
2. edit
3. insert/edit drawing
4. draw something & click on save

### Expected Behaviour

when clicking on save, the app should exit Drawio & back to the edit page.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/68305651/ac50d5f1-b85c-4155-ba5e-17d74c5ad5e6)

### Browser Details

chrome

### Exact BookStack Version

v23.08.1

### PHP Version

PHP 8.2.9

### Hosting Environment

Docker environment:
Image version: lscr.io/linuxserver/bookstack:23.08.1

**Comment by hieste** [comment]
Have same issue after update from 23.06.1 to 23.08. I also can not edit old drawio drawings. If i click on one in bookstack, nothing occurs... Also have the problem if on a page is an drawio drawing, cannot edit page content.

Error: 
app.js?version=v23.08.1:26 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at app.js?version=v23.08.1:26:124
    at tinymce.min.js?version=v23.08.1:4:151017
    at q (tinymce.min.js?version=v23.08.1:4:3324)
    at tinymce.min.js?version=v23.08.1:4:150848
    at ge (tinymce.min.js?version=v23.08.1:4:4719)
    at n (tinymce.min.js?version=v23.08.1:4:150818)
    at Yh (tinymce.min.js?version=v23.08.1:4:151045)
    at Object.parse (tinymce.min.js?version=v23.08.1:4:213073)
    at tinymce.min.js?version=v23.08.1:4:223347
    at tinymce.min.js?version=v23.08.1:4:223469
    at I.map (tinymce.min.js?version=v23.08.1:4:2258)
    at tinymce.min.js?version=v23.08.1:4:222703
    at Object.setContent (tinymce.min.js?version=v23.08.1:4:223532)
    at tinymce.min.js?version=v23.08.1:4:236914
    at tinymce.min.js?version=v23.08.1:4:236930
    at Object.map (tinymce.min.js?version=v23.08.1:4:79331)

<img width="363" alt="image" src="https://github.com/BookStackApp/BookStack/assets/30119314/bdffa221-b199-4731-b56c-99fe6a9f4869">

**Comment by ssddanbrown** [comment]
Thanks @oxismailxo for reporting, and thanks @hieste for the extra detail.
Has been patched in 2c20abc87245160229a48a8813df1c0c077a369e, and v23.08.2 is just being deployed to cover this.
