### ISSUE TITLE
Unable to edit pages after upgrade to 23.08.1

### ISSUE THREAD

**Issue by topazb** [BookStackApp/BookStack#4510]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After upgrading to v23.08.1
I'm unable to edit already existing pages
The edit page appears blank

<img width="1789" alt="Screenshot 2023-09-04 at 11 45 05" src="https://github.com/BookStackApp/BookStack/assets/25467194/a74cb4a9-ae34-44a9-893e-d52b9759608d">

### Exact BookStack Version

23.08.1

### Hosting Environment

upgraded using the official script

**Comment by daviserez** [comment]
I'v got a similar issue, but only on some pages and I can't figure out why some pages work and others don't.

Cleared browser cache and app caches.

![CleanShot 2023-09-04 at 11 23 47@2x](https://github.com/BookStackApp/BookStack/assets/832658/7acda36e-77ca-42e3-b581-255015404004)

**Comment by cdrfun** [comment]
I can +1 to @daviserez issue. Tested it on different machines with up-to-date Firefox, Edge and Chrome. If a page is broken, it is broken on all browser/machines.

**Comment by rockenren** [comment]
Not all pages are affected, but https://github.com/BookStackApp/BookStack/commit/2c20abc87245160229a48a8813df1c0c077a369e alone doesn't resolve the issue.

**Comment by ssddanbrown** [comment]
> but https://github.com/BookStackApp/BookStack/commit/2c20abc87245160229a48a8813df1c0c077a369e alone doesn't resolve the issue.

@rockenren Can you confirm how you tested that? Was just about to push it into release but will hold off if it doesn't address the issue.

**Comment by rockenren** [comment]
> > but [2c20abc](https://github.com/BookStackApp/BookStack/commit/2c20abc87245160229a48a8813df1c0c077a369e) alone doesn't resolve the issue.
> 
> @rockenren Can you confirm how you tested that? Was just about to push it into release but will hold off if it doesn't address the issue.

since this is a small fix: just copied raw from newer revision to current one.
Cleared bookstack caches and restarted web server/php, CTRL+F5 in browser.

Then tried editing broken page again, still showing no content and have same js exception in dev console.

Maybe I did something wrong? Should I pull from development branch via git for this single commit?

**Comment by ssddanbrown** [comment]
@rockenren JavaScript (and CSS) has to be built/bundled into the expected output file(s). I'm assuming this was not done based upon your response so I went ahead and pushed the release.

Thanks @topazb and everyone else for reporting/confirming the issue.
Should now be addressed in v23.08.2, but please let me know if you continue to have issues and I'll re-open.

**Comment by rockenren** [comment]
> @rockenren JavaScript (and CSS) has to be built/bundled into the expected output file(s). I'm assuming this was not done based upon your response so I went ahead and pushed the release.
> 
> Thanks @topazb and everyone else for reporting/confirming the issue. Should now be addressed in v23.08.2, but please let me know if you continue to have issues and I'll re-open.

yes, i've suspected this, my bad.
