### ISSUE TITLE
Wrong french translation in notification preferences

### ISSUE THREAD

**Issue by gblondet117** [BookStackApp/BookStack#4511]
### Describe the Bug

With french language, the "notification preferences" shows 2 identical options (the two first lines).

### Steps to Reproduce

1. Set the language to French
2. Go to Profil/preferences

You will see two checkbox lines, identically defined as "Notifier lors des modifications des pages que je possède".

### Expected Behaviour

The first option, I suppose, should have the same meaning as the english version. It should concern "Changes". It has to be checked, but I think it is ok.

The second should concern comments. It should be written : "Notifier lorsque les pages que je possède sont commentées."

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/123749840/d529e8c4-8dc6-4aed-ab94-bd90ee09139b)

### Exact BookStack Version

v23.08.02

### Hosting Environment

Debian 12

**Comment by ssddanbrown** [comment]
Thanks for raising @gblondet117,
I've addressed via [our translation system](https://crowdin.com/project/bookstack) with your advised translation.
It should therefore use the correct text in a future version, once the translation changes get merged in.

If needed, you can sign up to our translation system, at which point you'll get the ability to update/fix/add translations yourself.
