### ISSUE TITLE
Allow changing password for default admin@admin.com user before first start

### ISSUE THREAD

**Issue by e-g1gor** [BookStackApp/BookStack#4513]
### Describe the feature you'd like

Initial password for default admin should be configurable somehow, maybe via .env file, like

`DEFAULT_ADMIN_PASSWORD=xxx`

### Describe the benefits this would bring to existing BookStack users

There is default migration, that creates admin user with easily brutable credentials.
It allows to easily bruteforce admin access to newly deployed services - for as long as someone do not change password manually.

If this service is being deployed to domain that attracted attention of hackers - they may perform atack immediately, before default password will be changed.

### Can the goal of this request already be achieved via other means?

By tweaking original migration - https://github.com/BookStackApp/BookStack/blob/ad60517536918a81c14e001967f005e761a31e6b/database/migrations/2014_10_12_000000_create_users_table.php#L28

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request @e-g1gor.

Somewhat related to #3946 and #3947.
As per my comment in #3947, I'd ideally like to change how the initial account is created, but I just need to ensure it works for all existing use-cases & installation options without too much pain, and requires some coordination across hosting options and documentation.

I may start to think about intended route on for the current maintenance release cycle.

From my view I'm not too worried about the "bruteforce" scenario here (although no need to bruteforce where it's using a single default option), I think that's rare and can be mitigated via following our guidance, networking and other controls if that really is a concern, my main concern is just with folks not changing the default credentials.

**Comment by ssddanbrown** [comment]
I've now opened #4575 to put forward a multi-stage plan in changing the default admin account handling, with an aim to provide a smooth transition and work with downstream setup/install/guide providers.
I'll therefore close this in favour of centralising things to that issue.

Thanks again @e-g1gor.
