### ISSUE TITLE
Auto create a page if a public user is editing a page

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4515]
### Describe the feature you'd like

I'll try to formulate my idea:
Is it possible to build a function for a specific role (e.g. "Public") that automatically saves a template page as a new page when it is edited?
So that a template does not have to be selected first, but the user or guest simply edits the page and a new page is then automatically generated from it.

### Describe the benefits this would bring to existing BookStack users

Guests would not have to be instructed in the procedure for using the templates.

### Can the goal of this request already be achieved via other means?

I didn't find anything similar to this.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @Man-in-Black,
This sounds like it's closely aligned to the fundamental request in #3794.
I wouldn't really want to get this involved with role/user specific functionality, as this is likely use-case specific, but a generic solution, like the link-based option as requested in #3794 would be more practical for implementation, and abstract to use-case. Would mean you'd have to get those users to follow the right links.

**Comment by Man-in-Black** [comment]
That sound very similar and maybe it's a better solution than mine.
I will close this off in favour of the other request.
