### ISSUE TITLE
The possibility to create lists like in SharePoint

### ISSUE THREAD

**Issue by mkleger** [BookStackApp/BookStack#4516]
### Describe the feature you'd like

We document our entire IT landscape with BookStack and it happens again and again that we have lists / tables that we fill in, such as a simple ChangeLog or a bug list.

We would be happy if you could create a list instead of a normal page and define the columns yourself (similar to SharePoint) and then fill the lists predefined. Furthermore it would be great if you could filter the list.

### Describe the benefits this would bring to existing BookStack users

This makes it possible to prepare the data even better and make it available to the users.

### Can the goal of this request already be achieved via other means?

Of course you could do this with a simple table, but then you lack the filters and the "standardized" filling via a form. 
- Selectbox
- checkbox
- radio
- etc...

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @mkleger, but I'm not deeply familiar with sharepoint so I don't really understand what you're requesting here. We already support list formats within page content, so not totally sure how things differ in what you're asking.

> This makes it possible to prepare the data even better and make it available to the users.

That doesn't really detail how this feature would benefit BookStack users. "Make it available to users" could be used to justify any addition to the system. I need to know the actual value this adds for users, what does it enable which can't already be done? 

I don't really look to add features based upon them being available elsewhere, and I'm also quite strict in regards to preventing complexity entering the page content formats, hence my questions into the value.

**Comment by mkleger** [comment]
Sorry for my poor description of the request.

I'll try with a few screenshots from a SharePoint page with a list/table:
![image](https://github.com/BookStackApp/BookStack/assets/818390/b6236c2b-639e-4fb4-b1f2-b9268992710d)

![image](https://github.com/BookStackApp/BookStack/assets/818390/7b8e1239-2a5e-444d-98ed-4b44f826846f)

This is not simply a page with text but explicitly a page with a list / table that can only be filled via a form.

**Comment by otherjoel** [comment]
This would appear to be a request to turn Bookstack into a generic database tool. As an IT manager at an MS shop myself, I use Sharepoint lists to manage data, and I use Bookstack to document how those lists should be used. I think this arrangement makes more sense than bolting a Sharepoint-esque set of features onto Bookstack.

**Comment by mkleger** [comment]
Since we are planning to switch away from SharePoint, such a function would be desirable for general documentation and data storage, but then I will probably have to switch to Nextcloud for this.

**Comment by ssddanbrown** [comment]
Yeah, I agree with @otherjoel. While I can see why you may want this @mkleger within BookStack, it's a significant increase in scope for us and not one I'd be willing to take on, as I prefer to keep focused on our existing scope and audience, and there's been little other demand for this kind of thing. 
Therefore I'm going to close this as out of scope.

If you have some development resources available, it could be possible to built a form solution externally, or use existing options, then connect them to BookStack via the REST API, to build and/or display content as desired.
