### ISSUE TITLE
'Watch' action disappears from Actions sidebar once you watch a Book/Chapter/Page

### ISSUE THREAD

**Issue by pat-keeley-aurum** [BookStackApp/BookStack#4517]
### Describe the Bug

Unsure if this is my own permissions at fault, but couldn't see anything that could've caused this on my install. 

The new watch feature is great addition, however when I select 'Watch' on either a Chapter or a Page, it then disappears from the toolbar on the side. The user preferences > notification preferences mentions "To update your preferences for these, view the item then find the watch options in the sidebar." but I cannot see this after the initial 'watch'.

### Steps to Reproduce

1. Select 'Watch' on a chapter/page.
2. 'Watch' immediately disappears and is no longer visible for that chapter/page

### Expected Behaviour

I would expect to see the unwatch action appear. 

### Browser Details

Chrome Version 116.0.5845.141 (Official Build) (64-bit)

### Exact BookStack Version

BookStack v23.08.2

### PHP Version

PHP 8.2.3

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
This is intentional. During testing it didn't feel right having an "Unwatch", since the content still may be watched via a parent or via other preferences, plus it distracts from other watch options available.

When an item is watched (including via a parent) you'll see a watch status in the "Details" above. Click on that to configure the watch level and/or unwatch (Default option).

I know it's not the best UX, but it's the best configuration I found within the existing framework of controls/details for items. I may revise things in the future, or bring something new in for controls like this, but needs some longer term thinking for what's appropriate.

**Comment by pat-keeley-aurum** [comment]
Hi Dan,

Thanks for the response - this makes sense. 

Though I forgot to mention I've actually 'watched' from the Book level. I can see the 'Watching via parent book' if I go down into the Page, but the details on the dropdown are already set to Default. 

![image](https://github.com/BookStackApp/BookStack/assets/94916225/86b13ee0-62bd-4a27-9f51-d7f8dd01beb0)

How would I simply remove the 'Watch' from the book level that I set? 

Many thanks,

**Comment by ssddanbrown** [comment]
@patsyk1 You'd go to the book and change the options there.
The shown options represents the configuration of the page you're viewing.

**Comment by pat-keeley-aurum** [comment]
Thats what I would've assumed, but I don't ever see this on the Book level. Even as an admin. 

![image](https://github.com/BookStackApp/BookStack/assets/94916225/beae57e6-5334-45b7-b37c-84b5b2869998)

**Comment by ssddanbrown** [comment]
@patsyk1 That's strange, you're missing other details also. Do you have any customizations active? Using the theme systems at all of have "custom HTML head content" which could affect this?

**Comment by pat-keeley-aurum** [comment]
Ah, yes. This is the problem - looks like it's coupled with Owner in - 

<style>
[option\:entity-search\:entity-type="chapter"] .entity-meta .entity-meta-item:nth-child(1) {
  display: none;
}
</style>

Thanks Dan!

**Comment by pat-keeley-aurum** [comment]
Edited for accuracy - Fixed by removing my customisation that removed the Owner details pane as it looks like 'Watched' is coupled with this.
