### ISSUE TITLE
Wrong result through API call of updated_at property.

### ISSUE THREAD

**Issue by Phonksy** [BookStackApp/BookStack#4520]
### Describe the Bug

In .env file I have set the timezone to this value: 
APP_TIMEZONE = Europe/Vilnius
Even so, the time of updated_at property is always wrong. Three hours early to be exact, but the same property in MySql database shows the correct time.

### Steps to Reproduce

1. Using any API call containing updated_at property.

### Expected Behaviour

I expect to get the correct time of updated_at property.

### Screenshots or Additional Context

Image1 shows the result in the api call.
Image2 shows MySql data base time of the same property.
![image1](https://github.com/BookStackApp/BookStack/assets/101298331/5998a4be-cf64-4b80-a348-f836b13526d7)
![image2](https://github.com/BookStackApp/BookStack/assets/101298331/42018c32-577a-483a-be58-c89101b97a3f)

### Exact BookStack Version

v23.06.2

### Hosting Environment

I used XAMPP on windows to install bookstack.

**Comment by ssddanbrown** [comment]
Hi @Phonksy,
Assuming you're in Eastern European Summer Time right now, that looks correct to me.
I believe the API sticks to providing UTC (which is shown in your API response), so a 3 hour difference to clock time would be expected.

**Comment by Phonksy** [comment]
Hi,
Thank you for responding. I would like to get the correct time, I dont understand what the issue is. If the API sticks to providing UTC, is it possible to change that?

**Comment by Phonksy** [comment]
Fixed it in code. Found the offset from UTC time and added it to the property value. Thank you anyway.
