### ISSUE TITLE
User Permissions to Move Page/Chapter/Book

### ISSUE THREAD

**Issue by uhattech** [BookStackApp/BookStack#4521]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am finding that no users other than Admins can move pages/chapters/books. In the [documentation](https://www.bookstackapp.com/docs/user/organising-content/#moving-single-pages--chapters) it states, "Note that to move content you will need to have ’edit’ permission for both the content being moved and the parent it’s being moved into." I have tripled check all other user accounts that are needing this move permission and they all have view, create, update permissions on the books, chapters and pages. I've even set some of them to owners of the books themselves, but to no avail, the "move" button in the right sidebar of the chapters or pages shows up for them, only admins.

### Exact BookStack Version

v23.02.1

### PHP Version

8.2.3

### Hosting Environment

Hosted in Digital Ocean on Ubuntu 22.04.2 LTS using bookstacks how to installation guide

**Comment by ssddanbrown** [comment]
Hi @uhattech,
I think delete permissions are also needed for a move operation.
We have #3813 open as an issue to better document this.

**Comment by uhattech** [comment]
Thank you!! This did fix my issue.

**Comment by ssddanbrown** [comment]
Good to hear! I'll therefore close this off.
