### ISSUE TITLE
Saving page containing a list - 500 Internal Server Error

### ISSUE THREAD

**Issue by LoadedLen** [BookStackApp/BookStack#4524]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Pages containing bullet points, numbered lists, or checklists will fail with 500 Internal Server Error when trying to save page. Drafts save fine. 

### Exact BookStack Version

v23.08

### PHP Version

8.0

### Hosting Environment

Dreamhost VPS 20.04.1-Ubuntu (5.15.0-46-generic)

**Comment by ssddanbrown** [comment]
Hi @LoadedLen,
Are you able to see webserver logs for your environment? 
The webserver error log would probably hold the clues to indicating what's happening for that particular error message.

**Comment by LoadedLen** [comment]
Ahhh. My beginner's eyes tell me this is a false positive on a security threat.

ModSecurity: Warning. Pattern match "(?:get|post|head|options|connect|put|delete|trace|track|patch|propfind|propatch|mkcol|copy|move|lock|unlock)\\\\s+(?:\\\\/|\\\\w)[^\\\\s]*(?:\\\\s+http\\\\/\\\\d|[\\\\r\\\\n])" at ARGS:html. [file "/etc/modsecurity/mod_sec3_CRS/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "53"] [id "921110"] [msg "HTTP Request Smuggling Attack"] 

Some of the text on the page matches a pattern that might be consistent with an attack. ?? This is being set up as a private resource for my employees. Tutorials and business-specific information. Nobody here is interested in (or able) to initiate any sort of attack on any resource I put out. Can I override this?

**Comment by LoadedLen** [comment]
I might have to contact Dreamhost support for it. Hopefully, they can whitelist that subdomain with their ModSecurity rules.

**Comment by LoadedLen** [comment]
Solved it! I was able to disable ModSecurity entirely from Dreamhost's panel. Since this is a private subdomain and I control the access (and indexing is disallowed) I'm sure it'll be fine.

**Comment by ssddanbrown** [comment]
Good to hear you've managed to solve the issue. I'll therefore close this off.
