### ISSUE TITLE
bad parsing of shell code (cat EOF)

### ISSUE THREAD

**Issue by RANDOMLY-OBFUSCATED** [BookStackApp/BookStack#4528]
### Describe the Bug

When using shell code block (```sh), the last EOF is not correctly reconized and the rest of the cole take the same color of strings previously used.
The only one way I found to work around is to cut the shell block just after the last `EOF` et reopen a new one at next.
Three instances, same result.

### Steps to Reproduce

1. open a new page
2. open a new shell block, fill it with a `cat EOF` block in the middle of the rest of the code

### Expected Behaviour

Have the correct syntaxic coloration.

### Screenshots or Additional Context

<details><summary>Details</summary>
<p>

![Screenshot_20230910_135110](https://github.com/BookStackApp/BookStack/assets/5000101/fe4cb781-9e8d-4d6a-9abc-39afbbbb8022)
![Screenshot_20230910_135138](https://github.com/BookStackApp/BookStack/assets/5000101/c45e9ace-319a-47be-95d1-3c4b4a788758)
![Screenshot_20230910_135204](https://github.com/BookStackApp/BookStack/assets/5000101/c2a29f08-2650-4525-8349-5de5522c0d46)
![Screenshot_20230910_135230](https://github.com/BookStackApp/BookStack/assets/5000101/22862b14-229d-4ba7-bdad-8c4eb28a83b9)

</p>
</details> 

### Browser Details

FF 117.0 - openSUSE 15.4 up to date with Mozzilla repo

### Exact BookStack Version

v23.06.2

### PHP Version

8.2.8

### Hosting Environment

bare metal with PVE, Bookstack is in an openSUSE CT. It was installed and upgraded with git.

**Comment by ssddanbrown** [comment]
Hi @18info,
Looks like this was [addressed upstream here](https://github.com/codemirror/legacy-modes/pull/14), and from my testing appears to be included and working in BookStack v23.08.2. Can you upgrade your instance and test again?

**Comment by RANDOMLY-OBFUSCATED** [comment]
Hi @ssddanbrown,
It's effectively fixed in 23.08.2. Apologies, I didn't saw the notif from github for this new version. I'm one week late ;).
Thanks you for your fast response and thank you all for this amazing soft :)))
Wish you the best.
