### ISSUE TITLE
Breadcrumb issue after editing page

### ISSUE THREAD

**Issue by david-prv** [BookStackApp/BookStack#4529]
### Describe the Bug

Hi everyone,

usually, the breadcrumb should display:
![image](https://github.com/BookStackApp/BookStack/assets/66866223/a3a7407d-3e9a-4b54-8f47-cd1336beeb20)

but sometimes - after editing a page - it shows only:
![image](https://github.com/BookStackApp/BookStack/assets/66866223/c5e6fd17-7cfa-46dc-8a02-1ade13736c00)

It skips shelves and the current shelve name and starts with books. I've configured the instance to use the shelve view as homepage, so I think this might be a bug? Or what's causing this different breadcrumb location sometimes? It could confuse users of our wiki, e.g. when leaving an edited page and navigating back to home; they might end up in a different view than expected.

Kind regards,
David

### Steps to Reproduce

I don't know yet 100% how to trigger it. It happened after editing a page in this chapter. But only sometimes. It's not happening all of the time, what's also why I think it's not intended and might be a bug.

### Expected Behaviour

See bug description above.

### Screenshots or Additional Context

See bug description above.

### Browser Details

Brave v1.57.62

### Exact BookStack Version

BookStack v23.05.2

### PHP Version

8.1.20

### Hosting Environment

Ubuntu 20.04.6 LTS, Virtual Server

**Comment by ssddanbrown** [comment]
Hi @david-prv,
In BookStack, books (and their content) do not belong to a shelve. A book may be on a shelve but it may be on others, it does not belong to a single shelf. Therefore we won't always show shelves within the breadcrumb hierarchy if we can't track that the user entered via a shelf, so it is contextual based on the user's journey.

When a user navigates around content, we track what they view and remember the shelf if they view one.
That shelf will then be shown in the breadcrumb hierarchy, unless the viewer looks at an item that is not tracked within that  shelf, in which case we'll forget that shelf context and shelves will not be part of the breadcrumbs.

**Comment by david-prv** [comment]
Hi @ssddanbrown ,

thank you so much for your quick response. I understand now how this phenomenon occurs. I still think that this can be a bit confusing, but it's just how BookStack is organized. We use it as an internal wiki-tool, where different guidelines, best-practices, tutorials and so on can be found. Thus, it follows a strict organization: Shelve (= Topic) > Book (= Category) > Chapter (= Sub-Category) > Page (= Post), which is why we enabled the shelves as main page. So I thought the wiki would now also strictly follow this order.

That's where my initial supposition and confusion came from.

Thanks for the clarification.
