### ISSUE TITLE
npm run-script build does not minify common.js

### ISSUE THREAD

**Issue by spaceraccoon** [BookStackApp/BookStack#453]
* BookStack Version: Latest release
* PHP Version: 7.0
* MySQL Version: 5.7

##### Expected Behavior
1. Running npm run-script build should produce a minified common.js in public/js of about 800kb, similar to the one in release/the Github repository

##### Actual Behavior
1. This was on a completely clean AWS Ubuntu 16.04 EC2 instance with the installation script.
2. After installing Bookstacks and Node/npm, I ran `npm run-script build` in the bookstack folder.
3. The new common.js is huge (7.898MB) and causes a long load time. You can check it out at http://13.59.182.101/js/common.js?version=v0.17.3
4. My node version is v8.2.1 and npm is 5.3.0

**Comment by spaceraccoon** [comment]
Tested on Node 6.9 as well with the same results.

**Comment by spaceraccoon** [comment]
Ugh, sorry, should've run run-script production. Please close this. Sorry!

**Comment by ssddanbrown** [comment]
@spaceraccoon Thanks for advising, I've updated the readme to reflect the recent script changes.

I'd generally advise staying away from the master branch unless you're developing though. It often has breaking changes and things that can mess up a production install.
