### ISSUE TITLE
Align IDs on activity lists for easier customization

### ISSUE THREAD

**Issue by J-C-P** [BookStackApp/BookStack#4530]
### Describe the Bug

Hello,

I was trying to hide the recent activity from all pages.
It worked for some of them but not all of them using the CSS customization.

We found that some "recent activity" DIV has an ID and some have not.
changing 
```
@if(count($activity) > 0)
        <div class="mb-xl">
            <h5>{{ trans('entities.recent_activity') }}</h5>
            @include('common.activity-list', ['activity' => $activity])
        </div>
    @endif
```
to
```
@if(count($activity) > 0)
        <div id="recent-activity" class="mb-xl">
            <h5>{{ trans('entities.recent_activity') }}</h5>
            @include('common.activity-list', ['activity' => $activity])
        </div>
    @endif
```
solves the problem.

Of course our work around will work until net version update.

Thanks for your amazing work !!

Regards from Luxembourg :-)

### Steps to Reproduce

 1. Add **<style>#recent-activity { display: none; }</style>** in "Custom HTML Head Content"
 2. See "Recent Activity" disappear from home page.
 3. See it is still present in a shelf or book view.

### Expected Behaviour

Recent Activity should disappear in shelf or book views also.

### Exact BookStack Version

23.05.2

**Comment by ssddanbrown** [comment]
Hi @J-C-P,
The existence of IDs within the HTML mark-up, is not something we assure to support or something I'd deem stable.
I could add them if it helps for this scenario, but it's not something I'd assure to support, and therefore not something I'd consider bug reports for.

**Comment by J-C-P** [comment]
Thanks for the reply.
I get that.
Now that I have the info (and the work around), I will take care of it if it is not changed in the official release.

Anyway, I wanted to point it out as the css trick is mentioned in the "Custom HTML Head Content" section of the settings page.

Have a good day :-)

**Comment by ssddanbrown** [comment]
Okay, I'll recategorise this into a customization enhancement.
I've just applied 18f396c21bd55fcbf70398a626b76875f8e340ec, so these IDs will be set by default from the next feature release. Therefore I'll also close this off.

Take care in reverting changes before updating to that future feature release, if you've patched original code, otherwise you can get into a conflict when pulling down the latest changes.
