### ISSUE TITLE
JS TypeError in Firefox

### ISSUE THREAD

**Issue by aldem** [BookStackApp/BookStack#4531]
### Describe the Bug

When opening the page (any page) Firefox shows an error in console.

![image](https://github.com/BookStackApp/BookStack/assets/754722/4609a9d4-f897-42ce-80fa-2b3a5b577cf8)

### Steps to Reproduce

Visit any page on demo instance, for example: https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site

This happens on every page and of course not only on demo instance.

### Expected Behaviour

While the error seems to be harmless it might be a good idea to find the root cause and fix it.

### Browser Details

Firefox 117.0, Windows 11

### Exact BookStack Version

v23.08.2

**Comment by ssddanbrown** [comment]
Thanks for reporting @aldem.
I've addressed this in 99eb3e5f712a0596217d5e89f2ee0bea973433c1. Will be part of the next release (feature release or a patch release if we need to deploy one beforehand).
