### ISSUE TITLE
Offline update

### ISSUE THREAD

**Issue by wowagsm** [BookStackApp/BookStack#4532]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

How to update offline?

### Exact BookStack Version

v23.06.7

### Hosting Environment

php8.1 on Ubuntu 22.04, installed using official installation script

**Comment by ssddanbrown** [comment]
Hi @wowagsm,
There is no official means to update offline. 

You could essentially run an installation procedure externally, in an online environment, then copy over changes files but it's a little complex in ensuring you make all the additions/removals/changes required  (and again, not something I support so I'd be apprehensive to provide further guidance).

As an alternative, a docker-based installation could maybe better serve offline scenarios. 
That way it'd just be a case of downloading and transferring a new version of the docker image.

**Comment by wowagsm** [comment]
> Hi @wowagsm, There is no official means to update offline.
> 
> You could essentially run an installation procedure externally, in an online environment, then copy over changes files but it's a little complex in ensuring you make all the additions/removals/changes required (and again, not something I support so I'd be apprehensive to provide further guidance).
> 
> As an alternative, a docker-based installation could maybe better serve offline scenarios. That way it'd just be a case of downloading and transferring a new version of the docker image.

Dan, that is, I cannot download the archive (https://github.com/BookStackApp/BookStack/archive/refs/tags/v23.08.2.zip) and replace the files in it, as with recovery?

1. .env 
2. public/uploads
3. storage/uploads
4. themes/
We use a server with strict Internet access restrictions.

**Comment by ssddanbrown** [comment]
@wowagsm You could do something along those lines, at your own risk. You'd need to be sure you're also deleting content that's no longer needed. Also, that ZIP won't include the `vendor/` files which are managed via composer, which will also be required.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion on this support thread I'll go ahead and close this off.
