### ISSUE TITLE
Add not operator to search

### ISSUE THREAD

**Issue by turbo2ltr** [BookStackApp/BookStack#4536]
### Describe the feature you'd like

As far as I can tell, there is no documented way to say "this but not that".  Like say I want to find something with tag1 but not tag2, I can't do the google-esque search term `tag1 -tag2`.  I tried `!` and `not` with no luck.

### Describe the benefits this would bring to existing BookStack users

Being able to find pages easier.

### Can the goal of this request already be achieved via other means?

Not that I'm aware of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request @turbo2ltr.
Via the changes in #5239, negation support has now been added via advanced search syntax for exact terms, filters and tag search terms. This will be part of the next feature release.
