### ISSUE TITLE
Auto size title image of shelves and books

### ISSUE THREAD

**Issue by freddy2312** [BookStackApp/BookStack#4538]
### Describe the feature you'd like

Right now title images of books and shelves have to have a resolution of 440x250px. I´d think that many users would profit if that just would be the minimum resolution and you could just drag & drop any image of any size above 440x250px in there. 
I think that something like imagejs (https://github.com/image-js/image-js) would suit everything most users could need

### Describe the benefits this would bring to existing BookStack users

you won´t have to deal with image editing programs beforehand. That would also help to create a more beautiful bookstack platform for most that use it because lets be honest here, most of the normal persons don´t really know how to resize images or apply basic editing

### Can the goal of this request already be achieved via other means?

Yes but only with external software like Photoshop, Affinity Photo, Photopea, Paint.net and others

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

### Additional context

Keep up the great work! I started implementing bookstack about 1 month ago coming from confluence. For now Bookstack will have a long journey to travel but I think that it has the potential to get near, if not overtake the big players in this game! Much love from Germany 🔥❤️

**Comment by ssddanbrown** [comment]
Thanks for the request @freddy2312.

> Right now title images of books and shelves have to have a resolution of 440x250px.

Currently we accept a range of sizes, but input is scaled down and resized as needed, and set to cover specific areas via the design, to be adaptable to user input at some level. We don't force size requirements although the general design will target, or more often use, certain aspect ratios and frequent sizes.

What exactly do you see working differently in your request?

**Comment by freddy2312** [comment]
Oh sorry for bothering, i just realized that the Image I used for testing was just a bit too narrow and therefor I got an error ._. 
I think you can delete this issue 🤦‍♂️

**Comment by ssddanbrown** [comment]
Okay, will therefore close this off.
