### ISSUE TITLE
Dark/light button buggy in default dark mode

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#4543]
### Describe the Bug

When defaulting to dark mode through APP_DEFAULT_DARK_MODE=true in the .env the button for toggling between dark and light is not working for the first click. The second click on the button is switching the mode from dark to light.

This behaviour is probably caused by the default function of the button to switch from light to dark.

### Steps to Reproduce

1. Change in .env APP_DEFAULT_DARK_MODE=true
2. Visit your bookstack instance in a private windows
3. See dark mode as default
4. Click on dark/light mode button
5. Mode is not switching to light mode

### Expected Behaviour

The site should change from dark to light on the first press of the button.

### Browser Details

Firefox 117 on Windows 10

### Exact BookStack Version

BookStack v23.08.2

**Comment by ssddanbrown** [comment]
Thanks for raising @Bolthier, could confirm this.
Have patched in 417705651c66239e174a2fc2d5d7df6be6ef2ade, with a test added to cover, to be part of the next feature release.
