### ISSUE TITLE
Change page revision view permission

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#4544]
### Describe the feature you'd like

At the moment the right to view revisions for a page is depending on the standard view permission of a page. This view permission of revisions should not automaticly be given but permitted in the user role.

For example a public user could be restricted to see only the current version. Right now there is a lot of data for every page viewable by external users if you only want them to see the page. Both old content and up to hundred revisions of user data.

Similar to the option "Export content" an option like "View revisions in view-only pages" would be great to restrict this behaviour both for guest and normal users, that have no edit permissions. If a user has edit permissions they should be able to view the revisions regardless of this option.

### Describe the benefits this would bring to existing BookStack users

Better managing of available content and data to unauthorized or restricted users. No need to delete revisions to have information in older versions restricted.

### Can the goal of this request already be achieved via other means?

No. At least not with a lot of deletions of older revisions, which could be needed for editors of the page.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Over 5 years

### Additional context

Had a long time running an older bookstack version and finally up to date after a day of migrating to a new webserver. The documentation and workflow of the backup & restore is superb. Had no issues on the documentation part. So now I'm obviously testing all the new great features and looking into open issues I may have somewhere. Keep up the great work!

**Comment by ssddanbrown** [comment]
Hello again @Bolthier!

We had #4526 raised just last week, I'm going to re-open that and merge this into that, since that thread has has a bit more development with a few potential workarounds provided.

**Comment by Bolthier** [comment]
Sorry for duplicate issue. I was pretty sure I looked into all open issues with revision in its content.

Oh, you re-opened it. Now I get it.
