### ISSUE TITLE
"Follow" button

### ISSUE THREAD

**Issue by hkhiro** [BookStackApp/BookStack#4545]
### Describe the feature you'd like

1. Ability to follow and unfollow a page or section or book.
2. Emails to be sent via a connected Google workspace account and 
3. instructions to stop the subscription at the bottom of the email.

### Describe the benefits this would bring to existing BookStack users

Ability to engage with users and and visitors

### Can the goal of this request already be achieved via other means?

No but not sure

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

### Additional context

Currently exploring and evaluating this wiki for a personal knowledgebase as compared to a transitional blog. Open to suggestions including any other tools that may have this.

Thanks in advance

**Comment by Man-in-Black** [comment]
This feature was already implemented with the actual version 23.08

**Comment by ssddanbrown** [comment]
Yeah, details if needed can [be found in the v23.08 blogpost](https://www.bookstackapp.com/blog/bookstack-release-v23-08/#content-notification-system). 

@hkhiro I'll therefore close this but if we've misunderstood, and you were requesting something different feel free to still comment.
