### ISSUE TITLE
Hierarchical Sub Chapters

### ISSUE THREAD

**Issue by arvindjkhr** [BookStackApp/BookStack#4546]
### Describe the feature you'd like

I wanted to have a feature like Main Chapter > Sub Chapter > Sub Sub Chapter and so on.

### Describe the benefits this would bring to existing BookStack users

This will arrange the table of content accordingly and will be better for navigation and will give ease of managing multiple sub chapters in it.

### Can the goal of this request already be achieved via other means?

I am not sure about that 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @arvindjkhr, my response would be the same as per #3916.
