### ISSUE TITLE
Missing Translation Strings (Even if they exists in lang file.)

### ISSUE THREAD

**Issue by BaxAndrei** [BookStackApp/BookStack#4549]
### Describe the Bug

Missing Translation Strings (Even if they exists in lang file.)
Also webhook is affected 

### Steps to Reproduce

Just updated from v22 > v23

### Expected Behaviour

Display Translations

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/12484505/d9bace4d-5bdf-44f5-ba80-6f0ef073171d)
![image](https://github.com/BookStackApp/BookStack/assets/12484505/4b5979ca-503e-4084-adc6-cb03d6e1fb3e)
![image](https://github.com/BookStackApp/BookStack/assets/12484505/9f472285-91ec-4df1-ae3a-6e610ff01840)

### Browser Details

Google Chrome Version 116.0.5845.188 (Official Build) (64-bit) ON Windows 11 x64

### Exact BookStack Version

BookStack v23.08.2

**Comment by ssddanbrown** [comment]
Hi @BaxAndrei,

- Do you manage updates via the `git` command as per our official guidance?
- Have you ever altered, or added to, any of the language files in the past?
- Within your BookStack install folder, does a `resources/lang` folder exist?

**Comment by claptrap10** [comment]
Hello, 
Same problem for me and i got two lang folder
- BookStack\lang
- BookStack\resources\lang
Strange ?
Thx in advance

**Comment by ssddanbrown** [comment]
@claptrap10 Just delete the `resources\lang` folder and things should start working. If you've ever made any changes within this folder, be sure to back up your changes first for safe-keeping.

**Comment by claptrap10** [comment]
Perfectly, its work !
Thank you

**Comment by BaxAndrei** [comment]
Perfectly, its work for me too!
Thank you
