### ISSUE TITLE
Bug: The code box isn't working properly in 0.17.4

### ISSUE THREAD

**Issue by fredericmohr** [BookStackApp/BookStack#456]
### For Bug Reports

* BookStack Version: 0.17.4
* PHP Version: 7.0.15-0ubuntu0.16.04.4
* MySQL Version: mysql  Ver 15.1 Distrib 10.0.29-MariaDB

##### Expected Behavior

Code box in WYSIWYG editor should be displayed properly (like it did before)

##### Actual Behavior

Code box in edit mode is mangled, it's fine when viewing the page though. As a "workaround", it seems to work when putting the code box inside a quote box.

Code box preview (editing)
![screenshot_20170802_094835](https://user-images.githubusercontent.com/5955966/28863303-ac11aa60-7768-11e7-8c12-ff02d2079123.png)

Code box on saved page (viewing)
![screenshot_20170802_094907](https://user-images.githubusercontent.com/5955966/28863305-ac2b14b4-7768-11e7-950c-7afb6ec812dd.png)

Code box inside quote box (editing)
![screenshot_20170802_095007](https://user-images.githubusercontent.com/5955966/28863306-ac34ad94-7768-11e7-9733-3659e729b9d7.png)

**Comment by ssddanbrown** [comment]
Hi @fredericmohr,
I also noticed this, I think it's a caching issue of some kind. For me It went away after a hard refresh (Ctrl+R in chrome for Ctrl+F5 in IE I think).

Not sure why as the BookStack version is usually tagged on to any linked scripts. Let me know if clearing the cache works for your here.

I'm guessing that with #457 the cache expired or a different browser was used thus why things started randomly working.

**Comment by fredericmohr** [comment]
Works fine in firefox private mode, so I guess you're right. Seems to be a caching issue.

![spectacle cf8684](https://user-images.githubusercontent.com/5955966/28966514-efd1b8da-7916-11e7-965b-fb397f1f9b90.png)
