### ISSUE TITLE
Show books (and chapters) in notifications

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4566]
### Describe the feature you'd like

First of all: The notifications are awesome. Really like this feature and I'm using it a lot now.
But there is one think I miss in the notifications: the hierarchy.
Is it possible to show the name of the book (and the shelve if exists) within the notifications, beside the page title?
We have a lot of pages with the same name but in different books and everytime I had to klick the link so see which book the page is in.

### Describe the benefits this would bring to existing BookStack users

Faster filtering if the notification is relevant at the given time.

### Can the goal of this request already be achieved via other means?

no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by vgpastor** [comment]
+1

**Comment by Manuel311290** [comment]
+1

**Comment by Man-in-Black** [comment]
I've made a PR recently and it is already merged into the next feature release.
