### ISSUE TITLE
missing translation in notification mail (at least in german language)

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4567]
### Describe the Bug

Within the notifications there seems to be a translation missing:
![image](https://github.com/BookStackApp/BookStack/assets/9048534/9d1ce79c-1992-47e8-8bce-0d60b792e15a)

### Steps to Reproduce

1. enable notifications
2. create or edit a page
3. wait for the mail
4. check the text below the lower line

### Expected Behaviour

the correct action name should be displayed, like "show page"

### Exact BookStack Version

23.08.2

**Comment by ssddanbrown** [comment]
Thanks for reporting @Man-in-Black,
Did seem to be a `de_informal` specific issue, which I've now addressed on Crowdin.
Will be synced across for merge in the next feature release.
