### ISSUE TITLE
.env file not loaded

### ISSUE THREAD

**Issue by perfectfe** [BookStackApp/BookStack#4569]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am completely confused. We have been using Bookstack for a few months. I have edited the .env file several times in the past, it has never been a problem.

Now I wanted to edit the file again to adjust the sendmail parameters. But no matter what I do, the new configuration is not applied. Even deleting .env does not change anything, Bookstack still works. Even after reboot of Apache or the whole server, Bookstack is running file without having the .env file in place.

How can it be that Bookstack can be started successfully without .env file? Or where can the configuration be stored alternatively?

### Exact BookStack Version

23.06.2

### Hosting Environment

The Bookstack installation is done in the default path /var/www/bookstack, it is BookStack v23.06.2 on Ubuntu 20.04.

**Comment by ssddanbrown** [comment]
Hi @perfectfe,
Can you provide the output of running `ls -alh /var/www/bookstack/bootstrap/cache`?

**Comment by perfectfe** [comment]
Hi @ssddanbrown 

thanks for you quick response!

Here is the output:
```
ls -alh /var/www/bookstack/bootstrap/cache
total 68K
drwxrwxr-x 2 username www-data  4.0K Aug  9 13:27 .
drwxr-xr-x 3 username www-data  4.0K Jul 19 09:55 ..
-rwxrwxr-x 1 username www-data    14 May 17 16:35 .gitignore
-rw-r--r-- 1 root      root      30K Aug  9 13:27 config.php
-rwxrwxr-x 1 username username  1.6K Jul 19 09:55 packages.php
-rwxrwxr-x 1 username username   20K Jul 19 09:55 services.php
```

**Comment by SirTwinkleberry** [comment]
None of my instances have a `config.php` file in there. Could it be the file creating an issue?

**Comment by ssddanbrown** [comment]
Sorry, forgot to respond back to this, Yeah, please remove the `/var/www/bookstack/bootstrap/cache/config.php` file, and everything should work as expected. The config gets cached to this file when certain optimization commands are ran, and therefore `.env` changes won't be taken into account as experienced.

**Comment by perfectfe** [comment]
This solves the mystery of the ignored .env file.

Unfortunately, it only helps to a limited extent. When I delete the config.php file, Bookstack does not start anymore. When I call it up in the browser, I only get a white page.

**Comment by ssddanbrown** [comment]
@perfectfe A blank white screen usually indicates a permissions issue. To verify, the error should be logged to the webserver log (Commonly `/var/log/apache2/error.log` in this case).

I have [extra guidance on file-system permissions here](https://www.bookstackapp.com/docs/admin/filesystem-permissions/) if needed.

**Comment by perfectfe** [comment]
resetting the permissions helped, Boostack now runs as expected again.

a big thank you to both of you for the quick and competent help! i really appreciate it.
