### ISSUE TITLE
Hitting Enter When Editing Page Tags Clears Field

### ISSUE THREAD

**Issue by aswgxf** [BookStackApp/BookStack#4570]
### Describe the Bug

Whenever I am adding tags to a page, I occasionally submit to muscle memory, and tab between the Tag Name and Tag Value fields, and then hit Enter after entering the value. This clears the value in the field. 

### Steps to Reproduce

1. Edit a page's tags
2. Enter a value for either the Tag Name or Tag Value
3. Hit the Enter key

### Expected Behaviour

I would either expect it to go to the next row, or just do nothing. 

### Exact BookStack Version

v23.08.3

**Comment by SirTwinkleberry** [comment]
I have noticed the same thing but I thought it was a feature rather than a bug to be honest. ^.^
I too would expect "Enter" to save tag changes or go to a new tag line.

**Comment by ssddanbrown** [comment]
Thanks for raising @aswgxf, and thanks for confirming @Timothy-Anders0n.
Addressed in 0241032f061ba9fdc2ba5edd00ad92f945b10c70, to prevent field clearance.
Will be within the next feature release.
