### ISSUE TITLE
Prefill Internal Link/Entity Select Search With Selected Text

### ISSUE THREAD

**Issue by aswgxf** [BookStackApp/BookStack#4571]
### Describe the feature you'd like

I am currently going through some pages and adding links to other pages in BookStack. To try to quickly create these links, I am selecting the text I want to use for the link then using the keyboard shortcut ctrl+shift+k to bring up the Entity Select dialog to search for the page I want to link to. I was thinking it'd be nice to prefill the search dialog with the selected text. 

To prevent interfering with existing workflows, the prefilled text could also be preselected in the search dialog so users who don't want to use the prefilled text can just start typing to do a new search. 

For example, if I select the words "Frequently Asked Questions" in the following text and open the Entity Select dialog:
"For more information, check out the Frequently Asked Questions page."
I would like this result:
![image](https://github.com/BookStackApp/BookStack/assets/14831028/e22657fe-3e13-41a8-8828-4804679cac41)

### Describe the benefits this would bring to existing BookStack users

This would make it much quicker to add links to other pages on the site. I wouldn't consider it an essential feature to add, but it would be a nice QOL improvement

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks @aswgxf,
I quite like this idea as a nice UX improvement, and shouldn't be too tricky to add, at least when accessed via Keyboard.
Have assigned to the next feature release with intent to implement.

**Comment by ssddanbrown** [comment]
This has been added to all use of the selector popup within both editors via commit 21badde4ef7e9f907059b9f3d61859c62a5bc734. 
This will be part of the next feature release.

Thanks again @aswgxf for the suggestion.
