### ISSUE TITLE
Publish button

### ISSUE THREAD

**Issue by vgpastor** [BookStackApp/BookStack#4577]
### Describe the feature you'd like

I like to save the changes while i'm editing a file, but don't public this how a new version until we don't push in a specific button or similar.

### Describe the benefits this would bring to existing BookStack users

This allow to work with the application and make not neccesary use a external tool to develop the documentation and finally save this.

In the same way if i edit multiple pages we can publish all of them in the same version of book.

### Can the goal of this request already be achieved via other means?

Work in the book without publish the changes until we approve all of them.

Tag the version of the book with all changes.

Can have an historical of all changes from a version

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
As mentioned in #2982, there is not process built in to support this kind of flow.
Such a process has been requested via #473 already so I'm going to close this off as a duplicate.
