### ISSUE TITLE
Problem with Cyrillic when exporting to pdf

### ISSUE THREAD

**Issue by antonjuice** [BookStackApp/BookStack#4579]
### Describe the Bug

When exporting to PDF, instead of Cyrillic, I get the characters "?".

### Steps to Reproduce

Go to book|page -> Export -> PDF file

### Expected Behaviour

I was expecting to see Cyrillic characters

### Exact BookStack Version

v23.08.3

**Comment by ssddanbrown** [comment]
Thanks for raising @antonjuice, but I think this is essentially already covered by #719.
Let me know if this has worked previously, until recently, and I could re-open since it may be something else at play. I'd just need to understand what version of BookStack it worked in.

**Comment by antonjuice** [comment]
About the previous version. I can't say. I just installed the current version yesterday.
