### ISSUE TITLE
Folder "views" in Custom Themes

### ISSUE THREAD

**Issue by ikabod** [BookStackApp/BookStack#4580]
### Describe the feature you'd like

Hi,

you have the folder "icons" in the custom themes folder to override icons. You have the folder "lang" to override translation texts. 

Why not a folder named "views" for all view overrides?

Thanks,
Peter

### Describe the benefits this would bring to existing BookStack users

This would make the folder structure more cleaner, especially if somebody (like me) have some other folders too, e.g. "php" for own class files and "js" and "css" folder.

### Can the goal of this request already be achieved via other means?

If you are a .httaccess expert, may be you can provide an example to move an existing folder "/themes/my-theme/common/" to "/themes/my-theme/views/common/"?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
> Why not a folder named "views" for all view overrides?

Because the system was created just for views initially, then extended to the other content types.
Don't really want to change things for existing users.
Could run both options (Check both paths) but I'm not too keen on adding adding ambiguity to the theme system, for non-back-compat reasons, and I don't assure that folders/paths will always mirror the resources folder, things may change.

**Comment by ikabod** [comment]
Suggestion: A script, which runs on the next update only and moves all folders which exists in "/resources/views/" into the new "/themes/my-theme/views/" folder.

**Comment by ssddanbrown** [comment]
I'm not really sure what that achieves, at cost to maintaining. I'd rather users only have the folders they need.
Could always script that for your own instance if desired.

**Comment by ssddanbrown** [comment]
I'll proceed to close this off as per my reasoning above.
