### ISSUE TITLE
Videoplayer integration

### ISSUE THREAD

**Issue by towerplease** [BookStackApp/BookStack#4588]
### Describe the feature you'd like

As the count of videos added to bookstack in my instance is constantly growing, the current implementation of video playback could be optimized.

As fas as i know, there is no better way to upload videos, as of uploading it as an attachment, then using the direct-link to that attachment and add it via "add media".

For me i found that way "working", but it is now as good as i could be.

For example, i had to play around with the width and height values, to find a nice sweetspot. Currently 840 and 420 looks fine:

![image](https://github.com/BookStackApp/BookStack/assets/21177236/c3f77f80-2b98-4ffb-a040-5edfcdc6d6f8)

This results in a display that uses the browser's default media player (Firefox):
![image](https://github.com/BookStackApp/BookStack/assets/21177236/7a813db1-af8b-4940-a3da-40b511cf6349)

It would be nice, there were like an Mediamanager also for videos, with an integrated videoplayer provided by bookstack. This would also optimize the streaming capabilities for the user and the video does not has to be viewed as an attachment (which also should be an available option)

Its not a must have feature, but a really "nice to have" thing.
I am using confluence at work, and there is also a video player provided, little features like a small "download" button and playback speed is also available :)

Thanks in advance!

### Describe the benefits this would bring to existing BookStack users

Benefits would be a much smoother userexperience when providing videos.

### Can the goal of this request already be achieved via other means?

Yes, as already described, the default method of the browser can be used when inserting media with the attachment link.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

You are great!

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @towerplease.
I'll probably close this off though in favor of  #882 and  #3274 as I feel they already cover the core demand for proper video handling.

Personally I'd probably not look to implement a custom video editor for BookStack, and prefer to remain using native browser functionality where possible since functionality is usually good enough for most BookStack use-cases. Often those features are available via browser at some level, or keeping things default could allow instances to customize with their own desired libraries.

**Comment by towerplease** [comment]
Hi Dan,

thanks for having a look at the feature request. Surely i understand the decision in keeping browser-related features to keep bookstack slim. As i have a path to implement videos thats fine for me.
