### ISSUE TITLE
SQLSTATE [42S02]: Base table or view not found: 1146 Table '<databasename>.watches' doesn't exist

### ISSUE THREAD

**Issue by jameskeel** [BookStackApp/BookStack#4589]
### Describe the Bug

Bug appeared after updating from 23.06.2 to 23.08.2.  The error happens after an edit is saved and only appears once for each document that is edited.

### Steps to Reproduce

1. Within Bookstack webpage, open a previously created page
2. Edit the page, and then save.  You don't need to make any changes at all
3. Then the error displays
4. Refresh the page and the change is saved and updated.
5. Edit the same page again and the error does not appear.

### Expected Behaviour

After an edit is made the page is saved and then displayed.

### Screenshots or Additional Context

![libraryerror](https://github.com/BookStackApp/BookStack/assets/146385531/c2c8b0d6-81e2-4c0a-b627-36d30b133fb8)

### Exact BookStack Version

v23.08.2

**Comment by ssddanbrown** [comment]
Hi @jameskeel,

Did you run the `php artisan migrate` step during upgrade to this version, and if so did you see any errors?
What is the output if you re-run that update step command?

**Comment by jameskeel** [comment]
Thank you @ssddanbrown for the speedy reply.  I don't recall any errors but I'll run it again after hours tonight and keep you posted.

**Comment by jameskeel** [comment]
Thank you @ssddanbrown.  Re-running that command resolve the issue.

**Comment by ssddanbrown** [comment]
Good to hear that solved it! Will therefore close this off.
