### ISSUE TITLE
Create template/skeleton

### ISSUE THREAD

**Issue by hotgeart** [BookStackApp/BookStack#459]
Can we have the possibility to create "templates" or "skeleton" for the page?

Imagine in my bookstack I've docs for bikes and smartphones. That two differents item but always the same infos for each item and at the moment we've only a _title_ and a _content_ so I'll need to copy/paste a template like so:

**Template for Bike :**
Name: Super bike
Km: 2.000 km
...

**Template for Smarthphone:**
Name: Apple X
4G: YES
...

So my suggestion is to have the possibility to create a template with custom fields and categorize them (something more beautiful than <fieldset>).

At the template creation we could :
- Create custom fields (num, textarea, select, checkbox, etc.)
- Make fields required or not
- Create fieldset/cateogry to organise a group the fields and reorganize them wirh jQuery Sortable
- If the field is empty it'll not appear in the page.
- ... other sugg?

I think this'll be a powerful feature.

**Comment by ssddanbrown** [comment]
Hi @hotgeart, This is very similar to #129, Let me know if there's a clear definable difference between this issue and #129 otherwise I'll look to close this to prevent duplicate issues.

**Comment by hotgeart** [comment]
@ssddanbrown Ooops sorry for the duplicate, I'll close. Yes, I guess we want the same things.
