### ISSUE TITLE
In-line comments or suggested changes

### ISSUE THREAD

**Issue by nharris-lmg** [BookStackApp/BookStack#4591]
### Describe the feature you'd like

It would be rad if users could make in-line comments and/or suggested edits to documents. 

### Describe the benefits this would bring to existing BookStack users

This would improve the effort of collaboration on a single document currently we have are fighting over draft versions, and want to make in-line comments instead.

### Can the goal of this request already be achieved via other means?

There are comments at the bottom of the page to make your suggestions, but its constant scrolling to go to the comments and then back up to the section the comment is commenting about.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @nharris-lmg, but I feel #1265 already covers the fundamental request here so I'm going to close this off as a duplicate.

> but its constant scrolling to go to the comments and then back up to the section the comment is commenting about.

In a recent release I made comments also available in the editor sidebar to help with feedback/editing flow.
I do intent to continue improvements to the utility of comments in upcoming releases, for which inline commenting at some level may factor into.

**Comment by nharris-lmg** [comment]
Ah sorry I didn't see that one.

We are going to update our current deployment to check out those changes.
