### ISSUE TITLE
Search within Shelve

### ISSUE THREAD

**Issue by robske110** [BookStackApp/BookStack#4593]
### Describe the feature you'd like

It would be very nice to search within a shelve, like within a book. Alternatively just offering the option to limit the global search to results from a shelve would work.

### Describe the benefits this would bring to existing BookStack users

Easier to scope searches.
We use Shelves as segregations of "departments" / "orgunits" and it is hard to search for something that might also be similarly existent in other shelves. This is just an example though, I think this would be very useful for many other use cases too.

### Can the goal of this request already be achieved via other means?

Unfortunately not. Assigning a tag to the shelve and limiting the search to that does not work, for example.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @robske110, but I'd consider the fundamental request here already covered by #3546 so I'm going to therefore close this off as a duplicate.

**Comment by robske110** [comment]
Thank you and sorry for wasting your time here, I wasn't able to find that issue with my short search.
