### ISSUE TITLE
Internal Statistics

### ISSUE THREAD

**Issue by unixweb** [BookStackApp/BookStack#4601]
### Describe the feature you'd like

Please implement a statistic in bookstack. 
I want to know how many times a book has been read since my instance is public. 
At the moment I have to use Matomo externally.

Thank you 

### Describe the benefits this would bring to existing BookStack users

It helps us all to see which articles are well visited and what reader interest is.

### Can the goal of this request already be achieved via other means?

I have no idea if it possible in a existing 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

### Additional context

My workaround for now.
![Bildschirmfoto 2023-10-05 um 09 51 31](https://github.com/BookStackApp/BookStack/assets/12023025/72f6b51f-bb8a-4058-a023-1a499c2a1cc4)

**Comment by ssddanbrown** [comment]
Hi @unixweb,
Thanks for the request.

Could you explain why this should be part of BookStack rather than using an existing comprehensive analytics suite like Matamo? What are the issues with using an external solution for this?

Somewhat related to #518

**Comment by ssddanbrown** [comment]
Since there's been no further follow up to my message above I'll close this off.
