### ISSUE TITLE
Links in drawings do not work outside of editing mode

### ISSUE THREAD

**Issue by CentioRS** [BookStackApp/BookStack#4603]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When adding a link to a drawing (using drawing.io) the links will not work once the page is saved. Looking for a way to make this work.

Would be very helpful when creating networkdiagrams to be able to go to the website directly.

### Exact BookStack Version

v23.08

### Hosting Environment

Ubuntu 22.04 on Vmware Vcenter

**Comment by ssddanbrown** [comment]
Hi @CentioRS,
We don't currently support links within drawings (or other interactivity) since we convert and use drawings as standard PNG images. A request to support links within drawings is already open in  #1170 so I'll close this off in favor of that.

**Comment by CentioRS** [comment]
Somehow I missed #1170. Sorry for that. Will keep on eye on it,
