### ISSUE TITLE
Feature Request: Moderation Workflow for Page Edits

### ISSUE THREAD

**Issue by erseco** [BookStackApp/BookStack#4605]
### Describe the feature you'd like

I propose the addition of a moderation workflow for page edits. This would allow edits made by users to be held for review by a moderator or admin before they become publicly visible or replace the existing content.

### Proposed Functionality
1. When a user with appropriate permissions edits a page, the changes are saved as a "pending" version.
2. Designated moderators receive a notification of a pending edit.
3. Moderators can review, approve, or reject the changes.
4. If approved, the edits replace the current page version. If rejected, the pending version is either discarded or saved as a draft for further edits.

### Describe the benefits this would bring to existing BookStack users

In environments where the accuracy and quality of content are crucial, it would be beneficial to have a system where changes can be reviewed and approved (or rejected) by designated individuals. This ensures that all content changes meet the desired standards and prevents potential misinformation or undesired edits from being instantly live.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

### Additional context

Platforms like MediaWiki or Confluence offer workflows where content can be moderated. However, the simplicity and user-friendliness of BookStack make it a preferred choice for many, and the addition of this feature could significantly enhance its utility for teams or organizations that require a controlled editing environment.

I believe this feature would be a valuable addition to BookStack and hope the community and developers find this suggestion beneficial. 

Thank you for considering my proposal!

**Comment by erseco** [comment]
This issue is related to #3983, #473 and #2123

**Comment by ssddanbrown** [comment]
Thanks for the request @erseco, but I would consider the fundemental request here already covered by #473 so I'm going to close this off as a duplicate.
