### ISSUE TITLE
? shows shortcuts while editing

### ISSUE THREAD

**Issue by matthias4217** [BookStackApp/BookStack#4606]
### Describe the Bug

When editing a page, pressing `?` will both write the character and show the on-screen shortcuts available. This behaviour has only been observed in the Markdown editor.

### Steps to Reproduce

1. Edit a page in Markdown
2. Press the `?` key

### Expected Behaviour

When in edit mode, `?` should write the character and not show available shortcuts.

### Screenshots or Additional Context

We have made some customization to our Bookstack instance. I don’t think any of them should impact this behaviour.

### Browser Details

Firefox 118.0.1 (64-bit)

### Exact BookStack Version

v23.08.2

**Comment by ssddanbrown** [comment]
Thanks for reporting @matthias4217.
Could confirm this would occur on the markdown editor, upon all other system text inputs.
This has been addressed in d42af4affc047893e39be6ad25b384cde6c981ff which will be part of the next feature release.
