### ISSUE TITLE
Bookstackapp not reachable after IP adress change of host

### ISSUE THREAD

**Issue by macdilbert66** [BookStackApp/BookStack#4607]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have an installation of Bookstackapp running on Ubuntu on a VM on Mac.
I have changed the network adress of the Mac from 192.168.22.x to 192.168.44.x
Ubuntu host is running now also on a new adress, but since Bookstackapp is not reachbale on the old and the new IP adress.
Anyone can help?

### Exact BookStack Version

22.xx

### Hosting Environment

Ubuntu 22.04 on vmware VM on Mac

**Comment by ssddanbrown** [comment]
Hi @macdilbert66,
The exact detail will depend on how the instance was created/set-up.

Assuming you followed the install script, you'd also need to adjust the IP in:

- The webserver Apache config:
  -  Found towards the top of the `/etc/apache2/sites-available/bookstack.conf` file.
  - After changing, restart apache `sudo systemctl restart apache2`
- The BookStack `APP_URL` option variable: 
  -  Found in the `/var/www/bookstack/.env` file.

If you have existing content in the system, you'd also want to run the Update System URL command:
https://www.bookstackapp.com/docs/admin/commands/#update-system-url

Ensure things are backed-up/snapshotted first.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll go ahead and close this off.
