### ISSUE TITLE
APP_URL keeps resetting to initial value after URL change

### ISSUE THREAD

**Issue by maa13** [BookStackApp/BookStack#4608]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When trying to change the IP in the .env file it keeps resetting after every restart
I followed the suggestion to change the URL stored in the database by running below command

php artisan bookstack:update-url http://OLD-IP:6875 https://NEW-IP
The command asked for confirmation on two steps and I approved and it changed multiple entries, the clear cache command was ran too

The .env old value persists after every restart regardless of what I change there

### Exact BookStack Version

v23.01.1

### Hosting Environment

Red Hat Enterprise Linux Server release 7.9 (Maipo)
Client: Docker Engine - Community
Version:           19.03.11-ol

Utilizing offical docker-compose version with maria-db
lscr.io/linuxserver/bookstack
lscr.io/linuxserver/mariadb

**Comment by Man-in-Black** [comment]
I think as long as you are using docker you need to change the value in the environment variables of your `docker-compose.yml`

**Comment by ssddanbrown** [comment]
Yeah, I second the @Man-in-Black's comment above, check that you've update the `APP_URL` in you're compose env options. If you're not setting one, add one (it may have been blank in the original linuxserver example docker-compose file when you originally set-up the instance.)

Example as per this line: 

https://github.com/linuxserver/docker-bookstack/blob/0b32a2a4c34532b8581979d2af56d21f7928c9d9/README.md?plain=1#L110

**Comment by maa13** [comment]
Much appreciated, modifying the value in docker-compose.yml did the trick
