### ISSUE TITLE
public access for one book or one page

### ISSUE THREAD

**Issue by ArtisWorld** [BookStackApp/BookStack#4611]
### Describe the feature you'd like

Hi,

it would be cool, if i can grant public access for a person, who i want to read one book or one page (maybe his customer documentation). With one sent link.
Do you think its possible?

Thanks. :-)

### Describe the benefits this would bring to existing BookStack users

every bookstack user can grant someone to access the page or book with one link (with password?).

### Can the goal of this request already be achieved via other means?

yes, i can export the page and send it to this user.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

### Additional context

Great software, thank you.

**Comment by ssddanbrown** [comment]
Thanks for the request @ArtisWorld,
A request to share content via a link already exists via #288, so I'm going to close this off as a duplicate request.

There is another potential workaround via:

- Enabling public access on the instance via application settings.
- Remove all default permissions from the default guest user/role.
- Override the permissions for a single specific item, to provide the guest user role permissions to view.

But this does require enabling public access and active permission control, which can have security considerations.
