### ISSUE TITLE
Finnish translation for Bookstack

### ISSUE THREAD

**Issue by TomiToivio** [BookStackApp/BookStack#4614]
### Language to Add

Finnish

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Hi @TomiToivio,
Thanks for offering to translate things into Finnish.
I've now enabled Finnish as an option on Crowdin: 
https://crowdin.com/project/bookstack/fi

Note, if there's relatively little completion progress after a while I may remove the language. 
The option for Finnish within BookStack will only be added once the translations have relatively high coverage.

**Comment by TomiToivio** [comment]
Yes, Finnish translation is for the Finnish FLOSS Manuals. FLOSS Manuals used Booktype but since Booktype is no longer supported the Finnish site is switching to Bookstack.

**Comment by ssddanbrown** [comment]
Okay, just be aware that Booktype and BookStack appear to have quite different purposes, although may overlap in use and functionality. BookStack is not built, or designed for, book publishing like Booktype appears to be. BookStack is a general documentation platform with a structure following the ideas/theme of a book.
