### ISSUE TITLE
Ability to change font size for page content

### ISSUE THREAD

**Issue by alariva** [BookStackApp/BookStack#462]
Desired Feature: Ability to change font size for page content

* BookStack Version: `v0.17.3`

##### Expected Behavior

Is there any suggested way to change font size through configuration?

Since most of my docs users will prefer bigger font size, I wonder if there's a quick way to change it. An alternative approach would be allowing them to do so client-side with discrete `A+` and `A-` buttons.

##### Actual Behavior

It looks like the best (and only) approach for this is by customizing the HTML headers.

Also, this looks related to https://github.com/BookStackApp/BookStack/issues/423 , so in that case I'll follow-up.

Thanks and regards,

**Comment by domainzero** [comment]
On a per page basis you could always do a `<font size="16">` or make an arbitrary class and do a `<span class="biggertext">` to get bigger text where you want it since inline HTML is supported.

**Comment by alariva** [comment]
Thanks @domainzero , I was referring to a global-scope setting, but this also helps.

**Comment by watschi** [comment]
`<font size="16">` won't change text in codeblocks unfortunately.

**Comment by ssddanbrown** [comment]
@alariva Throwing this into the 'Custom HTML Head Content' will get you near:

```
<style>
.page-content {font-size: 1.1em;}
.cm-s-base16-light.CodeMirror {font-size: 14px;}
</style>
```

For a documentation platform it may be good to have this as on-page controls though 🤔 . Good idea.

**Comment by DoTheEvo** [comment]
Would be nice to be in the default toolset. I am missing it too.

**Comment by drmax24** [comment]
Any news on this?

**Comment by ssddanbrown** [comment]
@drmax24 Nope, Nothing upon the above options for now

**Comment by Seth-AIG** [comment]
> .cm-s-base16-light.CodeMirror {font-size: 14px;}

Seems this doesnt do anything to the text in the body but only the heading of the page. Has the code updated to reflect a different reference other than .cm-s-base16-light.CodeMirror?

**Comment by kauesena** [comment]
It would be nice to be able to choose the default font size of each level of heading (an perhaps style in general, some people may want to do something like Wikipedia with some titles in bold sans-serif and others in bold serif) .  I generally feel distracted by the big size of headings. I'm more for a slightly bigger heading.

**Comment by gtothill** [comment]
I'm a newcomer to BookStack but I'm already publishing in it. I'm also aware that 'Id like that too' posts are to be discouraged. That having said, the rather beautiful GUI that exists is somewhat, IMHO, degraded by the font sizes of titles and section headings. The ability to change these on a per book or system wide level would be hugely appreciated and allow more fine grained control of the appearance of content. I'm not suggesting full blown themes, just granular font control.

**Comment by ssddanbrown** [comment]
Hi @gtothill,
You can customize the default header sizes by adding something like the below to the "Custom HTML Head Content" setting:

```html
<style>
.page-content h1 { font-size: 2rem; }
.page-content h2 { font-size: 1.8rem; }
.page-content h3 { font-size: 1.6rem; }
.page-content h4 { font-size: 1.4rem; }
.page-content h5 { font-size: 1.3rem; }
.page-content h6 { font-size: 1.15rem; }
</style>
```
