### ISSUE TITLE
Recommend reading new books

### ISSUE THREAD

**Issue by yvesmarinho** [BookStackApp/BookStack#4623]
### Describe the feature you'd like

When including a book/title/page, there will be a button to recommend reading to the group or people registered on Bookstack.

### Describe the benefits this would bring to existing BookStack users

All system users are now aware of the new readings.

### Can the goal of this request already be achieved via other means?

I didn't find documentation on this.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

### Additional context

The Bookstack system is the best system we have found. It is very useful in system documentation, customer documentation, process documentation, etc.

**Comment by ssddanbrown** [comment]
Thanks for the request @yvesmarinho (and for the kind feedback), but I'm going to close this in favour of #4434 which, while desiring a specific different technical implementation, I feel already covers the same fundamental use-case/desire to push/recommend content upon other users/groups.
