### ISSUE TITLE
Editor toolbox icons not visible when selected while using dark app theme color on dark mode

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#4630]
### Describe the Bug

In Edit Mode Right Side
![image](https://github.com/BookStackApp/BookStack/assets/6242840/e1ebe1cd-7fc3-4395-ac29-f62d67397bd8)

### Steps to Reproduce

Go To Edit Mod with Dark Mode

### Expected Behaviour

Empty Icon see

### Browser Details

Chrome

### Exact BookStack Version

23.10

**Comment by ssddanbrown** [comment]
Thanks for reporting @reddexx.
I'm assuming you have a dark primary app color (header bar color) set for dark mode?

I've used the primary color here but the link color may be more appropriate instead.

**Comment by reddexx** [comment]
yes is the Primary Color

![image](https://github.com/BookStackApp/BookStack/assets/6242840/a4bc9f37-a423-4d96-ab28-ac3ced9fc721)

**Comment by reddexx** [comment]
I have change this CSS 

.floating-toolbox .tabs-inner>button:hover, .floating-toolbox.open .tabs-inner>button.active {
    background-color: var(--color-primary-light);
    color: #fff9f9;
    border-bottom: 1px solid #000;
    border-top: 1px solid #000;
}

unfortunately the declaration is often bound with many ID, see GIF
![chrome_0K9md135Tk](https://github.com/BookStackApp/BookStack/assets/6242840/7c5096c9-75b9-4a2b-8d7b-d0afa6625586)

**Comment by reddexx** [comment]
@ssddanbrown this Working

.floating-toolbox .tabs-inner>button:active, .floating-toolbox.open .tabs-inner>button.active {
    background-color: var(--color-primary-light);
    color: #fff9f9;
    border-bottom: 1px solid #000;
    border-top: 1px solid #000;
}
![chrome_4NeeCM7hFp](https://github.com/BookStackApp/BookStack/assets/6242840/98bc0017-d6c4-43e3-a412-768ca0ce8d94)

**Comment by ssddanbrown** [comment]
> yes is the Primary Color

Thanks for confirming. I've assigned to the next patch release, with an aim to just use the link color instead of the primary app color (Or a lighter grey as demoed above if that does not suit).

**Comment by ssddanbrown** [comment]
This has now been addressed within 02d140120ac6c00987ec536ad9adb4250aeeb3d8, to be part of the next patch release.

Thanks again for reporting @reddexx!
