### ISSUE TITLE
Group owned objects

### ISSUE THREAD

**Issue by FredericBrg** [BookStackApp/BookStack#4635]
### Describe the feature you'd like

I'd like the ability to define ownership of an object (like a shelf, book,...) to a group instead of a single user.

### Describe the benefits this would bring to existing BookStack users

In a context with a big team working over many different projects, and with some access control, it is tedious to always have to change the permissions of objects (mainly books) so that only a specific group can modify or view it.
Also when the owner of some objects leave the team, it takes some time to reassign every objects to a new owner.

Having group owned objects would solve both issues.
Group permissions over `Own` objects could then apply to the group owned objects, and turnover wouldn't be something to worry about.

### Can the goal of this request already be achieved via other means?

Yes, by creating exceptions every time we create an object, and manually reassigning objects to new owners in the case of an account deletion. But this takes a lot of time

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @FredericBrg.
This has a lot of overlap in fundamental request with #3964, I may close this in favour of that existing issue.

> In a context with a big team working over many different projects, and with some access control, it is tedious to always have to change the permissions of objects (mainly books) so that only a specific group can modify or view it.

Wouldn't you have to do this anyway? If we did add this ability you'd still have to go to the same permissions view and form to change the owner to the desired group.

>  Also when the owner of some objects leave the team, it takes some time to reassign every objects to a new owner.

What is the purpose of re-assigning in this context? I know there are some reasons to re-assign but they are quite limited and to no benefit to your process/context shared so far.
Just wondering if this step is required for you.

**Comment by FredericBrg** [comment]
There are indeed some similarities with #3964, and it seems that this solution is [mentioned in the comments](https://github.com/BookStackApp/BookStack/issues/3964#issuecomment-1564431903). I'll close my issue in favor of this one.

> Wouldn't you have to do this anyway? If we did add this ability you'd still have to go to the same permissions view and form to change the owner to the desired group.

When the amount of books per team gets large it can be slightly longer to change rights than to change the owner.

> What is the purpose of re-assigning in this context?

In the actual context, I sometime need to assign a team wiki manager, and then change him when he'll leave the said team. Having group owned objects wouldn't require me to change that, I could create a specific role for that, and also have multiple people assigned to it.
