### ISSUE TITLE
Navigating to header in Spoiler / collapsible blocks

### ISSUE THREAD

**Issue by JK1198** [BookStackApp/BookStack#4637]
### Describe the Bug

When you create an header in an collapsible block (spoiler) is is displayed in the page navigation. 
If you click on it in the navigation, nothing happens. 
If you open the spoiler manually and click on the header in the navigation, it jumps to the correct header.

But the URL always changes correctly e.g.: .../books/testbook/page/testpage#bkmrk-header-inside-block

### Steps to Reproduce

1. Create a page with a collapsible block and create a header in it.
2. After saving the page click on the header in the page navigation.
3. Nothing happens.

### Expected Behaviour

I would expect the spoiler to open and jump to the correct header when clicked on in the navigation section. Or it should at least jump to the spoiler.

### Screenshots or Additional Context

Example Page:
![image](https://github.com/BookStackApp/BookStack/assets/124798291/11c8fe05-21ea-4d96-96bc-4e0206bbb8ba)
With open spoiler:
![image](https://github.com/BookStackApp/BookStack/assets/124798291/69310042-ec05-4415-a525-f0040f4cc37c)

### Exact BookStack Version

v23.06.02, v23.08, v23.10

**Comment by ssddanbrown** [comment]
Thanks for reporting @JK1198,
Should be simple for us to open the block before scrolling and go to the correct location as expected.
Have assigned for the next patch release.

**Comment by ssddanbrown** [comment]
This has now been addressed as part of 38ac3c959bf1282cc46ff4ae7da7f24ad4ea8140, and will be part of v23.10.1.
Thanks again for reporting @JK1198.
