### ISSUE TITLE
Markdown editor shows header bar through editor controls when in fullscreen mode

### ISSUE THREAD

**Issue by codemicro** [BookStackApp/BookStack#4641]
### Describe the Bug

When going into fullscreen mode in the Markdown editor, the header bar shows through from behind the UI.

![image](https://github.com/BookStackApp/BookStack/assets/25284325/4048b65e-e814-4a8f-b3d0-90ed0fcb96b7)

### Steps to Reproduce

1. Create/open a page using Markdown editor mode
2. Enter fullscreen mode
3. Tada!

### Expected Behaviour

I'd expect this to behave the same as in the WYSIWYG editor, with the editor controls showing and the header bar being completely invisible.

### Screenshots or Additional Context

There is no customisation done to the UI of Bookstack here aside from some changing of some colours in the settings and the addition of some Mathjax scripts to the custom header content section.

I don't remember seeing this before v23.10, but that doesn't mean it wasn't already there before the editor UI tweaks because I don't often use Markdown editing.

I also did try to look for duplicates of this issue but couldn't find any - sorry if it is duplicated!

### Browser Details

Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

### Exact BookStack Version

v23.10

**Comment by ssddanbrown** [comment]
Thanks for reporting @codemicro.
Can confirm this. Would have been a scenario i missed in the editor design changes.
Have now patched this in 9dd05b87518e090a50432ba2ae7fe0e5fcc575dc.
This patch will be part of the next patch release (v23.10.1)
