### ISSUE TITLE
export to .html doesn't work in RTL languages

### ISSUE THREAD

**Issue by chezgi** [BookStackApp/BookStack#4645]
### Describe the Bug

in RTL languages like farsi, when exporting as .html single page, its layout will be broken

### Steps to Reproduce

language: farsi
write sample page
export to .html

### Expected Behaviour

must be in RTL layout

### Exact BookStack Version

latest

**Comment by ssddanbrown** [comment]
Thanks for reporting @chezgi,

It wasn't clear what the particular issue may be from the report, but I could observe that RTL was not followed for book or chapter exports, nor for the meta content for page exports.
I've now addressed this in 0254527bd9686eae16cb9d4639542009d3108ca7, and been through each HTML export type to ensure that RTl text is respected.
These changes will be part of the next feature release.
