### ISSUE TITLE
Suggested Feature: Distraction-Free mode

### ISSUE THREAD

**Issue by alariva** [BookStackApp/BookStack#465]
### For Feature Requests

Desired Feature: Distraction-Free mode

##### Expected Behavior

Distraction-free would stand for:

  * hiding nav and side bars (or any distracting controls)
  * centering text
  * enlaging font size
  * maybe switching font face

As an example, I'm attaching an example of my current docs on BookStackApp and a GetPocket read-mode screen to show the difference.

![Standard Mode](https://user-images.githubusercontent.com/3021314/29080525-58eacde4-7c36-11e7-97af-da53f229bd27.png)

![Distraction-Free Read Mode](https://user-images.githubusercontent.com/3021314/29080533-5f5755b2-7c36-11e7-986d-9452c51a4818.png)

**Comment by hotgeart** [comment]
Why you don't just export to PDF?

**Comment by alariva** [comment]
Yeah, PDF is great and I'm doing so right now. But since I'm not the only user of the app and the rest are non-dev roles, I thought it might be good to have a handly option for avoiding content download.

**Comment by alariva** [comment]
Thanks @ssddanbrown 
That sounds great to me

**Comment by tmikaeld** [comment]
Can you also add an option to have the book navigation on the right side?

I noticed (duuh) you changed it to the left side, but this removes focus from the text for me and some of my editors feel the same, it would be best to have it as an option.

**Comment by ezzra** [comment]
I also want to support the idea of removing distractions. At the moment I think that the cards on the left side are heavily distracting most of all new users. I would like to concentrate more on the content of the pages, Iam currently "fixing" this by using lower css opacity on most of the cards, but it would be great to make it possible activating the responsive mode effect even on larger screens
