### ISSUE TITLE
Audit Filter goes out of view box

### ISSUE THREAD

**Issue by lue30499** [BookStackApp/BookStack#4652]
### Describe the Bug

The Event Filter in the audit log section goes out of the screen at the top.

### Steps to Reproduce

1. Go to settings
2. Go to Audit log
3. Click Event Filter to add a filter
4. witness the list popup go out of screen at the top.

### Expected Behaviour

The filter popup goes down or is limited to within the screen, so I can see all options

### Screenshots or Additional Context

<img width="355" alt="Screenshot 2023-11-06 at 20 01 41" src="https://github.com/BookStackApp/BookStack/assets/63104612/9acee5f2-5480-40f5-bb73-1ec92287197d">

### Browser Details

Chrome 118.0.5993.117 arm64

### Exact BookStack Version

v23.10.1

**Comment by ssddanbrown** [comment]
Thanks for reporting @lue30499.
Could confirm, and have addressed this within fa6ac211b61bd3d86dadc558c89f7366f6613ab3, which makes dropdown positioning and sizing a bit smarter based on available space.

These changes will be part of v23.10.2 to be released soon.
