### ISSUE TITLE
Can't update to newer version 

### ISSUE THREAD

**Issue by ryanvoorspoels** [BookStackApp/BookStack#4653]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I followed the upgrade instructions and I see that the server is retrieving files but nothing is being updated to a new version

### Exact BookStack Version

BookStack v22.11 

### Hosting Environment

Ubuntu 22.10 php:8.2.6

**Comment by ssddanbrown** [comment]
Hi @ryanvoorspoels,
Please could you explain the detail/output/errors you're seeing when attempting to run the update commands?

**Comment by ryanvoorspoels** [comment]
Hi @ssddanbrown, It is solved. There were extra files in the public folder and git pull origin release gave an error.

**Comment by ryanvoorspoels** [comment]
Hi @ssddanbrown, after the update the header is too big. What can I do about it?
![afbeelding](https://github.com/BookStackApp/BookStack/assets/16672674/6b8e10b6-be88-41f3-aa55-baeab414973e)

**Comment by ssddanbrown** [comment]
@ryanvoorspoels 

- What is the current output of running `git status` from your bookstack directory?
- What is the current output of running `git log -n 1` from your bookstack directory?
- Have you attempted (now or previously) any customizations to the header via custom HTML or our theme systems?

**Comment by ryanvoorspoels** [comment]
git status
On branch release
Your branch is up to date with 'origin/release'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        bookstack-files-backup.tar.gz
        public/bookstack-files-backup.tar.gz
        public/dist/print-styles.css 
        public/libs/tinymce/custom-changes.md

nothing added to commit but untracked files present (use "git add" to track)

git log -n 1
commit c61af9c22b319f3fa00e1b089000aecefe36ad09 (HEAD -> release, origin/release)
Author: Dan Brown <ssddanbrown@googlemail.com>
Date:   Thu Nov 2 14:44:53 2023 +0000

    Updated version and assets for release v23.10.1

Before the update we added somthing to  Custom HTML Head Content. I have removed it but no change.

**Comment by ssddanbrown** [comment]
Thanks for the info @ryanvoorspoels.

Just a note, you may want to move/remove the `public/bookstack-files-backup.tar.gz` file you have, since that file would be accessible to anyone with any kind of web access to your instance.

Can't see anything which would affect the header though.
- Do you have anything with the `themes/` folder of your BookStack install?
- Does this remain the same if you open in a different browser and/or private window?
- What browser are you using?
- Does our demo instance look okay in the same browser (https://demo.bookstackapp.com)?

**Comment by ryanvoorspoels** [comment]
@ssddanbrown  thanks for the info. I removed the public/bookstack-files-backup.tar.gz file. I tried it on a differed pc and it looks normal. I only have the problem on firefox on windows but after the deleting history and cookies and the buffer the problem is gone. Thanks for helping me!
