### ISSUE TITLE
Enhanced Commenting Functionality

### ISSUE THREAD

**Issue by asaglam76** [BookStackApp/BookStack#4668]
### Describe the feature you'd like

I would like to propose the implementation of an enhanced commenting feature in BookStack, similar to the functionality seen in Microsoft Word. This feature would allow users to add comments to specific sections or paragraphs within a document, rather than just at the end of the document.

**Key Features**

1. **Inline Commenting**: Users can select a specific text segment and add a comment directly linked to that segment.
2. **Threaded Discussions**: Each comment could potentially become a thread, allowing for back-and-forth discussion on specific document parts.
3. **Highlighting Text**: The text segment related to a comment would be highlighted or marked, making it easy to identify which part of the document the comment refers to.
4. **Notification System**: Users involved in the document or comment thread receive notifications about new comments or replies.

### Describe the benefits this would bring to existing BookStack users

1. **Enhanced Collaboration**: This feature would significantly improve collaborative efforts, allowing team members to discuss and refine specific parts of a document efficiently.
2. **Clear Context**: By linking comments to specific text segments, it provides clear context for feedback, making it easier to understand and act upon.
3. **Streamlined Review Process**: Inline comments streamline the document review process, making it more efficient than having to refer to comments at the end of the document.
4. **Improved Document Quality**: Focused discussions on specific parts of the document can lead to more thorough reviews and, consequently, higher quality content.

### Can the goal of this request already be achieved via other means?

Currently, BookStack only offers a basic commenting feature at the end of the document, which does not allow for specific, contextual feedback on document segments. **Also in case off long documents, you have to scroll to end of page and cannot directly make a comment.**  While users can manually note down their comments and discuss them outside of BookStack, this process is cumbersome and disjointed. There is no integrated way within BookStack to achieve the level of detailed and contextual commenting that this feature request proposes. Implementing this feature would fill a significant gap in BookStack's current functionality.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @asaglam76 but I feel this is already covered by #1265 so I'm therefore going to close this off.

Note that current versions of BookStack do support some level of comment threading and notifications.
