### ISSUE TITLE
Quick save shortcut not working

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#467]
Ctrl+S shortcut not saving draft content in WYSIWYG editor. Markdown editor needs to be checked.

**Comment by domainzero** [comment]
Can verify that it does work in the markdown editor on v17.4 using Chrome 60 and Firefox 45

**Comment by ssddanbrown** [comment]
@domainzero Thanks for confirming. Think I just accidentally remove from WYSIWYG then.
