### ISSUE TITLE
Higllight search result in the location/s and/or positioning the cursor on the searched text

### ISSUE THREAD

**Issue by nicfab** [BookStackApp/BookStack#4670]
### Describe the feature you'd like

After performing any search, the results are shown at the top of the page.
However, by clicking on the result (for example, a page), you go to the specific content, but it's necessary to use the browser search to view the exact query (word/s).
I suggest improving the search feature by positioning the cursor on the exact searched text and highlighting it after clicking on a search result.

### Describe the benefits this would bring to existing BookStack users

The user can Immediately view the searched text.

### Can the goal of this request already be achieved via other means?

Yes, by using the browser search, but it's a waste of time, it's not convenient, and it should be a function of the app anyway.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues, and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Thanks for the request @nicfab but I feel this is already covered by #4263 so I'm going to therefore close this off.
