### ISSUE TITLE
Disable Mail server requirement

### ISSUE THREAD

**Issue by LeaderbotX400** [BookStackApp/BookStack#4671]
### Describe the feature you'd like

I am using authentik to handle the log ins. as such I do not require emails to be sent out when a user logs in, nor do I have a mail server I could give it

### Describe the benefits this would bring to existing BookStack users

Not require more setup then absolutely needed for this one service

### Can the goal of this request already be achieved via other means?

Unkown

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Hi @LeaderbotX400,
There is the [option for sendmail](https://www.bookstackapp.com/docs/admin/email-webhooks/#sendmail) to avoid needing a specific SMTP server, although email delivery may be affected depending on setup.

Otherwise, could you not just avoid using email-based features in BookStack?

**Comment by LeaderbotX400** [comment]
> Hi @LeaderbotX400, There is the [option for sendmail](https://www.bookstackapp.com/docs/admin/email-webhooks/#sendmail) to avoid needing a specific SMTP server, although email delivery may be affected depending on setup.
> 
> Otherwise, could you not just avoid using email-based features in BookStack?

I tried too, and maybe I was doing something wrong. But bookstack would not let me use my authentik provided account without sending a verification email.

**Comment by ssddanbrown** [comment]
@LeaderbotX400 Email confirmation on the BookStack side should only be active if you're using the email confirmation, or domain restriction, option within the BookStack registration settings. Remove the use of both of those options to stop email confirmation from BookStack.

**Comment by LeaderbotX400** [comment]
Ah, it's probably the domain restriction I enabled on bookstack. Thanks
