### ISSUE TITLE
Unique Page or Document ID

### ISSUE THREAD

**Issue by asaglam76** [BookStackApp/BookStack#4675]
### Describe the feature you'd like

When you set a link to a page from n external location to bookstack and than you relocate the page in bookstack to somewhere, than the linkt will Not Work anymore. In case of unique ID, you would always get a result till page is not removed.

### Describe the benefits this would bring to existing BookStack users

Document IDs help you manage your documents by providing an easy way to track items regardless of their location.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @asaglam76,

If you'd like an ID-based link you can follow this guidance from our docs:
https://www.bookstackapp.com/docs/user/content-permalinks/

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up to the suggestion above, I'll go ahead and close this off.
