### ISSUE TITLE
Dan Brown

### ISSUE THREAD

**Issue by ArkansasDev** [BookStackApp/BookStack#4677]
### Describe the Bug

I have a serious issue here, regarding Dan Brown.

Can we as a general public collective give this man more credit...

HOLY **** 

You rock Dan!~

### Steps to Reproduce

1.  Who is Dan Brown
2.  Kick *** Dev
3. Searching for .... 
4.  Thanks

### Expected Behaviour

You rock brother

### Exact BookStack Version

23.9999

**Comment by ArkansasDev** [comment]
❤️ Dan Brown

Thank you again for your support on this OS project

**Comment by ArkansasDev** [comment]
@ssddanbrown this guy is a machine, does anyone else see how flawless he is? **** shout out from [ARK Digital](https://arkansas.dev)

**Comment by ssddanbrown** [comment]
Thanks @ArkansasDev for the kind, flattering comments! It's much appreciated.
