### ISSUE TITLE
Actions --> Copy

### ISSUE THREAD

**Issue by Schaefle** [BookStackApp/BookStack#4679]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Obgleich Rolle für ein Regal und darunter befindlichem Buch für alle auf "nur Anzeigen" erlaubt ist, könnte das Buch kopiert werden und unter dem jeweiligen Username als Kopie nochmal existieren. Das möchte ich gerne abschalten, doch ich weiss nicht wodurch die Existenz des Links "Aktionen->kopieren" bzw. "Actions->copy" beeinflusst, also deaktiviert werden kann damit dieser nicht angezeigt wird.
Nebenbei...lässt sich auch der Punkt "Favoriten" im Usermenü deaktivieren?
Danke schön für Hilfe

### Exact BookStack Version

v23.10

### Hosting Environment

Ubuntu 22.04,PHP 8.1
![aktions](https://github.com/BookStackApp/BookStack/assets/151161914/826f9cc3-aa52-4e62-8606-2859e5498e68)

**Comment by ssddanbrown** [comment]
Hi @Schaefle,
There are no specific in-platform options for disabling the copy or favourite buttons.
The "copy" button will appear if the user has the ability to create pages anywhere else in the system.

If you wanted to hide the actions for just this page, you could likely create a customization using some custom CSS along with ["Tag Classes"](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#tag-classes) (so you could choose to hide actions by applying tags to pages) but it won't disable the action completely, so could be hacked around by enthusiastic users finding the right URLs. That said, they could just copy and paste the page contents into a new page anyway if they really wanted.

If you want an example of such a customization let me know, but it would be considered unofficial/unsupported.

**Comment by Schaefle** [comment]
@ssddanbrown, 
thank you, I understand now....for me no CSS necessary
