### ISSUE TITLE
MD format not completely rendering

### ISSUE THREAD

**Issue by Stump8743** [BookStackApp/BookStack#4683]
### Describe the Bug

A MD page created with code from the following example: https://raw.githubusercontent.com/fullpipe/markdown-test-page/master/test-page.md does not render all elements correctly.

### Steps to Reproduce

1. Get raw code from https://raw.githubusercontent.com/fullpipe/markdown-test-page/master/test-page.md
2. Create a new page with md editor
3. Save and view page

### Expected Behaviour

It should render the md file as shown at https://gist.github.com/rt2zz/e0a1d6ab2682d2c47746950b84c0b6ee

### Browser Details

Firefox 119.0.1

### Exact BookStack Version

v23.10.2

**Comment by ssddanbrown** [comment]
Hi @Stump8743,

I'm not quite sure what's rendering incorrectly.
That input content and example render link are two quite different documents.

Either way, in BookStack we support commonmark plus a few extensions including tables and tasklists. 
Outside of that, there may be indeed differences in supported syntax and behaviour.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up to the above I'll go ahead and close this off.
