### ISSUE TITLE
Update to 23.10.4 after installation-ubuntu-22.04.sh

### ISSUE THREAD

**Issue by Zen-Theo** [BookStackApp/BookStack#4685]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I create a bookstack with the installation-ubuntu-22.04.sh script many month ago. 
Today I need to update my bookstack to the 23.10.4 release but I don't know how. 
I don't have any .git file on my server. 

Any help?

### Exact BookStack Version

23.02.3

### Log Content

.

### Hosting Environment

.

**Comment by ssddanbrown** [comment]
Hi @Zen-Theo,
Please can you explain exactly what you are attempting in the command line, and share the exact output/error you're seeing?

**Comment by Zen-Theo** [comment]
I found solution thanks
