### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by 247no2** [BookStackApp/BookStack#4689]
### Describe the Bug

I have BookStack on v23.02.1, and now I wanted to update to the latest version --> v23.10.3

But certificate problems, what would I have to do to update?

Many thanks in advance. 
Best regards

### Steps to Reproduce

root@bookstack:/var/www/bookstack# git pull origin release
fatal: konnte nicht auf 'https://github.com/BookStackApp/BookStack.git/' zugreifen: server certificate verification failed. CAfile: none CRLfile: none
root@bookstack:/var/www/bookstack# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Notice:  date_default_timezone_set(): Timezone ID 'CEST' is invalid in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 47

   INFO  Discovering packages.

  barryvdh/laravel-dompdf ..................................................................................................................... DONE
  barryvdh/laravel-snappy ..................................................................................................................... DONE
  intervention/image .......................................................................................................................... DONE
  laravel/socialite ........................................................................................................................... DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  socialiteproviders/manager .................................................................................................................. DONE

62 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan cache:clear
PHP Notice:  date_default_timezone_set(): Timezone ID 'CEST' is invalid in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 47

   INFO  Application cache cleared successfully.

> @php artisan view:clear
PHP Notice:  date_default_timezone_set(): Timezone ID 'CEST' is invalid in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 47

   INFO  Compiled views cleared successfully.

root@bookstack:/var/www/bookstack# php artisan migrate
PHP Notice:  date_default_timezone_set(): Timezone ID 'CEST' is invalid in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 47

                                                                                                         APPLICATION IN PRODUCTION.

  Do you really wish to run this command? (yes/no) [no]
❯ yes

   INFO  Nothing to migrate.

root@bookstack:/var/www/bookstack#

### Expected Behaviour

Update to v23.10.3 successfully completed

### Screenshots or Additional Context

![Unbenannt](https://github.com/BookStackApp/BookStack/assets/124701569/b80fe88b-cab3-4018-893d-5c33c7430bc0)

### Exact BookStack Version

BookStack v23.02.1

**Comment by ssddanbrown** [comment]
@247no2 It looks like the HTTPS certs on the host system are out of date so are having trouble validating sites on the web.

Update your system packages and then try again.

**Comment by 247no2** [comment]
Hi Dan, thanks for your quick feedback.
After updating Ubuntu, everything worked fine.

Best regards

**Comment by ssddanbrown** [comment]
Good to hear, I'll therefore close this off.
