### ISSUE TITLE
Adding Serbian Language

### ISSUE THREAD

**Issue by ikrstic** [BookStackApp/BookStack#4690]
### Language to Add

Serbian Latin and Serbian Cyrilic

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by b0c0de** [comment]
I would like to participate as well to help @ikrstic with this intent of translating this into Serbian Latin or Serbian Cyrilic.

**Comment by chris-devel0per** [comment]
Translations for text within BookStack is managed through the [BookStack project on Crowdin](https://crowdin.com/project/bookstack).

So you can edit the translations there. 

See more here: 
https://github.com/BookStackApp/BookStack?tab=readme-ov-file#-translations

**Comment by ikrstic** [comment]
Thanks for the info, I'm aware if the process but the languages are not awailable on the list, thus we are unable to translate.
Request is to add the languages to the list.
Thanks.

**Comment by ssddanbrown** [comment]
Thanks for the offer to translate @ikrstic and @b0c0de.
Forgive my ignorance, I'm not familiar with Serbian at all.

- Which of Serbian Latin and Serbian Cyrilic is preffered?
- Or is it important to have translations for both?
- How closely related are the two in text/written form? (Can one be based on the other or is that unproductive?)

**Comment by ikrstic** [comment]
Hi,
The text would be different only in the way if it being on different
alfabet (Cirillic and Latin) Cirillic being similar to Macedonian,
Bulgarian, Russian... Latin being similar to all English, Croatian,
Slovenian...

These are essentially same content in two alfabets.

But they need to be listed separately.
Serbian Cirillic is the official language of the Republic of Serbia.

**Comment by ssddanbrown** [comment]
@ikrstic Thanks for the input.

> But they need to be listed separately.
> Serbian Cirillic is the official language of the Republic of Serbia.

So would just adding Serbian Cirillic cover your needs? Or do you have an active need to use both and a desire to translate for both language options?
I don't want to add both just because they exist, I only want to add languages that there's an active need for, and an active desire to translate for.

**Comment by ikrstic** [comment]
Hi Dan,

It's perfectly fine with just adding Serbian Cirilic.
Thank you.

**Comment by pavleknezevic** [comment]
Hello everyone,

I'm excited to be a part of the translation effort as well.

While Serbian Cyrillic is suitable for starters, I personally prefer the Serbian Latin script.

I am committed to assisting @ikrstic and @b0c0de with the translation.

**Comment by ssddanbrown** [comment]
Okay I've now Serbian Cyrlillic on Crowidn, and will therefore close this off.
I'll enable as a BookStack langauge option once it's mostly translated.
If a few months goes by without much progress, I may remove the language from Crowdin.

@pavleknezevic If you feel strongly about Serbian Latin, even after experiencing the process a bit for Serbian Cyrillic, and you're confident you'd want to translate for that language, feel free to open a new language request specific for that and I'd add that also at a convenient development point.

**Comment by ikrstic** [comment]
Ok, thanks.

**Comment by b0c0de** [comment]
My apologies. I have had some issues with github that I have finally resolved.
