### ISSUE TITLE
Ending compiling message

### ISSUE THREAD

**Issue by ybtx2957** [BookStackApp/BookStack#4693]
### Describe the Bug

Freezes when closing while compiling

### Steps to Reproduce

When i click x button and it asks me if i want to stop compiling and exit. And i click yes and then the progam just freezes and i have to shut it down from taskbar

### Expected Behaviour

Just not freeze

### Browser Details

Windows 11

### Exact BookStack Version

20.03

**Comment by ssddanbrown** [comment]
Hi @ybtx2957,
Are you sure you've got the right software? There shouldn't be anything to compile for production use, nor is there a windows taskbar icon unless you're reffering to webserver software you're using to run BookStack on.

**Comment by ybtx2957** [comment]
Hi @ssddanbrown ,
I meant while running. When i close then it freezes like this

https://github.com/BookStackApp/BookStack/assets/132209270/0b73d178-365d-43ab-b500-6abde3c6b98b

**Comment by ssddanbrown** [comment]
@ssddanbrown Thanks for the further information. I still have no idea how what you're doing is relevant to this project though.

What has led you to open a message here?

**Comment by ybtx2957** [comment]
@ssddanbrown I think it's a mistake I meant to open it on codeblocks issue. Or is bookstack a part of codeblocks? Anyway thanks for everything.

**Comment by ssddanbrown** [comment]
@ybtx2957 Ah, okay, We're not part of codeblocks in any way. Looks like they have a forum which can be found here:
https://forums.codeblocks.org/

I'll therefore close this off.
