### ISSUE TITLE
Can't get docker compose instance of BookStack running on WSL

### ISSUE THREAD

**Issue by tschilpi** [BookStackApp/BookStack#4696]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hey there,

I am trying to get BookStack running via docker compose. I tried it on windows and then using wsl. When I run it in wsl, as I try to access localhost/6875, I get redirected to the path specified in the yaml file, but https is added, namely https://192.168.1.105/login, and it gives me a connection failure. 

my yaml file and log:

`version: '3.3'
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - APP_URL=http://192.168.1.105
      - DB_HOST=db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstack
    volumes:
      - /path/to/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: bookstackdb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
    restart: unless-stopped

`

any Idea what could be the issue? Thing is, I have no clue how to debug docker containers. I suspect it could be something to do with the https redirection, but I don't know where I could check the docker container's network settings etc.

### Exact BookStack Version

BookStack v23.10.4 

### Log Content

migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done

GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
App Key found - setting variable for seds
Running config - DB_HOST set
Waiting for DB to be available

   INFO  Nothing to migrate.

chown: cannot dereference '/app/www/storage/logs/laravel.log': No such file or directory
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.

### Hosting Environment

WSL 2 with Ubuntu distro

**Comment by ssddanbrown** [comment]
Hi @tschilpi,

Try updating your `APP_URL` to `http://localhost:6875` in your compose file, then re-up the stack to re-create the containers.

Currently you're getting redirected to the `APP_URL`, which is expected, but not sure why it's forcing HTTPS although this could be due to a browser settting, extension or due to history on that IP address (hence my advisory to use localhost since that's at least redirecting you so partially working).

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up on this I'll go ahead and close this issue off.
