### ISSUE TITLE
Some Events are not in Event Filter list

### ISSUE THREAD

**Issue by logicalasia** [BookStackApp/BookStack#4697]
### Describe the Bug

I try to filter "page_create" but i cannot find the selection in your Event Filter List. 

### Steps to Reproduce

1. Go to Setting, Audit Log
2. Click the Event Filter

### Expected Behaviour

There should have page_create, page_delete, page_move, page_update and so on.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/84135001/2ca41fff-224b-4956-bf55-d04233bc07be)

### Browser Details

Chrome

### Exact BookStack Version

BookStack v23.10.1

**Comment by ssddanbrown** [comment]
Hi @logicalasia,
Would the desired event happen to be right at the top of the list?

**Comment by logicalasia** [comment]
my bad... I try to check again from mobile I facing the same issue.
then I go back to Chrome browser and check the coding, all the filter are there. I try to view the page with other zoom ratio and it show up.

Thank you
