### ISSUE TITLE
Translation missing in "Email notification" if somebody update page

### ISSUE THREAD

**Issue by hieste** [BookStackApp/BookStack#4698]
### Describe the Bug

".action_text" is shown...

### Steps to Reproduce

Change Page, wait for Email...

### Expected Behaviour

It should be "Seite anzeigen,." (German)

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/30119314/2560ccd5-1186-447c-bea6-2fc295c0ba77)

### Browser Details

Chrome

### Exact BookStack Version

23.10.4, think every Version has this problem...

**Comment by ssddanbrown** [comment]
Hi @hieste,
Are you sure you're using the latest version?

This was an issue in the text specifically of German translations for older versions, although this should have been addressed from v23.10.
