### ISSUE TITLE
Leave comments on someone elses pages

### ISSUE THREAD

**Issue by Di2g10** [BookStackApp/BookStack#47]
Sometimes i see documentation that may contain errors. I don't want to outwrite change the page but prompt the original submitter to check and correct if neccessary. My initial thought of how to do this is to enable some sort of commenting system that is say only viewable on however when reading but doesn't affect the flow of the document.

**Comment by AbijeetP** [comment]
This is something that I would be interested in too. Inline comments or comments at the bottom of the page, both would be good.

**Comment by bridgeyuwa** [comment]
And these type of comments should be visible only the group of users with edit permission granted to such pages

**Comment by ssddanbrown** [comment]
@bridgeyuwa Could this lead to duplication of comments though? I would have thought visible to all that can view the page

**Comment by bridgeyuwa** [comment]
@ssdanbrown I Was thinking of the comment more like a notification. If its a normal comment its ok to be viewed by all user that have view permission to the page.@ssdanbrown I Was thinking of the comment more like a notification. If its a normal comment its ok to be viewed by all user that have view permission to the page.

**Comment by AbijeetP** [comment]
I think the initial version of this implementation should have the following - 

- [ ] Ability to add comments via WYSIWIG editor
- [ ] Ability to edit own comments via WYSIWIG editor
- [ ] Ability to link directly to a comment in the page
- [ ] Ability to reply to a comment (upto 2 levels?)
- [ ] Ability to your own delete comments
- [ ] Display total comments on the page summary maybe?

We might want to add the following based on popular opinion - 

- Comment change history
- Ability for admin role user to edit others comments
- Ability for admin role user to delete others comments

These can be tackled in the next version of comments - 

- Inline document comments where users can highlight sections of pages and comment on those.
- Like comments

@ssddanbrown - Please let me know what you think, I'll try to take a crack at it.

**Comment by Abijeet** [comment]
I think the initial version of this implementation should have the following - 

- [ ] Ability to add comments via WYSIWIG editor
- [ ] Ability to edit own comments via WYSIWIG editor
- [ ] Ability to link directly to a comment in the page
- [ ] Ability to reply to a comment (upto 2 levels?)
- [ ] Ability to your own delete comments
- [ ] Display total comments on the page summary maybe?

We might want to add the following based on popular opinion - 

- Comment change history
- Ability for admin role user to edit others comments
- Ability for admin role user to delete others comments

These can be tackled in the next version of comments - 

- Inline document comments where users can highlight sections of pages and comment on those.
- Like comments

@ssddanbrown - Please let me know what you think, I'll try to take a crack at it.

**Comment by ssddanbrown** [comment]
Hi @Abijeet, Sorry I didn't come back to you sooner.

Great list. My thoughts are that we should keep things simple to start with, There's no need for a full chat solution within BookStack. Your feature list does cover the simple base features.

I don't think there's any need for full WYSIWYG inputs, We should just keep things simple and maybe spice it up with a little markdown, Much like these GitHub comments.

**Comment by Abijeet** [comment]
I've documented some of the implementation details here - 
https://gist.github.com/Abijeet/ac2e80f473359b2860b8bb6d33f6b541

**Comment by ssddanbrown** [comment]
Hi @AbijeetP, That plan looks great! The only thing I would change, on the database schema, is adding an additional field named `html` so we can store the comment HTML at save time without having to parse the markdown for every comment on every view. Also maybe an `edited` boolean field so we can display if a user has edited their original comment?

**Comment by Abijeet** [comment]
@ssddanbrown - Thanks. I agree with your inputs, I'll update the plan.

**Comment by alagu** [comment]
@AbijeetP Hey Abijeet, great to see the progress in this. Is there a plan to take this to upstream?

**Comment by Abijeet** [comment]
@alagu - Currently working on this. I expect to be done with this by sometime around June 10th.

**Comment by Abijeet** [comment]
An update on this,

Still working on this. Done with most of the stuff and you can check the progress here - https://github.com/BookStackApp/BookStack/pull/261

I'll soon submit the code for review by @ssddanbrown after doing the manual testing. I'm not sure if I can meet the June 10th deadline I'd given earlier. Maybe a couple of weeks more.

**Comment by Abijeet** [comment]
I'm done with the implementation on this. Have updated the merge requests with my comment. You can check the latest here - https://github.com/BookStackApp/BookStack/pull/261

**Comment by ssddanbrown** [comment]
Happy with where this is at now. Implementation now in master, Ready for v0.18 release hopefully tomorrow.
