### ISSUE TITLE
Page Sort Problem

### ISSUE THREAD

**Issue by magritus** [BookStackApp/BookStack#4700]
### Describe the Bug

When I try Sort Book Contents chapters sort working but page sort is not working. 
I saw this bug at 2021 but its still continuing. 

### Steps to Reproduce

1. I go to the book section of the library.
2. I choose the book and go into it.
3. In the area where the sections and pages are located, I click on the sort button on the right.
4. I enter the new order and click save.
5. The system says it saved without any errors.
6. When I check, the order has not changed.

### Expected Behaviour

System Version BookStack v23.10.4 
PHP 8.0.30 (cli) (built: Sep 27 2023 15:11:55) ( NTS )

### Screenshots or Additional Context

I attached video about this bug.
https://github.com/BookStackApp/BookStack/assets/152178678/8ff02164-3a66-4c8e-ab73-5d02b0396345

### Browser Details

Firefox Version 120.0 (64-bit)

### Exact BookStack Version

v23.10.4

**Comment by magritus** [comment]
I checked the pages table in the Mysql database. When I manually change the data of the priority column in this table, the order is adjusted. I think something is going wrong while the system is recording to this table.

**Comment by ssddanbrown** [comment]
Hi @magritus,
Does the user performing the sort have full edit and delete permission for the original content, and the original & target locations?

**Comment by magritus** [comment]
I'm doing while Admin user role already. 
I checked all checkbox user roles and tried, still not sorting.

**Comment by ssddanbrown** [comment]
Okay, thanks for checking.

- Can you remember how you installed BookStack?
- Can you describe the hosting method/environment at all? (Host operating system? Using docker?)

**Comment by magritus** [comment]
I'm using shared hosting so i installed while manual installation. 
I'm using GreenGeeks as hosting provider. 

Linux ams101.greengeeks.net 4.18.0-425.19.2.lve.el7h.x86_64 #1 SMP Thu Apr 6 13:40:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ssddanbrown** [comment]
Do you have control of PHP extension used via your hosting provider? If so, what are the available options for anything related to PHP extensions that mention `mysql`?

**Comment by cracrayol** [comment]
Same problem for me.

Also on shared hosting (planethoster.com)

Using PHP 8.2 with mysqlnd, nd_msqli, pdo and pdo_mysql extensions enabled but don't have access to any settings related to those extentions.

Edit: I've disabled pdo_mysql and enabled nd_pdo_mysql and now it's working.

**Comment by magritus** [comment]
> Do you have control of PHP extension used via your hosting provider? If so, what are the available options for anything related to PHP extensions that mention `mysql`?

<img width="357" alt="image" src="https://github.com/BookStackApp/BookStack/assets/152178678/4fd2c561-87e9-4906-8cf4-e00bc57868a2">

Yes, i have and you can see what i selected contain mysql. 
In additional pdo_mysql also checked.

**Comment by cracrayol** [comment]
> Yes, i have and you can see what i selected contain mysql. In additional pdo_mysql also checked.

Try by replacing pdo_mysql with nd_pdo_mysql. It fixed the problem for me.

**Comment by magritus** [comment]
> > Yes, i have and you can see what i selected contain mysql. In additional pdo_mysql also checked.
> 
> Try by replacing pdo_mysql with nd_pdo_mysql. It fixed the problem for me.

same as you, problem resolved.

**Comment by ssddanbrown** [comment]
Since this was resolved I'll close this off.

**Comment by Mister-M-alt** [comment]
Hi,
Indeed, same problem on my side, the workaround fixed it, thank you!
@ssddanbrown I would like to know if this is possible to add it to the official website, or readme.md, where do you think would make sens?

Thank you for your work again

**Comment by Cidwill** [comment]
I'm experiencing this problem on our bookstack.  Is this resolved in the latest bookstack version or will we need to do the workaround?
