### ISSUE TITLE
Show Page Tags in Book/Chapter View

### ISSUE THREAD

**Issue by derekwelton** [BookStackApp/BookStack#4704]
### Describe the feature you'd like

Currently in the Search Results, It shows the Tags associated with that page like below:

![image](https://github.com/BookStackApp/BookStack/assets/31353783/21b39e7f-e6ec-4087-a6fc-e28b1b3bd752)

But I wish we could see the tags when we have a "Book" view or Chapter opened that showed the tags. Currently it does not:

![image](https://github.com/BookStackApp/BookStack/assets/31353783/01fe4ad9-d55d-4c9f-b05a-a96c99676299)

### Describe the benefits this would bring to existing BookStack users

I believe having tags more available in other views besides Search and viewing the page itself gives the users a better idea on what each page contains without having to go into each page. One method we use tags for is to tag pages that need to be reviewed. Having the ability to go into each Book and see from a glance which pages/chapters have the "need review" tag. 

Another approach to solving my issue is having the ability to filter pages that do not have a specific tag as well. 

### Can the goal of this request already be achieved via other means?

Since the search results view already has this feature implemented, I assume it wouldn't take too much effort to implement this.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Over 5 years

**Comment by Man-in-Black** [comment]
Did you mean something like that?
<img width="810" alt="image" src="https://github.com/BookStackApp/BookStack/assets/9048534/a2dd7578-b466-41b3-88cf-78c5d0e6381f">

**Comment by derekwelton** [comment]
> Did you mean something like that? <img alt="image" width="810" src="https://private-user-images.githubusercontent.com/9048534/287049930-a2dd7578-b466-41b3-88cf-78c5d0e6381f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNzQzMTAsIm5iZiI6MTcwMTM3NDAxMCwicGF0aCI6Ii85MDQ4NTM0LzI4NzA0OTkzMC1hMmRkNzU3OC1iNDY2LTQxYjMtODhjZi03OGM1ZDBlNjM4MWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMTk1MzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNkZTJhNTkzOTUyYTkzYWI5MTdiNDI4YWU3MjgzMTZmYWRhMDJiMjI3NDU1YTc0ODg2ZTU1NmJkNzQ1ZDQyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DX4VVn5VeKZtsUQb5oiFtvF9FcFtgsvidU9s_8WwG84">

Yes, exactly like that. How is that done? I've looked through the settings, is this in the config file to enable?

**Comment by Man-in-Black** [comment]
no, I've done it via the visual theme system by modifying some of the php files of the application.
I can write a little guide tomorrow.

**Comment by Man-in-Black** [comment]
Alright...
For the pages to show the tags (and on top if it is a template or not) you need to edit the `pages/parts/list-item.blade.php` file in your theme folder.
I've changed the file from
```php
@component('entities.list-item-basic', ['entity' => $page])
    <div class="entity-item-snippet">
        <p class="text-muted break-text">{{ $page->getExcerpt() }}</p>
    </div>
@endcomponent
```
to
```php
@component('entities.list-item-basic', ['entity' => $page])
    <div class="entity-item-snippet">
        <p class="text-muted break-text">
            <!-- added for template marking -->
            @if($page->template)
                @icon('template')
            @endif
            <!-- end template marking -->
            {{ $page->getExcerpt() }}
            <!-- show tags -->
            @if($page->tags->count() > 0)
                @foreach($page->tags as $tag)
                    @include('entities.tag-page-list', ['tag' => $tag])
                @endforeach
            @endif
            <!-- end show tags -->
        </p>
    </div>
@endcomponent
```
so you get the view as shown above and on top templates are marked with a template symbol like this:
<img width="450" alt="image" src="https://github.com/BookStackApp/BookStack/assets/9048534/a4d4c7ae-9d5c-410d-8099-109af0df7b1c">

**Comment by derekwelton** [comment]
> Alright... For the pages to show the tags (and on top if it is a template or not) you need to edit the `pages/parts/list-item.blade.php` file in your theme folder. I've changed the file from
> 
> ```
> @component('entities.list-item-basic', ['entity' => $page])
>     <div class="entity-item-snippet">
>         <p class="text-muted break-text">{{ $page->getExcerpt() }}</p>
>     </div>
> @endcomponent
> ```
> 
> to
> 
> ```
> @component('entities.list-item-basic', ['entity' => $page])
>     <div class="entity-item-snippet">
>         <p class="text-muted break-text">
>             
>             @if($page->template)
>                 @icon('template')
>             @endif
>             
>             {{ $page->getExcerpt() }}
>             
>             @if($page->tags->count() > 0)
>                 @foreach($page->tags as $tag)
>                     @include('entities.tag-page-list', ['tag' => $tag])
>                 @endforeach
>             @endif
>             
>         </p>
>     </div>
> @endcomponent
> ```
> 
> so you get the view as shown above and on top templates are marked with a template symbol like this: <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/9048534/287458353-a4d4c7ae-9d5c-410d-8099-109af0df7b1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTQ2MjcsIm5iZiI6MTcwMTcxNDMyNywicGF0aCI6Ii85MDQ4NTM0LzI4NzQ1ODM1My1hNGQ0YzdhZS05ZDVjLTQxMGQtODA5OS0xMDlhZjBkZjdiMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTgyNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFkMzJhYzA3MzUyNjM4MDQxYjkzMWI5ODMzNGMwNDk4OTMyYmY5MjcxYzY5ZjkyMjlmYjg1MzM4MTA2YzUyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q7OGr2GOp4v_DwSnblo_Z8li2p5Gp0UVNGjNvDxo5Vg">

Excellent example. Thank you for taking the time to share it. Works as expected. Thanks again!

**Comment by Man-in-Black** [comment]
I'm happy if I could help you with this little tweak ;-)

**Comment by ssddanbrown** [comment]
Thanks @Man-in-Black for helping provide a workaround here.
Since this has been solved via a workaround, and since I'm not keen to expand tags into this view, I'm going to close this off.
There's #4536 which would additionally help the original request via the alternative option of searching for content without specific tags.

**Comment by GuillaumeV-cemea** [comment]
Hi,

I'm running v24.02.2, but your workaround was not working, I had the following error in laravel.log : `[previous exception] [object] (InvalidArgumentException(code: 0): View [entities.tag-page-list] not found. at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)`

I updated it to the following and it now works : 
```
@component('entities.list-item-basic', ['entity' => $page])
    <div class="entity-item-snippet">
        <p class="text-muted break-text">
            <!-- added for template marking -->
            @if($page->template)
                @icon('template')
            @endif
            <!-- end template marking -->
            {{ $page->getExcerpt() }}
            <!-- show tags -->
            @if($page->tags->count() > 0)
	    <div class="entity-item-tags mt-xs">
		@include('entities.tag-list', ['entity' => $page, 'linked' => false ])
	    </div>
            @endif
            <!-- end show tags -->
        </p>
    </div>
@endcomponent
```

**Comment by nesges** [comment]
This helped me solve an issue, thanks! I'm curious: is it possible to extend this to display a clickable tagcloud/sorted list of unique tags above the list of pages in a book?
