### ISSUE TITLE
Set Notfication for Roles

### ISSUE THREAD

**Issue by hieste** [BookStackApp/BookStack#4709]
### Describe the feature you'd like

Hello Dan,
I would like to have a function with which I can activate the watch function for a group (role). This would allow me as the owner of an entry to determine who receives an email. Now every user has to activate the function.

### Describe the benefits this would bring to existing BookStack users

Centrally determine who should monitor an entry, book or chapter.

### Can the goal of this request already be achieved via other means?

Think no. Write an email to the users, which entry, book or chapter should be watched.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request but I feel the fundamental desire is already covered by #4514 so I'm therefore going to close this off.

It may also be worth view the [unsupported hack here](https://www.bookstackapp.com/hacks/notify-tagged-page-updates/) which can enable this kind of functionality. You may be able to use and/or adapt that to your needs to work in existing version of BookStack.
