### ISSUE TITLE
activate more than one "logical theme"

### ISSUE THREAD

**Issue by meikestone** [BookStackApp/BookStack#4711]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I like the use more than one logical theme. How is it possible to activate them in the .env - file? It seems, that via the APP_THEME variable only one can be activated?!
I've created the folders  under bookstack/themes/theme_name/ and inside, the function.php
Every theme well on its own (if activated via  APP_THEME), but how to activate two or more logical themes at the same time?

### Exact BookStack Version

v23.10.2

### Hosting Environment

debian 12

**Comment by ssddanbrown** [comment]
Hi @meikestone,

>  It seems, that via the APP_THEME variable only one can be activated?!

Yeah, that's correct, only one theme folder can be active at a time.
Currently you'd need to merge the files together where desired, or get more inventive and attempt to load other folders/files from your main theme (again, no official methods provided for this).

**Comment by meikestone** [comment]
Ok, thanks for fast answer .. 
Then I'll investigate this a little further!
