### ISSUE TITLE
Temporary Links

### ISSUE THREAD

**Issue by chdcomputers** [BookStackApp/BookStack#4712]
### Describe the feature you'd like

A temporary link should be a record in a special table in the db with a global unique id, a target which will be an existing shelf, book, chapter or page, an optional description and a valid until date time.

For example:
GUID00001 - docs.example.com/books/book1/page/page1 - Offer for app developing to customer1 - 2023/12/31 00:00:00

When any NOT logged in user visits the link **docs.example.com/GUID00001** before 2023/12/31 00:00:00 should be re-directed to **docs.example.com/books/book1/page/page1**

Normally the shelf, book, chapter or page that will be used as a temporary link target will not have the view permission for the public user since we do not want it to be viewable by everyone who visits the site but rather only by the visitors who have the temporary link to it. So the security system should take that into account.

In addition to the above the temporary link visits should be audited and perhaps can trigger a webhook in order to have information on when and how many times they have been used by the visitors. Moreover, the admin should have the ability to delete or modify any temporary link.

Thank you for this great project and, of course, for your time.

### Describe the benefits this would bring to existing BookStack users

In our use case we have some books with procedures and product information that we use when we are making offers to our clients. We don't want them to be public for everyone to see, however we want them to be visible (for a limited time) by those clients that got an offer from us. Since we are talking about tens or hundred clients, creating user accounts for each one of them and provide them the login details just to see this content isn't practical. With the temporary links approach we can share the temporary link with the client so they can view it (without logging in) for the time span that the offer is valid.

### Can the goal of this request already be achieved via other means?

I don't think so

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Thanks for your request @chdcomputers, although I'm going to close this off since I feel the fundamental request is already covered by #288.

**Comment by chdcomputers** [comment]
Hi @ssddanbrown ,
Thank you for your prompt reply.
I saw #288 before adding this and on the fundamentals (sharing) it is similar so I am going to comment over there about the specifics of my idea...
