### ISSUE TITLE
Embedded Visio document are not visible when edit page

### ISSUE THREAD

**Issue by mfrattale** [BookStackApp/BookStack#4717]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,
We have Visio documents embedded in the bookstack pages. When we view the page we see the Vision document correctly. When we open the page to edit it, the Visio document disappears and if we save the page we lose the document. Visio documents are stored on Sharepoint. 

What can we verify? 

Thank you for support. 

Regards
Matteo

### Exact BookStack Version

v23.06.2. 

### Log Content

We don't have error on the screen

### Hosting Environment

It's hosted in a cloud provider and It's deployed on Kubernetes. There isn't proxy from outside.

**Comment by ssddanbrown** [comment]
Hi @mfrattale, How are the Visio documents being embedded onto the page? What does the process and/or embed code look like?

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll close this off.

**Comment by mfrattale** [comment]
Hi @ssddanbrown, 
I really apologize for the delay, I hope it's not too late to reply :-)

Visio documents are embedded using an iframe. Below is an example:

`<iframe src="https://sharepoint.com/sites/MyDocument/_layouts/15/Doc.aspx?sourcedoc=%111111-22222-33333%7D&amp;action=embedview" width="800px" height="600px" frameborder="0">Documento di <a target="_blank" href="https://office.com">Microsoft Office</a> incorporato, con tecnologia <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>`

Thanks,

Regards
Matteo

**Comment by ssddanbrown** [comment]
Okay, so a fairly standard iframe.
Should work, although you'd need to configure the iframe source to be allowed if not already done otherwise BookStack will block it via browser-level controls:

https://www.bookstackapp.com/docs/admin/security/#iframe-src-control

**Comment by mfrattale** [comment]
Hi @ssddanbrown,
I did some tests and I fixed the problem deleting this string:
`Documento di <a target="_blank" href="https://office.com">Microsoft Office</a> incorporato, con tecnologia <a target="_blank" href="https://office.com/webapps">Office</a>.`

Now it works fine! 
Thanks a lot for the support.

Regards

**Comment by ssddanbrown** [comment]
Good to hear you got things working!
I'll therefore close this off.
