### ISSUE TITLE
SAML External Auth ID for Role mapping with "Spaces"

### ISSUE THREAD

**Issue by holzi1005** [BookStackApp/BookStack#4718]
### Describe the Bug

I setup the external Auth with SAML and the group mapping as bescribed in the docs.
Some of the external users groups (keycloak and LDAP Sync) have "Spaces in the name (e.g. /group abc)
When the groups don not have a Space in the name, the External Auth Mapping works but if a Spaces is in the name, the mapping does not work and the users are not assined to the role

### Steps to Reproduce

Some of the external users groups (keycloak and LDAP Sync) have "Spaces in the name (e.g. /group abc)
When the groups don not have a Space in the name, the External Auth Mapping works but if a Spaces is in the name, the mapping does not work and the users are not assined to the role

### Expected Behaviour

I can create an External Group /Role Mapping with External-Auth-IDs with Spaces

### Exact BookStack Version

latest

**Comment by ssddanbrown** [comment]
Hi @holzi1005,
You should be able to map to those groups using hypens instead.
So a SAML group name of "Chuckle Brothers" could be mapped to a BookStack role via an "External Authentication Ids" values of "chuckle-brothers". If that's not working for you, let me know the details of what names is being mapped, and the external auth value used, and I'll dig deeper if needed.

**Comment by holzi1005** [comment]
Hi @ssddanbrown 

thank you for the answer.
I was able to map the external id from keycloak with out the "" only by exchanging the spaces with - and all in lower cases.
