### ISSUE TITLE
[QUESTION] Create a page without a book

### ISSUE THREAD

**Issue by noxify** [BookStackApp/BookStack#472]
Hi,

i would ask if it's possible to use BookStack as something like a "Tutorial Management System".

My use case is the following:

1. User can create a single tutorial / article
2. User can create a serie, which includes X episodes

Point 2 is possible with more as expected (because, the user can now decide between Books -> Pages or Books -> Chapters -> Pages)

But how can I create a tutorial / article without creating a book.

Thanks!

Greets
Marcus

Btw. If i'm not wrong, there was already an issue about the page creation without a book but I wasn't able to find it.

**Comment by bridgeyuwa** [comment]
Nice Suggestion.. have been looking forward to start a tutorial website.. bookstack is the best of all for me but lacks this feature..  I would like to add also that the front page can be customized to look like a directory or a regular website frontpage

**Comment by noxify** [comment]
You can customize the frontpage.

Just create your own controller with a view, then change the route for the frontpage ;)

This is how I did it :)

Or if you're a lazy guy, modify the existing frontpage view ;)

**Comment by ssddanbrown** [comment]
Just want to re-iterate for less technical viewers that modifying BookStack code can cause loss of changes or general issues when updating.

**Comment by sirup** [comment]
@noxify - Could you elaborate a little bit which files need to be edited? Where can I find the existing frontpage view?
Thank you!

**Comment by AbijeetP** [comment]
@sirup - https://github.com/BookStackApp/BookStack/issues/372#issuecomment-325445979

This already allows you to add a custom home page, might want to wait for it to land. 

Using this you can create a page that has browsable links or whatever else you'd like to have.

**Comment by noxify** [comment]
I agree with abijeetP. 
It makes more sense to wait for the next release, because the new feature allows us to create a frontpage/homepage with Bookstack.

My temporary workaround was a static view which was called from a controller (including overwriting the existing routes).

**Comment by ssddanbrown** [comment]
I'm going to close this off since this is relatively old now and many new features have since been release. The core request of creating a page outside of a book is not something I'd be looking to implement for BookStack.
