### ISSUE TITLE
An unknown error occurred - When saving changes

### ISSUE THREAD

**Issue by TheSteveBennett** [BookStackApp/BookStack#4723]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When saving any changes to a page, after pressing save, users receive an error message, "An unknown error occurred" and are left with the option to return home.  Changes have been saved and if user goes back to page and makes another edit the change is saved with no error.

### Exact BookStack Version

v23.10.4

### Hosting Environment

PHP 8.2 - RHEL 8.6 running apache

**Comment by ssddanbrown** [comment]
Hi @TheSteveBennett,
Please see our debugging page to learn how to gain more information about such an error from the logs or debug view:
https://www.bookstackapp.com/docs/admin/debugging/

Common issues are missing PHP extensions, unconfigured mail or filesystem permissions; but getting extra detail as per the above should provide some much more direct pointers to the actual issue/cause.

**Comment by TheSteveBennett** [comment]
**HTTPD Log** - [Mon Dec 11 11:21:48.554533 2023] [ssl:warn] [pid 29551:tid 139962192087360] AH0   1909: bookstack.cravencounty.com:443:0 server certificate does NOT include an ID which matches the server name

I am attaching the Laravel.log
[laravel.log](https://github.com/BookStackApp/BookStack/files/13650425/laravel.log)

The errors occured after upgrading from v23.06.2 to v23.10.

**Comment by ssddanbrown** [comment]
Based upon the errors in that log, you're missing some required database tables.
Did you perhaps upgrade, and forget to run the `php artisan migrate` update step?
Or did that step perhaps error?

**Comment by TheSteveBennett** [comment]
This is from the Debugging view and attached is the stack trace
[stack_trace.txt](https://github.com/BookStackApp/BookStack/files/13650590/stack_trace.txt)


Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstackdb.watches' doesn't exist (SQL: select `level`, `watchable_id`, `watchable_type`, `user_id` from `watches` where ((`watchable_type` = page and `watchable_id` = 185) or (`watchable_type` = book and `watchable_id` = 32) or (`watchable_type` = chapter and `watchable_id` = 67)))

**Comment by TheSteveBennett** [comment]
> Based upon the errors in that log, you're missing some required database tables. Did you perhaps upgrade, and forget to run the `php artisan migrate` update step? Or did that step perhaps error?

I don't remember seeing any errors.  I did have problems with the original pull but was able to work though those.  Can I re-run the "php artisan migrate" step?

**Comment by ssddanbrown** [comment]
> Can I re-run the "php artisan migrate" step?

Yeah, just be sure to record any errors you get on first-run, since errors on subsequent runs can be different.

**Comment by TheSteveBennett** [comment]
That resolved the problem.  Thanks for your patience with the "new guy".

**Comment by ssddanbrown** [comment]
Good to hear that resolved it, no worries, happy I could help!
