### ISSUE TITLE
Follow Page Bug When Page is Moved to Non-Followed Book

### ISSUE THREAD

**Issue by mschoon85** [BookStackApp/BookStack#4724]
### Describe the Bug

Hi @ssddanbrown ,

I might have found a bug. Through the API, I imported a DOCX document into Book A, which I am following, and I receive emails whenever there are changes within the book. Later, I moved the page to another book, let's call it Book B, which I am not following. Surprisingly, I received an email notification when someone made a change to that page, even though it's now in a book I'm not following. In the screenshot below, you can see the details on the page itself. It appears that I am not following it (apologies for the Dutch language), as the "follow" button (volg) is available, and the top details do not indicate that I am following the page.

![image](https://github.com/BookStackApp/BookStack/assets/96066244/84659275-df25-4d54-9e68-7763b0457f55)

Kind regards,

Michel

### Steps to Reproduce

1. Enable Notifications for Target Book: Ensure you are following the book where you intend to upload the document. Verify that email notifications are properly configured (e.g., SMTP settings).

2. Upload Document via API: Upload a DOCX document to this book through the API. Note: The issue might also arise when creating a new page manually, but this has not been tested yet.

3. Select a Non-Followed Book: Identify a book that you are not currently following and transfer the page to this book.

4. Test Notification Trigger: Modify the page within the book you're not following. Observe if you receive an email notification regarding this change, which will indicate whether the issue persists.

### Expected Behaviour

I would anticipate not receiving an email notification, as the page has been moved to a book that I am not following. Furthermore, the page's details themselves indicate that I am not following it, reinforcing this expectation.

### Browser Details

MS Edge

### Exact BookStack Version

23.10.4

**Comment by ssddanbrown** [comment]
Hi @mschoon85,
Could you also confirm the notification settings you have in "My account" > "Notification Preferences". Just want to check that these are not the cause.

**Comment by mschoon85** [comment]
@ssddanbrown 

![image](https://github.com/BookStackApp/BookStack/assets/96066244/c9f4af6c-07fc-411f-8c7a-c0c717883934)

It appears that I am currently following only one book, which is 'Book A' as mentioned in my problem description. 'Book B', on the other hand, is not listed on this page.

**Comment by mschoon85** [comment]
Ah, I've just noticed that these settings are configured to notify me about pages that I own. This could be the reason behind the issue.

**Comment by mschoon85** [comment]
I've manually updated the owner through the permissions settings, so I don't expect to receive any more emails regarding this issue.

**Comment by ssddanbrown** [comment]
Yeah, if you're the owner that you're getting notifications due to that general notification preference.

**Comment by mschoon85** [comment]
Thank you! We can now close the ticket as it's not a bug.
