### ISSUE TITLE
Add Edit-link to Application Homepage if it is a "Specific page"

### ISSUE THREAD

**Issue by chrisrueger** [BookStackApp/BookStack#4735]
### Describe the feature you'd like

Under **Settings / Customization / Application Homepage** you can select "Specific Page" to select an existing page.

Problem:
The homepage showing this "Specific page" does not have a sidebar with the Edit-Page link.

Wish:
Also the homepage should have a shortcut Edit page link if it is a specific page.

The homepage is our intranet main page I change that quite often to e.g. add news or important information to the top. 

### Describe the benefits this would bring to existing BookStack users

Faster editing workflow for Homepage content. 

### Can the goal of this request already be achieved via other means?

You have to go to this actual page to see the edit link. But this requires a search, or a browser bookmark. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

### Additional context

<img width="1359" alt="image" src="https://github.com/BookStackApp/BookStack/assets/188422/a9905714-c5c2-404e-9868-02256d991c0c">

**Comment by stvogel** [comment]
I helped myself with putting a linked text-line saying "edit" on the top of the page, but this not really convenient

**Comment by chrisrueger** [comment]
> I helped myself with putting a linked text-line saying "edit" on the top of the page, but this not really convenient

I think this workaround works for me as well. Closing this issue now. If it gets picked up in the future great, but if not, no problem :)
