### ISSUE TITLE
Special characters(°ýá...) display as garbage

### ISSUE THREAD

**Issue by C0rn3j** [BookStackApp/BookStack#4742]
### Describe the Bug

Possibly related to https://github.com/BookStackApp/BookStack/issues/4701

```php
mariadb 11.2.2-1
bookstack 23.10.4-1
nginx 1.24.0-3
php-fpm 8.2.14-1
libxml2 2.12.3-1
chromium 120.0.6099.129-1
```

### Steps to Reproduce

1. Try saving an article with the word Bábovka in it
2. Saves fine, but result is garbled when viewed

### Expected Behaviour

Result is not garbled

### Screenshots or Additional Context

https://rys.pw/books/recipes/page/recipes#bkmrk-fudgy-brownies

![image](https://github.com/BookStackApp/BookStack/assets/1641362/6861b970-ed7e-434c-b72e-57be35a0c3b6)

![image](https://github.com/BookStackApp/BookStack/assets/1641362/555da450-7c59-429b-bdb7-7f28e7fc8d53)

### Browser Details

chromium 120.0.6099.129-1

### Exact BookStack Version

23.10.4

**Comment by ssddanbrown** [comment]
Okay, I got BookStack installed via your AUR package for further testing, via php-fpm and nginx.
It worked fine without the encoding issue.

Downgrading the packages via a `/etc/pacman.d/mirrorlist` of:

```
#Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
Server=https://archive.archlinux.org/repos/2023/12/05/$repo/os/$arch
```

Would then cause the issue to re-show.
Resetting that back to current would then stop the issue.
Note: I did notice you'd have to restart the `php-fpm` service inbetween package changes for it to pick-up changes to the installed libxml version.

**Comment by C0rn3j** [comment]
I tried downgrading all the way to 2023-11-14 and rebooting -  that did not help, so unless the issue is hard to get rid of after it occurs once, it probably is not related to the other linked issue. 

```php
# pacman -Q mariadb bookstack nginx php-fpm libxml2
mariadb 11.1.2-1
bookstack 23.10.4-1
nginx 1.24.0-3
php-fpm 8.2.12-1
libxml2 2.11.5-1
```

I've no clue what else to try at this point

**Comment by ssddanbrown** [comment]
I'm not too sure at this point either, especially as this is working on my replication machine, and others report it to work fine in a similar environment post libxml downgrade.

My arch install was fairly basic, I think using the archinstall script.
The only other thing I can think of is that I maybe had been playing with locales before finding the specific cause.
My current `locale -a` output in that environment:

```
[root@bsarchtest ~]# locale -a
C
C.utf8
en_GB.utf8
es_ES.utf8
fr_FR.utf8
POSIX
```

**Comment by C0rn3j** [comment]
systemd has a nicer tool(in my opinion) for this.
```bash
# localectl list-locales
C.UTF-8
en_GB.UTF-8
en_US.UTF-8

# locale -a
C
C.utf8
POSIX
en_GB.utf8
en_US.utf8
```

Completely irrelevant to the issue, but just a side note that Arch suggests you to enable `en_US.UTF-8` as some applications can be hardcoded for it (namely Steam/Valve games for one).

I found out that the page looks fine in the editor AND in the rendered editor preview.

What I apparently haven't tried previously is just simply opening and (re)saving the page, as that has now fixed my issue.
