### ISSUE TITLE
Add Serbian language

### ISSUE THREAD

**Issue by pavleknezevic** [BookStackApp/BookStack#4743]
### Language to Add

Serbian

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Thanks for the to translate @pavleknezevic.
This is already requested under issue #4690, so I'm going to close this off.
I'd appreciate your input to [my comment there](https://github.com/BookStackApp/BookStack/issues/4690#issuecomment-1893676441) in regard to language options.
