### ISSUE TITLE
Force watch users on a document and add functionality for users to confirm they have read said document

### ISSUE THREAD

**Issue by Foosec** [BookStackApp/BookStack#4745]
### Describe the feature you'd like

When using the wiki to write documents, guidelines, procedures etc.. 
It would be useful to be able to automatically subscribe users to receive watch notifications on a document,
and have a mechanism for those users to confirm that they have indeed read the document.

### Describe the benefits this would bring to existing BookStack users

It would allow bookstack to be used for certain business procedures that require everyone to be up to date with
certain documents. 
A common example might be ISO certifications, employee work safety guidelines etc.. 

### Can the goal of this request already be achieved via other means?

Not within bookstack

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the suggestions @Foosec, although these topics have been discussed before.

- For watching see #4676 and #4514.
- For read-confirming, see #3736, #3609 and #2835.

Since these points have been discussed before and/or are already covered by existing issues, I'm going to go ahead and close this one off.

**Comment by Foosec** [comment]
Thank you for the prompt response, i only checked opened issues, my apologies.  (Though aparently missed #4514)

**Comment by Foosec** [comment]
I've read through the closed issues and whilst i can't speak on behalf of most users, 
it doesn't seem like a business use case is that out of the norm. 
For technical documentation related to projects or developers its very often other already existing projects that are less normal user friendly (but more developer friendly) that are used!

Now of course i completely understand if you or any other maintainer does not really want to implement this, but would you be against me making a PR and hopefully we can get a design implemented that isn't even noticed by default?

Im just really trying to avoid being forced into <insert microsoft solution>.

**Comment by ssddanbrown** [comment]
> but would you be against me making a PR and hopefully we can get a design implemented that isn't even noticed by default?

A PR wouldn't really help from my point of view, as it's likely a matter of scope and maintenance rather than implementation effort.
