### ISSUE TITLE
Update cover image wording to make sizing in usage clearer

### ISSUE THREAD

**Issue by steven-loscheider** [BookStackApp/BookStack#4748]
### Describe the Bug

The cover images for shelves and books are not consistent. The Edit menu suggests : "This image should be approx 440x250px."

Images are cut off or have the wrong aspect ratio when uploaded. The corporate branded images I have used with exactly 440x250 px are cut off or have different aspect ratio than the original file. So it is difficult to create a coherent look.

### Steps to Reproduce

Edit a shelf or book and add a cover image with the recommended size of 440x250px. If you refresh the shelf or book page, the image will not be displayed correctly as you created it.

### Expected Behaviour

Image will be used 1:1 as uploaded. 
Required aspect ratio and image resolution are defined in the edit menu before uploading
The original image will be used on all subsequent pages

Example to illustrate (with a realistic 250x150px image size):
 
- Image requirements in the edit menu indicate 250x150 px image to be uploaded.
- User generates and uploads 250x150 px image to bookstack.
- Original image will be used on all subsequent pages. No cutting, stretching or resizing is performed.
- Image looks as intended on all pages. 

### Browser Details

Firefox 120.0.1

### Exact BookStack Version

23.10.4

**Comment by ssddanbrown** [comment]
Hi @steven-loscheider,
The mentioned size is really just a rough guide for something of sensible size.
At no point do we promise or indicate the image will be used as per its exact original size, nor would I want to indicate/promise/support that really, since the size and aspect ratio of the area the image is used for will change in a flexible manner depending on a number of factors so suit the design.

**Comment by szabeszg** [comment]
I recommend changing the wording so that it more accurately aligns with the intended concept. Something like:
"The recommended image size is approximately 440x250 pixels. It is advisable to test beforehand to determine what suits you best."

**Comment by steven-loscheider** [comment]
Hi @ssddanbrown 
I see. Maybe change the wording on the edit page as @szabeszg suggested to avoid any confusion. In the meantime I will rework the graphics and add some margin to make them appear properly even if they get cut off here or there.

**Comment by ssddanbrown** [comment]
Thanks for the input.
I've now updated the wording in 16327cf40cbc98d549a222d48c844eb8b3bc7bdc, to better hint about the flexibility of the dimensions in use. This will be part of the next feature release.

**Comment by Saturo78** [comment]
> Thanks for the input. I've now updated the wording in [16327cf](https://github.com/BookStackApp/BookStack/commit/16327cf40cbc98d549a222d48c844eb8b3bc7bdc), to better hint about the flexibility of the dimensions in use. This will be part of the next feature release.

Hi, sorry if this is a silly question, but I just can’t figure it out.
No matter how I resize my book cover image, parts of it (like the heads of people) keep getting cropped.
Could someone please tell me what exact size or aspect ratio the cover image should have so that it’s displayed fully in BookStack?
Thank you very much for your help!

**Comment by ssddanbrown** [comment]
@Saturo78 There is no fixed size, it's dynamic based on display options and screen dimensions.
You'd need to add custom CSS to fix sizes where desired to specific sizes/ratios.

**Comment by Saturo78** [comment]
I want to use this picture as a book cover: Size 440 x 250

<img width="330" height="189" alt="Image" src="https://github.com/user-attachments/assets/235a5533-161c-47a4-bdfc-c3418a1b900c" />

No matter what size I set, I always get this result:

<img width="338" height="144" alt="Image" src="https://github.com/user-attachments/assets/2b17c708-a1be-4bf2-9965-97dc0178c79b" />

**Comment by Saturo78** [comment]
Can someone give me advice on how to use custom CSS to display the full image as a book cover? Thanks in advance!

**Comment by Saturo78** [comment]
Finally this worked for me:

```

<style>
    /* --- GRID / FEATURED VIEW --- */
    .featured-image-container {
        /* 1. Das Abschneiden verhindern */
        background-size: cover !important; 
        background-repeat: no-repeat !important;
        background-position: center !important;

        /* 2. Den Container auf dein 440x250 Format zwingen */
        /* Berechnung: (250 / 440) * 100 = 56.81% */
        height: 0 !important;
        padding-bottom: 56.81% !important; 
        width: 100% !important;
        
        /* 3. Eventuelle Standard-Begrenzungen aufheben */
        min-height: 0 !important;
        max-height: none !important;
    }

    /* Korrektur für die Grid-Karten, damit sie nicht zu hoch werden */
    .grid-card {
        height: auto !important;
    }

    /* --- LIST VIEW --- */
    .entity-list-item-image {
        /* Hier nutzen wir 'contain', damit das Vorschaubild links sauber aussieht */
        background-size: contain !important;
        background-repeat: no-repeat !important;
        background-position: center !important;
        background-color: transparent !important;
        
        /* Feste Größe für die Liste (proportional zu 440x250) */
        width: 120px !important;
        height: 68px !important;
        flex-shrink: 0 !important;
    }
</style>
```

**Comment by PatRiot1337** [comment]
@Saturo78 
How did you make it and where did you install?

**Comment by dynahpointch** [comment]
Settings > Customization > Custom HTML Head Content

Fixed an issue where list items without cover images displayed a blank white square instead of the default BookStack category color.

```
<style>
	/* --- GRID / FEATURED VIEW --- */
	/* Gilt nur, wenn ein echtes Bild (und kein transparenter Platzhalter) existiert */
	.featured-image-container[style*="background-image"]:not([style*="data:image"]) {
		background-size: cover !important; 
		background-repeat: no-repeat !important;
		background-position: center !important;
		height: 0 !important;
		padding-bottom: 56.81% !important; 
		width: 100% !important;
		min-height: 0 !important;
		max-height: none !important;
	}

	/* Verhindert zu hohe Kacheln im Gitter */
	.grid-card {
		height: auto !important;
	}


	/* --- LIST VIEW --- */
	/* Ändert die Listenansicht NUR, wenn ein echtes, hochgeladenes Bild existiert */
	.entity-list-item-image[style*="background-image"]:not([style*="data:image"]) {
		background-size: contain !important;
		background-repeat: no-repeat !important;
		background-position: center !important;
		background-color: transparent !important;
		width: 120px !important;
		height: 68px !important;
		flex-shrink: 0 !important;
	}

	/* Verhindert, dass das SVG-Icon bei echten Bildern das Cover überlagert */
	.entity-list-item-image[style*="background-image"]:not([style*="data:image"]) svg {
		display: none !important;
	}
</style>
```

**Comment by PatRiot1337** [comment]
Ich danke dir herzlich! ;))
