### ISSUE TITLE
[FEATURE REQUEST] Define names for each route

### ISSUE THREAD

**Issue by noxify** [BookStackApp/BookStack#475]
Currently the routes are defined like this:

```
Route::group(['prefix' => 'books'], function () {
        Route::get('/', 'BookController@index');
});
```

And inside the views, we have it defined like this:

```
<a href="{{ baseUrl("/books/") }}">
```

If I change the prefix to something else, each defined link shows an 404 error.

If we're changing it to:

```
Route::group(['prefix' => 'books'], function () {
        Route::get('/', 'BookController@index')->name('books.index');
});
```

We can use inside the view:

```
<a href="{{ route("books.index") }}">
```

This allows us, to change the url prefix to whatever we want.

**Comment by noxify** [comment]
For the AJAX urls, we can use https://github.com/tightenco/ziggy or something else.

**Comment by ssddanbrown** [comment]
If I'm honest I'd prefer to not use named routes as it adds another layer of abstraction when looking at the code.

In addition we'd need to override the default `name -> URL` resolving to work for BookStack instances placed on non root domains.

**Comment by ssddanbrown** [comment]
Closing as the fundamental goal of this is open under #406, This is more of an implementation detail of that request.
