### ISSUE TITLE
filesystem permissions on docker installation

### ISSUE THREAD

**Issue by ap2de** [BookStackApp/BookStack#4753]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am currently inspecting the filesystem permissions on my docker installation.
I am clear about the instructions here: https://www.bookstackapp.com/docs/admin/filesystem-permissions/, but they conver only a part of the folders created by docker.
Could you advise me on the filesystem permissions I need to set on the other folders created by docker?

### Exact BookStack Version

v23.10.4

### Hosting Environment

docker using portainer on synology nas.
image: image: lscr.io/linuxserver/bookstack
path: /volume1/docker/bookstack/config/*

subfolders (that were created by docker): 
backups
keys
log
nginx
php
www

plus files (that were created by docker)
.migrations
BOOKSTACK_APP_KEY.txt

**Comment by ssddanbrown** [comment]
Hi @ap2de,
With a solution like a docker container the permission requirements can often be handled differently.
If I remember correctly, I believe the linuxserver container manages its own permissions.
The "User / Group Identifiers" part of the [linuxserver docker readme](https://github.com/linuxserver/docker-bookstack/tree/master#user--group-identifiers) has some extra info on permissions.

**Comment by ap2de** [comment]
Hi @ssddanbrown,
thank you for the hint, I overlook that information :-(.
