### ISSUE TITLE
problem with thumbnail creation

### ISSUE THREAD

**Issue by ap2de** [BookStackApp/BookStack#4754]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am uploading images to bookstack.
With some images I receive errors:

Failed to handle image upload and/or create thumbnails due to system recource limits.

The image is uploaded correcty, but no thumbnails are shown. When I get into the gallery, i recive the error message:
Failed to create gallery thumbnails due to system resource limits.

Whe I try to re- create the thumbnail for an image, I receive the error message:
Failed to create image size variations due to system resource limits.

In tghe php.ini I have the following values:
upload_max_filesize = 1024M
post_max_size = 1024M

As far as i see the file size is not the problem, as the files are much smaller (e.g. 2.2 MB). For me it seems to be more the problem of resolution (5840x4140). But this is only guessing.
Could you advise me wghat setting I need to change in order to avoid this error message?

Thank you

### Exact BookStack Version

v23.10.4

### Hosting Environment

docker using portainer on synology nas.
image: image: lscr.io/linuxserver/bookstack

**Comment by ssddanbrown** [comment]
Hi @ap2de,

This will be likely due to hitting the PHP memory limit, which is controlled via a [memory_limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit) PHP option. You can try doubling the default to see if that helps:

```ini
memory_limit = 256M
```

**Comment by ap2de** [comment]
Hi @ssddanbrown,
thank you, this did the job!
