### ISSUE TITLE
Page includes only showing one paragraph, not an section anymore

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4759]
### Describe the Bug

Since version 23.12 I'm not able to include other page content completely.
It only shows the paragraph I'm selecting, not the rest of the section within the headline.
So if I have multiple paragraphs, it only includes this specific paragraph.
Example:
```
h1: Test
para1: this is some text
para2: this is another text
```

If I mark `para1` and try to include it on another page, it only shows `para1`, but not `para2`.

I hope I described it good enough.

### Steps to Reproduce

1. Create some content with multiple paragraphs
2. copy the anchor of a paragraph
3. paste the anchor on another page
4. it only shows this specific paragraph which was copied, not the rest of the paragraph under this headline

### Expected Behaviour

show the hole section under the headline from which I copied the paragraph.

### Exact BookStack Version

23.12

**Comment by ssddanbrown** [comment]
Hi @Man-in-Black,
The described functionality is how I've always expected the include functionality to behave,
as far as I'm aware there's never been anything to including a specific range, especially based upon header, nor do we officially state that's expected or supported behaviour.

There is issue #3854 open for this. Did you perhaps make use of the customization in that thread?

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll go ahead and close this off.
