### ISSUE TITLE
Login with GitLab OAuth

### ISSUE THREAD

**Issue by CordlessWool** [BookStackApp/BookStack#476]
Bookstack is a great wiki, but I miss a option to login with GitLab OAuth? I it is already added for Github and Google (I do not tested it jet)?

Would be great

**Comment by ssddanbrown** [comment]
Just for dev reference, There's a provider available here for this so it shouldn't be too much effort to add GitLab support:
http://socialiteproviders.github.io/providers/gitlab/

Will require the process to be documented though.

**Comment by ssddanbrown** [comment]
Added in #691, Will be in the next release (v0.20).
