### ISSUE TITLE
Missing Admin page on new install.

### ISSUE THREAD

**Issue by NascarUk** [BookStackApp/BookStack#4761]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have downloaded the latest image in docker-compose and have it running almost fine. I log in with admin@admin.com with the default password of password. Once I get in I can't access the admin settings even if I create a new admin user. It just directs me to /settings but has the default dashboard.

Screenshot of /settings

![image](https://github.com/BookStackApp/BookStack/assets/94526111/ad49818b-706d-4b81-89a5-4594dfd78806)

Screemshot of /

![image](https://github.com/BookStackApp/BookStack/assets/94526111/e4f1cb88-5bb8-4093-b819-906672e6efc8)

It seems like its just directing me back to the main page

If I try to access the Administrator Options under My Account I just get this:

![image](https://github.com/BookStackApp/BookStack/assets/94526111/0b93a273-5cfa-4b79-b482-94a5ae792153)

This is even with the built in admin... Any ideas anyone? 

### Exact BookStack Version

I just pulled latest. I can't check as I can't get to the admin settings.

### Hosting Environment

Ubuntu 20.04 docker container

https://docs.linuxserver.io/images/docker-bookstack/

**Comment by ssddanbrown** [comment]
- Are you able to create a book, and a page within that book, without any issue on this instance?
- Do you have a reverse proxy or web server sitting in front of this container?

**Comment by NascarUk** [comment]
Yup I can create books just fine...

![image](https://github.com/BookStackApp/BookStack/assets/94526111/20be2d2e-eb97-4b4c-b807-ac0f25a1920a)

It is behind a reverse proxy although everything seems to work other than the settings page which now gives me

![image](https://github.com/BookStackApp/BookStack/assets/94526111/32264017-a1c1-4cf8-afab-dcf5a694913f)

**Comment by NascarUk** [comment]
My bad , I have an extra "/" in my nginx config : ( All working now, thanks
