### ISSUE TITLE
Extend Default Pagetemplate to Chapters

### ISSUE THREAD

**Issue by cod3monk** [BookStackApp/BookStack#4764]
### Describe the feature you'd like

The recently implemented feature of "Default Pagetemplates" (issue #1803 and PR #3918) could be extended to Chapters. Where new pages created in a chapter are by default created with a configured template.

### Describe the benefits this would bring to existing BookStack users

In our wiki we have a book documenting internal workings of our association, one chapter is on processes which are meant to be documented in a standardized way. This is supported by a template. Thus, the process template should only be default in the processes chapter.

### Can the goal of this request already be achieved via other means?

Only be splitting the chapters of a book into separate books.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @cod3monk.

Related PR:  #4750

**Comment by Man-in-Black** [comment]
I'm using this change in my bookstack instances as for now, maybe I need to readd the default templates with the next update, but because it is a benefit for my installations I'm living with the risk to reset the changes to my database ;)

**Comment by ssddanbrown** [comment]
With the merge of #4750, this will be part of the next feature release.

**Comment by cod3monk** [comment]
Awesome! Thanks @Man-in-Black and @ssddanbrown  for all your work!
