### ISSUE TITLE
Chapter API endpoint doesn't return the field book_slug

### ISSUE THREAD

**Issue by ayrtonnadgel** [BookStackApp/BookStack#4765]
### Describe the Bug

Chapter API endpoint doesn't return the field `book_slug`.

### Steps to Reproduce

1. Make a GET request to `/api/chapters`
2. Choose any `id` of any chapter
3. Make a second GET request to `/api/chapters/{id}`

### Expected Behaviour

The field `book_slug` is returned in the response, as shown in the documentation. 

### Exact BookStack Version

v23.12

**Comment by ssddanbrown** [comment]
Apologies @ayrtonnadgel, and thanks for reporting.
This has now been added back in adf1806feaa541f7ff627ba83278ea7dd2fd7a04, with tests update to cover, and will be part of the next patch release due soon.

**Comment by ayrtonnadgel** [comment]
> Apologies @ayrtonnadgel, and thanks for reporting. This has now been added back in [adf1806](https://github.com/BookStackApp/BookStack/commit/adf1806feaa541f7ff627ba83278ea7dd2fd7a04), with tests update to cover, and will be part of the next patch release due soon.

Thanks. 🙇‍♂️
