### ISSUE TITLE
Small update problem

### ISSUE THREAD

**Issue by Phi2ca** [BookStackApp/BookStack#4771]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello

I want to update my version 23.08.2 to 23.12, and, not being a developer at all and therefore hardly ever using git, I get an error message following the command "git pull origin release".
Here is the message translated from French:

tip: Shoot without specifying how to reconcile diverging branches
tip: is discouraged. You can eliminate this message by running one of the following
tip: commands before your next draw:
tip:
tip: git config pull.rebase false # merge (default strategy)
tip: git config pull.rebase true # rebase
tip: git config pull.ff only # fast forward only
tip:
tip: you can replace "git config" with "git config --global" so that
tip: this is the default option for all repositories. You can also
tip: pass --rebase, --no-rebase or --ff-only on the command line to make it the default for all repositories.
tip: replace the configured default value on invocation.
From https://github.com/BookStackApp/BookStack
 * branch release -> FETCH_HEAD
Update 3f473528..457adc1f
error: Your local changes to the following files would be overwritten by the merge :
        lang/en/preferences.php
Please validate or re-save your changes before merging.
Abort

yes, there was a small translation problem in French on version 23.08, so I made the change in the lang/fr/preferences.php file, but this error has been corrected by you in the latest version.

So what command should I apply to override this error, overwrite my modification with your file, and be able to update my version of bookstack?

Thanks in advance.

### Exact BookStack Version

23.08.2

### Hosting Environment

debian 12

**Comment by ssddanbrown** [comment]
Hi @Phi2ca,

From your BookStack directory, you could try running `git restore lang/en/preferences.php` to undo changes to that file.
After that, running `git status` should not list out any files or directories, if it does, stop there and report back.
Otherwise, you should be good to go with running the update.

**Comment by Phi2ca** [comment]
Hi
As I had no answer (which I can understand), I asked one of my colleagues who told me to run the git stash command.
I then ran the git pull origin release command again and this time, despite the same warning, the new version of bookstack was installed.
On the next update I'll try your command to see if it actually makes the alert disappear, unless you want me to run it now.

**Comment by ssddanbrown** [comment]
Okay, git stash should save and remove your changes, instead of just undoing the changes, so kind the same intent/result for this.

> despite the same warning

Okay, that's a bit odd unless other files were changed. 
If you could provide the output of both `git status` and `git log -n 1`, I could double check if I can attempt to forsee any potential issues in the next update run.

**Comment by Phi2ca** [comment]
Hello

below the two commands requested:

```
root@Bookstack:/var/www/BookStack# git status
Sur la branche release
Votre branche est à jour avec 'origin/release'.

Fichiers non suivis:
  (utilisez "git add <fichier>..." pour inclure dans ce qui sera validé)
        .env.ori
        .env.save

aucune modification ajoutée à la validation mais des fichiers non suivis sont présents (utilisez "git add" pour les suivre)
```

and

```
root@Bookstack:/var/www/BookStack# git log -n 1
commit 457adc1fee24f6ad885ab6c840eaa8ae0ccb1e2c (HEAD -> release, origin/release)
Author: Dan Brown <ssddanbrown@googlemail.com>
Date:   Fri Dec 29 12:16:07 2023 +0000

    Updated version and assets for release v23.12
```

greetings

**Comment by ssddanbrown** [comment]
@Phi2ca Okay, that looks fine, You're probably getting the messages just because of those two added `.env` files, but it's unlikely we'd ever add files of the same name into the core code so things shouldn't conflict.

Since you've got things working for now I'll go ahead and close this off.
