### ISSUE TITLE
Table overlapping bookstack Content Container

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#4774]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Here a Example

![image](https://github.com/BookStackApp/BookStack/assets/6242840/f6b1fad9-758d-4a8f-b37b-7f887811fe7a)

### Exact BookStack Version

v23.12

### Hosting Environment

Docker

**Comment by reddexx** [comment]
.page-content table {
    hyphens: auto;
    table-layout: auto;
    max-width: 100%;
    height: auto !important;
}

  .page-content {
    width: 100%;
    max-width: 100%;
    margin: 0 auto;
    overflow-wrap: break-word;
}

fix this Problem

**Comment by ssddanbrown** [comment]
Good to hear you found a solution. Since you did find a solution, and since there are various other issues open in regard to table sizing and overflow, I'll close this off.
