### ISSUE TITLE
Problem attempting to Upgrade from BookStack v23.05.2 to the latest release

### ISSUE THREAD

**Issue by EAwesomeK** [BookStackApp/BookStack#4776]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When using the following command:   git pull origin release    I receive the following error message:     

Resolving deltas: 100% (3956/3956), completed with 473 local objects.
From https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
   4ac8ecad..457adc1f  release    -> origin/release
error: Your local changes to the following files would be overwritten by merge:
        .env.example
Please commit your changes or stash them before you merge.
Aborting
Updating 4ac8ecad..457adc1f

I did NOT modify this file - in any case how do I commit changes?

### Exact BookStack Version

v23.05.2

### Hosting Environment

Windows 2012 R2 Server

**Comment by ssddanbrown** [comment]
Hi @EAwesomeK, please could you share the output of running `git diff .env.example` from your BookStack directory?

**Comment by EAwesomeK** [comment]
```diff
diff --git a/.env.example b/.env.example
index a0a1b72e..1a37d96c 100644
--- a/.env.example
+++ b/.env.example
@@ -37,7 +37,7 @@ MAIL_FROM=bookstack@example.com
 # SMTP mail options
 # These settings can be checked using the "Send a Test Email"
 # feature found in the "Settings > Maintenance" area of the system.
-MAIL_HOST=localhost
+MAIL_HOST=192.168.0.132
 MAIL_PORT=1025
 MAIL_USERNAME=null
 MAIL_PASSWORD=null
```

**Comment by ssddanbrown** [comment]
Thanks for sharing @EAwesomeK.
That output does fairly clearly reflect that the file was modified.

You can just run `git restore .env.example` to undo any changes though, then re-attempt the update.

**Comment by EAwesomeK** [comment]
Thanks - have no idea how it was changed,  I;m the only one that maintains the system

It works now

**Comment by ssddanbrown** [comment]
Good to hear things are working now! Will therefore close this off.
