### ISSUE TITLE
Add basic Image Editing Support

### ISSUE THREAD

**Issue by chickentom** [BookStackApp/BookStack#4777]
### Describe the feature you'd like

If you paste/import Images you can resize them, but however you can not crop them. Just a simple functionality like it is present in Microsoft Word would be a huge Time saver. 
(More Image editing featues would be a nice to have, but i think cropping images is the most import one, that is missing)

### Describe the benefits this would bring to existing BookStack users

You can then directly past images and crop them in Bookstacks, so no third party software would be needed. Generally speaking more Image Options would be appropriated like it is shown on the Frola Editor:
![grafik](https://github.com/BookStackApp/BookStack/assets/49533314/e5aeda0b-b64c-411d-a963-c4d93d0b1a76)
or on the offical Tinymce demo:
![grafik](https://github.com/BookStackApp/BookStack/assets/49533314/e4de5448-e8e8-4818-9e1d-227884bdb523)

### Can the goal of this request already be achieved via other means?

Currently only with third party software. 
(I currently past it temporary in Word, crop it and then past it in Bookstacks)

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

i know theres a possible duplicate on the Issue: #3888 , but the Part about Image Cropping was not directly answered.
Hope this Features gets added.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @chickentom, But I feel open issues  #4476 and #3350 already cover this, so I'll close this off as a duplicate.
