### ISSUE TITLE
When inserting a link after selecting text in the page, the Entity Select interface no longer automatically performs the search

### ISSUE THREAD

**Issue by melat0nin** [BookStackApp/BookStack#4778]
### Describe the Bug

When editing a page, if some text is selected before clicking the insert link button, then the Entity Select button, the resulting search interface would be pre-populated with the selected text _and_ the results would be pre-filtered.

Now, as of v23.12, the search field is prepopulated, but the search results are not (they show the default listing of shelves/books/pages). Performing the search requires editing the field to trigger the search.

### Steps to Reproduce

1. Edit a page
2. Select some text
3. Click the Insert link button
4. Click the URL button
5. Observe that the search term field is prepopulated, but the results have not been filtered according to the value of that field.
6. Running the search requires altering the search term, to trigger it.

### Expected Behaviour

The search should be performed immediately.

### Browser Details

Firefox 122 beta on Windows 11

### Exact BookStack Version

23.12

**Comment by ssddanbrown** [comment]
Thanks for reporting @melat0nin, can confirm this issue.
I've now addressed this in 69c8ff5c2d491d8674e2671a912a025cf16f86d3, and it will be part of the next patch release (v23.12.2)
