### ISSUE TITLE
Something went wrong after using the automated installer for ubuntu 16.04

### ISSUE THREAD

**Issue by jms1989** [BookStackApp/BookStack#478]
* BookStack Version: current stable
* PHP Version: 7.0.22
* MySQL Version: 14.14

##### Expected Behavior
The default webpage to load after installation.

##### Actual Behavior
Error: Whoops, looks like something went wrong.

I've checked the logs, can't tell if anything is wrong. The only thing I have done was change the nginx server name to what I wanted to use on my network.

**Comment by lommes** [comment]
Set `APP_DEBUG` to true in your .env file and retry afterwards.

Everything in bookstacks logfile (in storage/logs/ might help.

**Comment by jms1989** [comment]
OK, a mysql database was never created. So I created it and the associated user, migrated the db tables, and now I have a login screen. woot

side note: I installed LAMP from the OS installer before realizing there was a automated install script. my bad.
