### ISSUE TITLE
Make only one page public of an authenticated site

### ISSUE THREAD

**Issue by stanislas14** [BookStackApp/BookStack#4781]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

My site is authenticated with LDAP authentication. The configuration is done in the .env configuration file and it works very well.

But I need a page on this site to be publicly accessible without authentication, is this feasible? I've played with permissions but I think authentication takes over every time.

Is there a solution? I would like to avoid making the site public and putting permissions on each shelf..

Regards

### Exact BookStack Version

v23.12 

### Hosting Environment

PHP 8.1 on redhat 9

**Comment by ssddanbrown** [comment]
Hi @stanislas14,
The main way to do this is to make the site public, but alter the guest role permissions so it has no permissions by default, then assign view permissions as required per book/chapter/page.
Note though, this does take away a significant layer of defence to the site.

Alternatively, if you have development skills, you could use the REST API to fetch your page content then display externally, or build some level of automation using the tools we provide (webooks, theme systems).

**Comment by stanislas14** [comment]
Hi,

Thanks a lot for your answer. Indeed, we have to look at the problem in reverse. This solution works

regards

**Comment by ssddanbrown** [comment]
Good to her that works.
I'll therefore close this off.
