### ISSUE TITLE
SQL error after updating

### ISSUE THREAD

**Issue by magaiverpr** [BookStackApp/BookStack#4787]
### Describe the Bug

Hello,

After updating 23.10.4 to 23.12.1, I cannot create books anymore. Reverting to 23.10.4 resolve the problem.

Message error after enabling APP_DEBUG=TRUE:

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description_html' in 'field list' (SQL: insert into `books` (`name`, `description_html`, `description`, `created_by`, `updated_by`, `owned_by`, `slug`, `updated_at`, `created_at`) values (Encaminhador de emails, , , 3, 3, 3, encaminhador-de-emails, 2024-01-19 16:19:12, 2024-01-19 16:19:12))

### Steps to Reproduce

- Update to 23.12.1
- Try to create a new book

### Expected Behaviour

Create the book normally

### Screenshots or Additional Context

Using Container in Azure ambient.
image used: lscr.io/linuxserver/bookstack:23.12.1

### Browser Details

Edge

### Exact BookStack Version

23.12.1

**Comment by ssddanbrown** [comment]
Check the container logs when starting your bookstack container.
The error indicates the database has not been updated to the expected format, which is a process that runs at start-up for that container image.

**Comment by magaiverpr** [comment]
Thanks!

Had to set up sql_generate_invisible_primary_key=OFF in mysql
