### ISSUE TITLE
Activity page

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#4795]
### Describe the feature you'd like

I would like to have a page that lists all activities that have been carried out recently, similar to the audit log, only public.
The administrative activities do not have to be shown there, only the changes to which the user has access.

### Describe the benefits this would bring to existing BookStack users

It would help to see more quickly where work is being done and to help out.
e.g.
- comments on other pages are quickly overlooked
- it is difficult to find which pages were last updated

### Can the goal of this request already be achieved via other means?

as admin you can, as user unfortunately not

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @Tealk.
The underlying desire here is very similar to #4308, so I may close this in favour of that existing issue.

**Comment by Tealk** [comment]
Yes, that sounds like my anliegn, sorry I must have overlooked it in my search.
