### ISSUE TITLE
After upgrade missing watchOptions variable

### ISSUE THREAD

**Issue by ajwstevens** [BookStackApp/BookStack#4797]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

We upgraded the system , docker-compose up from a 1/2 year old version. Seemed to be running well, but when we directly access a shelve  we get the following error: 

/config/log/bookstack/laravel.log:[previous exception] [object] (ErrorException(code: 0): Undefined variable $watchOptions at /app/www/storage/framework/views/eb0f06564035fb8e498f94ee536896aaefa7b3aa.php:79)
/config/log/bookstack/laravel.log:[2024-01-23 14:42:10] production.ERROR: Undefined variable $watchOptions (View: /app/www/resources/views/entities/meta.blade.php) (View: /app/www/resources/views/entities/meta.blade.php) {"userId":6,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined variable $watchOptions (View: /app/www/resources/views/entities/meta.blade.php) (View: /app/www/resources/views/entities/meta.blade.php) at /app/www/storage/framework/views/eb0f06564035fb8e498f94ee536896aaefa7b3aa.php:79)

production.ERROR: Undefined variable $watchOptions (View: /app/www/resources/views/entities/meta.blade.php) 

### Exact BookStack Version

23.12.1

### Log Content

/config/log/bookstack/laravel.log:[previous exception] [object] (ErrorException(code: 0): Undefined variable $watchOptions at /app/www/storage/framework/views/eb0f06564035fb8e498f94ee536896aaefa7b3aa.php:79)
/config/log/bookstack/laravel.log:[2024-01-23 14:42:10] production.ERROR: Undefined variable $watchOptions (View: /app/www/resources/views/entities/meta.blade.php) (View: /app/www/resources/views/entities/meta.blade.php) {"userId":6,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined variable $watchOptions (View: /app/www/resources/views/entities/meta.blade.php) (View: /app/www/resources/views/entities/meta.blade.php) at /app/www/storage/framework/views/eb0f06564035fb8e498f94ee536896aaefa7b3aa.php:79)

### Hosting Environment

Docker compose docker 

PHP 8.3.2 (cli) (built: Jan 18 2024 16:40:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies

image:
lscr.io/linuxserver/bookstack   latest              e434dd96b53e

**Comment by ssddanbrown** [comment]
Hi @ajwstevens,
Are you using the visual theme system at all to maybe override template files with customizations?

**Comment by ajwstevens** [comment]
Hello @ssddanbrown  , Dan, 

I did not realize, but yes. We were! I found the problem. Thank you very much. 

Regards ,

Albert-Jan

**Comment by ssddanbrown** [comment]
Great, good to hear you found the cause of the issue!
