### ISSUE TITLE
Curl, wget broken when it's mentioned in documentation.

### ISSUE THREAD

**Issue by s3n3c4** [BookStackApp/BookStack#4799]
### Describe the Bug

Hello, everyone.

I found a issue, and I don't know hot to solve it.

For example, when I use some linux commands as wget, curl it doesn't allow me to update the page, I got a timeout. I have to fill in the command with some blank spaces or nulling the command as putting double letters or something like that.

Example:

```bash
curl -I google.com
```

I have to put something like this:

```bash
curll -I google.com
````

### Steps to Reproduce

```bash
curl -I google.com
```

Failure, when I try to edit the draft shows me a timeout.

### Expected Behaviour

```bash
curll -I google.com
```

Here, it works.

### Exact BookStack Version

23.12.1

**Comment by ssddanbrown** [comment]
Hi @s3n3c4,
Can you screenshot the documentation that you're following?
Unfortunately I don't at all understand what this is in reference to.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll close this off.
