### ISSUE TITLE
Wrong revision information

### ISSUE THREAD

**Issue by bjinthahouse** [BookStackApp/BookStack#4800]
### Describe the Bug

Bookstack is displaying wrong revision information. Pages that have been created 3 months ago (see screenshot 1), with no extra revision are being displayed as "updated 20h ago". As you can see in the screenshot, there have been no revisions. 
Also, we are getting wrong time statements, if a page has been updated. See screenshot 2 & 3.
But this is not happening on all pages. 

### Steps to Reproduce

1. Open a page
2. Check the right-hand sidebar
3. Look at the revision information

### Expected Behaviour

If a page has been created, but not updated, I would expect no update information.
If a page has been created and updated, I would expect the correct update time.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/101190147/98dcd3a7-2bd4-4982-92d1-ab01498f8916)

![image](https://github.com/BookStackApp/BookStack/assets/101190147/5ced4414-8af8-4b0f-b891-f7d62bda5dce)

![image](https://github.com/BookStackApp/BookStack/assets/101190147/509e752d-1211-4fe0-9c96-7e65fecdd470)

### Browser Details

Google Chrome 120.0.6099.130 on Windows 10

### Exact BookStack Version

v23.08.3

**Comment by ssddanbrown** [comment]
Thanks @bjinthahouse for raising, but I'm going to consider this having the same fundamental request as #1777 so I'll therefore close this off as a duplicate.
