### ISSUE TITLE
Misplaced navigation buttons in RTL interface

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#4808]
### Describe the Bug

When the interface is right to left, the navigation buttons that can be used to surf pages are misplaced. They should be swapped.

### Steps to Reproduce

1. Go to the user settings and change the UI language to a RTL one; such as Persian.
2. Go the shelves.
3. Scroll down to see the navigation buttons.
4. They are misplaced and they should be on the right side.

### Expected Behaviour

The buttons block should be placed on right, not left; since the interface is right to left.
Another problem is the way the left and right buttons are placed. They should be swapped.

### Screenshots or Additional Context

![buttons](https://github.com/BookStackApp/BookStack/assets/100111649/be233fec-857c-47b4-832f-9a4a5d358e94)

### Browser Details

Google Chrome Version 104.0.5112.102 (Official Build) (64-bit) On Windows 10

### Exact BookStack Version

BookStack v23.12

**Comment by ssddanbrown** [comment]
Thanks for reporting @okaeiz,
This has been addressed as part of c66b8ad842a14e83e8a5ecb44710ca94ac1430e8, and this fix will be part of the next feature release.
