### ISSUE TITLE
[FEATURE REQUEST] allow text formatting in code blocks

### ISSUE THREAD

**Issue by uchytma** [BookStackApp/BookStack#481]
It would be great to implement text formatting in Code Blocks. 
Now there is no way how to highlight parts of code.

**Comment by ssddanbrown** [comment]
Think this will be quite difficult to implement since formatting is done dynamically via codemirror. Will interfere with the nice code formatting.

**Comment by jarensWizmo** [comment]
We also desire the ability to either highlight or bold text within a code block. We are currently using inline code as a workaround but we prefer to use code blocks in our documentation.

**Comment by jarensWizmo** [comment]
It appears that codemirror does support this feature, but I obviously do not know what complications would be faced with implementing this into BookStack editor.

https://codemirror.net/demo/variableheight.html

**Comment by ssddanbrown** [comment]
The above demo is simply showing variable height text. The formatting in that demo, As per all regular codemirror use cases, is dependant on the language syntax highlighting. To implement this with codemirror we'd be fighting the syntax highlighting system. We'd probably have to look at implementing an alternative alongside proper codeblock support.

**Comment by jarensWizmo** [comment]
I see, hrmm... not sure if it makes any difference or not, but we often don't select a language in the editor, the source code doesn't show it having a defined language.

`<pre><code class="language-">this is a test... I want this to be BOLD</code></pre>`

Do you think it is possible that not choosing a language could allow for other more basic formatting features?

I have tried to input `<b></b>` & `<strong></strong>` into the source code but it gets removed right away  :(

**Comment by kawawa** [comment]
I hope this has not previously been sugegsted, if so please ignore this comment.

What if, instead of trying to modify the codeblock, one of the two is added:
1. A block editing option that behaves similar to the **inline code** option but results in an instant look to the **code block** option
2. Add support for monospaced fonts like courier new, san serif

I particular would be interested in this because I predominantly work with outputs from network device command lines and would like to have control what aspects of the output I can emphasize

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since there's been relatively little demand for this since the original issue was opened.

**Comment by carlossierra311** [comment]
Too bad this was closed, as I too need something similar. In our documentation, it's important to show which lines of code changed at some version, or to highlight parts of code up for discussion/review. Text coloring/formatting would help us achieve that.
