### ISSUE TITLE
Misplaced description block (For Shelves, Chapters and Books) in RTL interface

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#4810]
### Describe the Bug

In RTL interfaces, when we want to edit (not view) the description, it is left to right. It looks fine after saving, though.

### Steps to Reproduce

1. In a RTL interface, go to a shelf, chapter or book.
2. Click on `Edit`.
3. The descrption block is left to right. Once you save, it goes on right.

### Expected Behaviour

I expect the editor to be right to left as well.

### Screenshots or Additional Context

![Capture](https://github.com/BookStackApp/BookStack/assets/100111649/2f327edd-1dc9-44bc-a8a9-85c83327d56d)

### Browser Details

Google Chrome Version 104.0.5112.102 (Official Build) (64-bit) On Windows 10

### Exact BookStack Version

BookStack v23.12

**Comment by ssddanbrown** [comment]
Thanks for raising @okaeiz and apologies for this.
This has been addressed as part of the work in #4815, and has been merged to be part of the next feature release.
