### ISSUE TITLE
Latex export

### ISSUE THREAD

**Issue by controleman** [BookStackApp/BookStack#4813]
### Describe the feature you'd like

Support for Latex for html and pdf export. 

### Describe the benefits this would bring to existing BookStack users

This can be used shared or stored offline.

### Can the goal of this request already be achieved via other means?

Haven't tried wkhtmltopdf for the pdf export. Currently looking for html support.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Thanks for the request @controleman but we don't support latex at all currently, as requested in #639, which would be a prerequisite so I'm therefore going to close this off.
