### ISSUE TITLE
Dropdown search partly hidden in lower viewports

### ISSUE THREAD

**Issue by Bolthier** [BookStackApp/BookStack#4824]
### Describe the Bug

When using the dropdown search in a mobile browser on a page or chapter the search bar and the first entry is hidden behind the mobile tab bar.

Additionally the dropdown element is partially hidden on the side when simulating desktop mode on a mobile browser or using only half the screen on a laptop with a desktop browser.

### Steps to Reproduce

1. Go to a bookstack page with a mobile viewport of 360x800
2. Click on dropdown search
3. See no search bar and first element

1. Go to a bookstack page with a viewport of 900x1000
2. Click on dropdown search
3. See vertically cut off dropdown, more cut off on books dropdown

### Expected Behaviour

The dropdown should start below the mobile tab bar and should be fully visible.

### Screenshots or Additional Context

![Screenshot_20240201-140704](https://github.com/BookStackApp/BookStack/assets/42382626/333b4794-f797-4e38-bfc6-b1daf26f747e)

![Screenshot_20240201-150101](https://github.com/BookStackApp/BookStack/assets/42382626/e277e78f-86a3-429b-876d-906a2487af4b)

### Browser Details

Firefox 122 on Android/Windows

### Exact BookStack Version

v23.12

**Comment by ssddanbrown** [comment]
Thanks for raising @Bolthier.
This has been addressed in bbb41e8b5cc5c6e33cb27ef1b69092cf7a0f70ba, to be part of the next feature release.
