### ISSUE TITLE
Firefox Icons not loading properly

### ISSUE THREAD

**Issue by WilliamBjerglund** [BookStackApp/BookStack#4826]
### Describe the Bug

The bug is that icons you set inside of the settings once your server is setup will load just fine on a chromium based browser (Tested on both Edge, Chrome, Brave & Opera)

However when you open up firefox the logo when bookmarked will turn back into the standard icon for BookStack and not change to your new icon.

### Steps to Reproduce

Open Firefox, Create ubuntu 22.06 LTS bookstack Server, use name server to call it & change the icon under Settings from Admin account.
Now it won't show correctly, but if you then go to any chromium based browser it works just fine.

### Expected Behaviour

Icon loads properly and shows when changed in the Bookmark

### Screenshots or Additional Context

Tested on 121.0.1 & 122.0.1 of firefox.

### Browser Details

121.0.1

### Exact BookStack Version

v23.12.2

**Comment by ssddanbrown** [comment]
Hi @WilliamBjerglund,
From my testing Firefox can pick up the icons fine (favicons, bookmark icons, homepage icons) but it can aggressively cache these images, which is fair enough since these are part of common UIs.
You might find that they change in time.

**Comment by WilliamBjerglund** [comment]
Hi @ssddanbrown 
I hope you are right and for now i guess i will to close this issue and hope it goes away with time. I just thought it might be a bug since we were a total of 5 people in our Project who had this issue, and still do.
