### ISSUE TITLE
List of people who viewed a page

### ISSUE THREAD

**Issue by bjinthahouse** [BookStackApp/BookStack#4834]
### Describe the feature you'd like

As e.g. an admin I would be able to see who has viewed the page.

### Describe the benefits this would bring to existing BookStack users

This is only one of the benefits. 
We document necessary work instruction in bookstack. Our employees are obliged to view these work instructions after being told to. Having this feature, we can check if all employees have viewed them.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

I think putting this in some sort of analytics page, which is only viewable for specified roles, would be quite beneficial.

**Comment by ssddanbrown** [comment]
Thanks for the request @bjinthahouse, but this has been requested previously to which you can see previous discussions about in #3609 and #2835. My thoughts remain the same in that this is desired for business compliance specific process, which could be managed external to BookStack (Business form/spreadsheet etc...)
