### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by sirup** [BookStackApp/BookStack#484]
Desired Feature: Change the Landing Page / Homepage after Login. Currently it shows
My Recently Viewed
Recently Created Pages
Recently Updates Pages
Recent Activity

I feel this is not a very usefull and intuitive landing page. I would love to have the ability builtin to design the Landing page. For example with the ability to give kind of a structure, like a index.

Thank you.

**Comment by ssddanbrown** [comment]
Thanks @sirup for creating this request.

This issue is already open under #126 so feel free to add your comments there. You will see that changes are due to be made for the next release.

Since this is a duplicate request I will go ahead and close this issue.
