### ISSUE TITLE
Additional Layer of Organization (e.g. Libraries, Rooms, ...)

### ISSUE THREAD

**Issue by mgmwhite** [BookStackApp/BookStack#4848]
### Describe the feature you'd like

How about adding another organizational layer to the shelves, books etc.?
Like the possibility to add libraries and/or rooms, where the shelves are sorted in.
Maybe even as an option that can be turned on or off.

Organziation would look like: library/(room)/shelve/book/chapter/page

### Describe the benefits this would bring to existing BookStack users

One more level to organize stuff, e.g. you aquire a new company and want to differentiate content between them.

### Can the goal of this request already be achieved via other means?

Not as i know. Sorry if already requested, could not find any matches.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Hi @mgmwhite,
Please see #95 for the most extensive past discussion on additional levels.

As an additional workaround, to achieve this via other means, you could instead set up multiple separate BookStack instances.

**Comment by mgmwhite** [comment]
Hi @ssddanbrown thanks for taking me back to this, great discussion and the workaround, will think of that.
Cheers
