### ISSUE TITLE
Book to Page

### ISSUE THREAD

**Issue by nervigenamenssuche** [BookStackApp/BookStack#4851]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hey Folks,

I would like to be able to link a page to a book.
So if I click on a book I get directly to a page and not "into" the book and have to select the  single page that is in that book.
Most of my books contain pages or chapters but some books are just one page and so I have to waste another cklick (or the customer) to get to that one page in the book.

### Exact BookStack Version

BookStack v23.10.4 

### Hosting Environment

Windows

**Comment by ssddanbrown** [comment]
Thanks for the request @nervigenamenssuche,
This is not currently a feature/option, at least without adding some custom code, but there is an existing request for this in #1184 so I'll therefore close this off as a duplicate.
