### ISSUE TITLE
Possible Bug / Possibly Intended 

### ISSUE THREAD

**Issue by pat-keeley-aurum** [BookStackApp/BookStack#4856]
### Describe the Bug

When sorting chapters, moving any page between a chapter will update the 'Last Updated' date of all pages that were 'moved' as part of the sort under the same chapter.

Unsure if a bug or expected behavior. 

### Steps to Reproduce

Go to Book, select 'Sort', move Pages between Chapters and the Pages under said chapter will update the last updated date to today. 

### Expected Behaviour

Organizing/Sorting content would not trigger an 'Last Updated' call similar to how moving files on a folder share doesn't change the last modified, as the action hasn't changed the page itself.  

### Browser Details

Chrome Version 121.0.6167.185

### Exact BookStack Version

BookStack v23.12

**Comment by ssddanbrown** [comment]
Thanks for raising @patsyk1, but I feel this is already covered by #1777 so I'll therefore close this off.

**Comment by pat-keeley-aurum** [comment]
Ah perfect. Thanks @ssddanbrown. Will keep an eye on this thread.
