### ISSUE TITLE
functionality to hide "revisions" for unauthenticated users

### ISSUE THREAD

**Issue by arminarmin** [BookStackApp/BookStack#4861]
### Describe the feature you'd like

When not authenticated (as a guest-user) the revisions of the page that is shown are available. 
For the purpose of confidentiality we would like to get the option to hide the "revisions" for unauthenticated users.

### Describe the benefits this would bring to existing BookStack users

Confidentiality.
Another achievement from our point of view would be that search-engines do not index these contents.

### Can the goal of this request already be achieved via other means?

We reached the goal by "disallowing" the path to the revisions with a wildcard-path-string in the robots.txt.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

This could also solve the following issue in a way: 

https://www.reddit.com/r/BookStack/comments/182zeet/hide_revisions_from_public/

While we are at it (the revisions topic), when you altered the REVISIONS_LIMIT, do you need to clean the revisions to activate the new limit ?

Thanks alot for bookstack and your help :) 👍

**Comment by ssddanbrown** [comment]
Hi @arminarmin,
We already have  #4526 which I feel covers this request so I'm going to close this off.

> when you altered the REVISIONS_LIMIT, do you need to clean the revisions to activate the new limit ?

From what I remember, the limit is taken into account the next time a revision is made, nothing runs in the background or upon change of env setting.

You can use the delete [page revisions command](https://www.bookstackapp.com/docs/admin/commands/#delete-page-revisions) if you want to remove all revisions (Is not related to the `REVISIONS_LIMIT` option though.)
