### ISSUE TITLE
Can use Chinese URL slugs in BookStack v23.12.2?

### ISSUE THREAD

**Issue by Sunskyey** [BookStackApp/BookStack#4868]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Can use Chinese URL slugs in BookStack v23.12.2?

The URL looks like "BookStack.xxxx.xxx/books/中文"

I have seen the use of Chinese URL slugs on other Bookstack websites.

### Exact BookStack Version

BookStack v23.12.2

### Hosting Environment

Ubuntu 22.04.4
Apache
BookStack v23.12.2

**Comment by ssddanbrown** [comment]
Hi @Sunskyey,
There's no option for this in BookStack.
That instance may be modified, or using a much older version of BookStack where non-ascii slugs were allows but we had negative feedback regarding the raw encoded form of these URLs.

**Comment by ssddanbrown** [comment]
Since the original query has been answered, and there's been no further discussion on this since my last reply, I'll go ahead and close this off.
