### ISSUE TITLE
Breadcrumb books & shelves lists are ordered by `id` not name

### ISSUE THREAD

**Issue by melat0nin** [BookStackApp/BookStack#4876]
### Describe the Bug

The order of books within the breadcrumb dropdowns (i.e. when you click the arrow) is done by the books' id, rather than by name (or any other method). This is counter-intuitive if the books weren't added to the instance in alphabetical order.

### Steps to Reproduce

1. Create >1 book, using names in non-alphabetical order (i.e. 'Beta Book' then 'Alpha Book')
2. Within a book, click the drop-down in the breadcrumbs to show the other books at the same level
3. Observe that they aren't alphabetical

### Expected Behaviour

Either the drop-down should by default order the books alphabetically, or there should be an option to select the ordering (perhaps manually, in line with the sorting available for chapters/pages within books).

### Exact BookStack Version

v23.12.2

**Comment by ssddanbrown** [comment]
Thanks for reporting @melat0nin.
This has been fixed in b7d4bd5bcef09ff20d08626f943d707c1e0f175e, with tests to cover, to ensure name order is used for default (Non-shelf context) book and shelf lists.

This will be part of the next patch release.
