### ISSUE TITLE
Nested collapsible block won't respond (open) to TOC click 

### ISSUE THREAD

**Issue by dfmdkai** [BookStackApp/BookStack#4878]
### Describe the Bug

When a TOC element is clicked and the header is in a collapsible block, the current behaviour is to position the page and automatically open that section. However a nested collapsible block will not work if the parent block is closed. So no child element will be triggered to show and open. 
Instead nothing will happen. 

If the parent is open the behavior is as expected, page is positioned and the block opened

### Steps to Reproduce

1. Create a collapsible block 
2. Create another collapsible block inside the first one 
3. Place text in the first and second one with a header to be picked up as TOC element
4. Close all blocks and  try to open the child header

### Expected Behaviour

If the header is selected in the TOC, the collapsible block should open down the actual element so it can be postioned and read.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/88430073/aaab05ca-5068-4e2c-86ef-305a62c07765)

### Browser Details

Chrome Version 121.0.6167.189 (Official Build) (64-bit)

### Exact BookStack Version

24.02

**Comment by ssddanbrown** [comment]
Thanks for reporting @dfmdkai.
I've addressed this in 5a5f0b8de95b95827d7ee83c3057429e4afa7836 to be part of the next patch release.
