### ISSUE TITLE
Web URL looks funky

### ISSUE THREAD

**Issue by Nitro-Zeus98** [BookStackApp/BookStack#4882]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi, 
I created an Ubuntu server 22 image and used the bookstack 3-step installation procedure "Ubuntu 22.04 Installation Script" Everything seems to work, and I attached the domain patteguf.dk and installed a certificate via certbot. 

When I open the site patteguf.dk i get a funky website? See the attached pictures. 
what can i do to fix this? as i remember i had the same issue on cloud-chefen.dk when made that website. 

![patteguf dk 01](https://github.com/BookStackApp/BookStack/assets/109220608/91dfcfc0-0788-4df5-88b7-ce35e6717c64)
![patteguf dk 02](https://github.com/BookStackApp/BookStack/assets/109220608/01f2dc4c-11a9-4aeb-89cf-507bd2422106)
![patteguf dk 03](https://github.com/BookStackApp/BookStack/assets/109220608/52bfcbf2-e345-4247-92a5-e31c0f428cbc)

### Exact BookStack Version

24.02

### Log Content

![nginx error log](https://github.com/BookStackApp/BookStack/assets/109220608/c65f7e2c-0516-415b-98f5-948f058ef9fd)
![apache2 error log](https://github.com/BookStackApp/BookStack/assets/109220608/ae74aa26-88e8-4806-a471-713358d5abde)

### Hosting Environment

Server is hosted at Cloud provider kamatera.com with a predefined Image -> Ubuntu 22.04 64bit_optimized (Optimized for best performance and with minimal OS services (OS use only 80MB RAM))

**Comment by Nectenebis** [comment]
It looks like you are trying to use https even in your .env file are set to http.

**Comment by Nitro-Zeus98** [comment]
> It looks like you are trying to use https even in your .env file are set to http.

So how do I fix that 😊

**Comment by ssddanbrown** [comment]
@Nitro-Zeus98 Edit the `/var/www/bookstack/.env` file, and update the `APP_URL` value so that is starts with `https://` instead of `http://`.

**Comment by Nitro-Zeus98** [comment]
that did the trick, thank you so much @ssddanbrown  I will write this info down to another time .

**Comment by ssddanbrown** [comment]
Awesome! I'll therefore close this off.
