### ISSUE TITLE
Special Characters is Database Password

### ISSUE THREAD

**Issue by buckybytes** [BookStackApp/BookStack#4884]
### Describe the Bug

Special characters in MySQL password cause "artisan migrate" to fail.

### Steps to Reproduce

1.  Create database user with complex password including special characters.  Test data password was [password#]
2.  Configure database user in .env file
3.  Follow manual installation steps.
4. Receive access denied error when running step 8, "artisan migrate" 

### Expected Behaviour

I would expect the database tables to be created and populated despite the complex password.

### Screenshots or Additional Context

This might be most easily resolved with a note on the manual installation instructions.  

### Exact BookStack Version

24.02

**Comment by ssddanbrown** [comment]
Hi @buckybytes,

This should be defined in the `.env` file you would have edited:

https://github.com/BookStackApp/BookStack/blob/8e01345f1494f37d462ad35fb6723c8051f9d752/.env.example#L6-L7

**Comment by buckybytes** [comment]
Ahh, that was the other hiccup with my install.  I created the .env file from scratch because I couldn't find it.
