### ISSUE TITLE
Report patch level in 24.02.1

### ISSUE THREAD

**Issue by msaladna** [BookStackApp/BookStack#4889]
### Describe the Bug

24.02.1 released today is [omitting the patch level](https://github.com/BookStackApp/BookStack/blob/v24.02.1/version) resulting in false positives on version sniffing. Previous releases, such as [23.12.3](https://github.com/BookStackApp/BookStack/blob/v23.12.3/version) include it.

### Steps to Reproduce

Inspect version within the release.

### Expected Behaviour

v24.02.1

### Exact BookStack Version

v24.02.1

**Comment by chrisnails** [comment]
i'm using [the cache breaker method](https://github.com/BookStackApp/BookStack/issues/3343#issuecomment-1076093833) for version checking, and have the same issue

**Comment by ssddanbrown** [comment]
Can confirm, my apologies, missed a couple of steps. Also missed building JS/CSS assets.
Have just pushed out https://github.com/BookStackApp/BookStack/releases/tag/v24.02.2 to correct.

Thanks for raising @msaladna and @chrisnails!
