### ISSUE TITLE
[BUG] Paste pictures Ctrl+V always at the end

### ISSUE THREAD

**Issue by sirup** [BookStackApp/BookStack#489]
### For Bug Reports

BookStack: v0.17.1 to v0.17.4
PHP: PHP 7.0.22-0ubuntu0.16.04.1 
MySQL:  5.7.19-0ubuntu0.16.04.1 (Ubuntu)
OS:  4.4.0-87-generic #110-Ubuntu x86_64 x86_64 x86_64 GNU/Linux:

##### Expected Behavior
If I paste pictures with CTRl+V I expect them to be pasted at the location where my mouse course is. 

##### Actual Behavior
However the pictures I paste appear at the very end of my editing window.

**Comment by ssddanbrown** [comment]
Confirmed to be an issue on the WYSIWYG editor. Not a problem on the markdown editor. Will mark for next bugfix release.
