### ISSUE TITLE
Tag count wrong - includes deleted pages?

### ISSUE THREAD

**Issue by hjertaker** [BookStackApp/BookStack#4892]
### Describe the Bug

There seem to be something wrong with the pages count on the Tags page. It includes pages that are already deleted, for example on one tag the pages count is 2, but when i click the tag to see the pages, there are 0 returned. This are a tag previously used, but the pages are where it was used is now deleted.

### Steps to Reproduce

1. Create testpage, add a new tag.
2. Delete the testpage
3. Go to the "View tags" page, the tag created for the testpage should be listed as used on one page.
4. Click on the pages to seach the pages including the tag - none is listed.

### Expected Behaviour

The tag pages count should not include deleted pages. 
Alternativly it should specify that the pages are deleted.

### Screenshots or Additional Context

![bookstack_tag_missing_example](https://github.com/BookStackApp/BookStack/assets/6689370/73513faa-735c-474e-86a6-351aca356cb3)

### Browser Details

Chrome on Windows 10

### Exact BookStack Version

v24.02

**Comment by ssddanbrown** [comment]
Thanks for raising this @hjertaker, I could confirm this and have addressed it in f05ec4cc26c3381a3bc8ea49f371b89bcf38140b, which will be part of the next feature release.
