### ISSUE TITLE
Text analysing to suggest Attributes

### ISSUE THREAD

**Issue by Di2g10** [BookStackApp/BookStack#49]
Have an algorithm the runs the frequency of words over all of bookstack and compares to frequency of words in particular pages or chapters. use this to highlight words that define the subject of the document. 
These could be used to suggest attributes or aid searches.
Searchs: show list of words identified as possibly key that is easy for a person to use in search.
Attributes: comparing other documents already assigned as particular attribute allows you to identify pages showing similar traits and so suggesting having the same attribute.
suggest using bayesian statistics

**Comment by ssddanbrown** [comment]
Thanks for submitting this request,
Since the page attribute system is not yet implemented  (#48) I will mark this as blocked until that features has been implemented.

**Comment by ssddanbrown** [comment]
Thanks again for this request.

Since this has had little demand from others in the last four years, and since it would realistically provide little user benefit over existing default of showing the most popular tags used, I'm going to close this off.
