### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxxxxxxxxx.users' doesn't exist

### ISSUE THREAD

**Issue by simpsoncraig25** [BookStackApp/BookStack#4905]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello, I am currently trying to install Bookstack on my Cloudways web server - I believe this is possible since Cloudways (Digital Ocean host) offer an out of the box Laravel application install.

I have installed the Bookstack git v23.02-branch inside a folder called "bookstack" within the "public_html" route and changed web root addresses to this location. 

I have followed the install steps as best as possible and a webpage does load - although all it says is "Page Not Found. Sorry, The page you were looking for could not be found. If you expected this page to exist, you might not have permission to view it. Image attached. Also the link to Login on this page does reside at "https://phplaravel-817644-4410496.cloudwaysapps.com/bookstack/login" but the same error is shown. So I feel "maybe" the route directory and probably apache business etc is all fine.

![page](https://github.com/BookStackApp/BookStack/assets/58085553/1cca7c09-6db7-4b84-b7c5-0dbf730d9f1e)

The install process appeared all fine and the database connection must be correct since it is now populated with tables. And the table "users" does exist with an admin and public user inside.

I did ask Cloudways support to check permissions, and there were "apparently" fine, as per the install guide. And I have reset on their recommendation (to which still no difference).

I am new to github, Laravel and Bookstack but have some fair web experience. Your support would be much appreciated. Please gudie me where to start and I will jump! Your help much appreciated. 

FYI - I wanted a web install to future users can access the Bookstack wiki inside and remotely from the work place.

Regards Craig

### Exact BookStack Version

v23.02-branch

### Log Content

Next Illuminate\\View\\ViewException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pjnmkcfctz.users' doesn't exist (SQL: select * from `users` where `system_name` = public limit 1) (View: /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/resources/views/layouts/base.blade.php) (View: /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/resources/views/layouts/base.blade.php) in /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
Stack trace:
#0 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#4 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#5 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#6 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#7 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()
#8 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()
#9 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()
#10 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#11 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#12 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#13 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/app/Exceptions/Handler.php(66): Illuminate\\Foundation\\Exceptions\\Handler->render()
#14 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): BookStack\\Exceptions\\Handler->render()
#15 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()
#16 /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#17 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#18 {main}
  thrown at /home/817644.cloudwaysapps.com/pjnmkcfctz/public_html/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 {main}
"} 

### Hosting Environment

PHP 8.1 
MySQL - MariaDB 10.4

**Comment by ssddanbrown** [comment]
Hi @simpsoncraig25,

> I have installed the Bookstack git v23.02-branch

Only the release branch is supported for normal production use, other branches won't include assets like built CSS or JavaScript, and can result in the screenshot shown where no styles exist.
That can also occur if the `APP_URL` option in your `.env` does not align with the actual URL that BookStack is used on.

I think the log message reported could be old? Unless that gets re-added to the log on every load attempt.

Unless carefully and specifically configured and intended, you should not have `bookstack` within the URL, you should have the web root pointed to the `public` folder within the `bookstack` folder.

**Comment by georgelouk** [comment]
I experience exactly the same issue.
But it happens "randomly" for example i navigate 4-5 clicks on admin, and then suddenly i see this error.
When i refresh the page, then it loads ok.

**Comment by simpsoncraig25** [comment]
its fixed - i just installed the wrong version! "v23.02-branch" isn't (wasn't) a full release version. So I started a fresh, used another latest version that didn't have "branch" in the name and it worked. Thanks all :)

**Comment by ssddanbrown** [comment]
Good to hear you found the issue @simpsoncraig25, I'll therefore close this off.

**Comment by georgelouk** [comment]
@ssddanbrown I've re-installed to release branch too and i 'm still getting this error in random moments when browsing the application...


<details><summary>Details</summary>
<p>

```
#0 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Connection.php(414): PDO->prepare('select * from `...')
#1 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#2 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Connection.php(405): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#4 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2705): Illuminate\Database\Connection->select('select * from `...', Array, true)
#5 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2694): Illuminate\Database\Query\Builder->runSelect()
#6 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3230): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2693): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(710): Illuminate\Database\Query\Builder->get(Array)
#9 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(694): Illuminate\Database\Eloquent\Builder->getModels(Array)
#10 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Database\Concerns\BuildsQueries.php(296): Illuminate\Database\Eloquent\Builder->get(Array)
#11 C:\wamp64\www\bookstack\app\App\Providers\AuthServiceProvider.php(73): Illuminate\Database\Eloquent\Builder->first()
#12 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Container\Container.php(885): BookStack\App\Providers\AuthServiceProvider->BookStack\App\Providers\{closure}(Object(BookStack\App\Application), Array)
#13 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Container\Container.php(770): Illuminate\Container\Container->build(Object(Closure))
#14 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(856): Illuminate\Container\Container->resolve('users.default', Array, true)
#15 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Container\Container.php(706): Illuminate\Foundation\Application->resolve('users.default', Array)
#16 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(841): Illuminate\Container\Container->make('users.default', Array)
#17 C:\wamp64\www\bookstack\app\Users\Models\User.php(98): Illuminate\Foundation\Application->make('users.default')
#18 C:\wamp64\www\bookstack\app\App\helpers.php(38): BookStack\Users\Models\User::getGuest()
#19 C:\wamp64\www\bookstack\app\Settings\SettingService.php(62): user()
#20 C:\wamp64\www\bookstack\storage\framework\views\838b4f1e71fbaa4217ae56f597ea1e5aef4f1dcb.php(4): BookStack\Settings\SettingService->getForCurrentUser('dark-mode-enabl...')
#21 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(109): require('C:\\wamp64\\www\\b...')
#22 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#23 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('C:\\wamp64\\www\\b...', Array)
#24 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\wamp64\\www\\b...', Array)
#25 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\View.php(195): Illuminate\View\Engines\CompilerEngine->get('C:\\wamp64\\www\\b...', Array)
#26 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\View.php(178): Illuminate\View\View->getContents()
#27 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\View.php(147): Illuminate\View\View->renderContents()
#28 C:\wamp64\www\bookstack\storage\framework\views\4ee384bfa731ad18bbedee63eefdd60c14abf97e.php(16): Illuminate\View\View->render()
#29 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(109): require('C:\\wamp64\\www\\b...')
#30 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#31 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('C:\\wamp64\\www\\b...', Array)
#32 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\wamp64\\www\\b...', Array)
#33 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\View.php(195): Illuminate\View\Engines\CompilerEngine->get('C:\\wamp64\\www\\b...', Array)
#34 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\View.php(178): Illuminate\View\View->getContents()
#35 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\View\View.php(147): Illuminate\View\View->renderContents()
#36 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#37 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Http\Response.php(35): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#38 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(57): Illuminate\Http\Response->__construct(Object(Illuminate\View\View), 500, Array)
#39 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(87): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#40 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(626): Illuminate\Routing\ResponseFactory->view('errors::500', Array, 500, Array)
#41 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(554): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException))
#42 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(BookStack\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException))
#43 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(BookStack\Http\Request), Object(Illuminate\View\ViewException))
#44 C:\wamp64\www\bookstack\app\Exceptions\Handler.php(89): Illuminate\Foundation\Exceptions\Handler->render(Object(BookStack\Http\Request), Object(Illuminate\View\ViewException))
#45 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(233): BookStack\Exceptions\Handler->render(Object(BookStack\Http\Request), Object(Illuminate\View\ViewException))
#46 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Illuminate\View\ViewException))
#47 C:\wamp64\www\bookstack\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\View\ViewException))
#48 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Illuminate\View\ViewException))
#49 {main}
```

</p>
</details>

**Comment by ssddanbrown** [comment]
@georgelouk If you'd like support, since you're on quite a different setup, and the issue appears in a different manner, please open a seperate specific support request issue. Within that, please provide the full error detail. Your log lines provided above is missing the main error message (Usually provided just above the lines you posted).

**Comment by georgelouk** [comment]
ok i will do, thanks
