### ISSUE TITLE
Exclude Tag from BookStack Search

### ISSUE THREAD

**Issue by j01110101** [BookStackApp/BookStack#4911]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

question in the title.
![image](https://github.com/BookStackApp/BookStack/assets/161697987/42274059-c9e0-4d33-a4eb-825457cf38ec)

Is it possible to exclude Tags from the search?

Thank you in advance!
-Ju

### Exact BookStack Version

v24.02.2

### Hosting Environment

PHP8.2, Debian 12, Nginx

**Comment by ssddanbrown** [comment]
Hi @j01110101,
This is not currently possible in BookStack.
There's an existing request for this here though: https://github.com/BookStackApp/BookStack/issues/4536
