### ISSUE TITLE
Custom link slugs

### ISSUE THREAD

**Issue by etsde** [BookStackApp/BookStack#4924]
### Describe the feature you'd like

It would be great if you could customize the link slug of a page/book/chapter/..

### Describe the benefits this would bring to existing BookStack users

You can enjoy shorter links and even more customization.

### Can the goal of this request already be achieved via other means?

Only by changing the actual name of the book for instance.

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @etsde but I'd considered the fundamental request already covered by existing open issue #3902 so I'll therefore close this off as a duplicate.

**Comment by etsde** [comment]
> Thanks for the request @etsde but I'd considered the fundamental request already covered by existing open issue #3902 so I'll therefore close this off as a duplicate.

Hey,
thank you and sorry.
Hope it'll be integrated soon, it would be great! ^^
Best
E
