### ISSUE TITLE
Insert/Edit Link in Book description to open in New Window does not work

### ISSUE THREAD

**Issue by marklo-de** [BookStackApp/BookStack#4925]
### Describe the Bug

Hi, I'm not very familiar with github, sorry, if I'm a bit clumsy. And English is not my mother tongue.
I'm using Safari 17.4.1 under macOS 14.4.1 and have an issue with BookStack v24.02.2.
When I insert a link into a description of a Book and choose "Open link in... New window" this option is not saved and the link always opens in "Current window". Of course I also save the whole Book afterwards.
If I open the Book to edit, I see the link option switched back to "Current window".
It works fine with Pages.
Same issue under Firefox 124.0.2.

### Steps to Reproduce

see above

### Expected Behaviour

see above

### Browser Details

Safari 17.4.1 under macOS 14.4.1

### Exact BookStack Version

v24.02.2

**Comment by ssddanbrown** [comment]
Thanks for reporting @marklo-de.
I could confirm and re-produce this issue. 

I've now fixed this in 19f78dbe6c1198a0b7072340d1422efaf0cd8bd0, which will be part of the next upcoming patch release.
