### ISSUE TITLE
UI Not Loading At All

### ISSUE THREAD

**Issue by Terrie-png** [BookStackApp/BookStack#4926]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I download the project down and trying to self hosted on my Apache on windows. It loads successfully.  However, it did not as intended. The UI did not load on it and everything is off. Please help. 

![Screenshot 2024-04-04 023552](https://github.com/BookStackApp/BookStack/assets/78715818/9d1ebb17-c888-4c79-a8f0-ec3b6e3b85c3)

### Exact BookStack Version

v24.02.2

### Hosting Environment

Windows 11, PHP 8.1.2, Composer v2.3.10, Apache v3.3.0

**Comment by ssddanbrown** [comment]
Hi @LeeXuan-Ong,
Can you confirm how exactly you downloaded the project?

**Comment by Terrie-png** [comment]
Hi @ssddanbrown ,

I followed through the documentation stated that need me to use in the cmd `git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch`  . Before that I have navigate to the xampp/htdocs and clone it.

**Comment by ssddanbrown** [comment]
@LeeXuan-Ong Okay, that's good.

In that case, does the `APP_URL` value in you `.env` file exactly align with the base URL you're accessing your BookStack instance on in the browser?

**Comment by Terrie-png** [comment]
@ssddanbrown  Thanks. You reminded me of the `APP_URL` and it works now. I realized is the difference between http and https. I just changed to http and it works now. 

![image](https://github.com/BookStackApp/BookStack/assets/78715818/0cf2313b-ad44-4733-a98e-6046a2aa4fe7)

**Comment by Terrie-png** [comment]
Really appreciate your help @ssddanbrown.

**Comment by ssddanbrown** [comment]
@LeeXuan-Ong Happy I could help, will therefore close this off.
