### ISSUE TITLE
custom favicon.ico

### ISSUE THREAD

**Issue by tipuraneo** [BookStackApp/BookStack#4927]
### Describe the feature you'd like

Via settings > personalization it is possible to set custom app logo and icon. They are loaded as
`<link rel="icon" type="image/png" sizes="32x32" href="https://[fqdn]/uploads/images/system/yyyy-mm/[logo].png">`
The favicon (https://[fqdn]/favicon.ico) remains the default bookstack icon. This results in showing the default bookstack icon to be shown when attachments are opened. E. g. by clicking on an image the image is enlareged in a new tab and there the custom app icon is not used.

I suggest to be able to also upload a custom
favicon.ico

and for apple devices
apple-touch-icon.png
apple-touch-icon-120x120.png
apple-touch-icon-120x120-precomposed.png
apple-touch-icon-152x152.png
apple-touch-icon-152x152-precomposed.png

### Describe the benefits this would bring to existing BookStack users

These change lead to more uniq and more professional look of bookstack.

### Can the goal of this request already be achieved via other means?

No.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @tipuraneo,
This is already supported somewhat. BookStack will attempt to create a custom favicon.ico, but will only do so if the `public/favicon.ico` path is writeable by the web-server.

**Comment by tipuraneo** [comment]
Hi Dan,
oh sorry. What is the configuration point namend in the webfrontend? Where do I have to upload the favicon.ico?

**Comment by ssddanbrown** [comment]
@tipuraneo It's handled via the "Application Icon" customization setting where you upload a PNG image.
As long as the webserver has permissions to edit the `public/favicon.ico` file, it'll be altered (How you check/change that would depend on how you run/installed BookStack)

**Comment by tipuraneo** [comment]
Thank you. The issue was, that my png had not the right ratio (1:1) and the wrong dimensions. Fixed it, now it works as designed. Thank you!
