### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by erikschlesinger** [BookStackApp/BookStack#4931]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi everyone,

I have the following problem. I have a BookStack version 23.08.03 server and can no longer update it (until this release this was not a problem). The background is that when I try to install the new version it is created in the Bookstack directory. This means "/var/www/BookStack/BookStack/Data" instead of "/var/www/BookStack/Data". Even the pull command directly in the /var/www/ directory only produces an error. Can you tell me how to reconfigure Git so that the update works again?

Thanks and best regards
Erik

Translated with www.DeepL.com/Translator (free version)

### Exact BookStack Version

23.08.03

### Hosting Environment

Oracle Linux Server release 9.3

**Comment by ssddanbrown** [comment]
Hi @erikschlesinger,

- How did you originally install BookStack?
- Can you please detail the exact steps you're following when attempting to update BookStack? Ideally from point of initial server login.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll go ahead and close this off.
