### ISSUE TITLE
Three dots on upload

### ISSUE THREAD

**Issue by gtmead** [BookStackApp/BookStack#4935]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I was uploading an image during the morning to create a new page. During the upload things seem to have gotten stuck and nothing refreshed like the image had been uploaded. I rebooted the server and now I am not getting anything but the three dots in the picture below. New to troubleshooting so any help is appreciated. Thank you.

<img width="428" alt="Screenshot 2024-04-09 at 8 06 39 AM" src="https://github.com/BookStackApp/BookStack/assets/166513220/d826847f-de10-4278-96f3-4720c7a8fb38">

### Exact BookStack Version

24.02

### Hosting Environment

Proxmox with individual CT, running via Docker in the container.

**Comment by ssddanbrown** [comment]
Hi @gtmead,

- Were image uploads working okay before?
- Can you upload attachments to pages without issue?
- If you start searching via the header search bar (without pressing enter but with at least three characters) does that load okay?

**Comment by gtmead** [comment]
I knew as soon as I posted I would figure it out. I had a PDF in Preview on my MAC and exported the images as a JPG. For whatever reason, uploading to Bookstack doesn’t like those exports. To fix it, I found the image clean up utility and that helped resolve it. I uploaded again, same result. Ran the clean up, everything was fine again.

**Comment by BuckTheWeasel** [comment]
same problem here 3 dots keep loading i am on a new installation:

-  if you search for the image name you can see it 
- press the "view all images' a couple times it will display the images. then press again and it will be back on the 3 dots.
- sometimes it give the error: Failed to create gallery thumbnails due to system resource limits.
- uploading works fine.
- if search not press enter won't do anything.

**Comment by ssddanbrown** [comment]
@BuckTheWeasel Typically that would occur if the system is running out of memory when attempting to create thumbnails, try upping php memory limits.

Will otherwise close this off since the original opener found a resolution.
