### ISSUE TITLE
.env file setup but test e-mail returning "Unable to connect to localhost:587"

### ISSUE THREAD

**Issue by ZuluPilgrim** [BookStackApp/BookStack#4937]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am using docker compose to spin up a bookstack instance.

I have the below .env file

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_ENCRYPTION=tls
MAIL_USERNAME=email@gmail.com
MAIL_PASSWORD=pwd
MAIL_FROM=email@gmail.com
MAIL_FROM_NAME=Recipes
```

I restarted the container  but when I try a test, I get 

`Error thrown when sending a test email: Connection could not be established with host "localhost:587": tream_socket_client(): Unable to connect to localhost:587 (Address not available)`

I would have thought  should be seeing a reference to gmail.com in the error which leads me to think that the .env file is not being referenced.

### Exact BookStack Version

BookStack v24.02.3

### Log Content

docker logs container-id did not return anything.

### Hosting Environment

 Ubuntu 22.04.4
Docker 25.0.4
Docker Compose version v2.3.3

**Comment by ssddanbrown** [comment]
Hi @ZuluPilgrim,
Just to confirm, Where is this `.env` file you're editing? Did you create this file?

**Comment by ZuluPilgrim** [comment]
Hi @ssddanbrown 

I created the file in the same folder as the docker-compose.yml file

![image](https://github.com/BookStackApp/BookStack/assets/111164245/20d51ee4-e973-4118-9550-c959503d7fdd)


user@server:~/docker/recipes$ ls -l -a
total 24
drwxrwxr-x 4 user user 4096 Apr  9 20:02 .
drwxrwxr-x 3 user user 4096 Apr  8 20:23 ..
-rw-rw-r-- 1 user user 746 Apr  9 19:51 .env
-rw-rw-r-- 1 user user 1020 Apr  9 18:48 docker-compose.yml
drwxr-xr-x 8  user user 4096 Apr  9 01:54 recipes_app_data
drwxr-xr-x 4  user user  4096 Apr  9 01:54 recipes_db_data

**Comment by ZuluPilgrim** [comment]
@ssddanbrown Have I missed something above?

**Comment by ssddanbrown** [comment]
Hi @ZuluPilgrim,
That `.env` file won't do anything unless you're somehow importing that into config.

Assuming you're using the linuxserver.io docker image, I would guess you'd find you `.env` file at `recipes_app_data/www/.env`.

**Comment by ZuluPilgrim** [comment]
Ah, another lightbulb moment :) Sorry, I think I now finally understand docker :)
