### ISSUE TITLE
Horizontally Scrolling Table for a Large Matrix?

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [BookStackApp/BookStack#4944]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

We are trying to create a reference page that will end up being a pretty large matrix. When approaching 9, 10, 11, etc. columns with the table, it starts getting squeezed together and formatting goes out the window.

Is there a way to maintain table formatting so things are readable and have it horizontally scroll?

### Exact BookStack Version

24.02

### Hosting Environment

Rocky Linux 9 on ESXi, installed using manual method

**Comment by ssddanbrown** [comment]
Hi @FMCUSystemAdmins,
There are no in-built options for large tables. Tables as a structure are quite inflexible, so I'd usually advise finding an alternative layout if possible.

Some related issues are #1574 and #1387. Within #1387 are some potential workarounds although they will have some limitations.

**Comment by FMCUSystemAdmins** [comment]
Thanks @ssddanbrown,

Those other issues led me on a path in which I ended up with using `style="overflow-x: scroll; display: block; max-width: fit-content; white-space: nowrap;"` in the `table` tag of the page we wanted this functionality on. Didn't put the code in the overall Bookstack customization setting because it messed up other tables we had that don't need this horizontal scrolling function. A bit clunky, maybe, but it's sufficient for now.
