### ISSUE TITLE
BookStack v24.02.3 .pdf export failure "Maximum execution time of 30 seconds exceeded"

### ISSUE THREAD

**Issue by YID-C** [BookStackApp/BookStack#4945]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi all.

Thank you for your time today. I'm having an issue with Bookstack where I am unable to export large books. My books contain many pages and these pages collectively contain hundreds of steps and images as I write in depth technical documentation. I initially received an "unknown error" but after enabling debugging, I can see the maximum execution time of 30 seconds is being exceeded.

I have found my way to issues #389 #1603 #1590 and #804

Per the comments in those tickets:

-I have changed the maximum execution time in my php.ini file from 30 to 3000.
-I have set my resource limit to -1 for unlimited resource use
-Checked and confirmed my server has 8gb of RAM available to it.
-Cleared my artisan cache
-Restarted my webserver through both a full system restart and by manually restarting appache via the command line using the command:

`# /etc/init.d/apache2 restart`

The issue still persists. However, I have noticed that despite having set the maximum execution time to 3000 seconds (fifty minutes) I notice BookStack will still give the error after just 30 seconds. Because of this I can only assume the php.ini file is either being ignored or overridden elsewhere. Is there any code in BookStack itself that could be causing this?

I have attached my debugging log file to this post and here are my version numbers. I installed BookStack into a completely fresh install of Ubuntu using the following commands found on the bookstack installation page. I experienced no issues during installation.

`wget https://raw.githubusercontent.com/BookStackApp/devops/main/scripts/installation-ubuntu-22.04.sh`

`chmod a+x installation-ubuntu-22.04.sh`

`sudo ./installation-ubuntu-22.04.sh`

Here are my versions:

Ubuntu 22.04.4 LTS
PHP Version: 8.1.2-1ubuntu2.14
BookStack Version: v24.02.3
Apache/2.4.52 (Ubuntu)

Here is a screenshot of the error:

![Screenshot_4454](https://github.com/BookStackApp/BookStack/assets/166672041/05467ba7-5314-4740-8b47-2edfdd678d2a)

I greatly appreciate any assistance with this and thank you for taking the time. I see this as a blocker and don't believe I'm able to resolve this myself.

### Exact BookStack Version

v24.02.3

### Log Content

[2024-04-11 00:22:45] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5748)
[stacktrace]
#0 {main}
"} 
[2024-04-11 00:27:45] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5765)
[stacktrace]
#0 {main}
"} 
[2024-04-11 01:03:47] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5757)
[stacktrace]
#0 {main}
"} 
[2024-04-11 01:11:17] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5748)
[stacktrace]
#0 {main}
"} 
[2024-04-11 01:22:16] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5748)
[stacktrace]
#0 {main}
"} 
[2024-04-11 01:36:31] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5762)
[stacktrace]
#0 {main}
"} 
[2024-04-11 01:50:31] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5771)
[stacktrace]
#0 {main}
"} 
[2024-04-11 01:55:33] production.ERROR: Maximum execution time of 30 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/bookstack/vendor/dompdf/dompdf/lib/Cpdf.php:5746)
[stacktrace]
#0 {main}
"} 

### Hosting Environment

Ubuntu 22.04.4 LTS
PHP Version: 8.1.2-1ubuntu2.14
Apache/2.4.52 (Ubuntu)

**Comment by YID-C** [comment]
I also tried investigating the "Cpdf.php" file the error log was pointing to. I made my way to the specific line thinking there may be another setting equivelant to "set_max_timeout" that could be changed but unfortunately that doesn't seem to be the case. This section appears to be about styling.
I did read in one of the other posts someone asked about fonts, but I only have the standard fonts that come with Ubuntu and haven't made any changes.
From the error log it seems it always terminates around line 5748, which I take to mean that is about as far as the process is able to get before the 30 second timer runs out and it is forced to terminate. It seems to me if it respected the extended time limit it would complete as it is near the end already. It appears to be functioning but just keeps getting killed before it can complete.
I may need to resubmit this as a bug?

See this screenshot of Cpdf.php with the cursor at line 5,748:
![Screenshot_4455](https://github.com/BookStackApp/BookStack/assets/166672041/83311069-7a06-4e50-bb27-7b49ba5cfcad)

**Comment by YID-C** [comment]
I SOLVED IT!

So as it turns out, there are *multiple* php.ini files. I was editing the php.ini file located in:
`/etc/php/8.1/cli/php.ini`

However the standard install of BookStack, at least for me, is Apache, which has it's own copy. So to solve the issue, I had to go into:
`/etc/php/8.1/apache2/php.ini`

Once I edited the php.ini file in the apache2 folder and restarted, it worked. When clicking on "export" and then ".pdf file", BookStack will open a new blank tab and it will hang there. In my instance, my book with several hundred pages and easily as many images took just over two minutes to complete, well beyond the default 30 second limit. Once it's complete it downloads via your browser. In my instance I've yet to setup HTTPS so I received a warning that it was insecure, but since I know where it's coming from I accepted and the .pdf downloaded and displays as normal.

Here's some troubleshooting steps for anyone else who receives either the "unknown error" or "maximum execution time of 30 seconds exceeded" when trying to export in future:

1. You need to know or find out what web server you're running as this will determine where the .php.ini file is. If you're having trouble getting the full name exactly correct, make sure you have installed ubuntu with the graphical user interface, click "files" from the desktop, click "other locations" and then "computer". This will get you to the very top of your directory or the equivalent of C: in windows. I don't know why Linux doesn't bring you here by default.
![Screenshot_4457](https://github.com/BookStackApp/BookStack/assets/166672041/c4e52c43-31d0-4a56-8066-b1e53e723092)

2. Once you're at the top of your directory, you can navigate/drill down and explore. First check /etc/php/((YOUR_VERSION))/ and theoretically your webserver should have a folder in here.
![Screenshot_4458](https://github.com/BookStackApp/BookStack/assets/166672041/d159383c-93ce-4c45-8443-8ba7bdbe7d04)

3. Now that you have the name for your web servers folder, open a terminal and navigate to it using the cd command. For this command I'll use apache2 as that seems to be the current default for Ubuntu, but replace "apache2" with the folder for your web server if necessary. I'm also running php 8.1 but replace as necessary for your version. Your command should look like
cd /etc/php/((YOUR_PHP_VERSION))/((YOUR_WEB_SERVER))
In my case
`cd /etc/php/8.1/apache2`

4. This should have changed your terminal so you see /etc/php/8.1/apache2 to the left of your cursor. From here we'll use Linuxs' built in command line text editor (nano) to edit the file. We're also going to need to run this with super user/root permissions or we won't be able to save the file so you'll need an administrator password. Run this command:
`sudo nano php.ini`

5. Enter your admin/root/account password and it should open a colourful window. From here we want to scroll all the way down using the arrow keys until we bump into RESOURCE LIMITS. Just below this you should see the line "max_execution_time = 30". We want to increase this. I set mine to 3000 which is 50 minutes but you set it to whatever you like.

6. Next, a few more lines down you should see "memory limit = 128M". You'll want to increase this as well, how much depends on how many resources your server has available. I provisioned (built) my server with 8GB of RAM so I just quadrupled the amount to 512 megabytes. You'll want the values to look like this:
![Screenshot_4456](https://github.com/BookStackApp/BookStack/assets/166672041/e1724b66-c109-4b56-a82f-41a050a7b740)

7. Once the values have been updated, you need to press "CTRL + X" to exit. You'll be asked if you want to save. Press "y". You'll then be asked what you want to name the file. It should be autofilled with "php.ini" already so just hit enter. If you have sufficient permissions, that should be it and you'll be back at the command line. Otherwise you'll receive an error stating you don't have permission.

8. Once this is done, restart your server. I just restarted ubuntu completely and it worked. If you can't or don't want to restart the server there are ways to restart webservers via the command line. In my case with apache, I used the command:
`/etc/init.d/apache2 restart`

9. Once your server is back up, go back to your BookStack instance and try the export again. Remember it will give you a blank page and probably sit there for a long time but just let it do it's thing.

Hopefully that's helped you out. Good luck!

**Comment by ssddanbrown** [comment]
Happy to hear you found the solution to your issue @YID-C, and thanks for sharing your resolution steps.
I'll therefore close this off.
