### ISSUE TITLE
screen layout on large screen

### ISSUE THREAD

**Issue by ap2de** [BookStackApp/BookStack#4947]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

On large screens the main text of the page could be larger.
The navigation column on the left hand side is fine, also the column with details and action on the right hand side.
But in the main of the page, where the content is, the column is too small and could be wider.
How can I change the width?
See screenshot blow

Also nice would be if the two lines of the back/forth navigation would have a lower spacing between the lines and if i could place them (additionally) below the breadcrumbs.

Any idea how to change the two topics?

Thank you very much for your ideas!

![bookstack](https://github.com/BookStackApp/BookStack/assets/24654693/557fcf2c-8d8d-4a9e-94af-8aa6e16fcdd6)

### Exact BookStack Version

BookStack v24.02.3

### Log Content

n/a

### Hosting Environment

docker using portainer on synology nas.
image: image: lscr.io/linuxserver/bookstack

**Comment by ssddanbrown** [comment]
Hi @ap2de, We generally work to a certain fixed max-width in BookStack.
A previous discussion with some workarounds to make the main content wider can be found in #1757.

> Also nice would be if the two lines of the back/forth navigation would have a lower spacing between the lines and if i could place them (additionally) below the breadcrumbs.

You'd need to get into [methods of customization/hackery](https://www.bookstackapp.com/docs/admin/hacking-bookstack/) to alter the existing design/layout.

**Comment by virtadpt** [comment]
For what it's worth, I've been tinkering with this to try to fix it, and haven't quite gotten it yet.
