### ISSUE TITLE
Add Scala to list of supported languages in code blocks

### ISSUE THREAD

**Issue by wbradley93** [BookStackApp/BookStack#4953]
### Describe the feature you'd like

I'd like to be able to add Scala snippets to some of my pages with full syntax highlighting.

### Describe the benefits this would bring to existing BookStack users

This would enable the use of Scala in pages.

### Can the goal of this request already be achieved via other means?

Not sure.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @wbradley93,
It looks like we're already importing scala, but just not showing it in the list, I've targeted this for next feature release to expose the option in the list.
If you type in `scala` to the language input in the code editor popup (at the top of the language list) you should find your code gets highlighted as desired.

**Comment by ssddanbrown** [comment]
Scala has now been added to the language list as part of 80ac66e0a665d23f05685753318b56b2307ce6f2 which will be part of the next feature release.
