### ISSUE TITLE
Update Bookstack form BookStack v23.12.2 to BookStack v24.02.3

### ISSUE THREAD

**Issue by Tutnich** [BookStackApp/BookStack#4954]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi,

i want to Update my Instance. But i get an Error:

apt update
apt upgrade
cd /var/www/bookstack
sudo composer self-update

git pull origin release

Aktualisiere 9441e32c..606f9d92
Fehler: Ihre lokalen Änderungen in den folgenden Dateien würden durch den Merge
überschrieben werden:...

He cannot carry out the update, otherwise the data will be overwritten.

Source:
https://www.bookstackapp.com/docs/admin/updates/
Thanks for your help!

### Exact BookStack Version

BookStack v23.12.2

### Log Content

Von https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
Aktualisiere 9441e32c..606f9d92
Fehler: Ihre lokalen Änderungen in den folgenden Dateien würden durch den Merge
überschrieben werden:
        .github/translators.txt
        app/Access/Oidc/OidcOAuthProvider.php
        app/Access/Oidc/OidcService.php
        app/Access/RegistrationService.php
        app/Activity/ActivityQueries.php
        app/Activity/CommentRepo.php
        app/Activity/Controllers/CommentController.php
        app/Activity/Controllers/FavouriteController.php
        app/Activity/Models/Comment.php
        app/Activity/Tools/CommentTree.php
        app/Api/ApiDocsGenerator.php
        app/App/HomeController.php
        app/App/Providers/ThemeServiceProvider.php
        app/App/PwaManifestBuilder.php
        app/Config/clockwork.php
        app/Config/filesystems.php
        app/Console/Commands/CopyShelfPermissionsCommand.php
        app/Console/Commands/RegenerateCommentContentCommand.php
        app/Entities/Controllers/BookApiController.php
        app/Entities/Controllers/BookController.php
        app/Entities/Controllers/BookExportApiController.php
        app/Entities/Controllers/BookExportController.php
        app/Entities/Controllers/BookSortController.php
        app/Entities/Controllers/BookshelfApiController.php
        app/Entities/Controllers/BookshelfController.php
        app/Entities/Controllers/ChapterApiController.php
        app/Entities/Controllers/ChapterController.php
        app/Entities/Controllers/ChapterExportApiController.php
        app/Entities/Controllers/ChapterExportController.php
        app/Entities/Controllers/PageApiController.php
        app/Entities/Controllers/PageController.php
        app/Entities/Controllers/PageExportApiController.php
        app/Entities/Controllers/PageExportController.php
        app/Entities/Controllers/PageRevisionController.php
        app/Entities/Controllers/PageTemplateController.php
        app/Entities/Controllers/RecycleBinController.php
        app/Entities/Models/Book.php
        app/Entities/Models/BookChild.php
        app/Entities/Models/Chapter.php
        app/Entities/Models/Page.php
        app/Entities/Queries/EntityQuery.php
        app/Entities/Queries/Popular.php
        app/Entities/Queries/RecentlyViewed.php
        app/Entities/Queries/TopFavourites.php
        app/Entities/Repos/BaseRepo.php
        app/Entities/Repos/BookRepo.php
        app/Entities/Repos/BookshelfRepo.php
        app/Entities/Repos/ChapterRepo.php
        app/Entities/Repos/PageRepo.php
        app/Entities/Repos/RevisionRepo.php
        app/Entities/Tools/BookContents.php
        app/Entities/Tools/Cloner.php
        app/Entities/Tools/MixedEntityListLoader.php
        app/Entities/Tools/PageContent.php
        app/Entities/Tools/PageEditorData.php
        app/Entities/Tools/ShelfContext.php
        app/Entities/Tools/SiblingFetcher.php
        app/Entities/Tools/TrashCan.php
        app/Http/DownloadResponseFactory.php
        app/Http/Kernel.php
        app/Permissions/JointPermissionBuilder.php
        app/Permissions/PermissionsController.php
        app/References/CrossLinkParser.php
        app/References/ModelResolvers/BookLinkModelResolver.php
        app/References/ModelResolvers/BookshelfLinkModelResolver.php
        app/References/ModelResolvers/ChapterLinkModelResolver.php
        app/References/ModelResolvers/PageLinkModelResolver.php
        app/References/ModelResolvers/PagePermalinkModelResolver.php
        app/References/ReferenceController.php
        app/References/ReferenceFetcher.php
        app/Search/SearchController.php
        app/Search/SearchRunner.php
        app/Settings/MaintenanceController.php
        app/Theming/ThemeEvents.php
        app/Translation/LocaleManager.php
        app/Uploads/Attachment.php
        app/Uploads/AttachmentService.php
        app/Uploads/Controllers/AttachmentApiController.php
        app/Uploads/Controllers/AttachmentController.php
        app/Uploads/Controllers/GalleryImageController.php
        app/Uploads/Controllers/ImageGalleryApiController.php
        app/Uploads/ImageRepo.php
        app/Uploads/ImageService.php
        app/Users/Controllers/UserProfileController.php
        app/Users/Queries/UserContentCounts.php
        app/Users/Queries/UserRecentlyCreatedContent.php
        app/Util/HtmlDescriptionFilter.php
        composer.lock
        database/factories/Activity/Models/CommentFactory.php
        dev/api/requests/chapters-create.json
        dev/api/requests/chapters-update.json
        dev/api/responses/chapters-create.json
        dev/api/responses/chapters-read.json
        dev/api/responses/chapters-update.json
        lang/ar/activities.php
        lang/ar/common.php
        lang/ar/editor.php
        lang/ar/entities.php
        lang/ar/errors.php
        lang/ar/settings.php

### Hosting Environment

PHP 8.2
Debian 12
Apache 2.4
MariaDB 10.11.6-MariaDB-0+deb12u1 Debian 12

**Comment by ssddanbrown** [comment]
Hi @Tutnich,

Please can you:

- Run `git config core.fileMode false` then confirm the output of `git status`.
- Confirm if you've made any intentional changes to BookStack source/app files?

**Comment by Tutnich** [comment]
Thanks Dan.
That solved my Problem.

**Comment by ssddanbrown** [comment]
Good to hear! Will therefore close this off.
