### ISSUE TITLE
An upgrade is required on your databases

### ISSUE THREAD

**Issue by truthsword** [BookStackApp/BookStack#4958]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When launching the container, my logs shows:

![](https://i.imgur.com/9GXKEZ0.png)

I am clueless. How do I stop the bookstack service (docker compose has both bookstack and maria), to allow this update.

Is this update done inside the maria container as such:

`docker exec -it <container_name> mariadb-upgrade -u root -p<PASSWORD>`

Or is this simply related to the fact that my compose file prescribes the maria version...

`image: lscr.io/linuxserver/mariadb:10.11.6`

If so, what version may I safely move to.

### Exact BookStack Version

24.02.3 

### Log Content

![](https://i.imgur.com/9GXKEZ0.png)

### Hosting Environment

Docker 26.0.1

**Comment by ssddanbrown** [comment]
@truthsword Just an FYI, this isn't within our realm of responsibility, that's all to do with the linuxserver mariadb docker image I guess.

I would:

1. Stop the entire docker `docker compose down`.
2. Take a backup of all volume files for all containers in the stack to be safe.
3. Access bash in the `bookstack_db` container `docker compose run bookstack_db /bin/bash`
4. Run the advised command `mariadb-upgrade -u root -p<PASSWORD>` (Replacing `<PASSWORD>` for the one you've set as the root password)

**Comment by truthsword** [comment]
Thank you. That worked perfectly.
