### ISSUE TITLE
CSS resources missing

### ISSUE THREAD

**Issue by nekromoff** [BookStackApp/BookStack#496]
`BookStack/css/styles.css` does not exist, neither does `BookStack/public/css/styles.css`, nor `BookStack/assets/css/styles.css`

**Comment by ssddanbrown** [comment]
Hi @nekromoff,
I'm going to assume you cloned down or downloaded the master branch files. Master branch does not come with built CSS files.

Try using the release branch. Let me know if that doesn't work.

**Comment by nekromoff** [comment]
Yes, thank you. Is there specific reason, why CSS is not included in the master?

**Comment by nekromoff** [comment]
Yes, thank you. Is there specific reason, why CSS is not included in the master?

**Comment by ssddanbrown** [comment]
@nekromoff Yeah, The styles are built from SCSS so any CSS files are not really the application source. Including them would bulk out commit diffs during development. Much cleaner to exclude them.

Same goes for the JavaScript.

I'll close this now you've found a solution.
