### ISSUE TITLE
Differences of line-heights for paragraphs in table cells between editor and page view

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#4960]
Need to align these line heights, and decide which one to use as definitive (maybe the view line height?)

**Comment by urvishdevelops** [comment]
Can you provide me screenshot or any reference it will help me to understand design issue better

**Comment by ssddanbrown** [comment]
@urvishdevelops Notice the inconsistent difference of text line heights of table content:

### In Editor

![image](https://github.com/BookStackApp/BookStack/assets/8343178/f325c919-611a-4cf4-9765-69c12319ca73)

### Outside of Editor (Page View)

![image](https://github.com/BookStackApp/BookStack/assets/8343178/ae00a834-a364-41b2-99cf-efe0fde740a8)

**Comment by urvishdevelops** [comment]
Thanks for providing more clarity on the issue. I will get back to you soon.
