### ISSUE TITLE
About restore a backup

### ISSUE THREAD

**Issue by 9acca9** [BookStackApp/BookStack#4961]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Well i just install bookstack in a Debian lxc with the script instructions file. I dont change it.
Later i try to restore a backup file that i already have.

i then follow the backup / restore document.
And........ it all work fine!!! (but, all work fine?)

Im asking here because in the backup / restore document it says 

> If you are restoring from scratch follow the [installation](https://www.bookstackapp.com/docs/admin/installation) instructions first to get a new BookStack instance set-up but do not run the php artisan migrate installation step when installing BookStack. You may need to comment this command out if using an installer script.

and yes i install from this script: https://www.bookstackapp.com/docs/admin/installation/#ubuntu-2004

But, just see this info of "php artisan migrate" --- " comment this command out if using an installer script" after already installed bookstack.

The thing is that i say "well, i dont care, lets see if works anyway". And IT WORKS! 

But then, that is wrong in the documentation? or could be that something is not well restored in my bookstack?

well, just that, im looking for i recall, and it seems was all recovered, but, i could be wrong.
And in case is all good, maybe that "comment out php artisan migrate" is old in the documentation?

Well, thanks for all!

### Exact BookStack Version

24.02.3

### Log Content

nothing

### Hosting Environment

Debian LXC

**Comment by ssddanbrown** [comment]
> maybe that "comment out php artisan migrate" is old in the documentation?

No, that's still current and valid advice. It's best to restore into a blank database otherwise there can be issues, and those issues may not show right away.

If the backup you restored was for the same version of BookStack, you might be okay, but it can depend on specifics of the backup format and data, therefore we just keep to the advise of restoring into an empty database.

**Comment by 9acca9** [comment]
Ok, yes, i believe..... believe... that it is the same version. 
Thanks for clarify!
