### ISSUE TITLE
Request for help using the Logical Theme system to enable logging in via url parameters

### ISSUE THREAD

**Issue by cepm-nate** [BookStackApp/BookStack#4962]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I'd like to use embedded iframes for an in-house call scripting setup. I'd like to use one of the chapters as the jumping-off point for the call script. Embedding an Iframe took a little bit of tweaking to the .env file (ALLOWED_IFRAME_HOSTS), as well as the hack for iframe embedding. Those are well written and understandable! :-)

I've delved into writing a functions.php within my /BookStack/themes/custom folder, and can hook into the APP_BOOT event. And I can grab the parameters from the url. But I've run into a lack of knowledge on how to login the user from that point on.

It's been quite a while since I've been in PHP, and I'm not familiar with the framework. I've been reading thru the source files from a repository search here for 'login', and my brain is starting to hurt.

Is there any chance someone has cooked something like this up for either the functions.php file on the APP_BOOT event, or could point me to an example of where the app does the "check user against DB, then tell framework which user is logged in" code so I can dig further?

Thank you so much!

Our CSR exclaimed "This is so much better than the old WIKI" when shown bookstack. :-) It really does look nice and the organization of shelves - > books -> chapters -> pages is logical and easy for anyone to follow. Totally loving it!

### Exact BookStack Version

v24.02.03

### Hosting Environment

PHP 8.3 on IIS (I don't think this relevant)

**Comment by ssddanbrown** [comment]
Good to hear you're liking BookStack!

>> But I've run into a lack of knowledge on how to login the user from that point on.

Here's an example:

```php
<?php

use BookStack\Theming\ThemeEvents;
use BookStack\Facades\Theme;
use BookStack\Users\Models\User;
use Illuminate\Http\Request;

Theme::listen(ThemeEvents::WEB_MIDDLEWARE_BEFORE, function (Request $request) {
    $userEmailParam = $request->query('as_user_email');

    // Ignore if no email parameter or if already logged in
    if (!$userEmailParam || auth()->check()) {
        return;
    }

    // Log user in if user matching email is found
    $user = User::query()->where('email', $userEmailParam)->first();
    if ($user) {
        // Silent direct login:
        auth()->login($user);

        // Login via app process which includes MFA, email confirmations, logging etc...
        // See https://github.com/BookStackApp/BookStack/blob/f32cfb4292f7e3b723b5f99aab17d0f3989c93b7/app/Access/LoginService.php#L26-L54
        // Uncomment two lines below, and comment auth line above, to activate:
        //$loginService = app()->make(\BookStack\Access\LoginService::class);
        //$loginService->login($user, 'custom_query_auth');
    }
});

```

_**Note: The above is a significant insecure addition so please don't add to your instance unless you understand the risk and how that applies to your usage context of BookStack.** Also, this customization uses BookStack internal code which could break upon future update._

There's a couple of options in there depending on what you need. Users will remain logged in from that point onward for the email user for the duration of their session. Let me know if you need any part/detail explained further.

**Comment by cepm-nate** [comment]
Thanks so much for the sample code and help! That points me in the right direction! and I can see how it'd be rather insecure (someone guessing the admin e-mail).

I'll work on adding a couple extra unknowns to make it a little trickier for this particular use case. :-)

Thanks again!
