### ISSUE TITLE
Error when empty trash

### ISSUE THREAD

**Issue by phmassa** [BookStackApp/BookStack#4966]
### Describe the Bug

when try to empty trash
with debug :

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'default_template_id' in 'where clause' (SQL: update `chapters` set `default_template_id` = ?, `chapters`.`updated_at` = 2024-04-22 08:51:59 where `default_template_id` = 1082 and `chapters`.`deleted_at` is null)

### Steps to Reproduce

click to "empty trash"

### Expected Behaviour

message : error unknow

### Browser Details

Firefox 125

### Exact BookStack Version

24.02.2

**Comment by ssddanbrown** [comment]
Hi @phmassa,
This indicates your database state is not up-to-date for the current version of BookStack.

- Did you see any errors when last attempting to update?
- Can you share the full output when re-running the `php artisan migrate` update step?

**Comment by phmassa** [comment]
do the last update 24.02.3, 

> php artisan migrate
>                                                                            APPLICATION IN PRODUCTION.
>   Do you really wish to run this command? (yes/no) [no]
> ❯ yes
> 
>    INFO  Running migrations.
> 
>   2024_01_01_104542_add_default_template_to_chapters ..................................................................................... 22ms DONE
>   2024_02_04_141358_add_views_updated_index .............................................................................................. 23ms DONE

now, it's ok
thx

**Comment by ssddanbrown** [comment]
> now, it's ok   thx

Good to hear, just be sure to run all commands (one by one) when updating, and note down any errors that appear on first run. Will therefore close this off.
