### ISSUE TITLE
Hide preview of pages

### ISSUE THREAD

**Issue by viisking** [BookStackApp/BookStack#498]
Under Books, it shows pages and their preview. 
Is there any way to hide page's preview, so it looks more simple and clean?
Thanks

**Comment by Alwaysin** [comment]
I second this. When you have code for example, the preview is hideous!

**Comment by ezzra** [comment]
You can use a workaround with CSS, use this as custom head in your settings:

```
<style>
.text-muted.break-text {
    display: none
}
</style>
```

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off, with the intention of such tweaks being made via our flexible customization options, as per the css tweak shared above.
