### ISSUE TITLE
Customization -> custom html style applies not on settings page

### ISSUE THREAD

**Issue by clemone210** [BookStackApp/BookStack#4980]
### Describe the Bug

When using customized style within the settings it is applied everywhere, except the settings page.
Is it intentional?

### Steps to Reproduce

1. Set primary color to white
2. Set custome style to include:
```
.button {
    color: #000;
}

header .links a {
    color: #000;
}

header .user-name {
    color: #000;
} 
```

### Expected Behaviour

Apply custom style also to settings page.

### Screenshots or Additional Context

![Screenshot 2024_04_30 16-57-14](https://github.com/BookStackApp/BookStack/assets/43761260/4b1fdec7-a31f-4293-b085-6570e997e077)
![Screenshot 2024_04_30 16-57-07](https://github.com/BookStackApp/BookStack/assets/43761260/e01c5b8c-4748-404c-831a-31c3b283286f)

### Exact BookStack Version

v24.02.3

**Comment by ssddanbrown** [comment]
> Is it intentional?

Hi @clemone210, yeah, this is intentional and should be mentioned below in input box:

![image](https://github.com/BookStackApp/BookStack/assets/8343178/31fbe996-2009-4990-ac49-775f566e5ea8)

**Comment by clemone210** [comment]
Closed for stupidity.
