### ISSUE TITLE
SMTP Email configuration generate error

### ISSUE THREAD

**Issue by Thomas-Lecuppre** [BookStackApp/BookStack#4981]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I configured the SMTP email service like the docs but, when trying to send an email from the web gui, I always get the same error and no logs in laravel.log file (and yes I set the right permission to those folder as asked in docs)

Here is the error message 
![image](https://github.com/BookStackApp/BookStack/assets/71729025/a01b7c32-6a8b-4db3-9ce3-26dc9c5e0e20)

Here is my config in .env file :

MAIL_DRIVER=smtp
MAIL_HOST=ssl0.ovh.net
MAIL_PORT=465
MAIL_USERNAME=contact@mydomain.ovh
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=tls
MAIL_VERIFY_SSL=true (test with and without and with true and false, changged nothing)

I also got a nextcloud app on my network that use those same credentials and I could get email from it.

![image](https://github.com/BookStackApp/BookStack/assets/71729025/ad051189-1471-46d4-83d2-5dd8c5824536)

### Exact BookStack Version

24.02.3

### Log Content

No log generated..

### Hosting Environment

Ubuntu server 22.04.4_amd64

**Comment by ssddanbrown** [comment]
Hi @Thomas-Lecuppre,

- Does your `MAIL_PASSWORD` contain any special characters?
- Can you share the output of running `ls -al bootstrap/cache` from your BookStack install directory?

**Comment by Thomas-Lecuppre** [comment]
Hi @ssddanbrown , thank you for your reply.

Of course my password contains specials characters (since it hasn't been mentioned in the docs that it shouldn't).
When I run your command it say there is no such file or directory.

I tried to set a password with no special character and it's seems to work well. 
Maybe it can be mentioned in the wiki on this page :

https://www.bookstackapp.com/docs/admin/email-webhooks/

Thank you for helping.

**Comment by ssddanbrown** [comment]
@Thomas-Lecuppre Do the special characters used include a space and/or hash?

**Comment by Thomas-Lecuppre** [comment]
@ssddanbrown @, # and *

**Comment by ssddanbrown** [comment]
@Thomas-Lecuppre Okay, then it was likely the hash causing trouble.
This is something mentioned at the top of the env file: https://github.com/BookStackApp/BookStack/blob/493d8027cd99656cdbeb92c01da99b5baa485a09/.env.example#L6-L7

Since you've managed to find and address the issue here I'll close this off.
