### ISSUE TITLE
Uploaded mp4 video doesn't play in Safari

### ISSUE THREAD

**Issue by yuelu714** [BookStackApp/BookStack#4983]
### Describe the Bug

Upload and attach a video in Safari.  The video doesn't play in Safari but does in Chrome and Firefox.

### Steps to Reproduce

1. Edit a page
2. Upload a video and attach to the page
3. Save and try to play the video

### Expected Behaviour

The attached video should play in Safari.  I have attached one of the videos we used.

https://github.com/BookStackApp/BookStack/assets/10090006/7ade976d-1cf9-4a7f-adea-eea31e3080ff

### Exact BookStack Version

We are currently on BookStack v24.02.2, but I don't think it ever worked on any version of Safari.

**Comment by ssddanbrown** [comment]
Hi @yuelu714,
I've just tested this, on both Safari on Mac (17.4.1) and Safari on iPad.
In my tests the video played without issue when embedded via an attachment.
Therefore I've not yet been able to replicate the issue.

- Within your BookStack `.env` file (or environment options if running via a docker solution) do you have any options set that start with `STORAGE_`?
- Does the video show up at all on the page when you get this error? (Do you still see the first frame of the video before play is pressed?)
- If you drag the video file direct into the URL bar in Safari, does the video show & play okay for you?

**Comment by yuelu714** [comment]
Hi Dan,

The videos we attached before did not play at all.  We re-attached the same videos to the page.  They actually play now.  So it is fixed.  Thanks.

**Comment by ssddanbrown** [comment]
Good to hear they play now! I'll therefore close this off.
