### ISSUE TITLE
Add rating section for Pages

### ISSUE THREAD

**Issue by nie3mals** [BookStackApp/BookStack#4989]
### Describe the feature you'd like

allow end users to rate pages and articles if they are usefull:

![image](https://github.com/BookStackApp/BookStack/assets/42218569/f5e13446-c5e5-4c68-b527-fb4308290407)

this would be helpfull to discover helpfull articels. those ratings should be filtered per Shelf / Book...

![image](https://github.com/BookStackApp/BookStack/assets/42218569/76233f77-8d1a-4519-8ece-4603d134a104)

### Describe the benefits this would bring to existing BookStack users

Improves content of articels. Helps to maintain the content better. Gives more statistics

### Can the goal of this request already be achieved via other means?

Maybe with Tags and allow to add them by End Users

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @nie3mals but I'd consider this already covered by previous issues #4722, #1524 and #505 so I'm going to therefore close this off as a duplicate.

**Comment by nie3mals** [comment]
I see, sorry I was only checking the **open** feature request! thanks for the prompt response!
