### ISSUE TITLE
changing language does not work

### ISSUE THREAD

**Issue by nekromoff** [BookStackApp/BookStack#499]
I have changed language (locale) both in `.env` and `config/app.php`, but to no avail. Language is still EN. 

Language exists in `resources/lang/` as it comes with the release.

**Comment by ssddanbrown** [comment]
Hi @nekromoff Can you undo any changes in `config/app.php` and confirm the values you are setting in the `.env` file.

Also confirm if the language you see on login is different to that once logged in. Language is also a per-user setting defined in your profile settings once logged in.

**Comment by timoschwarzer** [comment]
@nekromoff Have you cached your config files (`php artisan config:cache`) ? If yes, try to flush the cache.

**Comment by nekromoff** [comment]
Yes, clearing cache using `artisan` has resolved this.
