### ISSUE TITLE
Improve search dialog for Tags

### ISSUE THREAD

**Issue by nie3mals** [BookStackApp/BookStack#4990]
### Describe the feature you'd like

The search page which pops up could also display directly Tags, so that I can select the Tags and see all assigned Books / Pages. 
Here an Idea:
![image](https://github.com/BookStackApp/BookStack/assets/42218569/0a7ea712-4f80-4e04-a316-65467b2d848b)

### Describe the benefits this would bring to existing BookStack users

easier use of Tags and find Pages which have Tag assigned

### Can the goal of this request already be achieved via other means?

with the search page, which is however not interlinked with the search bar from the Top

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @nie3mals, but I'd consider the fundamental request here already covered by existing open issue  #2829, with https://github.com/BookStackApp/BookStack/issues/3565 being related.
I'll therefore close this off as a duplicate.
