### ISSUE TITLE
Allow to assing Thumbnail to Pages / Books

### ISSUE THREAD

**Issue by nie3mals** [BookStackApp/BookStack#4991]
### Describe the feature you'd like

It would be nice to allow to add some thumbnails to the pages. this can be used to enrich the pages representation in certain UI elements. Here an example:

![image](https://github.com/BookStackApp/BookStack/assets/42218569/7ad2810d-4447-4883-bcd9-cfa2169913be)

Can be easy integrated in the Page Edit page, as example 

![image](https://github.com/BookStackApp/BookStack/assets/42218569/ca29f298-7aa3-4f7c-9ae7-1d3d9ba964f1)

### Describe the benefits this would bring to existing BookStack users

more visual enrichment for the pages

![image](https://github.com/BookStackApp/BookStack/assets/42218569/d0659d3b-c377-40c5-935f-11c34575f953)

### Can the goal of this request already be achieved via other means?

extension of the Cover image for the Books, allow similar feature for the pages

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @nie3mals, but I'd consider the fundamental request here to be already covered by existing issue  #2012 so I'm going to therefore close this off as a duplicate.
