### ISSUE TITLE
After upgrading from 23.x to 24.x, headers are not showing properly

### ISSUE THREAD

**Issue by bishu05** [BookStackApp/BookStack#4992]
### Describe the Bug

After upgrading from 23.x to 24.x, headers are not showing properly

1. entities.shelves
2. entities.books. etc

### Steps to Reproduce

1. upgrade from 23.x to 24.x

### Expected Behaviour

headers should be 
1. shelves
2. books etc

### Screenshots or Additional Context

<img width="1128" alt="image" src="https://github.com/BookStackApp/BookStack/assets/31779683/7f7d0e5c-685e-4f65-8ddc-5686daceaf73">

### Browser Details

Chrome Version 124.0.6367.119 (Official Build) (arm64)

### Exact BookStack Version

v24.02.3

**Comment by ssddanbrown** [comment]
Hi @bishu05,
Did you intentionally make any changes to the `resources/lang` translation files within your BookStack instance?
If not, find and delete the `resources/lang` folder within your instance. Be careful not to delete any other folder, might be safe to take a backup of your entire bookstack install folder first.

**Comment by bishu05** [comment]
Thanks @ssddanbrown   It's working after removing the lang folder.

Had just backed up all the files, folder & db. After that upgraded to 24.x. No changes done to any file.
