### ISSUE TITLE
Attachment upload validation error message appears are shown as JSON

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#4996]
Can reproduce via uploading a file larger than the app upload limit.
Could do with reducing line-height here to provide more room for text too.

![image](https://github.com/BookStackApp/BookStack/assets/8343178/fbb91903-67b5-4cc4-988c-4442f0984361)

**Comment by KiDxS** [comment]
Hey @ssddanbrown, 

Can I work on this issue?

**Comment by ssddanbrown** [comment]
@KiDxS Sure! But only if you're able to do so fairly soon (by the end of tomorrow) since this is assigned to the next patch already which I'm hoping to release soon, otherwise I'll take it back on.

**Comment by KiDxS** [comment]
Thanks for letting me know, Dan!

I'll start working on it after I get home in 2 hours. 

If I don't finish it by the end of tomorrow. Feel free to take it back on.

**Comment by KiDxS** [comment]
Hi @ssddanbrown , 

I don't think I can fix this by the end of tomorrow. 

I think I bit more than I can chew.

Feel free to take it back on.

**Comment by ssddanbrown** [comment]
Thanks for updating me @KiDxS.
I've now addressed this via 72c5141decb1d83910a81fd0c4bf77f4a463ce5c, to be part of the next patch release.
