### ISSUE TITLE
bug in documentation - /dev/docs /visual-theme-system.md & corresponding YouTube video

### ISSUE THREAD

**Issue by mkduew** [BookStackApp/BookStack#4998]
### Describe the Bug

under "Customizing Text Content" it says:

"Folders with PHP translation files placed in a themes/<theme_name>/lang folder will override translations defined within the **resources/lang** folder."

That is not correct. Correct is:

"Folders with PHP translation files placed in a themes/<theme_name>/lang folder will override translations defined within the **lang** folder."

Also it is described wrong in the corresponding YouTube video = [[Customize BookStack using the Visual Theme System](https://www.youtube.com/watch?v=gLy_2GBse48&t=326s)](https://youtu.be/gLy_2GBse48?si=H4-zKESyugPGuqlH&t=291)

### Steps to Reproduce

1. see documentation
2. see YouTube video

### Expected Behaviour

---

### Exact BookStack Version

24.05

**Comment by ssddanbrown** [comment]
Thanks for raising @mkduew, I agree the docs should be updated. I'd consider the video (and all our videos) a point-in-time kind of thing though so I won't attempt to alter that.
