### ISSUE TITLE
Users are not shown any templates

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#5000]
### Describe the Bug

I have specified a template for a book, but when users with editor rights create a new page in the book, they are not offered the template.

### Steps to Reproduce

1. create book
2. create template
3. insert template in book

### Expected Behaviour

That users are shown the template when they create a new page so that they can fill it in.

### Browser Details

Firefox

### Exact BookStack Version

v24.05

**Comment by ssddanbrown** [comment]
Hi @Tealk,

- Do users have view access to the original template page (if they go to it directly via link)?
- Do users see the template in the templates part of the sidebar toolbox when editing/creating a page?
- Is this the same if you create a new page within a book, and within a chapter of that book?

**Comment by Tealk** [comment]
> Do users have view access to the original template page (if they go to it directly via link)?

No, I thought I could hide the templates from the users so they wouldn't be confused by them.

**Comment by ssddanbrown** [comment]
@Tealk That'll be the issue then. You can instead add them to a permission limited book, but within a chapter that has view access (or specifically set permissions per-template), which should limit discoverability a little while allowing access to the template.

**Comment by Tealk** [comment]
So I could create a book that only the administration can view and edit access, with templates with view access for everyone and then nobody could see the templates on the shelf?

**Comment by ssddanbrown** [comment]
@Tealk They'd still be able to see the original template pages via lists or search etc..., but they won't be discoverable by walking down the heirachy (looking into a book/shelf then navigating down etc...)

**Comment by Tealk** [comment]
I think that would be a compromise.

**Comment by ssddanbrown** [comment]
Alrighty, I'll therefore close this off since the reported behaviour is as expected and as described within the UI.
