### ISSUE TITLE
Wrong notification preferences URL in email

### ISSUE THREAD

**Issue by kroomagnon** [BookStackApp/BookStack#5005]
### Describe the Bug

The notification preferences URL in the email points to a 404 page.

In the mail: bookstack.example.com/preferences/notifications
On the website: bookstack.example.com/my-account/notifications

### Steps to Reproduce

1. Watch a book.
2. Modify book (with other user).
3. Receive notification mail.
4. Mail contains wrong link to the notifications settings: /preferences/notifications

### Expected Behaviour

Proper link in the mail: /my-account/notifications

### Screenshots or Additional Context

https://github.com/BookStackApp/BookStack/blob/a3a776d4a6d3a4d8d79c2a27a0e89dd929bd8b14/app/Activity/Notifications/Messages/BaseActivityNotification.php#L46

https://github.com/BookStackApp/BookStack/blob/a3a776d4a6d3a4d8d79c2a27a0e89dd929bd8b14/routes/web.php#L245C93-L245C112

### Exact BookStack Version

v24.05

**Comment by ssddanbrown** [comment]
Thanks for reporting @kroomagnon, I've assigned this for the next patch release.

**Comment by ssddanbrown** [comment]
Resolved by @KiDxS via https://github.com/BookStackApp/BookStack/pull/5008, to be part of next patch release.
