### ISSUE TITLE
Logging of mails that could not be delivered.

### ISSUE THREAD

**Issue by Nexulo** [BookStackApp/BookStack#5015]
### Describe the feature you'd like

An entry should be added to the logs if an e-mail could not be delivered during registration. 

### Describe the benefits this would bring to existing BookStack users

In my case, I had mistakenly entered an invalid / non-existent e-mail address when registering. The application then showed a message/toastr after registration that the e-mail could not be sent.

After a few adjustments in EmailConfirmationService.php, I was able to see that I had entered an email address that did not even exist for my domain. 

It would be good if this were visible in the logs.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

### Additional context

I searched the issues here and saw that some people also had problems and possibly used a non-existent e-mail address to register.

**Comment by ssddanbrown** [comment]
Look like we've added extra handling and specific logging for this as part of the changes of d12e8ec92369959ce2f3f43c4e047ab28e735538, and thread #5195, which was part of v24.10 so I'm therefore going to close this off. Thanks for the original request here @Nexulo!
