### ISSUE TITLE
Missing avatars after update to Bookstack v24.05

### ISSUE THREAD

**Issue by ishaulov** [BookStackApp/BookStack#5019]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi! After upgrading from BookStack v24.02.2 to BookStack v24.05, all users have missing avatars. The avatar files in public/uploads/images/user remained, file and directory permissions remained the same. URL and .env don't change.
When I check the url of the avatar file, I see the default file name — user_avatar.png:  https://my_bookstak_domain_name.com/user_avatar.png

The upgrade was performed using standard commands: 
```
git pull origin release
composer install --no-dev
php artisan migrate
php artisan cache:clear
php artisan config:clear
php artisan view:clear
```

Please, help to solve the problem.

### Exact BookStack Version

v24.05

### Hosting Environment

Ubuntu 22.04
PHP 8.1.2-1ubuntu2.17 (cli) (built: May 1, 2024 10:10:07) (NTS)
Composer version 2.6.6 2023-12-08 18:32:26
[Default manual installation](https://www.bookstackapp.com/docs/admin/installation/#manual)

**Comment by ssddanbrown** [comment]
Hi @ishaulov,
This is likely due to #4999. If you create a webserver-writable `storage/framework/cache/data` directory in your BookStack install folder, or set `CACHE_DRIVER=database`, you may find these things start working again.
Otherwise we'll be reverting the relevant change for the next patch release.

**Comment by ishaulov** [comment]
Hi @ssddanbrown!
Indeed, I assigned the `www-data` user as the owner (`chown -R www-data:www-data storage/framework/cache/data`)  of the `storage/framework/cache/data` directory and the avatars reappeared.

Thank you very much for your help! ☺️
