### ISSUE TITLE
Wraping large code blocks

### ISSUE THREAD

**Issue by Alwaysin** [BookStackApp/BookStack#502]
### For Feature Requests

Desired Feature: wraping when a code block is too large, as it is already done when not a code block

### For Bug Reports

* BookStack Version: 0.18
* PHP Version: 7
* MySQL Version: 5.6 MariaDB

##### Expected Behavior

wraping

##### Actual Behavior

not wraping : 

![sans titre](https://user-images.githubusercontent.com/7189936/30250945-3a999240-9657-11e7-8cfc-5e475b23299d.png)

**Comment by ssddanbrown** [comment]
@Alwaysin Was that content a code block or inline code?

If a block, And you're upgrading from BookStack pre-v0.17 then try clearing the browser cache and see if that helps.

**Comment by Alwaysin** [comment]
What is the difference between the two?

I use ``` ``` for code, should I use something else?

I already was on 0.17.4 (where the behaviour was the same) and using another browser which never visited bookstack before, it does the same.

**Comment by ssddanbrown** [comment]
@Alwaysin Ah, You use the markdown editor then?

Yeah, triple backtick for code blocks, Single for inline code. triple backtick blocks should be transformed into codemirror instances when viewing the page. Do you see line numbers on your code blocks when viewing?

**Comment by Alwaysin** [comment]
Yzq I'm using MD editor.
I have no line numbers, and it is the same behaviour when I use single backtick :'(

**Comment by ssddanbrown** [comment]
@Alwaysin Can you give an example of the exact code format you use for a codeblock? Just want to ensure the syntax you're using is what I expect.

**Comment by Alwaysin** [comment]
Sure.

Neither are working:
````
```blablabla```

`blablabla`

**Comment by ssddanbrown** [comment]
@Alwaysin Can you try:

\```
blablabla
\```

(With the newlines)

**Comment by Alwaysin** [comment]
Ah, my bad! With the new lines I got line numbers and the scrolling bar as well, so it's all good.
Even though maybe wraping would be better than the scrolling bar?

**Comment by ssddanbrown** [comment]
I believe this was fixed in 2019 by c14611d14bfd87148fbd96c9e33ed171b01dbd6a so I'll therefore close this off.
Thanks for reporting @Alwaysin.
