### ISSUE TITLE
Request to open translation contribution for Bengali language in crowdin 

### ISSUE THREAD

**Issue by chirohorit** [BookStackApp/BookStack#5024]
### Language to Add

Bengali (bn, bn/bd)

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Sorry @chirohorit , I had missed this. Do you still desire to perform translations of BookStack in this language?

**Comment by chirohorit** [comment]
No problem. 

Yeah, surely. I am still game.

**Comment by ssddanbrown** [comment]
Hi @chirohorit,
Thanks for offering to translate.
Bengali has now been enabled for the BookStack Crowdin project: https://crowdin.com/project/bookstack/bn

If the language remains mostly incomplete for a while, it may be removed again.
Once the language is mostly complete, it will be added to the language list as an available preference option in-app.

**Comment by chirohorit** [comment]
Thanks Dan.

**Comment by chirohorit** [comment]
Hi @ssddanbrown 

I posted a discussion thread on crowdin for you. Whenever you can have a look at it, would be helpful for me to move forward. Thanks
