### ISSUE TITLE
Updated from 0.17.4 to 0.18.0, cannot open books

### ISSUE THREAD

**Issue by m4ntic0r** [BookStackApp/BookStack#503]
Updated from 0.17.4 to 0.18.0, cannot open books

i can login, but if i click on a book i get only "Whoops, looks like something went wrong."

i had this problem before, its a bit annoying after every update.
https://github.com/BookStackApp/BookStack/issues/287

laravel.log:
https://pastebin.com/QRQmMdrh

**Comment by ssddanbrown** [comment]
Hi @m4ntic0r, Sorry to hear you're having issues with the update.

This appears to be a different issue compare to your previous upgrade woes. 

Could you confirm your PHP & MySQL versions?
Also, Just confirm if the upgrade commands ran smoothly and if running `git status` from your BookStack install folder gives any output.

**Comment by m4ntic0r** [comment]
php: Version: 7.0.22-0ubuntu0.17.04.1
mysql: Version: 5.7.19-0ubuntu0.17.04.1

I have no explanation for this, but i restored my failed upgrade to previous working version via vmware snapshot and mysql backup and run the update with the same command again. now it works without any problems.

**Comment by dsaundersWizmo** [comment]
It sounds like you didn't get the comments column in your database.   

I had the same issue where it got flubbed in the composer install and didn't complete the php artisan migrate.  When I ran sudo php artisan migrate it completed updating the comment column.

**Comment by ssddanbrown** [comment]
Glad to hear this is now resolved, Will close this issue.
