### ISSUE TITLE
Feature Request: Collapsible headings in pages.

### ISSUE THREAD

**Issue by dsaundersWizmo** [BookStackApp/BookStack#504]
### For Feature Requests

Desired Feature:  Collapsible headings within pages.

When writing a longer page with lots of headings, it would be nice to be able to collapse the headings to be more reader friendly.

**Comment by ssddanbrown** [comment]
Hi @dsaundersWizmo, Thanks for opening this issue.

I may close this as it's very similar to #78. Let me know if it differs to that issue otherwise I'll close this some point soon.

**Comment by dsaundersWizmo** [comment]
Sure, apologies for not appropriately checking all the open issues!

**Comment by dsaundersWizmo** [comment]
I apologize if this is an inappropriate place to email the question, but is there a way to piggy back off the authentication for sub directories?

For example, I use the Sandcastle Help File Builder to generate the code documentation for our various pieces of software: https://github.com/EWSoftware/SHFB

Previously on an IIS based solution, I could use the web.config to deny unauthenticated access to subdirectories where I could upload the documentation.

Is there a way in Bookstack to put these in a subdirectory that can use the same authentication (LDAP based) to view the directory?  As it stands now if I place them in a sub folder they are publicly accessible.

From: Dustin Saunders
Sent: Tuesday, September 12, 2017 9:51 AM
To: 'BookStackApp/BookStack' <reply@reply.github.com>; BookStackApp/BookStack <BookStack@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [BookStackApp/BookStack] Feature Request: Collapsible headings in pages. (#504)

Sure, apologies for not appropriately checking all the open issues!

**Comment by ssddanbrown** [comment]
Hi @dsaundersWizmo,
There may be a way to do this with your webser based on URL's.

Otherwise, Could you use the built in permission system within BookStack? Just create some roles, Allocate users to those roles then set permission on a book or chapter to stop other viewing the content.

**Comment by dsaundersWizmo** [comment]
Yeah, I can set up LDAP based authentication in the web configuration, but it acts like a 2nd login (which isn’t the end of the world, it would just be nice to be able to pass thru).  So on an IIS server with forms authentication, the login page will handle the authentication and in the web.config you can specify the directories or sub directories to require that same authentication.

What I was referencing is I use another application to generate a complete HTML site (MDSN style) with all the code documentation which is its own site; so unfortunately I wouldn’t be able to do that unless you could create a page that contains a child site.  I’ll play with it on my own to find a workaround (worst case scenario is just reauthenticating to view the detailed code documentation) but I appreciate your time to answer.

The app so far is great, looking forward to rolling our documentation over to it and using it as our new source.

**Comment by ssddanbrown** [comment]
@dsaundersWizmo Okay. Since the original issue is complete (As duplicate) I will now close this.
