### ISSUE TITLE
Desktop and Mobile app to work offline

### ISSUE THREAD

**Issue by nullgaro** [BookStackApp/BookStack#5042]
### Describe the feature you'd like

A desktop and / or a mobile app where you can access all your documentation and it's downloaded locally. You still can make updates offline and as soon as you get again access to Internet the documentation will be updated in the server. Kind of like OneNote

### Describe the benefits this would bring to existing BookStack users

Using my personal case, I travel a lot, and most of the time there's no signal or access to Internet. It would be very useful to still be able to use it even without connection

### Can the goal of this request already be achieved via other means?

I think no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by daffydock** [comment]
This request, specifically the mobile app that would allow editing while offline would truly be a great addition. I currently use a note app but if somehow offline access was available, I would drop it over Bookstack in a second. Since Bookstack is a better product and one that would allow for better organization and expansion.

**Comment by david-prv** [comment]
Hi, I think that this has been discussed some times already before, but mainly on the Discord. The main conclusion was that this would be a highly complex and maintenance intensive feature. Thus, I think that we shouldn't expect an official support soon or at all. 

However, it is possible to achieve similar things by other means. For example, you can use the API features to create an offline dump of all of your books and pages, cobbled with a cronjob this could become a reliable and up-to-date offline version of your notes. You could even extend that system and make it two-way, i.e. you can even update and sync changes to your online database as soon as you are online again, and not just read-only. But, in any case, this will require you to get your hands on programming and hacking a little.

Scan through the BS Hacking Directory. There you will find a basic template for a read-only local backup creator for your books and pages via the API.

Hope that helps.
KR

**Comment by david-prv** [comment]
I'll paste @ssddanbrown's answer here:
> Yeah, technically we could have the PWA cache page responses, but providing that as official functionality gets a bit messy when you start to think about permission control etc.... Some folks, as an alternative backup plan, automate exports to PDF for all books (which you could then sync via other means). I was thinking about creating a little companion mobile app, just to save specific pages with offline access in-app, but I don't want to get distracted with another side project.

**Comment by nullgaro** [comment]
I understand @ssddanbrown's point regarding the current state of the project.

While I am not fully aware of the existing hierarchy in BookStack, I believe it would be beneficial to explore the possibility of developing dedicated mobile and desktop applications. This would involve making the necessary adjustments to align with BookStack's standards to ensure feasibility and sustainability.

Given the maturity and scale of this project, I think creating these applications is crucial for its continued growth and usability.

**Comment by otherjoel** [comment]
Everyone hoping for BookStack’s sole developer to double/triple his workload in service of a free app, consider becoming a sponsor. https://github.com/sponsors/ssddanbrown

**Comment by david-prv** [comment]
> Everyone hoping for BookStack’s sole developer to double/triple his workload in service of a free app, consider becoming a sponsor. https://github.com/sponsors/ssddanbrown

Yeah. And also, I really doubt that an officially supported app would be necessary for the continued success of BookStack. As far as I'm aware of, many competitors such as for instance Wiki.js also don't offer such services. The goal for a local mirror of the documents can be achieved by other means. Didn't feel like this would have been an heavily requested feature, so far.

I agree, that Dan should continue to focus his work on the main application, namely BookStack itself. Beyond the fact that he is managing this project entirely alone, I believe that a second project is just not feasible to maintain in the same manner as he does for BS.

**Comment by ssddanbrown** [comment]
Yeah, I'd consider this as out of scope as the effort and large expansion in scope would not be worthwhile to support and maintain as an official offering. As touched on by @david-prv, we provide APIs that be used for external apps/solutions where required.

> Given the maturity and scale of this project, I think creating these applications is crucial for its continued growth and usability.

I don't really see that as true. Many have found BookStack to be usable without these elements being an official offering, and I don't strive for growth for the sake of growth, I focus on our core existing use-case and audience which tends to naturally bring growth.

> Everyone hoping for BookStack’s sole developer to double/triple his workload in service of a free app, consider becoming a sponsor.

Please don't sponsor with the expectation of that leading to anything requested here being achieved. Money is not a limiting/deciding factor for this. (Thanks though @otherjoel for the shout out and thanks @david-prv for the input and sharing my previous response).
