### ISSUE TITLE
Editor on wide-angle monitor

### ISSUE THREAD

**Issue by cosmicDustOfLightLength** [BookStackApp/BookStack#5047]
### Describe the feature you'd like

In full screen and normal editing mode.

There are empty spaces on a wide-angle monitor.
Is it possible to create a button to automatically adjust the content to the width of the window in edit mode?

Just as if we were editing a windowed program where we can adjust the window width, the editing field will adjust to our needs.

Or a button that allows you to expand the window in which the editor is open to 100%/75%/50% of the width?

![obraz](https://github.com/BookStackApp/BookStack/assets/71566296/081fe910-4176-479b-a94d-85a926811722)

![obraz](https://github.com/BookStackApp/BookStack/assets/71566296/ef92cffb-9897-4674-9513-b17d4106559c)

### Describe the benefits this would bring to existing BookStack users

Editing CSS/HTML to achieve such an effect does not require any work for every person. I see that many users have reported a minor problem and are suffering because of this while using this great app. Such a button or option in the settings can handle the matter cleanly and elegantly.

### Can the goal of this request already be achieved via other means?

Yes, but it is cottage industry carving and not befitting such a great application.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Hi @cosmicDustOfLightLength,

The edit view is intended to mirror the display view of page content. I wouldn't look to change the content width just for the edit view, or maintain addition options to support a variable max width.

The set content width has been discussed, with some potential  workarounds, in #1757.
I have previously provided my thoughts in regards to the set width in #3408.

**Comment by PhilippRieth** [comment]
I've thrown together some CSS and JavaScript that can be put into the "Custom HTML Head Content" -> [Extra Wide Pages and Editor for selected pages | Reddit
](https://www.reddit.com/r/BookStack/comments/1h0p79m/extra_wide_pages_and_editor_for_selected_pages/)

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off under the reasoning as provided in my last comment.
Thanks @PhilippRieth for sharing a potential workaround for those that desire it.
