### ISSUE TITLE
Create new user does not send email

### ISSUE THREAD

**Issue by rcarrascoz** [BookStackApp/BookStack#5051]
### Describe the Bug

When you create a new user and do click on checkbox send email for invitation, it does not send anything. Thanks :)

### Steps to Reproduce

create user

### Expected Behaviour

send mail to new user with invitation

### Browser Details

all browsers

### Exact BookStack Version

v24.05.1

**Comment by ssddanbrown** [comment]
Hi @rcarrascoz,
Does the "Send a Test Email" action in "Settings > Maintenance" work without error, and result in you receiving an email?

**Comment by biozic** [comment]
I have the same problem. The "Send a Test Email" command works, but no message is sent when a create a new user. Neither with the "Forgot password" action.

**Comment by ssddanbrown** [comment]
@biozic Have you set, or do you have, a `QUEUE_CONNECTION` option anywhere (in `.env` file or in container/system environment if relevant).

**Comment by biozic** [comment]
Well, forget it. I've just checked that the emails were actually sent just right, but blocked because of a DKIM mismatch 🙃

**Comment by ssddanbrown** [comment]
@biozic Good to hear you found the issue!
Since the original issue creator has not responded for some time I'll go ahead and close this off.
