### ISSUE TITLE
Changelog for first revision is hardcoded as "initial revision" and not respecting the given changelog

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#5056]
### Describe the Bug

If you set a changelog on the first revision of a page, eg. "Test", this gets not respected and will be overwritten by "intitial revision".
I've found the hardcoded part in the `/var/www/bookstack/app/Entities/Repos/PageRepo.php` on line 80.

### Steps to Reproduce

1. create a page and put in some content
2. insert a changelog "Test"
3. save the page
4. review the revisions and you will see "initital revision"

### Expected Behaviour

The revision should contain the given changelog if set.
if no changelog is set then the default would be fine.

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/9048534/b5fd8ca4-8996-49d3-b908-18a3ed965596)
Here I put in "Rollenbeschreibung erstellt" as a changelog, but it wasn't stored.

### Exact BookStack Version

24.02

**Comment by ssddanbrown** [comment]
Thanks for raising @Man-in-Black!
I've addressed this via a8ce199e0de8974c8be60450797301839a5d1e82, with test to cover, to be part of the next patch release.
