### ISSUE TITLE
Thumbnail via OIDC

### ISSUE THREAD

**Issue by jaapert** [BookStackApp/BookStack#5061]
### Describe the feature you'd like

For LDAP, there is the "LDAP_THUMBNAIL_ATTRIBUTE", which takes a via LDAP provided image. For OIDC this doesn't seem to be possible yet (we would need a OIDC_THUMBNAIL_CLAIM for example).

### Describe the benefits this would bring to existing BookStack users

This feature provides consistency with other authentication providers. With this, users would have their avatar that is provided by the OIDC identity provider without having to upload it themselves.

### Can the goal of this request already be achieved via other means?

Not that I'm aware of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for raising @jaapert, but I'm going to close this off since the fundemental request is already covered by existing issue #4271.
