### ISSUE TITLE
PDF Preview

### ISSUE THREAD

**Issue by 247no2** [BookStackApp/BookStack#5067]
### Describe the feature you'd like

Hello everyone,

Is it possible to upload a PDF document and display it not only as a URL, but also as a preview so that the content of the PDF is displayed on the page?

Currently I can only display a PDF as a link on the page.

Best regards

### Describe the benefits this would bring to existing BookStack users

You can see the content of the PDFs directly on the page instead of downloading all the PDFs, over and over again.

### Can the goal of this request already be achieved via other means?

Unfortunately no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

I am very satisfied with Bookstack

**Comment by Hallsie** [comment]
I would like this also.  It is not very useful to have the pdf download every time.

**Comment by reddexx** [comment]
Insert this code in Customize HTML

`<script>

  // Use BookStack editor event to add custom "Insert PDF" button into main toolbar
  window.addEventListener('editor-tinymce::pre-init', event => {
      const mceConfig = event.detail.config;
    mceConfig.toolbar = mceConfig.toolbar.replace('link', 'link insertpdf')
  });

  // Use BookStack editor event to define the custom "Insert PDF" button.
  window.addEventListener('editor-tinymce::setup', event => {
    const editor = event.detail.editor;
    
    // Add PDF insert button
    editor.ui.registry.addButton('insertpdf', {
        tooltip: 'PDF einfügen',
    icon: 'document-properties',
    onAction() {
        editor.windowManager.open({
            title: 'PDF Einfügen',
            body: {
                type: 'panel',
                items: [
                    { type: 'textarea', name: 'pdfurl', label: 'PDF URL' },
                    { type: 'input', name: 'sizeheight', label: 'Höhe (px)', placeholder: '500' }
                ]
            },
            onSubmit: function (e) {
                if (e.getData().sizeheight == '' || e.getData().sizeheight == undefined || e.getData().sizeheight == null) {
                    editor.insertContent('<object data="' + e.getData().pdfurl + '?open=true&amp;embedded=true" height= "500" width= "100%"></object>');
                    e.close();
                }
                else {
                    // Insert content when the window form is submitted
                    editor.insertContent('<object data="' + e.getData().pdfurl + '?open=true&amp;embedded=true" height= "' + e.getData().sizeheight + '" width= "100%"></object>');
                    e.close();
                }
            },




            onCancel: function (e) { e.close(); },

            buttons: [
                { type: 'submit', text: 'PDF Einfügen' },
                { type: 'cancel', text: 'Abbrechen' }
            ]
        });
      }
    });

  });

</script>`

**Comment by reddexx** [comment]
[https://github.com/BookStackApp/BookStack/issues/3586](url)

**Comment by kilian-goetz** [comment]
Greetings @247no2,

Have you tried specifying the ALLOWED_IFRAME_SOURCES variable in the .env file and setting the allowed sources from which you want previews? For example, I use this method to preview Google Forms or external PDFs inside my BookStack.

Kind regards, Kilian GOËTZ.

**Comment by ssddanbrown** [comment]
Thanks for the suggest @247no2, but I'd considered this already covered by existing issues #705 and/or #1270 so I'll therefore close this off.

**Comment by 247no2** [comment]
With the code and your own URL, you are now running. Thank you

<p>&nbsp;<canvas data-pdfurl="http://bookstack.cyx.com/attachments/**23**"></canvas>&nbsp;</p>

` <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.466/pdf.min.js"></script>
<style>
canvas[data-pdfurl] {
  background-color: lightgrey;
   width: 100%;
}
.page-content a {
 color: #39f;
text-decoration: underline;
}
.pdf-wrapper {
position: relative;
height: 80vh;
width: 100%;
}
.pdf-wrapper .download-link {
position: absolute;
top: -2em; 
right: 0;
z-index: 50;
}
.pdf-wrapper .pdf-scroller {
height: 100%;
overflow: auto;
}
</style>
<script type="text/javascript">
window.addEventListener('load', function () {
var renderPdf=function(canvas) {
  var url = canvas.dataset.pdfurl;
  var pdf = null;
  // wrap canvas in div
  var wrapper = document.createElement('div');
  wrapper.className='pdf-wrapper';
  var scroller = document.createElement('div');
  scroller.className='pdf-scroller';
  wrapper.appendChild(scroller);
  canvas.parentNode.insertBefore(wrapper, canvas.nextSibling);
  scroller.insertBefore(canvas, null);

  var downloadLink  = document.createElement('a');
  downloadLink.href = url;
  downloadLink.className="download-link";
  downloadLink.innerText = 'Download PDF now ↓';
  wrapper.appendChild(downloadLink);

  var renderPage = function(page) {
    var scale = 1.5;
    var viewport = page.getViewport(scale);
    // Fetch canvas' 2d context
    var context = canvas.getContext('2d');
    // Set dimensions to Canvas
    canvas.height = viewport.height;
    canvas.width = viewport.width;
    canvas.style.maxWidth='100%';
    // Prepare object needed by render method
    var renderContext = {
      canvasContext: context,
      viewport: viewport
    };
    // Render PDF page
    page.render(renderContext);
    if (currentPage < pdf.numPages) {
      currentPage++;
      var newCanvas = document.createElement('canvas');
      scroller.insertBefore(newCanvas, canvas.nextSibling);
      scroller.insertBefore(document.createElement('hr'), canvas.nextSibling);
      canvas=newCanvas;
      pdf.getPage(currentPage).then(renderPage);
    }
  };
  var currentPage = 1;
  pdfjsLib.getDocument(url)
  .then(function(pdfLocal) {
    pdf = pdfLocal;
    return pdf.getPage(1);
  })
  .then(renderPage);
}
Array.prototype.forEach.call(
  document.querySelectorAll('canvas[data-pdfurl]'),
  renderPdf);
});
</script>`
