### ISSUE TITLE
Fail to upgrade from v0.17.4 to v0.18.0

### ISSUE THREAD

**Issue by msaus** [BookStackApp/BookStack#507]
Hello there,

I fail to upgrade...

I run the following command.

git pull origin release && composer install && php artisan migrate
php artisan cache:clear
php artisan view:clear

Also, I have screen shot of it.

![image](https://user-images.githubusercontent.com/3432876/30420654-3a42502c-9975-11e7-9f0a-02d40cd0f8a8.png)

**Comment by ssddanbrown** [comment]
Hi @msaus,

The text towards the bottom of your screenshots show that you may have been on a `master` development branch if BookStack at some point since the text `{{vm.totalCommentsStr}}` has never been in a release.

Did you trial the comments system before the v0.18 release?

Please can you check you are on the `release` branch of BookStack. You can run `git status` in the BookStack directory to check this.

**Comment by msaus** [comment]
Hello there,

Ow....I was on master branch.

So, I switch to release branch now.

I did following.

git checkout release
git checkout .
rm -rf `git status --short | grep '??' | awk '{print $2}'`
php artisan view:clear 
 php artisan cache:clear

But, I am getting the same screen.....

**Comment by ssddanbrown** [comment]
@msaus Can you run `git status` within the BookStack folder and share the output?

**Comment by msaus** [comment]
Sorry for late reply.
here is my git status.
 
git status
On branch release
Your branch is up-to-date with 'origin/release'.
nothing to commit, working directory clean

**Comment by ssddanbrown** [comment]
@msaus Ah, That looks fine. Could try a `sudo php artisan cache:clear` to ensure it's not a caching problem. What do you see now? Broken styles or an error message?

**Comment by msaus** [comment]
It dose not change anything.....

![image](https://user-images.githubusercontent.com/3432876/30680679-fd7ca2c0-9edb-11e7-8223-0bb578fd65f0.png)

**Comment by AbijeetP** [comment]
Can you please run - 

```
git remote show origin
```

**Comment by msaus** [comment]
I got followings.

* remote origin
  Fetch URL: https://msaus:Haibara2@github.com/msaus/BookStack.git
  Push  URL: https://msaus:Haibara2@github.com/msaus/BookStack.git
  HEAD branch: master
  Remote branch:
    release tracked
  Local branch configured for 'git pull':
    release merges with remote release
  Local ref configured for 'git push':
    release pushes to release (up to date)

**Comment by msaus** [comment]
git log
*   0c2ec27 - (HEAD -> release, origin/release) a (7 days ago) <soseki>
|\  
| * 28a9bd5 - Updated header design (5 weeks ago) <Dan Brown>
| * 666c86b - Removed included fonts, Set to use system fonts. (5 weeks ago) <Dan Brown>
| * 1942936 - Removed v-show delayed content display (5 weeks ago) <Dan Brown>
| * 039ee5d - Aligned entity dash name and fixed chapter toggle on dash (5 weeks ago) <Dan Brown>
| * afc66b3 - Migrated attachment manager to vue (5 weeks ago) <Dan Brown>
| * a04b318 - Cleaned social callback (5 weeks ago) <Dan Brown>
| *   db3dde9 - Merge pull request #474 from timoschwarzer/translation_update_de (5 weeks ago) <Dan Brown>
| |\  
| | * 0d6a6b5 - Update/fix german translation (5 weeks ago) <Timo Schwarzer>
| |/  
| * d3e4a1a - Converted tag autosuggestion to vue component (6 weeks ago) <Dan Brown>
| * b023699 - Converted tag manager to be fully vue based (6 weeks ago) <Dan Brown>
| * f338dbe - Started vueifying tag system (6 weeks ago) <Dan Brown>
| * ab07f7d - Converted image manager into vue component (6 weeks ago) <Dan Brown>
| * a59d73d - Fixed bug causing image manager popup not to show (6 weeks ago) <Dan Brown>
| * 1ac7618 - Updated clipboard lib reference and version used (7 weeks ago) <Dan Brown>
| * 2a06988 - Converted jQuery bits into raw JS components (7 weeks ago) <Dan Brown>
| * 5e5928a - Added vanilla JS component system (7 weeks ago) <Dan Brown>
| * d6e8742 - Merged comment migrations and incremented dev version (7 weeks ago) <Dan Brown>
| *   79cfd39 - Merge branch 'Abijeet-master' (7 weeks ago) <Dan Brown>

**Comment by AbijeetP** [comment]
Here's the problem - https://github.com/msaus/BookStack/pull/1

You don't have the latest code. Please merge the above request, and then re-deploy.

**Comment by msaus** [comment]
Thank you very much for your help.
Now I am getting new v0.18!

**Comment by AbijeetP** [comment]
@msaus - Since everything is OK now, can you please close this issue?

**Comment by msaus** [comment]
Thank you :)

**Comment by ssddanbrown** [comment]
Thanks @AbijeetP, Didn't think about it being a fork 👍
