### ISSUE TITLE
Add Elixir to list of supported languages in code blocks

### ISSUE THREAD

**Issue by jakoubek** [BookStackApp/BookStack#5076]
### Describe the feature you'd like

I'd like syntax highlighting for the Elixir programming language in code blocks.

### Describe the benefits this would bring to existing BookStack users

Be able to read Elixir code blocks more easily.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

There is "elixir" in highlight.js : https://github.com/highlightjs/highlight.js/blob/main/src/languages/elixir.js

And yes, there is a ticket mentioning adding support for Elixir in the editor (#2125), but in the code editor it's not available nevertheless.

**Comment by ssddanbrown** [comment]
Thanks for the request @jakoubek, but I usually keep the scope of our supported languages to those we've previously added and/or those with official codemirror support, which I can't see for Elixir, so I'm therefore going to close this off.
