### ISSUE TITLE
Add HCL to list of supported languages in code blocks

### ISSUE THREAD

**Issue by simao-silva** [BookStackApp/BookStack#5085]
### Describe the feature you'd like

I would like to have syntax highlight for HCL code snippets.

### Describe the benefits this would bring to existing BookStack users

This would enable the syntax highlight of HCL code.

### Can the goal of this request already be achieved via other means?

Not sure.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

### Additional context

There is a npm package dedicated to the language: https://www.npmjs.com/package/codemirror-lang-hcl.

**Comment by ssddanbrown** [comment]
Thanks for the request @simao-silva, but I typically limit our language support to those that have official codemirror packages provided for, which HCL does not appear to have.

**Comment by ssddanbrown** [comment]
I'll therefore close this off as out of scope.
