### ISSUE TITLE
Adding tags results in 422 error in shelve, book, chapter, page API requests

### ISSUE THREAD

**Issue by ShajeeAmjad** [BookStackApp/BookStack#5087]
### Describe the Bug

I've been using Bookstack for development for a while and was wanting to add some tags to my content programmatically. However no matter what I do, it never works. I have tried the example data on the API docs, but even still it does not work.

Here is the code I am using:

`

    def create_shelf(api_url, api_token):
          shelf_url = f"{api_url}/shelves"
          headers = {
              'Authorization': f'Token {api_token}',
          }

        data = {
            "name": "My shelf",
            "description_html": "<p>This is <strong>my shelf</strong> with some books</p>",
            "books": [],
            "tags": [
              {"name": "Category", "value": "Learning"}
            ]
        }
    
        response = requests.post(shelf_url, headers=headers, data=data)
        
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Failed to create shelf. Status code: {response.status_code}")
            print(response.content.decode('utf-8'))
            return None

`

The result is always: Error 422, the data given was invalid, tags must be an array. Even though tags is clearly an array.

I have no clue what the problem is.

### Steps to Reproduce

Make the API request as above.

### Expected Behaviour

Should create a shelf with the given tags

### Browser Details

FireFox, latest version

### Exact BookStack Version

Bookstack latest version

**Comment by ssddanbrown** [comment]
Hi @ShajeeAmjad,

> Even though tags is clearly an array.

That would totally depend on how the requests library serializes the post data from the Python array, which I'd imagine to be different to the format BookStack accepts.

Instead, try sending the data as JSON:

```python
response = requests.post(shelf_url, headers=headers, json=data)
```

**Comment by ShajeeAmjad** [comment]
That seems to have worked, thank you for the quick response.
