### ISSUE TITLE
When I try to add an LDAP user as admin, the permissions do not save.

### ISSUE THREAD

**Issue by silvaguilherme** [BookStackApp/BookStack#5089]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

When I try to add an LDAP user as admin, the permissions do not save.
I change the .env (AUTH_METHOD=standard), then as admin.
I add my LDAP user as admin and save the page.
![image](https://github.com/BookStackApp/BookStack/assets/18178268/aaaa2a23-bacb-4903-9d2b-57368b6f9b12)
![image](https://github.com/BookStackApp/BookStack/assets/18178268/c56480ca-3e91-40ff-937d-233b29393158)

But when the user connects the application he loses the permissions.
![image](https://github.com/BookStackApp/BookStack/assets/18178268/677863a6-db81-40cc-800a-847eb099b5bc)

In my tests, the user only loses permission when logging into the application.
If I grant him permission, and he is logged in, he has admin permission until he logs out

### Exact BookStack Version

v24.05.2

### Hosting Environment

Oracle Linux

**Comment by ssddanbrown** [comment]
Hi @silvaguilherme,
I'm guessing you have the following option and values set:

```bash
LDAP_USER_TO_GROUPS=true
LDAP_REMOVE_FROM_GROUPS=true
```

In which case I'd expect the user to lose their admin role upon login unless this was mapping to a group in the LDAP system. If you intend for role assignments to remain, and not be removed by the LDAP group sync handling, you should set `LDAP_REMOVE_FROM_GROUPS` to `false`.

**Comment by silvaguilherme** [comment]
It worked
Thanks

**Comment by ssddanbrown** [comment]
Good to hear! Will therefore close this off.
