### ISSUE TITLE
Add Office 365/AzureAD as social auth option

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#509]
As title

**Comment by dsaundersWizmo** [comment]
Hey Dan,

Don't know if this is relevant to your idea here or not, but Azure can be configured for LDAPs-- which means your current LDAP config should work with it.
https://docs.microsoft.com/en-us/azure/active-directory-domain-services/active-directory-ds-admin-guide-configure-secure-ldap

It is a little more on the user side to set up as you need to install the appropriate certificates and adjust firewall settings as needed;  not saying one thing or another, just adding additional information to the thread.

**Comment by ssddanbrown** [comment]
Thanks for the info @dsaundersWizmo.

I'd like to add it as a social auth option though so it can be optionally used alongside main auth methods.
