### ISSUE TITLE
Reference in document in a table of contents type of way

### ISSUE THREAD

**Issue by mankiiii** [BookStackApp/BookStack#5090]
### Describe the feature you'd like

Basically like in the table of contents in a pdf or something where you can click on the section you want and you are then "teleported" to the section which is in the same document. For now as i can see you can only add a link taking you to another bookstack document or to another website(i think) but nothing regarding the same document and moving down.

### Describe the benefits this would bring to existing BookStack users

This feature would allow a better flow and navigation of the document if the document is huge so you don't have to scroll up and down.

### Can the goal of this request already be achieved via other means?

There is no way i have seen yet for someone to be able to do it. I might be wrong

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Hi @mankiiii,

We already generate a table of contents for the page based upon headings:

![image](https://github.com/BookStackApp/BookStack/assets/8343178/0f73f13c-1629-44af-8f52-8d7d64a8d583)

Page screenshotted: https://demo.bookstackapp.com/books/bookstack-demo-site/page/header-level-examples
Or are you specifically referring to PDF exports?

**Comment by mankiiii** [comment]
Hello,
Well I mean I know the table of contents exist. what i mean is 

![Picture1](https://github.com/BookStackApp/BookStack/assets/91251437/f912422b-939f-45ff-8d55-bac1c1b35eac)
For example in my LaTeX document if i click the 3.1 it will take me to the figure. In this case the reference to the figure shown in the first picture is on page 10 and the actual figure is on page 20. 
![image](https://github.com/BookStackApp/BookStack/assets/91251437/6c3a0bc3-4a4d-4973-a287-4b41b651df55)

**Comment by mankiiii** [comment]
I would like to add that, if you inspect element and find the id of the header element. And you put the URL/#id, if you add a link to the document that goes to URL/#id it will refresh the page and "teleport" you to that section of the document. But that still isn't the desired behavior as it has to reload the page to do it. I mean it is a work around but someone that doesn't know how to find the id of the element(someone not technical) can't do this

**Comment by ssddanbrown** [comment]
@mankiiii If you remove the `URL/#id` part of the link, and just use the `#id` part you may have some success.

If using the WYSIWYG editor you can use a `#` in the URL input (or press the down arrow on keyboard) to show a list of headings within the current document you can link to:

![image](https://github.com/BookStackApp/BookStack/assets/8343178/0824af83-277c-4bb9-87cb-87ce33574619)

**Comment by mankiiii** [comment]
Ah okay perfect that is exactly what I wanted. Is there documentation for this that I missed? or is it like hidden :)

**Comment by ssddanbrown** [comment]
@mankiiii I don't think we have any specific documentation for this feature (most minor features of the WYSIWYG are undocumented). Maybe something to improve upon but we'll likely be changing editors soon so not something to do right now.

> Ah okay perfect that is exactly what I wanted. 

Good to hear, I'll therefore close this request off since the above meets the desire.
