### ISSUE TITLE
Editor Shows Only Page Title and Cannot Edit

### ISSUE THREAD

**Issue by ash34** [BookStackApp/BookStack#5093]
### Describe the Bug

BookStack v24.05.2

When either creating a new page or attempting to edit and existing page the normal editing functions are not available, only a mostly blank except for the title.

### Steps to Reproduce

1. Click the edit button on an existing page or click new page.
2. Observe the most white screen with no editing functions
3. Click Back to exit

### Expected Behaviour

At step 2 the editing functions shown be available.

### Screenshots or Additional Context

![Screenshot 2024-07-03 at 18 44 12](https://github.com/BookStackApp/BookStack/assets/56022918/5b4245bd-add4-41a1-92ab-a5b777b29863)

### Browser Details

Seen in Chrome and Safari on MacOS 12.7.5

### Exact BookStack Version

 v24.05.2

**Comment by ssddanbrown** [comment]
Hi @ash34,
Can you detail your scenario and environment a little more?

- Is this a new instance?
- How did you install BookStack?
- Has the editor worked before on this instance?
- What OS is BookStack hosted on?
- Are you using any proxy layers like Cloudflare?
- Have you made any customizations?
- Do other interactive elements work (editor sidebar, profile menu in header)?

If you're familiar with the browser development tools, it would also be good to see any errors logged when refreshing this edit view.

**Comment by ash34** [comment]
It was Rocket Loader in Cloudflare. Enabled for another (test) subdomain but seems it applies to all. Once I deactivated Rocket Loader all is well again.
