### ISSUE TITLE
Text align

### ISSUE THREAD

**Issue by mixeme** [BookStackApp/BookStack#5100]
### Describe the feature you'd like

It would be better that a rendered page view has text align width by default.

### Describe the benefits this would bring to existing BookStack users

Better page view as in real books and documents.

### Can the goal of this request already be achieved via other means?

No, have not found such a setting in term of Markdown editor.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Hi @mixeme,

> It would be better that a rendered page view has text align width by default.

To be honest, I don't understand what that actually means at all.
Could you explain the desire/request further?

**Comment by mixeme** [comment]
> Hi @mixeme,
> 
> > It would be better that a rendered page view has text align width by default.
> 
> To be honest, I don't understand what that actually means at all. Could you explain the desire/request further?

Yes. I have difficulties with terminology in this field. Let's adopt, for example, terminology used in this document.
https://learn.microsoft.com/en-us/globalization/fonts-layout/text-justification

Currently, it is used text alignment "Align Left". I proposed to use "Justify" option by default for page views.

**Comment by ssddanbrown** [comment]
Hi @mixeme,

For that you could add the following to the "Custom HTML Head Content" customization in your BookStack settings:

```html
<style>
  .page-content { text-align: justify; }
</style>
```

**Comment by mixeme** [comment]
> Hi @mixeme,
> 
> For that you could add the following to the "Custom HTML Head Content" customization in your BookStack settings:
> 
> ```
> <style>
>   .page-content { text-align: justify; }
> </style>
> ```

Could you explain with more details? Where does this code should be inserted?

**Comment by ssddanbrown** [comment]
@mixeme I'm referencing the customization setting shown here (this particular setting is at the bottom of the "Customization" setting page):

![image](https://github.com/BookStackApp/BookStack/assets/8343178/d36d238a-a044-4166-91d5-335672f678bc)

**Comment by mixeme** [comment]
Thank you! It helped me. However, I think such a common modification should be at least added to the [documentation](https://www.bookstackapp.com/docs/admin/visual-customisation/), if you don't want to switch this by default (as is in real books that inspired BookStack).

**Comment by ssddanbrown** [comment]
@mixeme Good to hear that worked! I'll therefore close this off.

> However, I think such a common modification should be at least added to the [documentation](https://www.bookstackapp.com/docs/admin/visual-customisation/), if you don't want to switch this by default (as is in real books that inspired BookStack).

I can't remember getting this request before in the 8.5 years of having publicly shared BookStack, so I don't think it's anywhere near common enough to justify being in the documentation.
