### ISSUE TITLE
Specific pages are not affected when Custom CSS is applied

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#5103]
### Describe the Bug

I have created a custom CSS block which is used to make the UI right to left and change the font. It works everywhere but it doesn't affect the font of this specific page:
```
.../settings/features
```
Is there something different with this page? 

### Steps to Reproduce

1. Go to settings
2. Add a style block
3. The settings page itself is not changed

### Expected Behaviour

Since I have used an asterisk in my CSS to affect everywhere, I expect all pages to have the same font. 

### Screenshots or Additional Context

The other pages:
![1](https://github.com/BookStackApp/BookStack/assets/100111649/5eb385eb-7838-4189-8815-c009817a8201)

The Settings page:
![2](https://github.com/BookStackApp/BookStack/assets/100111649/a750abaf-aebf-4e86-95e0-b26927d7e0bf)

### Exact BookStack Version

v24.05.1

**Comment by ssddanbrown** [comment]
Hi @okaeiz,
Custom head HTML isn't applied to the settings page to ensure those pages remain accessible (and settings remain unaltered) in the case where any problematic/breaking code is applied.

**Comment by merrime-n** [comment]
So, what's your suggestion?
It is annoyingly inconsistent.

**Comment by ssddanbrown** [comment]
@okaeiz If really wanted, you could apply customizations via the [visual theme system instead](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md), [overriding this view](https://github.com/BookStackApp/BookStack/blob/development/resources/views/layouts/parts/base-body-start.blade.php) and adding styles, which would then be applied to all views.

**Comment by ssddanbrown** [comment]
I'll go ahead and close this off. #5219 has been open as a related request.

**Comment by merrime-n** [comment]
People raise issues and issues get closed with no convincing reason (e.g custom headings are not allowed because the project owner prefers to **zoom in** and **zoom out** and expects other people to follow this method). PRs are not welcomed.
I don't know how this project is open to contributions.
