### ISSUE TITLE
Right to Left direction does not affect the callouts

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#5104]
### Describe the Bug

When I create an RTL callout, the callout box is rendered LTR (the icon is displayed on the left).

![Capture](https://github.com/BookStackApp/BookStack/assets/100111649/b14e4542-ccef-4d9c-b976-4bff55f7753b)

### Steps to Reproduce

1. In the Persian UI, select a text, change its direction to RTL and change its style to Callouts.
2. It is the same as when the text direction is LTR.

### Expected Behaviour

I expect the callout box to be rendered accordingly.

### Exact BookStack Version

v24.05.1

**Comment by ssddanbrown** [comment]
Thanks for reporting @okaeiz.
I've now addressed this for most scenarios via commit 95c3cc5c00fefe954481129caa68f6bf6bad5f7a.
Where more modern CSS support (or RTL support) is lacking (old browsers, export formats) these may still default back to RTL display.
This will be part of the next patch release.
