### ISSUE TITLE
Ability to share specific books with specific users.

### ISSUE THREAD

**Issue by odootek** [BookStackApp/BookStack#5105]
### Describe the feature you'd like

As the title says Ability to share specific books with specific users.

Right now there is no way to share a specific book with a specific user. The only option to share is allow view/edit all book to a user using role. 

### Describe the benefits this would bring to existing BookStack users

I use bookstack for personal documentation, sometimes I need to share a travel guide, a tutorial, a food recipe or etc. to someone, an user o a guest. That is not possible. I have to create a role for a specific user then override permission, then it get bugged and I lose access to the pages I as the owner of the book. but the guest user get access.

### Can the goal of this request already be achieved via other means?

I do not know

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

It will be cool in book permission to be able to add multiple users with their permission to view or edit or allow public view.

![bug](https://github.com/BookStackApp/BookStack/assets/115769694/6dcf12d5-0bd3-4cb9-9dc3-6d546653eec3)

Lost access to a page when using book permission. It is hidden and no way to recover. guest account can see it, admin account can see it. just not the owner.

guest user/ public role can se the page and not the owner.

![tv](https://github.com/BookStackApp/BookStack/assets/115769694/ad095a12-a68b-4cbb-8076-c8dd83098f0b)

**Comment by ssddanbrown** [comment]
Thanks for the request @odootek, but I'd consider this already covered by existing issues #1747 and #288 so I'll therefore close this off as a duplicate.
