### ISSUE TITLE
It would be great if Turkmen language will be added

### ISSUE THREAD

**Issue by mikebionic** [BookStackApp/BookStack#5106]
### Language to Add

TK (Turkmenistan)

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Hi @mikebionic,
Sorry for my lack of response. Do you still need (and are you still willing to provide) Turkmenistan translations?

**Comment by mikebionic** [comment]
Yes I think it would be great if bookatack will have Turkmen translation, could you guide me how to accomplish this?

**Comment by ssddanbrown** [comment]
@mikebionic I've now enabled the Turkmen language on our Crowdin:
https://crowdin.com/project/bookstack/tk

You should be able to sign-up there, and then you'll have an interface to translate each of the translations.
These then automatically sync to the application and, when the language is mostly complete, I'll add it as a user language option. 
If there's little progress after a while (few months), I may remove the language option.

**Comment by mikebionic** [comment]
Isn't there an easier version, like exporting a .json or .strings file and after translated on computer, upload and merge strings?

**Comment by ssddanbrown** [comment]
@mikebionic There's the PHP format we store translations in: https://github.com/BookStackApp/BookStack/tree/l10n_development/lang/tk

If you're able to work to that format (keeping the structure, keys and filenames intact) I could do a one-time initial import of those files, but any further changes beyond that initial import would ideally be done in Crowdin.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion/follow-up here, I'll go ahead and close this off since the language has been made available on Crowdin.
