### ISSUE TITLE
[Support request] Migrate Ubuntu 20.04 install instance to new docker instance + new url

### ISSUE THREAD

**Issue by HerbertSchulz4711** [BookStackApp/BookStack#5109]
### Attempted Debugging

- [x] I have read the debugging page

### Searched GitHub Issues

- [x] I have searched GitHub for the issue.

### Describe the Scenario

I have a Bookstack instance which has been installed via the Ubuntu 20.04 install script and now I would like to move the whole installation / instance to docker. Current Bookstak version running is [BookStack v22.11.1]

I've already made a backup of all files and the database according to a support document on bookstackapp.com but now I can't figure out how to migrate it to docker.

Additionally I need to update the url for all files and bookstack itself.

How would I be able to achieve migration and setting up the new url?

Thanks in advance.

### Exact BookStack Version

BookStack v22.11.1

### Hosting Environment

Current: Ubuntu 20.04 | PHP 7.4.3
New version (should be): Docker (via Synology)

**Comment by ssddanbrown** [comment]
Hi @HerbertSchulz4711,
I have a video showing the steps of restoring files and a database backup here from about 17:30:

https://youtu.be/6A8hLuQTkKQ?t=1050

It's for a docker-compose setup, but hopefully you can adapt the guidance to suit your environment, the high-level steps and advice should be relevant.

You'll want to change the URL used in the content. 
This can be done using the "Update System URL" command detailed here:
https://www.bookstackapp.com/docs/admin/commands/#update-system-url
Earlier in my video linked above I show running commands.

**Comment by HerbertSchulz4711** [comment]
@ssddanbrown Thank you. I'll have a look at it. :)

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up or support needed I'll go ahead and close this off.
