### ISSUE TITLE
Delete Audit trail

### ISSUE THREAD

**Issue by ap2de** [BookStackApp/BookStack#5113]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

according to https://www.bookstackapp.com/docs/admin/commands/#delete-all-activity-history 
in the container console of my docker container I use the command 
_**php artisan bookstack:clear-revisions -a**_

I receive the following error message:
**_Could not open input file: artisan_**

**For deploying the stack in portainer I used the following compose file:**
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1023
      - PGID=1023
      - APP_URL=XXXX
      - DB_HOST=XXXX
      - DB_PORT=3306
      - DB_USER=XXXX
      - DB_PASS=XXXX
      - DB_DATABASE=XXXX
      - STORAGE_TYPE=local_secure
      - AVATAR_URL=false
      - DRAWIO=XXXX
      - ALLOW_ROBOTS=false
      - SESSION_SECURE_COOKIE=true
      - LOG_FAILED_LOGIN_MESSAGE="Failed login for %u"
      - RECYCLE_BIN_LIFETIME=20
      - REVISION_LIMIT=20
      - APP_TIMEZONE=Europe/Berlin

    volumes:
      - /volume1/docker/XXXX/config:/config
    ports:
      - 6878:80

**Questions**
a) is artisan missing in the docker image I use? If yes: what do I need to do?
b) is it safe to delete all rows in the table 'activities'?

Thank you for any proposals on how to proceed!

### Exact BookStack Version

24.02.3

### Log Content

n/a

### Hosting Environment

docker using portainer on synology nas.
image: image: lscr.io/linuxserver/bookstack

**Comment by ssddanbrown** [comment]
Hi @ap2de,

> a) is artisan missing in the docker image I use? If yes: what do I need to do?

No, it should be in there, you just need to be in the BookStack install directory first (which I think is at `/app/www/` in the linuxserver image).
If it helps, I show the process of running commands in a docker compose linuxserver bookstack stack in my video here at about 2:32:

https://youtu.be/6A8hLuQTkKQ?t=152

> b) is it safe to delete all rows in the table 'activities'?

I'm not sure without checking. Maybe but I'd advise against it and use the command instead.

Note that activity/audit-log is cleared via the `php artisan bookstack:clear-activity` command. Not via the clear revisions command you have in your original comment above.
