### ISSUE TITLE
"419 Page Expired" when saving any settings

### ISSUE THREAD

**Issue by mdezzi** [BookStackApp/BookStack#5114]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have recently performed a reinstall of the Bookstack container to help with some performance issues I was having. I have pulled down the latest docker container and it starts successfully. All pages and images appear to be loading correctly except for the app icon and favicon. When trying to reset those in the settings I encounter a "419 Page Expired" error any time that I try to save anything on a settings page. I have tried clearing cookies, and in an incogneto window with no success. 

[EDIT] It looks like I get a 419 Page Expired whenever i try to create new pages or edit pages as well. 

### Exact BookStack Version

v24.05.2

### Log Content

There don't appear to be anything in the lavarel log or php logs. 

### Hosting Environment

docker container running on Ubuntu 22.04 VM

**Comment by baldurrensch** [comment]
I am running into a similar issue. Especially on the login page, I am getting a 419. Usually, if I then go to a different page, I am still logged in.

**Comment by ssddanbrown** [comment]
This would usually occur if either:

- There's a mismatch in used and configured URL
  - Make sure the `APP_URL` setting is set properly, including ensuring the protocol (`https://` or `http://` part) matches  what's used in the browser.
- There's a file permissions issue and the system can't properly manage session data.

Usually it's the first of the above.

**Comment by mdezzi** [comment]
My issue seems to have mysteriously resolved itself after a few container restarts. I'm not sure what the issue was, because my APP_URL was correct.
