### ISSUE TITLE
How to Allow Users to Add Books to a Specific Bookshelf Without Editing the Bookshelf?

### ISSUE THREAD

**Issue by Maxtsou** [BookStackApp/BookStack#5116]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,

I am currently setting up permissions in BookStack and need some assistance. I would like to configure user permissions so that users can add books to a specific bookshelf, but they should not be able to edit the bookshelf itself. Here are the details of what I’m trying to achieve:

	1.	Users should be able to add new books to a specific bookshelf.
	2.	Users should not have the ability to edit or delete the bookshelf.
	3.	Users should not have the ability to edit or delete books in other bookshelves.

I have tried the following steps:

	1.	Created a new role and assigned the “Books - Create” and “Books - View” permissions.
	2.	Set detailed permissions on the specific bookshelf to allow the role to “View” and “Create Books”.
	3.	Assigned the role to the users.

Despite these settings, users are either unable to add books to the specific bookshelf or are given too many permissions.

Could you please provide guidance on how to correctly set these permissions in BookStack? Any help would be greatly appreciated.

Thank you!

Best regards,

### Exact BookStack Version

BookStack v24.05.2

### Hosting Environment

ubuntu 64-bit server 24.04 on VMware vSphere Client 8.0.2.00000, installed using official installation script

**Comment by ssddanbrown** [comment]
Hi @Maxtsou,
That desired setup of permissions is not something supported or possible.
The adding of a book to a shelf is considered an edit of that shelf.

**Comment by Maxtsou** [comment]
Ok, I understand. Thank you.

**Comment by ssddanbrown** [comment]
Thanks for your understanding, I'll therefore close this off since the original query has been answered.
