### ISSUE TITLE
Ability to set the PDF export timeout value in the .env file

### ISSUE THREAD

**Issue by jtee3d** [BookStackApp/BookStack#5119]
### Describe the feature you'd like

Currently, the PDF export timeout is set to 15 seconds. It would be useful to have this modifiable in the .env file, as per issue #5111.

### Describe the benefits this would bring to existing BookStack users

For large books, this would prevent Bookstack from timing-out before the PDF is generated.

### Can the goal of this request already be achieved via other means?

Yes, by modifying line 89 in /app/www/app/Entities/Tools/PdfGenerator.php

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @jtee3d.
This has now been added via 6103a22febd839fa76a3f9a54058b66a14906b35 to be part of the next feature release.
