### ISSUE TITLE
Plural in localized version is English-like (e.g. on the show profile page)

### ISSUE THREAD

**Issue by nekromoff** [BookStackApp/BookStack#512]
### For Bug Reports

* BookStack Version:  0.17.4 
* PHP Version: 7.1
* MySQL Version: 10.1.25-MariaDB-1 Ubuntu 17.10

##### Expected Behavior
Localized plural.

##### Actual Behavior
's' appended to the singular in localized translations.
![obrazok](https://user-images.githubusercontent.com/8550349/30505908-ee2b6102-9a77-11e7-9eb1-a25c9f700cb6.png)
Book-s = Kniha-s
Chapter-s = Kapitola-s
Page-s = Stránka-s
(sounds like Esperanto little bit :-))))

**Comment by ssddanbrown** [comment]
Hi @nekromoff,
Thank you for your issue request.

This was actually fixed as part of v0.18. Now each language can specify their own pluralizations. Details in #417. Will therefore close this issue.
