### ISSUE TITLE
Dark mode - text color change

### ISSUE THREAD

**Issue by SwiftRedline** [BookStackApp/BookStack#5120]
### Describe the Bug

when i do a chart in white mode i can clearly read all informations in it. 
But when i look it up in dark mode or someone else looks it up in dark mode, we cannot read anything in there because the text color won't change. 
Should this be normal? 

### Steps to Reproduce

Make a chart, switch to dark mode and u can't see the text

### Expected Behaviour

Change of color from chart. 

### Screenshots or Additional Context

dark mode:
![grafik](https://github.com/user-attachments/assets/0e0e3d58-f1f9-4cb0-a665-3f32301e34e0)
white mode: 
![grafik](https://github.com/user-attachments/assets/62da5462-991a-4c88-8c79-2b8c277133b0)

### Browser Details

Firefox

### Exact BookStack Version

v24.05.3

**Comment by ssddanbrown** [comment]
Hi @SwiftRedline,
I'm guessing you've copied in this table from elsewhere and existing styles (colors) have been imported via this process, or color styles have been specifically set via the BookStack editor.

You could click within the table within the editor, then use the "Clear table formatting" option as shown below. This will reset an existing styles that may have been copied in or applied which are currently forcing specific text colors.

![image](https://github.com/user-attachments/assets/535baa87-be8c-4399-8ee8-43a583e09fcb)

**Comment by SwiftRedline** [comment]
oh wow! It worked. - Thanks!
I'm sorry for your time.
