### ISSUE TITLE
Viewer role doesn't inherit permissions

### ISSUE THREAD

**Issue by CdrMarks** [BookStackApp/BookStack#5129]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Steps to reproduce:
1. Create a new user with the Viewer role.
2. Login as Admin
3. Enable Public access.
4. Under Roles, set Viewer role to View All Books.
5. Create a Book.
6. Edit Book permissions add Override for Public to View.
7. Log out.
8. Log in as the Viewer user.
9. When accessing /books, cannot see the Book.

Here's a video in case that's helpful.
https://www.loom.com/share/b362b2ee465642d68e721c18193de5cf

### Exact BookStack Version

v24.05.3

### Log Content

None

### Hosting Environment

Production: PHP8.2 (ea-php82) on EL8 cPanel shared hosting
Local: PHP8.1 on MacBookPro (2019) via ngrok

**Comment by ssddanbrown** [comment]
Hi @CdrMarks,
In your demo video, the "Logged in user"/viewer role shows 0 users assigned.
Can you check if the "Ryan" user has roles assigned to them (edit their user profile) otherwise they may not be receiving the permissions you're expected them to have.

**Comment by CdrMarks** [comment]
Nice catch @ssddanbrown.  I associated the user with the role and all is working as expected.

Thanks!
