### ISSUE TITLE
Right to Left direction does not affect the checkboxes

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#5134]
### Describe the Bug

When I create an RTL checkbox, the box is rendered LTR (the icon is displayed on the left).

### Steps to Reproduce

Steps to Reproduce
1. In the Persian UI, create a checkbox.
2. It's on the left no matter what the text direction is.

### Expected Behaviour

I expect the checkbox to be rendered accordingly.

### Exact BookStack Version

v24.05.1

**Comment by ssddanbrown** [comment]
Thanks for raising @okaeiz,
RTL support has now been added, where supported, via commit 8cef998f4977d23ba87f10e13260f8c7537e53a9 which will be part of the next patch release.
