### ISSUE TITLE
OAuth Patreon Support

### ISSUE THREAD

**Issue by Salvora** [BookStackApp/BookStack#5138]
### Describe the feature you'd like

It would be very good to have oauth support so that creators can self-host their content on Bookstack with a patreon system This will enable the supporters to access the content they have signed up for with appropriate permissions.

https://docs.patreon.com/#oauth
https://www.patreon.com/portal/start/oauth-explained

### Describe the benefits this would bring to existing BookStack users

can motivate the creators to selfhost their content on bookstack with a payment system linked to patreon.

### Can the goal of this request already be achieved via other means?

As far as I know, no.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Over 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @Salvora but I'm not keen on expanding our range of third-party authentication options out any further, at least without significant proven need.
Therefore I'm going to close this off as out of scope.

If you have some code/PHP know-how, we do provide a way to register custom/other oauth providers via our logical theme system: https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md#custom-socialite-service-example
