### ISSUE TITLE
Problem linking pages after .17.4 to .18 update.

### ISSUE THREAD

**Issue by dsaundersWizmo** [BookStackApp/BookStack#514]
### For Bug Reports

* BookStack Version: 0.18
* PHP Version: 7.0.22-0ubuntu0-16.04.1
* MySQL Version: 5.7.19-0ubuntu0.16.04.1

##### Expected Behavior

Should be able to create a reference to page like {{@45}}

##### Actual Behavior

Results in an error message:

`QueryException in Connection.php line 647:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'renderedHTML' in 'field list' `

**Comment by dsaundersWizmo** [comment]
It looks like any pages that already had references prior to the update work fine.  Any _new_ references don't work and if I try and save an edit to a page that did have them, same error occurs.

**Comment by ssddanbrown** [comment]
@dsaundersWizmo Apologies for this, Will release in next bugfix, Marked as a priority. Hopefully will have some time tomorrow night to fix and release.

**Comment by dsaundersWizmo** [comment]
Thanks Dan.
