### ISSUE TITLE
APP_DEFAULT_DARK_MODE var 

### ISSUE THREAD

**Issue by MamuMehdi** [BookStackApp/BookStack#5145]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

How can we set this variable to use dark mode for public user on BookStack via Pikapods?

### Exact BookStack Version

	24.05.3 

### Hosting Environment

pikapods.com

**Comment by ssddanbrown** [comment]
Hi @MamuMehdi,
I have no idea, I don't use PikaPods. Do they provide access to application files at all?

**Comment by MamuMehdi** [comment]
Unfortunately we don't have. Only through SFTP we can access to pod's data.

**Comment by ssddanbrown** [comment]
Okay, so you do have access via SFTP? That's fine.

What files do you see there?

**Comment by Parpar1369** [comment]
![IMG_20240804_102857_339](https://github.com/user-attachments/assets/b7c439f5-f709-4c9e-b703-9c91925a3ce9)
Hi
This is the list of files that I have access to

**Comment by ssddanbrown** [comment]
Within the `www` folder you should find a `.env` file. This may be hidden by default (you may need to change options in your SFTP browser there to show hidden files).

You can add `APP_DEFAULT_DARK_MODE=true` to this file (on it's own line, with no extra spaces before).

**Comment by Parpar1369** [comment]
Thanks for taking the time to help me out, You were absolutely correct🙂

**Comment by ssddanbrown** [comment]
Good to hear! I'll therefore close this off assuming you're connected to @MamuMehdi.
If that's not the case, this can be re-opened if needed.
