### ISSUE TITLE
Different line height between light and dark mode

### ISSUE THREAD

**Issue by mehmet-b-90** [BookStackApp/BookStack#5146]
### Describe the Bug

I have noticed that the light and dark modes are displayed with different line heights in code blocks. 

### Steps to Reproduce

1. Click Dark Mode
2. Click Light Mode

### Expected Behaviour

Equal line heights.

### Screenshots or Additional Context

![image](https://github.com/user-attachments/assets/18c4df1c-c420-4d23-a764-761ac9189122)

### Browser Details

Vivaldi Browser 6.8

### Exact BookStack Version

24.05.3

**Comment by mehmet-b-90** [comment]
![image](https://github.com/user-attachments/assets/a279ae8e-4f05-45fc-ba60-b4a150e7c601)

**Comment by ssddanbrown** [comment]
Thanks for reporting @mehmet-b-90.
This has bee addressed in 4630f0728225dbbfca285bd88345a678cf8d02d1, and is due to be part of the next patch release.
