### ISSUE TITLE
Fresh install - Frontend and JS bugs

### ISSUE THREAD

**Issue by Diverti** [BookStackApp/BookStack#5151]
### Describe the Bug

I made a fresh install today for version v.24.05.3 with install script on ubuntu 24.04 and some of the things not working:
- When I click on the top right corner for profile, nothing happens (don't know if something should happen or not..)
- Saving settings like Features & Security checkbox not working, nothing happens on save, it resets to an empty checkbox
- Although in the audit log, I can see the following: Admin settings_update  features 192.168.1.100 2024-08-06 13:53:48
- I can upload logo and I can make shelves too.
- Got JS error in console on every page: 
`Uncaught SyntaxError: Identifier 'p' has already been declared at app.js?version=v24.05.3:1:1`

### Steps to Reproduce

1. Install a Fresh 24.04 ubuntu
2. Install via the script from the documentation page
3. Log in

### Expected Behaviour

Saving settings 

### Browser Details

Microsoft Edge	127.0.2651.74 (Hivatalos build) (64 bites)  Változat	dbf5b0aa014c4e70e3d5e2d73248e21264f82957 Chromium-verzió	127.0.6533.73 Operációs rendszer	Windows 11 Version 21H2 (Build 22000.2538) JavaScript	V8 12.7.18.6 Felhasználói ügynök	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0

### Exact BookStack Version

v.24.05.3

**Comment by ssddanbrown** [comment]
Hi @Diverti,
Do you have any proxy or cache systems in place like Cloudflare? (Please confirm what you are using if yes).

**Comment by Diverti** [comment]
Hi!
No, I do not use any caching or proxy just a local Linux server with default install.
I should mention that I tried to reinstall this, and I got the same results.

**Comment by ssddanbrown** [comment]
Okay, could you open the browser devtools, view the console while on a page of your BookStack instance, then refresh. Please share a screenshot of all messages you observe in the console.

**Comment by Diverti** [comment]
Of course.
Here it is:
![image](https://github.com/user-attachments/assets/5c9a60a3-e90f-4d41-8b20-efb3344be216)

**Comment by ssddanbrown** [comment]
Thanks @Diverti, do you get the same on the demo site?: https://demo.bookstackapp.com/

**Comment by Diverti** [comment]
Yeah,, I got the same. I went ahead and tested different browser and everything works.
It seems the problem is caused by an extension, that I have on multiple browsers.
It's called: **User-Agent Switcher PRO | Version: 1.0.1**
It's used to anonymize my browsing as fake User-Agent.
For now, I keep this extension disabled.

**Comment by ssddanbrown** [comment]
Glad you found the cause! I'll therefore close off this issue.
