### ISSUE TITLE
Views log for guest user

### ISSUE THREAD

**Issue by victorvs0uz4** [BookStackApp/BookStack#5152]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello!
In the "users" table, the ID number 2 corresponds to the Guest user.
However, we saw that user id 2 does not generate access logs in the "views" table.
Is it possible to count these views? This counter would be very interesting for public pages where we could know the number of views.

### Exact BookStack Version

v24.05.3

### Hosting Environment

Docker Container, Linuxserver.io version:- v24.05.3-ls157 Build-date:- 2024-08-05T18:27:24+00:00

**Comment by ssddanbrown** [comment]
Hi @victorvs0uz4,
Sorry for the late response. No, we don't store this information in BookStack since there's no internal use for it.
Generally, if you need additionally analytics in this regard you use an external analytics service/option and use that with BookStack to get more information.
