### ISSUE TITLE
Need an "Exec" role

### ISSUE THREAD

**Issue by dagnabbit99** [BookStackApp/BookStack#5157]
### Describe the feature you'd like

I'd love to see an "Exec" role... can see everything, especially the audit log (to track progress), and cannot change anything.  

### Describe the benefits this would bring to existing BookStack users

The biggest benefit of this feature would be protecting BookStack content from those who demand to see everything in the system, but have no business being able to change content, permissions, or anything else in the BookStack install.

### Can the goal of this request already be achieved via other means?

I don't think so.  There's a similar request, #4308, but no action nor update

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Thanks for the request @dagnabbit99.
From my perspective I wouldn't want to complicate the permission system to suite this.
If there's demand over time maybe the audit log could be under its own permission, but I'd be hesitant to expand that further to viewing everything (that may be soley represented via forms right now).

As an alternative means, you could use the BookStack API or database to build relevant views/reports externally using Business-Intelligence/reporting tools if available.

**Comment by dagnabbit99** [comment]
Thanks, was thinking this myself- a daily audit log journal sent via email would work just as well.  Could easily use the API to pull that info.
