### ISSUE TITLE
Fix Non-Amazon, S3 Compatible Services docs (add STORAGE_S3_REGION)

### ISSUE THREAD

**Issue by Meettya** [BookStackApp/BookStack#5158]
### Describe the Bug

1) Create self-hosted Minio bucket, get correct keys.
2) Set all values to .env as described at doc https://www.bookstackapp.com/docs/admin/upload-config/#non-amazon-s3-compatible-services

As result get 500 error on front-end and 400 error at laravel log

`[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `HEAD https://domain.name/bucketname/uploads/images/gallery/2024-08/2024-08-08-131815.png` resulted in a `400 Bad Request` response at /app/www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)`

**Solution**
add `STORAGE_S3_REGION=you-region` to .env file

after this all work flawless.

PS. May be its optional setings and depends on Minio settings, but any way its seems should declared at docs.

### Steps to Reproduce

1. Create any empty page
2. Try to add image

### Expected Behaviour

Image should upload

### Exact BookStack Version

v24.05.3

**Comment by ssddanbrown** [comment]
Hi @Meettya,

I'm not sure that's a required option, and think something else may have been at play on your instance.
Just yesterday I tested BookStack with Minio, and this was not required.
I recorded my full integration and test process here:
https://foss.video/w/9noJP3x5gnmQ4bNUAg47qs

I don't want to document environment and platform specific edge-cases/issues within our own documentation, as it's intended to be fairly platform abstract and I don't want to indicate official support is provided for specific platforms.

**Comment by Meettya** [comment]
Hi @ssddanbrown

Looks reasonably. Ok, seems it to be enough just close issue and remain it for search, in edge case maybe someone can find it here. 
Anyway thank you :)

**Comment by Zomphie** [comment]
Hello! I'm using an S3 Object Bucket with Hetzner and have confirmed that my settings are correct. However, when I try to upload an image, the bucket remains empty, and I receive the following error message: "An Error Occurred: An unknown error occurred." There are no related error messages in the logs.

We're using the Docker installation, and while the upload process claims to complete successfully, the image isn't actually being uploaded. How can I resolve this issue?
