### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by genxlee** [BookStackApp/BookStack#516]
^

**Comment by s0n-** [comment]
Do you use a specific 2 factor vendor? I know I have requested Okta or SSO support.

**Comment by adambirds** [comment]
This is definitely needed, if it could be compatible with Google Authenticator that would be great.

**Comment by lwl12** [comment]
Also need it!

**Comment by cyclinggeorgian** [comment]
> > Google auth (so it's compatible with authy) would be wonderful!
> 
> Actually, they are all based on [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm), so just use this protocol and we can use it in many APPs~

Definitely voting on TOTP implementation. This would be great enhancement to the security of the whole platform. And just think of all the popularity points project going to score with this implementation :-).

**Comment by Cave-Johnson** [comment]
Would definitely like to add my +1 to TOTP support

**Comment by Cave-Johnson** [comment]
Came across this project recently, could this be implemented to deliver TOTP support?

https://github.com/Spomky-Labs/otphp

**Comment by ssddanbrown** [comment]
Just to flesh this out a little further, What kind of controls would you want for 2FA? For example, would you want to force 2FA on all users? Let users decide? User-level control by admins? Something else?

Not looking for extra ideal, just want to know what you'd specifically want for your environment(s).

I'm assuming, for new users and for newly-admin-enabled-2fa users, we'd force a "Setup 2FA" step upon login? 

We we need to implement a backup system? Or would an admin CLI command suffice to disable 2FA for system/specfiic-account suffice in scenarios where access is lost.

**Comment by fourthdimension** [comment]
Should be implemented system wide for all users. Let the admin decide to
enable or disable. Users would not have control over enabling or disabling.
It would be best to force setup of 2fa upon login. CLI command would
suffice where access is lost, for now.

Hope this helps to understand our environment better.

Dru

**Comment by ssddanbrown** [comment]
Thanks for the input @fourthdimension.

**Comment by ssddanbrown** [comment]
Realized we have duplicate issues for this, Will close this off in favour of #1118. Although this was the original, #1118 has more up-votes to indicate user-need and therefore more likely to be looked at when choosing features to implement.

For any further comments, please add them to #1118.
