### ISSUE TITLE
Unable to install composer dependencies

### ISSUE THREAD

**Issue by grandeljay** [BookStackApp/BookStack#5162]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I've just discovered BookStack and am attempting to first try/installation. Following the [documentation](https://www.bookstackapp.com/docs/admin/installation/), I have just run `composer install --no-dev` after cloning the repository. This is the output I get:
```
$ composer install --no-dev
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laravel/framework is locked to version v10.48.16 and an update of this package was not requested.
    - laravel/framework v10.48.16 requires composer-runtime-api ^2.2 -> found composer-runtime-api[2.1.0] but it does not match the constraint.
  Problem 2
    - laravel/framework v10.48.16 requires composer-runtime-api ^2.2 -> found composer-runtime-api[2.1.0] but it does not match the constraint.
    - socialiteproviders/manager v4.6.0 requires illuminate/support ^8.0 || ^9.0 || ^10.0 || ^11.0 -> satisfiable by laravel/framework[v10.48.16].
    - socialiteproviders/manager is locked to version v4.6.0 and an update of this package was not requested.
```

### Exact BookStack Version

v24.05.3

### Hosting Environment

PHP 8.3

I don't know more, sorry. If I can run some commands to give you any more info, I'd be happy to!

**Comment by ssddanbrown** [comment]
Hi @grandeljay,
That error indicates you're using an older version of composer that's incompatible. BookStack requires v2.2+, whereas you seem to be using composer v2.1 (Should be able to confirm via `composer -V`).

We have some guidance on updating composer on this page of the site:
https://www.bookstackapp.com/docs/admin/updating-php/#updating-php

**Comment by grandeljay** [comment]
Hey @ssddanbrown,

Thank you for your fast response!

> That error indicates you're using an older version of composer that's incompatible. BookStack requires v2.2+, whereas you seem to be using composer v2.1 (Should be able to confirm via composer -V).

You are absolutely correct!

Unfortunately, updating doesn't seem to work. The server is not mine, is this something I should ask my hoster about? Running `self-update` gave me the following output:

```
$ composer -V
Composer version 2.1.12 2021-11-09 16:02:04
$ composer self-update

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "self-update" is not defined.

**Comment by ssddanbrown** [comment]
Ah, you might be better off using a local version of composer then if you don't have control of the global version (and you're sure you don't. If this is a VPS you should have the ability to change the version, but it may be that you've installed composer using system packages).

To use a local version, follow the download commands on the [composer download page](https://getcomposer.org/download/) while in your BookStack install directory. This will create a `composer.phar` file.

Then you should be able to run composer via `./composer.phar install --no-dev`

**Comment by virtadpt** [comment]
I've used the method @ssddanbrown describes in shared hosting a few times and it works pretty well (though you might run into runtime caps once in a while).

**Comment by grandeljay** [comment]
> Ah, you might be better off using a local version of composer

> I've used the method @ssddanbrown describes in shared hosting a few times and it works pretty well (though you might run into runtime caps once in a while).

Yeah, that worked like a charm, thank you! I still have run into some issues though (unrelated to BookStack) and will report back when the installation completed. But this specific issue is definitely already resolved for me.

Thank you for all the help!

**Comment by grandeljay** [comment]
It all works by the way, thank you for the support!

**Comment by ssddanbrown** [comment]
Good to hear! I'll therefore close this off.
