### ISSUE TITLE
Save and New

### ISSUE THREAD

**Issue by roleforgaming** [BookStackApp/BookStack#5164]
### Describe the feature you'd like

After completing a page, add an option to save and create a new page.

### Describe the benefits this would bring to existing BookStack users

Would streamline my workflow (often converting PDFs to Bookstack Books)

### Can the goal of this request already be achieved via other means?

Yes. I can click save, navigate  back to the chapter I'm working on pages for, and click New Page.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @roleforgaming, but I'm going to close this off as I feel it's already covered by existing issue #3382
