### ISSUE TITLE
Mention @user to send notification 

### ISSUE THREAD

**Issue by cittadhammo** [BookStackApp/BookStack#5167]
### Describe the feature you'd like

Would be nice to be able to use the @user to send notification in the edit mode or comment mode directly to the user, instead of having to write an email to them or contacting them via other means.

### Describe the benefits this would bring to existing BookStack users

Directly connecting with people instead of using email or 3rd app.

### Can the goal of this request already be achieved via other means?

Somehow if people are watching the page you are editing or commenting.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @cittadhammo, but I'd considered this already covered by existing issue #560 so I'll therefore close this off as a duplicate.
