### ISSUE TITLE
Insert source code from WYSIWYG editor (HTML input)

### ISSUE THREAD

**Issue by cittadhammo** [BookStackApp/BookStack#5168]
### Describe the feature you'd like

I want to embed google folder or other google doc in our pages. I can do it by editing the source code of the page and using the right iframe :` <iframe style="width: 100%; height: 600px; border: 0;" src="https://drive.google.c....t"></iframe>`, but it is very inconvenient to scroll and look for the place in the entire source code of the page in the editor.
It would be nice to have a button in the WYSIWYG toolbar to include source code HTML input 

### Describe the benefits this would bring to existing BookStack users

Can have nice embed and easy to use

### Can the goal of this request already be achieved via other means?

Yes, via modifying source code

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @cittadhammo,
I believe this may already be possible using the media content type in the editor:

![image](https://github.com/user-attachments/assets/ba0eb184-a72c-4acf-ab52-866ea5298488)


![image](https://github.com/user-attachments/assets/fff66cc0-3756-4912-b970-e6f54cec491f)

**Comment by cittadhammo** [comment]
Yes, this is exactly what I wanted, thank you very much,
Best regards.
