### ISSUE TITLE
Page Views Count

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#518]
### For Feature Requests

Desired Feature: Tracking page views count, displayed on the details div.

**Comment by ssddanbrown** [comment]
Hi @dsaundersWizmo, Thanks for your suggestion.

I've thought about this before, BookStack does store view information so it wouldn't be hard to add but I've often wondered what value it would offer on a documentation platform.

I could see the value if it was part of an 'Analytics' area of BookStack where stats could be viewed/exported regarding top viewed, least viewed, most active users, most active times etc.. This area could then be permission controlled.

**Comment by Ethanb00** [comment]
I'd favor an analytics page. Readers of the page don't care how often the page has been looked at. The main use would be the author. So that content would be best offered in a separate location.

**Comment by Shackelford-Arden** [comment]
@ssddanbrown Potentially something I had in my mind when I was thinking about this #440

**Comment by Chris-ZA** [comment]
An analytics page would be awesome! 

It would be a useful tool to figure out what books, chapters and pages aren't being read, how popular they are etc. 

I've often wondered if the stuff I document is ever read. :/

**Comment by dsaundersWizmo** [comment]
Yes—There are a couple of valuable aspects:


  1.  Our most used documentation should be reviewed more frequently to ensure up to date information.
  2.  If there is documentation that is considered something that people should only have to reference a couple of times and then know, if they keep going back to it our process may be complex or convoluted and could be improved.
  3.  Pages that aren’t viewed frequently can be audited for archival and/or see if there is a problem that makes it “un-useful”.
  4.  I wasn’t sure if the app tracked views, which was part of my suggestion for ‘Better Sort’.

**Comment by marcusforsberg** [comment]
> I could see the value if it was part of an 'Analytics' area of BookStack where stats could be viewed/exported regarding top viewed, least viewed, most active users, most active times etc.. This area could then be permission controlled.

Would love to see a feature like this, especially the ability to track user activity to see the top contributors.

**Comment by yoginth** [comment]
+1

**Comment by moretolearn01** [comment]
Analytics dashboard would be great to help identify content regularly being used, as well as those that may not be visited and therefore should be updated or removed.
Another item on the analytics dashboard/page that would provide insight is the search terms being used (ranked by number of occurrences) and the click through to pages, e.g. if they clicked through it may be counted as successful.

**Comment by s1mpleman** [comment]
Ditto on this, or at least an easy way to use google analytics. Trying to find a decent place to put it in the code but can't find it at the minute.

**Comment by fanyigle** [comment]
> Ditto on this, or at least an easy way to use google analytics. Trying to find a decent place to put it in the code but can't find it at the minute.
> 
> Edit: Found the custom code settings :)

@s1mpleman sorry,Could you kindly point out where the code resides.

**Comment by n0nag0n** [comment]
I echo a few of what others have suggested here regarding page views. I noticed recently that searching seems to be a little more accurate, I can only assume that you're roping in the page views into the sorting algorithm? It's still not perfect, but seems like the more common articles are up top.

I would like a page view count of some kind to find the popular pages and just make sure their content is up to par and if any updates need to happen with it. It'd be nice to have a report of some kind to show aging articles (by book, etc) so they can be updated if possible. Of course if none of this is possible, I can just hack my way into the db (or through the api) and manually create a page that would show this info.

**Comment by mso-l** [comment]
I agree, statistics are missing on BookStack :

document statistics in order to :
- highlight the most frequently consulted documents when searching for one or x keywords
- list documents that are not often consulted in order to archive / delete them

search statistics to list frequent searches that have no associated relevant document, in order to create those missing documents

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since the OP no longer exists, and the goals/values desired seem to be mixed.
Feel free to open a new specific issue to detail the user value/end-goal you desire, but note I'll probably only leave it open for consideration if the value can't already be gained by simply incorporating an external analytics option.
