### ISSUE TITLE
Missing type specifications for `name` and `password` in /users CREATE endpoint documentation

### ISSUE THREAD

**Issue by ln-ws** [BookStackApp/BookStack#5183]
### Describe the Bug

In the BookStack API documentation for the `/users` endpoint, specifically for the `CREATE` request, the body parameters documentation fails to specify the required type for the `name` and `password` properties. This omission can lead to confusion for developers implementing API calls, potentially resulting in incorrect data types being sent and causing unexpected errors.

### Steps to Reproduce

1. Navigate to the BookStack API documentation.
2. Scroll down to the section for the `/users` endpoint. 
3. Find the documentation for the `CREATE` request.
4. Observe that the `name` property lacks a type specification.
5. Observe that the `password` property also lacks a type specification.
6. Compare these to other properties in the same documentation that do have type specifications.

### Expected Behaviour

We expect the body parameters documentation for the `/users` `CREATE` endpoint to clearly specify the data types for all properties. Specifically:

- The `name` property should be explicitly labeled with the type `string`.
- The `password` property should also be explicitly labeled with the type `string`.
- This type information should be consistently presented, matching the format used for other properties in the same documentation.

### Exact BookStack Version

v24.05.3

**Comment by ssddanbrown** [comment]
Thanks for raising @ln-ws, this has been addressed as part of 1f2506221ad7207b37bd093ca3233347d6d76ca1 to be part of the next patch release.
