### ISSUE TITLE
Expand/enlarge image within the page

### ISSUE THREAD

**Issue by ddkooker2** [BookStackApp/BookStack#5189]
### Describe the feature you'd like

I would love to see a feature to expand the image within the same page of bookstack when clicking on one instead of Bookstack opening a new tab to show the image.

### Describe the benefits this would bring to existing BookStack users

It would make the reading of the pages more of a unified experience, people will no longer need to switch to a different Tab in thier browser to see an enlarged version of a posted image.

### Can the goal of this request already be achieved via other means?

Not that i know off

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @ddkooker2, but I'm going to close this off as I feel the fundamental request here is already covered by existing issue #464.
