### ISSUE TITLE
General API call

### ISSUE THREAD

**Issue by sahara101** [BookStackApp/BookStack#5190]
### API Endpoint or Feature

Hi, 

A way to show an API json response where you get the total number of books, pages, shelves, etc in the same API call. Maybe /summary

### Use-Case

I would love to be able too add Bookstack to Homepage. Right now with just one custom API URL possible I cannot combine the results. 

### Additional context

<img width="388" alt="image" src="https://github.com/user-attachments/assets/ebf22237-8f3e-4f55-b2d7-9577be03d124">

Here, by having a /summary API we could define both Total Books and Total Pages in the same widget for example. 

Thanks!

**Comment by chris-devel0per** [comment]
What would be the Information you want to receive there?
Could you give some example of the response? 

What would be the benefit of having that information? What do you exactly mean with "Homepage"?

**Comment by sahara101** [comment]
Hi. I think total numbers of pages, books, shelves would be a start. I made this for now:

https://github.com/sahara101/bookstack-gethomepage-api

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @sahara101 but I'm not keen on adding extra API endpoints for the primary purpose of adapting existing data you can get (totals) to suit specific business process (reduce to single API call).
