### ISSUE TITLE
Docker error after update of Ubuntu OS.

### ISSUE THREAD

**Issue by whiteboxnqn** [BookStackApp/BookStack#5191]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After updating from ubuntu 22.04 to 24.04 lts the docker container got an error:

![imagen](https://github.com/user-attachments/assets/2cc02034-97cd-43b0-96f1-d0f1f5206aab)

### Exact BookStack Version

v24.05.4-ls162

### Hosting Environment

Ubuntu 24.04 lts with latest docker versión

**Comment by ssddanbrown** [comment]
Hi @whiteboxnqn,
I'm assuming you also changed docker image during this process? Any idea which you were using before?
What exact image are you using? (`docker images --digests`, report back full details including digest for image used).
What kind of system are you running docker on (What hardware/CPU?)

**Comment by whiteboxnqn** [comment]
hi!
Thanks for the quick reply. No, I've not changed the docker image (I've
tried pull a new one and use older versions, but nothing works). The
problem started after ubuntu release upgrade.
this is my docker compose yml:

services:
bookstack:
image: lscr.io/linuxserver/bookstack
#image: ghcr.io/linuxserver/bookstack:v23.10.2-ls112
container_name: bookstack
environment:
- PUID=1000
- PGID=1000
- TZ=America/Argentina/Buenos_Aires
- APP_URL=xxxxxxx
- DB_HOST=bookstack_db
- DB_PORT= 3306
- DB_USER=xxx
- DB_PASS=xxxxx
- DB_DATABASE=xxxxx
- LETSENCRYPT_HOST=xxxxxx
- VIRTUAL_HOST=xxxx
volumes:
- /var/lib/docker/volumes/bookstack/bookstack_app_data:/config
ports:
- 8100:80
restart: unless-stopped
depends_on:
- bookstack_db
networks:
- whitebox-plataformas
bookstack_db:
image: lscr.io/linuxserver/mariadb
container_name: bookstack_db
environment:
- PUID=1000
- PGID=1000
- TZ=America/Argentina/Buenos_Aires
- MYSQL_ROOT_PASSWORD=xxxxx
- MYSQL_DATABASE=xxxxxxx
- MYSQL_USER=xxxxx
- MYSQL_PASSWORD=xxxxxxx
volumes:
- /var/lib/docker/volumes/bookstack/bookstack_db_data:/config
restart: unless-stopped
networks:
- whitebox-plataformas
networks:
whitebox-plataformas:
external: true

We have an EC2 Instance of Ubuntu in AWS with other dockers running smoothly.

--

**Comment by ssddanbrown** [comment]
@whiteboxnqn What exact image are you using? (docker images --digests, report back full details including digest for image used).

**Comment by whiteboxnqn** [comment]
Hi!
This is the output:
# docker images --digests

REPOSITORY                               TAG              DIGEST                                                                    IMAGE ID       CREATED        SIZE
ghcr.io/linuxserver/bookstack            24.05.4          sha256:ce6f876f5244413c251ba85468a830eac87ccee9bf62e95b1ca2d3cfec4d029f   c9d6e25215a8   3 days ago     377MB
lscr.io/linuxserver/bookstack            latest           sha256:ce6f876f5244413c251ba85468a830eac87ccee9bf62e95b1ca2d3cfec4d029f   c9d6e25215a8   3 days ago     377MB
lscr.io/linuxserver/mariadb              latest           sha256:56da9bba3e5e0a08d35d038b72263bebc33483f41b5c58ee8a0baca52247807f   df922606a45d   13 days ago    334MB
ghcr.io/linuxserver/bookstack            v24.05.3-ls159   sha256:646e6913d76dfde257c7fe6725c87126fe8f71299bd45b3a04596b46596fe7d0   d0ede66c9a34   2 weeks ago    376MB
portainer/portainer-ce                   2.20.3           sha256:f5277f6cab33b3471148fb00dc4b4a09995ba64b473448a58f616d202686564b   3255108e46a0   3 months ago   288MB
jwilder/nginx-proxy                      latest           sha256:188589dbc8978f42fc95ff5c13ddbcf320f5aceb8cbc2e3eb9db862a08ebd18e   97275ada6cc9   3 months ago   205MB
jrcs/letsencrypt-nginx-proxy-companion   latest           sha256:4080738c7e364f6df021d62faabbfcddd168dfe407946edf3e931c95d93cae90   1d70c7c23955   4 months ago   51MB
portainer/portainer-ce                   latest           sha256:4a1ceadd7f7898d9190ee0a6d22234c4323aefd80e796e84f5e57127f74370f1   a3f85c245ec3   4 months ago   293MB
ghcr.io/linuxserver/bookstack            v23.10.2-ls112   sha256:2d409840c8a3845895cd7f4c2f0f91e95caec02b33c71ffc3cd5f06361589151   67fc56d61ea7   9 months ago   360MB

**Comment by ssddanbrown** [comment]
Thanks @whiteboxnqn, what kind of AWS EC2 machine type are you running on?

**Comment by whiteboxnqn** [comment]
Hi!

The specs:
- General computing (t3a.small)
- 1 vcpu
- 4 gb ram
- 50Gb SSD 
- Description:    Ubuntu 24.04.1 LTS, Release:        24.04, Codename:       noble
- docker version: 27.2.0, build 3ab4256

**Comment by ssddanbrown** [comment]
Thanks. For testing, can you pin an exact image so we can consistently test one scenario.

So in your compose file, set:

```
image: ghcr.io/linuxserver/bookstack:24.05.4@sha256:13d74eb35d93f5ba53bfb894bc4e46e47a3e2565d2869dffb6c046726083d531
```

For the bookstack service. For my future reference, [this image is found here](https://github.com/linuxserver/docker-bookstack/pkgs/container/bookstack/265579211?tag=v24.05.4-ls162).
Then run a `docker compose pull` before re-upping the containers `docker compose up -d` (not restarting) then let me know if that's any different.

**Comment by whiteboxnqn** [comment]
Hi! 

Thanks for the info. Unfortunatelly changing the image didn't work. We have the same error.

![imagen](https://github.com/user-attachments/assets/4b13d6a5-98f1-4367-b01d-1b206718459b)

we executed:  docker compose down, (updated docker-compose.yml with the new image) and then docker compose pull, docker compose up -d. 

And the console of bookstack container shows: 
![imagen](https://github.com/user-attachments/assets/99ede705-9adc-4832-95e1-618c9675a72c)

**Comment by ssddanbrown** [comment]
Not sure what's up in this environment.

Such an "Illegal instruction" error would typically show if you're running on the wrong CPU architecture, or if expected CPU instructions were missing. Maybe there could be security features that could interfere in this kind of way.

Linuxserver just put out a new image, so you could try that, otherwise not sure what else I can suggest that can be easily checked.

**Comment by whiteboxnqn** [comment]
Thank you so much for the info. We just restore an old backup with ubuntu 22.04.
Best Regards
