### ISSUE TITLE
install docs wrong due to missing directory  "vendor"

### ISSUE THREAD

**Issue by dtsoden** [BookStackApp/BookStack#5196]
### Describe the Bug

https://www.bookstackapp.com/docs/admin/installation/#manual

many of the scripts fail from manual to the SH scripts all complain about a missing "vendor" folder and obviously missing files inside needed to perform the installations

### Steps to Reproduce

follow your own steps  https://www.bookstackapp.com/docs/admin/installation

### Expected Behaviour

it installs the application as needed

### Screenshots or Additional Context

dsoden@web2405:/home/aminosdocs/public_html$ cd BookStack/
dsoden@web2405:/home/aminosdocs/public_html/BookStack$ php artisan key:generate
PHP Warning:  require(/home/aminosdocs/public_html/BookStack/vendor/autoload.php): Failed to open stream: No such file or directory in /home/aminosdocs/public_html/BookStack/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/home/aminosdocs/public_html/BookStack/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/aminosdocs/public_html/BookStack/artisan:18
Stack trace:
#0 {main}
  thrown in /home/aminosdocs/public_html/BookStack/artisan on line 18

### Exact BookStack Version

v24.05.4

**Comment by ssddanbrown** [comment]
Hi @dtsoden,
That indicates that you have not ran step 2 (`composer install --no-dev`) or that the command is failing when ran.

Also, ensure you are not installing BookStack into an existing exposed/served web environment.
The fact you are install into a `public_html` folder makes me wary that you are installing in an existing web location.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up on this I'll go ahead and close this off.
