### ISSUE TITLE
[FEATURE REQUEST] Allow/Deny Access To Particular Users To View/Modify Particular Books/Chapters/Pages

### ISSUE THREAD

**Issue by viktorjamrich** [BookStackApp/BookStack#520]
Hey guys,
I started using BookStack today and I must say it's one the
best organizing apps I've came across!

I use it to give people in my company access to various docs and it would be absolutely awesome if there was a way to give access permissions to books/chapters/pages to particular people.

Looking forward for any updates ;)

**Comment by Shackelford-Arden** [comment]
@viktorjamrich 

Do the current permission levels not work for this? You can create custom roles/permissions and assign them to users.

**Comment by viktorjamrich** [comment]
I don't think that would work - correct me if I'm wrong.

I'd love to create let's say Financial Manual for my business.
But I would love only Monica and Dominica view that - nobody else - and Dominica can also edit that.

The same holds for other things like Sales Manual which could be read by all my salespeople, but my sales manager could also edit that - and nobody else could access that - etc...

Is it something that is doable right now with the roles and permissions? ;)

**Comment by ssddanbrown** [comment]
@viktorjamrich Yes, That's do-able with some setup.

You need to create different roles (In settings area) for the different permission profiles you want to create.

Then, create a book and set permissions on it by selecting permission in the 'more' menu when viewing a book:

![image](https://user-images.githubusercontent.com/8343178/30776234-e623572a-a09a-11e7-933e-8f2f045e0c90.png)

In the permission area you can change abilities for each role. You'll need to select 'Enable Custom Permission' at the top as well as any role permissions you want to grant:

![image](https://user-images.githubusercontent.com/8343178/30776263-3fc8f078-a09b-11e7-9774-fae85acb2166.png)

Permissions on books will cascade to child chapters and pages unless overridden.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please comment and this can be reopened if required.
