### ISSUE TITLE
Search Icon in Mobile View is slightly detached

### ISSUE THREAD

**Issue by noafilou** [BookStackApp/BookStack#5204]
### Describe the Bug

![Bildschirmfoto vom 2024-09-17 19-17-44](https://github.com/user-attachments/assets/5ad3dc70-d355-4155-804b-104769ce465e)

This happens only in mobile view of Search Results.

### Steps to Reproduce

1. Go to Search
2. Search something
3. Click Inspect and mobile view or resize window to mobile
4. See the Problem occur

### Expected Behaviour

The Icon should stay inside the Search Bar.

### Browser Details

Firefox 130.0 (64.bit)

### Exact BookStack Version

v24.05.4

**Comment by ninaa-e** [comment]
We solved this issue for us by adding an `tabindex="-1" ` in all.blade.php to the Button/Searchicon element.
The line looks like this in the End `<button tabindex="-1" type="submit">@icon('search')</button>`

The reason this works is, that if this is added, a css rule that the searchbar in the header uses will apply here.

**Comment by ssddanbrown** [comment]
Thanks for reporting @whoamiafterall, and thanks @ninaa-e for sharing the solution.
This has now been addressed in 42264f402d2733fdf7e1260c6731455d85da12b1 to be part of the next feature release.
