### ISSUE TITLE
Code blocks for SAS and R

### ISSUE THREAD

**Issue by gokkan** [BookStackApp/BookStack#5206]
### Describe the feature you'd like

The option to choose SAS and R when inserting code blocks.

### Describe the benefits this would bring to existing BookStack users

Would benefit most statisticians using Bookstack.

### Can the goal of this request already be achieved via other means?

Don't think so.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
This has now been added as part of 8bc6e75319583298e1f19df5441dc820772f3666 and will be part of the next feature release.
