### ISSUE TITLE
Updating from v23.10.4 to current version

### ISSUE THREAD

**Issue by steven-loscheider** [BookStackApp/BookStack#5211]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello,

quick question. I have Bookstack on Version 23.10.4, and I would like to update it to the most current release (as of today: 24.05.4)

Can I update to the latest version directly, or do I need to perform interim release updates to avoid corruption?

Brgds,
 

### Exact BookStack Version

23.10.4

### Hosting Environment

Ubuntu Server 22.04

**Comment by ssddanbrown** [comment]
Hi @steven-loscheider,
It's best to update directly to the latest version.

Either way, ensure you have backups (and ideally a whole system snapshot/backup).

**Comment by steven-loscheider** [comment]
@ssddanbrown 

Great news! Will upgrade to the current release next week!
Yes, we have backups and snapshots :)

**Comment by ssddanbrown** [comment]
I'll go ahead and close this off but feel free to still comment if you run into issues!
