### ISSUE TITLE
Allowing for a new chapter actually refers to a chapter from another book.

### ISSUE THREAD

**Issue by racson** [BookStackApp/BookStack#5214]
### Describe the feature you'd like

Apart from 'New Page' and 'New Chapter,' I would like to propose 'Add a Link Chapter.' Some books need to reference the same content, but this may involve a chapter with multiple pages rather than just a single page.

### Describe the benefits this would bring to existing BookStack users

If creating a similar book with just a few different chapters, most of the chapters can link to the core one.

### Can the goal of this request already be achieved via other means?

Yes, create the chapter and link to each page. All titles need to retype.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @racson, but I'm going to close this off as I feel the fundamental request is already covered by existing issue #1360.
