### ISSUE TITLE
Add a symbolic link to a page inside another book or chapter

### ISSUE THREAD

**Issue by Grazouillis** [BookStackApp/BookStack#5220]
### Describe the feature you'd like

I would like to find a page into several places.
Example : if a page is transversal and can be sorted in a chapter #checklist, #troubleshoot and #php, it could be nice if we could make a symbolic link without copying pages ? or a link to the main page to "make bridges" like this : 
![image](https://github.com/user-attachments/assets/fdcf6006-af19-40e2-9307-e447a0215814)

### Describe the benefits this would bring to existing BookStack users

Finding doc easier what we search because the partial indexation ?

### Can the goal of this request already be achieved via other means?

link a href, but not so easy

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @Grazouillis, but I'd consider the fundamental request/need here already covered by existing issue #182 so I'm going to close this off as a duplicate.
