### ISSUE TITLE
Features & Security settings will not save

### ISSUE THREAD

**Issue by Noxcivis** [BookStackApp/BookStack#5224]
### Describe the Bug

Features & Security settings will not save as checked.

### Steps to Reproduce

Ubuntu Linux 22.04.  Logged in as root.  I ran the following commands...

# Ensure you have read the above information about what this script does before executing these commands.

# Download the script
wget https://codeberg.org/bookstack/devops/raw/branch/main/scripts/installation-ubuntu-22.04.sh

# Make it executable
chmod a+x installation-ubuntu-22.04.sh

# Run the script with admin permissions
sudo ./installation-ubuntu-22.04.sh

Logged in as the admin account and went to "Features & Security" and checked each of the three boxes and pressed Save.  Nothing saves.  All go back to unchecked.

Pretty much everything else seems to work like the theme (Dark mode), etc.  I changed my password without issue.  So, pretty much cannot make the site Public for sharing documents.

### Expected Behaviour

Checkboxes work but pressing Save does not save them as checked.

### Screenshots or Additional Context

![Step 1 - Screenshot 2024-09-27 180322](https://github.com/user-attachments/assets/b8f52f14-ecec-448e-a4a7-9d5cfb114c15)
![Step 2 - Screenshot 2024-09-27 180351](https://github.com/user-attachments/assets/cc1919bc-92e5-4407-b95f-b28ce480e0df)

### Browser Details

Chrome, Firefox, Edge.  Multiple computers.

### Exact BookStack Version

v24.05.4

**Comment by ssddanbrown** [comment]
Hi @Noxcivis,

- If you create/edit a role, do changes to checkboxes there save okay?
- Do checkboxes in the "Settings > Registration" view save okay?
- Are you using a service in front of BookStack like Cloudflare?
- Are you familiar with browser developer tools? If so, report any errors seen in the console after reloading this view.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll go ahead and close this off.
