### ISSUE TITLE
My Favourites in header

### ISSUE THREAD

**Issue by cavar** [BookStackApp/BookStack#5230]
### Describe the feature you'd like

Now My Favourites link is inside My profile dropdown. It would be nice if there is option under profile, or in Settings for admin, to add/move My Favourites in header next to Shelves and Books.

### Describe the benefits this would bring to existing BookStack users

My Favourites would be on more visible place, and it would mean faster navigation.

### Can the goal of this request already be achieved via other means?

No as I know, only if i change source code of app in header.blade.php.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @cavar,
Just an FYI, if you enable UI shortcuts in the "My Account" area you can use a shortcut to jump to favourites.

> No as I know, only if i change source code of app in header.blade.php.

If you're happy to hack, you can do this via the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md), overriding [this view file](https://github.com/BookStackApp/BookStack/blob/development/resources/views/layouts/parts/header-links-start.blade.php) which exists to allow custom additions to the header bar.

**Comment by cavar** [comment]
Great, this is more then enough. Thanks 👍
