### ISSUE TITLE
Hidden Articles

### ISSUE THREAD

**Issue by anaszak** [BookStackApp/BookStack#5233]
### Describe the feature you'd like

I would like to have hidden public articles that doesn't appear on the menu or when a user search for a keyword, the article only accessed by direct URL. 

### Describe the benefits this would bring to existing BookStack users

Some public articles may contain information that we dont need everyone to read. For example, in a classroom, we want certain students to follow some instructions to install a program.

### Can the goal of this request already be achieved via other means?

I was able to create a chapter and hide it from the public, but the articles inside the chapters are searchable. if a user search for a keyboard, they can see and access the hidden article.
Can we add a feature to exclude certain article from the search

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by anaszak** [comment]
Similar requests are:
https://github.com/BookStackApp/BookStack/issues/3917
https://github.com/BookStackApp/BookStack/issues/1691

**Comment by ssddanbrown** [comment]
Thanks for the request @anaszak, but I'd consider the fundemental desire/request here to be similar enough to #1691 to be a duplicate, so I'm going to close this off as so.
