### ISSUE TITLE
Class "BookStack\Entities\Tools\PageEditorType" not found

### ISSUE THREAD

**Issue by ngoclanbaby86** [BookStackApp/BookStack#5237]
### Describe the Bug

Hello.

I got this error suddenly, although the files and libraries existed, the Home page was normal but when I wanted to edit it, this error appeared.

`Illuminate\View\ViewException
Class "BookStack\Entities\Tools\PageEditorType" not found (View: /usr/local/lsws/guide/BookStack/resources/views/pages/parts/editor-toolbar.blade.php) (View: /usr/local/lsws/guide/BookStack/resources/views/pages/parts/editor-toolbar.blade.php) (View: /usr/local/lsws/guide/BookStack/resources/views/pages/parts/editor-toolbar.blade.php)`

PHP Version: 8.2.21
BookStack Version: v24.05.4
Branch : Released.

### Steps to Reproduce

Cannot for unknown reasons

### Expected Behaviour

It shouldn't have happened because I was using it normally.

### Screenshots or Additional Context

![image](https://github.com/user-attachments/assets/91abafb0-3b74-4e50-adac-e467a20aef8c)

### Browser Details

chrome

### Exact BookStack Version

v24.05.4

**Comment by ssddanbrown** [comment]
Hi @ngoclanbaby86,
Can you confirm the exact output of running each of these from your BookStack install directory:

- `git status`
- `git log -n 2`

**Comment by ngoclanbaby86** [comment]
> Hi @ngoclanbaby86, Can you confirm the exact output of running each of these from your BookStack install directory:
> 
> * `git status`
> * `git log -n 2`

Hello @ssddanbrown 

Here is my result.


```
> # On branch release
> # Changes not staged for commit:
> #   (use "git add/rm <file>..." to update what will be committed)
> #   (use "git checkout -- <file>..." to discard changes in working directory)
> #
> #       modified:   .env.example
> #       modified:   .env.example.complete
> #       modified:   .gitattributes
> #       modified:   .github/CODE_OF_CONDUCT.md
> #       modified:   .github/FUNDING.yml
> #       modified:   .github/ISSUE_TEMPLATE/api_request.yml
> #       modified:   .github/ISSUE_TEMPLATE/bug_report.yml
> #       modified:   .github/ISSUE_TEMPLATE/config.yml
> #       modified:   .github/ISSUE_TEMPLATE/feature_request.yml
> #       modified:   .github/ISSUE_TEMPLATE/language_request.yml
> ................
> ................
> ................
> 
> #       modified:   tests/test-data/bad-phtml-png.base64
> #       modified:   tests/test-data/bad-phtml.base64
> #       modified:   tests/test-data/compressed.png
> #       modified:   tests/test-data/test-file.txt
> #       modified:   tests/test-data/test-image.png
> #       modified:   version
> #
> # Untracked files:
> #   (use "git add <file>..." to include in what will be committed)
> #
> #       app/App/mb_strimwidth.php
> #       queue_worker.log
> #       resources/views/misc/opensearch.blade.php
> #       resources/views/pages/parts/wysiwyg-editor-tinymce.blade.php
> no changes added to commit (use "git add" and/or "git commit -a")





> [root@g****ks BookStack]# git log -n 2
> commit b0dda6e6a729ac0d6f2af771f448118745f0d5da
> Author: Dan Brown <ssddanbrown@googlemail.com>
> Date:   Thu Aug 29 16:04:51 2024 +0100
> 
>     Updated version and assets for release v24.05.4
> 
> commit d4025d95e70230542ced133c32be529785e8aafb
> Merge: d6021f4 3a058a6
> Author: Dan Brown <ssddanbrown@googlemail.com>
> Date:   Thu Aug 29 16:04:37 2024 +0100
> 
>     Merge branch 'development' into release
```

**Comment by ssddanbrown** [comment]
@ngoclanbaby86 Your instance is in quite a messy state, you seem to have files that are not yet in our release (in development) along with files I wouldn't expect in either.

- Have you attempted to perform local customizations/additions to app code?
- Have you attempted to merge the development branch, or accidentally ran commands which merged this in?
- What's the output of `history | grep git | tail`? (make sure to remove any potential sensitive information)

**Comment by ngoclanbaby86** [comment]
> @ngoclanbaby86 Your instance is in quite a messy state, you seem to have files that are not yet in our release (in development) along with files I wouldn't expect in either.
> 
> * Have you attempted to perform local customizations/additions to app code?
> * Have you attempted to merge the development branch, or accidentally ran commands which merged this in?
> * What's the output of `history | grep git | tail`? (make sure to remove any potential sensitive information)

Hello.

Here is my result.

```
[root@gemteks BookStack]# history | grep git | tail
  911  git pull
  914  git pull
  925  git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch .
  931  git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch
  938  git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch
  979  git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch
  992  git status
  993  git log -n 2
  995  git status
 1018  history | grep git | tail
[root@gemteks BookStack]#
```

**Comment by ssddanbrown** [comment]
Thanks,

- Have you attempted to perform local customizations/additions to app code?
- Have you attempted to merge the development branch, or accidentally ran commands which merged this in?
- Have you attempted to update or overwrite app files from another source (like a zip download)?

**Comment by ngoclanbaby86** [comment]
Hello

I have re-install with old database and ok now.
the problem might happen when i tried to add helper file by myself. 
thank you for your support.
