### ISSUE TITLE
Welsh transition added but can't be selected from preferred languages

### ISSUE THREAD

**Issue by jaw123-aber** [BookStackApp/BookStack#5240]
### Describe the Bug

Welsh/cymraeg can't be selected by users as a preferred

I've had a look at the lang/en.settings.php

I can see that `language_select`

doesn't have an option for cy => Cymraeg

when that is added you can use Cymraeg

seems like it just needs adding to en from the notes in the file

### Steps to Reproduce

when logged in as a user navigate to `my account` and open the drop down for languages

Welsh/Cymraeg isn't an option

### Expected Behaviour

Cymraeg should appear as an option in the preferred languages selection screen

### Exact BookStack Version

v24.05.4

**Comment by ssddanbrown** [comment]
Hi @jaw123-aber,

Some languages will exist in the files, but not in the language list, where they are newer and are awaiting development to be at the point of mostly complete. 
That said, looks like the Welsh translations are now complete thanks to some big efforts by [KateBarber on Crowdin](https://crowdin.com/profile/katebarber/activity)!

I've now added the option in b1a3ea1aa4bfb0d9d20470858e0f41fcb73a85e1 so this will be made available as an option in the next feature release.
