### ISSUE TITLE
Sorting a book as myself, changes the update time of a page for another user

### ISSUE THREAD

**Issue by LittleBennos** [BookStackApp/BookStack#5241]
### Describe the Bug

Updated time will update when sorting, but not the user

### Steps to Reproduce

go to page, check created and last updated time

![image](https://github.com/user-attachments/assets/ff55ae8a-621c-4c59-9de8-94b5177ca0c9)

then go to book the page is in

select sort

move the order of the page

save

then go back to the page and the updated time will change, but not the user
![image](https://github.com/user-attachments/assets/6c55adfe-528f-4321-ab28-6b9b6ddeed8c)

additionally, the updated time of the book wont change

### Expected Behaviour

I think there are 2 different expected outcomes:

- sorting the book will only affect the last updated time of the book, with no changes to the page
- sorting the book will affect the last updated time of the book, also updating the page last updated time and user

### Browser Details

Chrome

### Exact BookStack Version

23.08.3

**Comment by ssddanbrown** [comment]
Thanks @LittleBennos, but I'm going to close this off since the fundamental request has already been raised in prior issue #1777.
