### ISSUE TITLE
Editing comments of made by another user

### ISSUE THREAD

**Issue by goldseal-henry** [BookStackApp/BookStack#5242]
### Describe the Bug

When a comment is made on a page, it can be edited by another user. There is a tag saying it was "Updated" but not by who. It does show in the Audit Log who made the change but it shouldn't be changed by someone other than the original author of the comment.

### Steps to Reproduce

1. Go to a Shelf/Book/Page and find a comment made by another user and edit it.
2. If there is no comment, have another user make a comment then edit it.

### Expected Behaviour

Only the originating author should have the ability to edit their comment.

### Exact BookStack Version

v24.05.4

**Comment by ssddanbrown** [comment]
Hi @goldseal-henry,
You should be able to hover over the updated tag to see who it was lasted updated by, and a timestamp for the update.

**Comment by goldseal-henry** [comment]
Thank you.
