### ISSUE TITLE
Creating an additional category - A cabinet with shelves

### ISSUE THREAD

**Issue by thedemoncat** [BookStackApp/BookStack#5244]
### Describe the feature you'd like

Good afternoon!
I would like to have another hierarchy - a closet with shelves.For example, the cabinet will belong to one department, which will group sections of documentation by shelves.
There are not enough groupings at the moment (

### Describe the benefits this would bring to existing BookStack users

More convenient management and categorization of documentation

### Can the goal of this request already be achieved via other means?

I think not at the moment.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for raising @thedemoncat, but extra levels has been discussed in quite a few prior issues, with the original being #95, so I'm going to therefore close this off as a duplicate.
