### ISSUE TITLE
New update seems to break the WYSIWYG of the edit/draft page

### ISSUE THREAD

**Issue by koen-divtag** [BookStackApp/BookStack#5249]
### Describe the Bug

After updating the application i wanted to add a new page.
When i tried to open it, it showed multiple js errors in my console and the page does not show the content of WYSIWYG.
I can edit the title and save with pressing enter but that is it. This goes for creating or editing that i know of. 

### Steps to Reproduce

Create a new page or edit an existing page. Content / WYSIWYG is not shown.

### Expected Behaviour

I expect to see and be able to use the WYSIWYG so i can change my wiki content. 

### Screenshots or Additional Context

Example edit page. No content/WYSIWYG shown, only title.
![image](https://github.com/user-attachments/assets/b662c8f7-d6fd-4fdd-a743-066d01b83aca)
The errors shown in the console log.
![image](https://github.com/user-attachments/assets/83108792-33d3-4854-b4bf-f7185b018aec)

### Browser Details

Google Chrome Version 129.0.6668.58 (Official Build) (64-bit)

### Exact BookStack Version

v24.10

**Comment by ssddanbrown** [comment]
Hi @koen-divtag,
I'm seeing some things in the details provided that don't align with the latest release.

- Did the update steps complete okay?
- What updates steps did you perform?
- How did you originally install BookStack?
- Do you have any theme system customizations active (code in the `themes/` folder)?

**Comment by koen-divtag** [comment]
Hi @ssddanbrown,
What are the details that you see that don't align with the release?

- Did the update steps complete okay?
Yes, we have this automated for over a year and has not gone wrong since. I checked the output to be sure but i see no errors.
- What updates steps did you perform?
Clone latest update from git (26aadff), ran composer install. Ran migrate, only one migration was run. And then i cleared the cache and restarted the queue.
- How did you originally install BookStack?
Manually at first from docs https://www.bookstackapp.com/docs/admin/installation/, but now automated. It Clones the new update over the old one that we get from the git repo and then runs a few laravel commands.
We run it on a Ubuntu 20 server with php8.3 and nginx.
- Do you have any theme system customizations active (code in the themes/ folder)?
No, the themes directory is empty.
![image](https://github.com/user-attachments/assets/3ddb674f-1e10-4220-8c99-713a4c572bf7)

Only thing i can think of right now is that we copy the new source over the old source. Could this cause any issues that you know of?

**Comment by ssddanbrown** [comment]
> What are the details that you see that don't align with the release?

The template code in the error does not match the latest release, but the previous release(s) indicating the template used is not current.

> Only thing i can think of right now is that we copy the new source over the old source. Could this cause any issues that you know of?

Definitely introduces an extra complication. Could cause issues where folders/files are not removed as expected, or potentially have files missed in the process. Main issue is that is makes it hard to verify the state of the setup.

Worth force removing cached views like so (go careful, dangerous command, ideally backup things first):

```bash
sudo rm -rf /srv/wiki/bookstack/storage/framework/views/*.php
```

**Comment by koen-divtag** [comment]
I tried removing the views cache like you said but it didn't do anything.
Probably because we run php artisan view:cache which does the same that i know of.

Removing the whole application and reinstalling seems to do the trick!
So ill fix it so that we will be reinstalling the whole application every update.
Thank you for your time!

**Comment by ssddanbrown** [comment]
Good to hear you found a solution, I'll therefore close this off.
You shouldn't have to reinstall the app though, generally that indicates a cache that is not being cleared, potentially due to permissions (cache cleared/generated but can't be written or overwritten by app server in use).
