### ISSUE TITLE
500 Error on page creation

### ISSUE THREAD

**Issue by GamerClassN7** [BookStackApp/BookStack#5252]
### Describe the Bug

When only one specific user creates page he get 500 error but bage is saved and after refresh it not happen in next aprox 40 min

### Steps to Reproduce

1. Go to Pages
2. create Page
3. Write Some text
4. Click Save

### Expected Behaviour

not to get the 500 but after saving page be redirected to new page

### Screenshots or Additional Context

only log messages is this:
`[2024-10-09 14:52:46] production.ERROR: Connection could not be established with host "localhost:587": stream_socket_client(): Unable to connect to localhost:587 (Connection refused) {"userId":67,"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Connection could not be established with host \"localhost:587\": stream_socket_client(): Unable to connect to localhost:587 (Connection refused) at /app/www/vendor/ssddanbrown/symfony-mailer/Transport/Smtp/Stream/SocketStream.php:154)`

Whitch is wierd because we dont use SMTP with bookstack at all :(

### Exact BookStack Version

v24.05.4

**Comment by ssddanbrown** [comment]
> Whitch is wierd because we dont use SMTP with bookstack at all :(

Does that mean you've configured email via other means? Or that you just don't expect email to be used at all?

I'm guessing a user is using email-based features in some way (watching/notifications) and that this fails to send causing an error.

**Comment by GamerClassN7** [comment]
> > Whitch is wierd because we dont use SMTP with bookstack at all :(
> 
> Does that mean you've configured email via other means? Or that you just don't expect email to be used at all?
> 
> I'm guessing a user is using email-based features in some way (watching/notifications) and that this fails to send causing an error.

I mean, users even have permission to setup/receive notification, nether configuration contains any email confirmation. It should be possible to switch  email if it is not needed, right ? :) certainly there shouldn't be an error. :/

**Comment by ssddanbrown** [comment]
I'm not sure I understand/follow.

We don't disable email features based upon whether email is configured, we generally expect it will be if email features are then used.
If you don't want users to handle/receive notifications, you can update their roles to not have the "Receive & manage notifications" role system permission.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll go ahead and close this off.
