### ISSUE TITLE
Bug Report: Trailing space of page title adds unnecessary - to URL

### ISSUE THREAD

**Issue by mackcoding** [BookStackApp/BookStack#526]
* BookStack Version: Latest (all versions)
* PHP Version: N/A
* MySQL Version: N/A

##### Expected Behavior
URL should be:
https://demo.bookstackapp.com/books/bookstack-user-guide/page/test

##### Actual Behavior
Actual url is 
https://demo.bookstackapp.com/books/bookstack-user-guide/page/test-

Browsing to https://demo.bookstackapp.com/books/bookstack-user-guide/page/test causes an error. 

This can be fixed by trimming whitespace.

**Comment by ssddanbrown** [comment]
Hi @mackcoding, Thanks for reporting.

Thought Laravel did this out of the box but looks like i needed to add in the middleware. Fixed as of aca6de49b0324c9b1cf48a79908f6d3ad2fd0d5a. Will be in next bugfix release.
