### ISSUE TITLE
Cannot update profile if your SSO name is 1 character long

### ISSUE THREAD

**Issue by trwnh** [BookStackApp/BookStack#5263]
### Describe the Bug

Updating your Bookstack profile picture is not possible as long as your name is less than 2 characters.

### Steps to Reproduce

1. Log into Bookstack with SSO while your SSO name is 1 character long
2. Try to update your profile picture

### Expected Behaviour

Updating my profile picture should work, but it doesn't.

### Screenshots or Additional Context

I get an error message "The name must be at least 2 characters." when trying to update my profile picture.

### Browser Details

Firefox 132 on Arch Linux

### Exact BookStack Version

24.10

**Comment by ssddanbrown** [comment]
Thanks for reporting @trwnh, don't see any reason to have a minimum of 2 rather than 1, so have changed this in 6f1c54d018f7d55301eb4c31055b04769f5924d7 to be part of the next patch release.
