### ISSUE TITLE
Feature Request - Limit the Length of the Sidebar

### ISSUE THREAD

**Issue by sadume** [BookStackApp/BookStack#527]
### For Feature Requests

Desired Feature:

Being able to limit the length of:

RECENTLY VIEWED
RECENTLY UPDATED
RECENT ACTIVITY

##### Expected Behavior
Would like to only see about 5 per thingy, would be nice if I can modify this from the menu or a config file.

##### Actual Behavior

Shows quite a lot of records, about 8-12 (assuming there has been a lot of activity)

**Comment by ssddanbrown** [comment]
Thanks for this request.

To be honest, I'm not really looking to get to this level of options & configurability. A future view-override/theme system may allow this customization, Otherwise I'll close this off. Since this issue was opened, design changes may now mean this is less relevant anyway.
