### ISSUE TITLE
Excalidraw on Bookstack

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#5284]
### Describe the feature you'd like

is it possible to add Excalidraw to the new text editor?
The function exists in Lexical (see picture)

![image](https://github.com/user-attachments/assets/a649f134-f3e5-4fac-9511-d7f9126e7767)

### Describe the benefits this would bring to existing BookStack users

alternative to Drawio

### Can the goal of this request already be achieved via other means?

over extra Excalidraw instance

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @reddexx, but this has been discussed before in #4053 so I'm going to therefore close this off.
I wouldn't look to add support just for being an alternative.

Also, the features shown in the lexical playground are often specific to their playground code, they are not part of the core lexical library, and even then the editor is just one fact of support for something like this.
