### ISSUE TITLE
Bookstack Keyckloak integration problem

### ISSUE THREAD

**Issue by umlumpa** [BookStackApp/BookStack#5286]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Colleagues, good afternoon! I want to integrate Bookstack with Keycloak. I have a problem: the Keycloak login page opens, I authorize, but for some reason, it does not redirect me back to Bookstack. Here are my configurations:
```
OIDC_CLIENT_ID: bookstack.example.com
OIDC_CLIENT_SECRET: secret_from_keycloak
OIDC_DISPLAY_NAME_CLAIMS: email
OIDC_DUMP_USER_DETAILS: 'true'
OIDC_GROUPS_CLAIM: resource_access.bookstack.roles
OIDC_ID_TOKEN_PRE_VALIDATE: 'false'
OIDC_ISSUER: https://auth.example.com/auth/realms/Example
OIDC_ISSUER_DISCOVER: 'true'
OIDC_NAME: Login with Keycloak
OIDC_REMOVE_FROM_GROUPS: 'true'
OIDC_USER_TO_GROUPS: 'true'
AUTH_AUTO_INITIATE: 'false'
AUTH_METHOD: oidc
APP_URL: https://bookstack.example.com
```
![Screenshot 2024-10-24 at 14 46 49](https://github.com/user-attachments/assets/77c2dd56-57da-4cb3-a43c-cd55f6756bc3)

after login it returns like this

![Screenshot 2024-10-24 at 14 49 30](https://github.com/user-attachments/assets/81c67e35-a29d-46d7-95fc-8d0f83014958)

### Exact BookStack Version

latest

### Log Content

there no logs

### Hosting Environment

In docker solidnerd/bookstack

**Comment by umlumpa** [comment]
![Screenshot 2024-10-24 at 14 46 49](https://github.com/user-attachments/assets/16e78ffa-ff0d-48f3-aa8c-c66e13a23947)
![Screenshot 2024-10-24 at 14 49 30](https://github.com/user-attachments/assets/20f153a6-83da-4b97-9538-5ee6e355fde6)

**Comment by ssddanbrown** [comment]
Hi @umlumpa,

You have `OIDC_DUMP_USER_DETAILS: 'true'` set currently. This stops the login process and dumps users details on attempted login. Remove that option (or set it to false) and you should get past that debug view.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'll go ahead and close this off.
