### ISSUE TITLE
Ability to use a local admin account when using ldap authentication

### ISSUE THREAD

**Issue by eoli3n** [BookStackApp/BookStack#5296]
### Describe the feature you'd like

We should not need to edit the config to be able to connect with a local admin account

### Describe the benefits this would bring to existing BookStack users

Ability to easily connect with local admin account to fix some permissions issues, without permission to connect ssh to the server.
And ability to not break users authentication when debugging something with admin account.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

I don't know any other service that works like Bookstack does.

**Comment by ssddanbrown** [comment]
Thanks @eoli3n but I feel the fundamental request is already covered by existing issue  #2715 so I'm going to close this off as a duplicate.

> And ability to not break users authentication when debugging something with admin account.

You should only need to change this for login. Once logged-in, you can switch this back right away to help avoid affecting other users.
