### ISSUE TITLE
Multiple APP_ULRS added to base URL

### ISSUE THREAD

**Issue by urbaman** [BookStackApp/BookStack#5299]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Deployed with 

APP_URL: https://bookstack.domain.com

Had to deploy multiple times due to APP_KEY and DB management

When I go to the URL, I get redirected to https://bookstack.domain.com/bookstack.domain.com/bookstack.domain.com/login

With a not well composed page and a 404 page not found at the end.

### Exact BookStack Version

v24.10-ls171

### Log Content

[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v24.10-ls171
Build-date: 2024-10-28T18:30:45+00:00
───────────────────────────────────────

using keys found in /config/keys
Waiting for DB to be available

   INFO  Preparing database.

  Creating migration table ......................................... 20ms DONE

   INFO  Running migrations.

  2014_10_12_000000_create_users_table ............................ 270ms DONE
  2014_10_12_100000_create_password_resets_table ................... 38ms DONE
  2015_07_12_114933_create_books_table ............................. 10ms DONE
  2015_07_12_190027_create_pages_table .............................. 9ms DONE
  2015_07_13_172121_create_images_table ............................ 10ms DONE
  2015_07_27_172342_create_chapters_table .......................... 10ms DONE
  2015_08_08_200447_add_users_to_entities .......................... 44ms DONE
  2015_08_09_093534_create_page_revisions_table ..................... 9ms DONE
  2015_08_16_142133_create_activities_table ......................... 9ms DONE
  2015_08_29_105422_add_roles_and_permissions ..................... 255ms DONE
  2015_08_30_125859_create_settings_table ........................... 9ms DONE
  2015_08_31_175240_add_search_indexes .............................. 0ms DONE
  2015_09_04_165821_create_social_accounts_table ................... 37ms DONE
  2015_09_05_164707_add_email_confirmation_table ................... 48ms DONE
  2015_11_21_145609_create_views_table ............................. 11ms DONE
  2015_11_26_221857_add_entity_indexes ............................ 267ms DONE
  2015_12_05_145049_fulltext_weighting .............................. 0ms DONE
  2015_12_07_195238_add_image_upload_types ......................... 37ms DONE
  2015_12_09_195748_add_user_avatars ............................... 11ms DONE
  2016_01_11_210908_add_external_auth_to_users ..................... 26ms DONE
  2016_02_25_184030_add_slug_to_revisions .......................... 38ms DONE
  2016_02_27_120329_update_permissions_and_roles .................. 143ms DONE
  2016_02_28_084200_add_entity_access_controls .................... 141ms DONE
  2016_03_09_203143_add_page_revision_types ........................ 24ms DONE
  2016_03_13_082138_add_page_drafts ................................ 27ms DONE
  2016_03_25_123157_add_markdown_support ........................... 24ms DONE
  2016_04_09_100730_add_view_permissions_to_roles .................. 59ms DONE
  2016_04_20_192649_create_joint_permissions_table ................ 279ms DONE
  2016_05_06_185215_create_tags_table .............................. 63ms DONE
  2016_07_07_181521_add_summary_to_page_revisions .................. 13ms DONE
  2016_09_29_101449_remove_hidden_roles ............................ 50ms DONE
  2016_10_09_142037_create_attachments_table ....................... 57ms DONE
  2017_01_21_163556_create_cache_table ............................. 34ms DONE
  2017_01_21_163602_create_sessions_table .......................... 34ms DONE
  2017_03_19_091553_create_search_index_table ..................... 158ms DONE
  2017_04_20_185112_add_revision_counts ............................ 41ms DONE
  2017_07_02_152834_update_db_encoding_to_ut8mb4 .................... 0ms DONE
  2017_08_01_130541_create_comments_table .......................... 62ms DONE
  2017_08_29_102650_add_cover_image_display ........................ 10ms DONE
  2018_07_15_173514_add_role_external_auth_id ...................... 24ms DONE
  2018_08_04_115700_create_bookshelves_table ...................... 260ms DONE
  2019_07_07_112515_add_template_support ........................... 32ms DONE
  2019_08_17_140214_add_user_invites_table ......................... 38ms DONE
  2019_12_29_120917_add_api_auth ................................... 61ms DONE
  2020_08_04_111754_drop_joint_permissions_id ...................... 59ms DONE
  2020_08_04_131052_remove_role_name_field ......................... 11ms DONE
  2020_09_19_094251_add_activity_indexes ........................... 25ms DONE
  2020_09_27_210059_add_entity_soft_deletes ........................ 45ms DONE
  2020_09_27_210528_create_deletions_table ......................... 49ms DONE
  2020_11_07_232321_simplify_activities_table ..................... 159ms DONE
  2020_12_30_173528_add_owned_by_field_to_entities ................ 159ms DONE
  2021_01_30_225441_add_settings_type_column ....................... 10ms DONE
  2021_03_08_215138_add_user_slug .................................. 30ms DONE
  2021_05_15_173110_create_favourites_table ........................ 36ms DONE
  2021_06_30_173111_create_mfa_values_table ........................ 38ms DONE
  2021_07_03_085038_add_mfa_enforced_to_roles_table ................ 11ms DONE
  2021_08_28_161743_add_export_role_permission ...................... 8ms DONE
  2021_09_26_044614_add_activities_ip_column ....................... 11ms DONE
  2021_11_26_070438_add_index_for_user_ip .......................... 13ms DONE
  2021_12_07_111343_create_webhooks_table .......................... 71ms DONE
  2021_12_13_152024_create_jobs_table .............................. 25ms DONE
  2021_12_13_152120_create_failed_jobs_table ....................... 24ms DONE
  2022_01_03_154041_add_webhooks_timeout_error_columns ............. 12ms DONE
  2022_04_17_101741_add_editor_change_field_and_permission ......... 22ms DONE
  2022_04_25_140741_update_polymorphic_types ....................... 59ms DONE
  2022_07_16_170051_drop_joint_permission_type ..................... 72ms DONE
  2022_08_17_092941_create_references_table ........................ 60ms DONE
  2022_09_02_082910_fix_shelf_cover_image_types ..................... 2ms DONE
  2022_10_07_091406_flatten_entity_permissions_table ............... 57ms DONE
  2022_10_08_104202_drop_entity_restricted_field ................... 57ms DONE
  2023_01_24_104625_refactor_joint_permissions_storage ............ 114ms DONE
  2023_01_28_141230_copy_color_settings_for_dark_mode ............... 4ms DONE
  2023_02_20_093655_increase_attachments_path_length ............... 61ms DONE
  2023_02_23_200227_add_updated_at_index_to_pages .................. 14ms DONE
  2023_06_10_071823_remove_guest_user_secondary_roles ............... 4ms DONE
  2023_06_25_181952_remove_bookshelf_create_entity_permissions ...... 0ms DONE
  2023_07_25_124945_add_receive_notifications_role_permissions ...... 5ms DONE
  2023_07_31_104430_create_watches_table ........................... 47ms DONE
  2023_08_21_174248_increase_cache_size ............................ 43ms DONE
  2023_12_02_104541_add_default_template_to_books .................. 12ms DONE
  2023_12_17_140913_add_description_html_to_entities ............... 32ms DONE
  2024_01_01_104542_add_default_template_to_chapters ............... 11ms DONE
  2024_02_04_141358_add_views_updated_index ........................ 12ms DONE
  2024_05_04_154409_rename_activity_relation_columns ............... 86ms DONE
  2024_09_29_140340_ensure_editor_value_set ......................... 6ms DONE

[custom-init] No custom files found, skipping...
[ls.io-init] done.

### Hosting Environment

MicroK8s 1.31
Ubuntu 24.04
Traefik as proxy (problem found even with kubernetes direct proxy)
Linuxserver image and deployment settings.

**Comment by ssddanbrown** [comment]
> When I go to the URL, I get redirected to https://bookstack.domain.com/bookstack.domain.com/bookstack.domain.com/login

That generally occurs if the `APP_URL` value is missing a protocol.
If you've made changes to this recently, you need to ensure that the config is taking effect, otherwise however the value is being passed to the containers might not be effective.
I'm not really confident on any k8s stuff so can't advise there.

**Comment by urbaman** [comment]
That's exactly the problem! Adding the `https://` protocol to the APP_URL worked, thank you!
