### ISSUE TITLE
OIDC Azure not reading group claims

### ISSUE THREAD

**Issue by jnantg** [BookStackApp/BookStack#5306]
### Describe the Bug

User not being assigned to group when logging in with OIDC

### Steps to Reproduce

Configure OIDC and set the variables:

OIDC_GROUPS_CLAIM=groups
OIDC_USER_TO_GROUP=true

Verify the group claim is showing when

OIDC_DUMP_USER_DETAILS=true

Add the group ID to a role

Log in as the user

### Expected Behaviour

The user should be assigned the group. For example "Editor" when the object ID of the group has been added to external authentication ID. However this is not the case. The user logs in, but is not granted the role specified. Even thought the claim is configured and shows when user detail dump is enabled.

### Browser Details

Microsoft Edge

### Exact BookStack Version

24.10

**Comment by ssddanbrown** [comment]
Hi @jnantg,

>  when the object ID of the group has been added to external authentication ID. 

- Does the ID added exactly match a value you see when you have `OIDC_DUMP_USER_DETAILS` enabled? 
- Can you share (where possible) the output of having `OIDC_DUMP_USER_DETAILS` enabled?

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll go ahead and close this off.
