### ISSUE TITLE
How long to read feature 

### ISSUE THREAD

**Issue by pedroalves5770** [BookStackApp/BookStack#5307]
### Describe the feature you'd like

It would be excellent if my articles have a “How long to read” Tag, like: “10 minutes estimated time to read”.

### Describe the benefits this would bring to existing BookStack users

It could encourage readers to keep reading if they know that this text is really short to read, in associated articles or in in search mode, for example. 

### Can the goal of this request already be achieved via other means?

You could manually estimate a how long to read time and write in every article, the idea is to have this automatic. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Thanks for the request @pedroalves5770, but I'm going to close this off in favour of existing issue #852 which requested the same.
