### ISSUE TITLE
Searching for word only works if put inside ""

### ISSUE THREAD

**Issue by DagW** [BookStackApp/BookStack#531]
### For Bug Reports

* BookStack Version: v0.18.1
* PHP Version:
* MySQL Version:

I added some text about trello, 
tried to search for 'trello' -> No matches
tried to search for '"trello"' -> 1 match

##### Expected Behavior
To find the trello word without qoutes

##### Actual Behavior
Did not find the word

**Comment by ssddanbrown** [comment]
Hi @DagW, Thanks for raising this issue. In your content, is `trello` a word by itself (With only spaces around it) or is it part of more text such as `trello-cat` or `mytrello`?

**Comment by DagW** [comment]
" trello " would be a word by itself, with spaces around it.
Also if the line starts with "trello "
Thanks, love the app otherwise. Im trying to work it in as the main documentation platform :-)

**Comment by ssddanbrown** [comment]
After a deeper dive it looks like there were some indexing issues when words are at the start of a line or when after tabs.

I've updated the indexing to be smarter, Will be part of the next bugfix release (Hopefully deploying sometime this weekend).

Let me know after the update if this does not fix your issues and I'll re-open this.

**Comment by yapret** [comment]
Hi @ssddanbrown, I'm running the v0.18.3, and still seem to encounter this (or a very similar) problem. 

I prefix page titles with words surrounded by brackets like [TRELLO], but can only find them when the said word is searched with quotes.

**Comment by ssddanbrown** [comment]
@yapret Thanks for raising, Just about to deploy a release that splits on more characters include brackets. 

After updating to v0.18.4 you'll need to regenerate the search index to see the effects:

```shell
php artisan bookstack:regenerate-search
```
