### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by lricora** [BookStackApp/BookStack#5319]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello, 
I'm a newbie. I tried to installa bookstack with Ubuntu 22.04 Installation Script. After installation, i have an HTTP error 500.

_[Tue Nov 12 09:32:18.019649 2024] [php:warn] [pid 111001] [client X.X.X.X:28155] PHP Warning:  require(/var/www/bookstack/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/bookstack/pub
lic/index.php on line 34_

I have many errors in the installation logs :

> [4/9] Installing Composer (PHP dependency manager)...
> PHP Warning:  copy(https://composer.github.io/installer.sig): Failed to open stream: Connection timed out in Command line code on line 1
> PHP Warning:  copy(https://getcomposer.org/installer): Failed to open stream: Connection timed out in Command line code on line 1
> PHP Warning:  hash_file(composer-setup.php): Failed to open stream: No such file or directory in Command line code on line 1
> Could not open input file: composer-setup.php
> rm: cannot remove 'composer-setup.php': No such file or directory
> mv: cannot stat 'composer.phar': No such file or directory
> [5/9] Installing PHP dependencies using composer...
> Could not open input file: /usr/local/bin/composer
> [6/9] Creating and populating BookStack .env file...
> PHP Warning:  require(/var/www/bookstack/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/bookstack/artisan on line 18
> PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/bookstack/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/bookstack/artisan:18
> Stack trace:
> #0 {main}
>   thrown in /var/www/bookstack/artisan on line 18
> [7/9] Running initial BookStack database migrations...
> PHP Warning:  require(/var/www/bookstack/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/bookstack/artisan on line 18
> PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/bookstack/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/bookstack/artisan:18
> Stack trace:
> #0 {main}
>   thrown in /var/www/bookstack/artisan on line 18

How can i fix this issue ?

### Exact BookStack Version

N/A

### Log Content

_> [4/9] Installing Composer (PHP dependency manager)...
> PHP Warning:  copy(https://composer.github.io/installer.sig): Failed to open stream: Connection timed out in Command line code on line 1
> PHP Warning:  copy(https://getcomposer.org/installer): Failed to open stream: Connection timed out in Command line code on line 1
> PHP Warning:  hash_file(composer-setup.php): Failed to open stream: No such file or directory in Command line code on line 1
> Could not open input file: composer-setup.php
> rm: cannot remove 'composer-setup.php': No such file or directory
> mv: cannot stat 'composer.phar': No such file or directory
> [5/9] Installing PHP dependencies using composer...
> Could not open input file: /usr/local/bin/composer
> [6/9] Creating and populating BookStack .env file...
> PHP Warning:  require(/var/www/bookstack/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/bookstack/artisan on line 18
> PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/bookstack/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/bookstack/artisan:18
> Stack trace:
> #0 {main}
>   thrown in /var/www/bookstack/artisan on line 18
> [7/9] Running initial BookStack database migrations...
> PHP Warning:  require(/var/www/bookstack/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/bookstack/artisan on line 18
> PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/bookstack/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/bookstack/artisan:18
> Stack trace:
> #0 {main}
>   thrown in /var/www/bookstack/artisan on line 18_

### Hosting Environment

PHP 8.1.2 on ubuntu 22.04 (fresh OS)

**Comment by ssddanbrown** [comment]
Hi @lricora,
It looks like the script failed to fetch required files, maybe because of a network connection issue during install?
Are there any limitations in regards to the internet access/ability of this machine?
Might be worth re-trying the install process, just in case it was a temporary issue.

You'll need to start from a fresh system though, the script isn't intended to be ran more that once.
Also, any reason to start on Ubuntu 22.04? If this is a fresh system, it would make sense to use the latest Ubuntu LTS version (24.04) instead of an older one.

**Comment by lricora** [comment]
Hello,
I have no internet access issue on this machine. I will retry with new VM.
For Ubuntu version, I am dependent on a system team ;)

**Comment by lricora** [comment]
problem solved : php composer didn't work with proxy...
