### ISSUE TITLE
how works search?

### ISSUE THREAD

**Issue by turbotankist** [BookStackApp/BookStack#532]
Hello!
I have imported pages from jira direct to mysql
INSERT INTO pages VALUES (id, book_id, chapter_id, name, slug, html, 
   text , priority, created_at, created_at, 1, 1, 0, 0, markdown, 1)
These pages are ok in my book. But search don't work with it. 
I see the "search_terms" table in DB and it is empty. Can I fix it? 

Or how can I create page by POST request in web no direct database?

**Comment by ssddanbrown** [comment]
Hi @turbotankist,

You will need to rebuild the search index after a manual import. You can do this by running the following commands from your BookStack install folder:

```
php artisan bookstack:regenerate-search
```

**Comment by turbotankist** [comment]
Thanks!
That's what i need! 
Works perfect.
