### ISSUE TITLE
Unable to restore from backup

### ISSUE THREAD

**Issue by dannyjrr** [BookStackApp/BookStack#5320]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have the exact same issue as the user on #4207 however when I go to `cat /etc/apache2/sites-available/bookstack.conf | grep ServerName` I get my server IP instead of the domain name. I have tried accessing via http://<domain> but that doesn't work anymore either.  How can I resolve this issue?

### Exact BookStack Version

Unknown

### Hosting Environment

Ubuntu 22.04.5 LTS. Installed using documentation [here](https://www.bookstackapp.com/docs/admin/installation/)

**Comment by ssddanbrown** [comment]
- Did you use our script for the instance you're restoring into?
  - If so, when it promoted for the domain (or IP), what did you enter?
- Have you done any additional actions on the new system apart from BookStack install? (eg, using certbot, changed webserver config etc..)
- What are you intending to use for access? A domain name or an IP address?

**Comment by dannyjrr** [comment]
- I did use the script and I entered in my domain
- I haven't done anything else on the new system
- I want to use the domain name I was using for access. It had been working before but after I tried restoring it stopped working.

**Comment by ssddanbrown** [comment]
> I did use the script and I entered in my domain

Okay. That's odd then.
In that case, the `/etc/apache2/sites-available/bookstack.conf` is wrong and needs to be altered to use your domain. Replace the IP of in the value of `ServerName` in there with your domain, then restart your webserver (`sudo systemctl restart apache2.service`).

You'll have to use `http://` until you re-configure https on the new system, as you did for the old system.
If you had anything like hsts enabled on the old system, for the same domain, you have have a little trouble as the browser may force `https://` usage for the domain.

**Comment by dannyjrr** [comment]
I changed the ServerName to my domain and restarted the server but I am still seeing the same HTTP 500 error

**Comment by ssddanbrown** [comment]
@dannyjrr Check the latest logs in your apache error log (commonly `sudo tail -n 100 /var/log/apache2/error.log`).

**Comment by dannyjrr** [comment]
This is what I got
![gittt](https://github.com/user-attachments/assets/3cdfb22f-4af8-4a27-ae06-5f6c1b063ff9)

**Comment by dannyjrr** [comment]
I tried doing the reinstallation again and now my site is showing php code
![phphp](https://github.com/user-attachments/assets/7d7605bb-3c4a-4dbc-8278-d15ff3d217be)
