### ISSUE TITLE
`file://` attachment links not stored like `http://` and `https://`

### ISSUE THREAD

**Issue by haydenkwelsh** [BookStackApp/BookStack#5321]
### Describe the Bug

When a `http://` or `https://` attachment link is created ...
![image](https://github.com/user-attachments/assets/e017eec0-ce6e-47e3-8e1b-045b9d37eee4)
... it will be stored by Bookstack ...
![image](https://github.com/user-attachments/assets/7fdb9f71-f132-49c4-9759-062e33f2a63d)
... which makes updating a link used multiple times in a document easy, as you only have to change it once in the "Attachments" side menu.

On the other hand, when a `file://` attachment link is created ...
![image](https://github.com/user-attachments/assets/83665829-076d-496a-ab74-d7a9afc08bac)
... it is **NOT** stored by Bookstack ...
![image](https://github.com/user-attachments/assets/b6f2f1e2-e879-4334-8380-bfd8ed41aeeb)
... which makes updating a link used multiple times in a document very tedious.

Apologies if this is behaviour has a sound reason behind it, but it seems like Bookstack storing all attachment links would be helpful and provide consistency.

### Steps to Reproduce

1. Create an Attachment link starting with `http://` or `https://`.
2. Insert the Attachment link.
3. View the (Bookstack-stored) URL by clicking the newly-inserted link and the left-most chain (⛓) icon:
![image](https://github.com/user-attachments/assets/ab07e2b7-3254-4c85-b532-6daa0f06086d)
4. Repeat steps 1-3 for a link starting with `file://`.

### Expected Behaviour

All links (starting with `http://`, `https://`, `file://`, etc) added to a document's "Attachments" will be stored by Bookstack for ease of future link editing. Some may not be stored due to potential validation checks, but such failures should be indicated to the end user in the form of a pop-up or other sensible method.

### Screenshots or Additional Context

See screenshots taken above.

This is somewhat related to these other issues:
* [1669](https://github.com/BookStackApp/BookStack/issues/1669)
* [3488](https://github.com/BookStackApp/BookStack/issues/3488)

### Browser Details

n/a

### Exact BookStack Version

v24.02

**Comment by ssddanbrown** [comment]
Hi @haydenkwelsh,
From what I remember, we show/expose non http(s) links directly since we can't reliable be sure that other links types are going to function via the dynamic redirect mechanism that's in place for http(s) links.
Especially so with file links which are often blocked in various ways in modern browsers.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up, and I don't see an alternative better option, I'll go ahead and close this off.
