### ISSUE TITLE
No message when user has no right to delete attachment

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#5323]
### Describe the Bug

A user complained that he edited a page and wanted to delete an attachment. He clicked on the delete button for the attachment, confirm it but nothing happen. It turned out that the permission setting in the group was "own". Changing to "all" and he could delete the attachment in question. I guess the attachment was uploaded by another person.

### Steps to Reproduce

Check that the group setting for attachment is "onw". 
Edit a page as user A and upload an attachment
Save it
Edit the page as user B and try to delete the attachment. You can confirm the deletion but the attachment is still there.

### Expected Behaviour

Bookstack should provide a message why that attachment can't be deleted.

### Exact BookStack Version

v24.10.2

**Comment by ssddanbrown** [comment]
Thanks @JtheBAB for reporting.
Ultimately, the user shouldn't be provided the option in the first place if they don't have the permissions to perform the action. 

I've assigned to be addressed for the next feature release.

**Comment by ssddanbrown** [comment]
This has now been addressed in fcf0bf79a98c9b9b545d36ef728ee9cbe054048e, so that controls are not shown if the user does not have permission to use them. This will be part of the next feature release.

Thanks again for reporting @JtheBAB.
