### ISSUE TITLE
Title and Header Customization in BookStack

### ISSUE THREAD

**Issue by Ainz** [BookStackApp/BookStack#5326]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

The initial goal was to implement a structured text header with a specific title format: “HOMEWORLD.NET - CODEX of the UNBOUND.” This also required a meta title to display in the browser tab without causing duplication in the header. The process involved CSS styling, changes in the settings, and direct edits to theme and app Blade files.

https://homeworldlore.net

CSS Customization and Title Duplication
I first tried styling the header using CSS, aiming to split the title into two lines with sub-items. This approach worked visually, but I observed an absence of a distinct meta title setting. When the title was added through the App Name field in BookStack’s settings, it populated the browser tab title but also appeared visibly in the header, causing unwanted duplication. Tried toggling the App Name filed in different ways and with different symbols, like &nbsp; which should not be visible, but it was.

Blade File Edits: Theme and Default Application Files
To control the title directly, we modified Blade template files in both the active theme directory and the default application directory:

Theme Blade Edits: Changes to base.blade.php and plain.blade.php within the active theme directory (themes/YourTheme/views/layouts/) had no effect, indicating they were likely overridden or inactive, despite a relevant Them setting in .env.

Default Blade Edits: Direct modifications to base.blade.php and plain.blade.php in the app’s root directory (resources/views/layout/) were also ineffective for displaying the title.

To verify which Blade file was active, we inserted an `<h1>` test header in base.blade.php within the app’s root directory, which did appear as expected. This confirmed that changes to the root base.blade.php file were recognized, while those in the theme directory were not.

![image](https://github.com/user-attachments/assets/be8dc875-c633-4e31-ba93-696df258277e)

### Exact BookStack Version

24.10.2

### Log Content

There seem to be no errors logged relating to this matter

### Hosting Environment

Server OS: Ubuntu 24.04 LTS
Web server: Apache2 2.4.58
PHP 8.3.6
MySQL:  8.0.40

**Comment by ssddanbrown** [comment]
> Changes to base.blade.php and plain.blade.php within the active theme directory (themes/YourTheme/views/layouts/) had no effect

Hi @Ainz, That would be the wrong expected directory. The overriden files would be expected to be found in `themes/YourTheme/layouts/` (so no `views` folder involved when using the visual theme system).

**Comment by Ainz** [comment]
You mention that in your vid explaining the theme system, but still do not explain why I do not see the title when editing the default files. 

... what.. and suddenly it works... nuts

![image](https://github.com/user-attachments/assets/e17af673-6359-4b54-8da4-e9a6d7ddfab9)
