### ISSUE TITLE
Add Icelandic

### ISSUE THREAD

**Issue by Lord-asgeir** [BookStackApp/BookStack#5332]
### Language to Add

Icelandic

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ssddanbrown** [comment]
Hi @Lord-asgeir,
Thanks for offering to translate.
Icelandic has now been enabled for the BookStack Crowdin project: https://crowdin.com/project/bookstack/is

If the language remains mostly incomplete for a while, it may be removed again.
Once the language is mostly complete, it will be added to the language list as an available preference option in-app.
