### ISSUE TITLE
Simpler URL optimisation and nesting books within shelves

### ISSUE THREAD

**Issue by jadepilled** [BookStackApp/BookStack#5333]
### Describe the feature you'd like

Hi! I know that this has been requested at various other times but I'd like to remind the legendary BookStack dev that there is high demand for this. In short, I'd like to be able to simplify URLs as well as nest pages within shelves (which of course would alter their function and require books to be nested to only one shelf, with shelves acting not as a reference list but a container that excludes books from being sorted into other shelves).

### Describe the benefits this would bring to existing BookStack users

The primary benefit of this would be that domains can be simplified in a more user-friendly way. For instance, rather than displaying
`domain.com/shelves/shelf/books/book/chapter/page`, a site might be able to display 
`domain.com/shelf/book/chapter/page`, or `domain.com/shelf/book/page` in my opinion a much more user-friendly and SEO-optimised format. Ultimately this would result in broader usability and ease-of-use for the platform, as well as increased reach for websites hosted with BookStack.

### Can the goal of this request already be achieved via other means?

Not quite. I have experimented with implementing this format for some time but invariably ended up with a broken BookStack install. I managed to remove /shelves/ from URLs, but all links for pages, chapters, etc. were broken as they still used the old format. I sincerely tried my best to alter all the necessary functions including blade templates, models, the views folder etc. but I'm obviously missing something. I would love to see this implemented as a feature or fork in future as it would do amazing things for the optimisation of BookStack and its attractiveness to search engines, devs, users and advertisers.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

### Additional context

Thanks Dan! Keep up the incredible work mate.

**Comment by jadepilled** [comment]
Thanks Dan! Keep up the incredible work mate.

**Comment by ssddanbrown** [comment]
Thanks for the request and kind comments @jadepilled.

Sorry, but I am going to close this off though since the fundemental requests are already covered by existing requests (#4537 and #2686 being relevant) and due to multi-request issues being hard to track/handle.
