### ISSUE TITLE
Hello, what is the cause of this situation? I'm at my wit's wit...

### ISSUE THREAD

**Issue by github2023bye** [BookStackApp/BookStack#5334]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Synology 923+, DSM7.2.2
The docker image file (24.10.2-ls175) pulled by container manager cannot be connected to the MARIADB database after being deployed according to the tutorial, and later updated to 24.10.2-ls176 through the docker pull lscr.io/linuxserver/bookstack:latest, so the database and docker file of the original bookstack are deleted. The database is re-established and deployed according to the new image file, but the new An Error Occurred is displayed, and the problem cannot be found according to the container logs and configuration files, so I am helpless and ask for help.

### Exact BookStack Version

24.10.2-ls176

### Log Content

[bookstack.csv](https://github.com/user-attachments/files/17880415/bookstack.csv)
[book-cust](https://github.com/user
![book](https://github.com/user-attachments/assets/60498a0f-1e62-43a1-916f-7f04d30f028c)
-attachments/assets/844e9591-9208-40e6-9b5f-644a0d08ba38)
![book-cust](https://github.com/user-attachments/assets/41bbfa8c-3bb9-45f3-a33b-d603f9a61615)

### Hosting Environment

Synology dsm7.2.2 install PHP 8.1.9 (cli) (built: Dec 6 2022 02:51:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies(Official Suite); mariadb10 (official suite); Docker version 20.10.23, build 876964a (official suite)

**Comment by ssddanbrown** [comment]
Hi @github2023bye,

You'd need to check your app log for the actual cause of that error, which is likely to be at `/docker/bookstack/log/bookstack/laravel.log` looking at your volume mounts.

If you've added the `APP_KEY` recently as part of using a newer image, you may need to ensure you're including the `base64:` part of the generated key.

**Comment by github2023bye** [comment]
> 您好 ，
> 
> 您需要检查您的应用程序日志以了解该错误的实际原因，这可能是在查看您的卷挂载时。`/docker/bookstack/log/bookstack/laravel.log`
> 
> 如果您在使用较新映像时添加了 recently ，则可能需要确保包含生成的密钥的一部分。`APP_KEY``base64:`
Do you mean using a new APP_KEY?
I have also checked the laravel.log files, and the error records are all before the new image 24.10.2-ls176 is installed, and the new image file is installed in the early morning of 2024.11.23, so I feel that I have no clue and have no way to start
[laravel.log](https://github.com/user-attachments/files/17880453/laravel.log)

**Comment by github2023bye** [comment]
> 您好 ，
> 
> 您需要检查您的应用程序日志以了解该错误的实际原因，这可能是在查看您的卷挂载时。`/docker/bookstack/log/bookstack/laravel.log`
> 
> 如果您在使用较新映像时添加了 recently ，则可能需要确保包含生成的密钥的一部分。`APP_KEY``base64:`

It is amazing that I got the new key when installing the new image. After you reminded me to try to copy the whole key field, including bash64:, and then refresh it, a complete login interface appeared. Thank you, I have been blocked for three days because of this problem

**Comment by ssddanbrown** [comment]
Good to hear things are now working! I'll therefore close this off.
