### ISSUE TITLE
Codeblock inside of lists, end list.

### ISSUE THREAD

**Issue by Valiantiam** [BookStackApp/BookStack#534]
### For Bug Reports

* BookStack Version: v0.18.1
* PHP Version: 7.0

##### Expected Behavior
I should be able to nest code blocks and other items within lists, and then continue those lists somehow. 

![image](https://user-images.githubusercontent.com/5394853/30986547-6d031822-a459-11e7-8c2a-5459f31b69e1.png)

##### Actual Behavior
When doing a shift+enter to go to a new line without a doublespace, codeblocks in the WYSIWYG editor, try to turn the entire bulletpoint into a codeblock.

![image](https://user-images.githubusercontent.com/5394853/30986567-7987d8da-a459-11e7-9ba2-edd5351fac65.png)

**Comment by stealthbird77** [comment]
I have noticed that the latest version of tinyMCE has this functionality working.  

If Bookstack updated to tinyMCE latest would this feature work?

**Comment by Valiantiam** [comment]
I would also enjoy seeing this re-visited.

**Comment by MaartenUreel** [comment]
Would really love to have this implemented!

**Comment by CodeFinder2** [comment]
Would also really appreciate this feature! :-)

**Comment by Lab-Things** [comment]
+1 !

**Comment by AvrumFeldman** [comment]
A small workaround which is possibly a bug.

You can get the code block as the next list entry. This doesn't work out of the box as when you are in the list you cannot click on the code block. The solution is to type two lines in another program (vscode) paste it into the list, select it and ctrl+x then the code block option becomes available.

See attached gif showing this in action
![f4tW7BrX6w](https://user-images.githubusercontent.com/42219106/143077052-9be21436-ec99-4afa-b8a2-01336496db8f.gif)


Note: When I was trying to reproduce it for the recording I kept on running into issues where it worked for a minute and then stopped until I figured out the above sequence, I don't know what the paste does, as I compared the text when written manually and when pasted from vscode and both had identical characters (including hidden characters).

**Comment by ghost** [comment]
+1

**Comment by stealthbird77** [comment]
With https://www.bookstackapp.com/blog/bookstack-release-v22-02/ using the latest version of TinyMCE.  Does this feature now work? 

I tested it and it seems too

**Comment by ssddanbrown** [comment]
> With https://www.bookstackapp.com/blog/bookstack-release-v22-02/ using the latest version of TinyMCE. Does this feature now work?
> I tested it and it seems too

This might well be the case. Not specifically tested this myself but within that release I significantly changed how code blocks are handled, which may mean wider parent location support.

**Comment by Valiantiam** [comment]
It does appear to be working now as desired! Great!
