### ISSUE TITLE
Publishing Permission.

### ISSUE THREAD

**Issue by FreeSynergy** [BookStackApp/BookStack#5347]
### Describe the feature you'd like

I would like to add another permission: publish.

This is important for people or groups, who can create some pages (authors), but the editors or the publishers can publish this content …

### Describe the benefits this would bring to existing BookStack users

You can open the wiki or Bookstack for everyone, but the editors behind this could decide, if this article/page/book can be published or not. This would be easier to manage bigger projects …

### Can the goal of this request already be achieved via other means?

I don't know. Maybe we publish 2 Books - the official and the unofficial … and everything you write in the unofficial can be moved to the official … but this is not a nice workaround.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

**Comment by ssddanbrown** [comment]
Thanks for the request @Lord-KalEl, but I feel the underlying request is similar enough to #473 that I'm going to close this off as a duplicate.
