### ISSUE TITLE
Codeblock not formatting shell as expected

### ISSUE THREAD

**Issue by Valiantiam** [BookStackApp/BookStack#535]
BookStack Version: v0.18.1
PHP Version: 7.0

##### Expected Behavior
![image](https://user-images.githubusercontent.com/5394853/30987209-cc5a2d7c-a45b-11e7-9499-1054e53b99fd.png)

It doesn't need to color it the same, but it should be expected to format commands etc. more. 

##### Actual Behavior

![image](https://user-images.githubusercontent.com/5394853/30987249-f236b9a2-a45b-11e7-9f13-feb4e3696a86.png)

It seems there is a lot of formatting missing or done in a different way? Not sure how intentional that is but it makes documenting linux related subjects odd.

**Comment by ssddanbrown** [comment]
Hi @Valiantiam,

Thanks for raising this. Yeah, there seemed to be a missing style. Now added in, Will be part of the next bugfix release. Here's a preview of the updated styles:

![image](https://user-images.githubusercontent.com/8343178/31045922-52efa2be-a5e6-11e7-9b60-89eaa3b6cebb.png)
