### ISSUE TITLE
Custom Header & Footer on page exports

### ISSUE THREAD

**Issue by lucasplcorrea** [BookStackApp/BookStack#5351]
### Describe the feature you'd like

I don't know if this functionality already exists and maybe I don't know where to use it or look for it. But I would like to customize the book exports, so that I could add something like a header and footer to the pages (export in PDF), or somehow customize the reports and documentation generated on the platform (export in HTML).

Is there anything like this? Does anyone already use it? Would this be a feature request?

### Describe the benefits this would bring to existing BookStack users

Granular and individually personalized customization. In my case, I use Bookstack to document procedures for companies of different types and businesses, having a way to customize the exports would make the documentation very beautiful and professional, as there are some users who only ask for the PDF because they cannot access the web portal.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 3 months

### Additional context

I use the platform to create simple procedural documentation, and I would like to include customizations that give my style to the document.

**Comment by ssddanbrown** [comment]
Thanks for the request @lucasplcorrea but I'm going to close this off as a duplicate since the request is already covered by existing issue #493.
