### ISSUE TITLE
Update Bookstack in a LXC Container and get  500 Internal Server Error

### ISSUE THREAD

**Issue by Hindin81** [BookStackApp/BookStack#5355]
### Describe the Bug

After Updating Bookstack to the latest Version 24.10.3 I get an 500 error. When I look into  
`tail` -n 100 laravel.log `

I see this error: 
`[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) at /opt/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
[stacktrace]
#0 /opt/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /opt/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /opt/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()`

There is a user "forge" listed. I don't have this user in my .env file

### Steps to Reproduce

I installed bookstack via community script as LCX Container in proxmox. The last updates went all fine. 
I installed the latest update 24.10.3 and I get an 500 error.

### Expected Behaviour

I expected a running version of bookstack after the update. 

### Exact BookStack Version

24.10.2 to 24.10.3

**Comment by ssddanbrown** [comment]
Hi @Hindin81,

> I installed bookstack via community script 

Can you confirm exactly what script?

Additionally, Can you re-run and share the update commands you're running, then also share the output you see for each.

**Comment by Hindin81** [comment]
Hi, I used this script to install: https://community-scripts.github.io/ProxmoxVE/scripts?id=bookstack 
This script installs Bookstack in the latest version in a Debian 12 LXC container under proxmox. At the same time an update command is installed with which you can then automatically update Bookstack in the LXC container.  
The update script you can see here: bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/bookstack.sh)" .
I installed Bookstack a long time ago. I can't remember which version it was, but certainly more than 6 months ago.

**Comment by ssddanbrown** [comment]
I'm kind confused by this, you installed more that 6 months ago but it looks like BookStack was only added to that project on the 5th? Did you migrate at some point?

Either way, I'm not confident on what's going on in the update script.
You won't see any output from the update commands since it's not shown, or hidden.

But the bigger issue is that I can't see how these scripts can reliably manage the codebase for BookStack.
I don't think that update script is going to be handling files properly, so I can't advise its use.

**Comment by ssddanbrown** [comment]
I've dug further into this, and raised my concerns with the community-scripts project:

https://github.com/community-scripts/ProxmoxVE/issues/757

A potential workaround, to convert the app to be managed as expected to allow our official update commands to be followed, can be seen [in my additional comment there](https://github.com/community-scripts/ProxmoxVE/issues/757#issuecomment-2529381401).

**Comment by Hindin81** [comment]
Hey, thank you very much. I was also able to narrow down the error to the wrong mv command and the incorrect handling of the .env and the previous uploads. With your instructions the update has now worked, and now I can continue with your instructions in the LXC container in the future. I will continue to support the guys from the helper scripts so that the update function also works properly. Thank you very much again.
