### ISSUE TITLE
The ability to inherit rights from shelves to books

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#5360]
### Describe the feature you'd like

I know that this has not been done because the books may be on different shelves, but we do not need it. Now, for each book, when creating it, you also have to give the rights to view / edit for the group. Hierarchical inheritance of rights is much more convenient, as in Windows SMB

### Describe the benefits this would bring to existing BookStack users

Easier rights management. Fewer actions when creating a book

### Can the goal of this request already be achieved via other means?

Yes. Manually specifying the rights when creating the book

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request but I'm going to close this off as its been discussed in many forms before (https://github.com/BookStackApp/BookStack/issues/1091, https://github.com/BookStackApp/BookStack/issues/2652, https://github.com/BookStackApp/BookStack/issues/1455, #3959) with #1596 also being related.
