### ISSUE TITLE
Syncing with git

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#5361]
### Describe the feature you'd like

Synchronize shelves/books/pages with get in the form of a hierarchy of folders and files to be able to create documentation directly from VSCode

### Describe the benefits this would bring to existing BookStack users

The ability to create documentation from the development environment

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request but I'm going to close this off as I feel the fundemental desire is already covered by #776 and since the goal of syncing/editing content from the development environment/vs-code is something I'd consider out of scope.
