### ISSUE TITLE
Add a new level: a group of books

### ISSUE THREAD

**Issue by jefry7** [BookStackApp/BookStack#5362]
### Describe the feature you'd like

Add a new level: a group of books

### Describe the benefits this would bring to existing BookStack users

Increase the maximum nesting level from 4 to 5

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for raising @jefry7, but extra levels has been discussed in quite a few prior issues, with the original being https://github.com/BookStackApp/BookStack/issues/95, so I'm going to therefore close this off as a duplicate.
