### ISSUE TITLE
Adding a tree level ‘library’ as a parent of ‘shelf’.

### ISSUE THREAD

**Issue by NicolasGuilbaud** [BookStackApp/BookStack#5368]
### Describe the feature you'd like

When using it in a business setting, I often face difficulties in segmenting the documentation. We use BookStack for several services, and adding a ‘library’ element as a parent of ‘shelf’ would be great for better segmentation.

### Describe the benefits this would bring to existing BookStack users

Adding the library will allow for finer segmentation of permissions by department within a company, for example. This is a missing element for use in a company with multiple multidisciplinary departments.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

Available to discuss.

**Comment by ssddanbrown** [comment]
Thanks for the request @NicolasGuilbaud, but additional levels have been discussed many times prior, with the original being in #95.
