### ISSUE TITLE
Role / User Access For Home Page

### ISSUE THREAD

**Issue by RyanH264** [BookStackApp/BookStack#5369]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi Bookstack community.
On my bookstack application I have edited the home page blade file to contain hyper links to some external websites that a lot of my users use frequently. I want to add a new user / role to my bookstack application, but I don't want them to have access to these links. Is there any way that I can restrict access to the home page for a role in bookstack?

I'm guessing I could do it with some php cleverness, but wanted to get a second opinion before I go playing Dr. Frankenstein with my bookstack application any further. 

### Exact BookStack Version

 v24.02.3

### Log Content

No log content as the issue is more related to myself not knowing the best way to add a desired function.

### Hosting Environment

Amazon AWS Windows Server 2022 running Xampp, Apache, mySQL.

**Comment by ssddanbrown** [comment]
Yeah, There's no direct simple way for this built in.

There's a kinda complex way you could have role/permission controlled links on the homepage, by setting the homepage option to be a "Specific Page" (in customization settings) then, in that page, use [include tags](https://www.bookstackapp.com/docs/user/reusing-page-content/#include-tags) for the permission controlled content, then on the included pages set custom page-level permissions for roles as required.

**Comment by RyanH264** [comment]
Thanks Dan.

I might try a hybrid of both options and see how I go. Happy to mark this support issue as closed.
