### ISSUE TITLE
MariaDB Migrate Errors

### ISSUE THREAD

**Issue by vClouds** [BookStackApp/BookStack#537]
### For Feature Requests

Desired Feature:

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: v0.18.2
* PHP Version: 7.1.19
* MySQL Version: 10.1.28 (MariaDB)

##### Expected Behavior

Following the installation instructions along with [https://www.bookstackapp.com/docs/admin/ut8mb4-support/](url) results in the below shown current behavior.

Database already created using the below,
```
mysql -u root -p
CREATE DATABASE `bookstack` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL ON bookstack.* to 'bookstack'@'localhost' IDENTIFIED BY 'P@ssW@rd';
FLUSH PRIVILEGES;
```
and adjusted using the below,

```
ALTER DATABASE `bookstack` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `bookstack`;
```

##### Current Behavior

```
[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maxim  
  um column size is 767 bytes. (SQL: alter table `search_terms` add index `se  
  arch_terms_term_index`(`term`))
[PDOException]                                                               
  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maxim  
  um column size is 767 bytes. 
```

**Comment by juliusvaart** [comment]
Had the same problem. Forgot to run `php artisan key:generate`

**Comment by Relgisri** [comment]
Still have this error.
But I run the key generation...

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
