### ISSUE TITLE
Disabling Comments

### ISSUE THREAD

**Issue by Ethanb00** [BookStackApp/BookStack#541]
Desired Feature: Ability to disable/hide comments either globally and/or by page/chapter/book. 

For my purposes (Technical Documentation for a small team), the comments section, for the most part, is an unneeded resource. I totally under the utility for others, but I do not intend on using it. 

As a result, it would be nice to be able to disable it. I don't have a preference if that switch is global, by book, by chapter, or by page.  Turning it off would remove an unused a page component and clean up the UI a bit.

Thank you!

**Comment by Shackelford-Arden** [comment]
I like this idea. Definitely like the idea of having book/chapter level control of comments.

I realize you want to keep this simple @ssddanbrown but would this be something that we could potentially look at adding to a **Chapter/Book Settings** menu?

**Comment by salimnanji** [comment]
+1

**Comment by criskolkman** [comment]
+1 for me!

**Comment by faizmali** [comment]
We would greatly appreciate this feautre as well

**Comment by galaxyfeeder** [comment]
+1

**Comment by Abijeet** [comment]
Ok, there a few ways this can be done,

| Option                | Role                                         |
|-----------------------|----------------------------------------------|
| Global option         | Only administrator can do this.              |
| Option on the book    | People who have modify access to the book    |
| Option on the chapter | People who have modify access to the chapter |
| Option on the page    | People who have modify access to the page    |

I think row 1 and 2 should suffice. Let me know what you guys think. Once we have the requirements nailed down and @ssddanbrown has taken a look, I can submit a PR.

**Comment by Ethanb00** [comment]
@abijeet: I concur. Chapter and page are likely too granular. Per-book or global rights fit much better in terms of generating forms for documentation. 

Thank you for your work!

**Comment by ssddanbrown** [comment]
Yeah, I think we should keep this at a global level. Will mark up for next feature release (v0.19). @Abijeet Feel free to go ahead with this one if you'd like.

**Comment by Abijeet** [comment]
Have started working on this, few things to note - 

1. Added an option under app settings - **Disable comments**
2. If this is turned **on** then, 
   1. Adding comments is disabled.
   2. Existing comments will not be shown.
   3. The entire comments section is removed and no message is shown stating that comments are disabled.

Two things are debatable here,

1. _Do we show a message stating that comments are disabled?_ Not sure if it's needed, but can be easily added.
2. _Do we show existing comments?_ I removed them to save an extra query to fetch the comments.

**Comment by Shackelford-Arden** [comment]
For what it's worth, my opinion would be that if you disable comments, don't show them. I like what you said about saving ourselves the extra query.

**Comment by Ethanb00** [comment]
I think the absence of comments is clear enough that they are disabled. My goal with disabling them is to have as little extra stuff as possible on the page.

**Comment by jleroy** [comment]
IMHO @Abijeet choices are good ones. :)

**Comment by ssddanbrown** [comment]
I totally agree, Just hide all existence of comments with the option enabled.

**Comment by ssddanbrown** [comment]
Featured now added by @Abijeet within #593. Will be in the next release.
