### ISSUE TITLE
Desired Feature: Page Templates

### ISSUE THREAD

**Issue by eplastiq** [BookStackApp/BookStack#547]
Pretty self explanatory.

We plan on use BookStack for our SOPs (standard operation procedure) and we use a fixed template to unify all the documents and this feature will help a lot. 

thanks

**Comment by Ethanb00** [comment]
+1

**Comment by Abijeet** [comment]
Similar feature here - https://github.com/BookStackApp/BookStack/issues/129

**Comment by ssddanbrown** [comment]
Thank for the suggestion @eplastiq. As @Abijeet has pointed out this has already been required. Vote up issue #129 with thumbs up to make it more visible when new features are decided upon.

I will therefore close this issue.
