### ISSUE TITLE
AzureExtendSocialite error upgrading to 0.18.3

### ISSUE THREAD

**Issue by agalisteo** [BookStackApp/BookStack#549]
* BookStack Version: 0.18.1
* PHP Version: 5.6
* MySQL Version: 5.7

Current Behavior
```php
  [ReflectionException]                                               
    Class SocialiteProviders\Azure\AzureExtendSocialite does not exist
```
Steps to Reproduce

```
git pull origin release
php5.6 artisan migrate
```

**Comment by dsaundersWizmo** [comment]
Same issue for me.

**Comment by ssddanbrown** [comment]
@agalisteo Did you run `composer install` as per the [update instructions here](https://www.bookstackapp.com/docs/admin/updates/)?

**Comment by agalisteo** [comment]
@ssddanbrown I forgot to run ```composer install``` with my php version. Solved!
