### ISSUE TITLE
Make images and attachments non-public

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#551]
Desired Feature: Make images and attachments non-public.

##### Expected Behavior

Images should not be accessible when Bookstack is configured to require login to view content.  

My proposed solution (keep in mind I know nothing about Laravel) is to create an image proxy that boots up a minimal version of the application (just enough) to get authentication functional.   The image proxy would be used when Bookstack is configured to require login to view content.  This would be transparent, meaning it can be enabled and disabled without having to modify existing content.  Something (I think) can be achieved with URL re-writing.

##### Current Behavior

According to https://www.bookstackapp.com/docs/admin/security/ images are publicly accessible (for perfectly valid technical/performance reasons).  

A user knowing a URL can view any image/attachment and could result in sensitive information being leaked.

##### Steps to Reproduce

Configure Bookstack to require login when viewing content, copy the URL of an image, open a new private/incognito browser window.  Image is visible.

**Comment by yoginth** [comment]
Please take steps on this issue! Everyone can able to see all the sensitive attachments including profile pictures!

![screenshot](https://user-images.githubusercontent.com/10177861/34639639-f27b2bf8-f309-11e7-9ae8-8d7726b561d5.png)

**Comment by ssddanbrown** [comment]
Just to confirm on this, Attachments are handled differently and, as long as your BookStack instance is set-up properly, they should not be publicly-accessible unlike images.

**Comment by ssddanbrown** [comment]
Potential solution started in #665

**Comment by yoginth** [comment]
Thanks! Awesome!

**Comment by ssddanbrown** [comment]
Potential solution deployed as part of v0.20.0, Details can be found in blog post:
https://www.bookstackapp.com/blog/beta-release-v0-20-0/

Leaving this open for feedback purposes.

**Comment by svarlamov** [comment]
Is there a plan to have this feature setup with S3 via URL signing/proxy?

**Comment by ssddanbrown** [comment]
Closing this now that the feature has made release, Feel free to open new issues for any image-auth related problems.
