### ISSUE TITLE
Site Navigation gets shortened too early

### ISSUE THREAD

**Issue by Wachert** [BookStackApp/BookStack#556]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.18.3

##### Current Behavior

![grafik](https://user-images.githubusercontent.com/16701558/31585936-6e8f4124-b1ca-11e7-8964-31913cc582b8.png)

Should be shortened using CSS or give us an option after how many signs it should be cutted of, or that we can define if it should get cut off or not.

Where can i find in code the shortening to change it right now for me?

**Comment by ssddanbrown** [comment]
Thanks for the request @Wachert. Just came across this again.
Looks like it was fixed as part of a duplicate request (#1206) and has been part of BookStack since v0.27. Will therefore close this off.
