### ISSUE TITLE
Individual CSS is not used in Editor

### ISSUE THREAD

**Issue by Wachert** [BookStackApp/BookStack#562]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.17.1

##### Expected Behavior

Individual CSS from the Settings Page should also be used in Page Editor

##### Current Behavior

It is not used in the Editor.

##### Steps to Reproduce

Change color of callouts as example, edit a page with a callout => standard css, save the page and view it -> your changed css from the settings is used

**Comment by jonathanadams** [comment]
I am also struggling to do something similar to this like adjust the width of the content.

For example on a page in non-edit mode the following CSS works but no matter what I try I cannot do something similar when in edit mode.

`<style>
.page-content {
max-width: 100%;
margin: 40px 40px 40px 40px;
}

.container.small {
    max-width: 100%;
    margin-left: 40px;
}
</style>`

**Comment by ssddanbrown** [comment]
Thanks for making this request. This addition is now in the `master` branch ready for the next release.
