### ISSUE TITLE
Allow custom session lifetime expiry

### ISSUE THREAD

**Issue by shane-smith** [BookStackApp/BookStack#570]
### For Feature Requests

Desired Feature: Allow the session lifetime to be overridden in the .env file.

##### Suggested Solution

Modify config/session.php

From:
```'lifetime' => 120,```
To:
```'lifetime' => env('SESSION_LIFETIME', 120),```

This then allows us to specify a custom value as `SESSION_LIFETIME=123` in the environment file.

I am happy to submit a pull request sometime in the next few weeks for this. Anyone else is welcome to do it for me in the meantime if you're willing to do it sooner.

**Comment by ssddanbrown** [comment]
@shane-smith Thanks for this request, It's now implemented and will be in the next release.

**Comment by shane-smith** [comment]
Thanks!

**Comment by candrews67** [comment]
Thanks!!
