### ISSUE TITLE
Allow silent registration when LDAP is enabled and using Social Login

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#572]
I know this comes off initially as an odd request: allowing silent registration when LDAP is enabled and using something like Google SSO.  However there is a use case for it.

Consider a case where originally users where signing in using LDAP and the application is later configured to use SSO.  Obviously in a business type setting, registrations would be limited to a single domain.  Thus it does make sense to continue allowing LDAP user to sign in with the option to link there Google account.

There may also be cases where not all users are present in LDAP but are present in Google.  Again, in a business setting, the registration domain would be limited.

##### Expected Behavior

LDAP log-in is enabled, registration is enabled and limited to a domain.
Existing LDAP users can continue to sign in.
Existing LDAP user can link the Google account
User can now sign in using Google or LDAP.
New users attempt to log in using Google (the registration page would still be disabled)
New user is automatically registered.

##### Current Behavior

When Google SSO is enabled, and LDAP login is enabled, new users are unable to login/create account.

##### Steps to Reproduce

Enable Google SSO
Attempt to register as new user

**Comment by ssddanbrown** [comment]
Thanks for this request @tuaris.

As mentioned in your related issue here: https://github.com/BookStackApp/BookStack/issues/574#issuecomment-423613126

This will now generally be possible to do as of the next release therefore I will close this.
