### ISSUE TITLE
UI Error visualizing a bold word in a code sample

### ISSUE THREAD

**Issue by agalisteo** [BookStackApp/BookStack#583]
### For Bug Reports

* BookStack Version v0.18.4:
* PHP Version: 5.6
* MySQL Version: 5.7

##### Expected Behavior

Visualize bold word in a code sample

```
<pre>
sample <b>sample</b> sample
</pre>
```
<pre>
sample <b>sample</b> sample
</pre>

##### Current Behavior

Bookstack page dont visualize bold word.

![not_bold 1](https://user-images.githubusercontent.com/4834264/32397615-edc52038-c0ea-11e7-969c-5593788f9ce1.png)

##### Steps to Reproduce

Create new page with the following code, save and visualize the page.

```
<pre>
sample <b>sample</b> sample
</pre>
```

**Comment by ssddanbrown** [comment]
Hi @agalisteo, Thanks for opening this issue. This is not so much of a UI error as much as it's done on purpose due to code blocks being rendered with codemirror.

This is already open under #481 so I will close this issue request but feel free to continue the conversions on #481.
