### ISSUE TITLE
Referencing Popular & New Books from Home Page

### ISSUE THREAD

**Issue by s0n-** [BookStackApp/BookStack#584]
I love the popular and new books section of the Books Page. It would be great to reference these two divs in a customized home page.  This would bring together a lot of good info as soon as the user logs in.

Is there a way to tweak a page to reference these entities?

**Comment by ssddanbrown** [comment]
Hi @s0n-,

Currently there is no simple way to bring these sections into the homepage without editing view files. I'll be sure to consider this when thinking about adding view customization options in the future though.

**Comment by s0n-** [comment]
Thanks - it would be helpful.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and now close this off since the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) is fairly well developed for doing visual customization as requested.
