### ISSUE TITLE
Autocomplete, Arrows etc. not working in Ubuntu Install Script Installation

### ISSUE THREAD

**Issue by sirup** [BookStackApp/BookStack#585]
### For Bug Reports

 - Ubuntu 16.04 Installation Script

##### Expected Behavior
I want to use Tab for Autocomplete or Arrow Down/Up for Previous command.

##### Current Behavior
Not working - Tab just makes a tab. 
Arrows just print "^[[A"

##### Steps to Reproduce
I am not really good in Linux - I thought it is a bash issue.  Also if I login I don't see the user in the shell just "$".

Tried to install:
sudo apt-get install bash-completion
But was already installed.
Tried to add to bash config:
`# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi`

**Comment by Shackelford-Arden** [comment]
@sirup This is specific to **Bash**, not Bookstack.

I'm not sure what your end goal is though in using the tab completion? Can you give an example? You mentioned that you want to use the arrow keys and such but... 

The script doesn't ask for anything aside from the domain name you want to have applied to the instance.

**Comment by ssddanbrown** [comment]
Hi @sirup, Since this is not a BookStack issue I will close this issue but I won't lock it so feel free to continue to comment.

There's some good advise above. Try following that; otherwise provide some more details such as how you're logging in to your Ubuntu machine.
