### ISSUE TITLE
exporting to HTML ends in error 504 gateway timeout

### ISSUE THREAD

**Issue by lynchpatrickj** [BookStackApp/BookStack#587]
### For Bug Reports

BookStack v0.18.2
PHP Version: 7.0.25.1 Ubuntu 16.04.1
MySQL Version: 14.14 distrib 5.7.20 for Linux x64

##### Expected Behavior

Exporting a book to HTML should result in an HTML file. Exporting to PDF should result in a PDF file.

##### Current Behavior

Receive an error after a few moments - 

504 Gateway Time-out

nginx/1.10.3 (Ubuntu)

Individual chapters export fine to HTML; PDF sometimes times out still. 

##### Steps to Reproduce

Export a book with more than a few chapters / images within... Not sure what the limit is.

**Comment by lommes** [comment]
Hi,

what is your value of `max_execution_time` in php.ini?

If you are running php-fpm there might be more settings relevant:

In www.conf the value of `request_terminate_timeout` should be equal to max_execution_time. In the host configuration of nginx you might need to set fastcgi_read_timeout for php-files.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please comment and this can be reopened if required.
