### ISSUE TITLE
System-wide preferred language?

### ISSUE THREAD

**Issue by Alwaysin** [BookStackApp/BookStack#594]
### For Feature Requests

Desired Feature: an option in the settings for the admin to define a system-wide language other than English

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.18.5
* PHP Version: 
* MySQL Version:

##### Expected Behavior

Changes the language to at least every new account, maybe also the old ones?

##### Current Behavior

Can't do it

##### Steps to Reproduce

N/A

**Comment by ssddanbrown** [comment]
Hi @Alwaysin,
 Adding a `APP_LANG` variable to the `.env` file should achieve this. 

Available options are : 'en', 'de', 'es', 'es_AR', 'fr', 'nl', 'pt_BR', 'sk', 'ja', 'pl', 'it' or 'ru'. (Quotes not needed in .env file)

**Comment by ssddanbrown** [comment]
Will close this now since the above should now solve it.

Let me know if that does not work and this can always be re-opened.
