### ISSUE TITLE
Documentation "error": UTF8mb4/emoji support

### ISSUE THREAD

**Issue by Blizzke** [BookStackApp/BookStack#595]
On [this page](https://www.bookstackapp.com/docs/admin/ut8mb4-support/) the procedure to recreate the database is described in case you get the "key to long"-error. 

As it is described there it will not work, given that you are also making a backup of the `migrations` table which will be filled again when you run `artisan migrate` and then the restore will fail.

I think it might be easier to just add a _drop the `migration`-table_  to the beginning of the document (before creating the dump), that should solve everything.

**Comment by Blizzke** [comment]
Okay: it's actually much worse: The problem also occurs for `permissions_role`, `role_permissions`, `role_user`, `roles` and `users` table. Basically as is, that guide is unusable without emptying up all those tables first after you ran the `migrate` command

**Comment by ssddanbrown** [comment]
Since this is an old issue I'll close this off.
