### ISSUE TITLE
Plugin for QR-Codes

### ISSUE THREAD

**Issue by trenkert** [BookStackApp/BookStack#597]
### For Feature Requests

Desired Feature:

It would be nice to have QR-Codes for wiki pages. Similar to tiddlywiki: https://twitter.com/tiddlywiki/status/788455488635695104

**Comment by aljawaid** [comment]
That would be interesting.  So the person could read the paper version of the book but scan the printed qr code from the page to go directly to the online updated version.

**Comment by yoginth** [comment]
+1

**Comment by ssddanbrown** [comment]
Since there's been relatively little demand for this feature since originally opened, I'm going to go ahead and close this off.

**Comment by King-GO** [comment]
This is the must-have feature when it comes to printed papers. Just like a physical book, the changes and updated content can be checked via QR code.

**Comment by lommes** [comment]
If it's ok to have an QR-Code at the bottom of every page, you could use something like:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js" integrity="sha512-CNgIRecGo7nphbeZ04Sc13ka07paqdeTu0WR1IM4kNcpmBAUSHSQX0FslNhTDadL4O5SAGapGt4FodqL8My0mA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
	window.addEventListener('load', function () {
		if(window.location.href.indexOf("/page/") > -1) {
			new QRCode(document.getElementsByClassName("page-content")[document.getElementsByClassName("page-content").length -1], window.location.href);
		}
	})	
</script>
```
as custom HTML Head Content in the settings

**Comment by bug2point0** [comment]
nice idea! if you want to limit the pages having a qr code you can leverage/abuse the tag system in bookstack by modifiying the condition:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js" integrity="sha512-CNgIRecGo7nphbeZ04Sc13ka07paqdeTu0WR1IM4kNcpmBAUSHSQX0FslNhTDadL4O5SAGapGt4FodqL8My0mA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
	window.addEventListener('load', function () {
		if(window.location.href.indexOf("/page/") > -1 && document.querySelector('div.tag-item[data-name="has qr code at bottom"]') !== null) {
			new QRCode(document.getElementsByClassName("page-content")[document.getElementsByClassName("page-content").length -1], window.location.href);
		}
	})	
</script>
```
this will only show the qr code in pages with the tag "_has qr code at bottom_"
but if you want to print a page with the qr code you obviously can't use the export. you'll have to print using the browser
