### ISSUE TITLE
LDAP Authentication Error

### ISSUE THREAD

**Issue by obeardly** [BookStackApp/BookStack#600]
### For Bug Reports

* BookStack Version: v0.18.5
* PHP Version: 5.6.30-0+deb8u1
* MySQL Version: 14.14 Distrib 5.5.58

I installed Bookstack on Devuan Linux 1.0.0 using a modified version of the install script.  The install was successful and fully functional.  I was able to add local users and modify content without issue.

##### Expected Behavior

Modify `/var/www/bookstack/.env` file to authenticate with LDAP (Samba) and log in with any of my Samba users. 

##### Current Behavior

 After modifying my `/var/www/bookstack/.env` file to authenticate with LDAP (Samba), when I login, I get the following: 

`ErrorException in Ldap.php line 57:
ldap_search(): Search: Operations error`

We are currently using this LDAP (Samba) server to login to multiple machines. I can verify that it functions properly. 

##### Steps to Reproduce

Modify .env file: 

`AUTH_METHOD=ldap`
`LDAP_SERVER=ldap://server.mydomain.com:389`  This is the localhost. 
`LDAP_BASE_DN=dc=mydomain,dc=com`
`LDAP_USER=admin`
`LDAP_PASS=passwd`
`LDAP_USER_FILTER=(&(SAMAccount==${user}))`
`LDAP_VERSION=false`

Restart nginx and attempt login. 

#### Attached Files

Attached are my sanitized files.  (env, nginx, log)

[bookstack_env.txt](https://github.com/BookStackApp/BookStack/files/1507221/bookstack_env.txt)
[bookstack_nginx.txt](https://github.com/BookStackApp/BookStack/files/1507222/bookstack_nginx.txt)
[laravel.log](https://github.com/BookStackApp/BookStack/files/1507243/laravel.log)
[bookstack_error.txt](https://github.com/BookStackApp/BookStack/files/1507404/bookstack_error.txt)

**Comment by AbijeetP** [comment]
@obeardly - Google'd that error and found a link here - https://stackoverflow.com/a/19258443/903324 that might have some answers to your questions.

**Comment by obeardly** [comment]
@AbijeetP I actually saw that as well.  My problem is that I don't know how best to implement that variable.  Should I set it globally? Or is it something I should set within my Bookstack configuration?

**Comment by ssddanbrown** [comment]
@obeardly Sorry for my late reply.

Could you check your variables against the docs here: https://www.bookstackapp.com/docs/admin/ldap-auth/

You've set a `LDAP_USER` variable but I think this instead should be `LDAP_DN` and the value should be the full user DN instead of just the username.

**Comment by obeardly** [comment]
I've beat my head against this for two weeks and I cannot get it working.  It should be easier than this.

**Comment by obeardly** [comment]
@ssddanbrown  I've been through this LDAP 100 times, literally, and tried every variation of LDAP authentication I can think of.  It does not want to work.  Maybe v 19.0.0 will be better.  I'm currently on 18.5.  Is there anyway to get Bookstack to use local authentication, authenticate against the host machine versus local Bookstack authentication?

**Comment by obeardly** [comment]
Chose to use Slack authentication instead.  Please refer to this [ticket. ](https://github.com/BookStackApp/BookStack/issues/471)
