### ISSUE TITLE
Multi Level Chapters

### ISSUE THREAD

**Issue by mdidon** [BookStackApp/BookStack#601]
Desired Feature:
Allow for multi level chapters to create a grouping system.
For use as a wiki it would be beneficial to be able to group and sub group for better navigation.
- Book
-- Chapter 1
--- Sub Chapter 1.1
---- Page 1.1.1
---- Page 1.1.2
--- Sub Chapter 1.2
---- Page 1.2.1
-- Chapter 2
--- Page 2.1

**Comment by Shackelford-Arden** [comment]
I believe there is already a request for this :) I'd recommend having this issue closed and simply voicing your support on the existing issue.

#95

**Comment by mdidon** [comment]
Cheers
