### ISSUE TITLE
[Request] Change default email to match demo website

### ISSUE THREAD

**Issue by RayBB** [BookStackApp/BookStack#602]
### For Feature Requests

Desired Feature:
Right now the demo email is admin@example.com and the default email when setting up is admin@admin.com.
It would be nice if they both had the same username/password for convenience when trying to just get your first instance up and running before configuration.

**Comment by ssddanbrown** [comment]
Thanks for opening this issue.

I agree this would be an improvement. I think I made up `admin@admin.com` during dev then used `admin@example.com` for the demo in case `admin.com` is a legit domain and any emails get sent out.

I do think though that if we change this we might as-well do things properly and put in a system to specify login details during setup or via a post-install command.

**Comment by ssddanbrown** [comment]
As per my comment above, I'm going to close this issue in favour of planning a more secure solution of customized login details upon install.
