### ISSUE TITLE
CTRL+Enter to Finish Editing a Page

### ISSUE THREAD

**Issue by lithium-ap** [BookStackApp/BookStack#604]
### For Feature Requests

Desired Feature: CTRL+Enter to end editing a section or page. Somewhat similar to the way you hit ctrl+enter to send a message in Outlook or Gmail

The application is super fluid and intuitive but I find myself instinctively hitting ctrl+enter to end editing of a section.

**Comment by ssddanbrown** [comment]
@lithium-ap Good suggestion, thanks. 

Has been implemented within 02fd1c4 ready for next release (v0.19.0).
