### ISSUE TITLE
Bug: WYSIWYG Editor Full Screen

### ISSUE THREAD

**Issue by jonathanadams** [BookStackApp/BookStack#605]
* BookStack Version: v0.18.5
* PHP Version: 7.0.22
* MySQL Version: 5.7.20

##### Expected Behavior
When clicking the full screen icon the WYSIWYG editor should open up full screen.

##### Current Behavior
![screenshot](https://user-images.githubusercontent.com/813248/33745466-eba0afb4-dbae-11e7-9a69-32540d259ddb.png)

Editor opens full screen but its obscured by ?sidebar and ?whitespace

##### Steps to Reproduce
Open up page and attempt to edit full screen.

**Comment by ssddanbrown** [comment]
For reference, Occurs on Firefox, Not on chrome.

**Comment by ssddanbrown** [comment]
@jonathanadams Thanks for reporting this issue, Fix is now readied for the next release.
