### ISSUE TITLE
Feature request : Custom login page

### ISSUE THREAD

**Issue by Dav31** [BookStackApp/BookStack#608]
### For Feature Requests

Desired Feature: Hello, I ask you if it would be possible to make the login page customisable on Bookstack settings without touching to the code. Nothing very big, but just allowing us to add a welcome sentence or login indication.

Thank you for your work ! This is very appreciable.

**Comment by ssddanbrown** [comment]
Hello again @Dav31,

Thanks for the suggestion. I've got some ideas for general customisation which I think this will come under. My idea will involve touching code but would be fairly safe & upgrade compatible.

How often would you imagine needing to change the text? Just once or every so often?

**Comment by Dav31** [comment]
Thank you for your quick answer !

Well, ideally, this modification would only be done once. I could do it on the code but I'm afraid that it won't last any update. Am I wrong ?

**Comment by ssddanbrown** [comment]
@Dav31 No, you're not wrong. Currently you'd have to apply the change after each update or use git tactically to merge in you're change each time.

**Comment by ssddanbrown** [comment]
Assigning to the next release with the intent of adding a specific new partial template to have a specific view to override via the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md).

**Comment by ssddanbrown** [comment]
I have now merged #3848 for next release, which would allow setting custom content between the inputs and title of the login view, by [overriding this view](https://github.com/BookStackApp/BookStack/blob/development/resources/views/auth/parts/login-message.blade.php) via the visual theme system.  Will therefore close this off.
