### ISSUE TITLE
Request: Books page as application home page

### ISSUE THREAD

**Issue by jonathanadams** [BookStackApp/BookStack#615]
### For Feature Requests

Desired Feature: Allow the application homepage to be set to /books?

**Comment by Abijeet** [comment]
@jonathanadams - I'm don't know if this will be implemented but depending on which server you are using (nginx, Apache or IIS) you could set this up via a redirection.

Though this would mean that you will not be able to access the current homepage.

**Comment by aljawaid** [comment]
It would be better if a single book can be assigned as the application homepage (before/after loggin in).  It would also be beneficial, if we could assign one or more books so that the user can land on them books or direct onto the assigned book (if just one) when he/she logs in.

Example (purely ideas):
User X is temporary staff and only has access to procedures manual (one book).  User logs in and is only directed to homepage of that manual.
User Y is temporary senior staff and has 4 books assigned to him. User logs in and is shown a list of books assigned to his login.
User Z is admin/default.  Current system of v0.19 default settings apply to this user.

**Comment by olenoerby** [comment]
Thumbs up for user specifik settings and ability to set a global configuration dictating settings for all users by the admin.

**Comment by sorvani** [comment]
v0.20 has the ability to select a page as the default homepage, and that is cool, but setting /books to default would be better for our use case.

**Comment by sorvani** [comment]
@Abijeet the current home page is only useful if you want to go to something you have recently done or that someone else has recently done.

But often I will be going to a specific book to get to a specific page. It may well not be in the recent lists once my wiki is fully populated.
![image](https://user-images.githubusercontent.com/3302372/36449851-b685183c-1651-11e8-9b68-435e6ef5c667.png)

**Comment by olenoerby** [comment]
I use BookStack as a private documentation wiki and have a lot of users set up with different access controls to different books, so not all users have access to all books, representing different locations. 

However, when people log in, they're presented with a rather unscenic and confusing frontpage with changes and new pages - where it would be easier if they had direct access to the list of books / households they have read access to.

This is why I request the feature to set /books as homepage upon login.

**Comment by pierre-le** [comment]
A quick and dirty workaround could be to add a rule in Nginx (or whichever web server you're using) to redirect requests from the "Dashboard" to `/books`.
Using Nginx:
`    location = / {
        rewrite ^/$ https://docs.fioulreduc.com/books redirect;
    }`

**Comment by sorvani** [comment]
That breaks things unless you add a locaiton path for every other path such as /logon /css /libs, etc.

**Comment by pierre-le** [comment]
@sorvani No, as this rule is an exact match on the home page, which is an HTML page. You just need to place that rule on top of any other location rule.

And... I can certify that this workaround works fine bc we're using it in production right now :)

**Comment by Abijeet** [comment]
@ssddanbrown, I'd like to take a crack at this.

I've been trying to figure out how to fit this into the current UI and for now this is what I've come up with,

![screenshot-2018-4-16 settings bookstack](https://user-images.githubusercontent.com/1685517/38782036-50ffb12c-410b-11e8-8806-1d77fa8c26b3.png)

I've tried to merge it with the existing **Application Homepage** setting but I think its still confusing.

The other option would be to somehow merge it into the current page selector that we have. Maybe at the bottom of the popup.

![screenshot-2018-4-16 settings bookstack 1](https://user-images.githubusercontent.com/1685517/38782054-964a9616-410b-11e8-9263-079729953f65.png)

Note that the popup has a couple of minor quirks that I'll fix along with this merge request.

**Comment by ssddanbrown** [comment]
Thanks @Abijeet for having a go at this and sorry for my late reply.

I think merging it in with the entity selector will be more trouble so an extra setting, as your first screenshot, is the best option for now. 

I've been thinking about cleaning up the setting UI design recently so when I do that I may alter the implementation to be clearer but as the screenshot is perfectly fine for now.

I would say a new custom template may work better, With the same sidebar content as the existing custom homepage layout but with the 'all books' page main content.

**Comment by technowhizz** [comment]
@Abijeet You are a legend. I was about to use the nginx hack then saw the PR. Thank you!
