### ISSUE TITLE
SQlite: migration failing

### ISSUE THREAD

**Issue by bridgeyuwa** [BookStackApp/BookStack#617]
### SQlite: migration failing 

* BookStack Version *: 0.11
* PHP Version: 7.0
*Sqlite

Trying to install bookstack on an Sqlite database
##### Throwing This Exception

[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default  
   value NULL (SQL: alter table "pages" add column "created_by" integer not n  
  ull)                                                                         
[PDOException]                                                               
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default  
   value NULL                     

![screen shot 2017-12-15 at 6 20 05 pm](https://user-images.githubusercontent.com/17090054/34038175-64fa24e0-e1c6-11e7-956e-4a07bcd645e4.png)

##### Steps to Reproduce
Just run "php artisan migrate"

**Comment by AbijeetP** [comment]
BookStack does not support SQLite, only MySQL and by extension, MariaDB is supported.

**Comment by bridgeyuwa** [comment]
Bookstack is built on laravel... it sure can support SQlite. Just Altering the migrations should do that

**Comment by ssddanbrown** [comment]
@bridgeyuwa Thanks for creating this issue.

@AbijeetP is correct. While Laravel does support SQLite, BookStack does currently not.

An issue to add support is already open under #367 so I will close this. I would like to support SQLite at some stage to make setup for smaller instances even easier/more manageable but we do have to take into account the extra amount of testing and maintenance required going forward to add SQLite support.
