### ISSUE TITLE
Feature request: 'edit' link present at each header

### ISSUE THREAD

**Issue by lynchpatrickj** [BookStackApp/BookStack#618]
Desired Feature:

For long articles with lots of headers, it's cumbersome when proofreading to have to scroll all the way to the top to hit the Edit button - and then all the way back down - to fix an error. It would be nice if each header / anchor could have an 'edit' option which would allow you to edit the displayed text on the screen.

**Comment by thomasjsn** [comment]
Looks like PR #875 implemented this. No?

**Comment by ssddanbrown** [comment]
Ah, A bit late to this but yes @thomasjsn, Thanks for spotting.

Just for anyone looking for this feature, You can select some text in a block then click the edit icon in the little popover box:

![image](https://user-images.githubusercontent.com/8343178/51079728-69722480-16c4-11e9-9700-2860bd67f807.png)

This can be done on any text section, not just headers.
