### ISSUE TITLE
Feature Requests: Change Preferred layout for books viewing action button

### ISSUE THREAD

**Issue by yamss** [BookStackApp/BookStack#624]
Desired Feature: Let us change the "Preferred layout for books viewing" from grid or list using a button like the "Toogle Details" button.

And thank you so much for this awesome app!

**Comment by ssddanbrown** [comment]
Hi @yamss, Thanks for the suggestion.

This request is effectively already open under #613 so I will go ahead and close this. If I've misunderstood please feel free to continue commenting here and I'll re-open this.
