### ISSUE TITLE
Bug when exporting page with Polish characters to PDF

### ISSUE THREAD

**Issue by fmakowski** [BookStackApp/BookStack#625]
* BookStack Version: v0.18.5
* PHP Version: php:7.1.10-apache (I guess? I am using [solidnerd/docker-bookstack](https://github.com/solidnerd/docker-bookstack))
* MySQL Version: 5.7.20

##### Expected Behavior

When I export a file to PDF, the UTF-8 coding is preserved and I can see Polish chatacters.

Just like on the site:

![1-original-on-site](https://user-images.githubusercontent.com/2910034/34225064-5f918f86-e5c5-11e7-945c-767d8dd75241.png)

##### Current Behavior

When I export a file to PDF, and it consists of language-specific characters (śćńąę etc.), there will be `?` instead:

![2-export-to-pdf](https://user-images.githubusercontent.com/2910034/34225100-7d7184ca-e5c5-11e7-8cd9-aa7a90cd8398.png)

The issue is not present when exporting to HTML or to text file:

![4-export-to-html](https://user-images.githubusercontent.com/2910034/34225102-82ea6430-e5c5-11e7-8c95-9860da093d0f.png)
![3-export-to-txt](https://user-images.githubusercontent.com/2910034/34225107-85bf18fe-e5c5-11e7-87c7-8e77f9dd6cb2.png)

##### Steps to Reproduce

1. Create a page with the following title and contents:

    Just tęśtińg Półish chąraćters
    Iń thę ćóntęnt ąś węłł. 

2. Export to PDF.

##### Additional comments

I have checked other PDF viewers - they are not the reason it looks that way. 

Also, interestingly, "ó" is parsed properly (but maybe it's included in a character set that is somehow more compatible with the standard one).

I would also rule out the font, as each document is using the same one.

**Comment by fmakowski** [comment]
I see that this is a similar bug to the one in #148. For that reason, I am closing the issue, but referecing it in the other one.

**Comment by alexwoo-awso** [comment]
PDF export title glyphs break because headings use the heading font var and DOMPDF falls back to base fonts without Polish glyphs. I added a PDF-only heading font override to DejaVu Sans in export-styles.scss; verified Polish title characters render correctly. I have opened a PR with the fix -> https://github.com/BookStackApp/BookStack/pull/6069
