### ISSUE TITLE
Upgrade script results in 'something went wrong' 

### ISSUE THREAD

**Issue by lynchpatrickj** [BookStackApp/BookStack#627]
BookStack v0.18.2

PHP:
PHP 7.0.25-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 27 2017 13:43:45) ( NTS )
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

MySQL:
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper

Ubuntu:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

##### Expected Behavior

running the upgrade script to 0.19 should just work.

##### Current Behavior

Instead of the typical Bookstack site, the browser displays the 'something went wrong' page.

##### Steps to Reproduce

Following these instructions here: https://www.bookstackapp.com/docs/admin/updates/

**Comment by jonathanadams** [comment]
I had a similar problem and then realised that the update script needs to be ran as sudo.

Try this?

**Comment by lynchpatrickj** [comment]
I ran it as Sudo.



Patrick Lynch

c: (919) 327 7151 | v: (719) 422 3523 | g: lynchpatrickj

**Comment by ssddanbrown** [comment]
Hi @lynchpatrickj,
Sorry to hear you're having issues.

Did you see any error text or warnings during when running then update commands?

To get more information about why your instance is not running correctly you can view more debug information by [following these instructions](https://www.bookstackapp.com/docs/admin/debugging/).

**Comment by lynchpatrickj** [comment]
Thanks for the response!

I'm pretty unfamiliar with Linux, and I don't see any files named .env in
my bookstack directory:

[image: Inline image 3]

I don't really know how to search from the command line yet, so could you
help point me to it?

Here are the errors I get running the command::

[image: Inline image 1]

[image: Inline image 2]


*Here's the full output:*

plynch@ubuntu:/var/www/bookstack$ sudo git pull origin release &&
composer install && php artisan migrate
[sudo] password for plynch:
remote: Counting objects: 1141, done.
remote: Total 1141 (delta 746), reused 746 (delta 746), pack-reused 395
Receiving objects: 100% (1141/1141), 486.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (856/856), completed with 241 local objects.
From https://github.com/ssddanbrown/BookStack
 * branch            release    -> FETCH_HEAD
   e90da18..22df25a  release    -> origin/release
Updating e90da18..22df25a
Fast-forward
 .env.example                                                      |    3 +
 .gitignore                                                        |    7 +-
 .travis.yml                                                       |    4 +-
 app/Book.php                                                      |   29 +-
 app/Console/Kernel.php                                            |   17 +-
 app/Exceptions/Handler.php                                        |   14 +-
 app/Http/Controllers/Auth/LoginController.php                     |   15 +-
 app/Http/Controllers/Auth/RegisterController.php                  |   18 +-
 app/Http/Controllers/BookController.php                           |   14 +-
 app/Http/Controllers/HomeController.php                           |   10 +
 app/Http/Controllers/ImageController.php                          |    4 +-
 app/Http/Controllers/PageController.php                           |   17 +-
 app/Http/Controllers/SearchController.php                         |    6 +-
 app/Http/Controllers/TagController.php                            |    6 +-
 app/Http/Controllers/UserController.php                           |   16 +-
 app/Http/Kernel.php                                               |    4 +-
 app/Http/Middleware/Authenticate.php                              |    7 +-
 app/Http/Middleware/EncryptCookies.php                            |    4 +-
 app/Http/Middleware/TrimStrings.php                               |    4 +-
 app/Http/Middleware/TrustProxies.php                              |   47 ++
 app/Http/Middleware/VerifyCsrfToken.php                           |    4 +-
 app/Providers/EventServiceProvider.php                            |    1 +
 app/Repos/EntityRepo.php                                          |   19 +-
 app/Services/ExportService.php                                    |   23 +-
 app/Services/PermissionService.php                                |    7 +-
 app/Services/SearchService.php                                    |    2 +-
 app/Services/SocialAuthService.php                                |    7 +-
 artisan                                                           |   16 +-
 bootstrap/{autoload.php => init.php}                              |   28 +-
 composer.json                                                     |   43 +-
 composer.lock                                                     |
2649 ++++++++++++++++++++++++++++++++++++----------------------
 config/app.php                                                    |    4 +-
 config/services.php                                               |    8 +
 config/session.php                                                |    2 +-
 database/migrations/2017_08_29_102650_add_cover_image_display.php |   32 +
 database/seeds/DummyContentSeeder.php                             |   30 +-
 package-lock.json                                                 |
5977 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 phpunit.xml                                                       |    2 +-
 public/book_default_cover.png                                     |
Bin 0 -> 5672 bytes
 public/css/export-styles.css                                      |    4 +-
 public/css/styles.css                                             |    4 +-
 public/index.php                                                  |   16 +-
 public/js/common.js                                               |   55 +-
 readme.md                                                         |   13 +-
 resources/assets/icons/okta.svg                                   |    1 +
 resources/assets/js/components/collapsible.js                     |   37 +
 resources/assets/js/components/image-picker.js                    |   59 ++
 resources/assets/js/components/index.js                           |    2 +
 resources/assets/js/components/markdown-editor.js                 |    2 +
 resources/assets/js/pages/page-form.js                            |   19 +
 resources/assets/js/pages/page-show.js                            |   62 +-
 resources/assets/js/vues/components/autosuggest.js                |    4 +-
 resources/assets/js/vues/page-editor.js                           |    6 +-
 resources/assets/js/vues/tag-manager.js                           |    4 +-
 resources/assets/sass/_forms.scss                                 |   42 +-
 resources/assets/sass/_grid.scss                                  |   11 +-
 resources/assets/sass/_lists.scss                                 |   51 ++
 resources/assets/sass/_tinymce.scss                               |    9 +-
 resources/assets/sass/styles.scss                                 |    5 +-
 resources/lang/check.php                                          |  114 +++
 resources/lang/de/common.php                                      |    4 +-
 resources/lang/de/settings.php                                    |    3 +
 resources/lang/en/common.php                                      |    5 +-
 resources/lang/en/errors.php                                      |    2 +
 resources/lang/en/settings.php                                    |    3 +
 resources/lang/es/common.php                                      |    4 +-
 resources/lang/es/settings.php                                    |    3 +
 resources/lang/fr/common.php                                      |    4 +-
 resources/lang/fr/settings.php                                    |    4 +-
 resources/lang/it/settings.php                                    |    3 +-
 resources/lang/ja/common.php                                      |    2 +-
 resources/lang/ja/settings.php                                    |    4 +-
 resources/lang/nl/common.php                                      |    4 +-
 resources/lang/nl/settings.php                                    |    3 +
 resources/lang/pl/common.php                                      |    4 +-
 resources/lang/pl/settings.php                                    |    2 +
 resources/lang/pt_BR/activities.php                               |    4 +-
 resources/lang/pt_BR/auth.php                                     |    2 +
 resources/lang/pt_BR/common.php                                   |    9 +-
 resources/lang/pt_BR/components.php                               |   10 +-
 resources/lang/pt_BR/entities.php                                 |   51 +-
 resources/lang/pt_BR/errors.php                                   |   15 +-
 resources/lang/pt_BR/settings.php                                 |   11 +-
 resources/lang/ru/settings.php                                    |    2 +
 resources/lang/sk/common.php                                      |    4 +-
 resources/lang/sk/settings.php                                    |    3 +
 resources/views/books/create.blade.php                            |    5 +-
 resources/views/books/edit.blade.php                              |    2 +-
 resources/views/books/form.blade.php                              |   20 +
 resources/views/books/grid-item.blade.php                         |   18 +
 resources/views/books/index.blade.php                             |   29 +-
 resources/views/books/show.blade.php                              |    2 +-
 resources/views/chapters/show.blade.php                           |   28 +-
 resources/views/components/image-picker.blade.php                 |   53 +-
 resources/views/pages/form-toolbox.blade.php                      |    6 +-
 resources/views/pages/form.blade.php                              |    9 +-
 resources/views/pages/show.blade.php                              |   11 +-
 resources/views/partials/activity-item.blade.php                  |    2 +-
 resources/views/partials/book-tree.blade.php                      |    2 +-
 resources/views/partials/custom-head-content.blade.php            |    5 +
 resources/views/partials/custom-styles.blade.php                  |    1 +
 resources/views/settings/index.blade.php                          |    5 +
 resources/views/users/edit.blade.php                              |    9 +-
 routes/web.php                                                    |    1 +
 tests/Auth/AuthTest.php                                           |   39 +
 tests/BrowserKitTest.php                                          |   19 +-
 tests/Entity/CommentSettingTest.php                               |   28 +
 tests/Entity/EntitySearchTest.php                                 |    4 +-
 tests/Entity/EntityTest.php                                       |   22 +-
 tests/HomepageTest.php                                            |   25 +-
 tests/LanguageTest.php                                            |    2 +-
 tests/Permissions/RestrictionsTest.php                            |   66 +-
 tests/UserProfileTest.php                                         |   28 +-
 version                                                           |    2 +-
 114 files changed, 8864 insertions(+), 1364 deletions(-)
 create mode 100644 app/Http/Middleware/TrustProxies.php
 rename bootstrap/{autoload.php => init.php} (60%)
 create mode 100644
database/migrations/2017_08_29_102650_add_cover_image_display.php
 create mode 100644 package-lock.json
 create mode 100644 public/book_default_cover.png
 create mode 100644 resources/assets/icons/okta.svg
 create mode 100644 resources/assets/js/components/collapsible.js
 create mode 100644 resources/assets/js/components/image-picker.js
 create mode 100755 resources/lang/check.php
 create mode 100644 resources/views/books/grid-item.blade.php
 create mode 100644 resources/views/partials/custom-head-content.blade.php
 create mode 100644 tests/Entity/CommentSettingTest.php
Cannot create cache directory
/home/plynch/.composer/cache/repo/https---packagist.org/, or directory
is not writable. Proceeding without cache
Cannot create cache directory /home/plynch/.composer/cache/files/, or
directory is not writable. Proceeding without cache
> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Removing symfony/yaml (v3.2.4)


  [RuntimeException]
  Could not delete /var/www/bookstack/vendor/symfony/yaml/Unescaper.php:


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev]
[--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader]
[--no-scripts] [--no-progress] [-v|vv|vvv|--verbose]
[-o|--optimize-autoloader] [-a|--classmap-authoritative]
[--ignore-platform-reqs] [--] [<packages>]...



*Laravel.log file contents:*

#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148):
Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request),
Object(Closure))
#37 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148):
Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request),
Object(Closure))
#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148):
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request),
Object(Closure))
#43 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148):
Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request),
Object(Closure))
#46 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520):
Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route),
Object(Illuminate\Http\Request))
#50 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498):
Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#51 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174):
Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#52 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30):
Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148):
Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request),
Object(Closure))
#55 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148):
Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request),
Object(Closure))
#58 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148):
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request),
Object(Closure))
#61 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116):
Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /var/www/bookstack/public/index.php(53):
Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity
constraint violation: 1048 Column 'name' cannot be null (SQL: insert
into `page_revisions` (`page_id`, `slug`, `book_slug`, `created_by`,
`type`, `name`, `html`, `markdown`, `updated_at`, `created_at`) values
(3, 14a01---all, accounts, 3, update_draft, , , , 2017-10-05 01:35:05,
2017-10-05 01:35:05)) in
/var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647




Patrick Lynch

c: (919) 327 7151 | v: (719) 422 3523 | g: lynchpatrickj

**Comment by ssddanbrown** [comment]
In the above it looks like the `composer install` step does not complete properly due to a permissions issue thus the `migrate` command never runs.

I'd try removing the whole `/vendor` file, Reinstall dependencies, Migrate then see if things work:

Commands should be ran from BookStack install folder, Run at your own risk.
```sh
# Delete old dependencies
sudo rm -rf ./vendor

# Re-install dependencies
composer install

# Migrate database
php artisan migrate
```

You probably can't see a `.env` file as files starting with a `.` in unix-like systems are hidden files/folders. From the command line, Running the command `ls -al` from the BookStack install folder should show it.

**Comment by jonathanadams** [comment]
Try running the command as: 

`sudo git pull origin release &&
sudocomposer install && sudo php artisan migrate`

**Comment by ssddanbrown** [comment]
Thank you for opening this issue. As part of an issue clean-up we're closing off older support issues that may be outdated or irrelevant so therefore I am closing this issue.

If the issue remains and it is one you are still seeking to actively solve please ensure it is still not apparent on the latest version of BookStack then open up a new issue referencing this one.

Sorry if we were not able to solve your original request.
