### ISSUE TITLE
[Feature Request] Show all Books as Default Homepage

### ISSUE THREAD

**Issue by olenoerby** [BookStackApp/BookStack#628]
Desired Feature:

Whenever logging in, many users with access to different books are sometimes overwhelmed when presented with the default Home Page and all changes, but rather than showing a single book and they have to choose the Books menu by clicking, an option to set the Books (/books)-menu or submenu as default would be preferred.

TLDR: Allow user or admin to set Books menu as Default homepage.

**Comment by ssddanbrown** [comment]
Hi @olenoerby,
Thanks for this suggestion. I believe this has already been requested under issue #615 therefore I will close this one. Please give that issue a thumbs-up to show support. 

If i have misunderstood feel free to still comment here and this can always be re-opened.
