### ISSUE TITLE
After Deleting the User, user's profile picture is not deleted in the server!

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#630]
### For Feature Requests

Desired Feature: none

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 19
* PHP Version: 7.2
* MySQL Version: 5.7

##### Expected Behavior

Profile Picture needs to be deleted if the user is deleted.

##### Current Behavior

After Deleting the User, user's profile picture is not deleted on the server!

**Comment by sampathg9** [comment]
Hi @ssddanbrown 
I'll work on this bug. 
I'll do the following to fix this bug

After successful deletion of a User account
- Delete profile pics from uploads folder
- Delete user profile pic record from images table

Please let me know If you want to perform any other thing in this action.

**Comment by yoginth** [comment]
**_Thanks a Lot!_**

**Comment by sampathg9** [comment]
@ssddanbrown - Submitted a merge request - https://github.com/BookStackApp/BookStack/pull/646/files

Please review it.

**Comment by ssddanbrown** [comment]
Now closed as part of #646, 35e00ddb95733221a8868d81dec65e4d329eb1c3 and ead4b14d94d6daecdc7869c9c0f4ce597ef8f58c
