### ISSUE TITLE
Imgur API

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#631]
### For Feature Requests

Desired Feature: Image upload to Imgur

Currently, we are uploading images to our own server rather than that we can use **Imgur API** to Upload images like **Stackoverflow** uses.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion.

Generally I believe this kind of usage will be against imgur's terms of service. Looks like stackexchange have a special contract with Imgur for their use. I wouldn't want to support use against imgur's terms.

**Comment by yoginth** [comment]
It's not Against Imgur, The API is open for all! https://api.imgur.com/#limits The terms says that we should not hotlink existing image in imgur!

**Comment by ssddanbrown** [comment]
The API is free for non-commercial use. This then becomes hazy for an application like BookStack where it's likely to be used in commercial settings.

Upon that I'm pretty sure the use of Imgur, even via the API, is still [bound to the terms](https://imgur.com/tos). This basically states not to use them as a CDN which this use would likely constitute as.

**Comment by yoginth** [comment]
fine got it thanks!
