### ISSUE TITLE
Showing Login in 404 Page

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#634]
### For Feature Requests

Desired Feature: none

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 19
* PHP Version: 7.1
* MySQL Version: 5.7

##### Expected Behavior

in 404 Page, in the navbar, the login button will not be displayed

##### Current Behavior

but for me, the login button is displaying in navbar even if I logged in!

##### Steps to Reproduce

![screenshot from 2017-12-25 09-52-59](https://user-images.githubusercontent.com/10177861/34332661-6afbf2c0-e959-11e7-8b9c-944ff3be713d.png)
![screenshot from 2017-12-25 09-52-48](https://user-images.githubusercontent.com/10177861/34332662-6b90c184-e959-11e7-9a6b-a287fc71b955.png)

Token is empty!
`<meta name="token" content="">`

**Comment by Abijeet** [comment]
@ssddanbrown - Can confirm this, but not sure how to fix it.

- https://github.com/laravel/framework/issues/17187
- https://github.com/laravel/framework/issues/20508

There are a few solutions proposed here - 

1. https://github.com/laravel/framework/issues/17187#issuecomment-271147355 - Possible to do this, but seems like a bit of work.
2. https://github.com/laravel/framework/issues/20508#issuecomment-321860989 - Doesn't look like a good solution. Will cause problems with the API.

**Comment by yoginth** [comment]
it looks messy!

**Comment by yoginth** [comment]
I think there is an error in php version! I'm running it on Apache Server with php7.1! Also the fresh install of bookstack returning this error!

**Comment by yoginth** [comment]
Still can't fix it!

**Comment by ssddanbrown** [comment]
@yoginth Thanks for reporting this bug.

@Abijeet Thanks for providing the links above. I went with a different option by creating a new middleware group for error pages then manually loading that middleware before 404 errors are rendered. I dug into the Laravel source to load the required middleware in a similar manner to standard controller routing. Details can be seen here: afe781bc398b319b965a29ccc45ca4b6aa879d0f

**Comment by yoginth** [comment]
Thanks Fixed!
