### ISSUE TITLE
Future Request: Able to bookmark and like a Page/Book/Chapter 

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#636]
### For Feature Requests

Desired Feature: Able to bookmark and like a Page/Book/Chapter

If we can able to bookmark the page or book or chapter we can view the book at any time instead of searching again and again! Currently, i implemented with pocket!

![screenshot from 2017-12-27 10-55-04](https://user-images.githubusercontent.com/10177861/34371581-73e90c96-eaf4-11e7-9eb8-0910b761d264.png)

**Comment by ssddanbrown** [comment]
Thanks for opening this issue, This is essentially being discussed under #505 therefore I will close this to avoid duplication.

If I have misunderstood feel free to continue commenting and this can be re-opened.

**Comment by yoginth** [comment]
But no one try to implement it!

**Comment by ssddanbrown** [comment]
Well not yet but this is a feature that I'd like so I'll likely work on it at some point. I don't see that feature being too urgent since much of the advantages of such a feature can already be harnessed via native browser bookmarks or via browser plugins such as pocket.

**Comment by yoginth** [comment]
this can be useful that how many people liked the document like twitter and facebook do in their docs!
