### ISSUE TITLE
Future Request: Toggle Between Markdown Editor and WYSIWYG Editor

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#637]
### For Feature Requests

Desired Feature: Toggle Between Markdown Editor and WYSIWYG Editor

Allow the user to toggle between markdown editor and WYSIWYG editor, which be more comfortable to users what they like!

**Comment by Abijeet** [comment]
@yoginth - There are already quite a few issues related to this,

- https://github.com/BookStackApp/BookStack/issues/458
- https://github.com/BookStackApp/BookStack/issues/369
- https://github.com/BookStackApp/BookStack/issues/315
- https://github.com/BookStackApp/BookStack/issues/119 - Pretty much similar.

**Comment by yoginth** [comment]
Awesome
