### ISSUE TITLE
Powerful custom page search/filter/ordering interface

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#64]
Since BookStack will be used for many different purposes I think the ways in which people want to find relevant pages will be different. I think it would be worthwhile building in a system to allow front-end users to search and filter pages in as many ways as possible.

I'm thinking of doing this by building a simple custom query syntax. An interface could be built which simply builds up this syntax and displays all the possible options for filtering and ordering.

**Comment by ssddanbrown** [comment]
Partially implemented with introduction of tag search interface (`[tag=value]` syntax). Still need to open up the other page database fields.

**Comment by davidPilkington** [comment]
Allowing users to set multiple values for tags would be great too, for instance [tag=val1;val2;val3]

This would allow multiple values to be set in the tag rathern than adding the same tag over again with a new value.
