### ISSUE TITLE
[BUG REPORT] Reusing Page Content

### ISSUE THREAD

**Issue by levest28** [BookStackApp/BookStack#640]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: BookStack v0.18.5
* PHP Version: 7.0.22-0ubuntu0.16.04.1
* MySQL Version: mysql  5.7.20, for Linux (x86_64)

##### Setup details:
Page A with ID 117 and an html table with ID of "bkmrk-servers1"
Page B with ID 59 and trying to reuse the content from 117.
The code to do this should be: {{@117#bkmrk-servers1}}

##### Expected Behavior
BookStack displays the specified table from Page A in Page B

##### Current Behavior
BookStack displays the contents of the specified table from Page A, in Page B, without any formatting.

##### Steps to Reproduce
Attempt to reference an html table from another page.

**Comment by ssddanbrown** [comment]
@levest28 Thanks for reporting this issue. Bug confirmed and marked to be fixed for next feature release.

If you need a workaround for the meantime you can wrap the table in a `<div>` and move the `id` from the table to the new parent div.

**Comment by levest28** [comment]
Thank you, this work around is resolving our issue for the time being. Looking forward to the next update!
