### ISSUE TITLE
Clicking on Books Does not Display Chapters, Only Whitespace

### ISSUE THREAD

**Issue by lithium-ap** [BookStackApp/BookStack#641]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: v0.18.5
* PHP Version: 5.6.xxxx
* MySQL Version: 5.6

##### Expected Behavior
Page loads content

##### Current Behavior

Page does not load content, I'm able to login to the application, am provided the recent docs, able to navigate books, but any further and I'm greeted with a blank page where content should be. I can still access the rest of the web app without issue, only am unable to view chapters. 

Here is a screencap of a Book that has several chapters and pages after clicked on: 

![image](https://user-images.githubusercontent.com/4935041/34399207-d5999f72-eb4a-11e7-911a-9a780f1de7ee.png)

##### Steps to Reproduce
Logged in, click books, select book, no pages. 

Additionally... I enabled some security functions on the vhost, rolled them back, didnt make a difference.

**Comment by AbijeetP** [comment]
Hey @lithium-ap,

Sorry to hear that you're having problems. Could you please follow the steps here - https://www.bookstackapp.com/docs/admin/debugging/ and give me the laravel.log file?

**Comment by AbijeetP** [comment]
Oh I see now, you should be using PHP 7.x. That probably is the issue.

Requirements available here - https://www.bookstackapp.com/docs/admin/installation/

**Comment by ssddanbrown** [comment]
@lithium-ap Is this on a new instance or after an update?

Previous to BookStack v0.19 the min required version of php was `5.6.4`. Double check your exact php version to double check if this could be the issue.

For v0.19+ php `7.0.0` is the minimum so might be worth updating both PHP and BookStack if possible.

**Comment by lithium-ap** [comment]
Hi Dan, 

I am using PHP Version 5.6.31-4 on this server, but did have it working prior to testing a php7.1 update. Anyhow, I moved it to a new web server with php7.1 and it's working fine.
