### ISSUE TITLE
Paste Images directly into the page from firefox not working

### ISSUE THREAD

**Issue by Di2g10** [BookStackApp/BookStack#65]
I would like the option to paste directly into a edit page rather that upload image. This is specifically useful where inputting screenshots.

**Comment by ssddanbrown** [comment]
Hi, Thanks for the bug submit. This seems to be firefox specific as this works from chrome, I've updated the title to be more descriptive of the issue.

**Comment by ssddanbrown** [comment]
Thought this would be a quick fix but firefox does not seem to support the latest clipboard API's. Will have to look into the potential workarounds. Links for reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=906420
https://bugzilla.mozilla.org/show_bug.cgi?id=891247

Potential workaround:
https://stackoverflow.com/questions/21377838/how-does-image-pasting-in-imgur-work-in-firefox

**Comment by ssddanbrown** [comment]
As of FireFox 50 (Due to release in a few days) this will be fixed. Now no point in finding a work-around.
