### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Vicfigue99** [BookStackApp/BookStack#653]
### For Bug Reports

* BookStack Version : GitHub v0.19.0 release
* PHP Version: 7.0.23
* MySQL Version: 5.7.19

##### Expected Behavior
Page load with no errors to load resources:
http://localhost/bookstack/public/css/styles.css?version=v0.19.0
http://localhost/bookstack/public/libs/jquery/jquery.min.js?version=2.1.4
...

##### Current Behavior
Resourses css, js, libs, etc not found | Path is incorrect in all pages. Add /index.php/ in all paths
http://localhost/bookstack/public/index.php/css/styles.css?version=v0.19.0
http://localhost/bookstack/public/index.php/libs/jquery/jquery.min.js?version=2.1.4
...
![login page - resoures not found](https://user-images.githubusercontent.com/35129573/34622636-75447366-f213-11e7-984d-9ef4d7e4d439.png)
![index page - resoures not found](https://user-images.githubusercontent.com/35129573/34622635-7526357c-f213-11e7-82a3-571e38421590.png)
![wamp server](https://user-images.githubusercontent.com/35129573/34622637-7559cfae-f213-11e7-8867-67143d58c90b.png)

##### Steps to Reproduce
Manual Installation Windows 10
https://www.bookstackapp.com/docs/admin/installation/

**Comment by ssddanbrown** [comment]
You could maybe try setting `APP_URL=http://localhost/bookstack/public/css/` in your `.env` file and access the site at `http://localhost/bookstack/public/` but I'd imagine you're still going to experience some issues.

Really BookStack is designed to be set up on its own host. Although setting up on a sub-path of a domain is supported this should really be done via a proxy or similar with security in mind. 
A BookStack install should not be placed within another virtual host/website as this can expose many other files which should not be accessed publicly.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
