### ISSUE TITLE
Markdown editor preview pane weird behavior

### ISSUE THREAD

**Issue by domainzero** [BookStackApp/BookStack#658]
### Bug Report

* BookStack Version*: v.0.19.0
* PHP Version: PHP 7.1.12
* MySQL Version: 10.2.11-MariaDB

##### Expected Behavior
Markdown editor preview pane should take up entire allotted space.

##### Current Behavior
Markdown editor preview pane only takes up 50% of space until enough text has been entered.
![image1](https://i.imgur.com/lspjaae.png)
![image2](https://i.imgur.com/3zNUKbC.png)

I tried to dig through the CSS to see what was going on but couldn't pinpoint the problem. This issue occurs in Firefox and Chrome.

I'm not using any custom CSS besides changing the codemirror theme.

##### Steps to Reproduce
Create a new document using the Markdown editor.

**Comment by ssddanbrown** [comment]
@domainzero Thanks for reporting. Confirmed and set for next release.
