### ISSUE TITLE
Slack Requires Authorization At Every Login. 

### ISSUE THREAD

**Issue by obeardly** [BookStackApp/BookStack#659]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.18.5
* PHP Version:  PHP 5.6.30-0+deb8u1
* MySQL Version:  5.5.58

##### Expected Behavior

When logging in with Slack, I expect Bookstack to ask for authorization once, and then retain the ability to login without reauthorizing. 

##### Current Behavior

When logging in with Slack, it asks me to authorize the app every time. 

##### Steps to Reproduce

With the aforementioned versions of BookStack, PHP, and MySQL, enable Slack login and attempt to login more than once. Requires you to reauthorize at every login.

**Comment by ssddanbrown** [comment]
Can confirm this but I've had a good dig into and and cannot find why this happens. Pretty sure it's some sort of change on slack's side but cannot work out why or what. BookStack appears to construct the auth URL as expected.

Have you noticed this for a while? Wondering if it's a temporary problem on slack's side.

**Comment by ssddanbrown** [comment]
Just tried on another, Non-BookStack-related, app I manually set up slack auth on. Does that same thing.

**Comment by obeardly** [comment]
It has done this since I installed.  In the past, I have used Slack for
authentication on other apps, and it did not do this. However, as you said,
this may be a change on Slack's end.  I'll look further into it.

**Comment by shane-smith** [comment]
Maybe this is relevant?

https://stackoverflow.com/questions/46094760/sign-in-with-slack-keeps-prompting-user-for-permission-every-time

> Slack Sign-in does not cache user logins like other OAuth providers doe [sic], so if you want to avoid that users have to sign-in every time you have to cache user permissions in your app. e.g. by using cookies.

**Comment by obeardly** [comment]
That definitely seems relevant.  The question is now, how do we enable cookies in BookStack?

**Comment by ssddanbrown** [comment]
Just re-reviewing this, based upon the response from slack [in this stackoverflow question](https://stackoverflow.com/questions/58478994/slack-oauth-automatically-authorize-user-if-user-had-already-authorized-app?noredirect=1&lq=1) it appears the above text was an incorrect detail in the documentation. 

I don't think there's anything we can do about this so I'll close this off.

Note, Slack now advise using their more recent OIDC for authentication flow, which we now support as a primary authentication mechanism. I'd imagine this would not have this issue.
