### ISSUE TITLE
This is fantastic. Thank you!

### ISSUE THREAD

**Issue by ensemblebd** [BookStackApp/BookStack#660]
Just wanted to say thanks, and keep up the great effort. 

I'll do what I can to contribute when time permits. Great product.

**Comment by domainzero** [comment]
I've been meaning to say this for a long time.
Thanks a lot for this great project @ssddanbrown.

**Comment by yoginth** [comment]
Yeah thanks a lot for @ssddanbrown ❤️

**Comment by ssddanbrown** [comment]
:smile: Thanks for the kind words @ensemblebd.

And thanks to all the other contributors and helpers here on GitHub!

**Comment by ssddanbrown** [comment]
Since it's been a couple of years I'm going to close this off.

Thanks again @ensemblebd, @domainzero  and everyone else that's reacted for the kind words. Meant a lot.
