### ISSUE TITLE
Image Permission

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#661]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 19.0
* PHP Version: 7.1
* MySQL Version: 5.7

##### Expected Behavior

If a user uploaded an image to the server it must not be visible to others than the administrator.

##### Current Behavior

But the current behavior is every user can able to view others uploaded image including all profile pictures.

##### Steps to Reproduce

Public user should not see the user uploaded photos rather than theirs.

**Comment by ssddanbrown** [comment]
I think this is pretty much the same issue as #551?

If I'm wrong please clarify how this differs and I'll amend this.

As an additional note, If you can easily browse images I'd suggest following the advise on the security page in the docs to disable indexes and enabling the 'Higher security image uploads' option in setting to make it difficult for external users to find images.

**Comment by ssddanbrown** [comment]
Closing due to the above comment (Being a duplicate)
