### ISSUE TITLE
Roles to see a book only when you're not connected

### ISSUE THREAD

**Issue by PurpleBabar** [BookStackApp/BookStack#664]
Hi all,

Thanks for bookstack, i love the tool :) I was just wondering about the roles that are defined, is ther any way to make a chapter or a book public without authorizing people to acces other books ? at the moment when i enable public in the system admin panel, everybody can see every docs, or do i need to manually and explicitely set righst on every books ?

Thx for your answers :)

**Comment by ssddanbrown** [comment]
Hi @PurpleBabar, Thanks.

There is a way you can do this:
- In settings turn on 'Allow public viewing'.
- In the roles area, Edit the 'public' role and remove all permissions.
- Go to your 'public' book. In the 'more' menu at the top right select permissions. In here enable custom permissions and assign the 'view' permission to the 'public' role.

Book permissions will cascade to child items. Annoyingly you will also have to specify the permissions for all other roles if you still want to allow them to view/edit/delete etc...
I'm aware of this being a pain and I want to update it in the future so you can choose to only override default permissions for select roles but for now this should achieve what you want.

**Comment by PurpleBabar** [comment]
Thanks a lot :D It will do the trick ;)

**Comment by Abijeet** [comment]
@PurpleBabar - If this solves your problem, can you please close the issue?

**Comment by PurpleBabar** [comment]
I haven't teste it yet, but i'll close the issue as soon as i'll do it :)

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please comment and this can be reopened if required.
