### ISSUE TITLE
Long text in chapter description break the width in mobile 

### ISSUE THREAD

**Issue by joshuaavalon** [BookStackApp/BookStack#669]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: Demo
* PHP Version:
* MySQL Version:

##### Expected Behavior

Display like normal.

##### Current Behavior

![capture](https://user-images.githubusercontent.com/7152420/35215310-d297b76a-ff9e-11e7-818f-33ab2db1b880.PNG)

Long text like URL will create a white space on the right

##### Steps to Reproduce

Use long text at the start of a chapter.

**Comment by Abijeet** [comment]
Hey @ssddanbrown, I'll take a crack at this.

**Comment by ssddanbrown** [comment]
@Abijeet I'm going to take this on since I'm looking to get v0.20 out today.
