### ISSUE TITLE
No Exception While Signup!

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#670]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 19
* PHP Version: 7.1.13
* MySQL Version: 5.7

##### Expected Behavior

Register form should show exception while Register

##### Current Behavior

But Bookstack Don't show Exception if all fields are empty.

##### Steps to Reproduce

![screenshot from 2018-01-22 18-40-25](https://user-images.githubusercontent.com/10177861/35222396-c340edcc-ffa3-11e7-8267-63db929bcd78.png)

**Comment by ssddanbrown** [comment]
Thanks for reporting @yoginth, Now fixed for next release.
