### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by DSRobin** [BookStackApp/BookStack#672]
# For Bug Reports

    BookStack Version (Found in settings, Please don't put 'latest'): 0.19.0
    PHP Version: PHP Version 7.2.1
    MySQL Version: 5.7

Expected Behavior
accessing the platform 

Current Behavior
500 Internal Server Error

Hi,

I tried to install BookStack, according to the steps everything wen't pretty well. As soon as I finished the installation I end up getting the 500 Internal server Error.

At first I installed BookStack into a subfolder on the root, after reading some similar issues I re-installed everything on a subdomain, this tackled my issue in changing the DocumentRoot as I'm installing BookStak on a hosted webserver.

I printed the PHPinfo of the server and I can validate that I have all the requirements.
I enabled the debugging in the .env document, but perhaps I need a bit more information on how to retrieve the log.

all folders are writeable by the server and the correct user is owner.

The root of my subdomain did not have a .htaccess file, which I created with the given URL Rewrite given in the documentation.

Below the URL:
http://wiki.wikiharvest.org

**Comment by lommes** [comment]
Laravels logfile is located in the ```storage/logs``` folder, there should be more information about the error.

**Comment by DSRobin** [comment]
No files found in that folder.

I have the feeling this 500 error is due to the .htaccess.
if I have to apply the URL Rewrite, in which .htaccess file does that needs to be applied? I suppose in the root?

**Comment by yoginth** [comment]
Do chmod

**Comment by lommes** [comment]
Does your domain point to the public subfolder? This folder ist the main folder for the web, so the htaccess file there should be used.

**Comment by DSRobin** [comment]
Yes, the DocumentRoot points to the public folder.

`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>`

This is the .htaccess file in the public folder.

**Comment by DSRobin** [comment]
> 
Do chmod and change permissions
> 

hmm, my account has ownership of all files, as well all the required permissions. I changed the permissions to 777 on the folders: storage, bootstrap/cache & public/uploads

didn't help.

**Comment by lommes** [comment]
What kind of hosting do you use? Do you have access to the general errorlog of the webserver?

**Comment by DSRobin** [comment]
I don't think so. When I make an SSH connection and browse to /var/logs, the folder seems to be empty.

For a few folders I get a permission denied and the sudo command is not recognised.

**Comment by lithium-ap** [comment]
Can you verify your version of PHP. I had this happen if my dependencies were not met / used the wrong version of PHP

**Comment by DSRobin** [comment]
PHP Version 7.2.1

You can find thecomplete info at www.wikiharvest.org/phpinfo.php

-------- Original Message --------
Subject: Re: [BookStackApp/BookStack] 500 Internal Server Error (#672)
From: ape_lithium
To: BookStackApp/BookStack
CC: DSRobin ,Author


Can you verify your version of PHP. I had this happen if my dependencies were not met / used the wrong version of PHP

**Comment by DSRobin** [comment]
If the webserver by default enables .htaccess, is it required to edit the .htaccess  file with the URL Rewrite?

**Comment by domainzero** [comment]
Set `APP_DEBUG=true` in the .env file inside the BookStack root folder and post the error here.

**Comment by domainzero** [comment]
@DSRobin Any news on getting those debug logs? Lemme know if I can help at all.

**Comment by DSRobin** [comment]
Seems like no log is appearing in the log folder ...

-------- Original Message --------
Subject: Re: [BookStackApp/BookStack] 500 Internal Server Error (#672)
From: domainzero
To: BookStackApp/BookStack
CC: DSRobin ,Mention


@DSRobin<https://github.com/dsrobin> Any news on getting those debug logs? Lemme know if I can help at all.

**Comment by ssddanbrown** [comment]
In that case it's possible the requests are never reaching the application which aligns to the error message being a non-bookstack view.

You can try looking at the server logs. You could try watching the apache logs with the below command and see what errors pop up when you access the homepage of your site:

```shell
tail -f /var/log/apache2/error.log
```
That command will interactively watch the apache error log and show messages as they are logged. You may have to press `Ctrl+C` when you want to exit.

**Comment by DSRobin** [comment]
Hi, thanks for your reply.


I tried to execute the command, but there are no files or folders in my /var/log/ folder.

My webserver is hosted and I do not have root permissions on it, so I'm kind of limited in managing the server.



________________________________
Van: Dan Brown <notifications@github.com>
Verzonden: zondag 11 februari 2018 11:42:40
Aan: BookStackApp/BookStack
CC: DSRobin; Mention
Onderwerp: Re: [BookStackApp/BookStack] 500 Internal Server Error (#672)


In that case it's possible the requests are never reaching the application which aligns to the error message being a non-bookstack view.

You can try looking at the server logs. You could try watching the apache logs with the below command and see what errors pop up when you access the homepage of your site:

tail -f /var/log/apache2/error.log

That command will interactively watch the apache error log and show messages as they are logged. You may have to press Ctrl+C when you want to exit.

**Comment by 80sgraf** [comment]
I ran into the same problem on shared hosting and the solution was to add
`RewriteBase /`
into the public folder htacces file.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

In addition, Since this issue I've created a page to provide more support on apache subdirectory setup:
https://www.bookstackapp.com/docs/admin/subdirectory-setup/
