### ISSUE TITLE
Request: Copy/Clone Page to New Page

### ISSUE THREAD

**Issue by lithium-ap** [BookStackApp/BookStack#673]
### Feature Requests

Desired Feature: Hi, the ability to copy a page with the app would be nice. Generally selecting and pasting is ok, but I've found that some objects do not keep their format 100%, particularly if there is an embedded table. It would be nice if there was a 'Clone' or 'Copy' option a long with the 'Move' option under More. 

![image](https://user-images.githubusercontent.com/4935041/35289627-7a1cefd0-002d-11e8-9636-81228c2feab2.png)

Thanks again for the great app!

**Comment by ssddanbrown** [comment]
Agreed, I know I've wanted this before, Surprised this has not been requested previously.

**Comment by yoginth** [comment]
yeah, the cloning is very much important like GitHub does!

**Comment by bcc-sysops** [comment]
+1
