### ISSUE TITLE
Add option to set default books view

### ISSUE THREAD

**Issue by lostdesign** [BookStackApp/BookStack#675]
Hey, sorry for that question, could not find it anywhere.
Is there a possibility to set the grid view for every user by default?

The only way i found was to edit `../bookstack/resources/views/books/index.blade.php` and change the logic.

**Comment by yoginth** [comment]
+1 for this question!

**Comment by ssddanbrown** [comment]
Not currently but it will be very simple to make this configurable via the `.env` file. Will update title to make this actionable and mark for next release.

**Comment by lostdesign** [comment]
Oh thanks, i might even look into this myself.

**Comment by ssddanbrown** [comment]
As of v0.20 this will be possible by setting the below in your `.env` file:

```
APP_VIEWS_BOOKS=grid
```

**Comment by rnsvarsitybball** [comment]
Hi, how could I find the .env file?

**Comment by ssddanbrown** [comment]
@rnsvarsitybball You should have a `.env` file on the main folder where your BookStack files are stored. You would have had to edit this to get BookStack running. Depending on how you are accessing files, You may have to show hidden files.

**Comment by sesipod** [comment]
I added this to my .env config file and it does not work for me - I have tried both with no change to the view of my page.

APP_VIEWS_BOOKS=list
APP_VIEWS_BOOKS=grid
