### ISSUE TITLE
Error 500 while trying to register when changing the default locale

### ISSUE THREAD

**Issue by moutonnoireu** [BookStackApp/BookStack#677]
### Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: BookStack v0.19.0
* PHP Version : PHP 7.1.10 (cli)
* MySQL Version : mariadb 10.1.26-0

##### Expected Behavior

You can register a new account.

##### Current Behavior

Got an error 500 while tryng to register.

##### Steps to Reproduce

Go to ``app.php``, change ``'locale' => env('APP_LANG', 'en'),`` to ``'locale' => env('APP_LANG', 'fr'),``.

---

Maybe a setting to choose the default local for all user would sort this bug.

**Comment by ssddanbrown** [comment]
Hi @moutonnoireu, Sorry to hear you're having issues.

To avoid issues please refrain from making any edits to the files in the `config/` folder.
Instead you can add the below line to your `.env` file to make this work.
```
APP_LANG=fr
```

Remember to revert your `config/app.php` change back to 'en'.

**Comment by moutonnoireu** [comment]
Thank you for your help ! 👍
