### ISSUE TITLE
Permission on Comments

### ISSUE THREAD

**Issue by fmaruki** [BookStackApp/BookStack#678]
There should be an option to configure who can write comments on a book/page.

Today it looks like only editors can comment, but I have a scenario where I would like the readers to be able to comment on a page too. It would be a great way for them to give feedback on the documentations.

**Comment by ssddanbrown** [comment]
Hi @fmaruki,
Do the existing permission controls not work for you?

![image](https://user-images.githubusercontent.com/8343178/35455317-5d221510-02c9-11e8-8395-4f83308c5411.png)

**Comment by fmaruki** [comment]
Sorry, I knew that it should exist somewhere, but I was searching in the book permission and could not find.

For my use case this is enough already.

Thank you!
