### ISSUE TITLE
Draw.IO must cover the full screen

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#682]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 19
* PHP Version: 7.1
* MySQL Version: 5.7

##### Expected Behavior

Draw.IO must cover the full screen

##### Current Behavior

But Draw.IO is not covering, it is in a small area down

##### Steps to Reproduce

![screenshot 1](https://user-images.githubusercontent.com/10177861/35483489-bc5129fe-0468-11e8-8ff9-e43f945b53bd.png)

**Comment by ssddanbrown** [comment]
Hi @yoginth, Please can you try clearing your browser cache and checking again.
Most likely you've cached an old stylesheet which does not have the latest required styles.

**Comment by yoginth** [comment]
no not working! if possible please send your screenshot!

**Comment by yoginth** [comment]
And we can able to open multiple windows at a time!

**Comment by ssddanbrown** [comment]
There we go:
![image](https://user-images.githubusercontent.com/8343178/35484403-4391c3aa-0447-11e8-902b-9bc92384de01.png)

Tested on FireFox and Chrome.

This appears to be yet another docspen specific issue since you haven't merged in the required `style.scss` updates.

**Comment by yoginth** [comment]
thanks I will do it
