### ISSUE TITLE
Draw.IO Image is not Deleting if it is deleted in editor

### ISSUE THREAD

**Issue by Yoginth** [BookStackApp/BookStack#683]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 19
* PHP Version: 7.1
* MySQL Version: 5.7

##### Expected Behavior

The image should be deleted if image from draw.io is deleted

##### Current Behavior

but the image is not deleting from the server

##### Steps to Reproduce

Example Book: https://docspen.ga/books/docspen/page/drawio

Example for deleted image: https://docspen.ga/uploads/images/drawio/2018-01-Jan/jKUCkJxkPvYN0FZ2-Drawing-Yoginth-1517183332.png

**Comment by yoginth** [comment]
Any Steps taken?

**Comment by yoginth** [comment]
Any Steps taken?

**Comment by ssddanbrown** [comment]
I don't think the image file should be deleted when the image is removed within the editor. It may be the case that the user wants to restore an older page revision which has a reference to the image included.

Deleting page drawings on page deletion is somewhat logical but someone could potentially copy a drawing for use on another page. 
As said in #632, Will likely look to include a image-manger-like drawing manager to handle versioning and deleting.

**Comment by Yoginth** [comment]
ok fine, thanks for the clarity!
