### ISSUE TITLE
OKTA with new release v0.19

### ISSUE THREAD

**Issue by jacksonp2008** [BookStackApp/BookStack#686]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*:  BookStack v0.19.0
* PHP Version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
* MySQL Version:  mysql --version
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

I did a completely fresh install on Ubuntu 16.04 using your script:
https://www.bookstackapp.com/docs/admin/installation/#ubuntu-1604

##### Expected Behavior

Expected OKTA Login to function, local login works fine.  Followed instructions from here:

https://www.bookstackapp.com/docs/admin/third-party-auth/#okta

##### Current Behavior

Returns:  "Sorry, The page you were looking for could not be found."
URL is: http://nbs.lab.fsu.com/oauth2/v1/authorize?client_id=0oahn7cgekUVrKBgv0x7&redirect_uri=http%3A%2F%2Fnbs.lab.fsu.com%2F%2Flogin%2Fservice%2Fokta%2Fcallback&scope=openid+profile+email&response_type=code&state=7cKCbkwvn1VsT3LDFODiIGPCikVWaUPokg4BzUkF

##### Steps to Reproduce
.env set to:
# OKTA Settings
OKTA_BASE_URL=https://fs.okta.com/
APP_URL=http://nbs.lab.fsu.com/
OKTA_APP_ID=0oxxxxxxapp_id
OKTA_APP_SECRET=Iong_string_client-Secret

OKTA App has the following redirect URI
<img width="687" alt="screen shot 2018-01-29 at 17 15 09" src="https://user-images.githubusercontent.com/1813327/35543082-fe2dfcd0-0517-11e8-98d0-82fcc262f68b.png">

**Comment by jacksonp2008** [comment]
Did you want me to switch them or try something?

**Comment by lommes** [comment]
I will setup a clean install for testing. 

You can try, if calling https://fs.okta.com/oauth2/v1/authorize?client_id=0oahn7cgekUVrKBgv0x7&redirect_uri=http%3A%2F%2Fnbs.lab.fsu.com%2F%2Flogin%2Fservice%2Fokta%2Fcallback&scope=openid+profile+email&response_type=code&state=7cKCbkwvn1VsT3LDFODiIGPCikVWaUPokg4BzUkF manually works for you.

**Comment by lommes** [comment]
Ok, I just tried with a clean install and it works for me, without any issues (after changing the wrong keys in .env)

I get redirected to OKTA_BASE_URL/oauth2/v1/authorize... which is correct. Is it possible you used wrong settings first? It might be possible that you have to clear the cached env parameters with ```php artisan cache:clear``` first. Restarting the server should fix this I think.

**Comment by domainzero** [comment]
@ssddanbrown Looks like this got fixed in #692 - should be good to close.

**Comment by ssddanbrown** [comment]
@domainzero Ah, Thanks for bringing this up
