### ISSUE TITLE
Question: Is it possilbe for this to be ran from a USB

### ISSUE THREAD

**Issue by KarlWebster97** [BookStackApp/BookStack#690]
Hi,

Is there a way of getting this to run via A USB stick? (Like doku wiki). If so any pointers in setting it up? I have little to no experience with PHP hence the question.

Thanks for making this free!

**Comment by Shackelford-Arden** [comment]
Seems like DokuWiki is compiled into a binary package, which makes it easier to be able to run off of the USB. As BookStack is not compiled into binary packages, my assumption is no.

Now, you could install BookStack on a virtual machine and store it on the USB, which would achieve a similar setup, just you'd be dependent on the software you used to create the virtual machine (VMWare, VirtualBox, KVM, etc).

Other than that I'd think there wasn't much of an option for running it off of a USB. 

If there are other ways, hopefully someone else can point them out :)

**Comment by domainzero** [comment]
I would say you're probably out of luck here unless you use docker containers or something. DokuWiki doesn't use a database so it's possible to just feed it into a PHP interpreter and have it run.

BookStack, however, requires a relational database in addition to a PHP interpreter and web server. Until a flat file solution or something like a SQLite database is implemented you probably won't be able to just run this off a USB.

Hopefully that made sense.

**Comment by KarlWebster97** [comment]
Cheers!

**Comment by lommes** [comment]
Everything that @domainzero wrote is correct, but it should be usable with a portable solution (xampp, easyphp, ...)

But it is not as easy as a compiled version since you will have to setup everything in the webserver and database manually
