### ISSUE TITLE
Authentication not working correctly when DN has special chars

### ISSUE THREAD

**Issue by Mika56** [BookStackApp/BookStack#698]
* BookStack Version: v0.19.0
* PHP Version: 7.1.10 (From solidnerd/bookstack)
* MySQL Version: 5.7

##### Expected Behavior
Users that have special chars in their DN should be able to login a second time

##### Current Behavior
When a user has special chars in its DN, it can log in once. If it logs out, it cannot log in again as the email address is already in use.
In settings, the external authentication ID shows `CN=Charl` instead of `CN=Charlène Thibaud,OU=Larmor-Plage,DC=azimut,DC=local`. (The name is also truncated at the special char).

##### Steps to Reproduce
Install Bootstack and link it to an LDAP server.
Have a user with a special char in its DN, like é, è, ê, ë, à, ç, etc...

**Comment by Mika56** [comment]
Same problem with 0.20.0

**Comment by benrubson** [comment]
I faced same issue, be sure to have `LDAP_VERSION=3` in your `.env` configuration file 👍

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

**Comment by Mika56** [comment]
Hi,
If anyone happens to find this issue and have the same bug, I've found a fix in another issue:
Add
```ini
LDAP_VERSION=3
```
In your configuration file.
If that's not enough, you can also convert your database to utf8mb4 (see docs), but that shouldn't be the source of the problem.
