### ISSUE TITLE
Update to Laravel 5.6

### ISSUE THREAD

**Issue by Yoginth** [BookStackApp/BookStack#706]
### For Feature Requests

Desired Feature: Update to new Laravel 5.6 which was just released!

**Comment by lommes** [comment]
In my opinion we should stick with version 5.5 because of the LTS support.

**Comment by Yoginth** [comment]
ok fine!

**Comment by ssddanbrown** [comment]
Yeah, I agree. Not been long since upgrade to 5.5. We'll stick with LTS unless there's a specific reason to migrate.
