### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [BookStackApp/BookStack#707]
Hello, I would like to collaborate in the translation into Spanish, I have experience in this type of translations. Is it already done or is it still to be translated?

**Comment by Yoginth** [comment]
Spanish is already there

**Comment by ssddanbrown** [comment]
Hi @dbucci24,
We already have Spanish translations but if there's anything missing or anything that can be improved details of helping with translations can be [found in the readme here](https://github.com/BookStackApp/BookStack#translations).

I'll close this for now but for any more information feel free to continue to comment.
