### ISSUE TITLE
Books as homepage view

### ISSUE THREAD

**Issue by CodyWarmbo** [BookStackApp/BookStack#713]
Desired Feature: Allow setting "Books" as the default homepage view. This will allow the Bookstack owner or visitor to more quickly access information.

**Comment by ssddanbrown** [comment]
Hi @CodyWarmbo, Thank you for your request.

This request is already open under #615 therefore I'm going to close this issue to prevent duplicates. Please add a :+1: to the top post of that issue to show your support.
