### ISSUE TITLE
Long string causes compose area to change width in Markdown Editor

### ISSUE THREAD

**Issue by cpressland** [BookStackApp/BookStack#715]
### For Bug Reports

* BookStack Version 0.20.0
* PHP Version: `7.0.25-0ubuntu0.16.04.1`
* MySQL Version: `MariaDB 10.1.20`

##### Expected Behavior
When adding a long string in the compose area of the Markdown Editor the width of the preview pane doesn't change.

##### Current Behavior
The width of the preview pane changes when adding a long string.

##### Steps to Reproduce
1) Set Bookstack to Markdown Mode in Settings
2) Create or edit a page
3) Add a very long line, for example:

```
loooooonnnnggggstriiiiinnnggggloooooonnnnggggstriiiiinnnggggloooooonnnnggggstriiiiinnnggggloooooonnnnggggstriiiiinnnggggloooooonnnnggggstriiiiinnnggggloooooonnnnggggstriiiiinnnggggloooooonnnnggggstriiiiinnnggggloooooonnnnggggstriiiiinnngggg
```

**Comment by BackwardSpy** [comment]
I just opened #716 as a potential fix for this issue.

**Comment by ssddanbrown** [comment]
Thank you @BackwardSpy for your pull request on this one.
