### ISSUE TITLE
BookStack High Availability Setup

### ISSUE THREAD

**Issue by jacac** [BookStackApp/BookStack#722]
Hello BookStack developer,  thank you for creating an easy tool to create nice looking books/wikis. 

#### Intro
During a high availability setup of BookStack I could not find any documentation around this topic. I've setup already a few PHP applications in HA mode, so I knew the basics I needed. Hopefully I covered all the areas which needed special attention.

Here a list I came up with during the setup and please correct me if I missed anything:

- Sessions needs to be stored in DB, Memcache or Redis
- storage/uploads needs to live on a shared directory (SAN/NAS) with access from all nodes.
- public/uploads needs to live on a shared directory (SAN/NAS) with access from all nodes.
- No sure about the workflow for S3

It would be nice if a topic could be create in the documentation about this.

#### Missing feature: Customize the location of upload folder.
Feature missing is to customize the location of those upload folders. In the `.env` to have for `STORAGE_TYPE=local` another parameter `STORAGE_LOCAL_ROOT=/full/path/to/something` which could point to a shared folder and hold all files which need to be accessible by all nodes.

The workaround i did was to create links from those folders to SAN location. Now, every time I update BookStack those folders need to be removed and a link created instead.

**Comment by comnam90** [comment]
@jacac Hey I'm looking to setup HA bookstack as well, care you share your notes?    

I setup a MySQL Group Replication cluster initially but it seems Bookstack's DB schema isn't compatible.    

Next I tried a MariaDB Galera cluster, but I'm not as familiar with that and for some reason the bookstack DB doesn't seem to have replicated from one node to the other.

**Comment by comnam90** [comment]
Ah! that was the missing piece   
tables were replicating but without data. Specifying innodb specifically sorted that out

**Comment by jacac** [comment]
Your Galera cluster should have INNODB as the default table engine. Other
table types are not replicated see
https://mariadb.com/kb/en/library/mariadb-galera-cluster-known-limitations/.

**Comment by ssddanbrown** [comment]
Just coming back to this (4 years later :turtle:)

I've now appended a "High Availability" section to our install page:
https://www.bookstackapp.com/docs/admin/installation/#ha

In regards to a `STORAGE_LOCAL_ROOT` option, I'd only introduce such an option if there was a significant case and demand for it. Having predictable paths makes support easier while having less complications to consider when testing/changing things. I'd have thought many in a highly available setup may choose the s3/s3-like path anyway.
