### ISSUE TITLE
searches that starts with a dot gets no results

### ISSUE THREAD

**Issue by Evoolo** [BookStackApp/BookStack#724]
Hi all,

if i have a string on a page like ".test" and search for it, i get no results.

I tried several other symbols, it seems to be only an issue with the dot. 

Any easy way to fix this?

Thanks!

**Comment by ssddanbrown** [comment]
Hi @Evoolo,

The search system works by breaking up the text on a range of characters, A [list of which can be seen here](https://github.com/BookStackApp/BookStack/blob/master/app/Services/SearchService.php#L399) in the code. This includes the `.` which means that what you are seeing is correct (Although annoying for your use case).

Alternatively you can quote search terms, like `".test"` for example, to run a deeper less efficient search that will pick up searches with dots in them.

Let me know if that works for you.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and the above did not work out for you please comment and this can be reopened if required.
