### ISSUE TITLE
Application logo & local_secure

### ISSUE THREAD

**Issue by benrubson** [BookStackApp/BookStack#725]
Hi,

When we set `STORAGE_TYPE=local_secure`, and when we define an application logo :
- the logo does not show on the login page (as it then requires authentication) ;
- once logged-in, login page redirects to the logo image itself.

Environment :
Debian 9 server
MariaDB 10.1.26
BookStack version : v0.20.0
PHP version : 7.0.27

Thank you 👍 

Ben

**Comment by ssddanbrown** [comment]
Thanks @benrubson for reporting, I thought there might be some side-effects in the existing implementation. Will mark to be fixed for next release.

**Comment by ssddanbrown** [comment]
Just pushed an update to ensure system images such as the logo remain in public storage. You may need to re-upload the app logo once updated.

Update will be part of next release, Due later today.

**Comment by benrubson** [comment]
Many thx Dan 👍

**Comment by kevinblackdesk** [comment]
I'm still experiencing this @ssddanbrown. This is only when I visit the login page in an incognito tab. Once I login and logout, the problem is solved. It's only when you have no cookies it seems.

Exact BookStack Version (Found in settings): BookStack v0.31.6
PHP Version: 7.4

**Comment by ssddanbrown** [comment]
@kevinblackdesk If you've migrated to local_secure images this could occur otherwise app logo images uploaded after switching should still upload to the public space to avoid this.

**Comment by kevinblackdesk** [comment]
@ssddanbrown Also: i'm having a hard time uploading my app logo (.png file) again, even resetting and saving the settings doen't work. After saving the app logo is "nothing" again.
![image](https://user-images.githubusercontent.com/69786972/109118095-2740bb80-7743-11eb-9cc4-9f49a1fe951e.png)

**Comment by ssddanbrown** [comment]
@kevinblackdesk This type of behavior can occur if the cache is not behaving. You can try running  `php artisan cache:clear`. You may have to run this with `sudo` depending on permissions set.

**Comment by kevinblackdesk** [comment]
That didn't work @ssddanbrown. I select a picture and click the save settings button, a success alert will appear saying the settings are saved but no application logo is uploaded.

```sh
/usr/local/php74/bin/php artisan cache:clear
Application cache cleared!
```
