### ISSUE TITLE
MyISAM wrongly forced

### ISSUE THREAD

**Issue by benrubson** [BookStackApp/BookStack#726]
Hi,

On a Debian 9 server using MariaDB 10.1.26, with InnoDB as the only storage engine.
BookStack version : v0.20.0
PHP version : 7.0.27

Installation failed because some tables were being created with MyISAM engine.

Strangely enough, I had to comment the following :
`if($requiresISAM) $table->engine = 'MyISAM';`
where I found it, so in the following files :
`database/migrations/2015_07_12_114933_create_books_table.php`
`database/migrations/2015_07_12_190027_create_pages_table.php `
`database/migrations/2015_07_27_172342_create_chapters_table.php`

And it worked.

Perhaps the test used :
`$requiresISAM = strpos($mysqlVersion, '5.5') === 0;`
is not relevant for MariaDB ?

Thank you 👍 

Ben

**Comment by ssddanbrown** [comment]
Huh, That's odd that `5.5` would be at the start of your version string.

To be honest that check was for an old feature anyway but will still be needed for MySQL 5.5 users to get through the migrations.

As an ideal solution the whole old fulltext indexing needs to be removed from the migrations. Just have to be careful not to effect legitimate migrating users.  

Thanks for reporting this issue.

**Comment by ssddanbrown** [comment]
Old fulltext system now carefully stripped from migrations as of eebfd8904e07f2f0b4f4f5e02506f9f43a4969fa so will close this.

Thanks again for reporting!
