### ISSUE TITLE
InnoDB The maximum column size is 767 bytes

### ISSUE THREAD

**Issue by benrubson** [BookStackApp/BookStack#727]
Hi,

On a Debian 9 server using MariaDB 10.1.26, with InnoDB as the only storage engine.
BookStack version : v0.20.0
PHP version : 7.0.27

I faced the following issue during installation :
```
production.ERROR: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter table `search_terms` add index `search_terms_term_index`(`term`))
```

I then had to force :
`'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',`
in mysql connection in following file :
`config/database.php`

Thx 👍 

Ben

**Comment by sprnza** [comment]
The same here using ArchLinux.

**Comment by ssddanbrown** [comment]
Thanks for posting your fix here @benrubson. 

If we can confirm this isn't likely to have any side-effects on other systems it would be worth adding as a default.

**Comment by 1uk** [comment]
Works for me too on CentOS7. Thanks @benrubson and @ssddanbrown

**Comment by jacac** [comment]
This is what I used as well. Would be nice if it could be configured in the .env file.

**Comment by benrubson** [comment]
Closing this, as `DYNAMIC` is now the default InnoDB row format, as per MariaDB 10.2.2 :
https://mariadb.com/kb/en/innodb-row-formats-overview/
