### ISSUE TITLE
Log failed accesses

### ISSUE THREAD

**Issue by benrubson** [BookStackApp/BookStack#728]
Hello,

I think it would be really nice for BookStack to log failed authentications.
We would then be able to monitor these messages and ban malicious IPs, at firewall level, with for example Fail2Ban on a Linux server.

An easy and nice solution would simply be to log a message into the webserver log for each failed authentication attempt or misbehaviour, using for example PHP `error_log()` function.

Thank you very much 👍 

Ben

**Comment by ssddanbrown** [comment]
Thanks for this suggestion @benrubson, I really like this idea. Will really provide some useful security insight.

**Comment by benrubson** [comment]
Thank you very much for your feedbacks Dan 👍

**Comment by 917huB** [comment]
+1, adding this logging would be appreciated.

**Comment by berez23** [comment]
+1

**Comment by ssddanbrown** [comment]
@917huB @berez23 Please could you thumbs-up the original issue post to show support as we can sort issues by this meaning your support for this issue will be take more into account when we are deciding on new features to implement.

**Comment by benrubson** [comment]
See PR #1881 which solves this 👍

**Comment by ssddanbrown** [comment]
Thanks to @benrubson this will be part of the future v0.30 release.
