### ISSUE TITLE
Export pdf doesn't work properly [russian language]

### ISSUE THREAD

**Issue by S1AnGeR** [BookStackApp/BookStack#730]
### For Bug Reports

* BookStack Version v0.20.0
* PHP Version: 7.1-x64
* MySQL Version: MariaDB-10.2-x64

##### Expected Behavior
Correct export to pdf format with russian language support

##### Current Behavior

![Pdf Export](http://i66.tinypic.com/257m6f5.png)

##### Steps to Reproduce
1. Create page on russian language 
2. try export

**Comment by Rai-Rai** [comment]
Did you try to switch to wkHtmlToPdf?
https://www.bookstackapp.com/docs/admin/pdf-rendering/

**Comment by rockenren** [comment]
Can confirm, wkHtmlToPdf renders PDF correctly (in Russian).

**Comment by ssddanbrown** [comment]
To tidy things, I'm merging similar issues, Please see #719 for updates on this issue. Since this is essentially a duplicate I will close this.
