### ISSUE TITLE
Proxy Issue - Installation Script - Ubuntu 16.04

### ISSUE THREAD

**Issue by aaronstuder** [BookStackApp/BookStack#733]
```
Cloning into 'bookstack'...
remote: Counting objects: 12981, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 12981 (delta 0), reused 42 (delta 0), pack-reused 12939
Receiving objects: 100% (12981/12981), 8.11 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (8824/8824), done.
Checking connectivity... done.
ERROR: Invalid composer installer signature
```

Any idea how to resolve?

**Comment by aaronstuder** [comment]
Script works on Vultr, so must be something with the proxy...

I have run the following commands:

``export HTTP_PROXY=http://192.168.105.5:8080
export http_proxy=http://192.168.105.5:8080
export HTTPS_PROXY=http://192.168.105.5:8080
export https_proxy=http://192.168.105.5:8080
git config --global http.proxy http://192.168.105.5:8080

What else can I try?

**Comment by aaronstuder** [comment]
Both commands in the script seems to work....
```

studera@bookstack:~$ wget https://composer.github.io/installer.sig -O - -q
544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061
studera@bookstack:~$ curl -s https://getcomposer.org/installer > composer-setup.php
studera@bookstack:~$
```

**Comment by domainzero** [comment]
Hey @aaronstuder 

What does `php -r "echo hash_file('SHA384', 'composer-setup.php');"` return when you're in the  directory that has `composer-setup.php` in it?

The script is comparing the key obtained from `wget https://composer.github.io/installer.sig -O - -q` to a hash of the actual `composer-setup.php`

Is your copy of `composer-setup.php` getting changed somehow?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
