### ISSUE TITLE
Can't install on shared hosting "The Process class relies on proc_open, which is not available"

### ISSUE THREAD

**Issue by mariaczi** [BookStackApp/BookStack#735]
* BookStack Version *(Found in settings, Please don't put 'latest')*: v0.20.0
* PHP Version: 7.0.27
* MySQL Version: 15.1 Distrib 10.0.31-MariaDB

I'm not able to install BookStack v0.20 on my shared hosting. After run command 
`composer install`
I got:
```
$ composer install
> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"

                                                                                           
  [Symfony\Component\Process\Exception\RuntimeException]                                   
  The Process class relies on proc_open, which is not available on your PHP installation.  
                                                                                           

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```
It is important to have access to proc on server or exists some workaround to be able to install and use this BookStack version?

**Comment by domainzero** [comment]
Chances are your shared host has explicitly disabled `proc_open` on their PHP instance and there's no way around it. I would email your shared host's support team and see if they can give you a hand.

If they can't do anything, your next best option is to spin up a VPS and host everything yourself.

**Comment by lommes** [comment]
You may try ```composer install --no-scripts``` but you will have to run the needed scripts yourself afterwards:

```
php -r "file_exists('.env') || copy('.env.example', '.env');"
php artisan key:generate
php artisan cache:clear
php artisan view:clear
php artisan package:discover
```
I did not try this and it still may fail, but in that way you at least can skip the steps which seem to be ones failing.

The commands above are only the ones defined in the composer.json of BookStack, some dependencies may require additional commands.

You can also try to build BookStack locally and upload all files to your hosting afterwards and maybe run ```composer dump-autoload``` there.

**Comment by mariaczi** [comment]
@lommes Thank you vary much for your explanation. It work's as you wrote. I built BookStack  on my shared hosting and it works as should (I think :), because I checked only the login process and if I have my previously created Books/Chapters/Pages).
Regards.

**Comment by domainzero** [comment]
Today I learned!

**Comment by lommes** [comment]
@ssddanbrown @Abijeet I think this can be closed.

**Comment by Abijeet** [comment]
Thanks @lommes
