### ISSUE TITLE
Easier tag organization and usage

### ISSUE THREAD

**Issue by jtjosvold** [BookStackApp/BookStack#738]
**Desired Feature**
As our BookStack is growing I'm seeing multiple variants of tags being created because people do not know that a similar tag has been created (capitalization, abbreviations, etc.).  It would be helpful to have a page showing an index of tags so that editors can see what tags exist and, in addition, the tags could be linked to searches showing pages that are using that tag. This would also help us with individuals that are not as comfortable with using proper search syntax.

**Comment by ssddanbrown** [comment]
@jtjosvold Thanks for the suggestion, So like a tag-overview page?

I can see the benefit. I think this would be worthwhile once Books and Chapters support tags.
Thinking about this I should really increase the priority on Book/Chapter tags just to finish the base tag system off. 

Somewhat related to #121.

**Comment by jtjosvold** [comment]
Precisely. It would help to keep them organized and make searching easier for our users.

Thanks for looking into it.

**Comment by Cave-Johnson** [comment]
Would just like to add my plus one to this. I love the way bookstack uses tags and it makes the search feature really powerful. 
This would be really useful for managing large instances of bookstack. I like the way that its been done in the pull request. It would also be neat if there was the ability for an admin to combine tags so that multiple similar tags can be cleaned up. As an example, 3 tags for Jan2020 currently appear as jan-20, January2020 and jan2020. It would be really neat functionality to merge the 3, selecting a master tag and then updating the other tag throughout bookstack. 

One other thing that would make using tags much easier is to show all tags that have currently been used within that book or that shelf to avoid users creating a new version of that tag. For example show tags currently used in this book under the add tag box.

**Comment by Klemet** [comment]
I'd really love this to be implemented too. Right now, I kinda feel in the dark about the tags that exist in the Bookstack. It seems like the only way I could find them would be to look at each element of the Bookstack one by one, and make a manual list. To help users search for particular resources, a "all tags" page would be wonderful !

**Comment by ssddanbrown** [comment]
Potential alternative implementation offered here: https://github.com/BookStackApp/BookStack/issues/2943#issuecomment-927850224

**Comment by ssddanbrown** [comment]
In regards to the original issue, there seems to be a desire for something like a tag exploration page but the use-cases and requirements would need to be clear. This is something I've hard trouble defining. Don't want just a plain list of tag names.

I'm thinking:

- **Purpose:** To explore usage of tag names and values in the system.
- **Implementation:**
  - View would primarily be a paging list of tag names
  - List item for the tag name would show:
    - Count of pages/chapters/books/shelves assigned a tag using that name.
    - Count of unique values used with this tag name.
    - Count of all values used with this tag name.
  - List item could be expanded to show all unique name=>value options used for the tag of the specific name.

This would provide a view that's primarily orientated around usage via the instant visibility of counts, which could be expanded to understand tag application. No pages|chapters|books|shelves would be displayed in that view specifically but you'd click through to a tag search for entity views. 

Would be good to know if that specific implementation would meet people's requirements here. I'd want to keep the scope quite focused.

**Comment by jtjosvold** [comment]
I like your idea. We had been using #1354 as a solution (that was one of my developers) so that we had a better idea and had found it helpful but lacking.  I like your idea of incorporating the count and the ability to expand it to see more details.

**Comment by ssddanbrown** [comment]
Implementation as per my comment above has now been merged as per #3042. 
This will be part of the next feature release. 
Hopefully should cover the core requested case here, so will therefore close this off.
