### ISSUE TITLE
Changing the amount of content-preview in the book view

### ISSUE THREAD

**Issue by TheGammelgalopper** [BookStackApp/BookStack#739]
## How it has been

I have been running Bookstack version 0.18 for quite some time now. When I opened a book it showed me the different pages and chapters with the title and one line of the content of each page.

## How it is now

Today I made a fresh install of Bookstack v0.20 and migrated my old database. That all worked flawlessly! But when I now open a book it shows multiple lines of a page's content. I can only see three pages when I open the book and have to scroll a lot...
Proof: https://imgur.com/5dFz3Ot

## Desired Feature:

I totally know that this nitpicking, but somehow it puts me off... I would like an option in the settings, where you can turn the page preview in the "book view" on and off.

**Comment by ssddanbrown** [comment]
Hi @TheGammelgalopper, Thanks for opening this issue.
I've confirmed this issue that you're reporting. I don't think this was intended at all, Think it's a side-effect of a fix for overflowing text.
Have marked to be fixed for next release.

**Comment by TheGammelgalopper** [comment]
Thanks for the quick reply!

I noticed even more, when I was on the phone yesterday...

In the default view (the one you get, when you just log in), there is that switch for toggling detail. This totally works. But then in "book-view" there is no such switch.

Additionally in "book-view" the book's title (HALnet.cloud) also overflows on my iPhoneSE. Maybe setting a CSS option that changes text-size based on space available could help (at least to some degree)

**Comment by ssddanbrown** [comment]
As part of the update to fix the core issue here I also updated with some better, space conscious,  mobile styling in addition to preventing title overflowing.
