### ISSUE TITLE
PDF import garbled

### ISSUE THREAD

**Issue by msaus** [BookStackApp/BookStack#746]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*:v0.20.0
* PHP Version:PHP 7.0.25-0ubuntu0.16.04.1
* MySQL Version:mysql  Ver 14.14 Distrib 5.7.19

##### Expected Behavior
All words are not garbled

##### Current Behavior
All words are garbled

##### Steps to Reproduce
Click on export and PDF

![image](https://user-images.githubusercontent.com/3432876/37394497-3fbe87fc-27b7-11e8-8baa-79bcfd14148a.png)

**Comment by rockenren** [comment]
Install wkhtmltopdf (wkhtmltopdf), Dompdf (default render engine) have such issues (also cannot render PDF in Russian, for example).

**Comment by lommes** [comment]
This is a duplicate to #730 and #719 and will be fixed in [BookStack Beta v0.21.0](https://github.com/BookStackApp/BookStack/milestone/22)

**Comment by msaus** [comment]
okay, thanks for your reply.
is v0.21.0 coming soon?

**Comment by ssddanbrown** [comment]
To tidy things, I'm merging similar issues, Please see #719 for updates on this issue. Since this is essentially a duplicate I will close this.
