### ISSUE TITLE
Private Books (per-user)

### ISSUE THREAD

**Issue by luk51** [BookStackApp/BookStack#747]
Is it possible to have a private book per user? Other people should not even know that the book exist. I didn't figure out how it works, so I created another role with the same name as the user name. Then I enabled custom permissions and set permissions only for this role.
Short:
As a normal user I want to have the ability to create a private book(s), that only I can see, without having to ask the administrator to create an extra role for that as a workaround.

**Comment by Abijeet** [comment]
Currently this,

> I didn't figure out how it works, so I created another role with the same name as the user name. Then I enabled custom permissions and set permissions only for this role.

Is the only way to do it.

**Comment by Shackelford-Arden** [comment]
@Abijeet Are book permissions only set using groups? Could you not simply replace the group with the name of the user?

In terms of showing this in the UI, would it not be possible to add an option to show when creating a book. For example:

By default the toggle "selects" Public (no permissions override). If user toggles, available group permissions will show. Along with it an option to select "Personal" which simply uses the username of currUser for permissions.

Just spit balling here... Wish I had a better understanding of the innards to really help here.

**Comment by Abijeet** [comment]
@Shackelford-Arden - Technically, I think this would be possible with the current structure itself. We would create a hidden **group** with that user and would then give permission to that group to be able to access personal books.

We might have to look at any problems arising out of deleting that user itself. We would not want any orphaned books.

**Comment by Bolthier** [comment]
This is an idea I would like to see realized, too!

This task could be split up in two major ones:

1. Add new attribute "Set Permission" for Custom Permissions (and Asset Permissions)
Even without special user roles it would allow different roles to moderate different instances like books, chapters and even pages. This could even be applied to the default Asset Permissions. With the current Administrator role unaffected by these changes this shouldn't result in any orphaned instances. @Abijeet 

Right now these are the only current permission setting which are applied to every single viewable instance:
A: Manage all book, chapter & page permissions
B: Manage permissions on own book, chapter & pages

2. Add role type "User" for every user that gets registered
These special user roles should be viewable in Custom Permissions with two options customizable in the normal role permissions:
A: Manage custom permissions for all users
B: Manage custom permissions for themself

Combined this should give users (if allowed by the Administrator role) the option to make any instance private. For this scenario to work as intended the website administrator should use different accounts for administrating and the daily use. Which is like most systems should work. For example in my BookStack application I created an additional Co-Admin role which allows me to "hide" any books or sites I don't want to see on a daily basis while retaining any other major permissions.
