### ISSUE TITLE
files in bookstack/vendor directory disappear and cause the browser got 500 error 

### ISSUE THREAD

**Issue by junlicn** [BookStackApp/BookStack#750]
### For Feature Requests

Desired Feature:   normal http response.

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*:  0.20.0
* PHP Version:  PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
* MySQL Version:5.7.21-0ubuntu0.16.04.1 (Ubuntu)

##### Expected Behavior

normal page display.

##### Current Behavior
HTTP ERROR 500

nginx log:
2018/03/16 08:59:12 [error] 3537#3537: *486 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/bookstack/vendor/guzzlehttp/psr7/src/functions_incl5
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/bookstack/vendor/guzzlehttp/psr7/src/functions_include.php' (include_path='.:/usr/share/"

##### Steps to Reproduce

install with  Ubuntu 16.04 Installation Script

run for one or two more days with writing books.

**Comment by junlicn** [comment]
supplement：

root@iZ2ze9hcysthc2bloinso3Z:/var/www/bookstack# composer install 

> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Warning:  Uncaught ErrorException: require(/var/www/bookstack/vendor/guzzlehttp/psr7/src/functions_include.php): failed to open stream: No such file or director5
Stack trace:
#0 /var/www/bookstack/vendor/composer/autoload_real.php(55): Composer\Util\ErrorHandler::handle(2, 'require(/var/ww...', '/var/www/bookst...', 55, Array)
#1 /var/www/bookstack/vendor/composer/autoload_real.php(55): require()
#2 /var/www/bookstack/vendor/composer/autoload_real.php(45): composerRequireef4ebfde56517d00a30c3e00bd70fd1f('a0edc8309cc5e1d...', '/var/www/bookst...')
#3 /var/www/bookstack/vendor/autoload.php(7): ComposerAutoloaderInitef4ebfde56517d00a30c3e00bd70fd1f::getLoader()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/var/www/bookst...')
#5 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(238): Illuminate\Foundation\ComposerScripts::postAutoloadDump(Object(Composer\Script\Event))
#6 /usr/share/php/C in /var/www/bookstack/vendor/composer/autoload_real.php on line 55

**Comment by junlicn** [comment]
it seems  after a while ,  the  directory:  
the total amount size of /var/www/bookstack/vendor   will change from 84M  to 32M .

what happend？  how could I to prevent the files disappear ?

**Comment by ssddanbrown** [comment]
@junlicn Thanks for reporting, What kind of hosting are you using and what operating system is it on?

This is a very strange issue, Does the size of `vendor/` go down gradually over time or does it suddenly jump to that size?

**Comment by junlicn** [comment]
sorry, at first I thinks it is the composer update script problem after I googled it.  But now I am not sure.  It seems after I  deleted my crontab backup shell script which have some rm command, it is normal, not disappear any more.

**Comment by ssddanbrown** [comment]
Okay, No problem, I'll close this issue then. Feel free to comment if you find it is a BookStack issue.
