### ISSUE TITLE
does not support gif animation display

### ISSUE THREAD

**Issue by junlicn** [BookStackApp/BookStack#756]
### For Feature Requests

Desired Feature:  display animation 

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.20.0
* PHP Version: PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
* MySQL Version:

##### Current Behavior

only a static picture or no animation.

##### Steps to Reproduce
After I copy the gif to the bookstack markdown editor, it become a uploaded png file.

![](http://btclearning.net:8080/uploads/images/gallery/2018-03-Mar/scaled-840-0/image-1521447419131.png)

Even after I upload the gif  by link in  the edit page, it still does not display animation.

![Mrzgithub-branching.gif](http://btclearning.net:8080/uploads/images/gallery/2018-03-Mar/scaled-840-0/Mrzgithub-branching.gif)

**Comment by Abijeet** [comment]
Duplicate of https://github.com/BookStackApp/BookStack/issues/223

**Comment by ssddanbrown** [comment]
Closing since duplicate.
