### ISSUE TITLE
Page with name "Create" is inaccessible

### ISSUE THREAD

**Issue by svarlamov** [BookStackApp/BookStack#758]
### For Bug Reports

* BookStack Version:  v0.20.0

##### Expected Behavior

The URL slug should be changed to `/books/foo-book/page/create-1` so that it doesn't conflict with the `/books/foo-book/page/create` route for creating a new page

##### Current Behavior

Going to the page takes you into the page creation view and the page you created earlier is not accessible

##### Steps to Reproduce

Create a page with the name "create"

**Comment by svarlamov** [comment]
For users who may happen to run into this on a later version/before a fix is created, you can manually update the slug. Here is what I used in MySQL:


```sql
select id from pages where name like "create";
update pages set slug="create-1" where id = {{ID FROM STMT ABOVE}};
```

**Comment by ssddanbrown** [comment]
Thanks for reporting @svarlamov . Instead of renaming pages in they conflict I think it'll be good to go through and update all app routes so they cannot conflict with page slugs. Marking for next release.
