### ISSUE TITLE
Create category /  sub category for sorting thing when data scale up

### ISSUE THREAD

**Issue by kopax** [BookStackApp/BookStack#760]
Hi, I've just randomly pulled your project and I think it is nice compared to old twiki and xwiki.

Currently we can just write books with chapter, but there is no way to sort them by group.

Feature would add a way of creating category, eventually sub categories to save our book outside the global namespace.

Also, would you add later file upload on article like zip pdf ... ? Thanks

**Comment by ssddanbrown** [comment]
Hi @kopax, Thank you for your suggestions.

You can add an extra layer of categorisation by using tags. These can be added in the right sidebar when editing a book. Here you can also upload attachments, of any file type, to a page as requested: 

![image](https://user-images.githubusercontent.com/8343178/37848387-dbb01cb4-2ecb-11e8-803d-a3ce7c26872a.png)

If you instead wanted an extra level in the heirachy, That is already an open issue under #95.

Does the above solve your requests?

**Comment by kopax** [comment]
@ssddanbrown thanks for the info.
About the categorization by tags, it is good to be able to have tag for finding out a book from its tag. But as a way to display book, tags don't allow to list and display books by category, they are all mixed up. I think this is somehow very important if you want to have many books many users, and users to be allowed to read/display just certain categories of books. 

My use case is that we have services (marketing, developers,....) and users should be able to display/read book only from their own services

**Comment by ssddanbrown** [comment]
@kopax You can create roles, assign them to users, Then change permissions of particular books to only be readable/editable by certain roles. That sounds like what you're asking here.

**Comment by kopax** [comment]
@ssddanbrown even if it's true, it is not nice to do it for each book (rather than just adding it to a category where user have permissions). 

On the UI side, user will not have a way to browse by hierarchy other than filtering.
I believe we should create a bookshelf, and a UI to browse bookshelf.

I think this is not possible : 

![image](https://user-images.githubusercontent.com/1866564/37878306-261771e6-3091-11e8-8560-f82073b17b29.png)


This is what we need : 

![image](https://user-images.githubusercontent.com/1866564/37878299-096abe86-3091-11e8-9291-4e34814f1fa7.png)

**Comment by ssddanbrown** [comment]
As of the next release BookStack will have [Bookshelves as described here](https://github.com/BookStackApp/BookStack/issues/95#issuecomment-399753699) which brings a level of categorization to Books.  This appears to meet the main request of this issue so I will close this.

**Comment by kopax** [comment]
@ssddanbrown just wow. We've been going on with wikijs and aren't really satisfied of their UI that has many bugs. BookStack was good at testing but lacking some important feature. It sounds good if you corrected all that, is there a way to test online?

**Comment by ssddanbrown** [comment]
@kopax You can see the demo site here:
https://demo.bookstackapp.com/login?email=admin@example.com&password=password

It resets every half hour and some features are disabled (I think adding users or updating settings).

**Comment by kopax** [comment]
@ssddanbrown I don't see how you solved the categories permissions issues.

Our organization needs groups, and permissions should be given to group.

Right now with wikijs, we are able to protect anywhere in such path (not by group but at least individually): `a>b>c>d>e>f`.
