### ISSUE TITLE
Can I run other software on my Ubuntu/BookStack server?

### ISSUE THREAD

**Issue by dbc74** [BookStackApp/BookStack#762]
Hello,
I am _familiar_ with Ubuntu and Apache, but this is the first time I've ever used Nginx.  I used the installation script and everything is working GREAT!!  

My question is this, should I avoid using this server for anything other than BookStack?  I attempted to install phpMyAdmin and it did't connect correctly, so I purged it and stopped.  I would like to be able to create some php/mysql forms and use those outside of Bookstack if possible.

Thanks in advance!
DC

**Comment by ssddanbrown** [comment]
Hi @dbc74, There's no reason why you cannot run other software on the server.

If you are installing PHP applications, such as phpmyadmin via the system package manager you may run into problems as many of these are likely to be configured to use Apache by default which will clash with nginx but they can still be installed, May just require some more manual setup and nginx learning.

Have a search for `Ubuntu <version> nginx phpymadmin install guide`. If you have trouble feel free to ask for more guidance here. 

Just remember to backup beforehand before playing around.

**Comment by dbc74** [comment]
Good to know, I'll give it a go on my test system and see what I come up
with.

Thanks for the prompt response!

DC

**Comment by ssddanbrown** [comment]
Closing as believed to be resolved
