### ISSUE TITLE
Create Link to UNC path

### ISSUE THREAD

**Issue by dbc74** [BookStackApp/BookStack#766]
### For Feature Requests

Desired Feature: Is it already possible to create a link to UNC network directories?

Thanks!!

**Comment by ssddanbrown** [comment]
@dbc74 Not really sure myself, Feel free to give it a quick go [on the demo site](https://www.bookstackapp.com/#demo).

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
