### ISSUE TITLE
LDAP issue

### ISSUE THREAD

**Issue by walterdegraaf** [BookStackApp/BookStack#771]
Hi, 

I'm trying to connect my Bookstack to my Active Directory server. When I log in with a user I receive an error...

This is the config that I try to use: 

# LDAP Settings
LDAP_SERVER=serverip:389
LDAP_BASE_DN="OU=TEST,OU=COMPANY,DC=DOMAIN,DC=com"
LDAP_DN=username@domain.com
LDAP_PASS=password
LDAP_USER_FILTER=false
LDAP_VERSION=3

The error that I get:

production.ERROR: ldap_search(): Search: Protocol error {"exception":"[object] (ErrorException(code: 0): ldap_search(): Search: Protocol error at /var/www/bookstack/app/Services/Ldap.php:56)
[stacktrace]

Line 56 in Ldap.php refers to: return ldap_search($ldapConnection, $baseDn, $filter, $attributes);

Let me know if you need any more info

**Comment by ssddanbrown** [comment]
Hi @walterdegraaf,
I notice your `LDAP_USER_FILTER` is set to `false`. This is what's used to search for users within LDAP. It could be this causing such an error. Let me know if you need more info on that setting.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please comment and this can be reopened if required.
