### ISSUE TITLE
HTML/PDF Export problem, "An unknown error occurred" need some help.

### ISSUE THREAD

**Issue by Xerwulf7** [BookStackApp/BookStack#774]
* BookStack Version: latest
* PHP Version: 7
* MySQL Version: 5.7
* Apache2
* Ubuntu 16 LTS latest

I have a problem with the HTML/PDF Export, (with ngixn and apache2). Everytime I try to export a book to PDF or HTML I get an error:
"An unknown error occurred".... nothing else.
I tried to install it with the Ubuntu 16 script and after that I installed all on my own.
All works except the export function..
Can anyone help?

!chown -R www-data:www-data on BookStack directory is done and all folders which needs r/w got chmod 777.!

**Comment by ssddanbrown** [comment]
Hi @Xerwulf7,
Sorry to hear you are having issues.

You can find some debugging [instructions on the docs here](https://www.bookstackapp.com/docs/admin/debugging/). Please follow these and see if you get any more information with debugging turned on.

Post any logs or extra info here if you need further help.

**Comment by Xerwulf7** [comment]
Hey ssddanbrown,
here is some Info:

file_get_contents(/var/www/BookStack/public/css/export-styles.css): failed to open stream: No such file or directory (View: /var/www/BookStack/resources/views/books/export.blade.php)

/var
/www
/BookStack
/storage
/framework
/views
/02515d89108014d35935ae04766ce7bdb2647395.php

    <!doctype html>
    <html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title><?php echo e($book->name); ?></title>
     
        <style>
            <?php if(!app()->environment('testing')): ?>
            <?php echo file_get_contents(public_path('/css/export-styles.css')); ?>
     
            <?php endif; ?>
            .page-break {
                page-break-after: always;
            }
            .chapter-hint {
                color: #888;
                margin-top: 32px;
            }
            .chapter-hint + h1 {
                margin-top: 0;
            }
            ul.contents ul li {
                list-style: circle;
            }
            @media  screen {
                .page-break {
                    border-top: 1px solid #DDD;
                }
            }
        </style>
        <?php echo $__env->yieldContent('head'); ?>
    </head>
    <body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-content">
     
                    <h1 style="font-size: 4.8em"><?php echo e($book->name); ?></h1>
     

Arguments

    "file_get_contents(/var/www/BookStack/public/css/export-styles.css): failed to open stream: No such file or directory (View: /var/www/BookStack/resources/views/b ▶"

**Comment by ssddanbrown** [comment]
@Xerwulf7 Thanks for confirming the error info.

I can confirm this is a bug and I've just pushed out fix in 3cd08382e944600ecdd1212ce94a9922b4406050 and released v0.20.2 to cover this.

Simply [update your BookStack instance](https://www.bookstackapp.com/docs/admin/updates/) and this should be fixed.
Let me know if you experience any issues afterwards.

**Comment by Xerwulf7** [comment]
Nice to hear, thanks :)

**Comment by Xerwulf7** [comment]
Works like a charm, thanks for the quick response and fix! Have a nice eastern weekend :)
