### ISSUE TITLE
Edit Content and push to Git Repo

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#777]
Desired Feature:

Dependent on #776.  This feature describes how Bookstack can be used as an editor for Markdown files stored in a remote Git repository.

##### Expected Behavior

Assuming a Book has been created using feature #776 

The editor mode should (ideally) be Markdown, but feature #458 could also apply here.  With Markdown Bookstack can define it's own content/file/directory structure on how the files should be organized.  Something compatible to Read The Docs or Gitbook. 

Creating a new page and saving it will create the file on local storage, perform a `git add .` and then a `git commit` using the current user's email address and name, then finally a `git push`.  Editing an existing document follows a similar process.  Chapters would correspond to sub directories.

To handle cases when more than one user edits a page in a given moment.  I think Bookstack already solves this problem with the "Draft" feature.  This should prevent conflicts.

**Comment by ssddanbrown** [comment]
Thanks for writing this up and requesting this but since this issue relies on a non-implemented feature I'm going to close this in the interest of keeping issues actionable and focused. This can always be re-opened if #776 ever becomes a feature.
