### ISSUE TITLE
configurable robots.txt

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#779]
The robots.txt file should be configurable and default to false.

Existing related pull request and history: #734

**Comment by ssddanbrown** [comment]
Added a fully configurable solution to this now.

The default output depends on `Allow public viewing` app setting.
Otherwise can be overridden in `.env` file via `ALLOW_ROBOTS=false` or `ALLOW_ROBOTS=true`.

Otherwise view file can be customised/extended view theme overrides since the content is contained within a `robots.txt` view.

**Comment by userbradley** [comment]
@ssddanbrown Was wondering if this allows for custom overrides, as I dont want my bookstack being indexed at all, but would like one page to be indexed. 

Not sure if this is an option, or if it's either `all or none`

**Comment by ssddanbrown** [comment]
@userbradley The contents of robots.txt is driven by [this view template](https://github.com/BookStackApp/BookStack/blob/development/resources/views/misc/robots.blade.php).

Any of the view templates in BookStack can be overridden without editing the original files, using our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md). [(Video Guide)](https://www.youtube.com/watch?v=gLy_2GBse48).
Should be able to just override the above template using the visual theme system to do whatever you need. 

Just shout if you need further guidance.

**Comment by userbradley** [comment]
@ssddanbrown Ledge Thanks!!
