### ISSUE TITLE
Desired Feature: Ability to remove particular revisions

### ISSUE THREAD

**Issue by jsreynolds** [BookStackApp/BookStack#784]
### For Feature Requests

Desired Feature: Ability to remove revisions

##### Expected Behavior

Ability to remove a particular revision - for security reasons for example where someone has pasted in code or notes which contain private information and saved. Make a change, it still lives on in a revision.

##### Current Behavior

Revisions are unable to be removed.

##### Steps to Reproduce

Edit a page, see the revision

**Comment by Abijeet** [comment]
Hi @ssddanbrown,

I'd like to take a crack at this. I guess adding a **Delete** option here next to **Restore** would work?

![screenshot-2018-5-21 page revisions for examples of different bookstack](https://user-images.githubusercontent.com/1685517/40319947-a7a4578c-5d47-11e8-92c0-b106b9315ff2.png)

I'll look further into the technical complexities involved with this.

**Comment by jsreynolds** [comment]
That looks like a great idea to me; thank you for considering it.

**Comment by Abijeet** [comment]
Hey @ssddanbrown, Let me know if my comments [here](https://github.com/BookStackApp/BookStack/issues/784#issuecomment-390718746) sound okay, and I'll get started on this.

**Comment by ssddanbrown** [comment]
@Abijeet Ah, Sorry I missed this, Yeah sounds good!

**Comment by Abijeet** [comment]
This has been added in PR #1008 and will be in the next release.

**Comment by jsreynolds** [comment]
Just wanted to say thank you - really looking forward to this!
