### ISSUE TITLE
Images don't show on PDF export when using "local_secure" option

### ISSUE THREAD

**Issue by filipemarinheiro** [BookStackApp/BookStack#786]
* BookStack Version: 0.20.3
* PHP Version: 7.1.10
* MySQL Version: 5.7.20

Hi let me congratule for this excellent software.

I'm not being able to export pdf with images when using local_secure setting for images is this possible? 
I seems to be working as expected if images are public, is there anything there anything i can do to enable this for secure images?

thank you

**Comment by ssddanbrown** [comment]
Have updated the export system to enable this, Fix will be in the next release.

**Comment by filipemarinheiro** [comment]
Awesome, i'm happy to help.
Thank you
