### ISSUE TITLE
Feature request: spoiler

### ISSUE THREAD

**Issue by elevants** [BookStackApp/BookStack#788]
Desired Feature: Adding the possibility for collapsible contents (spoiler).

**Comment by skluthe** [comment]
Would love this for tables! I work in IT and clients can have tons of credentials and it can really clog up the screen. I would love to have this as well as a setting to have it collapsed initially (similar to mediawiki's visual editor tables)

**Comment by ssddanbrown** [comment]
Hi @elevants, Thank you for your request.
I think this has essentially already been requested in #78 and is somewhat related to #781.

Therefore I'm going to close this issue. If I have misunderstood and the functionality requested is different please feel free to comment and I'll re-open this issue.
