### ISSUE TITLE
Feature request: private content

### ISSUE THREAD

**Issue by DeehSlash** [BookStackApp/BookStack#792]
Feature request: It would be nice if we could create private content that is only available to the user itself, like a note to myself.

For example: I'll create a new page which should be available only to me, as it documents something related only to me. Or maybe a whole book for each user.

**Comment by Abijeet** [comment]
Hi @DeehSlash,

A similar issue already exists at https://github.com/BookStackApp/BookStack/issues/747, so I'm going to close this issue to prevent duplicates. Please add a +1 to the top post of that issue to show your support.
