### ISSUE TITLE
HTML image export

### ISSUE THREAD

**Issue by gnsiva** [BookStackApp/BookStack#799]
### For Bug Reports

* BookStack Version: 0.20.3
* PHP Version:
* MySQL Version: 5.7.21

This is using solidnerd/docker-bookstack

##### Expected Behavior

HTML export would contain images. These images are copy and pasted into the document, and so are uploaded into the bookstack uploads directory. This works correctly in normal use (expect for export).

##### Current Behavior

No images are visible in HTML export. When I inspect the html, I can see that it is a relative link which doesn't make sense for an export. e.g.

```html
<img src="/uploads/images/gallery/2018-04-Apr/scaled-840-0/image-1523372744778.png" alt="">

and
<img src="/uploads/images/gallery/2018-04-Apr/scaled-840-0/image-1523372680404.png" alt="">
```
I guess there should be a way of configuring the server address so that this is filled in before `/uploads`? Also it would be nice if base64 encoding and embedding the images was also supported.

##### Steps to Reproduce

Launch solidnerd version of bookstack docker container, paste an image into a bookstack page and try to html export.

**Comment by ssddanbrown** [comment]
Hi @gnsiva  and @mendiromania,

Currently BookStack does attempt to Base64 embed images on the page for exports as shown here:
https://github.com/BookStackApp/BookStack/blob/master/app/Services/ExportService.php#L182

If the image is not found then it's not base64 included. 

@gnsiva, Just some questions to help debugging this issue:

* Are you using the full solidnerd docker-compose setup or just the main BookStack container?
* Are you setting any image-based configuration environment variables?
* Have you set the `APP_URL` environment variable at all?

**Comment by gnsiva** [comment]
@ssddanbrown 
To quickly answer, I am using the full docker-compose.
And regarding environment variables, I'm not setting anything other than what is set in the solidnerd setup.

**Comment by gnsiva** [comment]
@ssddanbrown 
Sorry, my bad, setting the APP_URL environment variable in the docker-compose file fixed the exporting. It is base64 encoding it too, hurrah!
I will put in an issue to the solidnerd repo that setting the APP_URL should be in the instructions somewhere

**Comment by ssddanbrown** [comment]
@gnsiva Ah, Fantastic, Happy to hear things are working now. Will close this issue.

**Comment by gnsiva** [comment]
Thanks for your help!
