### ISSUE TITLE
A sincere thank you

### ISSUE THREAD

**Issue by mehrdad-shokri** [BookStackApp/BookStack#807]
This is not really a bug but I wanted to give a big appreciation for open sourcing this project and developing it.  
No other wiki system had the features I wanted except Bookstack. Besides who doesn't love Laravel+Vue stack.  
Thank you❤️

**Comment by stawek** [comment]
@mehrdaad I second that - I was looking for project for building and storing knowledge base - I tested a lot of "wiki" solutions: mediawiki, bluespice, tikiwiki, jswiki and many more but none of them worked out of the box and were so good for my purpose! I love this project!

**Comment by michaelmaw** [comment]
This app is BEAUTIFULLY simple, easy to use, and yet has some very powerful features. It is exactly what I was looking for! It's so intuitive. Excellent work! The other wikis I researched were either too buggy, too bloated, or just too ugly. I'm so excited to use this!

**Comment by ssddanbrown** [comment]
Thank you all, Really great to hear good feedback like this and know it's filling the gap in software that I originally found before creating BookStack. :heart:

**Comment by justinzyw** [comment]
+1 this is the best Confluence open source alternative

**Comment by vdavid** [comment]
Yes, thanks for this thread, I just wanted to thank the effort of @ssddanbrown, @Abijeet and any other contributors. <3 I've just finished doing an extensive research for a knowledge base tool for our growing startup. From all the options I've considered, Google Docs, Confluence and BookStack stood out very clearly. I think it puts you to a quite distinguished league :) Keep up the good work and I really hope we can help you somehow, in case we end up choosing BookStack.

**Comment by iBooster** [comment]
i just can agree to that! I love the Script and I hope it will go on. I am not an good developer, but i hope i can help to get the best out of this project, because this is really awesome

**Comment by thomasjsn** [comment]
I'll second that, I was searching for weeks before someone pointed out this to me. This is what I've been looking for and exactly what I need. Thanks!

**Comment by ssddanbrown** [comment]
Since it's been a couple of years I'm going to close this off. 

Thanks to everyone that's commented and reacted on this issue, Means a lot :heart:
