### ISSUE TITLE
Add ability to copy chapters

### ISSUE THREAD

**Issue by skluthe** [BookStackApp/BookStack#808]
Desired Feature: Allow us to copy a page/chapter to another location. You could put it in the drop down menu under more and it could really improve some peoples workflow. For example I have a template chapter for clients and when I get a new client I have to manually copy and paste each page in the chapter and fill it out. Would be so much easier if we could just clone/copy it.

**Comment by ssddanbrown** [comment]
Hi @skluthe, Thanks for your suggestion. The ability to clone pages has already been implemented in the `master` branch, so will be in the next release. Copying chapters is not part of that implementation.

Is it okay If I update the title of this to be specifically about chapters?

**Comment by skluthe** [comment]
Oh yeah, that would be great!

**Comment by thutex** [comment]
also chiming in as this would be an extremely usable feature... copying a chapter (which would be a template)

**Comment by ssddanbrown** [comment]
This was added within [v21.12](https://www.bookstackapp.com/blog/bookstack-release-v21-12/#copy-entire-chapters--books) so I'll therefore close this off.
