### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by mehrdaad** [BookStackApp/BookStack#809]
* BookStack Version: v0.20.3
* PHP Version: 7.2
* MySQL Version: 5.7

##### Expected Behavior
Upload images in drag and drop

##### Current Behavior
Trying to upload an image results with:  
File path /uploads/images/user/2018-04-Apr/Screenshot-from-2018-04-08-02-52-09.png could not be uploaded to. Ensure it is writable to the server. with error 500

##### Steps to Reproduce
Drag and drop an image to upload

**Comment by watschi** [comment]
Is your `uploads` directory writable by the webserver?

You need to `chown www-data:www-data -R bootstrap/cache public/uploads storage && chmod -R 755 bootstrap/cache public/uploads storage` in your bookstack directory after installation for uploads to work.

**Comment by mehrdaad** [comment]
I solved it. I thought I should just change ownership of ``storage/uploads`` **after turning secure image uploads on**.  
But it was going to upload on ``public/uploads`` anyway.

**Comment by ssddanbrown** [comment]
Thanks @watschi for your help.

Glad to hear this issue is solved, Will go ahead and close this issue.

**Comment by mehrdaad** [comment]
@ssddanbrown just a small question?  
What does turning secure image upload on do?  
Because it was uploading to public folder before and after turning this feature

**Comment by saikrishna1488** [comment]
Not working i am facing same issue in server as well as in container with s3. And another thing is i am getting the file upload error but files are uploaded to s3  :ok_woman:  :ok_woman:  :ok_woman:

**Comment by jagyas** [comment]
Same here, not working with s3 when running on docker
