### ISSUE TITLE
[FR] Edit button on headers

### ISSUE THREAD

**Issue by sprnza** [BookStackApp/BookStack#810]
It would be great to have an edit button, that appears hovering a header of any level, that will open a page in edit mode placing cursor beneath the selected header. It will avoid extra scrolling if one wants to edit something in the bottom of a long page.

**Comment by ssddanbrown** [comment]
Hi @sprnza, Thanks for this request.

This feature has actually already been requested on issue #618. Therefore I will close this one. Please add a thumbs-up to the original comment there to 'upvote' the issue.

If this issue is fundamentally different let me know in a comment and I'll re-open it.
