### ISSUE TITLE
document deployment without .htaccess

### ISSUE THREAD

**Issue by benrubson** [BookStackApp/BookStack#811]
Hi,

Would be nice to add to the documentation rules required by an Apache VirtualHost for a deployment without `.htaccess` file.
There is a performance hit enabling `.htaccess` files, as well as some security concerns.

Rewrite rules should ideally be given outside of `<Directory>` sections, so that an additional / unwanted `Options +FollowSymLinks` is not needed.

Thank you 👍 

Ben

**Comment by watschi** [comment]
I think these are already in [the official documentation](https://www.bookstackapp.com/docs/admin/installation/)

**Comment by benrubson** [comment]
Ah yes @watschi, thank you !
However the rules in the documentation need to be put into a `<Directory>` section (thus needing an additional / unwanted `Options +FollowSymLinks` directive).
In a dedicated BookStackApp Apache VirtualHost, I think we should rather use Rewrite rules outside of a `<Directory>` section 👍
