### ISSUE TITLE
desire auto wrap features

### ISSUE THREAD

**Issue by junlicn** [BookStackApp/BookStack#815]
### For Feature Requests

Desired Feature:
in markdown editor:  
![image](https://user-images.githubusercontent.com/14213863/39281970-058d038e-493a-11e8-9c2a-255b255052ff.png)

What's is in markdown editor , and show the wrap lines in the preview page.
now I need <br> to wrap the text, it is not simple.  

In most advanced markdown editor, it is  always in auto wrap way.  like : https://stackedit.io/app
![image](https://user-images.githubusercontent.com/14213863/39282144-b1d00a10-493a-11e8-96d3-fa2ec347ccca.png)

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*:
* PHP Version:
* MySQL Version:

##### Expected Behavior
![image](https://user-images.githubusercontent.com/14213863/39282047-58ec6af6-493a-11e8-9ced-8f7c660cd91d.png)

auto wrap as in markdown editor.

##### Current Behavior

![image](https://user-images.githubusercontent.com/14213863/39281981-1397601e-493a-11e8-8c0a-9d7df3e77fe5.png)

**Comment by ssddanbrown** [comment]
Thanks for the request @junlicn.

In BookStack we stick to the common-mark syntax for deciding on how to deal with Markdown. This means that you'd need an empty line between two bits of text to indicate a new paragraph. Two adjacent lines, with no empty line in-between, will be assumed to be part of the same line.
