### ISSUE TITLE
Cookies must be set with the Secure flag in HTTPS mode

### ISSUE THREAD

**Issue by hardware** [BookStackApp/BookStack#817]
All cookies should be created such that their access is as limited as possible. This can help minimize damage from cross-site scripting (XSS) vulnerabilities, as these cookies often contain session identifiers or other sensitive information. Session cookies sent from secure sites must be explicitly marked as secure to prevent being obtained by active network attackers.

https://github.com/BookStackApp/BookStack/blob/b0d027a4a9f6b139bdfe697aabffaba5eeaaa5ba/config/session.php#L140-L151

In HTTPS mode, all cookies must be set with the Secure flag, indicating that they should **only** be sent over an encrypted channel.

Can you add this parameter to the .env file to permit administrators to change the value ? Like this : 
```ini
# .env

SESSION_COOKIE_SECURE=true
```

**Hardenize report for demo.bookstackapp.com :**

https://www.hardenize.com/report/demo.bookstackapp.com/1525132852#www_cookies

I use this workaround in my nginx virtual host until you make this change :

```nginx
# Bookstack.conf

proxy_cookie_path / "/; Secure";
```
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path

**Comment by ssddanbrown** [comment]
Thanks @hardware for opening this issue.
I agree this would be good to have as a configurable option. Have marked to be in the next release.

**Comment by ssddanbrown** [comment]
Now implemented, Will be in the next release.
