### ISSUE TITLE
Feature: Subchapters, sub-subchapters etc

### ISSUE THREAD

**Issue by mendiromania** [BookStackApp/BookStack#818]
I'm surprised to see this doesn't exist 😮 
It would be really cool if chapters would support subchapters, 
like being able to create a chapter inside a chapter. 👍

**Comment by Abijeet** [comment]
Hi @mendiromania,

I think this is pretty much covered here - https://github.com/BookStackApp/BookStack/issues/95

Request you to add your support to the issue there by adding a :+1: 

Closing this as a duplicate.
