### ISSUE TITLE
QOL Improvement: Book Navigation withing pages

### ISSUE THREAD

**Issue by mendiromania** [BookStackApp/BookStack#819]
Would be cool when you scroll to the bottom of the page to scroll through the book-tree navigation thingy too.

**Comment by mendiromania** [comment]
Clarification:
It works like that on all the views EXCEPT the page view!

**Comment by mendiromania** [comment]
its still an issue tho cause its not working as intended

**Comment by ssddanbrown** [comment]
Since there has been a few changes to the sidebar and navigation items since this issue was created I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
