### ISSUE TITLE
API Feature

### ISSUE THREAD

**Issue by examinare-dk** [BookStackApp/BookStack#823]
Hello, this is more of a question to get involved in the project but only if there is a need for the functionality.

I have looked at the codebase but this is the first time I ever develop with this framework but have been a PHP developer commercially for over 17 years. 

My request is: If you are willing to get an API done where I can make the Api functions live in the project I would willing to devote some time for this. The functions I would like to add initially:

- Enable the possibility to fetch content to external systems. (For knowledge base sites or external sites)
- Add users enabled to login from external sites.

Then from there it would in theory possiblity to add an external sites connector for example you could make a main site on domain1.blah.com and have a small portion on a domain2.blah.com but that will use only a small part of the system in form of using the API for this.

Technology:

Api should be a simple JSON or XML connection so that you can embed things into it and use for external sites etc. 

What I need to be enabled to start this:

- Would need some help to get started mainly to have a slug connected to my function or class for instance /api/ to a special external class and also, of course, a connection to someone who I can ask things about the project to get the work done.

**Comment by jakoubek** [comment]
Yes - an API would be really useful. I have a ton of documentation that I would like to import into a Bookstack instance (without having to write SQL import statements).

**Comment by tiredofit** [comment]
An API would be very useful for exact usage case above, yet also an opportunity to display "Books" available to the user in question linking them to either BookStackApp, or displaying the actual content.

**Comment by Agadagluglu** [comment]
Hi guys. An API feature for book management would be really useful : adding a job to my CI to push .md doc to BookStack would be neat (;

**Comment by samtuke** [comment]
+1. We need to import xhtml. Cli import would also be fine.

**Comment by ssddanbrown** [comment]
Just to confirm, An API implementation is upcoming on the [roadmap](https://github.com/BookStackApp/BookStack#road-map). I have opened issue #1414 to discuss authentication options.

**Comment by col-panic** [comment]
I want to add a healthcheck to my bookstack container. Here I would really like to have an API endpoint which tells me whether bookstack is up and running ok. 

For rocketchat, for example, this looks like this (as part of the docker-compose.yml)

```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/chat/api/info"]
      interval: 30s
      timeout: 5s
      retries: 3
```

**Comment by MarcusTheSmith** [comment]
Glad this is on the road-map! Is there a timeline for this?

**Comment by ssddanbrown** [comment]
@MarcusTheSmith Nothing strict, since this project is only really a free-time endeavour, but the plan is to have an initial auth implementation with a single set of endpoints in the next release to gain feedback on. Hoping to have next release done for end of year at latest. Then expand on API in future release to cover other endpoints. So maybe first quarter of next year is what I'd like.

**Comment by cipi1965** [comment]
I’m currently implementing a GraphQL endpoint in BookStack. I don’t know if anyone is interested

**Comment by modem7** [comment]
Definitely interested in the endpoint for docker!

**Comment by ssddanbrown** [comment]
As of v0.31 we now have core CRUD actions for shelves, books, chapters and pages: https://www.bookstackapp.com/blog/beta-release-v0-31-0/#api-update---pages

Additionally, I have setup a repo to house some API script examples that can be used as a base or for reference:
https://github.com/BookStackApp/api-scripts

Therefore I'm going to close this off but feel free to open new issues if you have a legitimate need for additional specific endpoints or features.
