### ISSUE TITLE
Back to top blocking the editor in page edit mode!

### ISSUE THREAD

**Issue by mendiromania** [BookStackApp/BookStack#824]
Quick fix:     <script>window.onload = function() {$('div[back-to-top]').remove();};</script> in pages\edit.blade.php

**Comment by dsaundersWizmo** [comment]
Ditto.  

But the workaround above worked, thanks for posting.

**Comment by Abijeet** [comment]
Marking this as a bug because **Back to top**, doesn't do anything on the edit page view and can be removed.
