### ISSUE TITLE
How to get another home page ?

### ISSUE THREAD

**Issue by Guims** [BookStackApp/BookStack#827]
Hello, I would like my default homepage to be the books page. I try to change the path in my shared host but it does not work, he create me a folder books.

I would like this url https://my_domain.com/books

is transformed into https://my_domain.com

Thank you in advance for your help.

**Comment by Abijeet** [comment]
Hi @Guims,

A similar issue already exists at https://github.com/BookStackApp/BookStack/issues/615, so I'm going to close this issue to prevent duplicates. Please add a +1 to the top post of that issue to show your support.

PS - If you want another different page as your home page, you can do that from settings. See screenshot below, bottom left - **Application Homepage** setting.

![screenshot-2018-5-6 settings bookstack](https://user-images.githubusercontent.com/1685517/39676288-c6f580ac-5185-11e8-8bda-13221298ab5a.png)
