### ISSUE TITLE
Feedback: These draw.io diagrams are super-freakin'-awesome

### ISSUE THREAD

**Issue by viktorjamrich** [BookStackApp/BookStack#828]
Hey!

I just wanted to say thank you for implementing
these draw.io diagrams.

I now use them like all day long - it's been a massive help! ;)

The only thing I'd really appreciate is the revisioning with the diagrams,
so I could potentially revert back to a previous version.

Thanks a lot ;)

**Comment by Abijeet** [comment]
Hey @viktorjamrich,

I think @ssddanbrown is planning versioning. You can see the corresponding issue here - https://github.com/BookStackApp/BookStack/issues/770

**Comment by ssddanbrown** [comment]
@viktorjamrich Thank you very much for your kind comments, happy to know the integration is being used. 

Yeah, as Abijeet has mentioned above, image versioning (Including drawings) is a priority for me for the next release.
