### ISSUE TITLE
Feature Requests: Corporate Identity Styling/Definitions

### ISSUE THREAD

**Issue by MR-GamBit** [BookStackApp/BookStack#829]
### For Feature Requests

Desired Feature: To define default Fonts, Colors, Logos, Pageheaders and Pagefooters for Pages and Book-Export.

This would enable the system to generate Books according to corporate identity designes.

**Comment by lommes** [comment]
Have a look at #652 

This is not yet documented and may need some more work.

**Comment by ssddanbrown** [comment]
Hi @MR-GamBit,

Some information on what you want to do can be found here: https://www.bookstackapp.com/docs/admin/visual-customisation/

As lommes has mentioned above, There is a theme system planned which would allow further customisation. 

I feel like this request has a lot of overlap with existing issues, such as #652, #493 so I am going to close this but if there's anything specific upon those features feel free to add comments on those issues.
