### ISSUE TITLE
Can i export and import books, chapters or pages?

### ISSUE THREAD

**Issue by alphonse92** [BookStackApp/BookStack#831]
### Can i export and import books, chapters or pages?

If bookstack doesnt support export and importing books chapters and pages i desire it.

Desired Feature: Export and import books, chapters and pages

**Comment by doc-jay** [comment]
you can definitely export books, chapters, pages, but I haven't seen a feature to import, besides attachments.

**Comment by ssddanbrown** [comment]
Hi @alphonse92, As mentioned above there are export options. Alternatively all content is stored in both text and HTML in the database so can be exported, or even imported with some custom logic, directly via the DB.

System Import/Export has already been requested under a range of issues therefore I'm going to close this issue. If you have any specific format requests it would be great if you could add your thoughts to #43.
