### ISSUE TITLE
PDF Export fails with unknown reason at anything that isn't simple text

### ISSUE THREAD

**Issue by tdkl** [BookStackApp/BookStack#832]
### For Bug Reports

* BookStack Version: 0.21.0
* PHP Version: 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS ) 
* MySQL Version: Ver 14.14 Distrib 5.7.22
* Linux: Ubuntu Server 16.04 LTS

##### Expected Behavior
Converted PDF files with images, codeblocks as Export to HTML works without issues.

##### Current Behavior
Anything beyond headings, bodytext and an image or two fails with "Unknown error", or times out. I've tried it with wkhtmltopdf as well and there's same behaviour.

##### Steps to Reproduce
Exporting a page to PDF.

Here's the source code of an example of a page that results in unknown error with DomPDF and wkhtmltopdf.

https://pastebin.com/B4RYvSSD

**Comment by ssddanbrown** [comment]
Hi @tdkl,
Thanks for opening this issue and for providing the sample HTML.

During testing I've found DomPDF exports to work okay with your sample but WKHTML exports are indeed failing.

Could you [enable debugging](https://www.bookstackapp.com/docs/admin/debugging/) on your instance and post the error message shown when this fails? Would be good to know if your error message matches the one I'm seeing.

**Comment by ssddanbrown** [comment]
May be related to #796

**Comment by tdkl** [comment]
Hey @ssddanbrown, 

using DomPDF indeed does render this PDF, my mistake. Here's the snip of the log with debug enabled, hope I don't cut anything vital: 

`/var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#70 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#71 /var/www/bookstack/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#72 {main}
"} 
[2018-05-12 12:30:03] production.ERROR: The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=========================>                                  ] 42%
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
Printing pages (6/6)
[>                                                           ] Preparing
[===================>                                        ] Page 1 of 3
[=======================================>                    ] Page 2 of 3
[============================================================] Page 3 of 3
Done                                                                      
Exit with code 1 due to network error: ContentNotFoundError
"
stdout: ""
command: /var/www/bookstack/wkhtmltopdf --lowquality --print-media-type '/tmp/knp_snappy5af6de4a055e76.07222461.html' '/tmp/knp_snappy5af6de4a059651.74844259.pdf'. {"userId":3,"email":"tadej<redacted>","exception":"[object] (RuntimeException(code: 0): The exit status code '1' says something went wrong:
stderr: \"Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=========================>                                  ] 42%
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
Printing pages (6/6)
[>                                                           ] Preparing
[===================>                                        ] Page 1 of 3
[=======================================>                    ] Page 2 of 3
[============================================================] Page 3 of 3
Done                                                                      
Exit with code 1 due to network error: ContentNotFoundError
\"
stdout: \"\"
command: /var/www/bookstack/wkhtmltopdf --lowquality --print-media-type '/tmp/knp_snappy5af6de4a055e76.07222461.html' '/tmp/knp_snappy5af6de4a059651.74844259.pdf'. at /var/www/bookstack/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php:378)
[stacktrace]
#0 /var/www/bookstack/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(177): Knp\\Snappy\\AbstractGenerator->checkProcessStatus(1, '', 'Loading pages (...', '/var/www/bookst...')
#1 /var/www/bookstack/vendor/knplabs/knp-snappy/src/Knp/Snappy/Pdf.php(63): Knp\\Snappy\\AbstractGenerator->generate(Array, '/tmp/knp_snappy...', Array, false)
#2 /var/www/bookstack/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(221): Knp\\Snappy\\Pdf->generate(Array, '/tmp/knp_snappy...', Array)
#3 /var/www/bookstack/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(242): Knp\\Snappy\\AbstractGenerator->getOutput(Array, Array)
#4 /var/www/bookstack/vendor/barryvdh/laravel-snappy/src/PdfWrapper.php(176): Knp\\Snappy\\AbstractGenerator->getOutputFromHtml('<!doctype html>...', Array)
#5 /var/www/bookstack/app/Services/ExportService.php(141): Barryvdh\\Snappy\\PdfWrapper->output()
#6 /var/www/bookstack/app/Services/ExportService.php(87): BookStack\\Services\\ExportService->htmlToPdf('<!doctype html>...')
#7 /var/www/bookstack/app/Http/Controllers/PageController.php(458): BookStack\\Services\\ExportService->pageToPdf(Object(BookStack\\Page))
#8 [internal function]: BookStack\\Http\\Controllers\\PageController->exportPdf('cestni-in\\xC5\\xBEenir...', 'konfiguracija-i...')
#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('exportPdf', Array)
#11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Controllers\\PageController), 'exportPdf')
#12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/bookstack/app/Http/Controllers/Controller.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): BookStack\\Http\\Controllers\\Controller->BookStack\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/bookstack/app/Http/Middleware/Authenticate.php(48): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): BookStack\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/bookstack/app/Http/Middleware/Localization.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): BookStack\\Http\\Middleware\\Localization->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 `

Couple questions:

- does attaching large images in a Bookstack page influence the success of an PDF export (using both PDF  export engines)? I usually don't resize screenshots and they're properly resized when viewing on the web, also when exporting the HTML,

- does the server instance hardware affects export? I use a small VM, 1 core, 512MB RAM (only 2 users on the Bookstack instance, rarely at the same time).

**Comment by tdkl** [comment]
My mistake closing the issue 😇

**Comment by rockenren** [comment]
I have same issue: https://pastebin.com/5B7tTTwF
Some PDF renders ok, some not.
Temporary solution from #796 not worked for me.

**Comment by tdkl** [comment]
Hello,

release v22 with the commit from #796 fixed rendering the above example, thanks !
