### ISSUE TITLE
Problem instaling BookStack

### ISSUE THREAD

**Issue by ricardasg** [BookStackApp/BookStack#833]
Hi, I am having a problem instaling BookStack. The thing is I have issues with composer. 
When I try to install it, i get this error.  
I am using php 7

Problem 1
    - The requested PHP extension ext-tidy * is missing from your system. Install or enable PHP's tidy extension.
  Problem 2
    - Installation request for gathercontent/htmldiff ^0.2.1 -> satisfiable by gathercontent/htmldiff[0.2.1].
    - gathercontent/htmldiff 0.2.1 requires ext-tidy * -> the requested PHP extension tidy is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by Guims** [comment]
enable extension tidy in php

**Comment by ssddanbrown** [comment]
Hi @ricardasg, The error kind of explains itself. This is a PHP extension required by BookStack for revisioning. To provide more detail:

1. Find and open the file `C:\\xampp\php\php.ini` for editing.
2. Search for the line: `;extension=php_tidy.dll` in this file.
3. Remove the `;` at the start of this line.
4. Save the file and retry.

Hope that helps, Please confirm if that fixes things.

**Comment by ricardasg** [comment]
Yes it did, somehow found similar problem and fixed it. Thanks!

**Comment by Abijeet** [comment]
Closing the issue on behalf of @ricardasg

**Comment by obiefy** [comment]
Hi,
if some face a similar problem on Linux and does not find the extension he may install the extension:
`sudo apt-get install php7.2-tidy`
make sure the version of PHP.

**Comment by ssddanbrown** [comment]
Hi @obiefy,
You are commenting on an old, resolved issue.

If you still are experiencing issues I'd advise you please open a new issue with details which include the full version of linux you are using and details of how you have installed BookStack.
