### ISSUE TITLE
Unable to save Admin system permissions

### ISSUE THREAD

**Issue by doc-jay** [BookStackApp/BookStack#834]
* BookStack Version: .22-dev
* PHP Version:  7.0.30
* MySQL Version: 5.6

When I edit the admin role and deselect 'Manage permissions on own book, chapter & pages' and click 'Save', I would expect that setting to remain deselected.

When I edit the admin role and deselect 'Manage permissions on own book, chapter & pages' under system permissions' for the role and click 'save', it is not saved after I edit the role again to double check it.

GOAL:
**What I am trying to accomplish is having private books for users that members of the admin group cannot see.**

*Steps to reproduce
1.  Edit the admin role
2.  deselect 'Manage permissions on own book, chapter & pages'
3.  click 'save'
4.  edit the admin role
5.  check if settings were saved.

**Comment by ssddanbrown** [comment]
Hi @doc-jay, Thanks for opening this issue.
What you're reporting here is very much a purpose-built feature of the system, Admin permissions cannot be limited. This is to allow an admin the ability to always view, edit and help with supporting users within the BookStack instance. In addition, It allows us during development to allocate new features to those admin users without worrying.

You could rename the admin role to something along the lines of `super-user`, Have that role majorly limited and create a new `admin` role with restricted permissions.

**Comment by doc-jay** [comment]
okay, thanks for the update.  I appreciate it.
