### ISSUE TITLE
default books page

### ISSUE THREAD

**Issue by Guims** [BookStackApp/BookStack#836]
Hello, I'm looking for several days but I'm new to laravel. I would like my home page to be the books page, could you please help me.

**Comment by ssddanbrown** [comment]
Hi @Guims,
Thanks for this request. This is already open in #615 and is being actively worked on under #830 for the next release. You'll just need to update when the next release arrives. 

Since this is duplicate issue I'm going to close this.

**Comment by ssddanbrown** [comment]
@Guims Currently aiming for the end of this week. Might delay into next week though. No guarantees.
