### ISSUE TITLE
Upgrade Confusion

### ISSUE THREAD

**Issue by aljawaid** [BookStackApp/BookStack#839]
@ssddanbrown I am currently using v0.20.0 and told my hosting company to update to v0.20.1 (as per your blog).

The hosting company is saying that updating my bookstacks will upgrade to the latest version, currently v0.21.0.  Reading the blog, I am under the impression that I need to upgrade per-release.

### **Kindly clarify** is jumping from v0.19.0 > v0.21.0 will be correct.

_Below is the hosting company's explanation:_

> We can download the specific version of BookStack i.e v0.20.1 using the following link provided by you.
>
>https://github.com/BookStackApp/BookStack/releases/tag/v0.20.1
>
>But the "git" command and the steps given at following URL, used to update the BookStack will update the BookStack to the latest version. We do not find any version specific command for updating to BookStack v0.20.1.
>
>https://www.bookstackapp.com/docs/admin/updates/
>
>If you wish, you can perform the BookStack update to the specific version from your end. Alternatively kindly provide us the exact link containing the command to execute the BookStack to the specific version.

**Comment by Abijeet** [comment]
Hi @aljawaid. I think an upgrade from v0.19.0 or v0.20.0 to v0.21.0 should be fine. Please ensure a backup is taken before you run the upgrade so in the remote case of a failed update, you can still rollback to the previous version.

**Comment by aljawaid** [comment]
Thanks @Abijeet, I will get the hosting company to try it out

**Comment by aljawaid** [comment]
The hosting compny has updated directly from v0.19 > 0.21.0 without any problems.

Thanks for the help.
