### ISSUE TITLE
The page has expired due to inactivity.  Please refresh and try again.

### ISSUE THREAD

**Issue by dtw-chriss** [BookStackApp/BookStack#840]
**BookStack v0.21.0**

Users are receiving an error from time-to-time when using the markdown editor.  There does not appear to be much of a pattern that can be identified. (multiple browsers and users)

*"The page has expired due to inactivity.  Please refresh and try again."*

**Comment by ssddanbrown** [comment]
Hi @dtw-chriss, Thanks for opening this issue. Are you able to provide a screenshot of this error at all. Just want to see where, when and which system the error is generated at.

**Comment by mr-yaky** [comment]
Hi @ssddanbrown I had the same problem also on v0.21.0 version and after updating to v0.23.2 this problem gone away.

**Comment by mr-yaky** [comment]
After more deep investigating I found that problem always return after adding more than one replica of app.
I guess for two and more replicas we need use :

`SESSION_DRIVER=memcached`

and additional memcached service as dependency.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
