### ISSUE TITLE
ldap_search(): Search: Bad search filter

### ISSUE THREAD

**Issue by tesaorif** [BookStackApp/BookStack#843]
* BookStack Version: 0.21.0 
* PHP Version: PHP 7.0
* MySQL Version: MariaDB 10.0.34

##### Expected Behavior
Allows AD users to Login via LDAP

##### Current Behavior
ldap_search(): Search: Bad search filter
ldap_search(): Search: Unable to reach LDAP server

Hey there,

I'm getting multiple error from BookStack when i try to enable the LDAP login option. After enabling the advanced debug option i found out that BookStack wasn't acception my search filters.

Here's my LDAP config : 

LDAP_SERVER=192.168.23.110
LDAP_BASE_DN="OU=Section informatique,DC=orinfo,DC=lan"
LDAP_DN="CN=autouser,OU=Users,OU=Section informatique,DC=orinfo,DC=lan"
LDAP_PASS=REDACTED
LDAP_USER_FILTER=(&(uid=${user}))
LDAP_VERSION=3

and a screenshot of the error message : 

![error](https://user-images.githubusercontent.com/27957042/40177865-12b99926-59e0-11e8-8bf1-fd054e7500cb.png)

**Comment by albergoniSivaf** [comment]
Try this:

"(&(sAMAccountName=${user}))"

**Comment by tesaorif** [comment]
@albergoniSivaf Thanks for you answer.

I forgot to add the alternative option that i tried in my first comment. Unfortunatelly, i still get the same ldap_search error, even with your recommandation.

**Comment by albergoniSivaf** [comment]
This is my working configuration:

LDAP_SERVER=<server>:389
LDAP_BASE_DN=CN=Users,DC=<mydomain>,DC=local
LDAP_DN=CN=<myuserquery>,CN=Users,DC=<mydomain>,DC=local
LDAP_PASS=<myuserquery_password>
LDAP_USER_FILTER="(&(sAMAccountName=${user})(memberof=CN=<BookStack Users Group>,CN=Users,DC=<mydomain>,DC=local))"
LDAP_VERSION=false
LDAP_EMAIL_ATTRIBUTE=mail

My AD is build with Samba v4.
BookStack Version: 0.21.0

**Comment by tesaorif** [comment]
Finally got it working. Even added the option to login by with the email address. 

Here's the syntax that i'm using:

LDAP_USER_FILTER=(|(sAMAccountName=${user})(mail=${user}))
