### ISSUE TITLE
Codemirror problem with clike langs

### ISSUE THREAD

**Issue by l0co** [BookStackApp/BookStack#849]
In BookStack Version: from `solidnerd/bookstack:0.21.0` docker codemirror syntax highlight doesn't work with clike languages. Check the video attached.

[codemirror-clike.mp4.gz](https://github.com/BookStackApp/BookStack/files/2019398/codemirror-clike.mp4.gz)

**Comment by l0co** [comment]
In this version I've added custom html head content to change theme to `mbo` to check if it helps, but it doesn't. However, it doesn't work in the same way without the custom theme.

**Comment by ssddanbrown** [comment]
Thanks @l0co for reporting this.
I've marked up for the next release.

### Dev reference

Looks like I'm not setting the mode properly for the codemirror instance, c-like langs need to be a little more specific. Bottom of the source of this page shows this:
https://codemirror.net/mode/clike/index.html

**Comment by ssddanbrown** [comment]
Now patched, Fix will be in the next release.

**Comment by l0co** [comment]
Thanks, I'm going to patch this docker anyway
