### ISSUE TITLE
Unable to install Bookstack with MySQL Server Group Replication

### ISSUE THREAD

**Issue by comnam90** [BookStackApp/BookStack#853]
### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: Latest code from 'release' branch as of 22/05/2018
* PHP Version:  7.2
* MySQL Version: 8.0.11

##### Expected Behavior

- Manually deploy MySQL Server Group Replication hosts
- Run installer script (https://github.com/BookStackApp/devops/blob/master/scripts/installation-ubuntu-18.04.sh)
- Launch Bookstack

##### Current Behavior

During the stage of running `php artisan migrate --no-interaction --force` it throws the following errors    

```
  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 3098 The table does not comply with the requirements by an external plugin. (SQL: insert into `permission_role` (`permission_id`, `role_id`)
   values (1, 1), (1, 8))



  [PDOException]
  SQLSTATE[HY000]: General error: 3098 The table does not comply with the requirements by an external plugin.
```
I believe this is because Group Replication requires that every table have a defined primary key, and the permission_role table might not?
similar issue here https://stackoverflow.com/questions/47784729/drupal-8-installation-with-mysql-replication?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by comnam90** [comment]
Apologies, this isnt because of the primary key, checking the mySQL error logs shows this    
```
[ERROR] [MY-011543] [Repl] Plugin group_replication reported: 'Table permission_role has a foreign key with 'CASCADE' clause. This is not compatible with Group Replication.'
```

**Comment by comnam90** [comment]
Actually `password_resets` table isnt compatible either according to this

http://lefred.be/content/mysql-group-replication-and-table-design/

**Comment by ssddanbrown** [comment]
Apologies for not responding until now.
Just coming across this while looking through old issues.

I'm going to close this off since Server Group Replication is not something we specifically support, nor has it been requested by any other users as far as I've seen.
