### ISSUE TITLE
Integration in an existent project

### ISSUE THREAD

**Issue by mmteyrek** [BookStackApp/BookStack#856]
Hello,
It’s possible to integrate BookStack in an existent Laravel Project?
Did anyone done this before?
Thank you.

**Comment by ssddanbrown** [comment]
Hi @mmteyrek,
Thanks for the suggestion.

Please see my comments on this here:
https://github.com/BookStackApp/BookStack/issues/141

Since I stand by those points I will close this issue.

**Comment by mmteyrek** [comment]
Hello,
Thank you for your answer.
btw great job.
