### ISSUE TITLE
Image upload failed

### ISSUE THREAD

**Issue by DeehSlash** [BookStackApp/BookStack#857]
When I try to upload an image to use as a book cover, I get this error:
![2018-05-25_121344](https://user-images.githubusercontent.com/15927886/40552169-55fbc20a-6015-11e8-95f4-28b8fa59d042.jpg)

Which translating to english, is something like that:

> The file upload destination path (/uploads/images/cover/2018-05-May/4LI8jmX9g0Tkycaf-header.png) does not have write permission. Make sure that it has write rights to the server.

* BookStack Version: 0.21
* PHP Version: 7.2.4
* MySQL Version: 10.2.14-MariaDB

I already gave permission to apache:apache over the project folder (not just the public folder)

**Comment by DeehSlash** [comment]
@ssddanbrown CentOS 7

**Comment by ssddanbrown** [comment]
Potentially SELinux preventing write? Not really familiar with SELinux or CentOS myself though

**Comment by DeehSlash** [comment]
SELinux is disabled. I’ll run some tests tomorrow and then let you know here. Thanks for now.

**Comment by DeehSlash** [comment]
Strange... I applied chown again and now it is working.
