### ISSUE TITLE
Can not create page under book (selfhosted fresh install)

### ISSUE THREAD

**Issue by jarink0** [BookStackApp/BookStack#863]
* BookStack Version:  0.22.0 
* PHP Version:7.0
* MySQL Version:5.7.22

##### Expected Behavior

be able to create pages :)

##### Current Behavior

An Error Occurred
An unknown error occurred

Return to home

##### Steps to Reproduce

-create book
-create page
-edit title/text
-click save

thank you!

EDIT: with enabled debug

    Undefined property: DOMDocument::$documentElement/var/www/xxx/app/Repos/EntityRepo.php#731ErrorException

            $doc = new DOMDocument();
            $doc->loadHTML(mb_convert_encoding($htmlText, 'HTML-ENTITIES', 'UTF-8'));

            $container = $doc->documentElement;
            $body = $container->childNodes->item(0);
            $childNodes = $body->childNodes;
and this:

    errorlog[11:36:39] LOG.error: Undefined property: DOMDocument::$documentElement {"userId":1,"email":"admin@a...

**Comment by ssddanbrown** [comment]
Hi @jarink0,
Can you confirm what editor you are using (WYSIWYG-default or Markdown) and the OS you've installed BookStack on?
Also if you could confirm if you used one of the official scripts to install or not that would be great.

**Comment by jarink0** [comment]
hello @ssddanbrown ,

i tried both editors and the error was same, im running Ubuntu Server 16.04.4 with manual install (according to bookstack official documentation for first time and second time i used this guide https://www.howtoforge.com/tutorial/how-to-install-bookstack-on-ubuntu-1604/ but only for bookstack

pls let me know if you need more specific info

thank you
