### ISSUE TITLE
Missing string translations

### ISSUE THREAD

**Issue by moucho** [BookStackApp/BookStack#864]
On file resources/views/search/all.blade.php there are two headers related to search filters that are not "translatable". 

Lines and strings:

69 - "Options"
97 - "Date Options"

Could it be possible to be added to translations so it can be shown on other languages?

**Comment by ssddanbrown** [comment]
@moucho Thanks for reporting and sorry it's taken a while. Forgot to come back to this one for a while. Now done in `master` branch.
