### ISSUE TITLE
Cannot Install on Azure Web App

### ISSUE THREAD

**Issue by garethwarry** [BookStackApp/BookStack#871]
* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.22.0
* PHP Version: 7.2.4 (cli) (built: Mar 28 2018 04:26:56) ( NTS MSVC15 (Visual C++ 2017) x64 )
* MySQL Version: 5.7.9.0

##### Expected Behavior
Be able to connect to the In-App MySQL instance using the correct credentials.

##### Current Behavior
Unable to connect. Always throws the following error (even with the correct settings):

```
[Illuminate\Database\QueryException]                                         

  could not find driver (SQL: select * from information_schema.tables where t
  able_schema = localdb and table_name = migrations)                           

  [PDOException]         
  could not find driver
```

##### Steps to Reproduce
1. Create an Azure Web App with In-App MySQL enabled.
2. Enable php and web sockets in application settings and save.
3. Get the credentials for the Azure Web App through the Kudu console from D:\home\data\mysql\MYSQLCONNSTR_localdb.ini.
4. Enter credentials in .env and setup BootStack. For example: 
```
# Database details
DB_HOST=127.0.0.1:51002
DB_DATABASE=localdb
DB_USERNAME=azure
DB_PASSWORD=6#vWHD_$
```
5. Attempt to install BootStack and get to run `php artisan migrate`

**Comment by TBK** [comment]
If you run this command from the commandline: php -m

do then have the pdo_mysql extension?

**Comment by garethwarry** [comment]
I do not. How do I go about installing them on an Azure Web App? If I try editing php.ini, it says "access is denied". It doesn't look like it allows me to modify it directly from the console.

**Comment by TBK** [comment]
https://docs.microsoft.com/en-us/azure/app-service/web-sites-php-configure

**Comment by garethwarry** [comment]
Ah, thank you. I got it working. My problem was that I redefined a library in the extensions ini they have you add in that guide, and it crashed the website. Thanks for your help!
