### ISSUE TITLE
Upload timeouts after 30s

### ISSUE THREAD

**Issue by l0co** [BookStackApp/BookStack#876]
### For Bug Reports

* BookStack Version `solidnerd/bookstack:0.21.0`

##### Expected Behavior

With these settings setup and shown properly in `phpinfo()`:

```
file_uploads = On
memory_limit = 256M
upload_max_filesize = 256M
post_max_size = 256M
max_execution_time = 600
```

I expect to be able to upload >100MB file.

##### Current Behavior

Upload always gets killed after 30s. I've checked the underlying communication and there's nothing there. I suspect the 30s timeout is built in into the client request.

##### Steps to Reproduce

Try to upload file for which the upload process takes more than 30s.

**Comment by mendiromania** [comment]
+1 thought its just me

**Comment by Abijeet** [comment]
Related: https://stackoverflow.com/questions/46379917/dropzone-js-upload-with-php-failed-after-30-seconds-upload

Marking as a bug.

**Comment by Abijeet** [comment]
@ssddanbrown - I'm able to reproduce this. It seems dropzone has a default timeout of 30s.

Surprising thing is that on timeout, the error callback is not triggered. As per a thread on Gitlab - https://gitlab.com/meno/dropzone/issues/23#note_58283962, the only way to get around this is by registering a callback in the sending event,
```
function handleTimeout(file, xhr, formData) {
    xhr.ontimeout = function (e) {
        alert('Uploading ' + file.name + ' timed out.');
    };
}
```
The other issue is that setting a timeout of 0 is fine, but if the server doesn't respond for a long time, the file upload will be stuck.

I think we should increase the timeout significantly but not set it to 0. What do you think?

**Comment by l0co** [comment]
Sorry, somehow I haven't got the notification about your reply :)

Best option? Probably increasing the timeout to few minutes and giving an option either in the configuration file or in the UI to extend it even more.

Or even better option - to do the above, but even if the timeout is reached, the uploading component shouldn't stop upload, but only should display notification, that "it takes more than assumed - check if everything is OK with your upload".

**Comment by 80sgraf** [comment]
I have the same problem, but I can’t find where to increase the timeout value.
Can anyone point me towards a solution?

**Comment by Abijeet** [comment]
@iondive - You'd have to add a `timeout` parameter in `/BookStack/resources/assets/js/vues/components/dropzone.js`

But you'll have to rebuild the JavaScript files so it might be a better idea for us to fix it and for you to update BookStack.

@ssddanbrown  - Did you get a chance to review my comment here - https://github.com/BookStackApp/BookStack/issues/876#issuecomment-396070803
