### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by jkirkcaldy** [BookStackApp/BookStack#877]
On a fresh install on Ubuntu 16.04 LTS I can't access the bookstack index page or any page for that matter. I installed using the Manual instructions on the Bookstack website. 

Server: Ubuntu 16.04 LTS
Web Server: Apache
Apache Config:

```
<VirtualHost *:80>

    ServerName wiki.example.com
    ServerAlias wiki.example.com
	DocumentRoot /var/www/BookStack/public
    <Directory /var/www/BookStack/public>  
		AllowOverride All             
		Order allow,deny             
		Allow from all             
	</Directory>
    
    Options +FollowSymLinks
		RewriteEngine On

		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteRule ^ index.php [L]


</VirtualHost>
```
I have been back through the dependencies and I definitely have them all installed. But whenever I go to web page I get a 400 Bad request error. 

I checked the error logs in apache and all I get is this:
[error.log](https://github.com/BookStackApp/BookStack/files/2072652/error.log)

I have double checked permissions and the directories: storage bootstrap/cache and public are all owned by the webserver.

**Comment by mendiromania** [comment]
not project related 😟

**Comment by Abijeet** [comment]
Hi @jkirkcaldy 

Sorry to hear that you are having trouble.

There are a bunch of SIGTERM's in the error log, I'm assuming these were just restarts. Are you able to run normal PHP file on the server?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
