### ISSUE TITLE
Icons stretched across screen, design broken

### ISSUE THREAD

**Issue by Caddy14d** [BookStackApp/BookStack#879]
BookStack Version: Latest as of 07.06.2018
PHP Version: 7.0
MySQL Version: unknown, rather new version

I installed Bookstack manually on a shared host.

According to them, it should work. I installed bookstack without errors but... all Icons are stretched huge and the becames very long.

Does anyone have an idea what could cause this?

**Comment by ssddanbrown** [comment]
Hi @Caddy14d,

I'm guessing you might have installed the master branch code instead of the release code?
Is there a `public/dist` folder with files in it?

**Comment by Caddy14d** [comment]
No, there is no such folder and yes, I used the master branch.

Just reinstalled using the release branch and it works.
Thank you very much for your very quick help!
