### ISSUE TITLE
Problem with List in PDF export

### ISSUE THREAD

**Issue by iBooster** [BookStackApp/BookStack#891]
### Bug Report

* BookStack Version: BookStack v0.22.0
* PHP Version: 7.0.30 by OS vendor
* MySQL Version: I don't know, but i think this is irrelevant

Whenever i export an HTML List (in this case "ol") to **PDF**, the number besides the text goes a bit more up from li to li... that is going worse, if the list is long, the longer the list, the wider the space between expected position and actual position.

Screenshot: http://picul.de/Qd2

##### Expected Behavior
should just list in one line

##### Current Behavior
list number goes a bit up, from li to li a bit more in PDF

##### Steps to Reproduce
Just export an long UL or OL as an PDF.

**Comment by tdkl** [comment]
Did you try with [wkthmltopdf](https://www.bookstackapp.com/docs/admin/pdf-rendering/)?

**Comment by alexmannuk** [comment]
Listing appears to function correctly in v0.29.3, can probably be closed

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since list styles have since changed and things appeared to be working from a quick test on our demo instance.
