### ISSUE TITLE
php files in config directory?

### ISSUE THREAD

**Issue by Logoth** [BookStackApp/BookStack#893]
* BookStack Version *(Found in settings, Please don't put 'latest')*: v0.22.0
* PHP Version:  
* MySQL Version: 5.7.21 (i think)

Not really a bug, but I didn't see a discussion forum to ask this on, I was looking for a way to use other mail hosts and just poking around, and saw there's a bunch of php files in the config directory (mail.php, auth.php, etc). Are we supposed to use these, or are they internal items that pull from the .env file?

**Comment by iBooster** [comment]
i already asked myself the same. An answer would be nice

**Comment by ssddanbrown** [comment]
@Logoth These are internal files used by BookStack thats pull from the `.env` (or from environment variables). Any edits to these are not supported and may be overwritten upon update. 

Technically these are the way to configure Laravel (The framework BookStack uses) so they do provide additional options but many of these require additional dependencies.

Hopefully that answers the question so I'll close this. If it does not let me know and I'll re-open this.
