### ISSUE TITLE
Custom Code before </body>

### ISSUE THREAD

**Issue by iBooster** [BookStackApp/BookStack#894]
### For Feature Requests

Desired Feature:
I would love to have the option to put custom code right before `</body>` ... just like it is now with the custom header code.

Would that be possible ?

**Comment by TBK** [comment]
https://laravel.com/docs/5.5/blade#extending-a-layout
https://laravel.com/docs/5.5/blade#introduction

**Comment by ssddanbrown** [comment]
Currently, You could use JavaScript within the custom head content to dynamically insert content in the footer on run code once the page has loaded. 

In the future this will be directly possible via Custom Views/Themes (#652). Technically already possible but undocumented (In progress still) and you'd need to override the whole base view. Infor in the issue link above but can provide more details if you want to explore this approach though it is unstable.

**Comment by ssddanbrown** [comment]
I've allocated this to the next release as a reminder to add empty body-start and body-end partial templates within our base templates for easier overriding.
