### ISSUE TITLE
Click Browser Back and Forward button while editing a page -> page preview and page content mismatch

### ISSUE THREAD

**Issue by est-seb** [BookStackApp/BookStack#895]
### Bug Report

* BookStack Version: v0.22.0
* PHP Version: 7.1
* MySQL Version: the one used by v0.22.0 docker image

##### Expected Behavior
Click Back and Forward while editing a page and then click save, page preview and page content are matching and I can find back the latest content I was editing.

##### Current Behavior
Click Back and Forward while editing a page and then click save, page preview and page content mismatch. The content I lastly added is present in the preview but disappeear when I edit the page.

##### Steps to Reproduce
Edit a page, add some content.
Click Back and Forward while editing the page and then click save.
Now you should see the page preview containing your last changes.
Click on Edit.
The page does not contain the last edit.

**Comment by ssddanbrown** [comment]
Thanks for raising @est-seb.
I believe this should have been addressed as part of caching changes within 41ac69adb1a4c50dc3a9341a4391969befba3e9e. From my own testing this does seem to be the case so I'll therefore close this off but if any issues in this scenario are experienced using BookStack v21.08.5 or greater this can be re-opened and looked into deeper.
