### ISSUE TITLE
Books as Home

### ISSUE THREAD

**Issue by SamB-GB** [BookStackApp/BookStack#896]
Is it possible to have the /books page as the homepage, I would like our staff to be taken straight to that URL once they login.

**Comment by Abijeet** [comment]
Hi @SamB-GB 

This is already possible. Please go to the settings screen and under Application Homepage set "select the books page as your homepage" as true.

Bottom right of the screenshot below.

![screenshot from 2018-06-19 23-34-46](https://user-images.githubusercontent.com/1685517/41615683-88b9d5ac-7419-11e8-88a1-06ca7c5990ec.png)

**Comment by SamB-GB** [comment]
Not possible to select just /books instead have to select a books page.

**Comment by Abijeet** [comment]
@SamB-GB - Please select the checkbox shown in the screenshot below,

![41615683 88b9d5ac 7419 11e8 88a1 06ca7c5990ec png png image 692 x 812 pixels](https://user-images.githubusercontent.com/1685517/41636920-c917e2c4-746e-11e8-885f-733b4383bd24.png)
