### ISSUE TITLE
Search terms ignored

### ISSUE THREAD

**Issue by BenjaminLange** [BookStackApp/BookStack#898]
### For Feature Requests

Desired Feature:

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.22.0
* PHP Version: 7.0.30
* MySQL Version: MariaDB 10.0.34

##### Expected Behavior
Searching using terms such as new employee should return results with the page "New Employee" at the top.

##### Current Behavior
The search results contain every page in the database. They appear to be sorted only by creation date and ignore all search terms.

##### Steps to Reproduce
Search using any terms.

**Comment by ssddanbrown** [comment]
Hi @BenjaminLange,
Are you able to re-produce this on the demo site at all (https://demo.bookstackapp.com/login?email=admin@example.com&password=password)?

Expected results should contain at least one of your search terms. Is `New Employee` your exact search term you can re-produce this issue on and does that include quotes?

**Comment by BenjaminLange** [comment]
@ssddanbrown, it seems to be working fine on the demo site, so this may be an issue with my sepcific configuration.

I get the same results if I search with quotes or without quotes. Do you have any tips on where to start with troubleshooting?

**Comment by aidanfindlater** [comment]
@BenjaminLange did you ever get this worked out? I'm having a similar issue, on BookStack v0.26.4, mariadb 10.3.15, php 7.3.

**Comment by BenjaminLange** [comment]
Hi @aidanfindlater, unfortunately, I never found a solution. Other requirements caused me to move to another tool.

**Comment by aidanfindlater** [comment]
Figure it out, for me at least. I had misconfigured nginx. I just had to make sure that the try_files command was exactly as described in the documents ("try_files $uri $uri/ /index.php?$query_string;") and all works as expected.

**Comment by ssddanbrown** [comment]
Since the original poster has moved to another tool, And since other solutions have been discussed, I'll go ahead and close this.
