### ISSUE TITLE
order books, chapters and pages ? (give a position ?)

### ISSUE THREAD

**Issue by Guims** [BookStackApp/BookStack#899]
Hello,

it would be nice to be able to give a position in the book, chapters and pages view of BookStack, currently the view is in alphabetical order

Thank you in advance for your answer

**Comment by Abijeet** [comment]
Hi @Guims,

I believe this is already possible. Please see the gif below,

![book-order](https://user-images.githubusercontent.com/1685517/42120901-24d4dc96-7c41-11e8-8379-af7ca62f9856.gif)

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Guims.

As Abijeet has shown above, content within a book can already be sorted. 
For improving this sort and, adding Book sort options, are already open under issues #519 and #180 therefore I will close this request.
