### ISSUE TITLE
is there ayway to export whole book and import from another site ?

### ISSUE THREAD

**Issue by changchichung** [BookStackApp/BookStack#900]
### For Feature Requests

Desired Feature: system integrated backup/Restore

I write some books using BookStackApp , but the host machine have no internet access. so I build a VPS in vultr.com and I want to export all books to  bookstackapp in the VPS . I search the issues and find out there`s a "backup and restore" using mysqldump and tar. But I cant run the mysqldump because I cant login to the old host machine( for security they said).
so , I`m wondering is there anyway to backup and restore from the BookStackApp admin console or what ? that will be more convenience.

**Comment by Shackelford-Arden** [comment]
@changchichung If you're unable to complete the [documentation provided](https://www.bookstackapp.com/docs/admin/backup-restore/) then you might be out of luck.

Would you have the option of exporting each book via the UI? This was added in a recent release. It's not pretty but you'd at least have the content. When you're on the page for a given book, there's an export option (so long as you're on a recent release of Bookstack, I can't find which version you actually need):

![image](https://user-images.githubusercontent.com/7362263/41858302-2516344c-785f-11e8-9924-f8d6093ba549.png)


Looking around, they're looking at adding the functionality to backup from the UI (which would then allow you to import on another machine. See #723 for more information.

**Comment by lommes** [comment]
Do you have any other access to the old host? FTP or anything? You could use phpmyadmin or adminer to backup the whole database (files/uploads not included). 

Depending on the provider they will create a dump for you if they disallow you the login to do it yourself.

**Comment by Shackelford-Arden** [comment]
Ooh good points @lommes I didn't think about that.

I'll keep my fingers crossed for you @changchichung !

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
