### ISSUE TITLE
Telegram as Third Party Authentication 

### ISSUE THREAD

**Issue by Ampsicora** [BookStackApp/BookStack#901]
Would be cool and useful have telegram as third party authentication. 

Official article: 
https://telegram.org/blog/login 

In this article you can find more technical info and links.

**Comment by lommes** [comment]
Sadly telegram does not use OAuth which will make it much more complicated to implement, see also https://github.com/SocialiteProviders/Providers/issues/142

**Comment by Ampsicora** [comment]
I hope will be implemented even if is complicated, could be make the difference in future

**Comment by lifepeer** [comment]
Could this help? https://telepass.me
