### ISSUE TITLE
Scrolling with longer side navigation causes rubber-banding

### ISSUE THREAD

**Issue by garethwarry** [BookStackApp/BookStack#905]
##### Versions
* BookStack Version: v0.22.0-release
* PHP Version: v7.2.6-nts
* MySQL Version: v8.0.11-community

##### Expected Behavior

For a page with no scrollable content and a long book navigation that causes scrolling for the page, the user should be able to scroll to the bottom of the page and view the rest of the book navigation panel in the side menu.

##### Current Behavior

Attempting to scroll causes rubber-banding, where the user is taken back to the top of the page. As the user attempts to scroll, it keeps glitching them up back to the top of the page, causing the website to shutter / rubber-band violently. On smaller screens, the book navigation will be cut.

##### Steps to Reproduce

1. Create a new page in a chapter with many pages added.
2. Edit the page to display a limited amount of content (that would not scroll otherwise). I added 3 subheaders to mine.
3. Attempt to scroll, with the book navigation section requiring scrolling.

**Comment by aljawaid** [comment]
I have this issue too on 0.22 but couldn't figure out what the problem was.  Thanks for explaining it better.  Hopefully it might be resolved in 0.23

**Comment by aljawaid** [comment]
same issue exists in 0.23

**Comment by fmaytain** [comment]
Same issue here

**Comment by vmarlier** [comment]
Same here with v0.22.0

**Comment by aljawaid** [comment]
This is a growing problem for short pages :(

**Comment by garethwarry** [comment]
Replicated on Chrome and Firefox on Windows 10. Larger side navigation pane that scrolls off page for a small content page causes violent rubber banding.

**Comment by Kdecherf** [comment]
Same here, Linux (Exherbo) running 61.0.1. BookStack 0.23.2.

If the dynamically fixed sidebar is not a top feature for you, here is a workaround which will disable the separate scroll. Add the following block in the _Custom HTML head content_ textbox:

``` javascript
<script type="text/javascript">
window.onload = function() {
document.querySelector('#sidebar .scroll-body').classList.remove('scroll-body');
};
</script>
```

**Comment by ssddanbrown** [comment]
I have been able to re-produce this effect when the sidebar content is expanded after load. Have added a fix for that although ideally the general layout needs to be rebuilt for a full fix. 
Hopefully may fix this issue also but won't close this in-case it's something else.

**Comment by ssddanbrown** [comment]
Can anyone confirm if they still experience this issue on the latest BookStack version? If not I will assume this is fixed

**Comment by ssddanbrown** [comment]
As above, Assuming this is now fixed.
