### ISSUE TITLE
Feature Requests : Add/Remove codes in code block

### ISSUE THREAD

**Issue by Nico207** [BookStackApp/BookStack#910]
#### Desired Feature:

Adding or removing codes from the list displayed in "Code Block"

---
Hi,
it would be really nice to have the choice of the codes displayed in the "Code Block" layout.
Maybe it's already possible (in this case sorry for this request), but I haven't found how...

Thanks !

**Comment by lommes** [comment]
I'm not sure if a fully understand your request, but it might be duplicate of #844

**Comment by Nico207** [comment]
Yes, you understood my request, and sorry for the duplicate (and for my rough English)

**Comment by lommes** [comment]
Ok, no problem!

I will close this issue and we will keep track of this request in #844
