### ISSUE TITLE
Feature request: Hide sidebar on startpage.

### ISSUE THREAD

**Issue by tmikaeld** [BookStackApp/BookStack#913]
It happens often that a client find a page they shouldn't be on, that other client's should be on - due to recent activity and recently updated pages are visible on the startpage.

An option to disable this is deeply appreciated!

**Comment by aljawaid** [comment]
It would be nice to have one of the below:

- a toggle button to expand the sidebar.  Save which state it is left in.
- show sidebar on page load but then auto hide (to a button) to save screen space

**Comment by ssddanbrown** [comment]
This has had relatively minimal request over the years, and I don't want to go down the path of controls for every UI element, but we instead now have the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) which can facilitate override and customization of any view, so I'll therefore close this off.
