### ISSUE TITLE
Setting to disable normal registration with social auth enabled

### ISSUE THREAD

**Issue by MacChuck** [BookStackApp/BookStack#915]
### For Feature Requests

I believe this falls under feature requests, and it seems to ALMOST already work.
I just set our wiki up, enabled Azure AD authentication. I realized that I still had to email verification because otherwise, even though Azure AD restricts who can register (which auto-creates an account) or login, anyone could still register with a different domain using the standard login. (I was trying to avoid setting up sending email)

Desired Feature:
An admin/config setting with social logins enabled, registration enabled (those two already work together), to also disable standard registrations so email sending doesn't need setup if wanting to restrict access.

**Comment by nappe** [comment]
This is available as a setting in the .env `{SERVICE}_AUTO_CONFIRM_EMAIL=true`

https://www.bookstackapp.com/docs/admin/third-party-auth/#Automatic%20Registration%20&%20Email%20Confirmation

**Comment by ssddanbrown** [comment]
Closing this in favour of #1090 since that issue would achieve the same and has had more extensive discussion. 
Thanks @MacChuck for your original suggestion.
