### ISSUE TITLE
Integrate Google Docs

### ISSUE THREAD

**Issue by karneaud** [BookStackApp/BookStack#916]
### For Feature Requests

Can Google Docs be integrated into Book Stack? I want to be able to upload and convert documents for editing to be further exported back into PDF or what not. Can this happen? Not seeing anything about modular plugin development or the likes of

**Comment by ssddanbrown** [comment]
Hi @karneaud, Thank you for raising this request.

I think native google-docs integration is out-of-scope for this project at this stage. It would be a large component to maintain and there is a big overlap of the features and abilities of those two systems. Therefore I'm going to close this request. Apologies as I imagine this was not the response you were hoping for.

API and UI customization are on the roadmap so perhaps such an integration could be built externally in the future.
