### ISSUE TITLE
Export PDF file with Image not found or type unknown

### ISSUE THREAD

**Issue by sovankiry** [BookStackApp/BookStack#920]
### For Feature Requests

Desired Feature:

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: BookStack v0.22.0 
* PHP Version:
* MySQL Version:

##### Expected Behavior
Images must show as view.

##### Steps to Reproduce
1. Export with pdf
2. PDF File 

### Content in Web
![screenshot-2018-07-11-18-04-00](https://user-images.githubusercontent.com/35448386/42567800-2bb4f170-8535-11e8-8212-00d9463e64b2.png)

### Content in PDF file after export
![screenshot from 2018-07-11 18-07-47](https://user-images.githubusercontent.com/35448386/42567863-648c4e94-8535-11e8-8893-90dda87dba2d.png)

**Comment by rimsovankiry** [comment]
Dear @ssddanbrown,
Regard to your question, We've installed by docker container and we do not change any default configuration.

**Comment by h0cin** [comment]
I had almost the same issue  (excluding the square that are shown), same message "Image not found or type unknown" as the base64 was malformed (empty), the name of the picture appeared on the PDF but no image itself.

I'm using a docker container, with  BookStack v0.21.0, SSL with a valid fqdn certificate and
jwilder/nginx-proxy in front of it using a VIRTUAL_HOSTNAME=fqdn variable.

Solved the issue by setting on .env the APP_URL to the complete  BookStack APP URL
used in the VIRTUAL_HOSTNAME Variable of the nginx-proxy like this:

APP_URL=https://fqdn

This fixed both issues with images not showing in the "Contained Web File" and the "PDF File" section.

Thank you for this awesome piece of software!

**Comment by rimsovankiry** [comment]
Thank you @h0cin Let's me try with your solution.

**Comment by rimsovankiry** [comment]
Could you tell me the path of file .env? @h0cin

**Comment by h0cin** [comment]
I'm using docker.io/solidnerd/bookstack:0.21.0 and the .env file is located on:
/var/www/bookstack/.evn

**Comment by XizzoR** [comment]
Hello!

I've made changes as @h0cin suggested, because I got same issue as @rimsovankiry
It fixes this bug in "Contained Web File" export type, but not in PDF. I am not using jwilder/nginx-proxy, so I can't apply VIRTUAL_HOSTNAME variable per-se (I believe thats the "server_name" in "server" block), but I applied my fqdn to APP_URL in .env, which is also written in "server_name" in my config from /etc/nginx/sites-available/

**Comment by chasgames** [comment]
We had the same bug for drawings, but a different reason, we had a user with an apostrophe ` in their name. Once that symbol was removed and the drawing then is re-edited to update the image URL, all is well.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
