### ISSUE TITLE
New line without new paragraph?

### ISSUE THREAD

**Issue by Logoth** [BookStackApp/BookStack#923]
Is there a shortcut to create a new line that doesn't create a new paragraph in the HTML editor? Alt-Return is what I would usually expect.

If I type out something like the following there is a new paragraph between each line.
A
B
C

If I copy and paste from a text document the same thing, it formats properly with `<br/>` in the code instead of `<p>`

**Comment by Abijeet** [comment]
Hi Logoth,

Maybe you are looking for `Shift + Enter`

**Comment by Logoth** [comment]
Yep! I think I tried everything except Shift. Thank you!

**Comment by rajeshisnepali** [comment]
Any way to do without `Shift`?

**Comment by ssddanbrown** [comment]
@rajeshisnepali No, nothing built-in as far as I'm aware to allow for that.
