### ISSUE TITLE
Markdown - Linebreaks

### ISSUE THREAD

**Issue by EorlBruder** [BookStackApp/BookStack#928]
Currently the Markdown-Editor only inserts a line break (with a certain spacing) if I have an empty line (aka two linebreaks) between the lines. 
I am generally used to a single linbreak making a simple linebreak and a second linebreak leaving an empty line. (I think this is a difference between github-style markdown and plain-markdown). Would it be possible to maybe choose another style of markdown or generally adopt github-style-markdown?

**Comment by enyosolutions** [comment]
up on this one. I'm also very interested in this feature.

**Comment by tsacks** [comment]
This is a bit old of a bug to resurrect, but I was able to fix this on my local install by modifying one line of code. I'll try to submit a PR here soon.

But, until then, you can edit the file resources/js/components/markdown-editor.js and change line 17 from ```this.markdown = new MarkdownIt({html: true});``` to ```this.markdown = new MarkdownIt({html: true, breaks: true});```, then just run ```npm run production``` and it'll have webpack rebuild the js files.

**Comment by tsacks** [comment]
With the events in the custom HTML head option, you can now add the following to your Custom HTML head content setting to do the same thing, and you don't have to recompile BookStack every update.

```
<script>
  window.addEventListener('editor-markdown::setup', event => {
    event.detail.markdownIt.set({breaks: true});
  });
</script>
```

**Comment by ssddanbrown** [comment]
Thank you @tsacks for providing an easy-to-use solution via our editor hooks.

In the core project we generally align with the commonmark standard but the editor events were implemented for exactly this kind of customisation. Therefore I'll close this off.
