### ISSUE TITLE
Centos 7+PHP 7.1. When run "composer install" warning ext-tidy missing

### ISSUE THREAD

**Issue by soutou233** [BookStackApp/BookStack#930]
### For Feature Requests

Desired Feature:

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: 0.22.0
* PHP Version: 7.1
* MySQL Version: 

##### Current Behavior

Just follow the document's step until "composer install"

PHP 7.1 already include tidy module, no ideas that why the composer warning that

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-tidy * is missing from your system. Install or enable PHP's tidy extension.
  Problem 2
    - Installation request for gathercontent/htmldiff 0.2.1 -> satisfiable by gathercontent/htmldiff[0.2.1].
    - gathercontent/htmldiff 0.2.1 requires ext-tidy * -> the requested PHP extension tidy is missing from your system.
`

**Comment by lommes** [comment]
Is the module enabled?

**Comment by soutou233** [comment]
Thanks for your reply. I deal with it now
