### ISSUE TITLE
Windows AD Authentication

### ISSUE THREAD

**Issue by FelisWei** [BookStackApp/BookStack#931]
##### For Bug Reports
Windows AD：Server 2012
 BookStack Version：v0.22.0
 PHP Version: 7.2.7 ubuntu 18.04.2
 MySQL Version:5.7.22

##### Expected Behavior

Logging in with windows AD credentials

##### Current Behavior

ErrorException (E_WARNING)
ldap_bind(): Unable to bind to server: Invalid credentials

##### LDAP settings

```
AUTH_METHOD=ldap
LDAP_SERVER=ip:389
LDAP_BASE_DN=DC=xxx-xxx,DC=com
LDAP_DN=cn=1234,DC=xxx-xxx,DC=com
LDAP_PASS=xxxxxx
LDAP_USER_FILTER=(&(sAMAccountName=${user}))
LDAP_VERSION=3
LDAP_EMAIL_ATTRIBUTE=mail

```
![bookstack_20180719_095749](https://user-images.githubusercontent.com/22385478/42917073-90653188-8b3a-11e8-9644-7d59a7be2848.jpg)

**Comment by NK74** [comment]
Hi !

Have you try your user password first ?
`ldapsearch -xLL -b DC=yourdomain,DC=local -h dc1.yourdomain.local-D username@yourdomain.local -W`

**Comment by NK74** [comment]
Hi Felis,

You have your reason here....

First, can you ping your ldap IP ? 

- No, your ldap isn't available

- Yes, Retry to fix your credentials

In my last reply, this command prompt is to try if you can connect to your LDAP
> Have you try your user password first ?
ldapsearch -xLL -b DC=yourdomain,DC=local -h dc1.yourdomain.local-D username@yourdomain.local -W

**Comment by NK74** [comment]
Felis,

Maybe OU Name yes ... Can you send a dummy example of your command prompt

**Comment by NK74** [comment]
Hey Felis,

In .env file take care of this line

`# General auth`
`AUTH_METHOD=ldap`

`# LDAP Settings`
`LDAP_SERVER=false`
`LDAP_BASE_DN=false`
`LDAP_DN=false`
`LDAP_PASS=false`
`LDAP_USER_FILTER=false`
`LDAP_VERSION=false`
`# Do you want to sync LDAP groups to BookStack roles for a user`
`LDAP_USER_TO_GROUPS=false`
`# What is the LDAP attribute for group memberships`
`LDAP_GROUP_ATTRIBUTE="memberOf"`
`# Would you like to remove users from roles on BookStack if they do not match on LDAP`
`# If false, the ldap groups-roles sync will only add users to roles`
`LDAP_REMOVE_FROM_GROUPS=false`

You can find on github the 
[**.env.example**](https://github.com/BookStackApp/BookStack/blob/master/.env.example)


And use APP_DEBUG=true to find error quickly

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please comment and this can be reopened if required.
