### ISSUE TITLE
Subscribe to page change via Email

### ISSUE THREAD

**Issue by atom-wintermute** [BookStackApp/BookStack#935]
Could you add an email notification of the changes in the articles? If possible, with the ability to subscribe on them.

**Comment by atom-wintermute** [comment]
In general, this issue about the integration of the web-hook integation, but in the discussion the email notification also mentioned. Therefore, yes, it is covered by #147.

This is a rather old issue, are there any plans for its implementation?

**Comment by cornernote** [comment]
I'd also like to see this built into the core features.  For now you can achieve it with a theme plugin like this - https://gist.github.com/cornernote/23f970210577d9c25dd906bcc5c53891

**Comment by rseffner** [comment]
> I'd also like to see this built into the core features. For now you can achieve it with a theme plugin like this - https://gist.github.com/cornernote/23f970210577d9c25dd906bcc5c53891

Can't get this working under 22.11 and 23.01. Every action using BookStack is commented with "An unknown error occurred" until I remove/rename themes/custom/function.php.

**Comment by ssddanbrown** [comment]
Haven't tested these on the latest release, but here's a couple of similar scripts that I've put together.
These are unsupported customizations and there are notes to consider on each:

- [Email page updates based upon favourite pages](https://gist.github.com/ssddanbrown/f14f7a5b0ab190899b6bd84ba9731f36)
- [Email page updates based on roles tagged on parent book](https://gist.github.com/ssddanbrown/800c762ef53b26700ace2416f3cf0697)

**Comment by rseffner** [comment]
Thanks. I now tried the second one because it allows to control notification a bit.
It throws no errors but it also sends no mail.
I set the tag "notify" (without value) to a book, changed it and got no mail to changing user and another with editor rights.

**Comment by rseffner** [comment]
Same with "Email page updates based upon favourite pages" - no mail. Mail system is working, testing from bookstack is ok.

**Comment by cornernote** [comment]
@rseffner, apologies for the errors, it would seem I missed the important step of adding the namespace to `composer.json`.  I have updated the guide.

**Comment by ssddanbrown** [comment]
Since page update notifications were [added in v23.08](https://www.bookstackapp.com/blog/bookstack-release-v23-08/#content-notification-system), I'll go ahead and close this one off.

**Comment by rseffner** [comment]
That's not the same. With the previous hack, the creator of an article could ensure that certain users/groups were informed about article changes (push). With the now built-in function, only the user can decide whether and for which items he would like to receive notifications (pull).
We use bookstack as a wiki and would like to actively notify users in certain areas.

**Comment by ssddanbrown** [comment]
@rseffner Sure, but this issue was originally just for the core ability to have page update notifications you can opt-into, which was met by that release.

You already have #4514 open with the request for pushing preferences, so there's no use to re-open this issue for that also.
