### ISSUE TITLE
Markdown editor input chinese newline ,messy code

### ISSUE THREAD

**Issue by nicolasmeng** [BookStackApp/BookStack#938]
like this
![image-1532422973855](https://user-images.githubusercontent.com/4972409/43128121-bb9c2406-8f63-11e8-815c-b87e6b82aaca.png)

**Comment by nicolasmeng** [comment]
the editor page is utf8 code
![_20180724170829](https://user-images.githubusercontent.com/4972409/43128324-4bf54dca-8f64-11e8-878c-3863c19f18df.png)

**Comment by nicolasmeng** [comment]
copy the messy code to here like this:
�

**Comment by nicolasmeng** [comment]
which file I should check?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
