### ISSUE TITLE
Add option to force default language for public users

### ISSUE THREAD

**Issue by vasiliev123** [BookStackApp/BookStack#944]
After adding APP_LANG to the .env file, only the language for logged in user changes and not for the whole site.

1. Add **APP_LANG=pl** to the .env file
2. Log in as admin@admin.com
3. Set **Allow public viewing?** to yes
4. Log out
5. Homepage is still in english

**Expected behavior**
Whole site should change language to the polish/french/german etc..

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.23
 - PHP Version: 7.2
 - Using Docker or reverse proxy (Yes/No): No

**Comment by ssddanbrown** [comment]
Hi @vasiliev123,

Setting the `APP_LANG` Parameter provides a fallback for all users and a default for logged-in users.

For logged-out users, BookStack will try to identify their preferred language via headers sent by the browser (Most browsers have option to set languages) before falling back on the `APP_LANG` value.

**Comment by vasiliev123** [comment]
Thanks Dan for the answer :) so currently there is no way to force it? My whole site will be in polish so there is no need to use english anywhere.

**Comment by ssddanbrown** [comment]
@vasiliev123 Not at the moment but I can see your use case.

I'll update this issue to be requesting an option to force the language for public users.
Since this will be fairly simple to implement I'll mark this for the next release.

**Comment by vasiliev123** [comment]
@ssddanbrown Thank you!

**Comment by ssddanbrown** [comment]
Will be in the patch release going out today. You'll be able to set `APP_AUTO_LANG_PUBLIC=false` in your `.env` file to force a language for public users.

**Comment by juanmacuevas** [comment]
Thanks for this!
