### ISSUE TITLE
Internal server error after upgrade from v0.18 to 0.23

### ISSUE THREAD

**Issue by haynes11** [BookStackApp/BookStack#946]
**Describe the bug**
Upgraded to latest version (Albeit as a root user so permissions may be incorrect in terms of group but I have reset and they look normal. Internal server error

**Steps To Reproduce**

Upgrade to v 0.19 and after the upgrade completed I have an internal server error page. Nothing in the log file.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.18 > v0.23 (Latest > Just followed update page as documented on your website)
 - PHP Version: PHP 7
 - Using Docker or reverse proxy (Yes/No): No

**Additional context**

This could be a file permissions problem/owner problem as I ran the upgrade as a different user. I have pretty much ruled this out though and it only happened after the upgrade

**Comment by ssddanbrown** [comment]
Hi @haynes11,
If you're seeing a plain 'Internal Server Error' then the error will likely be shown in your server's error logs.
Depending on OS, These are commonly found at `/var/log/(apache2 or nignx)/error.log`. Check the latest lines (`tail -n 50 error.log`) to see if there's an error in there when you try to access your instance.

**Comment by haynes11** [comment]
Hi @ssddanbrown 6AM after being up all night I really wasn't thinking clearly, so thank you for pointing that out! Now resolved! :)
