### ISSUE TITLE
Can we custom a page with books?

### ISSUE THREAD

**Issue by cuteSakuraHime** [BookStackApp/BookStack#949]
First of all, We want a page which let user see different books. 

We find we can set /books as homepage. That's great. 

We want to make the page like this.

Before login,

![image](https://user-images.githubusercontent.com/10474077/43701476-dfab1418-9988-11e8-8095-9e97f2bc40a5.png)

We can only see this public book.

After login,

![image](https://user-images.githubusercontent.com/10474077/43701571-4477ec4a-9989-11e8-8173-80a50af3ef8b.png)

We can see two private books.

The feature will let user see better.

And also, use the tag to distinguish different books will let bookstack easier to find what they need.

**Comment by ssddanbrown** [comment]
Hi @Xuchenhao, Really sorry for my late reply.
You should already be able to do this by setting custom permissions on your Books as per this gif:

![BookStack set book permissions](https://user-images.githubusercontent.com/8343178/45692171-10e5ad00-bb52-11e8-99b0-9a673808a865.gif)

Simply give 'view' permissions to everyone but the 'public' role and the book, along with everything inside it, will be hidden for non-logged-in users.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If you feel there is still something that needs to be addressed please comment and this can be reopened if required.
