### ISSUE TITLE
Direct Link Popup doesn't work when APP_DEBUG is Enabled

### ISSUE THREAD

**Issue by gareththered** [BookStackApp/BookStack#950]
**Describe the bug**
Direct-link popup doesn't work when Debug is enabled in `.env` file.

**Steps To Reproduce**
1. Edit `.env`
2. Set `APP_DEBUG=true`
3. Re-load a page
4. Select text

**Expected behavior**
A popup with the URL to the page or selection should appear.

**Actual behaviour**
No popup

**Your Configuration (please complete the following information):**
 - 0.23:
 - PHP Version: 7.0.27.9+deb9u1
 - Using Docker or reverse proxy (Yes/No): Yes (Nginx rev proxy)

**Additional context**
More of a documentation bug maybe?  A comment added before the `APP_DEBUG` line in the `.env` file to the effect that it breaks the popup might suffice?  I was scratching my head for a while, before I remembered I'd set the debug option to help get `wkhtmltopdf` working.

**Comment by ssddanbrown** [comment]
@gareththered Thanks for reporting this issue but I am not able to re-produce this bug.

When setting `APP_DEBUG=true` the popup still shows as expected. Tested on Ubuntu 18.04, chrome & firefox. 

Can you confirm your browser and OS?

**Comment by gareththered** [comment]
I'm running Windows 10.  After a little digging around, it seems this only happens on the Chrome browser.  Edge/IE and Firefox work fine.

**Comment by gareththered** [comment]
It seems that Incognito mode does work.  So does normal mode with all extensions disabled.  However, trying to narrow down which extension using split-half brings inconsistent results.  At least we know its a browser extension issue.
