### ISSUE TITLE
Images gallery upload not found

### ISSUE THREAD

**Issue by jeanders** [BookStackApp/BookStack#954]
I get an error "images/gallery/upload" not found when I try to upload images to a page in BookStack.
Screenshot below. 

Centos 7 / Apache webserver.

Attachment uploads work fine, it is only image uploads. I don't see this directory existing anywhere under public, but I'm not sure if that's expected. All directories are owned by the apache user and are 755.
<img width="338" alt="screen shot 2018-08-08 at 8 15 04 am" src="https://user-images.githubusercontent.com/16355500/43839627-2d1fee9c-9ae4-11e8-8351-e1fc5501748a.png">

**Comment by ssddanbrown** [comment]
Hi @jeanders, Are you using a reverse proxy or are you hosting BookStack on a sub-path of a domain at all? (eg. `http://example.com/docs`)

**Comment by jeanders** [comment]
@ssddanbrown I was wondering if this may be an issue on my side related to something similar. This is a shared apache server, this vhost doesn't have reverse proxy but others do.

**Comment by jeanders** [comment]
Below is my apache config:

<VirtualHost *:80>
    ServerName bookstack.example.com

    DocumentRoot /var/www/bookstack/public

    <Directory /var/www/bookstack/public>
        Options -Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Order allow,deny
        Allow from all
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ /index.php [L]
    </Directory>
</VirtualHost>

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
