### ISSUE TITLE
Can bookstack be used without virtualhost?

### ISSUE THREAD

**Issue by Vicvinegar0** [BookStackApp/BookStack#958]
So the documentation and any guides I see for this use a virtualhost on the web server to access bookstack. However I don't want bookstack to be the root site on the web server nor do I want to have to use a port other than 80.
Can I not set this up on apache to be access via just http://server/bookstack ?

**Comment by lostdesign** [comment]
You cannot host any app on apache without using vhosts - i think you did not understand it's purpose.

A vhost is to resolve the users request and load the right site given by that configuration. The same is with your `/bookstack` - that is an alias and simply one line you need to add to your vhost config.

Furthermore you should not run any app on HTTP anymore which includes a login - 443/https is the way to go.

```
<VirtualHost *:443> 
    ServerName example.com
    DocumentRoot /var/www/bookstack

    # either one of these two alias
    Alias /bookstack
    Alias /bookstack "/var/www/bookstack     

    <Directory "/var/www/bookstack">
        Options None
        AllowOverride None
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```

**Comment by Vicvinegar0** [comment]
Many PHP web apps/sites can be used just via Directory directives without VirtualHosts, that's what I was after, since that fits my situation better. Thanks though
