### ISSUE TITLE
Unable to escape Blockquotes

### ISSUE THREAD

**Issue by Vicvinegar0** [BookStackApp/BookStack#961]
**Describe the bug**
Cannot escape a Blockquote when editing if there are no characters/lines below the blockquote.

**Steps To Reproduce**
Edit a new page, click Format > Blockquote, type something. Try to escape the blockquote when done

**Expected behavior**
Be able to escape the blockquote when complete to move on in the document

**Your Configuration (please complete the following information):**
Installed using the Ubuntu 18.04 script

**Comment by ssddanbrown** [comment]
Thanks for reporting @Vicvinegar0. Was actually quite a simple fix, Just needed to configure the editor a little. As of next release you'll escape the blockquote after Pressing enter on an empty line (Press enter twice).
