### ISSUE TITLE
Collapse element with text

### ISSUE THREAD

**Issue by nekromoff** [BookStackApp/BookStack#962]
**Describe the feature you'd like**
Something like this - a collapse block with text + caret to open (alternatively button):
https://www.w3schools.com/bootstrap/bootstrap_collapse.asp

**Describe the benefits this feature would bring to BookStack users**
In case of complicated paragraph structure, some paragraphs could be marked as this special collapse element and automatically close - e.g. tip on how to do something - without cluttering the main content.

**Additional context**
https://www.w3schools.com/bootstrap/bootstrap_collapse.asp

**Comment by Guims** [comment]
Hi,
See ==> https://github.com/BookStackApp/BookStack/issues/887

**Comment by ssddanbrown** [comment]
Thanks @nekromoff for your request, This is already requested under #78, Please thumbs-up the original, top comment there to show support.
Since this is effectively a duplicate I will close this.
