### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by baur** [BookStackApp/BookStack#964]
How to configure LDAP Authentication if I'm not domain admin and I have not access to LDAP service
LDAP_DN=*
LDAP_PASS=*

I'm serving another system where LDAP Authentication too, but here we entered just LDAP server address only and everything works well (C# [project](http://doc.rapidscada.net/content/en/software-configuration/user-authentication.html))

**Comment by lostdesign** [comment]
If you are not an domain admin, your user shouldn‘t be able to bind the LDAP unless your LDAP is not secure.
