### ISSUE TITLE
AzureAD the request does not match the reply urls

### ISSUE THREAD

**Issue by onggie** [BookStackApp/BookStack#967]
I have stumbled into a problem when authenticating against AzureAD.  I have checked my .env file and confirmed the following are correct;

- APP_ID
- APP_SECRET
- TENANT
- APP_URL 

When clicking **LOGIN WITH MICROSOFT AZURE** it asks which user I want to authenticate as, once logged in I get the following;

> AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'MY_APP_ID'. 

When I go into AzureAD and check my **Reply URLs** this matches my **APP_URL**

**Comment by onggie** [comment]
Further troubleshooting and I have discovered the solution please read below.

1. Login to Azure and head to Azure Active Directory
2. Click on App registrations
3. View all applications or search your application that you created for BookStack
4. Click Settings
5. Click Reply URLs
6. You will have an entry for URL to your BookStack eg https://bookstack.contoso.com
7. Change this entry to contain a wildcard https://bookstack.contoso.com/*
8. Save

I also noticed I would get an error when logging in, I have two accounts an admin and user Azure account and as I was logged into my admin account, it wouldn't log into BookStack as my profile was linked to my user account.

**Comment by onggie** [comment]
I have reopened this, could the devs please adjust the manuals then close this issue?

Thanks

**Comment by ssddanbrown** [comment]
I believe this was completed in the following commit: https://github.com/BookStackApp/website/commit/a98627d06ef0c2938a087e20d5462345c76be2dd#diff-a54035c86e10b14b97f9258a937439a6
