### ISSUE TITLE
Error on image upload

### ISSUE THREAD

**Issue by lhetke** [BookStackApp/BookStack#975]
**Problem:**
Error on image upload in the image manager. There's an error message in the laravel Debug Console:

The file "" does not exist {"userId":3,"email":"","exception":{}}

The file "" does not exist ../BookStack/vendor/symfony/http-foundation/File/MimeTypeGuesser.php#123

public function guess($path)
 {
        if (!is_file($path)) {
            throw new FileNotFoundException($path);
        }

**Configuration:**
Shared Hosting
CentOS 7.5.1804
Apache 2.4.6
PHP 7.1.20
MariaDB 10.1.33
BookStack v0.23.2

We are using BookStack since three months now. Up until now it worked flawlessly. A few days ago an error appeared whenever I tried to upload an image. I tried different image formats, sizes and Browsers. Updating to the latest BookStack version didn't fix the problem. Any Ideas how I can solve this error? Thanks in advance, Lukas

**Comment by ssddanbrown** [comment]
Hi @lhetke, 
Sorry to hear your having issues, Sounds like a strange one. 

Had you been uploading images before in the last 3 months?
Did error occur before updating or right after updating?
Have you tried a few different image types to see if it's just one image causing strange issues?

**Comment by lhetke** [comment]
Thank you for your response. We have been uploading Images up until a few days ago when the error message appeared. The error occurred before updating and persists after updating. I've tried several different images, different image file formats and sizes with no luck.

**Comment by lhetke** [comment]
I don't know how, but image upload started working again this morning. I didn't update or change anything. Maybe it's something our hosting provider has done. Thanks anyways :)

**Comment by ssddanbrown** [comment]
@lhetke Ah, Okay, Thanks for letting me know and happy to hear things are working! Will therefore close this.

**Comment by z3ugma** [comment]
We are seeing the same issue:

[2019-02-22 22:35:21] production.ERROR: The file "" does not exist {"userId":7,"email":"<user>@<email>","exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"\" does not exist at /u/apps/bookstack/bookstack/BookStack/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php:123)
[stacktrace]

**Configuration:**
AWS EC2
Ubuntu 18.04
NGINX nginx/1.14.0
PHP v7.2.15-1
MariaDB 10.3.12
BookStack v0.25.1

**Comment by z3ugma** [comment]
Might be related to max image upload size per https://github.com/laravel/framework/issues/23492
