### ISSUE TITLE
Lost admin access...

### ISSUE THREAD

**Issue by JeffCache** [BookStackApp/BookStack#977]
Me and the other sysadmins were made admin users on our Bookstacks instance. Today, when logging in, BookStacks prompted me to associate an email address. Weird... I have LDAP enabled... I associated with my work email.

I get back in and Bookstacks seems to have created a separate, new account for me. Except now I'm not an admin. Nor are any of the other sysadmins.

I still have ssh access. But I have no idea where to go to re-enable us to administer the instance through the WebUI. Can someone help?

**Comment by the-cybersapien** [comment]
@JeffCache `bookstack:create-admin` might be of help here.

Have a look on the [Official Documentation](https://www.bookstackapp.com/docs/admin/commands/) :smile:

**Comment by JeffCache** [comment]
@the-cybersapien Ah... that would certainly be useful, thanks!

Do I need to cd to a specific directory to run these commands? I'm getting an error when I run inside the bookstack directory.

**Comment by Vicvinegar0** [comment]
According to the doc (https://www.bookstackapp.com/docs/admin/ldap-auth/) you can change auth back to `standard` from `ldap`, login with the initial local admin account, and fix your ldap uid, if that's the issue.

**Comment by ssddanbrown** [comment]
Thanks @the-cybersapien and @Vicvinegar0 for both providing solid options here.

@JeffCache These should be ran from the top-level folder where your BookStack install is. The folder should contain your `.env` and an `artisan` file. Let me know once you're back in and I'll close this issue.

**Comment by ssddanbrown** [comment]
Since It's been a month I'm gonna assume you managed to get access again so will close this.
If you're still having issues feel free to comment for further assistance.
