### ISSUE TITLE
Code block copy icon hides content

### ISSUE THREAD

**Issue by watschi** [BookStackApp/BookStack#980]
**Describe the bug**
When using horizontal scrolling in code blocks, the copy icon hides the blocks content.

**Steps To Reproduce**
1. Create a single line code block with text long enough to require horizontal scrolling.
2. The copy icon hides the last few letters

**Expected behavior**
Attach the copy icon to the outside of code blocks, or make it only visible when hovering over a code block.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/26351931/44450108-5a44ea00-a5f0-11e8-893c-43c0c19066cf.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.23.2 
 - PHP Version: 7.0.30-0ubuntu0.16.04.1
 - Hosting Method (Nginx/Apache/Docker): Apache/2.4.18

**Comment by ssddanbrown** [comment]
Thanks for reporting @watschi, Marked for next release.
