### ISSUE TITLE
Related content section in sidebar

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#982]
**Describe the feature you'd like**
A "related content" section in the sidebar when viewing a page and the ability to manually indicate/link related content to the current page.

**Describe the benefits this feature would bring to BookStack users**
Can give more context to the current page, and/or can make it easier to locate additional related topics.

**Additional context**
In the future, the related content links can be auto generated?

**Comment by ssddanbrown** [comment]
Thanks @tuaris for this idea.
You could kind of emulate this at the moment using links as attachments. 

If I'm honest I don't think most people would go to the effort of finding and maintaining a list of related pages. Auto-generating will be a technical challenge. Probably not something I see as a priority to implement but a good idea nonetheless so will leave this open to discussion.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since there's been relatively little demand for this feature since the original request.
