### ISSUE TITLE
WYSIWYG Markdown Table Editor

### ISSUE THREAD

**Issue by derek-shnosh** [BookStackApp/BookStack#984]
**Describe the feature you'd like**
WYSIWYG Markdown Table Editor.

**Describe the benefits this feature would bring to BookStack users**
Basic spreadsheets are used heavily during planning/staging phases of our projects. I would love to transition them to bookstack since I'm trying to push it as our doc server; but editing MD tables is a bit unruly. A WYSIWYG markdown editor would be very welcome.

Example: https://nhnent.github.io/tui.editor/api/latest/tutorial-example01-basic.html

![](https://i.imgur.com/TTcjs8B.gif)

**Additional context**
I know the WYSIWYG editor allows this, but we'd prefer all documentation *source code* to be in MD, not HTML.

**Comment by ssddanbrown** [comment]
@derek-shnosh Thanks for pointing me to TUI editor. Seems fairly robust and featureful. Will have to have a deeper look to see if it would be a good fit in BookStack.

Is this request any different to #315? If not I'll close this as a duplicate.

**Comment by derek-shnosh** [comment]
@ssddanbrown After review, the request isn't any different.

I think I was distracted by the link to StackEdit which allows a WYSIWYG **insert table**, but wasn't able to **edit** in WYSIWYG, so I created this request.

So yeah, same as #315, close at will.

**Comment by ssddanbrown** [comment]
@derek-shnosh Cool, thanks for checking!

**Comment by derek-shnosh** [comment]
@ssddanbrown I know it was mentioned in the issue, but I wanted to re-clarify that the end goal (for me) would be that the WYSIWYG markdown editor builds the 'source' in MD. As opposed to HTML which would then gets put in line with the MD formatting of the doc.  Hope that makes sense.
