### ISSUE TITLE
Standardise PDF export size and allow configuration between a4/US-letter

### ISSUE THREAD

**Issue by nvnvnvnvn** [BookStackApp/BookStack#995]
**Describe the bug**
I'm using wkhtmltopdf and the output PDF is not 8.5x11. Any ideas how to change that now, or can it be something in the user-edited styles to be added?  Before we switched to wkhtmltopdf the document size was 8.5x11.

**Steps To Reproduce**
1. Export document with wkhtmltopdf

**Expected behavior**
document size 8.5x11

**Screenshots**
![pdf-size](https://user-images.githubusercontent.com/29762011/44933691-a2ba8100-ad2f-11e8-9154-6a5ea508de39.jpg)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.22.0
 - PHP Version: 7
 - Hosting Method (Nginx/Apache/Docker): Nginx

**Comment by ssddanbrown** [comment]
Hi @nvnvnvnvn,
I realise this is 3+ years late any may not even be relevant for you anymore, but I've wrapped this up into an .env option:

```bash
EXPORT_PAGE_SIZE=a4
# or
EXPORT_PAGE_SIZE=letter
```

Will be part of the next patch release.
