### ISSUE TITLE
Show context when searching

### ISSUE THREAD

**Issue by Vicvinegar0** [BookStackApp/BookStack#997]
Right now the search only returns the pages that contain the string. However when you have a lot of pages it can make it more difficult to find what you're looking for.

I think it's important to have a feature like MediaWiki where it shows the page title, but below also shows the context around the string you searched for.

Otherwise users would have to view a number of pages and then use the browser's search function to actually see the context.

**Comment by ssddanbrown** [comment]
This was a feature before so much of the code may still be there. Can't remember the exact reason for removing, if there was such a reason, May have been a mistake on my part.

**Comment by cooter2** [comment]
I am evaluating this for my use, this is one of the things I noticed as well. I would also like to expand on the feature by requesting that the search term is highlighted in both the response and in the page when it is opened from a search result. Perhaps make the highlighting feature a configurable option?

**Comment by mattpera** [comment]
Hi! Would love to have this feature as well!

**Comment by jameswmcnab** [comment]
@ssddanbrown Would you be interested in a PR  for at this time?

**Comment by ssddanbrown** [comment]
@jameswmcnab Absolutely! Especially if it came with a test to cover it. 

As mentioned above, I seem to remember this being a part of search before so there may be some residual code somewhere unless I got overly hasty with a past clean-up.

**Comment by jameswmcnab** [comment]
@ssddanbrown Okay great, I'll see what I can do when I get some time next week 👍

**Comment by sistemasge** [comment]
I have resolved the problem using the "Browser Searching Feature" (in Google Chrome, type the shortcut [CTRL + [F]) but I think this functionality would be very useful if Booksatck had it.

**Comment by mardukbp** [comment]
[TNTSearch](https://github.com/teamtnt/tntsearch) is a full-text search engine written in PHP that provides this feature.

**Comment by mattpera** [comment]
Hi team!
Any update on this enhancement? Is it something planned for near future?
Great job anyway!
Matt

**Comment by ssddanbrown** [comment]
No solid update on this right now @mattpera.
Was thinking about paying some attention to the search system overall when I have more time to dedicate to the project ([As of next month](https://danb.me/blog/posts/leaving-my-job-to-focus-on-open-source/)).

**Comment by ssddanbrown** [comment]
Highlighting (via boldening) of terms within search results has been added as part of #3043 and will be part of the next release.
Please note, this is somewhat of an estimation of what might have contributed to the match.
Will therefore close this off.
