### ISSUE TITLE
"No color" disappear or not present

### ISSUE THREAD

**Issue by Xarkam** [BookStackApp/BookStack#999]
**Describe the bug**
If you using Google chrome to write page,
the "No color" disappear after set color to a text.

If you use Microsoft Edge, the no color is not present.

**Steps To Reproduce**
_For Google Chrome_
1. click to background color
2. click in document to close colors list
3. click to background color
4. the "no color" is no longer there

**Expected behavior**
Always "no color" present in list of colors.

**Screenshots**
_Google Chrome_
first click:
![image](https://user-images.githubusercontent.com/331816/45121933-c97b1c00-b162-11e8-8087-eecca75e5a9b.png)
reopen list of colors:
![image](https://user-images.githubusercontent.com/331816/45121959-d6980b00-b162-11e8-8d9c-3fe7eb4d107c.png)

_Microsoft Edge_
![image](https://user-images.githubusercontent.com/331816/45122373-e82de280-b163-11e8-9feb-701c4a682c02.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.23.2
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): Apache 2.4

**Additional context**
No additional information.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Xarkam and thanks for the really clear description and screenshots. 
This will be fixed as of the next upcoming release, v0.24.
